### ISSUE TITLE
Add app.config to project if it didn't exist

### ISSUE THREAD

**Issue by twiernik** [fsprojects/Paket#1001]
install --redirects creates app.config file with proper entries but if app.config is not in project already ( like for class library project ) it is not added ( one has to add it manually ). It would be nice if it was :smile_cat:

**Comment by isaacabraham** [comment]
What function would it serve? As I understand it (and I might be wrong here) app.config files in class libraries aren't utilised by NET, only the hosting process e.g. An exe etc.

**Comment by twiernik** [comment]
To be specific app.config is created but not added to csproj. It is usefull if one has tests in a library.

**Comment by isaacabraham** [comment]
@twiernik Ah, I see. So the csproj / fsproj needs to be updated with the file, OK.

**Comment by forki** [comment]
@isaacabraham are you going to implement this?

**Comment by isaacabraham** [comment]
hmmm. could do it next week I guess :-) Is there anything I need to worry about with regards to updating the appropriate project file in terms of paket - or is it just adding a node to the project file for the app.config file?

**Comment by forki** [comment]
we have a parameter which does that
