### ISSUE TITLE
.net framework version

### ISSUE THREAD

**Issue by SavaNDragos** [fsprojects/Paket#1002]
Should this:
WARNING: Could not install package 'Packagename'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
fail instead of passing?
If we get a message like this the update will actually break the build, because it will not have an assambly to use.

**Comment by forki** [comment]
I don't really understand. Can you describe how to reproduce?

**Comment by SavaNDragos** [comment]
Ok so this is happening in nuget on paket the behavior is different.

**Comment by SavaNDragos** [comment]
If I have a project on .net version 4.0 and someone releases a newer version of a package that doesn't support version 4.0 anymore, the paket update should fail. It doesn't happen.

**Comment by forki** [comment]
Now I'm completely lost

**Comment by SavaNDragos** [comment]
In my solution i have a project that is .net framework version 4.0 and we used a package that was having an dll for .net framework v 4.0 but that dll stopped being released instead  assamblies v4.5+ where released. When we run paket update the project is updated correctly but when running it errors appear.

**Comment by SavaNDragos** [comment]
I know this is a result of people not using SemVar correctly but probably it could be nice if paket gives you an error when runnin update if it can't find a dll that will support the version of your project/s.

**Comment by SavaNDragos** [comment]
The problem is that will mean we need to verify the dlls to see if a specific version is awailable. Not sure if stuff like this should be included in paket.

**Comment by forki** [comment]
But this is basically like a breaking change in the dll itself. Your first
build will show that error. Paket doesn't make assumptions about what
target framework you use. Some people have different builds that target
different frameworks

**Comment by SavaNDragos** [comment]
Yeah i know, this is caused mostly due to beaking changes.
I will close the issue.
