### ISSUE TITLE
Unexpected install.xdt generated after conversion from nuget

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1006]
I have packages.config which includes

  <package id="Costura.Fody" version="1.3.3.0" targetFramework="net45" developmentDependency="true" />
  <package id="Fody" version="1.28.3" targetFramework="net45" developmentDependency="true" />

And the project has package specific content file FodyWeavers.xml with some custom content.

After Paket runs convert-from-nuget command something unexpected happens: FodyWeavers.xml is reset to its empty state (as after the package fresh install) and the real content is moved to FodyWeavers.xml.install.xdt 

It feels like Paket is trying to tell me something, but because install.xdt / uninstall.xdt are not documented I could not find how to get back to the workable state other than by pulling my content from install.xdt back to FodyWeavers.xml. It is not a big deal but it looks like Paket is doing some (unfinished?) counter-productive thing during convert-from-nuget. 

Could anybody shed some light on it?

Thank you!
Konstantin

**Comment by konste** [comment]
Appeared it happens again and again on each Paket install for each project in solution which uses Fody package! It gets annoying very fast. Any way to stop Paket from doing it?

**Comment by isaacabraham** [comment]
Yes, put content: none on the Fody line in the dependencies file. I've noticed this too though - it's also present on the Microsoft Service Bus nuget package.

**Comment by konste** [comment]
@isaacabraham your advice worked like a charm! Thanks a lot!
