### ISSUE TITLE
Microsoft.Bcl.Async is not working in a .NET40 Project

### ISSUE THREAD

**Issue by biohazard999** [fsprojects/Paket#1007]
Hi guys,

If you try to install the Microsoft.Bcl.Async package in a .NET40 project you can't use it.
After manually installing the Microsoft.Bcl.Build package via NuGet it works,
but after a paket install, the packages.config gets deleted.

So, I read #618 and I think is okay to blacklist. But why deletes paket the NuGet packages.config?
Should paket delete the packages.config only when convert-from-NuGet is used?!
 
Thanks Manuel

**Comment by forki** [comment]
packages.config gets deleted during install? That's strange. Do you have a repro for me?

**Comment by biohazard999** [comment]
Sure: https://github.com/biohazard999/PaketRepro

Version: 1.33.0.0

just run paket install

**Comment by forki** [comment]
try to put the following into your paket.dependencies file:

    nuget Microsoft.Bcl.Build 1.0.21 version_in_path: true

It seems to do what you want (that means it doesn't delete the packages.config).



But regarding the original error `Microsoft.Bcl.Async package in a .NET40 project you can't use it` - what does this mean?

**Comment by biohazard999** [comment]
Thats what i tried 

But I missed, paket needs the version part so it does not delete the packages.config. 

     nuget Microsoft.Bcl.Build version_in_path: true //wrong
     nuget Microsoft.Bcl.Build 1.0.21 version_in_path: true //correct

So the workarround is:

    paket.dependencies:

    nuget Microsoft.Bcl.Async
    nuget Microsoft.Bcl.Build 1.0.21 version_in_path: true

    paket.references
    Microsoft.Bcl.Async

    paket install

    Nuget-Console:
    update-package Microsoft.Bcl.Build -reinstall //Includes Microsoft.Bcl.Build.targets into Projects

Works for me.
----
If you like to reproduce the error:

Create a new ConsoleApp targeting .Net40

Add

      public async Task DoAsync()
        {
            var r = await TaskEx.FromResult(1);
        }


add to dependencies

    nuget microsoft.bcl.async
    nuget Microsoft.Bcl.Build 1.0.21 version_in_path: true

add to references

    Microsoft.Bcl.Async

run `paket install`

try to build:

    error CS0103: The name 'TaskEx' does not exist in the current context

After reinstalling the thing is working

    update-package Microsoft.Bcl.Build -reinstall //Includes Microsoft.Bcl.Build.targets into Projects

**Comment by biohazard999** [comment]
But there is a new problem: If you try to mix Nuget an paket for some workarrounds (packages that arn't supported yet via paket) the packages.config get overwritten on an install. I will create a new issue. this comment is just a reminder for me.

**Comment by forki** [comment]
Yes the question is what packages are not supported and why?

**Comment by biohazard999** [comment]
Microsoft.Bcl.Async does not work, but i didn't figure out why except the fact that Microsoft.Bcl target files are not referenced. I have no idea why this differes so much. 

forki, just try my steps in vs 2015 community, i have no idea why this does not work without the workarround. some strange stuff with the studio? 

i will try to make some more investigations on this. hope this helps for the people are stuck with that.


@forki awesome tool :+1: got our package upgrade from 3 ours to under 15 secs :)

**Comment by forki** [comment]
wow just found https://github.com/fsprojects/Paket/issues/618

**Comment by forki** [comment]
I tried to reproduce in the described repro above. But everything seems to work fine. even when I remove the packages.config it all compiles (see https://github.com/biohazard999/PaketRepro).

**Comment by forki** [comment]
> error CS0103: The name 'TaskEx' does not exist in the current context

TaskEx comes from Microsoft.Threading.Tasks - so why is the targets file needed at all?

**Comment by WebDucer** [comment]
I think it is needed because of backport of `async/await` with the BCL library to compile against the package version and not the default `Microsoft.Threading.Tasks` library from GAC.

**Comment by WebDucer** [comment]
I'm migrating from nuget to paket.

After `.paket\paket.exe convert-from-nuget` all bcl-imports are gone. `.paket/paket.exe install --hard` doesn't restore the imports. In `paket.dependecies` `import_targets: true` is set.

**Comment by forki** [comment]
yes they are blacklisted as #618 - but I assume we can remove that blacklisting and just use the version-in-path feature

**Comment by forki** [comment]
at least we should find a way to overwrite the blacklist

**Comment by WebDucer** [comment]
I think it should be possible to replace blacklist with groups:

```
[paket.dependencies]

source https://www.nuget.org/api/v2/

# default: import are allowed
nuget Newtonsoft.Json
nuget System.Data.SQLite content: none

group MyTargetsBlackList
    source https://www.nuget.org/api/v2/
    import_targets: false

    nuget Microsoft.Bcl.Build
```

or use the `import_targets` flag per item, like `copy_local` or `framework`.

**Comment by forki** [comment]
the issue is import_targets defaults to true. but I have an idea. give me a sec

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/1063 removes the file from the blacklist
instead we just change the import_targets default for that single package. 
This should reduce negative impact for other users and still allow you to install the targets file

**Comment by WebDucer** [comment]
How should I use them now to enable import_target for the bcl package?

**Comment by forki** [comment]
source https://www.nuget.org/api/v2/

nuget Newtonsoft.Json
nuget System.Data.SQLite content: none
nuget Microsoft.Bcl.Build import_targets: true; version_in_path: true

**Comment by WebDucer** [comment]
OK.

I'll try tomorrow on our big solution.

**Comment by WebDucer** [comment]
It's working on a smaller solution. On our big solution we have still the same error message. But I think now the problem is not in paket.

Great support and great tool!!!
