### ISSUE TITLE
Paket Install pulls in unneeded dependencies which cause assembly version mismatch

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1008]
I have rather big paket.dependencies file (result of conversion from NuGet). As I explicitly don't care about any .NET Framework other than 4.5 I have added "framework: >= net45" on top of it to reduce the noise.

paket.dependencies and paket.lock are both shared here: http://1drv.ms/1Psm7XJ

To my surprize when paket.lock is generated it still mentions versions of .NET other than 4.5, for instance:
    Microsoft.Azure.Common.Dependencies (1.0.0) - framework: >= net45
      Microsoft.Bcl (>= 1.1.9) - framework: portable-net45+wp80+wpa81+win, >= net40, >= net45

This causes warnings like: "Found conflicts between different versions of the same dependent assembly." and assembly in question is System.Runtime. The problem is that Microsoft.Bcl package (see above) carries System.Runtime version 2.6.9.0 in its net40 folder and nothing in its 4.5 folder. 
So project picks up System.Runtime 4.0.0.0 from .NET 4.5 AND System.Runtime 2.6.9.0 from Microsoft.Bcl\net40

Why Paket pulls in all .NET flavors of Microsoft.Bcl package even though it is globally limited to >= net45? Is there anything else wrong here? How to resolve it?

Thank you!
Konstantin

**Comment by konste** [comment]
By the way I have tried to replace "framework: >= net45" with "framework: net45" at the top of dependencies file, but it did not seem to change anything.

**Comment by forki** [comment]
sounds like a bug to me. will investigate tomorrow.

**Comment by forki** [comment]
I can't reproduce the error. The lockfile looks OK to me. Can you please mail me the csproj and paket.references or even the whole project? sforkmann @ gmail

thx.

Also please try to run `paket install --hard` does this help?

**Comment by konste** [comment]
I started conversion process from scratch and now there is no repro for me as well. Closing the issue.
