### ISSUE TITLE
Handle NuGet Build `.props` `.targets`

### ISSUE THREAD

**Issue by bartelink** [fsprojects/Paket#101]
Unless I'm mistaken, Paket does not yet hook in [`.props` and `.targets` files as NuGet has done since 2.5](http://docs.nuget.org/docs/release-notes/nuget-2.5); I believe it should.

The primary reason is that more often than not, it presents an appropriate way for packages to manage [adjustments to the buld process such as this](https://github.com/fsprojects/Paket/issues/65#issuecomment-55561378)

Key differences between such `.props` (imported at top of `.*proj`)  / `.targets` (imported at bottom of `.*proj`) and the `.ps1` are:

- no reliance on VS
- can deal with `TargetPlatform` etc. without silent problems and/or need to reinstall packages
- doesnt induce diffs when swithcing build output type

Note that `.props` is wired into VS with an editor for editing MSBuild Properties entries.

**Comment by forki** [comment]
conversation is happening at #516
