### ISSUE TITLE
Documentation :: Add Clarification about /install.sh

### ISSUE THREAD

**Issue by Adron** [fsprojects/Paket#1011]
Maybe I just missed it, but I couldn't find any information about using install.sh to get paket at the command line in Linux/OS-X. So this issue is to propose that we (I'm more than happy to do it myself) add a simple paragraph or two about the install.sh, what it does, and what it gives one when installing paket via git clone && build.sh && install.sh.

Maybe beyond this, I could also add something in regard to installation methods and preferred installation methods to the docs? I would have found this helpful, so figured I'd offer to contrib a PR for it.

**Comment by forki** [comment]
Yes that sounds great.

**Comment by Adron** [comment]
Cool. I'll get something written up and PR it... however I'm not sure entirely which docs I should edit. Is it just the *.md files and then someone will run the build for the gh-pages branch or should I edit the gh-pages branch itself for the PR?

**Comment by forki** [comment]
"If you want to contribute to the docs then please the modify markdown files in /docs/content and send a pull request. Note, that short description and syntax for each command is generated automatically from the Paket.Commands module."

see https://github.com/fsprojects/Paket#quick-contributing-guide

**Comment by Adron** [comment]
Thanks @forki. I'll take a look at that.  :+1:

**Comment by Adron** [comment]
Also @forki that was the nicest way I've ever been told the RTFM.  LOL  ;)  :+1:

**Comment by forki** [comment]
Sorry ;-)
