### ISSUE TITLE
Install modifies local nuget packages

### ISSUE THREAD

**Issue by rjnilsson** [fsprojects/Paket#1013]
Given something like this in `paket.dependencies`

    source imports/nuget
    nuget MyPackage

When running `paket install` the MyPackage.nupkg file under imports/nuget is modified, as reported by my SCM tool. Calculating the MD5 checksum also gives different results before and after.

Using Paket 1.33.0 under Win 8.1/.NET 4.5.2.

**Comment by forki** [comment]
yes it's fixing date convetions in the zip order to make unzip work in mono. we need to work around mono bugs here.

**Comment by rjnilsson** [comment]
Ok. Might be a stupid question, but is it really necessary to modify the source package instead of the copy under packages/?

**Comment by forki** [comment]
Mhm I think I agree, but the issue is we need to extract the meta data. So
we could (maybe should) copy the file to a temp folder and modify it over
there.

At the moment I'm really busy with other stuff, but I think this would make
a great up-for-grabs issue.

**Comment by rjnilsson** [comment]
What about detecting the platform at runtime and only fixup when running under mono, just as a workaround for the time being?

**Comment by forki** [comment]
Yes that would make even easier fix for you ;-)

**Comment by rjnilsson** [comment]
I'll check it out. If only it'd been C# instead... ;)

**Comment by forki** [comment]
If it would be C# it wouldn't be in the state that it is today. Believe me

**Comment by rjnilsson** [comment]
I wasn't complaining about the language itself. Good or bad code can be
written in any language.

I was simply referring to my zero experience with F#, or rather, my decent
experience with C#.

Anyway, I'll take a look.
Den 25 aug 2015 15:52 skrev "Steffen Forkmann" <notifications@github.com>:

**Comment by forki** [comment]
The code in question is at https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NuGetV2.fs#L324

you could port the isMono  function from https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/EnvironmentHelper.fs#L124 into Paket's Util.fs 

I think that's pretty straight forward. If you have question, then just ask.

**Comment by rjnilsson** [comment]
I'll give it a shot. Thanks for the pointers.

**Comment by rjnilsson** [comment]
Trying to build the project now, but when using build.cmd (default target) from the command-line I get the following error:

    Running build failed.
    Error:
    Fake.UnitTestCommon+FailedTestsException: NUnit test failed. Process finished with exit code FatalError (-2146232576).
    at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
    at FSI_0001.Build.clo@156-10.Invoke(Unit _arg6)
    at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 481

Windows also shows a dialog with the message "An app on your PC requires the following Windows feature ... .NET Framework 3.5 (includes .NET 2.0 and 3.0)".

Do I actually need to install .NET 3.5, or can I manage without (preferably)? I'm running VS2012 Pro and have .NET 4.5.2 installed.

**Comment by forki** [comment]
yes somehow MS managed to make 4.5.2 without including 3.5

**Comment by rjnilsson** [comment]
If I'm being unclear: Is there a way to build Paket with only .NET 4 or better installed? Where are the dependencies on .NET 3.5?

**Comment by forki** [comment]
TBH I have no idea. These framework versions and NUnits dependency on it are a mystery to me. 
Anyways, it seems everything is building and "only" the NUnit testrunner is not running for you.
When you create a WIP pull request you can see if everything still works on our CI servers.

**Comment by rjnilsson** [comment]
Would it be ok to replace NUnit.Runners with NUnit.Runners.Net4 to allow running tests when only .NET4 or later is available, or do you need to build Paket under previous .NET versions?

I've got ".\build RunTests" running happily with that change made locally, so I could push it and make a pull request.

**Comment by forki** [comment]
I think that change would be accepted ;-)

**Comment by rjnilsson** [comment]
So I've implemented a simple workaround that avoids the problem for .NET only. What would be a more general solution waiting for the Mono bug to get fixed?

**Comment by forki** [comment]
I guess we could copy the file to the temp-folder and modify there.

**Comment by jmchapman** [comment]
I just tried to build paket with a freshly installed mono mdk preview for os x el capitan and it failed with:

Running build failed.
Error:
Fake.UnitTestCommon+FailedTestsException: NUnit test failed (4).
  at Fake.NUnitSequential.NUnit (Microsoft.FSharp.Core.FSharpFunc`2 setParams, IEnumerable`1 assemblies) <0x88a6c00 + 0x00337> in <filename unknown>:0 
  at FSI_0001.Build+clo@158-10.Invoke (Microsoft.FSharp.Core.Unit _arg6) <0x88a6b98 + 0x00057> in <filename unknown>:0 
  at Fake.TargetHelper+targetFromTemplate@195[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x889b6b8 + 0x00020> in <filename unknown>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) <0x8892eb0 + 0x000bd> in <filename unknown>:0 

Is there a workaround? I guess I cannot install an older version of mono as it puts things in /usr/bin which is not allowed as of el capitan?

**Comment by forki** [comment]
Which tests failed?

**Comment by jmchapman** [comment]
Tests run: 684, Errors: 0, Failures: 4, Inconclusive: 0, Time: 0.0760673 seconds
  Not run: 1, Invalid: 0, Ignored: 0, Skipped: 1

Errors and Failures:
1) Test Failure : Paket.BindingRedirects.correctly creates a binding redirect
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="123456" culture="en-gb" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="123456" culture="en-gb" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
  Expected string length 241 but was 238. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n  <assemblyIdentity name="..."
  But was:  "...schemas-microsoft-com:asm.v1">\n  <assemblyIdentity name="A..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.correctly creates a binding redirect () <0x3c15a48 + 0x00143> in <filename unknown>:0

2) Test Failure : Paket.BindingRedirects.correctly creates a binding redirect with default culture
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
  Expected string length 247 but was 244. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n  <assemblyIdentity name="..."
  But was:  "...schemas-microsoft-com:asm.v1">\n  <assemblyIdentity name="A..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.correctly creates a binding redirect with default culture () <0x3c20158 + 0x0009f> in <filename unknown>:0

3) Test Failure : Paket.BindingRedirects.correctly updates an existing binding redirect
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="2.0.0" />
</dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="2.0.0" />
</dependentAssembly>"
  Expected string length 247 but was 244. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n  <assemblyIdentity name="..."
  But was:  "...schemas-microsoft-com:asm.v1">\n  <assemblyIdentity name="A..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.correctly updates an existing binding redirect () <0x3c20200 + 0x0011f> in <filename unknown>:0

4) Test Failure : Paket.BindingRedirects.redirects got properly indented for readability
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
    <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
  </dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
    <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
  </dependentAssembly>"
  Expected string length 253 but was 250. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n    <assemblyIdentity name..."
  But was:  "...schemas-microsoft-com:asm.v1">\n    <assemblyIdentity name=..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.redirects got properly indented for readability () <0x3c22ad8 + 0x0008b> in <filename unknown>:0


Tests Not Run:
1) Skipped : Paket.UtilsSpecs.mono runtime not reported on net platform
   Only supported on Net

**Comment by jmchapman** [comment]
Tests run: 684, Errors: 0, Failures: 4, Inconclusive: 0, Time: 0.0760673 seconds
  Not run: 1, Invalid: 0, Ignored: 0, Skipped: 1

Errors and Failures:
1) Test Failure : Paket.BindingRedirects.correctly creates a binding redirect
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="123456" culture="en-gb" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="123456" culture="en-gb" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
  Expected string length 241 but was 238. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n  <assemblyIdentity name="..."
  But was:  "...schemas-microsoft-com:asm.v1">\n  <assemblyIdentity name="A..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.correctly creates a binding redirect () <0x3c15a48 + 0x00143> in <filename unknown>:0

2) Test Failure : Paket.BindingRedirects.correctly creates a binding redirect with default culture
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
</dependentAssembly>"
  Expected string length 247 but was 244. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n  <assemblyIdentity name="..."
  But was:  "...schemas-microsoft-com:asm.v1">\n  <assemblyIdentity name="A..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.correctly creates a binding redirect with default culture () <0x3c20158 + 0x0009f> in <filename unknown>:0

3) Test Failure : Paket.BindingRedirects.correctly updates an existing binding redirect
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="2.0.0" />
</dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="2.0.0" />
</dependentAssembly>"
  Expected string length 247 but was 244. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n  <assemblyIdentity name="..."
  But was:  "...schemas-microsoft-com:asm.v1">\n  <assemblyIdentity name="A..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.correctly updates an existing binding redirect () <0x3c20200 + 0x0011f> in <filename unknown>:0

4) Test Failure : Paket.BindingRedirects.redirects got properly indented for readability
     Expected: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
    <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
  </dependentAssembly>"
Actual: "<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
    <assemblyIdentity name="Assembly" publicKeyToken="PUBLIC_KEY" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.0.0" />
  </dependentAssembly>"
  Expected string length 253 but was 250. Strings differ at index 60.
  Expected: "...schemas-microsoft-com:asm.v1">\r\n    <assemblyIdentity name..."
  But was:  "...schemas-microsoft-com:asm.v1">\n    <assemblyIdentity name=..."
  ---------------------------------------------^

at FsUnit.Extensions.shouldEqual[a] (FsUnit.a x, FsUnit.a y) <0x378c178 + 0x000ef> in <filename unknown>:0
at Paket.BindingRedirects.redirects got properly indented for readability () <0x3c22ad8 + 0x0008b> in <filename unknown>:0


Tests Not Run:
1) Skipped : Paket.UtilsSpecs.mono runtime not reported on net platform
   Only supported on Net

**Comment by jmchapman** [comment]
Here's the relevant bit from the build log about the 4 tests that failed:
[log.txt](https://github.com/fsprojects/Paket/files/36606/log.txt)

**Comment by isaacabraham** [comment]
Looks like on mono newlines are just \r instead of \r\n - I wonder if Environment.NewLine would fix this?

**Comment by forki** [comment]
But why didn't we see that in Travis builds?

**Comment by isaacabraham** [comment]
Then is this something that is Mac only? Or breaking change in latest mono? Can't be surely.

**Comment by rjnilsson** [comment]
Is this really relevant to #1013? Perhaps raise another issue?

**Comment by forki** [comment]
nope it's not

**Comment by forki** [comment]
I think I fixed these tests. there were also red on travis
