### ISSUE TITLE
paket simplify causes build break

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1015]
From the docs I was under impression that "simplify" is rather safe operation and should not cause breakage, but it does not seem to be the case. 

I have attached my dependencies and lock files here: http://1drv.ms/1EWpl00 

There were multiple issues after simplification, but here is the one I can clearly see:

Original dependencies file included packages with Google APIs:
nuget Google.Apis **1.9.1** framework: >= net45
nuget Google.Apis.Admin.Directory.directory_v1 1.9.0.500 framework: >= net45
nuget Google.Apis.Auth 1.9.1 framework: >= net45
nuget Google.Apis.Calendar.v3 1.9.0.1030 framework: >= net45
nuget Google.Apis.Core 1.9.1 framework: >= net45
nuget Google.Apis.Drive.v2 1.8.1.1260 framework: >= net45

Corresponding lock file had corresponding entries:
Google.Apis (**1.9.1**) - framework: >= net45
      Google.Apis.Core (>= 1.9.1)
      Zlib.Portable (>= 1.10.0)
    Google.Apis.Admin.Directory.directory_v1 (1.9.0.500) - framework: >= net45
      Google.Apis (>= 1.9.0)
      Google.Apis.Auth (>= 1.9.0)
...

After simplification three out of six Google APIs packages were removed:
nuget Google.Apis.Admin.Directory.directory_v1 1.9.0.500 framework: >= net45
nuget Google.Apis.Calendar.v3 1.9.0.1030 framework: >= net45
nuget Google.Apis.Drive.v2 1.8.1.1260 framework: >= net45
(for remaining 3 packages versions stayed the same)

But simplified lock file (after being recreated by paket install) shows this:
    Google.Apis (**1.9.3**) - framework: net45
      Google.Apis.Core (>= 1.9.3)
      Zlib.Portable.Signed (>= 1.11.0)
      log4net (>= 2.0.3) - framework: >= net40

So the Google.Apis package used is now 1.9.3 instead of 1.9.1 and it appears to be not backward compatible.

So it seems that simplification may affect versions of (indirect) packages you end up using. If this behavior is by design, then it is worth mentioning in documentation, otherwise it is rather unexpected.

**Comment by forki** [comment]
that's an interesting case. I guess it's more a heuristik. Maybe we could improve it with checking that lockfile stays same.

**Comment by forki** [comment]
I talked with @theimowski about this. 
Our current simplify algorithm doesn't take care of this case. So it's "by design" at the moment.
In some future version we could do an iterative approach where we try to simplify a dependency and see if the lockfile stays the sam until no dependency can be relaxed any more.

But the current algorithm is not that "safe". So yes we should make that clearer. I'd love to see a PR to the docs.
