### ISSUE TITLE
Bindung redirects should also catch later versions

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1019]
Consider the following scenario. You want to use FSharp.Core 4.3.1.0 but some idiot ships 4.4.0.1 with a tool called FAKE. We assume that binding redirects feature will solve that for us. 

paket generates "for 0.0.0.0 - 4.3.1.0 ==> use 4.3.1.0"

This does work against older versions but doesn't catch the new one shipped with FAKE. 

Instead paket should generate "for 0.0.0.0 - 999.999.999.999 ==> use 4.3.1.0"

**Comment by isaacabraham** [comment]
This is a perfect opportunity for someone to get up-to-speed with the Paket project. The change should be trivial - just replacing a sprintf in ```BindingRedirects.fs``` with a hard coded string - at least, this is what it appears to be :-)

**Comment by reidev275** [comment]
woohoo, that's even on my level :)  submitting the pull request
