### ISSUE TITLE
Bootstrapper cannot find stable version now that prereleases are filling the releases page

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#1021]
The github version downloader is manually parsing html for the release nodes looking for the latest stable.  Due to v2 development there are no stable versions listed on the release page, so the crawling mechanism ends up finding invalid html as the version string.

We should either add pagination or a proper github api call to this to prevent this from failing.
I know we've had api issues in the past with rate limiting, maybe we should add a github api strategy that only fires if the user has some config set up?

**Comment by forki** [comment]
thanks for reporting. for now I disable all but the first prerelease

**Comment by baronfel** [comment]
I see them as disabled now, but they still take up space on the releases page.  The quickest fix might be a new patch version of the 1.3x line?

**Comment by forki** [comment]
no the stuff seems to be ordered by version. I deleted the tags. Now it seems to work.

(will add that to my release script)

**Comment by baronfel** [comment]
Thanks for the quick fix! Would you like a PR trying to implement pagination?

**Comment by forki** [comment]
yes of course!

2015-08-28 17:23 GMT+02:00 Chester Husk III <notifications@github.com>:

**Comment by baronfel** [comment]
other thought: https://github.com/fsprojects/Paket/releases/latest redirects to https://github.com/fsprojects/Paket/releases/tag/1.34.0, which is the latest stable.  maybe we could make use of that instead of crawling the versions?

**Comment by forki** [comment]
yes that would be OK as a fallback

**Comment by forki** [comment]
there is also https://github.com/fsprojects/Paket/releases/latest
