### ISSUE TITLE
paket install and paket update is deleting packages.config files.

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#1033]
When there is a `paket.references` paket is deleting the `packages.config` file (even when they contain different packages). I'd like to use `packages.config` for some NuGet packages which setup the solution with powershell scripts, which is not possible with paket. Those changes made by powershell will work on linux (but they must be executed on windows).

Is this by design or a bug?

**Comment by forki** [comment]
This is a known issue with an easy workaround. 
You can still manage these packages in paket and just set version_in_path to true. Paket will automatically create the packages.config and add these packages. See http://fsprojects.github.io/Paket/nuget-dependencies.html#Putting-the-version-no-into-the-path 

The downside of this is that we take full control over the packages.config and since you didn't instruct paket to put stuff in, it assumes you don't want anything in it.

**Comment by matthid** [comment]
But with this powershell installation scripts are never executed, correct? Is there a workround where I can disable this feature and manage `packages.config` via visual studio?

Thanks for the fast answer.

**Comment by matthid** [comment]
I will test this version_in_path but I think this is really confusing (1. that the files are deleted and 2. that version_in_path has something to do with `packages.config`)

**Comment by forki** [comment]
This is a workaround to make xunit.runner work in visual Studio. It's super
annoying that we have to do such a stupid thing. We could change this
"feature" to "add only". This would not touch your packages.config, but
then we can't really delete stuff from packages.config if we delete a
package from dependencies file.
One way out of this would be to tag our packages in the packages.config
with a paket flag - do you know how such a flag could look like?

**Comment by matthid** [comment]
Ok I re-read the related issues #516, #928 .

I would suggest doing the following:
 - If no  `version_in_path` is used in `paket.dependencies` or `paket.lock` paket should ignore `packages.config` everywhere
 - Detect the deletion of a `version_in_path` from the previous lockfile.
 - Otherwise use the current behavior or throw if additional packages are used in `packages.config` (so when `version_in_path` is used paket "owns" all `packages.config` files)

In fact your solution would also work:
 - add a `isPaket` attribute to the root xml node. Ignore the file if it is not there.
 - Throw when we have a `version_in_path` package but the `isPaket` attribute is not set in `packages.config` and the file exists (this indicates that somebody used Visual Studio to add packages, we cannot realistically support this)

Problems/Notes:
 - When "reinstall all" is used within visual studio, the `isPaket` attribute (or anything really) will be removed. That's why I think it might be better to save this information somewhere else (use the previous `paket.lock` file or a new file)
 - I use a different folder for nuget package restore, this means packages managed by paket will be downloaded twice into different folders. This leads to problems when you use `version_in_path` and Visual Studio NuGet at the same time (that's why we should prevent this combination).

Even considering the problems it would be a improvement as this would allow us to use paket and nuget in the same solution. (In this scenario I'd like to use paket for build dependencies and nuget for the solution itself). Please tell me what you think and I can maybe try to hack something together ;)

So in essence: I don't see an unproblematic way to support `version_in_path` side by side with using NuGet in Visual Studio.

**Comment by matthid** [comment]
To give some more details to my use-case:
We have some packages using the powershell install features, that's why I wanted to use paket for build dependencies and NuGet within the solution. Aside from this I want to simplify the transition for my co-workers. But currently this seems to be impossible/annoying because paket is deleting all the `packages.config` files. I think this use-case worked fine in the past. 

Once at this point it is easy to convert project by project to paket if needed.

Please tell me if I'm doing things the wrong way :)

**Comment by forki** [comment]
partly solved in 73ee7c8
