### ISSUE TITLE
[V2] Unify syntax of command line parameters

### ISSUE THREAD

**Issue by inosik** [fsprojects/Paket#1035]
Maybe it's just me, but sometimes I find it a little bit confusing that some parameters need to be prefixed with an `-` or `--` and some don't. Take this output for example:
```
ilja@mbp:~/Projects/demo$ paket add --help
Paket version 1.36.1.0
Paket add

Adds a new package to your paket.dependencies file.

paket add nuget <string> [version <string>] [project <string>] [--force|-f] [--interactive|-i] [--hard] [--redirects] [--no-install]

	nuget <string>: NuGet package id.
	version <string>: Allows to specify version of the package.
	project <string>: Allows to add the package to a single project only.
	--force [-f]: Forces the download and reinstallation of all packages.
	--interactive [-i]: Asks the user for every project if he or she wants to add the package to the projects's paket.references file.
	--hard: Replaces package references within project files even if they are not yet adhering to the Paket's conventions (and hence considered manually managed).
	--redirects: Creates binding redirects for the NuGet packages.
	--no-install: Skips paket install --hard process afterward generation of dependencies / references files.
	--help [-h|/h|/help|/?]: display this list of options.
```
Maybe we could unify them before we go v2? Unfortunately, this would require to update all other tools which rely on `paket.exe`, like the FAKE helper or the Atom plugin. What do you say?

**Comment by forki** [comment]
I think they are standard according to Argu https://github.com/nessos/Argu  /cc @eiriktsarpalis

**Comment by inosik** [comment]
What I meant was: Lets make them all require `-` or `--`. Like this:
```
paket push --url <string> --file <string> [--apikey <string>] [--endpoint <string>]

```

**Comment by inosik** [comment]
So, do you think it's worth it? If not, I'm perfectly fine with that.

**Comment by forki** [comment]
@eiriktsarpalis what do you say?

**Comment by forki** [comment]
I don't think I want to break the parameters at this point.

**Comment by eiriktsarpalis** [comment]
@forki Sorry I just saw your question. The double dash is standard, the single dash is more or less user specified through the AltCommandLine attribute.

**Comment by eiriktsarpalis** [comment]
I think it's pretty common to use double dash for verbose parameter names and single dashes for abbreviations.

**Comment by inosik** [comment]
As I wrote, I thought we could make this before v2 stable release, maybe before we go v3 :wink:
