### ISSUE TITLE
Can't build from Visual Studio 2012

### ISSUE THREAD

**Issue by rjnilsson** [fsprojects/Paket#1037]
Building the solution from within Visual Studio 2012 gives the following output:

    1>------ Build started: Project: Paket.Core, Configuration: Debug Any CPU ------
    2>------ Build started: Project: Paket.Bootstrapper, Configuration: Debug Any CPU ------
    1>	"C:\Users\jni\prj\github\Paket\.paket\paket.exe" restore --references-files "C:\Users\jni\prj\github\Paket\src\Paket.Core\paket.references"
    2>  Paket.Bootstrapper -> C:\Users\jni\prj\github\Paket\bin\paket.bootstrapper.exe
    1>	Paket version 2.0.0.0
    1>	1 second - ready.
    1>C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets(155,9): error MSB4127: The "Fsc" task could not be instantiated from the assembly "C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\FSharp.Build.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Microsoft.FSharp.Build.Fsc' to type 'Microsoft.Build.Framework.ITask'.
    1>C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets(155,9): error MSB4060: The "Fsc" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
    1>Done building project "Paket.Core.fsproj" -- FAILED.
    1>
    1>Build FAILED.
    StopOnFirstBuildError: Build cancelled because project "Paket.Core" failed to build.
    Build has been canceled.

Running e.g. `.\build.cmd RunTests` from the command line works fine.

**Comment by forki** [comment]
sorry, but we don't support VS2012 for paket's own project.
