### ISSUE TITLE
Prereleases of transitive dependencies

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#1038]
When defining a nuget dependency like `nuget X prerelease` is there a possibility to also get _prereleases_ of transitive dependencies?

**Comment by forki** [comment]
I guess this should be made the default. Do you have an example for me to
test?

**Comment by devboy** [comment]
We got ourselves into a mess at work :P
We are in control of the transitive dependencies in this case, where this would make sense.
But when your not in control of the transitive dependencies this might be problematic.

**Comment by forki** [comment]
Did you try to add the transitive packages to the dependencies file and also activate prerelease for these? Not sure if this works, but we could try to make that work

**Comment by devboy** [comment]
That works!

**Comment by devboy** [comment]
But that causes quite some overhead for us. As when we want to switch from prerelease to actual release we need to change our continous integration dependencies file and we cannot ensure that our clients get the correct versions when they want a prerelease of something.

**Comment by devboy** [comment]
I still need to wrap my head around and check some variations in the nuspec files:

* `<dependency id="Y" version="0.6.0" />`
* `<dependency id="Y" version="0.6.0-prerelease" />`
* `<dependency id="Y" version="[0.6.0-prerelease]" />`
* `<dependency id="Y" version="[0.6.0-prerelease,0.7.0]" />`
* ...

maybe something like that would work for us. We just want to avoid having pinned dependencies in the nuspec so our clients would also get updated versions of base packages...

**Comment by forki** [comment]
So you propose a "transitive prerelease" operator?

**Comment by devboy** [comment]
If my test with the nuspec versions turns out successful, a PR for `paket pack` is more likely.
If not, the operator might be an option.
Doubt I will be able to follow up on this today though...

**Comment by devboy** [comment]
It looks like we can actually solve this by having our prereleases depend on other prereleases by using this version constraint: `>= x.x.x-prerelease`

**Comment by devboy** [comment]
In my `paket.dependencies` file having a nuget dependency:
`nuget Wooga.Lambda >= 0.0.0-prerelease` is not the same as `nuget Wooga.Lambda prerelease`
Is that intended?

**Comment by forki** [comment]
is this still open?
