### ISSUE TITLE
Documentation seems fuzzy on references

### ISSUE THREAD

**Issue by gdennie** [fsprojects/Paket#1046]
I was not able to easily discern the semantic differences between the dependencies, lock, and reference files. Your documentation does not speak to the model of version documenting. Clearly, a lot of work went into the documentation but it seems some concept scaffolding is needed.

**Comment by forki** [comment]
thx for the feedback. do you see a way to improve the docs? I'm always happy to get help with that. we have so many docs pages and it's hard to get real strcuture into it.

**Comment by gdennie** [comment]
I welcome the opportunity to help. Of course, I don't know Paket.

I would recommend the following:
1)  maintaining a comprehensive glossary
2)  make expansiveness implicit such that dependency implies transitive dependencies as well (had to look that word to see if it meant some other kind of dependency)
3)  focus on describing the implicit NoSql database that holds all that project information

One of the key benefits of this project is exposing a functional description of the API's of Nuget and GitHub repositories.

I've include a sample preliminary glossary extracted from documentation in creating this response (I dove back in a little):

paket.dependencies: The file is used to specify rules regarding your application's dependencies.
paket.lock: The file records the concrete dependency resolution of all direct and indirect dependencies of your project.
paket.references: The file used to specify which dependencies are to be added to installed into the MSBuild projects in your repository.
paket.template: These files are used to specify rules to create nupkgs by using the paket pack command.
.paket: This folder is used the same way a .nuget folder is used for the NuGet package restore. Place this folder into the root of your solution. It should include the paket.targets and paket.bootstrapper.exe files which can be downloaded from GitHub. The bootstrapper.exe will always download the latest version of the paket.exe file into this folder.

The complexity of packet design concerns me. It seems unnecessary.

**Comment by forki** [comment]
1) see http://fsprojects.github.io/Paket/glossary.html - please send PRs
2) no idea what you mean ;-)
3) do you mean the lock file?

    "Paket data model seems unnecessarily complex despite having no automatic provision for using multiple versions of the same package in a solution which may be expected from "transient" dependencies."

What you describe is a version conflict which is usally just ignored by NuGet. we have ways to resolve this. One way is via groups (see http://fsprojects.github.io/Paket/groups.html#Conflict-resolution-with-groups)

**Comment by gdennie** [comment]
2) ...Your documentation is written against the concepts of Nuget in which secondary or transient or indirect dependencies are not handled well; so, as I understand it, that's why the transient concept is emphasized. However, dependency is inherently expansive since A=>B=>C implies A=>C. Consequently, the emphasis was a bit confusing.

The data model of paket would appear to correctly handle, among other things, a dependency chain such as, A=>C1 & A=>B=>C2. I believe it would be useful to talk about the functionality from the perspective of the data architecture.
