### ISSUE TITLE
Paket 2.0 - Analysers are not removed or updated in msbuild files.

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#1047]
Analyzers are not removed from the msbuild files, when the package no longer actually contains them (for example after downgrading a package). 

Repro: Switch between latest `Microsoft.CodeAnalysis.Analyzers` and `1.0.0-rc2`
``` 
git clone https://gist.github.com/matthid/12287ff17adad06f951e paket-test
cd paket-test
paket.bootstrapper.exe prerelease
paket.exe update
```

After those steps I expect that the msbuild files have pending changes, because the (previously added) analyzer paths (`packages\Microsoft.CodeAnalysis.Analyzers\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll`) no longer exist.

As a sidenote `paket update --force --hard` or `paket install --hard` don't seem to update anything as well.

**Comment by forki** [comment]
Fixed in 006?

**Comment by matthid** [comment]
Not fixed in 006 :(.

**Comment by forki** [comment]
Sorry my comment was on wrong issue

**Comment by forki** [comment]
@vbfox could you please take a look? thx

**Comment by vbfox** [comment]
Yes i'll take a look, they should be updated due to the `<Paket>` node but I might have missed something

**Comment by vbfox** [comment]
Btw `1.0.0-rc2` doesn't contains any analyzer matching the expected convention (They were placed in `tools` and so can only be added by the powershell scripts.

**Comment by matthid** [comment]
@vbfox Thanks for the clarification and the fix, now everything seems to work fine.
