### ISSUE TITLE
paket pack creates package with wrong zip format if it is executed under Mono (Linux/OSX)

### ISSUE THREAD

**Issue by magicmonty** [fsprojects/Paket#1056]
I have the following paket.template:
```
type file
id Pagansoft.Functional
authors Martin Gondermann
owners Martin Gondermann
description
  Functional data types for C#
files
  Functional/bin/Release/Pagansoft.Functional.dll ==> lib/net40
  Functional.Net35/bin/Release/Pagansoft.Functional.dll ==> lib/net35
  Functional.Portable/bin/Release/Pagansoft.Functional.dll ==> lib/portable-wpa+windows8+net45
```

If I pack this with OSX or Linux (like I currently do with Travis CI), the last directory becomes `lib/portable-wpa%2Bwindows8%2Bnet45`, which breaks the installation via nuget.

If I pack under Windows, everything is fine.

Seems related to #963

**Comment by forki** [comment]
can you try to come up with a fix?

**Comment by magicmonty** [comment]
Sure, I try it

**Comment by magicmonty** [comment]
I investigated this problem further, and it seems the escaping ist not the problem. Instead we have here a more serious problem, where I currently have no solution for. I'll try to explain, what I found:

Paket itself uses `System.IO.Compression.ZipArchive` to create the nupgk-File. Under Mono this class is implemented as such, that the "Version needed to extract" in the PK-Header (Bytes 5 and 6) is set hardcoded to `0x003F`, which corresponds to a PKZip Version of 6.3.
In the .Net-Framework under Windows, this class creates a Zip file with a version of `0x0014` (corresponds to 2.0).

Nuget uses for decompression the `System.IO.Packaging.Package` class which in turn has a problem with "newer" Zip files that have a higher Version number than `0x0014`. This leads to a `NotSupportedException` in NuGet, as it tries to open the NuGet-Package, if the package was created under Linux or MacOSX (resp. under Mono).

I already tried to replace the ZipArchive class with `ICSharpCode.SharpZipLib`, but with no luck, as SharpZipLib also writes the wrong header. 

What we need here to fix this bug, is a library, which writes ZipFiles with Version 2.0 only.

I therefore change also the title of this issue to "paket pack creates package with wrong zip format if it is executed under Mono"

**Comment by forki** [comment]
So this is a mono bug? Maybe raise an issue in the mono bug tracker

**Comment by magicmonty** [comment]
No, I don't think this is actually a mono bug. It is just a different behaviour in mono and .Net

**Comment by magicmonty** [comment]
Maybe its more of a NuGet bug. NuGet should be able to open newer zip formats. I just opened a bug report on the NuGet BugTracker (https://github.com/NuGet/Home/issues/1381)

**Comment by magicmonty** [comment]
Update: A similar bug report already exists in the Mono bugtracker: https://bugzilla.xamarin.com/show_bug.cgi?id=33553

**Comment by forki** [comment]
question is: can we do something aout that?

**Comment by magicmonty** [comment]
I would say, until mono has fixed this: is there possibly another Zip-Library, which can be used?
I tried already https://github.com/icsharpcode/SharpZipLib and http://dotnetzip.codeplex.com, but both write the 0x003F header. The .Net Framwork can open at max 0x002D (4.5), so maybe we need a library that can write Zip64 but no Encryption or is at least configurable to to so.

**Comment by magicmonty** [comment]
maybe https://github.com/phofman/zip could work.

**Comment by forki** [comment]
We already tried different zip libs before and always found issues. I doN't think that's the way to go.

**Comment by magicmonty** [comment]
maybe we could give [ZipStorer](https://github.com/jaime-olivares/zipstorer) a try? One could even implement this directly in the package

**Comment by ristaloff** [comment]
Any progress on this? I'm trying to create nuget packages on my linux buildserver.

**Comment by forki** [comment]
that mono issues is still open, right?

**Comment by ristaloff** [comment]
Yes.

**Comment by tritao** [comment]
We've fixed the reported issue in Mono, please test with latest development version and let us know if there's any issues left for Paket.

**Comment by magicmonty** [comment]
I just tested it with the latest version of mono (manually built from [c153626bdf923ef47b48eaf119423b39dfb8184a](https://github.com/mono/mono/commit/c153626bdf923ef47b48eaf119423b39dfb8184a)) and it works for me. As soon as a new stable mono version is released, which contains this patch I would consider this bug as fixed.

**Comment by forki** [comment]
Thanks!
