### ISSUE TITLE
Create chocolatey installer 

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#106]
Relates to #42

**Comment by masaeedu** [comment]
@forki Why was this closed?

**Comment by forki** [comment]
I think we have a choco package. Not sure if it still works

**Comment by masaeedu** [comment]
@forki Is [`Paket.Powershell`](https://chocolatey.org/packages/Paket.PowerShell/3.35.6) it? I can't find any packages that just put a `paket.exe` binary on my PATH. Would be good to have something in your CI that publishes such a package.
