### ISSUE TITLE
Paket update added an app.config to every project

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#1068]
Using Paket v 2.2.1, when I ran an update it created an app.config in every single project. Would you mind taking a look please?

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
    <runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1" /></runtime></configuration>

**Comment by forki** [comment]
I'm off sailing for a week. Could you please downgrade for that week?

**Comment by cjbhaines** [comment]
Sure, no problem. Enjoy your holiday!

**Comment by forki** [comment]
sorry. that was a really bad bug

**Comment by cjbhaines** [comment]
Thanks for fixing!

**Comment by cjbhaines** [comment]
I just updated to 2.3.0 and I can confirm this is fixed.
