### ISSUE TITLE
paket.bootstrapper.exe fails on Ubuntu

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/Paket#1072]
paket.bootstrapper.exe fails to download paket.exe on Ubuntu using Mono.  See screenshot:

![screenshot from 2015-09-20 21 37 58](https://cloud.githubusercontent.com/assets/1795462/9984126/3768eef4-5fe0-11e5-9431-b5a5da70c24a.png)

I downloaded the solution and debugged using MonoDevelop.  Looks like the error occurs in the download strategies (GithubDownloadStrategy and NugetDownloadStrategy) whenever the WebClient tries to download anything.  The error is specifically thrown at https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/GitHubDownloadStrategy.cs#L48 and https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/NugetDownloadStrategy.cs#L72.

Here's the stack trace:

exn	{System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a   at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0    at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0    at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0    at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0    at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()   at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0    at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0    --- End of inner exception stack trace ---   at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0    --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0    at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0    at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0    at System.Net.WebClient.ReadAll (System.Net.WebRequest request, System.Object userToken) [0x00000] in <filename unknown>:0    at System.Net.WebClient.DownloadDataCore (System.Uri address, System.Object userToken) [0x00000] in <filename unknown>:0 }	System.Net.WebException

So it looks like Mono thinks the certificate is invalid.  I've actually seen this error before, also with Mono, when doing some Xamarin iOS development.  For whatever reason, when reaching out to a https URL the certificate validation fails.  There is a simple way to get around this though, by setting the ServicePointManager.ServerCertificateValidationCallback to always return true.  See here for an example: https://github.com/splunk/splunk-sdk-csharp-pcl/blob/master/examples/submit/Program.cs#L38

Anyway, I add the following code snippet to Program.cs to modify the ServerCertificateValidation callback:

```c#
static Program()
{
    ServicePointManager.ServerCertificateValidationCallback +=
        (sender, certificate, chain, sslPolicyErrors) =>
         {
             return true;
        };
}
```

And lo and behold, it works and downloads without error!

Anyway, should I submit this as a pull request?  To be perfectly honest I am not fully aware of the security ramifications of making that callback always return true.  I did a bit of research and found [this](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.servercertificatevalidationcallback%28v=vs.110%29.aspx) MSDN documentation which says "When custom validation is not used, the certificate name is compared with host name used to create the request. For example, if Create(String) was passed a parameter of "https://www.contoso.com/default.hmtl", the default behavior is for the client to check the certificate against www.contoso.com."  I tried to poke around the Mono code base to see if they did the same but couldn't really make sense of it.  I see that the Mono code in question is around [here](https://github.com/mono/mono/blob/88d2b9da2a87b4e5c82abaea4e5110188d49601d/mcs/class/Mono.Security/Mono.Security.Protocol.Tls.Handshake.Client/TlsServerCertificate.cs#L185), and the actual error is thrown [here](https://github.com/mono/mono/blob/88d2b9da2a87b4e5c82abaea4e5110188d49601d/mcs/class/Mono.Security/Mono.Security.Protocol.Tls.Handshake.Client/TlsServerCertificate.cs#L223).

Anyway, does anybody have any idea if changing the ServerCertificateValidationCallback to always return true is a terrible idea?  I think that given how limited the functionality of paket.bootstrapper.exe is it's probably fine.  Also, this error is blocking all users on Ubuntu and probably on OS X as well.  Thoughts?

**Comment by forki** [comment]
Yes please send us a pull request

**Comment by cdrnet** [comment]
I assume this is not resolved by calling `mozroots --import --sync` once?

**Comment by dnauck** [comment]
+1 for using ```mozroots --import --sync```

**Comment by NatElkins** [comment]
Ah, yep, that resolved it.  Did not realize that Mono does not ship with any default certificates.  Thanks for chiming in, much appreciated.

Perhaps I'll make a pull request to suggest this in the error message.

**Comment by forki** [comment]
Oh yes that would be nice.
