### ISSUE TITLE
Need to configure location for the "packages" folder

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1086]
I wonder if there is a way to configure where Paket creates (or expects to find) "packages" folder. It is really important, actually! Consider the following scenario:

Root folder contains subfolders with sub-solutions which all produce components to be assembled into a single product. Sub-solutions are used for manageability - to avoid having humongous solution with hundreds of projects. If each sub-solution maintains its own Paket.dependencies, Paket.lock and packages folder - results appear to be rather poor. Separate packages folders contain lots of duplicated packages, but what is much worse - there is no control that all those Paket.dependencies are coordinated and all sub-solutions end up using same versions of external packages! Do you see the problem? The whole point of Paket.dependencies is to have single location with all requirements for external packages, so that the final version to use could be coordinated. In case of sub-solutions it all falls apart. 

There must be a way to tell Paket to look for Paket.dependencies and create packages folder at the root location (for my example above), so that all sub-solutions share that infrastructure. Can this be done through the Paket configuration file maybe?

Thank you for consideration!
Konstantin

**Comment by forki** [comment]
We only have one paket.dependencies + one paket.lock at the root. The
packages folder is created at same level as the dependencies file.

**Comment by konste** [comment]
But "paket install" updates project files, right? How does it find the projects to update? Does it read solution file (and if yes, then which one)? or it simply finds all project files in subtree of the root and updates all of them where paket.references is found?

**Comment by forki** [comment]
It scans in the subtree and finds all projects and their corresponding
paket.references.

**Comment by konste** [comment]
Got it. Thank you! 
From documentation I was under impression that everything is placed relative to solution file, which does not seem to be the case.

**Comment by forki** [comment]
Would love to see that made clearer in the docs. Could you please try to
reword and send a PR?

**Comment by konste** [comment]
I never dealt with Git before, but may as well give it a try tomorrow.

**Comment by forki** [comment]
You can do this from the github UI. Just try to find the corresponding md
file in the repo and edit online. It will also allow you to send a pull
request

**Comment by konste** [comment]
So I'm trying to figure Paket behavior "black box style" which is not very effective, but I don't know F# :(

I can see that Paket traverses folders and updates all projects where Paket.references is found, BUT when it sees another Paket.dependencies it does not go further that branch! Which is actually good, just totally unexpected.

@forki let me try to clarify the docs, but I would really appreciate if you would be able to take a look at #1081 - every run of Paket install adds meaningless section to more or less all configs! The problem is cosmetic, but really ugly and makes Paket much harder to use.
