### ISSUE TITLE
Difference in dependency resolving from udate and install

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#1087]
This one has been bugging me for a while, but unfortunately I am unable to give a repro with publicly available packages.
(I can however provide `paket.dependencies` and `paket.lock` by email if it helps troubleshooting)

The main issue here is that `paket update nuget my.package` fails due to a dependency it claims to be unable to resolve.

However, if I just explicitly set the correct version in the `paket.dependencies` file, and run `paket install` it resolves and installs as expected.

The package in question is an interop package consumed from VB6 (*gasp*). And it is release together with a UI and core package that share the same version.

* My.Package.Interop (referred from the `paket.dependenies` file of the VB6 project
* My.Package.Ui (dependency of the interop package)
* My.Package (core package, both UI and Interop package depends on this one)

I update these package frequently, and always release them simultaneously.

No other dependency changhes are made, IE none of the indirect dependencies that might be shared with other unrelated packages are changed. Only these three packages have changes.

Which puzzels me, cause the dependency graph from running `paket update nuget My.Package` should be the same as the one you get when explicitly setting the version in the `paket.dependencies` file and running `paket install`. (At least in my naive mind it should be).

**Comment by forki** [comment]
Yes please send via mail.

/cc @mrinaldi

**Comment by Vidarls** [comment]
Sent you the paket files, together with verbose output from both failing update and succeeding install

**Comment by mrinaldi** [comment]
Can you send me them too?

**Comment by Vidarls** [comment]
I can, but then I'd need your email address :)

**Comment by mrinaldi** [comment]
me at marciorinaldi dot com

thx

**Comment by forki** [comment]
ok I was able to find the issue. It's related to ProGet.

The following reproduces it:

* Create local ProGet server
* Create paket.dependencies:

    source http://localhost:81/nuget/Default      
    nuget Automapper
* run paket update.

It will install Automapper 3.2.0 instead of 4.0.4. This os related to the fact that http://localhost:81/nuget/Default/FindPackagesById()?id='Automapper' only returns versions up to 3.2.0 and doesn't include a `rel="next"` link in the OData response - so we don't do pagination.

Question is: can we use a different url?

/cc @maartenba

**Comment by maartenba** [comment]
`/Packages?Id='Automapper'` may do the trick, but ideally it just needs continuation tokens imho.

**Comment by forki** [comment]
`http://localhost:81/nuget/Default/Packages?$filter=Id eq 'Automapper'` doesn't work at all

**Comment by maartenba** [comment]
Then Inedo is the party to talk with :)

**Comment by Vidarls** [comment]
Raised a support ticket with @Inedo support, referring to this issue, hopefully it will get some attention :)

**Comment by forki** [comment]
it even reproduces with nuget.exe:

![image](https://cloud.githubusercontent.com/assets/57396/10161063/c54a5fa6-66a1-11e5-9007-4cd96d9af17c.png)

**Comment by gdivis** [comment]
Hi, I'm a dev at Inedo. TLDR: We're fixing this in ProGet 3.8.3, which will be released today.

If you're still reading, here's a little explanation. ProGet's connectors kind of break down a little bit with very large result sets - in order for us to properly do things like apply filtering and aggregate versions from local packages/remote feeds, we'd have to unpaginate all the results from all connectors before returning anything to the client, and currently we don't do that for performance reasons. For most queries, the result set isn't large enough for this to be an issue, but you just ran into one where it is. However, GetPackagesById seems to be one case where we absolutely want to return everything, and the result set _shouldn't_ be large enough for it to be a big performance bottleneck, so we are changing this behavior to always follow all rel="next" links for that particular odata method.

The scalability issues of our NuGet connectors is something we're aware of and have plans to fix using a periodically updated local nuget.org index. It's on our [roadmap] (http://inedo.com/proget/roadmap), but doesn't have a scheduled release date yet.

Thanks for letting us know about this!

**Comment by Vidarls** [comment]
Confirming that `paket update` now works as expected with ProGet 3.8.3

**Comment by forki** [comment]
![dance](https://cloud.githubusercontent.com/assets/57396/10189952/c00427de-6769-11e5-82fa-7d443d559fd9.gif)

cool.
