### ISSUE TITLE
`>= 0.0.0-prerelease` vs `prerelease`

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#1088]
Let's say I have:

```
LibraryA 1.0.0
LibraryA 1.1.0-prerelease
```

Adding the nuget dependency:
`nuget LibraryA >= 0.0.0-prerelease` will resolve to `1.0.0`
`nuget LibraryA prerelease` will resolve to `1.1.0-prerelease`

When using Paket.Pack:
`nuget LibraryA >= 0.0.0-prerelease` will add a dependency to `">= 0.0.0-prerelease"` to the nuspec
`nuget LibraryA prerelease` will add a dependency to `""` to the nuspec

**Comment by forki** [comment]
Will look into this on Monday when I'm back from sailing

**Comment by forki** [comment]
nuget LibraryA >= 0.0.0-prerelease

this is actually not supported. Why don't you ise 

    nuget LibraryA >= 0.0.0 prerelease

?

**Comment by flowsprenger** [comment]
when we use
```nuget LibraryA >= 0.0.0-prerelease```
and then use Paket.Pack this dependency is added to the nuspec
``` <dependency id="LibraryA" version="0.0.0-prerelease" /> ```
which creates a transitive dependency on the prerelease.

if we use 
```nuget LibraryA >= 0.0.0 prerelease```
the nuspec has an empty version
```<dependency id="LibraryA" version="" />```

**Comment by forki** [comment]
But is that the correct nuspec syntax for prereleases?

**Comment by flowsprenger** [comment]
http://docs.nuget.org/create/versioning#Specifying-Version-Ranges-in-.nuspec-Files:
```As of NuGet 1.6, NuGet supports the creation of prerelease packages by specifying a prerelease string in the version number according to the Semantic Versioning (SemVer) specification.```

also paket update will resolve ```<dependency id="LibraryA" version="0.0.0-prerelease" />``` to the latest prerelease already

**Comment by forki** [comment]
Ok so the bug is actually in the code that creates the new nuspec during
pack, right?

**Comment by flowsprenger** [comment]
sounds reasonable to me. if it would apply the following transformations, i think it would mirror how paket update is resolving the packages:

```nuget LibraryA >= 0.0.0 prerelease``` => ```<dependency id="LibraryA" version="0.0.0-prerelease" />```
```nuget LibraryA = 0.0.0 prerelease``` => ```<dependency id="LibraryA" version="[0.0.0-prerelease]" />```
```nuget LibraryA >= 0.0.0``` => ```<dependency id="LibraryA" version="0.0.0" />```
```nuget LibraryA = 0.0.0``` => ```<dependency id="LibraryA" version="[0.0.0]" />```

**Comment by forki** [comment]
What about alpha and beta versions? Paket is making a difference here

**Comment by flowsprenger** [comment]
i dont think @devboy has tested the same with alpha & beta versions. unfortunately he is out of office this week. i can try and see if i can create a small testcase later.

**Comment by devboy** [comment]
Nope haven't tested that! Greetings from Greece!

**Comment by flowsprenger** [comment]
Paket.Pack behaves the same when packing nupkgs that depend on alpha release.
Or do you suspect that the difference in behaviour is for paket update?

**Comment by forki** [comment]
sorry I don't have a real repro sample at the moment, but I tried to fix it in the dark. could you please try with 2.4.8?

**Comment by flowsprenger** [comment]
thanks for looking into it so quickly. i only looked at it briefly so far but at first glance 2.4.8 does:
```nuget LibraryA >= 0.0.0 prerelease => <dependency id="LibraryA" version="0.0.0-prerelease" />```
which is good :) but
```nuget LibraryA = 0.0.0 prerelease => <dependency id="LibraryA" version="[0.0.0-prerelease]" />```
is
```nuget LibraryA = 0.0.0 prerelease => <dependency id="LibraryA" version="[0.0.0]" />```
which is weird, no? well i don't think we particularly have a usecase for the later either.

**Comment by forki** [comment]
mhm. I guess the last one is correct. Specifying a concrete version should always point to that version.
 the prerelease info is just not making sense on `=`
