### ISSUE TITLE
Inconsistent framework exclusion in paket.dependencies

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1093]
Consider this scenario: we target NET45 and nothing else. To indicate that fact we put "framework: net45" at the top of paket.dependencies, which in my understanding supposed to work the same as adding "framework: net45" to each package. Still we get this in the paket.lock:
ZendeskApi_v2 (3.0.2)
      AsyncCTP  - framework: >= net40

Package ZendeskApi_v2 depends on AsyncCTP ONLY for net40 and the fact that we get it for net45 actually causes build break, because AsyncCTP cannot be used with net45.

After vigorous pounding my head against the wall I found the workaround:
nuget ZendeskApi_v2 3.0.2 framework: >= net45
with that AsyncCTP does not get wired up to the project.

But WHY framework: >= net45 works better (or even differently) than framework: net45 is a mystery which keeps me awake at night. Could somebody please shed some light onto what is going on here?

**Comment by forki** [comment]
I assume the bug is the code that tries to minimize the dependency
requirements. Will try to reproduce

**Comment by forki** [comment]
confirmed. it's a bug

**Comment by konste** [comment]
Thanks a lot for speedy fix! I can sleep again ;-)

**Comment by forki** [comment]
Fix is not completely ready, but should already solve your use case. Can
you please confirm?

**Comment by konste** [comment]
On it...

**Comment by forki** [comment]
just found another related bug.

wait a minute

**Comment by konste** [comment]
I will wait for the next version, but just FYI 2.4.2 does not resolve my case. Struggling with GitHub to attach relevant repro files.

**Comment by konste** [comment]
Shared files in OneDrive folder here: http://1drv.ms/1O4Ttig

**Comment by forki** [comment]
so fixed the second bug. please try again. sorry for the ping pong

**Comment by konste** [comment]
Nope, still does not work. Resulting paket.lock.2.4.3.txt shared in the same folder.

**Comment by konste** [comment]
Critical part is this:
    ZendeskApi_v2 (3.0.2) - framework: >= net45
      AsyncCTP  - framework: >= net40
but a few other parts look weird:
    Antlr (3.5.0.2) - framework: net45, net45, net45, net40, >= net45, >= net451
or this:
      Newtonsoft.Json (>= 6.0.4) - framework: portable-net45+wp80+wpa81+win, >= net40, >= net45

**Comment by konste** [comment]
I prefer ping pong to "Chess by snail mail" ;-)

**Comment by forki** [comment]
are you sure you did the "paket update" with 2.4.3? I don't get AsyncCTP in the lock file any more.

**Comment by forki** [comment]
please try "paket update -f" maybe it's cache related

**Comment by forki** [comment]
btw: you don't need to add the nuget v3 feed, Paket is automatically detecting this feed when you have the v2 enabled.

**Comment by konste** [comment]
v3 feed removed.
With "update" the bug is indeed fixed, although I must admit I lost my understanding of the difference between Install and Update. I thought if I don't want to move package versions forward I don't need Update.
Folder http://1drv.ms/1O4Ttig updated.
Still weird cases when irrelevant frameworks are pulled in remain.

**Comment by forki** [comment]
yes usually an "install" is enough, but in this case you want to skip all the previous buggy logic from the cache.

I'm working on further optimizations.

**Comment by forki** [comment]
please retry a paket update. grouping should be much better now.

**Comment by forki** [comment]
shit. it's still not good.

**Comment by konste** [comment]
Don't rush it - my case is admittedly hard. Very well may serve as a comprehensive test in the future :-)

**Comment by forki** [comment]
ok now it loks pretty. hope it fixes your case now.

**Comment by konste** [comment]
Oh no! It got pretty indeed, but it regressed and the problem which started it all is back:

 ZendeskApi_v2 (3.0.2) - framework: >= net45
      AsyncCTP  - framework: >= net40

**Comment by konste** [comment]
Wait, I could be wrong...

**Comment by forki** [comment]
are you sure? it doesn't come back for me

2015-09-28 18:02 GMT+02:00 konste <notifications@github.com>:

**Comment by konste** [comment]
It looks like ".paket\paket update -f" fixed it. "-f" appeared to be the flag which made the difference.
Phew... Keep it as a test against regressions. Actually, I will let you know if it regresses :-)

**Comment by konste** [comment]
Thank you for a great and winning push!!

**Comment by forki** [comment]
I think I have some great news for you for the next version. your case made
me fix a perf issue that I didn't find before. so stay tuned ;-)

2015-09-28 18:10 GMT+02:00 konste <notifications@github.com>:

**Comment by forki** [comment]
first results are coming in. 2.5.0-alpha002 is 4.2x faster on your dependencies file than 2.4.0

**Comment by konste** [comment]
Faster on which operations?

**Comment by forki** [comment]
update, install
