### ISSUE TITLE
VS plugin should not create its own output pane

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1096]
VS plugin for Paket tends to switches current pane in Output window to "Paket" only to show couple lines "Restoring packages" and "Ready". Usually people want to see build output in the Output window when the build starts. In my opinion Paket output should go to the same pane where regular build output goes.

**Comment by forki** [comment]
Please open this issue in the Paket.VisualStudio project

**Comment by konste** [comment]
Done. I have not realized there is separate project for VS plugin.
