### ISSUE TITLE
How to remove Paket references from the project?

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1097]
When somebody wants to remove Paket created references from the project naive approach is to delete paket.references file. It takers some time to realize that the only effect it has - Paket does not look at that project anymore, but does not remove existing references from it either. Approach which works is to have empty paket.references file - then references indeed get removed. 

Ideally removal of the paket.references file should have the same effect, but it may be ineffective performance wise as it would require to look inside each and every project. If performance impact appear to be substantial, then the trick with empty paket.references file should be documented.

**Comment by forki** [comment]
"he trick with empty paket.references file should be documented" 

I'd love to see such a PR

**Comment by forki** [comment]
I decied that we should cover this case and now paket removes all installed Paket entries from projectes which have no corresponding paket.references.

**Comment by konste** [comment]
I'm glad you did! Trick with empty Paket.references really looked as a clumsy workaround. I would hate to have it documented as a proper way of removing references. Now it is much more natural.
