### ISSUE TITLE
"-prerelease" in .nuspec breaks `paket update` etc.

### ISSUE THREAD

**Issue by amazingant** [fsprojects/Paket#1099]
After building a project and distributing the new package today, noticed that `paket update` fails when updating a package that depends on a pre-release package. Calling the three packages "A", "B", and "C", "A" and "B" are in the same solution and now at version `0.33.0-beta`; "B" depends on "A", and this is specified as a project-dependency in the project file. Project "C" depends on "B" only.

Output of `paket update` looks like this:

```
Error in resolution.
  Resolved:
   - FSharp.Core 4.0.0.1
   - Project_B 0.33.0-beta
  Could not resolve package Project_A:
   - Project_B 0.33.0-beta requested >= 0.33.0-beta-prerelease
 Please try to relax some conditions.
```

After some quick testing, it looks like some part of the changes for #1088 added this `-prerelease` suffix to the end of project B's version requirement for project A, rather than leaving it as requiring `0.33.0-beta`. Assuming that this new suffix is intended to be there, I'm not sure whether this is considered an issue in how `paket pack` is naming my packages, how it's creating the `.nuspec` file, or in how dependency resolution is finding the required packages.

**Comment by forki** [comment]
"0.33.0-beta-prerelease" is not correct syntax. so I messed that up.

**Comment by forki** [comment]
so I fixed that in 2.5. - but you have to pack the package with the broken "0.33.0-beta-prerelease" in the nuspec again. sorry about that

**Comment by amazingant** [comment]
Thanks! I'll have to dig around and see how many things I've built since 2.4.8 got released, but it shouldn't be too many.

**Comment by amazingant** [comment]
Sorry I didn't notice this before, but continuing to dig around, paket 2.5.0 is still adding `-prerelease` on the end of another dependency. It's a "transient" dependency on version 4.3.1 of a package is specified as `(4.3.1)` in the lock file, and it's showing up as `4.3.1-prerelease` in the .nuspec file. [This line][1] makes it look like this is intentional? It looks like if I add it back into the dependencies file (`paket simplify` removed it for me a while ago), the .nuspec file goes back to just `4.3.1`.

[1]: https://github.com/fsprojects/Paket/blob/a914c37bee54fa4d57fd62617c2d12397a792d56/src/Paket.Core/PackageMetaData.fs#L253

**Comment by forki** [comment]
fixed that too. please try 2.5.1

**Comment by amazingant** [comment]
Now showing in the nuspec file as `[4.3.1]` :+1:

I'll try not to complain again for at *least* a few more hours :wink:

**Comment by forki** [comment]
It's good to have that fixed. Thanks for reporting
