### ISSUE TITLE
Allow specifying custom source for the bootstrapper to find paket.exe

### ISSUE THREAD

**Issue by amazingant** [fsprojects/Paket#1100]
As much as I love that paket auto-updates itself whenever I run my build scripts (loosely based on the ProjectScaffold project, so `build.cmd` calls `paket.bootstrapper` before doing anything else), new features sometimes break existing processes. In my work environment, for any third-party packages we use (including build tools like FAKE), we keep the latest .nupkg that we've tested against in our local package source.

To match this, it'd be useful to have a command-line option for the bootstrapper that tells it where to get `paket.exe` from, so that build scripts don't have to be updated to get the latest-and-greatest, but someone can run a new version of paket through some hoops before using it globally.

FWIW, it's rare that I actually have any concern with paket's auto-update (or new versions of FAKE, for that matter), and it's been great to see new features show up without having to do anything. This is an amazing tool that helps simplify otherwise complicated workflows, and the hard work put into this is very much appreciated!

**Comment by mexx** [comment]
@amazingant can it be closed?

**Comment by amazingant** [comment]
@mexx Just got a chance to try it at work and look at the code changes. While #1261 initially looked to solve the meat of this issue, the new `--nuget-source` parameter is limited to calling a web server. This originally made sense since the bootstrapper is intended to pull paket off nuget.org as a backup source when GitHub is down. Since the main `paket.exe` supports pulling `.nupkg` files out of a directory, I don't actually have a proper nuget "server" anywhere though, as my package source is a directory path pointing to an SMB share.

Actually running the new bootstrapper, I noticed that since it can't find the nuget API it's looking for, it decided to fallback to downloading paket off GitHub. While it should be a rare occurrence, if I forgot to mount that network share (or it went down for maintenance, or whatever), anything using paket during that time is going to get the latest release off GitHub. Rather defeats the original intent I had in opening this issue.

I can work on a pull request to make a few more changes, if that's alright? May take me a few days to get to it though.

**Comment by forki** [comment]
yes please

2015-11-30 14:22 GMT+01:00 Anthony Perez <notifications@github.com>:

**Comment by amazingant** [comment]
No complaints here as I'm happy working with C#, but slightly curious: how did the bootstrapper end up written in C# instead of F#?

**Comment by forki** [comment]
we wanted to keep it small (in terms of KB) and therefore wanted to avoid FSharp.Core reference

**Comment by amazingant** [comment]
Makes sense, and appears to have worked well given the size of the bootstrapper vs FSharp.Core.dll

Currently waiting for a DBA to get in, so I've got a pull-request started at #1268
