### ISSUE TITLE
Wrong paket ProjectRefences name causes incorrect packaging

### ISSUE THREAD

**Issue by SavaNDragos** [fsprojects/Paket#1113]
I fond a pretty intereting issue when creating nuget packages:
In a proj file we can find the ProjectRefences (they resolve the dependencies between projects that are part of the same solution).
In case the project name we are refencing is different from the value that the projectreference has as a name, when paket creates the packages, it will do it wrong (it will include the assamblies for 
referenced project also).
In the below example you can see   ClassLibraryt.dll was included in the package because 
<Name>ClassLibraryt</Name> is different from ClassLibrarytModified.csproj">

Example if we have:
    <ProjectReference Include="..\ClassLibraryt\ClassLibrarytModified.csproj">
      <Project>{e6fef228-2b3b-451c-b7b6-1f309f24e2de}</Project>
      <Name>ClassLibraryt</Name>
    </ProjectReference>
in our resulted packege we will have:
Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-----        06/10/2015     10:30       4096 ClassLibraryt.dll
-----        06/10/2015     10:45       4608 ConsoleApplicationc.dll
-----        06/10/2015     10:45      11776 ConsoleApplicationc.pdb

Normally if we would have had
    <ProjectReference Include="..\ClassLibraryt\ClassLibrarytModified.csproj">
      <Project>{e6fef228-2b3b-451c-b7b6-1f309f24e2de}</Project>
      <Name>ClassLibrarytModified</Name>
    </ProjectReference>
the rsult would have been:
Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-----        06/10/2015     10:31       4608 ConsoleApplicationc.dll
-----        06/10/2015     10:31      11776 ConsoleApplicationc.pdb

**Comment by SavaNDragos** [comment]
ProjectReference Include="..\ClassLibraryt\ClassLibrarytModified.csproj"
      Project {e6fef228-2b3b-451c-b7b6-1f309f24e2de} Project
      Name ClassLibraryt Name
    ProjectReference

    ProjectReference Include="..\ClassLibraryt\ClassLibrarytModified.csproj"
      Project {e6fef228-2b3b-451c-b7b6-1f309f24e2de} Project
      Name ClassLibrarytModified Name
  ProjectReference

**Comment by forki** [comment]
I'm not sure I understand the issue. can you try to put this into a repro.zip?

**Comment by SavaNDragos** [comment]
You should get it from https://github.com/SavaNDragos/Share

**Comment by SavaNDragos** [comment]
Now if you run paket pack on this you will see 2 packages created, one of them (ConsoleApplicationc) contains also the assamblies from the other one (which it is refering) because the ProjectReference Name is ClassLibraryt , but the project name ClassLibrarytModified (ClassLibrarytModified.csproj).
If you change the ProjectReference Name to ClassLibrarytModified the packages will be published correctly (ConsoleApplicationc will no longer contain the asamblies for ClassLibrarytModified).
