### ISSUE TITLE
Microsoft.Bcl.Async nags about missing "The type 'AnnouncementClient' is required here and is unavailable."

### ISSUE THREAD

**Issue by albertjan** [fsprojects/Paket#1117]
The project is built to .net 4.6 so it should not do anything. At least I was under the impression it shouldn't do anything. 

But to my suprise this ended up in my project file:

```xml
<When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And
 ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or 
  $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or
  $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6')">
  <ItemGroup>
    <Reference Include="Microsoft.Threading.Tasks.Extensions.Desktop">
      <HintPath>..\..\packages\Microsoft.Bcl.Async\lib\net40\Microsoft.Threading.Tasks.Extensions.Desktop.dll</HintPath>
      <Private>True</Private>
      <Paket>True</Paket>
    </Reference>
      yadda yadda yadda
  </itemGroup>
</when>
```

why does this reference get added to the project for 4.6 when the package is obviously meant for .net4.

I don't know if this is a paket issue, but I thought I'd ask here anyway.

ps. I'm so fed up with these Bcl packages...

**Comment by forki** [comment]
`net40` means .NET 4.0 and above. at least if there is no other net folder.

Try with Nuget - it will install the same dlls.

**Comment by albertjan** [comment]
Alright I believe you. :smile: I have to manually remove this ref from the project to get it to build.

**Comment by eiriktsarpalis** [comment]
I've recently started getting the same error message actually. For example [this project](https://github.com/fsprojects/FSharp.AWS.DynamoDB/tree/6405f729f6d18fd7973ab3a3e71e8e9191c78dd6) currently builds as expected, but it will fail as soon as I paket update.

**Comment by eiriktsarpalis** [comment]
For the record, and reproducing our private discussion with @forki, the problem more likely has to do with a bug in paket when resolving the dependency graph for AWSSDK.Core, which has the following dependency tree
```xml
    <dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETPortable0.0-net45+netcore45+wpa81+wp8+MonoAndroid10+xamarinios10+MonoTouch10">
        <dependency id="Microsoft.Net.Http" version="2.2.29" />
        <dependency id="PCLStorage" version="1.0.2" />
        <dependency id="PCLCrypto" version="1.0.2.15130" />
      </group>
    </dependencies>
```
which however is resolved to the following paket.lock:
```
 AWSSDK.Core (3.1.5.3)
      Microsoft.Net.Http (>= 2.2.29) - framework: >= net45, portable-net45+win8+wp8+wpa81
      PCLCrypto (>= 1.0.2.15130) - framework: >= net45, portable-net45+win8+wp8+wpa81
      PCLStorage (>= 1.0.2) - framework: >= net45, portable-net45+win8+wp8+wpa81
```
