### ISSUE TITLE
"Could not resolve package" when using local cache and nuget

### ISSUE THREAD

**Issue by mkb137** [fsprojects/Paket#1122]
With a `package.dependencies` file containing only:
```
    source C:\Users\mkb137\AppData\Local\NuGet\Cache
    source https://www.nuget.org/api/v2/

    nuget Microsoft.AspNet.Mvc 5.2.3 framework: >= net45
    nuget Microsoft.AspNet.WebApi 5.2.3 framework: >= net45
```

I was getting the error:

```
Error in resolution.
  Resolved:
   - Microsoft.AspNet.WebApi.Core >= 5.2.3 < 5.3.0
   - Microsoft.AspNet.WebApi.WebHost >= 5.2.3 < 5.3.0
   - Microsoft.AspNet.Razor >= 3.2.3 < 3.3.0
   - Microsoft.AspNet.WebPages >= 3.2.3 < 3.3.0
   - Microsoft.AspNet.Mvc 5.2.3
   - Microsoft.AspNet.WebApi 5.2.3
   - Newtonsoft.Json >= 6.0.4
   - Microsoft.AspNet.WebApi.Client >= 5.2.3
   - Microsoft.Net.Http >= 2.2.22
  Could not resolve package Microsoft.Bcl:
   - Microsoft.Net.Http 2.2.22 requested >= 1.1.9
   - Microsoft.Net.Http 2.2.22 requested >= 1.1.9
 Please try to relax some conditions.
```

It turned out to be the local cache.  Removing `source C:\Users\mkb137\AppData\Local\NuGet\Cache` fixed the problem, but the error message was mystifying.

**Comment by mkb137** [comment]
It also messed up my initial `convert-from-nuget`  If it's not just me, maybe mention clearing the cache in "getting started"?

**Comment by forki** [comment]
Mhm never heard about such issues. Strange

**Comment by forki** [comment]
do you have a way for me to reproduce this?

**Comment by mkb137** [comment]
No, I deleted the old cache and I haven't been able to reproduce it by messing around with the recreated cache.  If it happens again I'll compile paket.exe and do some logging.
