### ISSUE TITLE
Error when doing paket restore: Name cannot begin with the '.' character, hexadecimal value 0x2E. Line 20, position 17.

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#1126]
I am experiencing issues when building a solution on the CI server. Default targets fail on restore with the error below:

Paket version 2.11.1.0
Resolving packages for group Main:
 - Newtonsoft.Json is pinned to 7.0.1
 - ServiceStack is pinned to 4.0.46
 - ServiceStack.Client is pinned to 4.0.46
 - ServiceStack.Common is pinned to 4.0.46
 - ServiceStack.Interfaces is pinned to 4.0.46
 - ServiceStack.OrmLite is pinned to 4.0.46
 - ServiceStack.Text is pinned to 4.0.46
 - Autofac is pinned to 3.5.2
 - EventStore.Client is pinned to 3.2.1
 - Serilog is pinned to 1.5.11
 - Ix-Main is pinned to 1.2.5
 - EventStore.SerilogAdapter is pinned to 1.0.0
 - AggregateSource is pinned to 0.0.300
 - AggregateSource.EventStore is pinned to 0.0.300
 - Paramol is pinned to 0.0.125
 - Projac is pinned to 0.0.125
 - Nuget.CommandLine 2.8.6
Locked version resolution written to C:\Atlassian\Data\Bamboo\xml-data\build-dir
\AF-AES-JOB1\paket.lock
Paket failed with:
        Name cannot begin with the '.' character, hexadecimal value 0x2E. Line 20, position 17.

It is quite cryptic since it looks like an XML error but doesn't give a clue where to look.

**Comment by forki** [comment]
Can you please try to run it with "paket restore -v"?

**Comment by forki** [comment]
Also why is it using "paket update" or "paket install"? Usually you only
want to run "paket restore" on the CI.

Anyways please try -v

**Comment by forki** [comment]
closing since we have no repro
