### ISSUE TITLE
Is there a way to specify that I don't want any extra content from a package, just the dlls?

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/Paket#1128]
Whenever I update or restore the Coding4Fun.Toolkit.Controls package, I get a bunch of static files added to the project that then I always go and delete right after

**Comment by mrinaldi** [comment]
Have you tried specifying [`content: none`](http://fsprojects.github.io/Paket/nuget-dependencies.html#No-content-option)?

`nuget Coding4Fun.Toolkit.Controls content: none`

**Comment by ovatsus** [comment]
Tried both `nuget Coding4Fun.Toolkit.Controls 2.0.7 content: none` and `nuget Coding4Fun.Toolkit.Controls content: none 2.0.7` but it didn't work

**Comment by forki** [comment]
Content: none + paket update should work.
Is there a way for me to reproduce?

**Comment by ovatsus** [comment]
Repo that repros this issue is here: https://github.com/ovatsus/Apps

**Comment by forki** [comment]
source https://www.nuget.org/api/v2
    
    nuget Coding4Fun.Toolkit.Controls 2.0.7 content:none  
    nuget FSharp.Data prerelease
    nuget HereLaunchers
    nuget WPtoolkit content:none

+ `paket install` works for me. Notice that WPtoolkit was also bringing in content files.

**Comment by ovatsus** [comment]
Ah, sorry about that, it is working :/

**Comment by bentayloruk** [comment]
Thanks!  Just saved me from this [EventSource package](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource) spraying junk all over the place.
