### ISSUE TITLE
parser should detect missing comma between install settings

### ISSUE THREAD

**Issue by Thorium** [fsprojects/Paket#1129]
Paket is copying / creating extra files, from package's content -folder to project's root folder.
Is this really wanted behavior?

How to reproduce:
I create a new folder and add paket.bootstrapper.exe and this paket.dependencies to the folder:

	source https://www.nuget.org/api/v2

	nuget ABCpdf 10.1.0.3 framework: >= net40
	nuget log4net 2.0.0
	nuget Oracle.ManagedDataAccess framework: >= net40

Now, under that folder I create a new project called ConsoleApplication1. I also copy to this the project folder this file, paket.references:

	ABCpdf
	log4net
	Oracle.ManagedDataAccess

Then I run `paket.bootstrapper.exe` to get the latest version of paket.exe (in my case it was 2.12.0.0). Then I run `paket install`
What happens is that under my ConsoleApplication1 are new files of ABCpdf.chm (5 megabytes binary, not very happy to add this to git) and net40\*.xdt files.

**Comment by forki** [comment]
You can disable this with content:none option.

That said: what else would you suggest.

**Comment by Thorium** [comment]
So should this paket.dependencies help?

	source https://www.nuget.org/api/v2

	nuget ABCpdf 10.1.0.3 framework: >= net40 content: none
	nuget log4net 2.0.0
	nuget Oracle.ManagedDataAccess framework: >= net40 content: none

It doesn't...

**Comment by forki** [comment]
source https://www.nuget.org/api/v2
    
    nuget ABCpdf 10.1.0.3 framework: >= net40, content: none
    nuget log4net 2.0.0
    nuget Oracle.ManagedDataAccess framework: >= net40, content: none


works.

**Comment by forki** [comment]
I changed the title to reflect the bug in install settings

**Comment by Thorium** [comment]
Thanks!

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/10431880/f8e396a0-7107-11e5-9cd1-1ff08f8a6419.png)
