### ISSUE TITLE
Paket ignores framework tag and tries to resolve System.* libs

### ISSUE THREAD

**Issue by gpomykala** [fsprojects/Paket#1132]
Reproduced with FluentAssertions dependency:

references: strict
source https://www.nuget.org/api/v2/

nuget Autofac 3.5.2 framework: net45
nuget AutoFixture 3.36.1 framework: net45
nuget AutoFixture.AutoMoq 3.36.1 framework: net45
nuget FluentAssertions 4.0.0 framework: net40
nuget log4net 2.0.3 framework: net45 
nuget Moq >= 4.2 framework: net45
nuget Nancy 1.3.0 framework: net45
nuget Nancy.Bootstrappers.Autofac 1.3.0 framework: net45
nuget Nancy.Hosting.Self 1.3.0 framework: net45
nuget Newtonsoft.Json 6.0.4 framework: net45
nuget NUnit 2.6.4 framework: net45

Paket output:
> ".paket\paket.exe" install
Paket version 2.12.1.0
Resolving packages for group Main:
 - Newtonsoft.Json is pinned to 6.0.4
 - FluentAssertions is pinned to 4.0.0
 - AutoFixture is pinned to 3.36.1
 - AutoFixture.AutoMoq is pinned to 3.36.1
 - Autofac is pinned to 3.5.2
 - NUnit is pinned to 2.6.4
 - log4net is pinned to 2.0.3
 - Nancy is pinned to 1.3.0
 - Nancy.Bootstrappers.Autofac is pinned to 1.3.0
 - Nancy.Hosting.Self is pinned to 1.3.0
 - Moq 4.2.1502.0911
 - System.Runtime 4.0.20
 - System.Collections 4.0.10
 - System.Diagnostics.Debug 4.0.10
 - System.Globalization 4.0.10
 - System.Linq.Expressions 4.0.10
 - System.ObjectModel 4.0.10
 - System.Reflection 4.0.10
 - System.Runtime.Extensions 4.0.10
 - System.Text.RegularExpressions 4.0.10
 - System.Threading 4.0.10

FluentAssertions have no dependency for .net4.0 target. It seems like all dependencies for "unsupported" target are being resolved:

FluentAssertions NuSpec:

        <dependencies>
            <group targetFramework=".NETFramework4.0" />
            <group targetFramework="Silverlight5.0" />
            <group targetFramework="Windows8.0" />
            <group targetFramework="WindowsPhone8.0" />
            <group targetFramework="Unsupported0.0">
                <dependency id="System.Collections" version="4.0.10" />
                <dependency id="System.Diagnostics.Debug" version="4.0.10" />
                <dependency id="System.Globalization" version="4.0.10" />
                <dependency id="System.Linq" version="4.0.0" />
                <dependency id="System.Linq.Expressions" version="4.0.10" />
                <dependency id="System.ObjectModel" version="4.0.10" />
                <dependency id="System.Reflection" version="4.0.10" />
                <dependency id="System.Reflection.Extensions" version="4.0.0" />
                <dependency id="System.Reflection.Primitives" version="4.0.0" />
                <dependency id="System.Reflection.TypeExtensions" version="4.0.0" />
                <dependency id="System.Runtime" version="4.0.20" />
                <dependency id="System.Runtime.Extensions" version="4.0.10" />
                <dependency id="System.Text.RegularExpressions" version="4.0.10" />
                <dependency id="System.Threading" version="4.0.10" />
                <dependency id="System.Threading.Tasks" version="4.0.10" />
                <dependency id="System.Xml.XDocument" version="4.0.10" />
            </group>
            <group targetFramework="MonoTouch0.0" />
            <group targetFramework="MonoAndroid0.0" />
            <group targetFramework=".NETPortable0.0-net40+sl5+win8+wp8+wpa81" />
        </dependencies>

**Comment by forki** [comment]
with latest paket I get

    REFERENCES: STRICT
    NUGET
      remote: https://nuget.org/api/v2
      specs:
        Autofac (3.5.2) - framework: net45
        AutoFixture (3.36.1) - framework: net45
        AutoFixture.AutoMoq (3.36.1) - framework: net45
          AutoFixture (>= 3.36.1)
          Moq (>= 4.1.1308.2120)
        FluentAssertions (4.0.0) - framework: net40
        log4net (2.0.3) - framework: net45
        Moq (4.2.1507.118) - framework: net45
        Nancy (1.3.0) - framework: net45
        Nancy.Bootstrappers.Autofac (1.3.0) - framework: net45
          Autofac (>= 3.5.2)
          Nancy (>= 1.3.0)
        Nancy.Hosting.Self (1.3.0) - framework: net45
          Nancy (>= 1.3.0)
        Newtonsoft.Json (6.0.4) - framework: net45
        NUnit (2.6.4) - framework: net45


which looks ok to me?

**Comment by gpomykala** [comment]
With paket 2.12.1.0 i am getting:

REFERENCES: STRICT
NUGET
  remote: https://nuget.org/api/v2
  specs:
    Autofac (3.5.2) - framework: net45
    AutoFixture (3.36.1) - framework: net45
    AutoFixture.AutoMoq (3.36.1) - framework: net45
      AutoFixture (>= 3.36.1)
      Moq (>= 4.1.1308.2120)
    FluentAssertions (4.0.0) - framework: net40
      System.Collections (>= 4.0.10)
      System.Diagnostics.Debug (>= 4.0.10)
      System.Globalization (>= 4.0.10)
      System.Linq (>= 4.0.0)
      System.Linq.Expressions (>= 4.0.10)
      System.ObjectModel (>= 4.0.10)
      System.Reflection (>= 4.0.10)
      System.Reflection.Extensions (>= 4.0.0)
      System.Reflection.Primitives (>= 4.0.0)
      System.Reflection.TypeExtensions (>= 4.0.0)
      System.Runtime (>= 4.0.20)
      System.Runtime.Extensions (>= 4.0.10)
      System.Text.RegularExpressions (>= 4.0.10)
      System.Threading (>= 4.0.10)
      System.Threading.Tasks (>= 4.0.10)
      System.Xml.XDocument (>= 4.0.10)
    Moq (4.2.1507.118) - framework: net45
    Nancy (1.3.0) - framework: net45
    Nancy.Bootstrappers.Autofac (1.3.0) - framework: net45
      Autofac (>= 3.5.2)
      Nancy (>= 1.3.0)
    Nancy.Hosting.Self (1.3.0) - framework: net45
      Nancy (>= 1.3.0)
    System.Collections (4.0.10) - framework: net40
      System.Runtime (>= 4.0.0)
    System.Diagnostics.Debug (4.0.10) - framework: net40
      System.Runtime (>= 4.0.0)
    System.Globalization (4.0.10) - framework: net40
      System.Runtime (>= 4.0.0)
    System.IO (4.0.10) - framework: net40
      System.Runtime (>= 4.0.20)
      System.Text.Encoding (>= 4.0.0)
      System.Threading.Tasks (>= 4.0.0)
    System.IO.FileSystem (4.0.0) - framework: net40
      System.IO (>= 4.0.0)
      System.IO.FileSystem.Primitives (>= 4.0.0)
      System.Runtime (>= 4.0.0)
      System.Runtime.Handles (>= 4.0.0)
      System.Text.Encoding (>= 4.0.0)
      System.Threading.Tasks (>= 4.0.0)
    System.IO.FileSystem.Primitives (4.0.0) - framework: net40
      System.Runtime (>= 4.0.20)
    System.Linq (4.0.0) - framework: net40
      System.Collections (>= 4.0.10)
      System.Diagnostics.Debug (>= 4.0.10)
      System.Resources.ResourceManager (>= 4.0.0)
      System.Runtime (>= 4.0.20)
      System.Runtime.Extensions (>= 4.0.10)
    System.Linq.Expressions (4.0.10) - framework: net40
      System.Reflection (>= 4.0.0)
      System.Runtime (>= 4.0.0)
    System.ObjectModel (4.0.10) - framework: net40
      System.Collections (>= 4.0.10)
      System.Diagnostics.Debug (>= 4.0.10)
      System.Resources.ResourceManager (>= 4.0.0)
      System.Runtime (>= 4.0.20)
      System.Threading (>= 4.0.10)
    System.Reflection (4.0.10) - framework: net40
      System.IO (>= 4.0.0)
      System.Reflection.Primitives (>= 4.0.0)
      System.Runtime (>= 4.0.20)
    System.Reflection.Extensions (4.0.0) - framework: net40
      System.Reflection (>= 4.0.0)
      System.Runtime (>= 4.0.0)
    System.Reflection.Primitives (4.0.0) - framework: net40
      System.Runtime (>= 4.0.0)
    System.Reflection.TypeExtensions (4.0.0) - framework: net40
      System.Reflection (>= 4.0.0)
      System.Runtime (>= 4.0.0)
    System.Resources.ResourceManager (4.0.0) - framework: net40
      System.Globalization (>= 4.0.0)
      System.Reflection (>= 4.0.0)
      System.Runtime (>= 4.0.0)
    System.Runtime (4.0.20) - framework: net40
    System.Runtime.Extensions (4.0.10) - framework: net40
      System.Runtime (>= 4.0.20)
    System.Runtime.Handles (4.0.0) - framework: net40
      System.Runtime (>= 4.0.0)
    System.Runtime.InteropServices (4.0.20) - framework: net40
      System.Reflection (>= 4.0.0)
      System.Reflection.Primitives (>= 4.0.0)
      System.Runtime (>= 4.0.0)
      System.Runtime.Handles (>= 4.0.0)
    System.Text.Encoding (4.0.10) - framework: net40
      System.Runtime (>= 4.0.0)
    System.Text.Encoding.Extensions (4.0.10) - framework: net40
      System.Runtime (>= 4.0.0)
      System.Text.Encoding (>= 4.0.10)
    System.Text.RegularExpressions (4.0.10) - framework: net40
      System.Collections (>= 4.0.10)
      System.Globalization (>= 4.0.10)
      System.Resources.ResourceManager (>= 4.0.0)
      System.Runtime (>= 4.0.20)
      System.Runtime.Extensions (>= 4.0.10)
      System.Threading (>= 4.0.10)
    System.Threading (4.0.10) - framework: net40
      System.Runtime (>= 4.0.0)
      System.Threading.Tasks (>= 4.0.0)
    System.Threading.Tasks (4.0.10) - framework: net40
      System.Runtime (>= 4.0.0)
    System.Xml.ReaderWriter (4.0.10) - framework: net40
      System.Collections (>= 4.0.10)
      System.Diagnostics.Debug (>= 4.0.10)
      System.Globalization (>= 4.0.10)
      System.IO (>= 4.0.10)
      System.IO.FileSystem (>= 4.0.0)
      System.IO.FileSystem.Primitives (>= 4.0.0)
      System.Resources.ResourceManager (>= 4.0.0)
      System.Runtime (>= 4.0.20)
      System.Runtime.Extensions (>= 4.0.10)
      System.Runtime.InteropServices (>= 4.0.20)
      System.Text.Encoding (>= 4.0.10)
      System.Text.Encoding.Extensions (>= 4.0.10)
      System.Text.RegularExpressions (>= 4.0.10)
      System.Threading.Tasks (>= 4.0.10)
    System.Xml.XDocument (4.0.10) - framework: net40
      System.Collections (>= 4.0.10)
      System.Diagnostics.Debug (>= 4.0.10)
      System.Globalization (>= 4.0.10)
      System.IO (>= 4.0.10)
      System.Reflection (>= 4.0.10)
      System.Resources.ResourceManager (>= 4.0.0)
      System.Runtime (>= 4.0.20)
      System.Runtime.Extensions (>= 4.0.10)
      System.Text.Encoding (>= 4.0.10)
      System.Threading (>= 4.0.10)
      System.Xml.ReaderWriter (>= 4.0.10)

**Comment by forki** [comment]
can you please try to format this correctly? 4 spaces indent works with github.

**Comment by forki** [comment]
can you please try to format this correctly? 4 spaces indent works with github.
and is it still behaving like this if you do "paket update"?

**Comment by gpomykala** [comment]
Lock file attached
13 paź 2015 10:56 "Steffen Forkmann" <notifications@github.com> napisał(a):

**Comment by forki** [comment]
it's not working like that with github replies ;-)

 please send it to sforkmann @ gmail

2015-10-13 12:59 GMT+02:00 gpomykala <notifications@github.com>:

**Comment by gpomykala** [comment]
Email sent. Thanks

**Comment by gpomykala** [comment]
Hi, i found the root cause (one of the projects targeting .net 4.5.2 rather than 4.5 which falls into "unsupported" category in FluentAssertions NuSpec).

Feel free to close

**Comment by forki** [comment]
thx
