### ISSUE TITLE
Inconsistency when calling install and update affecting paket.lock

### ISSUE THREAD

**Issue by SavaNDragos** [fsprojects/Paket#1135]
This is similar to the old issue https://github.com/fsprojects/Paket/issues/810 .
The difference is that the issue is not happening in the csproj, it only happens in the paket lock file.

Paket lock gets modified if you run paket install and paket update (even if there was no updates). 

Paket install:
![initial](https://cloud.githubusercontent.com/assets/8431741/10481714/768b5922-726a-11e5-9afc-bf66506a0039.jpg) 

Paket update 3 seconds later:
 
![second](https://cloud.githubusercontent.com/assets/8431741/10481722/7e10068e-726a-11e5-96d2-6943bece0252.jpg)

**Comment by forki** [comment]
Can you please send me a dependencies + lock file? Sforkmann @ Gmail

**Comment by SavaNDragos** [comment]
Done.

**Comment by SavaNDragos** [comment]
I also added the example to https://github.com/SavaNDragos/Share. It is AAAAPaket.zip.
