### ISSUE TITLE
How to reference just a few assemblies from the package?

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1145]
NuGet package "IKVM" is weird - it carries long list of assemblies, so after it is referenced by the project Paket inserts this to the project file:
` ` `xml  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.2'">
      <ItemGroup>
        <Reference Include="IKVM.AWT.WinForms">
          <HintPath>..\packages\IKVM\lib\IKVM.AWT.WinForms.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="IKVM.OpenJDK.Beans">
          <HintPath>..\packages\IKVM\lib\IKVM.OpenJDK.Beans.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
` ` `

Is there the way to limit it to just a few assemblies we really need and get rid of many those we don't need?

Kosnstantin

**Comment by forki** [comment]
Not as today. Please propose a syntax that can be used in dependencies and references files

**Comment by konste** [comment]
This case is rather unusual and I'm not sure it deserves special Paket feature to deal with it. I was thinking towards one off workaround, like manually remove unneeded references from the project file and tell Paket to leave it alone. 
What confuses me is that <Paket>True</Paket> attribute is on each assembly reference, but not on the package level. How to skip unneeded references even with manual editing of the project file?

**Comment by forki** [comment]
Just set any of the paket nodes to false and it will ignore it.

But your request is not unusual. Heard it twice this week.

**Comment by konste** [comment]
No changes needed in dependencies file. It is about which version of package to select and it should not care if some projects only reference parts of the package. And different projects may be interested in different parts. So as far as I can see only references file needs a way to filter package assemblies. I will think about the syntax.

**Comment by konste** [comment]
Filtering of the package references would be rather fragile feature, because users make assumptions about internal structure of the package. What if in the next version they package the content between assemblies differently?
But anyway, if there is demand, should be supply. Syntax better be consistent with the other currently existing options, so I see it like this:
assemblies:assem1,assem2,assem3
If this element is present, only listed assemblies from the package get added to the project.
I think it should be that simple, until there is demand for something more complex, which I doubt.

**Comment by forki** [comment]
implemented in v3
