### ISSUE TITLE
Paket Update - Json File Location

### ISSUE THREAD

**Issue by jpalomo** [fsprojects/Paket#1147]
So we currently use Paket(specifically "update") in our build process for our nupkg dependency management and have run in to a couple of different issues that we have been able to solve up until now.  When we build a job on our CI server, we always want to make sure that we isolate the builds as best we can and Paket naturally supports this by downloading the packages from our internal repo and unpackaging them to the packages folder.  

We started using the --force option to ensure that previous builds that may have failed in downloading an artifact (json.failed file created) would not prevent a later build from failing if it tried to retrieve the same package.  Before using --force we had to manually delete the json.failed file to ensure Paket would go out to our repo, download, and unpackage.  However, since the json files are being stored in the NuGet cache and this is shared by all Paket processes, we sometimes run into issues when we have more than one Paket process running that are trying to download the same package.

If Job-A goes and downloads p1 and Job-B goes out and downloads p1, they both try to modify(I think it actually deletes the json file before recreating it), then JobA usually fails saying it can't find p1.  

It would be nice to have some support to control where those files are downloaded, possibly override the cache location as command line argument by which Paket downloads the packages to (instead of NuGet cache specified in NuGet.config).

**Comment by forki** [comment]
would https://github.com/fsprojects/Paket/pull/1158 help here?

**Comment by jpalomo** [comment]
@forki thanks for the reply.  I'm thinking that it won't help with our situation.  However, I think I might have been mistaken about the JSON file (not entirely sure though).  Maybe I can rephrase my problem.  

Say I have two build jobs (C# projects),  J1 and J2 that have NUnit as a dependency.  Also, say I am using the **paket update --force** command to resolve the project dependencies.  What happens, is that both J1 and J2 write their html, json, and nupkg files to the _C:/Users/someuser/AppData/Local/Nuget/Cache/_ directory.  The problem occurs if both jobs run simultaneously and one job begins unpackaging Nunit to the local packages directory while the other job tries to overwrite the nupkg (html and json, too) in the cache directory.

In this case, it would be nice if we could specify a local cache directory for Paket to use instead of the default NuGet cache directory in the AppData location.  So a command like **paket update --force --cachedir "C:\J1\cache** would download all files to the directory specified and unpackage from their into the local packages folder.   

I hope that helps.  I am trying to brush up on F# and see if I can find where I need to make the change, but time is hard to come by.  If you or someone else sees this as being a valuable enhancement, then hopefully we can get someone to contribute, if not, I will try in the near future.  Either way, it would be great to just be able to track something like this.  Thanks again!

**Comment by forki** [comment]
I guess making the cache folder confirgurable won't hurt.

**Comment by forki** [comment]
I think it will be pretty easy task.

* Check for cachedir param like https://github.com/fsprojects/Paket/blob/master/src/Paket/Program.fs#L21
* default that parameter to current nuget cachefolder
* somehow replace the new folder in https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NuGetV2.fs#L240

**Comment by jpalomo** [comment]
thanks!!  I will take a look at this.  appreciate your help.

**Comment by forki** [comment]
we have additional caches in v3
