### ISSUE TITLE
Build error on Linux

### ISSUE THREAD

**Issue by jrimclean** [fsprojects/Paket#1156]
$ ./build.sh 
Prerelease requested. Looking for latest prerelease.
'Github' download failed. Try fallback download from 'Nuget'.
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure (Nuget)
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure (Github)

**Comment by forki** [comment]
Do you have restrictive proxy settings?

**Comment by jrimclean** [comment]
Nope, no proxy at all.

**Comment by forki** [comment]
The strange thing is the bootstrapper can't download from github.com and
also fails on the nuget.org fallback. Maybe some firewall blocking?

**Comment by jrimclean** [comment]
My firewall only blocks incoming by default (I'm using UFW), same with my router firewall. It's very strange.

**Comment by jrimclean** [comment]
Figured it out. I needed to run: mozroots --sync --import

Thanks for your help!

**Comment by jrimclean** [comment]
Note: the build still fails, but for different reasons. I get a terminal filed with a bunch of garbled binary symbols followed by "Message: The requested feature is not implemented." Perhaps this is a Mono library problem?

**Comment by forki** [comment]
Yes sounds like you want to upgrade your mono
