### ISSUE TITLE
slowww update with myget dotnet-core

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#1157]
I'm trying out a [raw CoreClr tutorial](https://github.com/dotnet/coreclr/blob/master/Documentation/install/get-dotnetcore-windows.md), but with paket instead of nuget. `paket update` has screeched to a halt with either the latest release and prerelease version of Paket. Here is the file I am trying to restore. there is no proj file.

```
source https://www.myget.org/F/dotnet-core/

nuget System.Console
nuget System.Diagnostics.Contracts
nuget System.Diagnostics.Debug
nuget System.Diagnostics.Tools
nuget System.Globalization
nuget System.IO
nuget System.IO.FileSystem.Primitives
nuget System.Reflection
nuget System.Runtime
nuget System.Runtime.Extensions
nuget System.Runtime.InteropServices
nuget System.Text.Encoding
nuget System.Text.Encoding.Extensions
nuget System.Threading
nuget System.Threading.Tasks
nuget Microsoft.NETCore.Runtime.CoreCLR.ConsoleHost-x64
nuget Microsoft.NETCore.Runtime.CoreCLR-x64
```

**Comment by forki** [comment]
from first look I would say there are lots of conflicts going on and paket's current heuristic has a hard time to find a valid resolution. (If it runs that long then often this means there is no valid resolution)

what's strange is that there only prereleaseses listed. Is this expected?

If I add nuget as a source then it takes only 1 minute for `paket update -f`

so please add 

    source https://nuget.org/api/v2

**Comment by forki** [comment]
source https://www.myget.org/F/dotnet-core/
    source https://nuget.org/api/v2
    
    nuget System.Console prerelease
    nuget System.Diagnostics.Contracts prerelease
    nuget System.Diagnostics.Debug prerelease
    nuget System.Diagnostics.Tools prerelease
    nuget System.Globalization prerelease
    nuget System.IO prerelease
    nuget System.IO.FileSystem.Primitives prerelease
    nuget System.Reflection prerelease
    nuget System.Runtime prerelease
    nuget System.Runtime.Extensions prerelease
    nuget System.Runtime.InteropServices prerelease
    nuget System.Text.Encoding prerelease
    nuget System.Text.Encoding.Extensions prerelease
    nuget System.Threading prerelease
    nuget System.Threading.Tasks prerelease
    nuget Microsoft.NETCore.Runtime.CoreCLR.ConsoleHost-x64 prerelease
    nuget Microsoft.NETCore.Runtime.CoreCLR-x64 prerelease

gives in just about 1 minute

    NUGET
      remote: https://www.myget.org/F/dotnet-core
      specs:
        Microsoft.NETCore.Runtime.CoreCLR.ConsoleHost-x64 (1.0.0-beta-22914)
        System.Console (4.0.0-beta-23409)
          System.IO (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.IO.FileSystem.Primitives (4.0.1-beta-23409)
          System.Runtime (>= 4.0.20) - framework: dnxcore50
        System.Linq (4.0.1-beta-23420) - framework: dnxcore50
          System.Collections (>= 4.0.0)
          System.Collections (>= 4.0.10)
          System.Diagnostics.Debug (>= 4.0.10)
          System.Resources.ResourceManager (>= 4.0.0)
          System.Runtime (>= 4.0.0)
          System.Runtime (>= 4.0.20)
          System.Runtime.Extensions (>= 4.0.10)
        System.Reflection.TypeExtensions (4.0.1-beta-23409) - framework: dnxcore50
          System.Diagnostics.Contracts (>= 4.0.0) - framework: dnxcore50
          System.Diagnostics.Debug (>= 4.0.10) - framework: dnxcore50
          System.Linq (>= 4.0.0) - framework: dnxcore50
          System.Reflection (>= 4.0.0) - framework: dnxcore50
          System.Reflection (>= 4.0.10) - framework: dnxcore50
          System.Reflection.Primitives (>= 4.0.0) - framework: dnxcore50
          System.Resources.ResourceManager (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.20) - framework: dnxcore50
          System.Runtime.Extensions (>= 4.0.10) - framework: dnxcore50
      remote: https://nuget.org/api/v2
      specs:
        Microsoft.NETCore.Runtime.CoreCLR-x64 (1.0.1-beta-23225)
          System.Collections (4.0.11-beta-23225)
          System.Diagnostics.Contracts (4.0.1-beta-23225)
          System.Diagnostics.Debug (4.0.11-beta-23225)
          System.Diagnostics.StackTrace (4.0.1-beta-23225)
          System.Diagnostics.Tools (4.0.1-beta-23225)
          System.Diagnostics.Tracing (4.0.21-beta-23225)
          System.Globalization (4.0.11-beta-23225)
          System.Globalization.Calendars (4.0.1-beta-23225)
          System.IO (4.0.11-beta-23225)
          System.ObjectModel (4.0.11-beta-23225)
          System.Private.Uri (4.0.1-beta-23225)
          System.Reflection (4.1.0-beta-23225)
          System.Reflection.Extensions (4.0.1-beta-23225)
          System.Reflection.Primitives (4.0.1-beta-23225)
          System.Resources.ResourceManager (4.0.1-beta-23225)
          System.Runtime (4.0.21-beta-23225)
          System.Runtime.Extensions (4.0.11-beta-23225)
          System.Runtime.Handles (4.0.1-beta-23225)
          System.Runtime.InteropServices (4.0.21-beta-23225)
          System.Text.Encoding (4.0.11-beta-23225)
          System.Text.Encoding.Extensions (4.0.11-beta-23225)
          System.Threading (4.0.11-beta-23225)
          System.Threading.Tasks (4.0.11-beta-23225)
          System.Threading.Timer (4.0.1-beta-23225)
        System.Collections (4.0.11-beta-23225)
          System.Diagnostics.Debug (>= 4.0.0) - framework: dnxcore50
          System.Resources.ResourceManager (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.21-beta-23225) - framework: dnxcore50
          System.Runtime.Extensions (>= 4.0.0) - framework: dnxcore50
          System.Threading (>= 4.0.0) - framework: dnxcore50
        System.Diagnostics.Contracts (4.0.1-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.Diagnostics.Debug (4.0.11-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.Diagnostics.StackTrace (4.0.1-beta-23225)
          System.Reflection (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.21-beta-23225) - framework: dnxcore50
        System.Diagnostics.Tools (4.0.1-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.Diagnostics.Tracing (4.0.21-beta-23225)
          System.Collections (>= 4.0.10) - framework: dnxcore50
          System.Diagnostics.Contracts (>= 4.0.0) - framework: dnxcore50
          System.Globalization (>= 4.0.0) - framework: dnxcore50
          System.Reflection (>= 4.0.10) - framework: dnxcore50
          System.Reflection.Extensions (>= 4.0.0) - framework: dnxcore50
          System.Resources.ResourceManager (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.20) - framework: dnxcore50
          System.Runtime.Extensions (>= 4.0.10) - framework: dnxcore50
          System.Runtime.InteropServices (>= 4.0.0) - framework: dnxcore50
          System.Text.Encoding (>= 4.0.0) - framework: dnxcore50
          System.Threading (>= 4.0.10) - framework: dnxcore50
        System.Globalization (4.0.11-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.Globalization.Calendars (4.0.1-beta-23225)
          System.Globalization (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.IO (4.0.11-beta-23225)
          System.Globalization (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.20) - framework: dnxcore50
          System.Text.Encoding (>= 4.0.0) - framework: dnxcore50
          System.Text.Encoding (>= 4.0.10) - framework: dnxcore50
          System.Text.Encoding.Extensions (>= 4.0.0) - framework: dnxcore50
          System.Threading (>= 4.0.0) - framework: dnxcore50
          System.Threading.Tasks (>= 4.0.0) - framework: dnxcore50
        System.ObjectModel (4.0.11-beta-23225)
          System.Collections (>= 4.0.10) - framework: dnxcore50
          System.Diagnostics.Debug (>= 4.0.10) - framework: dnxcore50
          System.Resources.ResourceManager (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.20) - framework: dnxcore50
          System.Threading (>= 4.0.10) - framework: dnxcore50
        System.Private.Uri (4.0.1-beta-23225)
        System.Reflection (4.1.0-beta-23225)
          System.IO (>= 4.0.0) - framework: dnxcore50
          System.Reflection.Primitives (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.20) - framework: dnxcore50
        System.Reflection.Extensions (4.0.1-beta-23225)
          System.Diagnostics.Debug (>= 4.0.10) - framework: dnxcore50
          System.Reflection (>= 4.0.0) - framework: dnxcore50
          System.Reflection (>= 4.0.10) - framework: dnxcore50
          System.Reflection.Primitives (>= 4.0.0) - framework: dnxcore50
          System.Reflection.TypeExtensions (>= 4.0.1-beta-23225) - framework: dnxcore50
          System.Resources.ResourceManager (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.20) - framework: dnxcore50
          System.Runtime.Extensions (>= 4.0.10) - framework: dnxcore50
        System.Reflection.Primitives (4.0.1-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Threading (>= 4.0.0) - framework: dnxcore50
        System.Resources.ResourceManager (4.0.1-beta-23225)
          System.Globalization (>= 4.0.0) - framework: dnxcore50
          System.Reflection (>= 4.0.0) - framework: dnxcore50
          System.Reflection (>= 4.0.10) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.20) - framework: dnxcore50
        System.Runtime (4.0.21-beta-23225)
          System.Private.Uri (>= 4.0.1-beta-23225) - framework: dnxcore50
        System.Runtime.Extensions (4.0.11-beta-23225)
          System.Runtime (>= 4.0.20) - framework: dnxcore50
        System.Runtime.Handles (4.0.1-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.Runtime.InteropServices (4.0.21-beta-23225)
          System.Reflection (>= 4.0.0) - framework: dnxcore50
          System.Reflection.Primitives (>= 4.0.0) - framework: dnxcore50
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Runtime.Handles (>= 4.0.0) - framework: dnxcore50
        System.Text.Encoding (4.0.11-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.Text.Encoding.Extensions (4.0.11-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Text.Encoding (>= 4.0.10) - framework: dnxcore50
        System.Threading (4.0.11-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
          System.Threading.Tasks (>= 4.0.0) - framework: dnxcore50
        System.Threading.Tasks (4.0.11-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50
        System.Threading.Timer (4.0.1-beta-23225)
          System.Runtime (>= 4.0.0) - framework: dnxcore50


so I think the original dependencies file is just not valid.

**Comment by ctaggart** [comment]
Awesome! Makes sense.

**Comment by forki** [comment]
just to clarify: It wasn't stuck in endless loop or something like that. It
was still looking for a resolution and tries out all combinations.
But usually our heuristic guides the process to a fast resolution.

2015-10-21 17:40 GMT+02:00 Cameron Taggart <notifications@github.com>:

**Comment by forki** [comment]
@ctaggart are you looking into ".Nuget resolver" from https://github.com/Microsoft/visualfsharp/wiki/F%23-for-CoreCLR---Status? ;-)

**Comment by ctaggart** [comment]
Updating dependencies is an extremely time consuming, manual process when using `nuget` or `dnu`. Paket looks like a better option. I may post a blog if I get the basics working.

But really, I haven't been able to get the F# coreclr branch tests to build and run. https://github.com/Microsoft/visualfsharp/pull/687#issuecomment-149457251 I need to understand coreclr a bit better. I'm seeing if I can get the basic C# stuff working.

**Comment by forki** [comment]
The really annoying thing is that they seem to bake nuget into the framework.

**Comment by forki** [comment]
Anyways if you see a way  to make paket work for coreclr projects then please create an issue and list the steps/changes that we need to do.

**Comment by ctaggart** [comment]
It does appear that way at first and especially from Visual Studio. When you look at the low level, it looks very well designed and decoupled. `dnx` is just a host, like `CoreRun` is. `CoreRun` tries to load everything from the same folder in the classic and familiar way. It is what the F# compiler is using for testing. `project.json` is specific to `dnx` and `dnu` from the asp.net team. I think there is room for a host that loads stuff in the Paket folder structure. I'll open up a ticket after I know more.

**Comment by ctaggart** [comment]
My notes:

### CoreCLR CoreRun Host
`CoreRun` is packages in `TestHost`
"C:\fs\visualfsharp\packages\runtime.win7-x64.Microsoft.NETCore.TestHost\1.0.0-beta-23321\runtimes\win7-x64\native\CoreRun.exe"

https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts
https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/corerun/corerun.cpp

### ASP.NET DNX Host
https://github.com/aspnet/dnx/blob/dev/src/dnx/dnx.cpp
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.ApplicationHost/DefaultHost.cs

**Comment by forki** [comment]
btw: latest paket alpha reduced update time for the sample below from 1min12s to 21s.

    source https://www.myget.org/F/dotnet-core/
    source https://nuget.org/api/v2
    
    nuget System.Console prerelease
    nuget System.Diagnostics.Contracts prerelease
    nuget System.Diagnostics.Debug prerelease
    nuget System.Diagnostics.Tools prerelease
    nuget System.Globalization prerelease
    nuget System.IO prerelease
    nuget System.IO.FileSystem.Primitives prerelease
    nuget System.Reflection prerelease
    nuget System.Runtime prerelease
    nuget System.Runtime.Extensions prerelease
    nuget System.Runtime.InteropServices prerelease
    nuget System.Text.Encoding prerelease
    nuget System.Text.Encoding.Extensions prerelease
    nuget System.Threading prerelease
    nuget System.Threading.Tasks prerelease
    nuget Microsoft.NETCore.Runtime.CoreCLR.ConsoleHost-x64 prerelease
    nuget Microsoft.NETCore.Runtime.CoreCLR-x64 prerelease
