### ISSUE TITLE
convert-from-nuget takes hours to complete

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#1167]
I am trying to use convert-from-nuget with paket 2.7 on a small project and it takes hours to complete. I left it for the night and there was an issue that prevented conversion, I tried again at 8:00 today and now it is 12:45 and it is still running. It takes about 45 minutes to process one package.

**Comment by alexeyzimarev** [comment]
It is actually not convert but install and only install of pinned versions

**Comment by forki** [comment]
do you have a dependencies file for me?
if you have more than nuget feed: can you please downgrade to 2.16 and retry?

**Comment by alexeyzimarev** [comment]
I need to reproduce this again since I removed version constraints and it worked fine after that. Will try.

**Comment by forki** [comment]
Oh that sounds like yet another instance of
https://github.com/fsprojects/Paket/issues/1166

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/issues/1166#issuecomment-151562264

**Comment by alexeyzimarev** [comment]
Yesterday I had the same problem with 2.28 and FAKE as the only package in packages.config. It took about 1.5 hours to complete the emigration of a solution with one project, three cs files and one package.

Currently, I am doing paket install on this solution and I tried 2.22 and 2.28 with the same result, it gets stuck on 

Paket version 2.22.0.0
Resolving packages for group Main:
 - FAKE 4.9.3

Already waiting for 10 minutes
