### ISSUE TITLE
Check conflict boosting for specific case

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1169]
consider the following dependencies file (taken from #1166)

    nuget FSharp.Formatting
    nuget Microsoft.AspNet.SignalR.Core
    nuget Microsoft.AspNet.SignalR.JS
    nuget Microsoft.Owin.Hosting
    nuget Microsoft.Owin.Security.Cookies
    nuget Nancy 1.2.0
    nuget Nancy.MSOwinSecurity
    nuget NUnit 
    nuget NUnit.Runners
    nuget FAKE
    nuget SourceLink.Fake

and then add 

    .paket/paket.exe add nuget Nancy.Serialization.JsonNet

this resolves but takes a long time because the confilct booster doesn't work.

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/1170 resolves this very fast. Most of the time goes for actual download of the packages.

![image](https://cloud.githubusercontent.com/assets/57396/10768348/e3aa65ae-7ce0-11e5-88bd-d0980612d3ec.png)

**Comment by TheAngryByrd** [comment]
Nice!

**Comment by mrinaldi** [comment]
Awesome! Nice job!
