### ISSUE TITLE
Strange behaviour on HTTP dependency

### ISSUE THREAD

**Issue by inventti-pedro** [fsprojects/Paket#1173]
Having downloaded paket.exe only, and creating the paket.dependencies file with content:
```
http http://189.45.195.210/FAKE.zip ..\..\build\FAKE\FAKE.zip
```
The output of the `paket install` execution: 
![Paket install output](http://s3.postimg.org/eb63kok1v/problem.png)

Where did this `:` came from?

**Comment by forki** [comment]
What do you mean?

**Comment by inventti-pedro** [comment]
Downloading 189.45.195.210/:/varejo/NW.7z, it ends up creating a empty file.

But it was related to the firewall restrictions on the build machine.
