### ISSUE TITLE
Regression in framework filtering

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1182]
paket.dependencies is shared here: http://1drv.ms/1Rjae7E 

The following are the differences after "paket update -f"
Looks like regression to me. Or is it deliberately done?

Konstantin

![2015-10-30 17_39_34-diff - paket lock - microsoft visual studio](https://cloud.githubusercontent.com/assets/2653844/10860883/5800aec4-7f2d-11e5-80ea-892173e572ad.png)
![2015-10-30 17_40_14-diff - paket lock - microsoft visual studio](https://cloud.githubusercontent.com/assets/2653844/10860884/580377b2-7f2d-11e5-861d-75db8c84d134.png)

**Comment by forki** [comment]
can you also give me the old lock file?

**Comment by konste** [comment]
Thank you! 

Will updated build appear shortly?

**Comment by forki** [comment]
yes I hope so. Still fixing regression tests ;-)
my first shot broke some of the regression tests

**Comment by forki** [comment]
done. please give it a try

**Comment by konste** [comment]
Wow you are fast!

It is good!
