### ISSUE TITLE
If I have a paket.template of type file, can/does paket still infer the version of any dependent packages?

### ISSUE THREAD

**Issue by kurtschelfthout** [fsprojects/Paket#1183]
I used to have a @dependencies tag in my nuspec template, and then the FAKE build script filled in the right dependency versions based on the installed packages. Paket  Pack only seems to have CURRENTVERSION, but I need something like DEPENDENCYVERSION or some such. 

Does this exist? Sorry if I completely overlooked it.

Thanks.

**Comment by forki** [comment]
So you need something like LOCKFILEVERSION?

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/1184 should allow you to use `LOCKEDVERSION` as placeholder

**Comment by kurtschelfthout** [comment]
Yes.

**Comment by kurtschelfthout** [comment]
Brilliant, works great. Thanks!
