### ISSUE TITLE
Problem with version conflict during paket update

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/Paket#1186]
I've found the following problem: I'm having *paket.dependencies* with two sources within, one for getting the latest nigthly versions and the second one for usual third-party nuget packages. All looks like this:

```
source https://www.myget.org/F/akkadotnet/api/v2
source https://www.nuget.org/api/v2/

nuget Nuget.CommandLine
nuget Akka 
nuget Akka.Persistence 
nuget Akka.Persistence.Sql.Common 
nuget Akka.Persistence.TestKit 
nuget Akka.TestKit 
nuget Akka.TestKit.Xunit2 
nuget Google.ProtocolBuffers 
nuget Newtonsoft.Json >= 7.0.1 
nuget xunit >= 2.0.0 
nuget xunit.abstractions >= 2.0.0 
nuget xunit.assert >= 2.0.0 
nuget xunit.core >= 2.0.0 
nuget xunit.extensibility.core >= 2.0.0
```

However when I'm running `paket update`, I'm getting following problem:

```
.\.paket\paket.exe : Paket failed with:
At line:1 char:1
+ .\.paket\paket.exe update
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Paket failed with::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

    There was a version conflict during package resolution.
  Resolved packages:
   - Akka 1.0.4
   - Akka.Persistence.Sql.Common 1.0.5.90-beta
   - Akka.Persistence.TestKit 1.0.2.9-beta
   - Akka.TestKit 0.7.0
   - Akka.TestKit.Xuni
t2 1.0.2
   - Newtonsoft.Json 7.0.1
   - xunit 2.1.0
   - xunit.abstractions 2.0.0
   - xunit.assert 2.1.0
   - xunit.core 2.1.0
   - xunit.extensibility.core 2.1.0
  Could not resolve package Akka.TestKit:
   - Dependencies file requested: 
   - Akka.TestKit.Xunit2 1.0.2 requested: >= 1.0.2

  Please try to relax some conditions.
```

Paket version number is 2.21.0.0

**Comment by forki** [comment]
Looks like an edge case in the conflict detection. Will try to reproduce / fix tomorrow. 
If it's urgent then downgrading paket a couple of minor versions might help. 

/cc @mrinaldi

**Comment by forki** [comment]
this is a strange case.

I assume it has something to do with prereleases. The following dependencies file works.


    source https://www.myget.org/F/akkadotnet/api/v2
    source https://www.nuget.org/api/v2/
    
    nuget Nuget.CommandLine
    nuget Akka prerelease          
    nuget Akka.Persistence prerelease 
    nuget Akka.Persistence.Sql.Common prerelease 
    nuget Akka.Persistence.TestKit prerelease  
    nuget Akka.TestKit prerelease  
    nuget Akka.TestKit.Xunit2 prerelease  
    nuget Google.ProtocolBuffers 
    nuget Newtonsoft.Json >= 7.0.1 
    nuget xunit >= 2.0.0 
    nuget xunit.abstractions >= 2.0.0 
    nuget xunit.assert >= 2.0.0 
    nuget xunit.core >= 2.0.0 
    nuget xunit.extensibility.core >= 2.0.0

but I assume this is not what you want, right?

**Comment by forki** [comment]
mhm. very strange. now your sample resolves for me. did you push something?
