### ISSUE TITLE
Temporarily overwrite a nuget package with a local version

### ISSUE THREAD

**Issue by dotboris** [fsprojects/Paket#1188]
I'd like to ask for a feature to be added to Paket that would allow me to overwrite a package that is normally hosted on a nuget feed with a project or nuget package on my local file system. The overwrite is meant to be a temporary thing for development purposes.

Let me explain in a little more detail:

Imagine that you have a two projects. Let's call these `Acme.Utils` and `Acme.NeatApp`. They're both stored in different repositories and both are packaged as nuget packages. In this example, `Acme.NeatApp` depends on `Acme.Utils`.

In most cases, the two packages are perfectly fine existing as their own nuget pacakges. In some rarer instances a developer needs to work both libs at the same time. To give a concrete example, let's say that the dev needs to work on `Acme.Utils` and test the changes in `Acme.NeatApp`.

To do this with the usual nuget setup with paket, we would have to make a change to `Acme.Utils`, build and push a package (probably overwriting an older version) and finally run `paket restore` on `Acme.NeatApp`.

This is a pretty slow and messy way of working.

One way of doing this with paket is to edit `paket.dependencies` and set the source of the package as the directory where it's built. This is not as bad as the previous method but there are still some things that could be better.

We still have to build the `Acme.Utils` package and we also have to run `paket restore` on `Acme.NeatApp`. Another problem with this approach is that it messes with the `paket.dependencies` and `paket.lock` files. This is a problem for two reasons, if you make commits you need to be sure to avoid committing both of those files. Also, if when you're done you need to restore both of these files to their original state.

There's another thing that might make this very annoying. I'm not familiar enough with nuget to be sure, but it's possible that if a nuget package is already installed for a certain version, paket or nuget won't install again. In such a case, you'd have to delete the old package files first.

What I want is something that can reduce the time it takes between making a change in `Acme.Utils` and seeing its results in `Acme.NeatApp`.

To give you a better idea of what I mean, you can look at:
- Bundler's similar feature http://bundler.io/v1.10/bundle_config.html#local_git_repos
- Bower's link command http://bower.io/docs/api/#link

My needs only cover nuget packages, but I'm sure this can be applied to http and github dependencies.

**Comment by isaacabraham** [comment]
Sorry if I've misunderstood - but can't you just add a local folder as a source of nuget packages (I do this all the time), which you've set your project to copy your nuget package to. You can force a re-download when doing a restore or install so even if the version number is the same as what you already have installed, you'll get the latest version.

**Comment by beraboris** [comment]
You're right. I could do that, but I find it too many steps to do something simple. In my previous example, I would have to do:

1. Build `Acme.Utils`
1. Package `Acme.Utils`
1. Force restore/reinstall `Acme.Utils` in `Acme.NeatApp`
1. Rebuild `Acme.NeatApp` (not sure if this is required actually)
1. Run `Acme.NeatApp`

It'd be much easier if I could tell Paket: "Just pretend that the `Acme.Utils` nuget package is actually this directory over there" and it would do all of that for me.

**Comment by 7sharp9** [comment]
This would be nice, I regularly find myself having to patch something locally while I work out a fix for the github repo the nuget is from.  Rust package manager cargo has a [nice solution][1] for this.  

Although I realise  that .Nets nuget if father fumbled and broken package manager for anything more than simplistic :-(

[1]:http://doc.crates.io/guide.html#overriding-dependencies

**Comment by forki** [comment]
But as far as I understand that these are build system changes and only
small package manager changes

**Comment by forki** [comment]
Would we only swap nuget packages? Or do you suggest to reference the
source code in the combined project?

**Comment by 7sharp9** [comment]
I think swapping the nuget package for a local one is a good start.  Thats if you can generate them locally.  

I often find that nuget wont create packages due to all the windows centric paths and issue etc.  My most common use case is FCS where I find a bug that I patch locally, but because I cant generate a nuget package I have to switch to direct dll references and remove the paket references.  It really is a shame that .Net doesn't have a well though out package system like almost all other languages.  Um glad we have paket to at least remove some of the pain.

**Comment by forki** [comment]
Mhm good point. As I see it: switching packages would be relatively easy.
Switching package against project is nearly impossible with csproj and
fsproj.

Regarding FCS. We should use FAKE + paket to create the nupkg. That process
should be xplat

**Comment by 7sharp9** [comment]
Yep, FCS needs some work to be able to do x-plat releases.  Ive only ever succeeded on Windows.

**Comment by forki** [comment]
Please create an issue and set me cc there. Maybe I find some time over the
weekend

**Comment by dungpa** [comment]
@7sharp9 You can use FCS AppVeyor CI as NuGet source; the infrastructure has been in place. Just send a PR with changes to FCS repo and swap out NuGet feed. You can use your changes without any issue (see http://blog.ctaggart.com/2015/07/open-source-net-with-appveyor-nuget.html).

**Comment by matthid** [comment]
I think `paket.local` solves this?
