### ISSUE TITLE
Missing transitive dependencies after paket update

### ISSUE THREAD

**Issue by neoeinstein** [fsprojects/Paket#1190]
Reproduction case:
1. Create a new project targeting .NET 4.5.
2. Run `paket.exe add nuget xunit project myproject.tests`
3. Note that `xunit.abstractions` is not in the list of references

This can also be reproduced by taking an existing project with current xunit references and then running a `paket update`.

The relevant diff after performing an update in one of my own projects:
```diff
--- i/paket.lock
+++ w/paket.lock
@@ -134,7 +134,7 @@ NUGET
     xunit (2.1.0)
       xunit.assert (2.1.0)
       xunit.core (2.1.0)
-    xunit.abstractions (2.0.0) - framework: dnx451, dnxcore50, monoandroid, monotouch, xamarinios, winv4.5, wpv8.0, >= net45
+    xunit.abstractions (2.0.0) - framework: dnxcore50
     xunit.assert (2.1.0)
       System.Collections (>= 4.0.0) - framework: dnxcore50
       System.Diagnostics.Debug (>= 4.0.0) - framework: dnxcore50
```

I've determined that the issue was introduced in 2.19.0. The issue was not present in 2.18.0. Likely PR (unconfirmed) was #1174.

**Comment by neoeinstein** [comment]
cc: @kolektiv

**Comment by forki** [comment]
Cc @mrinaldi

**Comment by forki** [comment]
I can reproduce and the error and I understand the issue. hope to provide a fix soon.

**Comment by forki** [comment]
Please retry with latest

**Comment by kolektiv** [comment]
Just tried the paket update repro and that now doesn't cause a problem. It does change the dependency slightly, but only by a slight *expansion* of the supported frameworks. A quick glance at xunit and the dependency tree makes me think it's right, which means that if anything I'm guessing this is slightly *more* correct than before! For the case we discovered this on, it is certainly no longer broken :)

Fantastic work, thanks @forki - and @neoeinstein for tracking it down and reporting!
