### ISSUE TITLE
What are the rules for paket making dependencies private with hintpath?

### ISSUE THREAD

**Issue by leojh** [fsprojects/Paket#1191]
I am having an issue when referencing ```RazorGenerator.Testing v.2.3.4``` using paket. It's declaring its sub dependencies (```System.Web.Mvc``` and  ```System.Web.WebPages```) without setting ```private``` or the ```hintpath``` in the .csproj file, as follows: 

```xml
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6')">
      <ItemGroup>
        <Reference Include="RazorGenerator.Testing">
          <HintPath>..\..\packages\RazorGenerator.Testing\lib\net40\RazorGenerator.Testing.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="System.Web.Mvc">
          <Paket>True</Paket>
        </Reference>
        <Reference Include="System.Web.WebPages">
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

This, in turn, is causing my project build to fail because of DLL ambiguities with the GAC. Ideally, I would like to tell paket to make the references with ```private``` set to true with a ```hintpath``` to the assemblies that are also managed by paket.

**Comment by forki** [comment]
Please try to run "paket install --hard". Does this help?

**Comment by leojh** [comment]
@forki that command did not make a difference in the resulting .csproj

**Comment by forki** [comment]
but System.Web.Mvc and System.Web.WebPages are framework references. not references to dlls in the package

**Comment by leojh** [comment]
The way I am reading the .lock file, RazorGenerator.Testing is referencing those two nugets itself. VS/MSBUILD picks the GAC dlls for those instead of respecting the assembly binding. I'm going to close the issue as I think I may have a work around. Thank you for your time @forki

**Comment by romansp** [comment]
Also stumbled upon this issue. After adding reference to *RazorGenerator.Mvc* project build fails. 

**Reproduced here**: https://github.com/romansp/paket-repro
My environment:
Visual Studio 2013 Update 5
Paket 2.40.3.0
RazorGenerator 2.3.12

By removing those GAC references (?) build runs successfully. See [**fix-build**](https://github.com/romansp/paket-repro/tree/fix-build) branch.

Maybe something is wrong within RazorGenerator package itself? If so I will open an issue there.

**Comment by forki** [comment]
>> Please try to run "paket install --hard". Does this help?

**Comment by romansp** [comment]
No, it doesn't. Running "paket install --hard"" [makes some changes](https://github.com/romansp/paket-repro/commit/a588d5314629155ad11046356914c7b366f59619), but build still fails.

**Comment by forki** [comment]
ok. please create a new issue here with your repro.
