### ISSUE TITLE
Paket is selecting latest from release when both release and prerelease are available

### ISSUE THREAD

**Issue by martinkunc** [fsprojects/Paket#1192]
In my paket.dependencies I have
nuget myPackage >= 1.0 prerelease

I have found that our Nuget Feed contains both:
myPackage 1.0.11
and
myPackage 1.0.12-build0025

even thought I specified Latest version including prerelease, Paket picked up v 1.0.11 during update.
To workaround, I setup paket.dependencies to
nuget myPackage >= 1.0.12 prerelease
to pickup latest of defined version.

**Comment by forki** [comment]
Is this a package and feed that is publicly available?

**Comment by martinkunc** [comment]
Hi, unfortunately, both are private. I hope it is repro'ble with some hand crafted versions too.

**Comment by forki** [comment]
ok. will try to simulate then

**Comment by forki** [comment]
mhm. 81c2c19 indicates that Paket understands the order of both versions and that your requirement in the dependencies file matches both versions.

is there any chance to give me private access to your feed for debugging?

**Comment by martinkunc** [comment]
I believe, really in your commit it my case should be covered  I can provide you with a private Fiddler trace I got from my Artifactory.
Here is what I am getting as a reply ot package-versions:
[ "1.0.10", "1.0.11", "1.0.12-build00021", "1.0.12-build00022", "1.0.12-build00023", "1.0.12-build00024" ]
I have Paket 2.21.0.0

**Comment by forki** [comment]
So the response contains beta versions. That's good. 

Are there any other packages creating restrictions on this package? I mean is it possible that the package is also a transitive dependency?

**Comment by martinkunc** [comment]
If I understand how its displayed indented in paket.lock, myPackage is also dependency of another direct dependency. It does not specify the requirement. .lock fragment:
    myPackage  (1.0.11)
    otherPackage (its version)
      myPackage

In the otherPackage nuspec dependencies are just id's this way:
    <dependencies>
      <dependency id="myPackage" />

**Comment by forki** [comment]
[Seems there is somethign missing in your post]

but if you have

    myPackage (1.0.11)
    otherPackage (its version)
        myPackage

then everything works as expected (at least as expected from my standpoint ;-) )

clarifcation:

    otherPackage (its version)
        myPackage

means that otherPackage accepts every version of myPackage except prereleases. so it restricts Paket's resolver to releases.


By using `nuget myPackage >= 1.0.12 prerelease` in the deps file you are somehow overwriting this behaviour. this requirement will only give you prereleases and so the resovler phase is working a bit differently.

**Comment by martinkunc** [comment]
Thanks Steffen, I suppose the outcome for me is not to mix prereleases with releases - Closing the issue.
