### ISSUE TITLE
Usability: Paket install binding redirect error during merge.

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#1195]
When I was doing a rebase on one of my branches, I had conflicts in the paket.lock and app.config files in a few of my projects.  When I ran `paket.exe install` to cleanup the lock file and app.configs, I was presented with this error.
```
Paket failed with:
	Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 9, position 2.
```
In my case it was pretty easy to figure out where the problem was, but I think it would be nice to know which file it failed on.

**Comment by forki** [comment]
Can you provide me a repro? Sforkmann@gmail.com

**Comment by TheAngryByrd** [comment]
Throwing some garbage like
```
<<<<<<< HEAD
```
in the middle of an app.config simulates it pretty quickly.

**Comment by forki** [comment]
@mrinaldi I reused your scenario. pretty overkill for this bug, but worked.

**Comment by TheAngryByrd** [comment]
![high5](https://cloud.githubusercontent.com/assets/1490044/10976638/df8f8284-83ba-11e5-80e2-78013870d904.gif)

**Comment by mrinaldi** [comment]
![happy](https://cloud.githubusercontent.com/assets/1226112/10977279/381f160a-83d7-11e5-9d8a-01318fb73719.gif)
