### ISSUE TITLE
NormalVersion not working with min strategy

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1197]
source https://nuget.org/api/v2
    
    nuget FSharp.Formatting !~> 2.4.0

then run `paket update -f`

    Paket failed with:
       Couldn't get package details for package Microsoft.AspNet.Razor on ["http ...

reported by @robertpi

**Comment by forki** [comment]
I just tried and got:

![image](https://cloud.githubusercontent.com/assets/57396/10993125/c436f28a-846c-11e5-8d20-dc862c92a2d3.png)

**Comment by robertpi** [comment]
Sorry, it appears I was using an old version. FsBlog have committed paket.exe to the repo, so bootstrap never gets run, thus I was using 0.0.12.0. Once I manually ran boostrap it started working again. I'll send them a PR.

**Comment by forki** [comment]
Oh.

**Comment by forki** [comment]
Probably enough to just delete the paket.exe and gitignore it.
