### ISSUE TITLE
"Build" in dependency groups example

### ISSUE THREAD

**Issue by jamesjrg** [fsprojects/Paket#1198]
I thought I'd try out dependency groups, and copying the example in the docs I added a group called "build". This installed the packages into /packages/build. However my .gitignore has the seemingly standard line:

```# Enable "build/" folder in the NuGet Packages folder since NuGet packages use it for MSBuild targets
!packages/*/build/```

And hence everything in the build group shows up as a change for git. Is using "Build" as the name of a group a bad idea, or have I missed something?

**Comment by forki** [comment]
just remove that line from gitignore and just ignore completete packages folder.

**Comment by jamesjrg** [comment]
That is what I have done, but if everyone following the example will face the same issue is it a good example?

**Comment by forki** [comment]
the question is what strange thing added that gitignore line. ;-)

**Comment by jamesjrg** [comment]
I copied that line from the .gitignore in F# project scaffold, the line was added in this commit:

https://github.com/fsprojects/ProjectScaffold/commit/261e11e28a087568728b52fc1542ee133eaba11f

**Comment by forki** [comment]
please send PR to ProjectScaffold that removes that line. thx
