### ISSUE TITLE
open up the TemplateFile API in Paket.Core

### ISSUE THREAD

**Issue by krgn** [fsprojects/Paket#1201]
I would be great to be able to re-use the TemplateFile parser code in a project I'm building (https://github.com/krgn/Paket2Nix) but its currently internal/private.

Would you consider making the API public for use in cases where external tools (in this case my tool which reads `.lock` files to create `nix` derivations from) need access to this metadata without necessarily having access to the assemblies themselves? 

Or, which other process would be recommended in this case? 

Reading the assemblies themselves would mean the project would have to be built when my tool is invoked on a project, which might not always be the case.

Thanks!

Karsten

**Comment by forki** [comment]
Sure. Please add methods to PublicAPI.fs - we try to keep that interface
stable.
