### ISSUE TITLE
Framework dependencies handled too strict

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1206]
My dependencies file containes log4net.ElasticSearch which has the transitive dependency to log4net for either net40 or net45. I narrow down my framework dependency to `net40, net45, sl5`. In that case my lock file does not show the dependency to log4net. I played around a little bit and removed the framework constraint of sl5 and the transitive dependency.
I have the feeling that paket understands the framework in an exclusive way which it shouldnt IMO.

**Comment by forki** [comment]
Could you please create a minimal deps file?

**Comment by Stift** [comment]
Yep.
So this the not working dep file

    framework: net40, net45, sl5
    source https://nuget.org/api/v2

    nuget log4net.ElasticSearch

and this dep file results in a correct lock file

    framework: net40, net45
    source https://nuget.org/api/v2

    nuget log4net.ElasticSearch

I hope this helps!

**Comment by forki** [comment]
latest release is generating:

    FRAMEWORK: NET40, NET45, SL50
    NUGET
      remote: https://nuget.org/api/v2
      specs:
        log4net (2.0.3) - framework: net40, net45
        log4net.ElasticSearch (2.2.0)
          log4net (>= 2.0.3.0) - framework: net40, net45

**Comment by Stift** [comment]
Works as expected. Nice.
![](http://i.giphy.com/iOvgF8UrcP40E.gif)
