### ISSUE TITLE
Allow to pass paket.dependencies on command line

### ISSUE THREAD

**Issue by pdfforge** [fsprojects/Paket#1207]
We are just starting to use Paket and ran into a Problem on our CI server, where we have to navigate into the source folder in order to restore the packages (cd source && .paket/pakete.exe restore), which seems a bit weird. As far as I could tell, there is no way to tell Paket where the paket.dependencies file lies.

My suggestion would be to allow a call like this:

     Source/.paket/paket.exe restore --dependecy-file=Source/paket.dependencies

In this case, Paket would have to determine that the packages should be downloaded into the Source/packages.

Alternatively, Paket could "know" its location and always navigate one dir up from that, but that would be a breaking change compared to the current behaviour.

Unfortunately, my F# skills are close to non-existent, so I am not able to create a pull request for this right now, but we would find this really useful.

**Comment by forki** [comment]
in very early versions we had that parameter already, but decided against it again to keep it simple.

One question: why don't you move `.paket` folder and paket.dependencies one level up (like here in this repo and all ["projectscaffold"-like repos](https://github.com/fsprojects/ProjectScaffold)). One of the basic ideas in paket was always that we want to throw dependencies in the face of the developer (as oposed to nuget which tris to hide the fact that you have deps). From this idea all our repos have paket.dependencies direktly in the root.

**Comment by pdfforge** [comment]
that's a good question ;-)

Basically, we have two folders (Source and Setup) and traditionally, they wered checked out seperately from svn. Now using git, this is obsolete anyway, but we therefore have this separation.

In the end, we would like the have binary dependencies of the setup and the C# code and I am not sure if it is a good idea to mix these two sorts of dependencies. In our case, it also will be different developers going at the code and the C# devs always start in the source folder and the setup devs in the setup folder, so they would still be aware of the dependencies being there.

I will discuss this here, but still I would appreciate this feature ;-)

Many thanks,
Philip

PS: And thanks for the talk on the open space in Leipzig, we have started to move to Paket after we have heard about it there

**Comment by forki** [comment]
After thinking about this: I don't think we should make the internal code more complicated here.
Please work with a small `cd source` or put the dependencies and lock file into the root (which I would recommend).

**Comment by pdfforge** [comment]
Thank you for giving this another though. Finally, I think you are right and we will move the dependencies file into the root. While doing our tests with Paket, we have found that a few dependencies are shared between the setup and the source code. This gives even more emphasis on you suggestion that we should manage them with the same package resolution to be sure to use the same versions in both places.
