### ISSUE TITLE
Packages framework restriction are propagated incorrectly

### ISSUE THREAD

**Issue by vbfox** [fsprojects/Paket#1213]
Using this `paket.dependencies` file :

```
framework: >= net40

source https://nuget.org/api/v2

nuget Newtonsoft.Json redirects: on
nuget Nancy.Serialization.JsonNet ~> 1.2 framework: >= net451
```

The resulting lock file is : 

```
FRAMEWORK: >= NET40
NUGET
  remote: https://nuget.org/api/v2
  specs:
    Nancy (1.4.1) - framework: >= net451
    Nancy.Serialization.JsonNet (1.4.1) - framework: >= net451
      Nancy (>= 1.4.1)
      Newtonsoft.Json
    Newtonsoft.Json (7.0.1) - redirects: on, framework: >= net451
```

But the `Newtonsoft.Json (7.0.1) - redirects: on, framework: >= net451` line is incorrect as the configuration intended for `Newtonsoft.Json` to be usable in `framework: >= net40`.

It seem that the framework restriction applied to `Nancy.Serialization.JsonNet` has unexpectedly propagated to one of it's dependencies.

**Comment by vbfox** [comment]
First version with the bug seem to be 2.21.3 so it would point to #1190

**Comment by forki** [comment]
I'm very happy that we now have the integration test infrastructure in place. this one was really nasty and had a big chance to be regression to #1190. Anyways I think it's fixed. And I added your case as regression test.

**Comment by vbfox** [comment]
:+1: 

Perfect, we can now update to the latest version.

Thanks a lot.
