### ISSUE TITLE
More user-friendly message for bootstrapper

### ISSUE THREAD

**Issue by kostrse** [fsprojects/Paket#1214]
Bootstrapper prints the following output:

```
~/Dev/proj $ ./build.sh
No version specified. Downloading latest stable.
Starting download from https://github.com/fsprojects/Paket/releases/download/2.24.4/paket.exe
```

For people who do not know details about the build script implementation, it's unclear what exactly has no version specified, and should they worry about it :)

The message could be somewhat more user-friendly and descriptive, like:
```
Checking Paket version (downloading latest stable)...
```

**Comment by forki** [comment]
I like that. Would love to see a PR
