### ISSUE TITLE
Tranistive package shrinks usage of frameworks

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1215]
I use the following nuget package Microsoft.Bcl.Async in a Silverlight 5 project and this was fine so far. But now I added in my paket.dependencies file the nuget package OwinMiddlewares.Log4net. Because of that paket finds out that Microsoft.Bcl.Async is only needed in for framework >= net40, which is fine. But it now put this constraint as well in the paket.lock file on the pinned version and now in the csproj file no version is added for Silverlight 5.0. And this is not fine.

I have created a small sample. This contains 2 paket.dependency files and one project. The first dep file works fine, the second one removes the needed project reference
https://www.dropbox.com/s/puz3ustm5etr9wm/paket.zip?dl=1

**Comment by forki** [comment]
since I worked on similar issue a couple of minutes ago - could you please verify that this still happens with latest? thx

**Comment by forki** [comment]
yep seems still to be the case. confirmed => bug

**Comment by Stift** [comment]
Yep. Just tested it with 2.24.5 and still there.

**Comment by forki** [comment]
I'm already deplyoing a fix ;-)

**Comment by forki** [comment]
unfortunately all the integration test make this process much slower than a couple of weeks ago ;-)

**Comment by Stift** [comment]
2.24.6 works - very nice.
Will test it tomorrow in my office, but in my sample it looks promising.

![](http://i.giphy.com/c5dzk1pyeTlBe.gif)

**Comment by Stift** [comment]
Aaaand now its working completely. Thx again!
