### ISSUE TITLE
Paket does not put .props and .targets import project on correct location in project files

### ISSUE THREAD

**Issue by theggelund** [fsprojects/Paket#1219]
When Paket installs a nuget package with {packageid}.props/{packageid}.targets in build folder, it should 

1. Put '\<import Project="{path to {packageid}.props" />' as the first child element in Project element
2. Put '\<Import Project="{path to {packageid}.targets}}" />' as the last child element in Project element

Paket puts both imports in the middle of csproj file and by doing so, breaks compatiblity with nuget feature "Import MSBuild targets and props files into project"

**Comment by forki** [comment]
Do you have a csproj file and a dependencies file (or just nuget package
name) for me to create a integration test?

**Comment by theggelund** [comment]
https://github.com/theggelund/paket_bug

**Comment by forki** [comment]
does this work for you?

**Comment by theggelund** [comment]
It worked in the test project and in some of my real projects but not all. I will try to analyze the ones that didn't work and try to create a new test project for you.

**Comment by theggelund** [comment]
Updated https://github.com/theggelund/paket_bug

When nuget package is sorted after MultiTarget package => nunit
the import statement comes before nunit import

**Comment by theggelund** [comment]
Updated https://github.com/theggelund/paket_bug

Added a project called manual_project under MyCallLibrary. The initial issue is reproduced with the project. Used latest released paket 2.24.7

**Comment by forki** [comment]
ok I fixed that Nunit issue

**Comment by forki** [comment]
I hope it's not completely fixed.
