### ISSUE TITLE
File "paket.version" is locked?

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Paket#1220]
I'm trying to reference some files from GitHub repository (via HTTP to avoid getting transitive dependencies) in FsLab to make sure the FsLab template on the web (https://github.com/fslaborg/FsLab.Templates/tree/journal) is the same as the one that comes with VS template.

The change to do this is here: https://github.com/fslaborg/FsLab/commit/b5079e1b3626c39923717bfde86dd866764e2c38

Trying to run `paket restore` gives the following error (even when I clone a fresh version of the FsLab repo):

> Paket failed with:  
>        The process cannot access the file 'C:\Temp\FsLab-master\paket-files\raw.githubusercontent.com\paket.version' because it is being used by another process.

I think I've seen this error before when referencing files from GitHub, but I'm not sure in what situations. Am I missing something, or is this a bug in Paket restore?

**Comment by forki** [comment]
is this reproducable? can you send me a zip where I can repro?

**Comment by tpetricek** [comment]
It happens reproducibly on the FsLab repo (on my machine :-)): https://github.com/fslaborg/FsLab/archive/master.zip

**Comment by tpetricek** [comment]
Hmm, it happens reproducibly on my machine 20 minutes ago, but not anymore.

**Comment by forki** [comment]
da fuq?

**Comment by tpetricek** [comment]
It might have been something else running on my machine (though I don't have any third party antivirus and the folder is not in DropBox/OneDrive for synchronization...). I'll reopen this if I start getting this.

When downloading the files from HTTP, is this done in parallel? And are the updates to the `paket.version` file done when the files are downloaded? I imagine that could sometime end up in a situation where two threads attempt to open the file...
