### ISSUE TITLE
isolate paket changes to project files

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1223]
In the past I often saw that a different paket version updated csproj file when some internal paket behaviour/handling changed (e.g. different framewerk handlings etc.).
To minimize this paket should separate as much as possible changes it is doing from the developer area. This would mean, that developers and paket have each its own area.
That said, I suggest that paket creates a **ProjectName.Paket.targets** file and references it in the .csproj file via "\<Import Project="ProjectName.Paket.targets" />". The .targets file just looks like every other normal .targets files with all the *\<Choose>* and *\<When>* logic.
The advantage could be that merge conflicts on these files (which unfortunately happen from time to time in the paket area) can be easily ignored, and the dev just runs `paket install` after merging to recreate these files. Additionally syntactic changes (spaces, line breaks) just because the project file is rewritten would also be minimized.
When this should not be the default behaviour I would suggest to control the behaviour via the paket.dependencies file with some flags.

**Comment by forki** [comment]
Yes we already tried to make that work, but unfortunately ran in lots of
bad issues with this approach.

**Comment by Stift** [comment]
Oh, really. What was the problem behind this approach?

**Comment by forki** [comment]
See https://github.com/fsprojects/Paket/issues/417 it's a shame that we didn't get it working. We even had pull requests for this.

**Comment by isaacabraham** [comment]
Why closed? Reading through that issue again there was an option which was to delegate the restore to vs extension. I'm still missing what the problem with that approach was. I assume that command line Paket restore would still work as well?

**Comment by forki** [comment]
not when VS is open. there was no way to mak it work. Update/restore always foreced us to restart VS

**Comment by isaacabraham** [comment]
I thought doing it via Paket VS add-in would have solved the problem like the NuGet extension does?

**Comment by forki** [comment]
sure, but then you force people to ue the addin. which is against our "minimal tooling" idea.

**Comment by isaacabraham** [comment]
not sure it forces people to use the addin - if you're using command line you don't need to. I suppose if you use VS then yes, you force people to use the add in. would other IDEs be unaffected if they go straight to paket.exe anyway?

**Comment by forki** [comment]
We didn't test other IDEs, but command line + VS scenario would be broken.
Which is what most of the early adopters are using.

**Comment by isaacabraham** [comment]
what is "command line + VS scenario"? Using visual studio for development but manually opening up command prompt and typing ```paket.exe restore```? And this wouldn't work?

**Comment by forki** [comment]
It's even more complicated.
Projects like fsharp.data rely on automatic VS restore. Cline repo, open
sln,  press F5 - that's not working since paket restore needs to generate
targets files. Then you need to restart VS so that VS loads the generated
targets files.

**Comment by isaacabraham** [comment]
OK I'm thoroughly confused now. You'll need to Skype me to explain this ;-) Let's just leave it as "won't fix" :-)
