### ISSUE TITLE
Privacy Leakage: feed password may be revealed in output

### ISSUE THREAD

**Issue by cdrnet** [fsprojects/Paket#1224]
When paket fails it may leak the user's password in the output:

    Paket failed with:
            Could not find versions for package SomePackageName in any of the sources in [Nuget
       {Url =
         "https://feed-url";
        Authentication = Some (ConfigAuthentication ("user name","actual password"));}].

We may want to skip printing the actual password there.

**Comment by forki** [comment]
Yes we need to implement tostring for the Auth type. Care to send a PR?

**Comment by cdrnet** [comment]
Sure. Would it also make sense to use `SecureString` instead of `String` for the password?

**Comment by forki** [comment]
I guess it could be done, but most of the the passwords can be found on
your system (often in deps file) anyway.

**Comment by cdrnet** [comment]
Fair enough, I'll just open a PR for ToString of Credentials etc for now. Thanks.
