### ISSUE TITLE
Issue with paket convert-from-nuget

### ISSUE THREAD

**Issue by theggelund** [fsprojects/Paket#1225]
I tried to convert a project from nuget to paket.

![image](https://cloud.githubusercontent.com/assets/648714/11177050/e7db662a-8c42-11e5-832f-c74718b34533.png)
 
but paket stops, looks like its waiting for something that doesn't happen.

Paket has put a json file in nuget cache folder with the following content
```json
{"Dependencies":[],"PackageName":"odp.net.managed","SourceUrl":"http://dips-nuget/nuget/TeamFrost","Unlisted":false,"DownloadUrl":"http://dips-nuget/api/v2/package/TeamFrost/odp.net.managed/121.1.2","LicenseUrl":"http://www.oracle.com/technetwork/licenses/ea-license-noexhibits-1938914.html","CacheVersion":"2.0"}
```

paket.dependencies
```
source \\p-fs01\exetest\repository
source http://dips-nuget/nuget/TeamFrost

nuget Nuget.CommandLine @>= 0
nuget Antlr4.StringTemplate @= 4.0.6.9004
nuget Common.Logging @= 3.0.0 framework: >= net451
nuget Common.Logging.Core @= 3.1.0
nuget CommonServiceLocator @= 1.0 framework: >= net451
nuget Dapper @= 1.40
nuget DIPS.Lab.IfsServer.Plugin @= 0.0.0.9 framework: >= net40
nuget DIPS.Lab.IfsServer.Plugin.Lab.Persistence @= 0.0.0.9 framework: >= net40
nuget DIPS.Lab.Infrastructure @= 0.0.0.59
nuget DIPS.Lab.Infrastructure.Connector.MSMQ @= 0.0.0.59
nuget DIPS.Lab.Infrastructure.Database @= 0.0.0.57 framework: >= net451
nuget DIPS.Lab.Infrastructure.Logging.Serilog @= 0.0.0.56 framework: >= net451
nuget DIPS.Lab.Infrastructure.Messaging @= 0.0.0.59
nuget DIPS.Testing.NUnit @= 1.3.0.0
nuget Extended.Wpf.Toolkit @= 2.3.0 framework: >= net451
nuget FluentAssertions @= 3.3.0
nuget ICSharpCode.SharpZipLib.dll @= 0.85.4.369 framework: >= net451
nuget Jil @= 2.9.0
nuget MiniProfiler @= 3.1.1.140 framework: >= net451
nuget Moq @= 4.2.1502.0911
nuget Newtonsoft.Json @= 6.0.8
nuget NUnit @= 2.6.4
nuget odp.net.managed @= 121.1.2
nuget Prism @= 4.1.0.0 framework: >= net451
nuget Quartz @= 2.3.1 framework: >= net451
nuget Rx-Core @= 2.2.5 framework: >= net451
nuget Rx-Interfaces @= 2.2.5 framework: >= net451
nuget Rx-Linq @= 2.2.5 framework: >= net451
nuget Rx-Main @= 2.2.5 framework: >= net451
nuget Rx-PlatformServices @= 2.2.5 framework: >= net451
nuget Rx-Testing @= 2.2.5 framework: >= net451
nuget Rx-WinForms @= 2.2.5 framework: >= net451
nuget Serilog @= 1.4.76 framework: >= net451
nuget Serilog.Sinks.Seq @= 1.4.76 framework: >= net451
nuget Serilog.Sinks.Splunk @= 1.4.76 framework: >= net451
nuget Sigil @= 4.4.0
nuget SimpleInjector @= 3.0.5
nuget SimpleInjector.Extensions.ExecutionContextScoping @= 2.8.0 framework: >= net451
nuget SpecFlow @= 1.9.0 framework: >= net452
nuget SpecFlow.NUnit @= 1.1.1 framework: >= net452
nuget Splunk.Logging.Common @= 1.0.0 framework: >= net451
nuget Topshelf @= 3.1.4 framework: >= net451
```

packages folder
![image](https://cloud.githubusercontent.com/assets/648714/11177144/a60de672-8c43-11e5-8a44-09ebcdce0752.png)

Check to see if nuget server was not responding, but it was.

Any ideas?

**Comment by forki** [comment]
(side note: @mrinaldi @theimowski this is the third time I see `convert` creating `@=` contraints. any ideas why? I can't reproduce this yet)

**Comment by theggelund** [comment]
attached a debugger
![image](https://cloud.githubusercontent.com/assets/648714/11177281/c598d6f4-8c44-11e5-982c-cc720ae4b595.png)

**Comment by forki** [comment]
What nuget server are you using? 
Did you see other projects (with paket)  work against this servers?

**Comment by theggelund** [comment]
ProGet 3.4.3 (Build 7)

Yes, the other bugs I have reported the last few days uses the same server

**Comment by forki** [comment]
Mhm. Seems like it's waiting in the cache method /cc @xavierzwirtz 

Can you try to downgrade paket to maybe 3 or 4 minor versions?

**Comment by theggelund** [comment]
![image](https://cloud.githubusercontent.com/assets/648714/11177425/d04db7e4-8c45-11e5-9018-421c04f8a017.png)

**Comment by theggelund** [comment]
![image](https://cloud.githubusercontent.com/assets/648714/11177449/fa730614-8c45-11e5-9638-918d71082c7a.png)

**Comment by forki** [comment]
No I meant something like 2.21

**Comment by forki** [comment]
I hate when things go wrong on private feeds...

**Comment by theggelund** [comment]
![image](https://cloud.githubusercontent.com/assets/648714/11177522/6d934dfc-8c46-11e5-8f95-98c4544af3cb.png)

![image](https://cloud.githubusercontent.com/assets/648714/11177529/7c7160a2-8c46-11e5-9db0-f9d98623b8cf.png)

**Comment by forki** [comment]
Ok. Seems it's not related to latest cache changes. 

Unfortunately the attached debugger info is not that helpful. 

What I usually do in this situation is to start the convert process from VS
  * clone repo
  * set paket as startup project 
  * set working dir to you project dir 
  * set startup command to "convert-from-nuget" 
  * F5

**Comment by forki** [comment]
it's also possible that it is reated to `source \\p-fs01\exetest\repository`, but it's impossoble for me to checkout outside of your network ;-(

**Comment by forki** [comment]
one thing you could do is to run `convert-from-nuget -f- v` and meaybe we see a bit more info

**Comment by theggelund** [comment]
Internal Server Error from nuget server when calling this uri "http://dips-nuget/nuget/TeamFrost/Packages?$filter=Id eq 'odp.net.managed' and NormalizedVersion eq '121.1.2'"

**Comment by theggelund** [comment]
Happens twice, then it never continues from this
![image](https://cloud.githubusercontent.com/assets/648714/11177824/a323bdec-8c48-11e5-8803-48aa49e30b8c.png)

**Comment by forki** [comment]
do you get the same error manually from browser?

**Comment by theggelund** [comment]
Yes, trying do find error logs from server

**Comment by theimowski** [comment]
Regarding the `@=` operator - I'm not sure, but maybe that's because of the explicit specification of MaxResolver strategy [here](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NugetConvert.fs#L217)?

**Comment by mrinaldi** [comment]
I'm on the `@=` right now. I'll send a PR shortly.

**Comment by forki** [comment]
Mhm that sounds like it could be the issue. If I just could reproduce it.

**Comment by theggelund** [comment]
Shouldn't Paket fail with an error message instead of freezing when the http call to our local nuget repo fails?

**Comment by forki** [comment]
Yes. The code you mentioned is part of the normal paket update command.
It's very strange that the error doesn't escalate. Maybe there is still a
call going on and we should add a timeout or something. Does it really
freeze forever?
Did you find out why the server had an error?

**Comment by theggelund** [comment]
I left it yesterday and 8 hours later it still waits.

I've tried to get error logs from the server but all i could find was iis
logs stating the 500 error
17. nov. 2015 08:26 skrev "Steffen Forkmann" <notifications@github.com>:

**Comment by forki** [comment]
I will add a timeout to that function.
Maybe @gdivis can comment on the server error?

**Comment by forki** [comment]
what about this url? http://dips-nuget/nuget/TeamFrost/Packages?$filter=Id eq 'odp.net.managed' and Version eq '121.1.2' 

does this work in browser?

**Comment by forki** [comment]
there is a new alpha version that you can test. It runs all Nuget protocols for "GetPackageVersion" in parallel. Maybe it improves things.

**Comment by theggelund** [comment]
This doesn't work:

    what about this url? http://dips-nuget/nuget/TeamFrost/Packages?$filter=Id eq 'odp.net.managed' and Version eq '121.1.2'

    does this work in browser?

**Comment by theggelund** [comment]
I'll test the code later today

**Comment by forki** [comment]
OK so Async.Chice didn't work. Sorry for the pingpong (always big fun with private networks). I need to take a look at the code. At the moment I have no idea without debugging it.

**Comment by theggelund** [comment]
So I have played a little with our ProGet Nuget server and the query that Paket runs.

If you just but each part of the filter statement inside a () then it works

Change 

    http://dips-nuget/nuget/TeamFrost/Packages?$filter=Id eq 'odp.net.managed' and Version eq '
to

    http://dips-nuget/nuget/TeamFrost/Packages?$filter=(Id eq 'odp.net.managed') and (Version eq '121.1.2')

**Comment by forki** [comment]
Ok. Not sure if this is a proget bug, but we can do that. 

/cc @maartenballiauw do you see issues with this change in regard to other servers like myget?

**Comment by maartenba** [comment]
It's valid OData so should work fine

**Comment by theggelund** [comment]
this works for nuget as well
 
https://www.nuget.org/api/v2/Packages?$filter=(Id eq 'odp.net.managed') and (Version eq '121.1.2')

**Comment by forki** [comment]
ok then let's do it. Thanks maarten.

**Comment by forki** [comment]
@theggelund could you please try 2.26? thx

**Comment by theggelund** [comment]
Paket is able to download some data from the url but it stops at the same location as it did before. Don't know why but I saw the it tried to download from a uri with /odata/ between TeamFrost and packages in the uri.

![image](https://cloud.githubusercontent.com/assets/648714/11248911/f8bb323a-8e23-11e5-87e5-ba843df882c9.png)

![image](https://cloud.githubusercontent.com/assets/648714/11248922/104b3954-8e24-11e5-931c-c6b71e17ed89.png)

**Comment by forki** [comment]
Is this now a different server?

**Comment by forki** [comment]
Ok I reverted the parallel execution of the 4 protocols and only enabled the fix with ( ) in the OData.

I'M deeply sorry for this ping-pong.

**Comment by theggelund** [comment]
no worries. If this gets fixed i'm happy 
![image](https://cloud.githubusercontent.com/assets/648714/11264924/2da8706a-8e98-11e5-82ac-08a8e137ba0d.png)

So I left the convert-to-nuget running yesterday and i appears to be a timeout somewhere thats quite large. After 12 hours it has run through 10 of 44 packages and it appears to be continuing after a massive wait,

And there is a exception when source is folder but I don't think it is the problem

![image](https://cloud.githubusercontent.com/assets/648714/11265007/f234cd2a-8e98-11e5-88bf-f038e3ac3c20.png)

**Comment by forki** [comment]
the dependencies file ist already there right?
Can you try to remove the file system source (and the packages that are in the file system) from the deps file and run "paet update"? Maybe the issue is now in the file system scanning code?

**Comment by forki** [comment]
Alternatively can you create a mini deps file with contains only the file system source and a couple of packages from the file share. Is running paket update on this also slow?

**Comment by theggelund** [comment]
it was the filesystem scanning. After ignoring the filesystem there is no wait and it works

**Comment by forki** [comment]
ok. so we need to investigate this then.

**Comment by forki** [comment]
is this still relevant?

**Comment by theggelund** [comment]
No I think you can close the issue

Den tir. 8. mar. 2016, 16.49 skrev Steffen Forkmann <
notifications@github.com>:
