### ISSUE TITLE
Breaking visual basic projects on paket update

### ISSUE THREAD

**Issue by Rcomian** [fsprojects/Paket#1226]
Using paket v2.25.2.0

When upgrading a visual studio project, it moved an import statement to the end of the file:

    <Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" />

When this import is after the Reference sections, the references are not loaded. As a result, all paket references are effectively removed from the build.

Moving this Import statement further up the file, before the references, fixed the project.

Fortunately, running update again does not appear to automatically break it again.

The move was part of a block move, where a bunch of included files were moved to the end of the file, along with this import statement.

**Comment by forki** [comment]
@theggelund  in https://github.com/fsprojects/Paket/issues/1219 you saif the targets should be last stuff in the proj files. seems that#s not correct. what should we do?

**Comment by Rcomian** [comment]
The <Import> statement that was moved was not part of any nuget package. Can we exclude those <Imports> and not move them?

**Comment by forki** [comment]
we probably can.

**Comment by forki** [comment]
do you have the csproj file for me before the change?

**Comment by theggelund** [comment]
@forki I said that targets that are included in a nuget package (build folder) should be put last, not all targets in a file. Ordering of stuff in msbuild files are important

**Comment by forki** [comment]
yes. the big question is how can we detect where we want to put our paket references and paket.targets

**Comment by Rcomian** [comment]
I do, but since we use a lot of internal packages and code I'm not sure how much use they'll be.

[BEFORE_NE.SequenceManager.vbproj.txt](https://github.com/fsprojects/Paket/files/35450/BEFORE_NE.SequenceManager.vbproj.txt)
[AFTER_NE.SequenceManager.vbproj.txt](https://github.com/fsprojects/Paket/files/35451/AFTER_NE.SequenceManager.vbproj.txt)

**Comment by Rcomian** [comment]
Fix looks good - just moving the imports that are controlled by paket.
Can you let me know when there's a build I can try this out on?

**Comment by forki** [comment]
I'm still trying to reproduce the error, but the latest version has a fix that might help. Could you please retry with latest paket?

**Comment by forki** [comment]
(and then it's time to cleanup that mess in that function ;-) )

**Comment by Rcomian** [comment]
Hmm, no, as of 2.25.3.0, it's now leaving the resource files in place, which I like, but the include is still being moved to the end.

[AFTER_2.25.3.0.NE.SequenceManager.vbproj.txt](https://github.com/fsprojects/Paket/files/35479/AFTER_2.25.3.0.NE.SequenceManager.vbproj.txt)

**Comment by Rcomian** [comment]
And again, moving the include back to its original location (just under the resources, just before the references) works fine.

**Comment by forki** [comment]
ok. so it's a off by one issue ;-)

**Comment by forki** [comment]
so seems I was finally able to reproduce this in the integration tests. please retry.

**Comment by Rcomian** [comment]
That's the one. Tried that and it works fine. Much cleaner and correct set of changes:

[AFTER_2.25.4.0.NE.SequenceManager.vbproj.txt](https://github.com/fsprojects/Paket/files/35609/AFTER_2.25.4.0.NE.SequenceManager.vbproj.txt)

Thank you very much for your work!

**Comment by forki** [comment]
Cool. Thanks for caring and reporting.
