### ISSUE TITLE
paket pack failes if AssemblyName is empty and template type is project.

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#1234]
paket pack failes if AssemblyName is empty and template type is file. It complains that the file can't be found, but I think it would be more useful to point to the root issue in the GetAssemblyName function in ProjectFile.fs

Paket version is 2.15.7.0

**Comment by forki** [comment]
do you have a csproj and template file for me?

**Comment by trondd** [comment]
It is part of internal source code, but I'll prepare an example. Stay tuned.

**Comment by trondd** [comment]
See https://github.com/trondd/PaketIssue1234

  paket pack output temp -v

Note that I've manually cleared the AssemblyName in the Project file.

**Comment by forki** [comment]
what output would you expect? And why is the AssemblyName empty in the first place? Does it use a default?

**Comment by forki** [comment]
ok I can reproduce.

    	Ein Teil des Pfades "C:\Users\Steffen\AppData\Local\NCrunch\4112\7\integrationtests\scenarios\i001234-missing-assemblyname\temp\PaketBug\bin\Release\.dll" konnte nicht gefunden werden.


which is your filenotfoundexception. Question is: can we improve the GetAssemblyName function? I might use the CsProj name in this case!?

**Comment by trondd** [comment]
Awesome!
