### ISSUE TITLE
Issue with paket and third party Nuget server when revision number is zero

### ISSUE THREAD

**Issue by mvkra** [fsprojects/Paket#1239]
Some of the proprietary package systems take the version number too literally and don't include the "zero" in the HTTP request to their server. I'm wondering if we can make it more forgiving and allow it to try 3.6 and 3.6.0 as one and the same?

e.g 

Paket failed with:
        Couldn't get package details for package RhinoMocks 3.6 on http://{third-party-server}

When trying to restore packages it gives me the error:

Paket failed with:
	Could not retrieve data from http://{third-party-server}/Packages(Id='RhinoMocks',Version='3.6.0')

Looking at the package for RhinoMocks when you download it from nuget.org the version is coded as "3.6". So in this case the third party server (Proget) assumes this is the one and true version number.

Message from output:
Something went wrong while downloading RhinoMocks 3.6.0
Message: Could not retrieve data from http://{third-party-server}/odata/Packages(Id='RhinoMocks',Version='3.6.0')
 Message: Invalid URI: The hostname could not be parsed.

Hardcoding 3.6 in the paket.lock file works in this case works and allows the build to proceed.

**Comment by forki** [comment]
In latest I changed it back and don't write normalized version into the lock file

**Comment by mvkra** [comment]
Nice turnaround. Thanks
