### ISSUE TITLE
paket.bootstrapper.exe 2.27.0 fails

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#1240]
paket.bootstrapper.exe 2.27.0 fails with 

>.paket\paket.bootstrapper.exe
No version specified. Downloading latest stable.
**Input string was not in a correct format. (Github)**

**Comment by forki** [comment]
Argh. Probably regression in #1236

**Comment by alexeyzimarev** [comment]
May be there's a need for a small integration test :)

**Comment by forki** [comment]
We have one. But it's testing vnext (via paket init). So expect it to fail
now ;-)

Joking aside: will add one that checks the currently built version.

**Comment by inosik** [comment]
Sorry for that, can't do anything right now. I think it's better to revert for now.

**Comment by inosik** [comment]
This seems to only affect GitHub, NuGet works fine.

**Comment by forki** [comment]
reverting right now

**Comment by forki** [comment]
Could you please try with latest?
