### ISSUE TITLE
Unclear error message for issues in lock file

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsprojects/Paket#1247]
When there is something in `paket.dependencies` that Paket doesn't understand, it tells you exactly where, and what the problem is. For an error in `paket.lock`, I only got

    Paket failed with:
        Input string was not in a correct format.

This should at least say that it's about the lock file, so the user knows where to start looking.

**Comment by forki** [comment]
How did the wrong lock file look like?

**Comment by TeaDrivenDev** [comment]
I had tried to allow a "minimum" version at the top level:

    NUGET
      remote: https://nuget.org/api/v2
      specs:
        FAKE (>= 4.9.3)

**Comment by forki** [comment]
I just added this as an integration test and it now shows a better error message, but why do you change the lockfile manually?

**Comment by TeaDrivenDev** [comment]
Because

![200_s](https://cloud.githubusercontent.com/assets/2247219/11338569/256ae274-91f5-11e5-8d31-9899b1a8008d.gif)

:D

**Comment by forki** [comment]
yeah, lock files are usually not edited manually.
