### ISSUE TITLE
Paket changes my config files

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#1248]
<img width="691" alt="screen shot 2015-11-22 at 10 38 05" src="https://cloud.githubusercontent.com/assets/193115/11323013/2b56b42e-9105-11e5-88d0-1b5b0a42b9f2.png">

Do you know why?

XML should not contain BOMs imo, as no other language really support them.

**Comment by forki** [comment]
//cc @isaacabraham @mrinaldi

**Comment by isaacabraham** [comment]
Urgh. Don't know why that's there. I think this should be done as part of the cleanup of the formatting of the BRs anyway (you can see from the ```</assemblyBinding></runtime>``` line that it's not formatted properly).

**Comment by konste** [comment]
How about Paket leave XML formatting alone? We have never ending problem with Paket always changing our config files (incl. those it should not be touching at all). It keeps removing spaces in lines like 'value="false" />' So it removes the space between doublequote and slash and does it for ALL configs. We would leave it like that, but some other automated tool has different idea what the right spacing is and it keep adding that space back! This creates enormous churn and makes reviewing config file changes very hard. Please, please let Paket NOT CHANGE existing XML formatting.

**Comment by forki** [comment]
Yes it's definitely the plan to keep formatting as stable as possible. Will
try to add couple of tests tomorrow

**Comment by konste** [comment]
@forki, thank you for speedy response! It is always great to work with you!

**Comment by forki** [comment]
@konste can you give me the app.config in question (which contains value = false) for a unit test?

**Comment by konste** [comment]
[App.config.txt](https://github.com/fsprojects/Paket/files/50855/App.config.txt)

**Comment by forki** [comment]
wow. even if we disable formatting it seems .NET always writes `value="false"/>` as `value="false" />`

**Comment by konste** [comment]
I may look into it. Which exactly .NET Xml facility is employed here? XmlDocument? XDocument? 

But why rewrite configs which are not touched a bit at all?

**Comment by forki** [comment]
that are two separate issues. one is we should not touched configs that we don't change logically. second is that we don't stuff outside of redirects

**Comment by konste** [comment]
I understand that the second part is harder than it seems. Writing XML file is usually one call to a Save method (unless combination of reader and writer is used, which seems like overkill here), so we just need a way to preserve original formatting. So what .NET class is used to handle XML in Paket?

**Comment by konste** [comment]
As far as I can tell from src\Paket.Core\BindingRedirects.fs XDocument is used. Then formatting preservation is as easy as calling Save like that: x.Save(writeFileName, SaveOptions.DisableFormatting);

**Comment by forki** [comment]
^^ it's not I'm already doing this in my local version

**Comment by forki** [comment]
@konste with latest changes we should not touch files when we don't do logical changes. can you please test it?

**Comment by konste** [comment]
Is binary available? I don't have F# build environment at the moment.

**Comment by forki** [comment]
Yes it's in latest release.

**Comment by konste** [comment]
Version 2.32.5 keeps updating all config files when I do "paket update" which otherwise does nothing.

**Comment by forki** [comment]
what's the diff?

**Comment by konste** [comment]
Same - space before slash.

**Comment by forki** [comment]
![dog](https://cloud.githubusercontent.com/assets/57396/11570461/a99b3c9c-99f7-11e5-8a94-4a5271b0f336.gif)

**Comment by forki** [comment]
nothing else? only the spaces?

**Comment by konste** [comment]
1. One space before EACH />
2. At the end of each config a line is added: <runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1" /></runtime>
3. Fourth ".0" in versions is stripped again.

**Comment by forki** [comment]
ah ok. I assume 3 is the reason.

since I didn't find a way to tel the  .NET API to keep formatting of that char I tried to come up with "logical changes comparison". If no logical changes => we don't touch the file at all.

But 3 indicates a logical change => we touch it. please just commit that removement of .0 and the try again.

BTW: sorry. but this stuff is really tricky (and annoying)

**Comment by konste** [comment]
-- If no logical changes => we don't touch the file at all.

Can we make it: no changes **in BindingRedirect** => we don't touch the file at all?

Because in our case we have "redirects: off" and I would expect it to cut short all attempts to even read config files.

**Comment by forki** [comment]
yeah that's the next step.

>  ".0" in versions is stripped again.

why is that even in there if you have redirects: off?

**Comment by konste** [comment]
".0" in versions is stripped in paket.lock. Nothing to do with configs.

**Comment by forki** [comment]
ok I'm confused now.

let's start over:

* .0 is removed from lock file? That's intended and from other issue, right?
* Nothing semantically changed in binding redirects file? Only reformatting?

**Comment by konste** [comment]
Both Right.

**Comment by forki** [comment]
is there a chance for me to reproduce? Can you mail me and tell me what you did? I won't make it public.

**Comment by konste** [comment]
I think the problem is that last line it adds - it is basically empty BindingRedirects section. So the logic seems to be - if we are not going to add BindingRedirects to config, but it does not even have corresponding section - empty section is added. And "while we are here" extra spaces are added too.

**Comment by forki** [comment]
ook just to confirm. can you commit that line and try again? does it stay stable and doesn't remove the space before the slashes?

**Comment by konste** [comment]
Ok, here we go: when I replace this:
```xml
</configuration>
```
with this (literally!):
```xml
<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1" /></runtime></configuration>
```
then Paket leaves that config alone and does not add extra spaces or change it in any other way.

But if I add this section formatted differently than all in one line, then it is ignored and config is reformatted. Weird.

**Comment by forki** [comment]
GOOD!

that's what I wanted to hear - means we're on the right track. I will remove this tomorrow ;-)

**Comment by forki** [comment]
And sorry for all the trouble...

**Comment by konste** [comment]
No prob, thank you for the help! I wish I could contribute more than testing.

**Comment by forki** [comment]
dude testing is most important since that guy is me:

![wtf](https://cloud.githubusercontent.com/assets/57396/11571843/a6177386-99fe-11e5-8a75-841d30426c5d.gif)

**Comment by forki** [comment]
@konste please retry agan. we now remove `<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1" /></runtime>`

**Comment by konste** [comment]
2.32.7 is better and removing empty binding redirects section definitely works, but it is still not good enough. When config file does contain binding redirects section, then Paket still adds extra space! We have 17 files like that in solution. Still too much unnecessary churn.

**Comment by forki** [comment]
don't really know how to fix that. yet
at least not with that .NET API

**Comment by forki** [comment]
do you have bindind redirects completely disabled in paket? even for these 17 files?

**Comment by konste** [comment]
If that is what "redirects: off" at the top of paket.dependencies does - then yes.

**Comment by forki** [comment]
@mrinald can we skip the redirects processing completely in this case?

**Comment by mrinaldi** [comment]
Yep, will do when I have the time.

**Comment by konste** [comment]
For now I decided that space before slash is "standard enough" and I'm going to make all our configs look like that. Now Paket does not seem to change them anymore. One little concern though is that Paket still changes XML formatting as shown in the picture:
<img width="650" alt="2015-12-04 12_03_20-start" src="https://cloud.githubusercontent.com/assets/2653844/11600412/47e3944c-9a81-11e5-8e70-0ee730d30f86.png">
But after I correct formatting manually Paket leaves it alone, which is good enough for all practical purposes. After all VS can reformat XML in one click. 

Let's keep the issue open waiting for @mrinaldi to bypass config sniffing completely when possible.

**Comment by forki** [comment]
Latest version should not do this anymore

**Comment by jackfoxy** [comment]
Yep, this is a problem for us too, add and update both are wiping out the binding redirects in our app.config files. (As of 24 hours ago using the latest from nuget. I see @forki 13 hours ago says the latest fixes this. If it changed within those 11 hours I have not tested.)

**Comment by forki** [comment]
my comment was 13 days ago.
are you using redirect:force option?

**Comment by jackfoxy** [comment]
No, not using redirect or force. Here is the most common binding redirects Paket is overwriting. I can't remember why we need the FSharp.Core redirect, but we do need it. I think Paket wrote the `<Paket>True</Paket>` lines when I converted from nuget to paket. That may be the problem and why Paket thinks it can just eliminate these redirects.
 
`<dependentAssembly>`
    `<Paket>True</Paket>`
    `<assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />`
    `<bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.4.0.0" />`
  `</dependentAssembly>`
  `<dependentAssembly>`
    `<Paket>True</Paket>`
    `<assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />`
    `<bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.3.0.0" />`
  `</dependentAssembly>`

**Comment by forki** [comment]
Use "nuget fsharp.core redirects:force" in your dependencies file. We
needed to change that default.
