### ISSUE TITLE
Very slow `packet install`

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#1249]
![1](https://cloud.githubusercontent.com/assets/873919/11332426/ac263792-91d6-11e5-8393-81741737be52.gif)

It takes 1m 40s. It took about 6 seconds before I updated to 2.25 or so.

**Comment by forki** [comment]
Yes. seems I broke something.

**Comment by forki** [comment]
but what about the second run?
I think we invalidated all the cache in this version.

**Comment by vasily-kirichenko** [comment]
Same for subsequent runs.

**Comment by vasily-kirichenko** [comment]
No significant CPU load.

**Comment by forki** [comment]
thx. so I need to investigate. thx
(do you by any chance know the exact version where it becomes slow?)

**Comment by vasily-kirichenko** [comment]
2.25 is indeed slow. Sorry, cannot say if any older ones are also slow.

**Comment by vasily-kirichenko** [comment]
1m 38s for the seconds run. Very stable results.

**Comment by forki** [comment]
can you do a "paket.bootstrapper.exe 2.x" to the version you had before? just see that there is no network trouble or something like that

**Comment by vasily-kirichenko** [comment]
2.24.0 - 58s
2.23.0 -13s

**Comment by forki** [comment]
thx

**Comment by vasily-kirichenko** [comment]
2.23.4 - 14s

**Comment by vasily-kirichenko** [comment]
so it's certainly 2.24.0

**Comment by forki** [comment]
this sounds like we introduced this during the new code for "v3-only feeds".

can you show the paket.dependency file lines with the source feed configs?

/cc @xavierzwirtz

**Comment by vasily-kirichenko** [comment]
```
redirects: on
framework: net45, net451, net452, net46
source https://www.nuget.org/api/v2
source http://<a private TeamCity server>/guestAuth/app/nuget/v1/FeedService.svc
```

**Comment by forki** [comment]
Ok thanks. This should not touch the new code. Need to look deeper.

**Comment by vasily-kirichenko** [comment]
(it's unrelated, but still) At the end it consumes much CPU (all versions). Profiler shows this:

![image](https://cloud.githubusercontent.com/assets/873919/11333024/b4efbe5c-91db-11e5-8390-b569817cb754.png)
