### ISSUE TITLE
Paket pack and x86 libraries

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#1250]
I have a problem with paket pack, project templates and x86 libraries. Paket always failes with `Could not load file or Assembly` which I believe is because Paket does `assembly loadFrom filename` on the library to get dependencies. Is this a known problem? I can't recompile the binaries to `AnyCPU` due to interop dependencies

**Comment by forki** [comment]
mhm. can you create a small repro sample?
I assume we need to try/catch that block or do something clever to avoid the loading.

**Comment by trondd** [comment]
I've tried creating a small test solution, but unfortunatelly it does not occure there. It has three libraries, lib1 -> lib2 -> lib3, where lib2 is x86, and I don't get any errors from paket this time, but the problem is still there in the large-scale project. I'll take a look at the paket source code and see if I can figure it out.

**Comment by forki** [comment]
You should be able to debug:
* open VS
* set startup project to paket.exe
* set working dir to root of your repository
* set startup argument to "pack..."

**Comment by forki** [comment]
closing since we have no repro.
