### ISSUE TITLE
Use Chessie package from Nuget

### ISSUE THREAD

**Issue by xavierzwirtz** [fsprojects/Paket#1253]
I am referencing Paket.Core in a project, as well as using Chessie. The way Paket includes a full copy of Chessie is causing lots of pain and suffering translating between the Paket Chessie and the regular Chessie assembly. Would it be possible to switch Paket.Core to reference the Chessie Nuget package?

**Comment by forki** [comment]
I would prefer to internalize the types instead. Let me see if I get that
working.
BTW: why do you need chessie as a nuget package?

**Comment by xavierzwirtz** [comment]
Sweet. This has been resulting in this error, been making me feel like a crazy person:
```
This expression was expected to have type
Chessie.ErrorHandling.Result<Microsoft.FSharp.Core.string,Microsoft.FSharp.Core.string>
but here has type
Chessie.ErrorHandling.Result<Microsoft.FSharp.Core.string,Microsoft.FSharp.Core.string>
```

I need it because I another library that references Chessie, so the fact that I get two versions of the Chessie types, one from Chessie, and one from Paket,  causes the compiler to freak out.

**Comment by xavierzwirtz** [comment]
[Looks like in C# land you would fix this via `extern alias`](http://stackoverflow.com/a/517169/4358412). Cant do that in F# though :cry:

**Comment by forki** [comment]
mhm I tried to internalize the file, but it was harder than expected. ==> I guess I'd accept a PR whch replaces the file reference with proper NuGet package

**Comment by xavierzwirtz** [comment]
Alright, Ill clean up my changes and submit it. I already did that locally so that I could continue working, everything seems to be fine.

**Comment by xavierzwirtz** [comment]
Could I ask why you referenced Chessie like that originally? Did you just want one less dll dependency?

**Comment by forki** [comment]
originally we just wanted to extract chessie as a plain file. creating a nuget package was only because of C# users. we never intended F# projects to use the nuget package

**Comment by xavierzwirtz** [comment]
Would that not always result in this problem though? It would be impossible for you to use two libraries that referenced chessie that way, the types would conflict.

**Comment by forki** [comment]
Yeah but we planned to do automatic "internalizing". But didn't work yet

**Comment by xavierzwirtz** [comment]
Ahhh. That makes sense.
