### ISSUE TITLE
Could not load resources

### ISSUE THREAD

**Issue by vilinski** [fsprojects/Paket#1259]
No clue how to fix it or whether it is a proxy problem.

From cmd

> paket install
Paket version 2.27.14.0
Resolving packages for group Main:
Paket failed with:
        Could not load resources from https://api.nuget.org/v3/index.json

or from atom: if I send following code to FSI

    Paket.Dependencies.Install """
        source https://nuget.org/api/v2
        nuget FSharp.Data
        nuget Suave
    """;;

also tried `source http://api.nuget.org/v3/index.json` and `source https://api.nuget.org/v3/index.json`

	> > > System.Exception: Could not find versions for package Suave in any of the sources in ["http://api.nuget.org/v2"].
	   bei Paket.NuGetV2.versions@656-2.Invoke(String message)
	   bei Paket.NuGetV2.GetVersions(String root, IEnumerable`1 sources, PackageName packageName)
	   bei Paket.UpdateProcess.lockFile@173.Invoke(ResolverStrategy resolverStrategy, GroupName groupName, PackageName packageName)
	   bei Paket.UpdateProcess.getSortedAndCachedVersionsF@14(FSharpFunc`2 getSortedVersionsF, Dictionary`2 allVersions, FSharpList`1 sources, ResolverStrategy resolverStrategy, GroupName groupName, PackageName packageName)
	   bei Paket.UpdateProcess.getPreferredVersionsF@31-2.GenerateNext(IEnumerable`1& next)
	   bei Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
	   bei Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
	   bei Microsoft.FSharp.Collections.SeqModule.oneStepTo@1402[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
	   bei Microsoft.FSharp.Collections.SeqModule.f@4728-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
	   bei Microsoft.FSharp.Collections.SeqModule.result@1418.Invoke(Int32 i)
	   bei Microsoft.FSharp.Collections.IEnumerator.unfold@236.DoMoveNext(b& )
	   bei Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
	   bei Microsoft.FSharp.Collections.IEnumerator.next@224[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)
	   bei Microsoft.FSharp.Collections.IEnumerator.filter@219.System-Collections-IEnumerator-MoveNext()
	   bei Microsoft.FSharp.Collections.SeqModule.oneStepTo@1402[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
	   bei Microsoft.FSharp.Collections.SeqModule.f@4728-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
	   bei Microsoft.FSharp.Collections.SeqModule.result@1418.Invoke(Int32 i)
	   bei Microsoft.FSharp.Collections.IEnumerator.unfold@236.DoMoveNext(b& )
	   bei Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
	   bei Microsoft.FSharp.Collections.SeqModule.IsEmpty[T](IEnumerable`1 source)
	   bei Paket.PackageResolver.step$cont@310[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpFunc`2 getVersionsF, FSharpSet`1 openRequirements, PackageRequirement currentRequirement, FSharpRef`1 availableVersions, FSharpRef`1 compatibleVersions, FSharpRef`1 globalOverride, Unit unitVar)
	   bei Paket.PackageResolver.step@263[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpRef`1 lastConflictReported, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, Dictionary`2 conflictHistory, HashSet`1 knownConflicts, FSharpMap`2 filteredVersions, FSharpMap`2 currentResolution, FSharpSet`1 closedRequirements, FSharpSet`1 openRequirements)
	   bei Paket.PackageResolver.Resolve[a](GroupName groupName, a sources, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpOption`1 strategy, FSharpList`1 globalFrameworkRestrictions, FSharpSet`1 rootDependencies, UpdateMode updateMode)
	   bei <StartupCode$Paket-Core>.$DependenciesFile.resolveGroup@476-1.Invoke(GroupName groupName, b _arg1)
	   bei Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
	   bei Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
	   bei Microsoft.FSharp.Collections.MapModule.Map[TKey,T,TResult](FSharpFunc`2 mapping, FSharpMap`2 table)
	   bei Paket.UpdateProcess.selectiveUpdate(Boolean force, FSharpFunc`2 getSha1, FSharpFunc`2 getSortedVersionsF, FSharpFunc`2 getPackageDetailsF, LockFile lockFile, DependenciesFile dependenciesFile, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode)
	   bei Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode, Boolean force)
	   bei Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
	   bei <StartupCode$Paket-Core>.$PublicAPI.Install@155.Invoke(Unit unitVar0)
	   bei Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
	   bei Paket.Dependencies.Install(InstallerOptions options)
	   bei Paket.Dependencies.Install(Boolean force, Boolean hard, Boolean withBindingRedirects, Boolean createNewBindingFiles, Boolean onlyReferenced, SemVerUpdateMode semVerUpdateMode)
	   bei <StartupCode$FSI_0004>.$FSI_0004.main@()
	Stopped due to error

**Comment by forki** [comment]
Sounds like an issue with v3 feeds. 
Will try to reproduce tomorrow 

/cc @xavierzwirtz

**Comment by forki** [comment]
mhm. integration test in b5f5d53 seems to work.

**Comment by xavierzwirtz** [comment]
Works just fine for me as well. If you roll back to version `2.23.0` of paket, does it work? It sounds like you are using a proxy, I may have broken proxy support.

**Comment by vilinski** [comment]
Lost a half of today to configure my §&%$ corporate proxy for all kinds of Apps. Now cannot reproduce the issue anymore, sorry. 
I suspected proxy also, because VS was asking for credentials as I managed my NuGet packages.

P.S. For all behind corporate proxy - almost all windows programs are working good with [cntlm](http://cntlm.sf.net/).
