### ISSUE TITLE
Referencing XAML resources

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#1260]
When I you reference to [MahApps.Metro.Resources](https://www.nuget.org/packages/MahApps.Metro.Resources/)

Paket add following code into project file
```
    <Content Include="Resources\Icons.xaml">
      <Paket>True</Paket>
    </Content>
```
In the same time NuGet add it like 
```
    <Page Include="Resources\Icons.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
```

As a result when MSBuild does not compile `xaml` file and application crashes in the runtime when tries to load resources.

**Comment by sergey-tihon** [comment]
One more note, project previously used NuGet, it contains `<Page>` node, so Paket added duplicate files with `<Content>` nodes.

As well as Paket adds
```
<Content Include="Resources\Entypo.ttf">
      <Paket>True</Paket>
</Content>
```
even if NuGet already added this as
```
<Resource Include="Resources\Entypo.ttf" />
```
(leads to duplication in file explorer)

**Comment by forki** [comment]
I assume our xaml support is pretty poor (read as non-existent). We could
need some help here.

**Comment by sergey-tihon** [comment]
Not sure that I know how to support all cases...
 
- Migration from NuGet
- Install dependencies correctly
- Track/Update such dependencies

Could please mark this issues and `up-for-grabs` and mention some files that should be changed according to you feelings :smirk:

**Comment by forki** [comment]
I assume the fix is needed in https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/ProjectFile.fs#L447

**Comment by forki** [comment]
ping
