### ISSUE TITLE
paket pack fails when there is no build configuration named "Release"

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#1262]
csproj (irrelevant lines removed):
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>..\..\build\bin\dialer\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

As you can see we only have the "Release|x86" config. Paket 1.32 packed this just fine with `type project` in `paket.template`, but 2.28 yields:
```
.paket/paket.exe pack output build/deploy
Paket version 2.28.0.0
Paket failed with:
	Unable to find Release output path node in file above.csproj
```

I don't know how the "find output path" logic changed in particular, but maybe use "Release.*" as a fallback when looking for the `OutputPath`.

**Comment by forki** [comment]
I created a failing test in 106215a

@amazingant do you have an idea how we can handle this?

**Comment by amazingant** [comment]
@forki I know this isn't the desired answer, but this behavior looks correct to me. The shortened project file from @agross says on line 6 to target `AnyCPU` if a platform isn't specified, and there isn't a `Release` build configuration for `AnyCPU`. IMO, fixing this accurately would mean adding a `platform` parameter to paket's pack command, or perhaps just some kind of `projectflag` parameter that could be given multiple times? e.g., `paket pack output build/deploy projectflag Platform=x86`.

To quickly patch over this and get the issue resolved, `ProjectFile.GetOutputDirectory` could just call `GetPropertyWithDefaults` multiple times with different platform options and use the first one with a result.

**Comment by agross** [comment]
@amazingant One could argue the project file is incorrect. What should be fixed, in your opinion?

I'm not saying paket shouldn't change its "finding" logic, rather that VS created the csproj and it seems legit to VS, but not paket.

**Comment by forki** [comment]
(just to clarify why the older version worked. At that time we didn't analyzed at all, so by pure luck it worked)

**Comment by amazingant** [comment]
@agross Knowing that you can do this in VS' configuration manager, your project file looks perfectly legitimate to me:

![untitled](https://cloud.githubusercontent.com/assets/1761309/11443667/e4c53f30-94ec-11e5-9206-a39ff334fd0b.png)

(I *think* VS keeps this information in the solution file?) Unfortunately, paket doesn't know about this "Debug means x86 for project Y and AnyCPU for project Z" info.

Perhaps the best way to handle this would be to add an optional parameter to the `pack` command, and if it isn't provided, try all of the known platform targets and see if any result in an output path. It would allow being explicit about what you want, but it would also resolve your issue without you having to change anything.

Your thoughts, @forki? There's a nice list of platforms from the C# compiler documentation [here][1] that paket could check against.

[1]: https://msdn.microsoft.com/en-us/library/zekwfyz4.aspx

**Comment by forki** [comment]
mhm. at the moment we don't report any path, right? Maybe we should default to whatever we find with release then!?

**Comment by agross** [comment]
@amazingant 

> I *think* VS keeps this information in the solution file?

Yes, this is the case here.

> and if it isn't provided, try all of the known platform targets and see if any result in an output path

That would be fine with me. In this case, perhaps log some warnings about that and tell the user what platforms have been tried and which has been selected.

**Comment by agross** [comment]
@amazingant 

Thank you very much, our build turned green again :-)

I think the output can be improved when you have multiple `paket.template` files. What do you think?

```
No platform specified; found output path node for the x86 platform after failing to find one for the following: AnyCPU32BitPreferred, AnyCPU
No platform specified; found output path node for the AnyCPU platform after failing to find one for the following:
No platform specified; found output path node for the AnyCPU platform after failing to find one for the following:
No platform specified; found output path node for the x86 platform after failing to find one for the following: AnyCPU32BitPreferred, AnyCPU
No platform specified; found output path node for the AnyCPU platform after failing to find one for the following:
No platform specified; found output path node for the AnyCPU platform after failing to find one for the following:
Packed: Foo\paket.template
Packed: Bar\paket.template
Packed: Baz\paket.template
```

**Comment by amazingant** [comment]
@agross Just took a look at the build output for one of my projects and saw the same. Initially confused me seeing `after failing to find one for the following:` with nothing "following". I'll take a look at this when I get a chance, and see if I can clean it up.

**Comment by agross** [comment]
:+1: That would be great!
