### ISSUE TITLE
Wired behaviour of package resolution when pinning some dependecies

### ISSUE THREAD

**Issue by BADF00D** [fsprojects/Paket#1263]
Hi,
Situation: 
Nearly daily we publish new nuget packages containing the newest stuff. Within a repository that uses the new packages, there are two solutions (not my idea, restricted by my company). One uses the newest stuff, the other solution containing legacy apps. In order to avoid frequent updates on that legacy apps, their uses a separate group LegacyApps within paket.dependencies and the referenced version are pinned. 

Now I want to update packages in LegacyApps to a slightly newer, but not the newest version. So I changed the version of dependency Service and Service.Contracts from 1.1.1.2 to 1.1.31.2. Now the problem occurs. Service has a dependencies to Service.Core >= 1.1.31.2 and this has a reference to Service.Contracts >=1.1.31.2. 
```
Could not resolve package Service.Contracts:
 - Dependencies file requested: 1.1.31.2
 - Service 1.1.31.2 requested: >= 1.1.31.2
 - Service.Core 1.1.47.0 requested: >= 1.1.47

Please try to relax some conditions.
```
Paket see that Service request an version that must be at least 1.1.31.2 and it takes the newest one 1.1.47. But the newest one has a dependency to the newest Service.Contracts 1.1.47. If paket would use Service.Core 1.1.31.2 there would be no problem. 

The only way to solve this problem for now is, to pin all transient dependency to the same version. But with this solution I have to track transient references myself, which I wanted to avoid by using paket. 

Is there a option I missed?

**Comment by forki** [comment]
Can you please post your dependencies file? 
I assume it's all on internal feeds?

**Comment by forki** [comment]
(even if you show only the essential part of the deps file we might find a test with fake data)

**Comment by forki** [comment]
this is what I understnad dso far:

    let depsFile = """
    source https://nuget.org/api/v2
    
    nuget Service 1.1.31.2
    nuget Service.Contracts 1.1.31.2
    """
    
    let graph = [
        "Service","1.1.31.2",["Service.Core",VersionRequirement(VersionRange.AtLeast "1.1.31.2",PreReleaseStatus.No)]
        "Service","1.1.47",["Service.Core",VersionRequirement(VersionRange.AtLeast "1.1.47",PreReleaseStatus.No)]
        "Service.Core","1.1.31.2",["Service.Contracts",VersionRequirement(VersionRange.AtLeast "1.1.31.2",PreReleaseStatus.No)]
        "Service.Core","1.1.47",["Service.Contracts",VersionRequirement(VersionRange.AtLeast "1.1.47",PreReleaseStatus.No)]
        "Service.Contracts","1.1.31.2",[]
    ]

but this resovles correctly.

**Comment by BADF00D** [comment]
Sorry for the answering so late. Unfortunately I can't reproduce the situation I was confronted with 5 days ago. I'm going to close this ticket. Sorry for taking your time. 
If this problem arises next time, I'm going to create a new ticket with more detailed information.
