### ISSUE TITLE
paket pack includes referenced dlls from project that have paket.template files

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#1264]
I have a solution with three projects. One project has base classes for the other two projects so two projects reference one project as project reference. All three projects have paket.template files in their directories.

The documentation says:

>In a project template, the files included will be:
>
>    the output assembly of the matching project (in the correct lib directory if a library, or tools if an exe)
>    the output assemblies of any project references which do not have a matching template file

However, for those two projects, the referenced project dll is included in their packages and no package reference is added to the first project package.

What is the correct configuration for this feature to work?

**Comment by forki** [comment]
do you have "type project" in the template files?

/cc @mavnn

**Comment by alexeyzimarev** [comment]
Yes, I figured out. I need to run it without specifying template files one by one, just let it discover them. It works ok then.

**Comment by forki** [comment]
cool
