### ISSUE TITLE
.NET 4.6.1 support?

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#1270]
Now project files contain something like this:

```xml
<Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.6')">
      <ItemGroup>
        <Reference Include="FSharp.Core">
          <HintPath>..\..\packages\FSharp.Core\lib\net40\FSharp.Core.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
```

If I set target framework version to 4.6.1 (VS 2015 Update 1), then all the references are disappear and nothing compiles.

**Comment by vasily-kirichenko** [comment]
2.30.0.0:
```xml
        </Reference>
       </ItemGroup>
     </When>
-    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1')">
+    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.6')">
       <ItemGroup>
         <Reference Include="AlphaFS">
           <HintPath>..\..\packages\AlphaFS\lib\net451\AlphaFS.dll</HintPath>
```

**Comment by forki** [comment]
you are using `>= net45` ?

maybe there is still an issue with ordering, but integration tests show that 4.6.1 is emitted in many places. let me check again.

**Comment by forki** [comment]
are you sure you used latest? c349139 shows the sample with AlphaFS and it creates the 4.6.1 tag.

What else can be wrong?

**Comment by vasily-kirichenko** [comment]
I don't know. I added `Or $(TargetFrameworkVersion) == 'v4.6.1'` by hand. Everything compiles. Now I `paket install` and it removes `Or $(TargetFrameworkVersion) == 'v4.6.1'` from all the projects. And, of course, `paket install --redirects` does not add redirects for `FSharp.Core` any -> 4.4.0.0

**Comment by forki** [comment]
@vasily-kirichenko does work for you on the integration test? do you have minimal repro?

@mrinaldi any ideas about the redirects?

**Comment by vasily-kirichenko** [comment]
I revert `<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>` => `<TargetFrameworkVersion>v4.6</TargetFrameworkVersion>`, then `paket install` and everything ok now, including redirects:
```xml
<dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.4.0.0" />
</dependentAssembly>
```

**Comment by forki** [comment]
mhm. that's interesting.
I will try this in the test case.

**Comment by forki** [comment]
I'm not sure if the TargetFrameworkVersion change was related, yet.
But for me the binding redirects don't get updated as well. @mrinaldi if you find some time then could you please take a look at https://github.com/fsprojects/Paket/pull/1273? thx

**Comment by mrinaldi** [comment]
#1273 doesn't add the redirects because it's not needed. (the test still fails if you change the project to target v4.6)

If you add to the project the `Yaaf.FSharp.Scripting` package, however, it generates the redirects for FSharp.Core.

@vasily-kirichenko do you have a small repro for the redirects?

**Comment by forki** [comment]
But I explicitly stated that I want them in dependencies file?

**Comment by mrinaldi** [comment]
Explicitly stating a dependency should have redirects is any different than stating a global redirects?

I guess not. In that case, it'd behave like the global one and generate only the redirects for needed assemblies. Am I wrong here?

**Comment by forki** [comment]
No you are right behavior should be the same. I just wonder how I can add
redirects now. Especially with fsharp.core ww often have conflicts with GAC
versions.

**Comment by mrinaldi** [comment]
I guess you can't since #1187.

What do you suggest?
Should we take the GAC assemblies into account, should we have a `redirects: force`? Maybe both?

**Comment by forki** [comment]
The issue with GAC is that you can't know the GAC of the deployment
machine. So yes a force option would be awesome.

**Comment by vasily-kirichenko** [comment]
:+1: 

Relying on the machine's GAC where you run `paket install` is fragile.
