### ISSUE TITLE
paket.bootstrapper.exe all versions fails on "init"

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#1271]
It looks like Github API change issue, all versions of paket.bootstrapper.exe that I have and I am sure worked before, started to fail the "init" with 

> Input string was not in a correct format. (Github)

**Comment by forki** [comment]
shit

**Comment by forki** [comment]
can you explain what you are doing in more detail? just tried bootstrapper and it worked for me

**Comment by alexeyzimarev** [comment]
Hm, I created another project and it works there. But definitely I have this in one solution that I just created:

> C:\Dev\Worker\Frameworks\Test1\src>.paket\paket.bootstrapper.exe init
> Version init requested.
> *Input string was not in a correct format. (Github)*

**Comment by alexeyzimarev** [comment]
![2015-12-01_10-46-56](https://cloud.githubusercontent.com/assets/2821205/11497384/e8d578f4-9818-11e5-8527-bfafa829bf07.png)

**Comment by alexeyzimarev** [comment]
Damn silly me. I need to run the bootstrapper without parameters. Sorry
