### ISSUE TITLE
Paket keeps flapping .0 at the end of the package versions

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1282]
It looks like Paket randomly (?) adds or removes ".0" at the end of the package version every time the version changes. For instance, looking at the history of the paket.lock file I can see these changes:

Costura.Fody (1.3.3) -> Costura.Fody (1.3.3.0)
Costura.Fody (1.3.3.0) ->  Costura.Fody (1.3.3)
Costura.Fody (1.3.3) -> Costura.Fody (1.3.3.0)
Costura.Fody (1.3.3.0) ->  Costura.Fody (1.3.3)
... ... ...

It does not happen for all packages, but for many, for instance: 
Microsoft.Web.Infrastructure, PagedList, JSNLog, IKVM, MimeKit, etc.

**Comment by forki** [comment]
Mhm this seems to be related to which protocol responds the fastest. I will
try to find a solution.

**Comment by forki** [comment]
is this only with nuget.org?

**Comment by forki** [comment]
please check if this works for you. we only do this for nuget.org since other servers fail on NormalizedVersions

**Comment by konste** [comment]
It will take some time to make sure it is fixed as the problem was intermittent by nature.

**Comment by forki** [comment]
yes I know....
