### ISSUE TITLE
binding redirects from the last group always win.

### ISSUE THREAD

**Issue by Karamell** [fsprojects/Paket#1284]
This is probably related to #1218 . 

If i clone paket and then run `paket install --redirects` (on paket itself) all App.config is rewritten to only contain binding redirects from the _last_ group in the lock file. Easily reproduced.

Am I using packet wrong?

**Comment by forki** [comment]
I don't think this is what's going on. The last group from the lockfile is "Test" and I don't see NUnit Bindings.

Try `paket install --redirects --hard` and it basically removes all entries since the current logic decides there are no conflicts. The FSharp.Core entries are still needed so we discussed with @mrinaldi that we need a `force` option.

**Comment by Karamell** [comment]
I'm sorry I misunderstood. The missing FSharp.Core is a different problem.

Try and add modify the app.config-file to this:
```xml
<dependentAssembly>
 <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="7.0.0.0" />
    <Paket>True</Paket> <!-- important -->
       <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="7.0.0.0" />
</dependentAssembly>
```

you'll see it will be removed.

The next run Paket will first be add the bindings from the Main group, then removed everything in the Build group... and again in the Test group.

the `<Paket>True</Paket>` concept does not work with groups.

**Comment by forki** [comment]
tried to fix this in https://github.com/fsprojects/Paket/pull/1286 - @mrinaldi do you think this is correct?

**Comment by forki** [comment]
@Karamell I activated this in 2.23.2 could you please check if it works for you?

**Comment by Karamell** [comment]
it works for me @forki Both my own project and the paket project is ok.

Thanks for fixing it so fast   CI/CD FTW!
