### ISSUE TITLE
Package ExpressiveAnnotations.dll was referenced, but it was not found in the paket.lock file in group Main

### ISSUE THREAD

**Issue by jschroed** [fsprojects/Paket#1288]
I get a "Paket failed with" message when I do paket update command. It seems to be caused by a project reference (ProjectReference) in my csproj file.

I have a solution setup where I have Project A include a reference to Project B. Project B includes a reference to a 3rd-party package: ExpressiveAnnotations.dll. The setup is like this with the -> indicating a dependency:
A -> B
B -> ExpressiveAnnotations.dll

I created paket.refereneces files that are like this: Project B includes ExpressiveAnnotations.dll. Project A does not include ExpressiveAnnotations.dll.

I started seeing this issue in paket versions 2.22.0 (2.21.3 does not fail) and 2.22.0_alpha003 (2.22.0-alpha002 does not fail) in the pre-releases. My csproj file is updated correctly but I see this error message.

I wouldn't think that I would need to include "ExpressiveAnnotations.dll" in Project A. (I'm thinking that this is a transitive dependency.) My question are: should paket work without having to include "ExpressiveAnnotations.dll" in Project A? And if I don't need to include it, is there a way I can avoid this error message?

I tried setting "references: strict" and a few other things in my paket.dependencies but I was still getting that error with newer versions of paket.

**Comment by forki** [comment]
Can you please give the exact error message?
Is there a way for me to reproduce?

**Comment by jschroed** [comment]
The exact error is:
Package ExpressiveAnnotations.dll was referenced, but it was not found in the paket.lock file in group Main

To reproduce, create a new project/solution in Visual Studio. Add a new project to the solution so that there are 2 projects. In project 1, add a "Project/Solution reference" to project 2. (To add a project reference, go to the solution explorer, expand under the project, right click on references, select add reference. In the Reference Manager window, click on Solution, then projects, and check the box next to Project2.)

In the project1 directory, create paket.dependencies:
source https://nuget.org/api/v2
nuget Newtonsoft.Json

and paket.references:
Newtonsoft.Json

In the project2 directory, paket.dependencies:
source https://nuget.org/api/v2
nuget NUnit

and paket.references:
NUnit

Now, run paket update from a command prompt in the project1 directory, and you should get this error message: 
Paket failed with:
        Package NUnit was referenced, but it was not found in the paket.lock file in group Main.

I have a simple solution I create in VS 2012. It looks like I can't upload zip files here. I could email it or get to you some other means.

**Comment by inosik** [comment]
What you need is a `paket.dependencies` file **per solution**. Each project has it's own `paket.references`.

This image on Paket's homepage explains it:
![Structure](http://fsprojects.github.io/Paket/img/paket-overview.png)

**Comment by jschroed** [comment]
Would it be possible to have paket ignore project references perhaps as an optional flag that can be passed in? Would changing this to a warning (ideally one that we could have be ignored with a flag) be something that could be done?

I don't believe that it necessary at all to have paket check project references like this. When I build project1 from Visual Studio, it will bring in all of the DLLs from project2.

I understand that the issue is that we have a paket.dependencies in each project folder. However, we have a need to do this. When we build on our build server, our build process builds each project individually as a DLL. Part of the process is to remove the project references in each project and add the projects in the paket.references file so that it pulls down the DLLs of projects that it depends on.

When we build in Visual Studio, we keep the project references in place. This way we can develop across projects in our solution. One option that we could do is modify our build process to remove project references, run paket update, and then add the references back in. I think ideally we would prefer to have the option to have paket ignore this but I understand it goes against having one paket.references per solution.

**Comment by inosik** [comment]
Paket checks project references in order to create NuGet packages when calling `paket pack`. 

Why do you strip out project references and replace them with DLL (or NuGet package?) references? Isn't the result the same?

**Comment by forki** [comment]
there are two issues here:

1) you get an error since the paket seems to analyze the second paket.references and it doesn't match the first dependencies file. I will make the error message more clear. but this has nothing to do with project references. We don't use project references in this phase.

2) you should really realy have only one paket.dependencies file per repository. you can still paket restore independently per paket.references.

**Comment by forki** [comment]
just take a look at restore options: http://fsprojects.github.io/Paket/paket-restore.html

**Comment by matthid** [comment]
Hm, not saying that I ever used paket this way. But from the error description I would say this is a paket bug.
```
/solution/sol.sln
/solution/project1/paket.dependencies
/solution/project1/paket.references
/solution/project1/project1.fsproj
/solution/project2/paket.dependencies
/solution/project2/paket.references
/solution/project2/project2.fsproj
```

Why should it not work when running `paket update` in `/solution/project1`? I expect paket to "stay in it's directory" (even with the project reference in place).

Besides that I'm not saying we should support that use-case at all, just curiosity :) (Maybe some feature I don't know about jet :) )

**Comment by forki** [comment]
Can you reproduce? Can you maybe even find the root cause and provide a
fix?

**Comment by matthid** [comment]
Ah wait. Does paket check paket.references for referenced projects? This would actually explain this (and the error message would be perfectly correct actually)

**Comment by forki** [comment]
No it should not.

**Comment by matthid** [comment]
Yes I can reproduce. The problems seems to be the binding redirect generation, because it implicitly assumes all referenced projects use the same `paket.dependencies`. So the question comes down to how we want to handle project references to projects outside the current `paket.dependencies` context (maybe logically belonging to another solution). I have done this before but don't have a good answer on how paket should behave.

I still think the error message is OK, because you have a dependency and somehow drop a transitive dependency of it (which feels like a bug in the overall setup).

**Comment by matthid** [comment]
So technically it is a bug, because the binding redirection code should use the `paket.lock` from the other project? But on the other hand this definitely goes against the "global dependencies" philosophy...

**Comment by forki** [comment]
no there should only be one paket.lock

**Comment by jschroed** [comment]
> just take a look at restore options: http://fsprojects.github.io/Paket/paket-restore.html

I don't believe that will work for us since we need to generate the paket.lock file.

> Why do you strip out project references and replace them with DLL (or NuGet package?) references? Isn't the result the same?

We do this because we package each project as a nupkg. That way we can version each project and isolate issues.

> 1) you get an error since the paket seems to analyze the second paket.references and it doesn't match the first dependencies file. I will make the error message more clear. but this has nothing to do with project references. We don't use project references in this phase.

I'm pretty the issue is with the project references. When I remove them from the csproj file, the error goes away.

> 2) you should really really have only one paket.dependencies file per repository. you can still paket restore independently per paket.references.

I guess the issue is that we are doing something a little different where we have each project build a DLL and use the solution just to hold all of the projects.

For my purposes, having a suppressible warning instead of an error would be best. However, I understand now that the normal use case is to have one paket.dependencies file per solution. A workaround that we could implement is to remove the project references in the csproj file before we call paket.

**Comment by matthid** [comment]
@jschroed From your description "I think" the usual paket workflow is to separate all your projects as different solutions and then automate the process of creating DLLs and releasing nuget packages for them. Then you can test with those new (alpha) releases on the other projects.
Once you feel comfortable with the alpha release (like you are now when all projects are working) you create a real release (possibly on another nuget server?).

Paket helps you automate this (`paket update` is your friend) in a straightforward way.

**Comment by inosik** [comment]
Paket can perfectly create packages from projects and you don't need such hacky stuff. Project references get converted to package dependencies, *if* the other project is going to be a package, too. We do this all the time at work and it works just fine.

**Comment by jschroed** [comment]
Yes, I think the usual workflow would have separate solutions for each DLL. So, I think our way of working is a special case. We have a bunch of projects (about 40) and we wanted a way that developers could build all of the projects locally so that they could work on multiple projects at the same time but in the one solution. We also wanted each project to be built and packaged separately on our build server.

@inosik, I would be interested in using paket to create packages from projects. Is there something that I can look into for this?

**Comment by forki** [comment]
I still don't understand why you need more than one lock file. Could you
please elaborate?

**Comment by jschroed** [comment]
Our thinking was we wanted to keep each project isolated. We have nuspec files for each project and we have a pre-build script that parses the nuspec files and creates the paket.dependencies file.

**Comment by inosik** [comment]
Convert your .nuspecs to `paket.template` files with `type project`. Can't give you a link right now, because I'm on my phone, but Pakets honepage has an explanation of `paket pack` and `paket.template`.

**Comment by forki** [comment]
@jschroed even if you are working nuspec files and nuget.exe for packaging try to move to one deps/lock file approach. Only this ensures consistent dependency managament accross all projects. We created paket in order to avoid having different versions of the same package in different projects. That's basically one of the main reasons to use paket over nuget.

**Comment by jschroed** [comment]
Thanks! This has been a very useful discussion for me. I think it answers my biggest question when I saw this error message: Are we doing something wrong, does paket have an issue, or both?

I think it's becoming clearer that we should be running paket on the solution when we are building the solution. I'm still curious to see if we can make the solution build and the project builds work how we are currently doing them.

I'll work changing my paket configuration to the solution. Thanks for the help so far!

**Comment by jschroed** [comment]
I followed the directions on the main paket website and created just one paket.dependencies for my solution. Things are working much more quickly now and only having one packages directory is an improvement as well.

I'll go ahead and recommend that we move to one paket.dependencies when building the solution like this. I'm still curious if you guys think paket will change or if this is expected behavior. Everything worked fine in this scenario (i.e. the csproj files would be created correctly) but we would see this error message. Thanks again for the comments.

**Comment by forki** [comment]
Since I think having  multiple lock files is really the problem I don't think I want to fix anything here. It would just lead to new pain. IMHO it's much better to have one central lock file per repository (independently to how many projects or solutions you have).
Following this guidance will probably make you much happier in the long run.
