### ISSUE TITLE
User prompts do not work with redirected stdin

### ISSUE THREAD

**Issue by DavidHayden87** [fsprojects/Paket#1291]
We have multiple repositories all using NuGet for package management, and there are a number of steps I currently need to take in each to convert them to using Paket, beyond just calling convert-from-nuget.
I am trying to write a script which does all this for me, and calls into paket.exe for convert-from-nuget and simplify, redirecting the standard input/output so my script can make decisions about what to remove. But am having trouble when the executable prompts about deleting files:

> Paket failed with:
> 	Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.

This seems to be due to using `Console.ReadKey()` which according to the [documentation](https://msdn.microsoft.com/en-us/library/471w8d85(v=vs.110).aspx) cannot read from redirected standard input. I am proposing changing this to use `Console.ReadLine()`, which can read from standard input. The consequence of this, is that users would have to hit y/n followed by enter, rather than just y/n.

Thoughts?

**Comment by forki** [comment]
I don't think that would be an issue.
