### ISSUE TITLE
Embedded dependencies

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/Paket#1294]
Consider I've created a project P1 (with Paket-managed dependencies) and published it to GitHub. Its `csproj` / `fsproj` files are automatically set up to take the dependency DLLs from `P1/packages` directory.

After a while, I am creating the second project P2 that uses P1 as a GitHub dependency (i.e. `github ForNeVeR/P1` in my `paket.dependencies`). Paket correctly acquires P1 dependencies and installs it to `P2/packages`.

_To build P1 and P2 together, I've added P1 project files from `paket-files/ForNeVeR/P1` to the P2 solution. Is there another option for this case?_

But the P1 still wants its dependencies to be in `P1/packages`, not `P2/packages`! And from P2 project perspective that folder is `paket-files/ForNeVeR/P2/packages`, and Paket even don't create it.

Is it the Paket-compatible use case? What could I do instead of `mklink /j P1/packages P1/paket-files/ForNeVeR/p2/packages` (note, that works correctly for me)?

**Comment by forki** [comment]
mhm. that doesn't sound like a use case that we support.

**Comment by ForNeVeR** [comment]
So, the recommended way of doing this will be to publish the packages in question to Nuget?

**Comment by forki** [comment]
We don't support full project dependencies via github yet. Did you look at
git submodule or git subtree instead?

**Comment by ForNeVeR** [comment]
Is it a planned function or not? If not, I will close the issue.

Regarding your suggestion: yeah, thank you, I understood that I have to use something like git submodule or publish the package to Nuget, that's not a problem.

After all, I am already using Paket, and after some small manual modifications (`mklink`) it works.

**Comment by forki** [comment]
it's not planned, but maybe http://7sharpnine.com/Xebec/ will one day be something for you. /cc @7sharp9

**Comment by ForNeVeR** [comment]
Ok, thank you for discussion, I'm closing it.
