### ISSUE TITLE
convMethodRef: could not bind to method

### ISSUE THREAD

**Issue by flypixel** [fsprojects/Paket#1295]
error FS0192: internal error: convMethodRef: could not bind to method
I get this error, when I try to use paket from fsi on Ubuntu, after I call *dependencies.GetInstalledVersion "FSharp.Data"* as in [the example](http://fsprojects.github.io/Paket/reference-from-repl.html) . 
Version of mono is 4.2.1.102.
Paket version 2.33.1.0

**Comment by forki** [comment]
yeah that sounds like FSharp..Core issue.

**Comment by forki** [comment]
did you bind against paket.exe or Paket.core?

**Comment by flypixel** [comment]
paket.exe, like in the example

**Comment by forki** [comment]
Which VS version and f# version?

**Comment by flypixel** [comment]
Sorry I'm at work and fsharp is at home. But it seems that version of fsharp is 4.0.0.1, and of course I don't use Visual Studio (if you mean that by VS), because of 
>on Ubuntu

 I use emacs if it can help, and also  I run script with fsharpi with same result

**Comment by forki** [comment]
Yeah I guess the issue is that we built against FSharp.Core.dll 4.4.xx

**Comment by flypixel** [comment]
OK, I'll check and write reply to you from home. Thanks.

**Comment by flypixel** [comment]
Sorry, only for note: it's the same problem on windows with f# core version 3.3.1.0
Scripts, that i use, are



 in attachment

**Comment by forki** [comment]
yes it's incompatible unfortunately.

2015-12-07 17:44 GMT+01:00 flypixel <notifications@github.com>:

**Comment by flypixel** [comment]
Sorry again, but I checked the version of FSharp.Core and it is 4.4.0.0
>pixel@pixel-X751MD:/usr/lib/cli/FSharp.Core-4.3$ monodis --assembly FSharp.Core.dll 
Assembly Table
Name:          FSharp.Core
Hash Algoritm: 0x00008004
Version:       4.4.0.0
Flags:         0x00000001
PublicKey:     BlobPtr (0x00002087)

**Comment by Bomret** [comment]
Is there any solution to this? I have the same problem with referencing the paket.exe on OS X using Mono.

**Comment by Bomret** [comment]
Ok, found a solution myself: Just reference the Paket.Core nuget package instead of the paket.exe.

**Comment by flypixel** [comment]
ok, thank you, I'll try

**Comment by realvictorprm** [comment]
I'm running into this too. Isn't there anything I can do to fix this?

**Comment by gusty** [comment]
For the record, this error happens in general when you are running from fsi a dll that was built with a higher version of FSharp.Core than the one that your fsi version supports.
