### ISSUE TITLE
Unable to search custom nuget repos

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket#1298]
find-packages command line argument does not pick up the sources in the paket.dependencies file.  Nor when specifying a custom source is it able to find known packages in the repo.

For reference, I'm using a klondike server internal to a company network.

**Comment by cdrnet** [comment]
I've observed the same, with an internal Artifactory feed.

**Comment by forki** [comment]
as described in https://github.com/fsprojects/Paket.VisualStudio/issues/87 it's not implemented, yet. I marked it up-for-grabs.

**Comment by cdrnet** [comment]
An OData query to search for a package containing "Abc.Def" could look like this (tested against Artifactory):

    feeduri/Packages()?$filter=IsLatestVersion and IsAbsoluteLatestVersion and substringof('Abc.Def',Id)

**Comment by forki** [comment]
So you are basically half way there.

**Comment by cdrnet** [comment]
Yes :) ... just didn't have time yet to do the other half as well. I'll open a PR.

**Comment by cdrnet** [comment]
This is working for me (thanks again!).
@pms1969 for you as well? If so we can close this.

**Comment by pms1969** [comment]
I'll check tomorrow when I get into work.

**Comment by pms1969** [comment]
Works a treat.  Thanks.
