### ISSUE TITLE
Paket 2.36.0 breaking for C# projects when building from template files (Missing: Version)

### ISSUE THREAD

**Issue by richard-green** [fsprojects/Paket#1302]
Paket failed with:
        Incomplete mandatory metadata in template file D:\[redacted]\paket.template (even  including assembly attributes)
Template: {Id = Some "Shared.Rabbit.CSharp";
 Version = null;
 Authors = Some ["---"];
 Description =
  Some "Functional RabbitMQ integration for projects (C# wrapper)";
 Symbols = false;}
Missing: Version
Running build failed.
Error:
System.Exception: Error during packing ..
   at Fake.Paket.Pack@78.Invoke(String message) in C:\code\fake\src\app\FakeLib\PaketHelper.fs:line 78
   at Fake.Paket.Pack(FSharpFunc`2 setParams) in C:\code\fake\src\app\FakeLib\PaketHelper.fs:line 78
   at FSI_0001.Core.clo@45-1.Invoke(Unit arg10@)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483

**Comment by forki** [comment]
thanks for reporting. I removed that release from github.

Seems my changes in https://github.com/fsprojects/Paket/issues/1289 were not enough.

Any chance you could mail me the dll in question to sforkmann @ gmail?

**Comment by richard-green** [comment]
Thank you - I've emailed you the DLL, hope it didn't get blocked

**Comment by forki** [comment]
I got the mail and will investigate

**Comment by forki** [comment]
This is really strange. My test shows that paket can extract the version. Is there any chance that I can the template file and csproj file in order to try "paket pack" on it. 

Or is there any other chance to reproduce this?

**Comment by richard-green** [comment]
Hi, I retried with 2.42.4 and all seems well, happy to close now - thanks for your help
