### ISSUE TITLE
Nuget packages with FrameworkAssembly nodes not working

### ISSUE THREAD

**Issue by mterwoord** [fsprojects/Paket#1306]
I have nuget packages which (only) contain frameworkAssemblies references. paket seems to process the assemblies fine, but doesn't add references to the projects.

**Comment by forki** [comment]
Do you have a concrete repro case?

**Comment by mterwoord** [comment]
Well, We have third party dependencies which we packaged "in" nuget packages.  I'll see If i can come up with an isolated sample.

**Comment by mterwoord** [comment]
Here it is. I have the following package in a private repository:

``` 
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>TempPkg</id>
    <version>0.1</version>
    <title>TempPkg</title>
    <authors>MtW</authors>
    <owners>MtW</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>TempPkg</description>
    <language />
    <dependencies>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Xaml" />
    </frameworkAssemblies>
  </metadata>
</package>
```

When I add it to a project using ```paket add nuget TempPkg project PaketTest```, the reference doesn't show up. 
Note, PaketTest is a .net 4.5 console app in my testing.

**Comment by mterwoord** [comment]
Verified. My test project works now. Now only have to test it in my actual project.. :)
