### ISSUE TITLE
Project file path's get stripped?

### ISSUE THREAD

**Issue by teilin** [fsprojects/Paket#1310]
I have just been looking into paket and on one project I used the convertion from NuGet to Paket. That worked perfect.

When I run the paket install command, this also works as I expect it to do until it is going through the project files. The error message I get is "Unable to parse" and "Could not find file". From what I see, it looks like it do not like that I have one folder with the name XXX and a folder inside there with the same name (XXX).

So my project file is located in **C:\Projects\ProjectName\Entities\Entities\ProjectFile.csproj**. When **paket install** go through, it will find **C:\Projects\ProjectName\Entities\ProjectFile.csproj**.

For me it looks like Paket is stripping away some of the path's.

**Comment by forki** [comment]
Is there a chance that you mail me the program or is there any chance to
reproduce?

**Comment by teilin** [comment]
Unfortunately, it is not possible to send the program. I can try to create a small dummy project later today to see if I can reproduce it there. If I am able to do that, I can add that dummy project.

**Comment by forki** [comment]
That would help me a lot. Thanks

**Comment by teilin** [comment]
Okey, then I will do my best to reproduce this in a dummy project when I get home from work today.

**Comment by teilin** [comment]
Now I have tried to create a dummy project, but I am not able to get the same messages that I got in the project I started to use Paket. I guess that this issue can be closed and if i later are able to reproduce or something report again.

**Comment by forki** [comment]
Are you still getting this in the original repo? Can you run "paket install
-v"?

**Comment by teilin** [comment]
Okey, now I have been running **paket install -v** and I still get the same messages in the project. I can give you a a screenshot. This is maybe not exactly the case I sayed above, but that case is happeing as well in the beginning of the install process. But this is also a bit strange and I do not see why it happen.

![paketinstall](https://cloud.githubusercontent.com/assets/311637/11817672/4b250f18-a356-11e5-838e-b1168320c6a7.png)

**Comment by forki** [comment]
mhm. that's strange

not sure how to go forward without a repro case.

**Comment by Vilmir** [comment]
We have a similar error message, even though it does not seem to have an actual impact. Projects not found are correctly migrated to Paket.
As for @teilin, we cannot provide the projects for reproing :(

**Comment by forki** [comment]
If anyone is interested in debugging fixing this on your network:
* Clone paket repo and open in VS
* set paket.exe as startup project and set working dir to your comapny repo
* set startup argument to "install"
* hit F5 and try to see what happens.

If you find some time then this would be really really helpful.

**Comment by mexx** [comment]
@teilin my guess from the screenshot, it's the problem with the inter project dependencies.
Can you look at the `ProjectReference` node for the `Entities` project in the `SecurityIntegrationTests.csproj` file.
What is the value of the `Include` attribute?

**Comment by teilin** [comment]
Thaks @mexx. I see that the `ProjectReference` to the `Entities` project was wrong.

**Comment by forki** [comment]
is there something we could imrprove in Paket`?

**Comment by teilin** [comment]
I have not had time to look into it more than just seeing that the path was wrong in the project file. I can not think of any improvements in Paket that could fixed it. I guess the issue can be closed.
