### ISSUE TITLE
Simplify the update process

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#1312]
Currently, requesting to update one nuget package initiates a lengthy process for all packages (not sure why is that). In a project with tens of packages this takes significantly longer time than by using nuget package manager, which is frustrating. For internal packages that change often this creates issues for developers that need to update them often.

**Comment by forki** [comment]
IIRC nuget doesn't recompute the whole dependency tree and this allows to introduce conflicts (in very rare cases). We don't want to go that route in paket.

Usually updating a single package should still be relatively fast since we "soft pin" most dependencies and this should keep traffic low. But there might be still some edge case where paket isn't smart enough yet. We would need good samples to reproduce that.

**Comment by alexeyzimarev** [comment]
Doesn't paket already have the whole dependency tree in paket.lock and just need to fetch new dependencies from the package that is being updated, fix the lock file accordingly and have the tree ready?

**Comment by forki** [comment]
yes. in most cases.

but the new updated version might bring in new requirements that break the whole dependency graph. these things exist in the real world. We need to recompute then. The strange things is: usally (if nothing important changes) the process is smart and very fast. So it must find something strange in your case and recompute too much.

**Comment by alexeyzimarev** [comment]
$ .paket\paket update                                                                           
Paket version 2.27.14.0                                                                         
Resolving packages for group Main:                                                              
 - xunit is pinned to 2.0                                                                       
 - Services.DataAccess 0.2.0-unstable0013                                                  
 - Services.DataAccess.InMemory 0.2.0-unstable0013                                         
 - EventSourcing 2.0.0-unstable0052                                                        
 - EventSourcing.EventStore 2.0.0-beta0037                                                 
 - EventSourcing.Subscriptions 2.0.0-beta0009                                              
 - EventSourcing.Testing 2.0.0-unstable0052                                                
 - Services.Base 0.1.0-ci0007                                                              
 - Autofac 3.5.2                                                                                
 - Autofac.Extras.ServiceStack 2.0.2                                                            
 - AutoFixture 3.37.3                                                                           
 - AutoFixture.AutoNSubstitute 3.37.3                                                           
 - AutoFixture.Xunit2 3.37.3                                                                    
 - FAKE 4.10.5                                                                                  
 - FluentAssertions 4.1.1                                                                       
 - Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.1                                     
 - Microsoft.Net.Compilers 1.1.1                                                                
 - NSubstitute 1.9.2.0                                                                          
 - Projac.Connector 0.0.139                                                                     
 - Serilog 1.5.14                                                                               
 - Serilog.Sinks.Seq 1.5.27                                                                     
 - ServiceStack 4.0.50                                                                          
 - ServiceStack.Api.Swagger 4.0.50                                                              
 - ServiceStack.Client 4.0.50                                                                   
 - ServiceStack.Interfaces 4.0.50                                                               
 - ServiceStack.Logging.Serilog 2.0.0.9                                                         
 - ServiceStack.RabbitMq 4.0.50                                                                 
 - Topshelf 3.3.1                                                                               
 - Topshelf.Serilog 3.3.1                                                                       
 - xunit.abstractions 2.0.0                                                                     
 - xunit.runner.console 2.1.0                                                                   
 - xunit.runner.visualstudio 2.1.0                                                              
 - xunit.core 2.0.0                                                                             
 - xunit.assert 2.0.0                                                                           
 - ServiceStack.Common 4.0.50                                                                   
 - ServiceStack.Text 4.0.50                                                                     
 - System.Runtime 4.0.20                                                                        
 - System.Collections 4.0.10                                                                    
 - System.Diagnostics.Debug 4.0.10                                                              
 - System.Globalization 4.0.10                                                                  
 - System.Linq.Expressions 4.0.10                                                               
 - System.ObjectModel 4.0.10                                                                    
 - System.Reflection 4.0.10                                                                     
 - System.Runtime.Extensions 4.0.10                                                             
 - System.Text.RegularExpressions 4.0.10                                                        
 - System.Threading 4.0.10                                                                      
 - System.Threading.Tasks 4.0.10                                                                
 - System.Xml.XDocument 4.0.10                                                                  
 - System.Linq 4.0.0                                                                            
 - System.Reflection.Extensions 4.0.0                                                           
 - System.Reflection.Primitives 4.0.0                                                           
 - System.Reflection.TypeExtensions 4.0.0                                                       
 - RabbitMQ.Client 3.5.7                                                                        
 - Microsoft.Net.Http 2.2.29                                                                    
 - CompareNETObjects 3.03.0.0                                                                   
 - EventStore.Client 3.3.1                                                                      
 - EventStore.SerilogAdapter 1.0.0                                                              
 - Ix-Main 1.2.5                                                                                
 - MassTransit 3.0.17                                                                           
 - Mediatr 2.0.2                                                                                
 - Newtonsoft.Json 7.0.1                                                                        
 - Serilog.Sinks.Elasticsearch 2.0.70                                                           
 - System.Collections.Immutable 1.1.37                                                          
 - xunit.extensibility.core 2.0.0                                                               
 - System.IO 4.0.10                                                                             
 - System.Text.Encoding 4.0.10                                                                  
 - System.Xml.ReaderWriter 4.0.10                                                               
 - System.Diagnostics.Contracts 4.0.0                                                           
 - System.Private.Uri 4.0.0                                                                     
 - System.Reflection.Emit 4.0.0                                                                 
 - System.Resources.ResourceManager 4.0.0                                                       
 - NewId 2.1.3                                                                                  
 - Microsoft.Bcl 1.1.10                                                                         
 - Elasticsearch.Net 1.7.1                                                                      
 - Microsoft.Bcl.Async 1.0.168                                                                  
 - Microsoft.Bcl.Build 1.0.21                                                                   
 - System.Runtime.InteropServices 4.0.20                                                        
 - System.Text.Encoding.Extensions 4.0.10                                                       
 - System.IO.FileSystem 4.0.0                                                                   
 - System.IO.FileSystem.Primitives 4.0.0                                                        
 - System.Reflection.Emit.ILGeneration 4.0.0                                                    
 - System.Runtime.Handles 4.0.0                                                                 
 - System.Runtime.WindowsRuntime 4.0.10                                                         
 - System.Threading.Overlapped 4.0.0                                                            
Locked version resolution written to C:\Dev\Worker\Services.Customer\src\paket.lock 
*2 minutes, 3 seconds - ready.                                                                   *

**Comment by forki** [comment]
but why did you run update? I thought you changed only one package?

so try to run "paket update nuget X"

**Comment by forki** [comment]
or what is the process you want to do?

**Comment by alexeyzimarev** [comment]
$ .paket\paket update nuget Services.Base                                       
Paket version 2.27.14.0                                                              
Updating Services.Base in C:\Dev\Worker\Worker.Services.Customer\src\paket.
oup Main                                                                             
Resolving packages for group Main:                                                   
 - Services.Base 0.1.0-ci0007                                                   
 - xunit is pinned to 2.0                                                            
 - Services.DataAccess 0.2.0-unstable0013                                       
 - Services.DataAccess.InMemory 0.2.0-unstable0013                              
 - EventSourcing 2.0.0-unstable0052                                             
 - EventSourcing.EventStore 2.0.0-beta0037                                      
 - EventSourcing.Subscriptions 2.0.0-beta0009                                   
 - EventSourcing.Testing 2.0.0-unstable0052                                     
 - Autofac 3.5.2                                                                     
 - Autofac.Extras.ServiceStack 2.0.2                                                 
 - AutoFixture 3.37.3                                                                
 - AutoFixture.AutoNSubstitute 3.37.3                                                
 - AutoFixture.Xunit2 3.37.3                                                         
 - FAKE 4.10.5                                                                       
 - FluentAssertions 4.1.1                                                            
 - Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.1                          
 - Microsoft.Net.Compilers 1.1.1                                                     
 - NSubstitute 1.9.2                                                                 
 - Projac.Connector 0.0.139                                                          
 - Serilog 1.5.14                                                                    
 - Serilog.Sinks.Seq 1.5.27                                                          
 - ServiceStack 4.0.50                                                               
 - ServiceStack.Api.Swagger 4.0.50                                                   
 - ServiceStack.Client 4.0.50                                                        
 - ServiceStack.Interfaces 4.0.50                                                    
 - ServiceStack.Logging.Serilog 2.0.0.9                                              
 - ServiceStack.RabbitMq 4.0.50                                                      
 - Topshelf 3.3.1                                                                    
 - Topshelf.Serilog 3.3.1                                                            
 - xunit.abstractions 2.0.0                                                          
 - xunit.runner.console 2.1.0                                                        
 - xunit.runner.visualstudio 2.1.0                                                   
 - xunit.core 2.0.0                                                                  
 - xunit.assert 2.0.0                                                                
 - ServiceStack.Common 4.0.50                                                        
 - ServiceStack.Text 4.0.50                                                          
 - System.Runtime 4.0.20                                                             
 - System.Collections 4.0.10                                                         
 - System.Diagnostics.Debug 4.0.10                                                   
 - System.Globalization 4.0.10                                                       
 - System.Linq.Expressions 4.0.10                                                    
 - System.ObjectModel 4.0.10                                                         
 - System.Reflection 4.0.10                                                          
 - System.Runtime.Extensions 4.0.10                                                  
 - System.Text.RegularExpressions 4.0.10                                             
 - System.Threading 4.0.10                                                           
 - System.Threading.Tasks 4.0.10                                                     
 - System.Xml.XDocument 4.0.10                                                       
 - System.Linq 4.0.0                                                                 
 - System.Reflection.Extensions 4.0.0                                                
 - System.Reflection.Primitives 4.0.0                                                
 - System.Reflection.TypeExtensions 4.0.0                                            
 - RabbitMQ.Client 3.5.7                                                             
 - Microsoft.Net.Http 2.2.29                                                         
 - CompareNETObjects 3.3.0                                                           
 - EventStore.Client 3.3.1                                                           
 - EventStore.SerilogAdapter 1.0.0                                                   
 - Ix-Main 1.2.5                                                                     
 - MassTransit 3.0.17                                                                
 - Mediatr 2.0.2                                                                     
 - Newtonsoft.Json 7.0.1                                                             
 - Serilog.Sinks.Elasticsearch 2.0.70                                                
 - System.Collections.Immutable 1.1.37                                               
 - xunit.extensibility.core 2.0.0                                                    
 - System.IO 4.0.10                                                                  
 - System.Text.Encoding 4.0.10                                                       
 - System.Xml.ReaderWriter 4.0.10                                                    
 - System.Diagnostics.Contracts 4.0.0                                                
 - System.Private.Uri 4.0.0                                                          
 - System.Reflection.Emit 4.0.0                                                      
 - System.Resources.ResourceManager 4.0.0                                            
 - NewId 2.1.3                                                                       
 - Microsoft.Bcl 1.1.10                                                              
 - Elasticsearch.Net 1.7.1                                                           
 - Microsoft.Bcl.Async 1.0.168                                                       
 - Microsoft.Bcl.Build 1.0.21                                                        
 - System.Runtime.InteropServices 4.0.20                                             
 - System.Text.Encoding.Extensions 4.0.10                                            
 - System.IO.FileSystem 4.0.0                                                        
 - System.IO.FileSystem.Primitives 4.0.0                                             
 - System.Reflection.Emit.ILGeneration 4.0.0                                         
 - System.Runtime.Handles 4.0.0                                                      
 - System.Runtime.WindowsRuntime 4.0.10                                              
 - System.Threading.Overlapped 4.0.0                                                 
C:\Dev\Worker\Services.Customer\src\paket.lock is already up-to-date     

**1 minute, 19 seconds - ready.**

**Comment by forki** [comment]
looks like your packages are all on nuget,org. Can you send me the paket.depedencies and lock files? Then I might be able to look deeper

**Comment by alexeyzimarev** [comment]
Unfortunately those are on myget private feed:

Services.Base 0.1.0-ci0007
Services.DataAccess 0.2.0-unstable0013
Services.DataAccess.InMemory 0.2.0-unstable0013
EventSourcing 2.0.0-unstable0052
EventSourcing.EventStore 2.0.0-beta0037
EventSourcing.Subscriptions 2.0.0-beta0009
EventSourcing.Testing 2.0.0-unstable0052

**Comment by alexeyzimarev** [comment]
I will figure something out

**Comment by forki** [comment]
I improved the update performance. Can you please retry and tell me if things improved for you? And please run the update twice since we now cache more than before.

**Comment by forki** [comment]
ping

**Comment by alexeyzimarev** [comment]
Sorry. We are using paket in lots of projects and I executed the update many times with all recent versions, it works perfectly fine.
