### ISSUE TITLE
Paket failed with "Could not find versions for package in any of the sources in []."

### ISSUE THREAD

**Issue by WallaceKelly** [fsprojects/Paket#1318]
I am trying to setup paket for the first time. I was following the [Getting Started - Manual Setup](http://fsprojects.github.io/Paket/getting-started.html#Manual-setup) instructions. I am getting the error, `Could not find versions for package DotNetZip in any of the sources in [].`

Here is my folder structure:

    > dir /b /s
    C:\Temp\paket-test\.paket
    C:\Temp\paket-test\paket.dependencies
    C:\Temp\paket-test\.paket\paket.bootstrapper.exe
    C:\Temp\paket-test\.paket\paket.exe

Here are the contents of my paket.dependencies:

    nuget DotNetZip

Here is the result:

    > .\.paket\paket.exe install
    Paket version 2.36.7.0
    Resolving packages for group Main:
    Paket failed with:
            Could not find versions for package DotNetZip in any of the sources in [].

In contrast, nuget works just fine:

    > nuget install DotNetZip
    Installing 'DotNetZip 1.9.7'.
    Successfully installed 'DotNetZip 1.9.7'.

I am not using a proxy.

**Comment by forki** [comment]
You need to configure a nuget source feed at the top of the dependencies
file. See the samples.

**Comment by WallaceKelly** [comment]
Doh! The sample does indeed have this:

    source https://nuget.org/api/v2

    nuget Castle.Windsor-log4net >= 3.2
    nuget NUnit

    github forki/FsUnit FsUnit.fs

My eyes glazed over that first line. The Getting Started instructions say, "You can use NuGet packages, GitHub files and HTTP dependencies." I mistakenly saw the `source` line as an example of an "HTTP dependency." I see now that there is an `http` specifier for HTTP dependencies.

Thanks for the quick response!
