### ISSUE TITLE
Support for .NET 4.6.1.

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [fsprojects/Paket#1324]
Visual Studio 2015 Update 1 gave us .NET 4.6.1.

My `paket.dependencies` file currently contains:

`framework: net46`

But now that I've just changed my projects to target .NET 4.6.1, all the project references are missing, because they are conditional on .NET 4.6, like this:

`<When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6'">`

What framework string should I use for .NET 4.6.1?

I can't see any mention of .NET 4.6.1 in [FrameworkHandling.fs](https://github.com/fsprojects/Paket/blob/9b54a3e1b9e2804421878472dcf01bc44ff4ef46/src/Paket.Core/FrameworkHandling.fs).

**Comment by forki** [comment]
It's in master: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/FrameworkHandling.fs

I think `framework net461` should work.

**Comment by Bananas-Are-Yellow** [comment]
Ah, I saved a link to that source file a while ago, but obviously not to the master version of it.

Thank  you.
