### ISSUE TITLE
can't restore packages from AppVeyor feed in 2.38.0

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#1326]
This is probably related to the fix for #1317. `paket restore` fails when trying to download any private NuGet package from our AppVeyor feed. To reproduce locally, delete `%localappdata%NuGet\Cache` first.

```
Message: Couldn't get package details for package ...
```

**Comment by forki** [comment]
are you on latest? Nuget API changed yesterday and we have a fix around this issue.

**Comment by ctaggart** [comment]
Yes I am. this also affects 2.39.1. I get a message like this for each of our dependencies hosted on AppVeyor.
![image](https://cloud.githubusercontent.com/assets/80104/11985271/ce26420c-a977-11e5-9af1-1fc55b00a440.png)
![image](https://cloud.githubusercontent.com/assets/80104/11985281/ea84dbd4-a977-11e5-8df4-6825166d2f40.png)
![image](https://cloud.githubusercontent.com/assets/80104/11985285/f2893f1e-a977-11e5-9b39-4ea105057466.png)

**Comment by forki** [comment]
Mhm. Unfortunately I have no idea what happened yet. I will try to reproduce on 27th or 28th

**Comment by forki** [comment]
Just for my understanding is it also happening when you do "paket update -f"?

**Comment by ctaggart** [comment]
No, it is not happening with a `paket update -f`. It is happening with a `paket restore -f`.

**Comment by forki** [comment]
Ok thanks. Will try to fix it as first thing after Christmas

**Comment by forki** [comment]
First success: I can reproduce.
