### ISSUE TITLE
paket install fails on extraction if path is longer than 260 characters

### ISSUE THREAD

**Issue by jschroed** [fsprojects/Paket#1331]
I'm having an issue with paket when I execute paket in a really long directory name. When I try to run **paket update** or **paket install** in my directory with the long name (near or over 260 characters), I get this error message:

    Paket failed with:
            Error during extraction of C:\j\workspace\really-long-path-name\another-really-long-directory-name\third-really-name-path-name\last-really-really-long-name\packages\nuget-bot.Microsoft.VisualStudio.Services.Common\nuget-bot.Microsoft.VisualStudio.Services.Common.12.0.21005.1.nupkg.
    Message: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. In rare cases a firewall might have blocked the download. Please look into the file and see if it contains text with further information.

My paket.dependencies has a source line plus this package in it:

    nuget nuget-bot.Microsoft.VisualStudio.Services.Common

Microsoft has this information about prefixing paths with "\\?\" to resolve this: https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx#maxpath. I'm not sure if this can be applied to paket.

Is this an issue with paket that can be fixed or do I need to make sure our path names in our projects are always shorter than this limit?

Edit:
There was a ticket with using directories with more than 260 character but I think the issue is different: https://github.com/fsprojects/Paket/issues/949

**Comment by forki** [comment]
Currently this is not supported. We need to use a different api for this,
but I'm not sure when we have it.

**Comment by eggapauli** [comment]
Isn't it basically [this one](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/)?
