### ISSUE TITLE
Duplicate references to framework assemblies added

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsprojects/Paket#1333]
I think this is very similar to #932, if not actually exactly the same thing.

When adding a package to a project using Paket, a `<Choose>` section is added to the project file with references to all the assemblies in that package, as well as apparently any of the framework assemblies that are stated as dependencies in the package but not already referenced by the project. When the next package is added, those references to the framework assemblies are not found and added again in that package's `<Choose>` section.

An example:

FsXaml and FSharp.Desktop.UI reference the following framework assemblies:

- PresentationCore
- PresentationFramework
- System.Xaml
- System.Xml (FsXaml only)
- WindowsBase

I now use Paket to add those to a project that already references `System.Xaml`, `System.Xml` and `WindowsBase` (added through the References dialog, for example).

Adding FSharp.Desktop.UI now inserts the following into the `*.fsproj` file:

    <Choose>
      <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(  TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) ==   'v4.6.1')">
        <ItemGroup>
          <Reference Include="FSharp.Desktop.UI">
            <HintPath>..\..\packages\FSharp.Desktop.UI\lib\net45\FSharp.Desktop.UI.dll</HintPath>
            <Private>True</Private>
            <Paket>True</Paket>
          </Reference>
          <Reference Include="PresentationCore">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="PresentationFramework">
            <Paket>True</Paket>
          </Reference>
        </ItemGroup>
      </When>
    </Choose>

Next I add FsXaml; `System.Xaml`, `System.Xml` and `WindowsBase` are detected correctly, but the other two framework assembly references are not "seen" and get included again for FsXaml:

    <Choose>
      <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(  TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) ==   'v4.6.1')">
        <ItemGroup>
          <Reference Include="FsXaml.Wpf.TypeProvider">
            <HintPath>..\..\packages\FsXaml.Wpf\lib\net45\FsXaml.Wpf.TypeProvider.dll</HintPath>
            <Private>True</Private>
            <Paket>True</Paket>
          </Reference>
          <Reference Include="FsXaml.Wpf">
            <HintPath>..\..\packages\FsXaml.Wpf\lib\net45\FsXaml.Wpf.dll</HintPath>
            <Private>True</Private>
            <Paket>True</Paket>
          </Reference>
          <Reference Include="PresentationCore">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="PresentationFramework">
            <Paket>True</Paket>
          </Reference>
        </ItemGroup>
      </When>
    </Choose>

The result is that the respective framework assemblies show up multiple times in Solution Explorer; however, as far as I could see, the project still compiles and runs correctly, probably because they are always references to the exact same thing and thus don't cause conflicts as seen in #932.

My naive first thought would of course be simply putting all references to framework assemblies in normal ItemGroups, but considering we're dealing with Visual Studio, MSBuild and NuGet, that sounds too easy.

**Comment by forki** [comment]
I guess we still need Choose Nodes, but need to merge all the packages...

**Comment by forki** [comment]
I wonder why it installed the references at all. Usually it should not add the reference if it already finds one which doesn't have a Paket flag.

(this would also lead to a workaround)

**Comment by mexx** [comment]
I've also already noticed this behavior, but since it leads to no problems during the build and the result assemblies also have no problems at runtime and it's only weird display in the Solution Explorer, I haven't reported this one ;)

Currently a `Choose` node is generated per package and contains all assemblies, contained in the package as well as framework ones. Only the references already present without `Paket` flag will be removed from the list of references to include.

To deduplicate the nodes, we would need to collect framework references together with the conditions when each of it should be inserted and provide separate `Choose` nodes for them.
When removing packages, we would need to consider which of those references should also be removed, as not referenced anymore by any of the remaining packages.

**Comment by pavelhritonenko** [comment]
I have the same behavior. If you add to empty F# project nuget packages - `FSharp.Data` and `WindowsAzure.Storage` you will see `System.Xml twice` under References node:

![image](https://cloud.githubusercontent.com/assets/2510026/17552357/29ace3c4-5f08-11e6-8667-5a86580e7f54.png)

Although I have 3 `System.Xml` entries and 2 `System.Xml.Linq` entries in our solution it doesn't affect build process.

**Comment by forki** [comment]
can you please zip that sample project and attach it here? thanks

**Comment by pavelhritonenko** [comment]
Yes, in attachment.

[ConsoleApplication1.zip](https://github.com/fsprojects/Paket/files/410948/ConsoleApplication1.zip)

**Comment by forki** [comment]
Ok one System.Xml.Linq.dll is coming from  FSharp.Data and one from Microsoft.WindowsAzure.Storage

we could somehow store if we already emitted the reference for a given framework and only reference it once. So it would be ommited for Microsoft.WindowsAzure.Storage.

Is it worth it?

**Comment by isaacabraham** [comment]
I believe this goes into the category of "should fix". It's (I believe) mostly harmless but it's something that can confuse users and is not expected.

**Comment by forki** [comment]
so what do we do? removing the second reference?

Reordering choose nodes by grouping by target framework (see @mexx 's comment) is not what I want to do before we know how nuget is doing this in vNext.
