### ISSUE TITLE
Add a http file reference as project reference

### ISSUE THREAD

**Issue by jruizaranguren** [fsprojects/Paket#1341]
I have added a `dll` library downloaded as an `http` reference within a group. The `paket.dependencies`  file contains:

```
group Files
http file:///absolute/path/to/library.dll target/path/library.dll
```

Then in the `paket.references` file I use:

```
group Files
	File:library.dll
```

This is adding a content node in the references `ItemGroup` in the `.csproj`, such as:

```xml
    <Content Include="..\..\paket-files\files\localhost\target\path\library.dll">
      <Paket>True</Paket>
      <Link>paket-files/library.dll</Link>
    </Content>
    ...
    <Reference Include="System" />
    ...
```

This is just a link to the source file which I can not use to create a project reference.

Is there any way to add this file as a project reference?

**Comment by forki** [comment]
not yet. but I think it's not that hard to do.
let me see if I can hack something together

**Comment by jruizaranguren** [comment]
Thanks. If you give me some clues I might try to make the enhancement.

**Comment by forki** [comment]
it would be usefule if you could generate a minimal repro that uses a sample dll (doesn't need to compile - dll might be 0 bytes)

**Comment by jruizaranguren** [comment]
As a couple of tests or a folder with all required files (source file, solution file, project file)?

**Comment by forki** [comment]
yes a folder with all required files would be nice. I would then put this into our integration test suite

**Comment by jruizaranguren** [comment]
Here you have. http path must be changed!.

[i001341.zip](https://github.com/fsprojects/Paket/files/78340/i001341.zip)

**Comment by forki** [comment]
please test the latest version.
I added your sample repo as integration test and implemented a fix. but Im not completely sure if it works. so please see it as an alpha version that needs further testing.

**Comment by jruizaranguren** [comment]
Starting with a greenfield folder, it succesfully creates a project reference to the dll. But there are some undesirable behaviors:

* It copies the dll to a new local folder below the project folder: `paket-files/library.dll`. This is not needed because the library is already downloaded below the `paket-files` directory. Only the project reference should be created.
* When the reference is deleted in `paket.references`, it succesfully deletes the reference, but the mentioned new local file `paket-files/library.dll` is not deleted.
* When `paket-files/library.dll` is found below the project directory, the installation fails. So forced updates of the library will fail.
* If we already had the library referenced as a link in a `content` item, this is not deleted when the new reference is added (minor issue to be documented).

**Comment by forki** [comment]
just fixed this. paket-files/library.dll is no longer copied. 
regarding docs - could you please take a look at https://github.com/fsprojects/Paket/blob/master/docs/content/http-dependencies.md and send a PR with some docs improvements that you find useful? would help a lot
