### ISSUE TITLE
Cannot run 3.0.0 alpha2 on Mono

### ISSUE THREAD

**Issue by kerams** [fsprojects/Paket#1342]
Getting this eror when running Paket on Travis:

    Starting download from https://github.com/fsprojects/Paket/releases/download/3.0.0-alpha002/paket.exe
    Done.
    Cannot open assembly '.paket/paket.exe': File does not contain a valid CIL image.

**Comment by kerams** [comment]
I'm on the nightly version of Mono by the way.

**Comment by forki** [comment]
ouch

**Comment by forki** [comment]
let's see if it runs on Travis: #1342

**Comment by forki** [comment]
seems the program is working (only unittests failing)

**Comment by kerams** [comment]
https://travis-ci.org/kerams/Templatus/builds/100322344

Do you want to close this as a Mono issue?

**Comment by forki** [comment]
let's see if the nightly crashes 84007d6

**Comment by kerams** [comment]
It does not. Interesting.

**Comment by forki** [comment]
Also trying opposite: https://github.com/kerams/Templatus/pull/20

**Comment by forki** [comment]
let's close this for now as some strange flakyness

**Comment by kerams** [comment]
So this thing only pops up on 3.0.0-alpha2, on Mono nightly, but only in my project on Travis :D.

Alright, I'll keep an eye out for this once 3.0.0 is released properly.
