### ISSUE TITLE
paket.references gets overwritten by paket install

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/Paket#1344]
I've created new console project with Visual Studio (and closed it, so no any interference between VS and Paket), let's call it `ConsoleApplication8`, and done the following:

    .\.paket\paket.exe init
    .\.paket\paket.exe add nuget Tesla.Csxcad version 0.0.1-alpha3

Then written the following to `ConsoleApplication8\paket.references`:

    Tesla.Csxcad

After that I've ran `.paket\paket install`. It overwritten my `paket.references` with the following:

    FSharp.Data

I've set up the test repository [here](https://github.com/ForNeVeR/ConsoleApplication8). [That](https://github.com/ForNeVeR/ConsoleApplication8/commit/4c7c391601639397d1d13e9666d3c7dbb7331c84) is the state I got after `paket install`.

Is it a bug or not? Is it okay that it removes my `Tesla.Csxcad` from `paket.references`?

**Comment by forki** [comment]
something is fucky here. I'll investigate

**Comment by ForNeVeR** [comment]
Some additional details: that `Tesla.Csxcad` is written and published by me, so it could have any number of NuGet-related problems. And it really have this `FSharp.Data` dependency.

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/12117436/08218dec-b3c1-11e5-97d7-a9335a84c90b.png)

;-) you have a packages.references in the content folder of you package. This file gets extracted and overwrites the existing file.

**Comment by ForNeVeR** [comment]
Ah. Thanks for pointing that! Definitely my fault and not a Paket issue.

**Comment by forki** [comment]
I think I will add a error message here to make that more bovious.

**Comment by ForNeVeR** [comment]
Well, that would be really nice.

**Comment by forki** [comment]
we now skip this file and show a warning.

![image](https://cloud.githubusercontent.com/assets/57396/12117920/f63b3166-b3c3-11e5-8093-c689fb670635.png)

/cc @theimowski please verify that I didn't break your scenario

**Comment by ForNeVeR** [comment]
Thank you!

**Comment by theimowski** [comment]
No it shouldn't - I zip only paket.dependencies and paket.lock. Think I used 2.40.4 today and it was fine

**Comment by forki** [comment]
thanks buddy
