### ISSUE TITLE
Paket pack for symbols packages should allow for pulling in referenced projects.

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket#1345]
If I call "nuget pack -includereferencedprojects" when packaging sources, I get the referenced project source in the nupkg file.  There doesn't seem to be like operator in Paket.  Am I missing something?

Cheers,
Paul

**Comment by pms1969** [comment]
additonally, the pdb's are not currently packaged.

**Comment by pms1969** [comment]
Can anyone give me a nudge in the right direction to fix this?  I've found NupkgWriter, and would have thought it was in there somewhere, but nothing jumps out at me.

**Comment by baronfel** [comment]
I've been looking for some documentation from nuget about what this flag does specifically, but have had no luck.  Do you have any pointers?  By 'referenced project source', you mean the actual source code, not pdbs or anything?

**Comment by pms1969** [comment]
Don't have any doco, but when we set it, it pulls in the source code from any referenced project as well as all the pdbs of referenced projects.

So if you had project A depending on project B, and packaged against project A, B's source and pdb would be available in the symbols package, as well as A's.  The behaviour of paket (as far as I can see), is to only include the source and pdb from A.

The source is also added under it's project name, even if there are no reference projects (in nuget).  This is not the case currently with paket.

**Comment by pms1969** [comment]
I have a working implementation of this, just need to add some tests to it and then I'll put in a pull request.

**Comment by pms1969** [comment]
Pull Request submitted.  Let me know what you think.

https://github.com/fsprojects/Paket/pull/1373

**Comment by pms1969** [comment]
resubmitted as https://github.com/fsprojects/Paket/pull/1383

**Comment by pms1969** [comment]
all done
