### ISSUE TITLE
Strange Crypto Exception on some Windows machines

### ISSUE THREAD

**Issue by haraldsteinlechner** [fsprojects/Paket#1346]
On some machines i get a crazy windows encryption exception. The error occurs when protecting the password. 
Most likely this issue only happens if users only use a domain user but have no local admin user on the machine.
(have a local fix)

![paketerror](https://cloud.githubusercontent.com/assets/513281/12120568/977f84e8-b3d1-11e5-9e75-5c0d61302e68.png)

**Comment by forki** [comment]
please send pull request

**Comment by haraldsteinlechner** [comment]
https://github.com/fsprojects/Paket/pull/1347
