### ISSUE TITLE
Paket pack messes NPM type paths with @ char

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#1348]
Example: 

`font-awesome@4.5.0`

becomes

`font-awesome%404.5.0`

I'm using octopus deploy to deploy a web application that uses some npm type packages and I use paket to package the project. 

From looking at paket code, this seems to be more a feature than a bug, as Escape URI string seems to be used:

```f#
let ensureValidName (target: string) =
        let escapedTargetParts = target.Replace("\\", "/").Split('/') |> Array.map Uri.EscapeDataString
        let escapedTarget = String.Join("/",escapedTargetParts)

        let uri1 = Uri(escapedTarget, UriKind.Relative)
        let uri2 = Uri(uri1.GetComponents(UriComponents.SerializationInfoString, UriFormat.SafeUnescaped), UriKind.Relative)
        
        uri2.GetComponents(UriComponents.SerializationInfoString, UriFormat.UriEscaped)
```

ref: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NupkgWriter.fs#L229

It does however give me some 404 headaches now..

**Comment by forki** [comment]
ideas how to solve this?

**Comment by forki** [comment]
maybe @ sign needs to be excluded. PRs welcome

**Comment by Vidarls** [comment]
Probably a good idea to be as explicit as possible as long as no-one gives any generic solutions.
I'll try to put something together that will leave the `@` char alone. 
(Although I think this will also be a problem with international characters, like the scandinavian `æøå` and the german special double ss char. All of which are valid folder names in windows (at least `æøå` is), but here will be replaced with some hex code)

**Comment by forki** [comment]
Thx

**Comment by Vidarls** [comment]
Working now, thanx for express release and merge :)
