### ISSUE TITLE
Implement operating system detection

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1355]
For https://github.com/fsprojects/Paket/pull/1353 in Paket v3 we need a OS filter function along the lines:

    let isMatchingOperatingSystem (operatingSystemFilter:string option) : bool = ...

to make it interesting: the syntax for the filter string is still up for dicussion. So we need ideas here.

Volunteers?

**Comment by kerams** [comment]
Just to make sure I understand this correctly, the function is to decide whether the OS we're running on matches an OS specified in the filter or returns `true` if input is `None`, correct?

What are the exact OSes that need to be distinguished?
Is it necessary to tell apart different versions of the same OS?
Can the input string specify multiple OSes?

**Comment by forki** [comment]
Yes you understand correctly.
The issue is I don't really know yet.
Maybe we make it a bit easier and say string -> bool. This way we can at
least defer the decision if we want to match multiple OSes
