### ISSUE TITLE
Verbose dependency resolution option

### ISSUE THREAD

**Issue by xenocons** [fsprojects/Paket#1356]
When running a paket update , it is problematic on a big solution if one project within that solution references another project dependency that no longer exists, paket displays the following:

 ```
Unable to parse C:\Users\admin\Documents\Visual Studio 2015\Projects\ext\src\External\FSharp.Data\src\FSharp.Data.fsproj:
      Could not find a part of the path 'C:\Users\admin\Documents\Visual Studio 2015\Projects\ext\src\External\FSharp.Data\src\FSharp.Data.fsproj'.
```

It would be useful to have a verbose option that tells you where this .fsproj orignated (its another project referencing the now moved FSharp.Data), otherwise one has to go through Visual Studio and attempt to build all the projects to work out where the issue exists. I see issue https://github.com/fsprojects/Paket/issues/503 asked for a verbose option to help debugging various things (different issue though).

**Comment by forki** [comment]
We have -v option. 

But can you create a repro so that I can improve the error message?

**Comment by xenocons** [comment]
Sorry, I don't see -v in my paket help, although it does work, perhaps the `packet.exe /?` should display this verbose option?. Now I get the following, which makes it easy to debug the issue:
```
Installing to C:\Users\admin\Documents\Visual Studio 2015\Projects\\tests\TestData\Tests.fsproj
Unable to parse C:\Users\admin\Documents\Visual Studio 2015\Projects\\tests\.Agent.Delivery\Delivery.fsproj:
      Could not find a part of the path 'C:\Users\admin\Documents\Visual Studio 2015\Projects\\tests\.Agent.Delivery\Delivery.fsproj'.
```
