### ISSUE TITLE
v2.41.1 fails with segfault on mono when trying to get the paket.exe file version

### ISSUE THREAD

**Issue by kjnilsson** [fsprojects/Paket#1358]
OS: OSX

oryx:FifteenBelow.VersionedStorage karlnilsson$ mono --version
Mono JIT compiler version 4.2.1 (explicit/6dd2d0d Fri Nov  6 12:25:19 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen

oryx:FifteenBelow.VersionedStorage karlnilsson$ mono .paket/paket.bootstrapper.exe
No version specified. Downloading latest stable.
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Diagnostics.FileVersionInfo.GetVersionInfo_internal (System.Diagnostics.FileVersionInfo,string) <0xffffffff>
  at System.Diagnostics.FileVersionInfo.GetVersionInfo (string) <0x000a7>
  at Paket.Bootstrapper.BootstrapperHelper.GetLocalFileVersion (string) <0x00037>
  at Paket.Bootstrapper.Program.StartPaketBootstrapping (Paket.Bootstrapper.IDownloadStrategy,Paket.Bootstrapper.DownloadArguments) <0x0011f>
  at Paket.Bootstrapper.Program.Main (string[]) <0x000df>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

Debug info from gdb:

(lldb) command source -s 0 '/tmp/mono-gdb-commands.vLZT43'
Executing commands in '/tmp/mono-gdb-commands.vLZT43'.
(lldb) process attach --pid 60733
warning: (i386) /Library/Frameworks/Mono.framework/Versions/4.2.1/lib/mono/4.5/mscorlib.dll.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
Process 60733 stopped
* thread #1: tid = 0xd3a62, 0x993bdd06 libsystem_kernel.dylib`__wait4 + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x993bdd06 libsystem_kernel.dylib`__wait4 + 10
libsystem_kernel.dylib`__wait4:
->  0x993bdd06 <+10>: jae    0x993bdd16                ; <+26>
    0x993bdd08 <+12>: calll  0x993bdd0d                ; <+17>
    0x993bdd0d <+17>: popl   %edx
    0x993bdd0e <+18>: movl   0xaaaa317(%edx), %edx

Executable module set to "/usr/local/bin/mono".
Architecture set to: i386-apple-macosx.
(lldb) thread list
Process 60733 stopped
* thread #1: tid = 0xd3a62, 0x993bdd06 libsystem_kernel.dylib`__wait4 + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  thread #2: tid = 0xd3a65, 0x993bd402 libsystem_kernel.dylib`__psynch_cvwait + 10
  thread #3: tid = 0xd3a66, 0x993b6886 libsystem_kernel.dylib`semaphore_wait_trap + 10
  thread #4: tid = 0xd3a68, 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
  thread #5: tid = 0xd3a69, 0x993be812 libsystem_kernel.dylib`kevent_qos + 10, queue = 'com.apple.libdispatch-manager'
  thread #6: tid = 0xd3a6a, 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
  thread #7: tid = 0xd3a6f, 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
(lldb) thread backtrace all
* thread #1: tid = 0xd3a62, 0x993bdd06 libsystem_kernel.dylib`__wait4 + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x993bdd06 libsystem_kernel.dylib`__wait4 + 10
    frame #1: 0x9e9e57dc libsystem_c.dylib`waitpid$UNIX2003 + 48
    frame #2: 0x000dd24d mono`mono_handle_native_sigsegv(signal=11, ctx=0x00767fe0, info=0x00767fa0) + 541 at mini-exceptions.c:2193 [opt]
    frame #3: 0x00129702 mono`mono_arch_handle_altstack_exception(sigctx=<unavailable>, siginfo=<unavailable>, fault_addr=<unavailable>, stack_ovf=0) + 162 at exceptions-x86.c:1097 [opt]
    frame #4: 0x0002aeee mono`mono_sigsegv_signal_handler(_dummy=<unavailable>, _info=<unavailable>, context=<unavailable>) + 446 at mini-runtime.c:2461 [opt]
    frame #5: 0x9727701b libsystem_platform.dylib`_sigtramp + 43
    frame #6: 0x0026473c mono`find_pe_file_resources [inlined] find_pe_file_resources32(res_id=16, lang_id=0) + 185 at versioninfo.c:209 [opt]
    frame #7: 0x00264683 mono`find_pe_file_resources(res_id=16, lang_id=0, file_map=<unavailable>, map_size=<unavailable>, size=<unavailable>) + 3 at versioninfo.c:308 [opt]
    frame #8: 0x0026451a mono`wapi_GetFileVersionInfoSize(filename=0x0080081c, handle=0xbffe2424) + 58 at versioninfo.c:949 [opt]
    frame #9: 0x001b9d3a mono`process_get_fileversion(filever=<unavailable>, filename=<unavailable>) + 58 at process.c:250 [opt]
    frame #10: 0x001b9ca4 mono`ves_icall_System_Diagnostics_FileVersionInfo_GetVersionInfo_internal(this=0x00809b40, filename=0x00800810) + 68 at process.c:544 [opt]
    frame #11: 0x006d0728
    frame #12: 0x006d0598
    frame #13: 0x006d0498
    frame #14: 0x006d01d0
    frame #15: 0x006ccfb8
    frame #16: 0x006cd0b9
    frame #17: 0x0002dd5a mono`mono_jit_runtime_invoke(method=<unavailable>, obj=<unavailable>, params=<unavailable>, exc=<unavailable>) + 714 at mini-runtime.c:2334 [opt]
    frame #18: 0x001f252f mono`mono_runtime_invoke(method=0x798b5ac8, obj=0x00000000, params=<unavailable>, exc=<unavailable>) + 127 at object.c:2783 [opt]
    frame #19: 0x001f8281 mono`mono_runtime_exec_main(method=0x798b5ac8, args=<unavailable>, exc=0x00000000) + 401 at object.c:4040 [opt]
    frame #20: 0x001f803a mono`mono_runtime_run_main(method=0x798b5ac8, argc=<unavailable>, argv=<unavailable>, exc=<unavailable>) + 618 at object.c:3666 [opt]
    frame #21: 0x000a604d mono`mono_jit_exec(domain=0x796386c0, assembly=0x7a128530, argc=<unavailable>, argv=<unavailable>) + 93 at driver.c:1004 [opt]
    frame #22: 0x000a8360 mono`mono_main [inlined] main_thread_handler + 7920 at driver.c:1063 [opt]
    frame #23: 0x000a8322 mono`mono_main(argc=<unavailable>, argv=<unavailable>) + 7858 at driver.c:2052 [opt]
    frame #24: 0x00020650 mono`main [inlined] mono_main_with_options(argc=<unavailable>, argv=<unavailable>) + 768 at main.c:94 [opt]
    frame #25: 0x0002036d mono`main(argc=<unavailable>, argv=<unavailable>) + 29 at main.c:125 [opt]
    frame #26: 0x00020345 mono`start + 53

  thread #2: tid = 0xd3a65, 0x993bd402 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #0: 0x993bd402 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x9312af6b libsystem_pthread.dylib`_pthread_cond_wait + 757
    frame #2: 0x9312ecc0 libsystem_pthread.dylib`pthread_cond_wait$UNIX2003 + 71
    frame #3: 0x00250852 mono`thread_func(thread_data=0x00000000) + 466 at sgen-thread-pool.c:118 [opt]
    frame #4: 0x9312aa26 libsystem_pthread.dylib`_pthread_body + 138
    frame #5: 0x9312a99c libsystem_pthread.dylib`_pthread_start + 155
    frame #6: 0x93127f96 libsystem_pthread.dylib`thread_start + 34

  thread #3: tid = 0xd3a66, 0x993b6886 libsystem_kernel.dylib`semaphore_wait_trap + 10
    frame #0: 0x993b6886 libsystem_kernel.dylib`semaphore_wait_trap + 10
    frame #1: 0x0027334a mono`mono_sem_wait(sem=0x0035308c, alertable=1) + 26 at mono-semaphore.c:109 [opt]
    frame #2: 0x001f042e mono`finalizer_thread(unused=0x00000000) + 158 at gc.c:1096 [opt]
    frame #3: 0x001ca64c mono`start_wrapper [inlined] start_wrapper_internal + 463 at threads.c:723 [opt]
    frame #4: 0x001ca47d mono`start_wrapper(data=<unavailable>) + 29 at threads.c:770 [opt]
    frame #5: 0x0027aee0 mono`inner_start_thread(arg=<unavailable>) + 240 at mono-threads-posix.c:97 [opt]
    frame #6: 0x9312aa26 libsystem_pthread.dylib`_pthread_body + 138
    frame #7: 0x9312a99c libsystem_pthread.dylib`_pthread_start + 155
    frame #8: 0x93127f96 libsystem_pthread.dylib`thread_start + 34

  thread #4: tid = 0xd3a68, 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x9312a52d libsystem_pthread.dylib`_pthread_wqthread + 1289
    frame #2: 0x93127f72 libsystem_pthread.dylib`start_wqthread + 34

  thread #5: tid = 0xd3a69, 0x993be812 libsystem_kernel.dylib`kevent_qos + 10, queue = 'com.apple.libdispatch-manager'
    frame #0: 0x993be812 libsystem_kernel.dylib`kevent_qos + 10
    frame #1: 0x9cd5670e libdispatch.dylib`_dispatch_mgr_invoke + 234
    frame #2: 0x9cd562e2 libdispatch.dylib`_dispatch_mgr_thread + 52

  thread #6: tid = 0xd3a6a, 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x9312a52d libsystem_pthread.dylib`_pthread_wqthread + 1289
    frame #2: 0x93127f72 libsystem_pthread.dylib`start_wqthread + 34

  thread #7: tid = 0xd3a6f, 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x993bdd76 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x9312a52d libsystem_pthread.dylib`_pthread_wqthread + 1289
    frame #2: 0x93127f72 libsystem_pthread.dylib`start_wqthread + 34
(lldb) detach

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

(lldb) quit
Process 60733 detached
Abort trap: 6

**Comment by forki** [comment]
That sounds more like a mono bug

**Comment by kjnilsson** [comment]
The previous version worked fine though.

**Comment by forki** [comment]
Maybe. But I don't know what to do. The change is completely small.

**Comment by kjnilsson** [comment]
sorry it must have been due to to dodgy download - I deleted paket.exe and then the bootstrapper succeeded. May be worth attempting a re-download when paket.exe is present  but the bootstrapper fails to read the file version.

**Comment by forki** [comment]
Yes that sounds like a great PR.
