### ISSUE TITLE
Create a "Built with Paket" banner

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/Paket#136]
Something like the "Fork me on GitHub", so projects can put on their homepage and advertise Paket

**Comment by AlexZeitler** [comment]
How about this?
It's a CSS only solution:
![builtwithpaket](https://cloud.githubusercontent.com/assets/287480/5656578/51f4e66c-96df-11e4-9b1e-6f069f4b2a1a.png)
It can be left- or right-aligned.
Also the user can modify the text (and even color etc by modifying the CSS):

    <div class="ribbon ribbon-left">
        <a href="#">Built with Paket</a>
    </div>

    <div class="ribbon ribbon-right">
        <a href="#">Built with Paket</a>
    </div>

It's based on the code from here: https://unindented.org/articles/github-ribbon-using-css-transforms/

As you can see in the original post, it works in all browser and IE 9+

We could provide the CSS via GH as CDN, so the user has just to reference the CSS file and add one of the div variation as shown above.

**Comment by forki** [comment]
Thanks but I don't know what to do with this
