### ISSUE TITLE
Nemerle projects support

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#1367]
What should be done to support Nemerle projects? 

I created a hello world solution containing a regular console projects and a macro project https://github.com/vasily-kirichenko/NemerleHelloWorld, then added a NuGet package into each of them.

Project files look like normal ones for the first glance, so I don't think there may be problems. Just hint me where I should make changes.

**Comment by forki** [comment]
I think I would search for fsproj, csproj and "proj" in the source. It's
probably only 2 or 3 places.

**Comment by vasily-kirichenko** [comment]
Thanks. Implemented via https://github.com/fsprojects/Paket/pull/1368
