### ISSUE TITLE
Bug with nuget creation

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1370]
I encountered following issue that looks serious to me. 
paket.exe pack add pdb files in regular nugget packages. Nuget.exe includes them only in *.symbol.nuget packages. 

Adding pdb files in regular nuggets makes it impossible to get correct sources while debugging

**Comment by tsibelman** [comment]
@forki Did you saw this issue ?

**Comment by forki** [comment]
there was https://github.com/fsprojects/Paket/pull/1373 but I had to revert because of minor issues. /cc @pms1969

**Comment by tsibelman** [comment]
Is it related ? Here I talking about regular nuggets including pdb file while they should not.
