### ISSUE TITLE
Bug when declaring dependency on specific version

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1375]
I have flowing dependency   
nuget MySql.Data 6.9.8 

When I run paket pack I end up with following  dependency
`<dependency id="MySql.Data" version="[6.9.8-prerelease,6.9.8]" />`

Looks like it should not be a range dependency

**Comment by forki** [comment]
Is there something missing in your report?

**Comment by forki** [comment]
a h I see MySql.Data" version="[6.9.8-prerelease,6.9.8]"

**Comment by forki** [comment]
what is your lockfile showing?

**Comment by tsibelman** [comment]
Marked it as code so it will be shown

**Comment by tsibelman** [comment]
Lock file showing
  MySql.Data (6.9.8)

**Comment by tsibelman** [comment]
Also I see that bug not happening when I write dependency like this `MySql.Data  6.9.8  framework: >= net45`

**Comment by forki** [comment]
mhm I can't reproduce (see e9205aa)

**Comment by forki** [comment]
are you sure you don't have 

  nuget MySql.Data 6.9.8 prerelease

?

**Comment by tsibelman** [comment]
I tried to recreate it on new project and also failed. I try to pinpoint the issue

**Comment by forki** [comment]
maybe you can modify the integration test

**Comment by tsibelman** [comment]
Very strange I have a project where it recreated consistently but when I try to create similar project it works fine. I can't pinpoint the difference.

**Comment by forki** [comment]
it creates [6.9.8-prerelease,6.9.8] when it thinks prereleases are involved. so that#s the thing you need to look for.

**Comment by tsibelman** [comment]
Where it looking for prerelease ?

**Comment by forki** [comment]
can you mail me the project? sforkmann @ ggmail

**Comment by tsibelman** [comment]
Sorry it a company code, thank you for the help, the issue is not serious for me because I have good workaround right now.
