### ISSUE TITLE
Suggestion: Skip download of dependencies

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#1381]
Follow up of https://github.com/tpetricek/FSharp.Formatting/issues/337.
I think the underlaying problem is that paket doesn't know that FAKE depends on FSharp.Compiler.Service. If it would, it could resolve compatible versions and the problem would no longer appear in the future.

On the other hand I can see that we don't want to download all of FAKEs dependencies, because they are already bundled (which is good)....

Would it make sense to either have a paket feature to specify 'light' dependencies on a nuget package (ie dependencies which are not downloaded on restore), possibly even outside of the regular nuget dependencies, for example as an additional file bundled in the nuget package?

Or maybe even easier: Specify the dependencies as usual in the nuspec and add a feature for paket to not download dependencies (if they are not required by other packages in the group). Something like

```
nuget FAKE restore: skipdependencies
```

Another idea would be to have this flag but packages can enable it by themself (for example by adding a special file to the nupkg or via nuspec metadata?), this would enable backwards compat with exisiting `paket.dependencies`.

What do you think?

**Comment by forki** [comment]
I think this should all go into real nuget meta data.

That said: maybe we can still be smart here and special case fake inside of
paket or something like that

**Comment by matthid** [comment]
Yeah that would probably work as well for most users.
Do you think about adding the dependencies to FAKE and add a special case in paket to skip the download or do you see a special case without modifying the FAKE package?

Thinking about the dependencies of FAKE they probably need to be "==" because even if paket could solve a ">=" or "<=" constraint, downloading it wouldn't really help (because the version is locked/bundled in FAKE).

**Comment by matthid** [comment]
I think netcore and FAKE 5 will solve this
