### ISSUE TITLE
Creating (or updating) paket.dependencies file from paket.references files

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Paket#1384]
Bit unusual workflow but it would be really nice for F# project scaffolding / templating (like https://github.com/reidev275/Fix or https://github.com/fsprojects/generator-fsharp). 

Ideally, we would add new command which just takes all paket.references files there are existing in solution and based on them creates appropriate paket.dependencies file (with some sane defaults - public nuget source etc.)

**Comment by kerams** [comment]
I think it's currently impossible to recreate HTTP and Github dependencies from `paket.references` since the original URL seems to be only stored in `paket.dependencies`.
