### ISSUE TITLE
Couldn't get package details for package Bender

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [fsprojects/Paket#1387]
Hi, I'm trying to convert a solution from Nuget to Paket using convert-from-nuget, but I get this:
 - Bender is pinned to 3.0.29.0
Paket failed with:
        Couldn't get package details for package Bender 3.0.29.0 on http://api.nuget.org/v3/index.json.

It fails every time, if I'm using --force, it restarts the convert process and also breaks with the same error.

I'm guessing it has to do with something specific about that package, but for the sake of completeness: I'm on Windows 10, and my solution folder contains multiple projects and even other solutions (could this cause problems?).

Thanks.

**Comment by forki** [comment]
can you give us the paket.dependencies file that was generated?

**Comment by dcorriveau-omniscient** [comment]
[paket.dependencies.txt](https://github.com/fsprojects/Paket/files/90546/paket.dependencies.txt)

**Comment by isaacabraham** [comment]
@dcorriveau-omniscient it won't be solutions or projects - the resolution / download phase doesn't use them (which is where the error is occurring).

**Comment by dcorriveau-omniscient** [comment]
If I remove Bender, it does the same error for
 - Topshelf.Owin is pinned to 1.3.12.0
Paket failed with:
        Couldn't get package details for package Topshelf.Owin 1.3.12.0 on http://api.nuget.org/v3/index.json.

(the resolution / download is quite slow, I don't know if it's normal but it takes about 2 seconds for each package).

**Comment by forki** [comment]
yes resolution is slow here. already analysing.

**Comment by forki** [comment]
ok. already found the perf issue.

now I can reproduce (blazing fast):

![image](https://cloud.githubusercontent.com/assets/57396/12328005/b5231e56-bad9-11e5-81c3-7a6458f52e56.png)

**Comment by dcorriveau-omniscient** [comment]
You are probably looking at this as we speak, but in case somebody else has the issue and lands on this page, I also get the same error with:

 - SimpleConfig is pinned to 1.0.37.0
Paket failed with:
        Couldn't get package details for package SimpleConfig 1.0.37.0 on http://api.nuget.org/v3/index.json.

**Comment by forki** [comment]
ok in order to get you a bit further. please use Paket 2.42.7 and replace the NuGet v3 souce line with:

    source https://www.nuget.org/api/v2

I'm still trying to figure out what's wrong with the v3. @maartenba is there an issue with Bender on NuGet v3 feed?

**Comment by maartenba** [comment]
Not that I know of. What is the URL that you are requesting that would throw the above error?

**Comment by dcorriveau-omniscient** [comment]
@forki The package resolution is now working after changing to the v2 source and it's indeed "blazing fast". I've fixed a few version dependencies errors that I had (my mistake when creating custom packages) and it seems to complete the nuget conversion.

Danke !

**Comment by forki** [comment]
you should now try to remove as many versions pins as possible from the dependencies file.
Also running paket simplify will help you to clean the deps file.

In the end you only want to have top-level deps in it with as few as possible version restrictions

**Comment by dcorriveau-omniscient** [comment]
And I also had a few subfolders with "unused" projects in them which may have made the whole dependency tree worse than it should be, I'll have some cleanup to do, we'll see how awesome paket simplify is.

**Comment by forki** [comment]
it can do a lot, but it's only a heuristic...

**Comment by forki** [comment]
@maartenba  it's https://api.nuget.org/v3/registration1/bender/3.0.29.0.json

**Comment by forki** [comment]
I guess we have to normalize that one https://api.nuget.org/v3/registration1/bender/3.0.29.json works

**Comment by maartenba** [comment]
Yup

**Comment by forki** [comment]
@dcorriveau-omniscient with latest paket version you can back to the v3 url if you want.

**Comment by dcorriveau-omniscient** [comment]
Yep, it does work. Thanks !
