### ISSUE TITLE
convert-from-nuget oddities

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket#1388]
I'm seeing a lot of projects having net40, net45, net451 and net46 directories with a couple of app.config.* artifacts in them after running ```paket convert-from-nuget --force``` on a solution.

What are these, and how can I prevent them from being generated?

Cheers,
Paul

**Comment by isaacabraham** [comment]
Maybe these are generated from the content outputs of those packages. Can you try putting ```content:none``` at the top of your dependencies file and do a ```paket install``` to see if that removes them?

**Comment by pms1969** [comment]
looks like it's sqlite.

Can get content:none only for that?

<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <system.data>
    <DbProviderFactories>
      <remove xdt:Transform="RemoveAll"
              xdt:Locator="Condition(@invariant='System.Data.SQLite' or
                                     @invariant='System.Data.SQLite.Linq')" />
      <add xdt:Transform="RemoveAll"
           xdt:Locator="Condition(@invariant='System.Data.SQLite' or
                                  @invariant='System.Data.SQLite.Linq')" />
    </DbProviderFactories>
  </system.data>
</configuration>

**Comment by pms1969** [comment]
specifically ```System.Data.SQLite.EF6``` is the culprit.

**Comment by pms1969** [comment]
nevermind.  sussed it.  thanks Isaac

**Comment by isaacabraham** [comment]
Yes - just put the ```content:none``` line on that specific dependency in the .dependencies file.

**Comment by pms1969** [comment]
sorry Isaac to bother you again.  how do I stop it from being pulled in if it's a transient dependency?

**Comment by isaacabraham** [comment]
Just manually add that dependency to the ```paket.dependencies``` file with the ```content:none``` - don't put any version constraints in.

**Comment by pms1969** [comment]
cheers, thought that might be the answer
