### ISSUE TITLE
"Paket pack symbols" also puts the symbols in the non-symbol file

### ISSUE THREAD

**Issue by franknarf8** [fsprojects/Paket#1394]
Hello,

I noticed the 'symbols' flag of the 'pack' command changed behavior recently (it was either created lately or used to only output a single file, I can't recall properly). Anyway, I used to add my sources files manually in the paket.template file and I'm glad this new feature is now online.

I started using 'pack symbols' and I noticed that the .pdb files were also included in the non-symbol.nupkg file.

See repro example : https://github.com/franknarf8/paket-issue-repro/tree/4f8a1ff74bebc37c1dd99270bdaa74db37349c20

A.3.0.0-release.nupkg -> contains A.pdb
A.3.0.0-release.symbols.nupkg -> contains A.pdb + *.cs

Is it intended behavior that the debug symbols (.pdb) are also added to A.3.0.0-release.nupkg?

**Comment by pms1969** [comment]
prior to those changes, the pdb's existed for the project that that the template was for.  This is different to nuget.  I didn't want to break existing behaviour, so for reference projects, I just made sure that the pdb's were also included, as I thought that would be the right thing to do in that situation.  If strict nuget compatability is sought, I think that the referenced project and associated pdb's shouldn't be included unless the command line include-referenced-projects option is set.

personally, I don't mind the PDB's being present, but it's not what nuget does.

Steffen...  thoughts?

**Comment by tsibelman** [comment]
I opened a bug for this issue, I saw that then pdbs are present in main nuget it impossible to get sources from symbols nuget, looks like need to fixed.

**Comment by pms1969** [comment]
Hi @tsibelman, are you saying that because the pdb's are present in the main nuget package, VS fails to download the source package?

**Comment by tsibelman** [comment]
Yes it what I encountered during my testing.

**Comment by tsibelman** [comment]
Here is a duplicate bug #1370

**Comment by pms1969** [comment]
@tsibelman should now be fixed as of 2.45.0

**Comment by franknarf8** [comment]
Everything works works fine now!
Some paket users may not notice the change though and expect the pdb to be in the main nupkg.

**Comment by tsibelman** [comment]
@pms1969 thank you

**Comment by pms1969** [comment]
@franknarf8, the way I worked it, was this:  if you did not request symbols, pdbs are added if your template file has the switch "include-pdbs true"; if you did request symbols, the normal package will not include pdb's of the project file regardless of whether you have "include-pdbs" set or not, and the symols package will always include the pdbs.

might be useful if anyone goes searching for it.

**Comment by amazingant** [comment]
@pms1969:
> might be useful if anyone goes searching for it.

Very useful. Found this while trying to figure out why my packages don't include the .pdb files, as they did when I first set-up my project with paket and FAKE. Haven't had to debug a released build in a while, so I didn't realize this behavior had changed.

**Comment by pms1969** [comment]
not a wasted comment then ;-)

Sorry if it caused you issues, but I don't think there was any easy way to resolve it.

**Comment by amazingant** [comment]
No problem; adding `include-pdbs true` in my `paket.template` files resolves it going forward :)
