### ISSUE TITLE
Bug : Wildcarded source file path in Project file for 'paket pack' symbols flag

### ISSUE THREAD

**Issue by franknarf8** [fsprojects/Paket#1396]
Hello again,

While applying the 'paket pack' 'symbol' flag in our projects, I noticed that there was a bug when paket tried to pack sources files that were wildcarded in the Microsoft project file. Paket crashes with "Illegal characters in path." or "Could not find source file [...]".

e.g.
```
<Compile Include="GENERATED_CS\*.cs" />
```
or
```
<Compile Include="GENERATED_CS_LINKED\*.cs">
  <Link>translated\%(FileName).cs</Link>
</Compile>
```

Here is a repro example : https://github.com/franknarf8/paket-issue-repro/tree/92a01bed12d54b953f518b34979763fa7b14cb01

Thank you

**Comment by pms1969** [comment]
I'll take a look.

**Comment by pms1969** [comment]
@franknarf8, do you know if this was always the case, or was this always a problem?

**Comment by franknarf8** [comment]
Well, that was using the new 'symbol' flag for the 'paket pack' command, so it is fairly recent. I just started using this flag so I unfortunately can't tell you if it once was working with wildcards in the <compile [...]> elements.
Prior to this new flag, to get the source files in the nuget package, we had to manually add them in the paket.template file.

e.g.

```
files
    ../**/*.cs
```

The wildcards worked then, but with the new flag all the source files are added correctly in the .nupkg except for the ones with wildcards.

**Comment by pms1969** [comment]
OK. I know what to do and where, just need to formulate a plan for how.  I'm not a native f# speaker, but I'll get it done soon.

**Comment by pms1969** [comment]
@franknarf8  should be fixed in 2.45.0.  can you give it a shot and let me know how it goes?

**Comment by franknarf8** [comment]
@pms1969 @forki I just tested and everything seems to works perfectly.
Thanks again @pms1969

**Comment by forki** [comment]
Awesome
