### ISSUE TITLE
paket init doc isn't complete

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [fsprojects/Paket#1397]
I think it'd be nice to mention on the `paket init` documenation page (https://fsprojects.github.io/Paket/paket-init.html) that it also creates the paket.targets file. It also seems to download / replace paket.bootstrapper.exe.

One related question I have is: What is the command that adds `<None Include="paket.references" />` and `<Import Project="..\..\..\.paket\paket.targets" />` to the project files ? I've previously run `convert-from-nuget` and other commands on a particular directory structure and if I inspect the project files I can see that those lines have been added, however if I try to `init`, `install` and `update` another project manually, those lines aren't added. In Visual Studio although I can see the `.paket` folder and the `paket.dependencies` file under it, if I try to double click on it to edit it I get "The document cannot be opened. It has been renamed, deleted or moved.".

What's wrong with my workflow, I guess I'm missing a step somewhere ?

Edit: If I run `convert-from-nuget` on that solution folder, the project is "fixed". I can now edit the paket.dependencies file from within VS and the references are listed under (that's more likely related to the VS plugin though). So I'm confused, as this is probably not the "right" way to do it ?

**Comment by matthid** [comment]
`convert-from-nuget` is adding the line you are after. `paket install` is doing a lot of stuff as well.
