### ISSUE TITLE
Order of sources is not respected

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1404]
we have the following paket.dependecy file:

    source Externals/NugetStore
    source https://nuget.org/api/v2

    nuget npgsql 2.2.5

The situation is as follows - in both locations is a package with the specific version number (in the file feed is a custom patched version). Before 2.42.7 paket respected the order of the sources. But since >= 2.42.7 paket always resolves this package with the nuget feed. I assume some changes to the package discovery and making this asynchronous made this change.
Is this behavioural change intended and is there a possibility to rely on the order?

**Comment by forki** [comment]
Yes the change was intentional and only affects explicitly pinned versions.
The issue is that nuget.org responds much faster than many other feeds and
therefore we check it first.

I didn't think of packages that are manipulated.
Need to think about a strategy here.

**Comment by forki** [comment]
Would it help if you put the package into another group?

**Comment by Stift** [comment]
I think I can give our custom packages a package stream name like 2.2.5-custom and we pin that (which is maybe more better).
I'm not sure whether we have to think about this, because to have the same packages (with the same version) in two different feeds is also a little workaround by us. 

The group would not help because all the packages that depend on that one I would also have to put in the same group, right?

If you don't want to think about it, just close the bug, I'll do the renaming of the package.

**Comment by forki** [comment]
I think the issue is really perf. I goes down like 100x on deps files with
many pinned versions (like you have after convert)

**Comment by Stift** [comment]
Yeah. I completely understand.
You should close the issue, when we don't want to enable/introduce order precedence.
