### ISSUE TITLE
Feature Request: Ability to pass in tokens for replacement to Pack

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket#1411]
Feature request:

the Fake nuget pack command allows for passing tokens into the command that replace the token wrapped in dollar signs ($) in the template file.

It would be useful to have this facility available in paket from the command line.
Something like
`paket pack output temp symbols tokens "configuration=Release|id=MyId"`
where the tokens are split by "|" and replaced at the point the template is read into memory.

The template file could look something like this then

```
type project
id $id$

files
    bin\$configuration$\*.txt
```

Any thoughts?

**Comment by inosik** [comment]
I wouldn't implement this directly in Paket. With `paket.template`s simple format, it's very easy to do this with FAKE, while beeing much more flexible and powerful.

**Comment by pms1969** [comment]
How do you do it with fake, and also, how do you do it from the command line if it's not available as a command line option?

**Comment by inosik** [comment]
I've put a gist together, similar to what I'm doing in one of my projects:
1. Create a `paket.template` template (:wink:), like [this one](https://gist.github.com/inosik/64707bfa6c944868f617#file-paket-template_template).
2. Create a target in your [Fakefile](https://gist.github.com/inosik/64707bfa6c944868f617#file-fakefile-fsx) and plug it into your build pipeline.
3. `Paket.Pack`

**Comment by pms1969** [comment]
That's actually, some pretty awesome stuff.  I like the renaming.  The only thing it doesn't give me is the ability to just run a command line ```paket pack```.

I've had a rummage around, and think I know how to implement this in paket fairly easily.  Given your gist, outside of usage in fake is about the only thing you'd consider this for.  I guess it's a mater of how wide an audience you want to appeal to.

**Comment by inosik** [comment]
You can set up your build targets and then call call FAKE like `fake.cmd pack -ev project_url http://blah`. Depending on your dependency graph, only things related to `Pack` will be executed. 

The thing is, with some sane defaults, and the possibility to override them, you don't need to call `paket pack ...` every time.

**Comment by magne** [comment]
It would be nice to be able to include files (like resources) without preprocessing the template file. E.g.
```
type project
id someid

files
    $(OutputPath)/no/someresource.dll ==> lib/$(Framework)/no
```
where `OutputPath`is the output path from the project file, and `Framework` may be some variable passed in on the command line.

**Comment by matthid** [comment]
I'm kind of agreeing with @inosik here. Additionally it apparently wasn't important enough for someone to come up with a PR.
