### ISSUE TITLE
update "updates" to symbol packages when using filesystem source with symbol packages

### ISSUE THREAD

**Issue by mlidbom** [fsprojects/Paket#1413]
paket.dependencies:
```
  ....
  source ..\..\NuGetFeed
  .....
  nuget SomePackage prerelease
```

..\..\NuGetFeed contains both normal and symbol packages.

After I run paket update I end up with this broken lock file and symbol packages in my packages folder :

paket.lock:
```
....
SomePackage (3.4.0-beta02.symbols)
...
```

**Comment by forki** [comment]
Interesting. Is this a local file/directory nuget feed? 

Can you create 2 small packages (and mail me)  that we can take as integration tests?

**Comment by mlidbom** [comment]
Yes it is a local nuget feed.
And it turns out the same thing happens without prerelease in the dependencies file. Seems paket likes symbol packages :)
I'll see if I can cook up a repro for you. Hang on :)

**Comment by mlidbom** [comment]
FYI: Mailed you a zip with a minimal repro. Hope it gives you what you need.

**Comment by forki** [comment]
Doesn't look like I got it. Please try sforkmann at gmail

**Comment by mlidbom** [comment]
Gmail would not let me send the zip file. See my previous comment. I attached the zip file there so you can just download it from here.

**Comment by forki** [comment]
Ok will check later today

**Comment by mlidbom** [comment]
Thank you for once again fixing issues with very commendable speed :)
