### ISSUE TITLE
paket remove does not delete packages content

### ISSUE THREAD

**Issue by jruizaranguren** [fsprojects/Paket#1416]
When a dependency is removed from `paket.dependencies` or alternatively when `paket remove nuget nuget_id` is called, all the previously downloaded files stay in drive.

This content is garbage. It would be great if `remove` get rid of all package content in `packages` or `paket-files`.

**Comment by ivankoster** [comment]
I would actually propose to also implement garbage removal on install / update commands.
If I change the packet.dependencies file and perform an install command, I'd like the packages that are no longer referenced to be removed from disk.

**Comment by cdrnet** [comment]
Downloaded packages in the `./packages` folder can also become garbage passively by VCS operations like `git checkout`, where the lock file gets updated. Dropping downloaded packages as part of the install/update process (based on the changes it applies to the lock file) would therefore only reliably keep the `./packages` folder clean if that folder is actually checked into the VCS as well.

Do we assume that Paket "owns" the `./packages` folder, so it could technically garbage collect based on the lock file? If not, can it reliably find out which of the packages within were originally downloaded and put there by Paket?

**Comment by forki** [comment]
Yes we assume packages folder is owned by paket.

**Comment by forki** [comment]
comes with v3
