### ISSUE TITLE
Pin framework version?

### ISSUE THREAD

**Issue by CumpsD** [fsprojects/Paket#1425]
I am having an issue right now with something about Serilog, if you clone https://github.com/exira/user-ops/tree/98789c22fb9dbcec6f79028b6f039e8bccb4aa9c and run `build.cmd` you'll notice, some weird F# static linking error.

When I manually change the fsproj file to target the `net40` version of Serilog in their nupkg, everything works fine.

So I am wondering, if it is possible with Paket to tell it to use a specific version? (In this case it would pick `net45` in the fsproj)

**Comment by forki** [comment]
Did you try 

   Serilog framework: net40

?

**Comment by CumpsD** [comment]
In paket.lock?

**Comment by forki** [comment]
In dependencies file. Then run install or update

**Comment by forki** [comment]
http://fsprojects.github.io/Paket/nuget-dependencies.html#Framework-restrictions

**Comment by CumpsD** [comment]
I tried `nuget Serilog >= 1.0 framework: net40` but it probably conflicting with other dependencies, the lock looks like:

```
    Serilog (1.5.14)
    Serilog.Extras.Attributed (2.0.0)
      Destructurama.Attributed (>= 1.0)
    Serilog.Sinks.Seq (1.5.27)
      Microsoft.Net.Http (>= 2.2.20) - framework: net40
      Serilog (>= 1.5.10) - framework: >= net40
```

and the fsproj still generates:

```
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0')">
      <ItemGroup>
        <Reference Include="Serilog.FullNetFx">
          <HintPath>..\..\packages\Serilog\lib\net40\Serilog.FullNetFx.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="Serilog">
          <HintPath>..\..\packages\Serilog\lib\net40\Serilog.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1')">
      <ItemGroup>
        <Reference Include="Serilog.FullNetFx">
          <HintPath>..\..\packages\Serilog\lib\net45\Serilog.FullNetFx.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="Serilog">
          <HintPath>..\..\packages\Serilog\lib\net45\Serilog.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
```

**Comment by forki** [comment]
Mhm that one explicitly wants that other framework

**Comment by CumpsD** [comment]
Hmmm, ok, nothing to do about it then, I'll be in this static linking error mess for a while longer :(

Thanks anyway

**Comment by forki** [comment]
I suppose we could come up with something like framework == net40

**Comment by CumpsD** [comment]
Wouldn't that break things? Since that other one explicitly wants net45, maybe it has a reason ;)

**Comment by forki** [comment]
Yeah, but you are the user. You might know better.

**Comment by CumpsD** [comment]
I know it compiles when I change it manually in the fsproj, doesn't mean I am sure it will never give a runtime error.

I should probably try to figure out why the F# compiler blows up when I reference net45 of Serilog and not with net40 (somebody pointed me towards IReadOnlyDictionary being a problem inside Serilog)
