### ISSUE TITLE
Pack no longer generates dependencies based on referenced projects in a solution

### ISSUE THREAD

**Issue by kolektiv** [fsprojects/Paket#1429]
Paket pack given a template would generate dependencies for the other referenced projects in the solution which also had template files (and thus would also be packages). Given a project One and a project Two in a solution, if both had a paket.template, and Two referenced One, when generating the package, Paket would include One as a dependency of Two in the generated package.

This stopped working in the 2.46.2 -> 2.47.0 range (see https://github.com/fsprojects/Paket/compare/3239957ebef558761a98ad0d23c539ea910786f6...3334d3d6730a703f2ae1f1f945bb5470d6455d7b for a relevant comparison). It seems like the work to bring in referenced projects dependencies (which I'm not sure I understand the point of) may have wiped out this functionality. It is possible that this functionality would still work if `include-referenced-projects` was passed to Paket, but this configuration option does not yet appear in the Paket helper in Fake, so it's difficult to test this possibility.

Either way, I would consider it a regression, either removing the functionality without intent, or moving it behind a switch which previously did not exist and thus was a default `true`. I published a horribly broken set of packages today which had half of their dependencies missing before noticing this - hopefully I'll be the only one :smile: - thankfully they were prerelease!

If any more info is needed to repro, don't hesitate to ask...

**Comment by inosik** [comment]
Same here. `include-referenced-projects` seems to help, but I think that the behavior shouldn't have changed in first place.

**Comment by forki** [comment]
confirmed. this is a regression and shouldn't have happened.
I though we only add behaviour under the switch. The old automatic dependency recognition shouldn't change.

I'm working on integration tests and will try to come up with a fix.

**Comment by kolektiv** [comment]
Update: Confirmed fixed for my original case in 2.47.2.0 :smile: Thanks!
