### ISSUE TITLE
paket pack with enabled include-referenced-projects flag fails with NRE

### ISSUE THREAD

**Issue by ar3cka** [fsprojects/Paket#1434]
Find the build log here https://ci.appveyor.com/project/ar3cka/journalist

**Comment by forki** [comment]
I can reproduce

**Comment by forki** [comment]
@pms1969 I fixed it in https://github.com/fsprojects/Paket/pull/1435, but I'm not completely sure why that was in there. Any ideas?

**Comment by forki** [comment]
@ar3cka I released a new paket prerelease which allows you to test if the behaviour is correct. I mean the NRE should be gone, but you should look if the packages are built correctly.

**Comment by pms1969** [comment]
ok, I'll check it out.

**Comment by pms1969** [comment]
looks good.

**Comment by ar3cka** [comment]
I've checked. Package contains all assemblies. Thx.
