### ISSUE TITLE
Documentation formatting glitch

### ISSUE THREAD

**Issue by mexx** [fsprojects/Paket#1439]
The reference is not correctly rendered in this blockquote.
![image](https://cloud.githubusercontent.com/assets/378088/12640041/2de4ad4a-c5a8-11e5-8006-1f9ff33003c7.png)

**Comment by mexx** [comment]
It's on https://fsprojects.github.io/Paket/nuget-dependencies.html

**Comment by mexx** [comment]
Nope :unamused: 
![image](https://cloud.githubusercontent.com/assets/378088/12642612/35b057cc-c5b7-11e5-9367-d6946d416b16.png)

I don't know, maybe it's a problem in FSharp.Formatting with links in blockquotes?

**Comment by forki** [comment]
or with your cache ;-)

**Comment by mexx** [comment]
I hate caches ;)
