### ISSUE TITLE
Use a different repo for the github dependency example

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#1441]
http://fsprojects.github.io/Paket/github-dependencies.html#Referencing-a-GitHub-repository

`reveal.js` also looks like the name of a javasript file, maybe it'd be better to use a repository that doesn't have a name that looks like it ends with a file extension for the sake of clarity, e.g.
https://github.com/fsharp/FAKE or https://github.com/jack-pappas/ExtCore
;)

**Comment by forki** [comment]
care to send a PR?

2016-01-29 15:09 GMT+01:00 Jared Hester <notifications@github.com>:

**Comment by cloudRoutine** [comment]
#1446
