### ISSUE TITLE
If a dependent assembly is .NET 4.5.1, and the current project is .NET 4.5, it will silently fail

### ISSUE THREAD

**Issue by sharpe5** [fsprojects/Paket#1442]
How about a meaningful error if paket is failing to import dependent assembles, due to a .NET framework mismatch?

Scenario: We had an entire team of 10 developers trying to fix issues with Paket. No matter what we did, a "paket install" would not import a required assembly.

Eventually, after 4 hours and 3 senior developers had tried and failed to fix the issue, we realized that the dependent packaged assembly was .NET v4.5.1, which wouldn't load into a project configured for .NET 4.5.

**Comment by forki** [comment]
Unfortunately that is not always an error. Many packages are only used for some .NET framework versions and have counterparts in other nuget packages or the framework itself for other framework versions.

That said: would it have helped you if we provide a big yellow warning? We could warn if a framework was selected in the project but the install conditions create a empty lib set.

**Comment by forki** [comment]
It could look like this:

![image](https://cloud.githubusercontent.com/assets/57396/12681718/469cf2ee-c6b0-11e5-90e5-13a394d44d45.png)

**Comment by forki** [comment]
corresponding PR https://github.com/fsprojects/Paket/pull/1445

**Comment by sharpe5** [comment]
Thank you for your quick reply. It would definitely help if there was a yellow warning. 

In Visual Studio, unfortunately, I think the "Output" view is monochrome if the Paket Extension Tool is used, so it might be an idea to empahasize it with some surrounding stars.

**Comment by sharpe5** [comment]
Brilliant, that would work nicely!!

**Comment by CumpsD** [comment]
Any way to be smarter then the resolver and ask paket to reference a "wrong" target framework? :)

**Comment by forki** [comment]
Only manually
