### ISSUE TITLE
paket.references gets <SubType>Designer</SubType>

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#1449]
For some reason I get the following in my `.csproj` files:
```
<None Include="paket.references">
  <SubType>Designer</SubType>
</None>
```

I don't know why this happens. I usually drag `.references` files between (C#) projects to copy them, maybe it has something do to with it? 

The SubType thing makes VS pick a strange editor for the files.

Is `<SubType>Designer</SubType>` designer ever desired? 
If not would it be a good idea to have Paket remove it if it exists?

**Comment by forki** [comment]
Yes. Please send a pull request to clean up this. I think it's a VS issue

**Comment by mexx** [comment]
FYI: I had `<SubType>Designer</SubType>` attached after the NuGet conversion, when `packages` node had this one attached.

**Comment by forki** [comment]
Mhm.

**Comment by JohanLarsson** [comment]
@mexx that can explain it, I have converted most things.

**Comment by forki** [comment]
did the original package.config file had `<SubType>Designer</SubType>`?

**Comment by forki** [comment]
if yes then 73ec6da might fix it

**Comment by JohanLarsson** [comment]
I think this is solved, have not seen it in a long time.
