### ISSUE TITLE
Cannot download packages from VSTS package feed

### ISSUE THREAD

**Issue by biohazard999** [fsprojects/Paket#1453]
When you use the new Visual-Studio-Team-Services [package feeds](https://www.visualstudio.com/get-started/package/what-is-packaging) paket can't download them.

Finding packages is okay, but when paket want's to download them i get a 400 bad request:

```
Something went wrong while downloading Scissors.Utils.IO 0.2.0
Message: Could not download Scissors.Utils.IO 0.2.0 from https://pizvsblobprodsu6weus79.blob.core.windows.net/b-e309e533efef4fb59d88816df1e098fd/61F56B302D1AC1096845D3656E2ED9E1671E909EA75FADAF55E0B4DB799289B400.blob?sv=2014-02-14&sr=b&sig=0M0jiHqN4P3ExisNY%2FEHfBm5jyaL%2BSebrCsN7BtYeQA%3D&st=2016-02-02T09%3A23%3A23Z&se=2016-02-02T13%3A28%3A23Z&sp=r.
    Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
```
```
source https://www.nuget.org/api/v2
source https://mgrundner.pkgs.visualstudio.com/DefaultCollection/_packaging/Dev/nuget/v2 username: "%PRIVATE_FEED_USER%" password: "%PRIVATE_FEED_PASS%"

nuget xunit
nuget xunit.runner.visualstudio version_in_path: true
nuget Humanizer
nuget Scissors.Utils.Http
nuget Scissors.Utils.IO

```
If you need a package source to reproduce i think i can provide a token.
I don't know if this is paket specific or prerelase stuff, but with nuget it is working. No idea what black magic is going on in azure.
The install log with the verbose option is attached.

Thanks Manuel

[paket_install.txt](https://github.com/fsprojects/Paket/files/115503/paket_install.txt)

**Comment by forki** [comment]
Yes please send me a repro. Dependencies file with password included to sforkmann at gmail

**Comment by biohazard999** [comment]
Mail is on the way

**Comment by forki** [comment]
does it work?

**Comment by biohazard999** [comment]
awesome thanks!
