### ISSUE TITLE
Paket add causes unsaved changes to be lost

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [fsprojects/Paket#1454]
When using commands that are unloading and reloading projects such as paket add, the user is not prompted to save changes before executing the command, which results in losing any unsaved changes. For example, if you add a file to your solution, work in it and add a package, the file itself won't be included in the project anymore and your new changes (besides the default code included when you create a new file) will be lost.

I'm suggesting we detect if the projects are dirty and prompt for saving those projects (y/n in the console) and ideally the regular windows save prompt when it's done from the UI.

**Comment by forki** [comment]
Are you talking about the VS addin? This is the command line tool repo and we can't know if VS is in dirty state.

**Comment by dcorriveau-omniscient** [comment]
I was hoping it would be possible to detect from the command like tool, so that it could be fixed in both cmd and VS addin.

**Comment by forki** [comment]
how? we don't know which editor you use

2016-02-03 16:40 GMT+01:00 dcorriveau-omniscient <notifications@github.com>:

**Comment by dcorriveau-omniscient** [comment]
Not sure how, yet, but since the projects are unloaded, I'm guessing you know that's VS and you purposefully unload them. I haven't looked at paket's code though (that specific part), so maybe there is some magic that makes that happen automatically. From that I also assumed you would be able to know if it's dirty, but maybe that's impossible (although I would be surprised if there would be no ways to determine that).

**Comment by forki** [comment]
we do not unload from the command line. We don't even know that VS is open

2016-02-03 16:52 GMT+01:00 dcorriveau-omniscient <notifications@github.com>:

**Comment by dcorriveau-omniscient** [comment]
Yea I just looked at the addin code, and that's only where you are doing the unloading. Would it be OK if I update the VS addin to prompt the user to save if the project is dirty, the same way it does it when you manually unload a project ? Our users are using the UI only so it would be OK for us if it would be fixed in the addin only.

**Comment by forki** [comment]
sure. but I thought we already save...

2016-02-03 17:06 GMT+01:00 dcorriveau-omniscient <notifications@github.com>:

**Comment by dcorriveau-omniscient** [comment]
I've seen some places where you do it, but I don't think you do it when adding new packages. Personally I think it would be better if we would prompt instead of automatically saving, but it doesn't seem to bother my coworker when the solution is saved automatically so, since we have different opinions I'm not sure...

**Comment by forki** [comment]
I think the important point is that we don't lose work. ;-)

2016-02-03 17:13 GMT+01:00 dcorriveau-omniscient <notifications@github.com>:

**Comment by dcorriveau-omniscient** [comment]
Looks like it can only be done from within VS so it's been committed in the VS Addin only.
fsprojects/Paket.VisualStudio/pull/97

**Comment by forki** [comment]
Thanks for taking care of this.
