### ISSUE TITLE
Paket do not keeps versions locked for dependencies

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1457]
Hi have following paket.dependencies file I set all 3 dependencies to be locked to specific version

source https://www.nuget.org/api/v2/

framework: net451
redirects: on

nuget Microsoft.Orleans.Core **1.1.1**
nuget Microsoft.Orleans.CounterControl **1.1.1**
nuget Microsoft.Orleans.OrleansRuntime **1.1.1**

When paket.lock is created it looks like this:

Microsoft.Orleans.Core (1.1.1)
    Newtonsoft.Json (>= 6.0.8)
Microsoft.Orleans.CounterControl (1.1.1)
    Microsoft.Orleans.Core** (>= 1.1.1)**
    Microsoft.Orleans.OrleansRuntime** (>= 1.1.1)**
Microsoft.Orleans.OrleansRuntime (1.1.1)
    Microsoft.Orleans.Core** (>= 1.1.1)**

All dependencies are more permissive that is specified. I understand that these dependencies ranges are coming from nugets but I think they should be overridden in lock file. This will allow us to force users to use specific version of  transitive dependencies

**Comment by forki** [comment]
The indented lines are only showing the restrictions from the package nuspec. They are combined with the stuff that you specify in the dependencies file. As a result you see that we select the correct versions.

**Comment by forki** [comment]
In other words: indented lines are only for information. They don't represent what we select

**Comment by tsibelman** [comment]
Ok I see that when I create nuget packages the dependencies from paket.dependencies are not used in nuspec

**Comment by forki** [comment]
Or maybe I don't understand what you are describing.

**Comment by tsibelman** [comment]
I will try again :)

I created some nuget let's call it Common.dll, that has dependency on 3 Microsoft.Orleans nugets of specific version, I checked the nuspec file and it looks like all dependencies there are correct, here a sample:

      <dependency id="Microsoft.Orleans.OrleansRuntime" version="1.1.1" />
      <dependency id="Microsoft.Orleans.CounterControl" version="1.1.1" />
      <dependency id="Microsoft.Orleans.Core" version="1.1.1" />

But when I use the Common.dll nuget in my other project I don't get 1.1.1 versions but get 1.1.2 version of Orleans dependencies.

**Comment by tsibelman** [comment]
Ok I see the issue version="1.1.1" should be specified as version="[1.1.1]"

**Comment by forki** [comment]
<dependency id="Microsoft.Orleans.OrleansRuntime" version="1.1.1" />

means >= 1.1.1

**Comment by tsibelman** [comment]
Now i don't understand

**Comment by forki** [comment]
sorr reformatted

**Comment by tsibelman** [comment]
Yes but in paket i wrote it as specific version

**Comment by forki** [comment]
are you sure? Can I see a repro?

**Comment by forki** [comment]
wait a minute. I think I can reproduce

**Comment by tsibelman** [comment]
You can use the samples I used in first post.

**Comment by forki** [comment]
mhm. sorry I can't reproduce. https://github.com/fsprojects/Paket/commit/050bafb1b1ec55ce8356a9960fe7eb315d15a40f shows correct behaviour.

**Comment by tsibelman** [comment]
Hi I am atached scenario that reproduce it, rename file to zip


[ConsoleApplication1.txt](https://github.com/fsprojects/Paket/files/117401/ConsoleApplication1.txt)

**Comment by forki** [comment]
If I do pack I get:

    <?xml version="1.0" encoding="utf-8" standalone="yes"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
      <metadata>
        <id>ConsoleApplication1</id>
        <version>1.0.0.0</version>
        <title>ConsoleApplication1</title>
        <authors></authors>
        <description></description>
        <dependencies>
          <dependency id="Microsoft.Orleans.OrleansRuntime" version="[1.1.1]" />
          <dependency id="Microsoft.Orleans.CounterControl" version="[1.1.1]" />
          <dependency id="Microsoft.Orleans.Core" version="[1.1.1]" />
        </dependencies>
      </metadata>
    </package>

**Comment by tsibelman** [comment]
I use following command to pack: paket pack output nugets minimum-from-lock-file buildplatform x64

**Comment by forki** [comment]
>> minimum-from-lock-file 

Why did youn say that before? ;-)

**Comment by tsibelman** [comment]
From my point of view every one should use minimum-from-lock-file exclusively :)

**Comment by forki** [comment]
nope, that's only one of possible workflows.

**Comment by forki** [comment]
anyways will add a test and a fix for that

**Comment by tsibelman** [comment]
Thank you

**Comment by forki** [comment]
please try latest

**Comment by tsibelman** [comment]
Works perfect thank you
