### ISSUE TITLE
Support (Conditional) Framework Assembly References

### ISSUE THREAD

**Issue by bartelink** [fsprojects/Paket#146]
This is a split of an original issue #68 which, after some analysis breaks out into more than one problem.

I'm using latest of `Microsoft.AspNet.WebApi` which (indirectly) pulls in `Microsoft.Net.Http`. It's `.nuspec` has:

```
  <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Net.Http.WebRequest" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework="MonoTouch0.0" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework="MonoAndroid0.0" />
    </frameworkAssemblies>
```

The current workaround is to add the reference manually on 4.5 / 4.5.1.

The current problem with that workaround is that #145 clashes with this and puts in a reference to the `net40` version of the assembly if it's absent at `paket install` time.

Related: #140 (similar conditions on NuGet package references)
Related: #154 (file pakets should be able to specify framework requirements too)

**Comment by forki** [comment]
Already fixed
