### ISSUE TITLE
Paket.Bootstrapper prelease behavior

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#1464]
It seems as though the bootstrapper uses the release date instead of the version number in the tag

![](http://i.imgur.com/xFUhbVv.png)

Which has led to paket breaking when I've been relying on paket3 functionality that does not exist in 2.49.6 

Should the desired behavior be to download based on the chronological order or semantic versioning number?

**Comment by forki** [comment]
Yes it should use real semantics

**Comment by inosik** [comment]
Maybe you should try to update the bootstrapper first, the one in the Ionide repo was committed 9 months ago, which means it doesn't include #1236 (and #1241). I think you have a related issue to the one I tried to fix.

**Comment by forki** [comment]
any news here?

**Comment by Krzysztof-Cieslak** [comment]
Can be closed, working well after updating bootstraper to latest.
