### ISSUE TITLE
Paket and C++ projects?

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1467]
My colleague reported that Paket does not work right for C++ projects, while NuGet does.
What is the design decision here - is it even supposed to support C++ projects or not? 
If it supposed to support C++, then I gather more details about the problem from my colleague.
If it is not supposed to support C++, then can we have Paket and NuGet used in the same solution?

Thank you!
Konstantin

**Comment by forki** [comment]
yes please give details. Maybe it's just fixing https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/ProjectFile.fs#L229 and https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/ProjectFile.fs#L108

**Comment by forki** [comment]
I will try it out

**Comment by forki** [comment]
what is the correct project file ending?

**Comment by forki** [comment]
Ok. let's make this a thing. paket 2.50.0 comes with experimental support for vcxproj. Please let me know how badly it breaks you.

![granate](https://cloud.githubusercontent.com/assets/57396/12924410/25a342b6-cf5a-11e5-8518-cb81408acf48.gif)

**Comment by konste** [comment]
Looks encouraging... But we are brave! My colleague Tommy, who mostly cares about C++ will be looking at it shortly. Thanks for the swift response!

**Comment by forki** [comment]
yeah I added a small integration test with a "file new C++ project". It seems to reference it correctly, but I assume this is only the tip of the iceberg.

**Comment by tommysu** [comment]
Thanks, I plan on giving a go today.  A quick question will be what do you recommend we put for the "framework" or should I just leave that out?

**Comment by forki** [comment]
in the dependencies file?

Good question. I guess start by leaving it out.

**Comment by forki** [comment]
to clarify: I want to make this useful for C++, but since I don't use C++ myself it will likely involve some ping pong during the initial dev/testing phase.

**Comment by tommysu** [comment]
Yea, in the dependencies file.  I'm going to try it empty.  In nuget we would do something like this:   <package id="boost" version="1.60.0.0" targetFramework="native" />.  I'm giving 2.50 a try and will let you know soon the result.

**Comment by forki** [comment]
better remove the line completey (at least for now) we can add it back later when we know the correct framework monikers.

**Comment by tommysu** [comment]
This was able to include the library files correctly.  However, one thing that it was missing was the target files.  

An example is:
```
 <ImportGroup Label="ExtensionTargets">
    <Import Project="..\packages\cpprestsdk.v120.winapp.msvcstl.dyn.rt-dyn.2.7.0\build\native\cpprestsdk.v120.winapp.msvcstl.dyn.rt-dyn.targets" Condition="Exists('..\packages\cpprestsdk.v120.winapp.msvcstl.dyn.rt-dyn.2.7.0\build\native\cpprestsdk.v120.winapp.msvcstl.dyn.rt-dyn.targets')" />
```
   
When following the nuget instructions for this package:

https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial

**Comment by forki** [comment]
ok will look at this tommorow.

**Comment by forki** [comment]
@tommysu can you please send me the project that you get after "getting started" using Nuget? sforkmann at gmail

**Comment by tommysu** [comment]
Sent.

**Comment by forki** [comment]
I'm pushing a new version but I'm not sure if the "when conditions"  are generated properly. So I assume we need to iterate on that. But it is progress ;-)

**Comment by forki** [comment]
Ok release failed. I broke another integration test. Good thing that we have these in place. Will look into this tomorrow.

**Comment by forki** [comment]
Ok the version is released

**Comment by tommysu** [comment]
It appears that the project file will get corrupted it.  It generates a When condition with uneven number of ' marks.  And Visual Studio will complain of An unexecpted token "=="

  <Choose>
    <When Condition="$(Platform)'=='Debug|Win32'">

**Comment by forki** [comment]
ah. my copy paste bug. fixing it now.

**Comment by forki** [comment]
fixed that

**Comment by tommysu** [comment]
Sorry for going back and forth.  But it looks like the target file path is incorrect.

 `<Import Project="..\packages\cpprestsdk.v120.winapp.msvcstl.dyn.rt-dyn\build\$(__paket__cpprestsdk_v120_winapp_msvcstl_dyn_rt-dyn_targets).targets" Condition="Exists('..\packages\cpprestsdk.v120.winapp.msvcstl.dyn.rt-dyn\build\$(__paket__cpprestsdk_v120_winapp_msvcstl_dyn_rt-dyn_targets).targets')" Label="Paket" />
 `

It should be something like  \build\native\$(...).targets

**Comment by forki** [comment]
Ah I see. Yes this is completely different to the other target framework
stuff.

**Comment by forki** [comment]
Ok an another fix deployed. Please run "paket clear-cache" before you try again.

**Comment by tommysu** [comment]
Awesome, that works!  I'll let you know if I run into any more issues.

**Comment by forki** [comment]
Wow. Cool.

**Comment by forki** [comment]
Closing this one. 

Please open new issues for the new issues you find.
