### ISSUE TITLE
Paket holds on to files previously restored (via install)

### ISSUE THREAD

**Issue by haraldsteinlechner** [fsprojects/Paket#1477]
In my build script i use paket's install mechanism in order to install and restore packages. Afterwards i override some of the installed packages with packages, just compiled from source. 
(similar to cabal sandbox add-source)
After some debugging i could not figure out what function is holding on to extracted files.
concretely my pseudocode looks like:

```
let p = Paket.Dependencies.Locate(Environment.CurrentDirectory)
p.Install(false,false)
// here some dll's in packages folder are kept open, thus i get accessdenied exception in continuation.
restoreSourceDependencies()
```

my current version of paket is:  Paket.Core (2.48.2)

before further debugging, do you have any ideas what parts of the install procedures could hold on to file handles?

any ideas?
thanks harald

**Comment by haraldsteinlechner** [comment]
ok it seems to be related to assembly binding redirect stuff.
I have absolutely no clue why this happens (according to msdn docu) but this commit "fixes" this issue for me:
https://github.com/haraldsteinlechner/Paket/commit/09d17f32f02a4ac1cd9dfa1ae56f2c71e2253dc1

I tested the situation separately in fsi.exe and found that indeed System.Reflection.Assembly.ReflectionOnlyLoadFrom holds on to the file after returning. Note that i cannot reproduce the problem with copyShadowAssemblies enabled. 
Now comes the really odd part: i invoke my FAKE script already with shadow assemblies enabled. 

After all, not understanding the problem completely, we could simply load the file as demonstrated in my commit but i don't know what effects this could have.

**Comment by isaacabraham** [comment]
@haraldsteinlechner can you just send the link to the MSDN doc? And (ideally) a failing test for this (if possible and not a lot of work!)

Cheers

**Comment by haraldsteinlechner** [comment]
what i meant with docu is that: https://msdn.microsoft.com/en-us/library/system.reflection.assembly.reflectiononlyloadfrom(v=vs.110).aspx says nothing about holding on to fileHandles
