### ISSUE TITLE
Docs: difference between = and == operators isn't clear, could use example

### ISSUE THREAD

**Issue by rmunn** [fsprojects/Paket#1481]
The https://fsprojects.github.io/Paket/nuget-dependencies.html page describes using `=` to specify an exact version match, which seems pretty clear to me, then describes using `==` to manually resolve a version conflict. It then says:

> Important: If you want to restrict the version to a specific version then use the = operator. The == operator should only be used if you need to overwrite a dependency resultion due to a conflict.

But this paragraph isn't at all clear to me. I don't have a good grasp of when the `==` operator would be needed or how it should be used. Are you specifying a specific version of the "root" dependency? Of one (or more) of the transitive dependencies? An example of a version conflict, which could be resolved using `==`, would help a lot.

Also, I just noticed that the word "resultion" in that paragraph is misspelled and should be "resolution".

**Comment by forki** [comment]
Imagine a situation with 3 packages A, B and C.

A and B are your direct (or root level) dependencies, but both have a
dependency on C. A wants version (exactly) 1.0 and B wants version 1.1 of
C. This is a version conflict and paket will complain during resolution
phase.

If you specify C = 1.1 in the dependencies file then it's still considered
a version conflict with the version requirement in A. By specifying A ==
1.1 you overwrite all other requirements and paket will not complain about
the conflict anymore.

I hope that helps, if so I would love to see a PR to the docs with an
addition of this at a place where would have helped you.
