### ISSUE TITLE
How to easily update a chain of internal projects?

### ISSUE THREAD

**Issue by orloffm** [fsprojects/Paket#1484]
I have a tree of internal projects that use each other via `.nupkg` files. I increase the version number of some `Tools` library. How do I then update the `.lock`ed version of this package in all other solutions? There is no way to do it other than calling `paket update` manually on each solution, right?

**Comment by sergey-tihon** [comment]
If you would like to update all solution simultaneously you probably want to have simple `.dependency` and `.lock` file for all solutions. Why do you separate them?

**Comment by orloffm** [comment]
Because a solution is a self-contained unit. It would be ridiculous to have the `Tools` library in a shared `.dependencies` used by `Tools.sln`.

**Comment by orloffm** [comment]
To approach this problem from another point of view.

I have the projects (and dependencies):
`A`
`B` (`A`)
`C` (`A`, `B`)

Say, currently they are all 1.0.0 and reference each other via some feed/folder with `.nupkg` and have that versions in their `.dependencies` and `.lock` files.

Now, I introduce a CI strategy. I change `AssemblyInformationalVersion` in TeamCity on each build, so `A` builds as version `1.0.0-pre001`. What should I do with `B` and `C`?

I can think of two approaches.

1) Do not submit the `.lock` file to the source control. Do `paket install` each time instead of `paket restore`.
2) Submit the `.lock` file, call `paket update <groupname>`. This requires `.lock` file to be checked out (from Perforce), which is ugly.

I can't understand how to make it all work together, would be greatful for any comments.

**Comment by cdrnet** [comment]
Do B and C always have to automatically use the newest version of A, meaning you do not actually want to control the versions at all (thus no need for repeatable builds)? Or is this just one specific CI build e.g. to detect potential conflicts early on?

**Comment by cdrnet** [comment]
On 1) wouldn't you then have to check out the project files, since `paket install` may affect them?

**Comment by orloffm** [comment]
> since paket install may affect them?

Yes, I also just realized the project files are _always_ affected, even if no changes are made.

> Do B and C always have to automatically use the newest version of A

Well, I think they can reference `A` as `~> 2.0`, for example. So if I also have a local folder into which I build a local `2.0.0` version, that way `paket install`/`update` will grab that local version instead of anything prerelease in the global feed.

It comes down to what to do with `paket.lock` or `project.csproj` files. Maybe if the project files are not changed, they should not be overwritten at all?

**Comment by cdrnet** [comment]
Just to understand your scenario: If you do two builds form exactly the same source code revision of B you would expect two different results/outputs if a new version of A has been built in between (without touching A at all)?

**Comment by orloffm** [comment]
@cdrnet So basically, after https://github.com/fsprojects/Paket/issues/1471 and https://github.com/fsprojects/Paket/commit/c6bfd752ddac8531782f2557fbeb69101c63fc90 project files are _always_ touched when doing `paket install` in abscence of `paket.lock`, even if nothing was changed.

Can it be covered with some optional flag? Maybe reuse the same `--touch-affected-refs`?

To reiterate, what i want is to get the latest available versions on each build without touching/updating/checking out anything.

**Comment by orloffm** [comment]
@forki Can you please explain? Now, after https://github.com/fsprojects/Paket/pull/1493, without "forceTouch" `paket install` works as before, does not update the `.csproj` files?

**Comment by orloffm** [comment]
:(

**Comment by forki** [comment]
Yes that's what @cdrnet did right?

**Comment by orloffm** [comment]
@forki, no.

https://github.com/fsprojects/Paket/releases/tag/2.50.9 (before https://github.com/fsprojects/Paket/issues/1471 / https://github.com/fsprojects/Paket/pull/1485) did not update `.csproj` files on clean `install` if they were not changed. So in abscence of `packages` and `paket.lock` it was possible to restore all packages by doing `paket install`.

https://github.com/fsprojects/Paket/releases/tag/2.50.10 (with https://github.com/fsprojects/Paket/issues/1471 / https://github.com/fsprojects/Paket/pull/1485) always updates project files. This causes issues when working with Perforce because all files are read-only by default.

The latest https://github.com/fsprojects/Paket/releases/tag/2.54.0 (with https://github.com/fsprojects/Paket/pull/1493) claims "with forceTouch to only modify the last write time without content if unchanged". But it doesn't matter, it fails on read-only files anyway.

I suggest to make it not change anything in the `.csproj` file if there are no changes and `forceTouch` is not specified. The way it was before https://github.com/fsprojects/Paket/issues/1471 / https://github.com/fsprojects/Paket/pull/1485.

**Comment by forki** [comment]
> I suggest to make it not change anything in the .csproj file if there are no changes and forceTouch is not specified

yes that's the goal

**Comment by cdrnet** [comment]
Currently on restore, "forceTouch" is disabled by default and can be enabled with `--touch-affected-refs`. For install it is always enabled. Maybe we could add an argument to optionally disable it on install (but keep it enabled by default)?

**Comment by forki** [comment]
tbh I think it should not touch if nothing changes.

**Comment by cdrnet** [comment]
So what about doing it the same way as for restore, i.e. disabling forceTouch by default on install, add etc but enable it optionally with `--touch-affected-refs`?

**Comment by forki** [comment]
yes that's what I meant --touch-affected-refs should work for paket and install. Default should be: don't touch if you don't need

**Comment by cdrnet** [comment]
That would work for me. The change should be straight forward, I can provide a PR.

**Comment by forki** [comment]
thanks that would awesome!

2016-03-22 16:02 GMT+01:00 Christoph Ruegg <notifications@github.com>:

**Comment by orloffm** [comment]
@cdrnet Christoph, I don't want to be bragging, but is there any chance this can be implemented?

**Comment by cdrnet** [comment]
@orloffm Ah right; I've scheduled some time later today to put the PR together

**Comment by cdrnet** [comment]
@orloffm does v2.58.2 resolve your issues?

**Comment by orloffm** [comment]
@cdrnet Yes. Amazing, thank you very much!
