### ISSUE TITLE
When adding framework specification to paket.dependencies .props include is moved to the bottom of csproj file

### ISSUE THREAD

**Issue by theggelund** [fsprojects/Paket#1487]
I have a nuget package that includes both a .props and a .targets. Then I wantet to specify which frameworks should be included when installting packages.

Added framework specification

```
framework: net40, net45, net46

source nuget_repo

nuget MultiTarget
nuget Dapper
nuget NUnit
```

After this the .props include statement was moved to the bottom just before .targets import

![image](https://cloud.githubusercontent.com/assets/648714/13277164/0e4300fc-dac7-11e5-90e5-725a8d9ff2db.png)

![image](https://cloud.githubusercontent.com/assets/648714/13277174/201681f0-dac7-11e5-8456-cdb8d10dd61f.png)

Reproduced in repo [paket_bug](https://github.com/theggelund/paket_bug/tree/master/framework_bug) with latest commit

Just run reproduce.bat

Reproduced on 
![image](https://cloud.githubusercontent.com/assets/648714/13277309/3fbfac4c-dac8-11e5-87f5-427de7a76787.png)

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/issues/1233 shows that it should not go to the top since it contains a property that is defined later.

**Comment by forki** [comment]
I'm reverting this for now since the fix was obviously incorrect. But what would be a correct fix?

**Comment by inosik** [comment]
The problem is that Paket generates a `__paket__xyz_props` property for `.props` (and `.targets`) that aren't framework specific, when there is a framework restriction. So (I think) we should handle this special case when we generate the `<Choose />`-blocks for the contents of the package.

**Comment by forki** [comment]
the question is: is @theggelund's csproj file broken or is it just "different" after adding the framework specification.

**Comment by inosik** [comment]
It's not broken, it's different to what NuGet would generate.

**Comment by forki** [comment]
But the issue got opened here. So I assumed the generated xml was not working

**Comment by theggelund** [comment]
after adding the framework specification the .props got moved to the bottom of csproj. It's not framework specific or anything. Is it being processed as framework specific and with no specification? (how would you specify this if that's the case?) It just got moved and I think that's the bug.
