### ISSUE TITLE
Automatically convert special chars to be xml-compatible

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/Paket#1488]
This is only an idea. I've seen that special characters (like: <, >, &) included in release notes are converted to XML-safe versions (&lt; &gt; &amp;). I doubt it's an intent of person writing these. This also is not a clear to conclude from relation between RELEASE_NOTES markdown format and nuget output, which seems to be XML-compatible.

I think, that we should convert xml-unsafe chars inside markdown, so they look the same after publishing nuget package as they looked inside release notes.

**Comment by forki** [comment]
not really sure I understand this issue

**Comment by Horusiath** [comment]
Using the example. Given `RELEASE_NOTES.md` like:

> ### New in 0.3.0 (Released 2016/02/25)
* Ask operator `<?` now returns async of `AskResult<'msg>`

After publishing nuget package, what I received is:

> Ask operator `&lt;?` now returns async of `AskResult&lt;'msg&gt;`

I think that automatic conversion of `<` &rArr; `&lt;` based on input in markdown format is not something, that most people would expect.

**Comment by forki** [comment]
Isn't this a FAKE issue?

**Comment by Horusiath** [comment]
Thanks. I've created issue in the Fake repo: https://github.com/fsharp/FAKE/issues/1162 . Closing this one.
