### ISSUE TITLE
Paket will download all dependencies of a nuget package even though framework has been specified

### ISSUE THREAD

**Issue by theggelund** [fsprojects/Paket#1494]
I have specified a framework limitation in my paket.dependencies file

```
framework: net461
source nuget_repo
nuget simpleinjector
```

When I add a dependency with framework specific dependencies [SimpleInjector] other than my framework, paket will download all dependencies for all frameworks

![image](https://cloud.githubusercontent.com/assets/648714/13420376/fbbfb0d8-df85-11e5-84d2-7da6a9ba12f2.png)

This is from simpleinjector nuspec file
![image](https://cloud.githubusercontent.com/assets/648714/13420499/ff78df3c-df86-11e5-8b00-2e8aeccf3e80.png)

Issue is reproduced here -> [download_issue](https://github.com/theggelund/paket_bug/tree/master/download_issue) Run reproduce.bat

**Comment by forki** [comment]
you nuspec file file looks like that:

    <dependencies>
      <group targetFramework=".NETFramework4.0" />
      <group targetFramework="WindowsPhone8.0" />
      <group targetFramework="Windows8.0" />
      <group targetFramework="Unsupported0.0">
        <dependency id="System.Collections" version="4.0.10" />
        <dependency id="System.Collections.Concurrent" version="4.0.10" />
        <dependency id="System.Diagnostics.Debug" version="4.0.10" />
        <dependency id="System.Globalization" version="4.0.10" />
        <dependency id="System.IO" version="4.0.10" />
        <dependency id="System.Linq" version="4.0.0" />
        <dependency id="System.Linq.Expressions" version="4.0.10" />
        <dependency id="System.Reflection" version="4.0.10" />
        <dependency id="System.Reflection.Extensions" version="4.0.0" />
        <dependency id="System.Reflection.TypeExtensions" version="4.0.0" />
        <dependency id="System.Runtime" version="4.0.20" />
        <dependency id="System.Runtime.Extensions" version="4.0.10" />
        <dependency id="System.Threading" version="4.0.10" />
        <dependency id="System.Threading.Tasks" version="4.0.10" />
      </group>
      <group targetFramework="MonoTouch0.0" />
      <group targetFramework="MonoAndroid0.0" />
    </dependencies>

where is the "unsupported" coming from?
