### ISSUE TITLE
2.51: paket install is awfully slow

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#1495]
`2 minutes, 55 seconds - ready.`

It was in the following state all that time:

![image](https://cloud.githubusercontent.com/assets/873919/13421357/ffbf3500-df9e-11e5-990e-93f904524410.png)

**Comment by forki** [comment]
@vasily-kirichenko any details that might help us to analyze this?

**Comment by vasily-kirichenko** [comment]
2.50 was 16 seconds.

**Comment by forki** [comment]
So 2.15.16 is still fast? 
/cc @cdrnet

**Comment by cdrnet** [comment]
The only difference between 2.50.16 and 2.51 seems to be my commit b528ca43ec75d. This is not supposed to touch the install process. I assume you are not calling `restore --touch-affected-refs`?

**Comment by forki** [comment]
I assume the slowness is introduced earlier.

**Comment by vasily-kirichenko** [comment]
2.50.15 is OK (16 seconds)
2.50.16 is NOT (3 minutes)

**Comment by forki** [comment]
@vasily-kirichenko thanks that's what I thought. 
I already pushed 2.51.1 - does it help?

**Comment by vasily-kirichenko** [comment]
Yes, 2.51.1 is 16 seconds again :) Thanks!
