### ISSUE TITLE
Cannot consume package from VSTS private Nuget feeds

### ISSUE THREAD

**Issue by blumu** [fsprojects/Paket#1496]
Paket fails to get nuget packages from private feeds created in [Visual Studio Team Service Package Management](https://www.visualstudio.com/en-us/get-started/package/overview)

    Error in paket.dependencies line 1
      couldnt load resources from https://<MyVstsProject>.visualstudio.com/DefaultCollection/_packaging/<MyPrivateFeed>/nuget/v3/index.json

It reproes using both v2 and v3 versions of the nuget feed.

**Comment by forki** [comment]
Can you mail me a dependencies file with credentials that reproduces this?
Sforkmann at gmail

**Comment by talbottmike** [comment]
@blumu Don't know if this'll help. But I'm using a VSTS private feed and am able to get packages by including credentials like this
`Paket.Dependencies.Install """
    source https://mysubdomain.pkgs.visualstudio.com/DefaultCollection/_packaging/MyFeedName/nuget/v2 username: "myusername" password: "mypassword"
    nuget MyPrivatePackage
""";;`

**Comment by blumu** [comment]
@forki I can't share the credentials to this project/feed unfortunately. The source is configured as follows in the paket dependency file:

    source https://MYPROJECT.pkgs.visualstudio.com/DefaultCollection/_packaging/MYFEED/nuget/v3/index.json username: "***" password: "***"

I tried with both v2 and v3 and got the same error after running the command:

   .\.paket\paket.exe convert-from-nuget

**Comment by blumu** [comment]
Correction: the actual error message I get when running `paket convert-from-nugget` is:

	Paket version 2.51.4.0
	Dependencies files saved to sources/paket.dependencies
	Resolving packages for group Main:
	 - MyPackage is pinned to 2015.11.26.1
	Paket failed with:
			Couldn't get package details for package MyPackage 2015.11.26.1 on any of ["https://www.nuget.org/api/v2";
	 "https://MyProject.pkgs.visualstudio.com/DefaultCollection/_packaging/MyVstsFeed/nuget/v3/index.json"].

**Comment by forki** [comment]
Ok this is a really weird error. It finds the package versions, but not the
concrete package. Will be nearly impossible for me to debug without access

**Comment by forki** [comment]
pretty sure it depends on the url in https://MyProject.pkgs.visualstudio.com/DefaultCollection/_packaging/MyVstsFeed/nuget/v3/index.json

but I'd need access to solve that.

**Comment by blumu** [comment]
Is there any switch I could use when running paket.exe to collect additional diagnostics for you to debug?

**Comment by blumu** [comment]
@forki I can share with you the content of the index.json file if this helps. Let me know.

**Comment by forki** [comment]
no idnex.json doesn't really help.

I need access to a similar visualstudio.com server. Can you set up one for testing where this reproduces and give me access?

**Comment by forki** [comment]
I created an account and it looks like I can reproduce

**Comment by blumu** [comment]
Awesome. Looking forward to next release with the fix!

**Comment by forki** [comment]
it's already released

**Comment by isaacabraham** [comment]
lol

**Comment by blumu** [comment]
I confirm that the fix works for me. Thanks for implementing this quick workaround!

**Comment by stuartjdavies** [comment]
I have the same issue. Has this error been fixed? Is there a work around?
