### ISSUE TITLE
VS2015 does no more pick up Fixie unit tests after converting to paket

### ISSUE THREAD

**Issue by Martin-Bohring** [fsprojects/Paket#1501]
## Problem

When using paket, then the VS2015 test explorer does no more pick up the [fixie ](http://fixie.github.io/) test cases.
(And I have repeatedly cleaned the VS test runner cache directory).

Using the Fake Fixie support everything is OK on the local CLI build using paket.
The tests are being picked up and executed.
Before switching to paket everything runs smooth in VS2015 as well.

After switching to paket using:

> .paket/paket.exe convert-from-nuget)

the CLI build still execute the tests, but VS2015 does not see them anymore.
## Analysis

I have **not gotten to the root** of the problem yet, but I have some **observations**:
- Fixie has the test framework itself and the test runner in the same package
- Even after opening and closing the paket based solution (without the test being discovered), the previous version nuget based version still works correcly (with the test being discovered by VS2015)
- It could be related to the different directory structure used by paket
## How to reproduce

Therefore it can't just be a testrunner cache problem of VS2015.

I have created a repository at [Fixie problem](https://github.com/Martin-Bohring/AV.Core) that can be used to repro the problem.

The head commit is using paket (tests are not discovered in VS2015), the one before is using nuget (tests are discovered in VS2015)

**Comment by inosik** [comment]
VS is weird when it comes to test runners, that's why we have [the `version_in_path` feature](http://fsprojects.github.io/Paket/nuget-dependencies.html#Putting-the-version-no-into-the-path). VS needs the version number in the path of the unpacked package to pick up the runners assemblies, since VS 2015 it also needs a `packages.config` file.

**Comment by forki** [comment]
@Martin-Bohring did you try the version-in-path flag?

**Comment by Martin-Bohring** [comment]
**@forki**
Yes that solved the problem, thanks a lot. I glanced over the documentation before, but that detail escaped my attention. And yes VS is weird here. I have choosen paket **exactly **to get rid of that versioned hint path problem,

But now I have some of that back. I fully understand that you can do nothing about it. But MS should. I guess I now have to check those packet.config files in as well.

But the documentation could be more explicit why people might **"want"** versined hint path.

**Comment by forki** [comment]
there is a bit about that in this FAQ: http://fsprojects.github.io/Paket/faq.html#NuGet-puts-the-package-version-into-the-path-Is-Paket-doing-the-same

I'd love to get a PR with more clarification. please try to write a bit where you think it would have helped you.

**Comment by Martin-Bohring** [comment]
OK, I will try to ramp up my word smithing capabilities over the weekend

**Comment by enricosada** [comment]
> Yes that solved the problem, thanks a lot

Closing
