### ISSUE TITLE
[V3] Git dependency fails to install/restore

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#1502]
I have this weird issue with a git dependency. I appeared out of nowhere and I managed to get rid of it somehow once.

Whenever I try to restore or install, where paket.dependencies has a git dependency I get this

```
Paket failed with:
        Checkout to E:\Piskorz\Projekty\Wikibus\Argolis\paket-files\gist.github.com\5d9c6983004c1c9ec91f failed.
Message: Could not run "git clone file:///e:\Piskorz\.paket\git\db\5d9c6983004c1c9ec91f".
Error:
fatal: destination path '\Piskorz\.paket\git\db\5d9c6983004c1c9ec91f' already exists and is not an empty directory.
```

I tried deleting both directories, removing from paket.lock as if I installed for the first time and this just won't go away. Interestingly, the repository is actually successfully downloaded into paket-files, but paket doesn't continue with other packages

**Comment by forki** [comment]
do you have a repro sample for me?

**Comment by tpluscode** [comment]
Not really. I've been struggling with this myself. On my work computer works fine every time

 March 9 2016 10:01 AM, "Steffen Forkmann"  wrote:  

	�  
	do you have a repro sample for me? 

	—
 Reply to this email directly or view it on GitHub (https://github.com/fsprojects/Paket/issues/1502#issuecomment-194191637).  �     

	�

**Comment by tpluscode** [comment]
Please close this. I've not seen this in months :)
