### ISSUE TITLE
Paket pack file globbing doesn't add files that don't have an extension.

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#1506]
I was making a nuget package for an executable that we'd like to use at work, which comes with both a *Nix shell wrapper (blah) and a Windows batch runner (blah.foo).  I first attempted to use a Paket file-type template to package this tool, but discovered that when I did the *nix runner (blah) was not included in the package.

I then made a nuspec to do the same thing and found that nuget's packaging globbing did respect this type of file.  Is there a bug in our globbing?

I've attached a simple repro scenario with the following files:
```
d-----         3/9/2016  10:20 AM                .paket
d-----         3/9/2016  10:20 AM                nupkg
-a----         3/9/2016  10:17 AM              0 blah
-a----         3/9/2016  10:17 AM              0 blah.foo
-a----         3/9/2016  10:18 AM            456 Foo.nuspec
-a----         3/9/2016  10:21 AM          31021 Foo.zip
-a----         3/9/2016  10:17 AM             37 paket.dependencies
-a----         3/9/2016  10:17 AM              2 paket.lock
-a----         3/9/2016  10:19 AM            155 paket.template
```

Notably, the file globs for paket are:
```
files
  * ==> tools/
  **/* ==> tools/
  !nupkg/*
  !.paket/*
  flyway* ==> tools/
```

and the globs for the nuspec are:
```
<files>
    <file src="**/*.*" target="tools" exclude=".paket/*;nupkg/*" />
    <file src="*" target="tools" exclude=".paket/*;nupkg/*" />
  </files>
```

And the packages in each case are identical with the exception of `blah` missing in the paket-created package.

To repro, you should just be able to `.paket\paket init; .paket\paket pack output nupkg` to get the paket case, and `nuget pack Foo.nuspec -outputdir nupkg` to get the nuget case.

[Foo.zip](https://github.com/fsprojects/Paket/files/165560/Foo.zip)

**Comment by forki** [comment]
I tried to reproduce in 1badc74 - but everything seems normal and blah get's packed.
Can you please try to break that test?!

**Comment by baronfel** [comment]
ah! you're right!  I was using the nuget package explorer gui to inspect the package that was created, which shows 
![image](https://cloud.githubusercontent.com/assets/573979/13645073/bfab191a-e5ee-11e5-9060-cc6a43b97023.png)

but when I unpack the nupkg, it's actually there. So we can close this, you're all good :)
