### ISSUE TITLE
Allow to restore dll from remote dependencies file

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1507]
From https://gist.github.com/forki/be1fe52828dc4a9f3729#file-gistfile1-txt-L6

> Let's try a concrete example. privateeye.fsx has a dependency on privateeye.bridge.dll. What I would like to do is in my repository put up a paket.dependencies that specifies when you want privateeye.fsx /bin/privateeye.bridge.dll should also be downloaded.

The following is intended to work:

* https://github.com/PrivateEye/PrivateEye will contain
    * privateeye.fsx
    * /bin/privateeye.bridge.dll
    * paket.dependencies (with reference to /bin/privateeye.bridge.dll)

User repo has a paket.depndencies file like this:

    source https://nuget.org/api/v2
    nuget bla
    github PrivateEye/PrivateEye privateeye.fsx

Running `paket restore` should download privateeye.fsx and /bin/privateeye.bridge.dll

/cc @gregoryyoung

**Comment by gregoryyoung** [comment]
Yep this would be cool as I don't want to add a nugget pkg for one
dependency

**Comment by forki** [comment]
Ok I implemented support for this.

* I created a privateeye fork with the necessary files: https://github.com/forki/PrivateEye
    * notice how the remote dependencies file contains another github reference:
        https://github.com/forki/PrivateEye/blob/master/paket.dependencies
* I created an integration test which refences `github forki/PrivateEye privateeye.fsx`

with 2.52 this works
