### ISSUE TITLE
support for credential providers

### ISSUE THREAD

**Issue by blumu** [fsprojects/Paket#1509]
Credential providers a la [Nuget 3](http://docs.nuget.org/Consume/Credential-Providers) allow for seemless authentication with private package feeds while improving security (no need to store password/token on disk). It would be great to add support for this in Paket.

**Comment by kflu** [comment]
I also want to know without this feature currently, what's the recommended way of using private nuget feeds that require authentication with paket?

**Comment by forki** [comment]
http://fsprojects.github.io/Paket/paket-config.html#Adding-credentials

**Comment by gursharan001** [comment]
Checking to see if this is still up-for-grabs?

**Comment by forki** [comment]
Sure
