### ISSUE TITLE
Issue when d/l packages

### ISSUE THREAD

**Issue by NSmeef** [fsprojects/Paket#1510]
No version specified. Downloading latest stable.
    Paket.exe 2.52.2.0 is up to date.
    Paket version 2.52.2.0
    Downloading FSharp.Compiler.Service 1.4.0.6
    Downloading CsQuery 1.3.4
    Downloading FSharp.Data 2.2.5
    Downloading FSharp.Core 4.0.0.1
    Downloading FSharp.Formatting 2.12.0
    Downloading FSharp.RDF 1.1.97
    Downloading FAKE 4.9.3
    Downloading DotLiquid 1.8.0
    Downloading FSharpVSPowerTools.Core 2.1.0
    Downloading Fuchu 1.0.3
    Downloading Microsoft.Bcl 1.1.10
    Downloading Microsoft.Bcl.Build 1.0.21
    Downloading Microsoft.Net.Http 2.2.29
    Downloading Octokit 0.18.0
    Downloading SourceLink.Fake 1.1.0
    Downloading Suave 1.1.1
    Downloading Suave.DotLiquid 1.1.1
    Downloading Suave.Testing 1.1.1
    Downloading Unquote 3.1.0
    Downloading Zlib.Portable 1.11.0
    Something went wrong while downloading FSharp.Core 4.0.0.1
    Message: Could not download FSharp.Core 4.0.0.1 from https://www.nuget.org/api/v2/package/FSharp.Core/4.0.0.1.
        Error: SendFailure (Error writing headers)
      ==> Trying again
    Downloading FSharp.Core 4.0.0.1
    Something went wrong while downloading Unquote 3.1.0
    Message: Could not download Unquote 3.1.0 from https://www.nuget.org/api/v2/package/Unquote/3.1.0.
        Error: SendFailure (Error writing headers)
      ==> Trying again
    Downloading Unquote 3.1.0

It freezes here, can supply paket.dependencies. Not sure if its an issue with this release in particular.

Running OSX

    Mono JIT compiler version 4.2.3 (explicit/832de4b Thu Mar  3 19:24:57 EST 2016)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
      TLS:           normal
      SIGSEGV:       altstack
      Notification:  kqueue
      Architecture:  x86
      Disabled:      none
      Misc:          softdebug
      LLVM:          yes(3.6.0svn-mono-(detached/a173357)
      GC:            sgen

**Comment by forki** [comment]
yes please send the deps file. sforkmann @ gmail

**Comment by forki** [comment]
mhm works from here. Integration test at 7db4bf9

Can you try "paket clear-cache" and/or "paket update -f"?

**Comment by forki** [comment]
7db4bf9 is also green on travis and appvevor

**Comment by NSmeef** [comment]
I did a `clear-cache`, `paket update -f` done the trick. Thanks.

**Comment by luolong** [comment]
I still get an error:

**Comment by forki** [comment]
Are you using https?

**Comment by blair55** [comment]
I believe we have the same issue building inside a container on CircleCI. Happens about 50% of the time. We are using `source https://www.nuget.org/api/v2` in paket.dependencies.

**Comment by blair55** [comment]
Feedback received from CircleCI was that nuget's CDN was struggling so please ignore comment.
> I clicked though to the link to their CDN and it looks like they may be having issues http://status.verizondigitalmedia.com/#network-status
