### ISSUE TITLE
Paket should not add <Paket> element in csporj file to cs files that are added via nuggets 

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1513]
Following paket.dependencieswill 
```
source https://www.nuget.org/api/v2/
nuget Microsoft.Orleans.Templates.Interfaces 
```
Adds empty orleans.codegen.cs file to csproj like this
```
    <Compile Include="Properties\orleans.codegen.cs">
      <Paket>True</Paket>
    </Compile>
```
This unexpected element hides file from Orleans code generator, and no code is created. The failure is detected only during run time, right now we manually  remove this property.

**Comment by forki** [comment]
Can't you use the no-content option?

**Comment by tsibelman** [comment]
Then I will need to add this file manually ?

**Comment by forki** [comment]
Ok I don't really understand the problem. What is Orleans expecting?

**Comment by tsibelman** [comment]
It expecting to have this file in the csproject but it do not expect it to have <Paket>True</Paket> under it.

**Comment by tsibelman** [comment]
It should be just <Compile Include="Properties\orleans.codegen.cs"/>

**Comment by forki** [comment]
Tbh this sounds like a bug in that tool

**Comment by tsibelman** [comment]
I don't sure if it a bug, Paket is not a part of csproj XSD specification so varius tools that do XCD based validation could fail.

**Comment by isaacabraham** [comment]
@tsibelman What's the XSD spec say though - I wouldn't have thought that adding an extra element inside the Compile node would have caused an issue?

**Comment by tsibelman** [comment]
It defined inside Microsoft.Build.Commontypes.xsd as you can see Compile has number of possible predefined child elements and Paket is not one of them.

```xml
 <xs:element name="Compile" substitutionGroup="msb:Item">
        <xs:annotation>
            <xs:documentation><!-- _locID_text="Compile" _locComment="" -->Source files for compiler</xs:documentation>
        </xs:annotation>        
        <xs:complexType>           
            <xs:complexContent>
                <xs:extension base="msb:SimpleItemType">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">                       
                        <xs:choice>
                            <xs:element name="SubType"/>
                            <xs:element name="DependentUpon"/>
                            <xs:element name="AutoGen">
                                <xs:annotation>
                                    <xs:documentation><!-- _locID_text="Compile_AutoGen" _locComment="" -->Whether file was generated from another file (boolean)</xs:documentation>
                                </xs:annotation>
                            </xs:element>                                 
                            <xs:element name="DesignTime"/>
                            <xs:element name="Link">
                                <xs:annotation>
                                    <xs:documentation><!-- _locID_text="Compile_Link" _locComment="" -->Notional path within project to display if the file is physically located outside of the project file's cone (optional)</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="DesignTimeSharedInput"/>
                            <xs:element name="Visible">
                                <xs:annotation>
                                    <xs:documentation><!-- _locID_text="Compile_InProject" _locComment="" -->Display in user interface (optional, boolean)</xs:documentation>
                                </xs:annotation>
                            </xs:element>                                
                            <xs:element name="CopyToOutputDirectory"/>
                            <xs:element name="VBMyExtensionTemplateID"/>
                        </xs:choice>
                    </xs:sequence>
                    <!-- redefine Include just to give a specific description -->
                    <xs:attribute name="Include" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation><!-- _locID_text="Compile_Include" _locComment="" -->Semi-colon separated list of source files (wildcards are allowed)</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>                    
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
```

**Comment by isaacabraham** [comment]
Perhaps a ```Paket=true``` attribute rather than an element would work?

**Comment by tsibelman** [comment]
I think it can work

**Comment by forki** [comment]
Nope. IIRC the attribute failed somewhere in normal csproj process.

**Comment by isaacabraham** [comment]
Can you confirm this - remove the element, replace with attribute, does it work? Not saying that that's the right solution - Orleans is open source, we should find out what it's doing.

**Comment by tsibelman** [comment]
Maybe this info should not be stored in csproj at all ? It already available in nugets.

**Comment by isaacabraham** [comment]
@tsibelman it's needed for upgrades between packages I think.

**Comment by forki** [comment]
It's needed for paket to understand where people opt out of default
behavior. If you remove the flag our set it to false then we don't touch it
anymore.

**Comment by tsibelman** [comment]
@forki  if people choose option content: once  it looks logical to not add this element at all, what do you think ?

**Comment by forki** [comment]
Mhm that could make sense. Yes

**Comment by tsibelman** [comment]
@forki great, this change would definatly help us

**Comment by forki** [comment]
done. please try again

**Comment by tsibelman** [comment]
I tried I see that it still adding it

I declared content: once in the start of paket.dependencies  and run this command paket convert-from-nuget -f

**Comment by forki** [comment]
yes. try to remove the reference from the csproj to make it believe that it starts from scratch.

**Comment by tsibelman** [comment]
Can it work on conversion from nugget ?

**Comment by forki** [comment]
did not try that

**Comment by tsibelman** [comment]
I wanted it to work during conversion by adding paket.template with content: once,  looks like it not working :(

**Comment by forki** [comment]
I made it a bit more agressive. The test shows it's not adding the paket tag any more. In fact it's removing it.

**Comment by tsibelman** [comment]
It works perfectly thank you

**Comment by tsibelman** [comment]
Looks like in latest version this behavior not working

**Comment by forki** [comment]
Are you sure? We didn't change that.

**Comment by tsibelman** [comment]
Let's me double check it

**Comment by tsibelman** [comment]
All good it was my mistake
