### ISSUE TITLE
Message: End of Central Directory record could not be found.

### ISSUE THREAD

**Issue by Mpdreamz** [fsprojects/Paket#1515]
Opening and closing this issue as an FYI for future googlers:

If you see:

```
Something went wrong while downloading FAKE 4.22.0
Message: Error during extraction of C:\Users\Mpdreamz\dev\editorconfig-visualstudio\packages\build\FAKE\FAKE.4.22.0.nupkg.
Message: End of Central Directory record could not be found.
```

Locate the nuget file in `%APPDATA%\Local\Nuget\Cache` and open the nupkg as a text file. Chances are a proxy rewrote the response. In my case it was SonicWall tagging FAKE as as a bitcoin miner:

https://gist.github.com/Mpdreamz/15653dc118c70248d144

However downloading the file manually from https://www.nuget.org/packages/FAKE/4.22.0 (the download link appears if you are logged in) and placing it manually in `%APPDATA%\Local\Nuget\Cache` unblocked me while on this strict network.

**Comment by forki** [comment]
/cc @ilkerde 

Can we do something about that?
