### ISSUE TITLE
Better messaging when paket.dependencies cannot be found

### ISSUE THREAD

**Issue by pdoh00** [fsprojects/Paket#1518]
I had a hard time figuring out why paket was not updating references for a project. It was because I had put paket.dependencies in the .paket directory.  I am proposing the following message update. The italicized is new.

"Could not find 'paket.dependencies'. To use Paket with this solution, please run 'paket init' first.
_If you have already run 'packet.init' then ensure that 'paket.dependencies' is located in the source directory.
Like this:
MySolutionDir
  .paket
  MySolution.sln
  paket.dependencies_"

This change would be in PublicAPI.fs ```static member Locate``` to the ```failwithf``` call.  Let me know if you like the message and I can send the PR.

**Comment by forki** [comment]
Yes that sounds good. But please don't talk about solutions here. It should
be on top of the repo, but paket actually doesn't care about sln so that
might be misleading

**Comment by pdoh00** [comment]
I don't understand "on top of the repo".  Can you link where this discussion should move? Thanks.

**Comment by forki** [comment]
We usually assume that paket.dependencies is in the top level folder of
your git repository (which is usually where you find a sln)

**Comment by pdoh00** [comment]
I see that the sln doesn't really matter. Maybe it would be better to just show paket.dependencies at the same level as .paket.  

e.g.

MySourceDir
  .paket
  paket.dependencies
