### ISSUE TITLE
Pinned dependency causes conflict

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#1520]
Latest paket, I have a dependencies file which I have reduced to: -

```
source https://nuget.org/api/v2
nuget Microsoft.ApplicationInsights.WindowsServer = 1.2.3
```

This does not work, although (as far as I can see) it should.

```
Resolving packages for group Main:
 - Microsoft.ApplicationInsights.WindowsServer is pinned to 1.2.3
 - Microsoft.ApplicationInsights 1.2.3
 - Microsoft.ApplicationInsights.DependencyCollector 2.0.0
 - Microsoft.ApplicationInsights.PerfCounterCollector 2.0.0
 - Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 2.0.0
 - Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28
 - Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3
 - Microsoft.ApplicationInsights.DependencyCollector 1.2.3
Paket failed with:
        There was a version conflict during package resolution.
  Resolved packages:
   - Microsoft.ApplicationInsights 1.2.3
   - Microsoft.ApplicationInsights.DependencyCollector 1.2.3
   - Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3
   - Microsoft.ApplicationInsights.WindowsServer 1.2.3
   - Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 2.0.0
  Could not resolve package Microsoft.ApplicationInsights:
   - Microsoft.ApplicationInsights.DependencyCollector 2.0.0 requested: 2.0.0
   - Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3 requested: 1.2.3
   - Microsoft.ApplicationInsights.WindowsServer 1.2.3 requested: 1.2.3

  Please try to relax some conditions.
```
It seems to be pulling in version 2.0 dependencies for some reason...

**Comment by inosik** [comment]
According to nuget.org, [`Microsoft.ApplicationInsights.WindowsServer v1.2.3`](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer/1.2.3) requires **= 1.2.3** of `Microsoft.ApplicationInsights` and **>= 1.2.3** for it's other dependencies. That's why Paket tries to get **v2.0.0** of `Microsoft.ApplicationInsights.*`.

You could use [`strategy: min`](http://fsprojects.github.io/Paket/nuget-dependencies.html#Strategy-modifiers), to emulate NuGet's behavior of downloading the oldest compatible version. This should get **v1.2.3** of every package, which `Microsoft.ApplicationInsights.WindowsServer` depends on.

**Comment by forki** [comment]
I believe strategy:min vs max should not result in conflict vs. non-conflict since it only changes order. I'll take a deeper look

**Comment by forki** [comment]
I'm pretty sure this is a bug, but not sure where exactly yet

**Comment by forki** [comment]
@mrinaldi 

It has something to do with this optimization:

                            match !state with
                            | Resolution.Conflict(resolved,closed,stillOpen,lastPackageRequirement,getVersionF) 
                                when stillOpen |> Set.exists (fun r -> r = currentRequirement || r.Graph |> List.contains currentRequirement) |> not ->
                                forceBreak := true
                            | _ -> ()

If I comment this block out then it finds a resolution.

**Comment by forki** [comment]
I think https://github.com/fsprojects/Paket/pull/1521/commits/28d9b82b226cb03d56fa7b2c42466dadedb27727 solves it.

**Comment by forki** [comment]
please give it another try

**Comment by isaacabraham** [comment]
Yeah works now! Interestingly I still get up to 2.x for some of the transitive dependencies - is there a way to stop this aside from adding those manually into the .dependencies file?

**Comment by forki** [comment]
Yes now you can try to change the strategy to min.

**Comment by isaacabraham** [comment]
Hmmm. Yes that works as well although not *quite* what I'm thinking, which is more "don't go above 'major' version of transitive dependencies".

* A = 1.2.3
* A depends on B >= 1.2.3
* I don't want B to ever go >= 2.0

I guess this is more about the package author of A (not specifying deps version boundaries tightly enough) than paket though, right?

**Comment by forki** [comment]
yes that is something that can't be really expressed in nuget
