### ISSUE TITLE
Regression - paket install removing CopyToOutputDirectory property

### ISSUE THREAD

**Issue by fgauthier-boutin** [fsprojects/Paket#1522]
Hi,
I was using version 2.51.4.0 before updating to 2.52.9.0. From now on, when I do paket install, my csproj included items go from:

```
<ItemGroup>  
<Content Include="filepath">  
  <Paket>True</Paket>  
  <CopyToOutputDirectory>Always</CopyToOutputDirectory>  
</Content>  
...
</ItemGroup>
```

To:

```
<ItemGroup>  
<Content Include="filepath">
  <Paket>True</Paket>
</Content>  
...
</ItemGroup>
```

Effectively removing my "CopyToOutputDirectory" directive... and breaking my build.

**Comment by forki** [comment]
did you add that manualy?

**Comment by fgauthier-boutin** [comment]
In this situation, I installed a home-made nuget component where a couple of DLLs are defined as "content", not as "lib". Doing so, when paket installs it, it adds these xml tags to the csproj. Everything's fine so far.

But from that point, I indeed manually set the "Copy to Output Directory" property for these DLLs with the help of Visual Studio.

**Comment by forki** [comment]
mhm. then this is not really a regression. you were relying on a bug ;-)

Anyways let's make that work. We need something like http://fsprojects.github.io/Paket/references-files.html#copy_local-settings for content files right?

**Comment by fgauthier-boutin** [comment]
I think so because I don't only copy DLLs but other kind files that are definitely not .Net assemblies, but they are mandatory resources at runtime for my app. - i.e. I could not simply tag as "lib" in my nuget package.

BTW, thanks for your great responsiveness and support @forki.

**Comment by forki** [comment]
so this is implemented. see http://fsprojects.github.io/Paket/nuget-dependencies.html#CopyToOutputDirectory-settings

please let me know if this works for you

**Comment by fgauthier-boutin** [comment]
Just got 2.54.0, when I set something like,
`nuget jQuery CopyToOutputDirectory: always`

I get something like,
```
Paket version 2.54.0.0
Paket failed with:
        Error in paket.dependencies line 23
  Unknown package settings copytooutputdirectory: always
```

To work, I must use the property named 'copy_content_to_output_dir' instead of 'CopyToOutputDirectory'. 

But doing so everything works as expected.
![image](https://cloud.githubusercontent.com/assets/10144485/13922999/2468c6da-ef55-11e5-9ff5-399c2446a362.png)

**Comment by forki** [comment]
lol. I would appreciate a PR to the docs. ;-)

**Comment by tsibelman** [comment]
@forki  Is copy_content_to_output_dir works if specified in line of  specific dependency ?

**Comment by forki** [comment]
it should.

**Comment by fgauthier-boutin** [comment]
It works.

**Comment by tsibelman** [comment]
Thank you, documentation is scarce on this

**Comment by tsibelman** [comment]
Another question, maybe this feature should not copy items that are of type Compile ?

**Comment by forki** [comment]
please help to improve it.

2016-04-04 15:55 GMT+02:00 tsibelman <notifications@github.com>:
