### ISSUE TITLE
Cannot setup mixed framework correctly 

### ISSUE THREAD

**Issue by acmore** [fsprojects/Paket#1523]
Hi,

I am using Paket version 2.52.8.0 to maintain the packages for a solution with mixed framework(.net & native) projects. Paket doesn't setup the project file well for native projects.

Here is the paket.dependencies:

```
framework: native

source https://www.nuget.org/api/v2
nuget boost_filesystem-vc140
nuget boost_system-vc140
```

and paket.references
```
boost_filesystem-vc140 framework: native
boost_system-vc140 framework: native
```

It works perfect for this setting. The dependent project is added to the project file correctly. The project file is like this:
```xml
 <Import Project="..\packages\boost\build\$(__paket__boost_targets).targets" Condition="Exists('..\packages\boost\build\$(__paket__boost_targets).targets')" Label="Paket" />
  <Import Project="..\packages\boost_filesystem-vc140\build\$(__paket__boost_filesystem-vc140_targets).targets" Condition="Exists('..\packages\boost_filesystem-vc140\build\$(__paket__boost_filesystem-vc140_targets).targets')" Label="Paket" />
  <Import Project="..\packages\boost_system-vc140\build\$(__paket__boost_system-vc140_targets).targets" Condition="Exists('..\packages\boost_system-vc140\build\$(__paket__boost_system-vc140_targets).targets')" Label="Paket" />
```

However, when I changed framework to **net452** in paket.dependencies, it did not add the dependency `boost` to the project file.
```xml
  <Import Project="..\packages\boost_filesystem-vc140\build\$(__paket__boost_filesystem-vc140_targets).targets" Condition="Exists('..\packages\boost_filesystem-vc140\build\$(__paket__boost_filesystem-vc140_targets).targets')" Label="Paket" />
  <Import Project="..\packages\boost_system-vc140\build\$(__paket__boost_system-vc140_targets).targets" Condition="Exists('..\packages\boost_system-vc140\build\$(__paket__boost_system-vc140_targets).targets')" Label="Paket" />
```

So the build is broken because cannot find the boost package. And most of the packages used in my solution is .net packages, and due to some reason, we don't want to separate the paket.dependencies. Any idea about this issue?

Here is the project for testing this issue.
[TestPaket.zip](https://github.com/fsprojects/Paket/files/177080/TestPaket.zip)

**Comment by forki** [comment]
First your deps file should lookmlike this:

    framework: native, net452

    source https://www.nuget.org/api/v2
    nuget boost_filesystem-vc140
    nuget boost_system-vc140

you need to specify both native and net452 since otherwise the resolver would not check all dependencies.

That said there was still a bug and it's fixed in latest.
So please change your dependencies file, upgrade paket and try again.

**Comment by acmore** [comment]
Thanks for the fix!

I found another problem after add **native** to framework.

For some .net package, before adding native, the choose item is like this:
```xml
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.2'">
      <ItemGroup>
        <Reference Include="nunit.framework">
          <HintPath>..\packages\NUnit\lib\nunit.framework.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

After I added **native** to framework, it looks like this:
```xml
  <Choose>
    <When Condition="($(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.2') Or (true) Or ('$(Configuration)|$(Platform)'=='Debug|Win32') Or ('$(Configuration)|$(Platform)'=='Debug|arm') Or ('$(Configuration)|$(Platform)'=='Debug|x64') Or ('$(Configuration)|$(Platform)'=='Release|Win32') Or ('$(Configuration)|$(Platform)'=='Release|x64') Or ('$(Configuration)|$(Platform)'=='Release|arm')">
      <ItemGroup>
        <Reference Include="nunit.framework">
          <HintPath>..\packages\NUnit\lib\nunit.framework.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

Seems that the condition is always true since there is `(true)` inside the condition.

Could you help look at this issue again?

Here is the project for testing.
[TestPaket.zip](https://github.com/fsprojects/Paket/files/178507/TestPaket.zip)

**Comment by forki** [comment]
yes that `true` thingy is a bug.

But one question: do you expect nunit.framework.dll to be installed for native?

**Comment by forki** [comment]
ok that true thingy is gone.

**Comment by acmore** [comment]
@forki We dont expect nunit.framework.dll to be installed for native. The previous example is for a c# project.

**Comment by acmore** [comment]
@forki thanks for your fix!

**Comment by forki** [comment]
Is it already enough to make it work for you?

**Comment by acmore** [comment]
I think so. So it will work for both native and .net packages?

**Comment by forki** [comment]
Just let me know if you find other issues. I want to make it work with
native.

**Comment by acmore** [comment]
@forki I am not sure why it will add ` Or ('$(Configuration)|$(Platform)'=='Debug|Win32') Or ('$(Configuration)|$(Platform)'=='Debug|arm') Or ('$(Configuration)|$(Platform)'=='Debug|x64') Or ('$(Configuration)|$(Platform)'=='Release|Win32') Or ('$(Configuration)|$(Platform)'=='Release|x64') Or ('$(Configuration)|$(Platform)'=='Release|arm')"` to a .net framework?
```xml
  <Choose>
    <When Condition="($(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.2') Or ('$(Configuration)|$(Platform)'=='Debug|Win32') Or ('$(Configuration)|$(Platform)'=='Debug|arm') Or ('$(Configuration)|$(Platform)'=='Debug|x64') Or ('$(Configuration)|$(Platform)'=='Release|Win32') Or ('$(Configuration)|$(Platform)'=='Release|x64') Or ('$(Configuration)|$(Platform)'=='Release|arm')">
      <ItemGroup>
        <Reference Include="nunit.framework">
          <HintPath>..\packages\NUnit\lib\nunit.framework.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

**Comment by forki** [comment]
Yeah that's not really correct. Needs some work...

**Comment by acmore** [comment]
Hmm, are you going to fix it?

**Comment by forki** [comment]
Sure, but is it currently breaking you?

**Comment by forki** [comment]
I already had a fix, but that made trouble elsewhere so I reverted that.
On Mar 18, 2016 18:02, sforkmann@gmail.com wrote:

Sure, but is it currently breaking you?
On Mar 18, 2016 18:00, "acmore" <notifications@github.com> wrote:

Hmm, are you going to fix it?

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/1523#issuecomment-198454507>

**Comment by acmore** [comment]
it's not breaking me though. We have a lot of projects, so we don't want to change a lot, lol

**Comment by forki** [comment]
Ah I now understand what you mean. It's the diff in existing projects
that's worrying you.

I think I will revisit this over the weekend...

**Comment by acmore** [comment]
Thanks a lot:)

**Comment by forki** [comment]
done. please give it a try

**Comment by acmore** [comment]
Hi @forki, seems that this version will remove the boost dependency again. The test project I attached works well, but not in our production projects. Could you help to take a look?

**Comment by forki** [comment]
mhm integration tests are still green.
can you spot a difference?

**Comment by acmore** [comment]
Thanks @forki , it should be fine now.

**Comment by forki** [comment]
?
