### ISSUE TITLE
Packaged NuSpec description has trailing quotation

### ISSUE THREAD

**Issue by ianbattersby** [fsprojects/Paket#1525]
**Version: 2.52.12.0**

Just noticed when unpacking and verifying a packaged NuPkg that the description element has a trailing quotation mark even though the corresponding `AssemblyInfo.cs` does not.

`<description>[MyAssemblyInfoDescriptionAttribute]"</description>`

`[assembly: AssemblyDescriptionAttribute("[MyAssemblyInfoDescriptionAttribute]")]`

**Comment by forki** [comment]
huh? where is this coming from?

**Comment by forki** [comment]
?

**Comment by ianbattersby** [comment]
Well this is frightfully embarrassing. I've just gone back to check if it's still happening, and did another quick check of the template file to make sure it is indeed not in there, and it is. Which means (a) I'm an idiot for not checking all the template files and (b) unlucky the one I did check is the only one without it in.

A thousand apologies, I see me buying the beers in the future! :+1:
