### ISSUE TITLE
Cannot get package details Octokit

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#1526]
When runnnig paket update with the following dependency file:

```
source https://nuget.org/api/v2

group build
	source https://nuget.org/api/v2
	nuget FSharp.Formatting
	nuget Fake
	nuget SourceLink.Fake
	nuget Newtonsoft.Json
	github fsharp/FAKE modules/Octokit/Octokit.fsx

group project
	source https://nuget.org/api/v2
	nuget FSPowerPack.Community

group test
	source https://nuget.org/api/v2
	nuget Unquote
	nuget FsCheck
	nuget FsUnit
	nuget NUnit ~> 2
	nuget NUnit.Runners ~> 2
```
I run into the following error:

> Paket failed with:
>         Couldn't get package details for package Octokit 0.19.0 on https://nuget.org/api/v2.

**Comment by forki** [comment]
Sound like temporary nuget issue. Can you try to run "paket update -f"?

**Comment by forki** [comment]
I think I will increase the retry count anyways

**Comment by forki** [comment]
Ok 2.25.15 is automatically retrying with force flag if first trial doesn't succeed

**Comment by forki** [comment]
so please try "paket update" with 2.25.15. It should not need the -f flag

**Comment by halcwb** [comment]
I tried the latest paket version 2.52.16.0 and it now works, thanks!
