### ISSUE TITLE
transitive dependencies picks up conditional and copy_local attributes

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/Paket#1528]
I have those packages:

* package `Foo.Design`, depends on `Foo` and `Bar`
* package `Foo`, depends on `Bar`

in my paket.dependencies:

```
nuget Foo
nuget Foo.Design condition:DEBUG, copy_local:false
```

in projects referencing both `Foo.Design` and `Foo`, I'm still expecting `Bar` to be added without the conditionals and `copy_local = true`, but it seems paket is not behaving this way.

How can I make it behave the way I intend?

**Comment by forki** [comment]
Can you make that explicit with bar?

**Comment by smoothdeveloper** [comment]
One problem is that `Foo` has a sizeable dependency tree (my current case has 4 but next one might have more), do I need to explicitly add those to my `paket.dependencies` (all the 4 dependencies get affected)?

For now I'm just adding the reference manually rather than in `paket.references`, do you think what I described is expected behaviour or something we might want to change?

I'm using this to add references to the designer assembly, that I don't ship with the application.

I'm thinking it would make more sense to apply attributes only to the dependency it is specified, at least when there is a conflict with other ones (but better to be consistent), although it's true that it might be a breaking change if this current behaviour is being relied on.

**Comment by forki** [comment]
If I remember correctly this was introduced as feature request

**Comment by smoothdeveloper** [comment]
Worth checking if the request was for transitive dependencies in case of those being transitive to other dependencies as well.

I had a look at the titles of all issues containing transitive and only #602 seemed the closest on a short survey but comments don't seem related.

The current behaviour seems unnatural as it picks up arbitrarily the attributes from one of the package pulling the transitive dependencies. I'd consider for this use case adding a `apply_to_transitive_dependencies: true` attribute to explicitly state I want the same attributes on those even in case of conflict.

**Comment by forki** [comment]
Can you please build a repro case as zip or even as pull request here to the integration tests?

**Comment by smoothdeveloper** [comment]
@forki, I'm actually trying to add an integration tests but I'm seeing the correct behaviour actually.

Let's close the issue for now and I'll reopen it with a full case if I figure it out.

Thanks
