### ISSUE TITLE
Create infrastructure for system-tests

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#153]
Unfortunately our current unit tests can't simulate all the weird nuget responses. I would like to build a integration test suite which actually runs the whole paket process. We need infrastructure for this. 

Current idea:
  * create a new folder "integration-tests" 
  * create subfolders for every integration test
  * in testxxc subfolder create a "initial" subfolder and "expected" folder 
  * in "initial" add a "scenario.txt" file
     - first line contains command line call. 
     - other lines are comments 
  * running test
    -  copy initial folder to temp dir
    - run specified command from  scenario.txt 
    - compare temp folder with "expected" folder and report differences

Is this a good idea? Is there a tool that works on mono and .NET which works like this?

**Comment by forki** [comment]
Any news on this?

**Comment by jwood803** [comment]
Sorry for the delay, but I hope to send something this week or so for review.

**Comment by jwood803** [comment]
Was the `system-tests` folder moved or deleted? After fetching latest, I can't seem to find it anymore.

**Comment by theimowski** [comment]
I think @forki removed them so that they didn't pollute the codebase

**Comment by forki** [comment]
I deleted it. Since tests were too old. We need to create new ones.
