### ISSUE TITLE
Paket 2.53.0 does not add packages named MyLib.MyLib to project

### ISSUE THREAD

**Issue by jschroed** [fsprojects/Paket#1531]
I noticed an issue starting with Paket version 2.53.0. Paket is no longer adding one my libraries to my projects.

As far as I can tell, the only thing special about this package is that is has the same name before and after the period (e.g. MyLib.MyLib). Did something change in this version of Paket that could cause this?

The previous version 2.52.16 does not give me this issue. Also, version 2.53.0 works fine for all of my other packages.

I have the MyLib.MyLib package in my paket.references, paket.lock, and paket.dependencies. MyLib.MyLib is being downloaded into the packages directory. The only issue seems to be that it is no longer added to my csproj files.

**Comment by forki** [comment]
Can you please try to create a repro case?

**Comment by jschroed** [comment]
Sure, I can try. I'll see if I can find a package on nuget.org that has the same behavior.

**Comment by forki** [comment]
If not I will try to reproduce tomorrow.

**Comment by forki** [comment]
We also have integration tests that create new packages. We could copy and
tweak one of these.

**Comment by jschroed** [comment]
Okay, that might be best. I couldn't find any packages on nuget that have the same naming scheme. I can look into creating a custom package that has the same behavior but it would take some time.

I think it's an issue with the names but I could be way off. The only other guess I have is that it could an issue with the target framework.

**Comment by forki** [comment]
Ok let's start with the name (but I don't really think it's it). I'll try
to reproduce.

Just to make sure it's not the target framework. Can you mail me the
package? Of course I will keep it private.

**Comment by jschroed** [comment]
I probably can't email the package since it's work related. I can try to create a similar package, or at least strip out all of the proprietary code.

**Comment by forki** [comment]
You could unzip the package and replace all dlls with 0byte dlls with same
name and zip again. We could then even use it for repro if you allow

**Comment by jschroed** [comment]
I can build Paket locally. That might be easier than me trying to get a package to you.

I can diff the two versions of Paket to at least narrow it down. Do you have any debugging that I could add? The verbose option of Paket wasn't any different between the two versions.

**Comment by jschroed** [comment]
It seems that a change in the Utils.fs caused the issue.

**Comment by forki** [comment]
Ok. Then you are probably very near to a solution. Can you give a whole
path that is now parsed wrongly?

**Comment by jschroed** [comment]
Looks like the new code is getting "lib/net45" and the old code is just "net45".

**Comment by forki** [comment]
mhm a dll name ending in lib was already in the testcases. A package name ending in lib was not.
Should be fixed now. Sorry

**Comment by jschroed** [comment]
No problem. Just glad that we caught this sooner rather than later.

Thanks @forki! Paket 2.53.2 works for us.
