### ISSUE TITLE
References between projects in paket.references

### ISSUE THREAD

**Issue by ggrnd0** [fsprojects/Paket#1532]
Is it possible to add project references by paket.references ?
As posible feature is swap package reference by inculuded sources while debug.
This feature supoprted in new nuget3.

**Comment by forki** [comment]
This is not supported yet, but @k_cieslak and @cloudRoutine and others
requested that before. Currently I'm not completely sure if this is a good
idea (we would work against basic VS features).

**Comment by forki** [comment]
And AFAIK it's more a change of project system (and everything above) than
a new feature of nuget.

**Comment by ggrnd0** [comment]
Yes it is not about nuget.
But for paket it must easy feature.
It will good to manage this by paket. 
It is simpler then Pr -> AddReference -> PrReferences->(check some lines)

I hate csproj file, and prefer to do not touch this=)

**Comment by forki** [comment]
Maybe we can do that in v3, but I would need volunteers...

**Comment by isaacabraham** [comment]
Sounds like paket.dependencies starts to become like project.json ;-) *hides*

**Comment by forki** [comment]
In this case it's paket.references.

**Comment by isaacabraham** [comment]
Yes, true. I was thinking of another issue that I saw which was about putting paket.references embedded within the paket.dependencies file. Which I think has some legs in it.

**Comment by ggrnd0** [comment]
@isaacabraham, no, no, no, no =)
dependencies is perfect, do not make project.json with him =)

**Comment by ggrnd0** [comment]
> Yes, true. I was thinking of another issue that I saw which was about putting paket.references embedded within the paket.dependencies file. Which I think has some legs in it.

Can u give link?

**Comment by isaacabraham** [comment]
Can't find it - maybe I imagined it. But link to #1497 - this seems similar.

**Comment by ggrnd0** [comment]
@isaacabraham, 10x.

> project myproject path/to/myproject.csproj

it is interesting - manage project list by paket.dependencies?

but i about manage project-to-project references and swap nuget/[other] references by included project.

**Comment by isaacabraham** [comment]
I was more thinking within dependencies file having a section e.g.

```
project abc
   mydep
   myotherdep
```

rather than a paket.references for project abc with those elements in. I'll make a new issue if I can't find the original one.

**Comment by ggrnd0** [comment]
@isaacabraham, NO!
`references.paket` for project refecences 
`dependencies.paket` only store deps list with sources and versions

Is it original https://github.com/fsprojects/Paket/issues/590?

**Comment by isaacabraham** [comment]
@ggrnd0 no, that's not the original.

```paket.references``` is not for project references. It's for project *dependencies* (and not for transitive dependencies at that). All I am proposing is allowing us to specify that in the ```paket.dependencies``` if we want as opposed to having several files with them in.

Primarily this would make creating new projects in a solution and adding them to paket slightly easier.

**Comment by forki** [comment]
paket.dependencies is global. How would that help to specify inter-project dependencies?

**Comment by smoothdeveloper** [comment]
Duplicate with #1497
