### ISSUE TITLE
$(__paket__.... variables in csproj breaks website after convert-from-nuget, or paket update

### ISSUE THREAD

**Issue by mlidbom** [fsprojects/Paket#1536]
After running convert-from-nuget on a solution containing a web project I ended up with these two lines in the web csproj file: 

`<Import Project="..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform\build\$(__paket__Microsoft_CodeDom_Providers_DotNetCompilerPlatform_props).props" Condition="Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform\build\$(__paket__Microsoft_CodeDom_Providers_DotNetCompilerPlatform_props).props')" Label="Paket" />
  <Import Project="..\packages\Microsoft.Net.Compilers\build\$(__paket__Microsoft_Net_Compilers_props).props" Condition="Exists('..\packages\Microsoft.Net.Compilers\build\$(__paket__Microsoft_Net_Compilers_props).props')" Label="Paket" />`

Building "works" with this in place but the Imports are apparently not working, No "roslyn" folder is created in the bin folder, and trying to use the website gives the error: 
> Could not find a part of the path 'C:\Manpower\Manpower.Applications.Intake\Intake.UI.Web\bin\roslyn\csc.exe'.

Since this is a big powershell automated batch migration of many solutions with many web projects I added a bit of code that got this working again (Just replace the variables with the actual file names):

`$projectFileContent = $projectFileContent.Replace('$(__paket__Microsoft_CodeDom_Providers_DotNetCompilerPlatform_props).props','Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')
    $projectFileContent = $projectFileContent.Replace('$(__paket__Microsoft_Net_Compilers_props).props','Microsoft.Net.Compilers.props')`
I was hoping this was a bug in the migration code, and that I was done, but it seems not. 
Whenever I run paket update (Or, I'm guessing, any other paket command that changes csproj files) the lines that break the build are reintroduced. 

**This is a showstopper for us in our migration to paket :( . I would greatly appreciate getting this addressed since I really really want the advantages that paket will give us.**

**Comment by forki** [comment]
yeah convert-from-nuget uses the normal install process to add these imports. So this is at least consistently wrong ;-)

Will take a look later today

**Comment by mlidbom** [comment]
Great! Thanks for the quick response :)

**Comment by forki** [comment]
just tried to reproduce. Can you please send me a broken csproj and corresponding paket.references + paket.dependencies to sforkmann @ gmail ?

**Comment by inosik** [comment]
Seems that it's related to #1487, but in the latest version this should be actually working.

**Comment by forki** [comment]
yees it's related, but it seems we still generate something that doesn't work.

**Comment by inosik** [comment]
Wait a minute, `roslyn` folder? That thing gets created by the `install.ps1` script in the package. So the problem here is, that Paket doesn't execute PowerShell scripts. The `.props` file gets inserted in the right place, but it uses something which isn't there.

**Comment by forki** [comment]
argh. thanks for clarification. yes we don't execute ps1 scripts (same as newer nuget). Is there another way to create that thing?

**Comment by mlidbom** [comment]
One correction: The roslyn folder is created when you build. Not when you install the package.

I'll see if I can create a minimal repro.

**Comment by inosik** [comment]
Seems that [Microsoft.CodeDom.Providers.DotNetCompilerPlatform.BinFix](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.BinFix/) fixes it with a `.targets` file instead of a PowerShell script.

**Comment by mlidbom** [comment]
> Seems that it's related to #1487, but in the latest version this should be actually working.

Darn, my migration script caches paket.exe and it was not the latest version.
I just cleared the cache and the behavior changes.

I'm very sorry to have wasted your time with a bug report when using an old version :(


However, Now I get a build error instead:

> C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets(88,11): error MSB4064: The "Features" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.

I will investigate this a bit and create a new issue if it turns out to be a Paket problem. 
Again, apologies for wasting your time :(

**Comment by mlidbom** [comment]
It does seem to be a bug in paket causing the build failure. 
I added issue: #1537
