### ISSUE TITLE
Add an extension point to `paket pack` to specify dependancies by framework

### ISSUE THREAD

**Issue by enricosada** [fsprojects/Paket#1539]
to make it possibile to support dependencies by framework (like .NET Core) until #913 is ready

I think two command line arguments are enough, it's a temporary but can help a lot, and low regression (replacement/addition are done after nuspec is generated)

an example:
- `paket pack --defaultgroup net40` to put generated nuspec deps inside a group
- `paket pack --additionaldeps "path/to/file"` and `path/to/file` contains the other groups in nuspec format
  
  ```
   <group targetFramework="DNXCore5.0">
      <dependency id="Microsoft.FSharp.Core.netcore" version="[1.0.0-alpha-151221, )" />
      <dependency id="NETStandard.Library" version="[1.0.0-rc2-23811, )" />
    </group>
  ```

**Comment by forki** [comment]
mhm. can you come up with a syntax for paket.template instead?

**Comment by enricosada** [comment]
I dont know enough about resolution and backward compatibility to comment about paket.template syntax. 
I know that's an hack, i was trying to find something safe and easy to implement
But maybe it's better to wait template support, more clean, i'll close

**Comment by forki** [comment]
Let's keep it open for discussion. I will revisit soon

**Comment by enricosada** [comment]
Dunno, probably that's not the best way, or is not ok.

It's a bit selfish, but i just need something to add .NET Core framework to nuget packages created with `paket pack` atm is really an hack ( ref chessie https://github.com/fsprojects/Chessie/pull/43/commits/eef358e50b5c2f57ca3b93f3c391eb82a975f8b7 ) for dependencies ( unzip nuspec from nupkg, modify nuspec xml, zip back ).

Maybe some way to change the nuspec before the nupkg is created is ok too.

I can add the hack in FAKE as target, but not everyone who use paket use fake too, so it's a annoying

**Comment by cdrnet** [comment]
I have a need for this as well. Specifically I'll need to express something along the lines of in the template file:

    <dependencies>
        <group targetFramework=".NETFramework3.5">
            <dependency id="TaskParallelLibrary" version="1.0.2856" />
        </group>
        <group targetFramework=".NETFramework4.0" />
    </dependencies>

**Comment by enricosada** [comment]
Closing. `paket.template` support that
