### ISSUE TITLE
paket silently downgrades all non-pinned pre version packages when running update or add

### ISSUE THREAD

**Issue by mlidbom** [fsprojects/Paket#1542]
If you run any of the below commands in the attached folder SolrNet will be downgraded from the preversion installed:0.5.0-alpha2 to the latest stable version:0.4.0.4001

```
.\.paket\paket.exe update
.\.paket\paket.exe add nuget Newtonsoft.Json
```
I would expect the update command to have no effect at all.
I would expect the add command to add Newtonsoft.Json without changing the version of SolrNet

[PaketDowngradesPreVersions.zip](https://github.com/fsprojects/Paket/files/186070/PaketDowngradesPreVersions.zip)

**Comment by cdrnet** [comment]
The included paket.dependencies file does not permit prereleases, so it updates to the newest version compliant with the dependencies file.

You can allow prereleases e.g. by adding `prerelease` to the SolrNet line, see [Docs: PreReleases](http://fsprojects.github.io/Paket/nuget-dependencies.html#PreReleases)

**Comment by forki** [comment]
yes that's the reason. It detects that 0.5.0-alpha2 doesn't fit the requirements and fixes that.
But I wonder why it does that on "add"!? newtonsoft should not affect the graph. I need to revist that part and see why we do that over there.

**Comment by mlidbom** [comment]
Thank you for spending time on that RTM @cdrnet 
I can certainly see how that behavior makes sense for update in a command line use case. 
Apologies for not having RTM carefully enough.

As @forki observes the behavior seems, at least, debatable in the add case.
Should I edit the description to only include the add case as up for debate or should I just close this?

**Comment by forki** [comment]
I looked at the code. I think the resolver is working correct here. It tries to come up with something sound.
