### ISSUE TITLE
Inconsistent condition generation 

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#1552]
Almost each time when I call `paket.exe install` it change my `paket.lock` file from
> CommonServiceLocator (1.3) - framework: >= net40, monoandroid, portable-net45+wp80+wpa81+win+MonoAndroid10+xamarinios10, xamarinios, winv4.5, winv4.5.1, wpv8.1, wpv8.0, sl50

to
> CommonServiceLocator (1.3) - framework: >= net40, monoandroid, portable-net45+wp80+wpa81+win+MonoAndroid10+xamarinios10, xamarinios, winv4.5, wpv8.0, sl50

and vise versa.

What actually change most of my csproj files from
> When Condition="($(TargetFrameworkIdentifier) == 'WindowsPhoneApp') Or ($(TargetFrameworkIdentifier) == '.NETCore') Or ($(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1')) Or ($(TargetFrameworkIdentifier) == 'Silverlight' And $(TargetFrameworkVersion) == 'v5.0') Or ($(TargetFrameworkIdentifier) == 'WindowsPhone' And $(TargetFrameworkVersion) == 'v8.0') Or ($(TargetFrameworkIdentifier) == 'MonoAndroid') Or ($(TargetFrameworkIdentifier) == 'Xamarin.iOS') Or ($(TargetFrameworkProfile) == 'Profile5') Or ($(TargetFrameworkProfile) == 'Profile6') Or ($(TargetFrameworkProfile) == 'Profile7') Or ($(TargetFrameworkProfile) == 'Profile14') Or ($(TargetFrameworkProfile) == 'Profile19') Or ($(TargetFrameworkProfile) == 'Profile24') Or ($(TargetFrameworkProfile) == 'Profile31') Or ($(TargetFrameworkProfile) == 'Profile32') Or ($(TargetFrameworkProfile) == 'Profile37') Or ($(TargetFrameworkProfile) == 'Profile42') Or ($(TargetFrameworkProfile) == 'Profile44') Or ($(TargetFrameworkProfile) == 'Profile47') Or ($(TargetFrameworkProfile) == 'Profile49') Or ($(TargetFrameworkProfile) == 'Profile78') Or ($(TargetFrameworkProfile) == 'Profile84') Or ($(TargetFrameworkProfile) == 'Profile92') Or ($(TargetFrameworkProfile) == 'Profile102') Or ($(TargetFrameworkProfile) == 'Profile111') Or ($(TargetFrameworkProfile) == 'Profile136') Or ($(TargetFrameworkProfile) == 'Profile147') Or ($(TargetFrameworkProfile) == 'Profile151') Or ($(TargetFrameworkProfile) == 'Profile157') Or ($(TargetFrameworkProfile) == 'Profile158') Or ($(TargetFrameworkProfile) == 'Profile225') Or ($(TargetFrameworkProfile) == 'Profile240') Or ($(TargetFrameworkProfile) == 'Profile255') Or ($(TargetFrameworkProfile) == 'Profile259') Or ($(TargetFrameworkProfile) == 'Profile328') Or ($(TargetFrameworkProfile) == 'Profile336') Or ($(TargetFrameworkProfile) == 'Profile344')"

to
> When Condition="($(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1')) Or ($(TargetFrameworkIdentifier) == '.NETCore' And $(TargetFrameworkVersion) == 'v4.5') Or ($(TargetFrameworkIdentifier) == 'Silverlight' And $(TargetFrameworkVersion) == 'v5.0') Or ($(TargetFrameworkIdentifier) == 'WindowsPhone' And $(TargetFrameworkVersion) == 'v8.0') Or ($(TargetFrameworkIdentifier) == 'MonoAndroid') Or ($(TargetFrameworkIdentifier) == 'Xamarin.iOS') Or ($(TargetFrameworkProfile) == 'Profile5') Or ($(TargetFrameworkProfile) == 'Profile6') Or ($(TargetFrameworkProfile) == 'Profile7') Or ($(TargetFrameworkProfile) == 'Profile14') Or ($(TargetFrameworkProfile) == 'Profile19') Or ($(TargetFrameworkProfile) == 'Profile24') Or ($(TargetFrameworkProfile) == 'Profile31') Or ($(TargetFrameworkProfile) == 'Profile32') Or ($(TargetFrameworkProfile) == 'Profile37') Or ($(TargetFrameworkProfile) == 'Profile42') Or ($(TargetFrameworkProfile) == 'Profile44') Or ($(TargetFrameworkProfile) == 'Profile47') Or ($(TargetFrameworkProfile) == 'Profile49') Or ($(TargetFrameworkProfile) == 'Profile78') Or ($(TargetFrameworkProfile) == 'Profile84') Or ($(TargetFrameworkProfile) == 'Profile92') Or ($(TargetFrameworkProfile) == 'Profile102') Or ($(TargetFrameworkProfile) == 'Profile111') Or ($(TargetFrameworkProfile) == 'Profile136') Or ($(TargetFrameworkProfile) == 'Profile147') Or ($(TargetFrameworkProfile) == 'Profile151') Or ($(TargetFrameworkProfile) == 'Profile157') Or ($(TargetFrameworkProfile) == 'Profile158') Or ($(TargetFrameworkProfile) == 'Profile225') Or ($(TargetFrameworkProfile) == 'Profile240') Or ($(TargetFrameworkProfile) == 'Profile255') Or ($(TargetFrameworkProfile) == 'Profile259') Or ($(TargetFrameworkProfile) == 'Profile328') Or ($(TargetFrameworkProfile) == 'Profile336') Or ($(TargetFrameworkProfile) == 'Profile344')"

and vise versa.

**It's annoying. Why this happens?**

my `paket.dependencies` file

```
source https://nuget.org/api/v2

nuget CommandLineParser
nuget DocumentFormat.OpenXml
nuget DotNetZip
nuget MahApps.Metro 1.1.2
nuget MahApps.Metro.Resources 0.4.0
nuget Microsoft.Composition
nuget MvvmLightLibs
nuget NLog
nuget SharpShell
nuget WpfAnimatedGif
nuget squirrel.windows
nuget TaskScheduler

group Build
	source https://nuget.org/api/v2
	nuget FAKE

group Test
	source https://nuget.org/api/v2
	nuget NUnit
	nuget NUnit.Console

```

My `paket.lock` file:
```
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    CommandLineParser (1.9.71)
    CommonServiceLocator (1.3) - framework: >= net40, monoandroid, portable-net45+wp80+wpa81+win+MonoAndroid10+xamarinios10, xamarinios, winv4.5, wpv8.0, sl50
    DeltaCompressionDotNet (1.0.0)
    DocumentFormat.OpenXml (2.5)
    DotNetZip (1.9.8)
    MahApps.Metro (1.1.2)
    MahApps.Metro.Resources (0.4.0)
      MahApps.Metro (>= 1.0.0)
    Microsoft.Composition (1.0.30)
    Mono.Cecil (0.9.6.1)
    MvvmLightLibs (5.2.0)
      CommonServiceLocator (>= 1.0) - framework: net35, sl40
      CommonServiceLocator (>= 1.3) - framework: >= net40, monoandroid, portable-net45+wp80+wpa81+win+MonoAndroid10+xamarinios10, xamarinios, winv4.5, wpv8.0, sl50
    NLog (4.2.3)
    SharpShell (2.2.0)
    Splat (1.6.2)
    squirrel.windows (1.2.5)
      DeltaCompressionDotNet (>= 1.0.0)
      Mono.Cecil (>= 0.9.6.1)
      Splat (>= 1.6.2)
    TaskScheduler (2.5.16)
    WpfAnimatedGif (1.4.14)

GROUP Build
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    FAKE (4.22.6)

GROUP Test
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    NUnit (3.2.0)
    NUnit.Console (3.2.0.1)
      NUnit.ConsoleRunner (3.2.0)
      NUnit.Extension.NUnitProjectLoader (3.2.0)
      NUnit.Extension.NUnitV2Driver (3.2.0)
      NUnit.Extension.NUnitV2ResultWriter (3.2.0)
      NUnit.Extension.VSProjectLoader (3.2.0)
    NUnit.ConsoleRunner (3.2.0)
    NUnit.Extension.NUnitProjectLoader (3.2.0)
    NUnit.Extension.NUnitV2Driver (3.2.0)
    NUnit.Extension.NUnitV2ResultWriter (3.2.0)
    NUnit.Extension.VSProjectLoader (3.2.0)
```

**Comment by sergey-tihon** [comment]
May it be because [MvvmLightLibs](https://www.nuget.org/packages/MvvmLightLibs/) has very `interesting` dependencies?

![image](https://cloud.githubusercontent.com/assets/1197905/14077343/405cbc7c-f4f3-11e5-8b82-48e8eaed312e.png)

**Comment by forki** [comment]
Can you please create an csproj, paket.dependencies + paket.lock
combination that has that issue? Thx

**Comment by sergey-tihon** [comment]
Here it is https://github.com/sergey-tihon/paket-MvvmLightLibs

When I call 
> .paket\paket.bootstrapper.exe
> .paket\paket.exe install

Using ` 2.56.1.0`
![image](https://cloud.githubusercontent.com/assets/1197905/14082103/e18c20b0-f516-11e5-845f-657088aa2ae0.png)

I see
![image](https://cloud.githubusercontent.com/assets/1197905/14082130/0080fa54-f517-11e5-8a50-772b5501e83f.png)

**Comment by forki** [comment]
Thx. Will investigate tomorrow.

**Comment by sergey-tihon** [comment]
Thank you

**Comment by forki** [comment]
this is fixed now, but install/update will still change it one more time to a now stable version.

**Comment by sergey-tihon** [comment]
Thank you!

**Comment by forki** [comment]
did it work?

**Comment by sergey-tihon** [comment]
`paket.exe install` changed project files once, but after `paket.exe update` I see changes again
![image](https://cloud.githubusercontent.com/assets/1197905/14105304/71cbbb62-f5b3-11e5-981f-980305ac3ad3.png)

**Comment by forki** [comment]
I think the green one after update is correct and should be stable

**Comment by sergey-tihon** [comment]
It looks strange...
![image](https://cloud.githubusercontent.com/assets/1197905/14105388/f3d32000-f5b3-11e5-8846-07d91c3e66df.png)

**Comment by forki** [comment]
True. Can you copy and break the existing Integration test?

**Comment by sergey-tihon** [comment]
`paket.exe install` change it again
![image](https://cloud.githubusercontent.com/assets/1197905/14105425/2a96fd46-f5b4-11e5-9282-8e11f886fa9a.png)

**Comment by forki** [comment]
Sorry buddy. Please try to create yet another integration test. Will fix
asap

**Comment by sergey-tihon** [comment]
Here it is #1556

**Comment by forki** [comment]
ok, please give it another try

**Comment by sergey-tihon** [comment]
After `paket.exe update` I see
![image](https://cloud.githubusercontent.com/assets/1197905/14110387/d9920da8-f5ce-11e5-9767-bceb94d39e8d.png)
When I run `paket.exe install` again - `wpav8.1` disappears
![image](https://cloud.githubusercontent.com/assets/1197905/14110403/f696d3f2-f5ce-11e5-936a-11c4749cdf35.png)

**Comment by forki** [comment]
Please try with -f. Maybe now it's an issue with your cache

**Comment by sergey-tihon** [comment]
Even after `update`/`install` steps I see short package versions in spec
![image](https://cloud.githubusercontent.com/assets/1197905/14110578/b6d5e3c4-f5cf-11e5-8b50-5e16ca952c05.png)
Is it OK?

**Comment by forki** [comment]
Making the dependencies requirement with 3 digits is expected and guards you against conflicting responses from multiple source feeds

**Comment by forki** [comment]
So 3 digits should be stable

**Comment by sergey-tihon** [comment]
`paket.exe install -f`: 
![image](https://cloud.githubusercontent.com/assets/1197905/14110866/112a792e-f5d1-11e5-846c-6d3eaf939588.png)
`paket.exe update -f`:
![image](https://cloud.githubusercontent.com/assets/1197905/14110874/1f869e1c-f5d1-11e5-85ef-e92c445897b2.png)
+ project files changes

The next `paket.exe install` removes `wpav8.1` again
![image](https://cloud.githubusercontent.com/assets/1197905/14111052/d77d8198-f5d1-11e5-9534-a8a6cf1e28d9.png)

**Comment by forki** [comment]
![dead](https://cloud.githubusercontent.com/assets/57396/14111731/22bdd848-f5cc-11e5-981a-ce0a635d2afb.gif)

**Comment by sergey-tihon** [comment]
The good news is that I probably have repro again #1557

**Comment by sergey-tihon** [comment]
New error (on my machine) is strange ...

>  Expected string length 515 but was 513. Strings differ at index 86.
>  Expected: "...\n    CommonServiceLocator (1.3.0) - framework: >= net40, m..."
>  But was:  "...\n    CommonServiceLocator (1.3) - framework: >= net40, mon..."
>  ---------------------------------------------^

**Comment by sergey-tihon** [comment]
Ahhh, sorry, forgot to `prepare scenarioName`
I will try to come up with new repro ...

**Comment by forki** [comment]
(reverting that change with 3 digits versions)

**Comment by sergey-tihon** [comment]
One more integration test for this issue #1560

**Comment by sergey-tihon** [comment]
Thank you @forki 
It works now !!!

**Comment by forki** [comment]
![ok](https://cloud.githubusercontent.com/assets/57396/14137294/889aa7c2-f667-11e5-800d-e28600ac3350.gif)
