### ISSUE TITLE
CopyToOutputDirectory nodes blown away in project files after "paket update"

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket#1555]
If I've got some content from a package,  and it's been copied to the project, and I subsequently go and change the file metadata in the project so that it is copied to the output directory always (CopyToOutputDirectory node in the csproj file), then whenever I perform a `paket update`, (and likely the same for `paket install`), the CopyToOutputDirectory nodes are blown away in my project file.

I would expect these to be left alone unless there's a `copy_content_to_output_dir` flag set in the dependencies file.

Hope that makes sense.

**Comment by forki** [comment]
manual changes are not supported in this case. Why don't you use copy_content_to_output_dir ?

**Comment by pms1969** [comment]
That's my work around for the present. But we've got a lot of places where this might be a problem for us.  

Do you think it would be hard to add support for manual changes?  I can look into it, and in fact did a little debugging, but not sure what the strategy should be to resolve.

**Comment by forki** [comment]
why would it bring issues? that manual change is very very very hard to detect

**Comment by pms1969** [comment]
People are used to working with VS, so I can see it being a problem that in many cases isn't detected  until late in the deployment testing cycle for us. (for certain file types certainly, for others it's likely to cause build issues earlier which is fine).

Either way, if someone changes something in VS, you don't expect it to be blown away by another tool when it's run.

In terms of detecting the change, surely just changing existing the nodes instead of reconstructing them should do the trick?  (at least reconstructing is what I think the code is currently doing, feel free to correct me)

**Comment by forki** [comment]
Let me say I do understand that request, but it would make this work differently from all the other nodes. I'm not convinced that this is a good idea.

**Comment by pms1969** [comment]
well, if implemented, it should not be just for that one node, which I understand makes it a bigger job.

**Comment by smoothdeveloper** [comment]
If a node has `<Paket>true</Paket>` I expect it to be managed by the tool and I know it is going to be managed exclusively by paket.

Changing this behaviour seems like opening a whole can of worm and not very desired behaviour (I like the _sole source of truth_ concept, in this case it resides in paket.dependencies).

The expected workaround in this case is to specify `copy_content_to_output_dir` (and have the team do it that way) or to manage that dependency manually.

**Comment by pms1969** [comment]
that's a fair statement, and it's just given me a thought on how to manage those files without Paket blasting away the node. Thanks @smoothdeveloper/@forki

**Comment by forki** [comment]
if you remove the paket node it should not touch it. Is that what you mean? We can add integration tests for that
