### ISSUE TITLE
Targets from packages placed before Import of paket

### ISSUE THREAD

**Issue by WebDucer** [fsprojects/Paket#1562]
Helo.

I have the following problem with the current paket version (2.56.6.0)

If a package has build target (like SQLite or BCL libraries) paket generate something like this:

```xml
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.0'">
      <PropertyGroup>
        <__paket__System_Data_SQLite_Core_targets>net40\System.Data.SQLite.Core</__paket__System_Data_SQLite_Core_targets>
      </PropertyGroup>
    </When>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5'">
      <PropertyGroup>
        <__paket__System_Data_SQLite_Core_targets>net45\System.Data.SQLite.Core</__paket__System_Data_SQLite_Core_targets>
      </PropertyGroup>
    </When>
  </Choose>
```

With older versions (e.g. 2.50.1) this part is placed below `<Import Project=".paket/paket.targets" />` and with other `<Choose>` conditions for the packages.

In the current version this part is placed direct below  `<PropertyGroup>` for build configuration and above the `<Import Project=".paket/paket.targets" />`.

With this order the build fails (by SQLite the `x86` and `x64` Interops are not copied to output folder). If I change the order manually, build works.

**Comment by forki** [comment]
same as https://github.com/fsprojects/Paket/pull/1561?

**Comment by forki** [comment]
can you please retry with 2.57.0?

**Comment by forki** [comment]
please try with 2.57.1

**Comment by WebDucer** [comment]
Version 2.57.1 seems to work. I try tomorrow the version on a larger project.
