### ISSUE TITLE
Paket Push doesn't make use of the stored credentials for a given source.

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#1568]
if we specify a source url on the command line, should we be able to fetch the credentials from a stored set of credentials like we do for install/restore?

**Comment by forki** [comment]
that would probably make sense, but most use apikey!?

**Comment by baronfel** [comment]
I agree, but we do allow to set api tokens in the config already so couldn't we fetch from there?

**Comment by forki** [comment]
Yes. If you construct a repro sample, then it will be easy to make that
work

**Comment by baronfel** [comment]
Oh I was going to send a PR a bit later with a test and doc updates, if that's ok.

**Comment by forki** [comment]
Even better. ;-)
