### ISSUE TITLE
Redirects for assemblies in the GAC are removed by paket

### ISSUE THREAD

**Issue by freeranger** [fsprojects/Paket#1574]
### Description
I have a solution which needs this redirect:
```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Extensions" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```
Which is being removed by paket.

System.Web.Extensions is in the GAC.
I would expect paket to leave along any redirects for GAC registered assemblies by default or at least provide a configuration option where we can specify the redirects we want to keep

**Comment by forki** [comment]
When is that happening? Can you provide a repro sample? /cc @isaacabraham

**Comment by freeranger** [comment]
`paket convert-from-nuget --force`
is removing all redirects.
the paket.dependencies file only lets you specify keeping redirects for package references, not for GAC references

**Comment by forki** [comment]
AFAIK we should not touch GAC references in the redirects.

// @mrinaldi

**Comment by forki** [comment]
mhm. I tried to reproduce in b099dfe, but test is green. What am I missing?

**Comment by freeranger** [comment]
You are doing a `paket "install --force"` whereas the problem happens when you do a `paket convert-from-nuget --force`

**Comment by forki** [comment]
@theimowski are we doing something special in that command?

@freeranger can you reset the config files after conversion and rerun install? Does this keep the entries?

**Comment by freeranger** [comment]
@forki yes, if I re-add them after conversion then they are preserved

**Comment by forki** [comment]
Ok so it's something we do in convert.

**Comment by theimowski** [comment]
`update` is invoked as the last step in `convert`: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NugetConvert.fs#L392-L395, but it has `Force = true; Hard = true; Redirects = true`

**Comment by forki** [comment]
Mhm I guess it's the --hard flag. But I think it should not remove GAC stuff, right?

**Comment by theimowski** [comment]
Can't tell for sure @isaacabraham

**Comment by forki** [comment]
ok confirmed. it's the --hard flag

**Comment by freeranger** [comment]
Thanks for the quick turnaround fellas - works like a charm now :+1:
