### ISSUE TITLE
Can't provide credentials for install via CLI

### ISSUE THREAD

**Issue by rkachowski** [fsprojects/Paket#1576]
Paket allows to specify an api key for the `push` command, also taking it from the `nugetkey` environment variable. The same functionality doesn't exist for other commands (e.g. `install`). 

Currently the only way to authenticate with a private nuget server is to specify an apikey with the source declaration in the dependencies file. This results in private credentials working their way into source control which has obvious security problems.

Ideally I'd like to be able to specify a key on the command line. There's some complication with this as the key works per `source` item and potentially infinite sources can be pulled by any one file - perhaps a key per group or default to using the same key across all sources if only one is provided.

1. Is there a workaround for keeping credentials out of the paket.dependencies file?
1. Would this be a reasonable feature for a PR?

**Comment by baronfel** [comment]
Have you seen the `paket config add-credentials` command? https://fsprojects.github.io/Paket/paket-config.html

**Comment by forki** [comment]
see also https://fsprojects.github.io/Paket/nuget-dependencies.html#NuGet-feeds 

    source http://myserver/nuget/api/v2 username: "%PRIVATE_FEED_USER%" password: "%PRIVATE_FEED_PASS%"

allows to use env variables

**Comment by rkachowski** [comment]
awesome, thanks!
