### ISSUE TITLE
Build fails after nuget migration when a dependency exists for Baseclass.Contrib.Nuget.Output 

### ISSUE THREAD

**Issue by KevM** [fsprojects/Paket#1577]
### Description

Any time a project has a dependency on [Baseclass.Contrib.Nuget.Output](https://github.com/baseclass/Contrib.Nuget) it will not work under Paket. 

This utility nuget adds an msbuild target which to copies native .DLLs to the build directory. It does so in a way that is not compatible with Paket (uses packages.config to find files in, nuget-esque, paths with versions on them. 

This is not really Paket's problem but I am looking for suggestions on how we might use **Paket** on projects (we don't control) that rely on nugets using Baseclass.Contrib.Nuget.Output.

### Repro steps

Please provide the steps required to reproduce the problem

1. `git clone git@github.com:KevM/paket-contrib-repo.git`
1. `cd paket-contrib-repo`
1. `.\build.bat`

Build works and tests run.

#### Convert from nuget

1. '.\.paket\paket.exe convert-from-nuget --force`
1. `.\build.bat`

Migration goes well. But now the build fails. 

```
C:\Users\scoun\projects\paket-contrib-repo\packages\Baseclass.Contrib.Nuget.Output\build\net40\Baseclass.Contrib.Nuget.Output.targets(73,5): error : Failed to load package files: Could not find file 'C:\Users\scoun\projects\paket-contrib-repo\packages.config'. [C:\Users\scoun\projects\paket-contrib-repo\PaketContribRepro.csproj]
Running build failed.
Error:
Building PaketContribRepro.sln failed with exitcode 1.
```

### Related information 
* Windows 10
* Paket 2.58.3.0
* .NET Runtime 4.5

**Comment by KevM** [comment]
Hmm maybe I need to put all assemblies "tainted" by this nuget in to a Paket group and use `import_targets: false`. Sound realistic? I'd have to do the native .DLL copies myself but that would at least get the build working.

**Comment by forki** [comment]
yes that sounds like it may work.

**Comment by KevM** [comment]
The solution our project was to add `import_targets: false` to the troubled Nuget. 

```
nuget Baseclass.Contrib.Nuget.Output 2.1.0 import_targets:false
```

The troubled downstream nuget in our case was [lib-sodium](https://github.com/adamcaudill/libsodium-net) and we needed the native dll to be copied to the target dir so adding a post-build _xcopy_, to any project that did some crypto, did the trick.

```
 xcopy /s /y "$(SolutionDir)packages\libsodium-net\output\*.*" "$(TargetDir)"
```

If only there was a better way. But this worked.
