### ISSUE TITLE
Property Definitions: Placed before FSharp Targets

### ISSUE THREAD

**Issue by ascjones** [fsprojects/Paket#1585]
### Description

After ``paket install``, Websharper targets are moved up above FSharp target import which they depend on, since this commit: https://github.com/fsprojects/Paket/commit/8a9ba04b6abc0d49105f29f880c872c268465352

Guess we need something similar to this fix for CSharp targets: https://github.com/fsprojects/Paket/commit/de12ae86a5416f5ee3a9b608a89a826a340aa0a5

### Repro steps

Import FSharp targets like so:

```
 <!-- F# targets -->
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
  <Import Project="$(FSharpTargetsPath)" />
```

1. run ``paket install``

### Expected behavior

Expect the Websharper targets to show up **after** the FSharp Targets import

### Actual behavior

WebSharper Targets show up **before** the FSharp Targets import

**Comment by forki** [comment]
which nuget package is that?

**Comment by ascjones** [comment]
https://www.nuget.org/packages/WebSharper/3.6.11.234

I'm just guessing that it depends on FSharp targets, but anyway it works when the targets import it is below them.

**Comment by ascjones** [comment]
Yep just confirmed, the WebSharper target import needs to appear **after** FSharp targets import in order to run, like so:

```
  <Import Project="$(FSharpTargetsPath)" />
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.1'">
      <PropertyGroup>
        <__paket__WebSharper_targets>WebSharper</__paket__WebSharper_targets>
      </PropertyGroup>
    </When>
  </Choose>
```

**Comment by forki** [comment]
fix is under way

**Comment by ascjones** [comment]
Fantastic thanks!
