### ISSUE TITLE
Paket could not restore http dependencies to the same directory

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#1589]
### Description

Paket could not restore http dependencies to the same directory

### Repro steps

- `paket.dependencies`
```
source https://nuget.org/api/v2

http http://nlp.stanford.edu/software/stanford-ner-2015-12-09.zip
http http://nlp.stanford.edu/software/stanford-segmenter-2015-12-09.zip
```

- `paket.lock`
```
HTTP
  remote: http://nlp.stanford.edu
  specs:
    stanford-ner-2015-12-09.zip (/software/stanford-ner-2015-12-09.zip)
    stanford-segmenter-2015-12-09.zip (/software/stanford-segmenter-2015-12-09.zip)
```
- Execute `.paket.restore`
- Execute `.paket.restore`

### Expected behavior

Correct files restore

### Actual behavior

```
Paket version 2.58.9.0
Downloading nlp.stanford.edu/:/software/stanford-ner-2015-12-09.zip stanford-ner-2015-12-09.zip to d:\temp\paket-restore\paket-files\nlp.stanford.edu\stanford-ner-2015-12-09.zip
Downloading nlp.stanford.edu/:/software/stanford-segmenter-2015-12-09.zip stanford-segmenter-2015-12-09.zip to d:\temp\paket-restore\paket-files\nlp.stanford.edu\stanford-segmenter-2015-12-09.zip
Paket failed with:
        Error during deletion of d:\temp\paket-restore\paket-files\nlp.stanford.edu
  - Could not find a part of the path 'd:\temp\paket-restore\paket-files\nlp.stanford.edu'.
```

### Known workarounds

Uses Paket `v2.39.8.0`

### Related information 

* Paket version 2.58.9.0

**Comment by tpetricek** [comment]
I think I've seen similar issues (sometimes) when downloading multiple files via file dependencies from the same location.

It smells like some concurrency issue, but I never quite looked into the details.

**Comment by sergey-tihon** [comment]
We have [one more `CleanDir`](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/RemoteDownload.fs#L181) in the case of downloading `zip` file.

**Comment by forki** [comment]
@tpetricek the inner thingy is parallel as well: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/RemoteDownload.fs#L223

**Comment by forki** [comment]
and source.Commit is different so they are not in same group

**Comment by sergey-tihon** [comment]
Now it is slightly slower than before [2 minutes, 20 seconds](https://ci.appveyor.com/project/sergey-tihon/stanford-nlp-net/build/0.0.1.52#L25) vs [1 minute, 53 seconds](https://ci.appveyor.com/project/sergey-tihon/stanford-nlp-net/build/0.0.1.39#L25) in old parallel mode.

And it seems that you changes [the folder where zip archive will be extracted](https://ci.appveyor.com/project/sergey-tihon/stanford-nlp-net/build/0.0.1.52#L39)...

**Comment by forki** [comment]
I don't think we change the folder. But now we see the result of cleandir. it deletes the first thing when the second download happens. try to work around that

**Comment by sergey-tihon** [comment]
Yep, you are right. Only one last download in the folder.

**Comment by forki** [comment]
and another release...

**Comment by sergey-tihon** [comment]
Seems like paket is OK now.
Thank you @forki
