### ISSUE TITLE
Problem with source code content

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1592]
### Description
If nugget has source code as content item,  paket should not add  CopyToOutputDirectory Always element

Example:
```
<Compile Include="Properties\orleans.codegen.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
 </Compile>

```

**Comment by tsibelman** [comment]
@forki ?

**Comment by forki** [comment]
Do you have a repro sample for us? Or a package that creates such issues?

**Comment by tsibelman** [comment]
Yes you can try with Microsoft.Orleans.Templates.Interfaces nuget

**Comment by forki** [comment]
but you explicitly specified to set that property right?

**Comment by forki** [comment]
I guess we should never set that for Compile items

**Comment by tsibelman** [comment]
I used content once for this nugget, I think you correct that Compile items never should be copied
