### ISSUE TITLE
feature: generate .fsx / .csx include scripts

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/Paket#1593]
I noticed paket has excellent support for transitive dependencies.

When I'm doing F# scripting, I rely on assemblies located in packages, but I always have to reference explicitly the transitive dependencies, at least when public members I'm trying to use expose types from those.

It would be great if paket could generate (maybe an option in paket.dependencies) script files for including the packages' assemblies with it's transitive dependencies.

Here is a simple example

```fsharp
#r "packages/MBrace.Thespian/lib/net45/MBrace.Thespian.dll"
open MBrace.Thespian. // autocomplete at this point says I need to reference some other assembly
```

When, I do that, I have to add references to `MBrace.Runtime`, etc.

Instead, I'd like to do this:

```fsharp
#load "packages/include-scripts/MBrace.Thespian.fsx"
```

and be ready for happy scripting experience, even when transitive dependencies changes, etc.

It also simplifies a lot simple references as I don't have to lookup the exact location of assemblies.

To play nice with C# .csx users, identical .csx files could also be generated.

**Comment by isaacabraham** [comment]
We've had a think about this in the past. I seem to recall it's not as easy as that though - what was the problem @forki ?

You can use VFPT to generate a references.fsx though that does this.

**Comment by smoothdeveloper** [comment]
@isaacabraham mmh, I couldn't come up with an original idea that great, someone else necessarily thought about it before...

I think if it works in most of cases (like no native / architecture dependent) dependencies or packages which only have reasonable set of assemblies under lib folder, that could still be a great feature for scripting.

I'm aware of VFPT feature, but when I work with scripting, I don't even bother with fsproj / visual studio projects, I just need a paket.dependencies and a script file to start hacking.

**Comment by isaacabraham** [comment]
Yep re: fsproj - agreed. And using Paket or similar would remove dependency on VS as well.

**Comment by forki** [comment]
assembly load order is important and we don't know how to figure that out

**Comment by smoothdeveloper** [comment]
@forki, would Mono.Cecil be of help there? I know I've been using it to figure out dependencies of assembly files with reasonable success:

https://gist.github.com/smoothdeveloper/994522269a0a04c275c9#file-package-devexpress-fsx-L71
