### ISSUE TITLE
Can't pack project type templates from new csproj files

### ISSUE THREAD

**Issue by rkachowski** [fsprojects/Paket#1594]
### Description

After creating a new project via visual studio 2015 community edition and initializing paket, the `paket.exe pack` command doesn't create a nupkg file as explained in [the paket.template documentation](https://fsprojects.github.io/Paket/template-files.html).

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a new default class library project via Visual Studio Community 2015
2. Run `paket.exe init` to create a blank paket.dependencies file
3. Run `paket.exe install` to generate the paket.lock file
3. Create a `paket.template` file at the top of the dir with the contents below
3. Build the solution under the release configuration via Visual Studio
3. Run `paket.exe pack output bin version 1.0.0 templatefile paket.template`

paket.template contents
```
type project
licenseUrl http://opensource.org/licenses/MIT
```

### Expected behavior

Paket bundles the output of the project (in this case `ClassLibrary1.dll` ) into a nupkg file available in the bin dir.

### Actual behavior

Paket runs but does not create the nupkg file. If pack is run before the project is built (i.e. before the `ClassLibrary1.dll` exists in the bin/Release dir) Paket will error out and mention that it cannot find the output files.

### Related information 

* OSX 10.10
* Paket version 2.58.12.0
* Mono JIT compiler version 4.2.2

> Attached is the sample project - output from a new visual studio class library project

### Logs
```
$ tree
.
├── Class1.cs
├── ClassLibrary1.csproj
├── ClassLibrary1.sln
├── Properties
│   └── AssemblyInfo.cs
├── bin
│   ├── Debug
│   └── Release
│       ├── ClassLibrary1.dll
│       └── ClassLibrary1.pdb
├── obj
│   ├── Debug
│   │   ├── DesignTimeResolveAssemblyReferencesInput.cache
│   │   └── TempPE
│   └── Release
│       ├── ClassLibrary1.csproj.FileListAbsolute.txt
│       ├── ClassLibrary1.dll
│       ├── ClassLibrary1.pdb
│       ├── DesignTimeResolveAssemblyReferencesInput.cache
│       └── TempPE
├── packages
├── paket.dependencies
├── paket.lock
└── paket.template
​
10 directories, 14 files
[17:15][~/New folder/ClassLibrary1 (master)]
$ cat paket.template
type project
licenseUrl http://opensource.org/licenses/MIT
[17:15][~/New folder/ClassLibrary1 (master)]
$ mono paket.exe pack output bin version 1.0.0 templatefile paket.template 
Paket version 2.58.12.0
No platform specified; found output path node for the AnyCPU platform after failing to find one for the following:
[ClassLibrary.tar.gz](https://github.com/fsprojects/Paket/files/213318/ClassLibrary.tar.gz)

0 seconds - ready.
[17:15][:~/New folder/ClassLibrary1 (master)]
$ tree
.
├── Class1.cs
├── ClassLibrary1.csproj
├── ClassLibrary1.sln
├── Properties
│   └── AssemblyInfo.cs
├── bin
│   ├── Debug
│   └── Release
│       ├── ClassLibrary1.dll
│       └── ClassLibrary1.pdb
├── obj
│   ├── Debug
│   │   ├── DesignTimeResolveAssemblyReferencesInput.cache
│   │   └── TempPE
│   └── Release
│       ├── ClassLibrary1.csproj.FileListAbsolute.txt
│       ├── ClassLibrary1.dll
│       ├── ClassLibrary1.pdb
│       ├── DesignTimeResolveAssemblyReferencesInput.cache
│       └── TempPE
├── packages
├── paket.dependencies
├── paket.lock
└── paket.template
​
10 directories, 14 files
```

**Comment by forki** [comment]
do you have that sample project for me?

**Comment by rkachowski** [comment]
[ClassLibrary.tar.gz](https://github.com/fsprojects/Paket/files/213323/ClassLibrary.tar.gz)

i'm not sure why it didn't attach before

**Comment by forki** [comment]
thanks for reporting. please retry with the new version.
