### ISSUE TITLE
WebSharper project no longer builds due to Paket changes to project file

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [fsprojects/Paket#1595]
This happens with command line paket or with Paket for Visual Studio. There were two updates to Paket for Visual Studio recently. I'm not sure which one started this problem.

I have a WebSharper project, and if I understand correctly the WebSharper compiler is run by the following step at the end of the project file:

``` xml
<Import Project="..\packages\WebSharper\build\$(__paket__WebSharper_targets).targets" Condition="Exists('..\packages\WebSharper\build\$(__paket__WebSharper_targets).targets')" Label="Paket" />
```

The `__paket__WebSharper_targets` property is set earlier in the file:

``` xml
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.1'">
      <PropertyGroup>
        <__paket__WebSharper_targets>WebSharper</__paket__WebSharper_targets>
      </PropertyGroup>
    </When>
  </Choose>
```

This `<Choose>` code has now moved. It used to be quite near the end of the project file, not far from the `<Import>` statement that uses it, and now it is much earlier and now appears _before_ this line:

``` xml
<Import Project="$(FSharpTargetsPath)" />
```

I am not very familiar with how MSBuild works, so I'm only guessing that this line is significant.

The result is that the F# project compiles, but the WebSharper compiler is not started.

**Comment by forki** [comment]
I just pushed another Paket.VisualStudio update that brings the addin in
sync with paket.exe

**Comment by Bananas-Are-Yellow** [comment]
My Visual Studio (Tools / Extensions and Updates command) is not showing a new version yet, but I just got the latest paket.exe (v2.58.14), and updated from the command line, and I can confirm that it now builds correctly.

Thanks.

**Comment by Bananas-Are-Yellow** [comment]
The new version of Paket for Visual Studio is now showing. I guess it takes 15 minutes or so for it to appear.
