### ISSUE TITLE
pack fails for f# projects using ReflectedDefinition attributes

### ISSUE THREAD

**Issue by haraldsteinlechner** [fsprojects/Paket#1601]
This issue is related to a problem in FSharp.Data, where our pull request is in review (seealso: https://github.com/fsharp/FSharp.Data/pull/919)
However, since the problem occurs in paket and testing is difficult i created this issue, serving as solid test case as well as documentation for the problem.

### Description

pack fails internally in AssemblyReader.fs when parsing assembly metadata. 

### Repro steps

#1596 in my fork https://github.com/haraldsteinlechner/Paket/commit/7b0680aeda453951669e1a064d1fae6e0e5baf59 shows the problem. 

### Expected behavior
packing simply works

### Actual behavior

System.Exception : Paket failed with:
	decodeILCustomAttribData: error parsing type in custom attribute blob: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)

### Known workarounds

my FSharp.Data fork fixes the problem: https://github.com/haraldsteinlechner/FSharp.Data/commit/d4a30757dc5e5ef7096fffafc1ed377b6174771b

**Comment by forki** [comment]
we could point https://github.com/fsprojects/Paket/blob/master/paket.dependencies#L9 to your fork if you need a quick fix

**Comment by haraldsteinlechner** [comment]
i did this here: https://github.com/haraldsteinlechner/Paket/tree/assemblyMetadataFix
but still waiting for integration tests to complete. Although the involved code is tricky, we could give it a try and use my fix.
(pull request after test completion)

**Comment by forki** [comment]
this is released. Please set it back to FSharp.Data when they merged your PR

**Comment by forki** [comment]
and thanks!
