### ISSUE TITLE
Support --pre flag for paket update command

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1609]
Right now paket outdated has a --pre option so it possible to check for existence of beta versions. 
But it no possible to get them for testing by just runing paket update command.

**Comment by cdrnet** [comment]
When running `update -pre` and then later `update` again but this time without `-pre`, would you expect it to revert back to what was there before, i.e. only prereleases where allowed in the dependencies file?

NB: We currently have a similar problem with `update x version 1.3-beta2` which could also lead to a lock file inconsistent with the dependencies file.

**Comment by tsibelman** [comment]
Yes I would expect it to revert, if --pre is not used. It not for updating the dependency files. And I don't see it as inconsistency.

**Comment by cdrnet** [comment]
If we have a dependencies file that does not allow prereleases but use update twice in a row to update two different dependencies to prerelease versions, then currently the second call actually reverts the changes of the first one (since it is "inconsistent" with the dependencies file).

By specifying `--pre` on the second one I expect the changes of the first one would then be kept?

**Comment by tsibelman** [comment]
Yes looks right to me

**Comment by forki** [comment]
I think update  --pre should work like outdated and install latest of everything. 
Following update commands (without --pre) should downgrade again. (even paket install should detect the "invalid" lock file and downgrade) 

In general a "invalid" lock file is nothing bad. Dependencies file (and even packages on nuget.org) change all the time.

**Comment by cdrnet** [comment]
Great, that would simplify some use cases of our team as well.

Does that imply we'd also need `--pre` for install (and add, remove) to be able to prevent the downgrade?

**Comment by forki** [comment]
I assume it would be useful and not that much extra work to have that
consistent with all commands that have an install step.

**Comment by forki** [comment]
I marked it up-for-grabs and think it should go into v3. I don't really want to have new features in v2 anymore. Only stuff that is really needed.

**Comment by tsibelman** [comment]
@forki I think --pre must respect nuget and --filter params,

**Comment by enricosada** [comment]
Closed,

`paket outdated` support `--pre`
