### ISSUE TITLE
`aspnetvnext` transitive dependencies are not referenced

### ISSUE THREAD

**Issue by vladnega** [fsprojects/Paket#1616]
### Description

Transitive dependencies that have the `https://www.myget.org/F/aspnetvnext` source aren't being referenced in the F# project.

### Repro steps

I assume you have the Paket extension for Visual Studio installed. I'm using Visual Studio 2015.

1. Create an F# Library project. 
2. Press the `Convert from Nuget` button.
3. Add the `Autofac.Extensions.DependencyInjection` dependency in the `paket.references` file.
4. Press the `Update all dependencies` button.

### Expected behavior

I expect that at least the following packages are referenced in the project:

- Autofac (>= 4.0.0-rc1-177) - framework: >= net451, dnxcore50
- Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0-rc1-final) - framework: >= net451, dnxcore50
- System.Collections (>= 4.0.11-beta-23516) - framework: dnxcore50
- System.Diagnostics.Contracts (>= 4.0.1-beta-23516) - framework: dnxcore50
- System.Runtime (>= 4.0.21-beta-23516) - framework: dnxcore50
- System.Threading.Tasks (>= 4.0.11-beta-23516) - framework: dnxcore50

These are the first level transitive dependencies of `Autofac.Extensions.DependencyInjection (4.0.0-rc1-177)` according to the `paket.lock` file

### Actual behavior

Only the packages from the `Nuget` source are referenced:
- Autofac
- Autofac.Extensions.DependencyInjection

### Known workarounds

Edit the `.fsproj` file myself by adding the missing references.

### Related information 

* Operating system: Windows 10
* Paket version: 2.60.*
* .NET Runtime: 4.6 or 4.5.1
* Github repo with sample F# project reproducing the issue: https://github.com/vladnega/PaketTrial.git

### Question

Am I missing a flag in the `paket.dependencies` file, or is this an actual issue?

**Comment by forki** [comment]
Did you try with latest command line tool? I did not update the VS tool
yet. Will do in a minute.

**Comment by vladnega** [comment]
Just tried  doing a `paket.exe update` with version `2.62.1.0`, reloaded the project, but still got the same result.

**Comment by forki** [comment]
According to https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#list-of-net-corefx-apis-and-their-associated-net-platform-standard-version dnxcore is deprecated

**Comment by forki** [comment]
so iassume we need to treat dnxcore as some .netstandard thingy or wait until they release proper package that match their own specs

**Comment by vladnega** [comment]
I assume so. Paket was working fine prior to their *.rc3* releases.

**Comment by forki** [comment]
ok let's consider System.Collections:

![image](https://cloud.githubusercontent.com/assets/57396/14588618/f929d53e-04cd-11e6-9c6a-4ffc7e262d84.png)

so if you run .NET Runtime: 4.6 or 4.5.1 this should not be added. I think Paket does this correct,

**Comment by forki** [comment]
tbh. it doesn't look too bad. that dnxcore stuff should not be added to NET 4.5.1 projects.
So what file is really missing?

**Comment by vladnega** [comment]
You're right. I didn't pay attention to the runtime. Thanks.
