### ISSUE TITLE
How to Paket in a batch file [solved]

### ISSUE THREAD

**Issue by CADbloke** [fsprojects/Paket#1618]
### Description

I had to work this out myself. I thought it would work like Nuget does `nuget.exe restore path\to\yr\VisualStudio.sln` but no.

### Repro steps

Please provide the steps required to reproduce the problem

1. Look on the Internets

### Expected behavior

find an **example** of how to use paket in a batch file eg. `restore`

### Actual behavior

I got nuthin

### Known workarounds

keep trying different things until it works

### Related information 

* Operating system: Windows

### Solution
```bat
pushd your\paket\working\folder\with\paket\in\it
paket.exe restore
popd
```
It would be handy if you could add this to pages like https://fsprojects.github.io/Paket/paket-restore.html

**Comment by smoothdeveloper** [comment]
@CADbloke thanks for sharing your problem, I'm not sure what is the difference with nuget:

```bat
pushd your\nuget\working\folder\with\nuget\in\it
NuGet.exe restore
popd
```

Do you assume `NuGet.exe` is in your path? on my machine (which as VS2013 and VS2015 installed) it isn't the case, even if I run a VS command prompt.

If you want to create such a .bat you should look into calling `paket.bootstrapper.exe` first, and avoid checking in `paket.exe` in your repository.

**Comment by smoothdeveloper** [comment]
Also, have you checked https://fsprojects.github.io/Paket/getting-started.html#Manual-setup I think it gives a good overview.

**Comment by isaacabraham** [comment]
There *is* a decent amount of documentation on the site, but maybe @CADbloke you'd be interested in submitted a PR to the repo with a new "Batch File" documentation page?

There's not a lot to running in a batch mode (indeed, that's how it's commonly used within e.g. CI process): -

1. Ensure paket.bootstrapper is in source control
2. Run paket.bootstrapper
3. Run paket.restore

This is exactly the same as with NuGet except with NuGet most people check in the full NuGet.exe rather than a bootstrapper.

**Comment by magicmonty** [comment]
Please see also https://gist.github.com/magicmonty/858066629b08c0e2e310 for a paket.bat, which works nicely with TFS 2010 (readonly Project files, if not checked out already) ;)

**Comment by forki** [comment]
It's a command line tool. It works nicely in batch files. What's the
concrete issue?

**Comment by CADbloke** [comment]
Thanks for all the follow-ups.
The difference to Nuget is that you can run Nuget on an existing or newly cloned repo like

```
P:\ath\to\Nuget\nuget.exe restore y:\our\working\folder\with\your\VisualStudioSolution.sln
```

I expected paket to work like that but it didn't take the parameter for the path to the solution so I had to figure it out. So I dialed a whaaambulance because there was nothing to copy-paste from StackOverflow. #Luser

My use-case is keeping repos I've cloned and use a libs updated, the repo in this case was MahApps.Metro. I don't know if I'd add much more than I already have by doing a PR for a doc page but if you think any of this is useful I'll try to find time for it.

```
call :pull https://github.com/MahApps/MahApps.Metro.git MahApps.Metro
call :link MahApps.Metro.NET45.csproj
echo Restoring Pakets for MahApps
pushd C:\Codez\tvCAD\z.Libraries\MahApps.Metro\.paket\
paket.exe restore
popd
```

`:pull` pulls and rebases (or clones if missing) the repo in question, %2 is the folder for that repo, relative to the current running folder.
`:link` is a call to my [CodeLinker](https://github.com/CADbloke/CodeLinker) app which maintains my copy of the original `csproj` project but with my tweaks.

**Comment by forki** [comment]
ok. let's clarify. you need to sta in the folder with the paket.dependencies file, but you can do `P:\ath\to\`Paket\paket.exe restore` from there

**Comment by smoothdeveloper** [comment]
@CADbloke thanks, we now all understand why Santa would be sad not being able to install all the pakets :)
