### ISSUE TITLE
Add ability to query assemblies in a package.

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#1623]
The API should expose the ability to query Paket to provide the list of assemblies in a package (or all packages).

**Comment by smoothdeveloper** [comment]
@isaacabraham have you check `InstallModel`? I think it fits this use case.

**Comment by isaacabraham** [comment]
Not sure - @forki and myself spoke about this on the weekend - @forki have I just named this issue wrongly?

**Comment by smoothdeveloper** [comment]
@isaacabraham we did use it to get assemblies there: https://github.com/matthid/Paket/blob/generate_scripts_v3/src/Paket.LoadingScripts/LoadingScriptsGenerator.fs#L52

**Comment by isaacabraham** [comment]
Yeah that looks about right.... @forki ?

**Comment by smoothdeveloper** [comment]
@isaacabraham do you still need this? maybe we can close the issue or discuss further what you need in API?

**Comment by isaacabraham** [comment]
This was needed for the work I was looking to do in Functions for Paket interop. That's kind of taken a back seat at the moment so I've not checked now - let's close this and when I pick that up again if it's a problem I can reopen this.
