### ISSUE TITLE
When a group is named "Lib", nuget references won't get added to the projects

### ISSUE THREAD

**Issue by theor** [fsprojects/Paket#1627]
### Description

If I name a dependency group "Lib", `paket install` won't add the references in any fsproj.
### Repro steps
1. Create a paket.dependencies like that:

```
    group Lib
      source https://nuget.org/api/v2
      nuget FParsec
```

and the matching paket.references:

```
    group Lib
      FParsec
```

call paket install. Notice the fsproj does not contain the references to FParsec.
### Expected behavior

References to the nuget package in the fsproj
### Actual behavior

Packages are downloaded, but references are skipped
### Known workarounds

Rename the group
### Related information

Happened multiple times when using ProjectScaffold, I _think_ I had the problem with a raw paket project too.

**Comment by forki** [comment]
TBH I think we should exclude group names "lib" and "runtimes" for internal reasons. Can you send a pull request that throws an error in the GroupName "constructor"?

**Comment by smoothdeveloper** [comment]
@forki / @theor apparently the associated change was merged, should this issue be closed?

**Comment by TeaDrivenDev** [comment]
@forki Fixed?

**Comment by matthid** [comment]
That part was rewritten anyway. If there are still issues in paket 5 please report them!
