### ISSUE TITLE
Question: Can whole package groups be excluded in a paket.template file?

### ISSUE THREAD

**Issue by Martin-Bohring** [fsprojects/Paket#1630]
### Description

This is probably the wrong place for questions, but I did not find the right place.
Can paket groups be excluded via the **excludeddependencies** option in a paket.template file?

### Repro steps

I have organized paket dependencies into groups (a very nice feature). One of those is a build group.
Examples for build group packages are analyzers, Roslyn refactorings etc.

### Expected behavior

Right now I have no exspectations, Excluding package groups might be a new feature.

### Actual behavior

When using paket pack some of those build dependencies are picked up. 

### Known workarounds

Right now  I am resorting to enumerate all packages within the build group to be excluded.
 
### Related information 

Not relevant.

**Comment by forki** [comment]
mhm. I could see a *excludedgroups* property. Should be easy to implement if you follow the code of the current feature.

==> up-for-grabs
