### ISSUE TITLE
requirement that restore be from the install source breaks CI builds

### ISSUE THREAD

**Issue by mlidbom** [fsprojects/Paket#1633]
### Description

When developing projects that refer to each other through nuget packages the strict requirement that a package must be restored from the same source that it was installed from breaks builds on the CI server and other developers machines.

**It is possible to work around with a different workflow, but that becomes very costly in time when you are talking about dozens of projects depending on project A instead of 1 as in the repro steps below.**
### Repro steps
1. Developer works on Project A and B. Project B references A through a nuget package. 
2. Developer locally bumps project A from 1.0 to 1.1 and updates A in B.
3. paket.lock now has A 1.1 installed from c:\DEV_FEED
4. Developer pushes the new version of A and B
5. The CI server builds A and publishes the new version of A.nupkg. to http://OFFICIAL_FEED
6. The CI server tries to build B but fails since A.nupkg does not exist in c:\DEV_FEED on the CI server

```
Paket failed with:
        The package A 1.1 can't be found in c:\DEV_FEED.
Please check the feed definition in your paket.dependencies file.
```
### Suggested solution: Development sources

paket.dependencies

```
source http://OFFICIAL_FEED development c:\DEV_FEED 
```

When updating-to/installing a package from c:\DEV_FEED it would be entered as installed from http://OFFICIAL_FEED in paket.lock
When restoring paket would fall back to packages in c:\DEV_FEED if package is missing in http://OFFICIAL_FEED
### Alternative solution: Try each source

set an option in paket.dependencies
allowRestoreFromAnyFeedTryFeedsInOrderDefined true

With that option set paket would check for the existence of a package in each feed in order when restoring. 
You would define the official feeds first and the development/local feeds later so that official packages would always be preferred.

**Comment by forki** [comment]
yes overwriting sources on dev time is on our agenda. But I think it should be in a different file (to allow you to gitignore it).

I stil need an diea how the format would look like

**Comment by mlidbom** [comment]
How about something like this?

paket.dependencies
```
source OFFICIAL_SOURCE
```
paket.sourceoverrides
```
source OFFICIAL_SOURCE fallback LOCALLY_BUMPED_PACKAGES prefer EXPERIMENTING_DEBUGGING
```
When installing/updating paket.lock would always register the packages as coming from the feed in paket.dependencies

When restoring paket would look up a requested package in this order
1. prefered
2. paket.dependencies
3. fallback

**Comment by mlidbom** [comment]
If we want to make the file more generic in order to be able to put other development time overrides in there this might be a better fit: 

paket.overrides
```
sourceoverride OFFICIAL_SOURCE fallback LOCALLY_BUMPED_PACKAGES prefer EXPERIMENTING_DEBUGGING
```

**Comment by forki** [comment]
Interested in helping with this?

**Comment by mlidbom** [comment]
I'm willing to give it a shot.
However: I'm not exactly fluent in F# and I'm almost completely unfamiliar with the code.
Could you give me some pointers about the structure of the code as relates to this?
Can I get in touch with you and/or other Maintainers using skype or similar?

**Comment by forki** [comment]
I'm pretty much always available on gitter.
Let's start with something easy.

For a first step I'd like to see a PR which creates couple of (red) unit test for the parser. You can basically copy https://github.com/fsprojects/Paket/blob/master/tests/Paket.Tests/DependenciesFile/ParserSpecs.fs#L43 - then we implement that parser and I'm trying to discover how to fit that in.

**Comment by forki** [comment]
please send that against v3 branch

**Comment by theimowski** [comment]
I'm interested in this feature as well, and could give some help.
Not sure I understand why you'd need the `fallback` option? 
I'd suggest something like following:

`paket.local` file (added to gitignore)
```
source http:\\team_nuget_feed -> source c:\git\project\nupkgs
git http:\\remote_git_repository.git master -> git c:\git\project bugfix
```

Basically during restore, source on the right would replace source on the left side
Also note that Paket v3 comes with feature of [git-repo based feeds](http://fsprojects.github.io/Paket/git-dependencies.html#Using-Git-repositories-as-NuGet-source), thats why I'd propose a format for this as well (second line)

**Comment by forki** [comment]
Yes making this work with git repos will be awesome.

**Comment by Krzysztof-Cieslak** [comment]
:+1: to @theimowski idea. I don't think that "dev time dependency" should modify `paket.dependency` as it's committed and used by CI. gitignored file (let's say `paket.local`) would definitely be better option in my opinion.

**Comment by mlidbom** [comment]
> Not sure I understand why you'd need the fallback option

The gospel of package management as preached in my organisation (I agree completely by the way):
- Once an official package exists always build against that package.
 - Since a published package should never change it makes little sense to develop against anything but the official version once one exists. 
 - CI always builds only against official packages
 - If you need changes to a package you bump it and update in all dependent projects. 

We only need these overrides so that we can develop new versions of packages and test them locally before publishing them on the official feed.

Since our build scripts builds the packages automatically each developer workstation usually has local versions of the latest version of every packages. If these were "prefer"ed over the official source packages the developer would almost never be running the official package. This would make it very easy to make something "work" locally that would fail miserably as soon as pushed to CI. This would be likely to cause a lot of confusion and extra work.

We actually have little to no need for the prefer flag the way we work.

**Comment by mlidbom** [comment]
@theimowski 
> I'm interested in this feature as well, and could give some help.

I hardly speak F#,  I'm unfamiliar with the code base. And I have little to no time to spare for doing this.
Any and all assistance is welcome as far as I'm concerned. Up to and including taking care of the whole thing while I just observe :)

**Comment by theimowski** [comment]
> Since our build scripts builds the packages automatically each developer workstation usually has local versions of the latest version of every package. If these were "prefer"ed over the official source packages the developer would almost never be running the official package. This would make it very easy to make something "work" locally that would fail miserably as soon as pushed to CI. This would be likely to cause a lot of confusion and extra work.

Yes it could cause confusion, that's why I think there should be issued a big warning every time you build locally with an "overriden" source (i.e. local source).

> Any and all assistance is welcome as far as I'm concerned. Up to and including taking care of the whole thing while I just observe :)

I can try to create a WIP PR for this feature, and then we could cooperate on that

**Comment by mlidbom** [comment]
>I can try to create a WIP PR for this feature, and then we could cooperate on that

Great :)

>Yes it could cause confusion, that's why I think there should be issued a big warning every time you build locally with an "overriden" source (i.e. local source).

I completely agree for the "prefered" case. Prefer replaces official packages. This should in my opinion be done rarely indeed.

Fallback on the other hand will never replace an official package. As such It is not dangerous or confusing the way prefer is. It is a commonplace occurrence for us to work against locally built bumped packages that do not yet exist in the official feed. Fallback let's us do that safely.

You get "fallback" behavior from nuget.exe if you place the official feed before the local feed in the targets file. 
If you place the local feed before the official feed nuget.exe gives you "prefer" behavior.

"Fallback" is the way that we have been working for years. We tried "prefer" for a short time, years ago, and it caused a lot of trouble. We quickly changed it and have had no problems with that workflow since.

Could you explain how you imagine the workflow using prefer? Why you consider it to be superior and the only one that should be supported?

**Comment by forki** [comment]
Tbh I think we should always replace when we find a local replace
statement. That will makes things much clearer. I work against local copy
of something (git source) or the official repo. This should be configurable
on package level.

**Comment by theimowski** [comment]
Yeah it probably makes more sense to do it on package level instead of whole feed:

    nuget FAKE -> source c:\git\FAKE

But then do we want to point to specific .nupkg file/ dir or rather specify build command?

**Comment by theimowski** [comment]
@mildbom the workflow would be:
* you reference an official package from a feed
* the referenced package has a bug/ needs a new feature on context of the referencing project
* you want to test the new behavior against the referencing package, but ideally not releasing new versions until you've tested it locally
* for that you declare in paket.local "for package X use temporarily whatever comes from Y local dir"
* when you're done with changing the referenced package, release new version and then remove the entry from paket.local

Does it make any sense?

**Comment by mlidbom** [comment]
@theimowski, @forki 
(Sorry about the length of the post but I could not see a way to make our situation/needs clear much more consisely.)
 > Does it make any sense?
 
 Sure it makes sense. For many this workflow would probably work fine. 
 
Let me give you som context on my teams use of nuget packages. I think that context is what is missing for my arguments to make sense.


We maintain an enterprise SOA ecosystem:
- A handful of framework/library solutions
 - Each with its own separate source code repository and release lifecycle 
 - Together **producing about 20 nuget packages**.
 - Many consume packages produced by the others
 - All consume a number of 3rd party packages.
- About 30 Application/Service solutions
 - Each with its own separate source code repository and release lifecycle
 - Together **producing about 100 nuget packages**.
 - Virtually all consume packages from other Services
 - All consume framework packages
 - All consume 3rd party packages.
- Our own nuget feed server
- Our own symbol server with symbols+sources for all published packages
- Three Development teams on two continents 
- Occationally updates to the packages require all consumers to not only update, but to bump their produced packages as well. And so on recursively. For framework packages this might mean almost all packages being bumped and updated in all systems.
- Often parallel development efforts means that we must be able to maintain multiple branches that each requires packages from various Applications and/or frameworks to be bumped and all their dependents must updated.
- All of this needs to be possible to develop and test on a local environment before publishing the new versions of the packages to the shared feed.
- once you have everything working it is extremely important that you can be confident that it will still work when you push all these changes to their various repositories.

Half a decade of experience trying to make this run as smoothly as possible has led us to some conclusions:
- **It is an unreasonable amount of work for us to manage overrides manually each time something changes.**
- **Tracking down the problem if the wrong package is used is an unacceptable amount of work. In order to avoid this we must know that if there exists as official package that package is always used.**

This is a rough outline of how we work to avoid those problems and minimize extra work: 
- All projects have the local feed configured as the fallback source at all times(By placing the local feed after the official feed in the list of feeds that nuget uses from the targets file).
- On each build, create packages and publish them to the local feed (Scripted)
- When a package needs to be updated bump it locally and update it in dependents locally. Do this recursively if required.(Scripted)
- Once everything works locally push everything to CI(Scripted)
- Clean out all local package folders(Scripted)

Hopefully this should help to make our need for "fallback/WIP" sources more clear.

**Comment by mlidbom** [comment]
@theimowski, @forki 
Looking at the pull request I think I need to clarify what my thinking was.
Say we have the packages `A, B, C`
And the feeds set up as: `source O prefer P fallback F`
Then say the actual feeds have this content:
```
P:A
O:A,B
F:C
```
Say that we note A from feed O as AO etc.
Then O as used by paket would in practice look like this:
`USED_FEED: AP, BO, CF`

**That combined feed would be used by all paket operations.**
It might not be implemented in that fashion, but that would be the principle of it as I imagined it. 

This is how nuget behaves when you have multiple sources configured. The first source in the list is the "most prefered". Each package is looked for in the feeds in order. There is no restriction that a package must be restored from the feed it was installed from. This behavior would also be perfectly acceptable to us. **But I assume that there are others for whom the restrictions on restore are important. I would appreciate it if someone could explain why that is :)**

**Comment by OregonGhost** [comment]
I just tried to use the `source X -> source Y` proposed by @theimowski, which is what I would need for our setup, but it seems it has not gotten into the code (or it works differently and is not documented). The use case for this is as follows:

We're working on projects for a certain customer. The customer has his own nuget server, which is only reachable over VPN. Our own build server is not able (or rather, not allowed) to connect to the VPN, so it cannot access the packages. This is not a big deal for classic NuGet, because the build server has to restore packages manually for those, and so can just pass custom sources, pointing to our own nuget server.

I just migrated that project to our build server, though it had been on paket for quite some time now. I added manual single package overrides in paket.local, which is okay for this project (only a single internal nuget dependency), but will get cumbersome for projects with tens of depdendencies. Just overriding the entire source would be the best, especially since doing that would be a one-liner in TeamCity, and I'd love to have a solution that works exactly the same for all projects.

I know that paket.local has originally been made for developer-local overrides of certain packages, but it would be very useful for this as well, if it supported entire server overrides. Actually, a solution where some global configuration on the build server would automatically forward a certain source to our own would be a great thing as well.

**Comment by enricosada** [comment]
Closing.

Fixed by https://fsprojects.github.io/Paket/local-file.html 

Please open new issues to propose enhancements
