### ISSUE TITLE
Need More Informative Error Messages

### ISSUE THREAD

**Issue by Jman420** [fsprojects/Paket#1635]
### Description

When authorization fails for a nuget source the error message provided resembles the following:

```
Paket version 2.62.3.0
Resolving packages for group Main:
 - Our.Package 1.5.2-pre000042-01
Paket failed with:
        There was a version conflict during package resolution.
  Could not resolve package  Our.Package:
   - Dependencies file requested package  Our.Package: >= 1.5 < 2.0
   - Available versions:
     - (1.5.2-pre000042-01, [http://feedUrl/api/v2])

  Please try to relax some conditions.
```

This message in no way indicates that the issue is related to authorization and seems to indicate that a connection was able to be established and that the issue is related to version resolution.  The actual issue here was an invalid username & password combination for one of the sources listed in the paket.dependencies file.
### Repro steps

Simply provide invalid credentials for a nuget source in the paket.dependencies file.
### Expected behavior

I would expect an error message that indicates that the issue is related to authorization or authentication with a source.
### Actual behavior

An error message related to package version resolution is displayed.  This is misleading and uninformative.
### Known workarounds

We have had to write our own PowerShell script to attempt to validate the sources in our paket dependencies files.  This workaround is un-sustainable.
### Related information

An even better fix for this in addition to including more informative error messages would be to provide functionality to validate paket dependencies files.

**Comment by forki** [comment]
mhm in this case the error is not a simple auth issue.

A "normal" auth issue would look like (see 40fc0bc):

    	Could not find versions for package Argu on https://www.myget.org/F...

So this looks like authentication for "getVersions" worked, but not for "getPackageDetails". What nuget server are you using?

**Comment by Jman420** [comment]
Our organization is using myGet as our nuget server.  I believe the permissions are such that anyone in the organization can view a feed, but may not be able to consume it.

**Comment by forki** [comment]
//cc @maartenba sorry to bother you again. is that something that I can simulate with the paket myget account?

**Comment by maartenba** [comment]
What are the exact HTTP requests made? And which one returns an error?

**Comment by forki** [comment]
I have no idea. @Jman420 can you provide a repro sample?

**Comment by Jman420** [comment]
@forki What would you guys need for a repro sample?  I can provide redacted (or blacked out) output, but I doubt I can provide access to any of my organization's feeds.

**Comment by forki** [comment]
I think I would need a similar feed situation on myget with just one package but same auth situation.

**Comment by matthid** [comment]
I think this is resolved with the recent work on error message improvements. While we did not look into this issue in particular I think the error message is improved.

Please test if this is indeed solved.
