### ISSUE TITLE
Referencing portable library

### ISSUE THREAD

**Issue by JonCanning** [fsprojects/Paket#1645]
### Description

Using Auth0 libraries which only has portable targets

[nuspec](https://github.com/auth0/auth0.net/blob/master/nuget/Auth0.AuthenticationApi.nuspec)

Reference is not added to project
### Repro steps

paket add nuget Auth0.AuthenticationApi project MyProject
### Expected behavior

Reference is added
### Actual behavior

Warning shown in console

`Package Auth0.AuthenticationApi contains libraries, but not for the selected TargetFramework net452 in project`

Reference is not added
### Known workarounds

Rename folders in lib to `net45`

**Comment by inosik** [comment]
The `portable45-net45+win8+wpa81` directory doesn't look right to me. As of [NuGet docs](https://docs.nuget.org/create/targetframeworks), there is no `portable45`, only `portable`.

Their project file has the `Profile111` `TargetFrameworkProfile`, which should translate to `portable-net45+win8+wpa81`.

NuGet can't install this package either, BTW.

**Comment by forki** [comment]
Yeah I guess that's the issue.

**Comment by JonCanning** [comment]
I'll raise it with the Auth0 devs

**Comment by inosik** [comment]
Paket still translates the incorrect moniker into this:
```xml
<Choose>
  <When Condition="($(TargetFrameworkIdentifier) == 'WindowsPhoneApp') Or ($(TargetFrameworkIdentifier) == '.NETCore') Or ($(TargetFrameworkProfile) == 'Profile32')">
    <ItemGroup>
      <Reference Include="Auth0.AuthenticationApi">
        <HintPath>..\packages\Auth0.AuthenticationApi\lib\portable45-net45+win8+wpa81\Auth0.AuthenticationApi.dll</HintPath>
        <Private>True</Private>
        <Paket>True</Paket>
      </Reference>
    </ItemGroup>
  </When>
</Choose>
```
Which is wrong, obviously. Should we do something about that?

**Comment by forki** [comment]
I guess it will just go away when the package is fixed ;-)

**Comment by enricosada** [comment]
Closing, fixed in upstream package
