### ISSUE TITLE
Any way to share required paket executable versions with the team?

### ISSUE THREAD

**Issue by davidschwegler** [fsprojects/Paket#1646]
Our project requires the prerelease version of paket to work (needs the ``exclude`` feature). 

It's not a great idea to check in paket.exe to our git, but I'm not sure how else to do it, since paket.bootstrapper.exe will always use the latest stable unless otherwise specified.

Currently my thinking is I have to
1) Check in a version of paket.exe
2) Remove paket.boostrapper.exe 
3) Remove the code in paket.targets that updates it (so auto-restore doesn't clobber it)

or

1) Specify the version to download in paket.targets, and tell the team they'll get paket.exe after they first attempt to build.
2) Hope that people who accidentally run paket.bootstrapper.exe (eg people not on my team) don't waste too much time before asking me why things aren't working.

**Comment by smoothdeveloper** [comment]
can you use `paket.bootstrapper.exe prerelease` or am I missing something?

**Comment by davidschwegler** [comment]
Yeah, you're not quite understanding my question ;) That works on *my* machine, but when my other devs or devs not on my team want to build the code, they need to know to run that command too, and to not ever run paket.bootstrapper.exe like they normally would for other paket projects. 

I work in a fairly large organization with complicated tooling, so we try really hard to limit the amount of weird things you need to know about our build environment.

**Comment by smoothdeveloper** [comment]
Can you change `paket.targets` to give that `prerelease` argument there?

```xml
    <PaketBootStrapperCommand Condition=" '$(OS)' == 'Windows_NT'">"$(PaketBootStrapperExePath)"</PaketBootStrapperCommand>
    <PaketBootStrapperCommand Condition=" '$(OS)' != 'Windows_NT' ">mono --runtime=v4.0.30319 $(PaketBootStrapperExePath)</PaketBootStrapperCommand>
```

Sorry if I'm still missing something

**Comment by davidschwegler** [comment]
Yes, see the second half of the OP. I can do that, but will be crossing fingers that it's not forgotten about or people who aren't on my team and try to build the code don't mess themselves up. 

It's just adds unnecessary complexity. >.<

**Comment by forki** [comment]
Put the bootstrapper command into the build script. You can look here into
the paket source code. We have it in build.cmd and build.sh

**Comment by davidschwegler** [comment]
Thanks for your inputs!
