### ISSUE TITLE
Cross-post, compression regression using paket, mono 4.4

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#1661]
Cross-posted here for reference:
### Compression regression

"Could not fix timestamps in /home/travis/build/Hopac/Hopac/packages/FsCheck/FsCheck.2.2.2.nupkg. Error: The type initializer for 'SharpCompress.Common.ArchiveEncoding' threw an exception."

See https://travis-ci.org/Hopac/Hopac/jobs/127813205#L1114 for a build log w/ details.

Mono 4.4.0.

https://bugzilla.xamarin.com/show_bug.cgi?id=40862

**Comment by forki** [comment]
It looks like the mono issue was solved

**Comment by nosami** [comment]
Installing `libmono-i18n4.0-cil` fixed things for me

**Comment by haf** [comment]
Any docs on these changes, dare I wish? Asked in the bugzilla thread.

**Comment by akoeplinger** [comment]
This should be fixed according to my testing in the Mono 4.4 from the stable channel.

@haf an explanation of the issue can be found in https://bugzilla.xamarin.com/show_bug.cgi?id=39237#c21 (which your bug 40862 was duplicated to).
