### ISSUE TITLE
Paket 3 unconditionally removes all binding redirects from Web.config

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1665]
[WebConfigRepro.zip](https://github.com/fsprojects/Paket/files/251188/WebConfigRepro.zip)

Small Web project attached as a repro. Paket Install command removes all binding redirects from Web.config file. 

I have tried with "redirects: off" and "redirects: on" at the top of paket.dependencies - no change in behavior. 

It also worth nothing to mention that it still forcibly adds a space before XML tag closing.

And one more - Paket changes encoding of Web.config file by inserting BOM symbol in the beginning. 

All those three things are better be left alone, at least when "redirects: off" explicitly specified.

**Comment by forki** [comment]
@mrinaldi @isaacabraham can you please comment on this one? thanks

**Comment by forki** [comment]
I think this could be a result of me removing the --hard parameter.
Maybe we still need it for this

**Comment by forki** [comment]
I think I will bring this back as new parameter `--clean-redirects` (with default no). What do you think?

**Comment by konste** [comment]
Two points:
1. when paket.dependencies says "redirects: off" it means do not touch config files. It does not need any other command line parameter to explain or clarify or enforce its intention.
2. Unless you mark each binding redirect with the comment "added by Paket" (similarly to how you mark assembly references injected by Paket to project files) there is no way to distinguish binding redirects which are safe to remove from those which are not.

**Comment by forki** [comment]
"redirects: off" is not really related this

**Comment by konste** [comment]
Another consideration: since .NET 4.5.1 VS can generate binding redirects pretty much automatically with  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects> in the project file.

**Comment by forki** [comment]
We can't assume VS exists.

**Comment by konste** [comment]
True, but in this case actually msbuild is doing it and we rely on it anyway.

**Comment by forki** [comment]
let me readd the parameter - this changes the default back to paket 2 mode. I think this will work for you.

**Comment by konste** [comment]
Anyway my point is - there are two possible kinds of the problems:
1. Paket edits config files in some unexpected way or
2. Paket does not touch config files when it should

Between those two #2 is much better and safer. If not sure - do not touch it rather!

**Comment by konste** [comment]
--clean-redirects set to Yes would clean ALL redirects again - those added by Paket and those which were not. There is no way to separate them. 
What scenario you consider which would warrant existence of --clean-redirects: Yes?

**Comment by konste** [comment]
I understand that simply --clean-redirects:No would just work for us, but now I'm thinking about potential users confusion about that new option. I doubt it is needed.

**Comment by forki** [comment]
it is needed ;-)
your workflow is only one of many.

**Comment by forki** [comment]
--clean-redirects will remove all redirects that are not set by paket. this is a command you only run once and after that all your redirects are completely under paket's control.

**Comment by konste** [comment]
Meaningful action is not removing all binding redirects altogether. Meaningful action is to try to set binding redirects correctly, which means some may need to be added, some may need to be removed and some may need to be adjusted. That's the functionality I would expect from "redirects: on". When it is set to off I expect Paket to simply bypass opening of any config files.

**Comment by konste** [comment]
-- --clean-redirects will remove all redirects that are not set by paket.

So are they marked somehow?

**Comment by konste** [comment]
Anyway, it is time for me to stop burning midnight oil and hit the bed. I trust you to implement whatever solution you deem correct as long as there is an option to leave config files alone :-)

**Comment by isaacabraham** [comment]
Whoa. Just read the last part of this. @forki are we saying that the new defaults in v3 will remain or has been reverted back to v2?

**Comment by forki** [comment]
It's reverted to v2 behavior. This means manual redirects are only touched
if you specify that parameter.

**Comment by isaacabraham** [comment]
So hard not by default?

**Comment by forki** [comment]
yes. not for this case, but for everything else where hard was used. TBH i think it was unfortunate to use the same parameter for this and the other use case in the first place.

**Comment by smoothdeveloper** [comment]
I'm not following the minute details of the issue, but it seems important to preserve existing bindings, unless those are related to paket managed assembly dependencies, in which case paket should add/update those.

What I'm reading is that @konste had custom bindings that are not related to paket dependencies and that he likes to get those preserved (disregarding `paket.dependencies` or having to call an extra command) and @forki that made a convenience `--clean-redirects` option that will explicitly clean the redirects if user wanted to do that.

I'm not seeing how that will address @konste issue though, he'd expect paket to not touch any redirect (he has many entered manually) besides those related to `AWSSDK` (and transitive dependencies) since it is the only reference he has in his project.

**Comment by forki** [comment]
Yes we don't touch automatically anymore.

**Comment by smoothdeveloper** [comment]
@forki gotcha thanks! :+1:
