### ISSUE TITLE
Feature request: ability to replace a Nuget package by a local build of the component

### ISSUE THREAD

**Issue by xlegalles** [fsprojects/Paket#1672]
Hi, 
Let me try to explain quickly our problem. In my company, we work with at least 3 solutions:
- Solution A contains tens of core projects used by mainly all final products
- Solution B contains tens of projects more businesss oriented and still shared by several final products. B can use A components.
- Finally, Solution C is a final product and use A and B through Nuget packages.

When we want to debug A or B components from the C solution, we can of course access PDB through a symbol server. But things become more painful when we need to solve an issue in A or B, diagnosed from C: of course, we make a UT in the source solution to reproduce and solve the bug but most of the time, we want also to test it directly from the C solution. Currently, we use some PS scripts to build locally the Nuget packages for A and/or B and update them in the C solution. This can be a very long process!

The idea would be to use Paket to replace those PS scripts. Because Paket can update project files, it could replace the path from a Nuget package folder to the build output which contains the corresponding dlls. For instance, you would give the build output folder from the command line and Paket could check for any dependency to verify if it takes the one from this path (if present) or the default one from the package folder. Just the time to test: any install/update would then restore things according to the paket.dependencies.

I hope i's clear enough.

Thanks

**Comment by forki** [comment]
take a look at https://github.com/fsprojects/Paket/pull/1636

**Comment by forki** [comment]
is that what you mean?

**Comment by xlegalles** [comment]
Yes, I think so. If I understand all the story, we would be able to define a paket.local and redirect a nuget source to a folder? It would be perfect.

**Comment by theimowski** [comment]
exactly, it's a work in progress. have a look at [this integration test scenario](https://github.com/theimowski/Paket/blob/dev_source_override/integrationtests/scenarios/i001633-dev-source-override/before/paket.local#L1)

**Comment by forki** [comment]
it's now merged into beta
