### ISSUE TITLE
Paket seems corrupt NuGet zip files causing NuGet Pack to fail

### ISSUE THREAD

**Issue by StuartBaker65** [fsprojects/Paket#1673]
### Description
I cannot create a NuGet package using structuremap.automocking as a dependency. The NuGet Pack command fails
See: #https://github.com/NuGet/Home/issues/2718

### Repro steps

1. Created a simple console app
2. Added a Console.WriteLine("Helllo World");
3. Built and ran " nuget pack" with a default spec file.
It worked, "pack"ing with old and new versions of nuget.exe
4. Add a NuGet reference to structuremap.automocking (version is irrelevant)
This brings in structuremap and RhinoMocks as dependencies.
Build and run: Works
5. NuGet pack fails with error.

It's worth noting that this is with any version on the library, not just the most recent and is independent of the libraries dependencies.
- If I remove the dependencies from the package, but not automock ref; it fails
- Only when that specific line from packages.config is removed does the pack command work.

### Expected behavior
My library should be packed appropriately creating a NuGet package

### Actual behavior
System.Xml.XmlException: Unrecognized root element in Core Properties part. Line 2, position 2

### Known workarounds
I have extracted the libraries and repackaged them using NuGet package manager

### Related information 

* Windows 7 Enterprise
* .NET Runtime 4.6

**Comment by forki** [comment]
something in this error report looks strange. Can you please clarify where you meant paket pack and where nuget.exe commands?

**Comment by StuartBaker65** [comment]
apologies.
It appears that the author of strcuturemap.automocking has used Paket to create the NuGet package that my project consumes and sourced from nuget.org.

In my organisation we use the NuGet pack command to create Nuget packages and my project is therefore dependent on the above library. It compiles and executes, but when I issue the nuget pack command I get the xml exception raised.

Thinking this was NuGet issue I raised an issue which toddm investigated and discovered that paket appears to have corrupted the nupkg file. I don't know how he ascertained this, but he was able to reproduce the issue as described. The fact that it's not a single library version causing the issue would point (circumstantially at least) to an issue with Paket.

**Comment by forki** [comment]
I think it's built with some older paket version see https://github.com/NuGet/Home/issues/2718#issuecomment-217908567
