### ISSUE TITLE
Useless include files created by generate-include-scripts

### ISSUE THREAD

**Issue by ChrSteinert** [fsprojects/Paket#1675]
### Description

If for a NuGet package the requested framework is not present, but a GAC using is specified, the new `generate-include-scripts` command generates include files for this framework version with only the GAC usings inside.
### Repro steps
1. Set up a "clean" Paket directory (following the steps from the getting started page).
2. Use the following paket.dependencies file:

```
source https://nuget.org/api/v2

nuget EntityFramework
```
1. Generate include scripts via the command `paket generate-include-scripts framework net2`.
### Expected behavior

No include scripts and no folders had been generated as the Entity Framework package does not support NET 2.0
### Actual behavior

Include scripts has been generated with the following content:

```
#r "System.ComponentModel.DataAnnotations" 
printfn "%s" "Loaded entityframework"
```
### Related information
- Running Pre-release 3.0.0-beta036

**Comment by matthid** [comment]
Hm. I'm not sure if it is always safe to assume that a missing reference means the package doesn't support the current framework. It might be a meta package with only references. Or it just doesn't need any reference for the current framework.

The `EntityFramework` has an unconditional framework reference to `System.ComponentModel.DataAnnotations` therefore we generate the script, even when net2 is specified. I would say this works as intended...

**Comment by smoothdeveloper** [comment]
@matthid / @ChrSteinert I think the litmus test is after including 

```fsharp
#r @"paket-files/include-scripts/frameworkid/include.packageid.fsx"
```

Can I use the references properly from FSI the same way I'd be able to use it if I manually added all the references manually for the specified framework?

This is the happy path, if the reference has no assembly to load at all for selected framework, we expect to have no script (I think we have a test case for this already), but if there is at least still one valid reference (like in this case) or other nuget packages to load, it makes sense (for me) to have it referenced, in this case we loaded EntityFramework to the best extent possible for net2.

Although I'm not sure DataAnnotations is OK on net2, maybe we should figure out if a framework reference is valid for target framework, I don't know if Paket has this information available nor how we could get it deterministically.

**Comment by ChrSteinert** [comment]
Is there any known package where this makes sense for this specific package? If there is, we should close this issue then.

**Comment by ChrSteinert** [comment]
Paket 5.138 does not show this behaviour. Let's close this ;)
