### ISSUE TITLE
Init or Install scripts are ignored by include scripts

### ISSUE THREAD

**Issue by ChrSteinert** [fsprojects/Paket#1679]
Looking at NuGet packages, like Entity Framework, there sometimes are init or install scripts in the packages tools folder. Currently, they are completely ignored.

In general, it might does not make so much sense to "somehow" execute them, as they 
a) rely on powershell
b) most probably open only a readme.txt anyway.

This does not "feel" like it's Pakets intention anyway. But something might be figured out. 

Maybe this is more related to the Visual Studio Paket plugin.

**Comment by inosik** [comment]
http://fsprojects.github.io/Paket/faq.html#Does-Paket-run-install-ps1-scripts

The problem with the PowerShell scripts is that they depend on running inside Visual Studio, which Paket doesn't. The VS extensions does, but it's just a GUI for Paket.Core and doesn't actually extend any of it's functionality.

Additionally, we don't have PS on non-Windows OSes.

**Comment by forki** [comment]
PS scripts are not supported. AFAIK even nuget is get rid of this
unfortunate idea.

**Comment by inosik** [comment]
Their [blog](http://blog.nuget.org/20151008/NuGet-3-What-and-Why.html#powershell-install-and-uninstall-scripts) says they still execute `init.ps1`, which is strange IMHO. No idea what they do outside of VS, or if they do it at all.

**Comment by forki** [comment]
Yeah or on mono ;-)
Just don't trust that statement...

**Comment by ChrSteinert** [comment]
So let's close this?

**Comment by matthid** [comment]
Yep lets close this. Paket always ignored Powershell scripts, which is IMHO the correct thing to do.
