### ISSUE TITLE
Generating include scripts on restore

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#1681]
Currently we generate include scripts only with the explicit command.
Maybe we should generate the scripts on restore -> such that we can use them in a regular FAKE build script without the need to edit all exiting `build.cmd` and `build.sh` files.
See https://github.com/fsprojects/Paket/pull/1619 for context.

Please discuss.

**Comment by smoothdeveloper** [comment]
@matthid @forki mentionned he'd like `generate-include-scripts` to call `restore` as well.

I think this is relevant to this proposal but not sure how to handle recursive dependency.

One concern to do it on restore is framework identification, but you mentioned we should generate for all frameworks (maybe we should get the list of all relevant frameworks from the nuget packages themselves?).

**Comment by matthid** [comment]
> @matthid @forki mentionned he'd like generate-include-scripts to call restore as well.

Yes because it is a requirement and there is no reason to fail when we can do it on-demand.

> but not sure how to handle recursive dependency.

What do you mean?

> One concern to do it on restore is framework identification, but you mentioned we should generate for all frameworks 

paket knows the frameworks already. It should work exactly how paket already generates references in project.fsproj files. You can limit frameworks with http://fsprojects.github.io/Paket/dependencies-file.html#Framework-restrictions
IMHO this would be a seamless integration.

**Comment by smoothdeveloper** [comment]
> What do you mean?

Sorry I mean `generate-include-scripts` -> `restore` (what @forki mentioned) and `restore` -> `generate-include-scripts` (what this issue is about).

In any case, I do agree we should implement script generation on restore, maybe also at later point we can add something to `paket.dependencies` grammar to be able to specify the script type needed (all, csx, fsx).

**Comment by matthid** [comment]
Ah I see. In my world of thought my argumentation is this: If we add it to restore we could remove the 'generate-include-scripts' command. Configuration via paket.dependencies seems to be the logical consequence...

of course there is this argument against it that this has nothing to do with core package managment and therefore nothing should be added to the dependencies file. On the other hand paket currently has no extension points to somehow do the same outside of the core...

hence this thread to see what people think. IMHO once included it might be useful enough for some people such that it is reasonable to be included in the core. And this feature popped up several times in the past, might be a hint that it should to be on by default (ie happen on restore)...

**Comment by matthid** [comment]
We have this now, just tested it and found https://github.com/fsprojects/Paket/issues/2372
