### ISSUE TITLE
Q: Can I have a single paket.dependencies file for multiple solutions?

### ISSUE THREAD

**Issue by mmisztal1980** [fsprojects/Paket#1685]
As title says, I'm working in a project consisting of 30+ solutions. Keeping track of package versions is difficult and I believe paket would be a fantastic tool to help with that. I'm wondering if it's possible to have a shared .dependencies file that can be shared across the solutions?

**Comment by forki** [comment]
Yes. Dependencies files are per repository, not per solution.

**Comment by mmisztal1980** [comment]
Do I need to initialize paket in some special way then (last I checked the .depednecies file ended up alongside the .sln file) ? Can you give me an example?

**Comment by forki** [comment]
just put it in root of the repo. same as here in https://github.com/fsprojects/Paket

**Comment by forki** [comment]
sln doesn't need to be alongside paket.dependencies file. In fact paket doesn't even know abould sln files.

**Comment by mmisztal1980** [comment]
in that case, how does Paket know where to look for it? does it work it's way up to repository root?

**Comment by forki** [comment]
Yes it walks up until it finds one. But usually you just run paket commands
in root of repo and put deps into root and all is well

**Comment by mmisztal1980** [comment]
I'll try that out, thanks ! :)
