### ISSUE TITLE
[v3] paket.local should support local sources with build command

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#1690]
[Ripple](http://darthfubumvc.github.io/ripple/) had a nice feature called "local ripple". Given a matching project tree ripple was able to build all projects/nugets in the correct order and copy nupkgs to the correct locations.

I can see that one could use paket.local for something similar, even if only on a single level (ripple would build a tree of dependent projects). I would find it very useful if I could specify a `build` tag (?) for local sources. I haven't looked at the source, just reading [the docs](http://fsprojects.github.io/Paket/local-file.html).

```
nuget Argu -> git file:///c:\github\Argu feature_branch build:"build.cmd NuGet", Packages: /bin/
nuget Fake -> source c:\github\FAKE build:"build.cmd NuGet", Packages: /bin/
```

**Comment by forki** [comment]
// @theimowski

**Comment by theimowski** [comment]
You can have local sources with build command, but then the source acts as [Git-repositories-as-NuGet-source](http://fsprojects.github.io/Paket/git-dependencies.html#Using-Git-repositories-as-NuGet-source) - is this what you meant? 
`nuget Faket -> source ...` is assumed to work only if the target dir already contains build nupkgs (example use case: sharing built nupkg in team)

**Comment by agross** [comment]
Yes, I think this is what I meant. To verify:

My initial question is about the workflow when developing locally. I think it would be great if you could run Paket from the "superproject" (the project using another lib/nupkg) and the subproject's nupkgs are automatically created when you run Paket with a `paket.local` file. For this to work I don't want to compile each subproject myself, Paket should rather do the job of creating the subproject's nupkg by running a custom `build`.

Is that possible with the current implementation?

**Comment by theimowski** [comment]
Yes, I'm planning to make a blog post on the exact workflow. Till then you can have a closer look at the new git dependency feature that comes with paket 3 - the workflow I'm thinking about is built in top of that feature

**Comment by theimowski** [comment]
Here's the blog post: http://theimowski.com/blog/2016/05-19-paket-workflow-for-testing-new-nuget-package-before-release/index.html 
Please let me know if this makes things a bit more clear

**Comment by agross** [comment]
@theimowski :+1: Thanks, this was exactly what I was referring to :-)
