### ISSUE TITLE
Paket Restore and out of date paket.exe

### ISSUE THREAD

**Issue by cgravill** [fsprojects/Paket#1698]
### Description

I've been using Paket on a repository. I used Paket Restore and there are people using it indirectly unawares. This has generally gone really well. However, I used a newer feature (groups) that wasn't in their bootstrapped version of Paket. It's a simple fix - delete their paket.exe - but they didn't know to do that.

Could the paket version get written to e.g. paket.lock then paket restore knows to invalidate paket.exe and bootstrap a new one?
### Expected behavior

Use new Paket features, automatically install new Paket on people who need it.
### Known workarounds

Delete paket.exe, (or commit it to source control)
### Related information

Windows, Mac and Ubuntu
Recent paket.exe for me, 6-8 months old for other users

**Comment by forki** [comment]
The usual workflow in many projects is to call bootstrapper at the
beginning of the build command (before restore). That ensures you always
get latest paket.exe.

**Comment by cgravill** [comment]
I can achieve that by removing ```AND !Exists('$(PaketExePath)')``` from the paket.targets. Is that a recommended approach? Not really an issue but seemed a waste to make a web request per project build.

**Comment by forki** [comment]
ah you don't have external build process? You just build from within VS?

**Comment by cgravill** [comment]
It's a mixture but some scientists for some of our tools just use VS. I much prefer using Paket for the VS projects I create for them as well.

**Comment by isaacabraham** [comment]
@forki the Paket target doesn't call bootstrapper though does it? And if it does - you'd need to be able to supply an argument to target to say whether or not to use prerelease paket I guess.

**Comment by forki** [comment]
no bootstrapper is not called.

**Comment by forki** [comment]
maybe https://github.com/fsprojects/Paket/pull/1697 could help.

**Comment by forki** [comment]
#1697 is now merged into v3. so a call to the bootstrapper could be added to paket.targets

**Comment by cgravill** [comment]
Great, this works perfectly for me. In case anyone needs it, I did it in a very direct crude way in paket.targets i.e.

add

```xml
<PaketBootStrapperCommand Condition=" '$(OS)' == 'Windows_NT'">"$(PaketBootStrapperExePath)" $(PaketBootStrapperCommandArgs) --max-file-age=1200</PaketBootStrapperCommand>
<PaketBootStrapperCommand Condition=" '$(OS)' != 'Windows_NT' ">$(MonoPath) --runtime=v4.0.30319 $(PaketBootStrapperExePath) $(PaketBootStrapperCommandArgs) --max-file-age=1200</PaketBootStrapperCommand>
```

I don't want to have to remember to put it in all the Visual Studio projects that use Paket.

and drop  `AND !Exists('$(PaketExePath)')` from

```xml
<Exec Command="$(DownloadPaketCommand)" IgnoreStandardErrorWarningFormat="true" Condition=" '$(DownloadPaket)' == 'true'" />
```

I might tidy it up to a KeepPaketUpToDate later.

**Comment by enricosada** [comment]
Closing, bootstrapper is added to target file too
