### ISSUE TITLE
`paket install` fails due to JSON parsing error

### ISSUE THREAD

**Issue by vain0** [fsprojects/Paket#1699]
### Description
Please see repro steps.

### Repro steps
Locate `paket.exe` (from [Paket latest release](https://github.com/fsprojects/Paket/releases/latest)). Then run these commands:

```bat
paket init
echo github vain0/abdata >> paket.dependencies
paket install
```

(Note at **2016/May/24 07:55 JST**: I use an alias that "paket=.paket\paket.exe". So please read them as ``.paket\paket.exe init`` and ``.paket\paket.exe install``.)

And I got this error:

```
Paket failed with:
        After parsing a value an unexpected character was encountered: s. Path 'files[7].patch', line 1, position 10814.
```

### Known workarounds

``github vain0/hsp_green`` also invoked a similar error. Then I put `paket.dependencies` next to "src/all.hsp" (a file in the repository) and rewrite my `paket.dependencies` like this.

```
github vain0/hsp_green src/all.hsp
```

Then paket first fetches "src/all.hsp", and then it fetches all files in the repository due to the transitive dependency written in that `paket.dependencies`.

### Other cases
* Failure cases:
  * ``github/zeo_five_hsp`` (contains no files related to Paket)
    * Error message: Bad JSON escape sequence: \・. Path 'files[9].patch', line 1, position 3 5330.
  * ``github/speed_fs`` (contains paket.dependencies in the root)
    * Error message: After parsing a value an unexpected character was encountered: s. Path 'files[0].patch', line 1, position 5073.
* Success cases:
  * ``github vain0/git_edit`` (which contains no files related to paket), ``github vain0/rss_reader_fs` (which contains paket.dependencies), etc

### Related information
* Windows 10
* .NET framework 4.6
* Paket 2.65.2.0

**Comment by vain0** [comment]
This is because github API returns broken JSON containing non-unicode text (SHIFT_JIS encoding). (Such as <https://api.github.com/repos/vain0/hsp_green/commits/master>)
I don't know whether Paket should workaround it or not.

**Comment by smoothdeveloper** [comment]
@vain0 I assume paket doesn't handle json parsing itself but depends on 3rd part library (I believe Newtonsoft.Json), maybe you should inquire there or check with github what can be done with the json itself?

**Comment by vain0** [comment]
I see. Thank you for your suggestion.

**Comment by forki** [comment]
I think I still want to understand what's going wrong here.

**Comment by forki** [comment]
Paket install on a dependencies file conatinaing

    github vain0/abdata 

worked for me. Can you create a zip that reproduces?

**Comment by vain0** [comment]
Okay, here you are.

[repro_1699.zip](https://github.com/fsprojects/Paket/files/279294/repro_1699.zip)

I've just now confirmed that ``paket install`` produces the same error as I wrote above.

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/15501708/3377a88a-21af-11e6-9c8b-224617616e4f.png)

still can't reproduce with latest paket.

**Comment by vain0** [comment]
Mysterious. Only my environment...?

**Comment by forki** [comment]
I wonder if someone else can reproduce. 

Whatever the server returns to you is probably invalid json, but for me it returns the right thing.

![dog](https://cloud.githubusercontent.com/assets/57396/15501928/f98230b2-21b0-11e6-8ecf-cbbaafc69a58.gif)

**Comment by vain0** [comment]
Hmm... Let's wait for someone else try the repro.

**Comment by forki** [comment]
Maybe there is a firewall blocking it?

**Comment by vain0** [comment]
I've tried to `paket install` with Windows Firewall disabled but the same error occurred.

**Comment by vain0** [comment]
I asked my twitter account's followers to do repro steps and one could: <https://twitter.com/htid46/status/735076020584251394> (written in Japanese)

According to them, because Windows's standard char code is shift_jis (? I don't understand yet.)

**Comment by forki** [comment]
Can you please tweet same thing in English? Will retweet

**Comment by vain0** [comment]
Tweeted: https://twitter.com/ue_dai/status/735080574314905601 and https://twitter.com/ue_dai/status/735081112205025280 .

Their note: https://gist.github.com/hafuu/1e6cf81c0d08636ee86b5d0de3c55bb4

And they solved this issue immediately. I'll open a PR instead of them.

**Comment by vain0** [comment]
I forgot to say I built the PR version Paket and confirmed it succeeded to `paket install`.

**Comment by forki** [comment]
great work. thanks

**Comment by smoothdeveloper** [comment]
https://twitter.com/harrisj/status/734857735393714176

> When do you talk to your children about character encodings?
