### ISSUE TITLE
paket.local - cache invalidation

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#1700]
### Description

When overriden package is copied to packages folder, it stays there until either it's version gets updated or restore is invoked with `--force`

### Repro steps

1. Add override for a package to `paket.local`
2. Run paket restore
3. Remove the override from `paket.local`
4. Run paket restore once again

### Actual behavior

Running paket restore for the second time after removing override from `paket.local`  doesn't bring back the original package - caching logic treats the overriden package as the correct one

### Expected behavior

The question is whether actual behavior is justified? 
If someone wants the original package back, she can always add `--force` to paket restore, however this might not be very convenient, and should be somehow mentioned in docs.
Other option is that she pulls newer version of the dependent package when it's released - but again in some cases this might not be possible.

If we however want to invalidate that overriden package - then how to do that? The only idea that comes to my mind is by leaving some kind of a trail in file-system, e.g. empty `paket.overriden` file inside packages/package directory. Then restore would search for those files and automatically set `--force` only for those packages that have that file.

What are your thoughts?

**Comment by forki** [comment]
Yes please add a file into the packages folder that marks the packages as
local

**Comment by theimowski** [comment]
ok will do
