### ISSUE TITLE
BUG?: update with any of the --keep-?? flags doesn't honour content:none in paket.dependencies

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket#1701]
### Description

Not sure if it's a bug, expected behaviour or something else.  But if I do a `paket update --keep-major` when I have specified content:none for a package in paket.dependencies, I end up with the contents being copied to the project folder and the csproj being updated.  Running `paket update` again removes the files as expected.

### Repro steps

Please provide the steps required to reproduce the problem

1. create an empty solution with an bare class library project
2. `paket init`
3. `paket add nuget bootstrap project <projectname>`
4. note the addition of the content files to the project (folders contents, fonts, scripts)
5. edit paket.dependencies and place `content:none` next to bootstrap
6. `paket update`
7. note the contents have been removed from the project
8. `paket update --keep-major`
9. note the contents are back.

### Expected behavior

at step 9, the project **should not** contain the contents of the bootstrap package

### Actual behavior

It does

### Known workarounds

update the package.references file to include `content:none` for the package as well

### Related information 

* Operating system: Windows 7
* Branch : paket version 2.65.2.0
* .NET Runtime, CoreCLR or Mono Version: 4.5
* Performance information, links to performance testing scripts

**Comment by forki** [comment]
can you please send me the project after step 7? I can't reproduce

**Comment by pms1969** [comment]
I'll have to do it on my way home @forki .  Corporate policy dictates. :-s  Should be about an hour and a half.  Direct to your email ok?

**Comment by forki** [comment]
Yes that would be great. Or put it here as a zip. Both works for me. Thanks

**Comment by pms1969** [comment]
ok, can add as zip, hadn't spotted that.
[TestPaket.zip](https://github.com/fsprojects/Paket/files/277668/TestPaket.zip)

**Comment by forki** [comment]
Ok I can reproduce with that. thanks

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/15475312/b8af454a-2109-11e6-85b4-e4f063800c05.png)

should be flying again

**Comment by isaacabraham** [comment]
lol. genius.

**Comment by forki** [comment]
Puhh at least someone understood. ;-)

**Comment by pms1969** [comment]
Excellent work.  Thanks.  And yes, I think it was understood all round. ;-)
