### ISSUE TITLE
xunit.runner.visualstudio 2.1.0 result in 2.1 in the package folder name when restoring

### ISSUE THREAD

**Issue by ltvan** [fsprojects/Paket#1708]
I use this in my paket:
`nuget xunit.runner.visualstudio version_in_path: true`

The first `paket install`, it results in `xunit.runner.visualstudio.2.1.0` in `packages` folder and the .csproj refers to this folder.

The `paket restore`, it results in `xunit.runner.visualstudio.2.1` in `packages` folder and it breaks the references in .csproj.

The second `paket install`, it tried to update the reference to `xunit.runner.visualsudio.2.1`, which is an inconsistant behavior with the first install.

**Comment by forki** [comment]
Are you using latest paket.exe?

**Comment by ltvan** [comment]
Yes. I'm using the latest stable version (download by paket.bootstrap.exe)

**Comment by forki** [comment]
I can't reproduce yet.

Can you please create a zip which reproduces the situation just before the second paket install breaks it for you? I will then take a look and try to fix asap.

**Comment by ltvan** [comment]
You can see step by step here:
https://github.com/ltvan/PaketWithXUnit

Env: Windows 10, VS2013, VS2015

I run `paket install` from command line, version 2.66.4.0.

At the third commit, if I delete packages folder and call `paket restore`, `xunit.runner.visualstudio.2.1` will be restored and of course, the .csproj still refer to 2.1.0.

Note that I pinned version 2.1.0 just in case xunit has any upgrade. In my project I don't pin the version, the result is the same.

**Comment by forki** [comment]
OK thanks. I fixed that and paket will not remove the trailing zero in the lock file when version_in_path is true.

In order to fix your project:
* update to paket 2.66.5
* manually fix the paket.lock file to use 2.1.0
* rerun paket install

**Comment by ltvan** [comment]
Thank you very much for your quick fix.
