### ISSUE TITLE
Groups with different sources resolves the wrong packages

### ISSUE THREAD

**Issue by franknarf8** [fsprojects/Paket#1711]
### Description
We are working with multiple Nuget streams (Release, Debug, ...) and at one point we want to download a versions of the package from both feeds and put them in separate groups. They are named the same way and may have the same version number, but they have different content.

We have a paket.dependencies file that looks like this : 

```
source TestA
nuget Test

group Cumulus.1.0
    source TestB
    nuget Test
```

Thing is, when we try to resolve this with 'paket update' it installs the same version in both groups. (the version from the TestB feed)

### Repro steps

Just run 'paket update' on this repo at this point in time and you should see the problem. (One of the Test.nupkg contains a file 'a.txt' and the other one contains 'b.txt'; paket update resolves both packages to the one contianing 'a.txt') (I also tried it with different versions, and they still do not resolve properly)
https://github.com/franknarf8/paket-issue-repro/tree/Bug_GroupStreamResolving

### Expected behavior

I would expect that each groups are resolved completely independently; feeds and all.

### Actual behavior

If a package is found on another feed, another feed that has no versionning constraints may simply use that package even if the feed is different.

**Comment by forki** [comment]
thanks for the excellent repro sample.
Should be fixed now.
