### ISSUE TITLE
Paket does not respect pre-release constraints

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#1714]
### Description

The pre-release constraints does noe work as described by the documentation

### Repro steps
Use the following `paket.dependencies` file to reproduce the problem.

```
// Using paket version 2.66.6.0

source https://www.nuget.org/api/v2

// This installs the last release version
//nuget Paket

// ==> paket.lock
//NUGET
//  remote: https://www.nuget.org/api/v2
//  specs:
//    Paket (2.66.6)

// This should not install the pre-release version
// nuget Paket >= 3

// paket.lock
// NUGET
//  remote: https://www.nuget.org/api/v2
//  specs:
//    Paket (3.0.0-beta060)


// This should install the rc, but not the beta version
nuget Paket >= 3 rc

// paket.lock
// NUGET
//  remote: https://www.nuget.org/api/v2
//  specs:
//    Paket (3.0.0-beta060)
```

**Comment by forki** [comment]
there is no paket 3 rc!?

**Comment by trondd** [comment]
I know, but then I would expect it to fail, and it doesn't

**Comment by forki** [comment]
there is some addtional stuff happening around prereleases. This is in place because most nuget and myget package combinations are have big issues when it comes to prereleases. 

But I agree in this specific case we should probably don't enable this magic. I will take a look

**Comment by forki** [comment]
This is now fixed.

**Comment by trondd** [comment]
The problem with testcase 2 still remains: It still install pre-release version. My expectations is that Paket would only install pre-releases when asked too, and otherwise fail.

**Comment by forki** [comment]
That one is actually much harder to decide. 
As I already said there are many situations where people will be broken if we don't be careful. 

But I assume we can do the following: if a version restriction is given in deps file then we should not use prereleases. If no version restriction is given then we need to keep everything as we had.

**Comment by forki** [comment]
can you please retest?

**Comment by forki** [comment]
just to confuse your tests: I released a Paket 3.0 RC1 ;-)

**Comment by trondd** [comment]
Nice! This is much better. I would still consider 3.0.0-rc001 a pre-release, but I understand the backward compatibility argument.

**Comment by forki** [comment]
It is a prerelease. What do you mean?

**Comment by trondd** [comment]
Sorry! My mistake, I accidentally tested with an old version. Works like a charm.
