### ISSUE TITLE
Paket CLI in Chocolatey?

### ISSUE THREAD

**Issue by kostrse** [fsprojects/Paket#1715]
Hi, I was curious, why Paket still not present in Chocolatey?
Is it because no one just had time to do it, or there're any fundamental problems?

it would be very handy to have it in PATH on my machine so I could easily run it from any folder, like
`paket init` or `paket auto-restore` on a fresh repo without need to manually download and copy executables every time.

**Comment by forki** [comment]
did you see https://chocolatey.org/packages/Paket.PowerShell/2.66.8?

**Comment by kostrse** [comment]
Yes, saw it.

`Paket.PowerShell` probably is interesting on its own, but it is not the exactly same `paket.exe` which you could expect to have when you run the `paket` command in terminal.

Today's convention is to put `paket.sh`/`paket.cmd` wrappers in the repo root for convenient access to the paket command and it's useful for CI.

But for user experience it could be more handy to have the `paket.exe` accessible system-wide from PATH... so you could run `paket` for your new project even before you have downloaded/copied the paket.exe/paket.cmd etc scaffolding. into the repo.

**Comment by isaacabraham** [comment]
How would this work in the case of (frequent) updates to Paket?

**Comment by kostrse** [comment]
The same way as other repo-centric build tools do (**gulp** for JavaScript, **sbt** for Scala, **gradle** etc.).

They all can be installed system-wide from a package manager (and may be outdated on your machine) and also need to be present in your repo.

In practice, your package manager mitigates the problem of updates,  even if you are one week behind the latest version, you probably run `apt-get update`/`brew update`/`choco update` on your machine sometimes so you catch up with newer versions sooner or later.

Tools like sbt and gradle go further and check presence of the the tool in the repo and execute it instead. So you're consistent with your repo/CI build configuration. But this is not critical to start with. In future Paket could also have such hook implementation.

Even If I run `paket auto-restore` with system-wide outdated version of Paket, I get the most up to date bootstrapper and the bootstrapper in turn downloads most up to date version of `paket.exe` for build.

**Comment by cloudRoutine** [comment]
I also have a systemwide version of paket on my PATH and have found it quite useful. Since the bootstrapper is on the path too it's easy to update. Choco also makes it simpler to include paket as part of a set of packages to quickly setup a dev environment.

**Comment by johnypony3** [comment]
i made a chocolatey package for 3.53.3 it is currently awaiting moderation. when i tried to actually use it i realized that auto restore does not work. when the functionality is invoked from within visual studio the packages are installed to the users directory.
it would work for a build server but since its required for vs its useless...

**Comment by enricosada** [comment]
Closing,

dupe and discussion in https://github.com/fsprojects/Paket/issues/2179
