### ISSUE TITLE
Paket conflicts with pinned prerelease version

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1716]
### Description

When I want to update a dependency, paket stops with a version conflict. This seems to be introduced with 2.66.8

### Repro steps

1. The minimal dependency file
nuget npgsql 2.2.5-custom
nuget CustomPackage 

The custom package has a dependency on npgsql >= 2.0 < 3.0 and npgsql is a custom build version by us.

2. `paket install` works fine

3. `paket update` works fine as well

3. `paket update nuget CustomPackage` crashes with the following error message:

````
Paket failed with:
        There was a version conflict during package resolution.
  Resolved packages:
   - CustomPackage 1.0.10047
  Could not resolve package npgsql:
   - Dependencies file requested package npgsql: 2.2.5-custom
   - CustomPackage 1.0.10047 requested package npgsql: >= 2.0 < 3.0

  Please try to relax some conditions.
````

### Expected behavior

the dependency resolution should end without any error message as the npgsql package is in the scope of the dependency constraint of the CustomPackage

### Actual behavior

Error message as above.

### Known workarounds

Downgrading to paket 2.66.7

### Related information 

* Windows
* stable
* .NET Runtime

**Comment by forki** [comment]
Can you please create an zip with the repro sample?

**Comment by Stift** [comment]
Ok. Sent it to you via email.

**Comment by forki** [comment]
mhm I did not get any mail

**Comment by forki** [comment]
can you upload it here?

**Comment by Stift** [comment]
security scan of gmail took the mail down. :cry: 
I'll send a link again. Cannot post it here, because it's partially internal.

**Comment by forki** [comment]
please retry

**Comment by Stift** [comment]
seems to work for. thx
