### ISSUE TITLE
Bootstrap on linux

### ISSUE THREAD

**Issue by pazof** [fsprojects/Paket#1721]
### Compilation of Paket.exe on linux

I'm using Debian wheezy, and the alpha channel for mono. I'm trying to use Paket.exe, it looks like it was downloading something, but the package dir remains empty, and not a package is being downloaded.
This also occurs when trying to compile Packet, from Git or from the release tarball 2.66.9 
```
paul@lua:~/Downloads/Paket-2.66.9$ mono .paket/paket.bootstrapper.exe prerelease
Checking Paket version (prerelease requested)...
Paket.exe 3.0.0-rc002 is up to date.
```

### Repro steps

1. try and compile Paket-2.66.0

### Expected behavior

The compilation starts, not complaining about something wrong while downloading dependencies.

### Actual behavior

No package restoration. project.lock is generated, with a 'build' empty dir

### Known workarounds

none
[build-log.zip](https://github.com/fsprojects/Paket/files/310044/build-log.zip)

### Related information 

* Operating system : Debian 8.5
* .NET Runtime, CoreCLR or Mono Version : mono version 4.4.0

* highly available host

**Comment by forki** [comment]
the log says: Message: The type initializer for 'SharpCompress.Common.ArchiveEncoding' threw an exception.

this seems to be a mono issue. /cc @nosami

**Comment by nosami** [comment]
@pazof Do you have libmono-i18n4.0-cil installed? See https://bugzilla.xamarin.com/show_bug.cgi?id=40862

**Comment by pazof** [comment]
no, I didn't ...

**Comment by pazof** [comment]
and, it fixes some downloads, not all ... now I'm getting a SIGABORT :-) so many thanks ... I'll try and find out what's wrong with this.

**Comment by pazof** [comment]
Indeed, I hadn't it installed.
