### ISSUE TITLE
Feature Request: Add Batch option for add-credentials

### ISSUE THREAD

**Issue by pauxus** [fsprojects/Paket#1722]
Currently, add-credentials always asks credentials from the console.

In our developer machine setup, we automatically configure configuration files for various build systems / tools like maven, gradle, npm, nuget all using the same user credentials.

We do this by reading the credentials from the user once and after that executing config commands of the tools in sequence (npm config auth, nuget source...)

However, Paket does not allow to specify username and password directly on the command line, which makes it a lot harder to automatically configure it using that system.

I suggest providing a --batch flag:

paket config add-credentials <url> --batch <username> <password>

alternatively: 

paket config add-credentials <url> --username <username> --password <password>

**Comment by forki** [comment]
Yes this sounds doable.
I'm making this up-for-grabs
