### ISSUE TITLE
3.1.7: "paket install --log-file" blows up right away with IndexOutOfRangeException

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1743]
Documentation shows Filename parameter for --log-file command line switch as optional, but attempt to omit log file name causes Paket to break right away with IndexOutOfRangeException.

**Comment by forki** [comment]
You mean if you don't provide a name but still set the switch?

**Comment by konste** [comment]
Yes. From the doc it looks perfectly legal, although it does not tell what the default log file name is going to be.

**Comment by forki** [comment]
@eiriktsarpalis is this something Argu could handle?

**Comment by forki** [comment]
sorry this is not coming from argu. fixing it now
