### ISSUE TITLE
find-packages doesn't appear to do anything with a custom feed

### ISSUE THREAD

**Issue by michael-baker** [fsprojects/Paket#1744]
### Description

Using `find-packages` with a custom source/feed doesn't appear to do anything.

### Repro steps

Start Fiddler (HTTP debugger)
Run `paket.exe find-packages source http://foo`
At the prompt, enter "bar"

No results, nor an error will be returned. Fiddler doesn't indicate an HTTP request is ever made.

### Expected behavior

find-packages to search the custom feed.

### Actual behavior

No HTTP request made.
No search results returned.
No error generated (if the search could not be performed.

### Known workarounds

None

### Related information 

Paket version 3.1.6.0

**Comment by forki** [comment]
paket.exe find-packages source http://nuget.org/api/v2 works good.
Do you have a specific url for me?

**Comment by michael-baker** [comment]
Sure, you can just make one any source. In my above example, http://foo reproduces the issue.
For whatever reason using a DNS name with Paket never shows any traffic in Fiddler, where as an IP address does show in Fiddler.

For another example I just made up an IP address.

>paket.exe find-packages source http://64.88.123.8

Using this address (as it's an IP) the call now appears in Fiddler and shows as a failed HTTP call but `find-packages` doesn't return an error or return "no results". Instead it just prompts for another search string. Is this lack of error/response by design?

[paket-1744.zip](https://github.com/fsprojects/Paket/files/334495/paket-1744.zip)

**Comment by forki** [comment]
yeah that's because it's used in ionide.
/cc @Krzysztof-Cieslak

**Comment by michael-baker** [comment]
Great. If it is by design then I'll close this.
Thanks.
