### ISSUE TITLE
Paket removes references which are under user control

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1746]
### Description

References which are under user control should not be removed by Paket. Paket removes always references and let our build fail

### Repro steps

We have a silverlight class library project which we use for testing. We add e.g. System.Net to that library and want to use that in our code. When we add the nuget dependency `Microsoft.Bcl.Async` then System.Net is removed because the for net40 this is specified as reference.

### Expected behavior

We should be able to have control over that reference. But Paket always removes references. Also specifying `<Paket>False</Paket>` does not help.

### Actual behavior

We always lose the references after a paket run.

### Known workarounds

none. Use paket 2 as this behaviour seems new in Paket 3.

### Related information 

N/A

**Comment by forki** [comment]
Argh. Please create a repro sample and temporarily downgrade to 2.x

This is related to the fact that --hard is now the default. But it should
not remove manual references that are marked with paket = false.

**Comment by Stift** [comment]
Ok. Took me a while to have a minimal repro to understand what happens.

So, if you take the repro [here](https://www.dropbox.com/s/oq8u9o0rt65hy3p/pakettest160622.zip?dl=1) , then first is fine when you do `.paket\paket install`. But when you set `<Private>True</Private>` on the reference System.Net in the SilverlightClassLibrary.csproj and run `.paket\paket install` again, then it removes the dependency.
The check should be softer. In the reference-tag the include-attribute it could also contain a specifc version or sometimes also a subnode with a hint path. All these should be ignored by paket and let as-is because the user controls these.

**Comment by forki** [comment]
is https://github.com/fsprojects/Paket/commit/a0d66a7d0abefd7e2cc7c241c2084200cc060b7b the change you meant? It's still keeping things green

**Comment by Stift** [comment]
yes. Exactly that change makes it fail.

**Comment by forki** [comment]
according to the integration test it keeps it. can you please check again?

**Comment by Stift** [comment]
you need to add the dependency microsoft.bcl.async v1.0.168

**Comment by Stift** [comment]
this is the one which references system.net for net40

**Comment by forki** [comment]
ok. I can reproduce. It moves it down to it's own Choose nodes (which is expected).

That said. If I change it to

    <Reference Include="System.Net" >
      <Private>True</Private>
      <Paket>False</Paket>
    </Reference>

I'd expect it to stay. Unfortunately Paket still thinks it can take over control. I consider this a bug

**Comment by Stift** [comment]
The problem that I see in that case, that System.Net is only defined for net40. Do you think in this case it should take the control away? It takes a lot of knowledge and investigation to find this out. For general developers it's really hard.

**Comment by forki** [comment]
it's what the package specifies.
Anyways. a fix is underway that allows you to add paket = false

**Comment by Stift** [comment]
I agree with that, but still it feels like paket steals this!
![](http://i.giphy.com/VSiNfsl8VIRIk.gif)

**Comment by forki** [comment]
I really see it as: we fix it according to the package specification. But
we allow you to know better.

**Comment by Stift** [comment]
I understand this. At least the fix gives me a way to work with. I don't have a better solution for now. The only thing that I can think of, is also to define my other dependencies.

BTW, thx for the immediate reaction.

**Comment by Stift** [comment]
I tested it and it seems to work, but a `<Paket>False</Paket>` is not needed. Is this is intended by you?

**Comment by forki** [comment]
yeah. there was another bug(?) in exactly the same line. If you add "private" then it thought it was not a framework reference. But your sample shows that this assumption was wrong

**Comment by forki** [comment]
anyways marking it with paket = false is a safe bet

**Comment by Stift** [comment]
ok. thx.
