### ISSUE TITLE
Freeze paket version

### ISSUE THREAD

**Issue by pedrofelixsky** [fsprojects/Paket#1747]
Hi,

Is there a way to freeze the paket version that a solution is using? 
I would like that everybody working on my project (including the CI) would use the *same* paket version, independently of the moment where they do the bootstrap.
As an example, the new 3.0.0 version introduces some changes that results in lots of diffs in the files ("spec" removal on the lock file, "netstandard" choice in the csproj). Without freezing the version, this becomes difficult to manage, since I now have different team members using different paket versions with different csproj policies

Gradle supports this with the concept of the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html)

**Comment by inosik** [comment]
http://fsprojects.github.io/Paket/bootstrapper.html

Tell the bootstrapper which version you want to use:
``` bash
$ .paket/paket.bootstrapper.exe 2.66.10
```
You can also control this with the environment variable `PAKET.VERSION`, but the command line parameter overrides this value.

**Comment by forki** [comment]
yep fix it with the bootsytrapper call.
cheers

**Comment by pedrofelixsky** [comment]
Thanks for the very quick replies.
I may be missing something, however I do not think that this solves the issue entirely, due to the bootstrapper step being explicit. For instance, if I need to increase the paket patch version number to fix an error, I will need to ask all team members to run the boostrapper again.

A possible solution (inspired in gradlew) would be to create a paketw.bat file with
~~~
%~dp0paket.bootstrapper 3.1.8
%~dp0paket %1 %2 %3 %4
~~~
that is used instead of paket (e.g. use `paketw restore` instead of `paket restore`). This way, I would ensure that the correct version is used by everyone and that version updates are handled transparently.

What do you think? I'm I missing something more simpler to handle this?
Thanks

**Comment by forki** [comment]
We usually call the bootstrapper as part of the build script.

**Comment by cguedes** [comment]
Why don't we use something like the `engine` field in the nodejs' package.json (https://docs.npmjs.com/files/package.json#engines).

We can add something like

```
paket: 2.66.10
```

to the `paket.dependencies` file.

We can/should even use semver to specify the version.

**Comment by forki** [comment]
Yes this could work, but there are couple of things to consider:

* what happens when you don't have the version?
* What would Paket.VS do (it would probably test internal version of Paket.Core)
* Do we put it into lock file as well?

**Comment by cguedes** [comment]
I guess we can:

* default to the latest version (as for now, and to not break existing clients)
* I don't know this :-/
* Yes, maybe that can the usefull if we use semver to specify the paktet version

**Comment by forki** [comment]
no I meant the following:

Suppose you have paket 3.1.2 and it reads `paket: > 3.2` from deps file. What should happen?

**Comment by pedrofelixsky** [comment]
Download paket 3.2 and use it instead?

**Comment by cguedes** [comment]
I agree.

**Comment by forki** [comment]
so it should quit itself, patch itself silently and rerun?

**Comment by forki** [comment]
(that would not work with VS addin)

**Comment by forki** [comment]
I maked this up-for-grabs and think it can be done in two phase:

Phase 1
* Add a paket version restriction to the deps file and the lock file
* Make paket fail when it doesn't match the given version

Phase 2
* make paket upgrade (or downgrade) itself if it doesn't match the specified restriction
