### ISSUE TITLE
Runtime deps should be copied based on TargetFramework

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1751]
from https://github.com/fsprojects/Paket/issues/1693#issuecomment-228038155

* Currently we copy runtime deps to $(OutputPath). We should change that to $(OutDir)
* We should only copy the stuff that is used in current target framework

/cc @Rcomian

**Comment by forki** [comment]
this is now in alpha channel. @Rcomian can you please try it out?

**Comment by Rcomian** [comment]
Yes! this seems to have fixed the build issue on my build.

Thanks :D

**Comment by Rcomian** [comment]
Wish there was a tip jar for this project
