### ISSUE TITLE
Simplify removes pinned transitives from dependencies file

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#1752]
If you have a dependency in the dependencies file that is a transitive dependency that you've explictly put in to stop it being pulled to a newer version, and then do a simplify, the transitive is removed from the dependencies file. Thus, the next time you do a paket update, it will get promoted to the latest version.

**Comment by forki** [comment]
That is basically what the feature does. ;-)

**Comment by theimowski** [comment]
yep, and this is why there's the `--interactive` flag, which prompts on every removal

**Comment by isaacabraham** [comment]
@forki simplify should just simplify the file - it should always give the same results of doing a paket install before and after. currently it doesn't do that.

**Comment by forki** [comment]
no. it's a heuristic. we even have a disclaimer: http://fsprojects.github.io/Paket/paket-simplify.html#Notes-and-Warnings

**Comment by isaacabraham** [comment]
Makes sense. Is it possible for someone to change the simplify heuristic to "ignore" items that are pinned or have some specific version information?

**Comment by cdrnet** [comment]
One of the typical use cases of simplify is right after a repo has been converted from NuGet, where everything is typically pinned (to be safe). The current heuristic makes sense in this case. Maybe we need two different behaviors?
