### ISSUE TITLE
The "CopyRuntimeDependencies" task could not be initialized with its input parameters

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#1756]
### Description

Please provide a succinct description of your issue.

### Repro steps

1) Install [Net compiler platform](https://visualstudiogallery.msdn.microsoft.com/2ddb7240-5249-4c8c-969e-5d05823bcb89)
2) New project > Visual C# > Extensibility > Analyzer with Code Fix (Nuget + VSIX)
3) Convert to paket.

### Expected behavior

Expected the test to build & pass after converting to paket.

### Actual behavior

Build fails due to CopyRuntimeDependencies
This is what the element looks like after conversion:
`<CopyRuntimeDependencies OutputPath="$(OutDir)" TargetFramework="$(TargetFrameworkIdentifier) - $(TargetFrameworkVersion)" ProjectsWithRuntimeLibs="System.Collections;System.Diagnostics.Contracts;System.Diagnostics.Debug;System.Globalization;System.IO;System.Private.Uri;System.Reflection;System.Reflection.Extensions;System.Reflection.Primitives;System.Reflection.TypeExtensions;System.Resources.ResourceManager;System.Runtime;System.Runtime.Extensions;System.Runtime.Handles;System.Runtime.InteropServices;System.Text.Encoding;System.Text.Encoding.Extensions;System.Threading;System.Threading.Tasks" />`

### Related information 

* !Win 7
* Paket 3.2.3
* .NET 4.5

**Comment by forki** [comment]
can you please upload a zip with the code before step 3?

**Comment by forki** [comment]
and what's the concrete error?

**Comment by JohanLarsson** [comment]
This should repro the issue: [Uploading AnalyzerWithCodeFix-0.1.zip…]()

**Comment by JohanLarsson** [comment]
There were a bunch of errors after the conversion:
1) Analyzer paths not updated, stillpointing to the `x.y.z` paths.
2) This mysterious CopyRuntimeDependencies failed the build.
3) One more issue that I don't remember now.

**Comment by forki** [comment]
If I run paket convert-from-nuget on that zip I get:

![image](https://cloud.githubusercontent.com/assets/57396/16357678/7f406ea2-3afd-11e6-9958-7ba3bd75614b.png)

**Comment by forki** [comment]
can you please upload state after step 3?

**Comment by forki** [comment]
closed after discussion on gitter
