### ISSUE TITLE
Paket restore incorrectly fails with 'lock file out of sync'

### ISSUE THREAD

**Issue by krontogiannis** [fsprojects/Paket#1757]
### Description

After updating to paket `3.2.3` my build fails with
```
Paket failed with:
	paket.dependencies and paket.lock are out of sync in /Users/kostas/workspace/paket-issue.
Please run 'paket install' or 'paket update' to recompute the paket.lock file.
```
While trying to find a minimal example that fails I observed that i had the same package declared twice in my dependencies (once with a framework constraint and once without).

### Repro steps

`paket.dependencies`
```
source https://www.nuget.org/api/v2/

nuget NuGet.CommandLine
nuget NuGet.CommandLine framework: portable45-net45+win8
```

```
> mono paket.exe install
Paket version 3.2.3.0
Resolving packages for group Main:
 - NuGet.CommandLine 3.4.3
/Users/kostas/workspace/paket-issue/paket.lock is already up-to-date
1 second - ready.
> cat paket.lock 
NUGET
  remote: https://www.nuget.org/api/v2
    NuGet.CommandLine (3.4.3)
> mono paket.exe restore
Paket version 3.2.3.0
Paket failed with:
	paket.dependencies and paket.lock are out of sync in /Users/kostas/workspace/paket-issue.
Please run 'paket install' or 'paket update' to recompute the paket.lock file.
```

### Expected behavior

Probably warn/fail for duplicate packages.

### Actual behavior

paket instructs for a `install` or `update` that doesn't actually change `paket.lock` in this case.

### Known workarounds

Remove the duplicate entry.

### Related information 

* OSX 10.11.5
* paket 3.2.3.0
* mono 4.4.1 

Note: Last time I tried to build that project with paket 3.1.9 I got no errors.

**Comment by forki** [comment]
I think we should fail with better error:

![image](https://cloud.githubusercontent.com/assets/57396/16357152/df0dd2d4-3aee-11e6-907c-3b2a2cc2e90a.png)
cid
