### ISSUE TITLE
Using network cache with invalid credentials fails restore

### ISSUE THREAD

**Issue by xavierzwirtz** [fsprojects/Paket#1758]
I have a network cache declared that I am not on the domain for. Periodically my credentials age out, and my build fails like so:
```
  ==> Trying again
Downloading Microsoft.AspNet.WebPages 3.1.1
Something went wrong while downloading Microsoft.Bcl 1.1.10
Message: The user name or password is incorrect.
```
It would be preferable for it to just log a warning, and restore from the main feed in that situation.

**Comment by forki** [comment]
Is there a way for me to reproduce?

**Comment by xavierzwirtz** [comment]
Have a cache declared that you cannot login to:
```
cache //nas.domain.local/Shares/Development/PackageCache versions: all
```

**Comment by forki** [comment]
I only have a cache that i not available at all. But this allowed me to fix 2 things. Please retry with latest.

**Comment by xavierzwirtz** [comment]
Trying with `3.3.2.0`
```
Could not copy C:\Users\xavier\AppData\Local\NuGet\Cache\xunit.core.2.0.0.nupkg to cache //office4.birddogsw.local/Shares/Development/PackageCache
Paket failed with:
        The user name or password is incorrect.
```

**Comment by forki** [comment]
Ok so. I think I need a real repro.
