### ISSUE TITLE
Paket FizzBin / `paket restore`

### ISSUE THREAD

**Issue by bartelink** [fsprojects/Paket#176]
Recently I've tried to explain Paket to a number of people who are well versed in NuGet, .net, MSBuild (and in 2/3 cases, F#)

Examples:

* https://github.com/fsprojects/Paket/issues/166 - https://github.com/fsprojects/Paket/issues/166#issuecomment-56818046
* https://github.com/ploeh/Hyprlinkr/issues/33#issuecomment-56847064
* https://jabbr.net/#/rooms/fsharp
* various twitter discussions / DMs / Skype conversations.

I'd like to make a plea that you read [this "NuGet Package Restore misconceptions" article by Jeff Handley of the NuGet team](http://jeffhandley.com/archive/2013/12/09/nuget-package-restore-misconceptions.aspx) as it filled in / accentuated some key points for me. I don't think I was guilty of any of the misconceptions, but it leads into what I will say after the jump. **If you're going to bother to read on, PLEASE read the link - there's no point in reading on without the context**

So, my 'solution' is to attempt to write a compact guide to Paket that doesn't:

a) assume it can say "inspired by bundler" and not have that trigger 0-15 good things and 2-4 bad things dependeing on people's experience
b) does not work with detailed examples with a goal of having people read rather than scan it
c) have something that people are expected to read before anything. 

i.e. if something that if there's evidence that any core point is missing from somone's understanding, that one could (either conceptually or *really* be told "Come back when you've read **link** or we have no shared understanding and we're going to find out in 20 mins time that there are massive broken assumptions)

So.... v1 of it is:

**Comment by forki** [comment]
Restore is implemented, install has new semantics
