### ISSUE TITLE
Unable to build the WebSharper Library project when using paket as dependency manager

### ISSUE THREAD

**Issue by aph5nt** [fsprojects/Paket#1767]
### Description

How to reproduce:
- ensure that Websharper addon for visual studio is installed
- start new project with ProjectScaffold template
- add new W# Library (framework target version 4.5.2+)
- remove packages.config file from the project
- add paket.references and reference Websharper 
- run install cmd on paket.dependencies (from VS paket plugin)
- try build the project

Actual:
`Severity Code    Description Project File    Line    Suppression State
Error       The "CopyRuntimeDependencies" task could not be initialized with its input parameters.  Library1    C:\Workplace\camdora software\cryptogames\src\Library1\Library1.fsproj  53`

and

```
Severity    Code    Description Project File    Line    Suppression State
Error       The "TargetFramework" parameter is not supported by the "CopyRuntimeDependencies" task. Verify the parameter exists on the task, and it is a settable public instance property. Library1    C:\Workplace\camdora software\cryptogames\src\Library1\Library1.fsproj  53  

```

**Comment by aph5nt** [comment]
Work around:
set target framework in paket.dependencies file to:
- framework >= net46

**Comment by forki** [comment]
can you please add the broken project to this issue?

**Comment by enricosada** [comment]
Closing, as per workaround (probably netstandard stuff).

@aph5nt feel free to open a new issue
