### ISSUE TITLE
[V3] Why paket.dependencies should be in repo root?

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#1768]
We have the following repo structure:
```
\
├── src
│   ├── .paket
│   │   ├── paket.bootstrapper.exe
│   │   ├── paket.targets
│   │   ├── paket.exe
│   ├── paket.dependecies
│   ├── paket.lock
├── readme.md
├── build.fsx
├── other files
```
This worked well in V2. Now with V3 we get build errors that `paket.dependencies` file is not found and I need to ensure it is in the repo root. Indeed, when I move it there along with `paket.lock`, the error disappears. But this essentially means I have `.paket` under the `src`, however my dependencies and lock files are moved to the repo root despite there is no guarantee there is only one solution in this repo and they will get in conflict.

What was the reason behind the decision to have the dependencies and lock files in the repo root instead of a solution root?

**Comment by forki** [comment]
tbh it was always meant to look like the following:

    \
    .paket
    │   ├── paket.bootstrapper.exe
    │   ├── paket.targets
    │   ├── paket.exe
    ├── paket.dependecies
    ├── paket.lock    
    ├── src
    ├── readme.md
    ├── build.fsx
    ├── other files

if v2 allowed the structure that you had then this wasn't really intended. We really believe the dependencies file belong into the root to make things crystal clear. Deps are super important and everyone needs to know about them. This is a major difference to NuGet where it always was intended to hide dependency management.

Sorry if this breaks things for you, but it's really how we think about it.

**Comment by cdrnet** [comment]
Shouldn't this still work provided you set the working directory to `src` when running paket.exe? We also have a secondary dependencies file in a subdirectory (which is completely independent) and do no have any problems with this setup in V3.

**Comment by forki** [comment]
yes that's correct. but it will only work inside the src folder.

**Comment by alexeyzimarev** [comment]
I get build errors in Visual Studio, on a solution file that is within the src folder.

**Comment by forki** [comment]
Ok. Something is probably messed up now. 

Can you please try to convert to the suggested structure and use find/replace in files to fix the path issues? In most case paket install should fix this automatically but it seems something is weird now. If you want you can mail me the solution and I try to fix it for you

**Comment by alexeyzimarev** [comment]
OK, I run `paket auto-restore on` and path to both bootstrapper and paket itself seems to be correct. However, `<Import Project="..\.paket\paket.targets" />` remains and it fails there. Is it still needed? Shoudn't V3 remove it automatically?

**Comment by forki** [comment]
I would assume it fix that as well. But seems it doesn't.
Please try to do search / replace and see if it at least stays stable.
On Jun 29, 2016 11:10 AM, "Alexey Zimarev" <notifications@github.com> wrote:

OK, I run paket auto-restore on and path to both bootstrapper and paket
itself seems to be correct. However, <Import
Project="..\.paket\paket.targets" /> remains and it fails there. Is it
still needed? Shoudn't V3 remove it automatically?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/1768#issuecomment-229301002>,
or mute the thread
<https://github.com/notifications/unsubscribe/AADgNCFAFAMXXDNR05ctMtB8rmZY9Zvaks5qQjaSgaJpZM4JA5Pf>
.

**Comment by alexeyzimarev** [comment]
Yes, I changed my comment. `auto-restore on` fixed the path but it did not touch the path to `paket.targets`, instead it added a new tag with the right path, keeping the project file failing since the old path prevents it from loading in VS.

**Comment by forki** [comment]
Ok I guess this is a bug then.  Can you please prepare a repro?

**Comment by alexeyzimarev** [comment]
Here it is https://github.com/alexeyzimarev/Paket.ImportTargets
