### ISSUE TITLE
How to make Paket pick up packages for older .NET frameworks when intended?

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1771]
Here is what I don't understand despite all the efforts: we have internal package which intentionally targets NET35 and nothing else. What shall I write in paket.dependencies and paket.references so that the package is still picked up for .NET 4.6.1 projects? Whatever I do I get "Package BitTitan.DeviceManagement contains libraries, but not for the selected TargetFramework net461 in project...". I want those libraries to be referenced anyway, they are compatible with all versions of .NET
How?

**Comment by forki** [comment]
this sounds compelte strange. if you have only lib/net35 in the package then paket should install that. Can you mail me the project?

**Comment by forki** [comment]
if you can't send me the project - can you reproduce using the package Chessie from nuget? It hass only net40 - so pretty similar

**Comment by forki** [comment]
And thanks for taking care. I hope I didn't break anything important in all this .net core chaos.

**Comment by konste** [comment]
No repro with today's Paket 3.4.0. Closing the issue for now.
