### ISSUE TITLE
Paket update plan

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/Paket#1778]
It would be great to have an additional option to `paket update`, which would inform user about planned updates without actually making them. This way we could avoid accidental updates and make sure, that the scope of changes is known.

Example:

```
> paket update --plan
System.Collections.Immutable 1.1.36 ~> 1.1.37
Newtonsoft.Json 8.0.1 ~> 8.0.3
...
```

**Comment by forki** [comment]
Did you see the outdated command? What's wrong with that?

(also there is git reset ;-))

**Comment by Horusiath** [comment]
Sorry, I didn't see paket update outdated. Closing this one.
