### ISSUE TITLE
Paket Install and Large Sub-directories

### ISSUE THREAD

**Issue by nickbabcock** [fsprojects/Paket#1782]
### Description

`paket.exe install` does not finish when invoked in a directories with large sub-directories

### Repro steps

```
cd /
sudo touch paket.dependencies
sudo /paket.exe install
```

### Known workarounds

`cd` into `/tmp` and everything works fine :stuck_out_tongue: 

### Related information 

* Operating system: 14.04.4 LTS, Trusty Tahr (but should effect all systems)
* Branch: Paket 3.4.0
* Mono Version: 4.4.1

**Comment by forki** [comment]
Making this up-for-grabs since I think it will be probably easy to fix if one has a repro.

**Comment by nickbabcock** [comment]
The issue is [ProjectFile.FindAllProjects](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/ProjectFile.fs#L1369-L1399) (profiled through mono). It recursively searches all directories, which is not good when the directories are huge (and potentially irrelevant to the `install`).

Are the project files that make up a solution not known through some other file?

I'll edit the title and description to be a little less sensationalist :wink:

**Comment by baronfel** [comment]
It's important to note that paket doesn't require, and in fact never assumes, the presence of a solution file.  It's entirely fixated around projects.  Now, that said, it would be possible augment the existing FindAllProjects code to have an optional hot-path if it finds a .sln file to read that file and take the project list from there, but continue to support the search-based method.

**Comment by nickbabcock** [comment]
A hot path is fine, but the worst case is still pretty bad. I have a node.js project with a `node_modules` directory of >6k sub-directories, >60k files and `paket install` won't return after a minute. This could put a limitation on .net/node.js cross applications without a re-org of the project structure.

Also consider the use case when there are no projects [(Paket from F# interactive)](https://fsprojects.github.io/Paket/reference-from-repl.html). How could we implement a hot path?

**Comment by cdrnet** [comment]
Note that the presence of a solution file does not guarantee that it contains a complete list of all projects. I typically have multiple solution files, each of them covering a subset of projects only.

**Comment by forki** [comment]
Mhm we probably can black list parts of the tree. Like we don't need to look into packages folder. And we probably don't need to look into node folders. 

PRs welcome
