### ISSUE TITLE
NuGet packages with lib folder `.NetFramework 3.5` can't be referenced

### ISSUE THREAD

**Issue by danielrbradley** [fsprojects/Paket#1790]
### Description

When adding a NuGet reference to a package containing only a folder named `.NetFramework 3.5` in the `lib` directory (e.g. [MarkdownDeep.NET](https://www.nuget.org/packages/MarkdownDeep.NET/)) the project file does not get a reference added to it.

### Repro steps

1. Add the package MarkdownDeep.NET (or any other package with folder structure `lib/.NetFramework 3.5`).

### Expected behavior

The project should have a reference added to the package, with the condition `$(TargetFrameworkVersion) == 'v3.5'`

I would assume that the folder named `.NetFramework 3.5` should be treated in the same way as a folder named `net35`.

### Actual behavior

No reference is added to the project.

Reproduction of what happens when the package is added to an empty scaffolded project:
https://github.com/danielrbradley/PaketMarkdownDeepRepro/commit/3c5f37e35fd468db984731d636ceb84a68de37e5

### Workaround

Rebuild the original NuGet package using a fixed folder name, and host privately.

### Related information 

This has been tested when adding the package on both C# and F# projects.

This was found while running an automated conversion from NuGet.

**Comment by smoothdeveloper** [comment]
@danielrbradley another work around is to add the reference manually, just in case you didn't do that yet :)

If you want to give a shot at troubleshooting that, you can look at those definitions https://github.com/fsprojects/Paket/blob/38b32a72b12e48c1d2d24a54629a41723d1883d3/src/Paket.Core/FrameworkHandling.fs

and check implementation of `InstallModel.GetLibReferences` which you'd expect to return the assembly locations.

**Comment by smoothdeveloper** [comment]
and thanks for extensive bug report! :)

It would be great if you'd make a PR with failing test in integration tests project, this is very easy to do and would save a bit of work to the person who will fix this bug.

**Comment by smoothdeveloper** [comment]
The short way would be for you to change this line

https://github.com/fsprojects/Paket/blob/38b32a72b12e48c1d2d24a54629a41723d1883d3/src/Paket.Core/FrameworkHandling.fs#L266

compile the solution, and try to use the compiled paket.exe to see if this solves the issue.
