### ISSUE TITLE
Dependency resolution does not work for VSTS feed

### ISSUE THREAD

**Issue by wrummler** [fsprojects/Paket#1798]
### Description

I have a private package `A` in my VSTS feed that depends on a package `B` from the nuget.org feed. When I `paket install`, `A` is resolved and downloaded, but `A`'s dependency on `B` is not resolved (and `B` is not downloaded). By comparision, when I source a local folder feed containing `A`, `B` is successfully resolved and downloaded.

### Repro steps

1. Create a new feed in a VSTS project.

2. For private package `A` depending on nuget.org package `B`, push `A` to the VSTS feed.

3. Add the VSTS feed and package `A` to `paket.dependencies`, e.g.:

  - `c:\path\to\project\paket.dependencies`:
    ```
    source https://www.nuget.org/api/v2
    source https://myproject.pkgs.visualstudio.com/_packaging/myfeed/nuget/v2

    nuget A
    ```

4. `paket install`

### Expected behavior

```
Paket version 3.4.0.0
Resolving packages for group Main:
 - A 0.1.0.36
 - B 1.2.0
Locked version resolution written to c:\path\to\project\paket.lock
2 seconds - ready.
```

### Actual behavior

```
Paket version 3.4.0.0
Resolving packages for group Main:
 - A 0.1.0.36
Locked version resolution written to c:\path\to\project\paket.lock
4 seconds - ready.
```

### Known workarounds

None.

### Related information 

* Windows 7 Pro 64-bit
* .NET Framework 4.6.1

**Comment by forki** [comment]
ok this sounds very very strange.
Is there a way to reproduce with a public feed?

@isaacabraham do you have seen this?

**Comment by kostrse** [comment]
I'm also reproducing this problem, even with packages from the same source.
We are using internal package feed for mirroring nuget.org.

**paket.dependencies with  nuget.org source**
```
framework: >= net461
source https://www.nuget.org/api/v2
nuget Microsoft.AspNet.WebApi.OwinSelfHost ~> 5.2.3
```

**paket intall**
```
$ .\.paket\paket.exe install
Paket version 3.20.2.0
Resolving packages for group Main:
 - Microsoft.AspNet.WebApi.OwinSelfHost 5.2.3
 - Microsoft.AspNet.WebApi.Owin 5.2.3
 - Microsoft.Owin.Host.HttpListener 3.0.1
 - Microsoft.Owin.Hosting 3.0.1
 - Microsoft.AspNet.WebApi.Core 5.2.3
 - Microsoft.Owin 3.0.1
 - Owin 1.0
 - Microsoft.AspNet.WebApi.Client 5.2.3
 - Newtonsoft.Json 9.0.1
Locked version resolution written to D:\Temp\Test1\paket.lock
5 seconds - ready.
```



**the same paket.dependencies but with a custom source**
```
framework: >= net461
source https://xyz.pkgs.visualstudio.com/_packaging/xyz/nuget/v3/index.json
nuget Microsoft.AspNet.WebApi.OwinSelfHost ~> 5.2.3
```

**paket install with custom source**
```
$ .\.paket\paket.exe install
Paket version 3.20.2.0
Resolving packages for group Main:
 - Microsoft.AspNet.WebApi.OwinSelfHost 5.2.3
Locked version resolution written to D:\Temp\Test1\paket.lock
3 seconds - ready.
```

**Comment by kostrse** [comment]
Local filesystem - works OK
MyGet v3 feed- works OK

Profiled with Fiddler, in case of VSTS Paket doesn't attempt to fetch dependencies.
For MyGet (and NuGet) it seems to be using different workflow.

**Comment by kostrse** [comment]
This commit doesn't solve the problem.
OData v2 API of pkgs.visualstudio.com doesn't return any dependencies.

Why does Paket always stick to v2 API?

I tried to debug with Paket.NuGetV3.getPackageDetails implementatioin, but it crashes  (API incompatibility or something similar).

**Comment by forki** [comment]
Because c3 is faster in nearly all situations.

Is there a way for me to reproduce?

Am 04.10.2016 21:13 schrieb "Sergey Kostrukov" <notifications@github.com>:

**Comment by kostrse** [comment]
I will create an account in VSTS with a private NuGet feed for reproduction.
