### ISSUE TITLE
Incorrect CopyRuntimeDependencies.ProjectFile causes 'Could not find paket.dependencies'

### ISSUE THREAD

**Issue by vladnega** [fsprojects/Paket#1799]
### Description

About 3 weeks ago my project was building just fine. After running (with version 3.4.0.0) `paket update` and building the project again, it failed with "Could not find 'paket.dependencies'. To use Paket with this solution, please run 'paket init' first.".  

Looking at the changes that the `paket update` caused, I could see the following lines being added to one of my `.csproj` files:

```xml
  <UsingTask TaskName="CopyRuntimeDependencies" AssemblyFile="..\.paket\paket.exe" />
  <Target Name="AfterBuild" Condition="Exists('..\.paket\paket.exe')">
    <CopyRuntimeDependencies OutputPath="$(OutDir)" TargetFramework="$(TargetFrameworkIdentifier) - $(TargetFrameworkVersion)" ProjectsWithRuntimeLibs="System.Net.Http" />
  </Target>
```

The `outputPath` of my `MSBuildRelease` task is in a different folder than my `.csproj/.fsproj` files. The key thing is that the project file path and the output path are unrelated (no parent/child relationships). 

After a bit of digging around the Paket source code, I could see that the `CopyRuntimeDependencies.ProjectFile` member is set to the `outputPath` variable, instead of the `projectFile` one. This causes the `Dependencies.Locate` function to search in the wrong folder for the `project.dependencies` file.

### Possible fix

Set the `ProjectFile` member in the `CopyRuntimeDependencies` type using the `projectFile` variable:

```fsharp
member this.ProjectFile
    with get() = projectFile
    and set(v) = projectFile <- v
```

### Related information 

* Operating system: Windows 10
* Branch: version 3.4.0.0
* .NET 4.6

**Comment by forki** [comment]
please send a PR

**Comment by vladnega** [comment]
PR sent

**Comment by forki** [comment]
where?

**Comment by vladnega** [comment]
Sorry, created the PR on my forked repo
