### ISSUE TITLE
Feature Request: paket.local override nuget package with csproj.

### ISSUE THREAD

**Issue by gertjvr** [fsprojects/Paket#1803]
### Description

Feature request, what I am after is the ability to use `paket.local` file to override a `nuget package reference` with the `csproj` file that was used to produce to `nuget package`.

I have two example repositories [ServiceA](https://github.com/gertjvr/ServiceA) and [ServiceB](https://github.com/gertjvr/ServiceA), `ServiceB` has a `nuget package` reference to `ServiceA.MessageContract` a sub project of `ServiceA` repository.

### Repro steps

1. Create a `paket.local` file with content as below

```
nuget ServiceA.MessageContracts -> project c:\github\ServiceA\src\ServiceA.MessageContracts\ServiceA.MessageContracts.csproj
```

2. Run `.paket\paket restore`

### Expected behavior

The `nuget reference` in `ServiceB` is replaced with `csproj reference` of `ServiceA.MessageContracts`

### Known workarounds

The main issue is that our nuget package version number isn't stored in the git repository so have to customise the build script to pass a `build number` to recreate a `nuget package` so that `paket.local` can successfully override them locally.

cc @theimowski

**Comment by gertjvr** [comment]
Think #724 is a related issue

**Comment by theimowski** [comment]
This could be interesting however much effort would be required -  AFAIK there's currently no utility in Paket to build xprojs

**Comment by mterwoord** [comment]
After a gitter discussion on a wish/question I had, this issue was mentioned. We discussed the following option:

How about giving the option to specify a .dll (/.exe) file in the .local file? Then the only thing paket has to do is replace the hint path in the project file. The difficult paths (finding the outpt filename of the project, taking into account solution settings, etc, etc is then up to the user)

**Comment by theimowski** [comment]
As of now there's a possibility to give path to a nupkg file. 
If you had nuget packaging as a part of your referenced project build process, you could use that.

The workflow would then look like this:

1. for referenced project, specify override in .local file giving a path to where the nupkg is created
2. make changes in referenced project
3. build the referenced project, **creating a nupkg** in result
4. restore packages in referencing project to consume new changes 
5. if necessary repeat from 2.

You might consider the additional step in build process (creating a nupkg) redundant when the package is really just a single dll, however such solution was the easiest way to incorporate `paket.local` into existing Paket restore process.

**Comment by gertjvr** [comment]
The only issue we have is that the nupkg version number isn't discoverable from the local build process, in our case a locally build version is 0.0.0 and paket restore = local override, fails because it looking the nupkg with the exact reference version number.

**Comment by mterwoord** [comment]
One remaining "issue" for me is that if i have to make a nupkg file, i have spent 90% of the time of the build already...

**Comment by theimowski** [comment]
@gertjvr what we could do then is to allow for optional ``version`` param in the `paket.local` file, but it'd have to be pinned to specific verison (which should be fine for your case).
@mterwoord You mean the additional time of packaging is an issue?

**Comment by mterwoord** [comment]
In my situation, I'm building a package using a script, that consumes most of the time. If I still have to build the package every time, I won't be using the paket.local to override, i'd just push them to a server and pull from there

**Comment by gertjvr** [comment]
issue with pinned is paket restore fails to restore with version 0.0.0 if paket.dependencies has a specific version / range.

**Comment by theimowski** [comment]
I mean pinned version in the local file

**Comment by gertjvr** [comment]
sry for my ignorance is that currently implemented?

**Comment by theimowski** [comment]
No not yet. But should  be doable with little effort,  hence my suggestion

**Comment by theimowski** [comment]
I'll give it a go soon and keep you updated

**Comment by gertjvr** [comment]
That would be amazing

**Comment by theimowski** [comment]
PR submitted - #1843

**Comment by gertjvr** [comment]
Worked!!! :grinning:  now to blog `how to develop microservices locally` using this feature

**Comment by forki** [comment]
Awesome. Post link when you are ready ;-)

**Comment by theimowski** [comment]
@gertjvr glad it helped! you might have a look at my [blog entry](http://theimowski.com/blog/2016/05-19-paket-workflow-for-testing-new-nuget-package-before-release/index.html) on similar topic - I based on "Git override" though
