### ISSUE TITLE
How to reference project from packet.dependencies 

### ISSUE THREAD

**Issue by tigerclawn82** [fsprojects/Paket#1805]
### Description

How to add referenced  git dependencies in Project. eg: i added git repo in packet.dependencies and that repo has multiple projects, i want to reference project within that repo
### Repro steps
1. Add git repo in packet.dependencies 
### Expected behavior

There should be option to reference project within that Repo
### Actual behavior

Paket failed with:
        paket.references uses NuGet package xxx, but it was not found in the paket.lock file in group Main.
### Known workarounds

Please provide a description of any known workarounds.
### Related information
- Microsoft Windows Server 2008 R2
- Paket version 3.6.1.0 Stable
- .NET Runtime 4.0/4.5

**Comment by forki** [comment]
currently we don't reference projects in paket.references 

just go to VS and reference the project manually via the dialog.

**Comment by smoothdeveloper** [comment]
@tigerclawn82 there is discussion tracked here #1497 about project reference support

**Comment by enricosada** [comment]
Closing, currently project references are handled in msbuild project

Discussion to move it `paket.reference` file is tracked in https://github.com/fsprojects/Paket/issues/1497
