### ISSUE TITLE
paket restore exited with code 1 with msbuild

### ISSUE THREAD

**Issue by renangms** [fsprojects/Paket#1808]
C:\Builds\Main\src\.paket\paket.targets (39): The command "C:\Builds\Main\src\.paket\paket.exe" restore --references-files "C:\Builds\Main\src\Algorithms\paket.references"" exited with code 1.

Is there a minimum required msbuild version? I'm using msbuild v4.0.30319.

**Comment by forki** [comment]
When/where is this happening?

**Comment by renangms** [comment]
Nevermind. It was an permission issue to get one of the nuget packages. Closing the issue.

**Comment by rrvenki** [comment]
renangms. Please let us know how to solve this problem.

**Comment by slow-down** [comment]
So how did you solve it??? Why do you just close it without actually telling us how to solve it. Come on.

**Comment by dtwk1** [comment]
A path exceeded a limit on characters in my case. Moving the solution to a directory higher up solved the issue. Identified by running the  restore command (similar to op's) in Command Prompt.
