### ISSUE TITLE
Paket 3.7.0.0 broke paket pack

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#1810]
### Description

There is a regression in 3.7.0.0. Paket pack no longer works:

```
Paket version 3.7.0.0
Paket failed with:
        Did not find satellite assembly for (ontrols) try building and running pack again.
```

Sorry for not being able to provide more information at the moment, but I'll get back once I have an example that reproduces the problem

### Known workarounds

Use 3.6.1.0

**Comment by forki** [comment]
I reverted https://github.com/fsprojects/Paket/pull/1807 in 3.7.1 - please provide a repro if possible.

**Comment by forki** [comment]
We still want to have the feature with satellite assemblies
