### ISSUE TITLE
Paket 'pack' does not correctly exclude 'project' template files

### ISSUE THREAD

**Issue by varon** [fsprojects/Paket#1818]
### Description

I experienced some very unclear difficulties with adding exclusions to paket's pack command.

Paket pack `exclude` parameters doesn't seem to work when the`paket.template` file begins with `type project`, _even if the project specifies an ID on the next line_.

### Repro steps

1. Create a paket.template file in your project with the type as `project`.
2. Try to run paket pack:
    `.paket/paket.exe -v pack output "bin"  exclude OpenTK.GLWidget`

### Expected behavior

Paket should exclude the project by ID if it specifies one, regardless of whether the type is a project or a file.

### Actual behavior

Paket fails with an obscure error message:
`Paket failed with:
        Could not find a part of the path '<snip>\src\OpenTK.GLWidget\bin\Release\OpenTK.GLWidget.dll'.
`

### Known workarounds

Change the type from `project` to `file`.

### Related information 

* Operating system: W10
* Branch: Stable? Whichever the bootstrapper downloads.

**Comment by varon** [comment]
You can view an example of a build failing due to this here:
https://ci.appveyor.com/project/varon/opentk/build/0.0.1.6
https://travis-ci.org/opentk/opentk/builds/145428588

With the actual commit:
https://github.com/opentk/opentk/pull/418/commits/489d4022dbfd8c331cf906be92dba953a20269fd

**Comment by forki** [comment]
thanks for reporting. should be fixed now.

**Comment by varon** [comment]
Thanks!
