### ISSUE TITLE
Paket update does not update .csproj file correctly anymore (Regression)

### ISSUE THREAD

**Issue by franknarf8** [fsprojects/Paket#1829]
### Description

We encountered a new problem with one of our packages. When we pulled on it, paket did not add a reference to the dll in the project file.

### Repro steps

Here is a repro sample;
https://github.com/franknarf8/paket-issue-repro/tree/b363bf2d50031e71ff9bb3a39ca471b44b64f8c7

Here, we are trying to install WindowsNative in the project Sandbox2.0.

The commands listed below do not have the same effect on the .csproj file. We were expecting the old behavior. If the new behavior is the correct one, why is it so?

### Expected behavior

When we ran : `.paket\paket.exe.old.exe update` (2.66.3.0)
Paket used to create a reference to that dll in the .csproj file.

### Actual behavior

Now, when we run : `.paket\paket.exe.new.exe update` (3.8.1.0)
The reference is removed from the .csproj file.

### Known workarounds

Link directly to the .dll (bad workaround)

**Comment by forki** [comment]
Ok I tried to reproduce. which lib is missing?

![image](https://cloud.githubusercontent.com/assets/57396/17000165/8feee3f0-4ec1-11e6-8dbd-0b61ffbac56a.png)

the wk-component/WindowsNative package seems empty after extraction

**Comment by forki** [comment]
oh I just extracted it with 7zip:
![image](https://cloud.githubusercontent.com/assets/57396/17000241/daf1c30e-4ec1-11e6-8081-a95280e68b82.png)

so it looks like unzip is broken here. WTF!?
