### ISSUE TITLE
Topshelf debug issue

### ISSUE THREAD

**Issue by tigerclawn82** [fsprojects/Paket#1830]
### Description

Installed Topshelf pinned to specific version via Paket having project based paket.references and i was not able to install/debug but able to build successfully.

### Repro steps

1. Add nuget Topshelf == 3.3.1 in paket.dependencies

2. Add Topshelf in xxx.vbproj.paket.references

### Expected behavior

Package should be added as reference and should be able run as normal as if i added via Nuget

### Actual behavior

Package was added as dependency but was not able to debug, i added via nuget and then was able to Debug as usual.

### Known workarounds

Add topshelf via Nuget and everything should work as expected.

### Related information 

* Window Server 2008 R2
* Latest/Stable
* .NET Runtime

**Comment by forki** [comment]
What is the difference in the vbproj?
Can you create a minimal repro? Any ideas what's going wrong?

**Comment by smoothdeveloper** [comment]
> Add Topshelf in xxx.vbproj.paket.references

Could you make sure that the file name is just `paket.references` and sits next to .vbproj file?

**Comment by smoothdeveloper** [comment]
Mhh scratch that, you are able to compile.

Could you check the diff of vbproj file when you use nuget and paket, maybe topshelf has some special target which aren't caught by paket for some reason.

**Comment by tigerclawn82** [comment]
Hi, i am attaching project file created with Paket and Nuget.



[Paket-Issue.zip](https://github.com/fsprojects/Paket/files/381877/Paket-Issue.zip)

Hopefully it would help

**Comment by smoothdeveloper** [comment]
@tigerclawn82 is there anything under packages\Topshelf in your working copy?

**Comment by smoothdeveloper** [comment]
@forki that is how paket reference the package:

```xml
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v3.5' Or $(TargetFrameworkVersion) == 'v4.0')">
      <ItemGroup>
        <Reference Include="Topshelf">
          <HintPath>..\packages\Topshelf\lib\net35\Topshelf.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2' Or $(TargetFrameworkVersion) == 'v4.6.3')">
      <ItemGroup>
        <Reference Include="Topshelf">
          <HintPath>..\packages\Topshelf\lib\net40-full\Topshelf.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

it is strange that framework 4.0 seems to overlap both net-35 and >= 4 conditions.

nuget

```xml
    <Reference Include="Topshelf, Version=3.3.154.0, Culture=neutral, PublicKeyToken=b800c4cfcdeea87b, processorArchitecture=MSIL">
      <HintPath>..\packages\Topshelf.3.3.1\lib\net40-full\Topshelf.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

**Comment by tigerclawn82** [comment]
Yes, i do have Topshelf in packages, here is the screenshot

![packages-topshelf](https://cloud.githubusercontent.com/assets/457518/17107782/23a11276-52aa-11e6-8b78-7ebe6bf55fb1.PNG)

**Comment by smoothdeveloper** [comment]
@tigerclawn82 for now I think if you add `framework: >= net40` it would work around the issue (hopefully you don't need support for 3.5)

**Comment by smoothdeveloper** [comment]
(in `paket.depedencies`)

**Comment by matthid** [comment]
This looks like the net40-client and net40 quirk :)

**Comment by tigerclawn82** [comment]
adding framework: >= net40 in paket.depedencies didn't help. I guess, i should stick with nuget reference untill i didn't get any work around. I am using Paket with FAKE to streamline CI/CD and i wanted to only use Paket.

It would really appreciate to get any workaround to only stick with paket

**Comment by tigerclawn82** [comment]
i am targetting .net40 but topshelf is available for .net35

**Comment by smoothdeveloper** [comment]
@tigerclawn82 did you run paket install after changin `paket.dependencies`?

Another work around would be to remove Topshelf from `paket.references` and add the assembly manually to your project, this should work flawlessly, even if you upgrade topshelf in future.

**Comment by forki** [comment]
Will take a look at the repro tomorrow

**Comment by forki** [comment]
from what I can see the referenced topshelf looked good.
TBH we never had issues with the topshelf package together with paket.

I think what I need is a real repro sample. Can you please attach a zipped full solution that uses paket and doesn't work. Also please describe what you do to debug. I think I need very detailed steps here since currently I can't see any issue.

**Comment by tigerclawn82** [comment]
It just doesn't work. I tried adding manual reference from net35 after suggestion from @smoothdeveloper but it didn't work and i have to add reference from net40-full then it worked. I am attaching sample solution, hopefully it will help.
[TopshelfService.zip](https://github.com/fsprojects/Paket/files/383573/TopshelfService.zip)

Thanks

**Comment by forki** [comment]
<When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.0'">
      <ItemGroup>
        <Reference Include="Topshelf">
          <HintPath>..\packages\Topshelf\lib\net35\Topshelf.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2' Or $(TargetFrameworkVersion) == 'v4.6.3')">
      <ItemGroup>
        <Reference Include="Topshelf">
          <HintPath>..\packages\Topshelf\lib\net40-full\Topshelf.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>

I think I found something strange. Can you please go to line 57 in TopshelfService.csproj and try to change

     <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.0'">

to

    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' >

does this solve the issue?

It looks like  `$(TargetFrameworkVersion) == 'v4.0'"` gets emitted twice.

**Comment by forki** [comment]
oups. I meant change that line to 

<When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v3.5'">

**Comment by forki** [comment]
I think I found the bug. working on a fix

**Comment by tigerclawn82** [comment]
thanks @forki 
I really appreciate you guys quick responses, you guys are a really vibrant community.

**Comment by forki** [comment]
fix is underway. will take about 15min to pass all integration tests.

**Comment by forki** [comment]
please retry with latest and let me know if things work

**Comment by tigerclawn82** [comment]
yeah, thanks. Its working fine now. I really appreciate your help.

**Comment by forki** [comment]
Unfortunately I introduced a new bug. This is now fixed, but can you please verify that 3.9.6 still works for you?

**Comment by tigerclawn82** [comment]
yeah, v3.9.6 is also working fine. 
Thanks

**Comment by wahmedswl** [comment]
Hi, got bitten by this. I have targetted .net framework 4 in Project. I had framework: >= net40 in paket.dependencies but now i changed that to framework: net40.

Now, Topshelf references are again messed up. Before i had following in csproject

```
<Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' And $(TargetFrameworkProfile) == 'Client')">
      <ItemGroup>
        <Reference Include="Topshelf">
          <HintPath>..\packages\Topshelf\lib\net35\Topshelf.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2' Or $(TargetFrameworkVersion) == 'v4.6.3')">
      <ItemGroup>
        <Reference Include="Topshelf">
          <HintPath>..\packages\Topshelf\lib\net40-full\Topshelf.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

But now, its been changed to 

```
<When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.0'">
      <ItemGroup>
        <Reference Include="Topshelf">
          <HintPath>..\packages\Topshelf\lib\net35\Topshelf.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
```

Its not good, it should include net40-full\Topshelf.dll, as for framework: net40 both net35 and net40-full folders are available.

Thanks
