### ISSUE TITLE
Move Generate Include Scripts to public api

### ISSUE THREAD

**Issue by monkieboy** [fsprojects/Paket#1834]
### Description

The command `paket generate-include-scripts` is not available from the public api in the same manner as install dependencies is: `Paket.Dependencies.Install`

It would be useful to have this command available on the public api so that one might be able to call paket like so: `Paket.GenIncludeScripts(...args...)` or whatever is most suitable.
### Repro steps

N/A
### Expected behaviour

When calling the command from within code, it should create the paket-files folder and the desired include scripts in the current environment directory.
### Actual behaviour

N/A
### Known workarounds

The process could be executed via ProcessStartInfo calling a .bat or .cmd file of sorts.
### Related information

Initiated from Twitter conversation: https://twitter.com/MarkRGray/status/757914137762693122
- Operating system
- Branch
- .NET Runtime, CoreCLR or Mono Version
- Performance information, links to performance testing scripts

**Comment by smoothdeveloper** [comment]
@monkieboy, I'll check to add public api member for this, thanks for suggestion.

In meantime could you try this:

````fsharp
open System.IO
let path = __SOURCE_DIRECTORY__
let framework = Paket.FrameworkIdentifier.DotNetFramework Paket.FrameworkVersion.V4_5
let scriptType = Paket.LoadingScripts.ScriptGeneration.FSharp 
Paket.LoadingScripts.ScriptGeneration.generateScriptsForRootFolder scriptType framework (path |> System.IO.DirectoryInfo)
```

**Comment by smoothdeveloper** [comment]
@monkieboy can we close that issue?

I've added member to public API in next version: https://github.com/fsprojects/Paket/blob/9afb18d50905c57e0a76e74a5050e642eb770ed0/src/Paket.Core/PublicAPI.fs#L199

**Comment by monkieboy** [comment]
Yes, close this down thanks :)
