### ISSUE TITLE
Adds stray name to paket.lock file

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#1840]
<img width="565" alt="screen shot 2016-07-29 at 19 09 57" src="https://cloud.githubusercontent.com/assets/193115/17256946/1a4ad626-55c0-11e6-81dd-405837b2d360.png">

### Description

`Http.fs-prerelease` depends on Hopac. Logary depends on Hopac. Logary has Hopac 0.3. In Logary `paket update`. The above screenshot is the result. Also see Logary#bc7db58

### Expected behavior

Not stray Hopac line.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Delete the line.

### Related information 

* Operating system: OS X
* Branch: ???
* .NET Runtime, CoreCLR or Mono Version: 4.4.1

**Comment by inosik** [comment]
That looks right to me, actually. Paket installs the stuff from `paket.dependencies` in the logary/RingBuffer repository.

http://fsprojects.github.io/Paket/github-dependencies.html#Remote-dependencies

**Comment by forki** [comment]
is this a public repo?

**Comment by haf** [comment]
Yes, it was just that it was unclear to me that Hopac was a dependency of the file import, but of course it is. :)
