### ISSUE TITLE
paket.bootstrapper.exe downloads into unknown directory under windows

### ISSUE THREAD

**Issue by janni2** [fsprojects/Paket#1842]
### Description

There are several projects, using FSharp and paket, which are working fine as long as the paket.exe is downloaded into one specific folder that belongs to the project. Under Linux this is working, but under Windows, it states, that download was successful, but the file is still missing, which leads to the problem, that packet.exe could never be found, except if you download it manually

[Update]
- I tried Powershell, Admin cmd.exe etc. and now I assume, that my Comodo Internet Security Firewall blocked the creation of the file somehow, till a dialog popped up, to not isolate the paket.bootstrapper.exe.

**Comment by forki** [comment]
I don't understand? I use paket.bootstrapper multiple times a day on
Windows 10

**Comment by janni2** [comment]
OK sorry, in the Windows PowerShell it is working in the "cmd.exe" it is reproducable not :/

**Comment by janni2** [comment]
My fault, can be closed, I updated the ticket, suddenly anything works fine.
