### ISSUE TITLE
paket install on 3.10.0 is removing dll reference

### ISSUE THREAD

**Issue by feliara8** [fsprojects/Paket#1846]
### Description

I have a solution that is references rabbitmq client 3.6.0
After i package install, the rabbitmq reference is removed.
if i run paket install with an older version of paket this is not happening

**Comment by forki** [comment]
Can you please create a zip with repro sample?

**Comment by feliara8** [comment]
The project is private and its too big, is weird that paket its removing references, its there a workaround to tell paket to not remove references?

**Comment by forki** [comment]
No that's why I hoped you could create a small project which just contains
the package and shows that it removes the dll. I'm sure it can be isolated
from your big project. Thanks

On Aug 4, 2016 4:50 PM, "feliara8" <notifications@github.com> wrote:

The project is private and its too big, is weird that paket its removing
references, its there a workaround to tell paket to not remove references?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/1846#issuecomment-237576869>,
or mute the thread

**Comment by forki** [comment]
[RabbitmqSample.zip](https://github.com/fsprojects/Paket/files/401942/RabbitmqSample.zip)

I created a small project that installs rabbitmq. It looks like the reference to rabbitmq.client is set correctly. which dll is missing? What do I need to do?

**Comment by feliara8** [comment]
thanks for the example forki, i was able to fix the problem, when i converted from nuget, in the paket.dependencies file, it was restricting the framework to 4.5.2 and im on 4.
Changed the restriction and now its working.

I have another problem now,  i have a gruntfile.js in the root, after paket install its copied everywhere, i dont know why, and ive searched gruntfile.js in all the solution and i cant find anything related to gruntfile.js

**Comment by forki** [comment]
Wow. That sounds strange. Is it coming from a package? We have content settings that allow to copy only once

**Comment by forki** [comment]
Are you sure it's paket that copies the file?

**Comment by feliara8** [comment]
yes, after paket install, and set the file as a content withpaket true in the other csprojs

**Comment by feliara8** [comment]
i dont know paket obtains the info to treat that file diffrently

**Comment by feliara8** [comment]
![screen shot 2016-08-04 at 2 00 15 pm](https://cloud.githubusercontent.com/assets/7048028/17410834/d4e9ed34-5a4b-11e6-8230-3744c8f6f001.png)

**Comment by forki** [comment]
Do sent content:false for the package that includes the gruntfile

**Comment by feliara8** [comment]
its not coming from a package, the file its just in the root of the solution

**Comment by feliara8** [comment]
you were right, the specific gruntfile thats copied its coming from a package, ill try setting content to false

**Comment by feliara8** [comment]
i've managed to get all working, but i have one last problem, from visual studio everything builds fine.

But i have a rake task that builds everything.
Bundle exec rake gives me : ***.sln.projj error MSB3202 THe project file "***/.paket" was not found

**Comment by forki** [comment]
Looks like a path issue
