### ISSUE TITLE
pack single templatefile do not add dependencies to nuspec

### ISSUE THREAD

**Issue by lexarchik** [fsprojects/Paket#1847]
I have two projects ProjA, ProjB. 
Both have paket.template files. 
ProjA have reference to ProjB (in .csproj file)

I execute `paket pack output test` in solution folder 
In result package ProjA have a dependence with min version specified to package ProjB. 

But if  i execute `paket pack templatefile ProjA\paket.template output test` 
Result package ProjA do not have dependence to ProjB package.

I can't get logic of this behaviour.

Test solution in attached archive.
[PackSingleTemplateFile.zip](https://github.com/fsprojects/Paket/files/402847/PackSingleTemplateFile.zip)

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/17430898/3e1a7728-5af7-11e6-9fd6-30f70fdadd97.png)

the project got packed into the package.

I thin paket replaces project dependencies to nuget dependencies only when everything gets packed together.

**Comment by lexarchik** [comment]
Ok. But anyway it's unexpectedly that (1) and (2) commands have different output. 
1) `paket pack templatefile proj1.template`
`paket pack templatefile proj2.template`
2) `paket pack`

Maybe documentation needs some clarifing?

**Comment by forki** [comment]
yes I assume docs need clarification. Can you try to come up with a pull request to the docs that would have helped you to understand the situation?

**Comment by lexarchik** [comment]
ok, i'll try do it in this weekend

**Comment by forki** [comment]
:+1: thanks

**Comment by flin-zap** [comment]
I've just recently come across this. 

When specifying a template file with the "include-referenced-projects" switch, ProjB gets listed in ProjA's dependencies (without "include-referenced-projects", ProjB doesn't get listed at all) BUT ProjB's version in the depdency list becomes "0.0"!

Paket should be able to get the version for ProjB easily right? An alternative would be to allow the user to specify multiple template files (as opposed to using a long list of exclude's). We have a solution with 20+ projects and would like to pack only a few at any one time when developing

**Comment by lexarchik** [comment]
> ProjB's version in the depdency list becomes "0.0" 

It was fixed in 5.96.2

**Comment by flin-zap** [comment]
> It was fixed in 5.96.2
Thanks! We hit some issues with buggy versions previous and ended up pinning the version

**Comment by enricosada** [comment]
> It was fixed in 5.96.2

Closing
