### ISSUE TITLE
include-referenced-projects lead to strange changes in nuspec

### ISSUE THREAD

**Issue by lexarchik** [fsprojects/Paket#1848]
I have two projects ProjA, ProjB. 
Both have paket.template files. 
ProjA have reference to ProjB (in .csproj file)

I execute `paket pack output test` in solution folder 
In result package ProjA have a dependence with min version specified to package ProjB.

But if i execute `paket pack output test include-referenced-projects`
result package ProjA have a dependence without specified version to package ProjB
(`pin-project-references` do not change situation in this case)

Expected behavior: ProjA have a dependence with min version to ProjB (or with fixed version if `pin-project-references` was specified)

Sample solution in attached archive
[PackIncludeRefProj.zip](https://github.com/fsprojects/Paket/files/402862/PackIncludeRefProj.zip)

**Comment by jam40jeff** [comment]
@forki This behavior existed before the introduction of `pin-project-references`.  I am not too familiar with `include-referenced-projects` as I have not used it, but it seems to have always worked this way (which doesn't seem correct).  However, I am not sure I see much benefit to this command line option, as including a `paket.template` file for each project in the solution is a one-time cost which also provides other benefits.
