### ISSUE TITLE
Pack does not include referenced project.

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#1851]
### Description

I'm trying to use paket for packing [FsXaml](https://github.com/fsprojects/FsXaml) and the FsXaml.Wpf.dll does not get included in the package.

### Repro steps

Run pack on [FsXaml.Wpf.zip](https://github.com/fsprojects/Paket/files/414873/FsXaml.Wpf.zip)
Check if FsXaml.Wpf.dll is in the package.

### Known workarounds

Use `type file`

**Comment by forki** [comment]
paket.exe pack output out include-referenced-projects

==>

![image](https://cloud.githubusercontent.com/assets/57396/17618596/f0aed76a-6080-11e6-8411-541531c3f5f0.png)

**Comment by JohanLarsson** [comment]
Oh, I thought it included by default. Why is explicit `include-referenced-projects` needed in this case?

**Comment by forki** [comment]
that's always been an explicit parameter.

**Comment by forki** [comment]
maybe you can come up with a flag in the template file so that you don't need to type that every time

**Comment by forki** [comment]
so there is a new flag in the template file see http://fsprojects.github.io/Paket/template-files.html#Referenced-projects

you are welcome ;-)
