### ISSUE TITLE
Need a way to specify CopyToOutputDirectory in nuget content files

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/Paket#1852]
Suppose we have a nuget package that has a `content` folder, say [NewRelicWindowsAzure](https://www.nuget.org/packages/NewRelicWindowsAzure). Specifying this in a paket.references project
```paket.references
NewRelicWindowsAzure content: once
```
will generate the following in the coresponding *proj:
```xml
<Content Include="newrelic.cmd" />
```
Suppose now that I would like to change the CopyToOutputDirectory setting for a single item:
```xml
<Content Include="newrelic.cmd">
  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
```
Now, the problem occurs if re-run paket-update, which will cause the `CopyToOutputDirectory` to be wiped. This will happen, regardless of whether I insert a `<Paket>False</Paket>` element. The only way I could make paket preserve this configuration was to specify `content: none` in paket.references.

Is there a way I can make paket respect this configuration while still preserving `content: once`?

**Comment by forki** [comment]
http://fsprojects.github.io/Paket/dependencies-file.html#CopyToOutputDirectory-settings does this help?

**Comment by eiriktsarpalis** [comment]
@forki Cheers, I completely missed that one.
