### ISSUE TITLE
Cannot restore Git dependency on Azure web sites 

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Paket#1863]
### Description

I tried using Paket to install Git dependencies in Azure web sites - running Paket on Azure machine - and it fails to restore Git dependency:

```
Paket.exe 3.13.3.0 is up to date.
Paket version 3.13.3.0
Paket failed with:
	Checkout to D:\home\site\repository\paket-files\github.com\ionide\FsAutoComplete failed.
Message: Could not run "git clone file:///.paket\git\db\FsAutoComplete".
Error: 
Cloning into 'FsAutoComplete'...
fatal: 'D:/Program Files (x86)/Git/.paket/git/db/FsAutoComplete' does not 
appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Paket failed with:\r\n	
  Checkout to D:\home\site\repository\paket-files\github.com\ionide\FsAutoComplete failed.\r\n
  Message: Could not run "git clone file:///.paket\git\db\FsAutoComplete".\r\n
  Error: \r\nCloning into 'FsAutoComplete'...\r\n
    fatal: 'D:/Program Files (x86)/Git/.paket/git/db/FsAutoComplete' does not appear 
       to be a git repository\r\n
    fatal: Could not read from remote repository.\r\n\r\n
      Please make sure you have the correct access rights\r\n
      and the repository exists.\r\nD:\Program Files (x86)\
         SiteExtensions\Kudu\57.50815.2378\bin\Scripts\starter.cmd build.cmd deploy
```

### Repro steps

All I had in my `paket.dependencies` was 

```
framework: >= net40
source https://nuget.org/api/v2

nuget FAKE

git https://github.com/ionide/FsAutoComplete.git cors build:"build.cmd LocalRelease", OS: windows
git https://github.com/ionide/FsAutoComplete.git cors build:"build.sh LocalRelease", OS: mono
```

### Related information 

Version of Git on the Azure box is:

    git version 2.8.1.windows.1

**Comment by forki** [comment]
I don't have azure, so I'm not able to debug this. Any ideas what's going
wrong?

Am 21.08.2016 03:45 schrieb "Tomas Petricek" <notifications@github.com>:

**Comment by cdrnet** [comment]
To my understanding you do not have write permissions to `D:/Program Files (x86)` in Azure web sites.

**Comment by forki** [comment]
Weird. Why would we write there?

**Comment by isaacabraham** [comment]
@cdrnet Yeah, I would imagine that that's the problem, although the error message could be a little clearer.

**Comment by forki** [comment]
So if someone can find the place where we try to write there it would be really helpful

**Comment by tpetricek** [comment]
Is there a way to get more verbose log than with `-v`? 

The script runs in `D:\home\site\repository` and the output message says that it tries to check out into `D:\home\site\repository\paket-files\github.com\ionide\FsAutoComplete`, but then it says `Could not run "git clone file:///.paket\git\db\FsAutoComplete"`, which makes me think that perhaps (for some reason), the command that Paket runs is somehow incorrectly generated?

**Comment by forki** [comment]
-v is all we have. More details can only be added in pull request.

Am 21.08.2016 19:00 schrieb "Tomas Petricek" <notifications@github.com>:

**Comment by forki** [comment]
@tpetricek any chane for me to reproduce that with your project? like pushing more and more paket releases with more detailed logs and see what happens?

**Comment by forki** [comment]
when I run locally I get:

![image](https://cloud.githubusercontent.com/assets/57396/17859478/1529c53a-688a-11e6-8be4-a8a8ec18f50e.png)

so it's using my user path where it's using D:/Program Files (x86)/Git/ for you

**Comment by forki** [comment]
@tpetricek what's Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) giving you?

**Comment by tpetricek** [comment]
@forki Good psychic debugging skills!

> \> System.Environment.GetFolderPath(System.Environment.SpecialFolder.UserProfile);;
> val it : string = ""

**Comment by forki** [comment]
ok. then I need to work around that.

**Comment by forki** [comment]
any ideas for alternative location for git repo cache?

**Comment by tpetricek** [comment]
I suppose `LocalApplicationData` might work:

> \> System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData);;
> val it : string = "C:\DWASFiles\Sites\#1tryfsharp-autocomplete\LocalAppData"

(Unless the hash sign in the URL breaks something else :-))

Alternatively:

 - Allow an override via an explicitly specified environment variable? (Probably too much hassle)
 - Local directory of `paket.exe` (Not that useful, but would likely always work)

**Comment by forki** [comment]
ok let's test LocalApplicationData  - but tomorrow...

**Comment by tpetricek** [comment]
:+1:

**Comment by forki** [comment]
ok release new version with a fix. please try it

**Comment by tpetricek** [comment]
:tada: :clap: Everything working now!

**Comment by forki** [comment]
awesome!
