### ISSUE TITLE
Update / Install behave differently

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#1867]
### Description

Update / install generate different lockfiles.
I would expect that a ``install`` after an ``update`` is a no-op, but it actually changes the lockfile.

see the last few commits in https://github.com/0x53A/Paket/tree/issue-with-update-install

### Repro steps

Please provide the steps required to reproduce the problem

1. Open the Paket solution

2. Run update, it will update a few packages so changes are expected

3. Run install. I would expect there to be no changes, but this part changes:
![image](https://cloud.githubusercontent.com/assets/4236651/17839042/f1a133d0-67dc-11e6-9b38-912ccc26ed9f.png)

n. You can do this in a loop, running update again will revert the change from 3.

### Known workarounds

I'm not sure if this is actually relevant, if the different lockfiles cause a different behaviour.
A "workaround" is to just revert the changes before commiting.

### Related information 

I used the context menu in the VS extension:
![image](https://cloud.githubusercontent.com/assets/4236651/17839038/abdeb7dc-67dc-11e6-8ce4-c207ca8e25e7.png)

**Comment by forki** [comment]
thanks for reporting. should be fixed now
