### ISSUE TITLE
Hitting github limits

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#1873]
### Description

With a few file dependencies to github and a morning of updating of dependencies, I'm hitting the limits with

```
Paket failed with:
       	Could not find hash for https://api.github.com/repos/haf/YoLo/commits/master
```

or

```
Paket version 3.15.4.0
Paket failed with:
       	Could not find hash for https://api.github.com/repos/xyncro/chiron/commits/e0f4c122b21cb02d47ae3f4f83924b2dcb8dea9e
```

```
$ curl https://api.github.com/rate_limits
{
  "message": "API rate limit exceeded for 89.255.229.33. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A – spend a morning upgrading our solution

2. Step B – reach error message

### Expected behavior

Working calls to github.

**Comment by forki** [comment]
Please complain at github ;-)

can't you use git dependencies instead?

**Comment by haf** [comment]
It's not a problem of github AFAIK, it's an issue with unauthenticated requests.

**Comment by forki** [comment]
that sounds like a good way to go.

* add API token to deps file
* use API token for all github calls if it is set

**Comment by haf** [comment]
Yes, did you see my PR?

**Comment by forki** [comment]
oups there is already https://github.com/fsprojects/Paket/pull/1874 - nice

**Comment by haf** [comment]
Time to reopen!

![Uploading image.png…]()
