### ISSUE TITLE
paket.locked files: document

### ISSUE THREAD

**Issue by orloffm** [fsprojects/Paket#1876]
We've got McAfee in our corporate environment, and, obviously, it has a special rule to block creation of all ".locked" files. There was some virus related to that: https://www.pcrisk.com/removal-guides/9902-locked-ransomware. So paket.exe fails with "cannot acquire lock". I now need to explain this to IT guys, and it would be great to have some documentation page that clearly states the file name.

**Comment by forki** [comment]
Ok could you please send a pull request with whatever you think would convince your IT? I will merge and release asap

**Comment by orloffm** [comment]
No, I only wanted to notify, we handled that. Thank you.
