### ISSUE TITLE
FQA - Suggestions

### ISSUE THREAD

**Issue by hgleaves-ncuadmin** [fsprojects/Paket#1879]
As a newcomer to Paket (but also being someone growing tired of the NuGet pain points and I'm a F# developer) I have some initial questions, I think these would be good in your FAQ, here they are:

* Is Paket a complete alternative to NuGet or is it a better way of managing NuGet packages?
* Does Paket provide a way to convert our developed class libraries into "Pakets"?
* Does Paket provide a source of other people's Pakets as NuGet do at NuGet.org?
* Are there any Visual Studio add ons that provide GUI access to Paket functionality?

Finally:

* Is there a way to send you further FAQ candidates that you can consider adding to your FQA section on your website?

Thanks!

**Comment by forki** [comment]
I think most things are covered in the docs, but:

* Is Paket a complete alternative to NuGet or is it a better way of managing NuGet packages?

 Don't understand the difference!? It's a tool to manage nuget packages and other dependencies (git, github, http) in your porjects. But we don't replace nuget servers nor the package format.

* Does Paket provide a way to convert our developed class libraries into "Pakets"?

Yes. we have template files and a pack command (see http://fsprojects.github.io/Paket/template-files.html)

* Does Paket provide a source of other people's Pakets as NuGet do at NuGet.org?

Nope, but we are compatible to all nuget servers.

* Are there any Visual Studio add ons that provide GUI access to Paket functionality?

Yes we have addins for most editors: http://fsprojects.github.io/Paket/editor-support.html

**Comment by hgleaves-ncuadmin** [comment]
Thanks for these replies, but it was far from clear to me that Paket was simply an alternative means of working with NuGet packages, I'd formed the impression it was an alternative system with no reliance on NuGet.

Looking forward to the Visual Studio tool, I've been frustrated often by the gnarly workflow imposed on me by NuGet.
