### ISSUE TITLE
paket outdated detects older version as the newer version

### ISSUE THREAD

**Issue by kflu** [fsprojects/Paket#1885]
### Description

For xplot, I specify version 1.4.1 in the lock file. Running `outdated` reports 1.4.1 is outdated by 1.3.1
### Repro steps

Please provide the steps required to reproduce the problem

`paket outdated` output: (paket.[dependencies|lock] also attached)

```
Paket version 3.16.0.0
Resolving packages for group Main:
 - FAKE 4.38.3
 - FsLab 1.0.0
 - FsLab.Runner 1.0.0
 - Suave 1.1.3
 - Newtonsoft.Json 9.0.1
 - MathNet.Numerics 3.12.0
 - MathNet.Numerics.FSharp 3.12.0
 - Google.DataTable.Net.Wrapper 3.1.2
 - FSharp.Formatting 2.14.4
 - FSharp.Data 2.3.1
 - FSharpVSPowerTools.Core 2.3.0
 - FSharp.Compiler.Service 2.0.0.6
 - R.NET.Community 1.6.5
 - R.NET.Community.FSharp 1.6.5
 - XPlot.GoogleCharts 1.3.1
 - XPlot.GoogleCharts.Deedle 1.3.1
 - XPlot.Plotly 1.3.1
 - Deedle 1.2.5
 - Deedle.RPlugin 1.2.5
 - RProvider 1.1.20
 - FSharp.Charting 0.90.14
 - DynamicInterop 0.7.4
 - FSharp.Core 4.0.1.5
     unlisted
 - FSharp.Core 4.0.0.1
 - Http.fs 4.0.2
 - Hopac 0.3.13
Outdated packages found:
  Group: Main
    * XPlot.GoogleCharts 1.4.1 -> 1.3.1
    * XPlot.GoogleCharts.Deedle 1.4.1 -> 1.3.1
    * XPlot.Plotly 1.4.1 -> 1.3.1
```
# paket.dependencies

```
framework: >= net40
source http://nuget.org/api/v2

nuget FsLab
nuget FsLab.Runner
nuget FAKE
nuget Suave
```
# paket.lock

```
FRAMEWORK: >= NET40
NUGET
  remote: http://www.nuget.org/api/v2
    Deedle (1.2.5)
    Deedle.RPlugin (1.2.5)
      Deedle (>= 1.2.5)
      R.NET.Community (>= 1.6.4)
      R.NET.Community.FSharp (>= 1.6.4)
      RProvider (>= 1.1.13)
    DynamicInterop (0.7.4)
    FAKE (4.38.3)
    FSharp.Charting (0.90.14)
    FSharp.Compiler.Service (2.0.0.6)
    FSharp.Core (4.0.0.1)
    FSharp.Data (2.3.1)
    FSharp.Formatting (2.14.4)
      FSharp.Compiler.Service (2.0.0.6)
      FSharpVSPowerTools.Core (>= 2.3 < 2.4)
    FSharpVSPowerTools.Core (2.3)
      FSharp.Compiler.Service (>= 2.0.0.3)
    FsLab (1.0)
      Deedle (1.2.5)
      Deedle.RPlugin (1.2.5)
      DynamicInterop (0.7.4)
      FSharp.Charting (0.90.14)
      FSharp.Data (2.3.1)
      Google.DataTable.Net.Wrapper (3.1.2)
      MathNet.Numerics (3.12)
      MathNet.Numerics.FSharp (3.12)
      Newtonsoft.Json (9.0.1)
      R.NET.Community (1.6.5)
      R.NET.Community.FSharp (1.6.5)
      RProvider (1.1.20)
      Suave (1.1.3)
      XPlot.GoogleCharts (1.4.1)
      XPlot.GoogleCharts.Deedle (1.4.1)
      XPlot.Plotly (1.4.1)
    FsLab.Runner (1.0)
      Deedle (1.2.5)
      Deedle.RPlugin (1.2.5)
      DynamicInterop (0.7.4)
      FSharp.Charting (0.90.14)
      FSharp.Compiler.Service (2.0.0.6)
      FSharp.Data (2.3.1)
      FSharp.Formatting (2.14.4)
      FSharpVSPowerTools.Core (2.3)
      Google.DataTable.Net.Wrapper (3.1.2)
      MathNet.Numerics (3.12)
      MathNet.Numerics.FSharp (3.12)
      Newtonsoft.Json (9.0.1)
      R.NET.Community (1.6.5)
      R.NET.Community.FSharp (1.6.5)
      RProvider (1.1.20)
      Suave (1.1.3)
      XPlot.GoogleCharts (1.4.1)
      XPlot.GoogleCharts.Deedle (1.4.1)
      XPlot.Plotly (1.4.1)
    Google.DataTable.Net.Wrapper (3.1.2)
    Hopac (0.3.13)
      FSharp.Core (>= 3.1.2.5)
    Http.fs (4.0.2)
      FSharp.Core (>= 3.1.2.5)
      Hopac (>= 0.3.13)
    MathNet.Numerics (3.12)
    MathNet.Numerics.FSharp (3.12)
      FSharp.Core (>= 3.1.2.5)
      MathNet.Numerics (3.12)
    Newtonsoft.Json (9.0.1)
    R.NET.Community (1.6.5)
      DynamicInterop (0.7.4)
    R.NET.Community.FSharp (1.6.5)
      R.NET.Community (>= 1.6.5)
    RProvider (1.1.20)
      DynamicInterop (0.7.4)
      R.NET.Community (1.6.5)
      R.NET.Community.FSharp (1.6.5)
    Suave (1.1.3)
      FSharp.Core (>= 3.1.2.5)
    XPlot.GoogleCharts (1.4.1)
      Google.DataTable.Net.Wrapper
      Newtonsoft.Json
    XPlot.GoogleCharts.Deedle (1.4.1)
      Deedle
      XPlot.GoogleCharts (>= 1.4.1)
    XPlot.Plotly (1.4.1)
      Http.fs
      Newtonsoft.Json
```
### Expected behavior

Please provide a description of the behavior you expect.
### Actual behavior

Please provide a description of the actual behavior you observe. 
### Known workarounds

Please provide a description of any known workarounds.
### Related information
- Operating system
- Branch
- .NET Runtime, CoreCLR or Mono Version
- Performance information, links to performance testing scripts

**Comment by forki** [comment]
paket seems to be correct. 

From https://www.nuget.org/packages/fslab

![image](https://cloud.githubusercontent.com/assets/57396/17962022/11706e9a-6aaf-11e6-8ee5-729c0aae312f.png)

So FsLab is actually dependending on exactly XPlot.Plotly (1.3.1)

**Comment by kflu** [comment]
I think you may misunderstand my point. So there is an in Xplot 1.3.1 that was fixed in 1.4.1. So I updated the paket.lock file to force using 1.4.1. But when running paket outdated, it report that 1.3.1 is a more recent version than 1.4.1. This is very counterintuitive and functionally undesirable. Shouldn't we do something about this?

**Comment by matthid** [comment]
@kflu The real issue is that fslab "forces" 1.3.1 and has not specified a range.
One thing Paket could do better is tell you why it expects 1.3.1 (ie write "because of fslab requires 1.3.1")

**Comment by forki** [comment]
I agree the output could be better, but I still think it's correct. Paket outdated shows the difference that the resolver found to your lock file. And in rare cases this means a downgrade (e.g. if your lock file is invalid)

**Comment by kflu** [comment]
Is it really that the lock file is invalid? In my scenario, I know FsLab is depending on an outdated version of Xplot, which has a bug that was fixed in a later version. Without being able to change FsLab's dependency, I am fortunate to able to work it around by modifying the paket.lock file. Isn't it the point that paket recommands to check in paket.lock, so that the dependency versioning can be precisely controlled?

**Comment by forki** [comment]
Restore will always restore the version from the lock file. That's considered a feature. 

"invalid" is maybe a wrong word here. What you see is only the result of the resolver having a new opinion about the best resolution.

**Comment by kflu** [comment]
Got it. Thanks! I'm really happy that paket.lock lets me to work this issue around pretty easily!

**Comment by forki** [comment]
Maybe a good mental model for outdated command would be if you try to send it as "paket what-if-I-update"

**Comment by forki** [comment]
Or "paket what-if-I-resolve-right-now"

**Comment by enricosada** [comment]
> Got it. Thanks! I'm really happy that paket.lock lets me to work this issue around pretty easily!

Closing
