### ISSUE TITLE
paket pack buildconfig is case sensitive

### ISSUE THREAD

**Issue by pavelhritonenko** [fsprojects/Paket#1889]
### Description

`buildconfig` parameter for `packet pack` command is case sensitive

### Repro steps

1. Run `paket pack output bin buildconfig Release buildplatform AnyCPU`
2. Run `paket pack output bin buildconfig release buildplatform AnyCPU`

pay attention that buildconfig value is different in these cases `release` and `Release`

### Expected behavior

Results of these commands are same

### Actual behavior

```
$ paket pack output bin buildconfig release buildplatform AnyCPU
Paket version 3.16.3.0
Paket failed with:
        Unable to find release output path node in file C:\projects\project\src\project\project.fsproj targeting the AnyCPU platform
```

```
$ paket pack output bin buildconfig Release buildplatform AnyCPU
Paket version 3.16.3.0
Packed: C:\projects\project\src\project\paket.template
0 seconds - ready.
```

### Known workarounds

Use correct config names in your scripts

### Related information 

* Windows 10 build 14393.82
* paket 3.15 / 3.16

**Comment by forki** [comment]
mhm @cloudRoutine do you know if this is indeed case-insenstive in MSBuild?

**Comment by pavelhritonenko** [comment]
It's definitely case insensitive in MSBuild, I found this bug while was writing Fake build script and pack step is after build step.

**Comment by forki** [comment]
@cloudRoutine or @amazingant it looks like this code is from one of you. Could you please help? I'm a bit lost

**Comment by cloudRoutine** [comment]
This used to be a common Argu issue but I fixed that [a long time ago](https://github.com/fsprojects/Argu/commit/8008cc0ad1253880d25e20662034159426062cc2), I'm not sure what's going on here but I'll take a look.

**Comment by forki** [comment]
no I think this has nothing to do with argu. It's the way how we try to find the right configuration in a csproj XML haystack

**Comment by amazingant** [comment]
@forki the commit @cloudRoutine linked to might be the same fix needed here though. Quick look on my part, might just need to adjust [this line](https://github.com/fsprojects/Paket/blame/2ca6b5427fb6406ebf845b39f913e332c8d233b6/src/Paket.Core/ProjectFile.fs#L359)? I'll have to try it to be sure, but that should be it.

**Comment by forki** [comment]
I'll happily merge pull requests...

**Comment by amazingant** [comment]
If it works, the change is [here](https://github.com/amazingant/Paket/commit/6eb940882d90da0cacd164234e0189bd71922fd1); will PR after I find or create a test for this. Anyone have a preference for `StringComparison.OrdinalIgnoreCase` instead of `StringComparison.InvariantCultureIgnoreCase`? I'm not terribly sure what the difference is.

**Comment by cloudRoutine** [comment]
`StringComparison.OrdinalIgnoreCase` is faster and all that's necessary for this usecase
