### ISSUE TITLE
Additional caches supposed to be optional, but Paket still complains when cannot access it

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1894]
Additional caches configured in paket.dependencies supposed to be optional, right? They are purely for speed and reliability and not required. 
I have configured one cache on the network share and it works fine, but when developers work offline the share is not accessible and developers get error messages like
Could not copy C:\Users\<name>\AppData\Local\NuGet\Cache\Autofac.Owin.3.1.0.nupkg to cache \\<machine>\Temp\PaketDependenciesCache\

First of all, those errors confuse developers and I would prefer not to see them at all or only see them in verbose mode.

Second issue which contributes to confusion is that error messages are not generated for all packages, but only for a first five or six. This makes people think that there is something wrong with those five or six packages specifically.

Could you please make those messages verbose level and explain why only few packages cause errors?

Thank you!
Konstantin

**Comment by forki** [comment]
Ok the following happens: we probe the cache and if we see it failing then we mark it internall as ignore.
You see that warning multiple times since we try to download in parallel.
