### ISSUE TITLE
Microsoft.Bcl causing warnings during install

### ISSUE THREAD

**Issue by tastyeggs** [fsprojects/Paket#1896]
After converting a solution to use Paket, I see a lot of these warnings (1 per project) when I do a paket install:

`Package Microsoft.Bcl contains libraries, but not for the selected TargetFramework net461 in project`

The corresponding entry in paket.dependencies is:
`nuget Microsoft.Bcl 1.1.10 `

Am I doing something wrong?

**Comment by forki** [comment]
this should be fixed in latest alpha version.
