### ISSUE TITLE
Paket.template dependencies

### ISSUE THREAD

**Issue by Thorium** [fsprojects/Paket#1899]
Most of the fsharp projects have both net35 and net40 targets.
Then the end of the paket.lock looks something like this:

```
tags
    F#, fsharp, library
files
    ../bin/net45/MyLibrary.dll ==> lib/net45
    ../bin/net35/MyLibrary.dll ==> lib/net35
dependencies
    FSharp.Core ~> LOCKEDVERSION
```

If FSharp.Core is locked to v4 this can never work as it's not compatible with net35?

So is the best practice to:

 * Leave FSharp.Core dependency hidden and hope people has it even if it's not anymore in the default VS-installation?
 * Not use paket.template but nuget.nuspec? But ProjectScaffold already made the template, why it guides to this non-sustainable-way?
 * Or is there any solution currently?
 
I would like to have possibility create something like the dependency tree in this package shows: https://www.nuget.org/packages/LinqKit/

**Comment by forki** [comment]
Why do you look the version of fsharp.core?

Am 30.08.2016 1:04 vorm. schrieb "Tuomas Hietanen" <notifications@github.com

**Comment by matthid** [comment]
The v4 `FSharp.Core` nuget package has a `net20` folder so it should be compatible with `net35`.
So it shouldn't be a problem at all?

**Comment by Thorium** [comment]
Ok! So if [package](https://www.nuget.org/packages/Linq.Expression.Optimizer
) contains binary dll for net45, net35 and netcore it should work automatically?

Good.

**Comment by forki** [comment]
Yep

Am 31.08.2016 1:50 nachm. schrieb "Tuomas Hietanen" <
notifications@github.com>:
