### ISSUE TITLE
<When/> clauses added to early when adding global framework: >= net451 constraint. $TargetFrameworkIdentifier is not set (yet)

### ISSUE THREAD

**Issue by jbrunet** [fsprojects/Paket#1901]
### Description

when applying a global framework: >= net451 constraint, _when_ clauses are placed too early. $(TargetFrameworkIdentifier) is not set (yet) and thus the related targets are not imported

### Repro steps

1. Step A

create a blank csproj

paket.references content:
```
CodeGeneration.Roslyn.BuildTime
Microsoft.AspNet.WebApi.Core
```

paket.dependencies content:

```
source https://www.nuget.org/api/v2
nuget CodeGeneration.Roslyn.BuildTime
nuget Microsoft.AspNet.WebApi.Core framework: >= net451
```

`.paket\paket install`

the modified project is fine

2. Step B

modify paket.dependencies to move the constraint globally:
modified paket.dependencies content:

```
framework: >= net451
source https://www.nuget.org/api/v2
nuget CodeGeneration.Roslyn.BuildTime
nuget Microsoft.AspNet.WebApi.Core
```

`.paket\paket install`

### Expected behavior

The _when_ clauses should be at the same place in the csproj

### Actual behavior

a _when_ clause regarding CodeGeneration.Roslyn.BuildTime.targets is placed early in the project.
The problem is that $(TargetFrameworkIdentifier) is not set (yet) hence the when clause is ignored.
Consequently, the _Import Target=..._ line at the end of the project never occur since the condition is false.

### Known workarounds

place framework: >= net451 on each nuget in paket.dependencies

### Related information 

* Operating system Windows 7
* .NET Runtime

**Comment by klettier** [comment]
Fixed [here](https://github.com/fsprojects/Paket/commit/75dcb3b9b2763fa68ab2d4cff5ff9ff6a7a317da)

**Comment by jbrunet** [comment]
awesome. thanks !
