### ISSUE TITLE
Top-level framework restriction override package-level restriction

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#1904]
### Description

On our internal NuGet server we host copies of a number of packages from nuget.org. Shouldly is one of them. Shouldly has no dependencies, except for framework version netstandard1.3 if you use .Net Core.

The problem occur when I try to limit the framework to .net 4.5.1 for this particular package.

```
// OK
source http://server/feed
nuget Shouldly framework: net451

// Not ok
framework: net461
source http://server/feed
nuget Shouldly framework: net451
```

Paket will then try to resolve the .Net core dependencies for Shouldly, and these packages are not available on our internal server.

### Expected behaviour

I would expect the top-level framework modifier to only apply to packages without any explicit framework tag set.

### Known workarounds

1. Override individual packages.

### Related information 

* Paket version  3.17.2.0

**Comment by trondd** [comment]
It might be worth noticing that this only happens with the `Shouldly` package. Could it be related to the metadata section in the `.nuspec` file?

```
<dependencies>
      <group targetFramework=".NETFramework3.5" />
      <group targetFramework=".NETFramework4.0" />
      <group targetFramework=".NETFramework4.5.1" />
      <group targetFramework=".NETStandard1.3">
```

**Comment by trondd** [comment]
And one more thing: When resolving Shouldly directly from nuget.org - where the .Net Standard 1.3 packages are available - `Paket` ends up with this:

``` xml
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.1'">
      <ItemGroup>
        <Reference Include="Shouldly">
          <HintPath>..\..\packages\Shouldly\lib\net451\Shouldly.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>```

**Comment by forki** [comment]
can you please retry with latest?

**Comment by trondd** [comment]
This is still an issue with Paket `3.23.2.0`
