### ISSUE TITLE
TODOs to complete Dotnetcore Support

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#1909]
See https://github.com/fsprojects/Paket/pull/1785 for initial work. 
- [ ] Patch `paket pack` to include dependency groups for all detected binaries. 
- [ ] Completely get rid of `isMono` (now obsolete) 
- [ ] proper handling of `ref` and `lib` folder, see https://github.com/fsprojects/Paket/issues/1895#issuecomment-244387593
- [ ] Dotnetcore application (ie paket.exe)
- [ ] Dotnetcore tool (ie to use it like mergenupkg (https://github.com/fsprojects/Chessie/blob/master/src/Chessie/project.json#L33))
- [ ] Testing (At least execute a limited subset of the current suite)
- [ ] Add support into paket for the "runtime" folder
- [ ] Add support for parsing and working with 'runtime.json' (Microsoft.NETCore.Platforms),
     See [here](https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/build_projects/dotnet-cli-build/CompileTargets.cs#L40)
- [ ] Re - Add missing features in NETSTANDARD (possible future) or Port Features to Full Net
  - [ ] WebProxy
  - [ ] App.Config?
  - [ ] Use HttpClient in Full Net

**Comment by enricosada** [comment]
Closing.

.net core is tracked in https://github.com/fsprojects/Paket/issues/2875
