### ISSUE TITLE
Nexus 3: Could not find package Nuget.CommandLine

### ISSUE THREAD

**Issue by WebDucer** [fsprojects/Paket#1912]
### Description
If I use Nexus 3 as nuget package repository (with default configured neget proxy to nuget.org), I got problems with paket. I don't know, if the problem is on the Nexus 3 side or on paket side. So I post the issue to both.

Problem 1:

If I try to resolve the package `Nuget.CommandLine` I got the following error by `paket update` command:
```
C:\Temp\NexusTest>.paket\paket.exe update
Paket version 3.19.1.0
Resolving packages for group Main:
Paket failed with:
        Could not find versions for package Nuget.CommandLine on http://localhost:8081/repository/nuget-group.
```

Problem 2:
I build our solutions with FAKE. In Interaction with Nexus 3 the `paket update`  took very long, if I have FAKE in it (I think the problem here is on Nexus 3 side, because it tries to download all the versions of FAKE - and there are a lot of them).
```
C:\Temp\NexusTest>.paket\paket.exe update
Paket version 3.19.1.0
Resolving packages for group Main:
 - FAKE 4.39.1
Locked version resolution written to C:\Temp\NexusTest\paket.lock
Garbage collecting NUnit
1 minute, 27 seconds - ready.
```

### Repro steps

I prepared a simple project to reporoduce the steps:

https://github.com/WebDucer/Nexus3PaketIssue

1. Install the Docker container for Nexus 3

```
docker run -d -p 8081:8081 --name nuget-repo sonatype/docker-nexus3
```

2. Use the project above to execute `paket update` against nuget.org or Nexus3 as source (comment the unneded sources out).

### Expected behavior

1. `paket update` should resolve `Nuget.CommandLine`
2. `paket update` should update quicker for packages with a lot of versions

### Actual behavior

1. `paket update` stops with error if the package `Nuget.CommandLine` is in it.
2. `paket update` need a lot of time, if package `FAKE` is in it.

### Known workarounds

Using of two sources (nuget.org on the first place and Nexus 3 on the second).

**Comment by forki** [comment]
why would the empty nexus docker container return versions for NuGet.CommandLine?

**Comment by WebDucer** [comment]
After the default installation of Nexus 3 this has three nuget repositories

1. Nuget proxy (cache for nuget.org => delegate the calls to nuget.org, if no package of desired version is in cache)
2. Hosted repository (repository to store internal nuget packages)
3. Group repository (bundle proxy and internal repositories under one URL)

So the call to the group should resolve the packages (works well with a lot of packages)
```
C:\Temp\NexusTest>.paket\paket.exe update
Paket version 3.19.1.0
Resolving packages for group Main:
 - NUnit 3.4.1
Locked version resolution written to C:\Temp\NexusTest\paket.lock
Garbage collecting FAKE
Garbage collecting NuGet.CommandLine
8 seconds - ready.
```

```
C:\Temp\NexusTest>.paket\paket.exe update
Paket version 3.19.1.0
Resolving packages for group Main:
 - FAKE 4.39.1
Locked version resolution written to C:\Temp\NexusTest\paket.lock
Garbage collecting NUnit
1 minute, 27 seconds - ready.
```

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/18311066/97e87618-7502-11e6-9ed3-e4a27d9d63b6.png)

**Comment by WebDucer** [comment]
Your screeshot shows Nexus 2 installation, not Nexus 3. In Nexus 3 nuget repositories already configured.

**Comment by forki** [comment]
I don't get the nexus 3  docker running
is your command line correct?

**Comment by forki** [comment]
p 8081:8081 did the trick. container is running now

**Comment by forki** [comment]
lol wtf is this thing doing? Caching all fake versions if you try to install one? WTF

**Comment by WebDucer** [comment]
I send already the request to sonatype for this :) Perhaps they have an answer to this strange behaviour.

**Comment by forki** [comment]
regarding fake update: second update is much faster. So that's only nexus issue.

**Comment by forki** [comment]
regarding NuGet.CommandLine: if you change casing to NuGet.CommandLine it works. so sonatype nexus has a casing issue.

**Comment by WebDucer** [comment]
I got the following answer from sonatype:

> Hi Eugen,
> 
> For Problem 1, I have managed to get it to work if you change the package name from "Nuget.CommandLine" to "NuGet.CommandLine" in the file paket.dependencies.
> 
> For Problem 2, I agree it does take a long time.
> 
> This is what I see in the request logs of Nexus 3
> ```
> 192.168.0.111 - - [07/Sep/2016:13:38:12 +0100] "GET /repository/nuget-group/FindPackagesById()?id='FAKE' HTTP/1.1" 200 101628 101
> 192.168.0.111 - - [07/Sep/2016:13:38:12 +0100] "GET /repository/nuget-group/FindPackagesById()?$skip=40&id=%27FAKE%27 HTTP/1.1" 200 101720 109
> 192.168.0.111 - - [07/Sep/2016:13:38:12 +0100] "GET /repository/nuget-group/FindPackagesById()?$skip=80&id=%27FAKE%27 HTTP/1.1" 200 101766 107
> 192.168.0.111 - - [07/Sep/2016:13:38:12 +0100] "GET /repository/nuget-group/package-versions/FAKE?includePrerelease=true HTTP/1.1" 404 1823 555
> 192.168.0.111 - - [07/Sep/2016:13:38:12 +0100] "GET /repository/nuget-group/Packages?$filter=tolower(Id)%20eq%20'fake' HTTP/1.1" 404 1823 1
> 192.168.0.111 - - [07/Sep/2016:13:38:12 +0100] "GET /repository/nuget-group/FindPackagesById()?$skip=120&id=%27FAKE%27 HTTP/1.1" 200 102144 102
> 192.168.0.111 - - [07/Sep/2016:13:38:12 +0100] "GET /repository/nuget-group/FindPackagesById()?$skip=160&id=%27FAKE%27 HTTP/1.1" 200 102439 104
> ```
> I am not familiar with paket and we do not test with paket. Did this paket tool work fine with Nexus 2?
> 
> Kind Regards,
> Mahendra
>

**Comment by forki** [comment]
as I said: casing bug and to eager caching bug in nexus

**Comment by WebDucer** [comment]
Thanks for help.

**Comment by WebDucer** [comment]
Can I log the paket requests that goes to Nexus when I execute `paket update`?

**Comment by forki** [comment]
-v will show you some. Also fiddler can help
