### ISSUE TITLE
Projects removed from Solution

### ISSUE THREAD

**Issue by pdfforge** [fsprojects/Paket#1917]
### Description

We now had a very strange issue. In one commit in PDFCreator, we saw that a lot of projects were removed from the solution file and had no explanation for it. I have been able to observe this twice since then and it seemed to happen when a `paket update` could find a new version of a dependecy. After it was discovered the first time though, this would not happen even if I would reset the repository and clean the cached files from nuget. So this might also be a coincidence with something else happening at the same time.

Is there a situation where paket would modify the .sln file? In our case, the projects have been remove very cleanly including the references from other projects, which is even more odd.

So, please do not see this as accusation that Paket would be doing something wrong, we just want to check what is going on and would like to see if there is a chance that this might be the root of the problem or if we have to look at different ideas.

### Repro steps

Unfortunately, I have no idea how to reproduct it yet.

**Comment by forki** [comment]
We don't touch sln files.

Am 09.09.2016 2:33 nachm. schrieb "Philip" <notifications@github.com>:

**Comment by pdfforge** [comment]
Ok, that's good, but we have to continue on our quest towards the root ;-)
