### ISSUE TITLE
Puzzled

### ISSUE THREAD

**Issue by Korporal** [fsprojects/Paket#1919]
I've been reading through the documentation and some things are unclear.

1. There are many references to running paket commands - but where does one do this? In a console window? if so what folder should one set for the consoles current dir? the project root or some other place?
2. I installed the VS 2015 add-in, I see a menu for stuff like 'Convert from nuget' 'Update all packages' and so on, but expected to see something like 'Paket interactive window' but there's nothing like this.
3. Is there any support for an add-in that allows me to build a paket for a project? and then publish it? or are these things only posssible by running text commands in some place/window?

Sorry if these sound dumb but as I said, I read through the docs and didn't find specifics in these areas.

Thx

Others have been bewildered by this too, for example:

http://stackoverflow.com/questions/31257207/how-to-use-paket-from-command-line

the explanations on that page are rather involved and idiosyncratic - is there not a simpler way to do some of these things?

**Comment by isaacabraham** [comment]
1. Best practice is to place Paket in its own .paket folder at the top of your repository. You don't have to do this, but it's consistent with how everyone does it. Paket is smart enough to look in all other sibling folders to find project file etc.

You typically execute Paket commands from there command line, or via some IDE extension e.g. VS2015 and Code both have a Paket plugin.

2. You already have a Paket interactive window built into the OS, it's called Command Prompt :)

3. I'm not sure what you're think of when we mean build a Paket. Do you just mean the list of dependency files (just a text file with the list of dependencies) or building a nuget package? There is indeed support for building nuget packages via Paket, and there's docs on the site.

**Comment by Korporal** [comment]
Thank you.

It was unclear that we were to run cmd.exe in the same folder as the .paket file - thanks for explaining.

Can you clarify, when you refer to situating the .paket folder at the "top of your repository" are you referring to a containing Git repo or the root folder of the solution? We tend to store multiple solutions within a single Git repo so I'm not sure if you mean repo folder or solution folder.

Thx

**Comment by isaacabraham** [comment]
Sorry, I wasn't clear at all. So first point - Paket.exe and your .dependencies / .lock *do not* have to be in the same folder. I would suggest a common format is: -

.paket/paket.exe
paket.dependencies
paket.lock

You can also use the Paket.bootstrapper (which you commit into source control and include in the .paket folder) to ensure you always have the most recent version of Paket.exe.

Regarding multiple solutions in a single repo, I think you have two choices: -

1. Have one paket.dependencies file in each solution folder. This assumes that there is no common dependencies across your solutions. An alternative solution is to have a single dependencies file at the very top level, shared by all your applications. Now, normally this would mean that you're force to upgrade dependencies across applications simultaneously, which is not always desirable. In such a case, you can look at Paket's Groups feature, which allow you to store multiple "groups" of dependencies in a single Paket file, each with different versions. So you might have one group for each application.

I can't suggest which one of these three options is the right one for you - it depends on your situation - but I suggest one of them will be a good fit for you.

**Comment by Korporal** [comment]
This is very much appreciated, thanks for explaining.

**Comment by forki** [comment]
can we close this?

**Comment by dsyme** [comment]
@forki Yes we can
