### ISSUE TITLE
In 'bindingRedirect' element, 'oldVersion' range of '0.0.0.0-999.999.999.999' does not cover all possible versions

### ISSUE THREAD

**Issue by dmitryvk** [fsprojects/Paket#1930]
### Description

There are some libraries that have major version greater than 999 (e.g., https://www.nuget.org/packages/Stimulsoft.Reports.Web.Trial/ has version 2016.3.14). Because of this, the binding redirect generated by Paket does not apply to assemblies from those packages.

I propose to use range like '0.0.0.0-65535.65535.65535.65535' (which is a maximum possible version for .net assembly) to ensure that all possible versions are covered.

### Repro steps

1. Unpack the attachment
[paket-redirect-999-repro.zip](https://github.com/fsprojects/Paket/files/497859/paket-redirect-999-repro.zip)

2. Run `paket install`

### Actual behavior

App.config file contains this fragment:

```
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="Stimulsoft.Base" publicKeyToken="ebe6666cba19647a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="2016.1.3.0" />
  </dependentAssembly>
```

(note that 2016.1.3.0 is outside of range 0.0.0.0-999.999.999.999; so this redirect will not apply to earlier versions of this assembly)

### Expected behavior

`oldVersion` attribute should have range that at least covers the version 2016.1.3.0.

**Comment by isaacabraham** [comment]
That's an awesome bug :-)

Could you submit a PR to fix this?

**Comment by dmitryvk** [comment]
Sure, I'll submit a PR sometime soon.

**Comment by forki** [comment]
;-)

**Comment by isaacabraham** [comment]
P.S. Don't make the PR go up to 2016.1.3.1 ;-)
