### ISSUE TITLE
Firewall Exception/Rule for Paket Servers

### ISSUE THREAD

**Issue by smaglio81** [fsprojects/Paket#1933]
### Description

Our networking guy doesn't like to do proxy servers. He only wants to put firewall rules in place for the server applications that reach outside our network. For example, our build server downloads files from nuget.org.

When paket.bootstrapper.exe runs, it will check for updates against Paket servers. Is there a DNS name or IP range I can give him?

**Comment by forki** [comment]
/cc @part-timedev

Am 01.10.2016 1:17 vorm. schrieb "Steven Maglio" <notifications@github.com>:

**Comment by smaglio81** [comment]
I see, so the default behavior is to try and download from www.nuget.org and then fallback to github.com.
