### ISSUE TITLE
Xamarin paket addin cannot install dependencies

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#1935]
### Description

When I try to install dependencies for an F# project using Xamarin, I get the following error:

> Resolving packages:
>  - Informedica.GenUnits.Lib 0.4.5-beta
> Couldn't get package details for package Informedica.GenUnits.Lib on any of ["https://nuget.org/api/v2"].
> 
> Could not install paket dependencies.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a fresh F# project in Xamarin

2. Use the Xamarin paket addin to install a dependency.

### Expected behavior

The dependency gets installed

### Actual behavior

The error as described above

### Known workarounds

Installing the dependencies using paket command line works fine.

Also see: http://forums.xamarin.com/discussion/79487/paket-couldnt-get-package-details/p1?new=1.

**Comment by forki** [comment]
Please report this to the Xamarin plugin project itself. We don't maintain it here. Sorry

**Comment by mrward** [comment]
This bug has been [filed against the Paket addin](https://github.com/mrward/monodevelop-paket-addin/issues/5) for MonoDevelop/Xamarin Studio.
