### ISSUE TITLE
Locked sources change when paket update is run and multiple sources have the same nugets

### ISSUE THREAD

**Issue by Gonnagle** [fsprojects/Paket#1938]
### Description

Can sources that are to be used for each package somehow be freezed?

We have couple sources defined in our project and many of the packages are found from more than one of the sources. When I issue a `paket update` after making changes to the `paket.dependecies` it seems that paket might somewhat randomly change the source it uses for a given nuget. How is the source to be used resolved?

This behavior makes it harder to track what really changed (for example which transitive dependencies were updated, which removed and which added?). Is there a way to prevent paket from changing from one source to another when it's not necessary (version is not to be changed or can be found from the same source as used previously)?

### Repro steps

With a configuration where multiple sources with same nugets available:

1. Make changes to `paket.dependencies` (e.g. update versions)
2. run `paket update`

For example [this test repo](https://github.com/Gonnagle/paket-multiple-sources-test). I added a local source with few of the nugets downloaded in it and the run the update. While updating the packages paket changed to use the local repository on some of nugets making it harder to track what really changed like can be seen in [this commit](https://github.com/Gonnagle/paket-multiple-sources-test/commit/af1ccd98d17537ecf9609e3fddb2aa224a0f516e).

**Comment by Gonnagle** [comment]
In this example Commong.Logging.Core and Flurl.Http.Signed jump from nuget.org to private myget feed causing additional 'noise' to the diff and thus making it harder to track what really was changed. In contrast updates on Flurl.Signed and ServiceStack.* nugets can easily be observed as they remain in same sources as previously and don't jump to another part of the file.

```diff
diff --git a/Source/paket.lock b/Source/paket.lock
index fa0aac3..562b793 100644
--- a/Source/paket.lock
+++ b/Source/paket.lock
@@ -32,7 +32,6 @@ NUGET
     Chutzpah (4.0.3)
     Common.Logging (3.3.1)
       Common.Logging.Core (>= 3.3.1)
-    Common.Logging.Core (3.3.1)
     Common.Logging.Log4Net1213 (3.2)
       Common.Logging (>= 3.2)
       log4net (>= 1.2.13)
@@ -55,10 +54,7 @@ NUGET
     FluentValidation.MVC5 (5.6.2)
       FluentValidation (>= 5.6.2)
       Microsoft.AspNet.Mvc (>= 5.1 < 5.3)
-    Flurl.Http.Signed (0.7)
-      Flurl.Signed (>= 1.0.10)
-      Newtonsoft.Json (>= 6.0.3)
-    Flurl.Signed (1.0.10)
+    Flurl.Signed (2.0)
     FSharp.Control.AsyncSeq (1.13)
     FSharp.Core (4.0.0.1)
     FSharp.Text.RegexProvider (0.0.7)
@@ -235,13 +184,13 @@ NUGET
     RabbitMQ.Client (3.5.7)
     Select2.js (3.5.2)
       jQuery (>= 1.7)
-    ServiceStack.Common (4.0.52)
-      ServiceStack.Interfaces (>= 4.0.52)
-      ServiceStack.Text (>= 4.0.52)
-    ServiceStack.Interfaces (4.0.52)
-    ServiceStack.Redis (4.0.52)
-      ServiceStack.Common (>= 4.0.52)
-    ServiceStack.Text (4.0.52)
+    ServiceStack.Common (4.5)
+      ServiceStack.Interfaces (>= 4.5)
+      ServiceStack.Text (>= 4.5)
+    ServiceStack.Interfaces (4.5)
+    ServiceStack.Redis (4.5)
+      ServiceStack.Common (>= 4.5)
+    ServiceStack.Text (4.5)
     Should (1.1.20)
     SimpleRESTServices (1.3.0.2)
       Newtonsoft.Json (>= 5.0.6)
@@ -281,6 +215,10 @@ NUGET
     YUICompressor.NET (2.7)
       EcmaScript.Net (>= 1.0.1)
   remote: https://www.myget.org/F/private-feed
+    Common.Logging.Core (3.3.1)
+    Flurl.Http.Signed (0.7.0)
+      Flurl.Signed (>= 1.0.10)
+      Newtonsoft.Json (>= 6.0.3)
```

**Comment by forki** [comment]
I think it's prefering nuget sources from top to bottom

**Comment by Gonnagle** [comment]
Ok. We had our private myget feed defined before nuget.org. Some nugets are only in our own feed and others should be found from both (nuget packages mirrored to the private feed). Still most of the nugets are fetched from nuget.org and occasionally some change to the private feed...

I now changed nuget.org as our first source hoping it'll now be more consistent on using it as primary source and only fallback to our private feed on packages/versions that don't exist in nuget.org. I'll get back tomorrow when I've had time to examine if this stops used sources to change between updates.

**Comment by Gonnagle** [comment]
Seems that reordering the sources might have resolved this for us.
