### ISSUE TITLE
Paket wrongly pulls in .NETStandard dependencies

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1940]
Our solution targets .NET 4.6.1, which is reflected in each project settings and at the top of paket.dependencies we have "framework: net461". Among referenced packages we have Microsoft.IdentityModel.Clients.ActiveDirectory. It does not have any dependencies for .NET 4.6.1, but it has a ton of dependencies for ".NETStandard1.4"
In Paket.lock file it looks like
    Microsoft.IdentityModel.Clients.ActiveDirectory (3.13.4)
      System.Collections (>= 4.0.11)
      System.Collections.Concurrent (>= 4.0.12)
      System.Diagnostics.Debug (>= 4.0.11)
      System.Globalization (>= 4.0.11)
      System.IO (>= 4.1)
      System.Linq (>= 4.1)
      System.Net.Http (>= 4.0.1)
I.e. paket.lock loses information that dependencies are only for .NETStandard and make them unconditional dependencies! Results of that decision are catastrophic, because  System.Net.Http (>= 4.0.1) means the version built into .NET 4.6.1 is not good anymore (it is 4.0.0) and it pulls in newer System.Net.Http package. This causes chain reaction and the build get broken beyond repair. 

So as I see it the root cause of the problem is that Paket drops .NETStandard framework filter and pulls dependencies regardless of it. 

Konstantin

**Comment by forki** [comment]
System.Net.Http is compatible with net46x

![image](https://cloud.githubusercontent.com/assets/57396/19104830/f62d882a-8ade-11e6-8319-f9b7780d6875.png)

I assume you need to add `nuget System.Net.Http redirects:force` to your deps file and reference System.Net.Http from nuget in your app.

**Comment by konste** [comment]
Steffen, specifics of System.Net.Http is not the point here - I just used it as an example to illustrate the problem. For quite some time we had a stable state when running "paket install" would do nothing because everything is up to date already. Then something changes and Paket decided to bring in all extra dependencies I listed above with the versions 4.0.x This is wrong already! We don't need those dependencies in paket.lock. I expected that those new dependencies would never be added to csproj files, but another bug (?) causes them to still be referenced even though the projects clearly target ONLY .NET 4.6.1
Instead of looking for a workaround, how about we fix those two problems with the Paket?

**Comment by forki** [comment]
It's not a workaround. 

AFAIK the .NET Standard 1.4 is an alias for .NET 4.6.1

**Comment by forki** [comment]
I just checked with nuget.exe - it also thinks that System.Net.Http needs to be installed here

**Comment by isaacabraham** [comment]
@konste If this is a problem (and judging from what I'm reading, that may or may not be the case) - why not submit a PR to fix the issue? I'm sure @forki would be happy to see that in order to better understand what the problem is.

Accusing @forki over just "looking for a workaround" and adding a passive-aggressive "how about we fix those two problems" isn't the best way to get things moving - instead, I'd suggest actually taking the time to better explain what this is, or as mentioned, put in a proposed fix as a PR.

Cheers

**Comment by Gonnagle** [comment]
We are currently struggling with similar problems with couple of our solutions. I'm quite baffled with how this all (framework restrictions and netstandard stuff etc.) should work and what really is the root cause here... 

We tried to do what @forki suggested, but could not get it work yet. I'll try to dig deeper and maybe even come up with a repro.

**Comment by Rickasaurus** [comment]
This has been an issue for us too. There also seems to be a strange dependency on the ordering of the paket.dependenices file. 

This doesn't pull:
`framework: NET452
redirects: on

source https://nuget.org/api/v2

# The setting below means your libraries will assume a minimum of FSharp.Core 
# for F# 4.0 (nuget package 4.0.0.1). If you would like to assume a higher minimum
# then change to 4.1.17 or later.

nuget FSharp.Core 4.0.0.1 redirects: force
nuget FluentCommandLineParser 1.4.3
nuget Dapper 1.50.2
nuget XUnit 2.2
nuget xunit.runner.visualstudio 2.0.0 version_in_path: true
nuget xunit.runner.console 2.2
nuget xunit.runners 2.0

source http://hawthorn.sbs.local/nuget/sbs
nuget XurRefSubsetsDb
nuget XurDb.Live

group Build
  source https://nuget.org/api/v2
  
  nuget SourceLink.Fake
  nuget FAKE
  nuget FSharp.Formatting
  github fsharp/FAKE modules/Octokit/Octokit.fsx
`

But this does:

`
framework: auto-detect
redirects: on

source https://nuget.org/api/v2

# The setting below means your libraries will assume a minimum of FSharp.Core 
# for F# 4.0 (nuget package 4.0.0.1). If you would like to assume a higher minimum
# then change to 4.1.17 or later.

nuget FSharp.Core 4.0.0.1 redirects: force
nuget FluentCommandLineParser 1.4.3
nuget Dapper 1.50.2

source http://hawthorn.sbs.local/nuget/sbs
nuget XurRefSubsetsDb
nuget XurDb.Live

group Build
  source https://nuget.org/api/v2
  
  nuget SourceLink.Fake
  nuget FAKE
  nuget FSharp.Formatting
  github fsharp/FAKE modules/Octokit/Octokit.fsx

group Test
  source https://nuget.org/api/v2
  
  nuget XUnit 2.2
  nuget xunit.runner.visualstudio 2.0.0 version_in_path: true
  nuget xunit.runner.console 2.2
  nuget xunit.runners 2.0
`

**Comment by 0x53A** [comment]
@Rickasaurus framework restrictions and other settings are per group, that means the ``framework: NET452`` at the top is only active for the ``main`` group.

The NetStandard stuff is pulled in by the ``test`` group:

![image](https://user-images.githubusercontent.com/4236651/26995846-5d1766de-4d6f-11e7-9fc6-01f773871695.png)

**Comment by Rickasaurus** [comment]
Ahh! I would have thought that they would be inherited.

**Comment by 0x53A** [comment]
And in that you are probably not the only one. :D

------------

We could try to push the user to use an explicit ``main`` group, and print a warning if the dependencies file contains the implicit main group and one or more explicit groups.

Then it may be clearer that the options are only scoped to the group.

/cc @forki @matthid what do you think, would that make sense, or just be annoying?
The warning would probably pop for 90% of the current dependency files ...

**Comment by dsyme** [comment]
> And in that you are probably not the only one. :D

Correct :) I did too

**Comment by matthid** [comment]
@0x53A uah yes I agree the situation is unsatisfying. I don't even like how paket arranges the `packages` folder in that regard (I already said we have a problem if a package in "Main" is named after a group...). I'm sure if we should start that fight right now...

**Comment by matthid** [comment]
@konste to get back to this issue: Can you post the exact depsfile and the resulting `paket.lock` file ideally with the paket version used. So I can take a look and explain what's going on?

**Comment by matthid** [comment]
I get:

```
source https://nuget.org/api/v2
framework: net461

nuget Microsoft.IdentityModel.Clients.ActiveDirectory
```


```
RESTRICTION: == net461
NUGET
  remote: https://www.nuget.org/api/v2
    Microsoft.IdentityModel.Clients.ActiveDirectory (3.13.9)
```

with paket build from master.

**Comment by matthid** [comment]
@konste 

> I.e. paket.lock loses information that dependencies are only for .NETStandard and make them unconditional dependencies! 

No `paket.lock` just doesn't mark global restrictions again in the list below (see my example above). When we already have `== net461` globally paket will not repeat it for every dependency (that doesn't mean paket is not tracking everything thoughout).

If you have a non working example I'm happy to re-open ;)

**Comment by bacar** [comment]
I was having this issue too, but have subsequently realised that the `d:dependencies` element reported by the `Packages` nuget endpoint was being misreported by our internal nuget.org proxy (Nexus 2.x) - they didn't have the framework versions specified. Curiously the results of `/FindPackagesById` _does_ report them correctly, which is rather odd.
