### ISSUE TITLE
generate-include-script should not #r FSharp.Core.dll

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Paket#1942]
### Description

If you depend on a package that depends on `FSharp.Core` package, the `generate-include-script` command should not generate `#r "...FSharp.Core.dll"

### Repro steps

Run `paket install` and `paket generate-include-scripts framework net45` for a `paket.depenencies` file containing:

```
source https://nuget.org/api/v2
nuget Suave
```

Then you should be able to run:

```
#load @"paket-files\include-scripts\net45\include.main.group.fsx"
```

### Expected behavior

Evaluating the `#load` command in FSI works.

### Actual behavior

You get an error:

> error FS1222: When mscorlib.dll or FSharp.Core.dll is explicitly referenced the --noframework option must also be passed

### Known workarounds

You can start your `fsi.exe with `--noframework` option, but I think we don't want to make people do this.

**Comment by smoothdeveloper** [comment]
I'll fix that soon, thanks for the report!

**Comment by tpetricek** [comment]
❤️ please let me know when you have a new version so that I can integrate it into my fssnip PR!
