### ISSUE TITLE
Prettify paket.config

### ISSUE THREAD

**Issue by adamralph** [fsprojects/Paket#1952]
### Description

The XML content of paket.config is all on one line. For manual editing/eyeballing it would be better if this was prettified, i.e. with line breaks and indentation.

Feel free to reject this suggestion if it is crass.

### Repro steps

1. Open paket.config

### Expected behavior

The XML content is prettified, with line breaks and indents.

### Actual behavior

The XML content is not prettified, with line breaks and indents.

### Known workarounds

Format the XML after opening the file, either manually or with a text editor feature/extension.

**Comment by forki** [comment]
marked as up-for-grabs
