### ISSUE TITLE
The application has failed to start because its side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by wahmedswl** [fsprojects/Paket#1955]
### Description

During the build process today, i suddenly started to receive following error
```
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

### Repro steps

1. Invoke build.bat which has paket.bootstrapper.exe

2. Error will pop in Console

### Expected behavior

It should continue the build process as it was already doing.

### Actual behavior

Build process failed with error in event log
```
Activation context generation failed for "E:\Development\Production-WS\Infrastructure\.paket\paket.exe". The setting http://schemas.microsoft.com/SMI/2016/WindowsSettings^longPathAware is not registered.
```

### Paket
Paket.exe 3.23.0

**Comment by forki** [comment]
This is likely because of https://github.com/fsprojects/Paket/pull/1944 will revert that soon

**Comment by wahmedswl** [comment]
Hi, thanks for your quick response @forki. When new build will be available and will there be any manual step involved in update?

**Comment by forki** [comment]
it fixed. just rerun the build

**Comment by wahmedswl** [comment]
Thanks, its working now 👍
