### ISSUE TITLE
Paket doesn't find packages on Klondike

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1956]
### Description

Due to a fix in v3.17.3 paket cannot find new mirrored packages in Klondike.
Klondike is running with a mirror mode. Paket runs in NugetV2.GetVersions 3 different http requests against Klondike (http://localhost:9001/api/odata/Packages?$filter=tolower(Id) eq 'nunit', http://localhost:9001/api/odata/FindPackagesById()?id='nunit', http://localhost:9001/api/odata/package-versions/nunit?includePrerelease=true). Since the fix of 3.17.3 the first one is succesful and return an empty list. 
Later (https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NuGetV2.fs#L814) Async.Choice uses the first succesful answer of these three requests which is a problem, because the empty answer is chosen.

Short Explanation: Klondike manages mirrored packages from a remote source and local packages. The first request (of the three above) is only returning information from the already known data (cached or local) and does not query the remote source. The second request returns a combined answer from remote and local source. The third request fails.

IMHO We need sth to qualify the result of Async.Choice and let's choose a better result if possible, when the result does not satisfy an expectation, or (if this is possible and we don't lose compatibility) we remove the first request from the list of requests.
### Repro steps

Please provide the steps required to reproduce the problem
1. Start fresh klondike server (enable mirroring against nuget.org)
2. run `paket add nuget nunit`
### Expected behavior

Package should be downloaded; no error messages.
### Actual behavior

Error messages
### Known workarounds

Downgrade to version < 3.17.3
Or specify version `paket add nuget nunit version 3.5.0`

**Comment by Stift** [comment]
Just to emphasize it: The fix from 3.17.3 is correct and should stay.

**Comment by forki** [comment]
I think we should exclude the first request from running if we run against
Klondike

Am 10.10.2016 10:16 nachm. schrieb "Christian Fiebrig" <
notifications@github.com>:

**Comment by Stift** [comment]
Do we know how to detect? I have not found any specific information for that.

**Comment by forki** [comment]
like
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NuGetV2.fs#L261
;-)


2016-10-11 9:13 GMT+02:00 Christian Fiebrig <notifications@github.com>:

**Comment by Stift** [comment]
Saw this already, and don't like it that much. The only thing that Klondike currently is having is that the nuget endpoint is at .../api/odata
I thought whether we can detect it with some response headers. 
I'll take a look into that and try to come up with sth.

**Comment by forki** [comment]
Didn't say it's nice. but it worked...

**Comment by matthid** [comment]
Ähm has this been fixed ever since? Usually we don't trust "empty" answers so this should work now in theory. Though a test-base would be nice to have.
