### ISSUE TITLE
Create "why" command

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1959]
https://twitter.com/codepo8/status/785968938307903488

this command should analyze the paket.lock and show the reason in nice syntax.

**Comment by theimowski** [comment]
In addition to the resolution from paket.lock I'd also love to see whether any project actually references the package (can take that from paket.references).
This could be further extended to show whether the reference is reasonable from code POV (whether it's used at all)

Those however would imply that "why" command could end with "there's no reason for depending on X package" reason

**Comment by forki** [comment]
@theimowski did you just volunteered?

**Comment by theimowski** [comment]
I think so! Hope I can find some spare time to hack on this

**Comment by Stift** [comment]
Does not "find-refs" displaying what project references a dependency?
