### ISSUE TITLE
Pakages with targets in build folder and platfrom specific subfolder breaks the build

### ISSUE THREAD

**Issue by b0urb4k1** [fsprojects/Paket#1965]
### Description

When adding a NuGet package to a C# project, where the NuGet package has a build folder with a targets or props file and a netxxx, native or other folder that is recognized for a platform, then the condition added in the project file will make the build fail.
### Repro steps

https://github.com/b0urb4k1/broken_package
Use the build script in this repo to build the package then add the package to a C# project.
### Expected behavior

If all went right the build should produce a message "Golly, sir this worked mighty fine!"
### Actual behavior

The project file can not be built, since the Condition block makes it fail.
### Known workarounds

 You can move the props / targets file into the platfom specific subfolder.

**Comment by enricosada** [comment]
Closing, fixed in referenced PR
