### ISSUE TITLE
Local directory in paket.lock after convert-from-nuget

### ISSUE THREAD

**Issue by jschneidereit** [fsprojects/Paket#1968]
### Description

The command `convert-from-nuget` adds a local directory for remote: in paket.lock

```
FRAMEWORK: >= NET45
NUGET
  remote: C:\repos\my_project
    Castle.Core (3.3.3)
    Moq (4.5.22)
      Castle.Core (>= 3.3.3)
```

This path does not exist on my CI box and blew up, but I was able to replace it with the nuget.org url and everything worked fine. The [paket.lock page](https://fsprojects.github.io/Paket/lock-file.html) is a bit sparse on information on remote and am looking for further information on making sure that manually editing this file is the right way to do things

```
Paket version 3.23.2.0
Paket failed with:
        Could not find a part of the path 'C:\repos\my_project'.
```
### Expected behavior

Remote should default to the nuget url, not a local path I believe? Or at least an option for convert-from-nuget.
### Actual behavior

Local path is used on projects originally taken from nuget.
### Known workarounds

I swapped existing local path in remote with https://www.nuget.org/api/v2/ and it works a treat!

**Comment by jschneidereit** [comment]
This is my paket.dependencies file
```
source http://artifactory.net/artifactory/api/nuget/sandbox
source C:\repos\my_project
source http://artifactory.net/artifactory/api/nuget/release
source http://artifactory.net/artifactory/api/nuget/sandbox
source https://www.nuget.org/api/v2/
framework >= net45

nuget Moq 4.5.22
```

**Comment by forki** [comment]
I assume the path was in nuget.config of the machine where the convert
happened

Am 17.10.2016 11:22 nachm. schrieb "Jim Schneidereit" <
notifications@github.com>:

**Comment by jschneidereit** [comment]
You're right, had that in there for testing. My bad! 

What is strange is that the remote defaulted to the local path instead of the nuget.org url. Especially since none of those dependencies came from my local box.

**Comment by forki** [comment]
Maybe not originally. But it looks like the resolver found something over there.

**Comment by enricosada** [comment]
> You're right, had that in there for testing. My bad!

Closing. fixed in user environment
