### ISSUE TITLE
Download file to root of repository?

### ISSUE THREAD

**Issue by TraGicCode** [fsprojects/Paket#1970]
### Description

I currently use a build script from a public github repository.  Is it possible to have paket download and place this build script at the root of my github directory when no csproj exists there?  Is there a way to tell paket not to place it in the paket-files directory?
- .packet
- .git
- paker-files
- src
  - MySolution.sln
- BuildScriptFromPublicRepo.ps1

**Comment by forki** [comment]
No. It's putting it into paket-files.

**Comment by enricosada** [comment]
Closing.

The build script (committed in repo) can dot source import the file inside `paket-files`
