### ISSUE TITLE
group specification does not honor case-sensitivity

### ISSUE THREAD

**Issue by flaub** [fsprojects/Paket#1978]
### Description

When specifying a group in `paket.dependencies`, the resulting directory under packages does not match the case of the group name.
### Repro steps
1. Create a `paket.dependencies` like:
   
   ```
   group SomeGroup
   source https://www.nuget.org/api/v2
   nuget Newtonsoft.Json
   ```
2. Run `.paket\paket.exe install`
### Expected behavior

The directory name under `packages` should be `SomeGroup`.
### Actual behavior

The directory name under `packages` is `somegroup`.

On windows, this doesn't matter much, but it does on *nix systems.

**Comment by forki** [comment]
Currently it's lowercased by design. Does this lead to a concrete issue?

Am 24.10.2016 10:47 nachm. schrieb "Frank Laub" <notifications@github.com>:

**Comment by flaub** [comment]
I'm using an external build system based on https://waf.io/. Therefore, I don't use any `paket.references` files. Instead, I have a parser which understands `paket.lock` and can create the proper command line arguments for csc/mcs. We've been using this system for years to provide cross-platform builds (including native C/C++ bits).

It would be nice if my custom parser for `paket.lock` could simply use whatever the group name is in order to go searching inside of the packages directory to find libs and refs. It works OK on windows because the file system acts like it's case insensitive. 

My workaround is to simply use an all lower-case group name. 

Can you describe why the directory is lowercased by design?

**Comment by forki** [comment]
It's lowercased for exactly the reason you described. Basically most things
(all?) in the dependencies file are case insensitive (like package names).
So in order to keep things predictable on all systems and consistent
between ref files, we lowercase group names.

Am 02.11.2016 08:26 schrieb "Frank Laub" <notifications@github.com>:

**Comment by flaub** [comment]
I can understand wanting to deal with entries in `paket.lock` in a case insensitive manner, but how would creating a directory that matches the case in the `paket.lock` file break this behavior? I guess what's confusing to me is that if I specify `Newtonsoft.Json` as a nuget package, the directory on disk is `Newtonsoft.Json`, which matches the case.

If paket currently has to deal with the case of dealing with `newtonsoft.json` in the `paket.lock` file and have that match up to `Newtonsoft.Json` on disk, how would having the group name match the case exactly on disk break anything?

**Comment by forki** [comment]
We know the "correct" casing for newtonsoft from the nuget.org repo. We don't know it for groups since it can be different in dependencies and references files. We would need to settle on one.

**Comment by flaub** [comment]
Thanks for the explanation. As mentioned I have a workaround so this really isn't a big deal. Thanks for providing a system that doesn't depend on MSBuild!!
