### ISSUE TITLE
Paket confusing parallel package downloads with each other

### ISSUE THREAD

**Issue by cdrnet** [fsprojects/Paket#1996]
### Description

Lately I often run into an issue where Paket seems to confuse parallel downloads with each other, and putting the content of one nupkg into the file name of another package.

For example, after trying to use Accord, within the `AppData/Local/NuGet/Cache` folder, the file `Accord.Extensions.Core.3.0.1.nupkg` actually contains the data that it should have written to another file name `Accord.Extensions.Math.3.0.1.nupkg`.

![2016-11-02 09_07_55-nuget package explorer rd extensions math 3 0 1](https://cloud.githubusercontent.com/assets/47147/19920993/1f8fa578-a0dc-11e6-9c91-9b84d38f6567.png)

![2016-11-02 09_10_05-mingw64__c_svn_mathnet_mathnet-numerics](https://cloud.githubusercontent.com/assets/47147/19921020/38603c98-a0dc-11e6-87a9-945a235bc2ac.png)

This does not happen when I use e.g. the NuGet Package Explorer to download the same package from the same feed (otherwise I'd have suspected our proxy server to mess things up).

Am I the only one seeing this form time to time?

### Repro steps

1. clean caches
2. Try to restore the following lock file:

```
GROUP Benchmark
FRAMEWORK: NET45
NUGET
  remote: http://www.nuget.org/api/v2
    Accord (3.3)
    Accord.Extensions.Core (3.0.1)
      Accord (>= 3.0.2)
    Accord.Extensions.Math (3.0.1)
      Accord.Extensions.Core (>= 3.0.1)
      Accord.Statistics (>= 3.0.2)
      DotImaging.Primitives2D (>= 2.5.3)
    Accord.Math (3.3)
      Accord (>= 3.3)
    Accord.Statistics (3.3)
      Accord (>= 3.3)
      Accord.Math (>= 3.3)
    DotImaging.Primitives2D (4.8.3)
```

and dependencies file:

```
group Benchmark
    source http://www.nuget.org/api/v2
    framework: net45
	nuget Accord.Math
	nuget Accord.Extensions.Math
```

### Expected behavior

Download `Accord.Extensions.Core.3.0.1` into the `Accord.Extensions.Core.3.0.1.nupkg` cache file, and `Accord.Extensions.Math.3.0.1` into the `Accord.Extensions.Math.3.0.1.nupkg` cache file.

### Actual behavior

Downloads `Accord.Extensions.Math.3.0.1` into the `Accord.Extensions.Core.3.0.1.nupkg` cache file.

**Comment by forki** [comment]
What if you switch to https?

Am 02.11.2016 09:15 schrieb "Christoph Ruegg" <notifications@github.com>:

**Comment by cdrnet** [comment]
Indeed, that fixes it - that would mean it's a proxy server issue after all?

**Comment by forki** [comment]
I have no idea, but I saw it in our network as well and blamed it on
proxies being stupid. I wish I would have an idea how to fix it

Am 02.11.2016 09:18 schrieb "Christoph Ruegg" <notifications@github.com>:

**Comment by forki** [comment]
Can you reproduce it outside of your current network?

Am 02.11.2016 09:22 schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

**Comment by cdrnet** [comment]
I don't think I have seen this outside the work network, but I'll verify in the evening. I'm trying to catch it with wireshark, but now it seems to no longer be able to download the affected packages at all ...

**Comment by forki** [comment]
switch to https for now.

**Comment by cdrnet** [comment]
Yes, that works for me. Thanks.

**Comment by cdrnet** [comment]
FWIW, I can see in wireshark that on the same HTTP Stream we send 3 GET's together before we get any reply back (Accord.Extensions.Math, Accord.Math and DotImaging.Primitives2D), we first get a response for DotImaging.Primitives2D, and I can see in the result that the content of DotImaging.Primitives2D was indeed put into Accord.Extensions.Math. I don't have time right now to verify the sequence numbers, but I'll keep the capture for later.

**Comment by enricosada** [comment]
> Yes, that works for me. Thanks.

Closing, fixed in user environemt
