### ISSUE TITLE
paket -v install enters an infinite loop "license already downloaded"

### ISSUE THREAD

**Issue by t0yv0** [fsprojects/Paket#1998]
### Description

`paket -v install` enters an infinite loop on Paket version 3.26.0.0

### Repro steps

Reproducing is hard. This requires a source with basic HTTP auth that somehow malfunctions. It is easy to see where the loop is happening in source code though.

### Expected behavior

Terminate with an error

### Actual behavior

Infinite loop.

### Known workarounds

NA.

**Comment by forki** [comment]
If you already have found the reason, could you please try to come up with
a fix?

Am 02.11.2016 22:52 schrieb "Anton Tayanovskyy" <notifications@github.com>:
