### ISSUE TITLE
Paket does not create app.config when binging redirect is specified

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#2014]
### Description

Paket does not create app.config when binging redirect is specified for a NuGet dependency.

### Repro steps

1. Add `nuget Moq redirect: on`
2. Add `Moq` to `paket.references` to project without `app.config`.
3. Run `paket install`

### Expected behavior

`app.config` should be created and added to the project

### Actual behavior

No files is created

### Known workarounds

Create `app.config` in advance.

**Comment by forki** [comment]
We have special parameter to create new binding files

**Comment by trondd** [comment]
Note to self: RTFM!
