### ISSUE TITLE
Git Dependency fails to install when space exists in User Folder name

### ISSUE THREAD

**Issue by granttrevor** [fsprojects/Paket#2015]
### Description

I have a user folder that has a space in it eg: C:\Users\Firstname Lastname\
Git dependency resolution fails when attempting to clone from C:\Users\Firstname Lastname\.paket\git\db\folder into the paket-files folder.

It correctly fetches the repository from a remote github based repo into C:\Users\Firstname Lastname\.paket\git\db\folder

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a User with a Space in their User name, this will create a User folder that contains a space

2. Add git dependency in paket.dependencies

git git@github.com:MyOrganisation/MyRepo.git master build: "powershell build.ps1"

3. run packet.exe install

### Expected behavior

Dependency should be installed in packet-files

### Actual behavior

Paket failed with:
        Checkout to C:\Working\MySolution\MyProject\paket-files\github.com\MyOrganisation\MyRepo failed.
Message: Could not run "git clone file:///C:\Users\Firstname Lastname\.paket\git\db\MyRepo".
Error:
Cloning into 'Lastname\.paket\git\db\MyRepo'...
fatal: 'C:/Users/Firstname' does not appear to be a git repository
fatal: Could not read from remote repository.

### Known workarounds

None

**Comment by forki** [comment]
you don't have a existing git url for me?

**Comment by granttrevor** [comment]
I've created a test repo - https://github.com/wzowee/paket-test and stuck the Serilog nuget package in the root which you could use to test the pulling down from a git source.

Just to be clear the issue is with the name of the User folder on a Windows machine if this name has a space in it then the clone from the .paket folder with the user folder fails.

**Comment by forki** [comment]
argh. so I need to create a windows user with space. ok let me try that.

**Comment by matthid** [comment]
Windows username with a space is basically asking for trouble ;) 
@forki Try to add some special characters as well, heard lots of funny stories in the past.

**Comment by forki** [comment]
@matthid I will not! ;-)
