### ISSUE TITLE
Paket pack does not add dependent projects as package dependencies (regression?)

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#2016]
I have published tiny repro here: [https://github.com/konste/PaketRepro](url)
Two projects - library and main project which reference library project.
PaketRepro.cmd contains two pack commands (one for each project).
When I run those two pack commands main project gets both DLLs in the lib subfolder instead of making one NuGet dependency.
Interestingly if I specify include-referenced-projects (on the command line or in the paket.template file) and the result is totally counter intuitive - dependency DLL does not get copied to lib project! And that's the only difference. 

I honestly wasted a few hours trying to make it work, but failed and ask for help.
Konstantin
P.S. Paket version 3.26.3.0

**Comment by forki** [comment]
AFAIK this feature always worked only if you use ONE pack command on the whole repo.

And it seems to continue to work:

![image](https://cloud.githubusercontent.com/assets/57396/20212299/ae863080-a802-11e6-8763-981623d3dcca.png)

**Comment by konste** [comment]
Gosh... it works indeed, but I would never guess myself that I supposed to run Paket pack on the whole solution rather than on specific projects I want to package!

**Comment by forki** [comment]
That's pretty much how the whole paket tool works out of the box. It's
always for whole solution.

Am 11.11.2016 23:27 schrieb "Konstantin Erman" <notifications@github.com>:

**Comment by konste** [comment]
But Paket push breaks that rule and requires pushing of the packages one at a time, right?

**Comment by forki** [comment]
Really? Mhm

Am 14.11.2016 07:42 schrieb "Konstantin Erman" <notifications@github.com>:
