### ISSUE TITLE
Pack doesn't write the version from lock file into the nuspec

### ISSUE THREAD

**Issue by michael-baker** [fsprojects/Paket#2017]
### Description

Using Paket 3.9.6 via C#.

Packaging content using "use minimum from lock file" doesn't write the version info the package spec file. 

### Repro steps

Have a solution packaged via Paket.
Depend on some library via Package A.
Retrieve package A.
Call PackageProcess.Pack via C# like follows.

```
PackageProcess.Pack(workingDir: "C:\\somedir", 
                dependenciesFile: dependenciesFile, 
                packageOutputPath: spec.OutputPath, 
                buildConfig: FSharpOption<string>.Some("Release"),
                buildPlatform: FSharpOption<string>.Some("AnyCPU"),
                version: FSharpOption<string>.None, 
                specificVersions: new List<Tuple<string, string>>(), 
                releaseNotes: FSharpOption<string>.None, 
                templateFile: FSharpOption<string>.Some(fs.GetFullPath(file)), 
                excludedTemplates: GenerateExcludedTemplates(), 
                lockDependencies: true, 
                minimumFromLockFile: true, 
                symbols: false, 
                includeReferencedProjects: true, 
                projectUrl: FSharpOption<string>.None);
```

### Expected behavior

Paket should package my content and write the version information of the dependent libraries into the package nuspec.

### Actual behavior

When the package is created the resulting nupsec file reveals that Package A is a dependency but there no version written into the spec for it.

Looking at the F# code the behavior I want only occurs if you do not specify the "version" parameter. However not specifying the version parameter results in a "No version given for..." error.

### Known workarounds

None

**Comment by forki** [comment]
can you please upload a zip with a repro? thanks

**Comment by michael-baker** [comment]
Can do. I'll cook something up tomorrow.

**Comment by michael-baker** [comment]
I've managed to reproduce the issue using just the Paket command line which is probably a more "supported" use of the tool. 
However I have a C# wrapper around Paket and this is used inside my organization as we have some fairly complicated requirements for dependency management and we need to interop with several other dependency tools as well.

That said the full repro case is here: https://github.com/michael-baker/paket-issue-2017 and the nuspec which doesn't contain the version minimum: https://github.com/michael-baker/paket-issue-2017/blob/master/MyProduct.1.0.0/MyProduct.nuspec

**Comment by michael-baker** [comment]
Closing this as I have discovered you need to use the LOCKEDVERSION key word plus a constraint operator in the template file for the locking to be written into the nuspec file.
