### ISSUE TITLE
Semantic version resolving is broken

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#2018]
### Description

In 3.27.0 of paket mechanism of version resolving got broken, I have an internal
nugget, what has versions 2.0.0.9 and 2.0.10 I defined dependency on it as ~> 2.0, previously paket resolved it to 2.0.10 as it should now it resolves it to 2.0.0.9.

Sorry I can't give you repro because it internal nugget but I know that it got broken in 3.27.0

**Comment by forki** [comment]
probably related to https://github.com/fsprojects/Paket/pull/2008
@cdrnet I will revert that for now. please open new PR that just adds that for your server

**Comment by tsibelman** [comment]
Thank you @forki

**Comment by forki** [comment]
@tsibelman what kind of server do you have?

**Comment by tsibelman** [comment]
This one https://www.nuget.org/packages/NuGet.Server/

**Comment by tsibelman** [comment]
Took the latest all works now, thank you.

**Comment by cdrnet** [comment]
And as a result this is now broken for all Artifactory users again. Welcome to the brave world of OData where it seems impossible to work around one broken implementation without breaking the work around of another broken implementation...

Do we know what exactly was broken with NuGet.Server? Being opensource, maybe this could actually be fixed properly over there. I expect the NuGet Package Explorer doesn't work with this server then?

@forki will do

**Comment by enricosada** [comment]
> Took the latest all works now, thank you.

Closing
