### ISSUE TITLE
put paket.references inside msbuild project for .net sdk projects

### ISSUE THREAD

**Issue by enricosada** [fsprojects/Paket#2019]
Atm with #1977 the `core3paket.csproj.references` file is used to add packages ref on restore, like before.

I think the references can be included inside the fsproj:

```xml
<ItemGroup>
    <PaketReference>Newtonsoft.Json</PaketReference>
<ItemGroup>
```

or as property separated by `;` (easier for merge, like `TargetFrameworks`)

```xml
<PropertyGroup>
    <PaketReference>Newtonsoft.Json;log4net</PaketReference>
<PropertyGroup>
```

And remove the need for a `core3paket.csproj.references` (one file less), so all project files are self-contained

On `dotnet restore`, the paket target will:

- will read the `PaketReference` items/property
- create an `obj\core3paket.csproj.references` (inside `obj` dir)
- and call paket passing full path of `obj\core3paket.csproj.references` instead of infer location is near the .csproj

Like that the paket support seems more first class (like `PackageReference`), the csproj/fsproj is not verbose, and conditional based on framework or other is normal sintax ( Condition="'$(TargetFramework)' == 'net46'" ) already used for defined/props/packages

**Comment by forki** [comment]
I'm bit undecided on that right now. I'm not completely against it but I would wait a bit.

**Comment by enricosada** [comment]
Closing, hard to implement, no big gains atm
