### ISSUE TITLE
Paket should not overwrite changed content files

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#202]
NuGet [won't restore content files](http://jeffhandley.com/archive/2013/12/09/nuget-package-restore-misconceptions.aspx) because the user is expected to edit them. Or remove a subset of content files from the project. Or some other reason outlined in the post above.

The reasoning behind it is a bit unclear, especially since it allows you to get your dependencies into an inconsistent state:

```posh
PM> Install-Package jQuery -Version 2.1.0

# edit Scripts/jquery-2.1.0.js

PM> Update-Package jQuery
Updating 'jQuery' from version '2.1.0' to '2.1.1' in project 'ClassLibrary1'.
Removing 'jQuery 2.1.0' from ClassLibrary1.
Skipping 'Scripts\jquery-2.1.0.js' because it was modified.
...
```

This will leave you with an inconsistent set of jQuery files: the modified `jquery-2.1.0.js` stays in place, but you get an extra `jquery-2.1.1.js`. All other jQuery 2.1.0 files (minified, map) will be replaced with their jQuery 2.1.1 counterparts.

What are our options when we detect modified content files?
* Rebuild NuGet's behavior, possibly allowing inconsistencies
* Fail
* ?

Should do the same and install content just once and then leave them untouched? If we opt to always install content files, this would essentially remove the possibility to have the user modify them.

**Comment by dnauck** [comment]
+1

**Comment by 304NotModified** [comment]
Is this ever implemented?

**Comment by agross** [comment]
I think you can specify a mode for content files now.

nuget jQuery content: none // we don't install jQuery content files
nuget Fody content: once // install content files but don't overwrite
nuget ServiceStack.Swagger content: true // install content and always override nuget

From: http://fsprojects.github.io/Paket/nuget-dependencies.html

⁣Beste Grüße,

​Alex
-- 
http://therightstuff.de/
Tiny phone, tiny mail​

**Comment by 304NotModified** [comment]
Cool. Could we add that to the "Converting from NuGet" and "FAQ" pages?

**Comment by agross** [comment]
You can make it happen by creating an issue. Submit a pull request if you like, it would be greatly appreciated!

**Comment by 304NotModified** [comment]
It's just to the gh-pages branch isn't? The content is updated by hand or with a tool?

**Comment by agross** [comment]
See the docs directory. It's markdown that is used to create the documentation.
