### ISSUE TITLE
Dependency Hell - Looking for Help and Suggestions

### ISSUE THREAD

**Issue by mikecann** [fsprojects/Paket#2021]
### Description

Hi, we are using Paket internally on a large game and are encountering an issue when you have a number of packages with inter-dependent versioning.

### Example Scenario

*Package:* Json is at version 1.1.0 it depends upon nothing
*Package:* Advertising is at version 3.3.5 it depends upon `Json ~> 1` it has has its dependencies updated so that its `paket.lock` now reads: `Json (>= 1.1.0 < 1.2.0)`
*Package:* Downloading is at version 4.6.1 it depends upon `Json ~> 1` it has its dependencies updated so that its `paket.lock` now reads: `Json (>= 1.1.0 < 1.2.0)`
*Package:* MyGame depends upon `Advertising ~> 3` and `Downloading ~> 4` and `Json ~> 1`

We update dependencies on MyGame, it correctly pulls down Advertising 3.3.5 and Downloading 4.6.1 and Json 1.1.0 because paket can satisfy the dependencies of Downloading and Advertising for `Json (>= 1.1.0 < 1.2.0)`.

Now we decide to add a new feature (non-breaking) to Json that we want to take advantage of in MyGame so we bump its minor version to 1.2.0. We then update dependencies in the MyGame package and expect that Json 1.2.0 will be downloaded so we can use the new feature. The problem is, it wont be because Paket needs to satisfy the requirements for Advertising and Downloading too which is `Json (>= 1.1.0 < 1.2.0)`.

So we have now entered "Dependency Hell" as we now must update dependencies and commit both Advertising and Downloading just so we can use this new feature in MyGame.

In a nut shell this is the issue. obviously this is a little simplified but when everything is connected to everything else or when one dependency is pervasive making a minor version bump suddenly becomes super expensive. So the temptation is to just do "patch bumps" when you add a new feature even tho this is against semver.

### The Problem

The core of the problem is that the `paket.lock` file is (we suspect) too restrictive on its versioning.

For the above example the `paket.lock` for Advertising may look something like:

```
NUGET
  remote: http://some-server.com
  specs:
    Json (>= 1.1.0 < 1.2.0)
```

And in `paket.template` for Advertising we would have:

```
type file
copyright The Company
id Advertising
version 3.3.5
files
    Assets/src/ ==> content
dependencies
	Json ~> LOCKEDVERSION
```

And in paket.dependencies for Advertising we have:

```
source http://some-server.com

nuget Json ~> 1
```

We are using `LOCKEDVERSION` in `paket.dependencies` because we dont want to have to specify the version in both `paket.template` and `paket.dependencies` for everything all the time.

### Contemplated Solutions

We have thought about the following solutions:

1. Run a post-paket-update process that modifies `paket.lock` to change the `Json (>= 1.1.0 < 1.2.0)` dependency to something less restrictive such as `Json (>= 1.1.0 < 2)`.
2. Fork Paket to achieve 1. without writing a post-processor
3. Fork Paket and add a MAJORLOCKEDVERSION keyword which works like LOCKEDVERSION but only locks to the major version listed in `paket.dependencies`

### Queries

So we would like to know what you suggest here. Perhaps we are missing something fundamental. 

1. Is there a reason why Paket is restrictive to the minor version (`Json (>= 1.1.0 < 1.2.0)`) when semver itself should enforce the fact that only major version changes could be breaking?
2. Is there some other way to achieve what we want to do here?

**Comment by inosik** [comment]
Maybe you could remove the `dependencies` item from `paket.template` in Advertising and use the `minimum-from-lock-file` flag when calling `paket pack`. Then Paket should take the version requirement from `paket.dependencies` but starting from the resolved version.

> Fork Paket and add a MAJORLOCKEDVERSION keyword which works like LOCKEDVERSION but only locks to the major version listed in paket.dependencies

:+1: on something like this. I think `MAJOR`, and also `MINOR` and `PATCH`, should be kind of a "macro", which works also with `CURRENTVERSION`.

**Comment by forki** [comment]
the issue with minimum-from-lock-file is that it has no upper border. that can lead to issues as well.

   MAJOR, and also MINOR and PATCH as macros sounds like a good idea.

**Comment by mikecann** [comment]
Okay thanks guys, ill discuss this with the team
