### ISSUE TITLE
paket pack adds wrong prerelease dependency

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#2024]
### Description

When paket.lock includes a prerelease package `paket pack` command adds wrong dependency version to the .nupkg file

### Repro steps

1. Install a prerelease package. Sample entry `paket.dependencies`:
  ```
  nuget Nancy prerelease
  ```
2. Create a minimal `paket.template`
  ```
  type project
  version 0.1
  authors tpluscode
  ```
1. Build Release
2. Create package:
  ```
  paket pack output nugets
   ```
[Repro here](https://github.com/fsprojects/Paket/files/598216/paket-pack-pre.zip)

### Expected behavior

The reference should be `>= 2.0.0-barneyrubble`

### Actual behavior

Actual reference in .nupkg is listed as `<dependency id="Nancy" version="0.0.0-prerelease" />`

### Known workarounds

Adding these lines to `paket.template` solves the issue

```
dependencies
  Nancy >= LOCKEDVERSION
```

**Comment by forki** [comment]
If you remove the prerelease in the deps file you will get:

      <dependency id="Nancy" />

which basically means > 0 (but not prerelease).

0.0.0-prerelease is actually ny design. What's wrong with it?

**Comment by tpluscode** [comment]
So 0.0.0-prerelease will install any latest prerelease version, be it 2.0 or 3.0 or whatever?

**Comment by forki** [comment]
that's what I hope. yes

**Comment by tpluscode** [comment]
I don't think it's good design. It works when installed with Paket but most consumers will use NuGet that comes with VS.

With NuGet Package Manager the only way to install the desired version 2.0.0-prerelease is use the [Dependency behavior](http://docs.nuget.org/ndocs/tools/package-manager-ui#install-options) to `Highest`. Unfortunately that installs prerelease versions of all transitive packages. Selecting `Highest Patch` or `Highest Minor` installs 0.4 and 0.23 respectively.

**Comment by forki** [comment]
ok. but that's just Nuget being dumb.

**Comment by forki** [comment]
but that said: I thing we could change it to >= LOCKEDVERSION

for prereleases this would make sense
