### ISSUE TITLE
Paket installs dependencies to projects beside the deisgnated one in the same directory

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#2025]
### Description

Due to the lack of decent netcore tooling for the new fsproj format in the various F# editors I've been creating projects where I put a new netcore version and an old version side-by side and they share the same source files.

![](http://i.imgur.com/VveXLmT.png)

When I install a dependency into a specific project it works as expected 
```
λ» paket add project ExampleConsoleApp.fsproj nuget Argu
```
![](http://i.imgur.com/bI5wKKE.png)

But once I call 
```
λ» paket install
```
It installs into the other project as well, which totally breaks the netcore project since it's adding in net46 dependencies in the wrong format

![](http://i.imgur.com/AV0VIb0.png)

### Repro steps

Here's an archive of the repo in the screenshots in the state before running `paket install`

[paketfail.zip](https://github.com/fsprojects/Paket/files/599065/paketfail.zip)

### Expected behavior

paket only adds the dependencies to the project that had been specified

### Actual behavior

adds dependencies to the wrong project

### Known workarounds

I ran into this while working on [fsprojectile](https://github.com/fsharp-editing/fsprojectile), and I was forced to split the projects into different folders

![](http://i.imgur.com/xAareYm.png)

And use links to the original source files in the isolated netcore fsproj, which is really annoying to maintain, and is prone to breaking over changes that I forget to synchronize

![](http://i.imgur.com/Wln7mVE.png)

**Comment by matthid** [comment]
This is by design an was mentioned by me in various occations... paket searches for a paket.references in the current and the parent directory until it find one. 
Workaround is to create a matching emtpy paket.references....

I think this one will come back like a boomerang until we finally decide to make the breaking change ;) Or until everyone has the workaround in their bones.

**Comment by forki** [comment]
Are you using paket 4? It should never add old style references to MSBuild
15 files. That would be a bug. Can I reproduce?

Am 18.11.2016 07:49 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment]
Wait what? paket 4 changes this? What about manually handled references? Is there a in-depth discussion about this somewhere?

**Comment by forki** [comment]
not sure if we are talking about the same thing, but yes paket 4 doesn't add Choose Nodes to MSBuild 15 files - it only adds packagereferences

**Comment by forki** [comment]
Using Paket 4 it seems to do the right thing:

![image](https://cloud.githubusercontent.com/assets/57396/20423275/b621f9c4-ad6f-11e6-85dd-2d47bfadc9a8.png)

**Comment by matthid** [comment]
ok got it, for old style msbuild file the behavior is unchanged.

**Comment by forki** [comment]
yes. it detects the MSBuild veripn and tries to do the right thing. sorry for confusion

**Comment by cloudRoutine** [comment]
I was using paket 3, but I guess with all the netcore stuff I'm doing 4 is the way to go.

Using the tools version isn't a strong guarantee, new style msbuild projects can still be set to v14 and they'll build fine with `dotnet` cli. I saw a few csproj like this in one of MS's repos the other day.

http://i.imgur.com/xv0q2nl.png

@matthid I don't follow, there already was a `paket.references` you can see it in the screenshot. Are you saying there should be 2 of them?

**Comment by matthid** [comment]
@cloudRoutine I might be confusing something, but I think you can name the reference file like the project file and a second empty one named like the netcore project  file (maybe ` ExampleConsoleApp.netcore.references`) would help with paket 3.

**Comment by enricosada** [comment]
Closing.

as a note, fsproj of different sdk shouldnt be in same directory, because that is going to mess the `obj` dir a lot creating issues
