### ISSUE TITLE
Add support for setting the specific version attribute in paket.references

### ISSUE THREAD

**Issue by gautebrakstad** [fsprojects/Paket#2040]
### Description

Add support to set SpecificVersion on Reference in .csproject files via paket.references
As it is now you have to manually go into each Project file and update the Reference.

### Wanted result
```
<Reference Include="ccc.dll">
          <HintPath>..\..\..\packages\current\ccc\lib\net45\ccc.dll</HintPath>
          <SpecificVersion>False</SpecificVersion>
          <Private>True</Private>
          <Paket>True</Paket>
</Reference>
```

**Comment by batzen** [comment]
Would also like to see this feature added.
If you develop a base library which should support version ranges for it's own dependencies it's quite a lot of work to add `<SpecificVersion>False</SpecificVersion>` every time.

**Comment by batzen** [comment]
@forki I got this in my fork and already created PR #2413.

**Comment by enricosada** [comment]
Closing, done by @batzen , doc in https://fsprojects.github.io/Paket/nuget-dependencies.html#Referencing-specific-versions-in-projects
