### ISSUE TITLE
Cannot build Paket on Linux

### ISSUE THREAD

**Issue by Alaiven** [fsprojects/Paket#2041]
### Description
Paket sources are not buildable on Linux. 

Windows path to .net.core is hardcoded into build.fsx

        let zipFileName = sprintf "dotnet-dev-win-x64.%s.zip" dotnetcliVersion
        let downloadPath = sprintf "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/%s/%s" dotnetcliVersion zipFileName
        let localPath = Path.Combine(dotnetCliPath.FullName, zipFileName)

        tracefn "Installing '%s' to '%s" downloadPath localPath

        use webclient = new Net.WebClient()
        webclient.DownloadFile(downloadPath, localPath)

        System.IO.Compression.ZipFile.ExtractToDirectory(localPath, dotnetCliPath.FullName)

### Expected behavior

Linux installation without manual tricks.

### Known workarounds

You can remove the code responsible for checking for .net.core and provide it by yourself, but it crashes later on:

 ` dotnet exec --depsfile /home/user/.nuget/packages/.tools\dotnet-compile-fsc\1.0.0-preview2-020000\netcoreapp1.0\dotnet-compile-fsc.deps.json --additionalprobingpath /home/user/.nuget/packages/ /home/user/.nuget/packages/dotnet-compile-fsc\1.0.0-preview2-020000\lib\netcoreapp1.0\dotnet-compile-fsc.dll @/home/user/dev/studia/individial_project/Paket/src/Paket.Core/obj/Release/netstandard1.6/dotnet-compile.rsp
         dotnet exec needs a managed .dll or .exe extension. The application specified was '/home/user/.nuget/packages/dotnet-compile-fsc1.0.0-preview2-020000libnetcoreapp1.0dotnet-compile-fsc.dll'
`
I don't really know what causes it.

**Comment by forki** [comment]
yeah I guess .NET core part of the build is not ready for linux. tbf it's not even ready for windows. @enricosada is trying to help me here.

**Comment by enricosada** [comment]
ref https://github.com/fsprojects/Paket/pull/2032#issuecomment-262467970

**Comment by enricosada** [comment]
Closing.

now travis ci build both .net core and .net
