### ISSUE TITLE
Output detailled statics for sources request response

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2042]
### Description

Output detailled statics for sources request response

### Repro steps

create a paket.dependencies that reference multiple "Nexus" sources. These nexus are configured as Proxy with an upstream to nuget.org

>rm paket.lock
>paket install --StatPerRequest requestStat.csv

### Expected behavior

Havign data that i could parse to output graph about what's going in our internal network for these sources (often take more than one minute )

### Actual behavior

Not sure it exists

### Known workarounds

Open a browser and check by myself, but it seems that there's warmup on nexus that tend to lower the actual value on the network and how bad this is

**Comment by forki** [comment]
I think this could be added under verbose flag or something
