### ISSUE TITLE
Weird Paket Restore on repo "Paket"

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2043]
### Description

Paket download package for fedora / debian / NetStandard 1.6.1 etc ...
Maybe it's totaly intended to have it pike this, i was just surprised when restoring pakage to see this

### Repro steps

> mkdir TestingPaketOnPaket
> cd TestingPaketOnPaket
> git clone https://github.com/fsprojects/Paket.git
> cd Paket
> paket restore

### Remarks
* On a computer with Paket just update, .NetCore SDK + VsTools 1.1 & dotnet.exe
* I can see that Paket.Core reference this : `System.Security.Cryptography.OpenSsl` around line 1466 
* paket.dependencies does not specify any framework so when you type in :
> paket why nuget System.Security.Cryptography.OpenSsl` --detail
We can observe that package (like Chessie) goes with .NetStandard
-> Chessie
  -> FSharp.Core
    -> NETStandard.Library
....

### Actual behavior

```
C:\Workspaces\Github\Paket>paket restore
Paket version 3.29.5
Downloading ....

Downloading NETStandard.Library 1.6.1
Downloading runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.native.System 4.3
Downloading runtime.native.System.IO.Compression 4.3
Downloading runtime.native.System.Net.Http 4.3
Downloading runtime.native.System.Security.Cryptography.Apple 4.3
Downloading runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3
Downloading runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3
Downloading runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3

Downloading ...
```

**Comment by forki** [comment]
ok what's exactly strange?

**Comment by tebeco** [comment]
May be nothing as i said

Paket is going XPlat ?
I'm wondering why i see all these version of OpenSsl (the list of RID)

**Comment by forki** [comment]
We're in the process of making Paket work on coreclr. and all this crap is coming with .NET Standard Library. Welcome to the brave new world ;-(
