### ISSUE TITLE
Use  NTLM Proxy for Paket only (No System Proxy) ?

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2046]
### Description

CI server should never be able to acces internet into corporate environment except few apps
Is there a way to make "Paket" use specific Proxy settings like npm that uses .npmrc and "proxy" "https.proxy" settings.
Using HTTP_PROXY and HTTPS_PROXY env variable is absolutly a no go since it affect lots of application

**Comment by forki** [comment]
No we don't have such a special feature.

But if you wrap paket in a batch script you can probably set the proxy
environment variables locally to paket.

Am 25.11.2016 3:09 nachm. schrieb "tebeco" <notifications@github.com>:

**Comment by tebeco** [comment]
I'm not sure event wrapping it with Env variable will be accepted, what are the name of the env variable readed ?

**Comment by tebeco** [comment]
Proxy is not Set in windows account (forbiden),

From a command line on CI agent :

>SET HTTP_PROXY=http://myNtlmProxy:PortHere
>SET HTTPS_PROXY=http://myNtlmProxy:PortHere
>.paket\paket.exe restore -f --verbose

(yes there's no https on HTTPS_PROXY and it works with NPM, git ....)
No luck, it's creating the folder "packages" with nuget for "Remote" that are hosted on internal nexus

it's printing :

```
Downloading SomeExternalNugetOne
Downloading SomeExternalNugetTwo
... [Dump Data about internal Nuget only]
```
It stays stuck like this no error, no output (seems like our proxy is rejecting paket but silently)

So i tried locally sicne it works likes a charm with "System Proxy" :
* With Proxy set on the System : Everything works without any ENV_VAR
* Removing System proxy
  * Restore only internal Remote nuget
  * Cannot download from Nuget.org
* After setting env within a special cmd only
  * Tons of 407 error ==> _**Cannot use credential on CI**_
* Tried with "paket.exe.config" with `<defaultProxy useDefaultCredentials="true">` and <proxy proxyaddress="http://myNtlmProxy:PortHere"/>
```
Paket failed with:
        Could not download XXX y.y.y
    Couldn't get package details for package XXX y.y.y on http://api.nuget.org/v3/index.json.
StackTrace:
     at Paket.NuGetV2.download@988-43.Invoke(String message)
   at Paket.NuGetV2.download@904-40.Invoke(Exception _arg10)```

* Combinaison of HTTP_PROXY HTTPS_PROXY, paket.exe.config
  * Still failling or get Stuck indefinitly times to times

What did I missed ? from the source code paket :

```
    [ "http"; "https" ]
    |> List.fold addProxy Map.empty
```

This is adding the Proxy, wich end up in 407 so how does it works locally with system proxy and not local proxy and/or .config `<defaultProxy useDefaultCredentials="true">`

**Comment by tebeco** [comment]
closing this one, cant remember if i managed to make it works but the account is authorized so ...
