### ISSUE TITLE
[4.0.0-alpha030] - paket init creates misnamed bootstrapper with bizarre behavior

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#2050]
### Description

I use a global version of paket that's on my `PATH`, when I ran `paket init` in a new directory it created 

![](http://i.imgur.com/SoaZyq8.png)

which confused me, but I figured the `paket.bootstrapper.exe`  file had been created with the wrong name, so I decided to run it and see what would happen and I got -

```
λ» .\.paket\paket.exe --help
Paket version 4.0.0-alpha030
Help was requested:
USAGE: paket [--help] [--verbose] [--log-file <path>] [--silent] [--version] [<subcommand> [<options>]]

SUBCOMMANDS:

    add <options>         Adds a new package to your paket.dependencies file.
    clear-cache <options> Clears the NuGet and git cache folders.
    config <options>      Allows to store global configuration values like NuGet credentials.
    convert-from-nuget <options>
                          Converts from using NuGet to Paket.
    find-refs <options>   Finds all project files that have the given NuGet packages installed.
    init <options>        Creates an empty paket.dependencies file in the working directory.
    auto-restore <options>
                          Enables or disables automatic Package Restore in Visual Studio during the build process.
    install <options>     Download the dependencies specified by the paket.dependencies or paket.lock file into the `packages/` directory and update projects.
    outdated <options>    Lists all dependencies that have newer versions available.
    remove <options>      Removes a package from your paket.dependencies file and all paket.references files.
    restore <options>     Download the dependencies specified by the paket.lock file into the `packages/` directory.
    simplify <options>    Simplifies your paket.dependencies file by removing transitive dependencies.
    update <options>      Update one or all dependencies to their latest version and update projects.
    find-packages <options>
                          Allows to search for packages.
    find-package-versions <options>
                          Allows to search for package versions.
    show-installed-packages <options>
                          Shows all installed top-level packages.
    show-groups <options> Shows all groups.
    pack <options>        Packs all paket.template files within this repository.
    push <options>        Pushes the given `.nupkg` file.
    generate-include-scripts <options>
                          Allows to generate C# and F# include scripts which references installed packages in a interactive environment like F# Interactive or ScriptCS.
    why <options>         Prints user-friendly reason for referencing a specified package

    Use 'paket <subcommand> --help' for additional information.

OPTIONS:

    --verbose, -v         Enable verbose console output for the paket process.
    --log-file <path>     Specify a log file for the paket process.
    --silent, -s          Suppress console output for the paket process.
    --version             Display the version.
    --help                display this list of options.
```
 
which confused me even more.

so I renamed the file to `paket.bootstrapper.exe` and the `.config` to match it and ran it again and it downloaded paket4 properly.

after I renamed the bootstrapper to `run.exe` and saw that it still worked like the boostrapper should, then I removed paket from my `PATH`, deleted `paket.targets` and `paket.bootstrapper.exe` and ran the file again, and it went back to listing the commands for `paket`

![](http://i.imgur.com/CJLzL3u.png)

** SIDE NOTE ** - `paket.bootstrapper.exe` should get an file icon too

**Comment by cloudRoutine** [comment]
....aaaaand someone just told me about [magic mode](https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode) 

it should probably echo that it's running in "magic  mode" on the commandline 

personally I don't think this should be the default created by `paket init`

**Comment by forki** [comment]
Magic mode is the new default. It's a million times more useful. But we
need to iron out issues that users might have.

Am 30.11.2016 07:38 schrieb "Jared Hester" <notifications@github.com>:

**Comment by cloudRoutine** [comment]
if there's going to be a global cache, why not put it in somewhere like `%USER%/.paket/cache` instead of `Temp`?

**Comment by matthid** [comment]
I think this works as designed.

**Comment by 0x53A** [comment]
> Magic mode is the new default. It's a million times more useful. But we
need to iron out issues that users might have.

probably a bit late, but I'm not a big fan of magic mode. We lock our packages because we want a fixed behavior between dev and CI. The same should be true of the version of paket used. Updating it should be a conscious decision.

At the least, paket.init should write its current version to the paket.dependencies file.

**Comment by matthid** [comment]
@0x53A Yes I agree. I hope there will be a better alternative with netcore soon :)

**Comment by 0x53A** [comment]
Is there anything planned? Or how does netcore affect that?
