### ISSUE TITLE
Suggestion - include nupkgs with github releases

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#2051]
Additionally each github release should upload the `nupkgs` for 

- [paket.bootstrapper](https://www.nuget.org/packages/paket.bootstrapper/)
- [paket](https://www.nuget.org/packages/Paket/)
- [paket.core](https://www.nuget.org/packages/Paket.Core/)
- [paket.powershell](https://www.nuget.org/packages/Paket.PowerShell)

and zip archive for the `paket.powershell` psmodule

I'll even do the `build.fsx` PR myself 😜

**Comment by enricosada** [comment]
Closing, done.
