### ISSUE TITLE
Source protocol changes from HTTPS to HTTP

### ISSUE THREAD

**Issue by scoobadog** [fsprojects/Paket#2053]
When a NuGet v3 API is used the source protocol changes from HTTPS in `paket.dependencies` to HTTP in `paket.lock`.

**Comment by forki** [comment]
It's just normalizing the url. It should still always use the https in the
calls. Can you please check if that's true?

Am 30.11.2016 09:30 schrieb "Janne K" <notifications@github.com>:

**Comment by scoobadog** [comment]
scoobadog/PaketRepro branch issue#2053 has a repro

**Comment by scoobadog** [comment]
According to verbose log it's using v2 API over HTTP

```
Downloading AutoMapper 5.2
Response from http://nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'AutoMapper') and (Normalized
Version eq '5.2.0'):
```

**Comment by cloudRoutine** [comment]
offending code
```
let normalizeFeedUrl (source:string) =
    match source.TrimEnd([|'/'|]) with
    | "https://api.nuget.org/v3/index.json" -> Constants.DefaultNuGetV3Stream 
    | "http://api.nuget.org/v3/index.json" -> Constants.DefaultNuGetV3Stream.Replace("https","http")
    | "https://nuget.org/api/v2" -> Constants.DefaultNuGetStream
    | "http://nuget.org/api/v2" -> Constants.DefaultNuGetStream.Replace("https","http")
    | "https://www.nuget.org/api/v2" -> Constants.DefaultNuGetStream
    | "http://www.nuget.org/api/v2" -> Constants.DefaultNuGetStream.Replace("https","http")
    | url when url.EndsWith("/api/v3/index.json") -> url.Replace("/api/v3/index.json","")
    | source -> source
```
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Utils.fs

**Comment by forki** [comment]
we should normalize to https

**Comment by eugene-g** [comment]
#2071 should fix the issue, but I didn't test it nor checked if there exists related test.
If it's not enough, I'll dig it later this week.

**Comment by eugene-g** [comment]
Already released. I just tested and it works.

**Comment by scoobadog** [comment]
Thanks guys for a quick fix.
