### ISSUE TITLE
Binding Redicts are added only occasionally

### ISSUE THREAD

**Issue by Gonnagle** [fsprojects/Paket#2063]
### Description

Can't figure out why Binding Redirects are being added by paket only on some packages when I have set `redirects: on` or add `--redirects` parameter for paket.

### Repro steps

In this simple [example repo](https://github.com/Gonnagle/paket-tests/releases/tag/no-binding-redirects-transitive) I have the following paket.dependencies file (and xunit is added to project ConsoleApplication): 

```paket
redirects: on
source https://nuget.org/api/v2

nuget xunit
```

Now if i run any of the following

* `paket install`
* `paket install -f`
* `paket install -f --redirects`
* `paket install -f --redirects --createnewbindingfiles`

### Expected behavior

Binding Redirects are added to the existing App.config file. For the package itself and also for all the transitive dependencies.

Could be that I've misunderstood something here, but the [documentation ](https://fsprojects.github.io/Paket/dependencies-file.html#Redirects-option) quite clearly states:

> tells paket to create Assembly Binding Redirects for all referenced libraries

So I'd assume that all libraries that are added as reference in *.csproj, would get matching Binding Redirects added to App.config as well (direct and transitive).

### Actual behavior

Binding Redirects are not added. Not for the given package nor for the transitive dependencies.

### Remarks and additional info

No known workarounds. I tried to add the package with `--redirects` flag, but this did not help. Also tried to set `nuget xunit redirects: force` on `paket.dependencies`, but no luck there either.

On the other hand in the following test paket seems to add Binding Redirect for FSharp.Core, but not for UnionArgParser: https://github.com/Gonnagle/paket-tests/releases/tag/binding-redirects-partially-working

Weirdly if I try to add FSharp.Core to the original test (next to xunit) the redirects fail to appear for this package also...

**Comment by niklaskallander** [comment]
In my very limited experience with Paket, I've noticed that binding redirects are lost/not generated for transitive dependencies.

**Comment by isaacabraham** [comment]
If I remember correctly, the original implementation of BR code in Paket did exactly that - it was very simple and spat out BRs into the config file even if they weren't needed. I believe that the more recent implementation was a lot smarter and only added in BRs when they were necessary.

**Comment by forki** [comment]
usually redirects: force do a better job than on

**Comment by isaacabraham** [comment]
@forki is this a real argument? I couldn't find it documented anywhere.

**Comment by forki** [comment]
Force? Yes in the dependencies file. Should be documented

**Comment by isaacabraham** [comment]
I just tried it - it removed all BRs completely.

**Comment by smoothdeveloper** [comment]
@isaacabraham that behaviour is easy enough to document :laughing:

**Comment by Gonnagle** [comment]
I actually just managed to get the provided example to work by setting the `redirects: force` for the given nuget:

```
redirects: on
source https://nuget.org/api/v2

nuget xunit redirects: force
```

Changing the `redirects:` on the top of the file between `on` and `off` didn't seem to have any effect at all. And also tried to set this to `force` which resulted only to ``REDIRECTS: ON` to disappear from the lock-file (no BRs). So this seems to be supported only on individual dependencies?

Paket version used was `3.33.5`.

**Comment by Gonnagle** [comment]
Just tested this with `5.100.2` and it seems that the solution wide option `paket.dependencies` now works as expected. So changing it as follows:

```
redirects: force
source https://nuget.org/api/v2

nuget xunit redirects: force
```

And running `paket install -f` now creates the binding redirects as expected.
