### ISSUE TITLE
How to handle two packages containing assemblies with the same name

### ISSUE THREAD

**Issue by FunctionalFirst** [fsprojects/Paket#2064]
### Description

This issue is caused by an assembly, System.Collections.Immutable, being released under two different package IDs, _Microsoft.Bcl.Immutable_ up to version v1.0.34, and _System.Collections.Immutable_ thereafter. 

When System.Collections.Immutable is a top-level dependency, and Microsoft.Bcl.Immutable is a transitive dependency, compile errors like the following occur:

> The type 'ImmutableHashSet<T>' exists in both 'System.Collections.Immutable, Version=1.0.34.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	AGS.Web.Services	

### Repro steps

1. add nuget System.Collections.Immutable to paket.dependencies

2. add nuget Shields.Graphviz to paket.dependencies (and the same project)

Sample VS2015 project - [NewRepo.zip](https://github.com/fsprojects/Paket/files/625623/NewRepo.zip)

### Expected behavior

A way to instruct paket to use System.Collections.Immutable as the transitive dependency instead of Microsoft.Bcl.Immutable.

### Actual behavior

I haven't found a way to achieve this. 

### Known workarounds

None that I know of.

**Comment by cdrnet** [comment]
This should be resolved once `Shields.Graphviz` makes a new release. It has already been [updated](https://github.com/timothy-shields/graphviz/pull/1) in the source. The old BCL package has actually been unlisted.

**Comment by FunctionalFirst** [comment]
@cdrnet Very nice. Thanks!

**Comment by enricosada** [comment]
reference are added in order, compiler use last one.

Closing, was fixed by fixing the package
