### ISSUE TITLE
Resolution issue when using constraints

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#2069]
We have lots of different internal packages and they usually sent lower limit on dependencies. When I then try to use one of those dependencies with upper version limit, paket comes to endless resolution cycle. I am not sure if it ever ends since I am not patient enough to wait for it to visit all versions of all involved packages.

Here is the example diagnostic message:
```
  Could not resolve package MassTransit:
   - Dependencies file requested package MassTransit: < 3.5
   - Abax.MassTransit 0.3.0-unstable0006 requested package MassTransit: >= 3.4.1
   - Abax.Services.Base.MassTransit 1.0.0 requested package MassTransit: >= 0
   - Abax.SimpleDdd.MassTransit 0.1.0-unstable0006 requested package MassTransit: >= 0
   - MassTransit.Automatonymous 3.4.2 requested package MassTransit: >= 3.4.2
   - MassTransit.RabbitMq 3.4.1 requested package MassTransit: >= 3.4.1

The process is taking longer than expected.
Paket may still find a valid resolution, but this might take a while.
```

It is clear that there is no real issue with these constrains since MassTransit 3.4.1 fits all of them but for some reason paket is unable to figure this out.

Since most of the involved packages are internal on private nuget feed, I am not sure how to create a repo to reproduce this.

**Comment by alexeyzimarev** [comment]
I see now that I made a mistake by having this `MassTransit.Automatonymous 3.4.2 requested package MassTransit: >= 3.4.2`. May be this is the reason. I will check and update the issue.

**Comment by alexeyzimarev** [comment]
I found that we do have MassTransit 3.4.2 on our private feed so it should resolve it.

**Comment by alexeyzimarev** [comment]
So if I change `paket.dependencies` to have "equals" constraint like this:

```
nuget MassTransit.Automatonymous = 3.4.2
nuget MassTransit  = 3.4.2
nuget MassTransit.RabbitMq  = 3.4.2
```
it works fine. If I set it to `< 3.5` - it goes to this endless resolution cycle.

**Comment by cdrnet** [comment]
Does Paket find that specific version on the private feed when using `paket.exe find-package-versions`?

**Comment by alexeyzimarev** [comment]
It all works fine when I set version lock to a specific version

**Comment by cdrnet** [comment]
Yes, in this case it does not need to look for other versions. I was asking because private feeds can be quite broken such that find-package-versions might not be able to find all versions (e.g. Artifactory).

**Comment by matthid** [comment]
Closing as I think this has been solved. Please let us know if this still doesn't work.
