### ISSUE TITLE
Failing to add reference to System.Runtime.InteropServices.RuntimeInformation dll

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#2072]
### Description

Hi I tried to install  MongoDB.Driver and looks like it not adding all of it dependencies to the solution
paket correctly resolves all of the dependencies in the lock file:
    MongoDB.Bson (2.4)
    MongoDB.Driver (2.4)
      MongoDB.Bson (>= 2.4)
      MongoDB.Driver.Core (>= 2.4)
    MongoDB.Driver.Core (2.4)
      MongoDB.Bson (>= 2.4)
      System.Runtime.InteropServices.RuntimeInformation (>= 4.0)
    System.Runtime.InteropServices.RuntimeInformation (4.3)

But in project file it not adding  reference for System.Runtime.InteropServices.RuntimeInformation

### Repro steps

Download attached file, rename it to zip,  you will find inside two solution one using nugget other using paket 
[Repro.txt](https://github.com/fsprojects/Paket/files/635999/Repro.txt)

### Expected behavior

All references should be added to csproj

**Comment by tsibelman** [comment]
@forki I had same issue with another package Troschuetz.Random it dependent on Thrower and Thrower is not added to project

**Comment by forki** [comment]
Do you have a repro for the second one? I assume they have different root causes

**Comment by tsibelman** [comment]
Yes you correct it a different issue here it looks like Thrower is not added to paket.lock here repro
[PaketWithProblem.zip.txt](https://github.com/fsprojects/Paket/files/651235/PaketWithProblem.zip.txt)

**Comment by forki** [comment]
regarding case1: if I run install I see:

![image](https://cloud.githubusercontent.com/assets/57396/21176464/24cebb2e-c1e7-11e6-8d40-ac961055cb64.png)

so I assume it is a caching issue. Can you please run paket clear-cache and try again?

**Comment by forki** [comment]
regarding case 2: are you sure nuget is installing that dep for net451? It does not have net451 case in meta data

**Comment by forki** [comment]
@matthid: https://www.nuget.org/packages/Troschuetz.Random/ yet another way...

**Comment by forki** [comment]
@matthid @tsibelman I think it should be done like this: https://github.com/pomma89/Troschuetz.Random/pull/3

**Comment by tsibelman** [comment]
For case 1 clear cache worked thank you , I will be sure to make it as first step to solve problems in the future. For case 2 I don't sure what you suggesting

**Comment by tsibelman** [comment]
I tried adding Troschuetz.Random via nugget and it worked correctly maybe it relies on Portable Class Library (.NETFramework 4.5, Windows 8.0, WindowsPhone 8.0, WindowsPhoneApp 8.1) ?

**Comment by forki** [comment]
I need to dig a bit deeper. but I hope pomma89/Troschuetz.Random#3 gets merged

meanwhile you can manually add the Thrower dep to your deps and references file

**Comment by tsibelman** [comment]
@forki  Looks like real issue exists with MongoDB.Driver if I add  NETStandard.Library to paket.dependencies that has reference to System.Runtime.InteropServices.RuntimeInformation 4.3 paket takes ver 4.3 as it should but in app.config it redirects to older version like this oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.0.1.0" it looks like the same issue as #2090,

You can check attached repro
[PaketWithProblem.zip.txt](https://github.com/fsprojects/Paket/files/663008/PaketWithProblem.zip.txt)

**Comment by forki** [comment]
It looks like mono.cecil says the /ref/netstamdar1.1/System.Runtime.InteropServices.RuntimeInformation.dll has version 4.0.1.0

**Comment by forki** [comment]
seems dotpeek aggrees

**Comment by tsibelman** [comment]
It not works in runtime it tries to load 4.0.1.0 and fails

**Comment by forki** [comment]
I don't really know what going wrong now. The version of the lib is clearly 4.0.1.0 and that's what we put into the app.config. Seems we need to find expert in this area

**Comment by tsibelman** [comment]
I see now that it marked in csproj as CopyLocal=False, maybe this the issue ?

**Comment by tsibelman** [comment]
With CopyLocal=False I get this exception

Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

With CopyLocal=True I geting this exception 

Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

WTF ?

**Comment by vilinski** [comment]
Downgrade the mongo driver to 2.2.4 works for me. They forgot to set dependency in the nuget. Although the ticket is closed as fixed in 2.4
https://jira.mongodb.org/browse/CSHARP-1807

**Comment by tsibelman** [comment]
Ok @forki  I found the root issue, looks like this reference is handled differently in nugget so I changed the csproj to make it work.

Original created via paket
```
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.1'">
      <ItemGroup>
        <Reference Include="System.Runtime.InteropServices.RuntimeInformation">
          <HintPath>..\packages\System.Runtime.InteropServices.RuntimeInformation\ref\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll</HintPath>
          <Private>False</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
```
Here is the version that I changed by hand in order to make it work, I bolded changes 

```
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.1'">
      <ItemGroup>
        <Reference Include="System.Runtime.InteropServices.RuntimeInformation">
          <HintPath>..\packages\System.Runtime.InteropServices.RuntimeInformation\**lib\net45**\System.Runtime.InteropServices.RuntimeInformation.dll</HintPath>
          <Private>**True**</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

**Comment by forki** [comment]
wtf .net 451 should be compatible with .NET standard 1.1

**Comment by tsibelman** [comment]
Looks like dlls in different folders are different in size so I don't know what going on here, also I don't understand the difference between ref and lib folders, why paket is pointing to ref ?

**Comment by forki** [comment]
it shouldn't - just checking that

**Comment by forki** [comment]
please retry

**Comment by tsibelman** [comment]
It works . You the best.

**Comment by matthid** [comment]
I think you should use ref for compiling and lib for copying in this new world... This probably breaks some stuff in fake.vnext but I'm not sure if there is a simple fix for that...

**Comment by forki** [comment]
Ah that makes sense.

Am 20.12.2016 6:14 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
I had this on my radar and probably need to handle that sooner or later. But I have no idea how it would look in a perfect world. Its unrealistic that I have time for this anytime soon (maybe vacation...)

**Comment by vilinski** [comment]
Now it doesn't work in mono/linux. 
Paket downloads the System.Runtime.InteropServices.RuntimeInformation.dll (4.3) from nuget, but it seems to be a windows version - it calls into ntdll.dll on runtime and fails.
In my GAC I have a binary different from it. My program works fine if I manually delete the dll from build directory. MongoDB.Driver.Core 2.3 didn't referenced this dll, so as a workaround one can stick to 2.3 or delete it in the build script.

**Comment by IanMercer** [comment]
[Not using Paket] but I finally managed to get MongoDB 2.4.4 to work by adding the following to web.config:

```
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices.RuntimeInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>

```
There is some extreme version wierdness going on with that DLL and the Nuget package containing it.

**Comment by enricosada** [comment]
> It works . You the best.

Was fixed

**Comment by ToMakeSense** [comment]
Again, the same issue for dependency hell, add [SOF refers](https://stackoverflow.com/questions/44825245/c-sharp-system-runtime-interopservices-runtimeinformation-constant-annoyance-w) for future visitors
