### ISSUE TITLE
The localized satellite lib does not copy into the primary package

### ISSUE THREAD

**Issue by aconys** [fsprojects/Paket#2078]
### Description
Paket version 3.31.2
A feature copy localized files into primary package's lib does not work with paket

Nuget doc => https://docs.nuget.org/ndocs/create-packages/creating-localized-packages
" NuGet will recognize the package as a satellite package and install the localized files into the primary package's lib folder, as if they had been originally bundled."

Ex :
2 nuget packages

Primary package :
- lib
     -net40
          .MyLib.dll

Satellite package :
- lib
     -net40
          -de
               .MyLib.resources.dll

Satellite uses nuspec <language> and <dependency>
<dependency> reference the Primary package

paket dependencies file reference only the satellite package

paket restore, installs satellite package and primary package **BUT does not copy lib localized in Primary package lib.**

### Repro steps
[SampleLocalization.zip](https://github.com/fsprojects/Paket/files/652147/SampleLocalization.zip)

1. Unzip my sample SampleLocalization.zip
2. Open a command a Command Prompt or powershell
3. Go to in folder .paket
4. enter : .\paket.exe restore

### Expected behavior
Restored nuget packages + dependencies and localized packages lib copied into primary lib folder
in folder => **packages**

### Actual behavior
All packages are restored but localized lib in Satellite packagesare not copied in primary package

### Known workarounds
Manual copy

**Comment by forki** [comment]
Why did you close it? Did it work? I always thought we already do that

**Comment by aconys** [comment]
Duplicate with #1980
