### ISSUE TITLE
"unlisted" being output during update and slow package resolution

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#2084]
### Description

Paket version: 4.0.0-alpha033
Issue symptoms: 
- "unlisted" being written into log
- Slowness when resolving dependencies.

I just tried a convert-from-nuget on a new ASP.NET Core WebAPI project template in Visual Studio 2017 (latest update with simplified csproj). It took huge amounts of time to do the version resolution, I didn't actually get to the end after half an hour and cancelled it. The following 3 sources were added even though I only have the official feed in my sources inside Visual Studio:

```
source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
source https://dotnet.myget.org/F/cli-deps/api/v3/index.json
source https://api.nuget.org/v3/index.json
```

I cancelled it and then decided to run a paket update, because the convert-from-nuget now writes the dependencies and references file before this (thanks for changing that it's much better!). I slimmed the sources down to:

```
source https://api.nuget.org/v3/index.json
```

Because I thought the myget feeds might be causing the slowness. During the update it ran a bit faster but I still didn't let it finish as it was taking so long. It was writing a lot of "unlisted" lines into the output as can be seen here:

![Image of unlisted output logs](https://pbs.twimg.com/media/Cz9BUfxXAAAHvDg.jpg)

For the slowness, I've had this before at work about a year ago when proxy settings were enabled in Windows but I don't have this on my laptop at home, where I am now off my work VPN, so not sure why I'm seeing it. Paket update runs very quickly using Paket version 3.13.3.0 on a normal .NET/PCL project.

I've zipped up the solutions: 
- [Starting Point](https://dl.dropboxusercontent.com/u/49591225/Code/PaketTest_ConvertFromNuGetIssue_StartingPoint.zip)
- [Unlisted Output](https://dl.dropboxusercontent.com/u/49591225/Code/PaketTest_ConvertFromNuGetIssue_UnlistedOutput.zip)

### Expected behaviour

- Unlisted is not output, or if there is actually an issue with the packages then a better description
- The restore runs quickly (maybe this is an issue with my machine?)

**Comment by forki** [comment]
@cloudRoutine I assume the second zip makes for a good sample for resolver improvements. Maybe you are interested to take a look.

@cjbhaines I improved the output in the trace. The slowness comes from the overspecification. If you remove the version pins in the paket.dependencies file it actually finshed after a while. Second update will then be a bit faster

**Comment by cjbhaines** [comment]
@forki thanks for fixing that! 

I just got through an update in 4 minutes and 25 seconds by floating the version to ~> 1.0. The packages and versions listed are the default project template so the resolution should be fairly straight forward shouldn't it? This might be a problem in the future because .NET Core 1.1 was only released last month and people might not want to go forward yet, which I just updated to by floating but it also requires a change to the target framework in csproj, so they will have to pin framework versions and then will have issues updating if they want to pull a new third party dependency update.

**Comment by forki** [comment]
you can still pin. but you don't want to pin all the things

**Comment by cjbhaines** [comment]
Ok, before we finish this one up then, do you know where the myget references are coming from when running the convert? I can't find them anywhere in my sources.

**Comment by forki** [comment]
probably inherited from the configs machinewide
