### ISSUE TITLE
Paket "auto-restore on" corrupts VS2017 csproj

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#2085]
### Description

Paket version: 4.0.0-alpha033

When enabling auto-restore for a .NET Core project, Paket adds a namespace to the import which is invalid in the schema:

```
<Import Project="..\.paket\Paket.Restore.targets" />
<Import Project="..\.paket\paket.targets" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />
```

error  : The attribute "xmlns" in element <Import> is unrecognized.  C:\Temp\PaketTest\packages_unlisted\ConvertTest\ConvertTest.csproj

Is auto-restore meant to work with .NET Core projects? 

### Repro steps

https://dl.dropboxusercontent.com/u/49591225/Code/PaketTest_UnknownNamespace.zip

Unzip solution, then run:

```
dotnet restore
.paket\paket auto-restore on
```
### Expected Behaviour

Paket does not add an unexpected namespace.

**Comment by forki** [comment]
Good point. We don't need to do that in core projects.

**Comment by cjbhaines** [comment]
Just updated to Paket version: 4.0.0-alpha034 and tried a convert form nuget on one of my real solutions. It added the following targets:

```
<Import Project="..\..\..\.paket\paket.targets" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />
```

Instead of the new .NET Core ones:

```
<Import Project="..\..\..\.paket\Paket.Restore.targets" />
```

**Comment by bhugot** [comment]
Hello with the paket version:  4.0.0-alpha035 when we do install in a project the following import is added to csproj

  <Import Project=".paket\Paket.Restore.targets" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" /> but xmlns is not recognize and if I remove this attribute so I have  only <Import Project=".paket\Paket.Restore.targets" /> then it's working without any problem.

**Comment by forki** [comment]
do you have the full fsproj for me?

**Comment by forki** [comment]
@bhugot could you please try latest?

**Comment by bhugot** [comment]
@forki still the same, the proj is a simple dotnet create -t console on which I did convert from nuget with the last prerelease. I have some issue accessing to github from my computer at work why do not use
`let createNode name (project:ProjectFile) = 
        project.Document.CreateElement (name, project.Document.DocumentElement.NamespaceURI)`

**Comment by forki** [comment]
That's what we do in latest paket 4

Am 20.12.2016 1:52 nachm. schrieb "Benjamin Hugot" <notifications@github.com

**Comment by forki** [comment]
See core 3 branch.

Can you please upload a zip with the repro project?

Am 20.12.2016 1:54 nachm. schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

**Comment by bhugot** [comment]
Yup i noticed it, I can't from work but I m going to send it later

**Comment by bhugot** [comment]
@forki I just tried with project.Document.DocumentElement.NamespaceURI and not project.ProjectNode.NamespaceURI and it's working

**Comment by forki** [comment]
Could you please send a pull request? Thanks

Am 20.12.2016 14:51 schrieb "Benjamin Hugot" <notifications@github.com>:

**Comment by bhugot** [comment]
Last version is still not working because I just switched in your test but in fact I think when in dotnet core we need a null as namespace. I m going to do another pull request without the test.
