### ISSUE TITLE
.NET Standard libraries + FX 4.6.2: "Could not load file or assembly..."

### ISSUE THREAD

**Issue by SuperJMN** [fsprojects/Paket#2090]
### Description

Runtime exception (**Could not load file or assembly...**) when running an application that targets .NET Framework 4.6.2 and uses **.NET Standard** libraries.

### Repro steps

1. Clone this GitHub project: https://github.com/SuperJMN/Avalonia-JMN/tree/paket (the branch named "**paket**", that is an attempt to migrate the solution to use Paket. 
2. Compile and run the application inside the Folder "Samples\Catalog" named **ControlCatalog.Deskop**

### Expected behavior

The application should load and run (a Windows should be shown)

### Actual behavior

A runtime exception is thrown:

> An unhandled exception of type 'System.IO.FileNotFoundException' occurred in OmniXaml.dll
> 
> Additional information: Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

It seems the references set by Paket after the migration aren't right. Maybe the Assembly Bindings are wrong, or the references inside the csprof file are wrong. I have tried almost everything to fix the problem, for more than 6 hours this weekend. Unfortunately, I don't know how to handle this problem.

Please, take a look to see what's happening. Before migrating from NuGet to Paket, the application ran just right.

**Comment by forki** [comment]
this project doesn't build for me - probably I'm missing some VS components.


But yes there are assembly binding redirects missing. In your paket.dependencies file you explicitly reference System.ComponentModel.Primitives 4.3.0 but somewhere else 4.1.1.0 is used. This is a typical issue when using nuget.

There are three possible ways to solve that. 
1) try to find the place where 4.1.1.0 is referenced and remove the version dependency  (this might be hard when it comes from external)
2) set nuget System.ComponentModel.Primitives to 4.1.1.0 in deps file and run install again
3) add ", redirects: force" to the nuget System.ComponentModel.Primitives line and run install again

In general you want to go over your deps file and try to remove as many version pins as possible

**Comment by SuperJMN** [comment]
Thanks a lot for you help! I haven't found the project / reference that is using 4.1.1.0. Is there any tool or method to discover transitive references to different versions? I'm inside of a big mess...

**Comment by forki** [comment]
not that I know of. this a real issue. 
One of the reasons for paket is to make this better maintainable. but first you need to get to a stable state. unfortunately we canfix all the things

**Comment by SuperJMN** [comment]
That's a big bummer :( Maybe if you get the project to compile you could figure out what's happening. What compile error are you getting? Big thanks!

**Comment by forki** [comment]
even then. It's a lot of guesswork and all these issues are already present in the nuget version, but even more hidden.

**Comment by forki** [comment]
"search in files" brought:

![image](https://cloud.githubusercontent.com/assets/57396/21311056/81c53176-c5e5-11e6-8e62-7ce042d17062.png)

**Comment by forki** [comment]
and there are more in different app.configs - probably all cases where still packages.config files exist

**Comment by forki** [comment]
e.g. D:\temp\Avalonia-JMN\src\Markup\OmniXAMLv2\OmniXaml.Tests

**Comment by forki** [comment]
I assume you didn't convert the git submodules.

**Comment by SuperJMN** [comment]
Supposedly, I converted the submodules, too.

The package I want to install is System.ComponentModel.TypeConverter 4.3.0, but it depends on System.ComponentModel.Primitives 

Could it be a problem that the package System.ComponentModel.Primitives 4.3.0 contains an assembly whose version is 4.1.1? 

![captura](https://cloud.githubusercontent.com/assets/3109851/21311613/58a3fbbc-c5e8-11e6-8150-96d6845ebb22.PNG)

I don't have a clue of what's wrong :(

**Comment by forki** [comment]
> I don't have a clue of what's wrong :(

yes that is nuget version hell. 
I reccmomend you start with 

3) add ", redirects: force" to the nuget System.ComponentModel.Primitives line and run install again

**Comment by SuperJMN** [comment]
Right now I'm doing some tests to see if I can discover what's the problem. For now, I'm working with a much smaller solution that works, mysteriously. I have a Test Project with the offending assemblies/versions and it runs perfectly.

**Comment by SuperJMN** [comment]
OK, I have created **the bare minimum project** to reproduce this issue (or another that is VERY SIMILAR). It's pusblished it HERE (https://github.com/SuperJMN/PaketTesting). Please, clone it. It's super simple.

Inside I have only 2 projects. 
1. One is Class Library (Portable Class Library that targets .NET Standard 1.2), named "ClassLibrary";
2. The other is a .NET Framework 4.6.2 project, named "Sample"

The project in 2 references the class library in 1.

Running the Sample throws an exception:
```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot load the file specified. 
```

To make sure the references a fresh, I tried removing every reference in Sample except for ClassLibrary and invoked `paket install -f,`.

With this, some references are restored to the project, like mscorlib, System, System.Core...

What's the deal?

**Comment by forki** [comment]
can you please try again with latest? we fixed a problem that might be related

**Comment by SuperJMN** [comment]
Wow, it's working! At least in my Sample project, the toy application I created to reproduce the issue. It changed Sample.csproj

Here is the diff:
![captura](https://cloud.githubusercontent.com/assets/3109851/21361480/7e939d62-c6e4-11e6-8351-a97bbbc5f868.PNG)

I will have to test extensively, but for now, the problem is solved :)

Big thanks!
