### ISSUE TITLE
Mono, paket 3.31.6, usageStringCharacterWidth error

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#2092]
### Description

Getting an error in on Linux, Mono 4.6.2

```
Paket failed with:
    Must be positive value.
Parameter name: usageStringCharacterWidth
```

### Repro steps

1. Use a linux/docker container with mono 4.6.2
2. Run paket restore 

CI build shows it in action as well.
https://travis-ci.org/fsprojects/Paket/builds/185498758

### Expected behavior

Paket runs

### Actual behavior

Paket does not run

### Known workarounds

Pinning on paket.exe 3.31.5

**Comment by alexey-belous** [comment]
Have same issue

**Comment by forki** [comment]
Can you please try to send me a PR?

Am 20.12.2016 5:54 nachm. schrieb "Alexey" <notifications@github.com>:

**Comment by alexey-belous** [comment]
@forki, sorry, but I have no idea how to fix this issue. I just have a suggestion that mentioned commit may be a root cause of this issue.

**Comment by nosami** [comment]
Can confirm. Pinning Paket to 3.31.4 works for now.

```
+++ b/main/external/fsharpbinding/.paket/paket.targets
@@ -13,7 +13,7 @@
   <PropertyGroup>
     <!-- Paket command -->
     <PaketExePath Condition=" '$(PaketExePath)' == '' ">$(PaketToolsPath)paket.exe</PaketExePath>
-    <PaketBootStrapperExePath Condition=" '$(PaketBootStrapperExePath)' == '' ">$(PaketToolsPath)paket.bootstrapper.exe</PaketBootStrapperExePath>
+    <PaketBootStrapperExePath Condition=" '$(PaketBootStrapperExePath)' == '' ">$(PaketToolsPath)paket.bootstrapper.exe 3.31.4</PaketBootStrapperExePath>
     <PaketCommand Condition=" '$(OS)' == 'Windows_NT'">"$(PaketExePath)"</PaketCommand>
     <PaketCommand Condition=" '$(OS)' != 'Windows_NT' ">$(MonoPath) --runtime=v4.0.30319 "$(PaketExePath)"</PaketCommand>
     <PaketBootStrapperCommand Condition=" '$(OS)' == 'Windows_NT'">"$(PaketBootStrapperExePath)"</PaketBootStrapperCommand>
```

**Comment by forki** [comment]
Ok. Will revert argu update when I'm home and hopefully @eiriktsarpalis can send a pull request with showing me the error. It's especially weird that this only happens on mono.

**Comment by alexsorokoletov** [comment]
as @nosami pointed, you just need to specify required version as argument to paket.bootstrapper.exe 

`paket.bootstrapper.exe 3.31.5`

Glad the discussion is live as our FAKE scripts failed this morning :)

**Comment by varon** [comment]
Also getting this on Teamcity + Fake builds on mono/linux. Pinning to 3.31.5 works around it, but isn't ideal.

**Comment by forki** [comment]
ok I reverted. can someone please confirm 3.31.7 is good again?

**Comment by alexey-belous** [comment]
I've checked. 3.31.7 works. Thanks!)

**Comment by TheAngryByrd** [comment]
Seems to work for me 🎸

**Comment by varon** [comment]
Thanks!

**Comment by eiriktsarpalis** [comment]
@TheAngryByrd @alexey-belous Can you confirm that evaluating the `Console.WindowWidth` property on docker returns `0`? If so, this is related to an issue fixed in Argu 3.6.1

**Comment by forki** [comment]
ok I updated argu to 3.6.1 and hope the bug is gone. Can someone please verify that Pakt 3.31.8 still works on mono?

**Comment by alexey-belous** [comment]
@forki, 3.31.8 works for me.

**Comment by forki** [comment]
thanks everyone!
