### ISSUE TITLE
framework: auto-detect causes Out of sync warning

### ISSUE THREAD

**Issue by inosik** [fsprojects/Paket#2096]
### Description

As the title says, `framework: auto-detect` in `paket.dependencies` causes the out-of-sync warning to be printed.

### Repro steps

1. Create a `paket.dependencies` with `framework: auto-detect`, like this:

   ```
   source https://nuget.org/api/v2
   framework: auto-detect

   nuget Expecto
   ```

1. Create an F# project with a `paket.references`:

   ```
   Expecto
   ```

1. `$ paket install`

1. `$ paket restore`

### Expected behavior

I don't know what would be the best here. Maybe the warning should also tell *why* the warning is printed, so I can decide whether it is important or not.

### Actual behavior

Paket prints the out-of-sync-warning. IMHO because `paket.lock` says `FRAMEWORK: NET45`.

### Known workarounds

* Change `framework: auto-detect` to `framework: net45` in `paket.dependencies`
* Use the `--ignore-checks` flag

**Comment by forki** [comment]
can you please a sample zip with the repro?

**Comment by inosik** [comment]
Here you go: [Repro2096.zip](https://github.com/fsprojects/Paket/files/741733/Repro2096.zip)
