### ISSUE TITLE
Template with multiparagraph description isn't working with LF line endings

### ISSUE THREAD

**Issue by scoobadog** [fsprojects/Paket#2104]
### Description

When a `paket.template` with multiparagraph description is saved with Unix line endings `paket pack` command fails with the following error message:

```
Paket failed with:
	Unable to parse template file C:\Work\PaketRepro\ConsoleApplication1\paket.template: Indented block with no name line 7.
```

### Repro steps

1. Create a template with multiparagraph description and save the file with LF line endings.

2. Run `paket pack output dist` command.

### Expected behavior

I would expect the command to execute without errors like it does if the description has only one paragraph and LF line endings.

### Actual behavior

The command fails with the error message described above.

### Known workarounds

Save the template with Windows line endings (CRLF).

**Comment by forki** [comment]
Could you please upload a zip with a repro?

**Comment by scoobadog** [comment]
Can be reproduced with `issue#2104` branch in [scoobadog/PaketRepro](https://github.com/scoobadog/PaketRepro) repository.
