### ISSUE TITLE
Error message when typing mono .paket/paket.exe init

### ISSUE THREAD

**Issue by mziemys** [fsprojects/Paket#2116]
Good day,

I have started to learn F# development recently and I cannot work with Paket package manager. When I try to init my project with command `mono .paket/paket.exe init` on macOS Sierra, I get an error message that says this:
`Paket version 3.33.4
Paket failed with:
	The type initializer for 'Paket.Constants' threw an exception.`

Is this some kind of bug or I am doing something wrong? I am currently following book "Analyzing and Visualizing Data with F#"

**Comment by GusBricker** [comment]
@mziemys Did you end up solving this?

**Comment by cjbush** [comment]
@GusBricker We've reproduced this on Windows 7 with multiple versions of Paket. It appears to be something related to the system, but I haven't been able to figure out what's causing it. This is the screenshot my teammate sent to me. Is there a way to get a more informative stack trace out of it?

![stacktrace](https://cloud.githubusercontent.com/assets/5855938/25722438/3bdcdb4c-30e2-11e7-84fe-a8d77554b650.jpg)

**Comment by GusBricker** [comment]
@cjbush I'm not sure as I am not a dev on this project. Sorry I can't be of more help :(

**Comment by forki** [comment]
@cjbush any chance for you to debug it? It's actually not doing anything interesting at that point.

Debugging should be easy:
* clone the project
* run "build.cmd" to see that paket can build itself
* open sln in VS
* set paket project as startup project
* set startup path in project properties
* F5

**Comment by gantrior** [comment]
I had the same issue and figured out that nuget cache was incorrectly configured and inaccessible. So fix for me was verifying "NuGetCachePath" environment variable and fixing its path. It is unfortunate that error describing that was seen only within 3 inner-exceptions (so only when debugging Paket), so not very obvious from exception message thrown to console..

**Comment by cjbush** [comment]
@gantrior That appears to have fixed the problem my teammate was having. He had his NuGetCachePath variable pointing at a portable drive that wasn't mounted. Undefining the variable so that it uses the default value worked. I think this is probably just a logging issue, more than an actual problem with paket itself.

**Comment by GusBricker** [comment]
@gantrior Do you mean NUGET_HTTP_CACHE_PATH environment variable?

**Comment by GusBricker** [comment]
Ignore my previous comment, it is actually `NuGetCachePath` and it does fix the issue. Also ensure the directory its set to exists as well.

**Comment by enricosada** [comment]
Closing, was an environment issue.

added https://github.com/fsprojects/Paket/issues/3010 to track to add a log instead of just crash
