### ISSUE TITLE
paket.exe clear-cache --verbose does not give any details

### ISSUE THREAD

**Issue by inwenis** [fsprojects/Paket#2118]
### Description

The option `--verbose` used for `paket.exe clear-cache` does not give any details
D:\git\process_runner\src\.paket [Qpp12Update ≡]> .\paket.exe clear-cache -v
Paket version 3.33.4
0 seconds - ready.
D:\git\process_runner\src\.paket [Qpp12Update ≡]> .\paket.exe clear-cache
Paket version 3.33.4
0 seconds - ready.

### Expected behavior

Would be nice if `--verbose` could give a list of cleared caches/cleared packages/size or anything

### Actual behavior

There are no details

**Comment by theimowski** [comment]
This should just boil down to trace verbose messages [here](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PublicAPI.fs#L23-L26) 
You can use `traceVerbose` function from [Logging](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Logging.fs#L33) module
