### ISSUE TITLE
Cannot consume NuGet packages from Team Foundation Server 2017 private feed

### ISSUE THREAD

**Issue by drwatson1** [fsprojects/Paket#2138]
### Description

I have TFS 2017 with a private feed for internal use. For NuGet.org it works fine, but I can't use my own packages from our internal TFS server with the error:

Paket failed with:
        There was a version conflict during package resolution.
  Could not resolve package GeoCybernetica.Dal:
   - Dependencies file requested package GeoCybernetica.Dal: >= 0
   - Available versions:
     - (1.1.0.52, [http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json])
     - (1.1.0.51, [http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json])
     - (1.1.0.50, [http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json])
     - (1.1.0.49, [http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json])

and so on...

### Repro steps

1. Create the file paket.dependencies with the following content:

```
source https://nuget.org/api/v2
source http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json username: "***" password: "***"

nuget GeoCybernetica.Dal 

```

I can send username and password to reproduce.

2. Execute .paket/paket.exe install

### Expected behavior

The package is installed successfully

### Actual behavior

Get an error as described above. 

### Known workarounds

Unknown

**Comment by drwatson1** [comment]
I've got the following error in verbose mode:

`found:somepath\paket.dependencies
Parsing somepath\paket.dependencies
Resolving packages for group Main:
  0 packages in resolution. 1 requirements left
  Trying to resolve GeoCybernetica.DataContracts >= 1.1.0.51 (fromsomepath\paket.dependencies)
  - fetching versions for GeoCybernetica.DataContracts
 - GeoCybernetica.DataContracts 1.1.0.60
Source 'http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json' exception: System.Exception: could not find an Paket.PackageSources+NugetV3ResourceType endpoint for http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json
   в Paket.NuGetV2.getPackageDetails@686-10.Invoke(Exception _arg5) в D:\GitHub\Paket\src\Paket.Core\NuGetV2.fs:строка 697
   в Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Source 'http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json' exception: System.Exception: could not find an Paket.PackageSources+NugetV3ResourceType endpoint for http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json
   в Paket.NuGetV2.getPackageDetails@686-10.Invoke(Exception _arg5) в D:\GitHub\Paket\src\Paket.Core\NuGetV2.fs:строка 697
   в Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Source 'http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json' exception: System.Exception: could not find an Paket.PackageSources+NugetV3ResourceType endpoint for http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json
   в Paket.NuGetV2.getPackageDetails@686-10.Invoke(Exception _arg5) в D:\GitHub\Paket\src\Paket.Core\NuGetV2.fs:строка 697
   в Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Source 'http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json' exception: System.Exception: could not find an Paket.PackageSources+NugetV3ResourceType endpoint for http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json
   в Paket.NuGetV2.getPackageDetails@686-10.Invoke(Exception _arg5) в D:\GitHub\Paket\src\Paket.Core\NuGetV2.fs:строка 697
   в Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
    Package not available.
      Message: Couldn't get package details for package GeoCybernetica.DataContracts 1.1.0.60 on http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json.`

But the package is available, of course

**Comment by forki** [comment]
mmm can you try to use the v2 endpoint?

**Comment by drwatson1** [comment]
No, I can't. There is only v3

**Comment by forki** [comment]
sforkmann @ gmail if you want to send me login

**Comment by drwatson1** [comment]
I sent
