### ISSUE TITLE
Paket auto-generate scripts uses wrong current directory with type providers

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#2139]
I'm sceptical if this is a Paket issue per se but interested if anyone else has seen this: -

```fsharp
#load @"..\..\paket-files\include-scripts\net452\include.main.group.fsx"
/// load some other files

open FSharp.ExcelProvider
/// open some other namespaces

type Component = ExcelFile< @"..\..\data\DataFile.xlsx">
```

This appears fine in the IDE (Code or VS) but when compiled gives this error: -

```
BatchImport.fsx(20,18): error FS3033: The type provider 'ExcelProvider.ExcelProvider+ExcelProvider' reported an error: Could not open file 'c:\Users\Isaac\Source\Repos\myProject\paket-files
\include-scripts\net452\..\..\data\DataFile.xlsx'. DirectoryNotFoundException - Could not find a part of the path 'c:\Users\Isaac\Source\Repos\myProject\paket-files\data\DataFile.xlsx'.
```

Note that the path it's using is relative to where the *paket script* was loaded, rather than where the script I'm working in was loaded. Is this: -

* A Paket issue?
* An ExcelProvider issue?
* Something more fundamental with how scripts are loaded within the context of F# and Type Providers?

**Comment by forki** [comment]
Looks like something is changing the internal current directory. /cc @smoothdeveloper

**Comment by matthid** [comment]
I think I saw this before. I think that happens as well without the load (ie using #r directly in the script). Can you verify? If yes it's a F#/Type provider problem...

**Comment by smoothdeveloper** [comment]
@isaacabraham I've used the FSharp.Data.SqlClient and few other type providers from such scripts, although I always __SOURCE_DIRECTORY__ as a reference, I think it would solve your problem:

```fsharp
type Component = ExcelFile< const(__SOURCE_DIRECTORY__ + @"/../../data/DataFile.xlsx") >
```

**Comment by smoothdeveloper** [comment]
Also can you check if this happens in ionide versus plain FSI or VS?

**Comment by matthid** [comment]
Oh I didn't think of '__SOURCE_DIRECTORY__'. Good idea, thanks @smoothdeveloper

**Comment by isaacabraham** [comment]
Yeah, `__SOURCE_DIRECTORY__` fixes the problem I think.
