### ISSUE TITLE
Paket treats 2017 .NET Core Webapp as .NET Framework project

### ISSUE THREAD

**Issue by jdpage** [fsprojects/Paket#2143]
### Description

The `paket install` and `paket update` commands are treating .NET Core Web projects à la Visual Studio 2017 as if it were a .NET Framework project when adding dependencies, resulting in build failure.

### Repro steps

(On Windows 10 Pro x64 v1607, long paths enabled, using Visual Studio 2017 RC build 26206, and Paket 4.0.0-beta011)

1. Create a new "ASP.NET Core Web Application (.NET Core)"
2. Select the "Web API" template (this gives us some dependencies and files to work with) and continue
3. Hit "File > Save All" to commit to disk
4. Add paket.bootstrapper.exe to a .paket folder in the root; run with "prerelease" argument.
5. Run `paket convert-from-nuget`
6. Run `paket update`

See [WebApplication1.zip](https://github.com/fsprojects/Paket/files/779040/WebApplication1.zip) for the results of the above (minus the packages folder; you will have to run `paket restore`).

### Expected behavior

Paket adds references to the web project in a way that causes them to resolve and build under Visual Studio / `dotnet`. 

### Actual behavior

Paket adds references the way it would to a .NET Framework project (see WebApplication1.csproj from [WebApplication1.zip](https://github.com/fsprojects/Paket/files/779040/WebApplication1.zip) and the Choose elements in it), resulting in a project which no longer builds.

### Known workarounds

~~No known workarounds.~~

Manually edit the CSPROJ file for the website after every run of `paket install` or `paket update`, and manually specify the framework in paket.dependencies to ensure that the appropriate packages are downloaded.

**Comment by jdpage** [comment]
Followup: This also occurs with ASP.NET Core sites targeting .NET Framework, which are similarly mis-detected. Since it uses the same project system as .NET Standard libraries in 2017, the CSPROJ files should probably be looking something like this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

... which works fine with "dotnet restore" and builds, but is overwritten with garbage as soon as `paket install` or `paket update` is run.

**Comment by forki** [comment]
are you using latest paket 4 beta?

**Comment by forki** [comment]
so this is "just" an issue with convert? 

/cc @theimowski

**Comment by jdpage** [comment]
Nope! As far as I can tell, convert, install, and update are all producing the wrong output for these projects.

For example, if I do the conversation manually, then run "update", it breaks the build.

**Comment by forki** [comment]
Also with latest paket beta? I fixed something. Maybe unrelated but please
give it a try.

Am 16.02.2017 22:46 schrieb "Jonathan David Page" <notifications@github.com

**Comment by gfritz** [comment]
On paket 5.84.0 the repro steps seem to NOT cause a problem in Visual Studio 2017 (15.2). Vote to close?

![image](https://user-images.githubusercontent.com/2267030/28834677-f35aad3a-76b0-11e7-9577-f8869907df4a.png)
