### ISSUE TITLE
Add support for Tizen TargetFrameworkMoniker

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#2144]
### Description

If NuGet/Home#4175 goes in, then we'll need to update our list to match.

**Comment by ghuntley** [comment]
`tizen30` was merged into NuGet v4.1 over at https://github.com/NuGet/NuGet.Client/pull/1083

**Comment by forki** [comment]
up-for-grabs

**Comment by fsoikin** [comment]
NuGet also has `netstandard1.7` listed (which is supported by `tizen4.0`, hence the question).
Should that be added to Paket as well, or was it intentionally left out?

**Comment by forki** [comment]
Please send a pull request. No intention AFAIK

**Comment by matthid** [comment]
It is nothing official. 1.7 will be 2.0 afaik. I don't think we should support it. Reason is compat changes in 2.0, so simply adding 1.7 will probably not do the correct thing. Maybe it could be implemented as an alias for 2.0? But I'd prefer to just skip it if possible...

**Comment by fsoikin** [comment]
@matthid do you mean to say that there will never be any actual packages for 1.7?

**Comment by forki** [comment]
What does inofficial mean when nuget supports it?

**Comment by matthid** [comment]
https://github.com/dotnet/standard/issues/160

**Comment by matthid** [comment]
> It's a temporary place holder until netstandard 2.0 is ready in the toolchain (specifically nuget)

**Comment by matthid** [comment]
I guess that means they use it internally for some technical reason?

**Comment by fsoikin** [comment]
I see. Would there be any real harm if Paket supported it?

The way I think about it, if there are no actual packages with that version, then it's a no-op, but if there are any packages, then the last of Paket support would mean that such packages will fail to install.
