### ISSUE TITLE
convert-from-nuget breaks the solution file

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#2161]
### Description

If there is a `.paket` folder in the solution file already, after executing `paket convert-from-nuget`, paket adds the `paket.dependencies` reference *outside* of the `.paket` solution folder "project" and the solution file gets broken.

### Repro steps

1. Create a new project/solution in Visual Studio or Rider
2. Add `.paket` solution folder
3. Add `.paket` folder to the repo, put the bootstrapper, run it to get `paket.exe`
4. Run `.paket\paket convert-from-nuget`

The solution file gets this:

```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = ".paket", ".paket", "{75DC0F05-EDD7-4CAD-B88E-9BA4DFCDDAE2}"
EndProject
		..\paket.dependencies = ..\paket.dependencies
```

### Expected

I expect to have these likes in the solution file:

```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = ".paket", ".paket", "{75DC0F05-EDD7-4CAD-B88E-9BA4DFCDDAE2}"
ProjectSection(SolutionItems) = preProject
    ..\paket.dependencies = ..\paket.dependencies
EndProjectSection
EndProject
```

Paket version 3.36.0

**Comment by forki** [comment]
Marking as up-for-grabs
