### ISSUE TITLE
[Minor] Paket Pack: confusing yellow diagnostic

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2164]
The full project source is here: https://github.com/0x53A/Expecto.Xunit

![image](https://cloud.githubusercontent.com/assets/4236651/23487652/bd636c12-fee7-11e6-99e4-415ac54dee05.png)

Why is there no text after ``:`` and why is it printed three times?

**Comment by smoothdeveloper** [comment]
@0x53A good point, could you try with verbose option?

**Comment by forki** [comment]
wtf!? expecto.xunit? please noooo.

**Comment by forki** [comment]
;-)

**Comment by forki** [comment]
This project doesn't build for me. So I can't call pack

![image](https://cloud.githubusercontent.com/assets/57396/23499753/afc2af5a-ff2d-11e6-8bed-6ab6c7bfd98b.png)

**Comment by 0x53A** [comment]
@smoothdeveloper with verbose:
![image](https://cloud.githubusercontent.com/assets/4236651/23505606/a9912992-ff44-11e6-8f6a-7abfe141d709.png)

@forki: This is not what you probably think, it is an adapter to run the great new expecto tests with the legacy xunit console runner :)

If you want to build it, I think you need to manually call paket restore from cmd. (``The namespace Xunit is not defined`` points to missing assemblies).
I used the paket VS extension to initialize the project, but that didn't seem to add the restore targets file, will take a look in the evening ...

**Comment by forki** [comment]
Can you please attach a zip with everything already built? Or mail me?

**Comment by 0x53A** [comment]
sure, here: 
[Expecto.XUnit.zip](https://github.com/fsprojects/Paket/files/813646/Expecto.XUnit.zip)

in the root call ``.paket\paket.exe pack output nugets minimum-from-lock-file --verbose``
