### ISSUE TITLE
Paket add writes invalid XML namespace into project file

### ISSUE THREAD

**Issue by eugene-g** [fsprojects/Paket#2168]
### Description

Paket 3.36.0 adds invalid namespace to project file element.

### Repro steps

1. netcoreapp or netstandard app in F#
2. Add some dependency, e.g. `paket add nuget Argu project MyProject`
3. Build project.

### Expected behavior

Build should run successfully. Choose tags in fsproj should not have xmlns attribute.

### Actual behavior

You get:
`error MSB4066: The attribute "xmlns" in element <Choose> is unrecognized.`

because Paket creates choose tags like this:
`<Choose xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

### Known workarounds

Remove xmlns attribute manually.

**Comment by forki** [comment]
yoe need to use Paket 4 beta for netcoreapp
