### ISSUE TITLE
Paket Bootstrapper stopped working today

### ISSUE THREAD

**Issue by mreishus** [fsprojects/Paket#2169]
### Description

Paket Bootstrapper stopped working today, I'm not sure if it's broken my a change in my company's network configuration or if something happened on github.

### Misc

I'm not sure if paket bootstrapper is provided by this project or not, I hope this is the right place to report.

### Repro steps

Please provide the steps required to reproduce the problem

1. Windows 7, powershell, run `.\.paket\paket.bootstrapper.exe`

### Expected behavior

It downloads the latest version.

### Actual behavior

There's some sort of error in however it tries to determine the latest version.
```
λ .\.paket\paket.bootstrapper.exe
No version specified. Downloading latest stable.
Starting download from https://github.com/fsprojects/Paket/releases/download/CTYPE html>
<html lang=/paket.exe
The remote server returned an error: (404) Not Found. (Github)
```

### Known workarounds

If I manually provide the version number it works.
```
λ .\.paket\paket.bootstrapper.exe 3.36.0
Version 3.36.0 requested.
Starting download from https://github.com/fsprojects/Paket/releases/download/3.36.0/paket.exe
Done.
```

**Comment by forki** [comment]
I think we did not change anything

Am 02.03.2017 4:09 nachm. schrieb "mreishus" <notifications@github.com>:

**Comment by OlegZee** [comment]
The same here (was running on Travis-ci for years)
![image-paketfails](https://cloud.githubusercontent.com/assets/513301/23515191/026dcfa0-ff9c-11e6-8c40-67db7a19ef67.jpg)

**Comment by cloudRoutine** [comment]
the problem doesn't seem to be universal 

![](http://i.imgur.com/TUWcTkH.png)

**Comment by madhon** [comment]
So far ive found that updating the bootstrapper exe to one from the 3.36.0 tag has fixed the problem

**Comment by Stift** [comment]
An older version of the bootstrapper didn't look on the subsequent pages of the release page, and didn't find the current stable. Updating is the only counter-measure.

**Comment by Stift** [comment]
One counter-measure would be, that maybe @forki pushes a stable from time to time. Then the stable would show up here (https://github.com/fsprojects/Paket/releases).

**Comment by forki** [comment]
I actually do that.

Am 03.03.2017 12:18 schrieb "Christian Fiebrig" <notifications@github.com>:

**Comment by forki** [comment]
let me release one.

**Comment by forki** [comment]
done

**Comment by mreishus** [comment]
My old version of the bootstrapper now works without specifying a version.   I'll be sure to update.  Thanks!
