### ISSUE TITLE
CLI "Paket outdated --ignore-constraint" is going wild

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2170]
### Description

The behavior of `paket outdated --ignore-constraints` is realllyyyyy weird (see repro step)

### Repro steps

1. Create a solution with a Console Application in C# **in Full .Net Framework 4.6.2**
2. run a `paket init`
3. Add "Newtonsoft.Json" in version 8.0.3 : `paket add nuget Newtonsoft.Json --version 8.0.3 -i` (and say YES)
4. if needed, save, run `paket install`, etc ... the goal is to be sure that you have some

**paket.dependencies** will probably look like :
```
source https://api.nuget.org/v3/index.json

nuget Newtonsoft.Json 8.0.3
```

**paket.lock** will probably look like :
```
NUGET
  remote: https://api.nuget.org/v3/index.json
    Newtonsoft.Json (8.0.3)
```

**NOW**
`paket outdated` will output :
```
λ paket outdated
Paket version 3.36.0
Resolving packages for group Main:
 - Newtonsoft.Json is pinned to 8.0.3
No outdated packages found. 
1 second - ready.
```
No worry about "no outdated" because it's pinned

Here is the WTF :
`paket outdated --ignore-constraints` (remember we're in Full framework) output :
```
λ paket outdated --ignore-constraints
Paket version 3.36.0
Resolving packages for group Main:
 - Newtonsoft.Json 9.0.1
 - System.Runtime.Serialization.Primitives 4.3.0
 - System.IO 4.3.0
 - System.Linq 4.3.0
 - System.Linq.Expressions 4.3.0
 - System.Reflection 4.3.0
 - System.Runtime 4.3.0
 - System.Runtime.Extensions 4.3.0
 - System.Text.RegularExpressions 4.3.0
 - System.ObjectModel 4.3.0
 - System.Collections 4.3.0
 - System.Diagnostics.Debug 4.3.0
 - System.Dynamic.Runtime 4.3.0
 - System.Globalization 4.3.0
 - System.Text.Encoding 4.3.0
 - System.Text.Encoding.Extensions 4.3.0
 - System.Threading 4.3.0
 - System.Threading.Tasks 4.3.0
 - System.Xml.ReaderWriter 4.3.0
 - System.Xml.XDocument 4.3.0
 - Microsoft.CSharp 4.3.0
 - System.Reflection.Extensions 4.3.0
 - System.Resources.ResourceManager 4.3.0
 - System.Reflection.Primitives 4.3.0
 - System.Reflection.TypeExtensions 4.3.0
 - System.Runtime.InteropServices 4.3.0
 - System.Reflection.Emit 4.3.0
 - System.Reflection.Emit.ILGeneration 4.3.0
 - System.IO.FileSystem 4.3.0
 - System.IO.FileSystem.Primitives 4.3.0
 - System.Threading.Tasks.Extensions 4.3.0
 - System.Diagnostics.Tools 4.3.0
 - System.Reflection.Emit.Lightweight 4.3.0
 - Microsoft.NETCore.Platforms 1.1.0
 - Microsoft.NETCore.Targets 1.1.0
 - System.Runtime.Handles 4.3.0
Outdated packages found:
  Group: Main
    * Newtonsoft.Json 8.0.3 -> 9.0.1
28 seconds - ready.
```

**Microsoft.NETCore.Platforms and Microsoft.NETCore.Targets** <== WUT ?
```
λ paket why nuget Microsoft.NETCore.Platforms
Paket version 3.36.0
NuGet Microsoft.NETCore.Platforms was not found in paket.lock
0 seconds - ready.
``` 
``` 
λ paket why nuget Microsoft.NETCore.Targets
Paket version 3.36.0
NuGet Microsoft.NETCore.Targets was not found in paket.lock
0 seconds - ready.
``` 

**And here is the really crazy stuff :**

`System.Linq` is actually a nuget (https://www.nuget.org/packages/System.Linq/)
```
λ paket why nuget System.Linq
Paket version 3.36.0
NuGet System.Linq was not found in paket.lock
0 seconds - ready.
```
And the behavior of `outdated` and `why` are not really working well together

### Expected behavior

* Should only output that `* Newtonsoft.Json 8.0.3 -> 9.0.1`
* Should use every "nuget" that is listed in `paket.lock` 
* Should not scan each csproj et mix package & GAC assembly 
* Should not list any stuff about ".NetCore"

### Actual behavior

List GAC reference as if it was Nuget ?
List assembly that really seems releated to ".Net Core" <== wtf is going on here ?

### Known workarounds

Nop, you just loose time on huge project **27 sec lost on a single nuget reference here**

**Comment by cloudRoutine** [comment]
the problem is you're not actually in the full framework because you haven't specified that (also you forgot to add the package to the actual project) 

if you had added a framework restriction to your paket dependencies it would have worked like you expected
```
source https://www.nuget.org/api/v2
nuget Newtonsoft.Json 8.0.3 framework: net46
```

```
λ» paket outdated --ignore-constraints
Paket version 4.0.7
Resolving packages for group Main:
 - Newtonsoft.Json 10.0.1
Outdated packages found:
  Group: Main
    * Newtonsoft.Json 8.0.3 -> 10.0.1
2 seconds - ready.
```

**Comment by tebeco** [comment]
Thx @cloudRoutine, I'll check that
But it does not explain why it does not behave the same with or without constraint especially if you tell me that fixing the framework while ignoring contraints actually check framework

**Comment by cloudRoutine** [comment]
iirc ignore constraints is only for the version numbers

**Comment by tebeco** [comment]
@cloudRoutine 

Framework were already pinned in fact, here is my paket.dependencies :

```
framework: net462
source https://api.nuget.org/v3/index.json

nuget FSharp.Core
nuget Newtonsoft.Json
nuget Paket.Core

group Test
	source https://api.nuget.org/v3/index.json

	nuget NUnit
	nuget NUnit3TestAdapter version_in_path: true
	nuget NFluent
	nuget NSubstitute

group OutdatedOnPurpose
	source https://api.nuget.org/v3/index.json
	
	nuget System.Reactive.Interfaces 3.0.0
```

**Comment by cloudRoutine** [comment]
what do you think is going wrong with this? i ran outdated `--ignore-constraints` on it and it behaved as expected

are you expecting the one framework restriction you used to apply to the whole file? each group needs its own framework restriction

```
framework: net462
source https://api.nuget.org/v3/index.json

nuget FSharp.Core
nuget Newtonsoft.Json
nuget Paket.Core

group Test
	source https://api.nuget.org/v3/index.json
    framework: net462
    
	nuget NUnit
	nuget NUnit3TestAdapter version_in_path: true
	nuget NFluent
	nuget NSubstitute

group OutdatedOnPurpose
	source https://api.nuget.org/v3/index.json
	framework: net462

	nuget System.Reactive.Interfaces 3.0.0
```

**Comment by tebeco** [comment]
@cloudRoutine i completly forgot that ... thx
