### ISSUE TITLE
Question : Paket Dependencies file, network share files as source

### ISSUE THREAD

**Issue by neildanson** [fsprojects/Paket#2175]
### Description

nuget, http, github are supported as sources for paket. Would it be feasible or desirable to support something like file shares for same purpose?

### Repro steps
eg
nuget NUnit ~> 2.6.3
nuget FAKE ~> 3.4
nuget DotNetZip >= 1.9
nuget SourceLink.Fake
gist Thorium/1972349 timestamp.fs
fileshare //networkshare/my_companies_dlls/my_companies_dll1.dll
fileshare //networkshare/my_companies_dlls/my_companies_dll2.dll

### Expected behavior

I'd expect dlls to be copied to local folder and referenced locally. 
If the files have not updated then I'd expect them not to be re-copied locally. 

### Actual behavior

Nothing - this is a question :)

### Known workarounds

Build internal Nuget packages. In our case the build is managed by another team, who simply emit their output to a share.

**Comment by forki** [comment]
Local sources are already supported. Please see https://fsprojects.github.io/Paket/nuget-dependencies.html#Path-sources
