### ISSUE TITLE
Creation unnecessary folders after 'paket install' command.

### ISSUE THREAD

**Issue by rdcm** [fsprojects/Paket#2176]
### Description

I install in my solution with WebApi project paket, also in solution exist folder 'Content' with subfolders: 'css', 'font', 'js'. For app used packages: bootstrap, jQuery, knockoutjs. This three packages installed in solution before paket, content from packages store in listed folders.

### Repro steps

Invoke from solution level '.paket/paket.exe install' for install new package.

### Expected behavior

I do not expect the appearance something in git diff after 'paket install', besides new section in .csproj with needed package. 

### Actual behavior

In solution appear new solution level folders 'fonts', 'Scripts' with packages content.
The same way, in 'Content' folder appear content from bootstrap package, but this already exist in Content/css.

### Known workarounds

Paket 3.36.1
VisualStudio 2015,
bootstrap 3.3.7,
 jQuery 3.1.1, 
knockoutjs 3.4.1

**Comment by forki** [comment]
There are "content: none" options. Please see https://fsprojects.github.io/Paket/dependencies-file.html#No-content-option
