### ISSUE TITLE
WHY has empty dependency chain

### ISSUE THREAD

**Issue by fbehrens** [fsprojects/Paket#2187]
I was just wondering where comes the `./packages/Octokit` from when I `paket restore` on Ionide master 
https://raw.githubusercontent.com/ionide/ionide-vscode-fsharp/d1955448984da813927e93379afa435d72023620/paket.dependencies

But `paket why` does tell me it's a transitive dependency, 
but the dependecy chain seems empty.

```
on master [d195544]

> mono .paket/paket.exe why nuget Octokit                                                                                                                                       Paket version 3.37.0
NuGet Octokit is a transitive dependency.
It's a part of following dependency chains:

0 seconds - ready.

> mono .paket/paket.exe why nuget Octokit                                                                                                                                       master [d195544]
Paket version 4.0.1
NuGet Octokit is a transitive dependency.
It's a part of following dependency chains:

0 seconds - ready.
```

**Comment by inosik** [comment]
In that case, Octokit is a dependency of [Octokit.fsx][octokit.fsx]. `paket why` doesn't take GitHub dependencies into account.

  [octokit.fsx]: https://github.com/ionide/ionide-vscode-fsharp/blob/d1955448984da813927e93379afa435d72023620/paket.dependencies#L14

**Comment by forki** [comment]
Yep that's correct and a bit tricky to resolve here.
