### ISSUE TITLE
Pack doesn't work for <Project Sdk="Microsoft.NET.Sdk">

### ISSUE THREAD

**Issue by SavaNDragos** [fsprojects/Paket#2193]
Hi guys,

I tried to run a paket pack and discovered that it is failling. Initially the error was:

> PS ..> .\.paket\paket.exe pack  output .\Output\ buildconfig Release
> Paket version 4.0.7
> Paket failed with:
>         Unable to find Release output path node in file D:\1238\PaketRepro\Source\App\ClassLibrary1\ClassLibrary1.csproj for any known platforms

So I added in that csproj:

```
  <PropertyGroup >  
     <OutputPath>bin\$(Configuration)\$(TargetFramework)</OutputPath>
   </PropertyGroup>
```

And I encountered a new error:

> Paket failed with:
>         Incomplete mandatory metadata in template file

This is due to information like Version and Authors not being available to paket (I am not sure where this information is taken from by paket, if it was AssemblyInfo then this would explain it quite easy because the info was moved to csproj).

**Comment by cjbhaines** [comment]
@forki any ideas on this one?

**Comment by forki** [comment]
I guess new fsproj needs to run though dotnet pack

**Comment by cjbhaines** [comment]
@SavaNDragos have you tried calling dotnet pack instead? The paket templates should still be used even though it was requested through the dotnet cli.

**Comment by enricosada** [comment]
Closing, fixed
