### ISSUE TITLE
Can packet.dependencies specify source for individual packages?

### ISSUE THREAD

**Issue by bigbearzhu** [fsprojects/Paket#2195]
We found if we have forked a public nuget package from github and add a private feed source for getting the forked versions, paket very often goes to nuget.org to search for the package update and gives unlisted result for the forked version and eventually gives up updating the package. Is there any way to specify a source for individual package?

**Comment by forki** [comment]
Yes:

Source mylocalSource

NuGet X

Source nuget.org

NuGet A
NuGet B



Am 23.03.2017 07:04 schrieb "Jun Zhu" <notifications@github.com>:

**Comment by enricosada** [comment]
Closing, question was answered by previous comment
