### ISSUE TITLE
unable to parse C:\ ..... Could not find ... suspect project dependecy not handled correctly

### ISSUE THREAD

**Issue by MaLioNet** [fsprojects/Paket#2204]
When running paket for the first time at the solution level with the following command lines

.paket\paket.exe convert-from-nuget --force
.paket\paket.exe install

 I get the following errors ... (both the same error output)

Unable to parse C:\dev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Base\RR.Framework.Base.csproj:
      Could not find a part of the path 'C:\dev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Base\RR.Framework.Base.csproj'.
Broken project dependency: 'C:\dev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Server.Web\RR.Framework.Server.Web.csproj' -> 'C:\d
ev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Base\RR.Framework.Base.csproj'
Unable to parse C:\dev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Server.Base\RR.Framework.Server.Base.csproj:
      Could not find a part of the path 'C:\dev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Server.Base\RR.Framework.Server.Base.c
sproj'.
Broken project dependency: 'C:\dev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Server.Web\RR.Framework.Server.Web.csproj' -> 'C:\d
ev\RR.Framework\RR.Framework.Server.Console\RR.Framework.Server.Base\RR.Framework.Server.Base.csproj'
1 minute, 57 seconds - ready.

**Comment by forki** [comment]
Do you have a repro case for me?

Could you run same command with -v to show the stacktrace?

Am 27.03.2017 20:39 schrieb "MaLioNet" <notifications@github.com>:

**Comment by MaLioNet** [comment]
[file.txt](https://github.com/fsprojects/Paket/files/874790/file.txt)

Please see attached. I cannot post the source (although it is pretty much an empty project) due to company policy.

I can send to you personally if you send me a mail direct to malionet@gmail.com with contact details. If you provide a skype I can spend some time assisting if required.

**Comment by MaLioNet** [comment]
thanks for the assistance, the problem was that the project structure was poky ... paket was reporting the issue correctly
