### ISSUE TITLE
Paket install -f does not reinstall anything 

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2205]
### Description

`paket install -f` seems to only force "Download"
just like `paket restore -f`
It does not reinstall anything

### Repro steps

Create a project with a "paket.dependencies" and paket.lock"
here I reference `Paket.Core` <== no constrain (take the lastest)
Wait for an update so that `paket.lock` point to an obsolete version of `Paket.Core`
==> just fake it editing `paket.lock`

then force an install to FORCE the installation, it should give you latest bits right ?

Remember `paket.dependencies` was never changed
```
x>paket install -f
Paket version 4.0.10
Skipping resolver for group Main since it is already up-to-date
x\paket.lock is already up-to-date <======== THIS
Downloading FSharp.Core 4.1.0.2
Downloading Paket.Core 3.37 <======== THIS
```

see `Skipping resolver for group Main since it is already up-to-date` and `Downloading Paket.Core 3.37` 

```
x>rm paket.lock
x>paket install
Paket version 4.0.10
Resolving packages for group Main:
 - FSharp.Core 4.1.0.2
 - Newtonsoft.Json 10.0.1
 - Paket.Core 4.0.10 <======== THIS
```

and now we see ` - Paket.Core 4.0.10` was resolved

### Expected behavior

`paket install -f` should have forced the installation and resolved a newer version
there's a command for that name

### Actual behavior

It behave like `paket restore -f`
It does not "Install" anything ...

### Known workarounds

Delete `paket.lock` and run a simple `paket install`

**Comment by forki** [comment]
Can you please upload a zip with the project? Out of sync check says it's
OK so maybe out of sync check has a bug here

Am 28.03.2017 14:30 schrieb "TeBeCo" <notifications@github.com>:

**Comment by forki** [comment]
But maybe not. Install -f is different to update. Maybe you just want to
use "paket update".

Am 28.03.2017 14:34 schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

**Comment by tebeco** [comment]
so ...
if me paket.dependencies is :

```
framework: net462
source https://api.nuget.org/v3/index.json

nuget FSharp.Core
```

and I DO NOT edit it

but you push a new version of "Paket.Core", i have to explicitly says "update" ?

I mean there's a command for that ... `paket restore -f` that would read the lock

what is the meaning of `-f` for `install` then ?

**Comment by forki** [comment]
Yes you want to use update.
Install will try to be as conservative as possible and only try to "fix"
inconsistencies between deps and lock file (e.g. if you added a package).
Update on the other hand will update as much as possible. Both strategies
are valuable and the distinction of these two commands is very important
for many paket users.
I think if you think of update as that what you wanted to do with "install
-f" then everything is fine.

(the -f parameter is only used to skip various caches but does not change
the idea of the command itself)

Does that make sense?

Am 28.03.2017 14:38 schrieb "TeBeCo" <notifications@github.com>:

**Comment by tebeco** [comment]
Sounds like the naming of -f is a bit tricky but i understand now

Am i the only one looking for explicit graph showing worflow of each use case :
paket install
paket install -f
paket update 
paket update -f <== if exist
paket add
paket update

I means they all play together with csproj/lock/referencies/dependencies
etc ...
This might be lots better that online docs on command them self


Also is there "Acceptance Test" with scenario like "it should ... when dependency version change..."
Like BDD, describing how it behave when new version rollout, or releasing constrains, or pinning one
etc ...

**Comment by tebeco** [comment]
(not sure if bug still active of fixed, can't tell as i did not used `paket` for a long time now)
