### ISSUE TITLE
[netcore support] `paket restore` / `paket restore --project` don't create manifest resources for msbuild

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#2208]
Ideally paket would be able to work with netcore projects in conjuction with msbuild without any dependence on the dotnet cli and nuget

`paket restore` doesn't check to see in projects in the repo are netcore projects and if they need to be restored

`paket restore --project pakkit.fsproj` will do part of the restore and will create

![](http://i.imgur.com/ATWJUj0.png)

in the `obj` dir, but it will not do the essential step of 

```
  Generating MSBuild file C:\Users\jared\Downloads\pakkit (1)\pakkit\obj\pakkit.fsproj.nuget.g.props.
  Generating MSBuild file C:\Users\jared\Downloads\pakkit (1)\pakkit\obj\pakkit.fsproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\jared\Downloads\pakkit (1)\pakkit\obj\project.assets.json 
```

which create the manifest resources that `msbuild` needs in order to build the project.

enabling this functionality will be step 1 of freeing us from the shackles of nuget

**Comment by enricosada** [comment]
Closing. `dotnet restore` works, that's to be used after `paket restore` (as a note `paket restore` is automatically called on `dotnet restore`).
