### ISSUE TITLE
Paket fails with asp.net core project on net462 

### ISSUE THREAD

**Issue by llehn** [fsprojects/Paket#2212]
1. Create a simple asp.net core project. 
2. Change target to net462
   -> restore and build works

3. Convert to paket, either with convert-from-nuget or manuall
4. restore fails.

Repro:
https://github.com/llehn/paketRestoreBug

1st commit: no paket
2nd commit: same with paket.

The error during restore is:
````
  Restore completed in 1,15 sec for C:\dev\projects\paketrepro\Web\Web.csproj.
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Package System.Security.Cryptography.OpenSsl 4.3.0 is not compatible with net462 (.NETFramework,Version=v4.6.2). Package System.Security.Cryptography.OpenSsl 4.3.0 supports: netstandard1.6 (.NETStandard,Version=v1.6) [C:\dev\projects\paketrepro\LOLZ.sln]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : One or more packages are incompatible with .NETFramework,Version=v4.6.2. [C:\dev\projects\paketrepro\LOLZ.sln]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Package System.Security.Cryptography.OpenSsl 4.3.0 is not compatible with net462 (.NETFramework,Version=v4.6.2) / win7-x86. Package System.Security.Cryptography.OpenSsl 4.3.0 supports: netstandard1.6 (.NETStandard,Version=v1.6) [C:\dev\projects\paketrepro\LOLZ.sln]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : One or more packages are incompatible with .NETFramework,Version=v4.6.2 (win7-x86). [C:\dev\projects\paketrepro\LOLZ.sln]
  Generating MSBuild file C:\dev\projects\paketrepro\Web\obj\Web.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\dev\projects\paketrepro\Web\obj\project.assets.json
  Restore failed in 1,46 sec for C:\dev\projects\paketrepro\Web\Web.csproj.
````

This currently prevents me from using paket and I have to experience the utter hell of pure nuget, which on the 1st try fucks things up with 2 versions of same package...

**Comment by cjbhaines** [comment]
We are also blocked on moving to VS2017 by this one :(

**Comment by forki** [comment]
I can't repro with dotnet version 2.0.0-preview1-005683

but I see something very starnge (cc @davkean @enricosada)

* clone project
* run `.paket/paket.bootstrapper.exe`  (@llehn for paket 4 we reccomend to go [magic mode](https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode))
* run `dotnet restore`
* run `dotnet build` --> crash/MSBuild error
* rerun `dotnet build` -> success

**Comment by llehn** [comment]
I tried this again with my whole solution, not the repro, and it does work, however, there's another rather major issue, https://github.com/fsprojects/Paket/issues/2340.
Closing
