### ISSUE TITLE
Dependency resolution does not work for on-premise TFS private feed

### ISSUE THREAD

**Issue by drwatson1** [fsprojects/Paket#2213]
I encountered with the same issue as described in #1798 but for TFS. TFS has the same bug with package dependencies as VSTS (I create issue for this [here](https://developercommunity.visualstudio.com/content/problem/38370/package-management-server-does-not-return-package.html)).

I found this code to workaround for VSTS:

https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NuGetV2.fs#L682

and this:

https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NuGetV2.fs#L296

There are IF conditions for visualstudio.com.

But I have URLs something like this:

"http://vc-tfs-server:8080/tfs/DefaultCollection/_packaging/default/nuget/v3/index.json" - in first case (L682) and:

"http://vc-tfs-server:8080/tfs/DefaultCollection/_packaging/default/nuget/v2" - in second case (L296)

Can you fix it for me? Or I can fix this for both cases and send you pull request. What do you think about it?

**Comment by forki** [comment]
I'd prefer a pr

Am 31.03.2017 2:53 nachm. schrieb "drwatson1" <notifications@github.com>:
