### ISSUE TITLE
paket auto-restore on should not download bootstrapper in magic mode

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#2217]
### Description

I'm running paket in magic mode. `paket auto-restore on` downloads `paket.bootstrapper.exe`, although it's not required.

### Repro steps

1. Download `paket.bootstrapper.exe` and rename it to `paket.exe`

2. Run `paket.exe auto-restore on`

### Expected behavior

`paket.bootstrapper.exe` is not downloaded.

### Actual behavior

`paket.bootstrapper.exe` is downloaded.

```sh
$ paket auto-restore on
Paket version 4.1.3
Removing file project\.paket\paket.targets
project\.paket\paket.targets
Downloading file from https://github.com/fsprojects/Paket/releases/download/4.1.3/paket.targets to project\.paket\paket.targets
project\.paket\paket.bootstrapper.exe
Downloading file from https://github.com/fsprojects/Paket/releases/download/4.1.3/paket.bootstrapper.exe to project\.paket\paket.bootstrapper.exe
6 seconds - ready.
```

**Comment by forki** [comment]
@vbfox are you up for this? I think our internal tools should always try to setup magic mode

**Comment by vbfox** [comment]
Yes you can asign it to me :)
