### ISSUE TITLE
When using Paket, VS2017 becomes unresponsive

### ISSUE THREAD

**Issue by fourpastmidnight** [fsprojects/Paket#2218]
### Description

On more than one occasion, using the `Install` option in Visual Studio 2017 causes Visual Studio to become completely unresponsive, with the only alternative being left to force kill the VS process.

### Repro steps

1. Open a solution which contains Paket references
2. Open one or more code files from a project containing a `paket.references` file.
3. Right click the `paket.dependencies` file and choose `Install`.

VS 2017 hangs. For example, see the `git-tfs` project here on GitHub.

### Expected behavior

Visual Studio 2017 doesn't hang.

### Actual behavior

Visual Studio 2017 hangs

### Known workarounds

Don't open any project code files for projects containing a `paket.references` file when you need to perform any Paket operations on the solution.

**Comment by forki** [comment]
Is  this with the paket visual studio addin? if so then please reopen at https://github.com/fsprojects/Paket.VisualStudio

**Comment by fourpastmidnight** [comment]
@forki: yes, the VS extension/addin. Thanks for the redirect, will do!
