### ISSUE TITLE
Visual Studio 2017 new csproj and Paket.Restore.targets import

### ISSUE THREAD

**Issue by bchavez** [fsprojects/Paket#2220]
Hello. I'm trying to migrate [`Bogus`](https://www.nuget.org/packages/Bogus/) to VS 2017's new `.csproj` format. I'm using **paket** to manage the `Newtonsoft.Json` dependency and I've been fighting **paket** for a few days now. Specifically, `Paket.Restore.targets` injected import into `.csproj`.

I have a VS 2017 branch of my current progress here:
https://github.com/bchavez/Bogus/tree/vs2017 

There are a lot of errors so I'll try to walk though how I'm fighting **paket** to get it to work:

### The Paket Fight

* `git clone --branch vs2017 -v "https://github.com/bchavez/Bogus" .\Bogus`
* `cd Bogus\Source`

```
.\.paket\paket.bootstrapper.exe
.\.paket\paket.exe install
```

* `cd Bogus`
* `dotnet build`
:x: ***failure***

```
Database.cs(5,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
....
```

Build fails, okay, try `dotnet restore`...

* `dotnet restore`
:x: ***semi-failure***

```
C:\temp\Bogus\Source\Bogus>dotnet restore
  Paket version 4.1.6
   - C:\temp\Bogus\Source\Bogus\obj\Bogus.csproj.references created
  Generating load scripts for framework net46 in group build
  3 seconds - ready.
  Paket version 4.1.6
   - C:\temp\Bogus\Source\Bogus\obj\Bogus.csproj.references already up-to-date
  Generating load scripts for framework net46 in group build
  3 seconds - ready.
  Restoring packages for C:\temp\Bogus\Source\Bogus\Bogus.csproj...
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Package Microsoft.CSharp 4.3.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package Microsoft.CSharp 4.3.0 supports:\r [C:\temp\Bogus\Source\Bogus\Bogus.csproj]
... errors. red red red
```
Build again?

* `dotnet build`
:white_check_mark: ***success***

Cool, can we pack?

* `dotnet pack`
:white_check_mark: ***success***

```
C:\temp\Bogus\Source\Bogus>dotnet pack
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Bogus -> C:\temp\Bogus\Source\Bogus\bin\Debug\net40\Bogus.dll
  Bogus -> C:\temp\Bogus\Source\Bogus\bin\Debug\netstandard1.3\Bogus.dll
  Paket version 4.1.6
  0 seconds - ready.
  Successfully created package 'C:\temp\Bogus\Source\Bogus\bin\Debug\Bogus.0.0.0-localbuild.nupkg'.
```

Cool, can we create symbols?
* `dotnet pack --include-symbols --include-source`
:x: ***failure***

```
C:\temp\Bogus\Source\Bogus>dotnet pack --include-symbols --include-source
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Bogus -> C:\temp\Bogus\Source\Bogus\bin\Debug\net40\Bogus.dll
  Bogus -> C:\temp\Bogus\Source\Bogus\bin\Debug\netstandard1.3\Bogus.dll
  Paket version 4.1.6
  Paket failed with:
        Specified file 'obj\Bogus.0.0.0-localbuild.nuspec;obj\Bogus.0.0.0-localbuild.symbols.nuspec' does not exist.
C:\temp\Bogus\Source\.paket\Paket.Restore.targets(59,5): error MSB3073: The command ""C:\temp\Bogus\Source\.paket\paket.exe" fix-nuspec file "obj\Bogus.0.0.0-localbuild.nuspec;obj\Bogus.0.0.0-localbuild.symbols.nuspec" references-file "C:\temp\Bogus\Source\Bogus/obj/Bogus.csproj.references" " exited with code 1. [C:\temp\Bogus\Source\Bogus\Bogus.csproj]
```

* Next, open `Bogus.sln` in **Visual Studio 2017**. And we get some crazy error messages:

![wermgr_103](https://cloud.githubusercontent.com/assets/478118/24721107/17c61ce6-19f4-11e7-9941-1a4272cef9fe.png)
![devenv_104](https://cloud.githubusercontent.com/assets/478118/24721110/1a29f57a-19f4-11e7-888a-cc0fe8aa8387.png)

[VsProjectFault_333d4379-80d3-435f-a408-eb59c0d0a10e.failure.txt](https://github.com/fsprojects/Paket/files/900441/VsProjectFault_333d4379-80d3-435f-a408-eb59c0d0a10e.failure.txt)

---

All these problems go away by removing this one simple line [`Source\Bogus\Bogus.csproj` here](https://github.com/bchavez/Bogus/blob/vs2017/Source/Bogus/Bogus.csproj#L47):
```
<Import Project="..\.paket\Paket.Restore.targets" />
```
Remove this line and ***all*** the problems go away.

If **paket** isn't ready for VS 2017 prime-time; sorry for the noise, feel free to close the issue.

The `master` branch of [`Bogus`](https://github.com/bchavez/Bogus) *successfully* uses **paket** with `project.json` and **VS 2015** if that's any help.

Thanks,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

## Other Info

```
C:\temp\Bogus>dotnet
Microsoft .NET Core Shared Framework Host
  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

C:\temp\Bogus>dotnet --version
1.0.0
```
* Operating system
     **Windows 7 64-bit**

* .NET Runtime, CoreCLR or Mono Version
     **Visual Studio 2017**
![vs_installershell_93](https://cloud.githubusercontent.com/assets/478118/24672834/0460e484-192b-11e7-86a3-15fb78a8f227.png)

* Editing Tools (e.g. Visual Studio Version)
(snipped for brevity)
```
Microsoft Visual Studio Community 2017
Version 15.0.26228.12 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01590

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA337
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA337
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA337
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA337
Microsoft Visual F# 4.1

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

JetBrains ReSharper Ultimate 2017.1    Build 108.0.20170402.75312
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.13-alpha (2f64b6d)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
```

**Comment by forki** [comment]
I'll try to take a look tomorrow. 

I assume it's incompatibility with the installed dotnet cli version. 

Btw: AFAIK dotnet always wants you to run restore before build. So that very first part is expected.

**Comment by bchavez** [comment]
Hi. Thank you for the reply. What `dotnet` CLI should I be running? Presumably, I thought I was using the `dotnet` CLI that came with the default VS 2017 install. :disappointed:
