### ISSUE TITLE
Redirects/References Move Too Frequently

### ISSUE THREAD

**Issue by BlythMeister** [fsprojects/Paket#2228]
It seems that the ordering of redirects and references changes very frequently.

Just recently with the release of 4.1.0 the binding redirect order changed.
every time this happens and we update paket, we get hundreds of file changes which make merges harder and merge conflicts higher.

An example of this move is:
![image](https://cloud.githubusercontent.com/assets/1046836/24907447/34918274-1eb4-11e7-9029-20abdaf42581.png)

**Comment by forki** [comment]
yes I wondered too. I thought we order alphabetical. but something is fucky /cc @isaacabraham 
I'm definetly interested in a fix that settles this

**Comment by RustyF** [comment]
(newbie alert).  I'm trying to find something to fix but it looks like commit https://github.com/fsprojects/Paket/commit/3d0d8c560d5f36fef0a634c519b2da9d582a6adb fixes it?  If so, what's the strategy for finding stuff actually not fixed (but not closed)?

**Comment by forki** [comment]
I think we're missing a repro here. I don't know if it's fixed.

**Comment by BlythMeister** [comment]
Unfortunately it's on a private repo, I guess create a project with the references on the before and after versions?

**Comment by RustyF** [comment]
I can reproduce it with a simple project.  I will retrospectively add a test to thus cover https://github.com/fsprojects/Paket/pull/2230

**Comment by fsoikin** [comment]
So this issue should be closed now, right?

**Comment by BlythMeister** [comment]
Yeah, the original issue is resolved now.

**Comment by forki** [comment]
Thanks everyone
