### ISSUE TITLE
paket isnt aware of current target framework

### ISSUE THREAD

**Issue by enricosada** [fsprojects/Paket#2233]
### Description

Affect new sdk (the .net core sdk)

Paket doesnt seems to be aware of current target framework when restoring deps.

### Repro steps

Create a .csproj who target `net45` but does reference `System.Collections.Specialized` just for `netstandard1.3`, like

1. Create myapp.csproj

    ```xml
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>net45</TargetFramework>
      </PropertyGroup>
       <Import Project="..\.paket\Paket.Restore.targets" /> 
    </Project>
    ```

5. paket.dependencies 

    ```
    source https://nuget.org/api/v2
    
    nuget System.Collections.Specialized  framework: netstandard13
    ```
6. paket references

    ```
    System.Collections.Specialized framework: netstandard13
    ```

7. `dotnet restore`

### Expected behavior

Restore succeed, and `System.Collections.Specialized` is not a dependency

### Actual behavior

Restore fails because `System.Collections.Specialized` doesnt support `net45`

### Known workarounds

None.

### Notes 

As a note the following works.

```xml
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
      <PackageReference Include="System.Collections.Specialized" Version="4.0.1" />
    </ItemGroup>
```

Minimizing the repro, i think is because `paket.exe" restore --project "myapp.csproj"` doesnt pass the `$(TargetFramework)` and the generated `obj\myapp.csproj.references` contains all the netstandard1.3 packages.

I think the paket target file should pass a `--framework net45` argument invoking `paket`, so the generated `obj\myapp.csproj.references` contains only dependencies for that target framework.

Atm the target file cannot filter packages (adding the `Condition="'$(TargetFramework)' == 'netstandard1.3'"` because the information is missing, and ihmo is better done paket side)

As additional note, doing a crossgen (multiple target frameworks) currently invoke paket three times, so with the proposed change should work, because each time paket will generate correct package list and that will be included for that framework build.

ref https://github.com/elastic/elasticsearch-net/pull/2711

**Comment by forki** [comment]
I think I'd need help here

**Comment by enricosada** [comment]
@forki i think the current integration is ok.

just `paket restore --project` must expect also a target framework argument (`--framework`?), and filter packages before writing the list in the `obj\myapp.csproj.references` csv file. 
At maybe we need to add the same conditionals, in the target file, after reading the file and creating the PackageReference items (i'll check if that is needed asap)

Is also possibile to generate a file for each target framework (like `obj\myapp.csproj.net45.references`) but that require paket to read the proj file to known target frameworks, so is a bit annoying, so 👎 ihmo.
Also atm paket will be called multiple times when multiple target framework (`<TargetFrameworks>net45;netcoreapp1.0</TargetFrameworks>`), so is not needed.

**Comment by matthid** [comment]
> Is also possibile to generate a file for each target framework (like obj\myapp.csproj.net45.references) but that require paket to read the proj file to known target frameworks, so is a bit annoying, so 👎 ihmo.

Could we generate all? At least that would fit better into pakets philosophy (IMHO)

**Comment by forki** [comment]
fixed with paket 5 beta 1
