### ISSUE TITLE
Extended magic mode.

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#2242]
Here is an idea:
Small paket.exe downloads big paket.exe, then runs passing in its location, I guess this already happens.
Then big paket.exe can update small paket.exe if needed.

Plaintext:
Enable paket to update paket.bootstrapper.exe if needed.

**Comment by enricosada** [comment]
Closing.

paket-boostrapper has a `--self` flag to self update.

**Comment by enricosada** [comment]
@JohanLarsson please reopen if is not `--self` is not enough
