### ISSUE TITLE
"Dotnet restore" fails on .netstandard projects under 1.6

### ISSUE THREAD

**Issue by SavaNDragos** [fsprojects/Paket#2243]
dotnet restore  {SolutionFile} fails when we have a .netstandard project that triggers versions 1.0-1.5

### Repro steps

Please provide the steps required to reproduce the problem

1. cd to PaketRepro folder
2. dotnet restore .\PaketRepro.sln   --you should see it ok, <Import Project="..\.paket\Paket.Restore.targets" /> is missing from the csproj
3.  git checkout 0e599fd399af05345b5425d41152a91149beb315 --force
4. dotnet restore .\PaketRepro.sln   --you should see it fails now, the import is preset.
[PaketRepro.zip](https://github.com/fsprojects/Paket/files/916909/PaketRepro.zip)

### Expected behavior

When running "dotnet restore {SolutionFile}" runs we should not get an error.

### Actual behavior

C:\Program Files\dotnet\sdk\1.0.2\NuGet.targets(97,5): error : Package System.Security.Cryptography.OpenSsl 4.3.0 is not
 compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Security.Cryptography.OpenSsl 4.3.0 supports
: netstandard1.6 (.NETStandard,Version=v1.6) [D:\ticket\1373\PaketRepro\PaketRepro.sln]
C:\Program Files\dotnet\sdk\1.0.2\NuGet.targets(97,5): error : One or more packages are incompatible with .NETStandard,V
ersion=v1.3. [D:\ticket\1373\PaketRepro\PaketRepro.sln]

### Known workarounds

Remove the import, but not sure if it is ok.

**Comment by cjbhaines** [comment]
@forki the problem occurs when you require multiple versions of .NET Standard inside the same solution. Paket update/install/restore all work fine but you get a build error.

For example:

- NUnit: .NET Standard 1.6
- log4net: .NET Standard 1.3

If everything you reference is at the same version of .NET Standard then it seems to work ok.

Any ideas on how to solve this?

![image](https://cloud.githubusercontent.com/assets/3225747/25661413/38a33724-3019-11e7-923a-c6917baad708.png)

**Comment by forki** [comment]
fixed in paket 5 beta 001

**Comment by cjbhaines** [comment]
Confirmed this is fixed in Paket 5.0.0-beta003. Thanks a lot @forki, I massively appreciate all of your effort here.
