### ISSUE TITLE
Paket pack fails to find compiled DLL for "type project"

### ISSUE THREAD

**Issue by rasmus** [fsprojects/Paket#2248]
### Description

Paket fails to find the compiled DLL for projects using the new VS2017 project format and using `type project` template file.

A simple solution would be to allow switching off the automatic detection of DLL files to include and include them manually.

### Repro steps

1. Create a project

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net451</TargetFrameworks>
  </PropertyGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

2. Install Paket and setup a `paket.template` file with `type project`

3. Compile and execute `.paket\paket.exe pack`

Example repo here: https://github.com/rasmus/PaketBug

### Expected behavior

Paket creates a NuGet package with the compiled DLL within the correct target framework (`net451` in this case).

### Actual behavior

Paket fails with this output

`Unable to find Release output path node in file C:\PaketBug\PaketBug.csproj for any known platforms`

### Known workarounds

Manually copy the compiled DLL to from `bin/Release/net451` `bin/Release` and set property `TargetFramework` to `net451`

**Comment by cloudRoutine** [comment]
The default props from `Microsoft.NET.Sdk` probably aren't getting imported

**Comment by rasmus** [comment]
Even if I set the output like this

```
<OutputPath>bin\$(Configuration)</OutputPath>
```

The DLL is put in e.g. `bin\Release\net451` but Paket looks for the DLL in `bin\Release\`

**Comment by matthid** [comment]
See my comment in https://github.com/fsprojects/Paket/issues/2330
