### ISSUE TITLE
Paket netcore/msbuild15 - no nuget needed

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Paket#2249]
We're pretty close to the point where we won't need to rely on nuget for any part of the netcore, restore, build, pack, and publish process. 

## Remaining Features

_( WIP - I'll fill out the list with items and references as I investigate everything we'll need)_

- [x] paket pack intercepts and edits nuspec
- [ ] generate nuspec from project file - #2211 
- [ ] enable `paket.template` usage with `pack` target
- [ ] generate lockfile `project.assets.json`
  - [LockFileBuilder.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs) the actual `project.assets.json` file
  - [Nuget RestoreCommand.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L223-L476)
  - [RestoreTargetGraph.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreTargetGraph.cs)

- [ ] generate `nuget.g.props` & `nuget.g.targets` 
  - [BuildAssetsUtils.cs - GenerateMsbuildOutputFile](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/BuildAssetsUtils.cs#L364-L567)
  - [MSBuildOutputFile.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/MSBuildOutputFile.cs)
  - [MSBuildRestoreItemGroup.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/MSBuildRestoreItemGroup.cs)

## Open Questions

- should we wrap everything up in a **Paket.Sdk**?
- should there be default dirs or a default layout so that *paket.templates* and similar things are automatically pulled into the build process?

cc @forki @baronfel @enricosada @smoothdeveloper

**Comment by forki** [comment]
Will we have a version that does not need mono? 

/cc @matthid

**Comment by matthid** [comment]
Sorry to disturb a bit but how is "generate nuger.g.targets" the same as "won't rely on nuget"

@forki yes we could have build that ever since I did the huge coreclr branch. I was just lazy and only needed the nuget package :P

**Comment by forki** [comment]
The dependency on mono is one of the reasons why @alfonsogcnunez is not
keen on using it in fable templates.

Am 15.04.2017 3:41 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
making a dotnet standalone tool should be really straightforward at this point... I don't think any big code changes are needed (if at all).

more interesting is the bootstrapper or the distribution as then the package either requires an installed sdk/runtime or depends on a specific platform...

**Comment by cloudRoutine** [comment]
@matthid nuget creates the resources that msbuild15 needs to compile a project, that's the main role it's still playing in the build process

**Comment by matthid** [comment]
@cloudRoutine I know (therefore the sorry) it just still feels wrong ;)

**Comment by forki** [comment]
Yes bootstrapper is the hardest part. I hope someone will contribute a
black magic mode.

Am 15.04.2017 15:52 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by cloudRoutine** [comment]
am I missing something? what's hard about the bootstrapper? paket is a dev tool, so whoever is using it will have the sdk installed already. It's not like we worry about whether someone has installed netframework on their windows machine, because paket will be useless if they don't 😜

**Comment by enricosada** [comment]
@forki boostrapper Is in https://github.com/fsprojects/Paket/pull/2125

It doesn't use dotnet cli tool, just paket.dll (paket published as fdd)  inside a nupkg. 
Dotnetcli tool is not needed ihmo and had drawbacks 

Pratically at first restore, it restore the package who contains paket

**Comment by matthid** [comment]
> It's not like we worry about whether someone has installed netframework on their windows machine, because paket will be useless if they don't 😜

yes we do, otherwise we wouldn't mind installing mono :/

**Comment by enricosada** [comment]
As a note. 
We should not fight but integrate and open extension point of needed. 
No need to replace whole pack sdk. It's going to be harder and more corner cases. 

The only big issue I see ATM is having Sdk (the sdk attribute) so paket target exists before proj restore ( no need to custom import )
But that require something is wip atm

**Comment by matthid** [comment]
> Pratically at first restore, it restore the package who contains paket

so you still need nuget to restore paket? :/

**Comment by enricosada** [comment]
> yes we do, otherwise we wouldn't mind installing mono :/

If we restore like mine or with published paket (netcoreapp + net45) will work with mono, netcore and full fw. 
Like FSC does. It switch FSC based on msbuild host. With msbuild.exe use fsc.exe, with `dotnet mabuild` use FSC netcore

**Comment by enricosada** [comment]
> so you still need nuget to restore paket? :/

Yes. But who care? When sdk attribute will be extensible by custom sdk, will work like that, but no need ogni custom import

**Comment by enricosada** [comment]
To boostrap we can also call something else ( webclient.download) to restore the nupkg or a zip, instead of nuget sdk. 
But who care?

**Comment by cloudRoutine** [comment]
@matthid and I do since we're working toward a no msbuild, no nuget, no fsproj, build pipeline

**Comment by matthid** [comment]
> We should not fight but integrate and open extension point of needed.

I'm not trying to fight just arguing in another direction. Sorry if I sounded harsh. 

My argument is that we contradict ouself if we argue that we don't want to have mono installed but really just switch one dependency with another...

**Comment by forki** [comment]
I want it to work on both. A mono version and a dotnet version. That's what
I meant with back magic mode.

Am 15.04.2017 4:14 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by cloudRoutine** [comment]
@matthid you mean switching mono for netcore?

**Comment by matthid** [comment]
@cloudroutine yeah. the only fundamental advantage is that we can build a standalone tool (with the runtime included) with dotnetcore. But maybe I'm completely alone with this opinion (at least it seems like this).

**Comment by enricosada** [comment]
You don't need to choose mono over dotnetcore. 
Just use the same runtime msbuild is using. 
Msbuild is `Core`? Run `dotnet paket.dll`
Msbuild is `Mono`? Run `mono paket.exe`
Msbuild is `Full`? Run `paket.exe`

That's similar to how FSC is doing

**Comment by cloudRoutine** [comment]
@matthid there are some contexts where I think that will be useful for stuff I'd like to do with paket and FAKE, but I don't expect to be using the runtime specific standalone versions during normal dev over an fdd  version.

**Comment by enricosada** [comment]
Closing.

.net core only paket is tracked in https://github.com/fsprojects/Paket/issues/2875 (with notes about .net sdk too)
