### ISSUE TITLE
Question: Private Github Repo as Nuget Package Source

### ISSUE THREAD

**Issue by granttrevor** [fsprojects/Paket#2260]
Raised this on Stackoverflow first but had zero response - http://stackoverflow.com/questions/43466280/private-github-repository-as-nuget-source-with-paket

Is it possible to use a Github Repository as a Nuget Source with Paket?

Looking at the documentation https://fsprojects.github.io/Paket/github-dependencies.html it doesn't appear to be the case, and I've tried applying a combination of the Github Repository and Git Repository configuration with no real success.

I've been running myself in circles trying to get an SSH Agent working with our TeamCity configuration with zero luck, in order to just use the plain git dependencies.

Given that this is proving fruitless I'd like to switch to using an auth token with github but can't see any option to combine this with specifying a Package source as well.

Ideally I'm after something like:

     github myorganisation/myrepo githubAuthKey Packages: /nuget/

Should this be currently possible?

**Comment by forki** [comment]
Git dependencies is the way to go. And ssh key should be used from the cmd
line git installation. Is there a repro?

Am 19.04.2017 00:57 schrieb "granttrevor" <notifications@github.com>:

**Comment by Krzysztof-Cieslak** [comment]
Git dependencies work with private github repos without any problem, as far as I can tell.

**Comment by granttrevor** [comment]
@forki 's comment gave me the nudge to persist with configuring ssh properly and in the end I have that working with the TeamCity build process and all is as it should be. cheers.

**Comment by forki** [comment]
I was hoping it was config issues
