### ISSUE TITLE
MS Build error - The target "Rebuild" does not exist in the project

### ISSUE THREAD

**Issue by ivaylo5ev** [fsprojects/Paket#2264]
### Description

Checking out the project and building it using the build.cmd file.

My system info:
- *OS*: Windows 8.1 
- *IDE*: Visual Studio 2017 Community, with F# support installed

### Repro steps

1. Checkout the repository, happens with master (9b1bc25) branch.
2. Open command-line window and navigate to the checkout directory
3. Execute `build.cmd`

### Expected behavior

The build process completes without error.

### Actual behavior

An error occurs in MSBuild, details below:

  1) Building I:\Projects\OSS\Paket\Paket.sln failed with exitcode 1.
  2) MSB4057: I:\Projects\OSS\Paket\tests\Paket.Tests\Paket.Tests.fsproj(0,0): The target "Rebuild" does not exist in the project.
  3) MSB4057: I:\Projects\OSS\Paket\src\Paket.Core\Paket.Core.fsproj(0,0): The target "Rebuild" does not exist in the project.
  4) MSB4057: I:\Projects\OSS\Paket\src\Paket\Paket.fsproj(0,0): The target "Rebuild" does not exist in the project.
  5) MSB4057: I:\Projects\OSS\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj(0,0): The target "Rebuild" does not exist in the proje
ct.

The project is being checked out at I:\Projects\OSS\Paket

### Known workarounds

None I can think of at the moment.

**Comment by cdrnet** [comment]
Does this also happen if you use the Visual Studio Command Prompt, instead of just a normal command prompt (cmd.exe)?

**Comment by ivaylo5ev** [comment]
Did not try with the VS Command Prompt. Will try now and update

**Comment by ivaylo5ev** [comment]
The same happens with the Developer command Prompt of VS 2017. I was able to successfully build the solution inside Visual Studio though.

**Comment by forki** [comment]
is this solved?

**Comment by ivaylo5ev** [comment]
@forki Yes, I've been able to run the build.sh and build.cmd files and it works.

**Comment by Thorium** [comment]
Seems to be back when VS2019 is installed.

**Comment by Thorium** [comment]
To found the issue, I created my own Rebuild-target to the fsproj-file first:
```xml
<Target Name="Rebuild">
	<Message Text="Ext = $(MSBuildExtensionsPath)" />
	<Message Text="Tools = $(MSBuildToolsVersion)" />
	<Message Text="msb32 = $(MSBuildExtensionsPath32)" />
	<Message Text="targ = $(TargetFrameworkIdentifier)" />
	<Message Text="fs = $(FSharpTargetsPath)" />
	<Message Text="vs = $(VisualStudioVersion)" />
</Target>  
```

The issue was that a project file was saying
```xml
  <PropertyGroup Condition="'$(VisualStudioVersion)' != '11.0'">
    <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
  </PropertyGroup>
```
but with VS2019 the path was actually in `VisualStudio\v$(MSBuildToolsVersion)\FSharp\` and not in `VisualStudio\v$(VisualStudioVersion)\FSharp\` so 

```xml
  <PropertyGroup Condition="'$(VisualStudioVersion)' != '11.0' And Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\')">
    <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(VisualStudioVersion)' != '11.0' And Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(MSBuildToolsVersion)\FSharp\')">
    <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(MSBuildToolsVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
  </PropertyGroup>  
```
fixed it.
