### ISSUE TITLE
Error while parsing <dependency id="Newtonsoft.Json" version="*" />

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#2266]
### Description
Paket version 4.5.0
```
Paket failed with:
        Cannot load C:\Users\CameronTaggart\tachyus\thermion\packages\JWT\JWT.nuspec
Message: Error while parsing *
Message: Can't parse "*".
Input string was not in a correct format.
```

``` xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>JWT</id>
    <version>2.3.1</version>
    <authors>John Sheehan, Michael Lehenbauer, Alexander Batishchev</authors>
    <owners>johnsheehan, devinrader, abatishchev</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://creativecommons.org/publicdomain/zero/1.0/</licenseUrl>
    <projectUrl>https://github.com/jwt-dotnet/jwt</projectUrl>
    <description>Jwt.Net, a JWT (JSON Web Token) implementation for .NET</description>
    <copyright>Public Domain</copyright>
    <language>en-US</language>
    <tags>jwt json</tags>
    <dependencies>
      <dependency id="Newtonsoft.Json" version="*" />
    </dependencies>
  </metadata>
</package>
```

### Repro steps

Please provide the steps required to reproduce the problem

```
nuget JWT 2.3.1
```

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

I'm not sure if this is a nuspec authoring error or a paket error.

### Known workarounds
```
nuget JWT 1.3.4
```

**Comment by forki** [comment]
I think they changed something to allow this nightmare. A fix is underway - but will take some time since I want to run all integration tests

**Comment by forki** [comment]
NOTE: Someone should do it properly - I just fixed the error. but it seems nuget ranges are now changed and our parser needs adjustments

**Comment by forki** [comment]
also related: https://github.com/fsprojects/Paket/commit/1575266f56b62f155fe8b3cdddc177fe08c7b2a3

**Comment by forki** [comment]
reopened in order to let someone else fix it properly.  but paket 4.5.1 release build is running and reported error will be fixed

**Comment by forki** [comment]
ok fix is released.

**Comment by fsoikin** [comment]
Reading the nuspec/nuget/dotnet docs, I can't find any references to using a wildcard without preceding numbers. 

Also, JWT v2.3.1 seems to be no longer available on NuGet, and the next version 2.3.2 does have a version specified for the dependency.

However, all previous beta and alpha versions - from 2.0.0-beta2 up to 2.3.0-beta - still have the bogus dependency, which means Nuget.org does technically allow it.

In version 2.0.0-beta2, where the [offending nuspec line first appeared](https://github.com/jwt-dotnet/jwt/commit/6f398dc448b9f522f31c3796109eaba8a09d54d8#diff-c4ee3fc874cd15257e6d65d31218bf55R15), it had no "version" attribute at all, rather than an asterisk. This means that the asterisk was added during packing. Considering the lack of documentation for this "feature", I'm inclined to think that this is just a bug in `dotnet pack`.

**Comment by forki** [comment]
I think * should be parsed as >= 0

**Comment by fsoikin** [comment]
@forki:

1. But your fix in https://github.com/fsprojects/Paket/commit/3b8047e3c8112a7e0d63ace257f7c98073a25feb already does that, no?

2. Parsing * as >=0 is inconsistent with `dotnet restore`. When the spec is ">= 0", Paket will select the highest version, but `dotnet restore` will select the lowest (I have verified this empirically, just in case). This will cause different resolution of `Newtonsoft.Json` (and thus potentially different behavior) between Paket-based apps that reference `JWT` v2.3.0-beta and similar apps that do not use Paket. Is that ok?

**Comment by forki** [comment]
Paket had always been different in install behavior. I could write endless essays about that. When we do convert we try to do a conservative conversion and keep it as aligned as possible to nuget. But sometimes that's not really possible.

**Comment by fsoikin** [comment]
Ok, I suspected that would be the answer.

But what about the first point? Didn't your commit already make it parse as ">= 0"? Should this case be closed then?

**Comment by forki** [comment]
yes I think I did that
