### ISSUE TITLE
[Nexus] Nexus 2.14.x don't handle encoded '+' in url

### ISSUE THREAD

**Issue by Evolva** [fsprojects/Paket#2269]
### Description

The fix from commit https://github.com/fsprojects/Paket/commit/a46c0fd11ac8bcc7391b946955732d9707ed1205 "Encode '+' in Urls - fixes" seems to break Nexus 2.14.x support

### Expected behavior
The previous version of Paket (4.4.0) use the following query
https://someNexusFeedUrl/Packages?$filter=tolower%28Id%29+eq+%27myPackageName%27 which return a 200 status code

### Actual behavior
While the last version (4.5.1) use the following query
https://someNexusFeedUrl/Packages?$filter=tolower%28Id%29%2Beq%2B%27myPackageName%27 which return a 400 status code

### Known workarounds
Downgrade Paket to version 4.4.0

**Comment by matthid** [comment]
what a mess :/

**Comment by forki** [comment]
Sigh. Can someone please help me out and fix this properly?

Am 21.04.2017 15:58 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by baronfel** [comment]
It sounds like at minimum we need a per-source escaping strategy?

**Comment by forki** [comment]
No maybe we did that encoding wrong?

Am 21.04.2017 17:35 schrieb "Chet Husk" <notifications@github.com>:

**Comment by bigbearzhu** [comment]
Looks like the `'+'` means space in query string after the `?` mark, but should be escaped to `%2B` before the `?` mark.
http://stackoverflow.com/a/8116989/1837339

**Comment by forki** [comment]
I reverted a46c0fd  and applied e43745ab7132ca73da1f9807ad71ce016035640a
