### ISSUE TITLE
Paket adds a BOM to xxproj files

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#2271]
### Description

It would seem that Paket v4.4.0 adds a BOM to my xml files, widely considered a bad thing.

<img width="177" alt="screen shot 2017-04-22 at 10 40 32" src="https://cloud.githubusercontent.com/assets/193115/25302865/35d7c5f2-2748-11e7-8a6f-20ce782eef96.png">

### Repro steps

Please provide the steps required to reproduce the problem

1. `paket install`

2. `cat myproj.fsproj`

**Comment by forki** [comment]
If someone wants to address this then it would be appreciated.

**Comment by RustyF** [comment]
Hi - @haf do you think this is *since* 4.4 or do we need to pin down the regression version?

**Comment by haf** [comment]
It's pretty new, but I'm not sure which version it's from, I'm afraid.

**Comment by TeaDrivenDev** [comment]
I assume we'd never want to have a *change* regarding the BOM, right? Apparently `.fsproj` files created in Visual Studio *have* one, those created by Ionide/Forge don't.

My impression is that writing a BOM or not comes down to https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PaketConfigFiles/ProjectFile.fs#L1187 (or rather the configuration of the FileStream/StreamWriter used), but any fixed decision there would be wrong for "half" of the user's project files - unless we go back to the existing file, ask for its BOM and adjust the encoding accordingly before writing the XML document.

**Comment by forki** [comment]
Yes we don't want to write that. PRs welcome

Am 31.07.2017 05:46 schrieb "TeaDrivenDev" <notifications@github.com>:

**Comment by kichristensen** [comment]
@forki Isn't this issue fixed by #2575

**Comment by matthid** [comment]
Yes, thanks
