### ISSUE TITLE
Flawky test or paket hang

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2276]
https://travis-ci.org/fsprojects/Paket/builds/225228446#L4086

```
1) Error : Paket.IntegrationTests.AutoRestoreSpec.#1835 auto-restore on downloads targets and updates proj file

System.Exception : Paket failed with:

	Error occured while downloading from https://github.com/fsprojects/Paket/releases/download/4.6.3/paket.targets.

  at Paket.IntegrationTests.TestHelpers.directPaketInPath (System.String command, System.String scenarioPath) [0x0006b] in <58fe0b1691da6970a7450383160bfe58>:0 

  at Paket.IntegrationTests.AutoRestoreSpec.#1835 auto-restore on downloads targets and updates proj file () [0x00024] in <58fe0b1691da6970a7450383160bfe58>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
```

I think it first appeared in https://github.com/fsprojects/Paket/pull/2268 and now in master as well https://github.com/fsprojects/Paket/commits/master 

Look at how paket just stops downloading here: https://ci.appveyor.com/project/SteffenForkmann/paket/build/0.0.1.7884

Something is off. Maybe we can see the reason better after https://github.com/fsprojects/Paket/issues/2275?

**Comment by matthid** [comment]
Have not seen this for a while.

**Comment by jackfoxy** [comment]
I'm seeing Paket version 5.7.2 hang in Appveyor.

**Comment by matthid** [comment]
Problem is that I don't have the slightest clue of what could be the reason and there seems to be no way to reproduce this.
It could even be that a request is not returning and paket is waiting for it.
@jackfoxy If we ever get a detailed log for this I can take another look...

**Comment by forki** [comment]
Multi people report issues with 5.7.2. Is it broken?

**Comment by matthid** [comment]
Ah so it might be a different issue introduced recently, yeah maybe

**Comment by jackfoxy** [comment]
Resolved! Not a paket issue. Appveyor reported bad connection to nuget server and published work-around to point to European nuget server.

**Comment by forki** [comment]
Wow that's good news

Am 18.07.2017 02:17 schrieb "Jack Fox" <notifications@github.com>:

**Comment by jackfoxy** [comment]
I suspect this is almost always the issue. It doesn't make sense for paket to function locally, and then the same paket version, command, dependency file, etc. to have a problem in a different environment, except that that environment has a connection issue with nuget.

**Comment by forki** [comment]
All we can do is to try to make it as rel as possible. Nuget.org
connectivity issues are out of our control

Am 18.07.2017 10:43 nachm. schrieb "Jack Fox" <notifications@github.com>:
