### ISSUE TITLE
paket bootstrapper should not be a simple script ?

### ISSUE THREAD

**Issue by chicocode** [fsprojects/Paket#2279]
Committing binary files to version control does not seem to be a good idea to me.

Paket bootstrapper should not be a simple script that downloads paket.exe ?

**Comment by forki** [comment]
if you find a way to make that reliably work on all plattforms then I'm very interested

**Comment by chicocode** [comment]
Maybe a script for Windows and another for Linux based platforms, or even .fsx scripts should take care of this task. What you think?

**Comment by forki** [comment]
it just doesn't work that nice than the very very very little bootstrapper

**Comment by chicocode** [comment]
Closing as explained
