### ISSUE TITLE
Paket fails when group is removed (or renamed)

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2281]
1)

```
group Group1

source https://api.nuget.org/v3/index.json

framework: net461


nuget Microsoft.Net.Compilers
```

> paket install

2) Remove / rename a group

```
group Group2

source https://api.nuget.org/v3/index.json

framework: net461


nuget Microsoft.Net.Compilers
```

![image](https://cloud.githubusercontent.com/assets/4236651/25400993/ab6e039a-29f4-11e7-9d03-0a1ae600399a.png)

# Workaround:

either completely delete the lockfile, or remove the offending group from it

**Comment by forki** [comment]
thanks for the repro
