### ISSUE TITLE
FSharp.Compiler.Tools is installed as framework-specific

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2283]
take https://github.com/brase/castos

run paket install

__Expected__

It should import FSharp.Compiler.Tools at the top.

__Actual__

it imports it at the bottom, causing FSharpTargetsPath to not be set.

**Comment by 0x53A** [comment]
![image](https://cloud.githubusercontent.com/assets/4236651/25409340/cf378932-2a11-11e7-92c7-df9a792b664f.png)

I'm starting to think my approach to divide them into fw-specific and global was flawed from the start ...

cc @matthid do you have any ideas?

It is a bit unfortunate that FSharp.Compiler.Tools MUST be imported at the top ...

**Comment by matthid** [comment]
But NuGet is adding targets at the bottom as well, correct?

**Comment by 0x53A** [comment]
props at the top, targets at the end

**Comment by matthid** [comment]
So it isn't working with NuGet as well? Maybe the package itself needs to be fixed?

**Comment by 0x53A** [comment]
No, it works with nuget, but not with paket

**Comment by 0x53A** [comment]
FSharp.Compiler.Tools contains a FSharp.Compiler.Tools.__props__

**Comment by matthid** [comment]
I think paket was doing the same in the past (IE adding props on top and targets on bottom).
I can take a look but that might take a few days (and tbh. I first want my other PR to be integrated because there are changes at the same place)...

**Comment by 0x53A** [comment]
Before https://github.com/fsprojects/Paket/issues/2227 paket added props somewhere in the middle and targets at the end.

I added the whole global/fw-specific stuff specifically for FSharp.Compiler.Tools, but maybe there is a better way?

I am currently debugging it, just wanted to vent a bit

**Comment by matthid** [comment]
@0x53A Yes, looking at the original issue #2227 I think its enough to move the imported props files right after the initial propertygroups. That might fix most of this stuff for now. We probably don't even need global special handling...

**Comment by 0x53A** [comment]
@matthid Not with how FSharp.Compiler.Tools is defined currently:

https://github.com/fsharp/fsharp/blob/master/FSharp.Compiler.Tools.Nuget/build/FSharp.Compiler.Tools.props#L30

If we move it after ``TargetFramework`` is defined, then it thinks it is in netcore land, and doesn't set the property.

We would need another way to differentiate between netfx / netcore, and adapt the check.
Atm it needs to be imported totally at the top.

**Comment by 0x53A** [comment]
@matthid I think I found it:

It seems to apply the same logic for both DLLs and targets, but that is wrong (afaik):

// For a given list of paths and target profiles return tuples of paths with their supported target profiles.
// Every target profile will only be listed for own path - the one that best supports it. 

So if you have props in both /build/ and /build/netcore/, then it will use only /build/netcore/ for netcore, but that is wrong, it should use BOTH.

**Comment by matthid** [comment]
Ah ok interesting, I'd suggest not touching it or doing it on top of https://github.com/fsprojects/Paket/pull/2267. I've basically rewritten that part completely....

**Comment by matthid** [comment]
I think the easiest is probably to add the file to multiple "FrameworkFolder" (called "LibFolder" previously) instead of touching the calculation of the folders (just in case you wanna get into this)...

**Comment by 0x53A** [comment]
(I think) I found the issue, that is enough for tonight ...

My projects aren't affected, anyway, I just found this while trying to help someone on slack.

Note to self (or someone else who cares): add a unit test for this case

**Comment by 0x53A** [comment]
Also, another thing: paket should first filter for .props / .targets, because the directory netcoreapp1.0 does not contain any:
,
![image](https://cloud.githubusercontent.com/assets/4236651/25412188/7115d722-2a21-11e7-964f-1ce5536a20a7.png)

**Comment by 0x53A** [comment]
I have a workaround here: https://github.com/fsprojects/Paket/pull/2286
