### ISSUE TITLE
can't load PDBs for master anymore

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2285]
When I press F11 to step into paket.exe:

![image](https://cloud.githubusercontent.com/assets/4236651/25411255/07d85be0-2a1c-11e7-806a-cac68db61fa8.png)

The following diff re-enabled debugging for me: https://github.com/0x53A/Paket/tree/debuggable

master: fdbb707a
VS 2017:
![image](https://cloud.githubusercontent.com/assets/4236651/25411308/5400bce2-2a1c-11e7-9fc3-e680a1dfba47.png)

**Comment by 0x53A** [comment]
cc @ctaggart

**Comment by ctaggart** [comment]
Can you please file an appropriate bug about the portable pdb format not working yet in visualfsharp repro?

**Comment by 0x53A** [comment]
@ctaggart Can you reproduce it? It may also be an issue with my machine, or my settings, or whatever ..

**Comment by ctaggart** [comment]
I'll check tomorrow.

**Comment by ctaggart** [comment]
@0x53A, I'm not sure this is related to #2200. I just tried to reproduce the problem and couldn't using the latest from master.

I have Visual Studio 15.1 (26403.7) installed. Looks like you were on (26403.0).  I didn't see anything that stood out in https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes, but may be try updating. It doesn't look like I have the F# daily installed on this machine.

![image](https://cloud.githubusercontent.com/assets/80104/25613909/34b3eaf8-2f30-11e7-8654-9f038c82297a.png)

**Comment by 0x53A** [comment]
For me it is related - if i revert back to full pdbs then it works again. But I asked a few others and they don't have the same issue, so it seems to be related to my machine...

Thanks

**Comment by ctaggart** [comment]
May be try updating Visual Studio. I'm not sure how to downgrade it, else I would try.

**Comment by 0x53A** [comment]
Already did, that issue was a few days old:
![image](https://cloud.githubusercontent.com/assets/4236651/25615710/04ea7fae-2f39-11e7-9bc1-1603cab3f714.png)

The only thing I can think of would be debugger settings, e.g. managed compatibility mode and so on, I will try to play a bit with them, maybe it will start working.
