### ISSUE TITLE
Version resolution not successful

### ISSUE THREAD

**Issue by wooderz** [fsprojects/Paket#2291]
### Description

When downloading dependencies, multiple versions of the same package get downloaded.

### Repro steps

Please provide the steps required to reproduce the problem

1. Project A has following paket.template file
```
type file
id JW.MessageBus
authors James Woodley
description
  Message Bus
files
  ../../build/Infrastructure.MessageBus ==> lib
include-pdbs false
owners James Woodley
dependencies
  JW.Infrastructure.Http
  JW.Infrastructure.Http.Configuration
  JW.Infrastructure.Settings
  JW.Infrastructure.Tools
  MassTransit.RabbitMQ
  MassTransit.StructureMap
```
MassTransit.StructureMap has a dependency on structuremap (>= 4.4.3)
JW.Infrastructure.Settings has a dependency on structuremap

2. Project B has a paket.references file
```
JW.MessageBus
```

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Only the highest version is loaded and a binding redirect is added if necessary

### Actual behavior

 Visual Studio ends up with both StructureMap 4.4.4 and 4.4.5 loaded into Project B and thus an error occurs.

### Known workarounds

None. Yet

2 Structuremap Versions
![structuremap versions](https://cloud.githubusercontent.com/assets/4377107/25462937/5e3fd9a8-2aea-11e7-9772-5bd01e7fd333.PNG)

Visual Studio Error
![vs error](https://cloud.githubusercontent.com/assets/4377107/25462936/5e3e3242-2aea-11e7-87b5-50a7516f5811.PNG)

**Comment by cloudRoutine** [comment]
What are you using the template for exactly? It seems like you are creating a nupkg and then importing that into another file or something ([btw you can set versions in the template](https://fsprojects.github.io/Paket/template-files.html#Dependencies))

If that's the case you probably want to set the version using `LOCKEDVERSION` in the template or explicitly listing the constraint.

If that's not the case than both of your projects should have `paket.references` so they can reference the packages listed in your `paket.dependencies`

You may also want to check that an extraneous reference node isn't left in the xml of your csproj

But I'm having trouble following what exactly you're trying to do so I can't be of much assistance until I understand what you're trying to do better.

**Comment by cloudRoutine** [comment]
Could you also post your `paket.dependencies` file?

Although an archive of your repo would be the most helpful `git archive -o "<archiveName>.zip" HEAD`
You can drag and drop them into github comments

If there's sensitive material in the src that you can't share, just remove all of the source code, that's not important for diagnosing & fixing this issue.

**Comment by wooderz** [comment]
Exactly as you suggest. Project A is turned into a nupkg and then that is referenced in Project B as ive shown in the Project B paket.references file.

Setting LOCKEDVERSION in the paket.template doesnt resolve this issue.

**Comment by cloudRoutine** [comment]
okay I think I get it now, the issue is that two dependencies in the nupkg you're creating target the same package with different version constraints. These constraints aren't being unified and thus the double listing of the reference. That sound right?

But why are you using a nupkg instead of a project reference? is this not in the same solution?

**Comment by forki** [comment]
if you use normal project references then Paket pack will automatically transform these into nuget package references during "paket pack".

**Comment by wooderz** [comment]
My bad calling them projects hasnt helped.

They are projects in different solutions. We pack A because its a shared library that gets used across our whole architecture.

Project A is in a different solution to Project B.

Youve hit the nail though, the issue is the constraints arent unified so we get 2 versions.

**Comment by forki** [comment]
ok so we only need to look at the deps, lock and ref files in B.

A is just a nuget poackage that you draw from some source.
Cany ou mail me the repo B? If you have issues with security then delete all cs files. I just need csproj, sln, and all paket stuff

**Comment by wooderz** [comment]
Sure thing. There are a few other projects in B that I dont think are relevant here so ill remove them in their entirety but leave the .sln as is. Wont be long

**Comment by forki** [comment]
sforkmann @ gmail

**Comment by wooderz** [comment]
Sent via a wetransfer link. Let me know if you have any issues downloading or otherwise! Thanks a lot for looking into this!

**Comment by cloudRoutine** [comment]
@wooderz your template should be `project` not `file` btw

**Comment by wooderz** [comment]
@cloudRoutine not doubting youre right but can you please explain why?

**Comment by cloudRoutine** [comment]
https://fsprojects.github.io/Paket/template-files.html#Sample-1

> A paket.template file using type project may look like this:
>```
>type project
>licenseUrl http://opensource.org/licenses/MIT
>```
> This template file will create a nupkg: - Named Test.Paket.Package.[Version].nupkg - Version, Author and Description from assembly attributes - Containing $(OutDir)\$(ProjectName).* (all files matching project name in the output directory) directory in the lib directory of the package. - Referencing all packages referenced by the project. - Package references - Project references, for projects in the sln that has paket.template files.

**Comment by wooderz** [comment]
Ok I'll give it a go, I'm not sure I understand the difference as we've listed our dependencies in the .template file anyway, but I'll try it now. 

Should **all** .template files be done like that?

**Comment by forki** [comment]
ok this is what I did to reproduce:

I went to [Root]\Authorisation\src\paket.dependencies and added reference for testing:

    group Test
    
    source https://api.nuget.org/v3/index.json
    source nupkg
    
    nuget WhenYouMove.Infrastructure.Settings

then I built the package and run install:

    cd [Root]\Infrastructure\src\Settings
    paket pack templatefile .\Settings.paket.template output ..\..\..\Authorisation\src\nupkg\ version 1.0.1
    cd [Root]\Authorisation\src
    paket install

Then I looked at why structuremap is duplicated. The reason seems that you put the dll into the WhenYouMove.Infrastructure.Settings package AND referenced it as dependency. You should only reference it as dependency.

The issue is that file pattern in the template file probably also grabs the StrutureMap.dll. You don't want to do this. One way is to use type porject like @cloudRoutine suggested. Another is to fix the file pattern.

**Comment by wooderz** [comment]
I've changed everything to type project as @cloudRoutine mentioned. Now when I run `paket install` on my Project B, I get nothing. All the references included in the paket.references file aren't there. 

Is there a clean function to start again? Including recreating the csproj files?

**Comment by wooderz** [comment]
Also the nuspec files now don't have any <dependencies> sections? Should they?

**Comment by wooderz** [comment]
If I try and use nuget package manager I get an error stating "You are trying to install this package into a project that targets '.NetFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by wooderz** [comment]
Looking at the nupkg there is no /lib folder. How do I get the output into that? My output folder in the project is set to ../../build/ProjectName yet nothing is in the .nupkg

**Comment by cloudRoutine** [comment]
are you using `paket pack` to create the nupkg?

**Comment by wooderz** [comment]
Yes we are.

**Comment by wooderz** [comment]
Ok it seems changing the template file from `"ProjectName".paket.template` to just `paket.template` has resolved it.

**Comment by forki** [comment]
uih. that's a real bug then. @cloudRoutine we need to investigate that

**Comment by wooderz** [comment]
Having re-read the paket.template documentation it could be our issue. We had

`ProjectName.csproj`
`ProjectName.paket.template`

I think missing the .csproj in the paket.template name might have caused the confusion

**Comment by wooderz** [comment]
However 9/10 occasions we only have one project in the folder so `paket.template` suffices

**Comment by forki** [comment]
ok. so it's "just" an usability issue. we should have printed big yellow warning somewhere

**Comment by wooderz** [comment]
Guys, can't thank you enough. This seems to have resolved the issue! I'll close this GitHub issue and send my gratitude for your fast responses and efforts!
