### ISSUE TITLE
Paket generates `any/` folders

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#2304]
### Description

Update nugets: get this result after building;

```
$ tree src/Lib.Crypto/any/
src/Lib.Crypto/any/
└── netstandard1.6
    ├── FSharp.Core.optdata
    └── FSharp.Core.sigdata
```

What are they and why are they generated? Why aren't `obj` folders enough anymore?

**Comment by forki** [comment]
This is correct paket behaviour. These are files in the current FSharpCore package. @dsyme knows about it and created a fix which merges optdata and sigdata into FSharp.Core. This package is not released yet

**Comment by cloudRoutine** [comment]
This is actually the wrong behavior, `any` is used in lieu of a framework specification in the nuspec to indicate it should be added to all specified frameworks, but when installed `any` shouldn't be in the path

**Comment by forki** [comment]
what I meant is: it's correct that it's installed as content. Feel free to fix the any path

**Comment by matthid** [comment]
the path is correct nuget does not know any structure in the content folder (there is a contentFiles folder, which has a structure...)

**Comment by cloudRoutine** [comment]
![](http://i.imgur.com/VvP4Qb5.png) i think the FSharp.Core nuspec is setup wrong too....
