### ISSUE TITLE
Exception then i use copy_local: true in paket.references

### ISSUE THREAD

**Issue by vik-borisov** [fsprojects/Paket#2312]
### Description

------------------------>.paket\paket install --verbose
Paket version 4.8.4
found: ------------------------\paket.dependencies
Parsing ------------------------\paket.dependencies
Skipping resolver for group build since it is already up-to-date
Skipping resolver for group Main since it is already up-to-date
------------------------\paket.lock is already up-to-date
Paket failed with:
        Unable to parse ------------------------\paket.references
StackTrace:
     в Paket.UpdateProcess.clo0@1-7(IEnumerable`1 msgs)
   в Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
   в <StartupCode$Paket-Core>.$PublicAPI.Install@179.Invoke(Unit unitVar0)
   в Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   в Paket.Program.main@433-10.Invoke(ParseResults`1 results)
   в Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
   в Paket.Program.main$cont@420(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
   в Paket.Program.main()
### Repro steps

paket.refereences
npgsql    copy_local: true

paket.dependencies

cache ----------------
redirects : on
copy_local: false
framework : net45

nuget npgsql > 3

**Comment by forki** [comment]
Can you please upload a small repro sample?

Am 03.05.2017 10:56 vorm. schrieb "Viktor Borisov" <notifications@github.com

**Comment by vik-borisov** [comment]
@forki I will do in a few hours
if i removed copy local: false from paket.dependencies then install process is success

**Comment by forki** [comment]
Oh that's interesting. Yes please send a repro.

Am 03.05.2017 11:31 schrieb "Viktor Borisov" <notifications@github.com>:

**Comment by vik-borisov** [comment]
I found problem. i missed divider in paket.references, but i found a function [returnOrFail](https://github.com/fsprojects/Paket/blob/806b4054e55be1888eb12b2bcb75af4efbc655f5/src/Paket.Core/Installation/UpdateProcess.fs#L226), wich remove inner exception and it throw only the top exception.
