### ISSUE TITLE
paket pack does not work with .net core sdk

### ISSUE THREAD

**Issue by MiloszKrajewski** [fsprojects/Paket#2324]
### Description

This issue has been reported once and then seemed to be fixed, but it still does not work for me. Or maybe I missed something. So, this might be a duplicate or not.

### Repro steps

Create a project:
```
mkdir xxx && cd xxx && dotnet new console
```

Get `paket`:

```
curl -L -o paket.cmd http://bit.ly/2ooaInt
```

Initialize project:

```
paket init && touch paket.references && paket install && dotnet restore
```

Test if it runs:

```
dotnet run
```

Create `paket.template`:

```
echo type project > paket.template
```

Pack time!

```
paket pack output .
```

### Expected behavior

Nuget package is created.

### Actual behavior

Paket fails with:

```
Paket failed with:
        Unable to find Release output path node in file C:\dev\xxx\xxx.csproj for any known platforms
```

### Known workarounds

Use `dotnet pack`, although there are problems with that as well (see: #2323)

**Comment by haf** [comment]
If you guys want to help out to release Expecto v5 here https://github.com/dotnet/cli/issues/6593 as a means for testing the alpha/beta of Paket, I'd be delighted.

**Comment by enricosada** [comment]
@MiloszKrajewski  the `dotnet pack` is the way to go with .net sdk project.

Closing this, i'll check the #2323

**Comment by enricosada** [comment]
Added https://github.com/fsprojects/Paket/issues/3011 to track fix guidance about `paket pack` vs `dotnet pack`
