### ISSUE TITLE
paket pack netstandard library

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#2330]
### Description

I tried paket pack on what I think is a vanilla netstandard1.3 project

### Repro steps

When running `.paket/paket.exe pack output publish` it complains on:

1. `Unable to find Release output path node in file C:\Git\Kasta\Gu.Roslyn.Asserts\Gu.Roslyn.Asserts\Gu.Roslyn.Asserts.csproj for any known platforms`

The output path is `bin\Release\netstandard1.3\` I think this is the default. Manually changing it to `bin\Release\`  solves this issue.

2. `Project C:\Git\Kasta\Gu.Roslyn.Asserts\Gu.Roslyn.Asserts\Gu.Roslyn.Asserts.csproj has no AssemblyName set`

When inspecting it in VS it looks like: 
![image](https://cloud.githubusercontent.com/assets/1640096/25957476/b4b4b6a2-366e-11e7-9dff-1ef4a747125b.png)

My guess is that it defaults to the name of the project file.

Repro sln:

[Gu.Roslyn.Asserts.zip](https://github.com/fsprojects/Paket/files/993487/Gu.Roslyn.Asserts.zip)

### Expected behavior

Would be sweet if paket packed the project like it is. *Unless I have dumbed things.
So the result would be something like when using:
```
﻿type file
id Gu.Roslyn.Asserts
title Gu.Roslyn.Asserts
version 0.1.0-dev
authors Johan Larsson
owners Johan Larsson
copyright Copyright Johan Larsson 2017

description
  Asserts for testing Roslyn analyzers and code fixes.
projectUrl https://github.com/JohanLarsson/Gu.Roslyn.Asserts
licenseUrl http://opensource.org/licenses/MIT

tags Roslyn Diagnostic Analyzer Test

dependencies
  Microsoft.CodeAnalysis.CSharp.Workspaces 2.1.0

files
  ../Gu.Roslyn.Asserts/bin/Release/netstandard1.3/Gu.Roslyn.Asserts.dll ==> lib/netstandard1.3
  ../Gu.Roslyn.Asserts/bin/Release/netstandard1.3/Gu.Roslyn.Asserts.xml ==> lib/netstandard1.3 
```

### Known workarounds

Manually edit things until it packs or use a file template.

Side note: after chaning the project file it stopped building complaining about duplicate assembly attrivbutes. Adding `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` to the project file solved this.

**Comment by miloszes** [comment]
We also stumbled across the same problem

**Comment by matthid** [comment]
We currently recommend to use `dotnet pack` to create nuget packages in the new SDK.
If you still have old-style projects you can use dotnet-mergenupkg to merge them together.

Also please upgrade to the new SDK and tell us if this fixes the problem.
