### ISSUE TITLE
paket.exe find-package-versions requires paket.dependencies although it doesn't need to

### ISSUE THREAD

**Issue by nikoudel** [fsprojects/Paket#2332]
### Description

Running paket.exe find-package-versions fails with message:

Paket failed with: Could not find 'paket.dependencies'....

It's by design, I understand, but only looking up packages in repository should not put any requirements on local workspace because at that point no changes are being made anywhere.

### Repro steps

1. cd out of local paket repository (e.g. cd c:\temp) or rename your paket.dependencies to something else

2. paket.exe find-package-versions nuget Paket source https://www.nuget.org/api/v2 max 1 -s

### Expected behavior

Should print the latest version of Paket, e.g. "5.0.0-alpha023".

### Actual behavior

Paket failed with:
        Could not find 'paket.dependencies'. To use Paket with this solution, please run 'paket init' first.
If you have already run 'paket.init' then ensure that 'paket.dependencies' is located in the top level directory of your repository.
Like this:
MySourceDir
  .paket
  paket.dependencies

**Comment by forki** [comment]
Marked as up-for-grabs. If anyone wants to try it
