### ISSUE TITLE
DependencyChange detection is wrong for runtime graph

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#2334]
* Create a project as described in https://github.com/fsprojects/Paket/issues/2233

run paket restore and dependency change detection will go crazy on it. Basically every package will be reported as "not in deps file". I think the issue is that GetTransitiveDependencies is calculating wrong result.

Basically that function looks into all nuspecs and computes union of all deps. But since runtime dependency  resolution we retrieve deps from within the package. So this is no longer correct.

@matthid any chance you could fix that function?

**Comment by matthid** [comment]
Oh crap. Yes I will fix this, but probably in a week (or maybe tomorrow).

Basically I think it just needs to ignore deps in the lockfile which are marked with `isRuntimeDependency: true`

**Comment by matthid** [comment]
nice, thanks!
