### ISSUE TITLE
./build.sh fails in mono 4.8.0

### ISSUE THREAD

**Issue by oivvio** [fsprojects/Paket#2338]
### Description

Following the installations [instructions for linux](https://fsprojects.github.io/Paket/installation.html) I'm not able to build Paket in mono.

### Repro steps

I've tried this in my own mono installation on a Ubuntu 16.04 machine. I tried the mono that comes per default with ubuntu and and the most recent version from the mono project. But a cleaner reproduction is with the official mono docker image that reports this version of mono:

`Mono JIT compiler version 4.8.0 (Stable 4.8.0.524/9d74414 Wed Apr  5 17:57:04 UTC 2017)`

1. docker run -it mono bash

2. curl  -Lo master.zip  https://github.com/fsprojects/Paket/archive/master.zip

3. apt-get update && apt-get install unzip

4. unzip master.zip

5. cd Paket-master

6. ./build.sh

### Expected behavior

I'd expect the build script to complete with out errors.
 
### Actual behavior

I get this at the end:

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0137353
AssemblyInfo        00:00:00.0173965
Build               00:00:30.5149921
InstallDotNetCore   00:00:03.8019861
DotnetRestore       Failure
Total:              00:00:34.3943252
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: Restore failed on "restore" "/tmp/Paket-master/src/Paket.Core.preview3/Paket.Core.fsproj" 
  at Fake.DotNetCli+Restore@146-3.Invoke (System.String message) [0x00001] in <591449acccf1c534a7450383ac491459>:0 
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () [0x00012] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.PrintfImpl+Final1@224[TState,TResidue,TResult,A].Invoke (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] env, A a) [0x00038] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at Fake.DotNetCli.Restore (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] setRestoreParams) [0x0011c] in <591449acccf1c534a7450383ac491459>:0 
  at FSI_0005.Build+clo@247-32.Invoke (System.String proj) [0x0000a] in <ffa60ddca1be49f299a3077717b7be97>:0 
  at Microsoft.FSharp.Collections.SeqModule.Iterate[T] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] action, System.Collections.Generic.IEnumerable`1[T] source) [0x0002d] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build+clo@245-31.Invoke (Microsoft.FSharp.Core.Unit _arg2) [0x0000b] in <ffa60ddca1be49f299a3077717b7be97>:0 
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <591449acccf1c534a7450383ac491459>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <591449acccf1c534a7450383ac491459>:0 
---------------------------------------------------------------------

```
Full [buildlog here](http://termbin.com/pd61)

### Known workarounds

I don't know of any.

**Comment by matthid** [comment]
I get similar errors on windows as well. @cloudRoutine maybe we should use something more stable than the 2.0 preview bits?

**Comment by matthid** [comment]
'" 
﻿﻿/root/.local/share/dotnetcore/dotnet: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /root/.local/share/dotnetcore/dotnet)'

Do you have all dnc requirements installed?

**Comment by oivvio** [comment]
@matthid 
Am I supposed to use a mix of mono and dotnetcore? Where are those requirements listed?

I'm not coming to f# from a .net background. Is there stuff that I'm supposed to build Paket other than mono?

**Comment by matthid** [comment]
@oivvio https://github.com/dotnet/core/blob/master/Documentation/prereqs.md
Yes we are still trying to figure out how we want to do all this netcore stuff, sorry.
You can also try to disable all of that by setting the `DISABLE_NETCORE` environment variable (I hope that still works), if you don't care about netcore.

**Comment by oivvio** [comment]
After reading your feedback and some trial and error I managed to cook up this Dockerfile that results in a container with a working paket.exe 


```
# https://github.com/project-everest/everest/commit/e4c6591642c50c2e0c3457f1de3f56a346a91457
FROM ubuntu:xenial-20170214

ENV MONO_VERSION 4.8.0.524

RUN apt-get update \
  && apt-get install -y curl libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev unzip vim tmux\
  && rm -rf /var/lib/apt/lists/*

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF


RUN echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/$MONO_VERSION main" > /etc/apt/sources.list.d/mono-xamarin.list \
  && apt-get update \
  && apt-get install -y binutils mono-devel ca-certificates-mono fsharp mono-vbnc nuget referenceassemblies-pcl \
  && rm -rf /var/lib/apt/lists/* /tmp/*

RUN curl -Lo master.zip https://github.com/fsprojects/Paket/archive/master.zip \
    && unzip master.zip \
    && cd Paket-master \
    && export DISABLE_NETCORE=true \
    && ./build.sh

```

**Comment by matthid** [comment]
I'm closing this. We are not planning to go back to mono 4.8 at the moment, though it should build as long as msbuild is used (which is not default in mono 4.x)
