### ISSUE TITLE
Paket not using its packages

### ISSUE THREAD

**Issue by llehn** [fsprojects/Paket#2340]
I have a solution which has only projects using the new csproj format. However they target net462. 
Using dotnet sdk 2 preview 1 I can use paket, which I couldn't before (https://github.com/fsprojects/Paket/issues/2212)

I converted the solution using convert-from-nuget and a little editing, now I can do
dotnet restore
and 
msbuild 
which compiles my solution.

Looking at the build log I found that all referenced paths point to %HOME%\.nuget\packages.
Indeed, if I do dotnet restore, then just delete the packages folder created by paket, it still compiles fine.

**Comment by matthid** [comment]
That's because we don't have a real integration yet. We basically tell the nuget system which versions to use...

**Comment by matthid** [comment]
This is currently `by-design`, suggestions are welcome and we have `storage: none` to get back your disk-space.
