### ISSUE TITLE
How should paket and dotnet restore work together?

### ISSUE THREAD

**Issue by chicocode** [fsprojects/Paket#2346]
Sorry, I'm new to paket and I do not quite understand well how `dotnet restore` and `paket` should work together. 
Currently, in a new dotnet core application I am restoring via `paket restore` and If I try do build the application I get an error.
If I run `dotnet restore` right before `dotnet build` everything works fine.
Should I really restore both, via `paket restore` and `dotnet restore` to be able to run application?

**Comment by forki** [comment]
Dotnet restore will call paket restore and do a bit of extra work. So yes
for netcore we hook into the default cli commands and calling dotnet
restore is the way to go.

Am 17.05.2017 21:42 schrieb "Francisco Hisashi Berrocal" <
notifications@github.com>:

**Comment by chicocode** [comment]
Awesome!
Everthing works fine now! A solution file was absent in the root folder.
Another way is to indicate where is the .csproj or .fsproj when run dotnet restore from a folder that contains .paket folder.

Thanks!
