### ISSUE TITLE
dotnet restore 'Unable to find project to restore' on linux

### ISSUE THREAD

**Issue by TheInnerLight** [fsprojects/Paket#2355]
As discussed with @enricosada 

### Description

I am unable to restore dependencies when calling `dotnet restore` on a paket configured project in linux.

### Repro steps

dotnet sdk 1.0.4 + mono required

1. Pull https://github.com/TheInnerLight/Nomad in ubuntu

2. Run `dotnet restore`

### Expected behavior

The project successfully restores dependencies.

### Actual behavior

`dotnet restore` fails to find a project to restore.

> The command "mono .paket/paket.bootstrapper.exe" exited with 0.
> 
> 1.70s$ dotnet restore
> 
> /usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Unable to find a project to restore! [/home/travis/build/TheInnerLight/Nomad/Nomad.sln]
> 
> The command "dotnet restore" exited with 0.
> 
> 2.21s$ dotnet build
> 
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> /home/travis/build/TheInnerLight/Nomad/src/Nomad/Nomad.netcore.fsproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/home/travis/build/TheInnerLight/Nomad/src/Nomad/Nomad.netcore.fsproj.metaproj'.
> 
> /home/travis/build/TheInnerLight/Nomad/src/Nomad.TestApp/Nomad.TestApp.netcore.fsproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/home/travis/build/TheInnerLight/Nomad/src/Nomad.TestApp/Nomad.TestApp.netcore.fsproj.metaproj'.
> 
> /home/travis/build/TheInnerLight/Nomad/tests/nomad.tests/nomad.tests.fsproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/home/travis/build/TheInnerLight/Nomad/tests/nomad.tests/nomad.tests.fsproj.metaproj'.

**Comment by enricosada** [comment]
I can repro too

On windows works.
In ubuntu (on WLS) doesnt.
I'll try tomorrow in a vm

i am just curious if is CRLF of sln (i'll check)

**Comment by TheInnerLight** [comment]
The sln has only LF (no CR).  I also noticed that my paket.restore.targets files was not the latest version so I tried taking a new version from the paket repo, unfortunately this had no change on the behaviour.

The build log is available via travis: https://travis-ci.org/TheInnerLight/Nomad/builds/234901204?utm_source=github_status&utm_medium=notification

**Comment by TheInnerLight** [comment]
I managed to get this to build by changing the sln to use `/` characters as path separators, e.g.

```
Project("{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}") = "Nomad", "src/Nomad/Nomad.fsproj", "{BEB15B79-7295-473F-91A1-C1120DC3B513}"
EndProject
```
I don't think this should be a requirement though.

When adding a project to a solution with `dotnet sln add` in Linux, the sln is still generated with `\` path separators, e.g.

```
Project("{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}") = "Test", "src\Test\Test.fsproj", "{ACCF6B50-5296-4C58-A8A5-D46E3B6670DE}"
EndProject
```
Here `dotnet restore` works fine without paket installed.

**Comment by forki** [comment]
https://github.com/TheInnerLight/Nomad/pull/3  seems to work

**Comment by TheInnerLight** [comment]
Thanks @forki.  I also managed to get it working by changing the path separator.

I noticed that in linux, `dotnet sln add` generates paths using the windows path separator  convention so I want to do some more experimentation to rule out a paket issue when using `\` notation in the sln.

**Comment by enricosada** [comment]
Yes, path fix for now.

Closing. bug is tracked upstream in https://github.com/Microsoft/msbuild/issues/1957

Workaround is to change slash, like in https://github.com/fsprojects/Paket/commit/36d573db862a5a6cdac716fefbb5764c799581c9

**Comment by Magus069** [comment]
I had the same issue, I managed to remove the warning by simply adding a *.csproj file to the solution.
I used the following line:
`dotnet sln FileName.sln add FileName.csproj`

afterwards the warning wasn't there anymore.

**Comment by Alzemiro** [comment]
If you have another domains in your project try use this command `dotnet sln <your-solution-file>.sln add **/*.csproj`
