### ISSUE TITLE
Change error message when package is defined in 2 groups with different versions.

### ISSUE THREAD

**Issue by wooderz** [fsprojects/Paket#2357]
See screen shot. The fix was to pin the package to a specific version on one side. It would be great if the error message could be made a little more friendly and point to this as a resolution.

![image](https://cloud.githubusercontent.com/assets/4377107/26408773/a044d648-4096-11e7-878e-05f748dc5f71.png)

**Comment by matthid** [comment]
Can you try with latest? This bug should have been fixed.

**Comment by forki** [comment]
what does fixed mean?

**Comment by matthid** [comment]
IIRC this will take the later version and print a warning explaining the situation. At the very least I improved this message (I'm on mobile atm)

**Comment by wooderz** [comment]
I'm on 4.8.6 due to using paket.bootstrapper.exe renamed to paket.exe - shouldn't it get the latest if there's an update?

**Comment by matthid** [comment]
I meant prerelease

**Comment by matthid** [comment]
Future paket will tell you that you should use a single group or (for advanced scenarios) group conditions.

**Comment by wooderz** [comment]
Problem we have is we have an internal nuget server for our own packages. So we have the main group, then our own so we can issue an update command targeting just our own packages when updates are made. 

That's a super useful feature of paket and would be a shame to lose that

**Comment by matthid** [comment]
We have an filtered update mode even within a group?

**Comment by wooderz** [comment]
How do you mean? 

We do:
`paket update group WhenYouMove` 

and it just updates the packages in the WhenYouMove group

**Comment by matthid** [comment]
https://fsprojects.github.io/Paket/paket-update.html
`--filter`

I'd rather request a feature to filter by source (if the above is not enough for you) instead of going through the pain of pinning versions (will be longterm pain).

**Comment by wooderz** [comment]
So we could use --filter WhenYouMove.* and it'll just update the ones that start in our namespace. Yeah that could work

**Comment by matthid** [comment]
I mean feel free to use groups if you want a completely independent resolution. I'm just saying that you are doing stuff by hand which paket should handle for you.

**Comment by wooderz** [comment]
I think that could be the best way forward. Thanks for doing the error message!
