### ISSUE TITLE
Build fails with Duplicate definition of type, exception or module

### ISSUE THREAD

**Issue by zzdavid** [fsprojects/Paket#2366]
Building Paket fails for me. There are a lot of this kind of errors when running build.cmd

     3>C:\Users\dsm\Documents\github\Paket\src\Paket.Core\Versioning\Cache.fs(56,1): error FS0037: Duplicate definition of type, exception or module 'Cache' [C:\Users\dsm\Documents\github\Paket\src\Paket.Core\Paket.Core.fsproj]

Full build log is attached.

[build-log.txt](https://github.com/fsprojects/Paket/files/1031071/build-log.txt)

**Comment by matthid** [comment]
I guess we need F# 4.1 installed.

**Comment by zzdavid** [comment]
Yes, that got it working, thanks!
