### ISSUE TITLE
Paket resolve (used by Fake5) failes if there is no .paket folder

### ISSUE THREAD

**Issue by Alxandr** [fsprojects/Paket#2375]
See https://github.com/fsharp/FAKE/issues/1564 for more information. Creating the `.paket` folder solves it.

Exception: `Source 'https://api.nuget.org/v3/index.json' exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/alxandr/hub/Fable.Ava/.paket'.`

**Comment by matthid** [comment]
I'm closing this as I think this might have been solved by accident with the new `storage: none` option. It should actually work with latest. Please re-test and report back.

**Comment by matthid** [comment]
Apparently this hasn't been fixed after all.
