### ISSUE TITLE
Bootstrapper should cache the GetLatestVersion result at least for some time

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2377]
### Description

When the bootstrapper gets called multiple times in parallel (before any instance could finish its job). Every process tries to call Github and some might get restricted.

### Repro steps

This happens with FAKE 5 and netcore solutions with several projects

### Expected behavior

Bootstrapper works

### Actual behavior

https://ci.appveyor.com/project/SteffenForkmann/fake/build/1.0.3225#L873

```
EXEC : The remote server returned an error : (429) Too Many Requests. (Github - cached) [C:\projects\fake\src\app\Fake.DotNet.Testing.NUnit\Fake.DotNet.Testing.NUnit.fsproj]
C:\projects\fake\.paket\Paket.Restore.targets(17,5): error MSB3073: The command ""C:\projects\fake\.paket\paket.exe" restore --project "C:\projects\fake\src\app\Fake.DotNet.Testing.NUnit\Fake.DotNet.Testing.NUnit.fsproj" --target-framework netstandard1.6" exited with code -1. [C:\projects\fake\src\app\Fake.DotNet.Testing.NUnit\Fake.DotNet.Testing.NUnit.fsproj]
EXEC : The remote server returned an error : (429) Too Many Requests. (Github - cached) [C:\projects\fake\src\app\Fake.DotNet.Testing.XUnit2\Fake.DotNet.Testing.XUnit2.fsproj]
C:\projects\fake\.paket\Paket.Restore.targets(17,5): error MSB3073: The command ""C:\projects\fake\.paket\paket.exe" restore --project "C:\projects\fake\src\app\Fake.DotNet.Testing.XUnit2\Fake.DotNet.Testing.XUnit2.fsproj" --target-framework netstandard1.6" exited with code -1. [C:\projects\fake\src\app\Fake.DotNet.Testing.XUnit2\Fake.DotNet.Testing.XUnit2.fsproj]
```

### Known workarounds

Call the bootstrapper before restoring the solution, like https://github.com/fsharp/FAKE/commit/a2854faa2e21d58276f876957fb9626f398dcbf6

**Comment by vbfox** [comment]
We can avoid that in the boostrapper by locking per-folder during version resolution / download.

I'd also suggest that Paket should stop using github html as a way to convey what's the latest version and replace that with a real API somewhere.

Azure functions with a small DocumentDB for storage can be a good & pretty cheap solution. I can design a prototype if you want.

**Comment by matthid** [comment]
Actually, now I don't think my analysis of above is accurate.
I still see the error from above https://ci.appveyor.com/project/SteffenForkmann/fake/build/1.0.3233#L906 (well maybe a little less often, because some builds succeed now from time to time)
Now I think what's happening is that `paket restore` itself is requesting github here every time. It should probably have some timestamp and timeout where it doesn't look for updates as well.

**Comment by matthid** [comment]
Ok I think the message is from 
https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/Program.cs#L86
and
https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/DownloadStrategies/CacheDownloadStrategy.cs#L12
and
https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/DownloadStrategies/GitHubDownloadStrategy.cs#L21

but really I don't understand why the workaround if not working :/.
If I call the magic mode one time before doing the huge amount of parallel requests it should work IMHO.

I guess I'll add a hidden "trace" mode to the bootstrapper in magic mode, enabled by "PAKET_BOOTSTRAPPER_TRACE" set to "true" and see what it tells me.

**Comment by matthid** [comment]
Ah: https://ci.appveyor.com/project/SteffenForkmann/fake/build/1.0.3237 I guess it it not finding the dependencies file and is trying to search for the latest version...

**Comment by matthid** [comment]
So now we possibly have to bugs:
 - Bootstrapper should find the reqested version from the deps file in that case
 - Bootstrapper should cache the GetLatestVersion result at least for some time?

I'll send a fix for the first one and leave this bug open for the second one.

**Comment by matthid** [comment]
Seems like the second one is by design because somehow the bootstrapper figures out it wants prerelease? But why is that? 

Fix for the first case is https://github.com/fsprojects/Paket/pull/2384

**Comment by vbfox** [comment]
The second one was added by @forki in https://github.com/fsprojects/Paket/commit/d037031738c93413988af41ddfce1baf8efc9cf1 from the time the magic mode feature was merged.

I don't know the exact reason maybe to get prerelease faster in the paket project itself. Even if it's removed the behavior is also available by specifying a max age on the version line

`version prerelease --max-file-age=0`

**Comment by matthid** [comment]
Yes I think opt-out makes more sense, I mean we can lower the caching time when using prerelease by default. But we definitely need to cache some time even for prerelease...

What I'm wondering is why the bootstrapper figured it should use prereleases? Is that related to using a prerelease bootstrapper?

**Comment by vbfox** [comment]
It's currently being forced via app.config: https://github.com/fsprojects/Paket/blob/master/.paket/paket.exe.config

**Comment by matthid** [comment]
Ah thanks, that explains it. thanks!
