### ISSUE TITLE
[5.0.0-beta008] referencing a netstandard1.6 lib from net461 does not work

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2381]
extracted from https://github.com/fsprojects/Paket/issues/2378

---------------

in the future (tooling 2), net461 will support netstandard1.6.

https://docs.microsoft.com/en-us/dotnet/standard/library
![image](https://cloud.githubusercontent.com/assets/4236651/26560789/86e0a85e-44b9-11e7-9e8f-427ad198a3cf.png)

---------------

I tried to do exactly that with paket at the moment, but couldn't get it to run correctly.

# Project 1: NewSDK C# lib targeting ns16

__ns16lib.csproj__

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>

</Project>

```

```C#
using System;
using System.Collections.Generic;

namespace ns16lib
{
    public class Class1
    {
		public static List<int> Get()
		{
			return new List<int>{1, 2, 3};
		}
    }
}
```

do ``dotnet pack``

# Project 2: Old-School C# Console App targeting net461

```
source C:\temp\pakettest3\ns16lib\bin\Debug
source https://api.nuget.org/v3/index.json

framework: net461

nuget ns16lib

```

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = ns16lib.Class1.Get();
        }
    }
}


```

press F5
![image](https://cloud.githubusercontent.com/assets/4236651/26561504/4ee8f054-44bf-11e7-84ab-ea668598024e.png)

[ns16lib.zip](https://github.com/fsprojects/Paket/files/1036619/ns16lib.zip)

[ConsoleApp3.zip](https://github.com/fsprojects/Paket/files/1036621/ConsoleApp3.zip)

------------

There seems to be some magic inside NETStandard.Library.NETFramework:

![image](https://cloud.githubusercontent.com/assets/4236651/26561987/f6d5f340-44c2-11e7-85a0-7a35424a60e9.png)
![image](https://cloud.githubusercontent.com/assets/4236651/26561990/fca3fa42-44c2-11e7-8193-8eb9800c5b5e.png)
![image](https://cloud.githubusercontent.com/assets/4236651/26561993/03942f34-44c3-11e7-999a-5cf5f6f14f66.png)

My guess is that paket generates some bad conditions, so that these props/targets are not correctly included.

**Comment by 0x53A** [comment]
My scenario is:

* nuget with netstandard1.6 lib (created using the new sdk)
* old-sdk project targeting net461 with a packages.config/paket reference to that nuget

I think this is a plausible scenario - it will become more and more common as libraries move to netstandard1.6 and people update their packages.

----------

Is this supposed to work? If yes, what are we doing wrong?

**Comment by matthid** [comment]
how did you pull 'Netstandard.Library.NETFramework'?
By transitive deps on something or explicitely?

**Comment by 0x53A** [comment]
Tested a few different things.

If I just reference ``ns16lib``, then nothing gets pulled in transitively.
But even adding all references explicitly (``ns16lib``, ``Netstandard.Library.NETFramework`` and ``Netstandard.Library``) did not work.

Today I'm tired, will try again tomorrow.

**Comment by matthid** [comment]
will look as soon as I can. But it should add the targets when added explicitely. in new project formats it will just add the targets and props to the obj directory and msbuild should pick it up...

**Comment by 0x53A** [comment]
fixed by https://github.com/fsprojects/Paket/pull/2388

**Comment by matthid** [comment]
What do we do now with this?

**Comment by 0x53A** [comment]
Test a lot what works, and what doesn't?

Then wait for Microsoft to release Tooling2.0?

**Comment by matthid** [comment]
Yep I agree, ok then lets wait for stuff to become stable :)

**Comment by 0x53A** [comment]
for review: https://github.com/fsprojects/Argu/issues/78

I think it is a packaging issue, but not sure.

**Comment by matthid** [comment]
can we close this?

**Comment by 0x53A** [comment]
Sure, we (you) just need to remember to re-add support when microsoft releases 2.0
