### ISSUE TITLE
Conditional sources?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Paket#2401]
When developing a set of components, (e.g.. Vagabond --> MBrace.Core --> MBrace.Azure -> ...), each with their own package, it would be very convenient to be able refer to a "ephemeral" package feed such as an AppVeyor feed in order to access alpha versions of the packages without publishing them to nuget.org

Of course I can add

    source https://ci.appveyor.com/nuget/vagabond-6odcsr0usg1g

but the problem is that I would only want this to be active on my own local machine, or on the appveyor build, but never when building "final" non-alpha versions of packages that get pushed to nuget.

Basically I'm wondering if it could be plausible to have a feature where ``source`` declarations are conditional in some way.  It's not entirely obvious to me whet they would be conditional on - perhaps in this case I would just want a "not golden" or "devmode" flag or something.  And it's no clear how it would be applied, since all the paket.lock etc. is dependenct on this feed, so you have to re-run paket.exe

This is really just thinking out loud but it seems a common situation, and I'm wondering if people have hit this before?  I really fear pushing broken sets of packages to nuget.org that accidentally depend on alpha versions of other packages that aren't available on nuget.org

thanks
don

**Comment by forki** [comment]
Do you know about https://fsprojects.github.io/Paket/local-file.html ?

Am 08.06.2017 19:55 schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment]
No I didn't that will do the trick well enough, thanks!

**Comment by dsyme** [comment]
A couple of questions

- Can you use a nuget feed in the paket.local ?

      nuget Vagabond -> https://ci.appveyor.com/nuget/vagabond-6odcsr0usg1g

- Can you have a paket.local up a few further directories, governing a collection of projects (e.g. in my ``c:\github\dsyme`` directory rather than one in each of ``c:\github\dsyme\Vagabond`` , ``c:\github\dsyme\MBrace.Core``  etc)

- Is the spec of the feed in the paket.local additive to other feeds for the package (selected based on version) or does it completely override them?

**Comment by dsyme** [comment]
(reopen since there are active questions)

**Comment by theimowski** [comment]
> Can you use a nuget feed in the paket.local ?

Haven't tested this scenario. If it doesn't work at the moment, should not be a big deal to add

> Can you have a paket.local up a few further directories, governing a collection of projects (e.g. in my c:\github\dsyme directory rather than one in each of c:\github\dsyme\Vagabond , c:\github\dsyme\MBrace.Core etc)

Nope, that's not implemented, but should be fairly easy

> Is the spec of the feed in the paket.local additive to other feeds for the package (selected based on version) or does it completely override them?

It completely overrides them - the should always be a warning issued when an override is detected.

Also, there can be just a single override for a given nuget

**Comment by dsyme** [comment]
@theimowski What happens if the same repo and build command produces multiple NuGet packages? e.g. see below


```
nuget MBrace.Core -> git https://github.com/mbraceproject/MBrace.Core.git master build: "build.cmd NuGet", Packages: /bin/, OS: windows
nuget MBrace.Flow -> git https://github.com/mbraceproject/MBrace.Core.git master build: "build.cmd NuGet", Packages: /bin/, OS: windows
```

**Comment by dsyme** [comment]
Hmmm struggling to get paket.local to work at all...  I have the file:

![image](https://user-images.githubusercontent.com/7204669/26990612-2073c3a0-4d4f-11e7-96f1-7c49304d018a.png)

and it contains this:

```
nuget Vagabond prerelease -> file:///c:\github\dsyme\Vagabond master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.Core -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.Flow -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.Thespian -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.Runtime -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.CSharp -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.Azure -> file:///c:\github\dsyme\MBrace.Azure master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.Azure.Management -> file:///c:\github\dsyme\MBrace.Azure master build: "build.cmd NuGet", Packages: /bin/
nuget MBrace.AWS -> file:///c:\github\dsyme\MBrace.AWS master build: "build.cmd NuGet", Packages: /bin/
```


but Paket just ignores it.  My paket is up-to-date (not pre-release)

```
C:\GitHub\dsyme\MBrace.StarterKit>.\.paket\paket.bootstrapper.exe
Checking Paket version (downloading latest stable)...
Paket.exe 4.8.7 is up to date.
```
I tried Paket 5.0.0-rc003/ too

**Comment by dsyme** [comment]
@theimowski Any idea what I'm doing wrong? Thanks

**Comment by dsyme** [comment]
@theimowski @forki Ah, I see, ``paket.local`` is used when you run ``paket restore`` but not ``paket update``.  That's not what I had expected - I thought the package versions/resolutions would be influenced by the packages available from the local sources.

**Comment by theimowski** [comment]
Nope, the override thing happens only when running `paket restore` - overrides do not mess with `paket.lock`. I'm working currently to make this work for you case, should have a solution in couple minutes

**Comment by theimowski** [comment]
Ok, so this is what I'm getting when running `paket.restore` having cloned the repos:

```
C:\github\dsyme\MBrace.StarterKit (master)
λ .paket\paket.exe restore
Paket version 4.8.7
Paket failed with:
        Cannot parse line 'nuget Vagabond -> file:///c:\github\dsyme\Vagabond master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.Core -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.Flow -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.Thespian -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.Runtime -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.CSharp -> file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.Azure -> file:///c:\github\dsyme\MBrace.Azure master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.Azure.Management -> file:///c:\github\dsyme\MBrace.Azure master build: "build.cmd NuGet", Packages: /bin/'
        Cannot parse line 'nuget MBrace.AWS -> file:///c:\github\dsyme\MBrace.AWS master build: "build.cmd NuGet", Packages: /bin/'
```

So the format of paket.local lines is incorrect - there's an unwanted space between `build:` keyword and build command, as well as missing `git` keyword before path.
After fixing formatting to following:

```
nuget Vagabond -> git file:///c:\github\dsyme\Vagabond master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Core -> git file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Flow -> git file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Thespian -> git file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Runtime -> git file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.CSharp -> git file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Azure -> git file:///c:\github\dsyme\MBrace.Azure master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Azure.Management -> git file:///c:\github\dsyme\MBrace.Azure master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.AWS -> git file:///c:\github\dsyme\MBrace.AWS master build:"build.cmd NuGet", Packages: /bin/
```

And then running `paket.exe restore`, I get:


```
C:\github\dsyme\MBrace.StarterKit (master)
λ .paket\paket.exe restore
Paket version 4.8.7
paket.local override: nuget Vagabond group Main -> file:///c:\github\dsyme\Vagabond master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.Core group Main -> file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.Flow group Main -> file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.Thespian group Main -> file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.Runtime group Main -> file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.CSharp group Main -> file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.Azure group Main -> file:///c:\github\dsyme\MBrace.Azure master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.Azure.Management group Main -> file:///c:\github\dsyme\MBrace.Azure master build:"build.cmd NuGet", Packages: /bin/
paket.local override: nuget MBrace.AWS group Main -> file:///c:\github\dsyme\MBrace.AWS master build:"build.cmd NuGet", Packages: /bin/
Cloning file:///c:\github\dsyme\MBrace.Core to C:\Users\BRE44821\.paket\git\db\MBrace.Core
Cloning file:///c:\github\dsyme\MBrace.Core to C:\Users\BRE44821\.paket\git\db\MBrace.Core
Cloning file:///c:\github\dsyme\MBrace.AWS to C:\Users\BRE44821\.paket\git\db\MBrace.AWS
Cloning file:///c:\github\dsyme\MBrace.Core to C:\Users\BRE44821\.paket\git\db\MBrace.Core
Cloning file:///c:\github\dsyme\MBrace.Core to C:\Users\BRE44821\.paket\git\db\MBrace.Core
Cloning file:///c:\github\dsyme\MBrace.Azure to C:\Users\BRE44821\.paket\git\db\MBrace.Azure
Cloning file:///c:\github\dsyme\MBrace.Core to C:\Users\BRE44821\.paket\git\db\MBrace.Core
Cloning file:///c:\github\dsyme\MBrace.Azure to C:\Users\BRE44821\.paket\git\db\MBrace.Azure
Cloning file:///c:\github\dsyme\Vagabond to C:\Users\BRE44821\.paket\git\db\Vagabond
Checking for uncommitted changes in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.AWS
Checking for commits made in detached HEAD state in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.AWS
Setting C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.AWS to c0ce3f70505810d7e96ccf245b9f03e550215d47
Checking for uncommitted changes in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.Core
Checking for uncommitted changes in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.Azure
Checking for commits made in detached HEAD state in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.Core
Checking for commits made in detached HEAD state in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.Azure
Setting C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.Core to 581ea64e3b17276ad0f969430b618dc5f6fa56bf
Setting C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.Azure to d0f2c0d264e9cc90925ab07c0bb913cb4e390f12
Checking for uncommitted changes in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\Vagabond
Checking for commits made in detached HEAD state in C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\Vagabond
Setting C:\github\dsyme\MBrace.StarterKit\paket-files\localfilesystem\Vagabond to 9b5fcfada60e6330123b37f2765ffc5f34a91ad3
Paket failed with:
        Fetching the git cache at C:\Users\BRE44821\.paket\git\db\MBrace.Core failed.
Message: Could not run "git clone --mirror "file:///c:\github\dsyme\MBrace.Core" "C:\Users\BRE44821\.paket\git\db\MBrace.Core"".
Error:
fatal: destination path 'C:\Users\BRE44821\.paket\git\db\MBrace.Core' already exists and is not an empty directory.
```

So it seems that currently there's a limitation in how paket.local works in that there can be a single git override from a given directory.
A workaround can be specifying the git override just once for a single path, and then using `source` override, like below:

```
nuget Vagabond -> git file:///c:\github\dsyme\Vagabond master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Core -> git file:///c:\github\dsyme\MBrace.Core master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Flow -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.Thespian -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.Runtime -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.CSharp -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.Azure -> git file:///c:\github\dsyme\MBrace.Azure master build:"build.cmd NuGet", Packages: /bin/
nuget MBrace.Azure.Management -> source c:\github\dsyme\MBrace.Azure\bin
nuget MBrace.AWS -> git file:///c:\github\dsyme\MBrace.AWS master build:"build.cmd NuGet", Packages: /bin/
```

Please try this one and let me know if it works for you.

**Comment by dsyme** [comment]
@theimowski @forki An alternative would be this in paket.dependencies:

```
git file:///c:\github\dsyme\Vagabond master build: "build.cmd NuGet", Packages: /bin/
git file:///c:\github\dsyme\MBrace.Core master build: "build.cmd NuGet", Packages: /bin/
git file:///c:\github\dsyme\MBrace.Azure master build: "build.cmd NuGet", Packages: /bin/
git file:///c:\github\dsyme\MBrace.AWS master build: "build.cmd NuGet", Packages: /bin/
```

However this does clones and does the build in ``paket-files\localfilesystem`` e.g.
```
Running "C:\GitHub\dsyme\MBrace.StarterKit\paket-files\localfilesystem\Vagabond\build.cmd NuGet"
Running "C:\GitHub\dsyme\MBrace.StarterKit\paket-files\localfilesystem\MBrace.Core\build.cmd NuGet"
```

This loses sharing between different projects in the DAG.  It feels like we want a git source option in paket.dependencies to build shared components (e.g. Vagabind and MBrace.Core in this example) in-place and to ensure commit-ID consistency for all instances of that component  (effectively the commit ID becomes the version ID for that component)

**Comment by theimowski** [comment]
That's right - I forgot about the fact paket does clone the repo to `paket-files`, my example from previous comment will thus not work.

How about using the source override for all components, i.e.

```
nuget Vagabond -> source c:\github\dsyme\Vagabond\bin
nuget MBrace.Core -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.Flow -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.Thespian -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.Runtime -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.CSharp -> source c:\github\dsyme\MBrace.Core\bin
nuget MBrace.Azure -> source c:\github\dsyme\MBrace.Azure\bin
nuget MBrace.Azure.Management -> source c:\github\dsyme\MBrace.Azure\bin
nuget MBrace.AWS -> source c:\github\dsyme\MBrace.AWS\bin
```

and before running `paket restore` in StarterKit, you'd have to build locally all the subcomponents?

**Comment by dsyme** [comment]
> and before running paket restore in StarterKit, you'd have to build locally all the subcomponents?

@theimowski I'll try that to see if it works.   It feels wrong though -  the "update" has been run with respect to very different packages and dependency chains. These new sources could have totally different dependencies.  Also testing a one line fix in ``Vagabond`` would take quite a lot of fiddling around with paket update, doing builds, check to see if the new packages have been picked up and are consistent etc., 

It feels like to achieve one good (reliable builds) we sacrifice another (rapid iterative development for a graph of components).  

> ... paket does clone the repo to paket-files

@theimowski @forki was wondering if there is a  feature lurking where replacing the branch ID ``master`` with ``.`` indicates that the packages should be built in place

```
git file:///c:\github\dsyme\Vagabond . build: "build.cmd NuGet", Packages: /bin/
git file:///c:\github\dsyme\MBrace.Core . build: "build.cmd NuGet", Packages: /bin/
git file:///c:\github\dsyme\MBrace.Azure . build: "build.cmd NuGet", Packages: /bin/
git file:///c:\github\dsyme\MBrace.AWS . build: "build.cmd NuGet", Packages: /bin/
```

though it's quite hard to think through how this would actually work in practice

**Comment by matthid** [comment]
@dsyme `paket.local` was designed for local fast development when you know what you are doing. It shouldn't have an impact on `paket update` to not "accidentally" commit some intermediate dev packages which might not be available for others. Build Servers will than check if everything is still sane.

To be honest it's still unclear to me what you actually want.

> but the problem is that I would only want this to be active on my own local machine, or on the appveyor build

local machine is definitely `paket.local` but appveyor is kind of more tricky I guess.

> Basically I'm wondering if it could be plausible to have a feature where source declarations are conditional in some way.

There is a feature to make a complete paket group conditional, it's not that well documented though (and is not working jet for new SDK):

```
group g1
condition: COND1

group g2
condition: COND2
```

You can then use one set or the other depending on which msbuild variable you set to "true".

**Comment by dsyme** [comment]
> it's still unclear to me what you actually want.

The broad scenario is more or less clear to me, though the mechanisms to support it aren't.

1. Assume a component D made from 5 components in a DAG - call these A, B1, B2, C, D - with ``D --> C --> (B1,B2) --> A dependencies``.  These come from separate github projects and each projet builds one or more packages

2. Assume we have a local clone of each these projects. If you like we can assume the clones of A, B1, B2 and C are in ``D/paket-files/github.com/A/...`` (like existing github sources).  However these clones should **not** be nested (no ``D/paket-files/github.com/C/paket-files/github.com/B1/paket-files/github.com/A/...``) and there should only be **one** clone of each repo.  Each clone should be on a branch (not in detached-head state) to allow work on that.

3. I want to develop, build and update across this graph so that the freshly built packages and any extra implied dependencies are correctly built, picked up and consistent across the components.   

When I do a "Update and Build" across the whole DAG I would expect

2. build A  
3. paket update on B1
2. build B1
3. paket update on B2
2. build B2
3. paket update on C
2. build C
3. paket update on D
2. build D

* When in development mode, each operation happens "in place" using the HEAD commit (or even better using uncommitted changes). Each paket update should use the previous build(s) as sources

* Once the changes are confirmed, you commit, publish, tag and everything is re-checked on CI

* This feels like some kind of fantasy, but the alternative is to collapse everything into one github repo and one solution - an Everything.sln in Visual Studio.  That's very appealing of course!

**Comment by theimowski** [comment]
This kind of "cascade" behavior IMO would make things very complicated, and that's what we tried to avoid when introducing paket.local

I think there's one important detail that might not seem obvious at first:
Even if you have this kind of dependency chain, you can still test locally changes made in A component from D component without rebuilding components between.
In practice this means:
* apply change in A
* manually trigger the build of A
* make sure there's an override for A in D 
* restore packages (with override) and build D
* run D with the changes applied in A

And it seems this workflow could be easy enough given one is using floating version dependencies with default Paket resolution strategy, which is take the highest version matching.

**Comment by dsyme** [comment]
I'll close this.  I think the problem is very real and fundamental in the long run - in the long run we have to have mechanisms/practices in place where we can push a change to a base package through a whole graph of other packages relatively easily, all on a local machine, with no expansion of the DAG and with full paket dependency management and consistency checking.

But I don't have any specific mechanism to propose just yet - I'll keep thinking it over.
