### ISSUE TITLE
Many projects failed to load in Rider

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#2406]
```
Project 'Paket' load failed: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.  E:\github\Paket\src\Paket\Paket.fsproj at (52:3)
```
and son on.

![image](https://user-images.githubusercontent.com/873919/27001338-5bbf428c-4dd0-11e7-9b7a-d65d0bc1b8ab.png)

**Comment by forki** [comment]
Is that paket or rider issue?

Am 10.06.2017 10:31 vorm. schrieb "Vasily Kirichenko" <
notifications@github.com>:

**Comment by matthid** [comment]
I'd say its a rider issue. They are not handle to figure out the `FSharpTargetsPath` variable which is defined in the first line with `<Import Project="..\..\packages\FSharp.Compiler.Tools\build\FSharp.Compiler.Tools.props" Condition="Exists('..\..\packages\FSharp.Compiler.Tools\build\FSharp.Compiler.Tools.props')" Label="Paket" />`

It will probably take them quite a while to understand all the msbuild quirks possible (not even VS understands them all)

**Comment by matthid** [comment]
To clarify why I closed this so fast:
 - This hole msbuild stuff is really frustrating, using the `FSharp.Compiler.Tools` package is IMHO a good way forward and a way to minimize frustration in the future (hopefully)
 - So it might hurt a bit now
 - I don't want to remove that at the moment just because Rider doesn't understand it. Maybe we need to reconsider this at some point.

Hope this makes sense.

**Comment by vasily-kirichenko** [comment]
Thanks, I create an issue https://youtrack.jetbrains.com/issue/RIDER-7028

**Comment by 0x53A** [comment]
@vasily-kirichenko please try a manual paket restore and then reopen the Solution.

**Comment by 0x53A** [comment]
Afaik the issue is that the package is not yet restored, so the props file is not imported and the property FSharpTargetsPath is not set.

This could be improved by making the import conditional on the file existing.

**Comment by matthid** [comment]
@0x53A But then you get "Target Build/Rebuild/Clean/... doesn't exist" later when building the project. Ah crap

**Comment by 0x53A** [comment]
https://github.com/fsprojects/Paket/issues/1869

@matthid

**Comment by matthid** [comment]
@0x53A thanks added a comment there, but the `FSharpTargetsPath` line (which this issue is about) is not actually generated by paket.

**Comment by matthid** [comment]
@vasily-kirichenko If you can confirm that it works after restoring, we might want to re-open this to check if we can improve that experience thoughout IDEs ...

**Comment by vasily-kirichenko** [comment]
nuget.org is still down from the place where I am.
