### ISSUE TITLE
[5.0.0-rc005] Paket fails to update project file when framework restriction is used

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#2414]
Attached repro contains Hello World project targeting .NET Framework 4.6.1. Project references exactly one package Microsoft.CodeAnalysis. 
Paket.dependencies file contains `nuget Microsoft.CodeAnalysis framework: net46`
"paket install" command does not change project file whatsoever, which is very much unexpected - it should. If I remove `framework: net46` filter from paket.dependencies, then project file IS updated, but because the package targets many different profiles ALL of them get injected to the project file and it becomes huge. Please investigate!

[PaketRepro.zip](https://github.com/fsprojects/Paket/files/1066610/PaketRepro.zip)

**Comment by matthid** [comment]
```
framework: net461
content: none
redirects: off

source https://www.nuget.org/api/v2/

nuget Microsoft.CodeAnalysis framework: net46
```

`framework: ` on a package will further restrict the package (in addition to the global restrictions of the group). But `(==net461) && (==net46)` is the empty set. This means the package will never be installed.

This is actually explained in the documentation with a warning, but as the last published version is a stable one (paket 4) the docs do not contain this warning at the moment.

**Comment by konste** [comment]
So this is a change of behavior from Paket 4, because for Paket 4 it does work, right?

**Comment by matthid** [comment]
Paket 4 doesn't have a well defined behavior for this at all.

**Comment by konste** [comment]
Ok, makes sense. Closing.
