### ISSUE TITLE
[5.0.0-rc005] Paket pack ignores <ReferenceOutputAssembly>false attribute

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#2415]
When "paket pack" scans project references some of them may have this attribute `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>`
which means project reference is only to enforce the build order, but no binary from the referenced project should be pulled in. It looks like Paket ignores this attribute and cannot finish pack command because some projects referenced with it may not have output at all, but Paket still looks for the DLL with the name of the referenced project, cannot find it and blows up. 
Here is the error and call stack:
`Paket failed with:
        Could not find source file C:\$\Development\Databases\MigrationWiz_Watermark\..\bin\MigrationWiz_Watermark.dll
StackTrace:
     at Paket.NupkgWriter.Write@328.Invoke(String message)
   at Paket.NupkgWriter.Write(CompleteCoreInfo core, OptionalPackagingInfo optional, String workingDir, String outputDir)
   at Paket.PackageProcess.Pack@243-4.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Paket.PackageProcess.Pack[a](String workingDir, DependenciesFile dependenciesFile, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 buildPlatform, FSharpOption`1 version, IEnumerable`1 specificVersions, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile, FSharpOption`1 excludedTemplates, Boolean lockDependencies, Boolean minimumFromLockFile, Boolean pinProjectReferences, Boolean symbols, Boolean includeReferencedProjects, FSharpOption`1 projectUrl)
   at Paket.Program.main@473-22.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
   at Paket.Program.main$cont@448(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
   at Paket.Program.main()`

It seems that the best thing to do would be NOT to follow project references with this attribute at all.

**Comment by forki** [comment]
Happy to implement this. Can you please upload a zip with a repro?

**Comment by konste** [comment]
Absolutely! I will work on a small, but comprehensive repro today. Should be ready in a few hours.

**Comment by konste** [comment]
[PaketPackRepro.zip](https://github.com/fsprojects/Paket/files/1068740/PaketPackRepro.zip)
@forki Here is your repro "3 in 1" :-) It shows three negative cases when Paket does extra work, which is unnecessary and often harmful. All three cases are not artificial - I have all of them in my actual project.

Repro contains five projects - two positive and three negative:
1. PaketPackRepro - root EXE project, the only one with paket.template file.
2. RegularDependency - DLL dependency project which Paket handles right.
3. DontReferenceBinary - this project is referenced with <ReferenceOutputAssembly>false attribute. Paket should not even try to read it, but it does and includes project output to NuGet package, which is wrong.
4. DatabaseProject - Paket does not know how to handle *.sqlproj, so it should not even try to read it, but it still does and looks for the DLL output which for DB projects is very much optional.
5. IrrelevantProject - this project does not have paket.template and is not referenced by any other project, but Paket still tries to read it for no good reason and chokes on it if the file is malformed bad enough. 

To get a repro you build the solution for Release and then run 
`paket pack output NuGet include-referenced-projects`

I appreciate your attention! Let me know if there is anything else I can do.

**Comment by forki** [comment]
sorry can't build it. Can you please upload including release binaries?

**Comment by konste** [comment]
One min!

**Comment by konste** [comment]
I wonder why you cannot build it. Probably because you don't have SQL project support installed? That would support my point - Paket should not need projects 3, 4 and 5 to be buildable, should not need their binaries and should not even try to read their project files. As a result of the root project file reading it should only look for RegularDependency project and nothing else.

**Comment by forki** [comment]
Yes that's one reason. Please still send it ;-)

**Comment by forki** [comment]
Ah you did. Never mind

**Comment by forki** [comment]
please retry with rc007

**Comment by konste** [comment]
Trying...

**Comment by konste** [comment]
[PaketPackRepro3.zip](https://github.com/fsprojects/Paket/files/1069119/PaketPackRepro3.zip)
I have updated the repro to show that Database project indeed may not have any DLL output, but Paket rx007 is still looking for it and errors out because cannot find it.

**Comment by konste** [comment]
From what I see - IrrelevantProject is not read in anymore, which is a good step forward. But DontReferenceBinary project and DatabaseProject are still read in, while they should be skipped.

**Comment by forki** [comment]
008 will be out in a minute. Calling it a day...

**Comment by konste** [comment]
Darn, you work fast...

**Comment by forki** [comment]
lol. I broke crazy amount of unit tests. so no release today. will fix tomorrow morning, sorry

**Comment by konste** [comment]
Great! I'm looking forward to it!

**Comment by forki** [comment]
Please retry

**Comment by konste** [comment]
May I have a binary? Will be able to test in one hour.

**Comment by konste** [comment]
By the way, how do I build Paket to get single EXE? I understand it uses Mono.Cecil, but I don't see command which produces that single EXE.

**Comment by forki** [comment]
I released it. Why do you need to build?


Am 13.06.2017 20:19 schrieb "Konstantin Erman" <notifications@github.com>:

**Comment by konste** [comment]
I have not noticed it was released, so I rebuilt it. Anyway, there are a couple of shortcomings to address.

**Comment by konste** [comment]
While we are at it, I noticed that Paket pack only includes binaries in the package, but any other files produced by the project (config file, resources, etc.) are not included. Is it by design? Is there a way to include everything the project produces in the bin folder to the package?

**Comment by forki** [comment]
you can add more files with explicit includes

2017-06-13 21:32 GMT+02:00 Konstantin Erman <notifications@github.com>:

**Comment by konste** [comment]
See, I generate paket.template in each project folder in order to run pack once from the root and have everything NuGet packaged with cross-references. Crafting each paket.template manually is not an option. I'm looking for a way to pack everything without specifying it individually.

**Comment by forki** [comment]
Then you would probably need to contribute this as a new feature (create a
feature request and promot it so that someone implements it).
Currently AFAIK we just pack the primary output.

2017-06-13 21:39 GMT+02:00 Konstantin Erman <notifications@github.com>:

**Comment by konste** [comment]
I'm trying to grasp how existing feature work. So by default it grabs primary project output, ok. Now if I add this `
files
	bin\Release ==> .\`
to template file, it takes everything but stops resolving binaries as dependencies. Can I have both at the same time?

Also it is a little weird that bin\Release must be specified explicitly. Isn't there any token for the current configuration to use instead of "Release" string?

**Comment by forki** [comment]
can we discuss this in separate issue? can we close this original issue?

**Comment by konste** [comment]
YES, original issue is verified resolved. Closing.
