### ISSUE TITLE
[A long time ago in a galaxy far, far away] Keep an eye on MSBuild SdkResolvers

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2418]
MSBuild will add a package-based SDK resolving mechanism.

MSBuild spec: https://github.com/Microsoft/msbuild/issues/1493
NuGet work item: https://github.com/NuGet/Home/issues/5220

There is nothing to do at the moment - but as soon as NuGet actually implements this stuff, we should also start so we don't hang behind.

From the empty checklists in both issues, I would expect this to land in 16.0 maybe.

The important question is how the resolving works when we don't control the host (VS or Rider, or VS Code, ...).
Can we pass-in our paket resolver, or will VS always hardcoded use the NuGet resolver?

**Comment by enricosada** [comment]
Closing.

Work for .net core sdk is tracked in https://github.com/fsprojects/Paket/issues/2875
