### ISSUE TITLE
Paket can pick a wrong package if source is local folder

### ISSUE THREAD

**Issue by lexarchik** [fsprojects/Paket#2419]
### Description

When source set to folder (local or network share) paket can pick a wrong package when perform "install" command

### Repro steps

[repro.zip](https://github.com/fsprojects/Paket/files/1072198/repro.zip)

Test setup In attached archive:
testPackage folder contains just a paket.template file for creating a test library
testSolution trying to consume created library (paket dependencies entry: `nuget testlib 1.2.3`)

Repro steps (in a attached setup):
1. go to `testPackage` folder
2. call `paket pack output ..\nuget version 1.2.3-alpha`
3. go to `testSolution` folder
4. call `paket install`

### Expected behavior

"Can't find package" error

### Actual behavior

paket create a paket.lock file with line `testlib (1.2.3)` and copy `testlib.1.2.3-alpha.nupkg` to packages folder (and you can't see it unless browse a packages folder)

### Known workarounds

using nuget server instead of folder
using something like `>= 1.2.3 <= 1.2.3` version constraint

### Other cases

If folder contains two versions of package: 0.1.2.0 and 1.2.0.0 and dependency file line like `nuget <...> 1.2` than paket pick package with version 0.1.2.0.

Repro steps (in a attached setup):
1. go to `testPackage`
2. call `paket pack output ..\nuget version 0.1.2.0`
3. call `paket pack output ..\nuget version 1.2.0.0`
4. go to `testSolution` folder
5. add `nuget testlib 1.2` to paket.dependencies file
6. call `paket install`

Expected: package `testlib 1.2.0.0` in packages folder
Actual: package `testlib 0.1.2.0` in packages folder
Workarounds: write full version in `paket.dependencies` file (1.2.0)

---------------------

I found code in `C:\sources\github\Paket\src\Paket.Core\Dependencies\NuGetLocal.fs` file, function `findLocalPackage`:

```fsharp
    let v3 =
        Directory.EnumerateFiles(directory,"*.nupkg",SearchOption.AllDirectories)
        |> Seq.map (fun x -> FileInfo(x))
        |> Seq.filter (fun fi -> String.containsIgnoreCase (packageName.CompareString)  fi.Name)
        |> Seq.filter (fun fi -> fi.Name.Contains(normalizedVersion) || fi.Name.Contains(version.ToString()))
        |> Seq.tryHead
```
Is there valid cases with arbitrary .nupkg file name format? 
Maybe paket should just stick to `<id>.<version>.nupgk` name format?

**Comment by forki** [comment]
Ok this is clearly a bug at that location. 
Since you already found it, are you interested in fixing it and sending a pull request? 
Basically we need to check that the file ends with version + nupkg instead of the contains version check. 

Regarding your question: yes we need to go through some hoops here since the package name is case insensitive. So we might have packackexzy in dependencies file while the file is called PackageXYZ.1.0.1.nupkg

**Comment by lexarchik** [comment]
If just check `endwith version.nupkg` paket will "find" file like `package.1.2.3.nupkg` if user write `nuget package 2.3` in dependencies file.  (plus - case with 0.1.2.0/1.2.0.0: version 1.2 after normalization will become 1.2.0 and will pass "endwith".
And if package id end with number it can create some trouble.

Maybe after initial filtration with `contains ignorecase` try to read nuspec from filtered files?
Such check may be omitted if filename excactly in `id.version.nupkg` or `id.normalizedVersion.nupkg` format.

**Comment by forki** [comment]
I think if you take the filename and lowercase it then it should match lowercase [package].[version].nupkg

**Comment by lexarchik** [comment]
Case sensitivity is not the only problem here. I can see now that "contains" here for some sort of "version normalization" — `package.name.1.0.0.0` can be answer for user's input `nuget package.name 1.0`.
For 100% accuracy paket must read .nuspec in package file, parse `<version>` and compare version, provided by user with it as two SemVerInfo instance , but it cat be too slow (especially in case of network share).

So, i see two options here: 
1. Do fancy file name analysys, something like 
-- split name with first occurrence of dot followed by number, 
-- take first part as package name (lowercase it or whatever), 
-- take rest of the string as version string, 
-- parse it to SemVerInfo and than compare result with user input
In that case package with name ends with "dot number" will be out of support:
From file name only you can't tell `package.1.2.3.0` is "package version 1.2.3" or "package.1 version 2.3.0".

2. As i mentions in previous comment paket can check .nuspec file from package files filtered by some "loose" condition like `contains packageid && (contains version || contains normalizedVersion)`.
It can be slow in some cases i think.

**Comment by forki** [comment]
option 1 sounds good to me

2017-06-14 9:07 GMT+02:00 lexarchik <notifications@github.com>:
