### ISSUE TITLE
Generate binding redirects for test projects

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#2438]
I don't know if this makes any sense as my knowledge on this matter is `null` but here goes:
Add app.config with redirects if a dll project references xunit or nuint.

**Comment by forki** [comment]
There is a parameter --crearenewbindingfiles

**Comment by JohanLarsson** [comment]
It does not generate app.configs for dll projects from what I can tell.

**Comment by forki** [comment]
It should if you add the parameter.

**Comment by JohanLarsson** [comment]
Ok, I'm probably dumbing something, closing this.
