### ISSUE TITLE
Paket should prefer net40-full over net40-client

### ISSUE THREAD

**Issue by BlythMeister** [fsprojects/Paket#2444]
### Description

We are using log4net version 2.0.3 (yes...this is old...we know!)
We target all projects to .net 4.5 (again, old....we know!)
With paket 4, we got log4net net40-full
We now get log4net net40-client being referenced.
This is odd, as the target framework is v4.5 not a client profile version.

### Repro steps

1. Create project targeting net 4.5
2. Add log4net 2.0.3 as dependecy
3. Set frameworks in paket.dependencies to net45 only
4. run paket install with 4.x
5. run paket install with 5.x

### Expected behavior

No change to the version of log4net being used

### Actual behavior

Log4net changes from full to client

### Known workarounds

Do not upgrade to paket 5.x....

**Comment by matthid** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/deployment/client-profile
Client profile should no longer exist starting with 4.5

Can you post the diff paket is doing on your project-file you feel is suspicious?

**Comment by BlythMeister** [comment]
![image](https://user-images.githubusercontent.com/1046836/27277437-25de8350-54d6-11e7-971a-33181fb815ac.png)

log4net 2.0.3 does not have a net45 version, so uses the net40 version.
it used to use the net40-full
but now uses net40-client
