### ISSUE TITLE
Paket pack skips files

### ISSUE THREAD

**Issue by nikoudel** [fsprojects/Paket#2445]
### Description

Starting from 5.0.0-rc009 paket skips duplicate files from the package being created.

### Repro steps

1. Create a Test.template file like this:

```
type file
id Paket.Test
version 1.0.0
description Paket Test
authors NK
files
    File1.txt ==> tools\Dir1
    File1.txt ==> tools\Dir2
```
2. Run `.\paket.exe pack output . templatefile .\Test.template`

### Expected behavior

The resulting package should contain both directories with File1.txt in each of them.
A real-life scenario is when a package contains multiple applications sharing some common libraries.

### Actual behavior

The resulting package only contains Dir1.

![image](https://user-images.githubusercontent.com/1636683/27292849-4c49d00c-551d-11e7-9907-26310eec1436.png)

### Known workarounds

None.

**Comment by forki** [comment]
I tried to fix it in 5.1.2 but @konste you need to test as well since the relatred bug I fixed for you introduced this issue. So my fix was wrong (tbf it was a shot in the dark) and I'm not sure if now everything is well.

**Comment by forki** [comment]
5.1.3 already underway with yet another fix

**Comment by konste** [comment]
I will test when 5.1.3 is out.

**Comment by forki** [comment]
we're already on 5.1.4

2017-06-19 19:14 GMT+02:00 Konstantin Erman <notifications@github.com>:

**Comment by konste** [comment]
Gosh... you are too fast for me! Ok, will test now.

**Comment by konste** [comment]
[PaketPackRepro3.zip](https://github.com/fsprojects/Paket/files/1085801/PaketPackRepro3.zip)
Attached repro shows that simple `bin\Release ==> Tools\` causes EXE and PDB duplication (in the same folder!). At the same time adding ` !bin\Release\*.exe` causes both copies of EXE to disappear. 
Before jumping on fixing it we need to spend a little time designing what the desired behavior should be and how to make it predictable. Most confusion is coming from the fact that list of files to copy is coming from two sources - dependencies Paket found and explicit list in `files` section. But negative clauses in the files section affect both sources. Let me think for a few minutes...

**Comment by forki** [comment]
That's what I feared. The problem is that for some reason we can't detect that the target is the same. We can definitely detect that the source is the same. But that causes trouble

**Comment by konste** [comment]
It almost feels like two sources of files should be independent. First source - dependencies and primary output of the current project is one thing - it should go to the output regardless. Files section should work within itself - it adds some files, then may be exclude some files, but exclusion should only affect what it added! 
This way primary output will always go where it belongs and if somebody (like me) wants to take everything else he can add `bin\Release ==> Tools\` and `!bin\Release\*.exe` to add everything but EXE.

**Comment by forki** [comment]
@konste in any case we are not allowed to add two files into same folder inside zip. but that is what is happening. trying  to fix it

**Comment by konste** [comment]
It may sound drastic, but how about we change the logic of taking primary output only to taking everything   in the output folder?

**Comment by forki** [comment]
doesn't fix the root cause here. maybe it would fix your issue ;-)

**Comment by konste** [comment]
For class libraries it would not change anything - they only have DLL and PDB in the output folder. And for other types of projects it really makes sense to take everything as they probably cannot run without the rest of the files anyway.

**Comment by konste** [comment]
The problem with the "files" section is that there is no way to tell which part of the project output is primary output and dependencies and which is everything else. It is impossible to author "files" section properly without knowledge what is already included by default. So the algorithm looks like this:
1. Calculate the copy list from primary output and dependencies;
2. Calculate second copy list from the "files" section;
3. Merge the lists removing duplicates comparing **target path**!

This way whatever curious user writes to the "files" section he or she would only get single instance of all files in each ZIP folder.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/27298846-8ad10f36-552a-11e7-9970-6ce7d9eed4c3.png)

see the issue is casing as I expected. `Tools` vs. `tools`.

so it can't dedupe it.

**Comment by konste** [comment]
Make comparison case insensitive - what's the problem?

**Comment by forki** [comment]
other OSes ;-) but yes I guess we need to do that for win.

**Comment by forki** [comment]
ok. so I think both are resolved now
