### ISSUE TITLE
Paket pack doesn't properly parse OutDir when you use $(Targetframework)

### ISSUE THREAD

**Issue by TOTBWF** [fsprojects/Paket#2450]
### Description

When using `TargetFrameworks`, the default value for OutDir is `./bin/$(Configuration)/$(TargetFramework)`. When packaging, paket will look for the requisite .dlls in `./bin/Release/<Dll Name>` instead of `./bin/Release/<Target Framework>/<Dll Name>`
### Repro steps

1. Create a .fsproj file that uses `<TargetFrameworks>` and set `<OutDir>` to `./bin/$(Configuration)/$(TargetFramework)/`

2. Run `paket pack`

### Expected behavior

Paket properly creates a package

### Actual behavior

Paket fails with 
```
Paket failed with:
-> FileNotFoundException: Could not find file "<Path to Project>/bin/Release/<ProjectName>.dll".
```
### Known workarounds

None

**Comment by batzen** [comment]
@forki You think this is related to my SpecificVersion PR?

**Comment by forki** [comment]
It's using the feature you added, isn't it?

**Comment by forki** [comment]
@TOTBWF Can we please get a zip with everything already built so that we only need to call Pack to get the error? Thx

**Comment by TOTBWF** [comment]
Here is the most pared down example I could make
[Example.zip](https://github.com/fsprojects/Paket/files/1089196/Example.zip)

**Comment by forki** [comment]
I think I wanted to cc @bhugot

**Comment by bhugot** [comment]
I knew this problem before I did my PR. It s a problem with type project template and the csproj parsing. I will try to look at it when I have a bit of time

**Comment by bhugot** [comment]
Hi guys I m trying to fix it. I found a fix for <TargetFramework> but for <TargetFrameworks> as paket is not working for multiple Framework it's alot of change.
