### ISSUE TITLE
Paket init in "magic" mode deletes paket.exe

### ISSUE THREAD

**Issue by rmunn** [fsprojects/Paket#2451]
### Description

When you set up the Paket bootstrapper to run in "[Magic mode](https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode)" and then run `paket init`, it deletes the `paket.exe` file.

### Repro steps

1. On Linux, create an empty folder to represent a brand-new project: `mkdir $HOME/bugrepro`
2. `mkdir $HOME/bugrepro/.paket`
3. Download the [Paket bootstrapper](https://github.com/fsprojects/Paket/releases/download/5.1.7/paket.bootstrapper.exe) and put it in `$HOME/bugrepro/.paket/paket.exe`
4. Run `mono $HOME/bugrepro/.paket/paket.exe init`
5. Result: the `paket.exe` file disappears from `$HOME/bugrepro/.paket/` and you can't run any further Paket commands!
6. The only thing remaining in the `.paket/` folder after these steps is the `paket.targets` file.

### Expected behavior

The `paket.exe` file stays where the user put it.

### Actual behavior

The `paket.exe` file disappears.

### Known workarounds

After `paket.exe` disappears, if you look in the `/tmp` folder, you can find `paket_(hash).exe` and copy that into your `.paket` folder as `paket.exe`. But an F# beginner won't know to look there.

### System information

OS: Linux Mint 18.1 Serena (based on Ubuntu 16.04 Xenial)
Paket version: 5.1.7

**Comment by forki** [comment]
Marked as up-for-grabs
