### ISSUE TITLE
"Could not find AppDataFolder, try to set the APPDATA environment variable"

### ISSUE THREAD

**Issue by dbruning** [fsprojects/Paket#2457]
### Description

When I run `paket restore -v`, I get warnings:

```
Could not find AppDataFolder, try to set the APPDATA environment variable. Using '<appdir>\.paket' instead.
Could not detect a root for our (user specific) temporary files. Try to set the 'HOME' or 'LocalAppData' environment variable!. Using '<appdir>\.paket' instead.
Could not find LocalApplicationData folder, try to set the 'LocalAppData' environment variable. Using '<appdir>\.paket' instead
```

I'm not an F# coder but had a quick look at the code; Paket.Core/Common/Constants.fs has some string constants for special folder names that don't work for me in Powershell, and I wonder if they're correct.
That file has these constants:

ApplicationData -> "APPDATA"
UserProfile -> "USERPOFILE"
LocalApplicationData -> "LocalAppData"
ProgramFiles -> "PROGRAMFILES"
ProgramFilesX86 -> "PROGRAMFILES(X86)"

... when I try them using the Powershell command: 
[Environment]::GetFolderPath("<string>")
... they give the following results:

ApplicationData -> "APPDATA" - FAILS
UserProfile -> "USERPOFILE" - FAILS (typo?)
LocalApplicationData -> "LocalAppData" - FAILS
ProgramFiles -> "PROGRAMFILES" - WORKS
ProgramFilesX86 -> "PROGRAMFILES(X86)" - FAILS

If they are in fact meant to be the same strings that I'm using in the Powershell command, here is what works:

ApplicationData -> "ApplicationData" 
UserProfile -> "USERPROFILE" 
LocalApplicationData -> "LocalApplicationData"
ProgramFilesX86 -> "PROGRAMFILESX86"

Is it possible that everyone else is experiencing this too but not noticing because it falls back to .paket directory?

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Please provide a description of any known workarounds.

**Comment by matthid** [comment]
I was wondering about this for some time now as well. Never had a chance to look at it. Thanks for the analysis. You want to try and send a PR?

**Comment by dbruning** [comment]
Great. I'd like to do a PR but I'm just in the middle of a full computer reset/reinstall and getting behind in work so may not get to it very soon!

________________________________

**Comment by matthid** [comment]
I'm currently looking into that.
We don't use `[Environment]::GetFolderPath` but try to find the environment variables. And as far as I can see those are correct. 

I think the error here is an unintended side effect. It was introduced in https://github.com/fsprojects/Paket/commit/dd4e24a5957acbaaa111614cda641c5b6460114e
Paket basically always prints the message no matter if it actually found the correct path...
Fix is on the way.
