### ISSUE TITLE
Regression in 5.x , paket is failing to resolve prerelease dependency

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#2459]
### Description

We encountered following issue we have two packages that have a common dependency on of them using release and one is using prerelease of this dependency.

This an example: 

ServiceA.Interface (1.0.0)
      Common.Contracts (>= 2.4.10)

ServiceB.Interface (1.0.0)
      Common.Contracts (>= 2.5.0-pre01)

In paket 4.8.8  for Common.Contracts version 2.5.0-pre01 is taken but in paket 5.1.8 we geting a conflict it unable to find a package that satisfies both condition

**Comment by forki** [comment]
actually that seems like paket 5 is correct here. ServiceA.Interface doesn't allow prerelease.
I think you can `Common.Contracts prerelease` to deps file to allow that.

**Comment by lexarchik** [comment]
I try setup like in attached archive, but can't reproduce problem.
[paket2459.zip](https://github.com/fsprojects/Paket/files/1094631/paket2459.zip)

1. `ls *.template | % { paket pack output ..\nuget templatefile $_.Name }` in `\paket2459\packages\` folder
2. `paket install` in `\paket2459\solution\` folder

In `\paket2459\solution\paket.lock` file i get:
```text
NUGET
  remote: ..\nuget
    common (1.2.0-pre01)
    packageA (1.0.0)
      common (>= 1.1.1)
    packageB (1.0.0)
      common (>= 1.2.0-pre01)
```

**Comment by forki** [comment]
o_O

**Comment by tsibelman** [comment]
I will try to make a repro

**Comment by matthid** [comment]
I think this is kind of solved now. At least we improved the situation a bit via https://github.com/fsprojects/Paket/issues/2475 and https://github.com/fsprojects/Paket/issues/2471

Let us know if this is not the case. Short story: You need to tell paket that you want to allow the prerelease in the dependencies file. This is expected at the moment.
