### ISSUE TITLE
Regression in 5.2.x - References Conditions updated

### ISSUE THREAD

**Issue by JohnDev** [fsprojects/Paket#2464]
### Description

Since the version 5.2, the conditions to choose the good reference has change.

Before : net35\Cassette.dll was used only for frawework 3.5. 
Now : For all target framework :(
```
-    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v3.5'">
+    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v3.5' Or $(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.0.3' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2' Or $(TargetFrameworkVersion) == 'v4.6.3' Or $(TargetFrameworkVersion) == 'v4.7')">
       <ItemGroup>
         <Reference Include="Cassette">
           <HintPath>..\packages\Cassette\lib\net35\Cassette.dll</HintPath>
           <Private>True</Private>
           <Paket>True</Paket>
         </Reference>
       </ItemGroup>
     </When>
-    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.0.3' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2' Or $(TargetFrameworkVersion) == 'v4.6.3' Or $(TargetFrameworkVersion) == 'v4.7')">
-      <ItemGroup>
-        <Reference Include="Cassette">
-          <HintPath>..\packages\Cassette\lib\net40-client\Cassette.dll</HintPath>
-          <Private>True</Private>
-          <Paket>True</Paket>
-        </Reference>
-      </ItemGroup>
-    </When>
```

**Comment by forki** [comment]
@matthid urgs another one with client profile

**Comment by matthid** [comment]
Oh yeah its because we punish 40-client now and that makes paket prefer the net35 version :/

This penalty code needs some cleanup badly...

**Comment by optical** [comment]
I believe I've hit this issue too. We have a project targeting Full framework 4.5 which transitively depends on Microsoft.Bcl.

In 5.2.1 Paket would not include references to System.IO, System.Runtime and System.Threading.Tasks, however 5.2.2 and 5.2.3 currently do. This causes the build to fail since the framework already includes references to those assemblies. Heres a gist with the csproj and relevant files. https://gist.github.com/optical/102a08bd9fd71684195a6e3285b7ab8c

Have had to alter our build system to pin paket versions now, previously we were using the latest version available.

**Comment by optical** [comment]
Actually, given that 5.2.2 came out after this issue was logged, my case must be a separate regression. I'll split this off into its own case. Sorry!

**Comment by matthid** [comment]
Fix in https://github.com/fsprojects/Paket/pull/2498

**Comment by JohnDev** [comment]
Thx for the fix, it's working now ;)
