### ISSUE TITLE
Timeout in convert-from-nuget with UWP application

### ISSUE THREAD

**Issue by dbruning** [fsprojects/Paket#2465]
### Description

I was trying to add a UWP project to an existing solution which already was working well with Paket (thanks for your time on this project by the way!)

When I try to convert the UWP project to Paket (with convert-from-nuget), I kept getting a timeout.
My internet here isn't particularly slow, and I don't know whether Paket is supposed to work with UWP projects at all. So I've created a repro repository, which is basically just a blank UWP project with a reference to Newtonsoft.Json.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a new blank UWP application in Visual Studio

2. Add a reference to some Nuget package (e.g. Newtonsoft.Json)

Git repo with this simple project (and .paket/paket.exe added) is available at https://github.com/dbruning/paket-uwp-repro.git

### Expected behavior

Command completes and references are changed to Paket references

### Actual behavior

Command times out with "TimeoutException: Waited 30 seconds for a request to finish"
(Note: I've included the [full log](https://github.com/dbruning/paket-uwp-repro/blob/master/paket%20log.txt) from "paket convert-from-nuget -v" in the repo 

### Known workarounds

none

**Comment by forki** [comment]
this is a bug. working on it

**Comment by forki** [comment]
mhm I'm not completely sure what happes.

@dbruning  can you please remove the two myget sources from the deps file and run paket install again? should do as workaround

**Comment by forki** [comment]
ok lastest version doesn't add these obsolete nuget feeds anymore. This fixes it for me.
BUT: @matthid we need to take a deeper look. it should still have worked with these feeds.

**Comment by dbruning** [comment]
Yes, that workaround worked for me - thanks.
