### ISSUE TITLE
Paket keeps restoring packages on build with auto-restore off

### ISSUE THREAD

**Issue by megafinz** [fsprojects/Paket#2468]
### Description

I've converted a large repo (80+ projects) from NuGet into Paket using `convert-from-nuget` command. Then I used `auto-restore off` command to turn off package restoration on each build. For some reason one of my solutions keeps restoring packages on each build (just one, there are several of them and others seem to work fine).

I'm using Paket 5.2.1, Visual Studio 2017. Solution under question uses MSBuild Community Tasks. Paket for Visual Studio 0.32.1 is installed. There is no paket.targets file in the repo.

### Repro steps

Unfortunately I can't provide a repro since I don't understand what's going on. I switched off NuGet auto-restore in Visual Studio to see if that affects Paket—no luck. Also I tried switching on verbose build output, but unfortunately it starts producing messages after Paket finishes restoring packages.

Help needed to pinpoint the issue.

### Expected behavior

I expect Paket not to restore packages on each build when I use `auto-restore off`.

### Actual behavior

Paket tries to restore packages on each build which takes quite a bit of time on a solution of such scale (80 projects).

### Known workarounds

Nope.

**Comment by matthid** [comment]
While this is not enough info to figure out what's going on. I think we will need to solve this eventually because of netcore.

In netcore world we integrate into msbuild `dotnet restore` which means `paket restore` will run on every project. So we need to build-in some shortcut logic or dirty flag to make `paket restore` a no-op on the second run anyway. That will probably fix this issue as well?

**Comment by forki** [comment]
No this one is different (and in general paket restore behavior in netcore is very different).

Anyway please check if one of your csproj files contains a reference to paket.targets. That one needs to be removed.

**Comment by megafinz** [comment]
> Anyway please check if one of your csproj files contains a reference to paket.targets. That one needs to be removed.

I've double checked this—no csproj-files contain `paket.targets` text. Also there are no `paket.targets` files at all, so I guess the build would fail if csproj-files still reference `paket.targets`.

**Comment by forki** [comment]
do you have paket's visual studio addin installed? that one might interfere as well

**Comment by megafinz** [comment]
> do you have paket's visual studio addin installed? that one might interfere as well

Yep, seems that is what causing the restore. I uninstalled the add-in and everything is fine now.
