### ISSUE TITLE
5.2.2 Regression - Paket incorrectly adds reference to System assemblies on full frameworks

### ISSUE THREAD

**Issue by optical** [fsprojects/Paket#2469]
### Description

When a .NET 4.5 project depends upon Microsoft.Bcl, paket incorrectly adds a reference to System.IO, System.Runtime and System.Threading.Tasks. Previous versions did not do this.

### Repro steps
Download & save all the files found in https://gist.github.com/optical/102a08bd9fd71684195a6e3285b7ab8c

1. Install paket 5.2.2 
2. Run paket install

### Expected behavior

Those 3 system libraries are not referenced

### Actual behavior

They are infact referenced (5.2.1 and earlier did not do this)

### Known workarounds

Use version 5.2.1. Unsure if any other settings work around this.

**Comment by Ravadre** [comment]
We have similar issues (.Net 4.6, Paket 5.2.3). More references like `System.Collections.Concurrent` are incorrectly added to project files - this created duplicate references, as types from those libraries are already included in mscorlib.

In case of `System.Collections.Concurrent`, .Net Standard 1.3 libraries are included (superfluously):

`<HintPath>..\packages\System.Collections.Concurrent\lib\netstandard1.3\System.Collections.Concurrent.dll</HintPath>`

Downloading Paket 5.2.1 fixes the issue:
```
.paket\paket.bootstrapper.exe 5.2.1
.paket\paket.exe install
```

**Comment by forki** [comment]
@optical I think we do not have any relevant changes between 5.2.1 and 5.2.2

**Comment by optical** [comment]
@forki yeah I had a look at the changesets tagged between them to see if I could submit a PR, but couldn't see anything related. I don't know F# though, so possibly missed something.

Nevertheless, its easily reproduced. Stumps me!

**Comment by forki** [comment]
I think I found something. Give me a sec

**Comment by forki** [comment]
@matthid somehow we excluded the "_._" placeholders from our model -  I pushed a workaround since it's a serious bug.
@optical @Ravadre please retry with 5.2.4

**Comment by Ravadre** [comment]
@forki I can confirm that after updating from 5.2.1 to 5.2.4 and retrying everything works as expected (no changes to any .csproj in our solution after `paket install`).

Thanks a lot!

**Comment by matthid** [comment]
@forki Did you cherry-pick a commit of https://github.com/fsprojects/Paket/pull/2454? I said it's not ready and has this bug...

**Comment by forki** [comment]
Not sure how it got in

**Comment by forki** [comment]
@matthid yes looks like I messed this up. sorry. #2454 is now reverted

**Comment by matthid** [comment]
no problem I was just really confused because pr was still open

**Comment by forki** [comment]
as I said. no idea how I fucked that up. sorry again

**Comment by optical** [comment]
Can confirm it is working for me too. Thanks for the prompt fix :+1:
