### ISSUE TITLE
Warning: Failed to getDetailsFromNuGetViaODataFast '...'. Trying with Version instead of NormalizedVersion

### ISSUE THREAD

**Issue by parthopdas** [fsprojects/Paket#2472]
### Description

Getting the following warning with paket 5.2.5.
> Failed to getDetailsFromNuGetViaODataFast 'https://...'. Trying with Version instead of NormalizedVersion **(Please report this warning!)**:

### Repro steps

1. Clone https://github.com/tddstud10/Engine
2. ./build.cmd rebuild

### Expected behavior

No warning

### Actual behavior

Following warnings:
> Failed to getDetailsFromNuGetViaODataFast 'https://ci.appveyor.com/nuget/xtestplatform-ve52h0rqj3nc/Packages?$filter=(tolower(Id) eq 'r4nd0mapps.xtestplatform') and (NormalizedVersion eq '2.0.0-ci0017')'. Trying with Version instead of NormalizedVersion (Please report this warning!): System.Exception: Could not retrieve data from 'https://ci.appveyor.com/nuget/xtestplatform-ve52h0rqj3nc/Packages?$filter=(tolower(Id) eq 'r4nd0mapps.xtestplatform') and (NormalizedVersion eq '2.0.0-ci0017')' ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
>    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
>    --- End of inner exception stack trace ---
>    at Paket.Utils.getFromUrl@568-9.Invoke(Exception _arg3)
>    at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
> Failed to getDetailsFromNuGetViaODataFast 'https://ci.appveyor.com/nuget/common-wqs82t184w0x/Packages?$filter=(tolower(Id) eq 'tddstud10.common') and (NormalizedVersion eq '1.2.3-ci0092')'. Trying with Version instead of NormalizedVersion (Please report this warning!): System.Exception: Could not retrieve data from 'https://ci.appveyor.com/nuget/common-wqs82t184w0x/Packages?$filter=(tolower(Id) eq 'tddstud10.common') and (NormalizedVersion eq '1.2.3-ci0092')' ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
>    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
>    --- End of inner exception stack trace ---
>    at Paket.Utils.getFromUrl@568-9.Invoke(Exception _arg3)
>    at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
> Failed to getDetailsFromNuGetViaODataFast 'https://ci.appveyor.com/nuget/testhost-rrsttutj8jym/Packages?$filter=(tolower(Id) eq 'tddstud10.testhost') and (NormalizedVersion eq '2.1.0-ci0042')'. Trying with Version instead of NormalizedVersion (Please report this warning!): System.Exception: Could not retrieve data from 'https://ci.appveyor.com/nuget/testhost-rrsttutj8jym/Packages?$filter=(tolower(Id) eq 'tddstud10.testhost') and (NormalizedVersion eq '2.1.0-ci0042')' ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
>    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
>    --- End of inner exception stack trace ---
>    at Paket.Utils.getFromUrl@568-9.Invoke(Exception _arg3)
>    at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)

### Known workarounds

None

**Comment by Reelix** [comment]
I can confirm that I am receiving the same error on "Right Click packet.dependencies -> Update" in Visual Studio 2015

**Comment by matthid** [comment]
This seems to be solved now?
