### ISSUE TITLE
paket outdated formatting is misleading

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#2507]
`paket outdated` shows outdated versions in the (IMHO) wrong order:

```
...
 - Castle.Windsor 3.2.1
 - Nancy 1.4.1
 - Castle.Core 3.2.0
...
Outdated packages found:
  Group: Main
    * Castle.Core 3.3.3 -> 3.2.0
    * Castle.Windsor 3.4 -> 3.2.1
    * Nancy 1.4.3 -> 1.4.1
```

This implies that e.g. Nancy can/should be *downgraded* from 1.4.3 to 1.4.1 I argue this format would be a better fit:

```
    * Nancy 1.4.1 -> 1.4.3
```

**Comment by forki** [comment]
I think it's correct. It's what the resolver came up with.

**Comment by agross** [comment]
I'm concerned about the order of `package version-a -> version-b`.

From your perspective, should `version-a` be the currently used version or the version that can be upgraded to?

**Comment by forki** [comment]
A is what is currently in the lock file.

**Comment by agross** [comment]
OK, I get it. The output is correct, but my depfile was wrong. Thanks!
