### ISSUE TITLE
.net core project stripped of all references

### ISSUE THREAD

**Issue by stimms** [fsprojects/Paket#2518]
### Description

The .csproj file for a .net core project is not updated with any references either during a nuget conversion or when adding a package. 

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a new ASP.NET Core project in Visual Studio
2. Add the paket bootstrap at the solution level
3. In the project directory run `.paket/paket.exe convert-from-nuget`
4. Attempt to build in Visual Studio

https://github.com/stimms/PaketReferenceBug

### Expected behaviour

Project references the packages listed as dependencies.

### Actual behaviour

The project has no references to any libraries and cannot be built.

### Known workarounds

No trivial workaround

**Comment by forki** [comment]
I think we would need it BEFORE the conversion

**Comment by stimms** [comment]
Sorry, you'd need what before the conversion?

**Comment by forki** [comment]
the situation just before you run convert.

**Comment by forki** [comment]
can you upload a zip with that?

**Comment by stimms** [comment]
It is just file > new project. I put it in https://github.com/stimms/PaketReferenceBug/tree/before_conversion

**Comment by forki** [comment]
I get a paket.dependencies file with

    source C:\Users\Steffen\.dotnet\NuGetFallbackFolder
    source https://www.nuget.org/api/v2/
    
    nuget Microsoft.ApplicationInsights.AspNetCore 2.0.0
    nuget Microsoft.AspNetCore 1.1.2
    nuget Microsoft.AspNetCore.Mvc 1.1.3
    nuget Microsoft.AspNetCore.StaticFiles 1.1.2
    nuget Microsoft.Extensions.Logging.Debug 1.1.2
    nuget Microsoft.VisualStudio.Web.BrowserLink 1.1.2

and paket.references with

    Microsoft.ApplicationInsights.AspNetCore
    Microsoft.AspNetCore
    Microsoft.AspNetCore.Mvc
    Microsoft.AspNetCore.StaticFiles
    Microsoft.Extensions.Logging.Debug
   Microsoft.VisualStudio.Web.BrowserLink

that looks mostly correct.

    source C:\Users\Steffen\.dotnet\NuGetFallbackFolder

is probably not something I want to remove and cli tool conversion could be done. But what are you missing?

**Comment by inosik** [comment]
@stimms I think that is by purpose, because Paket "replaces" `PackageReference` items in the project with `paket.dependencies` and `paket.lock`.

I think all you are missing is a simple `dotnet restore` after Step 3. @forki shouldn't that be working?

**Comment by forki** [comment]
@inosik I have currently no idea what the bug is about. But I improved convert to understand cli references as well :P

**Comment by enricosada** [comment]
Closing as fixed
