### ISSUE TITLE
[external @VF#] newsdk + paket only loads in VS with FSharp.NET.Sdk

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2523]
ref https://github.com/Microsoft/visualfsharp/issues/3335

**Comment by forki** [comment]
This is a vs issue. Please report over there. I think it works in ionide.

**Comment by forki** [comment]
We should keep it still open until both sides fit together. 

/cc @enricosada @cartermp

**Comment by Krzysztof-Cieslak** [comment]
If it works in Ionide and MsBuild then it's working fine. VS not following specification was exact core of the problem with old project files, let's not repeat this mistake again ;]

**Comment by 0x53A** [comment]
I assume it is an issue in the F# implementation of Microsoft.NET.Sdk.

https://github.com/Microsoft/visualfsharp/issues/3335

**Comment by 0x53A** [comment]
![image](https://media.tenor.com/images/ddaf53bd25105cf4d616aa89cae41d02/tenor.gif)
