### ISSUE TITLE
Could not detect any platforms from 'Xamarin.*' messages.

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#2532]
### Description

I did a fresh install of Fable, all the way down from brew on El Capitan, including yarn and dotnet. Mono version 4.4.0 pre-installed.

### Repro steps

Install a new fable project following the instructions on the fable website. Build the project using dotnet restore and dotnet fable yarn-run build.

### Expected behavior

Installation of dependencies.

### Actual behavior

A lot of messages like:

Could not detect any platforms from 'Xamarin.*'

### Known workarounds

Ignore the messages.

**Comment by forki** [comment]
could you please copy the exact messages?

**Comment by halcwb** [comment]
> MacBook-Pro:GenPedGUI hal$ dotnet restore
>   Paket version 5.7.0
>   Could not detect any platforms from 'xamarin.tvos1.0'
>   Could not detect any platforms from 'xamarin.watchos1.0'
>   Could not detect any platforms from 'Xamarin.TVOS1.0'
>   Could not detect any platforms from 'Xamarin.WatchOS1.0'
>   Performance:
>    - Disk IO: 1 second
>    - Runtime: 7 seconds
>   Paket version 5.7.0
>   Could not detect any platforms from 'xamarin.tvos1.0'
>   Could not detect any platforms from 'xamarin.watchos1.0'
>   Could not detect any platforms from 'Xamarin.TVOS1.0'
>   Could not detect any platforms from 'Xamarin.WatchOS1.0'
>   Performance:
>    - Disk IO: 1 second
>    - Runtime: 7 seconds
>   Restoring packages for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj...
>   Restoring packages for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj...
>   Lock file has not changed. Skipping lock file write. Path: /Users/hal/Development/GenPed/GenPedGUI/src/obj/project.assets.json
>   Restore completed in 385,56 ms for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj.
>   Restore completed in 920,4 ms for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj.
>   
>   NuGet Config files used:
>       /Users/hal/Development/GenPed/GenPedGUI/NuGet.Config
>       /Users/hal/.nuget/NuGet/NuGet.Config
>   
>   Feeds used:
>       https://api.nuget.org/v3/index.json
> MacBook-Pro:GenPedGUI hal$ cd src/
> MacBook-Pro:src hal$ dotnet restore
>   Paket version 5.7.0
>   Could not detect any platforms from 'xamarin.tvos1.0'
>   Could not detect any platforms from 'xamarin.watchos1.0'
>   Could not detect any platforms from 'Xamarin.TVOS1.0'
>   Could not detect any platforms from 'Xamarin.WatchOS1.0'
>   Performance:
>    - Disk IO: 945 milliseconds
>    - Runtime: 6 seconds
>   Paket version 5.7.0
>   Could not detect any platforms from 'xamarin.tvos1.0'
>   Could not detect any platforms from 'xamarin.watchos1.0'
>   Could not detect any platforms from 'Xamarin.TVOS1.0'
>   Could not detect any platforms from 'Xamarin.WatchOS1.0'
>   Performance:
>    - Disk IO: 915 milliseconds
>    - Runtime: 7 seconds
>   Restoring packages for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj...
>   Restoring packages for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj...
>   Lock file has not changed. Skipping lock file write. Path: /Users/hal/Development/GenPed/GenPedGUI/src/obj/project.assets.json
>   Restore completed in 367,39 ms for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj.
>   Restore completed in 654,62 ms for /Users/hal/Development/GenPed/GenPedGUI/src/GenPedGUI.fsproj.
>   
>   NuGet Config files used:
>       /Users/hal/Development/GenPed/GenPedGUI/NuGet.Config
>       /Users/hal/.nuget/NuGet/NuGet.Config
>   
>   Feeds used:
>       https://api.nuget.org/v3/index.json

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/28265416-df73dfe8-6aef-11e7-9dcb-b259869033ef.png)


yeah it's becoming a bit annoying ;-)

/cc @matthid

**Comment by matthid** [comment]
Best think would be to add them and extend the parser ;)

**Comment by matthid** [comment]
Just an addition: imho just removing the warning is not an option. Paket needs to tell you if it cannot understand the supported platforms otherwise user has the expectation that all platforms work as expected. Additionally it might change the used references from what nuget might do.

**Comment by forki** [comment]
ot meant to remove the waring. we should implement it
