### ISSUE TITLE
Paket 5.7 install removes Foq references from all projects in solution

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#2533]
1. paket install
2. all references to Foq are removed

**Comment by forki** [comment]
do you have a repro!?

**Comment by vasily-kirichenko** [comment]
No.

**Comment by vasily-kirichenko** [comment]
It's on my solution at work. Just add a Foq dep and ref with older Paket, then update it and `paket install`, I believe it will pop up.

**Comment by forki** [comment]
did it update the Foq lib?

It's now `Lib` folder which is not correct. Should be `lib` /cc @ptrelford 
Also these "usage.fsx" are weid since they use version in path which only works with nuget.

**Comment by forki** [comment]
I'm working on a workaround

**Comment by vasily-kirichenko** [comment]
Do not rush, I've just reverted the changes for now.
