### ISSUE TITLE
After 5.1.6, paket fails with simple-nuget-server

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#2539]
### Description

After 5.1.6, paket fails to download pakages from  [simple-nuget-server](https://github.com/Daniel15/simple-nuget-server).  

### Repro steps

Steps listed in this repo:

https://github.com/TheAngryByrd/simplenugetserverpaketrepro

If you need help getting it setup or instructions aren't clear let me know

### Expected behavior

nuget packages are downloaded

### Actual behavior

nuget packages are not downloaded

### Known workarounds

Stay on version 5.1.6

Thanks!

**Comment by matthid** [comment]
Can you show what `http://172.16.122.130:5000/Packages?$filter=(tolower(Id) eq 'mycoollib') and (Version eq '0.1.0')'` returns?

**Comment by matthid** [comment]
Thanks for the repro :) will take a look

**Comment by TheAngryByrd** [comment]
```
$ curl "http://172.16.122.130:5000/Packages?$filter=(tolower(Id) eq 'mycoollib') and (Version eq '0.1.0')'"
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.11.1</center>
</body>
</html>

```

**Comment by matthid** [comment]
This is what we get. Nuget returns only the `<entry>` element, and not the feed.
```
<?xml version="1.0" encoding="utf-8"?>
<feed 
    xmlns="http://www.w3.org/2005/Atom" 
    xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" 
    xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xml:base="https://www.nuget.org/api/v2/">
    <id>http://localhost:5000//FindPackagesById</id>
    <title type="text">FindPackagesById</title>
    <updated>2017-07-18T17:45:55Z</updated>
    <link rel="self" title="FindPackagesById" href="FindPackagesById" />
    <entry>
        <id>https://www.nuget.org/api/v2/Packages(Id='mycoollib',Version='0.1.0')</id>
        <category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        <link rel="edit" title="V2FeedPackage" href="Packages(Id='mycoollib',Version='0.1.0')" />
        <title type="text">mycoollib</title>
        <summary type="text" />
        <updated>2017-07-18T17:34:09Z</updated>
        <author>
            <name>mycoollib</name>
        </author>
        <link rel="edit-media" title="V2FeedPackage" href="Packages(Id='mycoollib',Version='0.1.0')/$value" />
        <content type="application/zip" src="http://localhost:5000//download/mycoollib/0.1.0" />
        <m:properties>
            <d:Version>0.1.0</d:Version>
            <d:NormalizedVersion>0.1.0</d:NormalizedVersion>
            <d:Copyright />
            <d:Created m:type="Edm.DateTime">2017-07-18T17:34:09Z</d:Created>
            <d:Dependencies>NETStandard.Library:1.6.1:netstandard16|FSharp.Core:4.1.17:netstandard16</d:Dependencies>
            <d:Description>Package Description</d:Description>
            <d:DownloadCount m:type="Edm.Int32">1</d:DownloadCount>
            <d:GalleryDetailsUrl>http://localhost:5000//details/mycoollib/0.1.0</d:GalleryDetailsUrl>
            <d:IconUrl />
            <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
            <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
            <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
            <d:Language m:null="true" />
            <d:Published m:type="Edm.DateTime">2017-07-18T17:34:09Z</d:Published>
            <d:PackageHash>LPpx5j22ffENJNO0gdxfxtuTsy9Pvr9LTCu8SGnIpHUDkrSCkYQ02gpbmvzhgKqyMkWRFt+RxnZBNMRpeDN8yA==</d:PackageHash>
            <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
            <d:PackageSize m:type="Edm.Int64">3263</d:PackageSize>
            <d:ProjectUrl />
            <d:ReportAbuseUrl />
            <d:ReleaseNotes />
            <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
            <d:Summary m:null="true" />
            <d:Tags />
            <d:Title />
            <d:VersionDownloadCount m:type="Edm.Int32">1</d:VersionDownloadCount>
            <d:MinClientVersion />
            <d:LastEdited m:type="Edm.DateTime" m:null="true" />
            <d:LicenseUrl />
            <d:LicenseNames />
            <d:LicenseReportUrl />
        </m:properties>
    </entry>
</feed>
```

**Comment by forki** [comment]
Mhm I thought there was a time when we under both formats.

**Comment by matthid** [comment]
Yes I removed that It looked like code of just beeing lazy to be honest. I don't expect an api to return an entirely different response structure.

Will need to take another look to this mess

**Comment by forki** [comment]
It's not that important what we expect. Reality is a bitch ;-) 
Can you please put it back in?

**Comment by matthid** [comment]
Ok at least this one makes sense now. NuGet.exe is always using `http://localhost:5000/FindPackagesById()?id='mycoollib'` we are using `http://localhost:5000/Packages(Id='mycoollib',Version='0.1.0')` basically simple-nuget-server implementation is broken for `Packages` and does not return the correct result.

Would be interesting to see if there is a situation where nuget.exe is using `Packages` and to see if it fails.

**Comment by matthid** [comment]
We can add that fallback but I'll add a warning which says that the feed is broken.

To be honest the `<id>https://www.nuget.org/api/v2/Packages(Id='mycoollib',Version='0.1.0')</id>` line looks quite strange as well.

**Comment by forki** [comment]
It's not broken. It's just different.

Am 18.07.2017 10:11 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
Well I don't think the idea of a standard is to have different behaving implementations :/.
NuGet gallery is imho the standard because doing anything differently can break anytime NuGet team decides to do so. If they decide to use the `Packages` url like we do I'm pretty sure simple-nuget-server won't work anymore.

Everything else leads to insanity and leads to us being unable to provide a well performing paket implementation. So we can add workarounds but should guide the server implementations with warnings if possible.

The other option is that we use always `FindPackagesById` as well, because that always works because `nuget.exe` is using it. Nobody can implement it incorrectly because than `nuget.exe` will not work. But that again might degrade performance. It feels like a loose-loose situation :/

**Comment by matthid** [comment]
we could also think about adding a flag to the sources in the depsfile to enable using fast routes, this way people can decide and blame the feed implementations but it will work by default.

**Comment by forki** [comment]
IIRC correctly nuget returned it similarly long time ago. Then they
changed. And we adapted.

There is no standard. Unfortunately.

Am 18.07.2017 10:21 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
Ok I now verified that `nuget visual studio` is using the `Packages` route as well and can apparently handle the result.

> IIRC correctly nuget returned it similarly long time ago. Then they changed. And we adapted.

Thanks

Pr is https://github.com/fsprojects/Paket/pull/2541

I guess we can live with this particular case from a performance perspective as it is only local work to get the data we need. I'll make it clear in the code that this is required. Obviously this is another case we probably want a test for.

**Comment by TheAngryByrd** [comment]
You two rock! 🎸   I really appreciate dealing with my insane issue especially this quickly.

**Comment by matthid** [comment]
excellent repro steps need to be rewarded ;)
might even turn into a integration test
