### ISSUE TITLE
Add package to fable-suave-scaffold server not refresh the vscode editor

### ISSUE THREAD

**Issue by AviAvni** [fsprojects/Paket#2540]
### 

### Repro steps

1. Clone fable-suave-scaffold

2. Build and run

3. Add Neo4j.Driver package to the server with vs code

4. Build and run 

### Expected behavior

Intellisense need to work when adding code belong to this package

### Actual behavior

The editor not identify the added reference.

### Known workarounds

dotnet restore on the Server folder
and restart vscode

**Comment by forki** [comment]
I think the following is to do:

* ionide needs to monitor assets files. I think @Krzysztof-Cieslak is already working on this 
* paket install update, add, remove, restore should call dotnet restore and if that's not possible then we should at least try to do that from ionide plugin

**Comment by forki** [comment]
OK even then it seems to habe in some cases.

**Comment by enricosada** [comment]
there are diffenret issues there:
- fsac bugs (up to date check, wathc project.assets.json changes)
- paket integration to up to date check

so sdk2.0 will check `restore` running `build`, so will be ok. is an issue also in current c# of sdk1.0 that.
need to check how omnisharp handle it for 1.0.

but yes, at least FSAC should watch `project.assets.json` file for changes (in addition to fsproj changes), and invalidate the parsed project info (with notification to consumer like vscode). added https://github.com/fsharp/FsAutoComplete/issues/188 to track that.

> paket install update, add, remove,... should call dotnet restore and if that's not possible then we should at least try to do that from ionide plugin

i think these command should invalidate someone the up-to-date-check of the restore targets of sdk.
maybe as quickfix, add a useless `ProjectReference` (trimmed later by paket target), so the up to date check fails.
this should work in VS.

how FSAC based like vscode can replicate the uptodate check logic, dunno atm.
maybe check the hash of the packagerenferece list with the last recorded hash of project.assets.json is the same. dunno.
or add more paket awareness in FSAC (but is partial)

**Comment by forki** [comment]
> i think these command should invalidate someone the up-to-date-check of the restore targets of sdk.

that's interesting. we could create a `obj\ProjectName.fsproj.paket.targst` and put a number in there. right? If we touch that file - would that invalidate?

**Comment by enricosada** [comment]
Closing, implemented in both ionide and as general solution in VS 2017 based on msbuild
