### ISSUE TITLE
paket find-packages with empty arg is broken when using the bootstrapper

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#2545]
### Description

`paket find-packages ''` is used to search for top packages to provide completion. This has been working with 5.5 but seems broken now.

### Repro steps

Please provide the steps required to reproduce the problem

1. `paket find-packages ''`
1. paket enters interactive mode when it should find top packages

### Expected behavior

Top packages should be listed

### Actual behavior

Interactive mode is entered

**Comment by agross** [comment]
Could be a breaking change in  NuGet, seems like search doesn't work at all.

```sh
$ paket find-packages "FA"
Paket version 5.79.3
Ignoring error when requesting 'https://www.nuget.org/api/v2': Request to 'https://api.nuget.org/v3-flatcontainer/?q=FA&take=10000' failed with: 'BadRequest'
Performance:
 - Average Request Time: 778 milliseconds
 - Number of Requests: 3
 - Runtime: 3 seconds
```

**Comment by agross** [comment]
5.5.3 is the last version that works.

**Comment by agross** [comment]
`paket find-packages ""` doesn't work yet

**Comment by matthid** [comment]
For me it is working:

```
{ simplenugetserverpaketrepro } master » .paket/paket.exe find-packages ""                                                                                                                            /c/proj/simplenugetserverpaketrepro
Paket version 5.80.0
Ignoring error when requesting 'http://localhost:5000': Could not retrieve data from 'http://localhost:5000/Packages()?$filter=IsLatestVersion and IsAbsoluteLatestVersion and substringof('',tolower(Id))'
Newtonsoft.Json
NUnit
EntityFramework
jQuery
bootstrap
AutoMapper
NUnit.Runners
Microsoft.AspNet.Mvc
log4net
NuGet.Core
Npgsql
HtmlAgilityPack
SlowCheetah.Xdt
Microsoft.Owin.Host.SystemWeb
NLog
Microsoft.AspNet.SignalR
Microsoft.AspNet.WebApi
jQuery.UI.Combined
AjaxControlToolkit
angularjs
Performance:
 - Average Request Time: 429 milliseconds
 - Number of Requests: 3
 - Runtime: 2 seconds
```

**Comment by agross** [comment]
Hm, for me it's not:

cmd.exe:

```sh
$ .paket/paket.exe find-packages ""
Paket version 5.80.0
 - Please enter search text (:q for exit):
```

zsh/bash:

```sh
$ .paket/paket.exe find-packages ""
Paket version 5.80.0
 - Please enter search text (:q for exit):
:q

$ .paket/paket.exe find-packages ''
Paket version 5.80.0
 - Please enter search text (:q for exit):
```

**Comment by agross** [comment]
Do you use magic mode? It seems that the arg is lost in translation:

![2017-07-20_23-00-20](https://user-images.githubusercontent.com/16245/28438689-4ecc1a84-6d9f-11e7-8e78-45ef85b84b22.png)

**Comment by matthid** [comment]
no I did not in my tests, so yes that could be the reason...

**Comment by matthid** [comment]
Thanks for posting so quickly, was trying every shell I could find, and all were working ;)

**Comment by agross** [comment]
Tested again with the latest bootstrapper. No dice.

**Comment by matthid** [comment]
So technically it's a different issue which was there ever since magic mode was introduced I guess?

**Comment by agross** [comment]
Probably, yes. During completion development I only tested against locally compiled paket.exes since I required args that were not released yet.

**Comment by matthid** [comment]
Can we open a new one? I'd like to keep that one as a reminder to add a regression test for the initial issue.

**Comment by agross** [comment]
Or we can fix the issue :)
