### ISSUE TITLE
generate-load-scripts case sensitivity

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#2547]
### Description

generate-load-scripts has problems with casing.  This doesn't really affect Windows or macOS since they don't care, but this really affects anything linux related.  

paket exits with the error

```
Paket failed with
-> DirectoryNotFoundException: Could not find a part of the path "/app/packages/tests/Foq/lib/net45/Foq.dll".
```

### Repro steps

https://github.com/TheAngryByrd/generate-load-scripts-casing-repro

### Expected behavior

paket generates load scripts with correct casing in filepaths

### Actual behavior

paket does not generate load scripts with correct casing in filepaths

### Known workarounds

Use an insane OS like Windows or macOS :trollface:

**Comment by matthid** [comment]
Might be related to the fix of https://github.com/fsprojects/Paket/issues/2533

**Comment by forki** [comment]
@TheAngryByrd are you sure it's still an issue?
Is so can you please run it with -v?

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/28452735-5e4be55c-6df4-11e7-88f5-bb6e1a04c153.png)

**Comment by matthid** [comment]
repro works after converting `build.sh` to unix line feeds on windows...
I usually use git bash and `dos2unix build.sh` for that.

Problem is that windows git is checking out with windows crlf and if that gets added to the container it won't work.

**Comment by forki** [comment]
nice repro!

**Comment by agross** [comment]
> Problem is that windows git is checking out with windows crlf 

Can be solved with .gitattributes:
https://github.com/fsprojects/Paket/blob/master/completion/.gitattributes
