### ISSUE TITLE
paket.local should support packages with updated dependency sets

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#2549]
### Description

Project B has a dependency on a nupkg created by Project A.

Let's assume A 1.0 is the currently used version and it has no further dependencies.  While you work on A 1.1 you find that you need to add a dependency X to A. Now you want to test Project B with the updated version A 1.1, which now also requires X. Using the workflow described [here](https://fsprojects.github.io/Paket/local-file.html) it seems that this is currently not possible because the only command that looks for `paket.local` files is restore, which does not modify projects. Also `paket restore` does not process A's updated dependencies.

**Comment by matthid** [comment]
I think in this situation it's easier to work with CD and prereleases.
Maybe we should not allow to `paket pack` when a prerelease is in deps to prevent accidental deps on prereleases. 

Extending `paket.local` for this seems to overly complicate the process, this was not in scope when designing the feature.

See also https://github.com/fsprojects/Paket/issues/1925 /cc @theimowski

**Comment by theimowski** [comment]
Agreed with @matthid - paket.local does not recalculate lock file, just overrides single resolution. Extending it to described capability sounds like significant effort for this specific case

**Comment by agross** [comment]
OK, I in this case I'll just go with a temporary change to paket.dependencies specifying and additional local path source and recalculate the lockfile temporarily while testing.
