### ISSUE TITLE
Multiple HTTP dependencies no longer work

### ISSUE THREAD

**Issue by hmflash** [fsprojects/Paket#2566]
### Description

If your packet.dependencies file specifies more than one http dependency from the same server, `paket restore` completes successfully but only the last dependency exists on disk.

This was introduced with this commit:

https://github.com/fsprojects/Paket/pull/2565/commits/0d48da7fea80ba0e73d45810bb2a34440d5f32dc

Each time a dependency is downloaded, the directory is cleared, causing the removal of previously downloaded dependencies

### Repro steps

Example paket.dependencies:

```
http http://my_server/content/dependency1.zip
http http://my_server/content/dependency2.zip
```

`paket restore` completes successfully, but only `dependency2.zip` exists on disk.

**Comment by agross** [comment]
@forki please revert said commit. It will break `outdated - f`, but that's not used as frequently.



On Fri, Jul 28, 2017 at 7:59pm, Steffen Forkmann < notifications@github.com [notifications@github.com] > wrote:
/cc @agross [https://github.com/agross]

**Comment by forki** [comment]
I reverted that commit

Am 29.07.2017 05:21 schrieb "Alexander Groß" <notifications@github.com>:

> @forki please revert said commit. It will break `outdated - f`, but that's
> not used as frequently.
>
>
>
> On Fri, Jul 28, 2017 at 7:59pm, Steffen Forkmann <
