### ISSUE TITLE
install.sh fails with "Could not find a paket source on nuget.org."

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#2579]
### Description

I am following the system-wide installation on Linux and everything has build properly, now, when I run `sudo ./install.sh` I get this message:

> Could not find a paket source on nuget.org. Please check your internet connection and access to http://www.nuget.org.

### Repro steps

Follow the [installation instructions](https://fsprojects.github.io/Paket/installation.html#Installation-on-Linux) from the documentation

### Expected behavior

paket is installed in bash and zsh

### Actual behavior

Install script fails with an error
> Could not find a paket source on nuget.org. Please check your internet connection and access to http://www.nuget.org.

**Comment by RikkiGibson** [comment]
I'm experiencing this problem on macOS as well. Is anyone able to take a look at what could be causing it?

**Comment by forki** [comment]
I think the script is outdated. We should delete it - I'm open for someone to resubmit.

**Comment by Mousaka** [comment]
Also having this problem
