### ISSUE TITLE
Question about local cache

### ISSUE THREAD

**Issue by lexarchik** [fsprojects/Paket#2586]
After each restore Paket place cache of downloaded packages in `%HOME%\.nuget\packages\` folder.
Can i somehow change cache folder?
Adding `cache` option in dependencies file does not change this.

[Documentation](https://fsprojects.github.io/Paket/caches.html) not mention `%HOME%\.nuget\packages\`  folder at all.

(o.s. - Win10x64)

**Comment by lexarchik** [comment]
Env variable `NUGET_PACKAGES` set localion for this cache.
I'm quite confuse about caches in Paket. How this cache is differ from cache that i set in dependencies file?

**Comment by matthid** [comment]
`%HOME%\.nuget\packages\`: This is the global nuget cache we share with the "nuget.exe" or new dotnet-sdk (dotnet-cli tooling). You cannot change it in nuget.exe therefore you cannot change it in paket either afaik. It's an implementation detail to improve performance.

Caches in the dependencies file are user-managed additional caches which can live externally. Those caches are user-managed for example to provide stable builds.

Does that answer the question?

**Comment by lexarchik** [comment]
Yes, thanks.
