### ISSUE TITLE
paket pack fails on multi-targeting .NET Core projects

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsprojects/Paket#2591]
### Description

__sample.fsproj__
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Sample</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net462;netcoreapp1.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

__paket.dependencies__
```
source https://api.nuget.org/v3/index.json

frameworks: net462, netcoreapp1.0

nuget Chessie
```

__paket.template__
```
type project
title
    Something
owners
    Someone
authors 
    Someone
projectUrl
    https://example.com
iconUrl
    https://example.com
licenseUrl
    https://example.com
requireLicenseAcceptance
    false
copyright
    Copyright ©, star year 617308
tags
    fizz buzz fizzbuzz
summary
    Something quick
description
    It is common sense to take a method and try it. If it fails, admit it frankly and try another. But above all, try something.
```

### Repro steps

1. ⬆️
2. `paket pack bin`

### Expected behavior

A NuGet package would be created.

### Actual behavior

```
Paket version 5.84.0
Performance:
 - Runtime: 1 second
Paket failed with
-> Unable to find Release output path node in file C:\code\paket-bug\src\sample\sample.fsproj for any known platforms
```

### Known workarounds

😢

**Comment by forki** [comment]
For that you would want to use dotnet pack. Paket now hooks into that
command.

Am 07.08.2017 19:18 schrieb "Theodore Tsirpanis" <notifications@github.com>:

**Comment by baronfel** [comment]
It looks like the project hasn't been built in release mode, can you
`dotnet build -c Release` and then try again?

**Comment by teo-tsirpanis** [comment]
It works, but the package doesn't have the metadata specified in the template file.

**Comment by forki** [comment]
Yes it uses the normal dotnet meta data specification way. It's not really
clear to me if we still need/want template files for that scenario.

Am 07.08.2017 7:32 nachm. schrieb "Theodore Tsirpanis" <
notifications@github.com>:

It works, but the package doesn't have the metadata specified in the
template file.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2591#issuecomment-320728612>,
or mute the thread

**Comment by teo-tsirpanis** [comment]
Then what's the purpose of template files?

**Comment by forki** [comment]
It's invented for old school MSBuild projects - pre dotnet cli times. I'm
still thinking about it for dotnet cli.

Am 08.08.2017 9:49 vorm. schrieb "Theodore Tsirpanis" <
notifications@github.com>:

**Comment by Gonnagle** [comment]
Tried to multi-target netstandard2.0 and net461 as a workaround for #2705 but hit with this issue 
![image](https://cloud.githubusercontent.com/assets/136959/13203620/b7bd2b14-d881-11e5-810c-234e376ea8ed.gif )

We currently use internal MSBuilTask targets installed as nuget to automatically wire up the packing with paket as a part of build process. If this will not be supported and the "dotnet pack" is the advised way of packing netstandard packages we'll probably need to make some changes regarding that automation...

**Comment by teo-tsirpanis** [comment]
I am sorry, I forgot it but I can now perfectly create `.nupkg`s using `dotnet pack`.
