### ISSUE TITLE
Generating redirects for _._ results in FileNotFoundException

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#2611]
### Description

A net461 project referencing a netstandard1.3 project that references Microsoft.CodeAnalysis.CSharp.Workspaces

Running paket install generates redirect for `System.Threading`
In the system threading package we have `net45/_._` meaning a reference is not added to the net461 project and it throws when we run it.

>System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

```xml
<dependentAssembly>
  <Paket>True</Paket>
  <assemblyIdentity name="System.Threading" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.0.12.0" />
</dependentAssembly>
```
### Repro steps

1. Unzip [TestProject.zip](https://github.com/fsprojects/Paket/files/1222994/TestProject.zip)

2. Paket install

3. Run

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

I don't know how `_._` should be handled. Maybe some fallback strategy that uses content in `netstandardx/`

### Actual behavior

Redirect is added to a file that does not exist.

### Known workarounds

Dunno.

**Comment by forki** [comment]
what do you think should happen?
This is really shit since the app.config doesn't support framework restrictions, right?

**Comment by forki** [comment]
Did you try to set framework restrictions in dep file or references file? Would that work? 

/cc @isaac_abraham

**Comment by JohanLarsson** [comment]
I'm weak on all the netstandard stuff so I don't really have any suggestions. I was thinking a fallback strategy that uses content in netstandardx/ but I realize that it will get hairy.

**Comment by forki** [comment]
Tbh I think the references are OK. The issue is in the redirects since they
are different for different target frameworks

Am 16.08.2017 1:22 nachm. schrieb "Johan Larsson" <notifications@github.com

**Comment by forki** [comment]
as discussed on slack:

    framework: net461

fixes it
