### ISSUE TITLE
Conditional package references

### ISSUE THREAD

**Issue by yevhen** [fsprojects/Paket#2612]
In a mixed solution where some of the projects use new VS17 csproj format and target multiple frameworks (net462/nestandard) conditional references are required for some scenarios, such as referencing `System.AppDomain` for netstandard but not when building for net46.

Example:

```xml
<ItemGroup>
  <PackageReference Include="System.AppDomain" Version="2.0.11"
                    Condition="'$(TargetFrameworkIdentifier)' == '.NETStandard'" />
</ItemGroup>
```

Would be great to have this supported in `paket.dependencies` and/or `paket.references`

**Comment by TheAngryByrd** [comment]
Similar to https://github.com/fsprojects/Paket/issues/2394

**Comment by enricosada** [comment]
Closing as pratically a dupe of #2394 

@yevhen adding your use case to that issue, work will be tracked in #2394
