### ISSUE TITLE
Using minimum-from-lock-file without specifying version in paket.dependencies causes version pinning when creating nupkg

### ISSUE THREAD

**Issue by Allon-Guralnek** [fsprojects/Paket#2618]
### Description

If my paket.dependencies contains a reference to a package without specifying a version:

```
nuget MyCoolLibrary
```

Which causes version 8.2.1 of MyCoolLibrary to be installed (latest version). Then you `nuget pack` with `--minimum-from-lock-file`, the nuspec produced doesn't include a range (such as `>= 8.2.1`) but instead pins the dependency to a specific version (`=8.2.1`). This causes unexpected inflexibility in published NuGet packages, causing Paket to perform wild searches for the consumers of such packages. To work around it, you must manually specify a requested version range (e.g. `~> 8.2`) before publishing and then the resulting nuspec also has that range (`[8.2.1,9.0)`).

**Comment by forki** [comment]
Yes this is expected right now.

Am 16.08.2017 5:15 nachm. schrieb "Allon Guralnek" <notifications@github.com

**Comment by Allon-Guralnek** [comment]
Oh sorry, I misread nuspec's version format without any operators and brackets to mean pinned version (like it is in paket), when in fact it means minimum version.
