### ISSUE TITLE
Prerelease versions with hyphen are incorrectly handled

### ISSUE THREAD

**Issue by mexx** [fsprojects/Paket#263]
[SemVer](http://semver.org/) defines that prerelease identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-].
[NuGet](http://nuget.org/) allows prerelease identifies that match following regular expression `[a-z][0-9a-z-]*`, see [SemanticVersion.cs](https://nuget.codeplex.com/SourceControl/latest#src/Core/SemanticVersion.cs)

**paket.dependencies**

```
source http://nuget.org/api/v2

nuget Ninject == 3.2.3-unstable-001
```

**Output of** `paket update`

```
Paket version 0.8.1.0
Parsing paket.dependencies
Resolving packages:
  - fetching versions for Ninject
    - exploring Ninject 3.2.3-unstable-003
Locked version resolutions written to ...\paket.lock
Downloading Ninject 3.2.3-unstable-003 to ...\NuGet\Cache\Ninject.3.2.3-unstable-003.nupkg
Ninject 3.2.3-unstable-003 unzipped to ..\packages\Ninject
```

`paket`'s parsing of prerelease identifies do not honor the hyphens.
The problem is caused by using `.Split '-'` in [SemVer.fs](https://github.com/fsprojects/Paket/blob/b79d6888f4c266bf2cfbd662b3efa73ccaa27ce0/src/Paket.Core/SemVer.fs#L113-L130)
By this the `-001` part gets lost in the parsing process.
1. We should support such prerelease identifiers correctly.
2. If a version contains more data than we can recognize `paket` should fail.

**Comment by bigbearzhu** [comment]
This issue still exists. Should we reopen this?

**Comment by baronfel** [comment]
I'm slacking on this terribly, but there was a related fix in FAKE for the SemVer parser that corrected our handling of prerelease versions.  That fix is here: https://github.com/fsharp/FAKE/pull/1325, specifically the SemVerHelper.  I've been meaning to port those fixes over to Paket, in both the semver structures in the bootstrapper and Paket proper.

**Comment by jam40jeff** [comment]
Thanks, @baronfel.  I just came here to report this issue and was pleased to see it's already being worked on.
