### ISSUE TITLE
Fix integration test for 2294

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2631]
### Description

The package file in the integration test for #2294 has basically become unsolvable for paket after the netstandard.Library-2.0 release.

IMHO. We need to find a good way to solve this problem. If we can't we should at least try to restore the original riddle was it was a really good test-case.

Currently I set the test to ignore and added this issue (so the build is green for now, as this is probably a big resolver change)

**Comment by forki** [comment]
looks like I solved it. Release under way
