### ISSUE TITLE
Improve or remove Blacklisting logic

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2640]
![image](https://user-images.githubusercontent.com/4236651/29498154-7982fdaa-85f6-11e7-85c6-bf50de901c2c.png)

https://travis-ci.org/fsprojects/Paket/jobs/266553668#L7258

**Comment by matthid** [comment]
yeah potentially.
maybe we need to remember the errors and print them here..

**Comment by 0x53A** [comment]
Aha, I think this is related to that boring-ssl crap. If the first request hits the mono bug, then the source gets blacklisted.

https://github.com/fsprojects/Paket/pull/2637 may lessen the impact of this, but ultimately the paket behavior is probably ok.

**Comment by matthid** [comment]
Yes that's what I thought, but the message is still not optimal...

**Comment by 0x53A** [comment]
There are also issues with feeds getting blacklisted, if a package was not yet indexed:

I uploaded https://www.nuget.org/packages/0x53A.ReferenceAssemblies.net45/0.1.0 a few minutes ago:

```
 - 0x53A.ReferenceAssemblies.net45 0.1.0
Possible Performance degration, blacklist '1_https://www.nuget.org/api/v2/Packages(Id='0x53a.referenceassemblies.net45',Version='0.1.0')'
Possible Performance degration, blacklist '1_https://www.nuget.org/api/v2/Packages(Id='0x53a.referenceassemblies.net45',Version='0.1.0')'
Possible Performance degration, blacklist '1_https://www.nuget.org/api/v2/Packages(Id='0x53A.ReferenceAssemblies.net45',Version='0.1.0')'
Possible Performance degration, blacklist '1_https://www.nuget.org/api/v2/Packages(Id='0x53A.ReferenceAssemblies.net45',Version='0.1.0')'
Possible Performance degration, blacklist '2_https://www.nuget.org/api/v2/Packages?$filter=(Id eq '0x53A.ReferenceAssemblies.net45') and (NormalizedVersion eq '0.1.0')'
 - FSharp.Formatting 3.0.0-beta07
 - RoslynTools.MSBuild 0.4.0-alpha
Possible Performance degration, V3 was not working: Value cannot be null.
Parameter name: uriString
 - RoslynTools.ReferenceAssemblies 0.1.1
Possible Performance degration, V3 was not working: Value cannot be null.
Parameter name: uriString
 - FAKE 4.63
```

![image](https://user-images.githubusercontent.com/4236651/29733570-1b06ebf0-89ee-11e7-9fea-7ac31f54d025.png)

**Comment by matthid** [comment]
Yes this is real especially when a package is not existing on a source.

The huge problem is that we cannot trust a source that a 404 is correct (as some sources always do that for some V2 urls).

To be honest I have no idea anymore what to do. We need to somehow intelligently detect that a source is trustworthy and "trust" 404 responses as well.

**Comment by matthid** [comment]
I'm slowly starting to think that the only sane way forward is:

 - Implement what nuget.exe is doing exactly (figure that out by using fiddler on various sources)
 - Use this logic to validate before blacklisting a source or just remove the current logic

**Comment by matthid** [comment]
> Yes this is real - especially when a package is not existing on a source.

Thinking about this again, maybe the problem is something different.
We should not try to call GetDetails on package versions only returned by another source. I always thought this is already implemented but maybe this is broken in the special case when the other source is a local directory...

**Comment by forki** [comment]
I told you about that 404 debacle. ;-)
This is seriously shit.

Am 03.09.2017 11:58 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
@forki look at my last comment, maybe there is another bug here. Because when I implemented it the assumption was: when we make the request we already know the package exists on this source (because we got the version from it). Therefore we can follow: 404 -> broken Uri.

**Comment by forki** [comment]
yeah that assumption is sound.

**Comment by matthid** [comment]
I'm totally ignoring "This package has not been indexed yet", because IMHO that is clearly a server bug (and is only a transient error)

**Comment by matthid** [comment]
@Desarc Can you post your `paket.dependencies` or tell us if you had any "pinned" packages? Just want to ensure we actually solved the issue you are seeing.

**Comment by Desarc** [comment]
We get this in many different projects, with many different `paket.dependencies` configurations. It's generally a mix of pinning some packages to specific versions, while specifying version ranges for other packages (with `~>` or `@~>`, typically internal packages). We also mostly use `strategy: max`.

I don't know if it's relevant, but we usually don't use groups, and list multiple sources. The number of packages listed in one `paket.dependencies` can be anything from a few to over 100 (not counting unspecified transitive dependencies).
