### ISSUE TITLE
Paket.exe is detected as dangerous and moved to the quarantine

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [fsprojects/Paket#2647]
### Description

From time to time, paket.exe is detected as dangerous by Symantec antivirus and moved to the quarantine. User needs to restore file from quarantine and put it to the exception list

### Expected behavior
It would be helpful to add new point to FAQ or documentation for the new users

**Comment by forki** [comment]
I think you should contact them and ask what we can do to be whitelisted.
AFAIK we are already whitelisted for couple of antivir products

Am 22.08.2017 10:05 vorm. schrieb "Łukasz Pyrzyk" <notifications@github.com

**Comment by lukasz-pyrzyk** [comment]
I've sent a request to Symantec about adding Paket to the whitelist. 
I will let you know about the updates.

**Comment by forki** [comment]
Thank you!

Am 22.08.2017 10:17 vorm. schrieb "Łukasz Pyrzyk" <notifications@github.com

**Comment by lukasz-pyrzyk** [comment]
Symantec whitelist is based on MD5 and SHA checksum of the exe file, so it won't help us.

There is another way:

> - Digitally sign binaries with Class-3 digital certificates (X.509) from a Certificate Authority.

**Comment by forki** [comment]
Cc @agross

Am 22.08.2017 1:11 nachm. schrieb "Łukasz Pyrzyk" <notifications@github.com

**Comment by agross** [comment]
Working on it. Will try to get get a new certificate this week.

**Comment by lukasz-pyrzyk** [comment]
Hi, any update?

**Comment by forki** [comment]
Alex sent me the keys. Ball is on my field. Working on it

Am 30.08.2017 09:17 schrieb "Łukasz Pyrzyk" <notifications@github.com>:

**Comment by forki** [comment]
ok beta003 should be signed now

**Comment by pmbanka** [comment]
Did the signing ended up being used in latest releases? Symantec has some problems with https://github.com/fsprojects/Paket/releases/tag/5.118.0 on my machine.

**Comment by forki** [comment]
yes should be signed

**Comment by pmbanka** [comment]
Ugh this is going to be a nasty one :/ Symantec says this:

![image](https://user-images.githubusercontent.com/9840334/31725405-975d99be-b424-11e7-99e8-8d67703896fd.png)

But the signature looks fine:
![image](https://user-images.githubusercontent.com/9840334/31725431-a83c847a-b424-11e7-8e93-8b05a5e643f3.png)

I'll ask IT in my corp to look into the AV config.

**Comment by enricosada** [comment]
@pmbanka any info from your IT dep?

**Comment by pmbanka** [comment]
@enricosada they didn't respond to my request... but I don't remember the last time I saw this issue, so maybe it's better to close the issue (I can reopen if I see it again).

**Comment by enricosada** [comment]
@pmbanka nice, closing so, paket now is signed.

@lukasz-pyrzyk feel free to reopen Symantec antivirus quarantine another time paket
