### ISSUE TITLE
App.config gets cleared when running install

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#2648]
### Description

For one project the app.config gets cleared when running paket install.
I've been staring at it for a while but can't spot the difference.

### Repro steps

1. Clone: https://github.com/JohanLarsson/Gu.Reactive
2. Run paket install and check the diff.

### Known workarounds

Git revert.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/29711480-505ce560-8995-11e7-84ab-582657dc1f77.png)

where is the problematic diff?

**Comment by JohanLarsson** [comment]
Gu.Reactive.Tests/App.Config

**Comment by forki** [comment]
latest version allows you to set "redirects: force" on group level!
