### ISSUE TITLE
Don't download clitool packages and their dependencies into "packages" folder

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Paket#2651]
Being able to add `clitool` packages to paket.dependencies is a fantastic features and prevents having to take care of two different places (paket.dependencies and .fsproj) to manage your dependency versions.

However, given that what Paket doesn't manage clitools itself and just injects an MSBuild ItemGroup so the clitool is downloaded to the .Nuget global cache, wouldn't it be possible to prevent Paket from downloading clitool packages and their dependencies into the "packages" folder, so they don't take that extra disk space?

**Comment by matthid** [comment]
Tbh it shouldn't matter because we share the cache with nuget

**Comment by alfonsogarciacaro** [comment]
Using `clitool dotnet-fable storage:none` seems to do the trick :tada: Thanks a lot for your help!
