### ISSUE TITLE
Support Windows authentication for Nuget sources

### ISSUE THREAD

**Issue by samhanes** [fsprojects/Paket#2655]
We're not able to run `paket restore` from our build server because our private nuget feed (as presently configured) only supports Windows authentication and paket only supports basic auth.

It looks like adding support for windows credentials would be pretty straightforward.  I'm happy to work on a PR if you are open to the idea.

**Comment by forki** [comment]
Sure. Go ahead ;-)

Am 23.08.2017 5:33 nachm. schrieb "Sam Hanes" <notifications@github.com>:

**Comment by samhanes** [comment]
#2658
