### ISSUE TITLE
Entity Framework code-first migrations

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [fsprojects/Paket#2662]
How to work with code-first approach in EntityFramework and Paket? 

For example, is there any way to call Add-Migration on the EntityFramework tools?

**Comment by forki** [comment]
Paket does not call any ps1 scripts. They are considered bad practice and even MS tries to get rid of them.

**Comment by lukasz-pyrzyk** [comment]
So in another words - no? It is a big blocker, because I have to use paket and nuget...

**Comment by forki** [comment]
Even nuget has deprecated it long time ago. AFAIK it's only there for
legacy packages.config.

Am 25.08.2017 13:04 schrieb "Łukasz Pyrzyk" <notifications@github.com>:

**Comment by 0x53A** [comment]
The powershell tools in entity framework are different from install.ps1.

Install.ps1 is automatically called on install, which paket does not do (and the latest nuget doesn't either).

But the EF tools are just scripts that are bundled with the nupkg. You can still continue to call these manually.

The reason you can call these scripts through the Package Editor Console is that this is basically just a powershell window. You can do the same by just manually opening a powershell window, loading the scripts and running Add-Migration.

**Comment by forki** [comment]
Yes I was only talking about ps1 scripts during install. All other scripts that come with a package can be loaded with every Powershell command tool.

**Comment by M0ns1gn0r** [comment]
>... this is basically just a powershell window. You can do the same by just manually opening a powershell window, loading the scripts and running Add-Migration.

Actually you can't, you have to do it from Visual Studio's Package Manager Console. Otherwise you'll get the error:
> The module requires the following PowerShell host: 'Package Manager Host'.

However, the EF commands wouldn't appear in the VS console until I've added `version_in_path: true` in `paket.dependencies`:
> nuget EntityFramework ~> 6.2 version_in_path: true
