### ISSUE TITLE
[Discussion] Magic mode working in a team ? align teamate version ?

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2668]
### Description

Hello there,
in the past we encounter many times issue because we had to tell teamate to update paket CLI
once done we had other issue using magic mode (aka #2656)

### Expected behavior

Looking for an idea to align version of paket for developer + CI
we got about 30 developer, 10 build agents, the number of update per date can be hazardous sometimes
I'm wondering if there's a way to use magic mode across different multiple computer but not to the latest, a specified version 
It could be an ENV_VAR that for example point to a :
* server url
* shared folder
* exposed from a Git repo used by the team
* ...

### Actual behavior

Magic mode always get latest (if there's a bug we  have to fallback manually and communicate fast + change agent configuration)

### Known workarounds

Manually change paket.exe from magic mode to "normal mode", slow and kind of flacky

**Comment by matthid** [comment]
You can "lock" the version in your `paket.dendencies` file:
```
version 5.86.0-alpha005
source http://....
nuget MyPackage
```

The "Magic"-Mode-Bootstrapper will download the version locked in the depsfile.

**Comment by tebeco** [comment]
well we would have to align 60 repositories
if we decide to change, we have 60 repo to changes (we got like 100 repo only for our team, and 40 of it are yet to be migrated to paket)

I do understand it is a step forward but this is still a huge manual change

**Comment by matthid** [comment]
Yes I agree that it is not perfect. But is there a reason that all repositories need to use the same version?
/cc @forki what do you think about this scale?

**Comment by tebeco** [comment]
It's more like we need to be sure the CI Agent will run on the exact same configuration as any developer
We ended up rolling back mutually but nobody had the same version
but even CI had an older version (and this is not easy to change CI versions)

We have a process doing HASH on paket.exe on CI + a server dedicated of maintaining CI integrity
it ensure us that all agents are aligned not only for paket but also SDK, etc ...

**Comment by tebeco** [comment]
Another way would be to specified another URL for the Magic mode
for example, the CI Agents does not have Firewall right to access github.com (this site specifically)

So if you could for example say to the magic mode
`please dont use github.com/fsproject/paket/releases, use this other feed`
it would solve everything

**Comment by lexarchik** [comment]
> say to the magic mode

It can be done by options in dependencies file.
E.g. line `version <version> --force-nuget --nuget-source=<feed>`
We use network share as source for paket package in our projects.

**Comment by tebeco** [comment]
sooo paket.exe is released as a nuget ? and nuget-source is an private nuget feed that provide paket as a nuget ?

this is no CLI argument right ?
i dont want to confuse people says asking for them to add this param every time

**Comment by forki** [comment]
Also magic mode is reading a config file automatically. Put paket.exe.config alongside paket.exe. It allows you to pin the version

**Comment by tebeco** [comment]
@forki as said, i want to be driving by an external feed of each repo, avoviding us to edit 60 times the .config for each repo

**Comment by forki** [comment]
IIRC there was already an url parameter in the config file. If not we would
accept a pr. This url could provide a blessed version.

Am 26.08.2017 16:18 schrieb "TeBeCo" <notifications@github.com>:

**Comment by lexarchik** [comment]
> edit 60 times the .config for each repo

If you need synchronize paket version (and its changing) among many repo you can set nuget-feed in each dependencies file and not set version (also set `--max-file-age` to 0). 
For update paket everywhere you can just add new version of paket package to you nuget feed.

**Comment by tebeco** [comment]
will dig into paket code to see that nuget-feed
thx everyone here :)

**Comment by forki** [comment]
Ok seems url is not yet in
https://fsprojects.github.io/Paket/bootstrapper.html#In-application-settings


But I bet it's not hard to add. It's even a C# project ;-)

Am 26.08.2017 4:41 nachm. schrieb "TeBeCo" <notifications@github.com>:

**Comment by vbfox** [comment]
The reason I added version configuration in the `paket.dependencies` for magic mode is exactly this case : Synchronizing versions between all devs and our CI while still using magic mode.

BTW having the version pinned per-repository also allow you to build old git commits with old paket versions and get the same result. It can also allow teams to update paket at their own pace instead of forcing "big bang" upgrades but I can understand that upgrading a big number of repo can be painful. (We're mostly in monorepo so we sidestep that)

As for CI not having access to github.com it's also our case and we use the already cited ` --force-nuget --nuget-source=` in our "version" line in  `paket.dependencies` to point to our local NuGet cache (ProGet)

**Comment by trondd** [comment]
You can use the following solution to sync paket versions internally:

1. Add `paket.bootstrapper.exe` 5.92.2 or later and rename it to `paket.exe` to your repos.
1. Add the following `paket.exe.config` file as well:
```<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="ForceNuget" value="True"/>
    <add key="IgnoreCache" value="True"/>
    <add key="NugetSource" value="http://internal-feed" />
  </appSettings>
</configuration>```

Now all users will pick you that latest NuGet package that you push to your internal feed.

**Comment by vbfox** [comment]
btw the version line in paket.dependencies can accomplish the same

```
version -f --force-nuget --nuget-source=http://internal-feed
```

(version being a misleading name in this uncommon case, it's in fact the command line of the bootstrapper)

**Comment by enricosada** [comment]
@tebeco can solution proposed in https://github.com/fsprojects/Paket/issues/2668#issuecomment-327019657 (using internal feed) and https://github.com/fsprojects/Paket/issues/2668#issuecomment-327023800 (using version from cli) be enough? can this be closed?

**Comment by tebeco** [comment]
Yes it could be used, even if finnaly we're moving out from nuget due to other issue implying runtime resolution bug / binding redirect and other unwanted behavior since netStandard.
