### ISSUE TITLE
[Imporouvment] beeing warned if paket.lock was edited

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#2670]
### Description

In some scenario we found out that `paket.lock` has been edited. It could be for good or bad reason, this is not the point.
The thing that we found out that constraints were edited instead of pinning third part for example
This issue is that when you try to rollback to these previous state, removing `paket.lock` and redo a `paket install` it took us few hours to understand that it was in fact a manual edit that was the origin

I was wondering if there was a way to add a Hash in the very first lines of the `paket.lock`, that way, when using `paket restore` `paket install` `paket add` `paket update` ....
We would have a `WARN` or even `ERROR`(a paramter of the `paket.dependencies`

### Repro steps

1. create a project with package that have dependencies + transitie
2. manually edit `paket.lock` : the version constrains of the transitive packages
3. make sure constrains make no sense (like skip a major)
4. run a `paket restore` ==> no idea it was edited
5. backup `paket.lock` and remove it (rename it ?)
6. run a `paket install`
7. compare new and old `paket.lock`

### Expected behavior

Got warn or failure when any action reading / modifing `paket.lock` that does not match
An idea would be to add a line wish HASH of the resulted `paket.lock`
It would only required to rehash the `paket.lock` (expection of this line for evident reason)
then we could have warnings about manual edition

Bonus:
Beeing able to choose warning or error (just like WARN AS ERROR)

### Actual behavior

silent

### Known workarounds

None, 
we could try to see in Source control, but if the same commit contains both install+edit
Depending on constraints it is impossible to be sur that running paket install will endup with the same lock

**Comment by matthid** [comment]
I think we have some change-detection in place. But it didn't seem to catch your use case.
Usually paket warns when it detects that the dependencies-file doesn't match with the lockfile.
However, this can really only go so far...

Consider if someone edits the lockfile and updates the hash-file by hand. What to do now? Add another hash file for the hash file? IMHO Basically if users edit the file you need to assume they know what they are doing, such things need to be detected by code-reviews or other means.

**Comment by tebeco** [comment]
I did not want to speak about Hash editing because i had the exact same idea 🤣 
but i would love to be able that the change detection detection constraint edition and version resolved edition

and a toggle for that specific warn to be either warn or error (not all warning, our internal corp nuget sources are flacky as hell and generate warning)

Also, we cant predict human behavior, but this is happening because of a lack of comprehension of the tool. We are eager to help people that comes for helps, but cannot guess that someone will edit it after struggling alone ^^

**Comment by forki** [comment]
Just a personal note: editing lock files manually is a common use case. ;-)

Am 26.08.2017 4:13 nachm. schrieb "TeBeCo" <notifications@github.com>:

**Comment by tebeco** [comment]
hummm ok
will the change detection be upgraded or not ? just to be sure how should we communicate in the team about it ?

**Comment by forki** [comment]
Change detection means: lock file is invalid in terms of deps file.
It does not mean we detect if someone change it manually

Am 26.08.2017 19:05 schrieb "TeBeCo" <notifications@github.com>:

**Comment by matthid** [comment]
I'd suggest you use reviews to detect manual lockfile edits. Besides that I'm kind of thinking about closing this as I cannot see a technically sound way of doing what you want ...

**Comment by tebeco** [comment]
i though i closed it, my bad

conclusion is, we got no way to detect that
or remove paket.lock, run a paket install and compare both paket.lock and do a review
(That won't happen i guess)
