### ISSUE TITLE
Real test failure on mono: file not found, probably incorrect casing

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2676]
cc @matthid 

I think this is a real failure:

https://travis-ci.org/fsprojects/Paket/jobs/268953433#L7168

```
1) Error : Paket.IntegrationTests.InstallSpecs.#1270 install net461
System.Exception : Paket failed with
-> DirectoryNotFoundException: Could not find a part of the path '/home/travis/build/fsprojects/Paket/integrationtests/scenarios/i001270-net461/temp/packages/alphafs'.
   StackTrace:
```

It can't find "alphafs", but the real package id is mixed case:
![image](https://user-images.githubusercontent.com/4236651/29754367-e18e07cc-8b83-11e7-996c-a009387ef17d.png)

**Comment by matthid** [comment]
Yes we need to figure out how "nuget.exe" is saving it in the cache and then do the same. The depsfile of the test is:

```
source https://www.nuget.org/api/v2/
nuget Alphafs
```

Good catch, thanks

**Comment by forki** [comment]
should be fixed

**Comment by matthid** [comment]
I don't think this is fixed.

**Comment by matthid** [comment]
See report in https://github.com/fsprojects/Paket/issues/2262#issuecomment-332559351

**Comment by forki** [comment]
the other one is closed as well
