### ISSUE TITLE
Magic mode doesn't go back to no-prelease

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Paket#2681]
Recently we had a problem with a prerelease version (reported in #2680). We tried to go back to a no-prerelease Paket version, but deleting `paket.exe.config` was not enough. Apparently there was a cache somewhere that stubbornly used the faulty alpha version. We had to clone the repo to different directory to cheat the cache.

Should magic mode go back to a no-prerelease version when `paket.exe.config` is deleted? Or, how is it possible to clear the magic mode cache?

**Comment by matthid** [comment]
Clear:
 - `obj/` directories
 - revert paket.exe, Paket.Restore.targets and paket.targets

The important thing actually is reverting the `*.targets` files

**Comment by matthid** [comment]
There is always revert + `git clean -xdf` ;)

**Comment by alfonsogarciacaro** [comment]
Ok, thanks for the explanation!
