### ISSUE TITLE
"Key not valid for use in specified state." in paket config

### ISSUE THREAD

**Issue by dbruning** [fsprojects/Paket#2685]
After mucking around with the user account I was signing into my own computer with, "paket config add-credentials" started failing with message "Key not valid for use in specified state."

Turned out that the DPAPI-encrypted password that Paket was storing was no longer able to be decrypted. It's probably possible to update the code to work better in this scenario, but I just wanted to log this issue (and then close it) in case anyone else finds themself in this rare situation.

The fix is simply to edit %appdata%\Roaming\paket\paket.config and remove the previous key.

**Comment by matthid** [comment]
Is this a duplicate of https://github.com/fsprojects/Paket/issues/2627?

**Comment by dbruning** [comment]
Yep! Looks like it. Although in my case, the key itself had not expired, but had been DPAPI-protected with a different user principal.
Seems like if we're calling "paket config add-credentials" there should be no need to decrypt any existing credentials, we should just replace them with the new ones?
