### ISSUE TITLE
[Bug] Expecto is not restored properly in fable-scaffold

### ISSUE THREAD

**Issue by aprooks** [fsprojects/Paket#2686]
### Description

Expecto is not referenced properly by Paket. Error introduced by 5.91 and is reproducible by latest beta as well

### Repro steps

https://github.com/fable-compiler/fable-suave-scaffold/ clone and run build.

### Expected behavior

Fable-scaffold should be built without errors

### Actual behavior

Build fails during tests run with error:  `error FS0039: The namespace or module 'Expecto' is not defined.`

### Known workarounds

Rollback Paket version to 5.89.1.

Further discussion  https://github.com/fable-compiler/fable-suave-scaffold/issues/148

**Comment by forki** [comment]
I can repro when running build.cmd on windows.

**Comment by forki** [comment]
@matthid I can't see the ServerTests.paket.references file in obj

![image](https://user-images.githubusercontent.com/57396/29825421-a2ce916c-8cd4-11e7-80e2-2777c39f9e72.png)

**Comment by matthid** [comment]
If its introduced in 5.91 is has to do with `storage: none` and not the performance improvements?

**Comment by forki** [comment]
I don't see it using storage:none

**Comment by matthid** [comment]
Ah wait maybe it wasn't tested with a "clean" state, then it could be the performance improvements.
Basically paket should create a file called `ServerTests.fsproj.netcoreapp2.0.paket.resolved`

**Comment by forki** [comment]
looks like it just doesn't create the file.

![image](https://user-images.githubusercontent.com/57396/29825622-482f8364-8cd5-11e7-8c45-071b2ae27399.png)

**Comment by matthid** [comment]
I can take a look later

**Comment by matthid** [comment]
yes only latest beta is creating that file

**Comment by forki** [comment]
ok thanks.
At least I can confirm for now that it's reproducible.

**Comment by matthid** [comment]
So basically the question is:
 - Can you reproduce with 5.91 by reverting to the old targets file?
 - Can your reproduce with 5.90.1 with the old targets file?

I think both are "no".

**Comment by matthid** [comment]
Anyway I'll take a look :)

**Comment by cartermp** [comment]
This came up in last night's validation as well.  I'm having use this as the tracking issue.

**Comment by forki** [comment]
You found it internally at MS?
That's actually quite cool I have to say.

Ping @alfonsogcnunez @isaac_abraham - you guys know why.

Am 29.08.2017 17:01 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by cartermp** [comment]
Yep! FWIW we're currently doing validation on 2.0.0, but we'll eventually be validating against 2.1 as well.

**Comment by matthid** [comment]
Actually it seems like paket is doing the correct thing. 

Problem is the framework restriction in the `Test` group. `framwork >= net45` doesn't include `netcoreapp2.0`. Either get rid of the restriction completely or do something like `framework >= net45, >= netcoreapp20`.

**Comment by matthid** [comment]
Something is still not right

**Comment by matthid** [comment]
Ok you shouldn't delete paket's cache files otherwise you kill all the performance optimization that went into them ;) (https://github.com/fable-compiler/fable-suave-scaffold/pull/150/commits/7964553535a7fa4e7d26a12c86ebbbb0ab915687)
