### ISSUE TITLE
Hosted VSTS build fails

### ISSUE THREAD

**Issue by alexangas** [fsprojects/Paket#2693]
### Description

After converting a solution from NuGet to Paket, it fails to build using the Visual Studio Team Services (VSTS) hosted build server.

### Repro steps

Please provide the steps required to reproduce the problem

1. Convert existing solution with configured VSTS build from NuGet to Paket
2. Run build

### Expected behavior

Build completes successfully.

### Actual behavior

Numerous build errors where types used in referenced assemblies cannot be found.

### Known workarounds

Create a private build server connected to VSTS to perform builds.

**Comment by forki** [comment]
/cc @isaac_abraham any ideas what this is about?

Am 31.08.2017 12:24 vorm. schrieb "Alex Angas" <notifications@github.com>:

**Comment by alexangas** [comment]
I'm new to Paket, so if this should "just work", let me know and I'll narrow down a repro.

**Comment by forki** [comment]
Yeah I don't know why it would not. I'm not using vsts but AFAIK it worked
for other people

Am 31.08.2017 13:04 schrieb "Alex Angas" <notifications@github.com>:

**Comment by alexangas** [comment]
I couldn't reproduce this using a simple console application with class library. The main difference I can see is that the missing assemblies are never copied to the `packages` folder where Visual Studio build expects to find them. The working build has lines for `_CopyFilesMarkedCopyLocal` which does this whereas the not-working build has almost none.

Any ideas on what might be causing this?

**Comment by forki** [comment]
So the issue is unrelated to vsts? Maybe create a small repro zip to show
the problem?

Am 31.08.2017 3:37 nachm. schrieb "Alex Angas" <notifications@github.com>:

I couldn't reproduce this using a simple console application with class
library. The main difference I can see is that the missing assemblies are
never copied to the packages folder where Visual Studio build expects to
find them. The working build has lines for _CopyFilesMarkedCopyLocal which
does this whereas the not-working build has almost none.

Any ideas on what might be causing this?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2693#issuecomment-326297651>,
or mute the thread

**Comment by alexangas** [comment]
Sorry - the issue is only on VSTS. Here's the detailed background:

My solution of 20 projects was using NuGet and building locally and on VSTS fine. Then MS changed the behaviour of NuGet in VS2017 15.3 and there was no way I could get the solution to build locally any more. I converted the solution to Paket and everything built locally again. However builds then stopped working on VSTS. This appears to be because almost all of the assembly references that have been converted to Paket don't copy from the NuGet repo onto the VSTS hosted build server.

To try and reproduce I made a new console app and class library using NuGet and one of the package references from my 20 project solution. This all built fine locally and on VSTS. I then converted it to Paket and it still builds fine locally and on VSTS. So I don't know how to reproduce the problem.

The main difference that I noticed is that in my simple test repro it is correctly pulling down the packages from the NuGet package repo, but in my 20 project solution it is not.

Hopefully that is clearer... Please let me know what I should be looking for.

**Comment by forki** [comment]
So packages folder on vsts is empty after paket restore?

Am 31.08.2017 17:52 schrieb "Alex Angas" <notifications@github.com>:

**Comment by alexangas** [comment]
Please accept my apologies - my repro was invalid and paket restore was not being run.

Sorry for wasting your time!

**Comment by forki** [comment]
Yay! No worries. I'm happy we found it.

Am 31.08.2017 6:48 nachm. schrieb "Alex Angas" <notifications@github.com>:
