### ISSUE TITLE
mono paket.bootstrapper.exe SendFailure

### ISSUE THREAD

**Issue by TonyAbell** [fsprojects/Paket#271]
I have tried to run paket.bootstrapper.exe on my Ubuntu box, and am getting a 'SendFailure'
## From Github

```
$ mono paket.bootstrapper.exe 
No version specified. Downloading latest stable.
Error: SendFailure (Error writing headers)
```

---
## From Source

```
~/Paket/bin$ ./paket.bootstrapper.exe 
No version specified. Downloading latest stable.
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
```
### Mono

```
 mono --version
 Mono JIT compiler version 3.10.1 (master/36bfeec Fri Oct 17 13:03:53 PDT 2014)
 Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
         TLS:           __thread
         SIGSEGV:       altstack
         Notifications: epoll
         Architecture:  amd64
         Disabled:      none
         Misc:          softdebug 
         LLVM:          supported, not enabled.
         GC:            sgen
```

**Comment by paulkoerbitz** [comment]
Thank you Tony for documenting this at length here, I had the same issue on NixOS and running mozroots also worked here.

**Comment by Adron** [comment]
I ran into this issue and

    mozroots --impot --sync 

worked ok for me but I still get a lot of these "Could not fix timestamps in....  library here ...Error: The requested feature is not implemented." errors.

I found that I also needed to install the latest mono, which if skipped isn't entirely obvious. However after doing this I still ended up with errors about Nuget and NUnit and others not being implemented. I'm working through those issues now.

**Comment by pdoh00** [comment]
@Adron Did you ever figure this one out?  I am having the same issues with cannot fix timestamps and The feature is not implemented.  It's weird because I have 2 Linux Mint VM's, one on a work machine, and one at home.  The work machine downloads fine, but the home machine has the errors.
