### ISSUE TITLE
Why does the bootstrapper check for the SHA-1 hash of Paket?

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsprojects/Paket#2714]
Isn't HTTPS supposed to guarantee the file's integrity?

**Comment by iainnicol** [comment]
No, HTTPS means that nobody is impersonating the web server.  It doesn't prevent the web server itself being malicious.  Nor does HTTPS prevent the web server redirecting you to trusted but malicious mirror.

**Comment by teo-tsirpanis** [comment]
> It doesn't prevent the web server itself being malicious.

I don't understand. HTTPS guarantees that we are connected to the _actual_ GitHub site, and that we download what GitHub intents us to download. If GitHub sends us an evil file, why won't it send the SHA-1 of that evil file too?

> Nor does HTTPS prevent the web server redirecting you to trusted but malicious mirror.

Why would GitHub do something like that?

**Comment by iainnicol** [comment]
> If GitHub sends us an evil file, why won't it send the SHA-1 of that evil file too?

(Note: SHA-2 is different than SHA-1.  SHA-1 is considered insecure, but SHA-2 is considered secure.)

Ah, that's a good point.  I had assumed the hash was embedded in the bootstrapper.  Doing so would provide strong security, at the expense of (a) making it harder to do releases, and (b) preventing the bootstrapper from bootstrapping future versions.

You're right, IMO, the current system of downloading the SHA from GitHub offers minor benefits.  But it still theoretically helps with the following .

> > Nor does HTTPS prevent the web server redirecting you to trusted but malicious mirror.

> Why would GitHub do something like that?

Potentially the mirror could be cracked without GitHub noticing.  Unlikely but not impossible.

**Comment by matthid** [comment]
I think this was introduced to detect corrupt downloads (where the bootstrapper crashed while downloading for example). There are probably better options.

**Comment by iainnicol** [comment]
Ah, that's a good reason.

**Comment by teo-tsirpanis** [comment]
> Potentially the mirror could be cracked without GitHub noticing. Unlikely but not impossible.

A mirror? I think it is downloaded directly from GitHub.

> [T]his was introduced to detect corrupt downloads (where the bootstrapper crashed while downloading for example).

True, but as of Paket 2.92, the executable is Authenticode-signed.

**Comment by matthid** [comment]
@teo-tsirpanis Please send a PR to make it better ;)
Note that this needs to work x-plat

**Comment by iainnicol** [comment]
> A mirror? I think it is downloaded directly from GitHub.

GitHub redirects to AWS S3.  You can see this from curl, or using browser dev tools.

But both the SHA and the exe are served by S3, so again I'll concede you have a point.  If instead GitHub served the SHA file and S3 served the exe, then an attacker would have to compromise both.  And even then, code signing would remove the advantage.

**Comment by teo-tsirpanis** [comment]
> Note that this needs to work x-plat

In this case, we should consider strong-naming `paket.exe`. As it uses only system libraries, it should not be a problem. Mono and .NET Core support .NET Core. A problem is with referencing `paket.exe` directly (if somebody does that). But they can use `Paket.Core` instead which needs not to be strong-named.

>GitHub served the SHA file and S3 served the exe

Actually both are served by S3. And one must be really determined and skilled to infiltrate one of the biggest cloud providers to just replace the best NuGet client with a malicious one😛😈.

**Comment by haf** [comment]
@teo-tsirpanis Authenticode isn't that easy to work with cross platform and almost all guides are for Windows.

Also, the SHA1 checksum still takes 6500 years on CPU and then 110 years on GPU https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html so it's very costly to impersonate paket (around 110 000 USD at time of writing).

SHA256 is another much harder alternative, to crack; just switch to that and let's leave the MSFT-specific tech like authenticode and code signing behind us.

**Comment by enricosada** [comment]
Closing, original question is addressed.

Paket boostrapper check sha to detect corrupt downloads (where the bootstrapper crashed while downloading for example) and sha does that fast.

@teo-tsirpanis please open another issue if you want to discuss about authentication of paket/paket.boostrapper for security reason (but ihmo, because nuget package are checked is not that useful, there are easier attach vector ..)
