### ISSUE TITLE
Duplicates appear in generated scripts.

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#2716]
### Description

Duplicate `#r` lines appear in generated script files. Is this necessary? Can it cause problems?

### Repro steps

Use the Entity Framework nuget package as a test case.

### Expected behavior

I would expect to see the following in the generated script file:

```
#r "System.ComponentModel.DataAnnotations" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.dll" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.SqlServer.dll" 
```
### Actual behavior

Paket generates a file as follows:

```
#r "System.ComponentModel.DataAnnotations" 
#r "System.ComponentModel.DataAnnotations" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.dll" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.SqlServer.dll" 
```
### Known workarounds

Create your own references file.

**Comment by forki** [comment]
Oh we should dedupe these like we do in csproj references. PRs welcome.
Just filter it with a hashset or something

Am 04.09.2017 10:08 vorm. schrieb "Isaac Abraham" <notifications@github.com

**Comment by isaacabraham** [comment]
Maybe just a distinct rather than a hashset - need to maintain ordering I would imagine?

**Comment by forki** [comment]
distinct is using a hashset ;-)

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/seq.fs#L1084-L1089

**Comment by isaacabraham** [comment]
Yes but it maintains order? Does Hashset?

**Comment by forki** [comment]
look at the code. it just checks if the the thing is already in the set. It doesn't retrieve things from the set. So yes order is maintained

**Comment by isaacabraham** [comment]
ok sorry.

**Comment by matthid** [comment]
Yes use `distinct`  @forki is only trying to confuse you ;)

**Comment by matthid** [comment]
It shouldn't actually cause any harm so up-for-grabs

**Comment by forki** [comment]
Not meant to "confuse". I'm actually taking opportunities to educate the
readers about nice implementation details. :P

Am 04.09.2017 5:44 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

It shouldn't actually cause any harm so up-for-grabs

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2716#issuecomment-326991047>,
or mute the thread

**Comment by isaacabraham** [comment]
Very kind of you When I can get the solution to open on my PC maybe I'll do it otherwise yes up for grabs please
