### ISSUE TITLE
Paket update unable to resolve pakages.

### ISSUE THREAD

**Issue by b0urb4k1** [fsprojects/Paket#2717]
### Description

With the switch from version 5.85.7 to version 5.86.0-alpha001
I get messages
> Possible Performance degration, blacklist 'GetVersion_ById {LoweredPackageId = true;
                 NormalizedVersion = false;}'
then in the end
>  Please try to relax some conditions or resolve the conflict manually (see http://fsprojects.github.io/Paket/nuget-dependencies.html#Use-exactly-this-version-constraint).

Pulling the packages mentioned alone works fine.
I presume that the cache then is filled with .json files after i did it for all breaking packages
it works.

>  - unittest-cpp.vc140 is pinned to 1.4.0.14
Source 'https://www.nuget.org/api/v2' exception: System.Exception: All possible sources are already blac - 2_https://www.nuget.org/api/v2/Packages?$filter=(Id eq 'unittest-cpp.vc140') and (NormalizedV - 2_https://www.nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (No - 2_https://www.nuget.org/api/v2/Packages?$filter=(Id eq 'unittest-cpp.vc140') and (Version eq  - 2_https://www.nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (Ve - 2_https://www.nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (Version eq '1.4.0.14')
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Paket.NuGetCache.tryAndBlacklistUrl@478-7.Invoke(Tuple`2 _arg4)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
Source 'http://someipaddress:9001/repository/xxxxx-internal' exception: System.Exception: error ---> System.Exception: Could not retrieve data from 'http://someipaddress:9001/repository/xxxxx-internal/Packages(Id='unittest-cpp.vc140',Version='1.4.0.14')' ---> Paket.Utils+RequestFailedException: Request to 'http://someipaddress:9001/repository/xxxxx-internal/Packages(Id='unittest-cpp.vc140',Version='1.4.0.14')' failed with: 'NotFound'
   at Paket.Utils.failIfNoSuccess@465-5.Invoke(RequestFailedInfo _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at Paket.Utils.getFromUrl@655-8.Invoke(Exception _arg4)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---
   at Paket.NuGetV2.getDetailsFromNuGetViaODataFast@367-1.Invoke(FSharpChoice`2 _arg5)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
Source 'http://someipaddress:9001/repository/xxxxx-internal-unstable' exception: System.Exception: All po - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(Id eq 'unitte - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(tolower(Id) e - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(Id eq 'unitte - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(tolower(Id) e - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (Version eq '1.4.0.14')
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Paket.NuGetCache.tryAndBlacklistUrl@478-7.Invoke(Tuple`2 _arg4)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
Something failed in GetPackageDetails, trying again with force: Couldn't get package details for package unittest-cpp.vc140 1.4.0.14 on any of ["https://www.nuget.org/api/v2";
 "http://someipaddress:9001/repository/xxxxx-internal";
 "http://someipaddress:9001/repository/xxxxx-internal-unstable"].
Source 'https://www.nuget.org/api/v2' exception: System.Exception: All possible sources are already blac - 2_https://www.nuget.org/api/v2/Packages?$filter=(Id eq 'unittest-cpp.vc140') and (NormalizedV - 2_https://www.nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (No - 2_https://www.nuget.org/api/v2/Packages?$filter=(Id eq 'unittest-cpp.vc140') and (Version eq  - 2_https://www.nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (Ve - 2_https://www.nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (Version eq '1.4.0.14')
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Paket.NuGetCache.tryAndBlacklistUrl@478-7.Invoke(Tuple`2 _arg4)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
Source 'http://someipaddress:9001/repository/xxxxx-internal' exception: System.Exception: error ---> System.Exception: Could not retrieve data from 'http://someipaddress:9001/repository/xxxxx-internal/Packages(Id='unittest-cpp.vc140',Version='1.4.0.14')' ---> Paket.Utils+RequestFailedException: Request to 'http://someipaddress:9001/repository/xxxxx-internal/Packages(Id='unittest-cpp.vc140',Version='1.4.0.14')' failed with: 'NotFound'
   at Paket.Utils.failIfNoSuccess@465-5.Invoke(RequestFailedInfo _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at Paket.Utils.getFromUrl@655-8.Invoke(Exception _arg4)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---
   at Paket.NuGetV2.getDetailsFromNuGetViaODataFast@367-1.Invoke(FSharpChoice`2 _arg5)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
Source 'http://someipaddress:9001/repository/xxxxx-internal-unstable' exception: System.Exception: All po - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 1_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages(Id='unittest-cpp.vc140 - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(Id eq 'unitte - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(tolower(Id) e - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(Id eq 'unitte - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(tolower(Id) e - 2_http://someipaddress:9001/repository/xxxxx-internal-unstable/Packages?$filter=(tolower(Id) eq 'unittest-cpp.vc140') and (Version eq '1.4.0.14')
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Paket.NuGetCache.tryAndBlacklistUrl@478-7.Invoke(Tuple`2 _arg4)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
    Package not available.
      Message: Unable to retrieve package details for 'unittest-cpp.vc140'-1.4.0.14

We use 4 feeds internally.
1) Nuget
2) 3 internal feeds using Nexus (version OSS 3.3.2-02)

### Known workarounds
Exclude packages that fail the resolver (by commenting them out), rerun paket update, then later add them again, rerun update, until it works.

Also just adding
version 5.85.7
on top of your paket.dependencies helps.

**Comment by matthid** [comment]
Yes please see https://github.com/fsprojects/Paket/issues/2640 We are trying to figure out why paket is asking the wrong sources.

**Comment by matthid** [comment]
I think we finally solved this, please report back with latest (https://github.com/fsprojects/Paket/releases/tag/5.92.4)

**Comment by b0urb4k1** [comment]
It works as intended now.
Thank you as always for your great work guys.
