### ISSUE TITLE
Including NETStandard.Library for exclusively net461-projects

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#2718]
When doing a `paket update` for a .Net 4.6.1 project that only has net461 references, paket includes a .Net Core-related artifact that breaks the toolchains – ProjectCracker, FSAutoComplete, xbuild and FSharp.Compiler.Service.

Paket version: 5.92.1, 5.92.3.

**Comment by matthid** [comment]
I have no idea what we changed there besides `storage: none` but I guess you are not using that.

**Comment by haf** [comment]
I isolated it. It's because this line is added:

```
   </Choose>
+  <Import Project="..\..\packages\NETStandard.Library\build\NETStandard.Library.targets" Condition="Exists('..\..\packages\NETStandard.Library\build\NETStandard.Library.targets')" Label="Paket" />
 </Project>
```

So this is related to https://github.com/fsprojects/Paket/issues/2616#issuecomment-326290269 and possibly:

 - https://github.com/fsharp/FSharp.Compiler.Service/issues/795#issuecomment-325214740

**Comment by haf** [comment]
So I think one solution to this it to special-case the brokenness that is .Net Core from Paket's side. It's a sad state when releases for unrelated DLLs that will never be invoked by my app, are causing our development team to completely halt for WEEKS.

**Comment by forki** [comment]
> "special-case the brokenness that is .Net Core from Paket's side"

O_o - what exactly? where is it doing the wrong thing?

**Comment by haf** [comment]
Let's take expecto as an example.

It depends like this:

<img width="446" alt="screen shot 2017-09-04 at 16 28 50" src="https://user-images.githubusercontent.com/193115/30030554-2b8fcc1a-918e-11e7-9750-1d1f50e1b18d.png">

I don't think netstandard dependencies should be installed at all, in neither paket.lock nor in the fsproj file when there's a restriction for net461 in paket.dependencies and also all fsproj files are compiling against net 4.6.1.

**Comment by matthid** [comment]
There is an easy solution to that. Package Expecto correctly such that is has a group for the full framework

**Comment by forki** [comment]
Yes I agree. if you restrict to `framework: net461` (see https://fsprojects.github.io/Paket/dependencies-file.html#Framework-restrictions) in deps file then they should not be added.

(until other transitive deps like Argu or .. require them anyways)

with "paket why NETStandard.Library" you can see where it comes from

**Comment by haf** [comment]
@matthid It's not just Expecto.

**Comment by forki** [comment]
@matthid right. it prefers the netstandard

**Comment by matthid** [comment]
Actually, @forki you are correct.
At this time paket doesn't consider net461 to be compatible with netstandard16 so it should work for this case. But it doesn't make the package correctly packaged and later NuGet version will pick the netstandard group (like future paket versions might)


@haf Yes it is sad but we had to go through this with FSharp.Core already. Packages need to be packaged correctly or package managers cannot work...

**Comment by haf** [comment]
Paket has worked just fine for years until you added this "feature" though. Also, see my comment above.

**Comment by haf** [comment]
Furthermore, isn't it very clear that net461 is NOT compatible with net core? Just because you compat matrix says it is, it's very clear that the .net core team hasn't tested backward compatibility.

**Comment by matthid** [comment]
The same way I could say the package worked correctly until you added the netstandard group ;)

**Comment by haf** [comment]
Yes, but if I remove .net Core support from all my nugets people get angry. It's a trade-off.

**Comment by haf** [comment]
Plus, it's not me who added it in the first place, it's a large range of contributors who obviously didn't understand the intricacies of you matrix.

**Comment by matthid** [comment]
All you need to do is add another dependency group for the full framework and paket will pick that up ;)

Like what do you want us to do? We can provide a build of paket without netstandard support, but this means you cannot use a lot of libraries which no longer provide full framework builds so you will be broken at other places.

**Comment by haf** [comment]
What I would like is to be able to opt-out of any netstandard references being incorporated in my projects.

**Comment by matthid** [comment]
Like I said this will probably break you as well

**Comment by matthid** [comment]
> with "paket why NETStandard.Library" you can see where it comes from

**Comment by haf** [comment]
Ok, I see your point. Let's suppose I change to groups. I've gone through deps with `why` now. Here's one https://www.nuget.org/packages/Aether/

With why:

```
-> Our.Internal.Lib
  -> Chiron
    -> Aether
      -> NETStandard.Library
```

But Aether has the right groups, doesn't it? So it should not include NETStandard, when I've added the net461 restriction?

**Comment by forki** [comment]
ok I just did:

    source https://www.nuget.org/api/v2
    
    framework: net461
    nuget expecto

and I'm getting:

**    RESTRICTION: == net461
    NUGET
      remote: https://www.nuget.org/api/v2
        Argu (3.7)
        Expecto (5.0.1)
          Argu (>= 3.7)
          FSharp.Core (>= 4.1.12)
          Mono.Cecil (>= 0.10.0-beta5)
        FSharp.Core (4.2.3)
        Mono.Cecil (0.10.0-beta6)

**Comment by haf** [comment]
I see – I tried upgrading everything to .net core this weekend and left a netstandard ref in there. Rerunning it now; I may have wasted the Paket team's time, but it does indeed crash the dev env.

**Comment by matthid** [comment]
Yep they seem to be packaged correctly and it should work with the correct framework restrictions. Can you post `paket.dependencies`?

(I'd still urge you to change Expecto packaging otherwise it will break with next framework update)

**Comment by forki** [comment]
ok aether has.

    .NETFramework 4.5
       FSharp.Core (>= 4.1.0)

    .NETStandard 1.6
      FSharp.Core (>= 4.1.0)
     NETStandard.Library (>= 1.6.1)

**Comment by haf** [comment]
Indeed fixing deps causes only some NETStandard references.

I'll see what I can do with albacore then for groups. It's just heavy to pull that one forward with changes to infra.

**Comment by forki** [comment]
works as well:

    RESTRICTION: == net461
    NUGET
      remote: https://www.nuget.org/api/v2
        Aether (8.2)
          FSharp.Core (>= 4.1)
        FSharp.Core (4.2.3)

**Comment by forki** [comment]
@haf we are deeply sorry for all the trouble, but we're really only trying to do the right thing here ;-)

**Comment by haf** [comment]
@forki Yeah, thanks. Are your dev envs also broken due to the included ref to NETStandard.Library though? Because as you say, some nugets are only targeting netstandardx.y

**Comment by matthid** [comment]
Sometimes I may sound harsh but I only try to get to the point quickly, sorry for that

**Comment by haf** [comment]
@matthid I sound harsh too, it's alright with me ;)

**Comment by forki** [comment]
> Are your dev envs also broken due to the included ref to NETStandard.Library though

.NET "Standard" as we call it (quotes are important here) is one of the major sources for trouble in the whole ecosystem and yes that includes myself and my coworkers.
But as @matthid said, if you just exclude it completely then it won't work because many libs only ship netstandardxx these days...

**Comment by matthid** [comment]
Correctly packaging is the best option at the moment and the most important package (FSharp.Core) is done :)

**Comment by enricosada** [comment]
@matthid @forki i see lot of error for that import.

Is it really necessary to auto-import from nupkg in the old fsproj/csproj?

```
+  <Import Project="..\..\packages\NETStandard.Library\build\NETStandard.Library.targets" Condition="Exists('..\..\packages\NETStandard.Library\build\NETStandard.Library.targets')" Label="Paket" />
```

that's the main cause of error atm (like xbuild fail to parse that target, so mono 5 doesnt work etc).

**Comment by forki** [comment]
You mean explicitly black listing that one? I'm not against it. But why
can't they express that in the package itself?

Am 04.09.2017 5:58 nachm. schrieb "Enrico Sada" <notifications@github.com>:

@matthid <https://github.com/matthid> @forki <https://github.com/forki> i
see lot of error for that import.

Is it really necessary to auto-import from nupkg in the old fsproj/csproj?

+  <Import Project="..\..\packages\NETStandard.Library\build\NETStandard.Library.targets"
Condition="Exists('..\..\packages\NETStandard.Library\build\NETStandard.Library.targets')"
Label="Paket" />

that's the main cause of error atm (like xbuild fail to parse that target,
so mono 5 doesnt work etc).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2718#issuecomment-326993563>,
or mute the thread

**Comment by matthid** [comment]
@enricosada Technically from the nuget package it clearly is.

Also I think you want to get the shims for net461 and I think this target file is adding the required "magic" for these cases.

I'm not a huge fan of adding such hacks to paket itself. This will just hurt the one person who needs it and is doing everything correctly.

I can see how this is a bad situation, but with proper msbuild everything is clearly working so I'm really against such a hack for xbuild.

Also there are several workarounds, like adding `nuget Netstandard.Library <2` to the depsfile and updating msbuild as well as proper packaging.

**Comment by enricosada** [comment]
I am not speaking about blacklisting that package.

The auto import target/props files from nupkg existed also before? or is a new sdk thing? is not possibile to enable that just for new sdk projects? so old projects continue to work

**Comment by forki** [comment]
No. That always existed. Nothing new here

Am 04.09.2017 6:14 nachm. schrieb "Enrico Sada" <notifications@github.com>:

**Comment by matthid** [comment]
Yes importing props and targets is quite old and supported quite a while.

**Comment by enricosada** [comment]
Ok, thx for clarification!

**Comment by haf** [comment]
Is this correctly done now? https://www.nuget.org/packages/Suave.Locale/

(Ignoring the fact that I haven't updated the main Suave package yet)

**Comment by matthid** [comment]
@haf yes, though if it's the only group it doesn't really matter

**Comment by haf** [comment]
I released a new Suave, too https://www.nuget.org/packages/Suave/2.3.0-beta

Thanks @matthid
