### ISSUE TITLE
Enable exclusion of dependent packages in paket.references

### ISSUE THREAD

**Issue by mhoyer** [fsprojects/Paket#272]
Some nuget packages rely on a long dependency chain containing assemblies/packages that are not required for the actual use case of a given `.csproj`.

Therefore, I would like to recommend an approach to exclude such assembly references.

Quick idea for `paket.references`:

```
Prism 
- Prism.Interactivity
```

**Comment by hmoush95** [comment]
Sorry to bring up an old issue. Is this a thing that can be done now without going the Strict references route? I'd like to be able to include/exclude certain dependencies for a certain direct reference but not need to do the same for ALL references
