### ISSUE TITLE
Storage: none and relative path

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#2728]
### Description

When the option `storage: none` is used in `paket.dependencies`, all references are changed from

`../package/bla/version/`

to 
`../../.../.nuget/packages/bla/version`

This is as expected. The problem is that the relative path is dependent on the checkout location of the repository, which is a problem for teams, build servers etc.

### Expected behavior

The path to the referenced assembly should not be dependent on the location of the checked-out repository.

**Comment by forki** [comment]
Yes this is an important issue. So actually we only support storage:none for new style csproj with .NET sdk. In that model all paths are gone

**Comment by matthid** [comment]
As I said on slack: We could generate a props file with the correct property and use that in the generation. But this is actually up-for-grabs and not considered an issue (at least not by me)

**Comment by matthid** [comment]
To clarify with issue I mean bug. It works as implemented but we'd like to see that implemented(ie pr is welcome)

**Comment by matthid** [comment]
See some more suggestions about the solution in https://github.com/fsprojects/Paket/issues/2836

**Comment by enricosada** [comment]
Closing, dupe of https://github.com/fsprojects/Paket/issues/2674
