### ISSUE TITLE
Starting from 5.92.0-beta002 paket.exe hash doesn't match

### ISSUE THREAD

**Issue by inosik** [fsprojects/Paket#2729]
### Description

I install Paket globally via [Scoop][scoop]. While updating the installer manifest today, I noticed that starting from 5.92.0-beta002 the hash in `paket-sha256.txt` and the actual hash of `paket.exe` don't match.

  [scoop]: http://scoop.sh/

### Repro steps

```bash
$ curl -Lo paket.exe https://github.com/fsprojects/Paket/releases/download/5.92.4/paket.exe
$ curl -Lo paket-sha256.txt https://github.com/fsprojects/Paket/releases/download/5.92.4/paket-sha256.txt
$ sha256sum -c paket-sha256.txt
```

The tools should be available on Unix or in Git Bash on Windows.

### Expected behavior

```
paket.exe: OK
```

### Actual behavior

```
paket.exe: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

### Known workarounds

None.

**Comment by matthid** [comment]
See discussion in https://github.com/fsprojects/Paket/issues/2725 this was probably introduced with signing the paket.exe

**Comment by matthid** [comment]
```
$ curl -Lo paket.exe https://github.com/fsprojects/Paket/releases/download/5.92.5/paket.exe
$ curl -Lo paket-sha256.txt https://github.com/fsprojects/Paket/releases/download/5.92.5/paket-sha256.txt
$ sha256sum -c paket-sha256.txt
paket.exe: OK
```

Thanks for reporting this.
