### ISSUE TITLE
--force does not override paket.restore.cached

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#2731]
### Description

Line 391 in `RestoreProcess.fs` is quite clear, `paket.restore.cached` before `force`. Will send patch later tonite if the problem is acknowledged.

**Comment by baronfel** [comment]
I ran into this last night after locally deleting my packages folder. I'd
be in favor of this change to restore the behavior of the force switch.

**Comment by matthid** [comment]
Please elaborate or send the pr to discuss. i'm afraid I don't quite get it.

**Comment by trondd** [comment]
I can understand that the description is not of the highest standard :-). I'll try to elaborated.

As far as I can tell, the `--force` switch does not work when the file `paket.restore.cached` is present. This is unfortunate since it means that `paket.local` is useless. After rebuilding the locally references package I frequently do `paket restore` to update the referencing solution or project. But this does not seem to work any more.

I would expect the force switch to take presedence over the cached version.

**Comment by matthid** [comment]
Oh yes a PR would definitely be accepted :)

**Comment by trondd** [comment]
I think this should solve my problem: https://github.com/fsprojects/Paket/pull/2734

**Comment by enricosada** [comment]
Closing, fixed by #2734
