### ISSUE TITLE
"redirects: force" at the group level doesn't seem to do anything

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2739]
I am desperately fighting "FileLoadException: Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein." (the assembly manifest does not match the reference, basically a version mismatch).

After adding "redirects: force" to one nuget after another, I got the idea to just add it to the group - which does not seem to do anything.

**Comment by forki** [comment]
I'm working on this. There is an open pr where I still need to fix tests.
But I discovered that this setting was not possible for groups yet. It will
be after my pr is merged

Am 07.09.2017 7:24 nachm. schrieb "Lukas Rieger" <notifications@github.com>:

**Comment by 0x53A** [comment]
I also have another issue, where a redirect doesn't work. But this may already be solved, I am not yet running the latest version. Will try the latest tomorrow...:


```
System.IO.FileLoadException: Die Datei oder Assembly "System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/dev/p4/2017PrecastTim/TimPrecast/BuildOutput/x64/Debug/
LOG: Ursprünglicher PrivatePath = NULL
Aufruf von Assembly : RoslynPad.Roslyn, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: Diese Bindung startet im default-Load-Kontext.
LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\dev\p4\2017PrecastTim\TimPrecast\BuildOutput\x64\Debug\TIM.exe.Config
LOG: Die Hostkonfigurationsdatei wird verwendet: 
LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config wird verwendet.
LOG: In der Anwendungskonfigurationsdatei wurde eine Umleitung gefunden. 4.0.0.0 wird nach 4.0.1.0 umgeleitet.
LOG: Verweis nach der Richtlinie: System.Threading.Thread, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Download von neuem URL file:///C:/dev/p4/2017PrecastTim/TimPrecast/BuildOutput/x64/Debug/System.Threading.Thread.DLL.
WRN: Der Vergleich des Assemblynamens führte zum Konflikt: Buildnummer.
ERR: Das Setup der Assembly konnte nicht abgeschlossen werden (hr = 0x80131040). Die Suche wurde beendet.
</ExceptionString></InnerException></Exception></TraceRecord>
```

I have this in my paket.dependencies:

```
...
nuget RoslynPad.Editor.Windows redirects:force
nuget AvalonEdit redirects:force
nuget Microsoft.CodeAnalysis redirects:force
nuget System.Threading.Thread redirects:force
nuget Netstandard.Library redirects:force
...

```
C:\dev\p4\2017PrecastTim\TimPrecast>.paket\paket why System.Threading.Thread --details
Paket version 5.84.2
NuGet System.Threading.Thread 4.3 is a direct (paket.dependencies) dependency.
It's a part of following dependency chains:

-> Microsoft.CodeAnalysis
  -> Microsoft.CodeAnalysis.CSharp.Workspaces
    -> Microsoft.CodeAnalysis.CSharp
      -> Microsoft.CodeAnalysis.Common
        -> System.Threading.Thread (>= 4.3)

-> Microsoft.CodeAnalysis
  -> Microsoft.CodeAnalysis.CSharp.Workspaces
    -> Microsoft.CodeAnalysis.Workspaces.Common
      -> Microsoft.CodeAnalysis.Common
        -> System.Threading.Thread (>= 4.3)

-> Microsoft.CodeAnalysis
  -> Microsoft.CodeAnalysis.VisualBasic.Workspaces
    -> Microsoft.CodeAnalysis.VisualBasic
      -> Microsoft.CodeAnalysis.Common
        -> System.Threading.Thread (>= 4.3)

-> Microsoft.CodeAnalysis
  -> Microsoft.CodeAnalysis.VisualBasic.Workspaces
    -> Microsoft.CodeAnalysis.Workspaces.Common
      -> Microsoft.CodeAnalysis.Common
        -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp
      -> Microsoft.CodeAnalysis.Common
        -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp.Scripting
      -> Microsoft.CodeAnalysis.CSharp
        -> Microsoft.CodeAnalysis.Common
          -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp.Scripting
      -> Microsoft.CodeAnalysis.Scripting.Common
        -> Microsoft.CodeAnalysis.Common
          -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp.Workspaces
      -> Microsoft.CodeAnalysis.CSharp
        -> Microsoft.CodeAnalysis.Common
          -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp.Workspaces
      -> Microsoft.CodeAnalysis.Workspaces.Common
        -> Microsoft.CodeAnalysis.Common
          -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp
        -> Microsoft.CodeAnalysis.Common
          -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp.Features
      -> Microsoft.CodeAnalysis.CSharp.Workspaces
        -> Microsoft.CodeAnalysis.CSharp
          -> Microsoft.CodeAnalysis.Common
            -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp.Features
      -> Microsoft.CodeAnalysis.CSharp.Workspaces
        -> Microsoft.CodeAnalysis.Workspaces.Common
          -> Microsoft.CodeAnalysis.Common
            -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn
    -> Microsoft.CodeAnalysis.CSharp.Features
      -> Microsoft.CodeAnalysis.Features
        -> Microsoft.CodeAnalysis.Workspaces.Common
          -> Microsoft.CodeAnalysis.Common
            -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp.Scripting
        -> Microsoft.CodeAnalysis.CSharp
          -> Microsoft.CodeAnalysis.Common
            -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp.Scripting
        -> Microsoft.CodeAnalysis.Scripting.Common
          -> Microsoft.CodeAnalysis.Common
            -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp.Workspaces
        -> Microsoft.CodeAnalysis.CSharp
          -> Microsoft.CodeAnalysis.Common
            -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp.Workspaces
        -> Microsoft.CodeAnalysis.Workspaces.Common
          -> Microsoft.CodeAnalysis.Common
            -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp.Features
        -> Microsoft.CodeAnalysis.CSharp.Workspaces
          -> Microsoft.CodeAnalysis.CSharp
            -> Microsoft.CodeAnalysis.Common
              -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp.Features
        -> Microsoft.CodeAnalysis.CSharp.Workspaces
          -> Microsoft.CodeAnalysis.Workspaces.Common
            -> Microsoft.CodeAnalysis.Common
              -> System.Threading.Thread (>= 4.3)

-> RoslynPad.Editor.Windows
  -> RoslynPad.Roslyn.Windows
    -> RoslynPad.Roslyn
      -> Microsoft.CodeAnalysis.CSharp.Features
        -> Microsoft.CodeAnalysis.Features
          -> Microsoft.CodeAnalysis.Workspaces.Common
            -> Microsoft.CodeAnalysis.Common
              -> System.Threading.Thread (>= 4.3)
```

my app.config:

```
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="System.Threading.Thread" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.0.1.0" />
  </dependentAssembly>
```

There are way too many versions of this dll in my packages dir, I would guess that one overwrites another one:
![image](https://user-images.githubusercontent.com/4236651/30177027-b4144e8a-9404-11e7-85ad-ea6eb337d029.png)


Will investigate tomorrow.

**Comment by 0x53A** [comment]
should be fixed with https://github.com/fsprojects/Paket/pull/2666
