### ISSUE TITLE
paket cache fallback writes absolute path into paket.lock

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2744]
> Paket version 5.92.6

For some reason paket thinks [xunit.runner.visualstudio](https://www.nuget.org/packages/xunit.runner.visualstudio/2.2.0) was unlisted:

on paket update
![image](https://user-images.githubusercontent.com/4236651/30211330-d6dbd4be-94a0-11e7-8285-d904b8536d0e.png)

That was surprising, but I don't really care where it gets the version from, so it's ok.

BUT it wrote the absolute path, not the relative path, into the lockfile, which will break CI: 

```
  remote: .\Other\NugetCustom
    Argu (3.9.9) - redirects: force
    FsPickler (3.2.1)
    FsPickler.Json (3.2.1)
      FsPickler (3.2.1)
      Newtonsoft.Json (>= 6.0.5)
    Mvvm (0.8.16117892)
    WindowsAPICodePack-Core (7.1.2)
  remote: C:\dev\p4\2017PrecastTim\TimPrecast\Other\NugetCache
    xunit.runner.visualstudio (2.2.0) - version_in_path: true
```

as you can see, it correctly wrote the relative path for the other source above.

my dependencies file looks like this:

```
source .\Other\NugetCustom
source https://api.nuget.org/v3/index.json
cache .\Other\NugetCache versions:all

framework: net461

...

nuget xunit.runner.visualstudio version_in_path:true

```

**Comment by forki** [comment]
just tried that deps file and getting

    RESTRICTION: == net461
    NUGET
      remote: https://api.nuget.org/v3/index.json
        xunit.runner.visualstudio (2.2.0) - version_in_path: true

**Comment by 0x53A** [comment]
yes, I also can't reproduce the unlisting anymore - either nuget bug, or the author unlisted and relisted?

**Comment by forki** [comment]
not talking about unlisting. I can't get the weird lock file

**Comment by 0x53A** [comment]
hm, me neither. I tried explicitly referencing an unlisted package, but that also created the correct one. Will reopen if I have a reliable repro.

Thanks.
