### ISSUE TITLE
v5.92.x does not restore

### ISSUE THREAD

**Issue by et1975** [fsprojects/Paket#2747]
### Description

Presence of `paket-files` seems to mislead paket into believing everything is present and it exits with 
> Last restore is still up to date.

### Repro steps

1. checkout Fable
2. run build
3. if you didn't have `paket-files` that match the `paket.dependencies` observe it succeed
4. delete `packages`
5. run the build again and observe it fail with 
>Cannot open assembly 'packages/FAKE/tools/FAKE.exe': No such file or directory.

### Expected behavior
Expect it to check if the packages exist. 

### Actual behavior

Content of `paket-files` can easily go out of sync with packages, see this [Travis example]( https://travis-ci.org/fable-elmish/browser/builds/273255982?utm_source=email&utm_medium=notification).
I don't know what caused this and no clear course for fixing it.
 
### Known workarounds

Locally: delete `paket-files`

**Comment by forki** [comment]
I think you need to gitignore the paket-files folder and it should work.

@matthid we should make that much more visible that this is the issue.

Am 09.09.2017 10:22 vorm. schrieb "Eugene Tolmachev" <
notifications@github.com>:

**Comment by et1975** [comment]
Hm, I had it in my `.gitignore`, but apparently I've added it in the same commit.

**Comment by matthid** [comment]
should we change the up to date message?

**Comment by forki** [comment]
Yes. I think that's minimum. We should also announce it more openly and put
it in the FAQ

Am 09.09.2017 12:13 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:
