### ISSUE TITLE
Make `paket add` accept multiple NuGet packages

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Paket#2756]
In some rare cases (Forge scaffolding, for example) I'd want to add multiple packages at the same time. At the moment, we add packages one-by-one in the loop, what means that the whole process (starting Paket, resolver, I/O) is run multiple times... which adds a lot of overhead and is pretty long operation. It'd be really helpful to allow us add those packages at once.

Alternative solution would be adding flag to `paket add` that would disable resolver - in such case command would just add entry in `paket.dependency` without changing `paket.lock` and project files.

**Comment by matthid** [comment]
I vote for fixing the startup perf + add the flag to skip the resolver.

Sadly we will probably choose the hacky solution as it is easier to implement... I don't think I'm able to fix this anytime soon.

Skipping the resolver is probably easy, fixing the startup perf is not

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/2757
