### ISSUE TITLE
Constraining dependencies 

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#2759]
### Description

I have a project with `<TargetFrameworks>netstandard1.6;net462</TargetFrameworks>`  If I use paket to do the restore I get 

```
 Errors in /app/paket-constrain-framework.fsproj
      Package System.Security.Cryptography.OpenSsl 4.4.0 is not compatible with net462 (.NETFramework,Version=v4.6.2). Package System.Security.Cryptography.OpenSsl 4.4.0 supports:
        - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
        - netstandard1.6 (.NETStandard,Version=v1.6)
        - netstandard2.0 (.NETStandard,Version=v2.0)
      One or more packages are incompatible with .NETFramework,Version=v4.6.2.
```

### Repro steps

https://github.com/TheAngryByrd/paket-constrain-framework

Let me know if there's anything confusing or odd.

### Expected behavior

Able to build 

### Actual behavior

Receive error message as shown above.

### Known workarounds

Use nuget 😿

**Comment by forki** [comment]
/cc @matthid 

we have:

    System.Security.Cryptography.OpenSsl (4.4) - restriction: || (&& (>= dnxcore50) (>= netstandard1.6)) (&& (>= netstandard1.6) (< monotouch) (< xamarintvos) (< xamarinwatchos) (< xamarinios) (< xamarinmac))

isn't net462 supposed to be compatible to netstandard1.6?

**Comment by 0x53A** [comment]
Not yet. We are still at Tooling Level 1, so only netstandard1.5

![image](https://user-images.githubusercontent.com/4236651/30369906-414f1e0e-9876-11e7-9df8-ac14b517b1be.png)

**Comment by TheAngryByrd** [comment]
I guess the problem I see is it's choosing the netstandard FSharp.Core package over the netfull for net462.

**Comment by TheAngryByrd** [comment]
Maybe it's because it's labeled as All Frameworks for 4.1.17 ?

**Comment by forki** [comment]
why are you pinning to 4.1.7?

**Comment by TheAngryByrd** [comment]
Just to be clear it's [4.1.17](https://www.nuget.org/packages/FSharp.Core/4.1.17)

.If you're a library author aren't you supposed to choose the lowest version you can? Or is that advice wrong now?

**Comment by forki** [comment]
the problem ist that version doesn't work with netcore/netstandard

**Comment by TheAngryByrd** [comment]
The dependencies says netstandard1.6 and all frameworks. Is that wrong?  Should that be unlisted then?

**Comment by forki** [comment]
no idea tbh

**Comment by TheAngryByrd** [comment]
Doesn't really matter, FSharp.Core 4.2.3 produces the same problem.

**Comment by forki** [comment]
yes I think the FSHarp.Core is unrelated. What I wonder is why we have the following:

![image](https://user-images.githubusercontent.com/57396/30372096-115adaba-987d-11e7-81f0-4c7e73d7c715.png)

@matthid shouldn't this be filtered out?

**Comment by TheAngryByrd** [comment]
Paket 5.91.0 does not have the issue, seems to start with 5.92.1.

**Comment by forki** [comment]
yes that was when @matthid splitted the files. I assume it's related

**Comment by matthid** [comment]
what does paket why openssl say? (maybe we want an option to track only a particular framework in the future)

> shouldn't this be filtered out

yes maybe

> seems to start with 5.92.1

not sure why. I splitted the files but the observable behavior of nuget shouldn't have changed (I mean we basically should forward the same info)

**Comment by forki** [comment]
*should* ;-)

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/30373075-668efdf6-9880-11e7-8967-a20df1e6eaf0.png)

**Comment by matthid** [comment]
Yes that path shouldn't exist after restricting to net462 ..

**Comment by forki** [comment]
just took a quick look. looks like the new files are not filterd by the targetframework filter

**Comment by matthid** [comment]
- maybe one of the framework restriction simplifications is invalid 
- or the framework restrictions of the nuget packages are not read in correctly
- something in delegating the restrictions in the resolver itself.

**Comment by matthid** [comment]
or yes the files are written incorrectly

**Comment by forki** [comment]
the are all the same ;-)

**Comment by matthid** [comment]
but tbh the restriction in the lockfile looks aready fishy

**Comment by forki** [comment]
that is another issue. the current issue is that we generate a files without filtering at all.

**Comment by forki** [comment]
small correction. it was filtering, but since we didn't clear the list that was not really effective. Anyway new version is under way and should be available in a minute

**Comment by forki** [comment]
ok 5.96.1 is available

**Comment by forki** [comment]
and dotnet restore seems to work for your sample

**Comment by forki** [comment]
you might need to clean obj and paket-files folders

**Comment by TheAngryByrd** [comment]
🎸

**Comment by matthid** [comment]
@haf I remeber you encountered probably the same error but cannot find the issue/pr. please try again
