### ISSUE TITLE
Paket pack seems to evaluate all templates it finds even when using the --template switch

### ISSUE THREAD

**Issue by wastaz** [fsprojects/Paket#2765]
### Description

When running `paket pack` with the `--template` switch it seems that paket still goes looking at other `paket.template` files than the one provided. This is all fine as long as all other paket.template files it can find are ok, but if for some reason they arent (in this case because of only partially compiling the solution) paket still fails even though the packing of the template file given by the `--template` switch would work fine. 

### Repro steps

Check out the following reproduction repo: https://github.com/wastaz/paket-template-repro
Run `./build.sh targetHost=ProjectA`

### Expected behavior

This project contains two projects, ProjectA and ProjectB, each of these has its own paket.template file (and is meant to be pushed as two separate nugets). They have no references to each other.
By running `./build.sh targetHost=ProjectA` it should build only ProjectA and then pack only ProjectA. So I expect this to correctly produce a ProjectA nuget package.

### Actual behavior

However paket fails with the following message.
I've also tried running this without FAKE, and I get the exact same output and problem.

```
Starting Target: ProGetPack (==> Build)
C:\oss-code\PaketTemplateRepro\.paket\paket.exe pack output "../build"  --version  0.1.0.0 --template  ./ProjectA/paket.template
Paket version 5.96.2
Please use the new syntax: 'output' is the default argument and should be omitted.
Performance:
 - Runtime: 923 milliseconds
Paket failed with
-> DirectoryNotFoundException: Could not find a part of the path 'C:\oss-code\PaketTemplateRepro\ProjectB\bin\Release\ProjectB.dll'.
Running build failed.
Error:
System.Exception: Error during packing ..
   at Fake.Paket.Pack@128-4.Invoke(String message) in D:\code\FAKE\src\app\FakeLib\PaketHelper.fs:line 128
   at Fake.Paket.Pack(FSharpFunc`2 setParams) in D:\code\FAKE\src\app\FakeLib\PaketHelper.fs:line 128
   at FSI_0005.Build.clo@54-8.Invoke(Unit _arg4)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
```

Notice how what it is complaining about is that it could not find ProjectB.dll, which is of course correct since we have not compiled ProjectB and we do not need ProjectB in order to pack ProjectA.

### Known workarounds

Always compile everything or remove all other paket.template files...

**Comment by lexarchik** [comment]
it is due to my fix for #1848.
I see two solutions:
- ban usage `--include-referenced-projects` with `--template ...` and evaluate only one template with `--template`
- evaluate all templates with `--template` only if `--include-referenced-projects`

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/2766

**Comment by lexarchik** [comment]
@wastaz do you use `--include-referenced-projects` flag with pack command (or in template file)?

**Comment by wastaz** [comment]
@lexarchik No, I do not.
