### ISSUE TITLE
Paket fails to download HtmlAgilityPack 1.4.9

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/Paket#277]
Says the file is corrupt, other versions work fine

**Comment by ctaggart** [comment]
Was there a reason why that package was corrupt? `FSharpx.Collections` is now being served corrupt from the NuGet Gallery. :/ https://github.com/fsprojects/FSharpx.Collections/issues/21

**Comment by forki** [comment]
No we don't know the reason
