### ISSUE TITLE
How do I get prerelease packages?

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/Paket#278]
Tried to use paket update --pre to get FSharp.Data 2.1.0-beta, but still stayed at 2.0.15

**Comment by mateuszlewko** [comment]
I think it would be good to have `--prerelease` flag in update command. As far as I know there isn't any/

**Comment by forki** [comment]
Please define this in the dependencies file. We have a gazillion options for that

**Comment by mateuszlewko** [comment]
Okay... 
It's just checking cli help is the first thing I usually do when I don't know how do something instead of reading docs (I didn't know about prerelease keyword in dependencies).

**Comment by forki** [comment]
The problem with doing it in cli is that this is not reflected in the dependencies file. And then next time you have to do it again.
Think about the deps file as source code.

**Comment by mateuszlewko** [comment]
Okay, it makes sense now to omit this in cli.
