### ISSUE TITLE
Paket.Core packaged incorrectly

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2792]
### Description

https://www.nuget.org/packages/Paket.Core

- [X] We should not use the "All Frameworks" group. Instead we need to use the proper group for the framework we package.
- [x] should not reference `FSharp.Compiler.Tools`

This is the same problem which was solved in `FSharp.Core` recently.

**Comment by enricosada** [comment]
The all frameworks is fixed

![image](https://user-images.githubusercontent.com/147243/35287975-e88241b0-0063-11e8-9b3d-4ad0d6eb4396.png)

but reference to `FSharp.Compiler.Tools` remains

**Comment by matthid** [comment]
thanks a lot for taking care of this stuff!
