### ISSUE TITLE
Paket pulling loads of unexpected transitive dependencies

### ISSUE THREAD

**Issue by jamescrowley** [fsprojects/Paket#2799]
### Description

Doing a paket install after deleting our existing paket.lock file results in many new unexpected dependencies. 

### Repro steps

1. Running 5.85.1 (or newer).
2. With the attached paket.dependencies file
[paket.dependencies.txt](https://github.com/fsprojects/Paket/files/1333232/paket.dependencies.txt) we see the following changes to our paket.lock:
[lockChanges.txt](https://github.com/fsprojects/Paket/files/1333214/lockChanges.txt)
3. Note that there are no version changes to primary dependencies referenced in the paket.dependencies file

### Expected behavior

paket install is consistent when primary dependencies have not changed. Or that it is clearer why these additional dependencies have been pulled in

### Actual behavior

Lots of unexpected transitive dependencies.

### Known workarounds

None

**Comment by forki** [comment]
nuking lock file and running install is like doing paket update

**Comment by jamescrowley** [comment]
@forki sorry, was convinced none of the top level package versions were changing as a result of "paket update". Turns out, it is. I'll open seperate ticket to understand why Paket is doing what it is for that specific dependency bump.
