### ISSUE TITLE
.Net "standard" library referenced by an Android project fail after conversion from nuget -> paket

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/Paket#2800]
### Description

I have a .Net "standard" library referenced by a Android project, when the projects are converted to a paket solution I encounter a build failure.  

### Repro steps

I have a before paket conversion at https://github.com/7sharp9/androidTest and a `paket` branch https://github.com/7sharp9/androidTest/tree/paket after  the conversion available.  The nuget version build fine.

```
git clone https://github.com/7sharp9/androidTest -b paket
cd androidTest
dotnet build netstandardLib/netstandardLib.fsproj
msbuild androidTest/androidTest.fsproj
```
### Expected behavior

Build works

### Actual behavior

build fails with:

```
Build FAILED.

"/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj" (default target) (1) ->
(_ResolveAssemblies target) ->
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Identity.Client, Version=1.1.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Perhaps it doesn't exist in the Mono for Android profile? [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error : File name: 'Microsoft.Identity.Client.dll' [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x00124] in <6a0245f99c1849bf83cb02ca9f84914e>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00000] in <6a0245f99c1849bf83cb02ca9f84914e>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver, System.Collections.Generic.ICollection`1[T] assemblies, Mono.Cecil.AssemblyDefinition assembly, System.Boolean topLevel) [0x0015c] in <52b04bb21b54415ab282c60622b3bc28>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Xamarin.Android.Tasks.ResolveAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x0019c] in <52b04bb21b54415ab282c60622b3bc28>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
```

**Comment by 7sharp9** [comment]
detailed msbuild log available here: https://gist.github.com/7sharp9/e0bcee9fcaad3601c3dee702bb5c4b54

**Comment by forki** [comment]
1) you didn't gitignore the `paket-files` folder. The cache file is commited. so subsequent restores think everything is already in place

**Comment by forki** [comment]
(@matthid we should make convert somehow gitignore it!?)

**Comment by forki** [comment]
FileNotFoundException should be gone after nuking of paket-files folder and "paket restore"

**Comment by 7sharp9** [comment]
Let me try in a minute, to conflate stuff further the Xamarin droid linker fails on the nuget  solution in release mode :-(

**Comment by 7sharp9** [comment]
After nuking that folder and paket restore its still the same

**Comment by forki** [comment]
are you sure it's exactly the same message? because now the packages folder should exist

**Comment by 7sharp9** [comment]
```
"/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj" (default target) (1) ->
(_ResolveAssemblies target) ->
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Identity.Client, Version=1.1.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Perhaps it doesn't exist in the Mono for Android profile? [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error : File name: 'Microsoft.Identity.Client.dll' [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x00124] in <6a0245f99c1849bf83cb02ca9f84914e>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00000] in <6a0245f99c1849bf83cb02ca9f84914e>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver, System.Collections.Generic.ICollection`1[T] assemblies, Mono.Cecil.AssemblyDefinition assembly, System.Boolean topLevel) [0x0015c] in <52b04bb21b54415ab282c60622b3bc28>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1445,2): error :   at Xamarin.Android.Tasks.ResolveAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x0019c] in <52b04bb21b54415ab282c60622b3bc28>:0  [/Users/dave.thomas/Projects/androidTest/androidTest/androidTest.fsproj]
```

**Comment by forki** [comment]
TBH I have no idea what is happening. Do you see what is wrong in the fsproj?

**Comment by forki** [comment]
also it's weird that's importing NETStandard.Library 

why are you mixing old and new proj formats?

**Comment by 7sharp9** [comment]
Its just a new droid template from vs4mac, I can't tell whats wrong to be honest, I spent a good few hours yesterday trying to figure out whats going on then decided to file this small repo.

**Comment by forki** [comment]
it is so weird. but will try to dig deeper

**Comment by forki** [comment]
one thing that is not ok is: you did not set TargetFrameworkIdentifier

**Comment by forki** [comment]
and it looks like your TargetFrameworkVersion is 8 - which don't know yet in paket

**Comment by forki** [comment]
let's try something:

    <When Condition="$(TargetFrameworkIdentifier) == 'MonoAndroid' And ($(TargetFrameworkVersion) == 'v7.0' Or $(TargetFrameworkVersion) == 'v7.1')">
      <ItemGroup>
        <Reference Include="Microsoft.Identity.Client">
          <HintPath>..\packages\Microsoft.Identity.Client\lib\monoandroid70\Microsoft.Identity.Client.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>


please set targetframework to MonoAndroid and manually add the 8.0 in that condition.

would that help?

**Comment by matthid** [comment]
> (@matthid we should make convert somehow gitignore it!?)

We could move it to the `.paket` folder or somewhere where stuff is gitignored anyway?

**Comment by forki** [comment]
.paket is not gitignored everywhere

**Comment by 7sharp9** [comment]
Xamarin abuse the TargetFrameworkVersion to represent the Android version, 8 is the latest one.  I can drop it to 7.1

**Comment by forki** [comment]
still you need to set MonoAndroid  to activate the case

**Comment by 7sharp9** [comment]
note: this was the out of the box template for droid I didn't add or remove anything

**Comment by 7sharp9** [comment]
`TargetFrameworkIdentifier` along with TargetFrameworkVersion dropped to `7.1` is making things build, hard to decipher the errors in msbuild, especially as they look to be coming form Mono.Cecil

**Comment by forki** [comment]
ok. good. so we need to add the 8.o to our moniker collection. will do tomorrow.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/31008128-39dbd290-a503-11e7-9ed7-dfa4d8cc3e0b.png)

**Comment by forki** [comment]
5.100.3 will add this automatically. You still need to set TargetFrameworkIdentifier
