### ISSUE TITLE
Add syntax to paket.template to get version constraint from paket.dependencies

### ISSUE THREAD

**Issue by Tarmil** [fsprojects/Paket#2801]
I think it would be quite useful to have a syntax similar to `LOCKEDVERSION` and `CURRENTVERSION` to tell `paket pack` to grab the version constraint for a given dependency from `paket.dependencies`. For example something like this:

```
dependencies
    Paket.Core DEPENDENCIESVERSION
    Fake DEPENDENCIESVERSION group: mygroup
```

which, given the following `paket.dependencies`:

```
source https://api.nuget.org/v3/index.json
nuget Paket.Core ~> 5.100.2
nuget Fake ~> 4.0
group mygroup
nuget Fake >= 5.0.0-alpha
```

would be equivalent to:

```
dependencies
    Paket.Core ~> 5.100.2
    Fake >= 5.0.0-alpha
```

**Comment by inosik** [comment]
This should already be the case. But I think you then need to omit the `dependencies` section from your `paket.template`.

**Comment by sjancke** [comment]
@inosik I guess this is referring to paket.template with "type file". According to https://fsprojects.github.io/Paket/template-files.html#Dependencies dependencies for "type project" are added automatically:

> In a project file, the following dependencies will be added:
> * Any Paket dependency with the range specified in the paket.dependencies 
> [...]

Missed this OP feature also today - had to copy constraints from paket.dependencies for "type file" to get it working...

**Comment by enricosada** [comment]
@eiriktsarpalis added `LOCKEDVERSION` for groups with https://github.com/fsprojects/Paket/pull/2943

**Comment by enricosada** [comment]
Closing.

added with `LOCKEDVERSION-{groupName}`, like `LOCKEDVERSION-NetStandard` (`NetStandard is a group name)

@Tarmil  please open a new issue or reopen if that doesnt work or not enough
