### ISSUE TITLE
pack --include-referenced-projects ignores recursive inter-project dependencies with paket.template

### ISSUE THREAD

**Issue by mbett7** [fsprojects/Paket#2804]
### Description
`pack --include-referenced-projects` misses recursive inter-project dependencies that have a `paket.template` file.

i.e. in a solution with dependencies:
ProjectA -> ProjectB -> ProjectC

If ProjectA and ProjectC were to have `paket.template` files, The packed ProjectA nuspec should have a dependency on ProjectC

### Repro steps
1. Extract [ReferencePackTest.zip](https://github.com/fsprojects/Paket/files/1346184/ReferencePackTest.zip)
2. `paket restore`
3. Build solution
4. Run `pack.cmd`

### Expected behavior
ProjectC is included in ProjectA's nuspec dependencies.

### Actual behavior
It's not.

### Known workarounds
Rollback to paket 4.8.8

**Comment by Gonnagle** [comment]
Was just hitting the exact same issue with 5.156.1. Updating to the latest (5.196.2) seemed to fix the issue.

Based on release notes was probably fixed in [5.195.7](https://github.com/fsprojects/Paket/releases/tag/5.195.7).

**Comment by mbett7** [comment]
Indeed it is.  Thanks!
