### ISSUE TITLE
Paket creating references to incorrect location for PCL Project

### ISSUE THREAD

**Issue by tastyeggs** [fsprojects/Paket#2806]
### Description

Using the latest version of paket (5.100.3), for my Xamarin Forms Package, when my PCL is set to Profile7, it is creating references to `Xamarin.Forms\lib\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20`. Such a directory doesn't exist within the Nuget package, it should really be `portable-win+net45+wp80+win81+wpa81`.

### Repro steps

1. Create a PCL project with Profiley7
2. Install Xamarin.Forms (2.4.0.282) via paket

### Expected behavior

PCL Profile7 projects must link to the dlls in `portable-win+net45+wp80+win81+wpa81` directory

### Actual behavior

The following is generated:
`<When Condition="($(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2' Or $(TargetFrameworkVersion) == 'v4.6.3')) Or ($(TargetFrameworkIdentifier) == '.NETCore' And $(TargetFrameworkVersion) == 'v4.5') Or ($(TargetFrameworkIdentifier) == 'Xamarin.Mac') Or ($(TargetFrameworkProfile) == 'Profile7') Or ($(TargetFrameworkProfile) == 'Profile31') Or ($(TargetFrameworkProfile) == 'Profile32') Or ($(TargetFrameworkProfile) == 'Profile44') Or ($(TargetFrameworkProfile) == 'Profile49') Or ($(TargetFrameworkProfile) == 'Profile78') Or ($(TargetFrameworkProfile) == 'Profile84') Or ($(TargetFrameworkProfile) == 'Profile111') Or ($(TargetFrameworkProfile) == 'Profile151') Or ($(TargetFrameworkProfile) == 'Profile157') Or ($(TargetFrameworkProfile) == 'Profile259')">
      <ItemGroup>
        <Reference Include="Xamarin.Forms.Core">
          <HintPath>..\packages\Xamarin.Forms\lib\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.Core.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="Xamarin.Forms.Platform">
          <HintPath>..\packages\Xamarin.Forms\lib\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.Platform.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="Xamarin.Forms.Xaml">
          <HintPath>..\packages\Xamarin.Forms\lib\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.Xaml.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>`

Note that `portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20` doesn't exist.

### Known workarounds

Use Nuget.

**Comment by forki** [comment]
Can you please upload a zip with a repro sample?

**Comment by tastyeggs** [comment]
In trying to debug and narrow this, I realized the issue happened to due to another paket.dependencies file that ended up on my folder structure that was overriding this package with a different version.
