### ISSUE TITLE
The `Paket.Restore.targets` is not in `.paket` directory after boostrapping or restore

### ISSUE THREAD

**Issue by enricosada** [fsprojects/Paket#2817]
### Description

The `Paket.Restore.targets` is not in `.paket` directory after boostrapping or restore

### Repro steps

```
.paket\paket.bootstrapper.exe
.paket\paket.exe restore
```

### Expected behavior

the  `Paket.Restore.targets`  is created

### Actual behavior

the  `Paket.Restore.targets`  is not created

### Known workarounds

Run `install` or commit the `Paket.Restore.targets` to repository.

Note, is not a bug, atm is by design.
Just checking if is not better to create the `Paket.Restore.targets` on restore? so is aligned with current paket version (instead of be commited in repo).
Lots of build script are just boostrap + restore

**Comment by forki** [comment]
Question is a bit if we should overwrite with latest version when it's already there. I don't think we should. But creating it when it's missing is probably a good thing

**Comment by enricosada** [comment]
well, it should be always aligned with paket version, is just a temp file (required before `dotnet restore` just for techinical reason) 
so replace if different is not that bad, is like updating paket each build.

**Comment by enricosada** [comment]
Fixed by v5.104.0 now is created after restore

**Comment by andygjp** [comment]
Hi,

I think there might still be a related issue.

Just cloned my repo to my machine and kicked off a build but I get: "The system cannot find the path specified."

The .paket\Paket.Restore.targets is only 2.4KB. When it worked, the same file was 15.2KB. See attached screenshot.

Cheers,
Andy

![image](https://user-images.githubusercontent.com/1445933/31147932-353bbcc2-a883-11e7-876b-b191b307dad9.png)

**Comment by andygjp** [comment]
Actually, ignore that - it seems the target file was introduced when I updated FAKE.

Sorry,
Andy

**Comment by TheAngryByrd** [comment]
If I'm looking to debug `Paket.Restore.targets` on a repository is there a way to tell paket to not autodownload this file on restore?

**Comment by forki** [comment]
it does not download - it extracts it from resources

**Comment by TheAngryByrd** [comment]
Sorry, regardless of the mechanism of how the file gets there, is there a way to tell paket to not overwrite the file when I have changed it to include more debug messages? If not, would an environment variable be appropriate?

**Comment by forki** [comment]
Yeah would accept a pr which introduces a env variable

Am 16.02.2018 13:48 schrieb "Jimmy Byrd" <notifications@github.com>:

**Comment by TheAngryByrd** [comment]
Ok cool 😎
