### ISSUE TITLE
Make download of licenses explicit instead of implicit

### ISSUE THREAD

**Issue by batzen** [fsprojects/Paket#2819]
### Description

Licenses of nuget packages are automatically downloaded (asked for in https://github.com/fsprojects/Paket/issues/735 and introduced with https://github.com/fsprojects/Paket/pull/737).

This feature caused hundreds of builds at my employer to fail yesterday because github decided we made enough requests to raw.githubusercontent.com. I wasn't even aware till today that paket issues requests to hosts i didn't explicitly specify as sources for packages.

This causes long delays or even errors when:
- in restricted environments (without access to internet)
- a lot of licenses are downloaded from github and a lot of builds happen at once you get blocked by github

I also have a few more concerns on automatically downloading something from sources i did not specify:
- [Security] Requests to those sources could be tracked
- Content could have been moved thus causing sudden delays because of timeouts

### Repro steps

1. Add reference to a nuget package which hosts it's license file at github (for example ControlzEx)
2. Restore that package many times till github decides you had enough and starts blocking you

### Expected behavior

Paket should not makes requests to hosts other than those i explicitly sepcified in the sources.
Licenses should only be downloaded on demand.

### Actual behavior

Licenses are always downloaded automatically.

### Known workarounds

There are no workarounds i am aware of.

Please let me know if you need further details or explanations.

**Comment by forki** [comment]
what do you suggest? something in paket.dependencies per group and package?

`download-license: yes/no` ?

**Comment by matthid** [comment]
This was a troublesome feature from the very start. I think it was decided to do it as is because of legal reasons. technically, it should have been opt-in from the start?

**Comment by forki** [comment]
Ok I'm going for `license-download` because of singular/plural problen in group vs nuget package

**Comment by forki** [comment]
see https://github.com/fsprojects/Paket/pull/2820

**Comment by forki** [comment]
ok this is fixed

**Comment by batzen** [comment]
That was fast. Thanks a lot.
