### ISSUE TITLE
frameworks vs framework

### ISSUE THREAD

**Issue by ncave** [fsprojects/Paket#2822]
in paket.dependencies, this worked before:
`frameworks: net45`

but seems to fail with 1.0.6:
```
Paket failed with
-> Error in paket.dependencies line 1
     Could not parse framework 's'. Try to update or install again or report a paket bug.
```
it works if changed to: `framework: net45`
which makes sense I guess, if the property was changed, so feel free to close if by design.

**Comment by forki** [comment]
Urgs. Reverting that last change to give us time to  investigate
/cc @agross @matthid

Am 04.10.2017 18:57 schrieb "ncave" <notifications@github.com>:

**Comment by matthid** [comment]
Looks intentional, seems like it previously was parsed correctly "by accident"

**Comment by forki** [comment]
Ok. But question is where is it used. What do we break

Am 04.10.2017 19:21 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by ncave** [comment]
@forki One place is [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/fcs/paket.dependencies#L1).

**Comment by forki** [comment]
Oh breaking FCS. Nice one. ;-)
Anyway we decided to roll back (should already be available).

Am 04.10.2017 20:08 schrieb "ncave" <notifications@github.com>:

**Comment by ncave** [comment]
@forki Yes, it works now, closing as fixed ;-)

**Comment by matthid** [comment]
what the hell ;)

**Comment by ncave** [comment]
@matthid Sorry, just tried to help, please reopen if you need it for tracking.

**Comment by matthid** [comment]
nah everything is fine. I was just stating my feeling about how users managed to build a feature out of a bug/misspelling the keyword oO.

**Comment by ncave** [comment]
@matthid That was my OP, to better understand if it's a bug/misspelling in FCS that needs to be fixed there, or something else. Thanks for your quick response, @forki and @matthid

**Comment by matthid** [comment]
yes but I agree with @forki: if even fcs has this we should probably get over it and make it a proper (maybe undocumented) feature now ...

**Comment by forki** [comment]
We should still send a pr to things where we see it.

Am 04.10.2017 22:31 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by forki** [comment]
Also TIL we have a dependencies file in official visualfsharp repo
