### ISSUE TITLE
Paket should use preinstalled .NET Core package cache instead of downloading .NET Core framework packages to nuget global cache

### ISSUE THREAD

**Issue by julkwiec** [fsprojects/Paket#2827]
### Description

.NET Core 2.0 SDK comes with preinstalled package cache containg 331 default framework packages:
- `%PROGRAMFILES%\dotnet\sdk\NuGetFallbackFolder` on Windows
- `/usr/share/dotnet/sdk/NuGetFallbackFolder` on Linux

![image](https://user-images.githubusercontent.com/12023480/31273035-5a75af46-aa8d-11e7-966b-3a9844eb3531.png)

Paket is unaware of this cache and downloads all framework packages from NuGet into user's package cache (`%USERPROFILE%/.nuget/packages`). This can really slow down docker-based builds where you start with empty user cache each time.

### Repro steps

1. `paket clear-cache`

2. Create `paket.dependencies` file:
```
source https://api.nuget.org/v3/index.json
framework: netcoreapp2.0
nuget AutoMapper == 6.1.1
```

3. `paket install`

### Expected behavior

Paket should look inth the builtin cache (if available) before downloading framework packages.

### Actual behavior

Paket downloads a lot of frakework packages:
![image](https://user-images.githubusercontent.com/12023480/31273632-ca2be8f8-aa8f-11e7-9c5e-4eeea1939bbd.png)

**Comment by julkwiec** [comment]
A similar package cache is preinstalled with Visual Studio 2017. It's located in `C:\Program Files (x86)\Microsoft Web Tools\Packages`.

Before I start working on a PR, please let me know if you want Paket to use such local package sources.

**Comment by inosik** [comment]
These paths aren't necessarily correct. You can download the .NET SDK as a ZIP package and extract it anywhere you want it to be.

**Comment by julkwiec** [comment]
Good point. Any idea what to do in that case?

**Comment by inosik** [comment]
We'd need to call `dotnet --info` and extract the "Base Path" from the output, similar to [what OmniSharp does](https://github.com/OmniSharp/omnisharp-roslyn/blob/6b9058239c61c7df9c6f0c5bdeef79356fc7885d/src/OmniSharp.Abstractions/Services/DotNetCliService.cs#L122). But that comes with its own problems, see OmniSharp/omnisharp-vscode#1754.

**Comment by julkwiec** [comment]
Nice. Just tested it in console, looks like it works. 
I don't see how the issue you've linked could impact the use case we're discussing, `dotnet --info` contains proper paths both in portable version (extracted zip) and when installed:
- `D:\downloads\dotnetsdk\sdk\2.0.0\`
- `C:\Program Files\dotnet\sdk\2.0.0\`

**Comment by inosik** [comment]
The linked issue happens in some Windows + Bash environments where you happen to have environment variables which differ in case, e. g. `home` and `HOME`, as on my machine at work. AFAIR it didn't happen prior to .NET 4.6. It affects other .NET apps as well, so I don't know if there is anything to do.

Reading through various issues here on GitHub, it seems that the `NuGetFallbackFolder` should actually be considered a package source, rather than a cache. Do you know something about this?

**Comment by julkwiec** [comment]
That's possible, but `NuGetFallbackFolder`'s contents have the same structure as cache:
```
packagename/
|---1.0.0/
    |---packagename.1.0.0.nupkg
    |---packagename.1.0.0.nupkg.sha512
    |---packagename.nuspec
    |---lib/
        |---net45/
            |---packagename.dll
```

**Comment by julkwiec** [comment]
Treating it as first-class package source would complicate things:
- how to refer to it in the .lock file? It may or may not exist and paths may vary
- should a package be copied to the actual cache? that would cost time and space

**Comment by matthid** [comment]
Does it work for you if you add the cache location as `Cache` into the dependencies file?

> Before I start working on a PR, please let me know if you want Paket to use such local package sources.

I'd says: Yes in theory we want that. But finding the `NuGetFallbackFolder` is not exactly trivial. Especially considering that it has to work x-plat and we have situations where `dotnet` is not in path when paket is invoked.

On the other side: The worst case is that we don't use it and download stuff so maybe not an issue.
I'd like to know if @forki thinks it this is a good idea.

**Comment by julkwiec** [comment]
@matthid finding the package cache by parsing `dotnet --info` should work on both Windows and Linux - the relative path is always `../NuGetFallbackFolder`.

If `dotnet` is not in path then we could try to check the default path (`%PROGRAMFILES%\dotnet\sdk\NuGetFallbackFolder` on Windows, `/usr/share/dotnet/sdk/NuGetFallbackFolder` on Linux). If that doesn't work then IMO Paket should ignore it and proceed to download the frameworks packages.

**Comment by julkwiec** [comment]
Bump

**Comment by julkwiec** [comment]
Bumping again. I'm willing to work on this once we agree on how should it be done.

**Comment by forki** [comment]
how about we just probe couple of know paths?

**Comment by csmager** [comment]
I just came across this in #3235 (having failed to find this one first). Would be good to add support for this as e.g. on a VM when the cache is empty this results in large discrepancy in `dotnet restore` times for NuGet vs Paket due to downloading things that are already on the machine.

Microsoft recommend referencing the `Microsoft.AspNetCore.App` meta-package, which brings in the whole world. It's a lot to download.

I'm also happy to look into this if someone could point me in the right direction. Once we've determined where this fallback folder is (either by scraping `dotnet --info`  or probing known paths), where should it be included to get paket to search there?

**Comment by csmager** [comment]
Having done a bit more digging, I'd note that the MSBuild targets for SDK projects [populate a property called `_NugetFallbackFolder`] that contains the path to this offline cache.

Perhaps we could get this in `Paket.Restore.targets` and pass as a parameter to `paket.exe restore`?

**Comment by forki** [comment]
would love to see a PR!
