### ISSUE TITLE
Paket breaks dotnet pack and breaks further builds

### ISSUE THREAD

**Issue by Kurren123** [fsprojects/Paket#2830]
If I do `dotnet pack .\TestGraphQL.fsproj  --version-suffix "ci-1234"` I get the following error:

```
.paket\Paket.Restore.targets(157,5): error : The given path's format is not supported. [C:\Users\Kurren.Nischal\Documents\Visual Studio 2017\Projects\TestGraphQL\TestGraphQL\TestGraphQL.fsproj]
```

Every `dotnet build` after that fails with that error message. The only way to make the build succeed is to run a `dotnet clean`

**Comment by forki** [comment]
Any idea where that may come from? And which dotnet version?

Am 09.10.2017 17:46 schrieb "Kurren Nischal" <notifications@github.com>:

**Comment by Kurren123** [comment]
dotnet version 2.0.0

After some testing I found it's because I have `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` in my project file. Once this is set to false the error is no more.

**Comment by forki** [comment]
So we can close it?

**Comment by aggieben** [comment]
I'm experiencing this issue, but I don't have `GeneratePackageOnBuild` in my project.  I'm using the SDK-style project format.
