### ISSUE TITLE
Adding latest Mandrill nuget breaks ProjectCracker

### ISSUE THREAD

**Issue by samritchie** [fsprojects/Paket#2831]
### Description

`paket update/install` breaks project files for ProjectCracker/Ionide (parse failure with null ref exception). Appears to be related to:

* old-style project files targeting framework 4.5.2
* latest version of the Mandrill nuget package
* the `NETStandard.Library.targets` import

### Repro steps

unzip project & open in Ionide. My environment is:
MacOS 10.13
Mono 5.2.0.224
VS Code 1.17.0
Ionide-fsharp 3.5.1
Paket 5.113.1

[Paket test.zip](https://github.com/fsprojects/Paket/files/1370473/Paket.test.zip)

### Expected behavior

Project loads in F# Project Explorer

### Actual behavior

Project fails to load with
`/Users/sam/Desktop/Paket test/PaketTest/PaketTest.fsproj: Object reference not set to an instance of an object`

### Known workarounds

1. Removoing the `NETStandard.Library.targets` import allows the project to load
2. Downgrading Mandrill to 3.0.0 allows the project file to load, but build failures ensue
3. Downgrading to 2.4.181 appears to work

**Comment by forki** [comment]
getting 404 on the zip

**Comment by samritchie** [comment]
[Paket test.zip](https://github.com/fsprojects/Paket/files/1371041/Paket.test.zip)
 try again...

**Comment by forki** [comment]
did  paket update

![image](https://user-images.githubusercontent.com/57396/31392499-b09a92e8-add9-11e7-8afd-1f1338156f00.png)

**Comment by samritchie** [comment]
<img width="1024" alt="screen shot 2017-10-11 at 2 43 42 pm" src="https://user-images.githubusercontent.com/309444/31425637-b23963a4-ae92-11e7-98d0-26d24f672ca2.png">

I’m still getting the issue with 5.113.2. Interestingly, initial update succeeded, but if I pin to 3.0.0, update, then remove the pin, then update, I get the parse issue. Unsure why this would be different, I’ll try to save copies of the fsproj & diff them

**Comment by forki** [comment]
yes please

**Comment by samritchie** [comment]
Okay, this is super odd. I can reliably reproduce using the process:

1. `paket update` unpinned - loads okay
2. `paket update` pinned to 3.0.0 - loads okay
3. `paket update` unpinned - breaks

I’ve done a diff on the project file for 1 & 3, they are identical. I did a directory diff on the whole project and the only change is in `obj/fsac.cache`; if I’m understanding this file correctly, this is a side-effect of the project load failure, not its cause.

I’m pretty sure the load failure is not being triggered on 1 due to ionide not re-parsing the project when it should. If I delete the fsac.cache at step 1 it seems to be enough to trigger the re-parse and the load fails. At any rate, it doesn’t help much trying to track down the issue.

The only difference in the project file between the unpinned/non-loading and pinned/loading files are the following:

```<Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.2'">
      <ItemGroup>
        <Reference Include="Mandrill">
          <HintPath>..\packages\Mandrill\lib\netstandard1.1\Mandrill.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.2'">
      <ItemGroup>
        <Reference Include="Newtonsoft.Json">
          <HintPath>..\packages\Newtonsoft.Json\lib\net45\Newtonsoft.Json.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5.2'">
      <ItemGroup>
        <Reference Include="System.Runtime.InteropServices.RuntimeInformation">
          <HintPath>..\packages\System.Runtime.InteropServices.RuntimeInformation\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Import Project="..\packages\NETStandard.Library\build\NETStandard.Library.targets" Condition="Exists('..\packages\NETStandard.Library\build\NETStandard.Library.targets')" Label="Paket" />```

As before, deleting the `NETStandard.Library.targets` import will allow it to load.

**Comment by forki** [comment]
obj/fsac.cache <- I assume @enricosada @Krzysztof-Cieslak know something about it

**Comment by samritchie** [comment]
Ah, I’ve just found https://github.com/fsharp/FSharp.Compiler.Service/issues/795 - it looks like a combination of mono 5.2 and `NETStandard.Library.targets` is the problem. It looks like Paket’s not doing the wrong thing with the project file, I’ll close this.
