### ISSUE TITLE
Syntax error: Expected end of input, got '<= net45'.

### ISSUE THREAD

**Issue by derwasp** [fsprojects/Paket#2833]
### Description

A bunch of my existing projects stopped working with the recent update.
`paket restore` fails with the following message:

```

c:\.code\myproject>paket restore
Paket version 5.113.1
Performance:
 - Runtime: 919 milliseconds
Paket failed with
-> Error in paket.dependencies line 3
     Syntax error: Expected end of input, got '<= net45'.
```

I would like avoiding to fix the dependencies file for all the projects if that is possible.

### Repro steps

Use the following `paket.dependencies`:
group Build
  source https://nuget.org/api/v2
  framework: <= net45

  nuget FAKE
  nuget GitVersion.CommandLine

### Known workarounds

Change `<=` to `=`

**Comment by forki** [comment]
we think <= was a mistake. Our parser was not good enought to reject it.
Please use `=`

**Comment by matthid** [comment]
What does `<= net45` even mean?

**Comment by matthid** [comment]
Yes it seems the bug is that `paket restore` reads the dependencies file. Or that it doesn't continue when it fails there (With a warning as apparently we need it for the out-of-date warning).

@derwasp Can you post your `paket.lock` to verify/see if that is in a sane state?

**Comment by derwasp** [comment]
@forki @matthid I totally agree that it doesn't make much sense ;) And I have `=` for all the new projects. But it's not nice to see that the existing builds broke.

@matthid It doesn't go to the dependencies file if the restore is not required. And if I remove "packages" & "packet-files", it crashes.
This is the lock file:

```
GROUP Build
FRAMEWORK: NET45
NUGET
  remote: https://www.nuget.org/api/v2
    FAKE (4.50.1)
    GitVersion.CommandLine (3.6.5)

```

**Comment by forki** [comment]
yes we see it as bug that we crashed restore

**Comment by forki** [comment]
how about https://github.com/fsprojects/Paket/pull/2835?

**Comment by derwasp** [comment]
that was lightning fast! thanx.
I guess just not checking the dependencies file during restore is harder to implement?

**Comment by matthid** [comment]
> I guess just not checking the dependencies file during restore is harder to implement?

Correct, that would indeed be the preferred way. We would welcome a PR but some dragons are hidden there

**Comment by forki** [comment]
@derwasp unforunately I found 2 design fuckups that make this impossible. so we need to evolve in that direction.

**Comment by derwasp** [comment]
@matthid @forki affirmative! thank you for such a fast resolution folks. I'll be waiting for the new version 👍

**Comment by forki** [comment]
> I'll be waiting for the new version 

wil take an hour to run all integration tests. but it's under way
