### ISSUE TITLE
Bad internet connection results in bootstrapper hanging

### ISSUE THREAD

**Issue by xavierzwirtz** [fsprojects/Paket#2837]
### Description

Internet connection at my office is on the fritz, causing downloads of new versions of paket to get aborted mid-stream. When this happens paket.bootstrapper.exe gets hung up indefinitely, resulting in builds running indefinitely.

Prints this output: 
```
No version specified. Downloading latest stable.
Starting download from https://github.com/fsprojects/Paket/releases/download/5.113.2/paket.exe
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
```

### Repro steps

1. Run paket.bootstrapper.exe

2. Cut Ethernet cable with wire snips.
 
### Expected behavior

Fail gracefully and exit paket.bootstrapper.exe when connection is lost.

### Actual behavior

paket.bootstrapper.exe runs indefinitely. 

### Known workarounds

Don't cut your Ethernet cable.

**Comment by forki** [comment]
/cc @vbfox

Am 10.10.2017 18:33 schrieb "Xavier Zwirtz" <notifications@github.com>:

**Comment by xavierzwirtz** [comment]
I am going to close this. After testing with latest paket.bootstrapper.exe, I cannot get the hang to reoccur. The bootstrapper fails gracefully whenever the connection is interupted with the latest bootstrapper.
