### ISSUE TITLE
NU1100: Unable to resolve 'XXX' for '.NETFramework,Version=v4.6.2'.

### ISSUE THREAD

**Issue by jamescrowley** [fsprojects/Paket#2838]
### Description

We are getting

NU1100: Unable to resolve 'XXX' for '.NETFramework,Version=v4.6.2'.
followed by "Restore failed".

I am not yet sure if this is a NuGet/Build tools issue or a Paket issue. Doesn't happen if you have VS 2017 installed. Only appears to happen when you have "Build Tools for Visual Studio 2017" plus .NET Core 2.0 SDK installed (ie on our build server). We are running v15.4 of the build tools.

If anyone has any suggestions on how to diagnose further, it would be much appreciated.

### Repro steps

Please provide the steps required to reproduce the problem

1. We are running paket v5.114.0 via magic paket.exe (ie bootstrapper)

2. We have CS project files in the new project format, targeting .NET 4.6.2 

3. We are running

    paket restore --group build

to pull down FAKE and a few others and then

     msbuild Project.sln /t:Restore;Build

### Expected behavior

The project builds successfully, as it does on a machine with VS 2017 installed.

### Actual behavior

As a result of paket restore --group build, paket does this:

	Paket version 5.114.0
	- C:\BuildAgent\work\9703509c24d73488\src\XX\obj\XX.csproj.net462.paket.resolved created
	- C:\BuildAgent\work\9703509c24d73488\src\XX\obj\XX.csproj.paket.props created
	<snip>
	Performance:
	- Disk IO: 11 seconds
	- Runtime: 7 seconds
	Paket version 5.114.0
	Skipping resolver for group build since it is already up-to-date
	Skipping resolver for group Main since it is already up-to-date
	C:\BuildAgent\work\9703509c24d73488\paket.lock is already up-to-date
	Installing into projects:
	- Creating model and downloading packages.
	- src/XX/paket.references -> src/XX/FundApps.XX.csproj
	- src/YY/paket.references -> src/YY/FundApps.YY.csproj
	<snip>
	Performance:
	- Disk IO: 29 seconds
	- Average Download Time: 11 seconds
	- Number of downloads: 2
	- Runtime: 38 seconds

As a result of MSBuild:

	Building project: ./src/XX.sln
	C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ./src/XX.sln /t:Restore;Build /m /nodeReuse:False /tv:15.0 /v:m /p:RestorePackages="False" /p:Optimize="True" /p:DebugSymbols="True" /p:TreatWarningsAsErrors="True" /p:Configuration="Release" /logger:Fake.MsBuildLogger+TeamCityLogger,"C:\BuildAgent\work\9703509c24d73488\packages\build\FAKE.x64\tools\FakeLib.dll" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\BuildAgent\work\9703509c24d73488\packages\build\FAKE.x64\tools\FakeLib.dll"
	Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
	Copyright (C) Microsoft Corporation. All rights reserved.

	Paket version 5.114.0
	- C:\BuildAgent\work\9703509c24d73488\src\XX\obj\XX.csproj.net462.paket.resolved created
	- C:\BuildAgent\work\9703509c24d73488\src\YY\obj\YY.csproj.net462.paket.resolved create
	<snip>
	C:\BuildAgent\work\9703509c24d73488\src\ZZ\ZZ.csproj : error NU1100: Unable to resolve 'NodaTime (>= 1.3.1)' for '.NETFramework,Version=v4.6.2'. [C:\BuildAgent\work\9703509c24d73488\src\XX.sln]
	
	Generating MSBuild file C:\BuildAgent\work\9703509c24d73488\src\ZZ\obj\ZZ.csproj.nuget.g.props.
	Generating MSBuild file C:\BuildAgent\work\9703509c24d73488\src\ZZ\obj\ZZ.csproj.nuget.g.targets.
	Restore failed in 314.56 ms for C:\BuildAgent\work\9703509c24d73488\src\ZZ.csproj.

### Known workarounds

None

**Comment by forki** [comment]
do you have a zip for me to repro?

**Comment by jamescrowley** [comment]
@forki working on it :)

**Comment by jamescrowley** [comment]
@forki I'd like to think even if I don't know what I'm doing, I'm good at tracking down problems, but I'm at a loss. 

[PaketReproFromJC.zip](https://github.com/fsprojects/Paket/files/1381068/PaketReproFromJC.zip)

Attached is a sample. Locally, running VS 2017 15.4. After running 'git clean -fdx', and the 'build' the solution builds successfully. Run build a second time, and it fails.

    CS0246: NLogPropertyTarget.cs(3,11): The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Run on the build server (running .NET Core 2.0 SDK and VS Build Tools for 15.4 only), I get

NU1100: C:\BuildAgent\work\9703509c24d73488\src\FundApps.Common.Logging\FundApps.Common.Logging.csproj(0,0): Unable to resolve 'Newtonsoft.Json (>= 10.0.3)' for '.NETFramework,Version=v4.6.2'.
NU1100: C:\BuildAgent\work\9703509c24d73488\src\FundApps.Common.Logging\FundApps.Common.Logging.csproj(0,0): Unable to resolve 'NLog (>= 4.1.2)' for '.NETFramework,Version=v4.6.2'.

My next stop is ripping Paket out entirely and trying the native NuGet bits.

**Comment by jamescrowley** [comment]
@forki I have tried replacing with PackageReferences direct in the project files, and these work fine, so pretty confident this is a Paket issue.

[PaketReproFromJC.zip](https://github.com/fsprojects/Paket/files/1381069/PaketReproFromJC.zip)

Attached is a sample. Locally, running VS 2017 15.4. Any time after running 'git clean -fdx', and 'build' the solution builds successfully. Run build a second time, and it fails as if it's not restoring the packages.

    CS0246: NLogPropertyTarget.cs(3,11): The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Run on the build server (running .NET Core 2.0 SDK, .NET 4.6.2 SDK and VS Build Tools for 15.4 only), I get

    NU1100: C:\BuildAgent\work\9703509c24d73488\src\FundApps.Common.Logging\FundApps.Common.Logging.csproj(0,0): Unable to resolve 'Newtonsoft.Json (>= 10.0.3)' for '.NETFramework,Version=v4.6.2'.
    NU1100: C:\BuildAgent\work\9703509c24d73488\src\FundApps.Common.Logging\FundApps.Common.Logging.csproj(0,0): Unable to resolve 'NLog (>= 4.1.2)' for '.NETFramework,Version=v4.6.2'.

every time.

**Comment by forki** [comment]
ok how to reproduce?

I'm using 15.5 but that should matter that much. I open solution. build, clean, build again and everything still works!?

**Comment by jamescrowley** [comment]
@forki even when running from build.cmd rather than within VS?

My steps to repro the local issue just now were:

- Extract ZIP to fresh dir
- Run build.cmd (pass)
- Run build.cmd (fail)

With regards the build server issue, the build server has a consistent environment as it's scripted. Can give you the powershell to run to install the binaries as-is if that's helpful.

**Comment by forki** [comment]
That build.cmd does not even work for me on first trial

Am 13.10.2017 12:21 schrieb "James Crowley" <notifications@github.com>:

**Comment by jamescrowley** [comment]
@forki with the same error I'm reporting, or something else?

**Comment by forki** [comment]
I can now repro from developer command promt. Any reason why you don't use "dotnet build"?

**Comment by forki** [comment]
ok I found something: your MSBuild command doesn't call paket at all.
The very first success is because of `paket.cmd restore --group build` call. That one restored sdk projects. But that's actually a bug that I just fixed. So right now even the first call crashes. :P
Which is expected sind MSBuild is not calling paket at all.

Trying to find out why..

**Comment by jamescrowley** [comment]
@forki MsBuild - just a bit of a learning process here to figure out the least painful way to slowly migrate a .NET 4.6.2 150 project solution, running MVC 5 over time without breaking the rest of the engineering team's workflow :grin: 

I can confirm that I don't get either issue locally or on the build server switching to using 'dotnet build' instead.

Was gonna ask about that weird behaviour for the build restore, so thanks for fixing it :grin:

**Comment by forki** [comment]
lol. now everything works as expected.

**Comment by forki** [comment]
just upgrade to 5.114.4

**Comment by forki** [comment]
no need to use dotnet build

**Comment by jamescrowley** [comment]
thanks @forki appreciate it :)

**Comment by forki** [comment]
crazy bug....

**Comment by jamescrowley** [comment]
@forki there's still a bug lurking here. I still get the build server issue ("NU1100: Unable to resolve 'XXX' for '.NETFramework,Version=v4.6.2'.") when running msbuild (but not dotnet build).

**Comment by forki** [comment]
but that doesn't repro locally?

**Comment by forki** [comment]
so what's the difference on the CI? different msbuild or dotnet version?

**Comment by jamescrowley** [comment]
Yeah, can't repro locally. 

On the CI we only have the VS 2017 Build tools as opposed to the full VS installation. 

There was previously (unrelated?) NuGet weirdness-es with VS 2017 compared to just having the build tools which I experienced and were fixed in 15.4 (https://github.com/nuget/home/issues/4821/). 

Since then I've been able to build successfully using msbuild on the build server, but only if I switch to using PackageReference instead of paket.

**Comment by forki** [comment]
> On the CI we only have the VS 2017 Build tools as opposed to the full VS installation.

What I think you should do is to move over to `dotnet build`. I mean you probably need to have dotnet sdk 2.0.0 installed anyway

**Comment by jamescrowley** [comment]
Yeah, we have the dotnet SDK installed too, so I am switching to dotnet build 👍

**Comment by forki** [comment]
nice side effect " VS 2017 Build tools" no longer needed

**Comment by tarekahf** [comment]
I am using VSCode to build a C# Project with Selenium. I following the [steps here](https://www.fleekitsolutions.com/use-selenium-c-visual-studio-code/) however when I reach the step to add the Selenium package, I get this error:

> C:\Projects\Selenium\demoProject\FirstTest\FirstTest.csproj : error NU1100: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for 'net6.0

which is pretty close to the error reported in this issue. I also posted a [question for this issue here](https://stackoverflow.com/questions/71042459/configure-vs-code-for-selenium-4-error-while-installing-dotnet-6-sdk-using-pow).

I appreciate your help.
Tarek

**Comment by fleekitsolutions24** [comment]
Thanks for documenting this! I ran into a [similar problem](https://fleekitsolutions.com/) where Paket tried restoring SDK-style projects even though I specified a group. Glad to see it was resolved in v5.115.0. The fix saves time and avoids unnecessary restore errors. Great work by the team!
