### ISSUE TITLE
Extend github sourcing to any git repo

### ISSUE THREAD

**Issue by jonathanmorley** [fsprojects/Paket#284]
There should be support for any git repository to be sourced as a package.

This could be done with a similar [syntax to npm](https://www.npmjs.org/doc/files/package.json.html#git-urls-as-dependencies):

git://github.com/user/project.git#commit-ish
git+ssh://user@hostname:project.git#commit-ish
git+ssh://user@hostname/project.git#commit-ish
git+http://user@hostname/project/blah.git#commit-ish
git+https://user@hostname/project/blah.git#commit-ish

**Comment by isaacabraham** [comment]
@caindy Probably a new issue I would've thought? @forki

**Comment by ilkerde** [comment]
I strongly support this feature to be implemented with "git in path". If git is not available, paket can politely tell the user to require it.

Thanks for your work!

**Comment by forki** [comment]
There is a first alpha version available. This feature will come with Paket v3.

**Comment by CumpsD** [comment]
Are you using LibGitSharp now? If so, I thought it didn't support SSH repositories, or has that changed?

**Comment by caindy** [comment]
@CumpsD according to [the documentation](https://fsprojects.github.io/Paket/git-dependencies.html)

> This feature assumes that you have git installed. If you don't have git installed then Paket still allows you to reference files from github.

**Comment by CumpsD** [comment]
@caindy yes I know, I was referring to the comment of @yannisgu higher in this thread who proposed libgit2sharp, upon which my mind sprung to the fact it apparently doesn't wrap ssh yet.

**Comment by forki** [comment]
We use the installed git.exe

**Comment by jschiefer** [comment]
I have been playing with this and have a little trouble understanding the use model. I want to pull down a whole git repository, so I put a "git" line into the paket.depedencies and install, and it does that just fine. But where do I go from here? 

I expected I would run a build using the `build:"build.cmd"` syntax, and then somehow be able to refer to the build artifacts in the appropriate paket.references files. From looking at the code, it appears that the file: syntax in paket.references would be one way this might work. Or is building a Nuget file as described at the bottom of http://fsprojects.github.io/Paket/git-dependencies.html the correct way to do this?

Background: I was hoping to use Paket as an easy way to switch between binary (NuGet) and source (git repo) references for individual packages, for cases where you occasionally need to debug into a library..

**Comment by forki** [comment]
At the moment the only supported way is building nuget packages. But we
also want to allow more use cases. What do you want to achieve? Referencing
dlls
?

**Comment by jschiefer** [comment]
Yes, referencing assemblies. Let's say in my fsproj I have a reference to a dependent assembly that I satisfied via Paket/NuGet. I would be able right-click on the reference in the solution explorer and select a "get source" menu entry, which would, via Paket, retrieve the source repository for the dependent assembly, load its corresponding csproj file and replace any reference to the binary with a project reference throughout the solution. Bascially a low-friction way to go from binary/Nuget to source/git and back as needed.

**Comment by forki** [comment]
how about this (potentil feature):

in paket.references:

    // project: paket-files/.../MyNuGet.csproj
    // MuNuGet

By uncommenting one of the two lines and running "paket install" you could enable the corresponding setting.

**Comment by forki** [comment]
maybe we can do it in the same line!?

**Comment by jschiefer** [comment]
Initially this sounded like a good proposal, but let's think about the implications:

I assume there would need to be two entries for MyNuGet in the paket.dependencies: one for the Nuget, and one for the source, and they would need to be tied together somehow. The "obvious" assumption that the NuGet package name corresponds to the git repository name is probably invalid.

Which git commit would Paket select on install or update? Initially, you would want whatever is specified in paket.dependencies. But if you switch to source, you would eventually make changes, so now your local repository under paket-files is in a different state. Then what should Paket do on install or update? Should an update change the version specification in paket.lock to be different from paket.dependencies?That doesn't sound right...

Also, what if you had two references to MyNuGet in different projects, where one used the NuGet binary and the other used the source version from git, you'd end up with two different versions of MyNuGet in the end, which is not what you want. So maybe the switching needs to happen in paket.dependencies, not paket.references, for that reason?

Should we discuss this in https://github.com/fsprojects/Paket/issues/334?

**Comment by forki** [comment]
yes #334 is better place

**Comment by forki** [comment]
Implemented in v3

**Comment by Thorium** [comment]
How do I reference a private git (e.g. Bitbucket) repo? Will it ask password on every build or can it be set as env variable? https://fsprojects.github.io/Paket/git-dependencies.html didn't have any info of private repositories...

**Comment by forki** [comment]
It uses your local git installation and will use password from it's
password store / ssh key

Tuomas Hietanen <notifications@github.com> schrieb am Do., 30. Aug. 2018,
21:20:
