### ISSUE TITLE
Why is netstandard2.0.1 pulled in in this netstandard1.3 project

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#2843]
### Repro steps

1. Clone  https://github.com/JohanLarsson/PaketRepro/commit/11a737c2de72d53b8352b718db39b9c383bb7858

2. Paket install

### Behavior

I'm trying to keep the dependency on `System.Collections.Immutable` low but for some reason it resolves to System.Collections.Immutable (1.4)
Maybe I dumbed something but I think this setup has worked in the past.
Getting the same version with `stragety: min`

**Comment by forki** [comment]
Only from reading your verbal description I think you want to do
https://fsprojects.github.io/Paket/nuget-dependencies.html#The-modifier-1

The lowest_matching operator that you used is only for direct deps, but
according to your description you want to keep transitive deps low

Am 12.10.2017 22:02 schrieb "Johan Larsson" <notifications@github.com>:
