### ISSUE TITLE
Paket why is very slow

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#2844]
### Repro steps

1. git clone https://github.com/SAFE-Stack/SAFE-BookStore.git
1. cd SAFE-BookStore
1. .paket\paket.exe why ncrontabs

### Expected behavior

Blazing fast response

### Actual behavior

![image](https://user-images.githubusercontent.com/57396/31533174-5dfcce1a-aff1-11e7-96c2-c8e3d03b0b04.png)

**Comment by theimowski** [comment]
ouch, I'll try to give it a go

**Comment by forki** [comment]
@theimowski https://github.com/fsprojects/Paket/pull/2845 is a start

**Comment by theimowski** [comment]
Turns out the cycle dep prevention is the bottleneck. Can't yet think of an optimal replacement for `removeEdge`

**Comment by theimowski** [comment]
It could go down to 1s, so i think it's worth to try once more
