### ISSUE TITLE
CLI Tools aren't being restored properly now

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#2854]
### Description

CLI Tools aren't being restored properly now.  I'm getting errors like `﻿Version for package `dotnet-mono` could not be resolved` when trying to run a tool https://github.com/fsprojects/Paket/releases/tag/5.117.0 seems to be the culprit. 

### Repro steps

Please provide the steps required to reproduce the problem

paket.depedencies includes a dotnet tool like `clitool dotnet-mono 0.2.1` and include that in your paket.references

Do a `dotnet restore` `dotnet build` dance then try to use that tool.  

I'll try to get a github repo repro. 

### Expected behavior

dotnet tools are there

### Actual behavior

dotnet tools appear to not be there

### Known workarounds

Revert to earlier version

**Comment by forki** [comment]
ok I'll revert

**Comment by forki** [comment]
can you please retry?

**Comment by TheAngryByrd** [comment]
seems to work 🎸

**Comment by TheAngryByrd** [comment]
Everything seems broke :(

```
 error FS0074: The type referenced through 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.
```

**Comment by forki** [comment]
Ok reverting for now

Am 19.10.2017 20:46 schrieb "Jimmy Byrd" <notifications@github.com>:

**Comment by forki** [comment]
@TheAngryByrd are you around on skype?

**Comment by TheAngryByrd** [comment]
I'll be at work in about 45 mins if you can wait till then.
