### ISSUE TITLE
Paket ignores paket.references in netcore projects

### ISSUE THREAD

**Issue by OlegZee** [fsprojects/Paket#2856]
### Description

The build started to fail with recents paket updates.

### Repro steps

Please provide the steps required to reproduce the problem

1. create new project (`dotnet new console -lang f#`)

2. `dotnet add package akka`

3. add to Program.fs under main function the following line
```
let actorSystem = Akka.Actor.ActorSystem.Create "pg"
```

4. make sure project compiles and everything is file

5. migrate to paket (magic mode)

### Expected behavior

Project compiles.

### Actual behavior

Compilation files with the following message:

```
Build FAILED.

C:\projects\pg\Program.fs(1,6): error FS0039: The namespace or module 'Akka' is not defined. [C:\projects\pg\p
g.fsproj]
C:\projects\pg\Program.fs(6,23): error FS0039: The value, namespace, type or module 'ActorSystem' is not defin
ed. [C:\projects\pg\pg.fsproj]
    0 Warning(s)
    2 Error(s)
``` 

### Known workarounds

Add `version 5.119.0` to the top of paket.dependencies file.

**Comment by forki** [comment]
Can you please upload a zip?

Am 19.10.2017 20:31 schrieb "Oleg" <notifications@github.com>:

**Comment by OlegZee** [comment]
Here is the project [pg.zip](https://github.com/fsprojects/Paket/files/1399571/pg.zip)

**Comment by forki** [comment]
oh now I just read properly. Yes we don't integrate with dotnet add.

The command you are looking for is "paket add akka --project pg.fsproj"

**Comment by enricosada** [comment]
@OlegZee i tried unzip your `pg.zip` and the `dotnet build` works (restore with paket, and build the project)

> migrate to paket (magic mode)

what's exactly this step?

**Comment by OlegZee** [comment]
No, guys, the problem is different. Just ignore the attachment.

Will provide more accurate definition once I get to the computer.

I found more showstoppers with 5.119 which made my day. Hope to report more
issues a bit later.
пт, 20 окт. 2017 г. в 20:20, Enrico Sada <notifications@github.com>:

**Comment by OlegZee** [comment]
I repeated all the steps locally and I would confirm the issue is gone.
No idea what's going on. Thank you @forki  and @enricosada for assistance.
