### ISSUE TITLE
paket update --filter does not finish

### ISSUE THREAD

**Issue by olszewst** [fsprojects/Paket#2858]
### Description

Updating packages using the --filter option never finishes.

### Repro steps

Please clone the following repository: https://github.com/olszewst/paket-update-filter-failure
It contains a freshly generated "web" type of project targeting NET Core 2.0 and converted to use Paket.

Running `.paket\paket.exe update Microsoft\.AspNetCore\.All --filter` never finishes.
Updating all packages (by doing `.paket\paket.exe update`) or a specific package (`.paket\paket.exe update Microsoft.AspNetCore.All`) works flawlessly and take a couple of seconds to finish.

### Expected behavior

Running `.paket\paket.exe update Microsoft\.AspNetCore\.All --filter` should finish in a reasonable time.

### Actual behavior

Paket keeps running and does not finish after a couple of minutes of waiting.

### Known workarounds

Updating all packages or only specific packages, one at a time.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/36211450-8c41171a-11a1-11e8-98ee-99964e47ccac.png)

sorry took me a while. but should be fixed
