### ISSUE TITLE
Paket.restore.targets creates nuspec in wrong folder

### ISSUE THREAD

**Issue by trondd** [fsprojects/Paket#2865]
I just upgrade a solution to the new csproj format, but have a problem with packaging with `dotnet pack`
 afterwards. As I understand `paket.Restore.targets` override the packaging process by generating nuspec files which are modified afterward by `paket fix-nuspecs`. The problem is that these nuspec files are duplicated in `obj` and `obj/$(Configuration)`, and only last one is correct. There is one project which does not have a `paket.references` file and it is correctly generated.

As I work-a-round I tried deleting the entire section in the  `paket.Restore.targets` and now everything works as expected. Dependencies are also correct.

**Comment by trondd** [comment]
I've created this small example that reproduces the issue:

https://github.com/trondd/paket-issue-2865

```> dotnet --version
 2.0.2```

**Comment by trondd** [comment]
```
PS C:\Users\tda\tmp\paket-test> dotnet pack /p:Description=foobar
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  bar -> C:\Users\tda\tmp\paket-test\bar\bin\Debug\net461\bar.dll
  bar -> C:\Users\tda\tmp\paket-test\bar\bin\Debug\netstandard2.0\bar.dll
  foo -> C:\Users\tda\tmp\paket-test\foo\bin\Debug\net461\foo.dll
  Successfully created package 'C:\Users\tda\tmp\paket-test\bar\bin\Debug\bar.1.0.0.nupkg'.
  Paket version 5.119.8
  Performance:
   - Runtime: 1 second
  Paket failed with
  -> Could not parse nuspec file 'obj\foo.1.0.0.nuspec'.
  -> XmlException: Root element is missing.
C:\Users\tda\tmp\paket-test\.paket\Paket.Restore.targets(150,5): error MSB3073: The command ""C:\Users\tda\tmp\paket-test\.paket\paket.exe" fix-nuspecs files "obj\foo.1.0.0.nuspec" project
-file "C:\Users\tda\tmp\paket-test\foo/foo.csproj" " exited with code 1. [C:\Users\tda\tmp\paket-test\foo\foo.csproj]

**Comment by forki** [comment]
any chance you could come up with a patch?

2017-10-26 14:47 GMT+02:00 Trond Danielsen <notifications@github.com>:

**Comment by trondd** [comment]
Not sure were to begin. Do you have a clue about what could cause the duplicated nuspec file? I can't find anything in `Declaration.FixNuspecs` that should cause this, but I am not familiar with the other steps in the `paket.Restore.Targets` file.

**Comment by johlrich** [comment]
Same situation and issue here. Did similar research to @trondd and noticed the extra nuspec in obj's root when paket is involved. 

On my end the package would generate without error, but it wouldn't have the lib folder. The nuspec in the root had no file references, while the one in the configuration folder did (both were being generated). My best guess was that the tooling ran into the root one and just built the empty package when paket generated that extra file.

@forki I went through an replaced directory references from `$(BaseIntermediateOutputPath)` to `$(BaseIntermediateOutputPath)$(Configuration)/` for `_NuspecFiles` and `NuspecOutputPath` and everything gets packaged properly after clearing the bin/obj on my project and the repro repo above. Not 100% sure of impact with those changes. Thoughts?

**Comment by forki** [comment]
Cc @alfonsogcnunez is that maybe same issue that you had recently?

Am 28.10.2017 11:11 schrieb "Jonathan Ohlrich" <notifications@github.com>:

**Comment by forki** [comment]
@johlrich I assume it's more correct and PR appreciated

**Comment by johlrich** [comment]
Ok will do. Looks like there's an `$(IntermediateOutputPath)` actually, so will just use that instead.

**Comment by johlrich** [comment]
So it looks like dotnetcli 2.0.0 generates the nuspec in obj\ and dotnetcli 2.0.2 started generating the nuspec in obj\Configuration\

I was doing some work on my laptop with 2.0.0 still installed and it seemed to have different behavior wrt to the nuspec placement. After noticing that, I did some digging and I found the following commits that support this observation:

* This commit added the configuration bit, which shows 4.4.0.4432 as earliest release: https://github.com/NuGet/NuGet.Client/commit/1aa90ec1ad53df22cd119a0e96c538a0f23cea82
* This commit was the first that brought a nuget version later than build 4432 into the dotnet cli, which first appeared in 2.0.2: https://github.com/dotnet/cli/commit/069d94cbe48e78fdd100571cbc660fc2755e4899 

@forki So now I'm 99% sure I figured out what's going on, just not sure what should be done about it from paket's pov

**Comment by forki** [comment]
We should test if the file is in one of the locations and just use that.
Maybe try to use MSBuild condition

Am 30.10.2017 03:06 schrieb "Jonathan Ohlrich" <notifications@github.com>:
