### ISSUE TITLE
"Possible Performance degration, V3 was not working" error when using with TFS feed

### ISSUE THREAD

**Issue by drwatson1** [fsprojects/Paket#2877]
### Description

I get "Possible Performance degration, V3 was not working: One or more errors occurred." message when I use the on-premise TFS server.

### Repro steps

The minimal paket.dependencies file to reproduce:

```
source http://tfs.geobuilder.ru:8080/tfs/DefaultCollection/_packaging/default-1/nuget/v3/index.json
source https://api.nuget.org/v3/index.json

framework: >= net45

nuget GeoCybernetica.Shared ~> 1.1.0.77

```

http://tfs.geobuilder.ru:8080 - is the latest version of on-premise TFS server and it is accessible from internet. I can provide you a login and password to reproduce.

**Comment by shauser** [comment]
I also get this warning since a few days, using an UNC path for our internal repository. It seems to me that it happens when two sources are listed and resolve at the same time.
This is the full error I get (which includes the exception message which caused this for me):
Possible Performance degradation, V3 was not working: The process cannot access the file 'C:\Users\username\AppData\Local\Nuget\Cache\Microsoft.AspNet.WebApi.Client.5.2.3.s1689900308_v5.114.json' because it is being used by another process.Possible Performance degradation, V3 was not working: The process cannot access the file 'C:\Users\username\AppData\Local\Nuget\Cache\Microsoft.AspNet.WebApi.Client.5.2.3.s1689900308_v5.114.json' because it is being used by another process.

**Comment by drwatson1** [comment]
I think this is an another case.
For my issue these messages appear only for packages hosted by on-premise TFS. For nuget.org and myget.org they are absent. 

I found issue #2700 with the similar symptoms.

**Comment by blumu** [comment]
I also get this when pulling from a VSTS V3 feed. Also even though Paket falls back on V2, the message breaks our build because it now gets printed to stderror:
https://github.com/fsprojects/Paket/blob/1cc416b75663110eb3011a397e1e367d26c7047f/src/Paket.Core/Dependencies/NuGet.fs#L304

**Comment by matthid** [comment]
@blumu in vsts there usually is a checkbox in advanced to ignore stderr

**Comment by blumu** [comment]
I am aware of it but this is to ignore errors, not warnings. I still want the task to fail on actual errors, I would not want to ignore them.
Would it make sense to print Paket warnings to stdout like it use to?

**Comment by matthid** [comment]
@blumu Actual errors lead to a non-zero exit code.

**Comment by blumu** [comment]
@matthid Thanks for confirming that paket returns non-zero exit code. I would still love to have a paket option to silence this error though. As a workaround we use the VSTS option to not fail on stderror:
![image](https://user-images.githubusercontent.com/3913258/33148095-520de80c-cf7f-11e7-8ecf-b611479ec8f0.png)
The only drawback: we need to make sure to run paket in a dedicated VSTS task as we still want to fail on stderrors issued by our other build scripts.

**Comment by matthid** [comment]
Yes this is basically the "warnings as errors" feature. Note that in an ideal world we would have zero warnings. But the NuGet ecosystem is a mess and we are glad it is somehow not breaking apart every day. So yeah we have some edge cases.

**Comment by enricosada** [comment]
https://github.com/fsprojects/Paket/blob/1cc416b75663110eb3011a397e1e367d26c7047f/src/Paket.Core/Dependencies/NuGet.fs#L304

@matthid putting that to stdout instead of stderr can be ok?

**Comment by drwatson1** [comment]
As for me, I think it is a workaround only, not a solution. Because V3 is working

**Comment by matthid** [comment]
In my opinion warnings need to go to stderr not stdout, because stdout needs to be potentially parsable. That is generally agreed on in the unix and command line world.

**Comment by matthid** [comment]
Ideally the root cause is solved ;)

**Comment by matthid** [comment]
> Ideally the root cause is solved ;)

I should add: if that is not possible for some technical reason we *could* add an option to silence that particular warning.

**Comment by forki** [comment]
Everything agrees except Microsoft.

Am 24.01.2018 17:59 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment]
> Everything agrees except Microsoft. 

It's really just a matter of defaults. Microsoft thinks defaulting to "Warning as error" is a good default and you cannot argue with that. It's more a problem with people not being able to change the defaults ;)

**Comment by drwatson1** [comment]
))))
I don't think so. It's look like a holy war therefore.
I can supply you with an account to our server if you want to see what's the matter or you can close the issue as none relevant.... It's up to you)))

**Comment by matthid** [comment]
No war. Ultimately, we have something here which is not critical but might need to be fixed (-> therefore a warning).
Until then disabling "warning as error" is a viable workaround.

**Comment by drwatson1** [comment]
Ok, I agree
It's more then nothing)) Thank you
But what do you think about this? Is it a real degradation or it is a possibility only? About a month or two ago 'paket install' takes about 30-40 minutes to add a one new package.... For now it works several minutes

**Comment by matthid** [comment]
Some additional info (verbose mode):

```
Starting request to 'https://tfs/tfs/TEAM/_packaging/GUID/nuget/v3/registrations2/PACKAGE/index.json'
Possible Performance degradation, V3 was not working: Value cannot be null.
Parameter name: source
Error while using V3 API: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Microsoft.FSharp.Collections.SeqModule.Filter[T](FSharpFunc`2 predicate, IEnumerable`1 source)
   at Paket.NuGetV3.tryFindOnPage@789-4.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)

```

**Comment by matthid** [comment]
Actually I think this has been fixed since https://github.com/fsprojects/Paket/pull/3341
