### ISSUE TITLE
paket install does not cache resolved packages

### ISSUE THREAD

**Issue by MiloszKrajewski** [fsprojects/Paket#2878]
### Description

I'm not clear if it is a bug, but it is very annoying. "paket install" keeps resolving packages even if there was no change.

### Repro steps

I couldn't find any specific reason why it happens in my case so I needed to include small project.
[test2.zip](https://github.com/fsprojects/Paket/files/1430873/test2.zip)

1. Unzip
2. run "paket install"
3. run "paket install"

### Expected behavior

It should skip resolving packages the second time.

### Actual behavior

It resolves packages every time.

### Known workarounds

In other projects it works, I have no idea what causes such behaviour is this case.

**Comment by forki** [comment]
This means there is an issue with the out of date check. Thanks for repro.
Will investigate next week

Am 31.10.2017 14:39 schrieb "Milosz Krajewski" <notifications@github.com>:

**Comment by MiloszKrajewski** [comment]
I'm not closing it as it might still be a bug but I fixed it for my machine.
Apparently, the assembly I was using was "prerelease" but dependencies file was not having prelease flag. As this assembly had ONLY prereleases it was still downloaded (bug?), but later it was always reported as "VersionNotValid" from "findNuGetChangesInDependenciesFile".

I guess, it should not be resolved in the first place (it was "prerelease" but without "prerelease" flag in dependencies file).

Anyway, it works for me now.

**Comment by forki** [comment]
No. This is actually a special case then and paket works as expected. If only prereleases are available then we take one, but out of date check will trigger since it wants to switch to release as soon as possible
