### ISSUE TITLE
[Q] Stating differences between install and restore commands

### ISSUE THREAD

**Issue by eugene-g** [fsprojects/Paket#2879]
I've learned that at least several people are using `paket install` instead of `paket restore`. I suggest improving documentation and stating exact differences to avoid confusion.

Currently, we have following:

`paket restore`: `Download the computed dependency graph.`
`paket install`: `Download dependencies and update projects.`

@TheAngryByrd pointed out, that `paket restore` also creates `obj` folder which is _probably_ required for intellisense. Anything else?

I'll send PR after gathering clarifications.

**Comment by talbottmike** [comment]
@eugene-g  I was fighting with this too and @igorsutton helped me out. I had to close and re-open all my vscode instances. Apart from that vscode specific issue, I found the docs here helpful.
https://fsprojects.github.io/Paket/paket-and-dotnet-cli.html

**Comment by forki** [comment]
Install should do everything that restore does + additional resolver run if
it thinks it is needed.

(if you found something that restore does, but install does not then please
report)

Am 01.11.2017 02:33 schrieb "talbottmike" <notifications@github.com>:

**Comment by eugene-g** [comment]
> paket restore also creates obj folder

Could not reproduce for `paket restore`. Though, `dotnet restore` creates `obj` folders. Okay, no questions left here. Sending PR for minor docs clarification and closing this issue.

**Comment by eugene-g** [comment]
PS.
@talbottmike `reload window` usually does the trick. If not, try also `clear cache` before `reload window`.
