### ISSUE TITLE
paket doesn't preserve file permission

### ISSUE THREAD

**Issue by somdoron** [fsprojects/Paket#2893]
### Description

I have a package which have one linux executable file which I pack with paket.

However paket don't preserve the executable permission of the file. So when restoring the package the file is not executable and I have to manually set the file permission.

### Repro steps

1. Pack one executable file to output directory, example of paket file

```
type file
id package_example
version 0.0.0.1
authors XXX
files
  executable ==> output
dependencies
  Baseclass.Contrib.Nuget.Output >= 2.4.0
```

2. Restore the package

### Expected behavior

The file executable permission is preserved

### Actual behavior

The file is not executable

### Known workarounds

manually change the file permission in the packages directory.

**Comment by MiloszKrajewski** [comment]
I don't think it is paket bug. I understand that .nupkg is actually a zip file so storing unix permissions is not supported. I don't think there is possibility to put permissions in .nuspec file either.

As your symptoms are real (no unix permissions) you diagnosis is most likely wrong: it has nothing to do with paket. It is zip/nuspec format.

**Comment by somdoron** [comment]
I think you can, but the .net ZipArchive doesn't support that. Anyway thanks, I will close it for now.

**Comment by matthid** [comment]
Related https://github.com/dotnet/templating/issues/1028

**Comment by matthid** [comment]
> .nupkg is actually a zip file so storing unix permissions is not supported

Actually, zip supports file attributes. It could be possible to make paket support that scenario, the only question is if nuget.exe still works with such packages.
