### ISSUE TITLE
Paket Update seems to be ignoring dependencies?

### ISSUE THREAD

**Issue by wooderz** [fsprojects/Paket#2896]
### Description

When updating a package in a project, it seems to not update dependencies. For example

### Repro steps

1) Have Project 1 with MassTransit.
2) Have Project 2 with Project 1
3) Update MassTransit in Project 1
4) Update Project 1 in Project 2

Error message:
Assembly 'Project1' with identity 'Project1, Version=1.2.45.0, Culture=neutral, PublicKeyToken=null' uses 'GreenPipes, Version=1.2.0.96, Culture=neutral, PublicKeyToken=b800c4cfcdeea87b' which has a higher version than referenced assembly 'GreenPipes' with identity 'GreenPipes, Version=1.1.0.83, Culture=neutral, PublicKeyToken=b800c4cfcdeea87b'	

### Expected behavior
Dependency to be updated appropriately

### Actual behavior

Dependency not updated

### Command being executed
paket update ^Project1\\.\\S+ --redirects --create-new-binding-files --force

### Note
GreenPipes is not installed in Project 2. It is a dependency of Project 1 that doesn't seem to be being cleaned up/updated

**Comment by wooderz** [comment]
Anyone?

**Comment by forki** [comment]
do you have a repro?

**Comment by wooderz** [comment]
Not at the moment, this was 10 days ago and we've moved on now. If it happens again I'll provide a repro. One of the things I did think about was that if the dependency allows a >= for the dependency, MSBuild only copies over the one that matches the version number exactly..

I think setting the strategy to min actually solved this one for us, but not an ideal solution

**Comment by enricosada** [comment]
> Not at the moment, this was 10 days ago and we've moved on now. If it happens again I'll provide a repro

Closing. @wooderz please open a new issue if you get the bug another time
