### ISSUE TITLE
Paket Install always resolves

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2897]
Run ``paket install`` twice.

Expected: it resolves once, then says it is up-to-date

Actual: it resolves twice

-----------------

I have a hunch that it may be because the dependencies file specifies no prerelease (``nuget Precast.MsBuild``), but the actual package is prerelease (``Precast.MSBuild (0.5.0-alpha)``).

So it probably shouldn't resolve at all, and instead throw an error?

[paket-install.zip](https://github.com/fsprojects/Paket/files/1470863/paket-install.zip)

**Comment by MiloszKrajewski** [comment]
Your guess is right. I raised same issue here #2878 (my conclusion was wrong but describing same symptom).

**Comment by 0x53A** [comment]
thank you
