### ISSUE TITLE
Getting started and FAQ disagree on whether to commit .paket/paket.exe

### ISSUE THREAD

**Issue by Danl2620** [fsprojects/Paket#2902]
### Description

In the documents, the "Getting Started with Paket" [section](https://fsprojects.github.io/Paket/getting-started.html#Manual-setup) instructs you to add `.paket/paket.exe` to your source control repository. Meanwhile in the [FAQ](https://fsprojects.github.io/Paket/faq.html#What-files-should-I-commit) it tells you _not_ to add that file to the repository.

**Comment by forki** [comment]
Oh it's difference between magic mode and real paket.exe. Yes we need to
make docs consistent.

Currently we recommend: download latest paket bootstrapper.exe and rename
it to paket.exe and commit it.

Would love to see PRs that fix docs accordingly. Thanks so much

Am 16.11.2017 20:20 schrieb "Dan Liebgold" <notifications@github.com>:
