### ISSUE TITLE
Duplicate in the documentation

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#2903]
https://fsprojects.github.io/Paket/nuget-dependencies.html#Controlling-assembly-binding-redirects

![image](https://user-images.githubusercontent.com/873919/32937270-d7ee1064-cb88-11e7-8841-e5229a0b60da.png)

**Comment by CaringDev** [comment]
Fixed in https://github.com/fsprojects/Paket/commit/1d07a30bbc1c2fc1e780a614b976f838fc989cab#diff-ff980f08099e2bfda5c9290296d4e00b
Suggest to close.
