### ISSUE TITLE
Build failure on Linux

### ISSUE THREAD

**Issue by njlr** [fsprojects/Paket#2904]
### Description

The build fails on Ubuntu for me. 

### Repro steps

1. `git clone ... `

2. `./build.sh`

Log here: [build.txt](https://github.com/fsprojects/Paket/files/1485092/build.txt)

### Expected behavior

Build to finish

### Actual behavior

Build crashes

### Additional information

```
$ mono --version 
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

$ git log -1 
commit 482611c5b26610dba1b9f45c1e3950058334dfd5
Author: Steffen Forkmann <steffen.forkmann@msu-solutions.de>
Date:   Tue Nov 14 10:36:40 2017 +0100

    clean obj

```

**Comment by enricosada** [comment]
@njlr As per prerequisited ( https://github.com/fsprojects/Paket#linux ), required mono is > 5.0

as a note, now the build is under CI with travis, testing ubuntu and mono 5.4

Closing, please reopen if doesnt build it supported mono/os version
