### ISSUE TITLE
Paket install removes assembly bindings in app.config

### ISSUE THREAD

**Issue by princevince** [fsprojects/Paket#2905]
In my Windows app with .NET Framework 4.6.2:

When I throw away the packages folder to start fresh and then run `paket install`, the assembly bindings get removed from the app.config file of each project.

I manually have to undo all changes to the app.config files before checking them in. Otherwise my application throws a big fat error because of invalid assembly references.

**Comment by princevince** [comment]
Running `paket update` does the same. It throws away all the assembly references in the app.config. Why is this? I don't know whether they are needed or not, but my project won't start without them. These are a few of the dependencies that are deleted from the app.config file:

  ```
<dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.6.2.0" />
  </dependentAssembly>
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="Autofac.Integration.WebApi" publicKeyToken="17863af14b0044da" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.1.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="Autofac.Integration.Owin" publicKeyToken="17863af14b0044da" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.1.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.1.1.0" />
  </dependentAssembly>
```

The error I'm getting is:

```
Unhandled exception System.IO.FileLoadException: Could not load file or assembly 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da'
```

It sure looks like the code expects version 3.5.0.0 while my paket definitely references a newer version.

This is inside my paket.dependencies file:
```
nuget Autofac 4.6.2 restriction: >= net462
nuget Autofac.Owin 4.1.0 restriction: >= net462
nuget Autofac.WebApi2 4.1.0 restriction: >= net462
nuget Autofac.WebApi2.Owin 4.0.0 restriction: >= net462
```

**Comment by princevince** [comment]
I don't even have to delete the packages-folder. Simply running `paket update` removes all dependencies from the app.configs.

**Comment by princevince** [comment]
Ok. I think this repository is dead. It costed me two days, now I'm back to NuGet and everything works fine again.

**Comment by cdrnet** [comment]
Assuming you invested 5 minutes of these 2 days looking at the [docs](https://fsprojects.github.io/Paket/dependencies-file.html#Controlling-assembly-binding-redirects), what options did you try and what did not work as expected?

**Comment by princevince** [comment]
In the past 2 days I've read for hours in the docs and tried everything. Digging into all transitive dependencies, plowing through the .csproj file for false references, and completely rebuilding the app from the paket.dependencies file. Nothing worked. I couldn't figure it out. It's hard to find a solution in the docs if you don't know what you are looking for. I've asked for help here. No replies. I didn't know on beforehand that Paket was going to fuck up my project this bad. Otherwise I would have never started the whole conversion.

**Comment by forki** [comment]
@princevince 

did you try to use `redirects:force` it usally solves this.

**Comment by princevince** [comment]
No, I didn’t. I didn’t know the option was there. If I knew I could fix it this easy I would have done it. Now it costed me two days to figure out what went wrong. Couldn’t find it and went back to Nuget package manager.

**Comment by forki** [comment]
where would you have expected that info? It's right at https://fsprojects.github.io/Paket/dependencies-file.html#Controlling-assembly-binding-redirects

**Comment by Krzysztof-Cieslak** [comment]
@princevince, next time if you'd be interested in commercial level SLA (as I assume you need that if you declare repository dead after no response in 48h) for getting help with problems around F# OSS projects feel free to contact any consultancy specializing in F# ecosystem... just not with my company, I prefer to work with people that are able to read documentation :-)

**Comment by 0x53A** [comment]
![grafik](https://user-images.githubusercontent.com/4236651/33182774-925e0e40-d075-11e7-9adf-77ff82b8e6c6.png)

**Comment by princevince** [comment]
I prefer to work with software that doesn’t screw up my project this bad. Nor would I like to work with software wherefor it’s necessary to read the documentation for hours while still having no clue what to look for. I’ve also googled my ass off with terms like: “paket removes assembly references in app.config”. Nothing to be found. It’s hard to look for something while not knowing what to look for. I hoped for a positive and polite push in the right direction maybe. Instead I got accused of not reading the docs... 
It was a mistake to read the docs in the first place because it was promising me a better experience than with Nuget because I could use multiple package sources and I was promised to be in total control of the dependencies. The opposite is true. It totally messed up my dependencies and I haven’t been able to get my software up and running ever since I converted my project for use with Paket. Now I’m back to using Nuget and I’m able to focus on the important stuff again.

**Comment by princevince** [comment]
I wish someone showed me this in the 48 hours I was trying to save my project from a disaster.

**Comment by princevince** [comment]
Yeah, thanks. So I’ve been told. It’s not necessary anymore.

**Comment by forki** [comment]
@princevince I explicitly asked where you would suggest to improve the docs. I was looking for that feedback from you. And regarding "screwing up" - could you please provide a repro with what paket did wrong exactly? I think it's working really nicely with redirects, but maybe you hit a corner case?

**Comment by princevince** [comment]
I'm sorry Steffen. I'm sure Paket can do what it promises to do and I didn't want to get upset. It was because there are two things going on here. First: I have a deadline to catch before the end of november (totally my fault to start experimenting with a new package manager at this time) and I've spend two days trying to figure out why my assembly bindings were thrown away without any warning. Second: The first guy to react was implying I didn't take 5 minutes to read the documentation. True, I didn't read it from A to Z like a book. Apparently I was trying to find that one setting "redirect: on". I'm the one to blame for the fact I didn't know this was called "Assembly Binding Redirect". Otherwise I think I would have been able to find it. However, I would still like to know why the default is "off". I haven't tried it yet -because I don't have time for it now- but will this "redirect: on" be included if I had first converted the project from NuGet instead of afterwards?

**Comment by forki** [comment]
the situation is very simple: most people don't want to have binding redirects until things are needed. Then they add redirects:force to the packages where it's actually needed. This has to do with the fact that the app.config is a mess if add redirects for hundreds of packages and that you will always get merge confilcts there.

**Comment by princevince** [comment]
Thanks. I totally understand. In my case I had a hard time finding the packages that needed a reference to autofac version 3.5.0.0. Maybe because my app.configs are such a mess... So I think I still wouldn't be able to fix it with `redirects:force` in one ore more projects. Fact is that with NuGet I totally don't have to worry about this. It's the first time I have to dig into dependencies this deep. And maybe that's a good thing.

**Comment by forki** [comment]
> Fact is that with NuGet I totally don't have to worry about this

famous last words ;-)
TBH exactly the issues around nuget and redirects made us build paket in the first place

**Comment by 0x53A** [comment]
If you don't care about your app.config getting a little bit messy, you can add ``redirects: force`` to the __group__, then redirects will be added for __all__ packages, regardless of whether they are actually needed or not.
