### ISSUE TITLE
framework conditionals for assembly reference are incorrect in some circumstances

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/Paket#2906]
### Description

I have a repository with projects using NUnit and targetting framework 4.6.2, somehow, the assembly reference gets written by paket with the wrong framework conditionals.

This doesn't happen with a simpler `paket.dependencies` mentionning only NUnit.

### Repro steps

* call `paket install` in attached sample [paketnunit.zip](https://github.com/fsprojects/Paket/files/1489313/paketnunit.zip)
* check `ClassLibrary1/ClassLibrary1.csproj` file and locate nunit.framework assembly reference

### Expected behavior

It should have a bunch of framework versions in the conditionals, similar to Moq dependency.

### Actual behavior

Only has `Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5'"`

### Known workarounds

Haven't found one, beside bypassing `paket.references`.

**Comment by smoothdeveloper** [comment]
The issue is appearing in the `paket.lock` file which contains `NUnit (3.0.1) - restriction: == net45`, it seems this should have wider restriction.

Any clue where is the code dealing with deciding what to put there?

**Comment by matthid** [comment]
> Any clue where is the code dealing with deciding what to put there?

Yes I tried to give a bit more insights here:
https://yaaf.de/blog/post/2017-10-16/Paket%20internals%20-%20Framework%20Restrictions#Datastructures-and-Resolving-overview

Can you post your dependencies file so I can take a look on mobile ;)? I guess paket figured out that NUnit is only required for the single framework acording to your dependencies file...

**Comment by forki** [comment]
strategy: max
    source https://www.nuget.org/api/v2
    redirects: on
    framework: >= net40
    generate_load_scripts: true
    
    nuget AdamsLair.WinForms
    nuget AeroWizard
    nuget Antlr < 3.2
    nuget BenchmarkDotNet
    nuget Boo
    nuget Boo.Lang.Useful
    nuget Castle.Core = 2.5.2.0
    nuget Castle.ActiveRecord ~> 3
    nuget CommonServiceLocator
    nuget CsvHelper = 2.13.5
    nuget Dapper.StrongName
    nuget DockPanelSuite
    nuget ExcelDataReader
    nuget FAKE
    nuget FAKE.Lib
    nuget FileHelpers
    nuget FParsec
    nuget FsCheck
    nuget FSharp.Charting
    nuget FSharp.Collections.ParallelSeq
    nuget FSharp.Configuration
    nuget FSharp.Core
    nuget FSharp.Core.Fluent-4.0
    nuget FSharp.Data
    nuget FSharp.Data.SqlClient = 1.8.3-beta4
    nuget FSharp.Formatting
    nuget FSharp.Management
    nuget FSharp.Text.RegexProvider
    nuget FSharp.TypeProviders.StarterPack
    nuget FSharpVSPowerTools.Core
    nuget FSharpx.TypeProviders.Management
    nuget FSharpx.Async
    nuget FSharpx.Collections
    nuget FSharpx.Extras
    nuget FsUnit
    nuget Giraffe
    nuget GMap.NET.WindowsForms
    nuget Hopac
    nuget Hype
    nuget log4net
    nuget LumenWorks.Framework.IO
    nuget Iesi.Collections < 4
    nuget MBrace.Core condition: Azure
    nuget MBrace.Flow condition: Azure
    nuget MBrace.Runtime condition: Azure
    nuget MBrace.Azure condition: Azure
    nuget MBrace.Azure.Management condition: Azure
    nuget MetroFramework
    nuget Microsoft.Automatic.Graph.Layout
    nuget Microsoft.Azure.Management.Compute prerelease condition: Azure
    nuget Microsoft.Azure.Management.ResourceManager prerelease condition: Azure
    nuget Microsoft.Azure.Management.Sql prerelease condition: Azure
    nuget Microsoft.IdentityModel.Clients.ActiveDirectory = 2.19.208020213 condition: Azure
    nuget Mono.Cecil
    nuget Moq
    nuget MySql.Data
    nuget MvvmLight
    nuget netfx-System.Reactive.Event
    nuget Newtonsoft.Json
    nuget Npgsql ~> 2
    nuget NuGet.CommandLine
    nuget NUnit.Runners
    nuget NUnit = 3.0.1 framework: net45
    nuget reactiveui
    nuget Rhino-Etl
    nuget RhinoMocks
    nuget Rx-Linq
    nuget Rx-WinForms
    nuget Rx-Xaml
    nuget SevenZipSharp
    nuget SharpSvn.1.9-x64
    nuget SharpZipLib
    nuget SourceGrid
    nuget Spark
    nuget SQLProvider
    nuget Topshelf
    nuget QuickGraph
    nuget Wix.Toolset
    nuget ZedGraph
    


^from the zip

**Comment by forki** [comment]
nuget NUnit = 3.0.1 framework: net45


;-)

**Comment by matthid** [comment]
looks like the expected outcome then :)

**Comment by smoothdeveloper** [comment]
mmmh, I guess I'll call user error on that one... sorry for disturbance.

**Comment by smoothdeveloper** [comment]
For the record, I added that restriction when I faced #1621 which should not be a concern anymore.
