### ISSUE TITLE
Restores slow with dotnet sdk 2.0.3

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#2907]
### Description

Setup: Project B (net462) depends on Project A (netstandard2.0)

When checking for existence of `PaketResolvedFilePath` file in `Paket.Restore.targets`
```
<!-- Step 2 b detect relevant changes in project file (new targetframework) -->
    <PropertyGroup Condition=" !Exists('$(PaketResolvedFilePath)') AND '$(TargetFramework)' != '' ">
      <PaketRestoreRequired>true</PaketRestoreRequired>
      <PaketRestoreRequiredReason>target-framework '$(TargetFramework)'</PaketRestoreRequiredReason>
    </PropertyGroup>
```

If the project it's trying to restore against Project B, `TargetFramework` seems to be set to `net462` and the `PaketResolvedFilePath` doesn't exist since it's looking for 
`ProjectA/obj/ProjectA.fsproj.net462.paket.resolved` instead of `ProjectA/obj/ProjectA.fsproj.netstandard2.0.paket.resolved` and therefore needs to do a restore making the build a lot slower.

### Repro steps

I'll get you a repro later

### Expected behavior

Microsoft doesn't break shit in hotfix versions

### Actual behavior

Microsoft breaks shit in hotfix versions

### Known workarounds

Pinning to sdk 2.0.0

**Comment by forki** [comment]
Can you please report this to the corresponding Microsoft repos? /cc
@cartermp

Am 20.11.2017 23:21 schrieb "Jimmy Byrd" <notifications@github.com>:
