### ISSUE TITLE
Paket failed to resolve some dependencies

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/Paket#2908]
### Description

Can't build the repo, because paket failed to resolve two dependencies.

> C:\Projects\fable-repl\src\Fable.REPL\Fable.REPL.fsproj : error NU1100: Unable to resolve 'System.ValueTuple (>= 4.0.0)' for '.NETStandard,Version=v2.0'. [C:\Projects\fable-repl\Fable.REPL.sln]
C:\Projects\fable-repl\src\Fable.REPL\Fable.REPL.fsproj : error NU1100: Unable to resolve 'FSharp.Core (>= 4.2.0)' for '.NETStandard,Version=v2.0'. [C:\Projects\fable-repl\Fable.REPL.sln]

### Repro steps

Repo used: https://github.com/fable-compiler/fable-repl

* Create a folder to host the repo like "fable_repl_projects". (The build process will download several folders, at the same level as `fable-repl`)
* git clone git@github.com:fable-compiler/fable-repl.git
* git checkout update_fable_1_3
* build.cmd All setup=auto (this command can take some time, it will download several folders and build a lot of stuff, next executions will be quicker because it doesn't need to download everything)

### Expected behavior

Paket should resolve the dependencies and not crash the processus.

### Actual behavior

Paket doesn't resolve `System.ValueTuple` and `FSharp.Core`

### Known workarounds

Commenting [this line](https://github.com/fable-compiler/fable-repl/blob/ba7beb65988334c0bda0dd992f347fa3560d3d9c/src/Fable.REPL/Fable.REPL.fsproj#L32) allow us to build.

**Comment by ncave** [comment]
@MangelMaxime correct me if I'm wrong, trying to give it a bit more detail:
To clarify, it's the `dotnet restore` that fails, with dotnet core 2.0.2 and 2.0.3 (and anecdotally it was working before, started to fail fairly recently, without a code change, so it could be a new paket version, or one of the dependencies (just speculating here, my understanding of how paket works is very limited).

**Comment by MangelMaxime** [comment]
Hum yes, we were working on it. And it was working then one hour after it was failing without any change in the code.

Perhaps we can try to use an older version of paket and see if we can isolate a version by doing that.

**Comment by TheAngryByrd** [comment]
You might also want to try pinning to dotnet core 2.0.0 in your `global.json`.

**Comment by MangelMaxime** [comment]
Hum...

To test @TheAngryByrd options, I forced the dotnet version to `2.0.0` and it was working, then I change it to `2.0.2` and it was working. I switched back to `2.0.3` and it's working too.

Then, I decided to try from a fresh repo with `2.0.3` and it's failing again. Don't really understand what's happening.

**Comment by forki** [comment]
Is this still an issue? can you please retry? I think I fixed it

**Comment by MangelMaxime** [comment]
Thank you, it's seems fixed for me.

**Comment by ncave** [comment]
@forki I can still easily reproduce this issue on Fable master, if I project-reference some non-paket enabled project (for example the visualfsharp FCS). Perhaps this is to be expected (or not).

- cd /Fable/src/dotnet/Fable.Compiler/
- remove FCS from paket.references
- add FCS project reference to Fable.Compiler.fsproj:
`<ProjectReference Include="../../../../visualfsharp/fcs/FSharp.Compiler.Service.netstandard/FSharp.Compiler.Service.netstandard.fsproj" />`
- `dotnet restore`

`error NU1100: Unable to resolve 'System.ValueTuple (>= 4.0.0)' for '.NETStandard,Version=v1.6'.`

Paket version 5.133.0
dotnet 2.1.4

**Comment by runefs** [comment]
Had this issue with a different fable project. The resolution was to use an newly updated version of paket (instead of the one in .paket) to restore the package

**Comment by forki** [comment]
@ncave still an issue?

**Comment by ncave** [comment]
@forki The solution from @runefs sounds good, if nobody else has the issue anymore, you can probably close this.
