### ISSUE TITLE
Paket adds different Rx-PlatformServices library than Nuget when installing ReactiveUI

### ISSUE THREAD

**Issue by AlexAtNet** [fsprojects/Paket#2909]
### Description

paket and nuget installs different versions of the dependent library when installing reactiveui.

### Repro steps

I'm adding ReactiveUI to the project https://github.com/AlexAtNet/WPFFSharpQuickStart/tree/reactive as follows:

PS E:\WPFFSharpQuickStart> ./paket add reactiveui --version 7.4.0 --project MyApp\MyApp.fsproj

If fails to run because the System.Reactive.PlatformServices.dll added to the project has version 2.3 (while all other reactives has 2.2.5). When I add reactiveui with nuget, it installs the 2.2.5 version of Rx-PlatformServices.

### Expected behavior

Consistent behaviour from both paket and nuget in this use case.

### Known workarounds

Probably the exact version of the Rx-PlatformServices can be installed with paket.

**Comment by forki** [comment]
Paket has explicit flags to control resolution.
https://fsprojects.github.io/Paket/nuget-dependencies.html#The-modifier-1

Am 22.11.2017 03:18 schrieb "Alex Netkachov" <notifications@github.com>:

**Comment by AlexAtNet** [comment]
Thanks a lot! I've added "nuget reactiveui !~> 7.4.0" and it works well.

Is it expected behaviour from paket and not a bug? If it is not, can reactiveui team modify their package description to make it work better with paket?

Alternatively, is there any way to pinpoint only Rx-PlatformServices?

Kind Regards,
Alex

**Comment by forki** [comment]
no this is perfectly fine defined behaviour. NuGet has a different resolver and these giys see things differently. We provide a fallback to do the same (which we normally not recommend)

the problem is that teams like Rx only test against NuGte and therefor dependency meta data is often worse than it could be.
