### ISSUE TITLE
Paket Add Nuget Package is slow for already installed packages

### ISSUE THREAD

**Issue by Lanayx** [fsprojects/Paket#2910]
I've added a new project to a solution with other projects. All of them share the same paket.lock file. However when I add package to the new project that other projects already use it takes a long time. Here is the output:

```
Performance:
 - Resolver: 1 minute, 5 seconds (1 runs)
    - Runtime: 1 second
    - Blocked (retrieving package details): 52 seconds (79 times)
    - Blocked (retrieving package versions): 12 seconds (12 times)
    - Not Blocked (retrieving package details): 119 times
    - Not Blocked (retrieving package versions): 186 times
 - Disk IO: 3 seconds
 - Average Request Time: 786 milliseconds
 - Number of Requests: 476
 - Runtime: 1 minute, 11 seconds
```

From my point of view when adding an existing package, it should complete immediately, since this package is already on the disk and all dependencies are known. Am I right or not?

**Comment by forki** [comment]
Can you please give deps file and lock file? And the command you executed

Am 22.11.2017 09:29 schrieb "Vladimir Shchur" <notifications@github.com>:

**Comment by Lanayx** [comment]
I'm running _Paket: Add Nuget Package (to current project)_  command from Ionide-Paket

[paket.zip](https://github.com/fsprojects/Paket/files/1495518/paket.zip)

**Comment by forki** [comment]
should be fixed in latest. can you please retry?

**Comment by Lanayx** [comment]
Thank you, it worked.
