### ISSUE TITLE
Paket not updating project file

### ISSUE THREAD

**Issue by wooderz** [fsprojects/Paket#2912]
[Communication Service (Paket).zip](https://github.com/fsprojects/Paket/files/1499691/Communication.Service.Paket.zip)
### Description

Running the command `paket add <package> --redirects --create-new-binding-files --project <project>` will add the reference to the paket.references file, but not to the actual project. The csproj file is not changed.

### Repro steps

1. In attached project navigate to `src` folder.
2. Run `paket add WhenYouMove.Cases.Sdk --redirects --create-new-binding-files --project Tools`

### Expected behavior

Project file should be updated

### Actual behavior

Project File is not updated

**Comment by wooderz** [comment]
Why was this closed? I've given a repro and steps? Just closing without any comment??

**Comment by forki** [comment]
not without comment, but with  f54c122

**Comment by forki** [comment]
in other words: please try latest ;-)

**Comment by wooderz** [comment]
Ha! Dude sorry for being short... i'm having a bad day! Thanks for the quick one! Will try it right now

**Comment by wooderz** [comment]
Quick heads up, seems the bootstrapper isn't downloading the 5.122.3 exe. Will go download the exe manually
