### ISSUE TITLE
mixed with `<PackageReference PrivateAssets=All` doesnt download the nupkg

### ISSUE THREAD

**Issue by enricosada** [fsprojects/Paket#2930]
### Description

If not already in cache, the `PackageReference` is not downloaded

Atm is not yet possibile to specify that type of dependency in paket only, ref #2370 

### Repro steps

- `dotnet new lib -lang F#`
- make it paket ready
- add `<PackageReference Include="SourceLink.Create.CommandLine" Version="2.1.1" PrivateAssets="All" />`
- `dotnet restore`

### Expected behavior

the package reference is added, and doesnt exists in the deps after `dotnet pack`

### Actual behavior

fails with

```
E:\temp\provactag\provactag.fsproj : error NU1100: Unable to resolve 'SourceLink.Create.CommandLine (>= 2.1.1)' for '.NETStandard,Version=v2.0'.
```

### Known workarounds

Create a group, and restore it before the `dotnet restore`, with the exact version, so the nupkg is in cache

```
group NetCoreTools
  storage: none
  source https://nuget.org/api/v2

  nuget SourceLink.Create.CommandLine 2.1.1
```

and `paket restore -g NetCoreTools`

after that, `dotnet restore` works

**Comment by forki** [comment]
"mixed" is not supported any anyway. Because we have nuget.config that
forbids additional packages.

Am 05.12.2017 18:32 schrieb "Enrico Sada" <notifications@github.com>:

**Comment by enricosada** [comment]
Closing so.

It always worked for me, minus this issue, i was thinking was an ok scenario.
I use it a lot for `Microsft.Test.Sdk`, etc, pratically all sdks
@forki there is a way to configure paket to add a "development" dependency, so is not going in nupkg after `dotnet pack`?

**Comment by forki** [comment]
There is an issue about adding development dependencies to the netcore
support. I just need to know how to set the attributes

Am 05.12.2017 18:39 schrieb "Enrico Sada" <notifications@github.com>:

**Comment by enricosada** [comment]
@forki info is in https://github.com/fsprojects/Paket/issues/2370#issuecomment-307894201

The added `Assets` data to nuget deps, to change how deps flow.
with `Include`/`Exclude`/`Private` as modifier. you can see that in a generated nuspec or a PackageReference

- Compile – are the contents of the lib folder available to compile against
- Runtime – are the contents of the runtime folder distributed
- ContentFiles – are the contents of the contentfiles folder used
- Build – do the props/targets in the build folder get used
- Native - are the contents from native assets copied to the output folder for runtime
- Analyzers – do the analyzers get used

Plus `All` = shortcut for all in that list, `None` = none of that list

Pratically, if `PrivateAssets=All`, mean all these type of assets are private of the project (so no need to add the deps in the nupkg dep list)

in netcore is easier, because in paket target file you create the `PackageReference` items
