### ISSUE TITLE
How to disable local package download but use %UserProfile\.nuget\packages% cache instead?

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/Paket#2933]
Is it possible?
And how if possible?

**Comment by forki** [comment]
What do you mean? We use the cache.

**Comment by xperiandri** [comment]
I mean do not create `packages` folder at all but use %UserProfile\.nuget\packages% in order to resolve packages

**Comment by forki** [comment]
There is an option for that "storage:none" - you can set that per group.
But you should only do that for new style sdk projects

Am 09.12.2017 10:49 schrieb "Andrii Chebukin" <notifications@github.com>:

**Comment by xperiandri** [comment]
So that I just put this at the top of paket file?
Looks like it works

**Comment by forki** [comment]
Yes if only have one group then top of deps file will do

Am 10.12.2017 10:24 schrieb "Andrii Chebukin" <notifications@github.com>:

**Comment by enricosada** [comment]
> Looks like it works

Closing
