### ISSUE TITLE
paket pack packages entire directory into package lib folder when files block contains an empty line

### ISSUE THREAD

**Issue by sanderaernouts** [fsprojects/Paket#2949]
### Description
```paket pack``` packages entire directory into package lib folder when files block contains an empty line

### Repro steps
1. Create a paket.template file with an empty line between files:
```
type file
id some.package
files
  path/to/a/file ==> build/bin

  path/to/another/file ==> build/bin
```
Please provide the steps required to reproduce the problem

2. run ```paket pack out --template paket.template```

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior
The package contains only a build/bin folder with 2 files in there

### Actual behavior
The package contains a build/bin folder with 2 files in there but also contains a lib folder with the contents of the entire folder where the paket.template file is placed

### Known workarounds
Have no empty lines in your files block.

**Comment by sanderaernouts** [comment]
@enricosada any updates on this? Had the same issue again yesterday (paket  5.145.1) and this produces a 1GB package.

**Comment by sanderaernouts** [comment]
Thanks @forki

**Comment by forki** [comment]
please test and let me know. thanks
