### ISSUE TITLE
support equivalent of PrivateAssets="All"

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#2951]
See #2930 and https://github.com/ctaggart/SourceLink/issues/288. I'm looking for the equivalent of this, but using paket:
``` xml
  <ItemGroup>
    <PackageReference Include="SourceLink.Create.CommandLine" Version="2.7.2" PrivateAssets="All" />
    <PackageReference Include="SourceLink.Embed.PaketFiles" Version="2.7.2" PrivateAssets="All" />
  </ItemGroup>
```

**Comment by forki** [comment]
Will look into this tomorrow. If I find time...

**Comment by forki** [comment]
ok please retry with latest version. we reuse the copy_local settings. If copy_local is set to true, then this should set the PrivateAssets attribute to "All".

You need latest paket.exe and Paket.Restore.targets

/cc @enricosada

**Comment by ctaggart** [comment]
Thanks @forki, trying it out on Argu now.

**Comment by ctaggart** [comment]
It worked great. Here is how I updated Argu to SourceLink 2:
https://github.com/fsprojects/Argu/pull/97/files
