### ISSUE TITLE
Platform not specified warning from Paket when restoring e.g. xUnit

### ISSUE THREAD

**Issue by tlycken** [fsprojects/Paket#2958]
I'm getting a `Platform not specified for library or executable ..., please tell the authors of that project` error when building my project, specifically for a couple of dll's in the xUnit suite, but Brad Wilson maintains that this is not a problem with xUnit. Thus, I assume it's something with my setup - but what?

Steps to reproduce, log output etc are detailed in that issue: xunit/xunit#1603

If something is wrong with my setup and/or configuration, what? If not, is this a problem with Paket or with xUnit?

**Comment by matthid** [comment]
I think we can suppress the warning for folders or completely ignore folders starting with `_` .
