### ISSUE TITLE
Using paket to reference Martin.FSharp fails, while using Nuget runs fine.

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#2967]
### Description

When trying to add Martin.FSharp (@TheAngryByrd ) as a reference using Paket, I get an .net framework incompatibility error while adding the reference, using regular Nuget, everything runs fine. It seems that adding the reference using Nuget defaults to the local .net installed dependencies while Paket downloads all the dependencies to the local packages folder. However, this fails.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a new F# project in VS 2017 community edition

2. Add the Marin.FSharp package as a dependency to your project using Paket

3. Send references to FSI and send the following test script:

```fsharp
open System
open Marten

// Define your library scripting code here

let store = DocumentStore.For("host=localhost;database=postgres;password=password;username=user")

[<CLIMutable>]
type User = { Id: int; Name: string; Age: int }
let user = { Id = 0; Name = "Test"; Age = 20 }


let saveUser (user: User) =
    use session = store.LightweightSession()

    session.Store(user)
    session.SaveChanges()
    user


user |> saveUser
```

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Normal execution and storing the `user`.

### Actual behavior

> An error:
> Binding session to 'Z:\Development\Lab\Marten3\packages\FastExpressionCompiler\lib\net45\FastExpressionCompiler.dll'...
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
>    at System.Delegate.CreateDelegateNoSecurityCheck(Type type, Object target, RuntimeMethodHandle method)
>    at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
>    at FastExpressionCompiler.ExpressionCompiler.TryCompile[TDelegate](Expression bodyExpr, IList`1 paramExprs, Type[] paramTypes, Type returnType)
>    at FastExpressionCompiler.ExpressionCompiler.TryCompile[TDelegate](LambdaExpression lambdaExpr)
>    at FastExpressionCompiler.ExpressionCompiler.Compile[TDelegate](LambdaExpression lambdaExpr)
>    at Marten.Schema.DocumentStorage`1..ctor(ISerializer serializer, DocumentMapping mapping)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    at System.Activator.CreateInstance(Type type, Object[] args)
>    at Marten.Schema.DocumentMapping.Marten.Schema.IDocumentMapping.BuildStorage(StoreOptions options)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Marten.DocumentSession.Store[T](T[] entities)
>    at FSI_0002.saveUser(User user) in Z:\Development\Lab\Marten3\Marten3\Script.fsx:line 20
>    at <StartupCode$FSI_0003>.$FSI_0003.main@()
> Stopped due to error
 

### Known workarounds

The exact same script with the exact same setup runs when the reference to Martin.FSharp is added with regular Nuget package management instead of Paket. I don't think the referenced library Marting.FSharp is the problem, rather how Paket resolves dependencies when dynamic binding is involved.

**Comment by TheAngryByrd** [comment]
Do you have the same problem while referencing just Marten 2.5.0? I wonder if it's Marten itself or something to do with the fact Marten.FSharp's depedency `Marten (>= 1.5.3)` and paket is probably pulling latest on Marten.

**Comment by forki** [comment]
Yes, can you please check if the versions are same in both cases?

Am 05.01.2018 22:00 schrieb "Jimmy Byrd" <notifications@github.com>:

**Comment by forki** [comment]
Can you please create a zip with a minimwl repro?

Am 09.01.2018 06:41 schrieb "Casper" <notifications@github.com>:

**Comment by mavnn** [comment]
This appears to be an issue with FastExpressionCompiler - if you limit the version of FastExpressionCompiler to the minimum that Marten requires (as nuget would by default) F# plays nicely with it.

I don't have time to dig too deep right now, but I think the issue here can be closed and @halcwb and I will need to take this to FastExpressionCompiler.

**Comment by enricosada** [comment]
> I don't have time to dig too deep right now, but I think the issue here can be closed and @halcwb and I will need to take this to FastExpressionCompiler.

Closing

**Comment by halcwb** [comment]
Sorry, didn't have time to submit the minimum failing cases. But I guess you already figured out the source of the problem. Leaves me with a question whether it is possible to make sure Paket downloads minimum required versions instead of maximum possible version. Sames to me the first strategy is safer than the latter?

**Comment by forki** [comment]
It's not safer. Just different. But here it is:
https://fsprojects.github.io/Paket/nuget-dependencies.html#The-modifier-1

Am 28.01.2018 16:17 schrieb "Casper" <notifications@github.com>:
