### ISSUE TITLE
Package GitVersion.CommandLine is blacklisted

### ISSUE THREAD

**Issue by tforkmann** [fsprojects/Paket#2968]
### Description

When trying to install GitVersion.CommandLine with Paket I run into following issue.

### Repro steps

Try to paket install the folllowing paket.dependencies:

source https://api.nuget.org/v3/index.json
storage:none

nuget FSharp.Compiler.Service
nuget Microsoft.NET.Test.Sdk
nuget Expecto
nuget Expecto.FsCheck

group Build
  source https://api.nuget.org/v3/index.json

  nuget FAKE prerelease
  nuget GitVersion.CommandLine

I was running into that problem by trying to test the tool "mechanic".

### Expected behavior

Paket install runs smoothly

### Actual behavior

GitVersion.CommandLine is blacklisted:
Paket failed with
-> Could not download GitVersion.CommandLine 3.6.5.
-> Couldn't get package details for package GitVersion.CommandLine 3.6.5 on https://api.nuget.org/v3/index.json.
-> All possible sources are already blacklisted. 
	 - 1_https://nuget.org/api/v2/Packages(Id='gitversion.commandline',Version='3.6.5')
	 - 1_https://nuget.org/api/v2/Packages(Id='gitversion.commandline',Version='3.6.5')
	 - 1_https://nuget.org/api/v2/Packages(Id='GitVersion.CommandLine',Version='3.6.5')
	 - 1_https://nuget.org/api/v2/Packages(Id='GitVersion.CommandLine',Version='3.6.5')
	 - 2_https://nuget.org/api/v2/Packages?$filter=(Id eq 'GitVersion.CommandLine') and (NormalizedVersion eq '3.6.5')
	 - 2_https://nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'gitversion.commandline') and (NormalizedVersion eq '3.6.5')
	 - 2_https://nuget.org/api/v2/Packages?$filter=(Id eq 'GitVersion.CommandLine') and (Version eq '3.6.5')
	 - 2_https://nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'gitversion.commandline') and (Version eq '3.6.5')
	 - 2_https://nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'gitversion.commandline') and (Version eq '3.6.5')

### Known workarounds

None so far

**Comment by forki** [comment]
@matthid it looks like all sources were blacklisted on my brother's machine. Any ideas on how to work around?

**Comment by matthid** [comment]
Blacklisting is maybe the wrong word - it is not permanent. Also when I do the printed requests they all seem to work for me (for example sending the requests via postman). I guess we need a verbose log to see what is happening...

**Comment by forki** [comment]
Yes they do work for coworkers as well. Just not for Tim

Am 08.01.2018 17:42 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment]
please attach a verbose log :).
Also maybe it is caching related so `paket clear-cache` (or however it is called) may help. Still it would be nice to make a verbose log before that (just in case that clearing the cache solves the problem)

**Comment by tforkmann** [comment]
hey,

I created a log file. 

Where should I sent it?

**Comment by tforkmann** [comment]
paket clear-cache worked!

**Comment by matthid** [comment]
just attach it here maye in your initial or a new post

**Comment by tforkmann** [comment]
[verboselog.txt](https://github.com/fsprojects/Paket/files/1612801/verboselog.txt)

**Comment by matthid** [comment]
```
Source 'https://api.nuget.org/v3/index.json' exception: System.Exception: error ---> System.Exception: Could not retrieve data from 'https://nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'fake') and (Version eq '5.0.0-beta010')' ---> System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung. ---> System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.Sockets.SocketException: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig 191.236.146.247:443
   bei System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Ende der internen Ausnahmestapelüberwachung ---
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Paket.Utils.getFromUrl@716-8.Invoke(Exception _arg4)
   bei Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Paket.NuGetV2.getDetailsFromNuGetViaODataFast@376-1.Invoke(FSharpChoice`2 _arg5)
   bei Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
```

Sounds a bit like firewall or something like that.

**Comment by tforkmann** [comment]
Yeah, looks like it.

Probably Kaspersky is blocking it.

Will talk to my admins tomorrow.

**Comment by tforkmann** [comment]
We had to update Kaspersky.

Now everything is working like a charm!

Thanks!
