### ISSUE TITLE
Why would paket.exe outdated --pre suggest 6.0.13 -> 1.7.2 ?

### ISSUE THREAD

**Issue by pshrosbree** [fsprojects/Paket#2974]
### Description

`.\.paket\paket.exe outdated --pre` outputs `Avalanche.Common 6.0.13 -> 1.7.2`

### Repro steps

Run `.\.paket\paket.exe outdated --pre`

Repository is private.

### Expected behavior

No change to `Avalanche.Common` should be suggested since `paket.lock` contains `Avalanche.Common (6.0.13)` and `6.0.13` is greater than `1.7.2`

### Actual behavior

`.\.paket\paket.exe outdated --pre` outputs `Avalanche.Common 6.0.13 -> 1.7.2`

### Known workarounds

Omit `--pre`

**Comment by forki** [comment]
Is it printing other versions as well?
Upgrades are never isolated. It is only looking for a fully sound
resolution. As part of that there can be downgrades

Am 10.01.2018 21:45 schrieb "Peter Shrosbree" <notifications@github.com>:

**Comment by pshrosbree** [comment]
I downloaded Paket version 5.130.3, and this problem no longer occurs. I can't believe this is because of the Paket version, but it is no longer occurring, so I'll close it.
