### ISSUE TITLE
Paket.Restore.targets seems to cause exceptions in dotnet core Expecto builds

### ISSUE THREAD

**Issue by AnthonyLloyd** [fsprojects/Paket#2978]
### Description

Expecto builds correctly when Paket.Restore.targets project lines in projects are commented out. Exceptions when included.

Using Paket 5.129.2.

Could easily be me so any advice greatfully received.

### Repro steps

Branch when targets included: https://github.com/haf/expecto/tree/restore_errors
https://ci.appveyor.com/project/haf/expecto/build/4.0.511/job/0wemftooepism853
https://travis-ci.org/haf/expecto/jobs/327678575

Compared to working master: https://github.com/haf/expecto/tree/11eaad02829779700f6ab6aa77f99f98d09c5a4a
https://ci.appveyor.com/project/haf/expecto/build/4.0.512/job/m26imhe8kkxvo5qb
https://travis-ci.org/haf/expecto/jobs/327686620

### Expected behavior

Expected both to build the same.

### Actual behavior

Here are some example exceptions:

C:\projects\expecto\Expecto.Tests\Expecto.Tests.fsproj : error NU1101: Unable to find package runtime.win7-x86.Microsoft.NETCore.DotNetHostPolicy. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder

﻿﻿It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '2.0.5'.

### Known workarounds

Comment out Paket.Restore.targets line in the projects.

**Comment by forki** [comment]
I assume it needs to be in deps file?!

**Comment by AnthonyLloyd** [comment]
I don't think so. It's not a dependency of any of the projects.

**Comment by forki** [comment]
huh? you build for netcore - so it's clearly a dependency

**Comment by AnthonyLloyd** [comment]
Ah I didn't know this had to be added. Will try.

**Comment by forki** [comment]
Normally it's implicit, but seems you are using one that's not the default

Am 11.01.2018 16:09 schrieb "Anthony Lloyd" <notifications@github.com>:

Ah I didn't know this had to be added. Will try.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2978#issuecomment-356962309>,
or mute the thread

**Comment by AnthonyLloyd** [comment]
Now it complains Microsoft.NETCore.App is implicitly referenced and I shouldn't have a PackageReference which I don't.

Appreciate this may not Paket related but seems to work with the Paket import. 

https://github.com/haf/expecto/tree/restore_errors
https://ci.appveyor.com/project/haf/expecto/build/4.0.513/job/dm53rguj1yclb4d1

**Comment by forki** [comment]
> Appreciate this may not Paket related but seems to work without the Paket import.

Paket forbids to download stuff that is not known to it. Of course it works if you remove the import, because then nuget just downloads it. The question is: where is that version coming from and why is it not installed?

**Comment by AnthonyLloyd** [comment]
Fails the same across travis linux/osx and appveyor. Not sure what to try the projects are so simple now.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/34870231-c70cd50a-f789-11e7-9ab8-27ce6ae27a86.png)

why are you using PackageRefrences in the fsproj?

**Comment by forki** [comment]
I think you should revert that line in deps file that added explicit netcore.app and instead remove all the PackageReference tags from the fsproj and put them into references file

**Comment by AnthonyLloyd** [comment]
Ah ok, what a noob. Did that and now I'm back to the original exceptions:

https://ci.appveyor.com/project/haf/expecto/build/4.0.517/job/o79pnyqeyundd28s
https://travis-ci.org/haf/expecto/jobs/328064303

**Comment by forki** [comment]
ok it looks like a an issue with netcore1.1 - it can't build that on windows properly. I'm trying something
