### ISSUE TITLE
NuGet migration is failing

### ISSUE THREAD

**Issue by curdincaspar** [fsprojects/Paket#2979]
### Description

Running the nuget migration on my project fails with an error.

### Repro steps

1. Run migration

I will try to include a demo project and more info if needed.

### Expected behavior

Migration should succeed.

### Actual behavior

I get the following warnings:

> Profile portable-net45+win8+wp8+wp81+wpa81 is not a supported portable profile, please tell the package authors of Microsoft.AspNet.WebApi.Client 5.2.3

> Profile portable-net45+win8+wp8+wp81+wpa81 is not a supported portable profile, please tell the package authors of Microsoft.AspNet.WebApi.Client 5.2.4-preview1

> Could not detect any platforms from 'MonoAndroid4.0' in package Rebex.Ftp 2.5.6586, please tell the package authors

> Could not detect any platforms from 'win50' in package System.Runtime >= 4.0.0-beta-23019, please tell the package authors

> Could not detect any platforms from 'net35-cf' in package GeoAPI , please tell the package authors

And in the end the following error:

> Paket failed with
-> Unexpected framework while trying to resolve PCL Profile

### Known workarounds

None

**Comment by forki** [comment]
Yeah I guess we need a repro

Am 11.01.2018 17:37 schrieb "curdincaspar" <notifications@github.com>:

**Comment by curdincaspar** [comment]
I found the problem. The following package had a lib folder named "netcore50".
https://www.nuget.org/packages/TeamCity.ServiceMessages/3.0.7

Not sure what this is or if it's still needed. Feel free to close the issue if this is not relevant anymore.
The newer packages don't have this target anymore so updating resolved the issue for me.
