### ISSUE TITLE
Command to (only) migrate NuGet credentials 

### ISSUE THREAD

**Issue by pshrosbree** [fsprojects/Paket#2980]
### Description

I am investigating replacing our use of the NuGet client with paket. Our build system runs on custom dockerized agents in VSTS. These agents are configured with NuGet credentials, but are cleaned for each build. We have a single repository, with all projects in folders off the root.

What would be convenient, especially during the time during which some projects are using the NuGet client, and some paket, would be a command such as:

`paket migrate-credentials [--nuget-config <config-file>]`

or

`paket config migrate-credentials [--nuget-config <config-file>]`

Essentially something that migrates credentials, but does not `convert-from-nuget`. This would be called every time time there was a build. What I am doing now is parsing `%AppData%\NuGet\nuget.config` and executing `paket config add-credentials ...` and `paket config add-token ...` as appropriate. If this feature were available I would alter our script to execute `paket migrate-credentials` immediately after the `nuget.config` is configured by our setup script.

Is there a way to do this now?

If not, would you accept a PR to do this? If so, what syntax would be preferred?

**Comment by forki** [comment]
I think a pr for "paket get-credentials" would be accepted. It's a bit
weird case but I think it is possible. Or maybe "paket restore
--nuget-credentials nuget.config"

Am 11.01.2018 18:24 schrieb "Peter Shrosbree" <notifications@github.com>:

**Comment by pshrosbree** [comment]
If this isn't a common scenario then, and given I have a way of achieving the same functionality outside paket, it would be better not to clutter the code base with this functionality.

Thanks for the feedback.
