### ISSUE TITLE
Problem of binding redirect on a .net framework 4.6.2 library

### ISSUE THREAD

**Issue by pmiossec** [fsprojects/Paket#2982]
Disclamer: Due to fucking security policies, I can't sign in on github from a company computer and provide real data (this issue is open from another computer). So I can't provide the real material that will make the case easier to reproduce :( I'm so sorry.

### Description

I don't know if that's a behavior expected or a bug of paket, so it's more asking help to diagnose the problem (I already spent quite some time on trying to diagnose it).

I have a .net project using framework 4.6.2
This project has a dependency to `System.Net.Http.dll` provided by the .net framework 4.6.2 (from the csproj):

    <Reference Include="System.Net.Http" />

This project is using an internal nuget package that we will name `My.Package`.

The team that manage that package `My.Package` has added a dependency toward the nuget package `System.Net.Http` v4.3.3. They have also added the support of .NetStandard2.0 but I'm not sure it's linked to my problem.

When the package is updated, paket do only 2 things:
* the new dependency `System.Net.Http` is added in the `paket.lock` file (seems ok)
* a binding redirect is added on `System.Net.Http` with `newVersion="4.1.1.2"` 

The csproj are not updated (still using the framework version of `System.Net.Http.dll`.

Due to the binding redirect, the application fail to load with the error: 

```
Could not load file or assembly "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies. The system cannot find the file specified.
-------> Could not load file or assembly "System.Net.Http, Version=4.1.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies. The system cannot find the file specified.
-------> Could not load file or assembly "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Net.Http.dll" or one of its dependencies. The system cannot find the file specified.
```

Same problem with paket 5.130.3 and 5.2.4

My questions are:

1. Is that normal that this binding redirect is added (because `System.Net.Http` is loaded from the framework)? If the binding redirect is removed, that works well.

2. I don't understand from where the version `4.1.1.2` of the dll is taken. Could you tell me? Or is there a way to get it from paket when it calculate dependencies?

Because the nuget package of `System.Net.Http` is quite strange. The package has the version `4.3.3` but the `System.Net.Http.dll` inside has the product and file version to `4.6.25705.1` (and also the version of the same file in the framework has version `4.6.1590.0`). I can't find a place where this version `4.1.1.2` appears.

3. Could confirm me that it's normal that no csproj are modified to use the dll from the nuget package but still use the one of the framework?

### Repro steps

1. Create a .net project in 4.6.2 using `System.Net.Http` and having a nuget package that has no dependency on `System.Net.Http`
2. Update the nuget package that now have a new dependency on `System.Net.Http`

Perhaps just creating a project with a dependency on a package depending on `System.Net.Http` could reproduce it (but I don't know how to find such a nuget package on nuget.org)

>If possible then please create a git repository with a repro sample or attach a zip to the issue.

Unfortunately, no 😭 

### Expected behavior

No binding redirect (?)

### Actual behavior

There is a binding redirect that prevent the loading of the `System.Net.Http` file from the framework

### Known workarounds

None....

Thanks **a lot** in advance for the help provided!

**Comment by forki** [comment]
can you remove the System.Net.Http.dll reference manually and just use the package?

**Comment by pmiossec** [comment]
>can you remove the System.Net.Http.dll reference manually and just use the package?

Not really.

There is 3 possibilities.

1. I remove the references manually. Their is no more references because paket doesn't add the ones to the nuget package. Normal.

2. I remove it and do a `paket install`. The result is partly better but that doesn't solve the problem. 
* The csproj of the exe is well updated by paket (nuget ref added) and the binding is OK.
* The csproj of the test project is not well updated (paket add the ref to the framework dll, see below) and paket but the binding is OK :

```
<Reference Include="System.Net.Http" >
<Paket>True</Paket>
<Reference/>
```

So, test failed with the fileNotFountException

3. Even if that's not the expected thing to do, I added explicitly the dependency to the nuget package `System.Net.Http` to the `paket.dependencies` and all `paket.references` files AND remove all the ref in the csproj  before doing a `paket install`and this workaround seemed to work (I will retest it and keep you up to date because it take time to do and did it that yesterday).

But if we have to do that, it means that there is surely a case not well handled by paket :(

**Comment by forki** [comment]
System.Http issues are very common. But I fixed at least all the know issues. So I assume you would need to come up with some kind of repro, because I have no idea what's going wrong

**Comment by pmiossec** [comment]
Ok. I will try to build one...

**Comment by pmiossec** [comment]
@forki I tried to reproduce the bug but didn't succeed :(

https://github.com/pmiossec/paket_repro

When I add the nuget package `PaketReproPackage` paket didn't add the binding redirect on `System.Net.Http.dll` like it did in our repositories...
It still use the framework version of the dll

**Comment by pmiossec** [comment]
I stopped to look at it because never succeed to reproduce on a simpler project (and circumvent it by a manual fix).

Thanks for the time invested
