### ISSUE TITLE
dotnet restore is broken by Paket 5.130.4

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/Paket#2983]
### Description

Seems like Paket version `5.130.4` break dotnet restore.

Error:

> /home/maxime/.local/share/dotnetcore/sdk/2.0.2/NuGet.targets(476,5): error : File '/home/maxime/Workspace/Gitlab/fleetperformance/fleet-mapping/Client/obj/Fleet.Mapping.fsproj.NuGet.Config' does not exist. [/home/maxime/Workspace/Gitlab/fleetperformance/fleet-mapping/Client/Fleet.Mapping.fsproj]

I am saying that because I didn't touch the project since yesterday and it was working fine. And latest release of paket mention:

> Disable alternative Nuget.Config for now

Also, as a workaround I downloaded paket `5.130.3` exe and it works with it.

**Comment by forki** [comment]
yes I'm on it

**Comment by forki** [comment]
can you please try .6

**Comment by MangelMaxime** [comment]
.6 works for me :)
