### ISSUE TITLE
convert-from-nuget fails to convert .NetStandard2 project (missing `System` dependency)

### ISSUE THREAD

**Issue by pmiossec** [fsprojects/Paket#2984]
### Description

After the conversion, the project no more build with error:

     error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)

We could see that VisualStudio fails to find namespace `System`.

![image](https://user-images.githubusercontent.com/460196/34952259-6e0b68c6-fa19-11e7-8e41-37bcf5d92fd0.png)

Also, we could see that dependencies are no more well detected:

* Before conversion (with nuget):
![image](https://user-images.githubusercontent.com/460196/34951652-46a81e48-fa17-11e7-8dd4-d043f1ba7f2a.png)

* After conversion (with paket)
![image](https://user-images.githubusercontent.com/460196/34951549-f9592182-fa16-11e7-8ba3-d7fd1dc755dc.png)

Same result with an empty, newly created project or an existing project with some nuget dependencies.

That's my first use of paket with .NetStandard project (to try reproduce the problem described in #2982 )
Did I miss something?

### Repro steps

1. Create an empty "Class library (.Net Standard)" project with VS2017 
2. run `paket convert-from-nuget` (v5.130.3 & v5.124.0)

### Expected behavior

The project should build

### Actual behavior

The project doesn't build due to a missing reference:

`error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by forki** [comment]
can you please upload the project that you use after step 1.

**Comment by pmiossec** [comment]
@forki In the zip file, you have 2 project.
An empty one (just created with VS2017) and one with already an added dependency.
[ConvertFromNugetProblem.zip](https://github.com/fsprojects/Paket/files/1634737/ConvertFromNugetProblem.zip)

**Comment by forki** [comment]
can't repro. I extracted and ran `paket convert-from-nuget` and then build works fine:

![image](https://user-images.githubusercontent.com/57396/34985905-f01725f2-fab5-11e7-8383-948eed5c8dab.png)

**Comment by pmiossec** [comment]
Ok I understood why...

It failed in VS.
So, I run the same command than you and got (error not displayed in VisualStudio :( ):

```
D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject>dotnet build EmptyProject
Microsoft (R) Build Engine version 15.5.179.9764 pour .NET Core
Copyright (C) Microsoft Corporation. Tous droits réservés.

  '"D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\.paket\paket.exe"' n'est pas reconnu en tant que commande interne
  ou externe, un programme exécutable ou un fichier de commandes.
D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\.paket\Paket.Restore.targets(71,5): error MSB3073: La commande ""D:\Data\Tmp\ConvertFromNug
etProblem\EmptyProject\.paket\paket.exe" restore" s'est arrêtée avec le code 9009. [D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyPr
oject\EmptyProject.csproj]
C:\Program Files\dotnet\sdk\2.1.2\NuGet.targets(103,5): warning : Unable to find a project to restore! [D:\Data\Tmp\ConvertFromNugetProblem\
EmptyProject\EmptyProject\EmptyProject.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : Fichier de comp
osants 'D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\obj\project.assets.json' introuvable. Exécutez une restauration de pac
kage NuGet pour générer ce fichier. [D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\EmptyProject.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Fichier de comp
osants 'D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\obj\project.assets.json' introuvable. Exécutez une restauration de pac
kage NuGet pour générer ce fichier. [D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\EmptyProject.csproj]

ÉCHEC de la build.

C:\Program Files\dotnet\sdk\2.1.2\NuGet.targets(103,5): warning : Unable to find a project to restore! [D:\Data\Tmp\ConvertFromNugetProblem\
EmptyProject\EmptyProject\EmptyProject.csproj]
D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\.paket\Paket.Restore.targets(71,5): error MSB3073: La commande ""D:\Data\Tmp\ConvertFromNug
etProblem\EmptyProject\.paket\paket.exe" restore" s'est arrêtée avec le code 9009. [D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyPr
oject\EmptyProject.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : Fichier de comp
osants 'D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\obj\project.assets.json' introuvable. Exécutez une restauration de pac
kage NuGet pour générer ce fichier. [D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\EmptyProject.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Fichier de comp
osants 'D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\obj\project.assets.json' introuvable. Exécutez une restauration de pac
kage NuGet pour générer ce fichier. [D:\Data\Tmp\ConvertFromNugetProblem\EmptyProject\EmptyProject\EmptyProject.csproj]
    1 Avertissement(s)
    3 Erreur(s)

Temps écoulé 00:00:00.46
```

It didn't find the `paket.exe` file that is not in the `.paket` folder (but in the PATH).
Once I put the `paket.exe` file in the folder, that build well and in VS too...

Is it required to have `paket.exe` in the folder `.paket` of the project? We didn't do that in our projects (not using .NetStandard).

**Comment by forki** [comment]
the problem is that we hook the paket.Restore.targets into the csproj. and that one is not finding it. I generally recomment to commit the paket.exe in magic mode (see https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode)

**Comment by pmiossec** [comment]
OK. Thanks a lot.

Perhaps that the command `convert-from-nuget` should display a message to help the user on that when converting a .NetStandard project.
Do you want me to open an issue for that?
