### ISSUE TITLE
Adding FSharp.Compiler.Tools via paket not working for new project structure

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/Paket#2985]
### Description

It seems that adding `FSharp.Compiler.Tools` as a reference via paket does not work for projects using the new format.

### Repro steps

The project configuration found in [this commit](https://github.com/eiriktsarpalis/Repro/tree/f341401f096db4e76ebc5d2b5e80318ef4125855) reproduces the issue (using paket version 5.130.6). After running a `dotnet restore`, Visual Studio (version 15.5.3) fails to load the project with the following error message:
```
Repro.fsproj : error  : Project file is incomplete. Expected imports are missing.
```
The issue goes away if I remove the reference to `FSharp.Compiler.Tools` from `paket.references`.

**Comment by eiriktsarpalis** [comment]
I think that might actually be an issue of the particular package. Closing this.

**Comment by eiriktsarpalis** [comment]
Related issue: https://github.com/fsharp/fsharp/issues/807

**Comment by forki** [comment]
The compiler is already part of the new sdk? Why do you want it additionally?

**Comment by eiriktsarpalis** [comment]
Needed to pin to an older build of 4.1 due to the tuple regression.
