### ISSUE TITLE
"Could not parse version range" where version range is generated by Paket itself

### ISSUE THREAD

**Issue by Kazark** [fsprojects/Paket#2988]
### Description

We have an internal package, call it `Foo`, whose latest version is `2.0.3.3`. Its latest prerelease version is `2.0.3-prerelease3`, and that general pattern is followed for all prereleases.

Given a `paket.dependencies` that contains the line

    nuget Foo prerelease

and a `paket.lock` containing a prerelease version of it; and at least one other, say, FAKE:

    nuget FAKE

when I run 

    paket update FAKE

it runs normally. But when I run

    paket update --keep-major FAKE

I get:

>     Paket version 5.130.6
>     Updating FAKE in C:\bitbucket\customers\interlinebrands\NextJenPack\paket.dependencies group Main
>     Performance:
>     - Runtime: 1 second
>     Paket failed with
>     -> could not parse version range "~> 2.0prerelease"

where `2.0prerelease` is nowhere specified.

### Repro steps

This can be reproduced with just FAKE and NUnit. For example,

0. `mkdir paketrepro ; cd paketrepro`
1. `paket init`
2. `paket add FAKE`
3. `paket add NUnit`
4. Manually edit the `paket.dependencies` and add `alpha` after `nuget NUnit`, so it looks like `nuget NUnit alpha`. Manually edit the `paket.lock` and change the NUnit version to an alpha version, say `3.0.0-alpha-2`.0
5. `paket restore` to make sure you haven't screwed anything up
6. `paket update --keep-major FAKE` <- will error with `could not parse version range "~> 3.0prerelease"`

### Expected behavior

Able to run a `paket update --keep-major` like normal.

### Actual behavior

Paket claims about being unable to parse a version number constraint it apparently generated itself.

### Known workarounds

Update the package you want without `--keep-major`.

**Comment by forki** [comment]
Thanks for reporting. should be fixed

**Comment by Kazark** [comment]
@forki thanks so much. It is fixed.
