### ISSUE TITLE
Docker and Paket do not integrate.

### ISSUE THREAD

**Issue by MohsenBzm** [fsprojects/Paket#3006]
### Description

There are several projects in my solution (some production and some test ...)
and there is a docker image per each project.
Each .fsproj file in the solution contains the line:

    <Import Project="..\.paket\Paket.Restore.targets" />

But [docker's build context is limited by the project's folder][1]
and I'd rather not deal with that problem.
 So I can't access the root folder of my solution (where the .paket folder and .git lives)

On the other hand, causes the whole directory (including my test scripts) to be sent to the Docker daemon.

I also tried hard to have a `.paket ` folder inside each of my project folders and everything works without error by the `paket` but using the added packages in my project throws compile errors like this:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0039	The namespace or module 'Expecto' is not defined.
`

How can I use Paket in docker without the need for referring to parent folders?

  [1]: https://github.com/moby/moby/issues/2745

**Comment by enricosada** [comment]
@MohsenBzm you are building inside a docker container? or just using output?

A way is to use docker multi stage builds from root.

build in one image, move generated published output to another image.
minimal size, final image doesnt have useless artifacts (or tests etc)

> On the other hand, causes the whole directory (including my test scripts) to be sent to the Docker daemon.

```
FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

# copy fsproj and restore as distinct layers
COPY *.fsproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM microsoft/dotnet:2.0-runtime 
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "sample4.dll"]
```

**Comment by MohsenBzm** [comment]
The issue solved clearly
