### ISSUE TITLE
Unfinished sentence/paragraph in the documentation

### ISSUE THREAD

**Issue by madidier** [fsprojects/Paket#3027]
### Description

There is an unfinished sentence or paragraph in the GH pages documentation. [It reads](https://fsprojects.github.io/Paket/bootstrapper.html#Setting-version-in-magic-mode) : "you can no longer use the command line to specify", but the page ends with that.

Also, it appears the whole paragraph would essentially repeat what's already written a couple paragraphs above it, only adding that the application settings file should be named `paket.exe.config` rather than `paket.bootstrapper.exe.config`.

**Comment by forki** [comment]
Please send a correction. Would appreciate it

Am 05.02.2018 17:36 schrieb "Maxime DIDIER" <notifications@github.com>:

**Comment by JohnyWS** [comment]
Shouldn't this be marked as complete @forki ? :)
