### ISSUE TITLE
Package is resolved to different versions randomly on multiple paket update runs

### ISSUE THREAD

**Issue by Allon-Guralnek** [fsprojects/Paket#3035]
### Description

When I run `paket update` on [this solution](https://github.com/gigya/microdot), it sometimes resolves the package [`NLog`](https://www.nuget.org/packages/NLog) to version 4.4.6 instead of 4.4.12 for no apparent reason (no backtracking seems to occur, it's the first version that appears in the console output). This seems to occur randomly, multiple runs of Paket flips between the two package versions. I've run it 10 times, and it picked the incorrect version 4 times, so it's close to a 50-50 chance.

**EDIT:** This has nothing to do with the latest version, it happens with v5.124.1 too.

### Repro steps

1. Run `paket update` on [this solution](https://github.com/gigya/microdot) a few times. This will produce the following two outputs randomly:

```
>paket update

Paket version 5.135.0
Resolving packages for group Main:
 - Microsoft.CodeAnalysis.CSharp is pinned to 1.3.2
 - Microsoft.CodeAnalysis.Common is pinned to 1.3.2
 - Microsoft.Orleans.Core is pinned to 1.3.1
 - Microsoft.Orleans.OrleansRuntime is pinned to 1.3.1
 - Microsoft.Orleans.OrleansProviders is pinned to 1.3.1
 - Microsoft.Orleans.OrleansSqlUtils is pinned to 1.3.1
 - Microsoft.Orleans.OrleansZooKeeperUtils is pinned to 1.3.1
 - Microsoft.Orleans.OrleansCodeGenerator is pinned to 1.3.1
 - Microsoft.Orleans.OrleansCodeGenerator.Build is pinned to 1.3.1
 - Microsoft.Orleans.TestingHost is pinned to 1.3.1
 - Microsoft.Extensions.DependencyInjection.Abstractions is pinned to 1.1.1
 - Microsoft.Extensions.DependencyInjection is pinned to 1.1.1
 - Newtonsoft.Json 9.0.1
 - Nito.AsyncEx 4.0.1
 - System.Threading.Tasks.Dataflow 4.8.0
 - System.ComponentModel.Annotations 4.4.1
 - Castle.Core 4.2.1
 - NLog 4.4.6
 - ZooKeeperNetEx 3.4.10.1
[...]

>paket update

Paket version 5.135.0
Resolving packages for group Main:
 - Microsoft.CodeAnalysis.CSharp is pinned to 1.3.2
 - Microsoft.CodeAnalysis.Common is pinned to 1.3.2
 - Microsoft.Orleans.Core is pinned to 1.3.1
 - Microsoft.Orleans.OrleansRuntime is pinned to 1.3.1
 - Microsoft.Orleans.OrleansProviders is pinned to 1.3.1
 - Microsoft.Orleans.OrleansSqlUtils is pinned to 1.3.1
 - Microsoft.Orleans.OrleansZooKeeperUtils is pinned to 1.3.1
 - Microsoft.Orleans.OrleansCodeGenerator is pinned to 1.3.1
 - Microsoft.Orleans.OrleansCodeGenerator.Build is pinned to 1.3.1
 - Microsoft.Orleans.TestingHost is pinned to 1.3.1
 - Microsoft.Extensions.DependencyInjection.Abstractions is pinned to 1.1.1
 - Microsoft.Extensions.DependencyInjection is pinned to 1.1.1
 - Newtonsoft.Json 9.0.1
 - Nito.AsyncEx 4.0.1
 - System.Threading.Tasks.Dataflow 4.8.0
 - System.ComponentModel.Annotations 4.4.1
 - Castle.Core 4.2.1
 - NLog 4.4.12
 - ZooKeeperNetEx 3.4.10.1
[...]
```

### Expected behavior

`NLog` package should consistently be resolved to version 4.4.12.

### Actual behavior

`NLog` package is sometimes downgraded to 4.4.6.

### Known workarounds

Run `paket update` multiple times until the correct versions are resolved.

**Comment by forki** [comment]
I assume #3036 fixes it

**Comment by forki** [comment]
mhm I can't repro.

**Comment by Allon-Guralnek** [comment]
@forki Anything I can do to help repro? I just run `paket update` from a command prompt a few times and it repros easily.

**Comment by forki** [comment]
Can you please run "paket clear-cache" then try again?

Also: does it reproduce under "paket update -f"? 

In the PR I now try to repro on the CI

**Comment by Allon-Guralnek** [comment]
```
>paket clear-cache

Paket version 5.135.0
Performance:
 - Runtime: 8 minutes, 21 seconds
```
8.5 minutes... is that normal?

Anyway, even after clearing the cache, both `paket update` and `paket update -f` still have the issue.

**Comment by forki** [comment]
Would not say it's normal. But it's not used much so nobody cared to
optimize it.

OK. So I need to find a way to reproduce

Am 10.02.2018 16:18 schrieb "Allon Guralnek" <notifications@github.com>:

>paket clear-cache

Paket version 5.135.0
Performance:
 - Runtime: 8 minutes, 21 seconds

8.5 minutes... is that normal?

Anyway, even after clearing the cache, both paket update and paket update -f
still have the issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/3035#issuecomment-364662050>,
or mute the thread

**Comment by matthid** [comment]
The cache can become quite big and if you have a slow hard drive it can be normal :)
But I guess there is at least some room for improvement.

**Comment by Allon-Guralnek** [comment]
@matthis: That workstation has a pretty fast SSD (not NVMe, but still) and Task Manager showed very little disk usage for paket.exe, mostly CPU was used.

**Comment by forki** [comment]
it's not the disk - it's how we do the cleanup. it's not that smart. but that's not the issue here.

anyway. I fail to repro. I have an idea why it may happen, but I cannot verify it.
@matthid can you repro?

**Comment by forki** [comment]
ok. just took a deeper look at the lock file. The idea that I had - nope it's not that. I'm seriously puzzled.

**Comment by Allon-Guralnek** [comment]
I've just tried to repro this on my home machine, but am unable to. I'll take a closer look at what Fiddler can tell me on my work machine.

**Comment by forki** [comment]
thank you! I don't think the issue lies in the part that we changed yesterday for that other bug. Must be something else

**Comment by Allon-Guralnek** [comment]
@forki, it certainly doesn't have anything to do with the latest fix because it happens on my work machine with v5.124.1 as well.

**Comment by Allon-Guralnek** [comment]
Interesting. On my work machine, the according to Fiddler the responses from nuget.org are different when Paket resolves to 4.4.12 and 4.4.6. I'm not very familiar with the XML format of NuGet servers, so I've included the `.saz` file for you full inspection. I've removed all sessions except the ones that mention NLog. The first two are from the run that resolved to 4.4.12, the second two resolved to 4.4.6.

[Paket NLog Issue.zip](https://github.com/fsprojects/Paket/files/1713646/Paket.NLog.Issue.zip)
(GitHub.com doesn't allow `.saz` files, so I double-compressed it into another `.zip`)

Here's one thing I noticed that is different:

![nuget org nlog differences](https://user-images.githubusercontent.com/1709453/36065020-47ea6cda-0e9d-11e8-97af-fab3ed0c8345.png)

This is a comparison of the first request of each scenario. Left side is the one that resolved 4.4.12, right side is the one that resolved 4.4.6.

I don't think it's a caching problem (either at my workplace or some intermediary) because 4.4.6 was released 10 months ago. I don't know of any web cache that would keep something that long. So any idea what's going on here? I'm not sure Paket is involved anymore because I can repro this issue by simply replaying sessions in fiddler and I can see different results coming in, but maybe someone here who has more experience with nuget.org can help me figure this out?

**Comment by matthid** [comment]
Maybe it is some kind of paging problem. Can you try switching between V3 and V2 NuGet Gallery API?

**Comment by forki** [comment]
Yes looks like we don't follow the next link. That's weird

**Comment by Allon-Guralnek** [comment]
@matthid How do I switch to v3? I tried changing
`source https://www.nuget.org/api/v2/`
to
`source https://www.nuget.org/api/v3/`
but that just caused a bunch of errors to be thrown.

@forki: As you can see from the Fiddler capture, it does follow the link to the next page, but it doesn't contain version 4.4.12 either, so I don't think it's Paket's fault.

**Comment by Allon-Guralnek** [comment]
Okay, I figured it out, the v3 url is `https://api.nuget.org/v3/index.json`. Right now I can reproduce this issue consistently on v2, but I cannot reproduce it on v3. So as far as I'm concerned, it's a bug in NuGet.org's v2 API, not in packet, and since I can easily resolve it by switching to v3, I consider this issue resolved. Should I close it or should I leave it open so you can investigate paging on v2?

**Comment by forki** [comment]
I'd like to get it fixed and raise it with the nuget people.

Can you please help us out and make a list of all the nlog related urls
that are similar to what you have on the right side of the screenshot?

There must be one where we don't follow the link or there is one with
invalid data.

Am 11.02.2018 09:58 schrieb "Allon Guralnek" <notifications@github.com>:

**Comment by Allon-Guralnek** [comment]
@forki: I'm not sure what else you want me to collect. The two scenarios (works and doesn't work) and already fully captured in the Fiddler capture file in their entirety. The comparison was made from the captures in the files. You can check there for any corruption. What I see is that in the bad case, nuget.org returned only versions up to 4.4.6, and anything beyond was simply missing (even in the next page, which is also in the Fiddler capture).

I imagine you can just send the Fiddler capture to nuget.org and they can take a look. Consecutive identical requests to nuget.org should yield identical results, and that capture shows they don't.

I think everything you need is in the Fiddler capture, but if I misunderstood you and there is still something you'd like me to help you with, I'd be glad.

**Comment by forki** [comment]
Ah Ok thanks. Didn't notice you already have uploaded such a file. Thanks.
Will need to investigate that

Am 11.02.2018 10:13 schrieb "Allon Guralnek" <notifications@github.com>:

**Comment by forki** [comment]
mmm I tried to look into the logs. I see 4 requests. Is that correct? You talked about multiple sessions.

(I'm not a fiddler expert so maybe I'm not loading it correctly)

**Comment by Allon-Guralnek** [comment]
@forki The first two requests are from the `packet update` run that resolved NLog to 4.4.12, the other two are the ones that resolve to 4.4.6. I discarded all the other requests for the other packages for brevity's sake.

**Comment by forki** [comment]
Just saw it reproduces in CI in #3036

**Comment by matthid** [comment]
Yes this indeed looks like a server bug, or we use the API incorrectly (ie we need to forward some kind of context in the paging scenario).

If you send the request `https://www.nuget.org/api/v2/FindPackagesById()?id=%27NLog%27&amp;$skip=100` or `https://www.nuget.org/api/v2/FindPackagesById()?id='NLog'&$skip=100` often enough you can get:
 - A response containing "4.4.12"
 - A response not containing "4.4.12"

That alone I consider a server bug.


Lets say I name your requests as 1+2 (with 4.4.12) and 3+4 (without 4.4.12). We can see that `4.4.12` appears in BOTH responses while it doesn't appear in 3+4 at all.

This indicates to me that there is something wrong with their ordering, or that they have multiple servers with different ordering.

**Comment by matthid** [comment]
Reported this to NuGet directly: https://github.com/NuGet/NuGetGallery/issues/5431

**Comment by forki** [comment]
According to the nuget team it's fixed now. Can you please retry? Apparently they had a faulty search service in production.

**Comment by Allon-Guralnek** [comment]
Looks okay now, closing. Thanks everyone!
