### ISSUE TITLE
Paket is referencing the non-transitive version of a package dependency

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/Paket#3039]
### Description
Paket is referencing the non-transitive version of a package dependency (I though this is what paket was supposed to solve in the first place)

paket.dependencies (along with other packages)
```
// used in project A
nuget Giraffe ~> 1.0.0
// used in Project B
nuget Saturn  
```
paket.lock (along with other packages)
```
    Saturn (0.3.1)
      FSharp.Core (>= 4.3.3)
      Giraffe (>= 0.1.0-beta-700)
      Microsoft.AspNetCore (>= 2.0.1)
      Microsoft.AspNetCore.Authentication.JwtBearer (>= 2.0.1)
      Microsoft.AspNetCore.Cors (>= 2.0.1)
      Microsoft.AspNetCore.ResponseCompression (>= 2.0.1)
      Microsoft.AspNetCore.Rewrite (>= 2.0.1)
      Microsoft.AspNetCore.Session (>= 2.0.1)
      Microsoft.AspNetCore.StaticFiles (>= 2.0.1)
      Microsoft.Extensions.Caching.Memory (>= 2.0)

    Giraffe (1.0)
      FSharp.Core (>= 4.2.3) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.Authentication (>= 2.0.1) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.Diagnostics (>= 2.0.1) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.Hosting.Abstractions (>= 2.0.1) - restriction: || (>= net461) (>= netstandard2.0)
      Newtonsoft.Json (>= 10.0.3) - restriction: || (>= net461) (>= netstandard2.0)
      System.Text.RegularExpressions (>= 4.3) - restriction: || (>= net461) (>= netstandard2.0)
      System.ValueTuple (>= 4.4) - restriction: >= net461
      System.Xml.XmlSerializer (>= 4.3) - restriction: || (>= net461) (>= netstandard2.0)
      TaskBuilder.fs (>= 1.0) - restriction: || (>= net461) (>= netstandard2.0)
```
paket.references (of Project B)
```
FSharp.Core
Saturn
```

Now building Project B doesn't work: dotnet doesn't recognises the namespaces from (Giraffe (>= 0.1.0-beta-700) but does recognise and compile when fixing the breaking changes and using (Giraffe 1.0.0)

**Comment by forki** [comment]
I think that is actually a bug in the dotnet cli. I have see that before and wanted to create a repro. We try to do that properly tomorrow.

**Comment by Zaid-Ajaj** [comment]
`paket --version => 5.13.5`

@forki thanks for the quick response, if you want a repro, just clone [Fable.Remoting](https://github.com/Zaid-Ajaj/Fable.Remoting) and `./build.sh`

**Comment by forki** [comment]
ok I just looked at this and it seems to be correct. Everything binds to the one Giraffe `1.0` version from the lock file. As it should be. 

Or what am I missing? It's alway using the resolved versions from the lock file. `1.0` is `>= 0.1.0-beta-700`  - so everything is correct.

**Comment by Zaid-Ajaj** [comment]
```
// used in project A
nuget Giraffe ~> 1.0.0
// used in Project B
nuget Saturn  
```
It doesn't seem to be working correctly, becuase paket is not referencing the *actual* transitive dependency `Giraffe 0.1.0-beta-700` of `Saturn` but instead it is referencing a whole different package `Giraffe 1.0` that is being used in a different project. `Giraffe 1.0` is NOT a dependency of `Saturn` 

Maybe it is just that I don't understand paket and please correct me if I am wrong but it sounds very strange to me that EVERYTHING would bind to latest version of a package dependency while different libraries rely different versions of that same package. Especially because there is a major difference in the packages and thus there are breaking changes

**Comment by forki** [comment]
Giraffe 0.1.0-beta-700 is NOT an actual dependency of Saturn. It specifies a range `>= 0.1.0-beta-700` and that is fulfilled with 1.0.

Yes everything binds that one version. That is how .NET works (not specific to paket) you can not load more than one version of the same assembly. Paket is "only" there for you to find which version that is.

I assume you are coming from node/js background where things work differently.

**Comment by matthid** [comment]
(the previous answer is not technically accurate but simplified for better understanding of the ecosystem)

**Comment by forki** [comment]
;-) yes I ommited things like appdomains and so on

**Comment by Zaid-Ajaj** [comment]
Ahh yes I understand now, I was thinking in terms of exact versions, not ranges of versions. Interesting. 

My background is actually just .NET (I guess I still have much more to learn :smile:)

I am thinking of a couple of ways to solve this:
 - Use dependency groups and have project A and B use different groups (would that help?)
 - Changing the resolver strategy to `min` (trying this right now) 
 - Put the Saturn project in a whole different repo (not ideal for maintenance)

**Comment by forki** [comment]
let's be honest here: the real solution is to patch saturn to use Giraffe 1.0 - wonder if @Krzysztof-Cieslak is already working on it.

**Comment by Zaid-Ajaj** [comment]
Using different groups for different projects solved the issue, thanks a lot @forki @matthid
