### ISSUE TITLE
paket restore on old framework doesn't detect missing packages folder

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#3044]
### Description

I was helping @mathias-brandewinder debug an issue on the FAKE build for his [CNTK wrapper repo](https://github.com/mathias-brandewinder/CNTK.FSharp) and came across the following scenario, where paket thought a restore had occurred but packages were in fact missing.

### Repro steps

1. Have a old-SDK, full-framework repo with paket.lock. Note that we have not set `storage: none`
2. Perform a `paket restore`. Note that `paket-files/paket.restore.cached` is created
3. Delete the `packages` folder
4. Run a FAKE build that assumed the path `packages/FAKE/etc/etc/` was present.

The test repo can be found at https://github.com/mathias-brandewinder/CNTK.FSharp/tree/5994603edca1c3ab42ef98a0627aea184bdaf36c

### Expected behavior

Paket is able to determine that despite the presence of the cache file the packages dir is not present and performs the restore

### Actual behavior

`paket restore` detects the cache file, fast exits, and the build script continues

### Known workarounds

I realize that this could be finicky to workaround. Perhaps we need some new guidance around not manually modifying the `packages` directory? Or perhaps `paket clear-cache` needs to learn how to clean the local project environment so we can suggest to use that instead of manually deleting the `packages` dir?

**Comment by forki** [comment]
The cache file is for paket to detect if it needs to do something. If we
would still scan packages then we would defeat its purpose.

Am 13.02.2018 05:59 schrieb "Chet Husk" <notifications@github.com>:

**Comment by matthid** [comment]
Exactly, but I think clear-cache deleting the file could work out pretty
well.

**Comment by forki** [comment]
Yes I think clear-cache should remove paket-files and packages folder as
well.

Am 13.02.2018 08:36 schrieb "Matthias Dittrich" <notifications@github.com>:

> Exactly, but I think clear-cache deleting the file could work out pretty
> well.
>

**Comment by forki** [comment]
done
