### ISSUE TITLE
Looking for a way to reference different versions of FSharp.Core in multi-targeted projects

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/Paket#3045]
### Description

Multi-targeting provides an excellent means to author libraries that target both .NET classic and .NET standard frameworks. However, I am missing a way to specify different versions of FSharp.Core per target using paket. This is an important requirement, since I do not want to force FSharp.Core >= 4.2 on consumers of the net4x build.

### Repro steps

Using the [code from this commit](https://github.com/eiriktsarpalis/Repro/tree/6766bea05ae144ec643309a7798898a1a21fafd0), run `paket install`.

### Expected behavior

Should complete successfully.

### Actual behavior

Fails with the following error:
```
Paket failed with
-> Installation Errors :
   Package FSharp.Core is referenced in different versions in C:\Users\eirik.tsarpalis\Source\Repos\Repro\Library\Library.fsproj (4.3.1 vs 4.0.0.1), (inspect the lockfile for details) to resolve this either add all dependencies to a single group (to get a unified resolution) or use a condition on both groups and control compilation yourself.
```

### Known workarounds

Either stop using multi-targetting, or use the nuget client.

**Comment by forki** [comment]
see https://github.com/fsprojects/Paket/pull/3046

**Comment by eiriktsarpalis** [comment]
Awesome, thanks!
