### ISSUE TITLE
Transitive prerelease resolving fails when root dependency also marked as prerelease

### ISSUE THREAD

**Issue by faviann** [fsprojects/Paket#3057]
### Description
Pretty new to Paket so bear with me. I suspect this is a bug but it might be a misunderstanding.

Seems that adding a prerelease is not always respected in situations where the root and child are both marked as prerelease. 

Since I have a bit of a hard time explaining the problem clearly, I instead added a test in a fork, highlighting the issue. To make it simple I matched the test's existing content. Specifically the [PrereleaseSpecs.fs](https://github.com/fsprojects/Paket/blob/master/tests/Paket.Tests/Resolver/PrereleaseSpecs.fs) file which has the following dependency graph(?)

PackageA 1.0.11250   -- REQUIRES --> PackageB [1.0,2.0)
PackageB 1.0.11203
PackageB 1.0.11204-custom
PackageB 2.0.0

### Repro steps

1. Added to the [PrereleaseSpecs.fs](https://github.com/fsprojects/Paket/blob/master/tests/Paket.Tests/Resolver/PrereleaseSpecs.fs) test the following:
```
let config5 = """
source "https://www.nuget.org/api/v2"
nuget PackageA prerelease
nuget PackageB prerelease
"""

[<Test>]
let ``should resolve prerelease config5``() = 
    let cfg = DependenciesFile.FromSource(config5)
    let resolved = ResolveWithGraph(cfg,noSha1, VersionsFromGraphAsSeq graph, PackageDetailsFromGraph graph).[Constants.MainDependencyGroup].ResolvedPackages.GetModelOrFail()
    getVersion resolved.[PackageName "packageA"] |> shouldEqual "1.0.11250"
    getVersion resolved.[PackageName "packageB"] |> shouldEqual "1.0.11204-custom"
```
2. Run the Paket Test using the build.cmd/build.sh and watch the error.

Here is a repo with the Unit test failing in case its faster/easier:
[https://github.com/faviann/Paket/commit/6529bd48eb9eaa82a373ec9c58572602ab5662fb](https://github.com/faviann/Paket/commit/6529bd48eb9eaa82a373ec9c58572602ab5662fb)

### Expected behavior
Resolver chooses dependency PackageB 1.0.11204-custom;

### Actual behavior
Resolver chooses dependency PackageB 2.0.0 (which I suspect is wrong)
```
1) Failed : Paket.PrereleaseSpecs.should resolve prerelease config5
  Expected: "1.0.11204-custom"
Actual: "2.0.0"
  Expected string length 16 but was 5. Strings differ at index 0.
  Expected: "1.0.11204-custom"
  But was:  "2.0.0"
  -----------^
```
### Known workarounds

Not exactly sure

**Comment by forki** [comment]
nice catch. But in all my tests it was selecting 1.0.11203 - which at least did not violate any constraints.
I never saw it select. 2.0.0

**Comment by faviann** [comment]
Confirmed it fixed the issue on my side. That was bloody quick as a fix. Thanks a lot!
