### ISSUE TITLE
Remove paket.restore.cached

### ISSUE THREAD

**Issue by pchinery** [fsprojects/Paket#3060]
### Description
For us, the paket.restore.cached file mostly caused trouble so far. As it was silently introduced, it was accidentally added to git by a few developers. Recently, we had a problem where Paket updated the cache file, but the packages folder contained an outdated file. Sometimes, Visual Studio moves files from the packages folder and they are not restored, as the cache file says everything is ok.

`paket restore --force` downloads all files again, which is not what we want either, but in favor of stable builds, we prefer to have the dependencies extracted at each build instead of chasing bugs due to a failed cache invalidation.

### Suggestion

1. Add a parameter to skip the `paket.restore.cached` file

1. Remove the file completely

I assume it is just the performance benefit that is expected from this, right? Or does the file help to prevent other problems as well?

### Known workarounds

Our workaround is to delete the `paket.restore.cached` file on every build

**Comment by forki** [comment]
it wasn't silently introduced, we tried to explain it on all channels ;-)

yes it's a performance optimization and so far it works very well. To my knowledge there are no open bug reports. The biggest issue we see is that people commit the file instead of gitignoring it.

I don't think removing the file is a good idea because then new SDK/.NET Core restores will take forever.

@matthid The question is: should "manual paket restore" use the file or not. I believe it only makes sense to use it from "dotnet restore" context!?

**Comment by pchinery** [comment]
yes, I know it was not completely silent, from the devs perspective it was suddenly there and then committed due to lack of better knowledge. So I am sorry I sounded so accusational, that was not my intention :)

The argument of .Net Core is a good one, as the number of dependencies horribly grows and it sounds like that's the reason why it was introduced. I can't offer any reproduction, but we have been chasing a bug this whole morning where to packages folder was not properly restored, but the cache and lock files were in sync.

For us, a parameter that would allow to skip the log file would be sufficient.

**Comment by pchinery** [comment]
that was the first problem, but right now it was not committed, but locally for one dev the packages folder was not restored, but the `paket.restore.cached` file and the `paket.lock` were in sync, leaving us with strange and hard to trace build errors

**Comment by enricosada** [comment]
have it in `paket-files` is not enough? that dir should be .gitignored anyway

**Comment by pchinery** [comment]
@enricosada: that's two different things... before the file was introduced, there was no paket-files folder. After it was introduced, we added it to .gitignore. The main problem though is, that the `paket.restore.cached` file seems to have been writen when the restore was not successful, i.e. Visual Studio was not letting go some assemblies. The latter problem is why I started this discussion, as it results in sítuations that are hard to analyze.

**Comment by rabrahamOpti** [comment]
@forki I don't see anything in [the documentation](https://fsprojects.github.io/Paket/) about the paket-files folder or paket.restore.cached. Should that entire folder be included in .gitignore? Or just paket.restore.cached? Either way, documentation about what they do and how they are handled would be great.

**Comment by forki** [comment]
the whole paket-files folder belongs into gitignore. I'd love to see a PR
to the FAQ which explains that

Am Do., 7. Juni 2018 um 21:03 Uhr schrieb rabrahamOpti <
notifications@github.com>:

**Comment by forki** [comment]
wen now automatically exclude paket.restore.cached

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/48132307-61949f00-e293-11e8-9be5-d2be12082970.png)
