### ISSUE TITLE
Paket.bootstrapper.exe unable to communicate with GitHub (5.138.5)

### ISSUE THREAD

**Issue by dachew** [fsprojects/Paket#3065]
### Description

GitHub shut down an old insecure encryption cypher, and paket.bootstrapper.exe is not able to talk to their servers.  More info here:
https://githubengineering.com/crypto-removal-notice/

### Repro steps

Please provide the steps required to reproduce the problem

1. Download latest paket.bootstrapper.exe

2. Try to run it.  Observe error.

```
Checking Paket version (downloading latest stable)...
The request was aborted: Could not create SSL/TLS secure channel. (Github - cached)
```

### Expected behavior

The bootstrapper downloads the latest version of paket.exe.

### Actual behavior

```
Checking Paket version (downloading latest stable)...
The request was aborted: Could not create SSL/TLS secure channel. (Github - cached)
```

### Known workarounds

None.

**Comment by ptrstpp950** [comment]
**Workaround**
Add registry keys to force NET framework to use strong encryption. For example PowerShell commands:
```
new-itemproperty -path "HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord";
new-itemproperty -path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord"
```

**Comment by ppatino** [comment]
Any idea on expected resolution timeline? Workaround is easy enough locally but needs more work for CI servers.

**Comment by ptrstpp950** [comment]
As you can see pull request is in progress #3066  
Still, it will need to changes in source after the owner of this repository release it. I'm just an unlucky user, who need workaround ASAP 😄

**Comment by BlythMeister** [comment]
Also, all source code branches would need an updated bootstrap if you add the bootstrapper into your repo...

**Comment by egracer** [comment]
You can also force the download from nuget using `--force-nuget` or by configuring `paket.bootstrapper.exe.config` as described [in the bootstrapper documentation](https://fsprojects.github.io/Paket/bootstrapper.html#In-application-settings).

**Comment by samhanes** [comment]
If you're using magic mode, you can use the following paket.exe.config:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="ForceNuget" value="True"/>
  </appSettings>
</configuration>
```

**Comment by csmager** [comment]
I've updated to the bootstrapper in the 5.141.0 release (with the fix from #3066), I now get a different error in 'magic mode':
> The request was aborted: The connection was closed unexpectedly. (Github - cached (temporarily ignore updates))

**Comment by ptrstpp950** [comment]
No only `paket.exe.config` helps

**Comment by forki** [comment]
Any ideas what's still going wrong?

**Comment by csmager** [comment]
Update VS this morning and now VS and Rider both claim I don't have .NET Framework 4.5 SDK, so Paket won't build anymore. Once I've shaved that yak I'll see if I can debug and get more info...

**Comment by BlythMeister** [comment]
the release is missing the sha256.txt file...don't know if that helps

**Comment by csmager** [comment]
Ah, yeah. Clicking the link in the error message I posted gives you a 404.

**Comment by forki** [comment]
uploaded in 5.142.0

**Comment by BlythMeister** [comment]
![image](https://user-images.githubusercontent.com/1046836/36589027-d8bef698-1881-11e8-895d-12a053a56a75.png)

Seem good now for me.

**Comment by forki** [comment]
Thanks everyone

Am 23.02.2018 11:11 schrieb "Chris Blyth" <notifications@github.com>:

**Comment by MiloszKrajewski** [comment]
Thank you for quick fix!

**Comment by dsyme** [comment]
Could someone post a description of what we should do?

For example, at the moment I just have this `paket.exe`

```
 Directory of C:\GitHub\dsyme\visualfsharp\fcs\.paket

09/01/2018  10:37            63,784 paket.exe
               1 File(s)         63,784 bytes
               0 Dir(s)  63,022,436,352 bytes free
````

If you send a link to the replacement I can replace it.

**Comment by samhanes** [comment]
@dsyme That's correct.

**Comment by dsyme** [comment]
@samhanes thanks!

**Comment by misterspeedy** [comment]
Just to confirm - I had this exact issue with an extant project (VS Code + Win10) and downloading paket.bootstrapper.exe (as linked above) into .paket in my project, then renaming it to paket.exe, fixed the issue.  Didn't have to restart VS Code.

**Comment by haf** [comment]
macOS / linux is not fixed by anything above, instead, download a new version of paket and do this:

    curl -L -o /tmp/cacert.pem https://curl.haxx.se/ca/cacert.pem
    cert-sync --user /tmp/cacert.pem
    mono .paket/paket.exe install -vv

**Comment by Gonnagle** [comment]
This could probably be closed as fixed?
