### ISSUE TITLE
Release 5.141.0 doesn't contains paket-sha256.txt

### ISSUE THREAD

**Issue by AlexanderUsmanov** [fsprojects/Paket#3067]
### Description

Paket bootstraper couldn't dowload latest version of paket.exe from (https://github.com/fsprojects/Paket/releases/latest) because paket-sha256.txt doesn't presented.

### Repro steps

1. Download paket.bootstraper.exe
2. Run paket.bootstraper.exe
3. Catch error while dowloading latest version of paket.exe

### Expected behavior

paket-sha256.txt exists in https://github.com/fsprojects/Paket/releases/latest and downloading paket.exe doesn't causes error

### Actual behavior

Paket bootstraper couldn't dowload latest version of paket.exe from (https://github.com/fsprojects/Paket/releases/latest) because paket-sha256.txt doesn't presented. Paket.bootstraper.exe downloads paket.exe 3.13.0

**Comment by forki** [comment]
fixed
