### ISSUE TITLE
Fails to resolve the home folder

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#3072]
### Description

```
source https://api.nuget.org/v3/index.json
cache ~/.paket-cache versions: current
```

Results in

```bash
myproject % ls -lah \~
total 0
drwxr-xr-x    3 h  staff    96B Feb 25 15:52 .
drwxr-xr-x   22 h  staff   704B Feb 25 15:53 ..
drwxr-xr-x  116 h  staff   3.6K Feb 25 15:56 .paket-cache
```

### Expected behavior

`~` should be resolved to `$HOME` on *nix systems.

### Actual behavior

Paket believes it's a local folder.

### Known workarounds

Providing a full path is not really a workaround since it makes the git repository non-portable between peoples' machines.

**Comment by forki** [comment]
it should also do something sensible on windows - after all paket repos need to work on both platforms

**Comment by oopbase** [comment]
Something sensible on windows would be `%systemdrive%%homepath%` I guess?

**Comment by forki** [comment]
fixed by @oopbase
