### ISSUE TITLE
Exception restoring projects in parallel with dotnet sdk 2.1.100-preview

### ISSUE THREAD

**Issue by Tarmil** [fsprojects/Paket#3075]
### Description

Visual Studio 2017 15.6-preview installs dotnet SDK 2.1.100-preview. One change with this new SDK is that `dotnet restore` restores the projects of a solution in parallel. This causes paket to trip over itself:

```
  Paket failed with
  -> IOException: The process cannot access the file 'c:\if\websharper.ui.next\WebSharper.UI.CSharp\obj\WebSharper.UI.CSharp.fsproj.netstandard2.0.paket.resolved' because it is being used by another process.
c:\if\websharper.ui.next\.paket\Paket.Restore.targets(74,5): error MSB3073: The command ""c:\if\websharper.ui.next\.paket\paket.exe" restore" exited with code 1. [c:\if\websharper.ui.next\WebSharper.UI.Templating.Tests\WebSharper.UI.Templating.Tests.fsproj]
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Install a dotnet SDK preview, either by installing VS2017 15.6-preview or by getting an installer [here](https://github.com/dotnet/cli/blob/master/README.md#installers-and-binaries) (this one is 2.1.300-preview, which has the same behavior)

2. Run `dotnet restore` in a solution that has multiple projects with dependencies between them.

### Expected behavior

Restore succeeds.

### Actual behavior

Restore fails with the above error message.

### Known workarounds

Use `global.json` to use an older SDK.

**Comment by Jand42** [comment]
Other workaround: run `dotnet restore` with the `--disable-parallel` flag.

**Comment by forki** [comment]
Can you please upload a zip with a sample project that would fail on new
sdk? Thanks

Am 10.03.2018 18:00 schrieb "András Jankó" <notifications@github.com>:

**Comment by forki** [comment]
just tried with https://github.com/SAFE-Stack/SAFE-BookStore locally. but can't repro.

**Comment by forki** [comment]
Unfortunately we did not get a repro yet, but can you pelase retry with 5.150.1?

**Comment by Tarmil** [comment]
The issue still happens reliably with Paket 5.151.1 and dotnet 2.1.300-preview2-008260. There needs to be at least 4 projects in the solution for it to happen reliably. Having dependencies between them does not actually seem to be a factor.
Here is a minimal repro: https://github.com/Tarmil/repro-paket-3075

`dotnet restore` gives me either one of these two errors:

```
  -> FileNotFoundException: Could not find file 'c:\my\pakettest\proj2\obj\proj2.fsproj.references'.
```

or

```
  -> IOException: The process cannot access the file 'c:\my\pakettest\proj2\obj\proj2.fsproj.paket.references.cached' because it is being used by another process.
```

It happens every time, provided that I clean the obj directories between attempts with `git clean -dffx`.

**Comment by forki** [comment]
Thanks. Had to revert that change that I made because it broke others.
Will look into it tomorrow.

**Comment by MiloszKrajewski** [comment]
dotnet core sdk 2.1.101 does not even honor `--disable-parallel` so I needed to use `global.json` to force use of `2.1.4`

**Comment by forki** [comment]
can you guys please try with paket 5.152.0-alpha001

**Comment by MiloszKrajewski** [comment]
Seems like `5.152.0-alpha001` works. It does not do parallel though. I just waits for other "pakets" to finish, right?

**Comment by forki** [comment]
yes there needs to be finer locks eventually

**Comment by forki** [comment]
@MiloszKrajewski ok alpha002 has finer locks and only blocks the obj folder. Still working for you?

**Comment by MiloszKrajewski** [comment]
`alpha003`: There is no perceived performance improvement related to "finer locks", but it works as expected (which is the important part).
