### ISSUE TITLE
Paket 5.145.0 fails to generate-load-scripts completely

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/Paket#3080]
### Description

Paket 5.145.0 fails to generate-load-scripts completely, at least on AppVeyor builds.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a Project Scaffold project referencing `Microsoft.Azure.Management.Fluent`
2. Generate load scripts and reference the `Microsoft.Azure.Management.Fluent` script in `build.fsx`
3. Create an AppVeyor build that calls `paket.exe generate-load-scripts --group main --framework net462 --type fsx --silent`
4. Run the build on AppVeyor

### Expected behavior

Load scripts should be correctly generated and referenced in build.fsx, and build should succeed.

### Actual behavior

```
Build failed.
Error:
Could not find script '../Microsoft.Azure.Management.AppService.Fluent.fsx' in any paths searched. Searched paths:
[]
-------------------
 FAKE usage
-------------------
    fake.exe [<scriptPath>] [<targetName>] [options]
    scriptPath: Optional.  Path to your FAKE build script.  If not specified, FAKE will use the first .fsx file in the working directory and fail if none exists.
    
    targetName: Optional.  Name of the target you wish to run.  This will override the target you specifed to run in the build script.
                           When targetName is equal --listTargets or -lt FAKE will list the targets with their dependencies.
    Options:
```

### Known workarounds

Use paket version 5.141.0. For magic mode, add  `<add key="PaketVersion" value="5.141.0"/>` to the `paket.exe.config` `appSettings` section.

**Comment by panesofglass** [comment]
All of our builds just started failing, and I was only able to fix it by locking on paket 5.141.0.

**Comment by matthid** [comment]
Yes something is wrong, I'm trying to fix :/

**Comment by baronfel** [comment]
We hit this today as well. Http.fs is a good test case if you need one.

**Comment by matthid** [comment]
> We hit this today as well. Http.fs is a good test case if you need one.

@baronfel Yes, but we need those test-cases in our test suite to be effective ;)

Either way I think I found the problem and fix is on the way, sorry for the breakage. That shouldn't have gone through our test suite :/

**Comment by matthid** [comment]
Let me know if https://github.com/fsprojects/Paket/releases/tag/5.145.1 works again.

**Comment by panesofglass** [comment]
@matthid no, it still fails for us with the same error.

**Comment by panesofglass** [comment]
@matthid I can confirm that version works.
