### ISSUE TITLE
UriFormatException for gist references with GitHubApi token (versions > 5.142.0)

### ISSUE THREAD

**Issue by orient-man** [fsprojects/Paket#3086]
### Description

Throws UriFormatException for gist references with GitHubApi token (versions > 5.142.0)

### Repro steps

Example reference that used to work:

    gist orient-man/c29c299ed970fd097f80124ffde734ce FindOutdatedPackages.fsx github-api-token

### Expected behavior

Should work as described in https://fsprojects.github.io/Paket/github-dependencies.html#Referencing-a-private-GitHub-repository

### Actual behavior

Throws "Paket failed with -> UriFormatException"

### Known workarounds

Do not upgrade > 5.142.0. Set in paket.dependecies:

    version 5.142.0

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/36733367-a6103da4-1bd0-11e8-8791-b4dcb5a29435.png)

seems to work for me.

**Comment by forki** [comment]
ok now I can repro. @matthid this looks like a regression that was introduced with CredentialProviders

**Comment by matthid** [comment]
Yeah another area where our test-coverage is not all that awesome ;)
