### ISSUE TITLE
Retry HTTP downloads

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#3088]
### Description

When a http dependency fails to download, please retry the request. I see a lot of transient errors with sourceforge.

### Repro steps

1. Add `http https://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.7/optipng-0.7.7-win32.zip` and try to restore.

### Expected behavior

Retry like we do with NuGets for x times, then fail.

### Actual behavior

```
Paket version 5.145.6
Downloading downloads.sourceforge.net/:/project/optipng/OptiPNG/optipng-0.7.7/optipng-0.7.7-win32.zip optipng-0.7.7-win32.zip to C:\BuildAgent\work\e3efd18142ae7728\paket-files\downloads.sourceforge.net\optipng-0.7.7-win32.zip
Performance:
 - Average Download Time: 22 seconds
 - Number of downloads: 1
 - Runtime: 22 seconds
Paket failed with
-> Could not download from 'https://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.7/optipng-0.7.7-win32.zip'
-> HttpRequestException: An error occurred while sending the request.
-> WebException: Unable to connect to the remote server
-> SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 5.10.152.194:443
```

### Known workarounds

Restart `paket restore`.

**Comment by agross** [comment]
Thank you very much!

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/36794543-eb2b3166-1ca0-11e8-8570-8bbc3caa7d7b.png)

already helping me in another scenario...

**Comment by agross** [comment]
I'm glad you benefit as well :) 👍
