### ISSUE TITLE
Do framework conditional references in paket.references work with .NET SDK-style projects?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Paket#3091]
I've had trouble getting conditional references in `paket.references` working in the context of .NET SDK-style projects.  Roughly speaking I had this in `paket.references`:

```
Nancy.Hosting.Self framework: net461
```

But I still get this error for when compiling `TargetFramework=netcoreapp2.0` for a multi-targeting project:

```
C:\GitHub\dsyme\FSharp.Data\tests\FSharp.Data.Tests\FSharp.Data.Tests.fsproj : error NU1701: 
Package 'Nancy.Hosting.Self 2.0.0-clinteastwood' was restored using '.NETFramework,Version=v4.6.1' 
instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully
compatible with your project.
```

I would have thought that the `framework: net461` would suppress the reference for `netcoreapp2.0`?

**Comment by dsyme** [comment]
(This is a question - I suppose I can create a repro if this is expected to work - thanks)

**Comment by forki** [comment]
Yes we minimal repro would be good. Tbh I'm not sure.

Am 27.02.2018 19:22 schrieb "Don Syme" <notifications@github.com>:

**Comment by punker76** [comment]
@forki [Here is](https://github.com/punker76/PaketMultiTargetingTest) a simple sample which shows this issue (error NU1202). A package should only be added in a higher framework, but it will be also added to the other ones:

VS 2017 15.6.4
R# 2017.3.5
Paket 5.153.2

The `MaterialDesignThemes` package should only be add for >= .NET45

```
JetBrains.Annotations
MahApps.Metro.IconPacks
MahApps.Metro

MaterialDesignThemes framework: >= net45
```

Bu the `PaketMultiTargetingTest.csproj.net40.paket.resolved` contains also the `MaterialDesignThemes` package.

```
ControlzEx,3.0.2.4,Transitive,Main,false
JetBrains.Annotations,11.1,Direct,Main,false
MahApps.Metro,1.6.1,Direct,Main,false
MahApps.Metro.IconPacks,2.1,Direct,Main,false
MaterialDesignColors,1.1.3,Transitive,Main,false
MaterialDesignThemes,2.4.0.1044,Direct,Main,false
```

![2018-03-26_21h02_24](https://user-images.githubusercontent.com/658431/37927219-c58fd47c-3139-11e8-9770-46f33149c9f4.png)
