### ISSUE TITLE
Backslashes not escaped after #3071

### ISSUE THREAD

**Issue by JarnoNijboer** [fsprojects/Paket#3093]
### Description
Today I upgraded from Fake 5-beta018 to beta020 because of the broken intellisense in VSCode. (fsharp/fake#1744).
With this change the forward slashes in intellisense.fsx are replaced with single back slashes.

### Repro steps

Please provide the steps required to reproduce the problem

1. Upgrade Fake 5 from beta018 to beta020

2. Delete [script_name.fsx].lock file

3. Call fake.cmd, such that a restore is triggert

4. Open directory in Ionide

[repo](https://github.com/matthid/fake-bootstrap/tree/master)
### Expected behavior
Expected output:
```
#if !FAKE
#r "C:/Users/jarno/.nuget/packages/fake.core.xml/5.0.0-beta018/lib/net46/Fake.Core.Xml.dll"
```

### Actual behavior
Actual output:
```
#if !FAKE
#r "C:\Users\jarno\.nuget\packages\fake.core.xml\5.0.0-beta020\lib\net46\Fake.Core.Xml.dll"
```

### Known workarounds
Possible workarounds are:
1. Replacing the `\` with `/`
2. Escape the `\` with a extra `\`

Example: 
```
#if !FAKE
#r "C:\\Users\\jarno\\.nuget\\packages\\fake.core.xml\\5.0.0-beta020\\lib\\net46\\Fake.Core.Xml.dll"
```

**Comment by matthid** [comment]
Ah sorry... you fix something on one side and something else breaks on the other side :/

**Comment by forki** [comment]
Is that a paket bug?

Am 27.02.2018 22:12 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment]
Yes most likely load script generation is still broken

**Comment by forki** [comment]
Are you looking into this?

Am 28.02.2018 07:13 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment]
I added the fix to https://github.com/fsprojects/Paket/pull/3090

**Comment by forki** [comment]
that one gets huge ;-)

**Comment by matthid** [comment]
+45 −18 is still kind of review-able ;)
