### ISSUE TITLE
Generate Load Scripts fails with BadImageFormatException on Microsoft.TestPlatform.TestHost

### ISSUE THREAD

**Issue by ChrSteinert** [fsprojects/Paket#3097]
### Description

When the package `Microsoft.TestPlatform.TestHost` is a dependency in `paket.dependencies` file and it is tried to create a load script for that dependency paket fails with a `BadImageFormatException`.

### Repro steps

See a repro repo here: https://github.com/ChrSteinert/Paket-3097
Do a `paket install` && `paket generate-load-scripts` do trigger the bug.

### Expected behavior

Paket ignores native dll files.

### Actual behavior

Paket tries on multiple occasions to load `.dll` files of a package. [Some](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Installation/InstallProcess.fs#L300) are guarded by `try…with`, but [some](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PaketConfigFiles/DependencyCache.fs#L101) are not. Load Script generation hits the latter one and breaks if it tries to load native dlls from (for instance) the `Microsoft.TestPlatform.TestHost` package.

### Known workarounds

Do not generate Load Scripts for those packages.

**Comment by forki** [comment]
any chance to send a fix? I think @isaacabraham  hit it as well

**Comment by isaacabraham** [comment]
Hmmm. I vaguely remember something about this but can't remember when or where. Getting old I guess...

**Comment by ChrSteinert** [comment]
It was hitting you here: https://github.com/fsprojects/FSharp.CloudAgent/pull/19 @isaacabraham 😄

**Comment by ChrSteinert** [comment]
Let me see if I can understand what is going on quickly and not just bash a `try…with` in there as well…
