### ISSUE TITLE
Can't get dotnet to build using the target framework

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#3122]
### Description

When using `dotnet build` I keep running into incompatible framework versions that do not target the requested netstandard v2 framework.

### Repro steps

Please provide the steps required to reproduce the problem

1. Use this dependency file:

```
redirects force
framework: auto-detect
generate_load_scripts: true
storage: none

source https://api.nuget.org/v3/index.json

nuget FSharp.Data
nuget FSharpComposableQuery prerelease
```

2. Use these references in a dotnet F# console or classlib project.

3. Run the `paket install` and `dotnet build` commands

### Expected behavior

The right framework targets are used and the build has no warnings.

### Actual behavior

This is what I see in my example:

> /src/Informedica.GenProduct.Lib/Informedica.GenProduct.Lib.fsproj : warning NU1701: Package 'FSharp.Data 2.4.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/GenFormService.sln]
> /src/Informedica.GenProduct.Lib/Informedica.GenProduct.Lib.fsproj : warning NU1701: Package 'FSharpComposableQuery 1.0.4-beta' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/GenFormService.sln]
> /src/Informedica.GenProduct.Lib/Informedica.GenProduct.Lib.fsproj : warning NU1701: Package 'Zlib.Portable 1.11.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/GenFormService.sln]
> /tests/Informedica.GenProduct.Tests/Informedica.GenProduct.Tests.fsproj : warning NU1701: Package 'FSharp.Data 2.4.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/GenFormService.sln]
> /tests/Informedica.GenProduct.Tests/Informedica.GenProduct.Tests.fsproj : warning NU1701: Package 'FSharpComposableQuery 1.0.4-beta' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/GenFormService.sln]
> /tests/Informedica.GenProduct.Tests/Informedica.GenProduct.Tests.fsproj : warning NU1701: Package 'Zlib.Portable 1.11.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/GenFormService.sln]
> /src/Informedica.GenProduct.Lib/Informedica.GenProduct.Lib.fsproj : warning NU1701: Package 'FSharp.Data 2.4.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
> /src/Informedica.GenProduct.Lib/Informedica.GenProduct.Lib.fsproj : warning NU1701: Package 'FSharpComposableQuery 1.0.4-beta' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
> /src/Informedica.GenProduct.Lib/Informedica.GenProduct.Lib.fsproj : warning NU1701: Package 'Zlib.Portable 1.11.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
> /tests/Informedica.GenProduct.Tests/Informedica.GenProduct.Tests.fsproj : warning NU1701: Package 'FSharp.Data 2.4.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
> /tests/Informedica.GenProduct.Tests/Informedica.GenProduct.Tests.fsproj : warning NU1701: Package 'FSharpComposableQuery 1.0.4-beta' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
> /tests/Informedica.GenProduct.Tests/Informedica.GenProduct.Tests.fsproj : warning NU1701: Package 'Zlib.Portable 1.11.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
>     12 Warning(s)
> 

The lock file seems OK though:

GENERATE-LOAD-SCRIPTS: ON
REDIRECTS: FORCE
STORAGE: NONE
RESTRICTION: || (== netcoreapp2.0) (== netstandard2.0)
```
NUGET
  remote: https://api.nuget.org/v3/index.json
    Argu (5.1)
      FSharp.Core (>= 4.3.2)
      System.Configuration.ConfigurationManager (>= 4.4)
    Expecto (7.0)
      Argu (>= 5.1)
      Mono.Cecil (>= 0.10.0-beta7)
      System.Diagnostics.FileVersionInfo (>= 4.3)
    Expecto.FsCheck (7.0)
      Expecto (>= 7.0)
      FsCheck (>= 2.10.4)
    FsCheck (2.10.8)
      FSharp.Core (>= 4.2.3)
      NETStandard.Library (>= 1.6.1)
      System.ValueTuple (>= 4.4)
    FSharp.Core (4.3.4)
    FSharp.Data (2.4.5)
      Zlib.Portable (>= 1.11)
    FSharpComposableQuery (1.0.4-beta)
    MathNet.Numerics (4.4)
    MathNet.Numerics.FSharp (4.4)
      FSharp.Core (>= 4.3.3)
      MathNet.Numerics (>= 4.4)
    Microsoft.NETCore.Platforms (2.0.1)
    Microsoft.NETCore.Targets (2.0)
.....
```

### Known workarounds

I have none ;-(

**Comment by forki** [comment]
This are nuget warnings. Are you sure it's a paket issue?

Casper <notifications@github.com> schrieb am Fr., 16. März 2018, 23:19:

**Comment by halcwb** [comment]
You're right, I am not sure were this problem lies. But I was thinking that it is Paket that is fetching the packages? So, when I look at the references of the packages, this is what I see:

> @"/Users/hal/.nuget/packages/fsharp.data/2.4.5/lib/net45/FSharp.Data.dll"
> #r @"/Users/hal/.nuget/packages/fsharpcomposablequery/1.0.4-beta/lib/net40/FSharpComposableQuery.dll"
> #r @"/Users/hal/.nuget/packages/mathnet.numerics.fsharp/4.4.0/lib/netstandard2.0/MathNet.Numerics.FSharp.dll"

So, the MathNet.Numerics package is correct, but not the FSharp.Data and FSharpComposableQuery packages.

**Comment by forki** [comment]
What do you mean they are not correct?

Casper <notifications@github.com> schrieb am Sa., 17. März 2018, 09:57:

**Comment by forki** [comment]
Can you please upload a zip with detailed repro? I have trouble to understand your issue.

Also please try without auto detect

**Comment by halcwb** [comment]
With 'not correct' I mean that FSharp.Data.dll is targeted at the net45 framework, not the required netstandard2.0:

@"/Users/hal/.nuget/packages/fsharp.data/2.4.5/lib/**net45**/FSharp.Data.dll"
#r @"/Users/hal/.nuget/packages/fsharpcomposablequery/1.0.4-beta/lib/**net40**/FSharpComposableQuery.dll"
#r @"/Users/hal/.nuget/packages/mathnet.numerics.fsharp/4.4.0/lib/**netstandard2.0**/MathNet.Numerics.FSharp.dll"

**Comment by forki** [comment]
Well, target framework selection in dotnet build is done by nuget. Paket is
only telling it package name and package version

Casper <notifications@github.com> schrieb am Sa., 17. März 2018, 10:13:

**Comment by halcwb** [comment]
I am going to put my blame on dotnet build then ;-)

This is the project I am referring to: http://github.com/halcwb/GenForm.git.

**Comment by halcwb** [comment]
Ok, sorry for wasting your time, but I was assume (mother of all f.. ups) that FSharp.Data would have a netcore version, but this is not the case. My mistake.

**Comment by forki** [comment]
Don't worry it's confusing message. They should improve that

Casper <notifications@github.com> schrieb am Sa., 17. März 2018, 10:23:
