### ISSUE TITLE
symbolic link storage option support

### ISSUE THREAD

**Issue by cboudereau** [fsprojects/Paket#3127]
### Description

In order to reduce time + disk space of the packages folder, an option storage: symlink could link the nuget cache dir to the package folder (inside the packages folder).

I have done the dev in my fork and I am building integration test (I need an issue number to name scenarios).

**Comment by cboudereau** [comment]
Could you assign me the issue please ?

**Comment by matthid** [comment]
thanks for looking into that :)

**Comment by matthid** [comment]
Just a word of warning: Keep in mind that we have not done this yet because a lot of devils lie in the details (xplat for example is one of those devils ;) )

**Comment by cboudereau** [comment]
done #3128
