### ISSUE TITLE
Running paket install fails?

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#3132]
### Description

Clone my repository https://github.com/halcwb/GenForm.git. Run `mono .paket/paket.exe install` And you get:

> Error: SecureChannelFailure (The authentication or decryption has failed.) (Github - cached (temporarily ignore updates))

### Repro steps

Please provide the steps required to reproduce the problem

1. See above

If possible then please create a git repository with a repro sample or attach a zip to the issue.

Install of packages

Please provide a description of the behavior you expect.

See above

Please provide a description of the actual behavior you observe. 

Problem need to commit paket genererated files as well! But why?

Please provide a description of any known workarounds.

**Comment by matthid** [comment]
Have you tried updating your bootstrapper since
- https://github.com/fsprojects/Paket/pull/3066
- https://github.com/fsprojects/Paket/issues/3068

?

**Comment by forki** [comment]
also mono updated?

**Comment by halcwb** [comment]
@forki  Indeed it seemed that particular machine had an outdated mono version. I already had tried using the lates bootstrapper in 'magic mode'. But it was the mono framework.

Thanks!
