### ISSUE TITLE
paket outdated --silent is not silent

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#3135]
### Description And Repro

Create a `paket.dependencies` + `paket.lock` containing outdated stuff 
for example `Newtonsoft.Json 10.x` in lock file and no constraints in `paket.dependencies`

run `paket outdated -s`
run `paket outdated `

It actually write the SAME thing except the `performance block`

```
>paket outdated -s
Resolving packages for group Build:
 - MSBuild.Microsoft.VisualStudio.Web.targets 14.0.0.3
 - FAKE 4.64.4
 - FAKE.Lib.x64 4.64.4
 - FSharp.Core 4.3.4
 - Http.fs 4.1.2
 - GitVersion.CommandLine 3.5.4
 - OpenCover 4.6.519
 - MSBuild.SonarQube.Runner.Tool 4.1.0
 - NUnit.Runners 3.8.0
 - ReportGenerator 3.1.2
 - SourceLink 1.1.0
 - NUnit.ConsoleRunner 3.8.0
 - NUnit.Extension.VSProjectLoader 3.7.0
 - NUnit.Extension.NUnitV2Driver 3.7.0
 - NUnit.Extension.NUnitProjectLoader 3.6.0
 - NUnit.Extension.NUnitV2ResultWriter 3.6.0
 - NUnit.Extension.TeamCityEventListener 1.0.3
 - Hopac 0.3.23
 - NETStandard.Library 2.0.1
 - Microsoft.NETCore.Platforms 2.0.1
Resolving packages for group Main:
 - Autofac.WebApi2.Owin 4.0.0
 - Microsoft.AspNet.WebApi 5.2.4
 - Microsoft.Owin.Host.SystemWeb 4.0.0
 - Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.8
 - Microsoft.Net.Compilers 2.7.0
 - Microsoft.Owin.StaticFiles 4.0.0
```

### Expected behavior

I have no idea because i don't really know what `silent` actually means
Should the %ERRORLEVEL% be set to a specific code error when it is silent ?
What is the purpose of silent when this only way to parse result should not be printed ?

### Actual behavior

Verbose (~100 lines for me), but remove `Performance` ~10 lines

### Known workarounds

None

**Comment by tebeco** [comment]
you're too fast man ;) (and that's amazing)

**Comment by agross** [comment]
Does it makes sense to run `paket outdated` in silent mode? I only use it interactively.

One use-case might be to run `paket outdated -s || paket update` to perform a scripted update only when there is outdated stuff in the lockfile.

**Comment by tebeco** [comment]
@agross 
it could make sense with this : https://github.com/fsprojects/Paket/issues/3136

We use it on nightly + a Board that does reporting for all our ~180 repos
So it kinda make sense in this specific use case

**Comment by agross** [comment]
Yep, I agree. So `-s` should make the `outdated` command silent and `exit 1` accordingly.
