### ISSUE TITLE
paket.dependencies download_license does not work

### ISSUE THREAD

**Issue by jafz** [fsprojects/Paket#3148]
### Description
https://fsprojects.github.io/Paket/dependencies-file.html#License-download describes how to make paket download the licenses for nuget packages.
However, paket does not seem to understand that configuration setting.

### Repro steps
This is in my paket.dependencies file:
`source https://api.nuget.org/v3/index.json
download_license: true
nuget Automapper`

when I run '.paket\paket.exe install', paket returns the following error:
`Performance:
 - Runtime: 893 milliseconds
Paket failed with
-> Error in paket.dependencies line 7
     Unrecognized token: download_license: true`

### Expected behavior
I would expect that the licenses of the packages are downloaded.

### Actual behavior
Paket returns an error and does not download anything.

### Known workarounds
paket runs normally when not using that configuration setting, but then I do not get license files.

**Comment by forki** [comment]
would appreciate a PR
