### ISSUE TITLE
Can't bootstrap paket on travis-ci's ubuntu?

### ISSUE THREAD

**Issue by NullVoxPopuli** [fsprojects/Paket#3153]
### Description

I'm trying to run a dotnet core project on travis.
### Repro steps

https://travis-ci.org/NullVoxPopuli/CryptoExchangeClient/builds/366045372

my init script:
```
      cd .paket \
      rm paket.exe paket.bootstrapper* \

      wget https://github.com/fsprojects/Paket/releases/download/5.156.0/paket.bootstrapper.exe \
      && chmod +x paket.bootstrapper.exe \
      && ./paket.bootstrapper.exe \
      && chmod +x paket.exe
```

https://github.com/NullVoxPopuli/CryptoExchangeClient/commit/5716c25788b8c0c24ec25ab0c9f4d2ce9d367488

### Expected behavior

Paket to be bootstrapped

### Actual behavior

error: https://travis-ci.org/NullVoxPopuli/CryptoExchangeClient/builds/366045372

```
./run: line 56: ./paket.bootstrapper.exe: cannot execute binary file: Exec format error
```

Note that locally, on my ubuntu 16.04 machine, the script works.

**Comment by forki** [comment]
You need to install mono

L. Preston Sego III <notifications@github.com> schrieb am Fr., 13. Apr.
2018, 12:44:

**Comment by NullVoxPopuli** [comment]
really? I thought this worked with dotnet core's cli?

**Comment by forki** [comment]
yes but it calls into paket.exe which is still a .NET tool so you still need mono. But this will be gone eventually
