### ISSUE TITLE
Pack: files with space will contain %20 inside the nupkg

### ISSUE THREAD

**Issue by pchinery** [fsprojects/Paket#3170]
### Description

Files with space will contain %20 inside the nupkg. It does not seem to matter if the files are included specifically or through wildcards/globbing.

### Repro steps

1. Clone https://github.com/pchinery/paket-bugreport/tree/master

2. Run `paket pack .`

### Expected behavior
The file `test with space.txt` should be in the tools folder of the package.

### Actual behavior

The file is named `test%20with%20space.txt` instead

### Known workarounds

none

**Comment by pchinery** [comment]
I started digging in the project and a good candidate for the root is `createRelativePath`, but it is used in quite a few places and I am still trying to get some orientation in the project ;-)

**Comment by matthid** [comment]
afaik this is by design and nuget is/was doing the same, do you have an issue with that?

**Comment by pchinery** [comment]
ok, I am quite surprized. Do you know if this will be decoded to spaces again when extracted with Paket/NuGet? If yes, then I can close this again and sorry for bothering you ;-)

**Comment by matthid** [comment]
Yes at least that's the idea. That's why I asked if you encountered any errors with this.

**Comment by pchinery** [comment]
No, I just came across this and it kept the %20 even after extracting the files, but in restrospect, I found that I extracted them with a regular ZIP tool.

**Comment by matthid** [comment]
Welcome to NuGet world where everything is magic, even extracting a zip file.
