### ISSUE TITLE
Paket version 5.157.0-alpha003 is breaking Fulma repo

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/Paket#3180]
### Description

Since yesterday evening people are reporting me problems with Fulma repo and templates.

Errors are like:

```
> No executable found matching command "dotnet-fake"

> No executable found matching command "dotnet-fable"
```

I suspect this issues will impact any project using `clitool`.

### Repro steps

Please provide the steps required to reproduce the problem

1. `git clone git@github.com:MangelMaxime/Fulma.git`

2. ` ./fake.sh build`

3. The build is failing

### Expected behavior

`dotnet fake` should work.

### Actual behavior

```
> No executable found matching command "dotnet-fake"
```

### Known workarounds

If replace the magic mode with `paket.exe` version **5.156.7** then it's working again.

**Comment by forki** [comment]
urgs @matthid

**Comment by matthid** [comment]
Oo? Is the paket bootstrapper using prereleases by default?

**Comment by MangelMaxime** [comment]
@matthid I don't think.

I have this [paket.exe.config](https://github.com/MangelMaxime/Fulma/blob/master/.paket/paket.exe.config) file in my project:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="Prerelease" value="True"/>
  </appSettings>
</configuration>
```

I should probably remove it at least from the template indeed but it's useful to detect bugs :)

**Comment by matthid** [comment]
Yes I’m glad we found this, but we shouldn’t break people on an alpha release :)

Is this an urgent fix considering the template it out? If yes @forki can you release another alpha from master? I’m not sure I can takle this today or tomorrow...

**Comment by forki** [comment]
do we know what broke it? and how to fix?

**Comment by MangelMaxime** [comment]
Just for info, I fixed the template and my Fulma repo to use only stable version of paket.

**Comment by matthid** [comment]
At least I have no idea but fest step would be to look atthe build output which I cannot run at the moment

**Comment by forki** [comment]
so what should I do? people are reporting this on fable gitter? unlisting the prerelease versions?

**Comment by MangelMaxime** [comment]
@forki I think the safe approach is to remove the prerelease versions.

**Comment by forki** [comment]
@matthid would that break FAKE?

**Comment by MangelMaxime** [comment]
Or apply the solution proposed by @matthid 

> If yes @forki can you release another alpha from master? I’m not sure I can takle this today or tomorrow...

**Comment by matthid** [comment]
No it won’t break fake. actually unlisting should have worked just as well, sorry

**Comment by forki** [comment]
pushed a master version as latest prerelease

**Comment by matthid** [comment]
Ok I debugged into this, however now I have no idea why it ever worked. Apparently we currently don't detect these kind of new-style sdk projects (using `Import` instead of `Sdk` attribute as well as `.proj` file extension)
I fixed these issues and the problems went away. However it must be some kind of side-effect from some other change as all my changes were unrelated to this....

**Comment by matthid** [comment]
@MangelMaxime Can you try again with https://www.nuget.org/packages/Paket.Core/5.162.0-alpha002? Seems to work now.

**Comment by MangelMaxime** [comment]
Sorry for the delay.
This is working with latest version of paket.

Thank you guys
