### ISSUE TITLE
Best practices for using Paket with monorepos and Docker builds

### ISSUE THREAD

**Issue by gaui** [fsprojects/Paket#3185]
What are the best practices for using Paket with monorepos and Docker builds?

We have a fairly large repository 2.5GB and when we're doing Docker builds for projects further down the tree, it takes way too much time, because .paket/ is in the root and is needed as a part of the build context.

When we do the following, it takes up to 5 minutes:

```
$ pwd
/monorepo
$ docker build -t api -f DocumentAPI/Dockerfile .
```

Dockerfile:

```
ARG DOTNETCORE_VERSION="2.0"
FROM microsoft/aspnetcore-build:${DOTNETCORE_VERSION} AS build
ARG PROJECT_NAME="DocumentAPI"

WORKDIR /app

# Install Mono
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
	&& echo "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list \
	&& echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/4.4.2.11 main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list \
	&& apt-get update -yq \
	&& apt-get install -yq mono-devel \
	&& rm -rf /var/lib/apt/lists/*

RUN echo ${PROJECT_NAME}

# Copy everything and run build
RUN mkdir ${PROJECT_NAME}
COPY . ${PROJECT_NAME}
RUN dotnet restore ${PROJECT_NAME}
RUN dotnet build ${PROJECT_NAME}


# Create a intermediate image and run tests
FROM build AS testrunner
WORKDIR /app
RUN dotnet test
ENTRYPOINT ["dotnet", "test"]


# Publish runtime artifacts to a seperate folder
FROM build as publish
WORKDIR /app/${PROJECT_NAME}/${PROJECT_NAME}
RUN dotnet publish -c Release -o out


# Create a runtime image
FROM microsoft/aspnetcore:${DOTNETCORE_VERSION}-runtime AS runtime
WORKDIR /app
COPY --from=publish /app/${PROJECT_NAME}/${PROJECT_NAME}/out .


EXPOSE 8080
ENTRYPOINT ["dotnet", "DocumentAPI.exe"]
```

**Comment by forki** [comment]
I don't understand. What concrete issue is paket causing?

Gudjon <notifications@github.com> schrieb am So., 6. Mai 2018, 01:39:

**Comment by matthid** [comment]
I guess the problem is that the cache is empty and paket is downloading everything. One workaround would be to mount the .nuget directory. However I don't know if that is even possible with dockerfiles

**Comment by skalinets** [comment]
@gaui can `.dockerignore` help you?

**Comment by gaui** [comment]
@skalinets Perhaps! If I have `/monorepo/DocumentAPI/.dockerignore` with the following content:

```
# Ignore everything
**
# Allow only
!./paket/**
!./monorepo/DocumentAPI/**
```

and then from within `/monorepo` I run `docker build -t api -f ./DocumentAPI/Dockerfile .` , does it use the `/monorepo/DocumentAPI/.dockerignore` ?

**Comment by gaui** [comment]
This might just work...

![](https://i.imgur.com/L21KINY.png)

**Comment by gaui** [comment]
Actually, the `.dockerignore` files has to be on the same level as the `docker build .` command , and is always relative from that. I would like to see Docker look up the `.dockerignore` file with a bottom-up approach, from the same location as the Dockerfile in the `-f` flag, where you could ignore files from the root context, but specify all `.dockerignore` rules from the project folder. This is just how Docker works. [I raised this in the docker/cli repo](https://github.com/docker/cli/issues/1308). Going to close this issue.
