### ISSUE TITLE
`copy_local: false` has no effect in paket.references (.NET SDK)

### ISSUE THREAD

**Issue by nightroman** [fsprojects/Paket#3186]
The issue is related to the recently resolved https://github.com/fsprojects/Paket/issues/3154

Use the same steps for reproducing the problem with one change:

- do not use `copy_local: false` in *paket.dependencies*
- instead, in *paket.references* use `Suave copy_local: false`

**Expected result**

On building the project *Suave.dll* is not copied to the output directory.

**Actual result**

*Suave.dll* is copied to the output directory.

**Comment by atlemann** [comment]
I also have this problem. I have tried fiddling with paket.restore.targets, but I cannot make it work. I also cannot find any good documentation on what exactly the options for ExcludeAssets and PrivateAssets mean, and which of those that replaces the old copy local/private flag.

**Comment by atlemann** [comment]
Seems like the `<ExcludeAssets>runtime</ExcludeAssets>` tag is not inserted into the `obj/{project.file}.paket.props` file even though the `obj/{project.file}.%(Identity).paket.resolved` says `exclude` in for the NuGets marked with `copy_local`.

**Comment by atlemann** [comment]
The difference between setting `copy_local: false` in `paket.dependencies` and `paket.references` you can see in the generated `{projectfilename}.paket.net462.resolved` file in the `obj` folder:

- set `copy_local: false` in `paket.dependencies`:
FSharp.Core,4.5.2,Transitive,Main,exclude
Suave,2.4.3,Direct,Main,exclude

- set `copy_local: false` in `paket.references`:
FSharp.Core,4.5.2,Transitive,Main,false
Suave,2.4.3,Direct,Main,false

I would think that both should end up with `exclude` as the last element.

**Comment by atlemann** [comment]
Seems like it's hard-coded to be `copy_local: true` in the references files (the 4th argument):
https://github.com/fsprojects/Paket/blob/81c7479ed18688e3776a74552fd2b344903e8531/src/Paket.Core/PaketConfigFiles/ReferencesFile.fs#L176

**Comment by atlemann** [comment]
Hmm...the easiest is actually to see the `paket.lock` file:

- set `copy_local: false` in `paket.dependencies`:
```
RESTRICTION: == net462
NUGET
  remote: https://www.nuget.org/api/v2
    FSharp.Core (4.5.2) - copy_local: false
    Suave (2.5) - copy_local: false
      FSharp.Core (>= 4.0 < 5.0)
```

- set `copy_local: false` in `paket.references`:
```
RESTRICTION: == net462
NUGET
  remote: https://www.nuget.org/api/v2
    FSharp.Core (4.5.2)
    Suave (2.5)
      FSharp.Core (>= 4.0 < 5.0)
```

Soooo...why is it ignored in the references file. It says in the docs that this should work:
https://fsprojects.github.io/Paket/references-files.html#Overriding-settings-from

**Comment by atlemann** [comment]
It seems like for new .NET SDK projects, the options provided in the `paket.references` files are not taken into consideration, since that info is not written to the `paket.lock` file when running `paket install`.

**Comment by Uriel6575** [comment]
It seems that it's broken again for .NET Core 3 Preview.
Here's an example folders. If you change TargetFramework to netcoreapp2.0 in the paket folder then NLog.dll won't be copied to bin. For netcoreapp3.0 it's copied. For standard folder it's not copied either way.

[copy_local.zip](https://github.com/fsprojects/Paket/files/3094969/copy_local.zip)

**Comment by forki** [comment]
You mean core 3 breaks it? /cc @cartermp

**Comment by Uriel6575** [comment]
It's hard for me to tell what's the reason for it no to work anymore, but with preview 4 installed targeting to netcoreapp3.0 ignores copy_local option. While targeting netcoreapp2.0 don't.
