### ISSUE TITLE
paket restore should restore deleted packages directory

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#3187]
### Description

When you delete a subdirectory inside `packages` and run `paket restore` the package in question is not restored.

Also seen with `rm -rf packages`.

### Repro steps

1. Add a nuget and `paket install`
1. `rm packages/your-nuget`
1. `paket restore`

### Expected behavior

`packages/your-nuget` is restored.

### Actual behavior

`packages/your-nuget` remains deleted.

### Known workarounds

`rm paket-files/paket.restore.cached`

**Comment by matthid** [comment]
It’s a feature ;)

The error message is slightly adjusted in https://github.com/fsprojects/Paket/pull/3173/files#diff-a27f9adaeaed43d26a2b333ceb480fdaL211

**Comment by matthid** [comment]
The workaround is exactly what you need to do when you manually mess around with the packages or .nuget/packages directories

**Comment by agross** [comment]
Thanks for the clarification!
