### ISSUE TITLE
`paket install` crash with realloc(): invalid next size

### ISSUE THREAD

**Issue by somdoron** [fsprojects/Paket#3190]
### Description

Whenever I'm running `paket install` after changes to paket.dependencies the process crash and produce the following error

```
realloc(): invalid next size
Stacktrace:

  at <unknown> <0xffffffff>
```

### Repro steps

I suspect it is only happen on my computer, as it happen across all the project I'm using.
It is only started few month ago, so I can try and test different paket version.

I'm using fedora 26, paket 5.161.2 and mono 5.4.1.6

### Expected behavior

All new packages get installed.

### Actual behavior

Paket crash.

### Known workarounds

Updating paket.lock manually and calling `paket restore` which does work.

**Comment by forki** [comment]
urgs that sounds like bad mono bug. can you please update mono?

**Comment by somdoron** [comment]
seems to work with latest mono.

Thanks.
