### ISSUE TITLE
Paket overhead on compile

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#3196]
Cross-posted as a question: https://stackoverflow.com/questions/50255905/improve-edit-run-cycle-time-on-net-core

Feel free to close issue; it's just for your information.

**Comment by xenocons** [comment]
Just wondering, if you run .paket/paket restore on the root repo before doing any running, does this improve things? I have noted significant improvements with this (I don't have scientific measure for it though)

**Comment by forki** [comment]
can you please update your paket.targets file (install should do that) and try with 5.163 again?

**Comment by haf** [comment]
That unfortunately breaks the full restore 

```
C:\dev\logary\.paket\Paket.Restore.targets(132,5): error MSB4044: The "ReadLinesFromFile" task was not given a value for the required parameter "File". [C:\dev\logary\s
rc\Logary.PerfTests\Logary.PerfTests.fsproj]
```

**Comment by haf** [comment]
I've pushed the WIP, so you can test on the logary branch if you want.

**Comment by haf** [comment]
This is what you use to run it:

```
hfeldt@catamorphism MINGW64 /c/dev/logary/src/Logary.PerfTests (feature/benchmarks)
$ dotnet run --configuration Release --framework netcoreapp2.0
```

**Comment by matthid** [comment]
@haf In the targets file is the line `ReadLinesFromFile File="%(PaketResolvedFilePaths.Identity)" >`
Can you try adding a condition like `Condition="'@(PaketResolvedFilePaths)' != ''"` and try again?

**Comment by matthid** [comment]
Also can you please try to run `dotnet run` with the `/bl:mylog.binlog` parameter and attach the generated logfile to this issue?

**Comment by matthid** [comment]
thing is paket shouldn't be run at all after a full restore

**Comment by haf** [comment]
The 163 version + @matthid's condition solves the problem!

**Comment by matthid** [comment]
@haf I think forki already released again, can you check if perf is better now?

**Comment by haf** [comment]
Much better!

**Comment by forki** [comment]
yay!
