### ISSUE TITLE
Paket run multiple times for multi project sln file

### ISSUE THREAD

**Issue by landy** [fsprojects/Paket#3204]
### Description

when running `dotnet build` in directory containing sln file with two projects paket restore is being run multiple times and showing error 

```dotnet build
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Paket version 5.163.2
  Paket version 5.163.2
  C:\projects\temp\pakettest\src\PaketTest1\obj\paket.locked is locked by paket.exe (PID = 5304). Waiting...
```

dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051
```

### Repro steps
`mkdir pakettest`
` cd .\pakettest\`
`dotnet new classlib -lang f# -o src/PaketTest1`
`dotnet new classlib -lang f# -o src/PaketTest2`
`dotnet new sln`
`dotnet sln add .\src\PaketTest1\PaketTest1.fsproj`
`dotnet sln add .\src\PaketTest2\PaketTest2.fsproj`
`cd .\src\PaketTest1\`
`dotnet add reference ..\PaketTest2\PaketTest2.fsproj`
` cd ..\..`
` mkdir .paket`
download paket bootstrapper to .paket
`.\.paket\paket.exe convert-from-nuget`
`dotnet build`

test repository https://github.com/landy/pakettest
### Expected behavior

no error shown 

### Actual behavior

after running `dotnet build` error is shown

```
dotnet build
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Paket version 5.163.2
  Paket version 5.163.2
  C:\projects\temp\pakettest\src\PaketTest1\obj\paket.locked is locked by paket.exe (PID = 17256). Waiting...
```

**Comment by r4tz52** [comment]
Same here, running "dotnet build" for solution with few projects never finishes. Parameters --no-restore or --disable-parallel doesn't show any effect.

```
C:\Projects\%MyProjectName%>dotnet build %MyProjectName%.sln
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Paket version 5.164.0
  Paket version 5.164.0
  Paket version 5.164.0
  Paket version 5.164.0
  Could not acquire lock to C:\Projects\%MyProjectName%\docs\Storage\UbiqLanguage\obj\paket.locked.
  The process cannot access the file 'C:\Projects\%MyProjectName%\docs\Storage\UbiqLanguage\obj\paket.locked' because it is being used by another process.
  Trials left: 99.
  C:\Projects\%MyProjectName%\docs\Storage\UbiqLanguage\obj\paket.locked is locked by paket.exe (PID = 4072). Waiting...
  C:\Projects\%MyProjectName%\docs\Storage\UbiqLanguage\obj\paket.locked is locked by paket.exe (PID = 4072). Waiting...  ```

**Comment by forki** [comment]
@matthid this should be fixed in latest after one paket install?

**Comment by landy** [comment]
tested it with latest Paket and it is working correctly, thanks
