### ISSUE TITLE
Generate-load-scripts seems to create many unncessary duplicate directories

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/Paket#3219]
### Description

The generate-load-scripts command seems to create a bunch of unnecessary/duplicate directories.

### Repro steps
Mono version: 5.12.0.226
Paket version: 5.167.1
OS: Ubuntu 18.04

1. Clone https://github.com/NatElkins/paket-load-scripts-repro
2. cd into repo
3. mono ./.paket/paket.exe generate-load-scripts

### Expected behavior

All the load scripts directories will be created in .paket/load

### Actual behavior

All the load scripts directories are created in .paket/load, and a bunch of duplicate (but empty) directories are created at root.

![paket-load-scripts-repro](https://user-images.githubusercontent.com/1795462/40429729-604a4754-5e71-11e8-9e6f-8cfcdfbee25e.gif)

### Known workarounds

Delete the empty directories.

**Comment by pmbanka** [comment]
I noticed the same happens on Windows.

**Comment by matthid** [comment]
whoops... happened probably due to some refactoring for fake :/
