### ISSUE TITLE
Ignore projects in hidden directories (starting with a dot)

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Paket#3225]
...or at least in the `.fable` directory. This is because Fable 2 copies the sources of the referenced packages into a hidden folder in the repository named `.fable`. This is done to avoid problems with most JS tooling which usually expects all sources (and F# files are also considered sources of JS project thanks to Webpack & fable-loader) to be in the hierarchy defined by the `package.json` file.

Right now Paket checks the projects in this `.fable` directory too, so if I run `.paket/paket.exe install` I get warnings like the following:

```
 - paket.references -> .fable/Fable.Elmish.1.0.3/Fable.Elmish.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fable.Elmish.1.0.3/Fable.Elmish.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fable.Elmish.Browser.1.0.0/Fable.Elmish.Browser.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fable.Elmish.Browser.1.0.0/Fable.Elmish.Browser.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fable.Elmish.Debugger.1.0.1/Fable.Elmish.Debugger.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fable.Elmish.Debugger.1.0.1/Fable.Elmish.Debugger.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fable.Elmish.HMR.1.0.0/Fable.Elmish.HMR.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fable.Elmish.HMR.1.0.0/Fable.Elmish.HMR.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fable.Elmish.React.1.0.3/Fable.Elmish.React.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fable.Elmish.React.1.0.3/Fable.Elmish.React.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fable.PowerPack.1.5.0/Fable.PowerPack.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fable.PowerPack.1.5.0/Fable.PowerPack.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fable.React.3.1.2/Fable.React.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fable.React.3.1.2/Fable.React.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fulma.1.0.0-beta-022/Fulma.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fulma.1.0.0-beta-022/Fulma.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fulma.Elmish.0.1.0-beta-010/Fulma.Elmish.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fulma.Elmish.0.1.0-beta-010/Fulma.Elmish.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Fulma.Extensions.1.0.0-beta-016/Fulma.Extensions.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Fulma.Extensions.1.0.0-beta-016/Fulma.Extensions.fsproj does not reference FSharp.Core.
 - paket.references -> .fable/Thoth.Json.1.0.0/Thoth.Json.fsproj
F# project /Users/alfonsogarciacaronunez/dev/fulma-demo/.fable/Thoth.Json.1.0.0/Thoth.Json.fsproj does not reference FSharp.Core.
 - src/paket.references -> src/Demo.fsproj
```

**Comment by matthid** [comment]
Is the reason that you have a paket.references in a parent directory or alongside the .fable directory? I’m so sad we never got rid of this behavior. It is also a performance bottleneck independent of this issue.

I vote for release paket 6 and change this stuff...

**Comment by matthid** [comment]
Also this behavior can be a blocker for adoption, for example if you introduce fake and manage it with paket. In this scenario you have a paket.reference in your root and paket will rewrite/format all project files. I have seen that already creating questions...

**Comment by forki** [comment]
I think we should ignore hidden folders.
Matthias Dittrich <notifications@github.com> schrieb am Sa., 26. Mai 2018,
07:05:

**Comment by alfonsogarciacaro** [comment]
Thanks @forki!

@matthid There's indeed a `paket.references` in the repo root (same level as `.fable` folder) because @MangelMaxime likes to have a *.proj file there to be able to use dotnet CLI tool commands from the repo root :wink:

**Comment by matthid** [comment]
Yes I really think we should fix that. And honestly I'm not sure how many people this would actually break. Probably not that many....
