### ISSUE TITLE
dependecies for paket pack

### ISSUE THREAD

**Issue by keroiber** [fsprojects/Paket#3227]
### Description

Dependency resolution for paket pack and type file paket.template does not work as expected
When defining the version with the LOCKED syntax always a fixed version is written in the nuspec file, regardless of the range specified.

### Repro steps

1. Using
`SomeLib ~> 2.11.0`
results in `version="[2.11.0,2.12.0)"`

2. When locked is (2.11.0-alpha8) using
`SomeLib ~> LOCKED:[3]`
results in `version="[2.11.0]"`

### Expected behavior

I would expect that both variants result in `version="[2.11.0,2.12.0)"`

**Comment by viktor-svub** [comment]
Mae culpa, expected to be fixed via PR #3229
