### ISSUE TITLE
VS's Package Management Console is broken

### ISSUE THREAD

**Issue by M0ns1gn0r** [fsprojects/Paket#3231]
### Description

The changes introduced in commit 833b36c13 broke the _Package Management Console_ in Visual Studio.

```
An error occurred while reading file 'D:\Work\PaketVersionTest\packages.config': Invalid package version for package id 'EntityFramework': '[6.2.0]'
```

The brackets syntax seems to be not supported by NuGet.

### Repro steps

1. Create `paket.dependencies` with the following content:
```
framework: net472
redirects: on

source https://api.nuget.org/v3/index.json

nuget EntityFramework ~> 6.2 version_in_path: true
```

2. Create a classic .csproj and put `EntityFramework` to its `paket.references`.

3. Execute `paket install`.

### Expected behavior

1. The created `packages.config` contains:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.2.0" />
</packages>
```

2. The _Package Management Console_ window can be opened, no errors are shown.

### Actual behavior

1. The created `packages.config` contains:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="[6.2.0]" />
</packages>
```

2. An error is displayed after opening the _Package Management Console_ window.

**Comment by forki** [comment]
But the packages.config is correct. Isn't it?

**Comment by 0x53A** [comment]
This also breaks unit test integration (e.g. xunit.runner.visualstudio)

**Comment by ben-reilly** [comment]
Do you folks have any updates on this? As far as I can tell and can verify locally, we just need to remove the square brackets from the version string in `packages.config`.

**Comment by forki** [comment]
Yes, we would accept a fix. I can't do it myself right now, since I'm on
longer vacation.

ben-reilly <notifications@github.com> schrieb am Do., 14. Juni 2018, 01:07:

**Comment by inosik** [comment]
See #3253.

**Comment by ben-reilly** [comment]
@inosik That looks right to me. Thanks for putting it together.

For others, here's the reference: https://docs.microsoft.com/en-us/nuget/reference/package-versioning

It appears that although it's possible to specify ranges in project and .nuspec files, and even in the "allowedVersions" attribute in `packages.config`, only exact versions are permitted in the "version" attribute in `packages.config`. So being able to read ranges is fine for those other files, but we should only be writing exact versions to `packages.config`.
