### ISSUE TITLE
redirects: force doesnt work anymore

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#3240]
(moved from https://github.com/fsprojects/Paket/issues/2573)

As far as I know, MSBuild also checks the app.config and only complains if there is no existing redirect.

Manual redirects in app.config and ``AutoGenerateBindingRedirects`` exclude each other - if the property is set, then all manual ones are ignored and overwritten on build.

Until now I've always tried to use forced redirects from paket, because then I can copy-paste an app.config file from source control to prod. Otherwise I'd need to make sure to insert the redirects block back first.

Maybe change this feature to
``redirects: [off|true|force|auto]`` ?

As it is currently implemented, I have set ``redirects: force``, but it doesn't insert any redirects in the app.config and adds ``<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`` to all my projects.

Which is what you want, but not exactly what I want ;D

**Comment by BlythMeister** [comment]
I have redirects true (so paket is adding redirects) and these remain on build.

According the the msbuild code (I did look at it before making this change) it will not read any binding redirects in app.config.  these are a runtime directive not compile time.

The auto generate redirects prevents msbuild from doing an assembly unification process (which even with redirects in the config) will cause build time warnings.

**Comment by BlythMeister** [comment]
Hmm reading https://github.com/Microsoft/msbuild/issues/1310#issuecomment-300155346 to get binding redirects to be created automatically there are 2 properties to set.

We want the inverse...do you have the second one also set to true in your project file?

**Comment by 0x53A** [comment]
AHA I found my issue:

``redirects: force # some comment`` removes all binding redirects
``redirects: force`` correctly adds them

...

**Comment by 0x53A** [comment]
I'm still not 100% clear regarding msbuild and ``AutoGenerateBindingRedirects`` (and I have wasted a lot of time already with that topic the last few years), but everything seems to work now, and I think I'll leave it at that.

I'll create a new issue for the comment and close this.

Thank you ;-)
