### ISSUE TITLE
Writing to dotnet folder?

### ISSUE THREAD

**Issue by et1975** [fsprojects/Paket#3243]
### Description

Paket 5.172.0 is trying to write to my dotnet SDK folder on OSX:
>Error: System.UnauthorizedAccessException: Access to the path "/usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.io.filesystem/4.3.0/paket-installmodel.cache" is denied.

Why would paket try to write to my root-only folder?

### Repro steps

`paket update dotnet-fable`

### Expected behavior

Shouldn't try/complain.

### Actual behavior

Stack trace for some, but not all packages.

### Known workarounds

It doesn't seem to be a critical failure, it's just complaining on every attempt at package manipulation.

**Comment by forki** [comment]
uh that's unfortunate and like due to #3242 
I unlisted that version (without revert)

@csmager can you please take a look? I'm about to go on vacation for 3 weeks, but @matthid can merge and release fixes.

**Comment by csmager** [comment]
Will do. This is one of the reasons I didn’t reuse the cache stuff, but I’ve obviously missed something!

**Comment by forki** [comment]
thank you. just let @matthid know. he knows the drill :P

**Comment by csmager** [comment]
A find doesn't give any hits for `paket-installmodel.cache`. If you happen to know where and why it's generated that might be helpful! Will keep looking...

**Comment by csmager** [comment]
@et1975 could you provide a more detailed repro? Ideally provide a `paket.dependencies` file. I've been doing installs and updates the last 5 mins and I'm yet to hit any issues.

**Comment by et1975** [comment]
@csmager Seeing how 5.172.0 is now delisted, I don't think I can give you anything reproducible. However, the stack trace starts with:
>  at System.IO.File.WriteAllText (System.String path, System.String contents) [0x00007] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at Paket.NuGet.ofDirectory (System.String targetFolder)

**Comment by csmager** [comment]
I can have a look in there. I'm aware it's delisted, but I'd've thought it would still be cached on the machine you saw the problem on?

**Comment by csmager** [comment]
OK, it looks like in `NuGet.ofDirectory` we save some sort of cache of the results of enumerating the files/folders within:
https://github.com/fsprojects/Paket/blob/3d9e4b5110d4baafa2e716b402e6216a2729688f/src/Paket.Core/Dependencies/NuGet.fs#L116-L144

Line 142 is where it's failing. I'll look into it, I guess we probably need to skip this where we don't have permission to do that.
