### ISSUE TITLE
Paket (in library and console) add reference for System.Windows.Forms / WindowsBase 

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket#3246]
### Description
`paket 5.172.1`

We're having jobs every night that removes `paket.lock` and run `paket install` then `fake build`
Most of our libs are `Owin` or `technology/framework` agnostic
We also have few sample bootstrapping WebApi within Console app

### Actual behavior

I'm starting to see diff like this :

```
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.2'">
      <ItemGroup>
        <Reference Include="System.Windows">
          <Paket>True</Paket>
        </Reference>
        <Reference Include="System.Windows.Forms">
          <Paket>True</Paket>
        </Reference>
        <Reference Include="WindowsBase">
          <Paket>True</Paket>
        </Reference>
        <Reference Include="System.Reactive">
          <HintPath>..\..\packages\System.Reactive\lib\net46\System.Reactive.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

### Expected behavior

It should not start adding GAC reference in csproj, especially
`WindowsBase`
`System.Windows.Forms`
`System.Windows`

### Known workarounds

Manually delete them, in EACH csproj one by one
This one is trully fearsome

I would recommand Paket BLOCKING the `paket install` with a `Yes/No` question (with an opt out like --force)
This prompt explain the WHY it is adding a GAC reference ... especially big one like this ...

**Comment by forki** [comment]
Why would you delete them? It's what the package defines.

TeBeCo <notifications@github.com> schrieb am Mo., 11. Juni 2018, 09:59:

**Comment by tebeco** [comment]
My bad, this is on me

It seems that the major `4.x` from System.Reative on `netcoreapp2.0` dependens on [System.Runtime.InteropServices.WindowsRuntime](https://www.nuget.org/packages/System.Runtime.InteropServices.WindowsRuntime/)

and my guess is that this is the reason

**Comment by tebeco** [comment]
Also we just "Updated" from `3.1.1` to `4.0.0` so i guess we probably don't need it at all
We do not have the same behavior with the same solution but without using `paket`

Also i cannot publish a repository as a reprostep asap, it might take lots of time

**Comment by inosik** [comment]
This is in the `.nuspec` file of System.Reactive 4.0.0:

``` xml
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Windows" targetFramework=".NETFramework4.6" />
      <frameworkAssembly assemblyName="System.Windows.Forms" targetFramework=".NETFramework4.6" />
      <frameworkAssembly assemblyName="WindowsBase" targetFramework=".NETFramework4.6" />
    </frameworkAssemblies>
```

So Paket works as expected here. I just wonder why System.Reactive depends on some Windows-specific assemblies. Version 3.1.1 doesn't depend on them.

**Comment by tebeco** [comment]
thx i missed tha, i was tired ... my bad

i’ll check the lib and console using netcoreapp / netstandard because it leaks in projects.assets.json as i don’t use paket ... closing this one
