### ISSUE TITLE
Paket generates wrong path in load script

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Paket#3247]
### Description

Paket version 5.172.2

We have a FAKE 4 script referencing a load script generated by Paket, but it contains one slightly wrong path that breaks the build at one point with `System.IO.FileNotFoundException: Die Datei oder Assembly "Microsoft.Rest.ClientRuntime.Azure, Version=3.0.0.0, ` error.

### Repro steps

Unfortunately the project is not public so I cannot add a link but the conditions are more or less the following. In **paket.dependencies**, we have:

```
group Build
  source https://nuget.org/api/v2
  generate_load_scripts: true
  framework: net461
  
  nuget FAKE
  nuget Microsoft.Azure.DocumentDB >= 1.12
  nuget Microsoft.Rest.ClientRuntime.Azure == 3.0.0
  nuget Microsoft.Azure.Management.ResourceManager.Fluent 1.4.1
  github CompositionalIT/fshelpers src/FsHelpers/ArmHelper/ArmHelper.fs
```

Then in the **build script**:

```fsharp
#r @"packages/build/FAKE/tools/FakeLib.dll"
#load @".paket\load\net461\Build\build.group.fsx"
      @"paket-files\build\CompositionalIT\fshelpers\src\FsHelpers\ArmHelper\ArmHelper.fs"
```

The paket-generated **build.group.fsx** file looks like:

```fsharp
#r "../../../../packages/build/Microsoft.Azure.DocumentDB/lib/net45/Microsoft.Azure.Documents.Client.dll" 
#r "../../../../packages/build/Microsoft.Rest.ClientRuntime/lib/net452/Microsoft.Rest.ClientRuntime.dll" 
#r "../../../../packages/build/Microsoft.IdentityModel.Clients.ActiveDirectory/lib/net45/Microsoft.IdentityModel.Clients.ActiveDirectory.dll" 
#r "../../../../packages/build/Microsoft.IdentityModel.Logging/lib/net451/Microsoft.IdentityModel.Logging.dll" 
#r "../../../../packages/build/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll" 
#r "../../../../packages/build/Microsoft.Rest.ClientRuntime.Azure/lib/net45/Microsoft.Rest.ClientRuntime.Azure.dll" 
#r "../../../../packages/build/Microsoft.Rest.ClientRuntime.Azure.Authentication/lib/net461/Microsoft.Rest.ClientRuntime.Azure.Authentication.dll" 
#r "../../../../packages/build/Microsoft.IdentityModel.Tokens/lib/net451/Microsoft.IdentityModel.Tokens.dll" 
#r "../../../../packages/build/Microsoft.IdentityModel.Clients.ActiveDirectory/lib/net45/Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll" 
#r "../../../../packages/build/Microsoft.Azure.Management.ResourceManager.Fluent/lib/net452/Microsoft.Azure.Management.ResourceManager.Fluent.dll" 
#r "Microsoft.CSharp" 
#r "System" 
#r "System.Runtime.Serialization" 
#r "System.Xml" 
#r "System.Core" 
#r "System.Net" 
#r "System.Net.Http" 
#r "System.Net.Http.WebRequest" 
```

However, line 6 is wrong. It should be:

```
#r "../../../../packages/build/Microsoft.Rest.ClientRuntime.Azure/lib/net452/Microsoft.Rest.ClientRuntime.Azure.dll" 
```

That is, `lib/net452` instead of `lib/net45`.
### Known workarounds

Add references manually

**Comment by matthid** [comment]
So the path it generates doesn't even exist?
Have you tried clearing your nuget cache (in particular the .nuget folder in HOME)?

**Comment by alfonsogarciacaro** [comment]
No, the path doesn't exist. I haven't tried clearing the nuget cache, but please note this problem happened in several machines and also the packages are being installed locally in the `packages` folder within the repo.

**Comment by robkuz** [comment]
During the last few month we had these issues on and off (without really pin pointing it).
My gut feeling for now is that paket (or fake?) are far to agressive in their caching strategies.

**Comment by matthid** [comment]
@robkuz Yes we have very aggressive caching everywhere... Did you use the `packages` folder as well?

**Comment by smoothdeveloper** [comment]
One thing to try is to erase the `.paket/load` folder as paket might not generate the scripts again if some exist in that location.

If the Microsoft.Rest.ClientRuntime.Azure somehow changed their layout / supported target framework, the matching load script could be outdated.

@alfonsogarciacaro could you confirm if it also reproduces when you `paket restore` after deleting `.paket/load` folder?

**Comment by forki** [comment]
Did you check that you gitignore paket-files folder?

Gauthier Segay <notifications@github.com> schrieb am Di., 12. Juni 2018,
03:42:

**Comment by alfonsogarciacaro** [comment]
Yes, we're ignoring `paket-files`. I just tried restoring again after deleting `.paket/load`,  `packages` and `paket-files` (a new restore wasn't triggered until I removed paket-files) and it seems to be fine now. The path in the load script is the same as before, but it's the correct one now.

It may be that I mistook yesterday the `Microsoft.Rest.ClientRuntime.Azure` package with `Microsoft.Rest.ClientRuntime` (the second one has the `lib/net452` subfolder). I removed the `packages` folder for the new restore, so I'm not sure now :/

I'll close the issue for now, and I'll reopen it if I get more info. Thanks a lot for your help and sorry for the hassle!

**Comment by forki** [comment]
Yes the cache file in paket-files is likely a problem here. If someone
deletes load scripts but not the cache file then paket still thinks
everything is up to date

Alfonso Garcia-Caro <notifications@github.com> schrieb am Di., 12. Juni
2018, 13:02:
