### ISSUE TITLE
Is there a fix for log path names?

### ISSUE THREAD

**Issue by pshrosbree** [fsprojects/Paket#3283]
Is there a warkaround for this this error?

```
C:\src\appcenter\lib-dotnet-appcenter\.paket\Paket.Restore.targets(210,5): error : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

This was raised in #1331, which is closed.
I am using version 5.173.4.

**Comment by forki** [comment]
For new project system you can try "storage:none" and for old project system you need to move the repository to a shorter path.
We won't fix this, since it is a windows limitation

**Comment by pshrosbree** [comment]
Thanks. I'll give it whirl. Fortunately, I am using the new project system.
