### ISSUE TITLE
System.Memory restrictions cause invalid delimiter in paket.lock file

### ISSUE THREAD

**Issue by spaceywolfi** [fsprojects/Paket#3291]
### Description

When i run "paket update", my packages are updated. However when i run "dotnet restore" afterwards I get the following error:
```bash
 dotnet restore
  Paket version 5.142.0
  Performance:
   - Runtime: 2 seconds
  Paket failed with
  -> Error during parsing of '/home/TestProject/paket.lock'.
  -> Could not parse 'framework: restriction: || (&& (< net46) (< netcoreapp2.1) (>= netstandard2.0)) (>= netcoreapp2.0) (>= uap10.1)' as key/value pairs.
  -> invalid delimiter at position 22
/home/user/TestProject/.paket/Paket.Restore.targets(78,5): error MSB3073: The command "mono --runtime=v4.0.30319 "/home/user/TestProject/.paket/paket.exe" restore" exited with code 1. 
```

I looked into the paket.lock file and searched for the restriction. 
Before updating the packages the restrictions of Microsoft.Win32.Registry (4.4) are:
```bash
    Microsoft.Win32.Registry (4.4) - restriction: >= netcoreapp2.0
      Microsoft.NETCore.Platforms (>= 2.0) - restriction: >= netcoreapp2.0
      System.Security.AccessControl (>= 4.4) - restriction: || (&& (>= monoandroid) (< netstandard1.3)) (>= monotouch) (&& (< net46) (>= netstandard2.0)) (>= net461) (>= netcoreapp2.0) (>= xamarinios) (>= xamarinmac) (>= xamarintvos) (>= xamarinwatchos)
      System.Security.Principal.Windows (>= 4.4) - restriction: || (&& (>= monoandroid) (< netstandard1.3)) (>= monotouch) (&& (< net46) (>= netstandard2.0)) (>= net461) (>= netcoreapp2.0) (>= xamarinios) (>= xamarinmac) (>= xamarintvos) (>= xamarinwatchos)
   ```
After updating the packages the restrictions change and a new package called System.Memory is added:

```bash
  Microsoft.Win32.Registry (4.5) - restriction: >= netcoreapp2.0
      System.Memory (>= 4.5) - restriction: || (&& (< net46) (< netcoreapp2.1) (>= netstandard2.0)) (>= netcoreapp2.0) (>= uap10.1)
      System.Security.AccessControl (>= 4.5) - restriction: || (>= monoandroid) (>= monotouch) (&& (< net46) (>= netstandard2.0)) (>= net461) (>= netcoreapp2.0) (>= netcoreapp2.1) (>= xamarinios) (>= xamarinmac) (>= xamarintvos) (>= xamarinwatchos)
      System.Security.Principal.Windows (>= 4.5) - restriction: || (>= monoandroid) (>= monotouch) (&& (< net46) (>= netstandard2.0)) (>= net461) (>= netcoreapp2.0) (>= netcoreapp2.1) (>= xamarinios) (>= xamarinmac) (>= xamarintvos) (>= xamarinwatchos)
    
```
The restriction of System.Memory seems to be causing this error for me.

I am not sure where the best place is to submit this issue, as I am not sure if this has something to do with Paket, System.Memory, Microsoft.Win32.Registry or mono, so please tell me if i am in the wrong repository :)

### Repro steps
1. Use a linux distro ( i suspect it could have something todo with mono? or/and running linux), i'm an up-to date Manjaro arch distribution 
```bash
uname -a
Linux omega 4.14.52-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:24:31 UTC 2018 x86_64 GNU/Linux
```

2. Install a template that still uses an older version of Microsoft.Win32.Registry such as the fable-elmish-react template
```bash
dotnet new fable-elmish-react -n awesome -lang f#
```
3. Follow the template instructions to get everything to work, using just the template i do not get any issues.
```bash
cd src
dotnet restore
```
4. Go back to the root directory of the TestProject and run paket update. All packages update how they are meant to
```bash
paket update
```

5. Go to Src and run dotnet restore, I then get this error:
```bash
 dotnet restore
  Paket version 5.142.0
  Performance:
   - Runtime: 2 seconds
  Paket failed with
  -> Error during parsing of '/home/TestProject/paket.lock'.
  -> Could not parse 'framework: restriction: || (&& (< net46) (< netcoreapp2.1) (>= netstandard2.0)) (>= netcoreapp2.0) (>= uap10.1)' as key/value pairs.
  -> invalid delimiter at position 22
/home/user/TestProject/.paket/Paket.Restore.targets(78,5): error MSB3073: The command "mono --runtime=v4.0.30319 "/home/user/TestProject/.paket/paket.exe" restore" exited with code 1. 
```

### Expected behavior

I should be able to update my packages and run dotnet restore without any errors

### Actual behavior

I get an error when running dotnet restore telling me that there is an invalid delimiter

**Comment by inosik** [comment]
Your version of Paket is pretty outdated (5.142.0) and it obviously can't parse this restriction.

Can you try to run `PAKET_VERSION=5.174.2 dotnet restore` once to update Paket? I wonder why the bootstrapper didn't update Paket itself.

**Comment by spaceywolfi** [comment]
thank you @inosik!
so the command   ```PAKET_VERSION=5.174.2 dotnet restore```, it still used the old version.
however i checked the .paket folder and realized that the elmish template i was using (https://github.com/elmish/templates/blob/master/.paket/paket.exe) did not use the bootstrap version of paket. and therefore it did not update. I now replace the paket.exe file with the latest bootstrap version and it seems to work now :+1:

**Comment by inosik** [comment]
The template uses Pakets ["magic mode"](https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode), that is the bootstrapper renamed to `paket.exe`.

The bootstrapper in the template should be fine, it's the version with the fixed TLS configuration. I use a globally installed 5.142.0 on my machine as well.

**Comment by spaceywolfi** [comment]
@inosik the paket.exe file in the template is 8.02 MB this is why i think that it is not the bootstrapped version, but maybe im wrong

**Comment by inosik** [comment]
You're right, I only looked at the commit message in the repository.
