### ISSUE TITLE
restore force does not properly clear FileListAbsolute

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/Paket#3308]
### Description

````paket restore -f```` does not clear obj\release\netstandard2.0\<project name>.fsproj.FileListAbsolute.txt, but rather it appears to rely on appending to the file. 

For most purposes this does not seem to cause problems, but some corner cases will fail. 
Specifically, the build target in my build script works, but it fails in doc generation looking for the wrong path to document templates.

### Repro steps

I sync my source repos between 2 machines. The root paths on the machines differ.

paket restore on machine 1

go to machine 2, ````paket restore -f````

### Expected behavior

All files should be initialized for machine 2

### Actual behavior

Paths to both machine 1 and machine 2 are in file

````
<machine 1 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.deps.json
<machine 1 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.dll
<machine 1 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.pdb
<machine 1 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.xml
<machine 1 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.fsprojAssemblyReference.cache
<machine 1 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.dll
<machine 1 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.xml
<machine 1 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.pdb
<machine 2 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.deps.json
<machine 2 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.dll
<machine 2 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.pdb
<machine 2 root>\DependentTypes\src\DependentTypes\bin\Release\netstandard2.0\DependentTypes.xml
<machine 2 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.fsprojAssemblyReference.cache
<machine 2 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.dll
<machine 2 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.xml
<machine 2 root>\DependentTypes\src\DependentTypes\obj\Release\netstandard2.0\DependentTypes.pdb
````

### Known workarounds
 
Manually clear obj folders.

**Comment by forki** [comment]
we don't create or touch the `*.FileListAbsolute.txt*` at all in paket - @davkean should we?

@jackfoxy can you please upload a zip with a repro - all files just before you call restore -f? thanks

**Comment by jackfoxy** [comment]
[DependentTypes.zip](https://github.com/fsprojects/Paket/files/2220030/DependentTypes.zip)
Uploaded

**Comment by forki** [comment]
there are no *FileListAbsolute* in the zip

**Comment by jackfoxy** [comment]
Sorry, I misunderstood your request. You are right. FileListAbsolute must be an artifact of dotnet build. 
In preparing a zip as you want it is now way too big for github. I'll follow-up with a bug report to dotnet build.

**Comment by davkean** [comment]
Any such bug should be against http://github.com/microsoft/msbuild. The behavior looks deliberate (that FileListAbsolute contains all produced files) - so you might want to provide a repro of what the actual issue this is causing.

**Comment by jackfoxy** [comment]
@davkean  It's hard to imagine why you would want files listed from a prior build that are no longer produced in the current build. Anyway, you are right. It is a subsequent documentation generation step that is reading the file list and incorrectly consuming the first matching file path, which happens to be from a prior build on a different machine. Any consumer of this file list should be aware, and look for matching files from the bottom up, instead of top down, to ensure only current file paths are found.

**Comment by jackfoxy** [comment]
Come to think of it, bottom up is also an incorrect strategy. The right thing to do is test for path existence, not just pattern matching.

**Comment by davkean** [comment]
FileListAbsolute is an attempt at listing files produced in past and future builds so that Clean will clean them up. It is not consumed (only produced) during a normal build, you can see its usage here: https://github.com/Microsoft/msbuild/blob/b3f9eeab651c92bade6e4f64d11b59aa39e149cb/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5011. If you have a bug where the documentation generation step is getting the wrong file, it's unlikely to be from this file.
