### ISSUE TITLE
Target specific feeds against specific dependencies

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#331]
The current implementation looks at e.g. all nuget sources across all nuget dependencies e.g.: -

```
source http://nuget.org/api/v2
source http://myprivatefeed
source http://myotherprivatefeed

nuget My.Package1
....
nuget My.Package24
nuget My.Package25
```

In the example above, My.Package24 goes against "privatefeed" and My.Package25 against "myprivatefeed". However, there is no way to indicate that in the dependencies file. As a result, updates etc. for any given package search across all feeds. It would be great if you could do something like: -

```
source http://nuget.org/api/v2
nuget My.Package1
....
nuget My.Package23

source http://myprivatefeed
nuget My.Package24

source http://myotherprivatefeed
nuget My.Package25
```

Where only packages 1-23 are searched against nuget.org, My.Package24 against myprivatefeed and My.Package25 against myotherprivatefeed.

**Comment by forki** [comment]
Closing old issue. This can be done via groups
