### ISSUE TITLE
Paket doesn't seem to restrict library versions of dependencies

### ISSUE THREAD

**Issue by ZenoArrow** [fsprojects/Paket#3311]
### Description

When using a restriction in a paket.dependencies/paket.lock file, would expect this to apply to the packages that are downloaded by Paket.

### Repro steps

1. paket.dependencies file:

```
framework: >= net40
source https://www.nuget.org/api/v2
nuget Microsoft.TeamFoundationServer.Client
```

2. After install packages, check folder packages\Newtonsoft.Json\lib . Will currently see that 9 versions of this library have been obtained by Paket, including net20 and net35.

### Expected behavior

In the example listed above, would expect the net20 and net35 versions of the Newtonsoft.Json library to be excluded (possibly others as well, but it may be more tricky to determine whether the 'netstandard' and 'portable' versions of the library should be excluded).

### Actual behavior

The net20 and net35 libraries are included, despite the restriction of framework: >= net40 existing in the paket.dependencies and paket.lock files.

### Known workarounds

No workarounds that I'm aware of.

**Comment by forki** [comment]
we don't filter during extraction of the package. we filter the creation of XML reference tags in the csproj
