### ISSUE TITLE
More redirects are defined when using redirects:force (yml) than --redirects (CLI)

### ISSUE THREAD

**Issue by rabrahamOpti** [fsprojects/Paket#3335]
### Summary

I see more binding redirects defined when I put the `redirects: force` flag in `paket.dependencies` than I do when I use the `--redirects` flag on the CLI `install` command. I'm not sure if this is a bug or expected behavior. 

I've attached three app config files, once generated with the CLI install command without any flags (`PlainInstall_app.config`), one with the CLI `--redirects` flag (`CLIRedirects_app.config`), and one with the paket.dependencies `redirects: force` flag (`Flag_app.config`). 

### Description

I have a code base across multiple repos, but only want paket to set up binding redirects in one of them. I routinely rebuild `paket.lock` using the CLI `install` command, and often forget to use the `--redirects` flag in the repo that needs it, wasting some time.

I recently found out that I could add a flag that repo's `paket.dependencies` file that should produce the same behavior as using the `--redirects` flag on the CLI `install` command.

Using a merge tool, I see PlainInstall.app.config doesn't have binding redirects set up, as expected. The other two do, but, interestingly, the config file generated when I used the `redirects: force` flag in paket.dependencies has MORE assembly redirects defined than the one generated using the `--redirects` flag on the CLI `install` command.

### Repro steps

I'm afraid I don't understand binding redirects, or how paket manages them, well enough to come up with a simple reproduction example, but I have attached three versions of a config file from one of my projects. FYI: I removed a token from them.

### Expected behavior

I'd expect the resulting app.config to be identical between using `paket install --redirects` and  installing without `--redirects` where the `redirects: force` flag in `paket.dependenncies` is set.

### Actual behavior

There are more binding redirects defined when I use `redirects: force` than when I don't have that flag in the yml, and use the `--redirects` flag on the `install` command.

### Known workarounds

None. Not sure if this is a bug either.

[Flag_app.config.txt](https://github.com/fsprojects/Paket/files/2290251/Flag_app.config.txt)
[PlainInstall_app.config.txt](https://github.com/fsprojects/Paket/files/2290252/PlainInstall_app.config.txt)
[CLIRedirects_app.config.txt](https://github.com/fsprojects/Paket/files/2290253/CLIRedirects_app.config.txt)

**Comment by ghmoore** [comment]
paket add Microsoft.Toolkit.Uwp.DeveloperTools --version 4.0.0

**Comment by 0x53A** [comment]
In paket.dependencies, you can either specify on or force.

On tries to be smart and only adds required redirects.

Force says fuck it, and just adds redirects for all assemblies.

I would assume that the cli flag is equivalent to redirects: on.

Can you try that?

**Comment by rabrahamOpti** [comment]
Yup, looks adding `redirects: on` to `paket.dependencies` results in the same behavior as using the `--redirects` flag on the `install` command (except for an extra line in `paket.lock` that reads `REDIRECTS: ON`)

This is what I need, and the behavior's explained. Closing this issue, thanks!
