### ISSUE TITLE
RunCodeAnalysis task fails when using paket

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#3339]
### Description

I don't understand what's going on. I'm migrating a project which already uses paket to to .NET Standard 1.5. It fails to build but works fine when referencing packages using csproj instead of paket.references.

### Repro steps

Here's a distilled projects from my solution. I recreated it from scratch and simply copied sources over.

[runcodeanalysis.zip](https://github.com/fsprojects/Paket/files/2300653/runcodeanalysis.zip)

### Expected behavior

Should build successfully

### Actual behavior

I get these errors:

```
Target RunCodeAnalysis:
    Running Code Analysis...
    * Could not load file: 'C:\path\bin\Debug\netstandard1.5\JsonLD.Entities.dll'.
    * Analysis was not performed; at least one valid rules assembly and one valid
    target file must be specified.
    * 1 total analysis engine exceptions.
    MSBUILD : error : CA0055 : * Could not load file: 'C:\Projects\github\wikibus\JsonLD.Entities\src\JsonLD.Entities\bin\Debug\netstandard1.5\JsonLD.Entities.dll'.
    MSBUILD : error : CA0058 : Could not locate the framework assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
    MSBUILD : error : CA0052 : No targets were selected.
    Code Analysis Complete -- 3 error(s), 0 warning(s)
```

### Known workarounds

I checked the output dlls in both cases and both reference version `4.0.20` of System.Runtime. It would seem that the code analysis task is not executed when paket is not used. Disabling code analysis for the .NET standard target seems to do the trick for now.

```xml
<PropertyGroup Condition="'$(TargetFramework)' == 'netstandard1.5'">
  <RunCodeAnalysis>false</RunCodeAnalysis>
</PropertyGroup>
```

**Comment by ghmoore** [comment]
paket add Microsoft.Toolkit.Uwp.DeveloperTools --version 4.0.0

**Comment by ghmoore** [comment]
paket add Microsoft.Toolkit.Uwp.DeveloperTools --version 4.0.0

**Comment by ghmoore** [comment]
paket add Microsoft.Toolkit.Uwp.DeveloperTools --version 4.0.0

**Comment by ghmoore** [comment]
paket add Microsoft.Toolkit.Uwp.DeveloperTools --version 4.0.0

**Comment by ghmoore** [comment]
paket add Microsoft.Toolkit.Uwp.DeveloperTools --version 4.0.0

**Comment by tpluscode** [comment]
Ok, forget it. The issue was actually with one of the dependencies
