### ISSUE TITLE
Referencing a GitHub repository and its Files

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#334]
When referencing an entire repository like `github hakimel/reveal.js:2.6.2`: Is it possible to reference Files of it in a project via `paket.references`?

After reading http://fsprojects.github.io/Paket/github-dependencies.html my impression was I could check out a repo containing a *.csproj, reference the *.csproj and trigger a BuildAction.
Is that at all possible? 

Or am I supposed to reference them manually into my project?

**Comment by forki** [comment]
Closing old issue. Manual referencing is the way to go.
