### ISSUE TITLE
Paket changes casing of NuGet package id in some cases

### ISSUE THREAD

**Issue by sanderaernouts** [fsprojects/Paket#3340]
### Description

When I run `paket install` the casing of some of my NuGet packages is changed.

### Repro steps
Paket version is `5.176.6` but since I use the `paket.bootstrapper.exe` it may have been updated this morning.
#### Steps:

1. Run `paket install` on an existing solution
![image](https://user-images.githubusercontent.com/6184673/44457008-57eb8b80-a602-11e8-906a-0294b65ac7c5.png)

It does not happen for all packages and also not for all packages in the same way. The example here has a naming structure like Company.WordWord.redist but it is changed to company.wordword.redist. In our VSTS NuGet feed it shows as Company.WordWord.redist

### Expected behavior

Packages are updated and casing is the same as the name of the package ID as it is set in the NuGet package

### Actual behavior

Packages are updated but casing is diffrent from the package ID as it is set in the NuGet package

### Known workarounds
None

**Comment by matthid** [comment]
Do you have the package in multiple feeds? If not than this might be related with v3 fallback to v2 and the casing depends on which feed version we are using....

**Comment by OsirisTerje** [comment]
I see these changes in the csproj files for purely nuget.org packages, and they seem to change both ways.   Have not figured out yet when they go in one direction and when they go in the other.  
![image](https://user-images.githubusercontent.com/203432/47101863-7d2ffb00-d23b-11e8-8982-a267f661212c.png).  This package is only in one feed, but it is also a dependency of packages that exists in another private feed.    I can't see any reason why this should be case sensitive.

**Comment by sanderaernouts** [comment]
What command do we need to run to produce the logs you require? It seems to happen on when updating a package. Would `paket update MoreLinq` for example provide you with the logs you need?

**Comment by sanderaernouts** [comment]
I did notice we have this in our `paket.dependencies` file:
```
...
nuget MoreLinq ~> 2.9
...
```

**Comment by sanderaernouts** [comment]
I did find these files in my `%LOCALAPPDATA%\NuGet\Cache` not sure if that explains anything but the files do contain a `PackageName` property which has the uppercase M and L in some cases. See this zip archive: [Cache files.zip](https://github.com/fsprojects/Paket/files/2491754/Cache.files.zip)

I askes @OsirisTerje to check his cache as well, he found similar files there:
![image](https://user-images.githubusercontent.com/6184673/47153072-c84f1a00-d2de-11e8-8d0f-a12646f52c3e.png)

**Comment by sanderaernouts** [comment]
@matthid any thoughts on this? I just updated a package in a solution and this happens again. What commands do you need me to run to provide you with the debug/verbose logging?

**Comment by matthid** [comment]
Like I said we need a verbose logfile from both situations. Another way might be to do a through code review on where we use the package id...

**Comment by forki** [comment]
I wonder if we want to draw the package name from lock file - if it's
already there

Matthias Dittrich <notifications@github.com> schrieb am Di., 30. Okt. 2018,
08:09:

**Comment by sanderaernouts** [comment]
@matthid it took a while but I was able to create small solution with 2 projects and only 2 packages that reproduces this issue. We could reproduce it by running `paket update` on both my machine and on @OsirisTerje machine. We both get different results for the casing of the `morelinq` package.

# Steps to reproduce:
1. pull down https://github.com/sanderaernouts/paket-casing-repro.git
2. run paket update NUnit3TestAdapter --verbose --log-file paket.update.log

I created the solution so on my machine there are no casing changes:
![image](https://user-images.githubusercontent.com/6184673/48126213-de6a4d80-e280-11e8-856c-e246e9702808.png)

On Terje's machine it paket does make casing changes:
![image](https://user-images.githubusercontent.com/6184673/48126343-2a1cf700-e281-11e8-84b0-8221dd7d8925.png)

Below are the logs, I added the lock paket.files for both situations as well. One set is `lowercase.*` the other set is `uppercase.*`. The lowercase set is where the change happens from `MoreLinq` to `morelinq`
[logs.zip](https://github.com/fsprojects/Paket/files/2556993/logs.zip)

The problem here is that we still have a lot of old style CSPROJ files, if `paket update` was running for one of our real solutions a lot of `.csproj` files would be modified because of this casing change. We see this happen for our own packages as well as for public nuget.org packages such as `morelinq`. Also the `packet.lock` file is changed but that is less of a pain since that is only 1 file. Because of this our PR's contain a ton of changes that aren't really changes but just casing changes paket made.

**Comment by forki** [comment]
do you already have an idea where the wrong casing is coming from?

**Comment by matthid** [comment]
@forki important is also what the 'wrong' casing is. Afaik some nuget feeds are case sensitive and the correct answer depends on what we get from the feed

**Comment by OsirisTerje** [comment]
@forki @matthid  Does it depend **only*' on the feed?  The name can appear in a package nuspec dependency list, and can have a different casing there, from how it is by itself in the feed

**Comment by sanderaernouts** [comment]
In this case we are both using exactly the same `paket.dependencies` file and we only use packages from nuget.org so I would expect we get the same name (and casing of the name) in both cases.

Initially, I suspected that the problem might by that we have `MoreLinq` in our `paket.dependencies` file and that this is the casing that was used by paket before and that a change to paket caused this behaviour to be different. But that would mean it should stabilize after some time. We now see different behaviour on different machines. 

One thing I can think of that is different on each machine is the nuget caches and maybe paket caches if it has its own. Isn't it possible to use the actual package id from the package metadata that way the casing should only change if the casing of the package id in the nuget package metadata has changed.

**Comment by forki** [comment]
can you please both run `paket clear-cache` and check again?

**Comment by sanderaernouts** [comment]
Yes, but if we do that we may no longer be able to reproduce the issue if further fixing is required. Isn't there a way to list out the cached content or some folder(s) we need to look into to validate our suspicion that this is the issue before we clear the caches?

**Comment by OsirisTerje** [comment]
I cleared the cache.  No difference. Same diff.

**Comment by forki** [comment]
I really wonder where it's coming from. As @matthid said we ask nuget feed for it.

**Comment by sanderaernouts** [comment]
I cleared my caches as well, still the same result.

**Comment by OsirisTerje** [comment]
@sanderaernouts Perhaps the best way is to clone the source, build a debug version and try to step through.  We have a consistent repro, so that might be the most easy  way to get to the bottom of this.

**Comment by sanderaernouts** [comment]
@OsirisTerje good point, will give that a try and see if can at least find out where the uppercase name is comming from.

**Comment by sanderaernouts** [comment]
@forki/@matthid I am able to debug locally now with the latest `master` branch. But I'm unfamilliar with F# and with the Paket codebase. Do you have any pointers as to what to debug?

**Comment by sanderaernouts** [comment]
It seems that the problem disappears when you run follow these steps:
1. Close all VS instances 
2. Run `paket clear-cache --clear-local`
3. Run `paket install`

**Comment by Flohack74** [comment]
I have the same issue here with an SQLite dependency:
![image](https://user-images.githubusercontent.com/16186470/58075142-39bdb680-7ba7-11e9-8037-7aaa45bc86e3.png)

What´s very annoying is that multiple colleagues get either Camel case or lower case variant, and then its bouncing between both variants in Git. And people are afraid to commit those changes because the seem unnecessary and nobody understands whats happening. Paket version has been double-checked and is the same on all machines.

Also changes like this happen from time to time, also between colleagues with the same version, also for no obvious reason:
![image](https://user-images.githubusercontent.com/16186470/58075265-902af500-7ba7-11e9-8611-e8840fabc261.png)

**Comment by forki** [comment]
please see https://github.com/fsprojects/Paket/pull/3578

**Comment by forki** [comment]
Please upgrade and let me know if it works

**Comment by Flohack74** [comment]
Fixed for me, but I cannot speak for the OP. Thx!
