### ISSUE TITLE
Paket pack only takes on target (and ignores --build-platform)

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#3344]
### Description

I'm trying to `paket pack` a multi-target project. It almost works but only one targeteds up in the `nupkg`

### Repro steps

Create a project with multiple targets

```xml
<TargetFrameworks>net452;netstandard1.5</TargetFrameworks>
``` 

Run `paket pack`

### Expected behavior

Output of all targets should be packaged

### Actual behavior

Only the first one is included in the package.

### Known workarounds

1. I could use `dotnet pack` (if not #2370)
1. I can use `type file` in my template but it's more verbose

**Comment by jam40jeff** [comment]
@forki This should be fixed along with #3494.
