### ISSUE TITLE
Unexpected version bump on a package when running paket update

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/Paket#3347]
On F# Data we have these groups in paket.dependencies:

    group fs31
        frameworks: netcoreapp2.0, net461
        source https://api.nuget.org/v3/index.json
        nuget FSharp.Core ~> 3.1.0

    group fs40
        frameworks: netcoreapp2.0, net461
        source https://api.nuget.org/v3/index.json
        nuget FSharp.Core ~> 4.0.0

    group fs41
        frameworks: netcoreapp2.0, net461
        source https://api.nuget.org/v3/index.json
        nuget FSharp.Core ~> 4.2

And paket.lock looks like this:

       GROUP fs31
       RESTRICTION: || (== net461) (== netcoreapp2.0)
       NUGET
         remote: https://api.nuget.org/v3/index.json
           FSharp.Core (3.1.2.5)
       
       GROUP fs40
       RESTRICTION: || (== net461) (== netcoreapp2.0)
       NUGET
         remote: https://api.nuget.org/v3/index.json
           FSharp.Core (4.0.0.1)
       
       GROUP fs41
       RESTRICTION: || (== net461) (== netcoreapp2.0)
       NUGET
         remote: https://api.nuget.org/v3/index.json
           FSharp.Core (4.3.4)

After running paket update, it bumps the 4.3.4 to 4.5.2 on the fs41 group. It seems it's ignoring the `~-> 4.2` and always goes to the last version

**Comment by matthid** [comment]
That is by design, what you want is ~> 4.2.0

**Comment by ovatsus** [comment]
Thanks, that fixes it
