### ISSUE TITLE
storage: symlink fails on Linux

### ISSUE THREAD

**Issue by Dravere** [fsprojects/Paket#3368]
### Description

`storage: symlink` doesn't work under Linux (Ubuntu 18.04.1). Paket fails to create a symbolic link and throws an error about already existing files.

### Repro steps

* Have an empty folder and setup a basic paket setup.
* Have the following `paket.dependencies`:  
  ```
  storage: symlink
  source https://nuget.org/api/v2
  framework: netstandard2.0
  nuget Newtonsoft.Json
  ```
* Execute `mono .paket/paket.exe install`
* Be greeted with:  
  ```
  ...snip...
  Paket failed with
  -> symlink /home/<me>/.nuget/packages/newtonsoft.json/11.0.2 -> 
  /home/<me>/<somewhere>/packages/Newtonsoft.Json failed with error : [1] with output : 
      and error : /bin/ln: failed to create symbolic link 
  '/home/<me>/.nuget/packages/newtonsoft.json/11.0.2': File exists
  ...snip...
  ```

### Expected behavior

It should create the symlinks.

### Actual behavior

It doesn't create the symlinks.

---

Looking at the code I think you have the `source` and `target` wrong: https://github.com/fsprojects/Paket/blob/86a790131e3e8060e374620b6e3626735c3d51f1/src/Paket.Core/Common/SymlinkUtils.fs#L21

https://linux.die.net/man/1/ln

Contrary to `mklink` with `ln` you have the target and then the link name. In your parameter naming that would be `source` and then `target`.

Not sure if this affects MacOS as well since they use `ln` too.

**Comment by inosik** [comment]
That's strange, I thought I tested this feature on my Mac, but I get the same error. Paket created a symlink to the directory in the directory itself:

``` shell
$ ll ~/.nuget/packages/fake-cli/5.6.1/
total 16424
-rw-r--r--  1 ilja  staff   655B  9 Sep 12:55 [Content_Types].xml
drwxr-xr-x  3 ilja  staff    96B 21 Sep 16:52 _rels/
# This:
lrwxr-xr-x  1 ilja  staff    51B 21 Sep 16:52 fake-cli@ -> /Users/ilja/Projects/symlink-demo/packages/fake-cli
-rw-r--r--  1 ilja  staff   7,3M 21 Sep 16:52 fake-cli.5.6.1.nupkg
-rw-r--r--  1 ilja  staff    88B 21 Sep 16:52 fake-cli.5.6.1.nupkg.sha512
-rw-r--r--  1 ilja  staff   1,4K  9 Sep 12:55 fake-cli.nuspec
drwxr-xr-x  3 ilja  staff    96B 21 Sep 16:52 package/
drwxr-xr-x  3 ilja  staff    96B 21 Sep 16:52 tools/
```

**Comment by inosik** [comment]
See #3372.
