### ISSUE TITLE
Failing to restore (due timeout?)

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/Paket#3375]
I'm trying to restore https://github.com/thinkbeforecoding/UnoCore using a slow internet connection.
During downloading transitive dependencies it seems to time out and fail and Paket doesn't tell anything about why it cannot restore.
Packages it fails on:
`runtime.win10-arm.Microsoft.Net.Native.SharedLibrary`
`runtime.win10-x64.Microsoft.Net.Native.Compiler`
`runtime.win10-x86.Microsoft.Net.Native.Compiler`
I was able to restore it using PackageReference and it took several minutes for each package.

Any additional info I could provide?

**Comment by forki** [comment]
Then it should be downloaded and work in second attempt.

Eugene Auduchinok <notifications@github.com> schrieb am Do., 27. Sep. 2018,
00:09:

**Comment by auduchinok** [comment]
It tries to download it three times and then exits with non-zero code.

**Comment by forki** [comment]
Mhm can you please create a repro? This sounds weird. If nuget already
downloaded it, then it should never download it again

Eugene Auduchinok <notifications@github.com> schrieb am Do., 27. Sep. 2018,
14:58:

**Comment by auduchinok** [comment]
It was the first time it was being downloaded on that machine so it couldn't fall back to the packages folder.
My workaround was to create a separate project and to restore these packages using Nuget. Only after me doing that Paket was able to restore the project.

**Comment by auduchinok** [comment]
@forki Can you reproduce it with the solution above by removing the downloaded packages?
Not sure how to repro the slow connection, though. :)

**Comment by forki** [comment]
no, works for me. even after "paket clear-cache". but these packages are huge!

![image](https://user-images.githubusercontent.com/57396/46190666-cd7b0380-c2f4-11e8-9518-c1400d7b3ca7.png)

**Comment by Vidarls** [comment]
I'm struggling with the same right now, not an issue in my dev environment, but on a CI server with no cache it breaks the build for some of these huge runtime packages.

**Comment by forki** [comment]
suggestions welcome

**Comment by Vidarls** [comment]
In my case, the package is coming from a public MyGet feed (that seems to be throttled), so the download is taking several minutes to complete (even though it is "just" ~65 MB).

It looks like #3383 could be a viable fix? I can set the required Env variables in the build environment and keep normal timeouts for other builds.
