### ISSUE TITLE
Adjustable timeouts for downloading packages

### ISSUE THREAD

**Issue by pawld** [fsprojects/Paket#3384]
### Description
Timeouts while downloading big packages from local package server.

### Repro steps

Issue occurs with:
- nexus repository manager OSS 3.10.0-04
- slow internet connection
- big packages > 50MB

And then run paket update.

https://github.com/fsprojects/Paket/pull/3383

### Expected behavior

To be able to adjust the timeout.
Process shows progress of the Download and does not timeout.
Exception states what timeout has been requested (not included in the pull request)

### Actual behavior

Timeouts waiting for the request or processing the streams.

**Comment by pawld** [comment]
We use the paket Version 5.176.9

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/3383
