### ISSUE TITLE
paket.local is not consulted on new install

### ISSUE THREAD

**Issue by et1975** [fsprojects/Paket#3386]
### Description

Trying to test an unpublished local package and following `paket.local` instructions fails. 

### Repro steps

1. Create a package with an ID that hasn't been published on any of your package sources.
2. Add it to `paket.dependencies`, create `paket.local` and the entry for this new package.
3. Run `paket install`

Observe it fail, not even trying to look in the local folder.

### Expected behavior

It should consult the `paket.local` and install should succeed, assuming everything else is in order.

### Actual behavior

Fails.

### Known workarounds

Specify the local folder as `source` in the `paket.dependencies` instead.

**Comment by forki** [comment]
Or you trying that for dotnet core / dotnet cli? It's not supported in that
model

Eugene Tolmachev <notifications@github.com> schrieb am Sa., 13. Okt. 2018,
20:23:

**Comment by et1975** [comment]
It fails at `paket install`, it shouldn't matter what my downstream tooling is, should it?

You're right in that it fails down the road on `dotnet restore` as well, so maybe it doesn't matter if install itself is failing as well. 

For now I've fell back to nuget's own facilities for local sources and package resolution.

**Comment by forki** [comment]
Do you have a repro zip?

**Comment by et1975** [comment]
https://github.com/et1975/paket_3386

**Comment by forki** [comment]
after thinking about this. I think this is considered correct. local files only override restore behaviour. It's not a good idea to let it  touch the lock file.

but there is an easy workaround for what you are trying to do. Just add `source ../elmish/oidc/src/bin/Release` to the top of your dependencies file.

**Comment by et1975** [comment]
fair enough!
