### ISSUE TITLE
Paket fails to update project files on install and update

### ISSUE THREAD

**Issue by Bikeman868** [fsprojects/Paket#3387]
### Description

My solution has two projects in the same folder, Paket updates one of the projects but not the other.

### Repro steps

Clone this repository https://github.com/Bikeman868/OwinFramework.Pages
Run the restore.cmd script.
Compile the OwinFramework.Pages.Net40.sln and notice that is compiles without errors.
Compile the OwinFramework.Pages.Net45.sln and notice that is has lots of errors caused by missing assembly references.
Note that these solutions reference all of the same source code files, the only difference is the framework version that they target.
Run the update.cmd and/or install.cmd script.
Note that the Net40 projects are all still correctly referencing the right assemblies and still compile.
Note that the Net45 projects still have missing assembly references. 

### Expected behavior

The assembly references should be added to the Net45 version of the solution.

### Actual behavior

Some assembly references are missing from the Net45 version of the solution but the Net40 version is updated correctly

### Known workarounds

Manually re-add assembly references by hand after each install or update.

**Comment by forki** [comment]
solution is to use 2 references files. see https://github.com/Bikeman868/OwinFramework.Pages/pull/1
