### ISSUE TITLE
Unable to retrieve package versions for 'RestSharp'

### ISSUE THREAD

**Issue by sheam** [fsprojects/Paket#3395]
### Description

I am attempting to convert a project from Nuget using the _convert-from-nuget_ command. It seems to build my reference files fine, but then throws an error:

```
eferences file saved to D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\StrangeBrew.TypeScriptGenerator\paket.references
References file saved to D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\StrangeBrew.Web\paket.references
Resolving packages for group Main:
Performance:
 - Resolver: 953 milliseconds (1 runs)
    - Runtime: 131 milliseconds
    - Blocked (retrieving package versions): 822 milliseconds (1 times)
 - Average Request Time: 33 milliseconds
 - Number of Requests: 22
 - Runtime: 3 seconds
Paket failed with
-> Unable to retrieve package versions for 'RestSharp'
   -- CLOSED --

   -- OPEN ----
      RestSharp 106.5.4 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      Newtonsoft.Json 11.0.2 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      Sendgrid 9.10 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      WindowsAzure.Storage 9.3.2 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      Microsoft.OData.Core 7.5.1 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      Microsoft.OData.Edm 7.5.1 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      Microsoft.Spatial 7.5.1 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      EntityFramework 6.2 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      Microsoft.AspNet.OData 6.1 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
      Auth0.Core 5.10 (from D:\Users\sheam\code\Mine\bn-alt\StrangeBrewWeb\paket.dependencies)
```
### Repro steps

1. Create a project nuget that references RestSharp 106.5.4.
2. Run paket convert-from-nuget.

### Expected behavior

A successful run, conversion to paket.

### Actual behavior

aforementioned error occurs.

### Known workarounds

Stil with nuget.

**Comment by forki** [comment]
Do you have correct nuget source feed in the dependencies file?

Shea Martin <notifications@github.com> schrieb am Mo., 22. Okt. 2018, 11:56:

**Comment by sheam** [comment]
What dependency file? All I did was download paket.bootstrap.exe rename it,
and run it with the convert command.

I am just using the default nuget repository. Do I need to change it to
something else?

**Comment by forki** [comment]
Can you please upload the generated paket.dependencies file?

Shea Martin <notifications@github.com> schrieb am Mo., 22. Okt. 2018, 22:13:

**Comment by sheam** [comment]
I think the issue was an old nuget source. I removed it, and then it worked find. Sorry for false alarm.
