### ISSUE TITLE
Is Paket as a global tool an expected scenario?

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/Paket#3398]
### Description

Tried using Paket as a global tool, and it is SUPER close to working.  I think the only thing that needs to be updated is the Paket.Restore.targets.

### Repro steps

On Ubuntu:

1. `dotnet tool install -g Paket --version 5.182.0-alpha003`
2. `mkdir ~/paket-test`
3. `cd ~/paket-test`
4. `paket init`
5. `dotnet new console -lang F# -o Test`
6. `paket add FSharp.Core --project Test`
7. `dotnet restore Test/Test.fsproj`

### Expected behavior

Project restores.

### Actual behavior

Restore fails with:

```
Cannot open assembly '/home/nat/paket-test/.paket/paket.exe': No such file or directory.

/home/nat/paket-test/.paket/Paket.Restore.targets(91,5): error MSB3073: The command "mono --runtime=v4.0.30319 "/home/nat/paket-test/.paket/paket.exe" restore" exited with code 2. [/home/nat/paket-test/Test/Test.fsproj
```

### Known workarounds

Go into Paket.Restore.targest and replace `$(MonoPath) --runtime=v4.0.30319 "$(PaketExePath)"` with `paket`.  Obviously this isn't the right thing to do though.

I'm pretty bad at MSBuild, but my understanding is that the conditions can be crafted to check if Paket exists as a global tool (or at least a global command).  It could be done after checking if Paket exists in the .paket directory.

**Comment by matthid** [comment]
> I'm pretty bad at MSBuild

everyone is, just give it a try, if it works for you and .paket/paket.exe still works it's already an improvement ;)

**Comment by tomzo** [comment]
> my understanding is that the conditions can be crafted to check if Paket exists as a global tool (or at least a global command). It could be done after checking if Paket exists in the .paket directory.

I am also interested in this. Because we build in docker images which already have all tools pre-installed, including paket, and therefore I never really want to download paket again (since I have reference to a docker image tag which is strict enough anyway).
Maybe we could simply have an extra file, e.g. `.paket/global_mode` which implies that paket should not attempt to search for executable or bootstrap anything, but rather run with `dotnet paket` or just `paket`. `Paket.Restore.targets` could check for that file.
Or perhaps just place an extra property into `Paket.Restore.targets` 
```
<PaketGlobalMode>true</PaketGlobalMode>
```
Then when paket regenerates `Paket.Restore.targets`  it would have to keep the flag.

@forki what do you think?

**Comment by NatElkins** [comment]
I don't know if an extra file is needed.  The targets file already tries to figure out what kind of Paket is installed based on whether there's a `paket` or `paket.exe` in the `.paket` folder.  Right now it's sort of a "waterfall" logic, and using mono is the default fallback right now.  I made a change locally to assume that Paket is installed globally if an executable isn't found in any of the expected locations.

I need to do more testing to ensure all commands work on the various scenarios (Paket installed locally and getting run via mono, Paket installed locally but running as a self-contained executable on .NET Core, etc), but it worked last time I was playing with it.  I'll try to get a PR out in the near future.

**Comment by tomzo** [comment]
@NatElkins thanks. 
Can you share the part you added?
I could check if that would work in my cases too.

**Comment by NatElkins** [comment]
@tomzo Actually I guess I pushed some code up a while ago that I'd forgotten about.  See here: https://github.com/NatElkins/Paket/commit/ac81f253517326384ed6120446f2514aa04220e7

**Comment by NatElkins** [comment]
The way to test would be to install Paket as a global tool as per my first post, then do paket init, then replace the Paket.Restore.targets with the version in the commit I posted.  Then play around with `paket commands_go_here`.

**Comment by NatElkins** [comment]
Only thing is that I don't know if there's a better/more elegant way of doing this than whatever change I made.

**Comment by NatElkins** [comment]
Thanks @tomzo for taking the initiative!
