### ISSUE TITLE
Intermittent Paket.Restore.props error in 5.181.1 - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by yaakov-h** [fsprojects/Paket#3404]
### Description

After upgrading Paket to 5.181.1 from 5.173.1 I get an intermittent build error in Paket.Restore.props.

### Repro steps

1. Run `.paket\paket.exe restore`
2. Run `dotnet.exe restore MyProject.csproj --no-dependencies`

### Expected behavior

Packages are restored

### Actual behavior

```
 Checking Paket version (version 5.181.1 requested)...
  Paket.exe 5.181.1 is up to date.
  Paket version 5.181.1
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 104 milliseconds
C:\path\to\project\.paket\Paket.Restore.targets(147,5): error MSB4184: The expression ""System.String[]".GetValue(5)" cannot be evaluated. Index was outside the bounds of the array. 
```
### Known workarounds

Delete all un-source-controlled files and rebuild.

**Comment by yaakov-h** [comment]
On further investigation this appears to be caused by having paket files from 5.173.1 lying around when running the 5.181.1 restore process.

**Comment by yaakov-h** [comment]
It seems to be reliably trigger-able by a dirty workspace.

In my case, `Project\obj\Project.csproj.netstandard2.0.paket.resolved`, `Project\obj\Project.csproj.net46.paket.resolved` and similar are CSV files with only 5 columns, not 6.

e.g.

```
Newtonsoft.Json,11.0.2,Transitive,Main,false
Microsoft.AspNet.WebApi.Client,5.2.6,Direct,Main,false
```

I assume that either:

- Paket did not know to invalidate this and recompute this intermediary file, or
- Paket does know to invalidate and recompute, but does that at some point **after** the MSBuild parsing runs and crashes.

**Comment by forki** [comment]
Can someone can send a pr to the targets file with proper error handling
around that?

Am Mo., 5. Nov. 2018, 22:27 hat Jonathan Leaver <notifications@github.com>
geschrieben:

**Comment by yaakov-h** [comment]
I think I can make a get-or-default fairly easily, but should the default be true, false, or some other behaviour entirely?

**Comment by forki** [comment]
maybe just make it a nicer error message?

**Comment by yaakov-h** [comment]
“Aaaaaaaah please delete all your obj/ folders and try again”? 🙃

**Comment by forki** [comment]
Well maybe go with a default of false then 😂

Am Di., 6. Nov. 2018, 11:57 hat Yaakov <notifications@github.com>
geschrieben:

**Comment by yaakov-h** [comment]
I can't quite make sense of 373c969:

A new column was inserted as the second-last column in the file.
The new column is `AllPrivateAssets`.
The old column was `AllPrivateAssets` and is now `CopyLocal`.

This doesn't leave me with a simple answer to default value.

Can we perhaps force packet.exe to regenerate this intermediary file if the column count is off?

**Comment by forki** [comment]
Ok then just give the error with info about cleaning /obj. Sorry

Am Mi., 7. Nov. 2018, 01:40 hat Yaakov <notifications@github.com>
geschrieben:

**Comment by yaakov-h** [comment]
I'd rather have Paket self-recover than stall and require the user to take action. Particularly because I'd have to manually clean up a _lot_ of obj folders.

Another possible fix:

If there are 5 columns, use old behaviour in props.
If there are 6 columns, use new behaviour in props.

Would you be OK with a bit of back-compat in the props file?

**Comment by forki** [comment]
Git clean -xdf and run build again. It does not matter how many obj you
have.
The problem with the fallback is that it's doing wrong behavior if you
already use the properties.

I think I'd rather see it come up with a better error message.

Am Mi., 7. Nov. 2018, 07:42 hat Yaakov <notifications@github.com>
geschrieben:

**Comment by yaakov-h** [comment]
> Git clean -xdf and run build again. It does not matter how many obj you
have.

Try about 80 different TFVC repositories times 40 build servers, and I'd have to clean all serversat the time where paket is upgraded, in each repository. If I clean too early, the old paket will write the old files back out again.

(No, the build servers don't auto-clean between builds yet 😢)

**Comment by forki** [comment]
Ok but these issues are unrelated to paket. They will always bite you with
all the others tools as well.
I mean I can certainly feel your pain, but I don't see a good solution here
that won't make things potentially worse.

Am Mi., 7. Nov. 2018, 08:00 hat Yaakov <notifications@github.com>
geschrieben:

**Comment by yaakov-h** [comment]
Possibly, but at the same time, I've never seen a similar tool that requires major intervention on a minor version upgrade. It should be able to either deal with it, or self-heal.

**Comment by forki** [comment]
can you please retry with latest - it also comes with slightly changed targets file

**Comment by matthid** [comment]
I'm not sure this is solved. I'm seeing something similar in the fake release process.

I'd expect that the following scenario works:
- Restore with an older paket version
- Continue the build with a newer paket version (consider the user updating the version in `paket.dependencies` for example)

As the [following build](https://dev.azure.com/fakebuild/FSProjects/_build/results?buildId=783&view=logs) shows this scenario is not working:

```
error MSB4184: The expression ""System.String[]".GetValue(5)" cannot be evaluated. Index was outside the bounds of the array. [D:\a\1\s\src\app\Fake.Core.Context\Fake.Core.Context.fsproj]
```

I feel like we need to be much more careful when updating caching files as this scenario is kind of important for fake to work properly together with paket.
