### ISSUE TITLE
InvalidOperationException: Timeouts not supported with this stream when using BaGet

### ISSUE THREAD

**Issue by danyx23** [fsprojects/Paket#3407]
### Description

I want to install a nuget package from our BaGet server (https://github.com/ai-traders/BaGet). This fails with an InvalidOperationException: Timeouts werden in diesem Datenstrom nicht unterstützt (german windows, the error message says timeouts are not supported for this data stream). It works with the previous stable version (5.181.1)

This behaviour was observed on Windows 10 with both the full dotnet framework and the dotnet core sdk installed (latest-ish versions - let me know if the precicse versions help)

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a new f# console application, add the paket bootstrapper

2. Use this as paket.dependencies
```
storage: none
source https://api.nuget.org/v3/index.json
framework: auto-detect

nuget FSharp.Core

source https://baget.cloud.douglasconnect.com/v3/index.json
nuget DouglasConnect

```

3. Run paket install and you should see the InvalidOperationException.

### Expected behavior

The package should be downloaded and installed

### Actual behavior

An exception occurs:
```
Paket failed with
-> Could not download DouglasConnect 6.0.6 from https://baget.cloud.douglasconnect.com/v3/package/douglasconnect/6.0.6/douglasconnect.6.0.6.nupkg.
   StackTrace:
        bei Paket.NuGet.download@853-54.Invoke(Exception _arg12)
        bei Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
     --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
        bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        bei Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
        bei Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
        bei Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
        bei Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
        bei Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
        bei Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        bei Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
        bei Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
        bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
        bei Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
        bei Paket.InstallProcess.InstallIntoProjects[a](InstallerOptions options, Boolean forceTouch, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projectsAndReferences, FSharpMap`2 updatedGroups)
        bei Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
        bei <StartupCode$Paket-Core>.$PublicAPI.Install@266.Invoke(Unit unitVar0)
        bei Paket.Utils.RunInLockedAccessMode[a](String lockedFolder, FSharpFunc`2 action)
        bei Paket.Program.handleCommand@822-11.Invoke(ParseResults`1 results)
        bei Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        bei Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        bei Paket.Program.handleCommand(Boolean silent, Command command)
        bei Paket.Program.main()
-> InvalidOperationException: Timeouts werden in diesem Datenstrom nicht unterstützt.
```

### Known workarounds

Switch from using paket in magic mode to using the last stable version.

**Comment by kimsk** [comment]
We are experiencing the same error, `InvalidOperationException: Timeouts are not supported on this stream.` when using paket `5.183.0`. The version `5.181.1` works fine.

**Comment by forki** [comment]
ok I'm reverting

**Comment by CaringDev** [comment]
I can confirm this issue also occurs for ProGet feeds.

**Comment by forki** [comment]
Latest version should work again. Can anyone confirm?

Raphael Schweizer <notifications@github.com> schrieb am Mi., 31. Okt. 2018,
08:41:

**Comment by CaringDev** [comment]
@forki Yes, latest (5.184.0) does work. Sorry, should have mentioned this as well.

**Comment by forki** [comment]
Ok good.

If someone finds a way to reapply the PR in a way that is non-breaking then
it would be appropriated.

Raphael Schweizer <notifications@github.com> schrieb am Mi., 31. Okt. 2018,
09:06:

**Comment by Kevin-M-Smith** [comment]
@forki - Just following up - 5.184.0 is working for me as well. Thanks!

**Comment by b0urb4k1** [comment]
Thanks to the feed provided i think that i was able to solve the problem and will make a PR tomorrow.
One remaining question to be answered would be if the default timeouts set are ok like they are now.
They could just be set to never timeout as default.

**Comment by forki** [comment]
Thanks
