### ISSUE TITLE
Feature Request: Enable Generation of multi packages for multi-target project.

### ISSUE THREAD

**Issue by moh-hassan** [fsprojects/Paket#3421]
I have a project for net45 console and netcoreapp2.1
I tried to generate multi packages by using choose/when in msbuild project

		<Project Sdk="Microsoft.NET.Sdk">
		  <PropertyGroup>
			<OutputType>Exe</OutputType>
			<TargetFrameworks>netcoreapp2.1;net45</TargetFrameworks>
		  </PropertyGroup>
		  <Choose>
			<When Condition="'$(TargetFramework)' == 'net45'">
			  <PropertyGroup>
				<PackageId>MyPackage.net45</PackageId>
				<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
			  </PropertyGroup>
				  
			</When>
			<When Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
			  <PropertyGroup>
				<PackageId>MyPackage.NetCore</PackageId>
				<PackAsTool>true</PackAsTool>
				<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
			  </PropertyGroup>

			</When>
		  </Choose>

		  <Import Project="..\.paket\Paket.Restore.targets" />
		</Project>

`paket.template` has entry for only one package

Currently, paket generate successfully  package for the **first** framework in `TargetFrameworks` for **FUll** Framework and use only the  data provided in the file `paket.template`

It fail if the first framework is netcoreapp2.x
Sure, I can't generate multi packages using nuget pack tool

I consider that Mult-packages in multi-target project that build tools in Full Framework and the new Global tool in netcoreapp2.1 is becoming necessary  for distributing one for every framework. 
The way of installation and updating these tools is different.

**Suggested solution:**
- Use the data provided in csproj project for pack
- data in `paket.template` overwrites csproj corresponding properties.
- in multi-target project for mult-packages the file `paket.template` may have section for every package and we can avoid using choose/when in msbuild project to minimize complexity.

**Comment by generik0** [comment]
Any updates on this?

**Comment by jam40jeff** [comment]
@forki This should be fixed along with #3494.
