### ISSUE TITLE
dotnet pack fails with paket and .NET Core 2.1.500

### ISSUE THREAD

**Issue by dbrattli** [fsprojects/Paket#3427]
### Description

Get the error message when running `dotnet pack` with .NET Core 2.1.500:
```
/Users/dbrattli/Developer/GitHub/classlib/.paket/Paket.Restore.targets(226,5): error : The provided SymbolPackageFormat value  is invalid. Allowed values : 'snupkg', 'symbols.nupkg'. [/Users/dbrattli/Developer/GitHub/classlib/classlib.csproj]
```

I have no idea is this is an issue is related to dotnet and/or paket. Tested on Mac OS X 14.4.1, and Windows 10, and get the same error on three different machines and installations.

### Repro steps

1. Install .NET Core 2.1.500, https://www.microsoft.com/net/download

2. dotnet new classlib -o myproject

3. Add paket to new project and initialize. Add a nuget to dependencies so project file `classlib.csproj` imports Paket.Restore.targets`:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <Import Project=".paket\Paket.Restore.targets" />
</Project>
```

4. `dotnet restore`

5. `dotnet build`

6. `dotnet pack`

### Expected behavior

Expected behavior is that `dotnet pack` completes without error. This used to work in earlier versions of dotnet.

### Actual behavior

```
➜  classlib dotnet pack                  
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  shasum: /Users/dbrattli/Developer/GitHub/classlib/.paket/../paket-files/paket.restore.cached: 
  Paket version 5.188.1
  Starting full restore process.
  Performance:
   - Disk IO: 17 milliseconds
   - Runtime: 2 seconds
  Restoring packages for /Users/dbrattli/Developer/GitHub/classlib/classlib.csproj...
  Restore completed in 178.88 ms for /Users/dbrattli/Developer/GitHub/classlib/classlib.csproj.
  Paket version 5.188.1
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 60 milliseconds
  classlib -> /Users/dbrattli/Developer/GitHub/classlib/bin/Debug/netstandard2.0/classlib.dll
  Paket version 5.188.1
  Performance:
   - Runtime: 644 milliseconds
/Users/dbrattli/Developer/GitHub/classlib/.paket/Paket.Restore.targets(226,5): error : The provided SymbolPackageFormat value  is invalid. Allowed values : 'snupkg', 'symbols.nupkg'. [/Users/dbrattli/Developer/GitHub/classlib/classlib.csproj]
```

### Known workarounds

Don't know any workarounds. Downgrading dotnet might work.

**Comment by MarkNicholls** [comment]
I have the same problem in an F# project, coincidentally after updating visual studio 2017 to the latest version.
I have the problem in both Visual Studio AND the a fake build script (using MSBuild)

I don't have the details here but I got

....Paket.Restore.targets(226,5): error : The provided SymbolPackageFormat value  is invalid. Allowed values : 'snupkg', 'symbols.nupkg'.

my project compiles if 
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
is not present (and presumably false).

it fails with the above error if "true"

I have no workaround except reverting to nuget.

**Comment by forki** [comment]
do you guys have a zip with a repro?

**Comment by dbrattli** [comment]
Empty classlib `dotnet new classlib` with added Paket. https://github.com/dbrattli/PackFailure

**Comment by forki** [comment]
cc @cartermp

**Comment by forki** [comment]
ok I can repro - but I have no idea what's going on. it works with 2.1.403 but does not with latest .500 - ouch

**Comment by forki** [comment]
so we need to find a way to detect if we are in .net 500 or earlier and duplicate the pack task yet another time. WIP in https://github.com/fsprojects/Paket/pull/3428

I added 2 ToDos - so if someone can try to come up with what needs to go there - I'd appreciate the help

**Comment by 7sharp9** [comment]
Enrico is on _honeymoon_/holiday for a month.

**Comment by dbrattli** [comment]
Tried looking at the `RuntimeFrameworkVersion` but it's only set to `2.1` when not set explicitly.

**Comment by cartermp** [comment]
Is there an issue on the CLI for this? I'm not aware of any major changes to pack for 2.1.500

**Comment by NinoFloris** [comment]
https://github.com/Microsoft/msbuild/issues/2350
`$(MSBuildVersion)` each msbuild version usually correlates to a version of the sdk as they're shipped and updated together.

**Comment by dbrattli** [comment]
MSBuildVersion=15.9.20 when run with 2.1.500. Notable New Features in 15.9. "We have improved the debugging experience for NuGet packages using the new symbol package format (.snupkg).". https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes

**Comment by MarkNicholls** [comment]
yeah I noticed that and thought it a bit of a coincidence.

**Comment by MarkNicholls** [comment]
@forki  is the message about addiing the property in the .deps file a workaround?
my choice at the moment really is remove paket completely or wait (I actually needed the MSBuild upgrade to make something else work)

**Comment by forki** [comment]
Yes you can add that property manually in the targets file. I just can't
release it yet because it would break older cli.

@cartermp yes it seems to be breaking since the new property does not have
a default. That wouldn't be a problem if the pack task that ships with
nuget in old cli would just ignore it.

Am Do., 15. Nov. 2018, 17:26 hat MarkNicholls <notifications@github.com>
geschrieben:

**Comment by cartermp** [comment]
Sounds like you need to add a check for the MSBuild version then. Though I'm generally worried that people on very old SDKs would still be using much newer Paket versions.

**Comment by forki** [comment]
"very old"? We are talking about a single minor version. But yes we trying
to be as backwards compatible as possible

Am Do., 15. Nov. 2018, 17:43 hat Phillip Carter <notifications@github.com>
geschrieben:

**Comment by cartermp** [comment]
The implication here is that _any_ project on an older SDK is likely to be using the very latest Paket, yes?

**Comment by forki** [comment]
Many users are always using latest paket versions. Yes. That has benefits -
except on days like today ;-)

Am Do., 15. Nov. 2018, 17:53 hat Phillip Carter <notifications@github.com>
geschrieben:

**Comment by MarkNicholls** [comment]
so just for advice to others, my workaround is to copy the paket.restore.targets and add SymbolPackageFormat line as described about and then ammend my projects to import this ammended file rather than the default one. Hopefully will get a fix and undo this, it only affects a few of my projects

**Comment by forki** [comment]
I think I have a fix ready in https://github.com/fsprojects/Paket/pull/3428 - I'd appreciate review.

**Comment by dbrattli** [comment]
Confirmed fixed in 5.189.0

**Comment by NinoFloris** [comment]
So according to @dasmulli `$(NETCoreSdkVersion)` also exists!

**Comment by forki** [comment]
PR welcome if it improves things

**Comment by MarkNicholls** [comment]
it worked for me!

**Comment by forki** [comment]
So apparently my fix wasn't good enough. https://github.com/fsprojects/Paket/issues/3429

Any ideas?
