### ISSUE TITLE
Fix to #3427 broke .NET Core 2.1.4

### ISSUE THREAD

**Issue by MiloszKrajewski** [fsprojects/Paket#3429]
### Description

5.189.0 fixing "pack" problem with .NET core 2.1.500 (issue #3427) breaks "pack" for .NET core 2.1.4.

### Repro steps

0. Install .NET Core 2.1.4
1. Use attached project (it forces .net core 2.1.4 using `global.json` setting)
2. Run `paket restore`
3. Run `dotnet pack src`

### Expected behavior

Pack won't fail

### Actual behavior

Pack will fail

### Known workarounds

A. Use most recent version of .NET core
B. Force older version of paket (5.188.0 is fine)

[p51890c214.zip](https://github.com/fsprojects/Paket/files/2590975/p51890c214.zip)

**Comment by forki** [comment]
Ouch. I tried with 2.1.403

Can you please add "version 5.188.0" at the top of your dependencies file
for now?

Any ideas what's going wrong?

Am Fr., 16. Nov. 2018, 22:48 hat Milosz Krajewski <notifications@github.com>
geschrieben:

**Comment by MiloszKrajewski** [comment]
Oh, I wasn't explicit. By saying "B. Force older version of paket (5.188.0 is fine)" I do mean adding it to paket.dependencies, and yes, it solves the problem. 
Not ideal of course, but at least we can build.

**Comment by forki** [comment]
please retry with latest
