### ISSUE TITLE
paket.local - csproj incompatibility with the new dotnet sdk, missing(or not obvious) from the doc

### ISSUE THREAD

**Issue by alexandrosntak** [fsprojects/Paket#3443]
### Description

The local-file.md or the paket-and-dotnet-cli.md files do not contain any text warning users that the paket.local system is not compatible with the csproj format when using the new dotnet sdk. After some hours of trying to get it to work, I googled and found the problem in this issue.

https://github.com/fsprojects/Paket/issues/3116

### Repro steps

https://github.com/fsprojects/Paket/blob/master/docs/content/local-file.md
https://github.com/fsprojects/Paket/blob/master/docs/content/paket-and-dotnet-cli.md

### Expected behavior

I would like to have a sentence indicating that this feature does not work with the new dotnet sdk. I don't know what the appropriate place is though. Perhaps it could save some time for other people. :)

**Comment by forki** [comment]
They work with csproj - just not with the new dotnet sdk.

Am Sa., 1. Dez. 2018, 01:19 hat Ntakwing <notifications@github.com>
geschrieben:

**Comment by alexandrosntak** [comment]
Hello @forki , thank you for your answer. I did not know this, I will rewrite then the issue to better reflect the situation. :)

**Comment by forki** [comment]
Thanks. And I think you are right: a disclaimer for this is needed in the
docs

Am Sa., 1. Dez. 2018, 09:46 hat Ntakwing <notifications@github.com>
geschrieben:

**Comment by dustinlacewell** [comment]
I, too, just wasted _hours_ on this issue. How is this not merged?
