### ISSUE TITLE
Paket bootstrapper fails to detect its own version when ran in magic mode

### ISSUE THREAD

**Issue by stackh34p** [fsprojects/Paket#3456]
### Description

I have a project using the .NET sdk and multi-targeting a number of frameworks: net20, net35, net40; net45; netstandard1.0 to netstandard2.0 each and I am using paket in "magic" mode. Often enough, paket-related errors occur which cause the msbuild operations to fail.

### Repro steps

1. Create a C# project for the new .NET sdk and multi-target many different frameworks. For example net20 to net40 and netstandard1.0 to netstandard2.0 could replicate the issue.

2. Set up the project to use paket, make it so that paket bootstrapper is used in magic mode. Add paket references/dependencies files with some trivial dependencies there.

3. Invoke paket restore / update / install against the project file. This would ensure the project will reference the Paket.Restore.targets

4. Issue any of the following commands in the project directory:  
 * `dotnet clean`  
 * `dotnet build`  
 * `dotnet pack`  

### Expected behavior

All operations complete successfully

### Actual behavior

Sporadically often, a paket-related error would cause the dotnet operation to fail.

Here is an excerpt from the stacktrace I get from my msbuild output:

```
1>PaketRestore:
            at System.Version..ctor(String version)
            at Paket.Bootstrapper.PaketRunner.SetBootstrapperArgument(String program, IEnumerable`1 arguments)
            at Paket.Bootstrapper.PaketRunner.Run(String program, IEnumerable`1 arguments)
            at Paket.Bootstrapper.Program.OnSuccessfulDownload(BootstrapperOptions options)
```

As I have looked trough Paket's own code, it seems the issue comes from [here](https://github.com/fsprojects/Paket/blob/80a776b60043cb088647c761bd7e1f82920baf6d/src/Paket.Bootstrapper/PaketRunner.cs#L18). 

I believe the cause is that paket in magic mode first downloads the actual paket executable and stores it in a temp folder. Then it would delegate the command line arguments to the downloaded exe. I think the issue is that the same temporary paket exe is being called for multiple batched targets by msbuild (as I have multiple target frameworks, most of the clean / build / pack operations get batched and executed simultaneously by the msbuild engine). When the same temp exe is ran by two targets simultaneously, one of them would fail to get the executable's version, thus crashing the entire paket call.

### Known workarounds

Use actual paket.exe instead of paket bootstrapper in magic mode does not lead to these errors. It bypasses any code called trough the paket boostrapper.

**Comment by forki** [comment]
Cc @vbfox

Am Do., 13. Dez. 2018, 13:23 hat Ivaylo Slavov <notifications@github.com>
geschrieben:

**Comment by vbfox** [comment]
AFAIK all such issues should have been fixed in the latest big bugfix related to parallel operation

Can you give a few more information:

* Version of the bootstrapper
* If possible a git repository reproducing the issue (No need for any code files, the structure and msbuild files importing paket should show the same problem)

**Comment by ivaylo5ev** [comment]
Hello, @vbfox, great to know this is going to become a thing of the past. Here is a [link to a demo project](https://github.com/ivaylo5ev/Paket.Bootstrapper.Parallel.Ops.Issue) where some of the effects can be observed. 

The paket.boostrapper used there has version number 5.124.0.0 (as seen from windows file properties tab)

Unlike my real use case, however, where I have a lot of custom MSBuild targets around the clean / build / pack operations, I did not reproduce a failing build. The error I reported, however, is still visible in the paket output logs. One may need to run the dotnet build commands a couple of times to see. 

I hope this helps.

**Comment by forki** [comment]
5.124 is pretty old - can you please update the bootstrapper and try if it still reproduces?

**Comment by ivaylo5ev** [comment]
@fork, will do and update here.

**Comment by vbfox** [comment]
🎉
