### ISSUE TITLE
Allow to use aliases for libs

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#346]
As used in scriptcs.

**Comment by cdrnet** [comment]
I also have a need for aliases recently (to work around a type collision in NUnit 3, nunit/nunit#1349). It is not blocking, but a `paket.exe install` would drop the aliases I've added manually.

Has there been any new insight into this since this issue was opened, or would adding an alias parameter to `paket.references` still be the preferred way?

**Comment by forki** [comment]
Don't think we have new things that were not discussed here.

**Comment by freeranger** [comment]
Is there any plan to implement this feature?
I had to create a custom version of a package recently because of type collisions which I would previously have solved with aliases in visual studio

**Comment by forki** [comment]
PR at https://github.com/fsprojects/Paket/pull/1583

**Comment by forki** [comment]
this is now in v3 alpha channel

**Comment by ivaylo5ev** [comment]
Hello. I am trying to get library aliases to work for a .NET SDK project with no success. Is there anything special I need to do besides adding the following to my `paket.references` file?

```
MyNugetPackage
  alias MyNugetPackage.dll MNP
```

**Comment by forki** [comment]
@enricosada do you know if the dotnet sdk supports this?

Am Do., 1. Nov. 2018, 09:06 hat Ivaylo Slavov <notifications@github.com>
geschrieben:

**Comment by 0x53A** [comment]
No, but you can hack around it: https://github.com/NuGet/Home/issues/4989#issuecomment-426666530

**Comment by ivaylo5ev** [comment]
The last time I've use the `<PackageReference>` stuff from within a dotnet sdk project it got messed up with package restoration. Referenced packages from within the project file get resolved using the nuget sources of Visual Studio. I am using git repos and local filesystem paths to resolve non-publicly available internal dependencies. Would the above work for me as well?
