### ISSUE TITLE
Any plans on packaging paket as a dotnet global tool?

### ISSUE THREAD

**Issue by sanisoclem** [fsprojects/Paket#3480]
### Description

.net core 2.1 introduces dotnet global tools. Packaging the cli as a global tool could save us the trouble of doing that bootstrapper business. And instead just do something like:

```bash
$ dotnet tool install -g paketcli
$ dotnet paket restore
```

**Comment by forki** [comment]
I think it's already possible to use paket as global dotnet tool

Am Di., 15. Jan. 2019, 06:44 hat Jerahmeel Cosinas <notifications@github.com>
geschrieben:

**Comment by sanisoclem** [comment]
@forki my bad. I just saw this: https://github.com/fsprojects/Paket/issues/3435 closing as duplicate.
