### ISSUE TITLE
Paket restore runs on dotnet build --norestore

### ISSUE THREAD

**Issue by BlythMeister** [fsprojects/Paket#3485]
### Description

When calling dotnet build with the --norestore option a paket restore is still run.

### Repro steps

On any repo, call donet build --norestore.

### Expected behavior

Paket is not called

### Actual behavior

Paket is called

### Known workarounds

None

**Comment by forki** [comment]
maybe there is a MSBuild property set and we can use that in our targets
file!?

Am Do., 17. Jan. 2019 um 15:29 Uhr schrieb Chris Blyth <
notifications@github.com>:

**Comment by BlythMeister** [comment]
it's doing it because even on a no restore the CollectPackageReferences runs.
However, if the written props version does not match the props version in the targets, it will force a restore in order to correctly generate the props files. (which does kinda make sense)
So to fix, we should ensure that the PaketPropsVersion in targets & in https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Installation/RestoreProcess.fs#L328 are kept in sync.
I've re-synced them on #3486 :)

**Comment by BlythMeister** [comment]
It does also seem that `CollectPackageReferences` isn't a valid target to run before.

The nuget restore targets run restore before `_GenerateRestoreGraph`

**Comment by BlythMeister** [comment]
Closing as duplicate of #3449
