### ISSUE TITLE
dotnet restore is broken

### ISSUE THREAD

**Issue by rojepp** [fsprojects/Paket#3487]
### Description

dotnet restore does not work for non-trivially sized projects. Files will fail to download and the CI build breaks. Sample printout: 

>   Paket version 5.195.1
  Paket version 5.195.1
  Paket version 5.195.1
  Paket version 5.195.1
  Could not acquire lock to E:\dev\T4eko\src\EIFileParser\obj\paket.locked.
  Could not acquire lock to E:\dev\T4eko\src\EIFileParser\obj\paket.locked.
  Could not acquire lock to E:\dev\T4eko\src\EIFileParser\obj\paket.locked.
  The process cannot access the file 'E:\dev\T4eko\src\EIFileParser\obj\paket.locked' because it is being used by another process.
  E:\dev\T4eko\src\EIFileParser\obj\paket.locked is locked by paket.exe (PID = 19044). Waiting...
  Trials left: 99.
  The process cannot access the file 'E:\dev\T4eko\src\EIFileParser\obj\paket.locked' because it is being used by another process.
  The process cannot access the file 'E:\dev\T4eko\src\EIFileParser\obj\paket.locked' because it is being used by another process.
  Trials left: 99.
  ..
  ..
  Could not acquire lock to E:\dev\T4eko\paket-files\paket.locked.
  Process is terminated due to StackOverflowException.
  Trials left: 42.

It will retry a whole bunch of times but in the end fail to get all files. 

Doing `.paket\paket.exe restore` doesn't fail in this way, but fails to generate needed project.assets.json and the build fails for that reason. The project targets .Net Core 2.2.

### Repro steps

```bash
git clean -xdf
dotnet restore
```

**Comment by forki** [comment]
Mhm. I'm running it on non-trivial projects and it works. Do you have a
more specific repro?

Am Do., 17. Jan. 2019, 18:59 hat Robert Jeppesen <notifications@github.com>
geschrieben:

**Comment by rojepp** [comment]
Sorry for wasting your time. I think I found the cause. There were some old-style format projects in the repo but not in the solution. Removing these made it work.
