### ISSUE TITLE
paket pack with multi-targeted project only creates first framework specified

### ISSUE THREAD

**Issue by ozwaldDunlop** [fsprojects/Paket#3494]
### Description

using `paket pack` on a project with multiple TargetFrameworks creates a nupkg with only the first specified framework. ie. if the declaration is `<TargetFrameworks>netstandard2.0;net472</TargetFrameworks>`, then the nupkg has just the `netstandard2.0` contents.
If they're swapped round:
`<TargetFrameworks>net472;netstandard2.0</TargetFrameworks>`, then the nupkg has just the `net472` contents.

### Repro steps

Get this repo: <https://github.com/ozwaldDunlop/paket-multitarget-bug>

1. Run `.paket\paket.exe install`
2. Build in Debug mode
3. Run `.paket\paket.exe pack . --build-config Debug`
4. Open the resulting nupkg in 7zip or [Nuget Package Explorer](https://chocolatey.org/packages/NugetPackageExplorer)

### Expected behavior

You should see `netstandard2.0` and `net472` folders in the nupkg as you do when you run `dotnet pack`:
![image](https://user-images.githubusercontent.com/1648478/51837112-4e292b00-22fa-11e9-9a2f-3a363c030732.png)

### Actual behavior

You only see one lib folder: ![image](https://user-images.githubusercontent.com/1648478/51837052-289c2180-22fa-11e9-96dc-b35acc195308.png) 

### Known workarounds

Use `dotnet pack` instead of `paket pack`

**Comment by generik0** [comment]
I am also interested in this, very much.
dotnet pack is not working for me. dotnet pack is doing something very weird and https://github.com/NuGet/Home/issues/3324

**Comment by fjoppe** [comment]
Swapping the frameworks around gives the above behavior, even without rebuild.

I've even tried to "paket pack" the stuff **in** the netstandard2.0 folder, it even then came with a net45 folder in the nupkg.

**Comment by forki** [comment]
Did you try dotnet pack? Paket integrates into that and it allows multi
targeting

Am Sa., 2. Feb. 2019, 21:42 hat Frank Joppe <notifications@github.com>
geschrieben:

**Comment by fjoppe** [comment]
Yes, I was experimenting with that. The result appeared good. However, my question (for me) is, what is the best choice now, to put in my FAKE5 build script? Dotnet pack or paket pack? I don't know at this point. I o like the Paket integration in FAKE.

**Comment by forki** [comment]
Dotnet pack is probably the way to go forward.

Am So., 3. Feb. 2019, 08:57 hat Frank Joppe <notifications@github.com>
geschrieben:

**Comment by jam40jeff** [comment]
@forki The problem is that `dotnet pack` doesn't support many of the setting that `paket pack` does.  Namely, I need `--interproject-references fix`.

**Comment by jam40jeff** [comment]
@forki I believe PR #3534 should be ready to go and will fix this.
