### ISSUE TITLE
Load script generation doesn't reference expected dll 

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#3501]
### Description

When running `.paket/paket.exe generate-load-scripts --framework net462`, in a just created new Saturn project. The Saturn.fsx doesn't reference Saturn?? 

### Repro steps

Please provide the steps required to reproduce the problem

1. dotnet new Saturn

2. .paket/paket.exe restore

3. .paket/paket.exe generate-load-script --framework net462

### Expected behavior

An Saturn.fsx file in the load folder which references the Saturn.dll

### Actual behavior

Loads all the required script files that reference dependent dlls, except Saturn!!

### Known workarounds

Add a reference to Saturn manually.

**Comment by inosik** [comment]
I think that's because Saturn only supports `netstandard2.0`, which Paket doesn't consider as compatible with `net462`.

**Comment by halcwb** [comment]
Thanks.
