### ISSUE TITLE
5.197.1 all builds failing

### ISSUE THREAD

**Issue by MClode** [fsprojects/Paket#3506]
### Description

As of 1 hour ago all of our production builds are failing after an upgrade to paket. Restoring to  5.197.0 has fixed it for us.

### Repro steps

`mono ./.paket/paket.bootstrapper.exe`
`mono ./.paket/paket.exe restore -f`

`dotnet publish -c Release`

### Expected behavior

We expect the project to get built using the dependencies which paket has sorted out, or for paket.exe to provide an error if something is wrong.

An example error from `dotnet publish` (there are lots, but here is just one):
```
/codebuild/output/src585219588/src/github.com/XXX/XXXX/src/XXX.Mongo/XXX.fs(10,13): error FS0039: The type 'SerializerBase' is not defined. [/codebuild/output/src585219588/src/github.com/XXX/XXX/src/XXX.Mongo/XXX.Mongo.fsproj] 
```

### Actual behavior

`paket.exe restore -f` gives no error, and finishes 'fine'. But then `dotnet publish` fails, because it doesn't have its dependencies.

### Known workarounds

Restoring to 5.197.0

**Comment by M0ns1gn0r** [comment]
Our builds fail too, but with a different error:

`error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'`

**Comment by forki** [comment]
Ok I'll revert for now.

**Comment by forki** [comment]
ok revert is released
