### ISSUE TITLE
Migrating ASP.NET Core to Paket

### ISSUE THREAD

**Issue by curdincaspar** [fsprojects/Paket#3511]
### Description

After migrating a new ASP.NET Core project to Paket the website cannot be started anymore.
Paket adds a lot of binding redirects which NuGet did not and because of this it fails.
The following exception is is thrown:

`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'`

Adding "strategy: min" to paket makes no difference.

Example project with the exception can be found here: https://github.com/icfm/PaketTest

### Repro steps

1. Create a new ASP.NET Core 2.2 project with TargetFramework net472

2. Migrate to paket

### Expected behavior

Website should be loaded.

### Actual behavior

An exception is thrown.

### Known workarounds

None

**Comment by forki** [comment]
binding redirects are ignored in dotnet core anyway

**Comment by forki** [comment]
ah net472 - didn't read that. why would you do that?

**Comment by curdincaspar** [comment]
😆 
Because we use WPF.

**Comment by forki** [comment]
anyway, did you try

to remove 

    framework: net472
    redirects: on

from paket.dependencies and run paket install?

this should remove the binding redirects

**Comment by curdincaspar** [comment]
This is not possible as we have a big repo with around 80 projects and the redirects are needed because of all the dependencies.

**Comment by forki** [comment]
yeah but you can do that on package level for the packages that need the redirects.

like 

      nuget FSharp.Core redirects:force

**Comment by curdincaspar** [comment]
I did try that but then System.Runtime cannot be found anymore.

Found a bug which could be related to this and is open for more than a year: https://github.com/NuGet/Home/issues/7440

**Comment by curdincaspar** [comment]
I found a workaround.
I created a group for the ASP.NET Core project which has redirects off
We have to duplicate all the shared dependencies but it works.

Thanks for the hint with the redirects.

**Comment by forki** [comment]
cool!

Am Do., 21. Feb. 2019 um 15:51 Uhr schrieb curdincaspar <
notifications@github.com>:
