### ISSUE TITLE
Paket push hangs

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#3537]
### Description

<img width="627" alt="image" src="https://user-images.githubusercontent.com/193115/55361236-e00a0b80-54d6-11e9-9a5c-74773fc4469a.png">

- CTRL+C doesn't even work. No output for many minutes.

### Repro steps

Please provide the steps required to reproduce the problem

1. Push the Logary project

```
Starting target 'Push'
Starting task 'PaketPush': /Users/h/dev/haf/logary/pkg/Logary.Targets.Stackdriver.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.RabbitMQ.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.ApplicationInsights.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.BigQuery.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.InfluxDb.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Ingestion.UDP.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.Jaeger.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.CSharp.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.SSE.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Ingestion.HTTP.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.ElmahIO.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.Mixpanel.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Adapters.AspNetCore.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Adapters.Facade.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.Shipper.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.Elasticsearch.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.OpsGenie.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Targets.AliYun.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Adapters.EventStore.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Ingestion.TCP.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Adapters.NLog.5.0.0-rc.7.nupkg, /Users/h/dev/haf/logary/pkg/Logary.Adapters.Topshelf.5.0.0-rc.7.nupkg
/Users/h/dev/haf/logary/pkg> "/Users/h/dev/haf/logary/.paket/paket" push  --api-key  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /Users/h/dev/haf/logary/pkg/Logary.5.0.0-rc.7.nupkg (In: false, Out: false, Err: false)
... etc
Paket version 5.196.2
Paket version 5.196.2
Paket version 5.196.2
Paket version 5.196.2
Paket version 5.196.2
Pushing package /Users/h/dev/haf/logary/pkg/Logary.5.0.0-rc.7.nupkg to https://nuget.org/api/v2/package - trial 1
Pushing package /Users/h/dev/haf/logary/pkg/Logary.Targets.RabbitMQ.5.0.0-rc.7.nupkg to https://nuget.org/api/v2/package - trial 1
Pushing package /Users/h/dev/haf/logary/pkg/Logary.Targets.Jaeger.5.0.0-rc.7.nupkg to https://nuget.org/api/v2/package - trial 1
Pushing package /Users/h/dev/haf/logary/pkg/Logary.Targets.InfluxDb.5.0.0-rc.7.nupkg to https://nuget.org/api/v2/package - trial 1
Pushing package /Users/h/dev/haf/logary/pkg/Logary.Ingestion.UDP.5.0.0-rc.7.nupkg to https://nuget.org/api/v2/package - trial 1
Pushing /Users/h/dev/haf/logary/pkg/Logary.Ingestion.UDP.5.0.0-rc.7.nupkg complete.
Performance:
 - Runtime: 2 seconds
Pushing /Users/h/dev/haf/logary/pkg/Logary.Targets.Jaeger.5.0.0-rc.7.nupkg complete.
Performance:
 - Runtime: 2 seconds
Pushing /Users/h/dev/haf/logary/pkg/Logary.Targets.InfluxDb.5.0.0-rc.7.nupkg complete.
Performance:
 - Runtime: 2 seconds
Pushing /Users/h/dev/haf/logary/pkg/Logary.Targets.RabbitMQ.5.0.0-rc.7.nupkg complete.
Performance:
 - Runtime: 2 seconds
Pushing /Users/h/dev/haf/logary/pkg/Logary.5.0.0-rc.7.nupkg complete.
Performance:
 - Runtime: 5 seconds












^C
```

2. Wait

### Expected behavior

No hang

### Actual behavior

Hang

### Known workarounds

Unknown

https://github.com/logary/logary/issues/408

**Comment by matthid** [comment]
I think I have noticed this before. However, I was never able to actually debug this. To debug this we would need either stacktraces of "where" it hangs or a way to reproduce this.
If you can indeed reproduce, can you try to get at least a verbose output?

**Comment by haf** [comment]
I haven't been able to find docs on either how to increase the verbosity of paket during this op (build log?) nor how to print stacktraces using signals to .net core... This is for the .net core paket version. Could you tell me how to run the command?

**Comment by matthid** [comment]
I don't think there are any docs and I'd guess the only way to have verbose is to "hack" the verbose flag into the `paket.targets` file.

**Comment by haf** [comment]
I'm sorry, that's not something I'm willing to spend time on. How about you add logging to the --verbose flag, and I can generate any output you want?

**Comment by haf** [comment]
Perhaps we can discuss how to log/trace with a sidecar log server, e.g. Rutta by using a pid-file?

**Comment by haf** [comment]
Ping? Any insight into how this project can be debuggable?

**Comment by matthid** [comment]
I thought you were not interested in investing time into this...
My previous comments still hold. If you want to debug this yourself just attach the debugger when this happens and look where it "hangs". It should be a straightforward fix once we know what happens.
The verbose output really only is a shot into the dark, it might help or it might not.

**Comment by haf** [comment]
I'm not hacking around a .targets file, but this is still blocking me. Or perhaps you think I'm the only one who pushes packages with paket?

Like I said, I can send a PR to increase logging verbosity so that people don't have to hack around msbuild files? Would you like a PR like that?

**Comment by forki** [comment]
everything that helps solve it is welcome.

**Comment by matthid** [comment]
We probably **wouldn't** accept a PR just adding the `--verbose` flag. We probably **would** accept a PR which enables `--verbose` by when an environment variable is set. We could even add that into the paket code itself for this particular situation. Like I said: It is not guaranteed to help but this way we could debug this via slow printf debugging.

**Comment by haf** [comment]
Not a problem anymore for some reason.
