### ISSUE TITLE
Add support for license property in paket.template file

### ISSUE THREAD

**Issue by Kiryushin-Andrey** [fsprojects/Paket#3564]
The licenseUrl attribute in nuspec files is being [deprecated ](https://github.com/NuGet/Announcements/issues/32) by Microsoft. Paket needs to support the proposed alternative - a [license](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license) attribute. So we should be able to add license attribute to paket template file and get it built into the resulting nuspec in the package.

**Comment by forki** [comment]
We would love to see a pull request here

**Comment by cdrnet** [comment]
Related: #3475

**Comment by cartermp** [comment]
I think we can close #3475 as a duplicate of this. I'd be happy to take a crack at this along with #3707. Is there a best place to look?
