### ISSUE TITLE
Paket managed references brings Visual Studio in trouble

### ISSUE THREAD

**Issue by mapfel** [fsprojects/Paket#3565]
We changed our dependency management to Paket.
The build runs fine, everything is OK.
But in case we open such a project in Visual Studio it is marked with the yellow exclamation mark. Again, build is possible without any issues.

Unfortunately, we also use DevExpress and during design time we cannot use it anymore, because the types from these packages are unknown then.

But this behavior is not the same for different machines. We have one machine without that issue and two with it. All are more or less identical from the setup. We use the same baseline (hardware, software) for them.

One slight difference: the machine where it works has VS2019 only, the second one only VS2017 and the last one VS2017 and VS2019.

In the [screenshot](https://paste.pics/5GDEY), you can see the point.
We have the bundled the Microsoft.VisualBasic assembly in an own NuGet package named StepAhead.Microsoft.VisualBasic.
Also interesting, at the machine where it works the package is not visible, only the DLL. Here the other [screenshot](https://paste.pics/5GDKI).

What's the trick to get it run?

**Comment by forki** [comment]
Are you using dotnet cli?

Marko Apfel <notifications@github.com> schrieb am Fr., 3. Mai 2019, 15:06:

**Comment by mapfel** [comment]
Paket installed as described [here](https://fsprojects.github.io/Paket/installation.html#Installation-per-repository).

Then used with

```
paket init
paket convert-from-nuget --force
paket install --force
...
```

current version:

```
PS C:\...\WindowsFormsApp1\.paket> .\paket.exe --version
Paket version 5.203.2
```

**Comment by forki** [comment]
No I meant your projects. Is it new dotnet sdk based?

Marko Apfel <notifications@github.com> schrieb am Fr., 3. Mai 2019, 15:43:

**Comment by mapfel** [comment]
The screenshots are from a project which is a simple NETFX WinForms app.
Inside the (classic) csproj file are some conditions which look fine and seems to be fine because compilation works also inside VS.

**Comment by mapfel** [comment]
After additional investigations, the issue is solved.
In the obj folders, Visual Studio caches some Package knowledge. Notably with packages from our private NuGet feed that cache gets into conflict during/after migration to Paket.
Deleting the obj folders fixes that issue.
Maybe content for a troubleshooting guideline?

**Comment by forki** [comment]
We fixed couple of other issues around obj today. maybe this would help...
