### ISSUE TITLE
Paket 5.203.2 pulls packages it shouldn't pull -> build fails

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#3566]
### Description

Just updated paket and now run into a issue similar to https://github.com/fsprojects/Paket/issues/3544 but for a `net461` project:

```
Reference to package System.Runtime.WindowsRuntime is added which causes error The type 'IAsyncOperationWithProgress2' is required here and is unavailable. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.
```

This is probably related to https://github.com/fsprojects/Paket/pull/3545 or https://github.com/fsprojects/Paket/pull/3530 (or both)

The following changes make me suspicious in the lockfile:

![image](https://user-images.githubusercontent.com/1866463/57142270-69ee1280-6dbc-11e9-8f47-cd2a7e9e067f.png)

![image](https://user-images.githubusercontent.com/1866463/57142284-707c8a00-6dbc-11e9-80ed-c1361371fc6e.png)

I think there is a second bug here, because even considering paket pulling the dependencies (as there might be frameworks which need it) it should filter them when considering a project building for `net461`. I'm wondering why people are not reporting this issue more often.

### Expected behavior

Paket shouldn't think `Microsoft.CSharp` has dependencies in this situation.

### Actual behavior

Paket thinks `Microsoft.CSharp` has dependencies.

### Known workarounds

Downgrade to `5.198.0`

**Comment by matthid** [comment]
So it seems to be related to the fact that we have a `netstandard2.0` project and a `net472` project which references the former. The `netstandard2.0` project seems to pull the `System.Runtime.WindowsRuntime` dependency and then the `net472` project no longer compiles.

Not sure why the previous fix doesn't work

**Comment by matthid** [comment]
I think this might be related to the filtering: I think restriction groups without "framework" are considered "generic" groups which "match everything" (see https://github.com/fsprojects/Paket/issues/3556#issuecomment-486179677). It feels like this is happening here: We consider the `.NETCore 5.0` now as a "fallback" group, which we shouldn't. Maybe there is even something else going on, because that doesn't explain the above changes on the lockfile, but it could explain the overall behavior.

@forki any change to take a look?

**Comment by matthid** [comment]
To reproduce run `paket update` on the following `paket.dependencies`

```
version 5.203.2
framework netstandard2.0
source https://api.nuget.org/v3/index.json
nuget Microsoft.CSharp
```

Now inspect the lockfile and see that paket "thinks" `Microsoft.CSharp` has dependencies which is shouldn't

**Comment by matthid** [comment]
With `version 5.206.0` this now creates:

```
RESTRICTION: == netstandard2.0
NUGET
  remote: https://api.nuget.org/v3/index.json
    Microsoft.CSharp (4.5)
```

Which is the expected result. Maybe we should add a test for this.

**Comment by forki** [comment]
Yes if you like it you should put a ring on it. Beyoncé Driven Development

Matthias Dittrich <notifications@github.com> schrieb am Sa., 11. Mai 2019,
11:54:
