### ISSUE TITLE
Paket install does not do a dotnet restore and does not notify Ionide

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#3577]
When you call `paket install`, I would expect dotnet restore to be implicitly called, but it is not - you have to explicitly call `dotnet restore` in order to get installed projects to show up. Using paket global tool version 5.207.0.

## Steps to reproduce
1. Create an empty F# console application.
1. Convert it to paket
1. Add `Saturn` to the dependencies file.
1. Add a paket references file and add Saturn as well.
1. Run paket install.
1. Try to open the `Saturn` namespace. Observe that the compiler does not recognise it in e.g. Ionide.
1. Run `dotnet restore`.
1. Observe that the namespace is now available.

## Sample dependencies file

```
source https://www.nuget.org/api/v2
storage: none

nuget Saturn
```

**Comment by forki** [comment]
yeah I think the question is: Do we want to call dotnet restore automatically at the end of paket install or paket restore. I would probably make things easier for IDEs /cc @matthid

**Comment by isaacabraham** [comment]
@forki would this lead to some kind of infinite loop - dotnet restore also calls paket restore doesn't it?

**Comment by forki** [comment]
well, in theory the new spawned paket just sees that everything is up-to-date and will exit early.

**Comment by matthid** [comment]
We can try but lots of questions arise and it is dangerous territory.
- what if no dotnet sdk is installed?
- where do we search?
- what if loops exist? -> very much possible when we cannot detect all target frameworks with our heuristic, for example if people use build.props or other msbuild tricks
- should we fail if dotnet fails?

**Comment by forki** [comment]
I think we would just try to call it and not fail. This would be just convenience for IDEs

**Comment by forki** [comment]
one question is why Ionide doesn't call dotnet restore after 5) automatically. cc @Krzysztof-Cieslak any ideas?

**Comment by forki** [comment]
OK I think I found the reason. It doesn't nukes the project.assets.json - which means Ionide can't know that it needs to restore again

**Comment by isaacabraham** [comment]
On a clean project there won't be a project.assets.json though

**Comment by forki** [comment]
can you please update the text with when you open ionide in the process

**Comment by forki** [comment]
>> On a clean project there won't be a project.assets.json though

dotnet new is calling dotnet restore. So yes you have that file hanging around

**Comment by isaacabraham** [comment]
Didn't even realise that :-)

**Comment by isaacabraham** [comment]
@forki thanks that's great.
