### ISSUE TITLE
Unclear error message when Paket fails to detect platform

### ISSUE THREAD

**Issue by object** [fsprojects/Paket#3581]
### Description

NB! This might not be an issue anymore because I experienced the problem with older Paket versions. If the error message is now improved, just close the issue.

### Repro steps

I updated FSharp.Core in a project using Fable from 4.6 to 4.6.2 and project no longer built. It failed at "dotnet restore" step with the error message:

> Paket failed with
> -> Extracting platforms from path 'netcoreapp2.1' failed
> 

It appeared to be that I was using an older Paket version (5.142.0, from 2018). Upgrading it to the recent Paket version (5.207.2) resolved the problem. However the error message was not clear, especially since the project didn't refer to 'netcoreapp2.1'.

### Expected behavior

If Paket fails to detect the platform, this is often due to outdated Paket version. So the error message might be: "Extracting platforms from path 'netcoreapp2.1' failed. This might be due to the outdated Paket version (X.XXX.X). Consider upgrading Paket."

**Comment by forki** [comment]
The error message could indeed be improved. Usually this error means that there is a new moniker available in one of the packages and either you just need to update paket or you need to send a PR that implements the handler for the monuker

**Comment by object** [comment]
Thanks. I can look into this since this one is up-for-grabs. I guess I am not the only one stupid who used a few hours trying to figure out what needs to be done after seeing this error.

**Comment by object** [comment]
@forki  What do you think about such message?

"Extracting platforms from path '%s' failed, a newer Paket version might support it, otherwise consider sending PR that implements the handler for this moniker."

**Comment by forki** [comment]
Maybe we should be less ambitious and ask people to open an issue

**Comment by object** [comment]
"Extracting platforms from path '%s' failed, a newer Paket version might support it, otherwise please open an issue for a missing platform handler."

???

**Comment by forki** [comment]
Yes.

Vagif Abilov <notifications@github.com> schrieb am Mi., 22. Mai 2019, 15:36:

**Comment by object** [comment]
PR sent.
