### ISSUE TITLE
Paket fails when running `dotnet pack` on a library after its version was changed.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsprojects/Paket#3584]
### Description

When the version of a library changes and a `dotnet pack` is invoked again, Paket gets confused, because there are many `*.nuspec` files in `<project-directory>/obj/<configuration>`: one for the old version, and another for the new one.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a library powered by Paket.

2. Set it a version in the project file, say `1.0.0`.

3. `dotnet pack`.

4. Set it to another version, say `2.0.0`.

5. `dotnet pack` once again.

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

A `nupkg` file with the new version.

### Actual behavior

Paket fails with an incorrect path error.

![A screenshot from my project exhibiting the bug](https://user-images.githubusercontent.com/12659251/58252005-bef2c800-7d6d-11e9-8754-2fc23812df15.png)

### Known workarounds

Delete the `nuspec` files before the packing. However, .NET Core SDK is smart enough to keep both of them and pick the correct one.

### Additional info

* The path Paket complains about might give us some insight. It is a semicolon-delimited list of the `nuspec` of a package version, and _the `obj/<configuration>` directory_.

* ~~I ran an experiment: I temporarily set my library's version to 2.0.0, without deleting the `obj` folder, and tried to pack again. The faulty path had the `nuspec` of version _4.0.0_; the _chronologically_ earliest, not the lexicographically one.~~ Actually, it was built for version 4.0.0, so never mind.

**Comment by enricosada** [comment]
That's because there is a glob who pass old nuspec and new nuspec, not just the current one.

I'll fix that. I'll assign to me

**Comment by enricosada** [comment]
fix in PR #3585
