### ISSUE TITLE
Paket 5.207.4 broke the FAKE release process and creates empty packages

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#3599]
### Description

You can see how I managed to pin it to that particular Paket release: https://github.com/fsharp/FAKE/pull/2341

In fact, I cannot even reproduce this locally, this only seems to happen in CI and in particular only Azure DevOps and sometimes in GitLab, but only Azure DevOps reproduces 100%

The diff is quite small and only a [single PR](https://github.com/fsprojects/Paket/pull/3585) was involved: https://github.com/fsprojects/Paket/compare/5.207.3...5.207.4

/cc @enricosada 

What's really bad is that the packaging process works but creates corrupt packages. The release process did catch the issue, because we bootstrap some of the packages.

You can download and inspect the packages from the build: https://dev.azure.com/fakebuild/FSProjects/_build/results?buildId=1123&view=results

![image](https://user-images.githubusercontent.com/1866463/59968108-5e090c00-9534-11e9-839c-a99a6db77aa0.png)

I tried to figure out what the problem is as only a single line changed, for example with [this commit](https://github.com/fsharp/FAKE/pull/2341/commits/a182531496a59b49905de5a405951ad4126e457c), but I couldn't figure it out.

So I boiled it down to a single line change in the targets file but I have no clue why or how it leads to broken packages.

### Repro steps

Update to `5.207.4` (or newer), see [this commit](https://github.com/fsharp/FAKE/pull/2341/commits/631cbebd67c11539079a5e345d3c3690522253de)

### Expected behavior

Release process should work as it did before

### Actual behavior

Paket-change leads to broken packages, which might be detected only after the package has been released without proper validation.

### Known workarounds

- Stay on `5.207.3` or lower
- Use previous targets file (and force paket to use it, by not calling `paket restore` or by checking out the old targets afterwards)

**Comment by matthid** [comment]
It seems like the change leads to `paket fix-nuspec` not being called anymore in the `dotnet pack Fake.sln` command

**Comment by matthid** [comment]
Oh my god I figured it out, it took a bit longer because paket was restoring the targets file within the process so all my attempts to add logging failed miserably.

I added the following warning message:
`<Warning Text='TEST: OutputPath: $(AdjustedNuspecOutputPath), All: "@(MyPaketNuspecFiles)", Version: "$(PackageVersion)", Command: $(PaketCommand) fix-nuspecs files "@(_NuspecFiles)" project-file "$(PaketProjectFile)"  ' />`

This is the result:

`TEST: OutputPath: obj\Release, All: "obj\Release\Fake.Api.Slack.5.15.1-alpha.1129.nuspec", Version: "5.15.1-alpha.1129+vsts.2fdb5b21981edf02be1fe6bf2b748197d9ead56d", Command: "d:\a\1\s\.paket\paket.exe" fix-nuspecs files "" project-file "d:\a\1\s\src\app\Fake.Api.Slack/Fake.Api.Slack.fsproj"`

So the problem is that `PackageVersion` includes the Semver "Build metadata" while the file doesn't...

@enricosada Any idea how to fix? Is there another msbuild variable we could use?

**Comment by matthid** [comment]
I think we need at least:
- Error out if we cannot found a nuspec at all
- Fix the issue at hand and add a test ...

**Comment by forki** [comment]
Please send me a pull request. I will release asap

Matthias Dittrich <notifications@github.com> schrieb am So., 23. Juni 2019,
00:27:

**Comment by matthid** [comment]
@forki I'd like to but I don't know how to fix, the only thing that probably works is reverting that PR :/

**Comment by forki** [comment]
Ok. Please send me a pr with the revert and then we need to talk to @enricosada to find a new approach

**Comment by forki** [comment]
Or never mind. I'll do the revert myself

**Comment by matthid** [comment]
Give me a bit, I might find another solution

**Comment by matthid** [comment]
See https://github.com/fsprojects/Paket/pull/3600, it is a bit of a hack so we probably should let the CI test it
