### ISSUE TITLE
Paket 5.212.0 doesn't extract packages copied from the dotnet Nuget fallback folder

### ISSUE THREAD

**Issue by BillHally** [fsprojects/Paket#3606]
### Description

When a Nuget package is referenced which is available from `C:\Program Files\dotnet\sdk\NuGetFallbackFolder`, only the .`nupkg` file is copied to `~/.nuget/packages/<package>/<version>` i.e. the package is not extracted.

### Repro steps

1. Reference a version of a Nuget package which is available in the `dotnet` `NuGetFallbackFolder`

2. Run package restore

I've not created a repository or attached an archive for this issue, because which packages will show the issue depends on a user's own machine. For example, this `paket.dependencies` showed the issue on my machine:

```
source https://www.nuget.org/api/v2

nuget System.Composition 1.0.31
```

but it won't on a machine which already has that specific version of that package installed.

### Expected behavior

The package should be copied from the Nuget fallback folder to the appropriate location in the user's Nuget packages folder and then extracted there.

### Actual behavior

The package is copied to the appropriate location in the user's Nuget packages folder as expected, but is not extracted.

### Known workarounds

Pin the version of Paket used to less than 5.212.0 e.g. add this to the top of the paket.dependencies file:

```
version 5.211.0
```

**Comment by forki** [comment]
can you please retry with 5.213.0 which will be available in about 5min? thanks!

**Comment by BillHally** [comment]
Yes, that fixed it - thanks!
