### ISSUE TITLE
net471 doesn't default to netstandard but a older net framework

### ISSUE THREAD

**Issue by BlythMeister** [fsprojects/Paket#3613]
When taking a dependency into a net471 project, i would expect a netstandard2.0 dependency to be favoured over an older (pre standard) framework version.

Since netstandard2.0 is fully compatible with net471, a project maintainer is unable to support newer features in an older framework version (as seen here: https://github.com/EasyNetQ/EasyNetQ/issues/623#issuecomment-510444144)

This means that if a project maintainer is using a multi target switch to support the newer features, and is publishing these as netstandard2.0 and say net451 paket will always default to the net451 version because it's framework.

Short of asking the maintainer to also publish the netstandard2.0 version as net471 (which isn't always practical) would it not make more sense for paket to use netstandard2.0 with the same level of "penalty" as the directly compatible framework version? - or at least give users a preference that they would like to use netstandard over older netframework versions.

**Comment by matthid** [comment]
This has nothing to do with paket. Target framework preferences are spec'd by NuGet and I doubt they will change them. In any case you should open an issue over there.

**Comment by BlythMeister** [comment]
so paket isn't the one choosing to use the net451 over netstandard2.0 when both are present in the package?

I'm a little confused, since paket is adding the reference to the net471 project and stating to use the net451 version.  for example:

```
<Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.7.1'">
      <ItemGroup>
        <Reference Include="EasyNetQ">
          <HintPath>..\..\packages\EasyNetQ\lib\net451\EasyNetQ.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```
on package: https://www.nuget.org/packages/EasyNetQ/ which has net451 and netstandard2.0

**Comment by matthid** [comment]
The code is in paket, but the spec is on NuGet, we follow the spec closely.

**Comment by matthid** [comment]
What I mean is: If you use nuget client or dotnet sdk it will/should reference the same dll.
If we diverge here this change will not be in dotnet sdk style projects as there we only forward to NuGet.

As we don't care to much about legacy projects we won't do such a radical change for old-style projects only. And I don't see this working on dotnet sdk style projects

**Comment by BlythMeister** [comment]
Ok, I think I understand.

Thanks for clarifying.

I'm going to speak to this project maintainer and see if we get a net461 version added with the releavant newer framework features added!
