### ISSUE TITLE
Paket breaks nuget symbol packages in snupkg format 

### ISSUE THREAD

**Issue by hravnx** [fsprojects/Paket#3615]
### Description

Paket ignores symbols package format 'snupkg' and always generates the legacy format on `dotnet pack`

### Repro steps

1. With paket 5.215.0 and some dotnet core sdk installed (tested with both 2.2.301 and 3.0 preview6) create a new blank directory (here called `paket-issue`) somewhere and cd into it.
2. Run `dotnet new classlib` and confirm that the project was successfully created
3. Open the csproj file in a text editor and add the following under the `<PropertyGroup>` tag:
   ```xml
   <PackageId>paket_issue</PackageId>
   <Version>0.1.0-alpha</Version>
   <IncludeSymbols>true</IncludeSymbols>
   <SymbolPackageFormat>snupkg</SymbolPackageFormat>
   ```
4. Run `dotnet pack` and observe that two packages are created under `./bin/Debug`:
   - paket_issue.0.1.0-alpha.nupkg
   - paket_issue.0.1.0-alpha.snupkg
5. Delete the `obj` and `bin` folders
6. Run `paket convert-from-nuget`
7. Run `dotnet pack` again.

### Expected behavior

Generated `snupkg` symbols package

### Actual behavior

Legacy `symbols.nupkg` package was generated

### Known workarounds

None.

In the generated `Paket.Restore.targets` file there is an entry for the `<PackTask />` containing:

```xml
    <PackTask Condition="$(UseMSBuild16_0_Pack)"
    ... stuff ...
    SymbolPackageFormat="symbols.nupkg"
    ... more stuff ...
    />
```

which suggests that the value is hardcoded to the legacy format. Changing it to `snupkg` or `$(SymbolPackageFormat)` both produced an error:

    error NU5005: Failed to build package. Ensure '/path/to/paket-issue/obj/Debug/paket_issue.0.1.0-alpha.nuspec' includes source and symbol files.

**Comment by teo-tsirpanis** [comment]
`Paket.Restore.targets` was fixed by #3636, but Paket still has problems in generating `.snupkg` files, as shown in #3685.

I suggest you close this issue.
