### ISSUE TITLE
Paket update problem in sdk style project

### ISSUE THREAD

**Issue by Sylwekqaz** [fsprojects/Paket#3618]
### Description

After package update (in `paket.dependencies` and `paket.lock`) and restore packages, old packages are copied to `bin` dir. Probably they are cached in `obj\project.assets.json`.

### Repro steps

1. Create new sdk style project (e.g. net core project) and add packet

    Example main function

    ```csharp
    static void Main(string[] args)
    {
        var version = FileVersionInfo.GetVersionInfo("Newtonsoft.Json.dll");
        Console.WriteLine(version.FileVersion);
        Console.WriteLine(JsonConvert.SerializeObject(new
            {
                version.ProductName,
                version.FileVersion,
                version.ProductVersion,
            },
            Formatting.Indented));
        Console.ReadKey();
    }
    ```

2. Reference package (e.g.  `Newtonsoft.Json = 12.0.1`)
3. Compile & run program

    ```bash
    paket install
    dotnet restore
    dotnet run
    # Output
    # 12.0.1.22727
    # {
    #   "ProductName": "Json.NET",
    #   "FileVersion": "12.0.1.22727",
    #   "ProductVersion": "12.0.1+509643a8952ce731e0207710c429ad6e67dc43db"
    # }
    ```

    To bin folder was copied `Newtonsoft.Json.dll` in version `12.0.1.22727`, with is correct.

4. Update package in `paket.dependencies` (e.g.  `Newtonsoft.Json = 12.0.2`)
5. Compile & run program

    ```bash
    paket install
    dotnet restore
    dotnet run
    # Output
    # 12.0.1.22727
    # {
    #   "ProductName": "Json.NET",
    #   "FileVersion": "12.0.1.22727",
    #   "ProductVersion": "12.0.1+509643a8952ce731e0207710c429ad6e67dc43db"
    # }
    ```

    To bin folder was copied `Newtonsoft.Json.dll` in version `12.0.1.22727`, with is not  correct.

### Expected behavior

Packages should be restored with correct version

```bash
dotnet run
# 12.0.2.23222
# {
#   "ProductName": "Json.NET",
#   "FileVersion": "12.0.2.23222",
#   "ProductVersion": "12.0.2+4ab34b0461fb595805d092a46a58f35f66c84d6a"
# }
```

### Actual behavior

Packages are restored with old version version

```bash
dotnet run
# Output
# 12.0.1.22727
# {
#   "ProductName": "Json.NET",
#   "FileVersion": "12.0.1.22727",
#   "ProductVersion": "12.0.1+509643a8952ce731e0207710c429ad6e67dc43db"
# }
```

Packages probably are cached in `obj\project.assets.json` and restored in old version to `bin` folder. Rebuild/clean project dosent help.

### Known workarounds

Delete `obj` folders in projects.

**Comment by forki** [comment]
Cc @matthid is that related to "fast restore"?

Sylwester <notifications@github.com> schrieb am Mo., 22. Juli 2019, 10:32:

**Comment by matthid** [comment]
maybe, what 'should' happen is that lockfile gets updated which invalidates the various cache files and the msbuild integration should pick it up if required.
In this particular scenario paket install should update all the cache files and dotnet restore should be fast

**Comment by danyx23** [comment]
I think I ran into this problem as well in a SAFE stack application. After upgrading paket.dependencies to bump a library from version 3.1 to 3.2 and running paket install (or doing the same via paket update) the paket.lock file contains the correct new entry but the /src/Client/obj/Client.fsproj.reference file still lists the old library version so Fable restores this old library version and then I wondered why the behaviour did not change.

Deleting the obj folder forces a refresh of this file and then everything works as expected.

**Comment by forki** [comment]
@danyx23 any chance for repro?

**Comment by forki** [comment]
ok I think I found the issue. we are nuking he assets file butkeep all Paket files intact. this is a bug

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/commit/b13d8069573860420e43eb98222f0b9ae06741f9 <- waiting for CI

**Comment by danyx23** [comment]
@forki I have this repo that I was using as the example (https://github.com/danyx23/safe-stack-sweet-alert-debug) that is currently at Elmish.SweetAlert 3.1 and if you build and then upgrade to 3.2 it exhibits the problem. I'll try the new version as soon as it is published - thanks for the fast fix!

**Comment by forki** [comment]
publish. please give it a try

**Comment by danyx23** [comment]
@forki thanks! The bug that I described is fixed in the new version but the delete is too agressive - it deletes the paket.references files in the source directories which then breaks the builds!

**Comment by baronfel** [comment]
Agree with @danyx23, just saw this happen to me as well. luckily `git checkout` is a thing :)

**Comment by forki** [comment]
Revert is released

Chet Husk <notifications@github.com> schrieb am Mi., 4. Sep. 2019, 19:04:

**Comment by forki** [comment]
5.218.0-alpha001 should be available in couple of minutes. Can you please
try it?

Am Mi., 4. Sept. 2019 um 19:26 Uhr schrieb Steffen Forkmann <
sforkmann@gmail.com>:

**Comment by forki** [comment]
new alpha should be available

**Comment by danyx23** [comment]
Works like a charm. Thanks a lot for your great work @forki!

**Comment by forki** [comment]
cool so I'm releasing it properly. Thanks for your help with testing
