### ISSUE TITLE
Make paket.references file optional for single projects?

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#3640]
When you create a simple, single project application, your references and dependencies file is normally a 1:1 match. What's the thoughts on making the references file optional in such cases (and simply reading the dependencies as references), or for even making that a setting i.e. if no references file is found, simply defer to the dependencies file for everything?

**Comment by BlythMeister** [comment]
How many single project things do people create?
I mean, my minimum is normally 2.  The app, and the tests.

**Comment by isaacabraham** [comment]
Not everyone uses tests :-)

I'm also thinking about lowering the barrier to entry to Paket here - people are used to either packages.config, or package reference (which is embedded in the cs/vb/fsproj). Moving to paket means understanding three different files with different needs.

Sometimes someone will just create a simple application, try out paket, and might get confused from the three files ("why do I need all these files? I just add an element to my project with nuget!") and give up, or ask questions like "why do I need to add the same element into both the deps and refs file".

I often demo Paket to people and here this sort of thing a lot of the time i.e. Paket might be better for "big" projects but for small ones, NuGet is simpler to use. We should try to reduce the cognitive overhead and make it easier for people to try it out.

**Comment by isaacabraham** [comment]
Closing

**Comment by isaacabraham** [comment]
Replaced by #3724
