### ISSUE TITLE
add-credentials for DevOps returns 401

### ISSUE THREAD

**Issue by mauriciomagni** [fsprojects/Paket#3643]
### Description

I am trying to consume a DevOps feed using Paket. 
I have created a nuget, deployed it into DevOps and now I am trying to have Paket consuming it.
I was able to install the nuget using the Nuget Management tool built in VS2019.
When executing "paket install" I got this message:
"Could not load resources from 'devops url': Unauthorized (401)

I tried executing "paket config add-credentials 'devops url'", and I get this message as response:
"UnauthorizedAccessException: Credentials or the URL for source 'devops url' are invalid"

Regarding add-credentials commands I am not sure what values I should provide. I tried different options for username/password tuples:
1. Microsoft credentials: microsoft account (email) / microsoft account password
2. DevOps Alternate Credentials: username / password
3. Personal Access Token: username / token

All of them returned the same message.

I am almost sure I am doing something wrong but I cannot get it. Any help will be greatly appreciated.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a nuget package
2. Deploy it into visual studio online (devops)
3. Include the source in NuGet configuration
4. Include the source in paket.dependencies
5. Include the reference in paket.dependencies
6. Include the reference in paket.references
7. Execute paket install

### Expected behavior

I expect the package to be downloaded and the paket.lock file updated

### Actual behavior

Unauthorized (401) error is raised

### Known workarounds

not know

**Comment by mauriciomagni** [comment]
Issue solved.

**Comment by matthid** [comment]
@mauriciomagni please feel free to post your solution just in case someone runs into a similar issue

**Comment by mauriciomagni** [comment]
hello everybody, this is what I did to make it work, I hope it helps forward
1. Follow instructions here:
https://github.com/microsoft/artifacts-credprovider#azure-artifacts-credential-provider
Basically, it boils down to install CredentialProviders in $HOME\.nuget\plugins
2. Create, in DevOps (aka Visual Studio Online) an alternative credentials
3. Execute this command to grant access to your feed:
`paket config add-credentials "https://[YOUR STUFF].pkgs.visualstudio.com/_packaging/StorkwayNugets/nuget" --verify --username "[Alternate Credential UserName]" --password "[Alternate Credential Password]" --verbose`
Please, not that when executing 'paket config add-credentials' the ending part of the feed url (/v3/index.json) has been removed. 

After following this 3 steps everything worked. I guess I made some mistake or missed some step in my first attempts.

Kind regards,
Mauricio

**Comment by tforkmann** [comment]
@mauriciomagni I just ran into the same error. Could you please tell me how the source looks like in paket.dependencies file?
Did you used the netcore or the netfx credential provider?

Thanks in advance!

**Comment by mauriciomagni** [comment]
Hello @tforkmann 

My paket.dependencies looks like (some packages remove to avoid wasting space):
`
source https://www.nuget.org/api/v2
source https://[YourCompany].pkgs.visualstudio.com/_packaging/StorkwayNugets/nuget/v3/index.json
framework: NetCoreApp2.2
nuget FSharp.Core
nuget FSharp.Data
nuget FSharp.Data.SqlClient
nuget [YourNugetPackageName]
`
In my last attempt, I did not have to remove "/v3/index.json"... so try that yourself and make sure you do not get an error when adding credentials to paket.

Regards,

**Comment by tforkmann** [comment]
Hi Mauricio,

I tried to add the credentials by running the following cmd:
paket config add-credentials "https://pkgs.dev.azure.com/[MyCompany]/_packaging/[Packagename]/nuget" --verify --username "MyUsername" --password "MyPassword" --verbose

I got following error message:
```
Paket failed with
-> UnauthorizedAccessException: Credentials or the URL for source https://pkgs.dev.azure.com/[MyCompany]/_packaging/[Packagename]/nuget are invalid
   StackTrace:
        bei Paket.ConfigFile.askAndAddAuth(String source, String passedUserName, String passedPassword, String authType, Boolean verify)
        bei <StartupCode$Paket-Core>.$PublicAPI.AddCredentials@247-5.Invoke(Unit unitVar0)
        bei Paket.Utils.RunInLockedAccessMode[a](String lockedFolder, FSharpFunc`2 action)
        bei Paket.Program.handleCommand@832-5.Invoke(ParseResults`1 results)
        bei Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        bei Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        bei Paket.Program.handleCommand(Boolean silent, Command command)
        bei Paket.Program.main()
```

**Comment by mauriciomagni** [comment]
hello Tim

Try including the ending part of the url: /v3/index.json; I know I wrote
that I removed it, but currently it is working with this ending part.
Hope it works!

Regards,
Mauricio
