### ISSUE TITLE
"copy_local: false" has no effect

### ISSUE THREAD

**Issue by yaakov-h** [fsprojects/Paket#3645]
### Description

There seem to be a bit of a history of this (https://github.com/fsprojects/Paket/issues/3154, https://github.com/fsprojects/Paket/issues/3186, https://github.com/fsprojects/Paket/issues/3352).

In my scenario, I'm using the new .NET SDK project format to build a .NET Framework 4.6 assembly.

`paket.dependencies`:

<details>

```
version 5.216.0 --force-nuget -v

group CsProjCop
	source https://api.nuget.org/v3/index.json
	framework: net46, net472
	storage: none

	nuget Microsoft.Build.Locator
	nuget YamlDotNet

group MSBuild
	source https://api.nuget.org/v3/index.json 
	framework: net46, net472
	storage: none
	lowest_matching: true
	strategy: min
	
	copy_local: false
	copy_content_to_output_dir: never
	
	nuget Microsoft.Build >= 15.0
	nuget Microsoft.Build.Framework >= 15.0
	nuget Microsoft.Build.Utilities.Core >= 15.0
```

</details>

`paket.references`:
<details>

```
group CsProjCop
	Microsoft.Build.Locator
	YamlDotNet

group MSBuild
	Microsoft.Build copy_local: false
	Microsoft.Build.Framework copy_local: false
	Microsoft.Build.Utilities.Core copy_local: false
```

</details>

### Repro steps

1. Clone `https://github.com/yaakov-h/paket-copy-local-repro`
1. Run `build.cmd`

### Expected behavior

1. The build succeeds
1. `bin\net46` DOES NOT contain:
    - `Microsoft.Build.dll`
    - `Microsoft.Build.Framework.dll`
    - `Microsoft.Build.Utilities.Core.dll`

### Actual behavior

1. The build fails due to an error from `Microsoft.Build.Locator`'s targets file, warning that `Microsoft.Build.*` is being copied to the output directory.
2. `bin\net46` DOES contain:
    - `Microsoft.Build.dll`
    - `Microsoft.Build.Framework.dll`
    - `Microsoft.Build.Utilities.Core.dll`

**Comment by xperiandri** [comment]
I have the same issue with `netstandard2.0` project

**Comment by yaakov-h** [comment]
git-bisect puts the blame at `88620a9` (#3417).

Any idea what's happened here, @matthid?

**Comment by yaakov-h** [comment]
This seems wrong to me:

```
<ExcludeAssets Condition=" '%(PaketReferencesFileLinesInfo.Splits)' != '6' And %(PaketReferencesFileLinesInfo.AllPrivateAssets) == 'exclude'">runtime</ExcludeAssets>
```

Shouldn't `%(PaketReferencesFileLinesInfo.AllPrivateAssets) == 'exclude'` be `%(PaketReferencesFileLinesInfo.AllPrivateAssets) == 'true'`?
