### ISSUE TITLE
Documentation page for bootstrapper contains HTML tags in title element

### ISSUE THREAD

**Issue by yaakov-h** [fsprojects/Paket#3658]
![image](https://user-images.githubusercontent.com/426009/65099179-c7e96280-da0a-11e9-83b6-372aa20dfa71.png)

That probably shouldn't be there, right?

**Comment by JohnyWS** [comment]
You're right - if you look at the other titles in the same part of the docs menu, you can see they follow a pattern of "`# The <something> file`" (replace "<something>" with the item in question), whereas [the paket.bootstrapper.exe page](https://fsprojects.github.io/Paket/bootstrapper.html) does not, but instead includes the backtick notation around file paths, that are used everywhere else in the page.

Would you like to have a go at it, as a PR? It seems to be fixable by just utilizing the same header pattern as on the other pages. If not, I'll get around to it. :)
