### ISSUE TITLE
dotnet restore <solution name> takes several minutes to finish

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#3661]
The log is full of this stuff:
```
 Paket version 5.219.2
  Starting restore process.
  Performance:
   - Disk IO: 8 milliseconds
   - Runtime: 1 second
  Paket version 5.219.2
  Starting restore process.
  Performance:
   - Disk IO: 7 milliseconds
   - Runtime: 1 second
  Paket version 5.219.2
  Starting restore process.
  Performance:
   - Disk IO: 6 milliseconds
   - Runtime: 1 second
  Paket version 5.219.2
  Starting restore process.
  Performance:
   - Disk IO: 9 milliseconds
   - Runtime: 1 second
  Paket version 5.219.2
  Starting restore process.
  Performance:
   - Disk IO: 6 milliseconds
   - Runtime: 1 second
```
and so on. It outputs a block of `Starting restore process...` every ~1 second. 

The CPU load looks like this:

![image](https://user-images.githubusercontent.com/873919/65412978-09a64e80-ddf9-11e9-8c75-029f9321287c.png)

There was no such issue ~a month or two ago, everything was fast.

**Comment by matthid** [comment]
:(

**Comment by forki** [comment]
@matthid what was the requirement for fast restore? Certain msbuild
version?

Matthias Dittrich <notifications@github.com> schrieb am Mo., 23. Sep. 2019,
11:06:

**Comment by matthid** [comment]
I don't think it has something to do with msbuild version, if we fallback to slow mode we trigger a warning. I think we probably just broke it again with one of the recent changes.

**Comment by vasily-kirichenko** [comment]
If it helps, it takes this long on the first run after switching branches, the consequent calls are fast (~6 seconds).

**Comment by matthid** [comment]
Hm it depends a bit on what changed between branches
- If the lockfile changed it should detect it, run a full restore and "be fast"
- If only the references files on the project changed it will be slow for those projects and there is no way around
- If nothing changed it should be fast

I guess this might be related to our recent "fix" where we just delete the paket cache files, but instead we should re-generate them.

**Comment by vasily-kirichenko** [comment]
Switching from the magic mode to the normal one has solved the problem. It seems the magic mode created a real paket.exe file somewhere on the file system and that place is not in my antivirus exclusion list. Could anybody explain in detail how the magic mode works? Is there a stable location where the real paket.exe is launched?

**Comment by forki** [comment]
@vbfox in https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode we just say "to a temporary location". could we clarify that?

**Comment by JohnyWS** [comment]
Would love to hear about that too, because we're also having AV issues in our environments, and are using magic mode..! :) Any update on that @forki or @matthid ? :)

**Comment by JohnyWS** [comment]
Just found it in the source code:
// In magic mode the real 'paket.exe' is downloaded to the system temporary directory with a
            // stable name depending on the bootstrapper location. It give two advantages :
            //  - Multiple executions of the same boostrapper will use the same path and can reuse the
            //    downloaded executable if needed. All of that without needing any additional state as
            //    our location on the file system act as the only state needed.
            //  - There is no risk to have two bootstrapper instances in two different locations
            //    accessing the same file as their path depends on the bootstrapper path.

**Comment by JohnyWS** [comment]
[Is on line 359 in the argument parser](https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/ArgumentParser.cs)

Could we perhaps use a work folder instead inside the .paket folder, which should then be ignored in .gitignore?

That would avoid issues with AV like the one we too are seeing.

**Comment by forki** [comment]
we should do 2 things:
1) that comment that you fould should go to docs in https://fsprojects.github.io/Paket/bootstrapper.html
2) we should allow to use a parameter in paket.bootstrapper.exe.config to allow a different path.

PRs for this are very welcome

**Comment by JohnyWS** [comment]
@forki yeah I was just wondering if a _work folder wouldn't be a good addition anyways, since that could than contain various cache, to bump up performance even more. Do we know how long all the config parsing takes if a lot of processes are doing it simultaneously?

I'll look at option 2 first, to see if I got it right, before adjusting the docs.

**Comment by JohnyWS** [comment]
Adding it to the config conflicts a bit with the `--output-dir=` commandline argument though. I'll try to make some sort of compromise here.

**Comment by JohnyWS** [comment]
PR created.

**Comment by forki** [comment]
new bootstrapper released
