### ISSUE TITLE
Various AspNetCore packages upgraded to .Net Core 3.0 incorrectly

### ISSUE THREAD

**Issue by markpattison** [fsprojects/Paket#3666]
### Description

Packages are being updated to versions which don't support the specified framework.

### Repro steps

Start with this working [repo](https://github.com/markpattison/paket-issue).

This builds and runs fine with `fake build -t run`.

`paket outdated -g Server` lists five Microsoft packages to update from 2.2 to 3.0.0.

1. `paket update -g Server`
2. `fake build -t run`

#### For background only

I have the .Net Core 3.0 SDK installed.  Repo was created using:

1. SAFE-Stack template 1.18.0 with options `--js-deps npm --communication remoting`
2. Server project changed to `net461` in both the project file and `paket.dependencies`
3. `paket update --keep-major -g Server`

### Expected behavior

Packages in a `net461` build group are not updated to versions which do not support it.

### Actual behavior

Building the Server project fails with the following error message:

`error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 3.0.0 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Microsoft.AspNetCore.Authentication.JwtBearer 3.0.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)`

### Known workarounds

Only update using `paket update --keep-major`

**Comment by forki** [comment]
Keep major and downgrade to NET 461? Does this make sense?

Mark Pattison <notifications@github.com> schrieb am Mi., 25. Sep. 2019,
11:50:

**Comment by markpattison** [comment]
In my real project, I'm depending on some old .NET Framework libraries.

The `--keep-major` update in step 3 is not necessary to reproduce the issue, but it helps show which packages are causing the problem.

> 
> Keep major and downgrade to NET 461? Does this make sense?

**Comment by matthid** [comment]
This behavior is basically the design change of nuget<>paket. But the sad reality is paket does a very bad job making this scenario user friendly to deal with.
Life is good as long as you stay on latest, as soon as you try to use older packages with lots of dependencies not so much...

**Comment by markpattison** [comment]
Sorry, I thought it was a genuine bug - my thinking was that the 3.0 packages would somehow declare themselves to be .Net Core only.

No problem to close if this is the best feasible behaviour.

**Comment by forki** [comment]
ok I looked into it. This is basically an unsupported use case together with nuget bug.

first: the JWT for 2.2 is also not really compatible with net461 since it's netstandard 2.0 - this is based on pure luck and MS has retracted it's statement that they are compatible.

Now after the update Paket detects that it's incompatible and tells nuget not to take it.

![image](https://user-images.githubusercontent.com/57396/65592648-45731c80-df8f-11e9-9b88-6ab8ce86a170.png)


But NuGet/MSBuild decides on their own to just take it anyway
