### ISSUE TITLE
`dotnet restore` does not work on Linux when installed as global tool

### ISSUE THREAD

**Issue by bash** [fsprojects/Paket#3671]
### Description

Paket version:  5.219.6
Last Paket version without this issue: 5.219.5

`dotnet restore` fails on Linux with the following message when paket is installed using `dotnet tool install -g paket`

The issue seems to be the following line in `Paket.Restore.targets`:
```xml
<PaketCommand Condition=" '$(PaketCommand)' == '' AND '$(_PaketExeExtension)' == '' ">dotnet "$(PaketExePath)"</PaketCommand>
```

### [Repro steps](https://github.com/bash/paket-issue-3671/blob/master/.travis.yml)

Please provide the steps required to reproduce the problem

1. Install paket: `dotnet tool install -g paket`
2. Run `paket install`.
3. Run `dotnet restore`.

GitHub Repository with Travis CI setup: https://github.com/bash/paket-issue-3671

### Expected behavior

No error.

### [Actual behavior](https://travis-ci.com/bash/paket-issue-3671/builds/129455412)

```
No executable found matching command "dotnet-paket"
/home/travis/build/bash/paket-bug/.paket/Paket.Restore.targets(139,5): error MSB3073: The command "dotnet "paket" restore" exited with code 1. [/home/travis/build/bash/paket-issue-3671/PaketBug/PaketBug.csproj]
The command "dotnet restore" exited with 1.
```

### Known workarounds

Installing an older version of paket:
```
dotnet tool install -g paket --version 5.219.5
```

**Comment by forki** [comment]
related: https://github.com/fsprojects/Paket/pull/3668
@atlemann do you see a fix to support both?

**Comment by forki** [comment]
maybe something about order of the lines?

**Comment by atlemann** [comment]
Ops, hmmm... Not sure. I'll have to investigate.

**Comment by forki** [comment]
would appreciate any help!

**Comment by atlemann** [comment]
Not near a computer, but does `dotnet tool run paket` invoke the global tool? It works for local. But that command might only be available on 3.0 SDK

**Comment by bash** [comment]
Doesn't seem to work:
```
~> dotnet --version
3.0.100
~> dotnet tool run paket
Cannot find a tool in the manifest file that has a command named 'paket'.
```

**Comment by NatElkins** [comment]
Just got hit by this too (on macOS).  Problem is that the new condition (checking for empty extension) also applies to using `paket xxx`.

Here's a fix.  Add this to Paket.Restore.targets (make sure it's not in a property group, so just inside the Project element:

```msbuild
<Target Name="LocalPaketToolCheck" BeforeTargets="Restore">
  <Exec Command="dotnet paket --version" >
    <Output TaskParameter="ExitCode" PropertyName="PaketLocalToolExitCode"/>
  </Exec>
</Target>
```

That will run `dotnet paket --version` and assign the exit code to a value called `PaketLocalToolExitCode`.

Then change the condition for `PaketCommand` for `dotnet paket` to this:

```
    <PaketCommand Condition=" '$(PaketCommand)' == '' AND '$(_PaketExeExtension)' == '' AND '$(PaketLocalToolExitCode)' == 0 ">dotnet "$(PaketExePath)"</PaketCommand>
```

Maybe some people can give this a try.  Here's how:

1. Navigate to your repo.
2. Run `export PAKET_SKIP_RESTORE_TARGETS=true`.  This will prevent Paket from re-extracting the targets file it came with.
3. Make the changes I specified above.
4. Run `dotnet restore` on your solution file or project file.

**Comment by atlemann** [comment]
I'll try this now

**Comment by forki** [comment]
Please semd PR if it works. Thanks

Atle Rudshaug <notifications@github.com> schrieb am Fr., 27. Sep. 2019,
21:53:

**Comment by atlemann** [comment]
My MSBuild-fu is not great and I'm struggling to see how it works. I try to print messages inside the task, but they don't show up. If I try to print a message inside a target with `BeforeTargets="Build"`, then I do get a message.

**Comment by atlemann** [comment]
I can actually leave out the Target and just add that last condition and it "works", since it seems to ignore the line and local tool is broken again.

**Comment by atlemann** [comment]
So if I add these two at the top of `Paket.Restore.targets` I only see `--- Before build ---` message.

```xml
  <Target Name="Msg1" BeforeTargets="Restore">
    <Message Text="--- Before restore ---" Importance="high"/>
  </Target>

  <Target Name="Msg2" BeforeTargets="Build">
    <Message Text="--- Before build ---" Importance="high"/>
  </Target>
```

**Comment by atlemann** [comment]
https://github.com/NuGet/Home/issues/4781

**Comment by NatElkins** [comment]
Oops yeah I guess it's actually `CollectPackageReferences`.

**Comment by atlemann** [comment]
Both of these worked separately: `<Target Name="Msg1" BeforeTargets="ResolvePackageAssets;CollectPackageReferences">`

**Comment by atlemann** [comment]
But now it blows up with this error:

```
error MSB3073: The command "dotnet paket --version" exited with code 1
```

**Comment by atlemann** [comment]
`<Exec Command="dotnet paket --version" ContinueOnError="True">` fixes that

**Comment by atlemann** [comment]
but it ends up being very verbose and spitting out a bunch of warnings, which is not great.

**Comment by NatElkins** [comment]
Add this to the Exec task:
`    <Exec Command="dotnet paket --version" StandardOutputImportance="low" StandardErrorImportance="low" >`

**Comment by NatElkins** [comment]
That will suppress the messages, unless someone has some kind of MSBuild debug setting set.

**Comment by atlemann** [comment]
That removed the output from the Exec command, but I still see lots of these in the output:

```
.... .paket/Paket.Restore.targets(6,5): warning MSB3073: The command "dotnet paket --version" exited with code 1. ....
    10 Warning(s)
    0 Error(s)
```

**Comment by atlemann** [comment]
Hmmm....It's getting late and I think this solution spits out too much warnings. Not sure what the alternative should be. Maybe search for a `dotnet-tools.json` file somehow, then use `ReadLinesFromFile` and `FindInList` to see if there is a `"paket"` item in any of them?

**Comment by NatElkins** [comment]
@atlemann I'm not getting any warnings.  Maybe we can hop on a Google Hangout or something to figure out why you're seeing the messages, or how you're workflow is differing from mine?

If you're on the FSSF Slack, my username is Nelkins.

**Comment by forki** [comment]
Should I revert for now?

**Comment by atlemann** [comment]
Yes, maybe. I don't think this fix works. It seems the target is invoked after the paketcommand has already been resolved, so it doesn't work for local tool. But it was getting a bit late, so I might have missed something.

Maybe another fix could be to look for that tools manifest file and check if paket is in there?

**Comment by forki** [comment]
Oh that sounds promising. I think I will wait for that.

Atle Rudshaug <notifications@github.com> schrieb am Sa., 28. Sep. 2019,
08:32:

**Comment by atlemann** [comment]
But I'd rather support local tool that global tool, since you can pin a paket version in your repo and bootstrap with 'dotnet tool restore'

**Comment by atlemann** [comment]
Ok, I can try that instead tonight.

**Comment by forki** [comment]
The golbal tool is advertised in many places. We should still support it

**Comment by NatElkins** [comment]
@atlemann Okay you're right I prematurely declared victory before.  I think I've actually got it this time, although it's kind of horrible (but let's be honest, anything having to do with MSBuild is horrible).

Add this target at the top:
```xml
  <Target Name="SetPaketCommand" >
    <!-- Call 'dotnet paket' and see if it returns without an error. Mute all the output. -->
    <Exec Command="dotnet paket --version" IgnoreExitCode="true" StandardOutputImportance="low" StandardErrorImportance="low" >
      <Output TaskParameter="ExitCode" PropertyName="LocalPaketToolExitCode" />
    </Exec>

    <!-- This is just a debug statement. -->
    <Message Importance="high" Text="$(PaketCommand) - paket command should be empty | $(LocalPaketToolExitCode) - code" />

    <!-- Then we go through our normal steps of setting the Paket command.
         I called it InternalPaketCommand here because apparently properties aren't available
         outside the targets they are declared in. -->
    <PropertyGroup>
      <_PaketExeExtension>$([System.IO.Path]::GetExtension("$(PaketExePath)"))</_PaketExeExtension>
      <InternalPaketCommand Condition=" '$(InternalPaketCommand)' == '' AND '$(_PaketExeExtension)' == '.dll' ">dotnet "$(PaketExePath)"</InternalPaketCommand>
      <InternalPaketCommand Condition=" '$(InternalPaketCommand)' == '' AND '$(_PaketExeExtension)' == '' AND $(LocalPaketToolExitCode) == 0">dotnet "$(PaketExePath)"</InternalPaketCommand>
      <InternalPaketCommand Condition=" '$(InternalPaketCommand)' == '' AND '$(OS)' != 'Windows_NT' AND '$(_PaketExeExtension)' == '.exe' ">$(MonoPath) --runtime=v4.0.30319 "$(PaketExePath)"</InternalPaketCommand>
      <InternalPaketCommand Condition=" '$(InternalPaketCommand)' == '' ">"$(PaketExePath)"</InternalPaketCommand>
    </PropertyGroup>

    <!-- The way to get a property to be available outside the target is to use this task. -->
    <CreateProperty Value="$(InternalPaketCommand)">
      <Output TaskParameter="Value" PropertyName="PaketCommand"/>
    </CreateProperty>

    <!-- This is just a debug statement. -->
    <Message Importance="high" Text="$(PaketCommand) - paket command | $(LocalPaketToolExitCode) - code" />
  </Target>
```

This target will be responsible for creating the `PaketCommand` property, which is used in two other targets, `PaketRestore` and `PaketOverrideNuspec`.  Unfortunately it looks like you can't have properties depend on targets/tasks, so I think this is the only way to do it.

Then to make sure `PaketCommand` is set before `PaketRestore` and `PaketOverrideNuspec` are called, you need to update the `DependsOnTargets` property for each of them.  Top lines of those targets should look something like this:

PaketRestore:
```xml
<Target Name="PaketRestore" Condition="'$(PaketRestoreDisabled)' != 'True'" BeforeTargets="_GenerateDotnetCliToolReferenceSpecs;_GenerateProjectRestoreGraphPerFramework;_GenerateRestoreGraphWalkPerFramework;CollectPackageReferences" DependsOnTargets="SetPaketCommand;PaketBootstrapping">
```

PaketOverrideNuspec:
```xml
<Target Name="PaketOverrideNuspec" DependsOnTargets="SetPaketCommand" AfterTargets="GenerateNuspec" Condition="('$(IsPackable)' == '' Or '$(IsPackable)' == 'true') And Exists('$(PaketIntermediateOutputPath)/$(MSBuildProjectFile).references')" >
```

**Comment by atlemann** [comment]
This works for both global and local clitool. Haven't tried mono or on windows, but it still does the things it used to do, so that shouldn't have changed.

**Comment by atlemann** [comment]
I don't see any warnings either. I didn't have `IgnoreExitCode="true"` yesterday.

**Comment by atlemann** [comment]
An alternative to invoking `dotnet paket --version` would be to check the `dotnet-tools.json` file for "paket" like this:

```xml
<PropertyGroup>
  <DotnetToolsJson>($([System.IO.File]::ReadAllText("$(PaketRootPath)/.config/dotnet-tools.json")))</DotnetToolsJson>
  <ContainsPaket>$(DotnetToolsJson.Contains('"paket"'))</ContainsPaket>
</PropertyGroup>
```

Then we wouldn't require that separate task I guess.

**Comment by NatElkins** [comment]
The `dotnet paket --version` way will definitely avoid errors, since if it's not installed it won't work.

**Comment by atlemann** [comment]
True that. It's the safest. Thanks for the help! Took a while to figure out of all this MSBuild stuff.

**Comment by forki** [comment]
Can we get a PR? Thanks

Atle Rudshaug <notifications@github.com> schrieb am Sa., 28. Sep. 2019,
20:05:

**Comment by atlemann** [comment]
I added one yesterday
