### ISSUE TITLE
Local tool dotnet pack fails

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#3677]
### Description

When running paket as a [local tool](https://fsprojects.github.io/Paket/installation.html#Local-tool) it fails when running `dotnet pack` on a library:

```
The command ""paket" fix-nuspecs files "obj/Debug/miniscaffold-test-local-paket.1.0.0.nuspec" project-file "/Users/jimmybyrd/Documents/GitHub/miniscaffold-test-local-paket/src/miniscaffold-test-local-paket/miniscaffold-test-local-paket.fsproj" " exited with code 127
```

### Repro steps

Please provide the steps required to reproduce the problem

1. clone : https://github.com/TheAngryByrd/miniscaffold-test-local-paket 

2. run `./build.sh dotnetpack`  or `.\build.cmd dotnetpack`

### Expected behavior

😸 

### Actual behavior

😿 

### Known workarounds

don't use local tools

**Comment by TheAngryByrd** [comment]
Seems like this is an issue in osx/linux in general.  Also getting an issue with restore

```
/Users/jimmybyrd/Documents/GitHub/miniscaffold-test-local-paket/.paket/Paket.Restore.targets(138,5): error MSB3073: The command ""paket" restore" exited with code 127. [/Users/jimmybyrd/Documents/GitHub/miniscaffold-test-local-paket/tests/miniscaffold-test-local-paket.Tests/miniscaffold-test-local-paket.Tests.fsproj]
```

**Comment by TheAngryByrd** [comment]
Hmm I think this is a targets file being extracted over during the FAKE build.

**Comment by forki** [comment]
Paging @matthid we need to make sure fake doesn't change the targets files

**Comment by matthid** [comment]
Yes, I'd like to wait a bit for stuff in paket to stabilize ;)

**Comment by forki** [comment]
The problem is that it changes things back and forth. That's breaking many use cases

**Comment by matthid** [comment]
Please see the discussion in https://github.com/fsharp/FAKE/issues/2332 and in particular https://github.com/fsharp/FAKE/issues/2332#issuecomment-506896559

In the end it boils down to not yet being a supported use case (fake tells you to use a “compatible” paket version, you just ignore it), but there is a workaround

**Comment by TheAngryByrd** [comment]
Yep that's the environment variable I had to set to fix it.
