### ISSUE TITLE
paket why hangs

### ISSUE THREAD

**Issue by apobekiaris** [fsprojects/Paket#3702]
### Description

Please provide a succinct description of your issue.

### Repro steps

```ps1
.\paket.exe why castle.core -v
Paket version 5.231.0
found: C:\Work\eXpandFramework\DevExpress.XAF\paket.dependencies
Parsing C:\Work\eXpandFramework\DevExpress.XAF\paket.dependencies
```
### Expected behavior

graph display

### Actual behavior
hangs on parsisng...
Stops with no output

**Comment by apobekiaris** [comment]
oops spoke too fast it actually works however super slow

```ps1
.\paket.exe why Xpand.VersionConverter
Paket version 5.231.0
NuGet Xpand.VersionConverter - 1.0.36 is a transitive dependency.
It is part of following dependency chains:

-> Xpand.XAF.Web.All - 0.0.1.3
  -> Xpand.XAF.Core.All - 0.0.1.8
    -> Xpand.XAF.Modules.AutoCommit - 1.0.17.5
      -> Xpand.VersionConverter - 1.0.36

... and 48 chains more starting at Xpand.XAF.Web.All ...
To display all chains use --details flag.

-> Xpand.XAF.Win.All - 0.0.1.10
  -> Xpand.XAF.Modules.GridListEditor - 0.0.19.5
    -> Xpand.VersionConverter - 1.0.36

... and 61 chains more starting at Xpand.XAF.Win.All ...
To display all chains use --details flag.

Performance:
 - Runtime: 10 minutes, 21 seconds
```

**Comment by forki** [comment]
Can you please upload your dependencies and lock file?

Apostolis Bekiaris <notifications@github.com> schrieb am Do., 7. Nov. 2019,
03:05:

**Comment by apobekiaris** [comment]
[XAF.zip](https://github.com/fsprojects/Paket/files/3818214/XAF.zip)

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/68376020-277d0800-0148-11ea-9dc6-2d17cfbe5047.png)

@theimowski I think you were the last one optimizing this. Any ideas?

**Comment by theimowski** [comment]
I'll try looking into that this week

**Comment by theimowski** [comment]
Seems the issue is due to cycles in dependencies between packages like `Microsoft.NETCore.Platform`, `System.Runtime`, `Microsoft.NETCore.Targets` and friends ...
Will investigate further

**Comment by forki** [comment]
PS D:\temp\XAF> .\.paket\paket.exe why castle.core
    Paket version 5.234.1
    Package system.buffers is defined more than once in group Main of D:\temp\XAF\paket.dependencies
    NuGet castle.core - 4.4 is a direct (paket.dependencies) dependency.
    It is part of following dependency chains:
    
    -> Moq - 4.13
      -> castle.core - 4.4
    
    Performance:
     - Runtime: 571 milliseconds
    PS D:\temp\XAF> .\.paket\paket.exe why Xpand.VersionConverter
    Paket version 5.234.1
    Package system.buffers is defined more than once in group Main of D:\temp\XAF\paket.dependencies
    NuGet Xpand.VersionConverter - 1.0.37 is a transitive dependency.
    It is part of following dependency chains:
    
    -> Xpand.XAF.Web.All - 0.0.2.1
      -> Xpand.XAF.Core.All - 0.0.2.1
        -> Xpand.XAF.Modules.AutoCommit - 1.0.18
          -> Xpand.Extensions.XAF - 0.0.8
            -> Xpand.VersionConverter - 1.0.37
    
    -> Xpand.XAF.Win.All - 0.0.2.1
      -> Xpand.XAF.Core.All - 0.0.2.1
        -> Xpand.XAF.Modules.AutoCommit - 1.0.18
          -> Xpand.Extensions.XAF - 0.0.8
            -> Xpand.VersionConverter - 1.0.37
    
    Performance:
     - Runtime: 574 milliseconds
    PS D:\temp\XAF>

Great work  @theimowski
