### ISSUE TITLE
Support for `repositorytype` and `repositoryurl` in paket.template

### ISSUE THREAD

**Issue by cartermp** [fsprojects/Paket#3707]
The .NET SDK supports `RepositoryType` and `RepositoryUrl` properties for a project. These get added to the generated nuspec as a single `repository` element.

This is relevant for [GitHub Package Registry](https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-nuget-for-use-with-github-package-registry), since you need this field to be able to associate multiple packages with a single repo.

**Comment by forki** [comment]
Sounds good. Do we also need this for resolution?

**Comment by forki** [comment]
ok read the description. It's not needed to change things in resolver part
