### ISSUE TITLE
Documentation: sequence of commands not working

### ISSUE THREAD

**Issue by selketjah** [fsprojects/Paket#3712]
### Description

On my macbook pro, when I try out the new steps to install paket for `.NET Core (preferred)`, I get an error after step 4.
https://fsprojects.github.io/Paket/get-started.html

### Repro steps

Please provide the steps required to reproduce the problem

1. dotnet new tool-manifest
2. dotnet tool install paket
3. dotnet tool restore
4. dotnet paket restore (gives the error)

### Expected behavior

No errors and `.paket` folder and files exist.

### Actual behavior

```
terminal-path $ dotnet paket restore
Paket version 5.232.0
Performance:
 - Runtime: 58 milliseconds
Paket failed with
-> Could not find 'paket.dependencies'. To use Paket with this solution, please run 'paket init' first.
   If you have already run 'paket.init' then ensure that 'paket.dependencies' is located in the top level directory of your repository.
   Like this:
   MySourceDir
     .paket
     paket.dependencies

```
### Known workarounds

```
terminal-path $ dotnet paket init
Paket version 5.232.0
Saving file /xxx
Performance:
 - Runtime: 279 milliseconds

terminal-path $ dotnet paket install
Paket version 5.232.0
```

After that, the `dotnet paket restore` gives no errors anymore.

**Comment by forki** [comment]
I removed the paket restore from that first block since the paket init is directly following in step 3.
