### ISSUE TITLE
A new project fails to run

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#3721]
I created a completely new F# dotnet core project. when adding 
`<Import Project="..\..\.paket\Paket.Restore.targets" />`  and dotnet running it then it fails:

![image](https://user-images.githubusercontent.com/57396/68853816-1baabc00-06db-11ea-95e2-fdfec95f2f7d.png)

adding FSharp.Core made it work again. I wonder if it's related to https://github.com/fsprojects/Paket/pull/3706? /cc @atlemann @JohnyWS

**Comment by JohnyWS** [comment]
Hmm, sounds plausible - it's not the best data to progress further with
though.

Do you have a small repo that I can try running it with? (never done F#
development before... :-/ )

Den tor. 14. nov. 2019 kl. 12.36 skrev Steffen Forkmann <
notifications@github.com>:

**Comment by forki** [comment]
[repro.zip](https://github.com/fsprojects/Paket/files/3846799/repro.zip)

It's just a new console app which references the target file and no deps.

please run `dotnet run` with dotnet 3.0.100

**Comment by atlemann** [comment]
I tried with the previous version as well and the same happens.

**Comment by forki** [comment]
ok. thanks. any idea what  "the same" means?

**Comment by forki** [comment]
the weird thing is: this is a runtime error

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/68866421-b06de380-06f4-11ea-8e8c-110c7c97698a.png)

so it looks like the version without paket is using the FSharp.Core and the paket one does not.

**Comment by forki** [comment]
so it's unrelated to the targets file changes and I think I know the root cause

**Comment by atlemann** [comment]
Did you figure it out?

**Comment by forki** [comment]
yes.

![image](https://user-images.githubusercontent.com/57396/68926760-8bc24c00-0786-11ea-8356-9ec7092b03b6.png)

I think we should somehow only do that when we know that FSharp.Core was used. In other words this should go into the props inside obj

**Comment by atlemann** [comment]
Ah, right. Yes, how to we do that...

**Comment by forki** [comment]
@atlemann see https://github.com/fsprojects/Paket/pull/3725
