### ISSUE TITLE
Does paket support floating versions?

### ISSUE THREAD

**Issue by bpaczkowski** [fsprojects/Paket#3729]
I'm evaluating nuget alternatives as it handles floating versions (e.g. `1.*`) very poorly. Mainly, when a project references a package with a floating version, after packing the project it resolves it to the newest version that was available, and we have to manually edit the nupkg before pushing it to the feed.

Another issue we have with it is if the project references another project that is not a nuget, after packing, that project is added as a dependency, even though the dll is already in the nupkg, so we also have to remove it. Does paket have the same issue?

**Comment by forki** [comment]
Hi, this is a bug tracker and not so much a support channel. Anyway information about various ways for floating can be found here: https://fsprojects.github.io/Paket/nuget-dependencies.html#Version-constraints
Information about packaging and replacement of project references with nuget references can be found: https://fsprojects.github.io/Paket/template-files.html#Referenced-projects
