### ISSUE TITLE
Packages downloading to nuget cache despite "storage: packages" set. 

### ISSUE THREAD

**Issue by neildanson** [fsprojects/Paket#3736]
### Description

When "storage: packages" is set I would expect nuget packages to only be downloaded to the packages folder. The packages are also downloaded to the .nuget cache folder and seemingly referenced from there. 

### Repro steps

Please provide the steps required to reproduce the problem

1: Create a new VS .net core console application
2: Change Target Framework to 4.7.2
3: From command line run .paket\paket convert-from-nuget
3: add "storage: packages" to the dependecies file
4: In paket dependencies add a nuget package *that is not in your local nuget cache*
5: .paket/paket install
6: Observe the nuget package added now in the cache. (
7: File is *also* in packages (as expected)

However what is not expected is that the one used by the build is the one from the cache and *not* the one from the packages folder. I often drop in replacement dlls when developing locally into the packages folder, so this seems a bit naff.

### Expected behavior

~~Use *either* packages folder *or* cache, but not both.~~

If packages are not supported in new netsdk template projects then a warning should be emitted. 

### Actual behavior

~~Dlls downloaded to nuget cache *and* the packages folder.~~
Build references nuget cache and not packages. 

### Known workarounds

N/A

**Comment by neildanson** [comment]
Reading the docs a little further I guess it is expected/desirable to download to both (although I'm not sure why). However I dont think it's desirable to reference the nuget cached version during build - the packages folder should be referenced (this is the way it seems to work for "old school" projects)

**Comment by forki** [comment]
Afaik you can't specify where the package is referenced from in new SDK
projects.

Neil Danson <notifications@github.com> schrieb am Fr., 29. Nov. 2019, 16:50:

**Comment by matthid** [comment]
I think we could override the `NugetPackageRoot` msbuild variable. But I'm not sure if we want to do this. It wouldn't work with multiple groups and/or will write in our directory.

**Comment by neildanson** [comment]
What purpose does the packages folder offer for netsdk projects? Its a little confusing to see it populated but not used for the build. Should it be deprecated for netsdk projects?

**Comment by neildanson** [comment]
@matthid  I've tried setting the environment variable (I saw that in the docs when I found the download behaviour was correct) But the folder remains resolutely empty :(

**Comment by forki** [comment]
It's basically deprecated. But we hoped they would re-enable this feature
for us.

Neil Danson <notifications@github.com> schrieb am Fr., 29. Nov. 2019, 17:01:

**Comment by matthid** [comment]
@neildanson There isn't really a compelling reason to use `storage: packages` I'd say.
There is one minor thing I sometimes still use it for: If any nuget package contains an `.exe` I'd like to start via relative path. Often I use a separate group with `storage: packages` just for these packages.
But as time goes on it will become more and more obsolete (considering dotnet tools for example)

**Comment by neildanson** [comment]
The main reason we used it was for some internal tooling. But it looks like we might have to update that instead. Thanks for the clarification guys.

**Comment by forki** [comment]
Yeah. We used it to override official packaged with custom builds. This is
now impossible since you don't want to have custom builds end up in central
caches and maybe breaks other solutions on your machine. Or worse other
builds on your CI infrastructure.

Neil Danson <notifications@github.com> schrieb am Fr., 29. Nov. 2019, 17:26:
