### ISSUE TITLE
github dependency fails to download

### ISSUE THREAD

**Issue by enricosada** [fsprojects/Paket#3738]
```
-> Could not download from 'https://raw.githubusercontent.com/enricosada/add_icon_to_exe/e11eda501acea369ac2950beb34b8888495bf21f/rh/ResourceHacker.exe'
-> FileNotFoundException: Could not load file or assembly 'System.Net.Http.WinHttpHandler, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

**Comment by JohnyWS** [comment]
Any progess? Not sure how I can help out here? :-/

**Comment by JohnyWS** [comment]
Hmm, the issue appears to be resolved now? What has been changed? @matthid / @forki ? :)

**Comment by forki** [comment]
It's not resolved. @enricosada I assume we need to ilmerge the lib into the
net46x exe, right?

Johny Woller Skovdal <notifications@github.com> schrieb am Di., 3. Dez.
2019, 08:12:

**Comment by enricosada** [comment]
Yes, that’s my guess too. I tried yesterday but failed.
I’ll retry later today

**Comment by JohnyWS** [comment]
Hmm, but github update does not fail for me today? It did last night. Has the release page been updated, or why am I not experiencing any errors today if the error isn't resolved?

**Comment by forki** [comment]
@JohnyWS  I assume you tested with 5.x

**Comment by enricosada** [comment]
I tried the exact same ilmerge change but didn’t work for me.
Dunno

**Comment by forki** [comment]
whate xactly did not work? ILRepack failed or did the resulting exe not work?

**Comment by enricosada** [comment]
Ilmerge ok, but the resulting exe didn’t fix the issue.
Maybe I did something wrong locally dunno, probably my bad, it’s the fix I expected too

**Comment by forki** [comment]
@enricosada  it worked, but:

    -> FileNotFoundException: Could not load file or assembly 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by forki** [comment]
ILMerging the second one helped. build is green. yay

**Comment by JohnyWS** [comment]
@forki yes I did, in multiple repos, but this morning it started working again, so I was wondering what had changed?

A forced update run in a local test repo yesterday evening:
```
.paket\paket.exe --self --run --version
Checking Paket version (downloading latest stable)...
Trying self update
Starting download of bootstrapper from https://github.com/fsprojects/Paket/
Self update failed. Resetting bootstrapper.
Access to the path 'D:\git\QrGenerator\.paket\paket.exe' is denied. (Github
Paket version 5.238.2
```
This morning the forced update worked again though...

**Comment by forki** [comment]
I guess the one time when it was broken you ran 6.x alpha. It was only
broken on alpha channel. But it's fixed there as well.

Johny Woller Skovdal <notifications@github.com> schrieb am Di., 3. Dez.
2019, 17:20:
