### ISSUE TITLE
Does the paket version constraint >= download the next version up if it's not available?

### ISSUE THREAD

**Issue by imranazad** [fsprojects/Paket#3740]
I have the following version constraint in my packet.lock file

```
Arachne.Core (2.3.23)
  FParsec (>= 1.0.1)
  FSharp.Core (>= 3.1.2.1)
```
I understand that this means that it requires at least version 1.0.1 of FParsec however what if 1.0.1 is not available? When restoring will paket proceed to download the next version up? I ask this question because I want to lock down all my packages to ensure a consistent output in my application for safety reasons.

Should I manually change the paket.lock to:

```
Arachne.Core (2.3.23)
  FParsec (1.0.1)
  FSharp.Core (3.1.2.1)
```

**Comment by forki** [comment]
During restore it will only use exactly the pinned versions or raise an
exception. That's the whole point of the lock file.

Imran Azad <notifications@github.com> schrieb am Di., 3. Dez. 2019, 16:58:

**Comment by imranazad** [comment]
@forki That's brilliant, thank you!
