### ISSUE TITLE
Issue cleanup - help offered

### ISSUE THREAD

**Issue by JohnyWS** [fsprojects/Paket#3742]
I have noticed a lot of open issues, that seems to either miss follow-ups, or are actually done, but just have not been officially closed.

Is there any way I can help out with cleanup, then I would be glad to offer my help. Would also give a better overview of what the current state really is.

Anyways, it was just if you could use a hand with that. Any form you need is OK by me (tagging, mentions, follow-ups etc)

**Comment by forki** [comment]
very cool. thanks a lot. This is appreciated!
I will try to answer that in email. please ping me if I forget to do it in next 2 days.
