### ISSUE TITLE
paket restore - file creation issues

### ISSUE THREAD

**Issue by Flohack74** [fsprojects/Paket#3743]
### Description

A `paket restore` cannot extract / copy certain files to the pacakges folder

### Repro steps

Please provide the steps required to reproduce the problem

1. Have paket.dependencies file from here: `git@github.com:Flohack74/paket-issuetracking.git`

2. Do a paket restore with latest version 5.239, or one version bewlo 5.238.2

### Expected behavior

All packages are downloaded and installed

### Actual behavior

```paket restore``` breaks with
```
  ==> Last trial
Downloading Microsoft.Extensions.DependencyInjection 3.1
Not moving as 'C:\Users\flole\.nuget\packages\microsoft.extensions.dependencyinjection\3.1.0\microsoft.extensions.dependencyinjection.3.1.0.nupkg' already exists (maybe some other instance downloaded it as well)
Download of Microsoft.Extensions.DependencyInjection 3.1 done in 28 milliseconds. (50758 kbit/s, 0 MB)
Performance:
 - Disk IO: 23 seconds
 - Average Download Time: 180 milliseconds
 - Number of downloads: 216
 - Average Request Time: 177 milliseconds
 - Number of Requests: 234
 - Runtime: 56 seconds
Paket omitted 4 warnings similar to the ones above. You can see them in verbose mode.
Paket failed with
-> Error during extraction of C:\USERDATA\DEVEL\packages\Microsoft.Extensions.DependencyInjection\microsoft.extensions.dependencyinjection.3.1.0.nupkg.

    In rare cases a firewall might have blocked the download. Please look into the file and see if it contains text with further information.
-> IOException: The file 'C:\USERDATA\DEVEL\packages\Microsoft.Extensions.DependencyInjection\packageIcon.png' already exists.
```
It breaks on either Microsoft.Extensions.DependencyInjection or Microsoft.Extensions.DependencyInjection.Abstractions...

Also, ```paket restore --force``` breaks on various packages with
```
Paket failed with
-> Error during cleaning of C:\USERDATA\DEVEL\packages\Microsoft.AspNet.WebApi.Client
     - Access to the path 'C:\USERDATA\DEVEL\packages\Microsoft.AspNet.WebApi.Client\lib\net45' is denied.
-> UnauthorizedAccessException: Access to the path 'C:\USERDATA\DEVEL\packages\Microsoft.AspNet.WebApi.Client\lib\net45' is denied.
```

But this is a random race condition. Every time this appears its a different package.

### Known workarounds

None

**Comment by forki** [comment]
what's the last version that works?

**Comment by Flohack74** [comment]
It seems this is a broken package on NuGet - this worked until Monday with 5.239. Then they released 3.1.0, and this breaks now. I will investigate with MS, but you might want to check if this is intended behaviour for paket, or an issue you can deal with. I did not look into the contents of Microsoft.Extensions.DependencyInjection so far.

**Comment by forki** [comment]
yeah we saw this error in the CI as well. I thought it's only a problem with paket 6 alpha but seems it's all versions. /cc @BlythMeister

**Comment by forki** [comment]
in CI it's failing on `Microsoft.Extensions.Configuration`

**Comment by Flohack74** [comment]
I now pinned to nuget Microsoft.Extensions.DependencyInjection 3.0.1 and that solves it for the moment. Also used contact form on NuGet to inform the maintainer but I am not sure how fast they will respond.

**Comment by forki** [comment]
-> IOException: Die Datei "D:\temp\downloadhack\paket-issuetracking\packages\Microsoft.Extensions.DependencyInjection.Abstractions\packageIcon.png" already exists.

ouch. the zip is corrupt!?

**Comment by forki** [comment]
we do `System.IO.Compression.ZipFile.ExtractToDirectory(fileName, targetFolder)` on that package.

**Comment by Flohack74** [comment]
Yeah thats what we think here as well:
![grafik](https://user-images.githubusercontent.com/16186470/70148686-ec1e1c80-16a6-11ea-89cc-ff9f6b1ee4bc.png)

**Comment by isaacabraham** [comment]
Confirmed, I've seen this today as well.

**Comment by BlythMeister** [comment]
![](https://media2.giphy.com/media/S6qkS0ETvel6EZat45/giphy.gif?cid=5a38a5a27c5f7d771ceb85d3679283d14ecfb71dbb3b2c32&rid=giphy.gif)

Package borked good and proper....

**Comment by forki** [comment]
there are multiple packages borked. Something must be wrong with how they got packaged. I assume a bug in nuget pack command.

Anyway, good news: if we fallback to extracting manually in a loop then we can work around it. paket 5.240.0 should be up in couple of minutes

**Comment by Flohack74** [comment]
Very nice Sir, thanks!

**Comment by forki** [comment]
ok please test 5.240.0. thanks

**Comment by Flohack74** [comment]
Yes that fixes the issue. Many thanks!

**Comment by forki** [comment]
it still remains a mystery how those packages made it to the server but I let this one for the nuget team.

**Comment by forki** [comment]
@BlythMeister please rebase your PR and hopefully that one will now be green as well.

**Comment by matthid** [comment]
Should we create an issue over at nuget and link back? Has someone reported this?

**Comment by Flohack74** [comment]
@matthid I just used the feedback form to send them a note, but I doubt this will be processed soon. Do you have other options for bug reports?

**Comment by matthid** [comment]
Either on the repository the package was build from as github issue or directly in dotnet cli `dotnet pack` issue or nuget client, I'm pretty sure they will move it around between microsoft teams anyway.

**Comment by Flohack74** [comment]
I opened an issue, lets see ;)

**Comment by matthid** [comment]
@Flohack74 Thanks!

**Comment by dracan** [comment]
I've had this today too, and can reproduce with a brand new directory and `paket.dependencies` file...

    source https://api.nuget.org/v3/index.json
    nuget Microsoft.Extensions.Configuration.Json 3.1.0

However, removing this from the project I'm working with, I then his the same error on a package this _isn't_ new. Doing a `paket install` on this `paket.dependencies` file _also_ fails...

    source https://api.nuget.org/v3/index.json
    nuget NetMQ 4.0.0.207
 
So presumably this suggests that it's not just new packages that are problematic?

**Comment by forki** [comment]
@dracan please retry with latest Paket

**Comment by matthid** [comment]
@dracan Note that these packages (especially Extension.Configuration) are very widespread and you might still need one though transitive resolution even tough you don't have them directly in your depsfile

**Comment by dracan** [comment]
@forki Brilliant! That's fixed it! 😄 I had freshly installed Paket today too on another laptop to see if it was an issue with my work PC. But because I did a Chocolately install, it hadn't got your fix in yet. I'm glad Chocolately is slightly behind though, otherwise it would have worked on the other laptop and I'd have blamed my work PC! 😄

**Comment by dracan** [comment]
@matthid Thanks. Yep, most of the codebase won't use this even transitively. There's only one small project in a lot of other projects that use .NET Core / ASP.NET.

**Comment by vivainio** [comment]
Confirming that updating to Paket 5.241.2 fixed this for me
