### ISSUE TITLE
Allow a way to ignore existing files

### ISSUE THREAD

**Issue by CumpsD** [fsprojects/Paket#3753]
### Description

I am upgrading Microsoft.Build to 16.4.0 and I am confronted with:

```
Paket failed with
-> Error during extraction of /home/cumpsd/dotfiles/repos/gh-aiv/tostring-builder/packages/Microsoft.Build.Framework/microsoft.build.framework.16.4.0.nupkg.
   
    In rare cases a firewall might have blocked the download. Please look into the file and see if it contains text with further information.
-> IOException: The file '/home/cumpsd/dotfiles/repos/gh-aiv/tostring-builder/packages/Microsoft.Build.Framework/MSBuild-NuGet-Icon.png' already exists.
```

After some investigating, it seems this icon is declared twice in the nuget. I've opened an issue at https://github.com/microsoft/msbuild/issues/4988 for that.

However, it would be nice to have the force flag to overwrite those cases?

### Repro steps

Probably a paket dependencies with just `nuget Microsoft.Build 16.4.0` in it

### Expected behavior

An option to turn this into a warning?

### Actual behavior

Blocking and unable to continue.

### Known workarounds

None

**Comment by baronfel** [comment]
What paket version are you on? I believe https://github.com/fsprojects/Paket/releases/tag/5.240.0 was released specifically to handle this issue because a lot of the .net core 3.1 packages had a similar issue.

**Comment by CumpsD** [comment]
5.226.0

I'll try upgrading, thanks

**Comment by CumpsD** [comment]
Fixed with upgrading, thanks
