### ISSUE TITLE
Control TypeScript version in a Microsoft.NET.Sdk.Web project

### ISSUE THREAD

**Issue by FilippoPolo** [fsprojects/Paket#3758]
### Description

I have a project that uses Microsoft.NET.Sdk.Web. As part of this SDK, VS will run TypeScript compilation on any .TS files in the project. The version of TS being used is governed by specific sections within the .csproj file. I would like to control this with paket, but I can't figure out how.

### Repro steps

This is my .csproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="3.6.4" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

And I have a paket.references with **Microsoft.TypeScript.MSBuild**, and a paket.dependencies which says **nuget Microsoft.TypeScript.MSBuild 3.0.3**

### Expected behavior

I would expect paket to modify my .csproj file to make the build use TypeScript version 3.0.3.

### Actual behavior

Running paket install has no effect on the .csproj and the build uses TypeScript 3.6.4.

**Comment by forki** [comment]
Why do you have the explicit package reference in the csproj? I think you
need to remove that and put it in the paket.references file.

FilippoPolo <notifications@github.com> schrieb am Mi., 18. Dez. 2019, 18:04:

**Comment by FilippoPolo** [comment]
Hi forki,

I have tried doing that. This is the result:

`1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\TypeScript\Microsoft.TypeScript.targets(72,5): warning : Your project does not specify a TypeScriptToolsVersion. The latest available TypeScript compiler will be used (3.7). To remove this warning, set TypeScriptToolsVersion to a specific version or "Latest" to always select the latest compiler.`

It is not using the version from paket.references.

**Comment by forki** [comment]
can you please upload a zip with a repro?

**Comment by FilippoPolo** [comment]
Okay, this is weird. The problem is not happening in the simplified repro. So I have something wrong in the original setup.

Is there a way to get a verbose log of what packages are being used during a build and why?

**Comment by forki** [comment]
you can look into your obj. there is an assets file and mayn other files that have such output

**Comment by matthid** [comment]
Use msbuild binlog feature and download the viewer to inspect the log

**Comment by FilippoPolo** [comment]
Got it. I had some group issues in paket.dependencies that caused the reference to be ignored outright. Thanks for your help!
