### ISSUE TITLE
NuGets with duplicate files get only partially extracted

### ISSUE THREAD

**Issue by viktor-svub** [fsprojects/Paket#3763]
### Description

NuGets with duplicate files get only partially extracted, resulting in Paket steps passing, but dotnet/msbuild restore failing as if they were not present. 

### Repro steps

1. Using paket.dependencies with: 
```
version 5.241.2 --prefer-nuget
storage: none
framework: netcoreapp3.1
source https://api.nuget.org/v3/index.json
nuget Microsoft.Extensions.DependencyInjection.Abstractions ~> 3.1
```

2. Run ```paket update --no-install && paket install && dotnet restore --force && dotnet build```
Paket steps seem to complete with suspicious log messages (will elaborate) but without explicit errors or warnings. DotNet restore & build fail as if the affected packages were missing completely, e.g. 
```My.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.DependencyInjection.Abstractions (>= 3.1.0)' for '.NETCoreApp,Version=v3.1'. [My.sln]```

### Expected behavior

Packages in global storage should be fully usable or not present at all. We should make best effort to make even badly authored packages usable, especially in scenarios where NuGet itself works. 

### Actual behavior

Packages with duplicate file entries are sometimes unpacked only partially, with some files and directories missing, without explicit errors or yellow warnings. 

interesting log fragments: ```
Paket version 5.241.2
[...update seems to run fine...]
Download of Microsoft.Extensions.DependencyInjection.Abstractions 3.1 done in 141 milliseconds. (3134 kbit/s, 0 MB)
[...other files are downloaded...]
Something went wrong while downloading Microsoft.Extensions.DependencyInjection.Abstractions 3.1
Message: The file '[user-home]\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.1.0\packageIcon.png' already exists.
  ==> Trying again
Downloading Microsoft.Extensions.DependencyInjection.Abstractions 3.1
[...other files are downloaded...]
Not moving as '[user-home]\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.1.0\microsoft.extensions.dependencyinjection.abstractions.3.1.0.nupkg' already exists (maybe some other instance downloaded it as well)
Download of Microsoft.Extensions.DependencyInjection.Abstractions 3.1 done in 562 milliseconds. (786 kbit/s, 0 MB) ```

resulting ```paket-installmodel.cache``` which mathes the actual unpacked directory: ```
D: /lib
D: /lib/netstandard2.0
F: /lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll
F: /lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.xml
D: /_rels
F: /_rels/.rels
F: /microsoft.extensions.dependencyinjection.abstractions.3.1.0.nupkg
F: /Microsoft.Extensions.DependencyInjection.Abstractions.nuspec
F: /packageIcon.png```

but actual ```nupkg``` file content was: ```
.signature.p7s
[Content_Types].xml
_rels\.rels
lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.xml
Microsoft.Extensions.DependencyInjection.Abstractions.nuspec
package\services\metadata\core-properties\59C9F67FAE1D6C4565E518716C4810FC.psmdcp
packageIcon.png
packageIcon.png```

### Known workarounds

I was able to get the solution working by resolving the failing packages using dotnet/nuget, and once they were correctly extracted in the global storage, everything, including further paket restore & install, passed ok.

**Comment by viktor-svub** [comment]
I'll attempt a fix, but it might be much faster with someone familiar with the current code -- it looks like the recent one-by-one unpacking fallback fix gets bypassed for some reason.

**Comment by forki** [comment]
If you delete the whole folder. Will extract it properly? Maybe this is an
artefact?

Viktor Svub <notifications@github.com> schrieb am Sa., 21. Dez. 2019, 17:55:

**Comment by viktor-svub** [comment]
I have a cleanup process like ```git clean -dfx && paket clear-cache && nuget locals all -clear``` and after getting to the workaround & semi-working state, I ran this, and the issue reappeared, with the same set of packages -- it seems to behave quite consistently and affects specifically the Microsoft.Extension.* 3.1.0 package sub-set, i.e. the borked ones.

**Comment by viktor-svub** [comment]
I did _not_ see the (expected) "... Trying to extract files individually" message in any of the runs, it looks like the error gets handled on different path.

**Comment by forki** [comment]
Related: #3745 #3747
So we likely have another case of ZipFile.ExtractToDirectory somewhere.

Help very welcome.

**Comment by viktor-svub** [comment]
the most likely unhandled `ZipFile.ExtractToDirectory` call comes from `ExtractPackageToUserFolder`, which does some magic itself -- rather than mix the handler into that, I'd roll the whole "extract individually" code into a wrapper around `ExtractToDirectory` and replace that call everywhere

**Comment by forki** [comment]
Yes that sounds like what we need to do

**Comment by viktor-svub** [comment]
fixed and verified the fix as-is, please review :)
