### ISSUE TITLE
Support for DevOps' Personal Authentication Token

### ISSUE THREAD

**Issue by mauriciomagni** [fsprojects/Paket#3765]
### Description

Microsoft is finalizing support for Alternate Credentials in Azure DevOps by March 2, 2020 (https://devblogs.microsoft.com/devops/azure-devops-will-no-longer-support-alternate-credentials-authentication/)
Currently, I am using Alternate Credentials to access Azure Artifacts to store and retrieve nugets to/from it. 
I wonder what would become the best option to keep using Paket to consume the Nugets stored in Azure Artifacts.

### Repro steps

None

### Expected behavior

Be able to connect to Azure Artifacts not using DevOps Alternate Credentials; possibly, by using Personal Authentication Tokens (https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)

### Actual behavior

Unknown. Maybe the support for PATs is already in place and I am not aware of it :(

**Comment by mauriciomagni** [comment]
I had followed the instructions given in:
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page

and added credentials this way:
paket config add-credentials "https://[YOUR DEVOPS].pkgs.visualstudio.com/_packaging/[YOUR REPO]/nuget/v3/index.json" --verify --username "[T O K E N]" --password "[T O K E N]" --verbose  

and it worked as expected.

I have not tested the option add-token (https://fsprojects.github.io/Paket/paket-config.html)

**Comment by forki** [comment]
Would be really awesome if you could send us a PR which adds this to the
docs.

Mauricio Magni <notifications@github.com> schrieb am Di., 21. Jan. 2020,
07:44:

**Comment by JohnyWS** [comment]
Was just about to suggest the same thing! :) @mauriciomagni if you find it too much of a hassle to go through the contribution process, coming with suggested edits here is also fine, and I'll be sure to add it. But then my name will be on it, and I'm more into credit where it is due. But all contributions are welcome. :)
