### ISSUE TITLE
Generated load scripts not working with dotnet fsi

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/Paket#3788]
### Description

It seems that generated load scripts do not work well with `dotnet fsi`.

### Repro steps

1. Check out [this branch from Argu](https://github.com/fsprojects/Argu/tree/load-script-repro).
2. Run `dotnet tool restore && dotnet paket restore`.
3. Open `dotnet fsi`
4. Type `#load ".paket/load/netcoreapp3.1/DocGeneration/docgeneration.group.fsx" ;;`

### Expected behavior

Should load dependencies in context.

### Actual behavior

Complains about missing framework assemblies:
```
.paket\load\netcoreapp3.1\DocGeneration\docgeneration.group.fsx(42,1): error FS0078: Unable to find the file 'System.ComponentModel.Composition' in any of
 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.1
 C:\Program Files\dotnet\sdk\3.1.101\FSharp\../../../packs/Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1
 C:\Users\eitsarpa\devel\public\Argu
 C:\Program Files\dotnet\sdk\3.1.101\FSharp\
```

### Known workarounds

Manually delete framework assemblies loaded from script.

**Comment by baronfel** [comment]
System.ComponentModel.Composition isn't part of the sdk ref pack for 3.1.x, how does paket determine which assemblies to load?  FSI itself just auto-includes every .dll in the refs path (https://github.com/dotnet/fsharp/blob/master/src/fsharp/DotNetFrameworkDependencies.fs#L315) so paket shouldn't be getting in the business here of listing some platonic ideal list of refs.

**Comment by matthid** [comment]
@baronfel I agree, but as I understand the issue it is the reverse, the script contains references the OP thinks it shouldn't contain.
I'd assume (without checking) that these are declared as framework dependencies in one of the packages. 

The question remains: How should paket decide what to generate and what not?

**Comment by baronfel** [comment]
That's a good point, should paket probe the potential folders and cross-check the presence/absence of these framework refs then?  

Side-question: @eiriktsarpalis do you know which reference in particular is causing this framework reference to be added? looking at its Nuspec in more detail may shed some light on the discussion.

**Comment by matthid** [comment]
>

**Comment by inosik** [comment]
The filtering of framework assembly references doesn't seem to work correctly:

``` shell
$ rg -i 'system\.componentmodel\.composition' packages/docgeneration/
packages/docgeneration/System.Runtime\System.Runtime.nuspec
79:      <frameworkAssembly assemblyName="System.ComponentModel.Composition" targetFramework=".NETFramework4.5" />
80:      <frameworkAssembly assemblyName="System.ComponentModel.Composition" targetFramework=".NETFramework4.6.2" />

$ paket why -g docgeneration system.runtime
Paket version 5.242.0
NuGet system.runtime - 4.3.1 is a transitive dependency.
It is part of following dependency chains:

-> FSharp.Formatting - 4.0.0-alpha02
  -> FSharp.Compiler.Service - 33.0.1
    -> System.Diagnostics.Process - 4.3
      -> Microsoft.Win32.Primitives - 4.3
        -> system.runtime - 4.3.1

Performance:
 - Runtime: 976 milliseconds
```

**Comment by inosik** [comment]
These lines produce the framework references:

https://github.com/fsprojects/Paket/blob/91e3ddd6ed414e49ce05c793cad35d10450b4857/src/Paket.Core/Installation/ScriptGeneration.fs#L262-L264

**Comment by vilinski** [comment]
for me it is always either  `System.ComponentModel.Composition` or `Mono.Posix`. 
I have only .net core on the system - neither mono nor any full framework possible.
Reproducible even without Argu:
```
paket init
paket add SomePaket
paket install
paket generate-load-scripts
touch script.fsx <- and write the #include to it
fsharpi script.fsx
```
getting errors about missing dlls

**Comment by forki** [comment]
Would love to get a pr with blacklist if that's possible.

Andreas Vilinski <notifications@github.com> schrieb am Fr., 7. Feb. 2020,
18:39:

**Comment by inosik** [comment]
We should rather pass the framework to this call:

https://github.com/fsprojects/Paket/blob/91e3ddd6ed414e49ce05c793cad35d10450b4857/src/Paket.Core/PaketConfigFiles/DependencyCache.fs#L133

I tried to change the code to call the [`getLegacyFrameworkReferences` method](https://github.com/fsprojects/Paket/blob/91e3ddd6ed414e49ce05c793cad35d10450b4857/src/Paket.Core/PaketConfigFiles/InstallModel.fs#L958) (which accepts the target profile) and I don't get the wrong references anymore.

Should I create a PR and see what it breaks?

**Comment by forki** [comment]
Sure!

Ilja Nosik <notifications@github.com> schrieb am Mo., 10. Feb. 2020, 07:29:

**Comment by inosik** [comment]
See #3793.

**Comment by forki** [comment]
@eiriktsarpalis can you please retry?

**Comment by eiriktsarpalis** [comment]
Yep, looking good now. Thanks!

**Comment by vilinski** [comment]
I'm just here to say thank you! the way for scripting is free again

**Comment by jkone27** [comment]
does this also work without paket? i have a solution in C# and i want to test it on a script in .fsx, can i do it without paket as dependency manager and just use it as a tool to reference the assemblies. is there any other tool, i am on mac
