### ISSUE TITLE
Paket does not install Microsoft.NET.Test.Sdk correctly

### ISSUE THREAD

**Issue by siegeon** [fsprojects/Paket#3796]
### When updating a Visual Studio c# to use paket we ran into an issue with adding Microsoft.NET.Test.Sdk
![image](https://user-images.githubusercontent.com/5737831/74577276-9938cf00-4f4b-11ea-8c3e-964b755e97d3.png)

The project does not see the reference as installed.
![image](https://user-images.githubusercontent.com/5737831/74577325-c9806d80-4f4b-11ea-9076-85539324ed30.png)

Even though it is in the paket.references file
![image](https://user-images.githubusercontent.com/5737831/74577350-ea48c300-4f4b-11ea-938d-a78582049fe5.png)

And it is listed in the .csproj
![image](https://user-images.githubusercontent.com/5737831/74577463-85419d00-4f4c-11ea-9377-3e4f85ae70a5.png)

When the reference is added by nuget we get the following set 
![image](https://user-images.githubusercontent.com/5737831/74577498-ab673d00-4f4c-11ea-802c-edb6a6c87314.png)

### Expected behavior

Adding Microsoft.NET.Test.Sdk to be managed by paket should allow tests to run in visual studio. 

### Actual behavior

The reference is added sort of, but tests are unable to run. 

### Known workarounds

Currently, my only option appears to not use .paket

**Comment by forki** [comment]
Are you using new msbuild sdk?

siegeon <notifications@github.com> schrieb am Sa., 15. Feb. 2020, 01:11:

**Comment by siegeon** [comment]
Not sure, its the newest visual studio update.

**Comment by siegeon** [comment]
Closing - I blew away everything, nuget cache, repo, etc., Then I started over with the new paket.dependencies file, and this time everything worked as expected.
