### ISSUE TITLE
Cannot use paket as a local tool with .Net Core 3.1 SDK

### ISSUE THREAD

**Issue by WiredSharp** [fsprojects/Paket#3801]
### Description

I try to use Paket as a local tool with the new .Net Core SDK 3.0+ feature. It works fine with 3.0.100 sdk but it fails with 3.1.x SDK.

### Repro steps

_ensure .Net Core 3.1 SDK is installed._

in a new folder, generate a tool manifest
run the following:

```
dotnet new tool-manifest
dotnet tool install paket
dotnet tool restore
dotnet paket init
```

### Expected behavior

a new *paket.dependencies* file should be created.

### Actual behavior

an error is returned: _Execute "dotnet tool restore" to make "paket" command available._

### Known workarounds

_Ensure .Net Core 3.0 SDK is installed_

create a global.json file with the following content (forcing usage of SDK 3.0 with tools):
```
{
  "sdk": {
    "version": "3.0.100",
    "rollForward": "minor"
  }
}
```

**Comment by forki** [comment]
Cc @enricosada @matthid ideas?

**Comment by WiredSharp** [comment]
Hello,
I tried to reproduce on a different machine, and it runs without issue with SDK v3.1.101. I did not have to declare a global.json. It seems that it is a local issue on my computer.

**Comment by WiredSharp** [comment]
Also, i only have the issue with paket, i try dotnetsay or fake tools and it works correctly. Thats why i thought it was related to paket but maybe it is on dotnet tool side...

**Comment by WiredSharp** [comment]
Paket works fine if installed as a global tool too.

**Comment by WiredSharp** [comment]
I finally identified the issue, it is an issue with the dotnet cli toolresolvercache.
