### ISSUE TITLE
Project name same as dependency name - cycle detected and restore failed

### ISSUE THREAD

**Issue by padzikm** [fsprojects/Paket#3821]
### Description

Restore fails when project is name is the same as project's dependency. Tested on windows which is case insensitive.

### Repro steps

Follow steps described in https://saturnframework.org/docs/guides/how-to-start/ inside saturn folder:
1. install .net core sdk version 3.1.201
2. mkdir saturn && cd ./saturn
3. dotnet tool install fake-cli -g
4. dotnet new -i Saturn.Template
5. dotnet new saturn -lang F#
6. fake build

### Expected behavior

Build succeeded

### Actual behavior

Build failed with error:
Restore completed in 83,95 ms for C:\projects\saturn\src\saturn\saturn.fsproj.
C:\projects\saturn\src\saturn\saturn.fsproj : error NU1108: Cycle detected.
C:\projects\saturn\src\saturn\saturn.fsproj : error NU1108:   saturn -> Saturn (>= 0.12.1).
Restore failed in 1,09 sec for C:\projects\saturn\src\saturn\saturn.fsproj.

### Known workarounds

Name root project folder with different name than referenced saturn dll - for example saturnexample

**Comment by forki** [comment]
that seems to be a NuGet / dotnet SDK related issue and not related to
Paket. I think

Am Fr., 3. Apr. 2020 um 00:41 Uhr schrieb padzikm <notifications@github.com

**Comment by padzikm** [comment]
Can you explain why do you think that? Paket is responsible for restoring packages and I can't see any logical connection to dotnet sdk.

**Comment by forki** [comment]
You are not allowed to name your project as the dependency. this is a requirement that dotnet SDK / NuGet brings. NU1108 is an NuGet error that is raised in such cases by NuGet itself (which is still running even when you use paket).

**Comment by padzikm** [comment]
Ok, thanks for explanation
