### ISSUE TITLE
Visual Studio 2019 & .Net Core 3.1: paket.lock failed with invalid parameter 'netcoreapp3.1'

### ISSUE THREAD

**Issue by gggggeorge** [fsprojects/Paket#3827]
Hello,

I have been using Paket in Visual Studio 2015, for maybe 2 years, and I am fairly familiar with it, and I like it -thanks! :smiley:

Here is my problem:

### Description

Did a Build within Visual Studio 2019, and it fails with:

Error List:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""paket.exe" restore" exited with code 1.	LRDaily	C:\SOURCE_CONTROL\S1\LRDaily\.paket\Paket.Restore.targets	120	
```

Output:
```
1>------ Rebuild All started: Project: LRDaily, Configuration: Debug Any CPU ------
1>Checking Paket version (downloading latest stable)...
1>Paket.exe 5.243.0 is up to date.
1>Paket version 5.206.0
1>Performance:
1> - Runtime: 381 milliseconds
1>Paket failed with
1>-> Error during parsing of 'C:\SOURCE_CONTROL\S1\LRDaily\paket.lock'.
1>-> invalid parameter 'netcoreapp3.1' after >= or < in '== netcoreapp3.1'
1>C:\SOURCE_CONTROL\PrimaryIT2\S1\LRDaily\.paket\Paket.Restore.targets(120,5): error MSB3073: The command ""paket.exe" restore" exited with code 1.
1>Done building project "LRDaily.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

### Repro steps

1. Visual Studio 2019: create a new c# "Hello World" project with .Net Core 3.1.  I created a class/library DLL, but I'm guessing it will also fail with a Console project, etc.

2. I then simply created my normal:

**paket.dependencies** (at solution level):
```
source https://www.nuget.org/api/v2

framework: auto-detect

nuget System.Diagnostics.EventLog
```

**paket.references** (at project level):
`System.Diagnostics.EventLog`

3. I then did (at solution level) at the DOS prompt (to install the libraries -also tried a "-f" force, made no difference):
`.paket\paket.exe install`

4. I observed that my lock file was created, as per (at solution level):
**paket.lock**
```
RESTRICTION: == netcoreapp3.1
NUGET
  remote: https://www.nuget.org/api/v2
    Microsoft.NETCore.Platforms (3.1)
    Microsoft.Win32.Registry (4.7)
      System.Security.AccessControl (>= 4.7)
      System.Security.Principal.Windows (>= 4.7)
    System.Diagnostics.EventLog (4.7)
      Microsoft.NETCore.Platforms (>= 3.1)
      Microsoft.Win32.Registry (>= 4.7)
      System.Security.Principal.Windows (>= 4.7)
    System.Security.AccessControl (4.7)
      Microsoft.NETCore.Platforms (>= 3.1)
      System.Security.Principal.Windows (>= 4.7)
    System.Security.Principal.Windows (4.7)
```

-and the install in (3) seemed to work fine, no errors.

5. I then went back to Visual Studio 2019, and did a "Build", and then I got the error indicated (in the **Description**).

### Expected behavior

Project should have built.

### Actual behavior

Project build failed.

### Known workarounds

Go back to NuGet? :worried:

### Related information 

* Operating system: Windows 10

Thanks,
George H.
04/10/2020 5:42pm ET

**Comment by ChrSteinert** [comment]
Somehow it seems that you have multiple pakets running. Looking at the build output, there are two version numbers going on:
```
1>Paket.exe 5.243.0 is up to date.
1>Paket version 5.206.0
```
Is it possible, that you have paket locally (paket.exe) and as a dotnet global tool?
Can you try to run `dotnet tool update -g paket` ?

**Comment by gggggeorge** [comment]
Hi ChrSteinert,

I only refer to the .\\.paket\paket.exe in each Solution dir.,and I wasn't aware of "dotnet global tool" -until just reading about it now.  I don't recall ever doing anything to "install" paket.exe a a global tool, but regardless, I executed the command as you indicated, as per:

```
Microsoft Windows [Version 10.0.18363.720]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>dotnet tool update -g paket
You can invoke the tool using the following command: paket
Tool 'paket' (version '5.243.0') was successfully installed.

C:\WINDOWS\system32>
```

----
Right after doing the above, I did a "paket install", and this seemingly ran ok:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe install
Paket version 5.243.0
Resolving packages for group Main:
 - S.U.LRD 2.0.2
 - System.Diagnostics.EventLog 4.7.0
 - Microsoft.Win32.Registry 4.7.0
 - System.Security.Principal.Windows 4.7.0
 - Microsoft.NETCore.Platforms 3.1.0
 - System.Security.AccessControl 4.7.0
Locked version resolution written to C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\paket.lock
Installing into projects:
 - Creating model and downloading packages.
 - Installing for projects
   - ConsoleApp1/paket.references -> ConsoleApp1/ConsoleApp1.csproj
Extracted Paket.Restore.targets to: C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)
Performance:
 - Resolver: 1 second (1 runs)
    - Runtime: 525 milliseconds
    - Blocked (retrieving package details): 209 milliseconds (6 times)
    - Blocked (retrieving package versions): 1 second (4 times)
    - Not Blocked (retrieving package versions): 2 times
 - Disk IO: 9 milliseconds
 - Average Request Time: 60 milliseconds
 - Number of Requests: 13
 - Runtime: 3 seconds

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
```

----
I then went to Visual Studio, and attempted a "Build", and it failed (same error as I originally posted):

```
> 1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
> 1>Checking Paket version (downloading latest stable)...
> 1>Paket.exe 5.243.0 is up to date.
> 1>Paket version 5.206.0
> 1>Performance:
> 1> - Runtime: 453 milliseconds
> 1>Paket failed with
> 1>-> Error during parsing of 'C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\paket.lock'.
> 1>-> invalid parameter 'netcoreapp3.1' after >= or < in '== netcoreapp3.1'
> 1>C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets(120,5): error MSB3073: The command ""paket.exe" restore" exited with code 1.
> 1>Done building project "ConsoleApp1.csproj" -- FAILED.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

----
I also noticed in my Visual Studio settings I had set:

![image](https://user-images.githubusercontent.com/43475376/79285349-55027600-7e8b-11ea-8a78-d72dd275f273.png)

-but I really don't want this, so I changed them to:

![image](https://user-images.githubusercontent.com/43475376/79285579-fd183f00-7e8b-11ea-8d20-5320ad58153e.png)

I also did a "Clear All NuGet Cache(s)", for what ever that is worth.

I also did "paket clear-cache" if that makes any difference, as per:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe clear-cache
Paket version 5.243.0
  - C:\Users\gh\.nuget\packages
  - C:\Users\gh\AppData\Local\Nuget\Cache
  - C:\Users\gh\.paket\git\db
Performance:
 - Runtime: 813 milliseconds

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
```

----
I then tried another Build (in Visual Studio), but it still fails the same way, as per:

```
1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>Checking Paket version (downloading latest stable)...
1>Paket.exe 5.243.0 is up to date.
1>Paket version 5.206.0
1>Performance:
1> - Runtime: 502 milliseconds
1>Paket failed with
1>-> Error during parsing of 'C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\paket.lock'.
...
```

----
One question I have is why Paket tries to automatically update itself, and seemingly attempt a "restore" every time I compile -I don't want this, and how do I turn this off?

In my *.csproj file, I noticed "Import Project":
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

How/why is this in my project file...? 

----
I'm noticing that things don't seem to work "the same" as in say Visual Studio 2015 vs. 2019.

With Visual Studio 2015, my Paket NuGet packages never automatically restored when I did a build.

----
Ok, I re-read the output from the paket install, and I see a reference to **PAKET_SKIP_RESTORE_TARGETS**, so I did set this environment variable, as per:

![image](https://user-images.githubusercontent.com/43475376/79286949-3b176200-7e90-11ea-941c-b525d8ea5699.png)

I then completely created a new Visual Studio 2019 console project, and did a "paket install", as per:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe install
Paket version 5.243.0
Resolving packages for group Main:
 - S.U.LRD 2.0.2
 - System.Diagnostics.EventLog 4.7.0
 - Microsoft.Win32.Registry 4.7.0
 - System.Security.Principal.Windows 4.7.0
 - Microsoft.NETCore.Platforms 3.1.0
 - System.Security.AccessControl 4.7.0
Locked version resolution written to C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\paket.lock
Installing into projects:
 - Creating model and downloading packages.
 - Installing for projects
Performance:
 - Resolver: 1 second (1 runs)
    - Runtime: 439 milliseconds
    - Blocked (retrieving package details): 299 milliseconds (6 times)
    - Blocked (retrieving package versions): 1 second (4 times)
    - Not Blocked (retrieving package versions): 2 times
 - Disk IO: 443 milliseconds
 - Average Request Time: 77 milliseconds
 - Number of Requests: 13
 - Runtime: 2 seconds

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
```

I then attempted a Build in Visual Studio, and now I get the errors:

Output:
```
1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file 'C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "ConsoleApp1.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Error List:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	ConsoleApp1	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
```

----
At this point I can't think of anything else to try, any ideas?

There is still also the strange reference of the two different paket versions, as well:

```
> 1>Paket.exe 5.243.0 is up to date.
> 1>Paket version 5.206.0
```


Thanks,
George H.
04/14/2020 9:00pm ET

**Comment by gggggeorge** [comment]
Hi ChrSteinert,

I did some more digging about the different Paket versions:

```
> 1>Paket.exe 5.243.0 is up to date.
> 1>Paket version 5.206.0
```

I have Cygwin installed and executed a "whereis", and sure enough a "global" Paket was installed here:

```
C:\WINDOWS\system32>whereis paket.exe
paket: /cygdrive/c/ProgramData/chocolatey/bin/paket.exe

C:\WINDOWS\system32>

```

I then did (which solves the mystery of 5.206.0):

```
C:\ProgramData\chocolatey\bin>.\paket.exe --version
Paket version 5.206.0

C:\ProgramData\chocolatey\bin>
```
so I uninstalled it (choco uninstall paket), and I also uninstalled the "dotnet global paket", as per:

```
C:\WINDOWS\system32>dotnet tool uninstall -g paket
Tool 'paket' (version '5.243.0') was successfully uninstalled.
```

I then completely created a new Visual Studio console project, did the "paket install" (no problems), and then I did a Build (within Visual Studio) that failed with a new error:

Ouput:
```
1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Error List:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets" was not imported by "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj" at (7,3), due to the file not existing.	ConsoleApp1	C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets	7	
Error	MSB4019	The imported project "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets" was not found. Confirm that the expression in the Import declaration "..\.paket\Paket.Restore.targets" is correct, and that the file exists on disk.	ConsoleApp1	C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj	7	

```

It should be noted I did not change my environment variable, so this was/is still in effect:

PAKET_SKIP_RESTORE_TARGETS=true

-so why is paket trying to still do an "automatic restore when compiling"...?


Thanks,
George H.
04/14/2020 9:36pm ET

**Comment by ChrSteinert** [comment]
Good find with the chocolatey paket version! :)

So the `Paket.Restore.targets` file is needed as it is needed for `dotnet restore` to use paket.
It seems you are missing an initial `paket install` and/or `paket restore` before you can build you solution in VS.
Can you try running both commands and then attempt a build again?

**Comment by gggggeorge** [comment]
Hi ChrSteinert,

ok, I just executed both paket install & restore, as per:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe install
Paket version 5.243.0
Skipping resolver for group Main since it is already up-to-date
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\paket.lock is already up-to-date
Installing into projects:
 - Creating model and downloading packages.
 - Installing for projects
   - ConsoleApp1/paket.references -> ConsoleApp1/ConsoleApp1.csproj
Performance:
 - Disk IO: 5 milliseconds
 - Runtime: 1 second

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe restore
Paket version 5.243.0
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 220 milliseconds

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
```

-as I expected, it had nothing to do, since I already did a seemingly successful "paket install".

----
I will now delete:

 C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\paket.lock
 C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\packages

-and then do "paket install" again, as per:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>rm -rf packages

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>rm paket.lock

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe install
Paket version 5.243.0
Resolving packages for group Main:
 - S.U.LRD 2.0.2
 - System.Diagnostics.EventLog 4.7.0
 - Microsoft.Win32.Registry 4.7.0
 - System.Security.Principal.Windows 4.7.0
 - Microsoft.NETCore.Platforms 3.1.0
 - System.Security.AccessControl 4.7.0
Locked version resolution written to C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\paket.lock
Installing into projects:
 - Creating model and downloading packages.
 - Installing for projects
   - ConsoleApp1/paket.references -> ConsoleApp1/ConsoleApp1.csproj
Performance:
 - Resolver: 1 second (1 runs)
    - Runtime: 528 milliseconds
    - Blocked (retrieving package details): 193 milliseconds (6 times)
    - Blocked (retrieving package versions): 1 second (5 times)
    - Not Blocked (retrieving package versions): 1 times
 - Disk IO: 428 milliseconds
 - Average Request Time: 87 milliseconds
 - Number of Requests: 13
 - Runtime: 3 seconds

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>
```

-as can be seen above, all seems well.

----
I will now do a "paket restore", but first, I will delete 

`C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\packages`

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>rm -rf packages

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe restore
Paket version 5.243.0
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 213 milliseconds

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>

```

Hmmmmm, that seems strange, why did paket "think" the current state of things is "good", and not do a restore...?  I deleted the entire packages dir. (along with all the packages/libraries).

I guess because nuget caches on...?:

C:\Users\georgeh\\.nuget\packages

-ok, so now I do the following:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>rm -rf C:\Users\georgeh\.nuget\packages

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>rm -rf packages

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe restore
Paket version 5.243.0
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 212 milliseconds
```

-so to me the above seems wrong, as clearly I have deleted all my packages/DLLs...? Shouldn't paket detect something is "wrong", and attempt to "fix things" by doing a restore?

Ok, so now I will do a restore force, as per:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>.\.paket\paket.exe restore -f
Paket version 5.243.0
Starting restore process.
Downloading S.U.LRD 2.0.2
Downloading System.Security.AccessControl 4.7
Downloading Microsoft.NETCore.Platforms 3.1
Downloading System.Diagnostics.EventLog 4.7
Downloading System.Security.Principal.Windows 4.7
Download of Microsoft.NETCore.Platforms 3.1 done in 887 milliseconds. (268 kbit/s, 0 MB)
Download of SynQor.UTILS.LoggerRotateDaily 2.0.2 done in 916 milliseconds. (287 kbit/s, 0 MB)
Downloading Microsoft.Win32.Registry 4.7
Download of System.Diagnostics.EventLog 4.7 done in 1 second. (2017 kbit/s, 0 MB)
Download of System.Security.Principal.Windows 4.7 done in 1 second. (3875 kbit/s, 0 MB)
Download of System.Security.AccessControl 4.7 done in 1 second. (3943 kbit/s, 0 MB)
Download of Microsoft.Win32.Registry 4.7 done in 490 milliseconds. (6177 kbit/s, 0 MB)
Performance:
 - Disk IO: 1 second
 - Average Download Time: 138 milliseconds
 - Number of downloads: 6
 - Average Request Time: 65 milliseconds
 - Number of Requests: 7
 - Runtime: 3 seconds

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>

```

-ok, that seems like it worked.

----
Now I will go into Visual Studio 2019, and do a Build -here are the results (failed):

Ouput:
```
1>------ Build started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj(7,3): error MSB4019: The imported project "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets" was not found. Confirm that the expression in the Import declaration "..\.paket\Paket.Restore.targets" is correct, and that the file exists on disk.
1>Done building project "ConsoleApp1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Error List:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets" was not found. Confirm that the expression in the Import declaration "..\.paket\Paket.Restore.targets" is correct, and that the file exists on disk.	ConsoleApp1	C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj	7	
Error		Project "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets" was not imported by "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj" at (7,3), due to the file not existing.	ConsoleApp1	C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket\Paket.Restore.targets	7	
```

It seems I continue to have the same error.

----
Here is more info for you:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1>cat ConsoleApp1.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1>
```

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\ConsoleApp1>cd ..

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1>cd .paket

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 78C4-F86B

 Directory of C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket

04/14/2020  09:49 PM    <DIR>          .
04/14/2020  09:49 PM    <DIR>          ..
12/03/2018  07:00 PM            69,928 paket.bootstrapper.exe
04/14/2020  07:44 PM         8,711,936 paket.exe
               2 File(s)      8,781,864 bytes
               2 Dir(s)  95,857,336,320 bytes free

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\ConsoleApp1\.paket>

```

-so the Paket.Restore.targets is being referenced in my C# project file (ConsoleApp1.csproj), but it doesn't exist in the .paket dir...?

----
Thanks for continuing to try to help me troubleshoot this issue.

As I've indicated I've used paket many times w/ Win7 & Visual Studio 2015, and never had any of these issues.

It is only since I moved to Win10 & Visual Studio 2019 that I can't seemingly get packet to work.


Thanks,
George H.
04/15/2020 5:00pm ET

**Comment by ChrSteinert** [comment]
So I tried to rebuild your problem.
I think your problem is, that on one hand you tell paket to not have the restore targets, but on the other hand you had the old version during project setup which included the targets file.

I would suggest, that you try to set up the project from scrach again. Going really from nothing to 
```
paket init
dotnet new ...
paket install
paket restore
dotnet build (or VS build)
```

Hope this helps.

Or, if you feel like it you could also remove the `<Import Project="..\.paket\Paket.Restore.targets" />` part from the *.csproj files yourself.

**Comment by gggggeorge** [comment]
Hi ChrSteinert,

I still have the same issue, seemingly no matter what I do w/Visual Studio 2019...?

Thanks for having patience with me -I'm really trying to get this working.
 
----
Trying a different way, example:

1. Create a C# .Net Core 3.1 console application:

![image](https://user-images.githubusercontent.com/43475376/80426822-81b78400-88b4-11ea-86b7-a261a1ec24e7.png)

2. dotnet new tool-manifest
![image](https://user-images.githubusercontent.com/43475376/80426866-a0b61600-88b4-11ea-80f2-ce3f258be253.png)

3. dotnet tool install Paket
![image](https://user-images.githubusercontent.com/43475376/80426941-c7744c80-88b4-11ea-893f-b34e20a10fbb.png)

4. dotnet paket init
![image](https://user-images.githubusercontent.com/43475376/80426998-e2df5780-88b4-11ea-989b-897a04c6f158.png)

----
Here is my dir. tree now:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200427_000>tree /f
Folder PATH listing for volume Local Disk
Volume serial number is 00540045 78C4:F86B
C:.
└───ConsoleApp1
    │   ConsoleApp1.sln
    │   paket.dependencies
    │
    ├───.config
    │       dotnet-tools.json
    │
    ├───ConsoleApp1
    │   │   ConsoleApp1.csproj
    │   │   Program.cs
    │   │
    │   ├───bin
    │   │   └───Debug
    │   │       └───netcoreapp3.1
    │   └───obj
    │       └───Debug
    │           └───netcoreapp3.1
    │                   ConsoleApp1.AssemblyInfo.cs
    │                   ConsoleApp1.AssemblyInfoInputs.cache
    │                   ConsoleApp1.csprojAssemblyReference.cache
    │
    └───paket-files

C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200427_000>
```

----
5. I added the following (highlighted):

![image](https://user-images.githubusercontent.com/43475376/80427446-c2fc6380-88b5-11ea-805a-627d611a9f24.png)

6. I create the paket.references:

![image](https://user-images.githubusercontent.com/43475376/80428263-74e85f80-88b7-11ea-9052-77ccd5b67f0c.png)

7. dotnet paket install

![image](https://user-images.githubusercontent.com/43475376/80427675-4453f600-88b6-11ea-8814-45bce7a1ec49.png)

----
Here is my paket.lock file:

![image](https://user-images.githubusercontent.com/43475376/80428031-f1c70980-88b6-11ea-8143-22aabc71b98c.png)

8. dotnet build

![image](https://user-images.githubusercontent.com/43475376/80427720-5c2b7a00-88b6-11ea-9292-47cd86748d1a.png)

----
Here is my dir. tree now:

```
C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200427_000>tree /f
Folder PATH listing for volume Local Disk
Volume serial number is 00540045 78C4:F86B
C:.
└───ConsoleApp1
    │   ConsoleApp1.sln
    │   paket.dependencies
    │   paket.lock
    │
    ├───.config
    │       dotnet-tools.json
    │
    ├───ConsoleApp1
    │   │   ConsoleApp1.csproj
    │   │   paket.references
    │   │   Program.cs
    │   │
    │   ├───bin
    │   │   └───Debug
    │   │       └───netcoreapp3.1
    │   │               ConsoleApp1.deps.json
    │   │               ConsoleApp1.dll
    │   │               ConsoleApp1.exe
    │   │               ConsoleApp1.pdb
    │   │               ConsoleApp1.runtimeconfig.dev.json
    │   │               ConsoleApp1.runtimeconfig.json
    │   │
    │   └───obj
    │       │   ConsoleApp1.csproj.nuget.dgspec.json
    │       │   ConsoleApp1.csproj.nuget.g.props
    │       │   ConsoleApp1.csproj.nuget.g.targets
    │       │   project.assets.json
    │       │   project.nuget.cache
    │       │
    │       └───Debug
    │           └───netcoreapp3.1
    │                   ConsoleApp1.AssemblyInfo.cs
    │                   ConsoleApp1.AssemblyInfoInputs.cache
    │                   ConsoleApp1.assets.cache
    │                   ConsoleApp1.csproj.CoreCompileInputs.cache
    │                   ConsoleApp1.csproj.FileListAbsolute.txt
    │                   ConsoleApp1.csprojAssemblyReference.cache
    │                   ConsoleApp1.dll
    │                   ConsoleApp1.exe
    │                   ConsoleApp1.genruntimeconfig.cache
    │                   ConsoleApp1.pdb
    │
    └───paket-files
            paket.restore.cached

```

----
Notice how the above failed because it could not find:

`C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200427_000\ConsoleApp1\.paket\Paket.Restore.targets`

I understand why -because the .paket dir. was never created.

What am I doing wrong...?


Thanks,
George H.
04/27/2020 6:53pm ET

**Comment by ChrSteinert** [comment]
I suspect that you have mixed a global tool, and a per solution tool.
Can you try setting up the project again, but without creating a tool manifest and installing paket for the solution, but rather use the globally installed (`dotnet tool install -g paket`) Paket?

**Comment by gggggeorge** [comment]
Hi,

I tried that (dotnet tool install -g paket), still the same issue.  I deleted -every- instance of:

```
paket.exe
paket.bootstrapper.exe
```

on my entire hard-drive, to make certain that no other "paket" is being used, and I still get the same failure -always an error that it can't find reference "Paket.Restore.targets".

I have tried to simplify the reproducibility of this issue as much as possible, so I created a new ticket (#3863 ) yesterday (06/10/2020).

I'm closing this ticket, and can you take a look/comment on the simplified ticket I created?

Thank you for taking a look at this, as I really want to use paket with .Net Core!


Thanks,
George H.
06/11/2020 3:49pm ET
