### ISSUE TITLE
`dotnet paket` fails when NUGET_PACKAGES - (dotnet nuget global-packages) is set to alternate location

### ISSUE THREAD

**Issue by da9l** [fsprojects/Paket#3833]
### Description

If you set NUGET_PACKAGES to an alternate folder. "D:\cache" on a build agent for instance,
```powershell
dotnet tool restore # and then directly after
dotnet paket info # or paket <whatever>.
``` 

will fail with $lastexitcode=1 and
`Run "dotnet tool restore" to make the "paket" command available.`
### Repro steps

See this minimal example: https://github.com/da9l/dotnetpaketProblem_minimalExample

### Expected behavior

it should work.

### Actual behavior

fail with $lastexitcode=1 and
`Run "dotnet tool restore" to make the "paket" command available.`

### Known workarounds

Don't set `NUGET_PACKAGES` to anything non-standard.

**Comment by inosik** [comment]
The error message comes from the .NET SDK, so I don't think this is an issue with Paket. Can you confirm that other tools work?

**Comment by da9l** [comment]
Thanks for pointing that out. I added two more datapoints (dotnet tools) and you are very likely right. The problem is not paket specific. I'll post an issue in the dotnet repo instead.

This case can be closed as not applicable.
