### ISSUE TITLE
Microsoft is changing netcoreapp5.0 to net5.0

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#3834]
see

https://github.com/dotnet/runtime/issues/35202

https://github.com/dotnet/runtime/pull/35176

**Comment by TheAngryByrd** [comment]
Just hit this.

**Comment by forki** [comment]
So it's already changed?

**Comment by ngg** [comment]
Yes, since .NET 5.0 Preview 3, the target has been renamed `netcoreapp5.0` -> `net5.0`. Also there is a `net5.0-windows` target which also supports some windows specific extensions like WPF. 

Probably only from .NET 6.0, but according to https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md and https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/ there will be more targets like `net6.0-ios14.0` which targets iOS 14.0 or higher.

**Comment by forki** [comment]
net5-win? or what's the exact moniker? @terrajobst

**Comment by ngg** [comment]
https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#what-about-net-10 says that `net5` "Will work, but shouldn't be used" and only `net5.0` should be used. I don't think the "windows" part can be shortened.

**Comment by terrajobst** [comment]
That’s correct “net5.0-windows” is the correct form. The short form “win” is from an earlier draft.

**Comment by seanamosw** [comment]
Using version `5.247.4` of paket, after doing a `dotnet paket install`, attempt to do a restore:

```sh
-> failed to parse line '      System.Reflection.Emit.ILGeneration (>= 4.7) - restriction: || (&& (== netcoreapp2.0) (>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)' (invalid parameter 'netcoreapp5.0' after >= or < in '>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)') (Could not parse 'framework: restriction: || (&& (== netcoreapp2.0) (>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)' as key/value pairs.)
	-  invalid parameter 'netcoreapp5.0' after >= or < in '>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)'
	-  Could not parse 'framework: restriction: || (&& (== netcoreapp2.0) (>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)' as key/value pairs.
	-> invalid delimiter at position 22
```

I've worked around this by rolling back paket to version `5.245.0`, before support was added for `netcoreapp5.0`.

**Comment by thinkbeforecoding** [comment]
should net5.0 be parsed as a FrameworkVersion.V5 or a DotNetCoreAppVersion.V5_0, or something new ?

**Comment by forki** [comment]
Yes I think it needs to be parsed as exactly that

Jérémie Chassaing <notifications@github.com> schrieb am Di., 18. Aug. 2020,
17:36:

**Comment by thinkbeforecoding** [comment]
I created a PR for this #3899

**Comment by thinkbeforecoding** [comment]
This seems to be working great with 6.0.0-alpha042 ! I think we can close this issue

**Comment by forki** [comment]
Hurray
