### ISSUE TITLE
csproj file is no longer updated after upgrading project's ToolsVersion

### ISSUE THREAD

**Issue by peter-f-s** [fsprojects/Paket#3837]
### Description

when running `paket install`, the references in my project files (csproj) are updated according to the `paket.references` file. This worked fine as long as I was working with Visual Studio 2017 (the projects have set `ToolsVersion="15.0"`).
After upgrading to Visual Studio 2019 (`ToolsVersion="16.0"`), paket ignores changes in the `paket.references` file. The references in the projects are staying the same when doing a `paket install`. However, paket touches the project file (it moves the import directive to `Paket.Restore.targets` to another location in the file).

### Repro steps

paket.dependencies:
```
source https://api.nuget.org/v3/index.json
framework: net48

nuget StreamJsonRpc
nuget NUnit
```

paket.references:
```
StreamJsonRpc
```
csproj file beginning like this:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="16.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

### Expected behavior

When I change the `paket.references` file (e.g. adding `NUnit`), I expect that a reference to NUnit is added to the project when I run `paket install`. 
(This is actually the case when the csproj's `ToolsVersion="15.0"`)

### Actual behavior

The reference added to `paket.references` file is not added to the csproj file.
Removing references also doesn't work.

**Comment by forki** [comment]
actuall we're always checking for `if toolsVersion >= 15.0 then`.

Can you please upload a zip where this reproduces? I want to fix it

**Comment by peter-f-s** [comment]
Thank you! Here you go:
[csprojUpdateIssue.zip](https://github.com/fsprojects/Paket/files/4544912/csprojUpdateIssue.zip)
(I hope the zip is ok - I had to try several options and browsers until GitHub accepted the file)

**Comment by forki** [comment]
this should be fixed

**Comment by forki** [comment]
@peter-f-s does it work for you?

**Comment by peter-f-s** [comment]
@forki: Yes, works perfectly! Many thanks for the quick reply. :thumbsup:
