### ISSUE TITLE
paket install opens too many connections for downloading package metadata

### ISSUE THREAD

**Issue by Flohack74** [fsprojects/Paket#3850]
### Description

We have a paket.dependencies file with approx 350 packages inside. Paket install works well when in the company network. However, when being at home, people report a lot of yellow or red warnings regarding connections to NuGet. This happens frequently also when the people are connected to the company VPN.

It seems we are depleting the pool of IP connections via the VPN gateway, as paket seems to ask NuGet for a lot of data in parallel. Another case happens since one of our providers started to use DSLite stack, where all IPv4 connections are pooled behind a proxy, and users do not have their own IPv4 address anymore. That seems to create issues now since a lot of people are at home and the proxy runs out of socket connections during the day. Mostly paket install works on the evening hours.

This ticket is primarily for finding out what strategy you use when trying to get the package infos from the servers. And if there would be a way to have a command line parameter to limit the max amount of connections there.

**Comment by cdrnet** [comment]
I have the same problem against feeds only accessible through the company VPN.

There are already some networking parameters like timeouts which can be overwritten through environment variables. If we can identify a variation that would resolve the problem, maybe a similar approach could be used to enable/adjust it as well.

**Comment by ChrSteinert** [comment]
Chiming in…
I just hit that issue too, where we proxy a feed via an nginx, and paket seems to deplete it's worker connections.

**Comment by forki** [comment]
Can anyone suggest a fix?

**Comment by ChrSteinert** [comment]
I'm currently looking into it :)

**Comment by ChrSteinert** [comment]
So as I guessed, the "issue" is, that for every package a new `HttpClient` is created. Multiple instances do not share the same Connection Pool and thus it might happen that the connectinons are depleted. This is currently mainly in that way (as I think) because it uses a new Handler for each request/package. I'll have a look how this can be rewritten. Just give me a bit more time ;)

**Comment by Flohack74** [comment]
Oh yes that sounds reasonable. As discussed over the whole internet it seems that while HttpClient implements IDisposable, it should not be disposed but just be reused as much as possible.

**Comment by ChrSteinert** [comment]
@Flohack74  can you please Check with 5.248.1? This should fix it.

**Comment by Flohack74** [comment]
Yes I can tomorrow morning ;)

**Comment by Flohack74** [comment]
Confirmed to be solved! Only a handful of connections is used now:
![grafik](https://user-images.githubusercontent.com/16186470/88372527-5dc1ec80-cd96-11ea-9ab7-22266dda5f9f.png)

**Comment by forki** [comment]
Is this having positive performance impact?

**Comment by Flohack74** [comment]
Well performance-wise I think not much changed, but there are no retries, API v2 downgrade messages etc. So while I feel it equally fast, it might be in fact faster. At least it finishes now, I dont have to run it 5 times or so :)

**Comment by cdrnet** [comment]
It works much better over VPN for me as well now. Even "outdated" now completes in a larger repo, for the first time ever over VPN. Thanks a lot! 💐

**Comment by ChrSteinert** [comment]
> Is this having positive performance impact?

In theory there can be perf gains by not having the syn/ack overhead. But the current Connection Pool Size is set to four – so this might in return be a limiting factor. I think, for instance, that Chrome does ~20 connections per Host.

**Comment by Flohack74** [comment]
Yes you can safely increase this limit to at 10 or so. It wouldnot be a problem I think.
