### ISSUE TITLE
Visual Studio 2019 & .Net Core 3.1: Paket.Restore.targets was not found -will not build.

### ISSUE THREAD

**Issue by gggggeorge** [fsprojects/Paket#3863]
Hello,

I can't get paket to work with Visual Studio 2019 & .Net Core.

I have used paket many times with .Net (example 4.7.2) without any issues, but I can never get it to work with .Net Core (example 3.1).

----
Here are all the steps I went through:

1. Create .Net Core 3.1 "Hello World" console application.

2. Visual Studio Package Manager Console:
`dotnet new tool-manifest`

3. Visual Studio Package Manager Console:
`dotnet tool install paket`

4. Visual Studio Package Manager Console:
`dotnet tool restore`

5. Visual Studio Package Manager Console:
`dotnet paket init`

6. I edited paket.dependencies, so now is this:
```
source https://api.nuget.org/v3/index.json

storage: none
framework: netcore3.1, netstandard2.0, netstandard2.1

nuget Newtonsoft.Json
```

7. I created paket.references, so now is:
`Newtonsoft.Json`

8. Visual Studio Package Manager Console:
`dotnet paket install`

9. I examine ConsoleApp1.csproj, and I see Paket.Restore.targets has been added to the XML, as per:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

10. Rebuild the solution/project, and I get the errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200610b\ConsoleApp1\.paket\Paket.Restore.targets" was not imported by "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200610b\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj" at (7,3), due to the file not existing.	ConsoleApp1	C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200610b\ConsoleApp1\.paket\Paket.Restore.targets	7	
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200610b\ConsoleApp1\.paket\Paket.Restore.targets" was not found. Confirm that the expression in the Import declaration "..\.paket\Paket.Restore.targets" is correct, and that the file exists on disk.	ConsoleApp1	C:\PROJECTS\MISC\VS_2019_PAKET_TEST\TEST_20200610b\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj	7	
```

11. Here is my Solution/Project dir./file tree:
```
C:.
│   ConsoleApp1.sln
│   paket.dependencies
│   paket.lock
│
├───.config
│       dotnet-tools.json
│
├───ConsoleApp1
│   │   ConsoleApp1.csproj
│   │   paket.references
│   │   Program.cs
│   │
│   ├───bin
│   │   └───Debug
│   │       └───netcoreapp3.1
│   └───obj
│       └───Debug
│           └───netcoreapp3.1
│                   .NETCoreApp,Version=v3.1.AssemblyAttributes.cs
│                   ConsoleApp1.AssemblyInfo.cs
│                   ConsoleApp1.AssemblyInfoInputs.cache
│                   ConsoleApp1.csprojAssemblyReference.cache
│
└───paket-files
        paket.restore.cached
```

----
----
Can someone point out what I'm doing wrong with such a basic example?  I must be missing something.  Sorry if I'm not understanding something.

Attached is a ZIP of my project/solution as per the above 1-11 steps:

[ConsoleApp1.zip](https://github.com/fsprojects/Paket/files/4762497/ConsoleApp1.zip)

Thanks,
George H.
06/11/2020 12:12am ET

**Comment by gggggeorge** [comment]
Hi,

I deleted -every- instance of:

```
paket.exe
paket.bootstrapper.exe
```

on my entire hard-drive, to make certain that no other "paket" is being used, and I still get the same failure -always an error that it can't find reference "Paket.Restore.targets".

I know in .Net framework (example 4.7.2), I will have this dir. structure:

```
├───.paket
│       paket.bootstrapper.exe
│       paket.exe
│       Paket.Restore.targets
│       paket.targets
```

----
I'm using .Net Core 3.1, and it would seem my error is either one of the following...?

1. I'm missing the above dir/files.

2. In my csproj file, I'm referencing `<Import Project="..\.paket\Paket.Restore.targets" />`, but it should not be referencing this.

Which is it?


Thanks,
George H.
06/11/2020 4:16pm ET

**Comment by ChrSteinert** [comment]
I assume you have set the environment variable `PAKET_SKIP_RESTORE_TARGETS` to `true`? 
When I set this in my environment I can reproduce your problem. 
Out of curiosity; why to you set this environment variable?

**Comment by gggggeorge** [comment]
Hi Christian,

thank you for finding this! -and it's funny you mention that, because last night I found an article (https://forums.fsharp.org/t/how-can-i-get-paket-to-generate-paket-restore-targets/591) indicating a **paket restore** should create the **Paket.Restore.targets** file, so I decided to look at the Paket source code, to find out why my paket restore didn't do this, and I found this:

```
MASTER\Paket\src\Paket.Core\Installation\RestoreProcess.fs:

...
let extractRestoreTargets root =
    let path = Path.Combine(root,".paket","Paket.Restore.targets")
    if Environment.GetEnvironmentVariable "PAKET_SKIP_RESTORE_TARGETS" <> "true" then
        // allow to be more clever than paket
        if !copiedElements then path
        else
            let (fileWritten, path) = extractElement root "Paket.Restore.targets"
            copiedElements := true
            if fileWritten then tracefn "Extracted Paket.Restore.targets to: %s (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)" path
            path
    else path
...

```
-which pointed to the ENV variable **PAKET_SKIP_RESTORE_TARGETS**, and sure enough mine was set.

I don't recall ever setting this variable, or why I would have set it, but I deleted ENV **PAKET_SKIP_RESTORE_TARGETS**, and things started working.

I wanted to do some more experimenting, before I posted this, but you beat me to it -thank you for looking at this!

----
I found that .Net vs .Net Core don't seem to behave in the same way, in regards to the **Paket.Restore.targets** -this is just a .Net Core thing...?

I could not find any "official" explanation (what exactly it does, why I want it, why I don't want it, etc.) of **PAKET_SKIP_RESTORE_TARGETS** -in any of the Paket documention (https://fsprojects.github.io/Paket/).

I only found bits and pieces of references to it, in some past Paket issues.

----
----
Possible suggestion:

For someone such as myself who is still learning Paket, I have a suggestion that when a "restore" is done, and **Paket.Restore.targets** is not created (because of **PAKET_SKIP_RESTORE_TARGETS=true**) that a STDOUT message (the opposite message of **Paket.Restore.targets** being created) be indicated -something like:

`"Paket.Restore.targets not extracted to: %s (Can be enabled by deleting  PAKET_SKIP_RESTORE_TARGETS or set to false)"`

Maybe I originally saw the message:

`"Extracted Paket.Restore.targets to: %s (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)"
`
-and I thought, hmmmmm.... why do I need this **Paket.Restore.targets**...?  I don't recall seeing this with paket/.Net "classic", so I will set **PAKET_SKIP_RESTORE_TARGETS=true**, and then I just forgot about it.


Thanks,
George H.
06/12/2020 1:39pm ET

**Comment by ChrSteinert** [comment]
Glad I could help.
I have no idea why this thing exists any why you would want it. Maybe if you have your own `targets` file doing some restore magic?
@forki; do you have some insights?

@gggggeorge would you agree that this issue can be closed then? I'd open a new issue about the missing message after that.

**Comment by gggggeorge** [comment]
Hi Christian,

I am closing out this issue, and I just created a new issue (#3869), regarding `PAKET_SKIP_RESTORE_TARGETS`.


Thanks,
George H.
06/15/2020 5:34pm ET
