### ISSUE TITLE
Paket install changes fsproj file

### ISSUE THREAD

**Issue by landy** [fsprojects/Paket#3867]
### Description

command `dotnet paket install` adds `<Import Project="..\..\.paket\Paket.Restore.targets" />` line to every fsproj in a solution. This is somewhat unwanted behaviour because we have introduced Directory.Build.Targets file to our solution witch contains this import already 
```
<Project>
    <Import Project=".paket\Paket.Restore.targets" />
</Project>
```

### Repro steps

1. have paket enabled project
2. create `Directory.Build.Targets` file in the root of the project
3. delete `<Import Project...>` lines from each fsproj file
4. run `dotnet paket install`

### Expected behavior

Don't modify project files outside of `migrate-from-nuget` and use the import from Directory.Build.targets, or at least provide a way to disable this with some setting in the `paket.dependencies` file 

### Actual behavior

Install adds the import back to fsproj and causes build warning `.paket/Paket.Restore.targets cannot be imported again....`

**Comment by forki** [comment]
Well that's just by design. Don't really see a way to do that without
breaking the world.

Jiří Landsman <notifications@github.com> schrieb am Fr., 12. Juni 2020,
14:37:

**Comment by landy** [comment]
That is unfortunate but thx for the info :)
