### ISSUE TITLE
PAKET_SKIP_RESTORE_TARGETS=true vs. false.

### ISSUE THREAD

**Issue by gggggeorge** [fsprojects/Paket#3869]
Hi,

this is related to issue #3863 .

For someone such as myself who is still learning Paket, I have a suggestion that when a "restore" is done, and `Paket.Restore.targets` is not created (because of `PAKET_SKIP_RESTORE_TARGETS=true`) that a STDOUT message (the opposite message of `Paket.Restore.targets` being created) be indicated -maybe something like:

`"Paket.Restore.targets not extracted to: %s (Can be enabled by deleting PAKET_SKIP_RESTORE_TARGETS or set to false)"`

----
I must have seen (when I did a paket restore, etc.):

`"Extracted Paket.Restore.targets to: %s (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)"
`
-and I thought, hmmmmm.... why do I need this Paket.Restore.targets with .Net Core...? I don't recall seeing this with Paket/.Net "classic", so I will set `PAKET_SKIP_RESTORE_TARGETS=true`, and then I just forgot about it.

...well this caused a very subtle "issue", where `Paket.Restore.targets` was not created, and I could not figure out why, until I read through the Paket source code.

----
Also, in the Paket documentation I can find no official reference to `PAKET_SKIP_RESTORE_TARGETS` -it only popped up when google searches pointed to some old Paket issues.

Thanks,
George H.
06/15/2020 5:28pm ET

**Comment by JohnyWS** [comment]
@gggggeorge could you have a look at my PR and see if you agree with the message, plus try it out locally and see if at works as expected?
