### ISSUE TITLE
support generation of `GeneratePathProperty` msbuild variables similar to nuget

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#3876]
### Description

In `PackageReference`ed dependencies, the `GeneratePathProperty` xml attribute can be set, and if it is set to "True" nuget processing will generate an MsBuild property of the form `Pkg{normalized package identifier}` (as per the logic [here](https://github.com/NuGet/NuGet.Client/blob/e9c3e9bb16b901219e9db8f62a198bfdc3af1d79/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/BuildAssetsUtils.cs#L789-L796).  I'd like paket to automatically enlist referenced packages in this property, as all it does is provide useful information for users of tasks like ILRepack.

### Expected behavior

PackageReferences written/managed by Paket include the `GeneratePathProperty="True"` attribute.

### Actual behavior

Paket-managed PackageReferences do not have the attribute set.

**Comment by baronfel** [comment]
I think I might be off-base here, I seem to already have the required parameters available.

**Comment by apm1grb** [comment]
Hi @baronfel, where to find these parameters? I also need this property filled and it's emtpy.
