### ISSUE TITLE
5.248.0, Error during parsing paket.lock. Invalid parameter 'netcoreapp5.0'

### ISSUE THREAD

**Issue by seanamosw** [fsprojects/Paket#3896]
### Description

After doing a `dotnet paket update/install` with paket > 5.245.0, attempting to do a `dotnet restore` results in the error:

```sh
Paket failed with
  -> Error during parsing of 'xxx/paket.lock'.
  -> Error during parsing of 'xxx/paket.lock'.
  Performance:
  -> failed to parse line '      System.Reflection.Emit.ILGeneration (>= 4.7) - restriction: || (&& (== netcoreapp2.0) (>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)' (invalid parameter 'netcoreapp5.0' after >= or < in '>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)') (Could not parse 'framework: restriction: || (&& (== netcoreapp2.0) (>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)' as key/value pairs.)
   - Runtime: 585 milliseconds
        -  invalid parameter 'netcoreapp5.0' after >= or < in '>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)'
        -  Could not parse 'framework: restriction: || (&& (== netcoreapp2.0) (>= netcoreapp5.0)) (&& (== netcoreapp2.0) (< netstandard1.1)) (&& (== netcoreapp2.0) (< netstandard2.0)) (&& (== netcoreapp2.0) (>= uap10.1)) (== netstandard2.0)' as key/value pairs.
        -> invalid delimiter at position 22
```

### Known workarounds

Downgrade paket to 5.245.0. Revert any changes to paket.lock file. Run `dotnet paket update/install` again.

**Comment by forki** [comment]
I think the lock file was generated with Paket 6!? That version is not
compatible with 5.0.

seanamosw <notifications@github.com> schrieb am So., 9. Aug. 2020, 23:01:

**Comment by seanamosw** [comment]
You would think so, but I've never touched Paket 6. It's also happened on multiple different dev machines (including my own) now with Paket > 5.245.0.

Paket always installed from `dotnet-tools.json` using `dotnet tool restore`.

To make it even more strange, I have projects where this doesn't happen! The only thing I can see that separates those projects that get this netcoreapp5.0 in their paket.lock is they are netcore2.2. The others are netcoreapp2.1 and netcoreapp3.

I'll see if I can gather some more info.

**Comment by isaacabraham** [comment]
@theimowski might be worth us rolling back to paket 5.245 in the interim?

**Comment by theimowski** [comment]
safe template is using paket 6 format already, so not sure why it would be an issue

**Comment by isaacabraham** [comment]
@theimowski Yes, that makes sense. I've never seen this issue before but we have seen it in the last couple of weeks with a customer and ourselves - I'll see if we can reproduce it to figure it out.

**Comment by Freymaurer** [comment]
As @theimowski mentioned something similiar, i am currently using the new SAFE template (2.0) with the paket version 5.249.2 and after i try to add any nuget paket to my project i also get the following error

`There was a problem while setting up the environment:
-> Error during parsing of 'C:\Users\Kevin\source\repos\Freymaurer\Test\paket.lock'.
-> invalid parameter 'netcoreapp5.0' after >= or < in '>= netcoreapp5.0)) (&& (== netstandard2.0) (>= uap10.0))'`

I get this error with a fresh SAFE template and then adding for example: Microsoft.Data.SqlClient.

`paket add Microsoft.Data.SqlClient --version 2.0.0 -p Server`

**Comment by mphelt** [comment]
same issue here. It was working for 5.249.2, but my builds started to failed since 5.250.0 showed up.

**Comment by forki** [comment]
@mphelt please try 5.251.0 and let me know

**Comment by mmuffins** [comment]
Just tried 5.251.0 and it fixed the issue for us.

**Comment by mphelt** [comment]
What makes paket.bootstrapper.exe (5.251.0) to actually download paket.exe 5.251.0?

**Comment by forki** [comment]
You may want to put

    version 5.251.0

at top of your paket.dependencies file
