### ISSUE TITLE
Duplicate ItemGroup > Reference in csproj under .Net Core

### ISSUE THREAD

**Issue by wahmedswl** [fsprojects/Paket#3911]
### Description
Paket is duplicating ```<ItemGroup>``` in csproj file in case of .Net Core. Its only happening with ```http``` dependencies of ```dll``` type.

```Paket version 5.249.2```

```
<ItemGroup>
    <Reference Include="Oracle.DataAccess">
      <HintPath>..\paket-files\net45\www.gitlab.local_12345\Oracle.DataAccess.dll</HintPath>
      <Private>True</Private>
      <Paket>True</Paket>
    </Reference>
    <Compile Include="..\paket-files\www.gitlab.local_12345\Version.cs">
      <Paket>True</Paket>
      <Link>paket-files/Version.cs</Link>
    </Compile>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
  <ItemGroup>
    <Reference Include="Oracle.DataAccess">
      <HintPath>..\paket-files\net45\www.gitlab.local_12345\Oracle.DataAccess.dll</HintPath>
      <Private>True</Private>
      <Paket>True</Paket>
    </Reference>
  </ItemGroup>
```

### Repro steps

Please provide the steps required to reproduce the problem

1. ```paket.dependencies``` has group

```
group net45
	source https://api.nuget.org/v3/index.json
	framework: net45
	redirects: on

	http http://www.gitlab.local:12345/api/v1/artifact/81052/Shared/References/32bit/net40/Odp/10g/Oracle.DataAccess.dll
	nuget Microsoft.AspNet.WebApi
```

2. ```paket.references``` has group

```
group net45
	File: Oracle.DataAccess.dll framework: net45
```

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

It should not duplicate the ```<ItemGroup>``` and project file should be like 

```
<ItemGroup>
    <Reference Include="Oracle.DataAccess">
      <HintPath>..\paket-files\net45\www.gitlab.local_12345\Oracle.DataAccess.dll</HintPath>
      <Private>True</Private>
      <Paket>True</Paket>
    </Reference>
    <Compile Include="..\paket-files\www.gitlab.local_12345\Version.cs">
      <Paket>True</Paket>
      <Link>paket-files/Version.cs</Link>
    </Compile>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
```

**Comment by wahmedswl** [comment]
Hi, any help to find this issue would be helpful or anything can help with? Doing something wrong etc?

**Comment by forki** [comment]
can you please upload a zip with the repro? would like to see what's going wrong. thanks

**Comment by wahmedswl** [comment]
@forki thanks for your prompt reply, i have created minimal repro at 
https://github.com/wahmedswl/Paket-3911

Thanks

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/3929 has a potential fix. Let's see if integration tests stay green

**Comment by wahmedswl** [comment]
thanks @forki, that's pretty quick 👍 is this only with sdk style projects? i was thinking to keep sdk style project and normal projects separate due to this issue.
But, if this solves it then wouldn't have to leave the sdk style projects as these are clean.

**Comment by wahmedswl** [comment]
```
source https://api.nuget.org/v3/index.json
framework: auto-detect
redirects: on
```
is it mandatory to include it in every group? that's pretty redundant

**Comment by forki** [comment]
can you please confirm that it works?

**Comment by wahmedswl** [comment]
Thanks @forki, issue has been fixed. I will test it on real project as well and will update if there is any issue.

Thank you so much 👍
