### ISSUE TITLE
Sponsor wanted for Code Certificate

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#3917]
We are looking for a new sponsor of a code certificate for Paket.

What we need: https://www.psw-group.de/code-signing/detail/c1-sectigo-code-signing/a40-microsoft-authenticode/
Ideally for at least 2 years

Reason: Multiple anti-virus softwares are complaining about paket.exe after download. This problem went away (mostly) after we started to code sign the releases. This certificate is now expired and we need a new one. The certificate would then be put on my machine - where I do the deployments.

PSW Group (the current certificate vendor) needs a company, so I'm afraid it can't be registered to a private person.

PS: Big thanks to [GROSSWEBER](https://grossweber.com/) for sponsoring us for multiple years in the past!

**Comment by Danl2620** [comment]
Can it be a company based in the US? And is there an English translation of the site (my German is quite rusty 😅 )?

**Comment by sja-schleupen** [comment]
is it important, that PSW Group issues the certificate?

**Comment by forki** [comment]
no we don't care about the vendor. 

The idea would be: a company buys a code sign cert for exe, similar to the one I linked above. And then the company lends me the cert file until it's expired. Of course we would put the company name somewhere onto our docs site.

**Comment by irgendwienet** [comment]
We (www.rhein-spree.com) can and will buy such a certificate for 5 years. Since we don't care where to buy it, let's use PSW group.

@forki can we hold the discussion here and proceed in private (e.g. Mail / Twitter)?

I just want to make sure nobody else is buying such a certificate at the same time.

**Comment by forki** [comment]
Awesome. Please just send me a DM
