### ISSUE TITLE
.NET 5 projects won't compile in Visual Studio when framework restriction is used

### ISSUE THREAD

**Issue by mk185147** [fsprojects/Paket#3939]
### Description

When you set in paket.dependencies restriction to net5.0 or net5.0-windows or similar then you will be able to compile with dotnet build but when you open such a solution in Visual Studio it won't load nuget packages for such .NET 5 based projects

### Repro steps

Use Paket 6.0.0-alpha054

1. Have a solution with projects that target netstandard2.0, netstandard2.1, net5.0 and net5.0-windows

2. Create paket.dependencies and add line:
framework: netstandard2.0, netstandard2.1, net5.0, net5.0-windows

3. Ensure the project use somethig from referenced nuget packages

4. Open the solution in Visual Studio

### Expected behavior

Visual Studio is able to work when paket.dependencies contains restriction to .NET 5 based projects

### Actual behavior

You will see that netstandard project have nuget packages loaded but net5.0 and net5.0-windows won't and if you try to compile them they will fail on the missing references. If you try to compile the same solution with dotnet build it will work.

**Comment by thinkbeforecoding** [comment]
It was working with the VS 16.8 last preview version.... what did they break ?!

**Comment by thinkbeforecoding** [comment]
Actually it seems to be working with v5.253.0
But not with 5.254.0 and 5.255.0
