### ISSUE TITLE
Paket load script main.group.fsx takes System.Web.Extensions from the wrong place?

### ISSUE THREAD

**Issue by njlr** [fsprojects/Paket#3945]
### Description

My Paket load scripts has a line `#r "System.Web.Extensions"`, which fails. 

### Repro steps

```
dotnet tool install paket
dotnet paket init
dotnet paket install
```

```
dotnet --version
3.1.403
```

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "paket": {
      "version": "5.241.6",
      "commands": [
        "paket"
      ]
    }
  }
}
```

Try to use the "load" scripts:

```
$ dotnet fsi Program.fsx

.paket/load/netcoreapp3.1/main.group.fsx(162,1): 
  error FS0078: 
    Unable to find the file 'System.Web.Extensions' in any of
     /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.9
     /home/njlr/project
     /usr/share/dotnet/sdk/3.1.403/FSharp/
```

### Expected behavior

The load scripts should work without modification. 

### Actual behavior

The load scripts fail at `#r "System.Web.Extensions"`

### Known workarounds

Comment out `#r "System.Web.Extensions"` in `.paket/load/netcoreapp3.1/main.group.fsx`

**Comment by smoothdeveloper** [comment]
@njlr can you share the `paket.dependencies` and `paket.lock` file as well as the commands you are issuing?

It is not clear how you are using the load script, also, the issue maybe with one of the nuget packages which reference wrong assembly rather than paket specific.

Above mentioned elements will help to sort it out.

**Comment by njlr** [comment]
I was unable to reproduce this issue with Paket `5.257.0`, so it appears this bug has been fixed!
