### ISSUE TITLE
Question: Is Paket available as a library?

### ISSUE THREAD

**Issue by njlr** [fsprojects/Paket#3988]
### Description

Is Paket available as a library?

### Repro steps

I tried the following:

```
source https://api.nuget.org/v3/index.json

storage: none
framework: net5.0, netstandard2.1

nuget FSharp.Core
nuget Paket
```

But I think this fetches _Paket the tool_ not a library. 

### Expected behavior

I would like to use the Paket code as a library. 

### Actual behavior

`paket install` succeeds, but `dontnet build` fails. 

```
error NU1202: Package Paket 5.257.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). 
Package Paket 5.257.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any

error NU1212: Invalid project-package combination for Paket 5.257.0. 
DotnetToolReference project style can only contain references of the DotnetTool type 
```

_(Note I also tried setting my project to `netcoreapp2.1`)_

### Known workarounds

Git Submodules?

**Comment by TheAngryByrd** [comment]
Have you tried [Paket.Core](https://www.nuget.org/packages/Paket.Core/6.0.0-beta8)?

**Comment by njlr** [comment]
Yes that works. Thanks!
