### ISSUE TITLE
Paket needs a logo

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#4]
Firstly let's look on available images.
What do you like?

Option 1:
![image](https://cloud.githubusercontent.com/assets/1197905/4096028/3f0ca934-2fbc-11e4-9660-2393c5bf91f1.png)
Option 2:
![image](https://cloud.githubusercontent.com/assets/1197905/4096034/4fb1e52e-2fbc-11e4-9e5a-acfaf436ef9e.png)
Option 3:
![image](https://cloud.githubusercontent.com/assets/1197905/4096042/5ea0b362-2fbc-11e4-9d7e-130b935a06bc.png)
Option 4:
![image](https://cloud.githubusercontent.com/assets/1197905/4096044/67d80b92-2fbc-11e4-9f29-1f20800072f4.png)
Option 5:
![image](https://cloud.githubusercontent.com/assets/1197905/4096046/702fe85a-2fbc-11e4-875b-915a458a4ee6.png)
Option 6:
![image](https://cloud.githubusercontent.com/assets/1197905/4096052/7abf3aaa-2fbc-11e4-838d-5016be10c6ca.png)
Option 7:
![image](https://cloud.githubusercontent.com/assets/1197905/4096056/82e33b64-2fbc-11e4-818c-4ecbf25e17c8.png)
Option 8:
![image](https://cloud.githubusercontent.com/assets/1197905/4096061/9239981a-2fbc-11e4-86b3-aecf6d333e40.png)
Option 9:
![image](https://cloud.githubusercontent.com/assets/1197905/4096064/9d25aa5c-2fbc-11e4-8173-a7ae230d0e39.png)
Option 10:
![image](https://cloud.githubusercontent.com/assets/1197905/4096067/a7a0c00c-2fbc-11e4-806b-8e5c739521be.png)
Option 11:
![image](https://cloud.githubusercontent.com/assets/1197905/4096072/aebcce80-2fbc-11e4-8c2a-f19af8cf01b3.png)
Option 12:
![image](https://cloud.githubusercontent.com/assets/1197905/4096079/b7ffe9c8-2fbc-11e4-8c50-954150882a6b.png)
Option 13:
![image](https://cloud.githubusercontent.com/assets/1197905/4096082/c39b55e2-2fbc-11e4-9830-d63a7d581f01.png)
Option 14:
![image](https://cloud.githubusercontent.com/assets/1197905/4096088/cb94a046-2fbc-11e4-974b-db2a8a2a691a.png)
Option 15:
![image](https://cloud.githubusercontent.com/assets/1197905/4096093/d4ce9fae-2fbc-11e4-9d33-f747ee5ebf04.png)
Option 16:
![image](https://cloud.githubusercontent.com/assets/1197905/4096095/dd5910a0-2fbc-11e4-8281-64654469b47d.png)
Option 17:
![image](https://cloud.githubusercontent.com/assets/1197905/4096096/e4d663d2-2fbc-11e4-9f1a-a1339cc0e2c3.png)
Option 18:
![image](https://cloud.githubusercontent.com/assets/1197905/4096101/ee425a7a-2fbc-11e4-8ebc-96a79390c546.png)
Option 19:
![image](https://cloud.githubusercontent.com/assets/1197905/4096109/fb53f55c-2fbc-11e4-9268-08619890f6d4.png)
Option 20:
![image](https://cloud.githubusercontent.com/assets/1197905/4096116/04354f0e-2fbd-11e4-9fee-24a89e1934ff.png)
Option 21:
![image](https://cloud.githubusercontent.com/assets/1197905/4096122/19a4ba46-2fbd-11e4-922a-330cc1589dec.png)
Option 22:
![image](https://cloud.githubusercontent.com/assets/1197905/4096125/269c61d6-2fbd-11e4-963c-4cabdde9bf5b.png)
Option 23:
![image](https://cloud.githubusercontent.com/assets/1197905/4096127/333365d4-2fbd-11e4-93e8-7823150dd19c.png)
Option 24:
![image](https://cloud.githubusercontent.com/assets/1197905/4096130/422a25fa-2fbd-11e4-8a7a-e6fb3f6a195a.png)
Option 25:
![image](https://cloud.githubusercontent.com/assets/1197905/4096133/5cd3e684-2fbd-11e4-8b40-7572cef8cc40.png)
Option 26:
![image](https://cloud.githubusercontent.com/assets/1197905/4096136/6764b100-2fbd-11e4-90f2-d563dc9b0d25.png)
Option 27:
![image](https://cloud.githubusercontent.com/assets/1197905/4096138/78860c5e-2fbd-11e4-9ff0-7196b97a1043.png)
Option 28:
![image](https://cloud.githubusercontent.com/assets/1197905/4096141/8786ee6c-2fbd-11e4-945b-34c10973ae60.png)
Option 29:
![image](https://cloud.githubusercontent.com/assets/1197905/4096148/97715d80-2fbd-11e4-9602-c77041ddeca0.png)
Option 30:
![image](https://cloud.githubusercontent.com/assets/1197905/4096154/a2e53394-2fbd-11e4-961e-39b88f93520c.png)

Option 31(*):
![image](https://cloud.githubusercontent.com/assets/1197905/4096317/eb16ff2e-2fbf-11e4-8b6f-877359824d6f.png)

**Comment by smoothdeveloper** [comment]
@sergey-tihon do you happen to have a .svg for the logo? If we can get one, it should go in vscode for file icons, and probably other places.

**Comment by sergey-tihon** [comment]
Sorry no, IIRC I did not have it 9 years ago too.
