### ISSUE TITLE
Cannot resolve reference to AspNet, but can resolve with other packages

### ISSUE THREAD

**Issue by jake-bickle** [fsprojects/Paket#4011]
Hi, I am sure this is an issue on my end, but I cannot find any information online about solving this.

### Description

On Paket version 5.257.0 (macOS Catalina 10.15.7), despite installing Microsoft.AspNet.SignalR via Paket, I am still unable to import it.

### Repro steps

1. Enter the following
```
mkdir my-proj
cd my-proj
dotnet new console
dotnet new tool-manifest
dotnet tool install paket
dotnet tool restore
dotnet paket init
paket add Microsoft.AspNet.SignalR  # This is the problematic package.
paket add Newtonsoft.json  # This ends up being imported just fine.
paket update
paket install
paket restore
```
2. In `Program.cs`, add the following directives at the beginning of the file
 ```
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
```
3. Overwrite `my-proj.csproj` file with:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>my_proj</RootNamespace>
  </PropertyGroup>
  <Import Project="/Users/jacobbickle/dev/my-proj/.paket/Paket.Restore.targets" />
</Project>
```
4. Create a new file `paket.references`
```
Microsoft.AspNet.Signalr
Newtonsoft.Json
```
5. `dotnet build`

### Expected behavior

`Program.cs` is compiled without any errors or warnings.

### Actual behavior

I get one build error related to Microsoft.AspNet.
```
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/jacobbickle/dev/my-proj/Program.cs(1,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [/Users/jacobbickle/dev/my-proj/my-proj.csproj]

Build FAILED.

/Users/jacobbickle/dev/my-proj/Program.cs(1,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [/Users/jacobbickle/dev/my-proj/my-proj.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.98
```

### Known workarounds

Unfortunately, none.

Of course, let me know if there's any other information I can provide.

**Comment by baronfel** [comment]
The problem is probably that you're missing a `FrameworkReference` to the AspNetCore framework (which is how this is distrbuted since .Net Core 3 released. You no longer get AspNetCore itself from nuget, only satellite packages/frameworks on top of it like SignalR.

To get aspnetcore in a .net core 3 or greater application, you can either:

* Manually add a `<FrameworkReference Include="Microsoft.AspNetCore.App" />` to your project files, or 
* change the `Sdk` node of your project file to `Microsoft.NET.SDK.Web` instead of `Microsoft.NET.Sdk`, which will do this and several other web-related things for you

**Comment by baronfel** [comment]
Also, `Microsoft.AspNet.SignalR` is the old .net framework package and only support .net framework 4.5 from what I can read here: https://www.nuget.org/packages/Microsoft.AspNet.SignalR/2.4.1

You probably want `Microsoft.AspNetCore.SignalR`: https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/

**Comment by jake-bickle** [comment]
Switched the Sdk to `Microsoft.NET.SDK.Web` and am using `Microsoft.AspNetCore.SignalR` which works now. I'm still learning C# and it's got a curve to it. I likely wouldn't have ever found out that I needed to append ".Web" to the SDK since I have found so little information about it online. Thanks for your help!
