### ISSUE TITLE
Support .net 6

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/Paket#4012]
### Description

with paket 6.0.0-beta10, the "framework" tag cannot be set to net6.0

### Repro steps

create paket file like so:

```
version 6.0.0-beta10

source https://api.nuget.org/v3/index.json
framework: net6.0
storage: none
```

Then run `dotnet paket install`

### Expected behavior

It works.

### Actual behavior

```
Paket failed with
-> Error in paket.dependencies line 4
     Could not parse framework 'net6.0'. Try to update or install again or report a paket bug.
```

**Comment by pbiggar** [comment]
Perhaps there is a different way to use .net 6 (preview 3), but this seemed the natural way and it didn't work. I couldn't find docs or issues pointing to another way to do it.

**Comment by smoothdeveloper** [comment]
@pbiggar I've seen it but haven't had chance to hack on it.

There is probably adjustments to make to this file in the first place:
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Versioning/FrameworkHandling.fs

As well as adding a test case:
https://github.com/fsprojects/Paket/tree/master/integrationtests/scenarios

**Comment by pbiggar** [comment]
Thanks so much, and for the speedy update. I'll check it out this week.

**Comment by pbiggar** [comment]
This seems to work, see https://github.com/darklang/dark/pull/3044

Thanks!

**Comment by smoothdeveloper** [comment]
@pbiggar thanks for the update, could you close the issue (and we create another one if there is still something down the line)?
