### ISSUE TITLE
Paket.Core strict reference to Fsharp.Core 5.0

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/Paket#4034]
### Description

Currently, `Paket.Core` has a [strict reference](https://github.com/fsprojects/Paket/blob/master/paket.dependencies#L6) to `FSharp.Core` `5.0`.  This makes it difficult to use if anything is referencing a higher `FSharp.Core` version such as `5.0.1`

```bash
Paket failed with
-> There was a version conflict during package resolution.
     Resolved packages:
      - Paket.Core 6.0.0-beta8
     Conflict detected:
      - Oryx 4.0.0 requested package FSharp.Core: >= 5.0.1
      - Dependencies file requested package FSharp.Core: >= 0
      - Paket.Core 6.0.0-beta8 requested package FSharp.Core: 5.0*
```

### Repro steps

1. In a new paket project, `dotnet paket add Paket.Core`
2. `dotnet paket add Oryx 4.0.0` 

### Expected behavior

Both can be added to a project

### Actual behavior

Oryx can only be referenced by version 2.0

### Known workarounds

Not sure of any

**Comment by forki** [comment]
please retry with rc003

**Comment by Tarmil** [comment]
This issue is happening again with Paket.Core 8.0.0-alpha002, which depends strictly on FSharp.Core 6.0.3.
