### ISSUE TITLE
Using Paket with Shared projects - referencing different package versions from different projects

### ISSUE THREAD

**Issue by hmemcpy** [fsprojects/Paket#405]
I'm trying to use Paket on a project (a R# plugin) which uses Shared projects, and duplicated .csproj/packages.config files for referencing different R# SDK versions.

An example of such structure is:

    /MyPlugin.sln
    /MyPlugin.Domain/MyPlugin.Domain.8.2.csproj
    /MyPlugin.Domain/MyPlugin.Domain.9.0.csproj
    /MyPlugin.Domain/packages.MyPlugin.Domain.8.2.config // <-- NuGet-supported packages.config format
    /MyPlugin.Domain/packages.MyPlugin.Domain.9.0.config
    ...
etc.

The `packages.*.config` contains a reference to a particular version of ReSharper SDK, either 8.2 or 9.0. NuGet is smart enough to update the relevant csproj file.
I'm using this to avoid `#if`/`#else` hell in my project, so I'm using partial classes to accommodate for the differences in the API.

I want to migrate this structure to Paket. 
Couple of questions:

1. Can I even do this? Can Paket support different `packet.dependencies` in the same directory?
2. Same question about `paket.references` - how do I add a reference to a different version of the SDK in different projects?
3. Where do I put those files? Per-project? At solution level?

Thanks!

**Comment by forki** [comment]
I think this can be done with groups since v2
