### ISSUE TITLE
Paket does not recognize net6.0-android30.0

### ISSUE THREAD

**Issue by Dolfik1** [fsprojects/Paket#4054]
### Description

Recently Xamarin added new platform to its packages. New platfrom breaks Paket:

```Could not detect any platforms from 'net6.0-android30.0' in Xamarin.AndroidX.Collection 1.1.0.8, please tell the package authors```

Since today I cannot use Paket with Xamarin.Android without pinning packages to the oldest version.

**Comment by DonnieKiel** [comment]
stumbled on same issue
