### ISSUE TITLE
paket.bootstrapper.exe does not work on a  macbook

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Paket#4058]
<img width="250" alt="Screen Shot 2021-08-02 at 7 05 27 AM" src="https://user-images.githubusercontent.com/1394644/127866691-c2bc8db5-90bd-49e5-8459-8e5f51065694.png">
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Please provide a description of any known workarounds.

**Comment by baronfel** [comment]
The bootstrapper is a really really old way of using paket, and it should be invoked with mono.

Have you tried using the dotnet CLI tool for paket instead? `dotnet tool install paket` should be all you need to get started.

**Comment by jamessdixon** [comment]
I used "mono" in front and it worked.
