### ISSUE TITLE
Issue with two parameters of the "PackTask" task (PackageReadmeFile & NoDefaultExcludes)

### ISSUE THREAD

**Issue by ThierryPot** [fsprojects/Paket#4069]
### Description

I have two errors when building with `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`

> .paket/Paket.Restore.targets(369,15): error MSB4030: " " is an invalid value for the "NoDefaultExcludes" parameter of the "PackTask" task. The "NoDefaultExcludes" parameter is of type "System.Boolean"

> .paket/Paket.Restore.targets(368,15): error MSB4064: The "PackageReadmeFile" parameter is not supported by the "PackTask" task loaded from assembly: NuGet.Build.Tasks.Pack, Version=5.11.0.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35 from the path: /usr/share/dotnet/sdk/5.0.400/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Build.Tasks.Pack.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.

### Repro steps

Please provide the steps required to reproduce the problem

1. docker run --rm -t -i mcr.microsoft.com/dotnet/sdk:5.0 bash (at the time I'm writing this ticket the sdk is version 5.0.400)
2. clone a simple helloworld project using a nugget to build with the following csproj:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	<Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```
3. dotnet new tool-manifest
4. dotnet tool install paket
5. dotnet paket restore
6. dotnet build project

By removing the extra space line 389 in .paket/Paket.Restore.targets the first error is fixed (MSB4030) and the second one occurs (MSB4064)

### Expected behavior

No error

### Actual behavior

Errors MSB4030 & MSB4064 described before

### Known workarounds

Use sdk version 5.0.300

**Comment by wesleyantal** [comment]
Hi @ThierryPot,
if you are not using this property (NoDefaultExcludes) from Paket.Restore.targets file, you can remove it. If the build show other error with the property before, you can delete as well.

**Comment by baronfel** [comment]
I can't reproduce this anymore on version 6.0.13 of paket, following your steps above.

**Comment by ThierryPot** [comment]
Right it works as expected with version 6.0.13
Thanks
