### ISSUE TITLE
Paket 6.0.6 does not correctly install packages

### ISSUE THREAD

**Issue by yaakov-h** [fsprojects/Paket#4075]
### Description

Paket v6.0.6 seems to be sometimes unpacking packages one directory too high in the filesystem hierarchy, which results in build-time warnings from .NET.

I did not see this behaviour under any previous version of Paket up to and including v6.0.0-beta8.

### Steps to Reproduce

I wish I knew, I can't get this to repro on demand.

The steps I took when this happened twice were to take an existing repo using Paket 5.x, update it to Paket 6.0.6, and add new net5.0 build targets (the repos did not previously target net5.0, only net472, netstandard2.0, and netstandard2.1).

The Paket groups have `storage: none` defined.

### Expected behavior

Paket installs packages as done previously and as done by NuGet. There are no new build warnings in my project.

### Actual behavior

![image](https://user-images.githubusercontent.com/426009/130010576-b3dcbbf2-e58b-4184-8c1b-918f9cff4667.png)

Errors from MSBuild:
```
warning Undefined: The folder 'C:\Users\yaakov.smith\.nuget\packages\system.reflection.typeextensions\lib' contains an invalid version.
warning Undefined: The folder 'C:\Users\yaakov.smith\.nuget\packages\system.reflection.typeextensions\ref' contains an invalid version.
warning Undefined: The folder 'C:\Users\yaakov.smith\.nuget\packages\system.reflection.typeextensions\runtimes' contains an invalid version.
```

**Comment by forki** [comment]
@baronfel is https://github.com/fsprojects/Paket/pull/4033 related?

**Comment by yaakov-h** [comment]
That's quite possible. rc005 seems to be working as expected, and that was only merged into rc006.

**Comment by yaakov-h** [comment]
Got a repro project up at https://github.com/yaakov-h/paket4075

Run `run-to-repro.cmd`, then inspect any of the package folders under `<path to repo>\nuget\<package name>`:

![image](https://user-images.githubusercontent.com/426009/131951386-8d8641b6-8306-4af7-9068-d01bed668012.png)

**Comment by baronfel** [comment]
@yaakov-h thank you! I'll try to take a look soon.

**Comment by baronfel** [comment]
yeah that's definitely quite odd and I've reproduced it with your sample.

**Comment by baronfel** [comment]
I think I've found the reason for this, and it's entirely me being dumb and the nuget client APIs being utterly incomprehensible and very very overabstracted. It comes down to the difference in behavior/implementation of [ExtractPackageAsync](https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs#L20) and [InstallFromSourceAsync](https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs#L353).

The former is what is currently in use in Paket, and it takes a path resolver that gives back old-style nuget paths. This is why we had a separate 'now move the extracted files to their proper versioned directory' step after this extraction.  However, `InstallFromSourceAsync` takes a versioned path resolver and does all of the correct things by default, meaning we can remove our custom copying code for the extraction, as well as no longer leaving any extracted files in the package root.

MR coming up shortly.
