### ISSUE TITLE
Wrong version number?

### ISSUE THREAD

**Issue by Flohack74** [fsprojects/Paket#4082]
### Description

The latest paket version number reporting seems odd

![grafik](https://user-images.githubusercontent.com/16186470/133402885-1d41c393-d629-4986-84a3-4f340ad5cf7e.png)

Is this intentional?

**Comment by baronfel** [comment]
This is probably introduced in the change I made in #4080, the AssemblyInfo generation probably isn't getting done correctly for the packed paket tool. Can you clarify a bit on what the `paket-pack` executable you're running is? it is some kind of shell script around invoking Paket?

**Comment by baronfel** [comment]
Yeah, if you look at [nuget.info for Paket 6.1.0](https://nuget.info/packages/Paket/6.1.0), the shipped, merged `paket.exe` has an informational version of 1.0.0, but the netcoreapp2.x paket.dll has the correct version

**Comment by Flohack74** [comment]
Thanks! I was about to clarify that paket-pack is just a shell script wrapper with my needed constant parameters to speed up typing ;)

**Comment by Flohack74** [comment]
Slightly better its now `Paket version 6.1.2+35b64ff2d36b1bc7d17bca871fcb7323ad6194d8`
