### ISSUE TITLE
Is there automation to revert *paket convert-from-nuget*? [Question]

### ISSUE THREAD

**Issue by skowronek-relativity** [fsprojects/Paket#4090]
### Description

I have a solution with around 60 projects. We use paket, but with multpiple groups with projects referencing each other, we got some trouble with transitive netstandard2.0 dependencies etc - it all became just huge ugly mess. Since our company policy is "we don't support paket", I wanted to try and remove paket to test whether it changes anything.

Is there a command that reverts `paket convert-from-nuget`? The process is fairly straight forward - copy paket.references into csproj and put it into PackageReference and remove inclusion of paket.restore.targets (at least for SDK projects)

### Repro steps

Please provide the steps required to reproduce the problem

1. Convert solution to paket with `paket convert-from-nuget`

### Known workarounds

I know that I can script that in few minutes (and probably will while I wait on the response), but is there a built in way to do this?

Maybe this could be a feature?

**Comment by hvester** [comment]
Same question has been asked here: https://github.com/fsprojects/Paket/issues/3997

**Comment by skowronek-relativity** [comment]
So no chance for this to be a feature? thanks for the link, it's very usefull

**Comment by jpdlpassos** [comment]
hi, @skowronek-relativity I'm also interested in reverting for more than 200 projects
did you manage to find a way to automate it?
thank you!
