### ISSUE TITLE
Updates to clarify fsprojects policies

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Paket#4094]
Hi Paket admins,

@sergey-tihon  and I have updated the policies we use for "fsprojects" to clarify things like when we would consider archiving a project, see https://github.com/fsprojects/fsprojects-admin/blob/master/README.md

We'd be grateful if you check you're ok with the policies and/or discuss here: https://github.com/fsprojects/fsprojects-admin/discussions/29

thanks

**Comment by sergey-tihon** [comment]
Now we can mention teams inside organisation - @fsprojects/paket-team

**Comment by dsyme** [comment]
Oh cool!
