### ISSUE TITLE
Mixed .NET Framework and .NET Core solution - how to install/restore all packages

### ISSUE THREAD

**Issue by Flohack74** [fsprojects/Paket#4099]
### Description

Seems we have an odd issue here, after converting an existing solution from framework to Core, paket deliberately ignores that project in all operations.
- Wont install packages, wont modify csproj file
- dotnet paket restore does not work on top level (Specify which project file to use because this 'C:\xxxxx' contains more than one project file.) regardless of what I specify there. It also does not work in the projects subfolder since it then says Could not execute because the specified command or file was not found.

How are mixed solutions ought to be set up these days, and which order of commands are needed so that I get everything restored? Thanks!

**Comment by Flohack74** [comment]
Edit: It in fact adds   <Import Project="..\..\..\..\..\.paket\Paket.Restore.targets" /> correctly, but thats all what happens ;)

**Comment by Flohack74** [comment]
Humm I was hoping I get a quick pointer to what we are doing wrong... Seems current solution is only to let NuGet handle the .NET core projects, but I would hate to leave it like this...

**Comment by seanamos** [comment]
I'm not aware of anything that should stop paket from working with mixed .NET 4.x and .NET Core projects. I don't have an example on hand at the moment though.

If you check in the the .NET Core .csproj, does it have a line similar to this:
```xml
<Import Project="..\.paket\Paket.Restore.targets" />
```
(make sure the path is correct for your structure)

If that line was missing then paket wouldn't work with that project, the automatic conversion might not have added it.

The other potential issue is in your paket.dependencies file, is there a framework line?
```
framework: xxxxx
```
That would cause only dependencies that match that framework version to be added.

**Comment by Flohack74** [comment]
@seanamos Indeed I found the limiting `framework: net48` today morning, after re-thinking all potential issues ;) so yes case can be closed.
