### ISSUE TITLE
Paket not extracting XML docs correctly, breaks XML doc intellisense

### ISSUE THREAD

**Issue by seanamos** [fsprojects/Paket#4103]
Version 6.2.1

### Description

When paket extracts `.xml` files from nuget packages, it extracts them as .zip files. eg. `Microsoft.CSharp.xml.zip`.

### Repro steps

```
# from a solution folder that uses paket with `storage: none`

dotnet nuget locals -c all
rm -rf paket-files # make sure paket restores files
dotnet paket restore

cd ~/.nuget/packages
find . -name "*.xml*"

# observe hundreds of .xml.zip files
```
### Known workarounds

Run a script to unzip the `.xml` doc files in the nuget global cache

**Comment by seanamos** [comment]
I believe this issue is in: https://github.com/fsprojects/Paket/blob/0cb7d7807342c91a0ee1cee518b40fcf990d3add/src/Paket.Core/Dependencies/NuGetCache.fs

```
let private extractionContext = NuGet.Packaging.PackageExtractionContext(PackageSaveMode.Defaultv3, XmlDocFileSaveMode.Compress, signingContext, nugetLogger)
```

Specifically `XmlDocFileSaveMode.Compress`. Judging from https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/PackageExtraction/XmlDocFileSaveMode.cs , you would think `XmlDocFileSaveMode.None` would be the "legacy"/incorrect option.

However that is exactly what Nuget uses: https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/PackageExtraction/PackageExtractionBehavior.cs (Defaults to `None`)

**Comment by baronfel** [comment]
I concur with @seanamos's analysis, this change should be made and pushed out.
