### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by fourglobe302500** [fsprojects/Paket#4105]
### Description

I created a simple project with this form

* src
  * <console application>
  * CoreLib
  * Tests
* sln

being sln the solution file and converted it to paket but I can't find anywhere that says how I can referende CoreLib in Tests

I've runned throgh lots of posts and the documentation but just can't find anyqhere how. If I can receive any help I would be gratefull

**Comment by 64J0** [comment]
If you are using Linux and have the .NET SDK then try using this command on the terminal:

```bash
dotnet add ./src/Tests.fsproj reference ./src/CoreLib.fsproj
```

**Comment by fourglobe302500** [comment]
Thanks

**Comment by 64J0** [comment]
Did it work @fourglobe302500 ?

**Comment by fourglobe302500** [comment]
Yes
