### ISSUE TITLE
Support net7.0 TFM

### ISSUE THREAD

**Issue by kerams** [fsprojects/Paket#4119]
A "nightly" is available from here https://github.com/dotnet/installer, no official previews yet, so there's no rush.

**Comment by kerams** [comment]
A preview is out now too https://devblogs.microsoft.com/dotnet/announcing-net-7-preview-1/.

Is it not possible to automate this thing so that someone does not have to manually go in and patch a new TFM every year? Or maybe add support for 7, 8 and 9 in advance?

**Comment by kerams** [comment]
That's very true, you really can't be quite certain with MS :).

**Comment by forki** [comment]
I just published  a alpha version with support for net7. Please check it out. thanks

**Comment by kerams** [comment]
Looks good, many thanks.

**Comment by Thorium** [comment]
Could the non-alpha be updated to know net7.0 target?
I'm struggling to do a Fake build as it fails:

```
There was a problem while setting up the environment:
-> Error during parsing of 'C:\myproject\paket.lock'.
-> failed to parse line '      Microsoft.Win32.Registry (>= 5.0) - restriction: && (< net472) (< net7.0) (>= netstandard2.0)' (invalid parameter 'net7.0' after >= or < in '< net7.0) (>= netstandard2.0)') (Could not parse 'framework: restriction: && (< net472) (< net7.0) (>= netstandard2.0)' as key/value pairs.)
        -  invalid parameter 'net7.0' after >= or < in '< net7.0) (>= netstandard2.0)'
        -  Could not parse 'framework: restriction: && (< net472) (< net7.0) (>= netstandard2.0)' as key/value pairs.
        -> invalid delimiter at position 22
```

This happens with both
`7.1.5+e2fe7c693356a5e70a74cc01501f7dc5f8996695` and 
`7.2.0-alpha001+e9bb0b5eadeb7124835087319e57df9271f2d449`
..so I'm kind of lost.

**Comment by Thorium** [comment]
.NET seems to pick the sdk from `global.json`, for example, if I'd try to avoid .NET 7 yet, then I do:
```json
{
    "sdk": {
        "version": "6.0.403",
        "rollForward": "minor"
    }
}
```
Is that file totally ignored by Paket or not?

**Comment by Thorium** [comment]
I think updating Fake-cli from 5.23.1 to 6.0.0-alpha004 and avoiding 7.0 in the global.json did the trick.
