### ISSUE TITLE
NuGet 6.3 and HTTPs everywhere

### ISSUE THREAD

**Issue by akhansari** [fsprojects/Paket#4171]
### Description

Since NuGet 6.3 (SDK 6.0.400), Paket fails to restore when the source is not HTTPs.

https://devblogs.microsoft.com/nuget/https-everywhere/

https://github.com/NuGet/NuGet.Client/blob/6.3.0.131/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L221

### Repro steps

paket install

### Expected behavior

The restore should work with warnings.

### Actual behavior

The restore fails with this message:
Paket failed with
-> dotnet restore "xyz.sln" failed

### Known workarounds

Downgrade the SDK version:
`dotnet new globaljson --sdk-version 6.0.303`

**Comment by jakob-ledermann** [comment]
Could you maybe document the Version of `paket` you have/had this problem with?
Using Version `7.2.1+8e4eb74b42fbd45f39f7afce9184c16ebb65f16c` I do see the nuget warnings but can still successfully execute `paket install`

**Comment by akhansari** [comment]
Yes I no longer reproduce the bug. I close the issue.
