### ISSUE TITLE
Paket fails to add/remove packages when storage is set to none

### ISSUE THREAD

**Issue by superrnovae** [fsprojects/Paket#4177]
### Description

After settings `storage: none` in paket.dependencies, paket can no longer add or remove packages.

### Repro steps

1. Set `storage: none` in paket.dependencies

2. Run `paket.exe restore --force`

3. Run `paket.exe add --project test EntityFramework` or `paket.exe remove --project test EntityFramework`

### Expected behavior

Paket is able to find the tools and add/remove packages.

### Actual behavior

Paket fails with the following error:   

`-> C:\Users\root\.nuget\packages\.tools\microsoft.visualstudio.web.codegeneration.tools\2.0.2 doesn't exist. nuspec file can't be loaded.`

### Known workarounds

Haven't found any.

**Comment by ChrSteinert** [comment]
Do you still have that issue with a more recent version?
Have you tried paket as a dotnet tool?

**Comment by superrnovae** [comment]
Sorry for the late reply, I no longer use paket, so I can't tell whether the issue still exists or not.
