### ISSUE TITLE
Support net8.0 TFM

### ISSUE THREAD

**Issue by kerams** [fsprojects/Paket#4199]
New year, new https://github.com/fsprojects/Paket/issues/4119

**Comment by forki** [comment]
If someone could provide a PR, then I'm happy to merge and release

**Comment by GordonBeeming** [comment]
Great stuff, thanks @forki 💪

**Comment by smoothdeveloper** [comment]
Taking a look at it: #4219

**Comment by forki** [comment]
thanks @smoothdeveloper . I just released it as 8.0.0-alpha001

**Comment by kerams** [comment]
It works, much obliged.
