### ISSUE TITLE
paket.exe release 9.0.0 download has incorrect version signature

### ISSUE THREAD

**Issue by rupertbenbrook** [fsprojects/Paket#4277]
### Description

The paket.exe file available in the 9.0.0 release has an incorrect version signature, causing 404 errors when it requests the SHA256 hash from GitHub, and can cause build failures for .NET Framework projects.

### Repro steps

1. Download paket.exe from release 9.0.0 [link](https://github.com/fsprojects/Paket/releases/download/9.0.0/paket.exe)
2. Run `paket.exe --version`

### Expected behavior

The output to running `paket.exe --version` for release 9.0.0 should be:
```
Paket version 9.0.0+9a1e773deca255dc6d1e7f80058193c43ea1e959
```

### Actual behavior

The output to running `paket.exe --version` for release 9.0.0 is actually:
```
The remote server returned an error: (404) Not Found. (Github - cached (temporarily ignore updates))
Paket version 9.0.0-alpha001+e5a50effc24f7d0cfbadb3ee08e9de7c5184c408
```

Debugging the URL requested when running shows it requests:

https://github.com/fsprojects/Paket/releases/download/9.0.0-alpha001+e5a50effc24f7d0cfbadb3ee08e9de7c5184c408/paket-sha256.txt

Which does not exist, because it's an incorrect version signature.

I have also found this to cause failures trying to do a `paket update` or `paket install` for a number of our .NET Framework based projects, but I've not managed to put together a repro as yet.

### Known workarounds

None found.

**Comment by 1eyewonder** [comment]
I'm having errors over in .netcore as well

Here's the `dotnet --info` from my machine
![image](https://github.com/user-attachments/assets/96554624-2e14-42bf-8301-47853e4a9c5e)

**Comment by Flohack74** [comment]
Unfortunately this broke all of our Azure DevOps pipelines, since even though paket successfully finishes its job, the auto updater sets a negative return code.

**Comment by forki** [comment]
I'm working on bringing it back. It's really hard.

Flo Lee ***@***.***> schrieb am Fr., 15. Nov. 2024, 10:23:

**Comment by forki** [comment]
please retry

**Comment by rupertbenbrook** [comment]
I've just checked and that looks much better, thank you.
```
paket.exe --version
Paket version 9.0.1+5ce3e318e789ca069a1e00c3aefa816721c73af1
```
