### ISSUE TITLE
Refactor towards ROP

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#464]
What do you guys think about employing the [Railway Oriented Programming](http://fsharpforfunandprofit.com/rop/) in Paket codebase?

One obvious benefit would be that in case of any failure, no file would get modified. (yeah I know one could simply ``git reset``, but that is probably not the best UX)

A command-line tool seems like a good candidate for the ROP technique.
As a volunteer I could do an experiment with the commands I'm most familiar with, i.e. ``convert-from-nuget`` and ``simplify`` to see where we can get to.

Edit:
List of paket commands that use ROP:
- [x] Init
- [ ] Add
- [ ] Remove
- [ ] Install
- [ ] Restore
- [ ] Update
- [x] Outdated
- [x] ConvertFromNuget
- [x] InitAutoRestore
- [x] Simplify
- [x] FindRefs
- [x] Config

**Comment by forki** [comment]
are you going to refactor other commands as well?

**Comment by theimowski** [comment]
I plan to, but surely it can take more time. 
Applying ROP gradually (i.e. not in a single PR) to the commands should be less error-prone

**Comment by forki** [comment]
:+1

**Comment by forki** [comment]
I wonder what Scott Wlashin is thinking about this!? It's becoming probably the biggest OSS project on ROP.

**Comment by theimowski** [comment]
yeah, it'd be great if he could review the stuff one day when more commands use ROP, and tell whether that's what he meant :+1:
