### ISSUE TITLE
0.20.1: paket install takes 40 seconds while 0.18 took 2 seconds

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#487]

**Comment by forki** [comment]
please retry with 0.20.10
as before the second install should be a lot faster, even with multiple feeds

**Comment by vasily-kirichenko** [comment]
32 seconds first `paket install` (after updating to 0.20.11), 5 seconds subsequent `install`s. 

Great job!

**Comment by forki** [comment]
should be even faster now.
Could you please retry with 0.20.21?

**Comment by vasily-kirichenko** [comment]
4 seconds.
