### ISSUE TITLE
Install changes gist to github

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#498]
I think the latest bundle-like install came with a little twist. Whenever there is a gist dependency in `paket.dependencies` running `paket install` it gets rewritten to `github X/Y FULLPROJECT`

**Comment by forki** [comment]
Mhm that's not good.

**Comment by forki** [comment]
do you have a public repo where I can reproduce this?

**Comment by tpluscode** [comment]
Actually it seems the problem is not with install but rather with add. At least I can't reproduce now.

Try this [repo](https://github.com/wikibus/data.wikibus.org/) and run `src/.paket/paket.exe add nuget nhibernate`

This will change gist into github in paket.dependencies

**Comment by forki** [comment]
Thanks for reporting. Fixed.
