### ISSUE TITLE
Forced update resets gist dependency

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#499]
When there is a gist dependency locked to some commit other than the initial running `paket.exe update --force` downloads the gist's first commit and updates `paket.lock` accordingly. Can be reproduced in [this repo](https://github.com/wikibus/data.wikibus.org/)

**Comment by forki** [comment]
strange I get the following expected diff:

![image](https://cloud.githubusercontent.com/assets/57396/5594733/5c8409bc-9259-11e4-98fa-77a781a84732.png)

**Comment by tpluscode** [comment]
That's it precisely what I meany though it seem that I wrongly assumed `5d9` was the initial commit. It's even worse because it's the gist id only. I though they were the same thing. And `77ad6` is the latest revision, which should appear in `paket.lock` after running update, forced or otherwise.

**Comment by forki** [comment]
Look into your dependencies file. You pinned the commit to 5d9 - I think it's all correct now.

**Comment by tpluscode** [comment]
Why do say I pinned the commit? [Looks fine to me](https://github.com/wikibus/data.wikibus.org/blob/master/src/paket.dependencies#L34)

**Comment by forki** [comment]
sorry my bad. that hash is not the version but the gist identifier.

will try to fix asap.
