### ISSUE TITLE
Add --logfile option and trace all output to this file 

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#501]
Sometimes `paket restore --references-files` fails with code 1 and it's impossible to understand what's went wrong. Build server log contains the following:

```
"...aproject.csproj" (Rebuild target) (46:2) ->
[12:43:07][Step 3/3]        (RestorePackages target) -> 
[12:43:07][Step 3/3]          ...\.paket\paket.targets(36,5): error MSB3073: The command ""...\.paket\paket.exe" restore --references-files "...aproject\paket.references"" exited with code 1. 
```

It would be great if Paket writes error message / full stack trace into stdout (or whatever place such that TeamCity can consume it and show in its logs) in case of error.

**Comment by forki** [comment]
mhm, not sure how to do this. It seems all messages are eaten by MsBuild

**Comment by vasily-kirichenko** [comment]
Am I right that paket.exe returns non-zero error code if an unhandled exception occures?

**Comment by forki** [comment]
on every error.

**Comment by forki** [comment]
(this will probably be improved when we moved to railway oriented programming)

**Comment by vasily-kirichenko** [comment]
How can Either monad style design help with it? The whole paket will be a function of type `unit -> Choice<_, exn>` or something like this and you will able to get `exn` in case of `Choice2Of2`, but it's not different from `try <do the whole paket logic here> with e -> ...`. 

Can paket.exe write exceptions in a (optional) log file? It'd allow to investigate errors.

**Comment by forki** [comment]
what would be a good location for such a file?

**Comment by vasily-kirichenko** [comment]
User's temp folder I think.

**Comment by vasily-kirichenko** [comment]
And it would be great if location of this file appears in teamcity log.

**Comment by forki** [comment]
then we're back to the beginning. ;-)

We need to figure out why teamcity/MsBuild captures the output.

**Comment by vasily-kirichenko** [comment]
I think if we pass log file path as an explicit argument, it would be enough to easily find it later.
