### ISSUE TITLE
Improve diagnostics output in verbose mode

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#503]
```
"...\.paket\paket.exe" restore --references-files "...\...\paket.references"
Paket version 0.20.21.0
found: ...\paket.dependencies
```

and it hungs on this stage forever. 

I suggest to add more output in `-v` mode in order to understand what exactly it's doing.

**Comment by vasily-kirichenko** [comment]
It turns out it waits forever here:

![image](https://cloud.githubusercontent.com/assets/873919/5596432/b6910a28-929e-11e4-9ad3-bd818d1ec5b6.png)

**Comment by forki** [comment]
yep that's what I feared.
maybe there is a zombie process that keeps the lock?
any ideas to improve this?

**Comment by vasily-kirichenko** [comment]
Yes, there's a `paket.exe` process launched under by credentials and I cannot kill it:

![image](https://cloud.githubusercontent.com/assets/873919/5596459/1ffa19d2-929f-11e4-8af2-d852c515720a.png)

**Comment by isaacabraham** [comment]
We could add the least add a timeout. Just pass it through waitForUnlocked as an argument - if the current time > maxtime then fail.

**Comment by vasily-kirichenko** [comment]
Maybe print something like "paket.lock is locked by paket.exe (PID = 333). Trying to kill it..." every 5 seconds or so, then give up after several attempts and exit?

**Comment by forki** [comment]
@vasily-kirichenko do you suggest to automatically kill the old process? I don't think that's a good idea.

What do you think would be a good timeout?

**Comment by forki** [comment]
like this: https://github.com/fsprojects/Paket/pull/504 ?

**Comment by vasily-kirichenko** [comment]
I think we should kill the locking process since it does not make sense to run two paket.exe on same folder.

**Comment by forki** [comment]
the locked file is used to serialize the requests. This is needed when MsBuild runs parallel builds (for C# projects). 
see https://github.com/fsprojects/Paket/issues/244

**Comment by vasily-kirichenko** [comment]
When I build my solution inside VS:
```
69>  Paket version 0.21.2.0
69>  found: ...\paket.dependencies
69>  packages folder is locked by paket.exe (PID = 10720). Waiting...
69>  Paket failed with:
69>     The process cannot access the file '...\packages\paket.locked' because it is being used by another process.
69>...\.paket\paket.targets(36,5): error MSB3073: The command ""...\.paket\paket.exe" restore --references-files "...\Source\...\paket.references"" exited with code 1.
```

It happens after 45 seconds after solution building was started.

**Comment by forki** [comment]
Will look into it tomorrow.

**Comment by forki** [comment]
I improved stability.
