### ISSUE TITLE
NRE

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#505]
![image](https://cloud.githubusercontent.com/assets/873919/5597033/7b5ad624-92ac-11e4-9ae2-105348f0ec76.png)

**Comment by forki** [comment]
Mhm could still be everywhere.
We could be brutal and open debugger?

**Comment by forki** [comment]
Do you want me to pu Debugger.Break into this line: https://github.com/fsprojects/Paket/blob/master/src/Paket/Program.fs#L213 ?

**Comment by vasily-kirichenko** [comment]
Wait a minute, I'll try to reproduce it under debugger. Seem to appear after paket version updated.

**Comment by vasily-kirichenko** [comment]
Cannot catch it :( Yes, add `Debugger.Break` please.

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/5597161/ab341624-92ae-11e4-87d3-acb9f9289674.png)

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/5597184/fac25368-92ae-11e4-81d4-b8866d7a1752.png)

**Comment by vasily-kirichenko** [comment]
Cannot understand what here is null tho :(

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/5597216/8bb6f59a-92af-11e4-9430-2bc434489a38.png)

**Comment by vasily-kirichenko** [comment]
Maybe it's caused by concurrent access to `pathPenalties` dictionary (if it's concurrent)?

**Comment by vasily-kirichenko** [comment]
It seems that 4 threads are invoking this code:

![image](https://cloud.githubusercontent.com/assets/873919/5597249/ed536d74-92af-11e4-9677-80dc13f95340.png)

**Comment by forki** [comment]
wow didn't know that Dictionary is not thread-safe. 
http://msdn.microsoft.com/en-us/library/dd287191%28v=vs.110%29.aspx seems to be the one I should use, right?

**Comment by vasily-kirichenko** [comment]
:) Absolutely!

**Comment by forki** [comment]
WTF. Why isn't the thread-safe version the default?
Ok I changed it.

**Comment by isaacabraham** [comment]
Most of the collections in the BCL aren't thread safe.

**Comment by vasily-kirichenko** [comment]
All concurrent collection are much slower, for example, here http://stackoverflow.com/questions/15252115/concurrentdictionary-performance-at-a-single-thread-misunderstanding `ConcurrentDictionary` is 3x slower than `Dictionary`.

**Comment by forki** [comment]
Yep I understan that - so I think in special case one could switch to UnsafeButFasterDictionary ;-)

Do you think we can close this? Or do you still see this error

**Comment by vasily-kirichenko** [comment]
I don't see it anymore. If it returns, I reopen this issue.

**Comment by haf** [comment]
Just beware that ConcurrentDictionary has no notion of [strict serialisability](http://www.bailis.org/blog/linearizability-versus-serializability/) as:

 - there's no global time
 - you may perform double work when adding to the cache
 - you cannot be guaranteed to read-your-writes

Also note that ConcurrentDictionary is likely faster for your use-case of a cache, since your reads will outnumber your writes.

**Comment by forki** [comment]
So all is well?

**Comment by haf** [comment]
Yes ;)
