### ISSUE TITLE
Wrong dependency version resolution

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#506]
`paket.dependencies`:
```
source https://www.nuget.org/api/v2

nuget HtmlAgilityPack
nuget Fizzler.Systems.HtmlAgilityPack
```
`paket.references`:
```
HtmlAgilityPack
Fizzler.Systems.HtmlAgilityPack
```
`paket.lock`:
```
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    Fizzler (1.0.0) - >= net20, >= net35
      LinqBridge (>= 1.3.0) - >= net20 < net35
    Fizzler.Systems.HtmlAgilityPack (1.0.0)
      Fizzler (>= 1.0.0) - >= net20, >= net35
      HtmlAgilityPack (>= 1.4.6) - >= net20, >= net35
      LinqBridge (>= 1.3.0) - >= net20 < net35
    HtmlAgilityPack (1.4.9) - >= net20, >= net35
    LinqBridge (1.3.0) - >= net20 < net35
```
Dependencies in dotPeek:

![image](https://cloud.githubusercontent.com/assets/873919/5596998/db5ad552-92ab-11e4-8cdc-9a272efbdce7.png)

An attempt to run the console:

![image](https://cloud.githubusercontent.com/assets/873919/5597074/1e70a370-92ad-11e4-987b-cde431ab9906.png)

**Comment by vasily-kirichenko** [comment]
Repro here https://github.com/vasily-kirichenko/PacketTest

**Comment by forki** [comment]
Just tried your repro. It looks perfectly fine on my machine.

I assume it has to do with the "fixed" unzip of the HtmlAgilityPack package. Maybe the old dll was still there and got referenced.

**Comment by kerams** [comment]
Looks to me like a binding redirect issue. Give `paket install --redirects` a shot.

**Comment by vasily-kirichenko** [comment]
The project did not contain `app.config`. I added it, `paket install --redirects` modified it as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Fizzler" publicKeyToken="4ebff4844e382110" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-0.1.15619.0" newVersion="0.1.15619.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="LinqBridge" publicKeyToken="c2b14eb747628076" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
But the error as before.

**Comment by vasily-kirichenko** [comment]
@forki try to run PaketTest console.

**Comment by vasily-kirichenko** [comment]
If I manually add 
```xml
<dependentAssembly>
        <assemblyIdentity name="HtmlAgilityPack" publicKeyToken="bd319b19eaf3b43a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4.9.0" newVersion="1.4.9.0" />
</dependentAssembly>
```
the error is gone.

**Comment by kerams** [comment]
@vasily-kirichenko  I was about to suggest that :))).
Guess it means that ``--redirects`` fails to detect it.

**Comment by isaacabraham** [comment]
Hmmm. Is HtmlAgilityPack strong named?

**Comment by forki** [comment]
Isaac could you please take a look? It's strange, but I assume https://code.google.com/p/fizzler/source/browse/src/Fizzler.Systems.HtmlAgilityPack/Fizzler.Systems.HtmlAgilityPack.csproj#45 is the cause.

**Comment by isaacabraham** [comment]
sure, will do.

**Comment by isaacabraham** [comment]
@vasily-kirichenko  Just trying your test project - interestingly when I try a ``paket restore`` I get:

``Bad Crc during unzipping lib/sl3-wp/_._ in HtmlAgilityPack 1.4.9: CRC error: the file being extracted appears to be corrupted. Expected 0x00000000, Actual 0x6AF4413C``

**Comment by vasily-kirichenko** [comment]
That's known issue with this package.

**Comment by vasily-kirichenko** [comment]
@forki maybe this causes the problem with missing redirect?

**Comment by isaacabraham** [comment]
The redirect is missed because the assembly doesn't appear to be strong named.

**Comment by forki** [comment]
Isaac, that crc error should be ignored in latest paket.

**Comment by isaacabraham** [comment]
OK, fixed it. It's because only some of the libs in the package are strong named. The current algorithm in ``applyBindingRedirects`` just takes the last assembly with the highest version. I'm rewriting this to take into account that only some assemblies in a package may be strong named.

**Comment by vasily-kirichenko** [comment]
Any chance to publish the fixed version?

**Comment by isaacabraham** [comment]
Submitted a PR - please test it out. I tested it against your test project and HtmlAgilityPack is then added: -

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
	  <runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
		  <dependentAssembly>
			<assemblyIdentity name="Fizzler" publicKeyToken="4ebff4844e382110" culture="neutral" />
			<bindingRedirect oldVersion="0.0.0.0-0.1.15619.0" newVersion="0.1.15619.0" />
		  </dependentAssembly>
		  <dependentAssembly>
			<assemblyIdentity name="LinqBridge" publicKeyToken="c2b14eb747628076" culture="neutral" />
			<bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
		  </dependentAssembly>
		  <dependentAssembly>
			<assemblyIdentity name="HtmlAgilityPack" publicKeyToken="bd319b19eaf3b43a" culture="neutral" />
			<bindingRedirect oldVersion="0.0.0.0-1.4.9.0" newVersion="1.4.9.0" />
		  </dependentAssembly>
		</assemblyBinding>
	  </runtime>
	</configuration>

**Comment by forki** [comment]
Released. Thanks
