### ISSUE TITLE
Authorize GitHub calls

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#509]
Unauthorized API calls has very small call per hour limit:  
>Unauthenticated requests will be limited to 60 per hour ... To enjoy the default rate limit of 5,000 requests per hour, you’ll need to authenticate via Basic Auth or OAuth

It is very annoying when you has GitHub dependencies
![image](https://cloud.githubusercontent.com/assets/1197905/5603647/ca25d5b6-93a0-11e4-8a5a-89d7cfb829bc.png)

As workaround I would like to be able to create `paket.exe.config` and specify my GitHub `username` and `password`. This should allow me work without limits and delays.

@forki Your thoughts about this?

**Comment by forki** [comment]
Related: https://github.com/fsprojects/Paket/issues/510

**Comment by sneal** [comment]
I'd prefer to use a GitHub API key instead of my username and password.

**Comment by JonCanning** [comment]
Just been looking at this, we would like to use a token to retrieve files from private repos. The possibilities seem to be:

Adding the token to the top of the dependencies file:
```source https://github.com/forki/FsUnit token```

Adding it in line:
```github forki/FsUnit FsUnit.fs token```

Or adding it to the paket.config

Any thoughts/guidance?

**Comment by forki** [comment]
I guess the config would be most helpful.

**Comment by baronfel** [comment]
For bonus points, once we have the concept of github tokens we could use the github releases api in the bootstrapper instead of HTML parsing, if the token was present.

**Comment by forki** [comment]
I don't think that's needed. Would just introduce more stuff to the
bootstrapper

**Comment by forki** [comment]
released in 2.9
