### ISSUE TITLE
Make bootstrapper use a apikey for github.com 

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#510]
See https://twitter.com/sforkmann/status/551404242846896128

**Comment by sergey-tihon** [comment]
This issue can be resolved by adding to paket-bootstrap a configurable ability to restore Paket from nuget instead of GitHub.

**Comment by forki** [comment]
that would involve nuget link discover, unzipping and much more.

**Comment by forki** [comment]
http://blog.simplytestable.com/creating-and-using-a-github-oauth-token-with-travis-and-composer/

**Comment by forki** [comment]
Or maybe we just avoid the github api and scrape the link from the html page.
