### ISSUE TITLE
Allow to "internalize" package dependencies

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#515]
Sometime we have conflicts in our dependency graph.
One solution to solve (even if not always applicable) is to install both versions of the package.

NuGet puts the version no. in the path to solve this. But this makes updates a nightmare since the path is not stable.

I propose the following:

We add a new syntax to the `paket.dependencies` file which specifies that a given dependency of a package should be internalized.

```
nuget FSharp.Formatting
    internalize nuget Microsoft.AspNet.Razor
    internalize nuget RazorEngine
```

then we propagate this into the `paket.lock` file.

During restore we would create the following structure:

```
- packages/FSharp.Formatting/... // normal package
- packages/FSharp.Formatting/dependencies/Microsoft.AspNet.Razor/...
- packages/FSharp.Formatting/dependencies/RazorEngine/...
```

This would allow people to deal with conflicts and still have stable paths.

**Comment by panesofglass** [comment]
:+1:

**Comment by DamianReeves** [comment]
:+1: 
I just stumbled on a use case for this recently:
   - I have a solution which has a windows service targeting .NET 4.5 and uses Microsoft.AspNet.WebApi.OwinSelfHost which depends on Microsoft.Owin version >= 3.0.0 (which only has a .NET 4.5 target).
   - I have a webproject which targets .NET 4.0 and references Microsoft.Owin.Host.SystemWeb 2.1.0 which needs Microsoft.Owin version 2.1 (which has both a .NET 4.5 and 4.0 target). 

With paket in its current state I can't proceed and it looks like I need to revert to using vanilla NuGet.

**Comment by forki** [comment]
I tried to implement this but it's too hard. Closing this for now
