### ISSUE TITLE
Paket init auto restore fail if there are spaces in the solution path

### ISSUE THREAD

**Issue by Ouarzy** [fsprojects/Paket#518]
Hi there,
I might have found an issue unless I'm missing an important point.
Indeed, trying to setup a Build using paket on Jenkins, my workspace is in 'c:/program files(x86)/...'

Now, whenever I try to Build the solution, I have an error because it tries to run the following command:
"C:\Program Files (x86)\ztest\.paket\paket.exe" restore --references-files C:\Program Files (x86)\ztest\paket.references

As you can see there are no quotations mark around the second argument, and it interprets each space as a new file path. 
Thus, if you setup any paket restore in a solution containing spaces in its path, it just can't build.

Of course, you can move your solution in a path without spaces, or disable restore, but maybe it could be fix? 
I guess the problem root cause is in paket.targets, which contains the command: <RestoreCommand>$(PaketCommand) restore --references-files $(PaketReferences)</RestoreCommand>"

I tried to do it myself dowloading the paket solution, but I do no really understand where this paket.targets is generated, if it is actually generated.

Any help would be great,

Emi

**Comment by forki** [comment]
See https://github.com/fsprojects/Paket/blob/master/.paket/paket.targets#L22 - you need to fix this manually or better download again from https://github.com/fsprojects/Paket/releases/latest
