### ISSUE TITLE
Paket no longer works on Windows XP / Server 2003 possibly due to Github SSL changes

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#519]
Paket bootstrapper fails to download latest paket on WinXP / Server 2003 with the following error

```
The underlying connection was closed: An unexpected error occurred on a send.
```

I suspect the reason is this: ref: https://github.com/blog/1937-improving-github-s-ssl-setup

As stated in the blogpost, internet exporer on XP / Server 2003 is no longer supported, and afaik webclient in .net is basically a wrapper around some native internet explorer libs.

Not sure what can be done about this thouhg..

**Comment by forki** [comment]
@shiftkey Is this correct?

**Comment by forki** [comment]
which version of the bootstrapper are you using?

**Comment by shiftkey** [comment]
@Vidarls @forki correct, this is a recent change due a known vulnerability with the RC4 cipher suites: https://github.com/blog/1937-improving-github-s-ssl-setup

cc @dbussink

**Comment by forki** [comment]
any ideas how to fix?

**Comment by dbussink** [comment]
I know nothing about how Paket works, but would it be possible to use the git command tools on XP / 2003? Those use OpenSSL and that worked in the tested we did. Anything based on `libgit2` uses the Microsoft SSL stack afaik and won't work.

**Comment by dbussink** [comment]
Also using SSH instead of HTTPS should still work if that's possible.

**Comment by shiftkey** [comment]
@dbussink i'm not aware of any workarounds for avoiding the Microsoft SSL stack - this is just making HTTPS calls to GitHub.com as far as I can tell...

**Comment by forki** [comment]
no we don't use git here. we just want do discover the latest version of github's release page (see https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/Program.cs#L75) and then download that release (see https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/Program.cs#L102)

**Comment by dbussink** [comment]
@forki The only way would be to use some library that doesn't use the Microsoft SSL stack for making HTTPS requests to the API, but I have no idea if those exist or are usable in .NET. A quick search turned up https://github.com/masroore/CurlSharp that might be usable?

Other than an approach like that or dropping support for XP / 2003 I don't think there's a way to solve this.

**Comment by dnauck** [comment]
It's also possible to extract alll required classes for TLS 1.2 from BouncyCastle.NET and use that for the SslStream.
