### ISSUE TITLE
`content none` removes files

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#523]
Hi. I've learned about the `content none` and I hoped it would be a temporary solution for the content files being overwritten by Paket. However when I set the option the existing content files were removed. I think they should stay intact if present. What do you think?

**Comment by ctaggart** [comment]
I don't agree. I think it should continue to remove the files. paket marks the files as being managed by paket. A manual work-a-round would be to remove the marks in the *.*proj file before adding `content none`.

**Comment by isaacabraham** [comment]
I agree with @ctaggart on this one. Any files that are provided by paket are managed _by_ paket.
