### ISSUE TITLE
Why is Simplify static in PublicApi?

### ISSUE THREAD

**Issue by mexx** [fsprojects/Paket#527]
@theimowski Is there a reason why `Simplify` is offered as static method of `Dependencies` and not as instance one like other processes?

**Comment by theimowski** [comment]
I wanted to move away from ``Locate`` member of ``Dependencies`` which throws exception if dependencies file is not found. That was the easiest way to leave rest of the commands as they are now

**Comment by mexx** [comment]
You can use `Create` method, it doesn't throw.

**Comment by mexx** [comment]
But is it not what is intended for `Simplify`, can it function without dependencies file?

**Comment by theimowski** [comment]
nope, that's why it calls ``PaketEnv.fromRootDirectory`` first which returns Failure if dep file not found

**Comment by forki** [comment]
Solved?

**Comment by theimowski** [comment]
whoa I can see some hard issue cleaning going on ;)
nope, it stayed that way - might need revision one day

**Comment by forki** [comment]
/// Converts the current package dependency graph to the simplest dependency graph.
    member this.Simplify(interactive : bool) =
        Utils.RunInLockedAccessMode(
            this.RootPath,
            fun () ->
                PaketEnv.fromRootDirectory this.RootDirectory
                >>= PaketEnv.ensureNotInStrictMode
                >>= Simplifier.simplify interactive
                |> returnOrFail
                |> Simplifier.updateEnvironment
        )
