### ISSUE TITLE
paket install doesn't discover new http dependencies

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#532]
Unlike github/gist and nuget dependencies adding a http dependency to `paket.dependencies` and running `paket install` doesn't add the HTTP remote to `paket.lock`. Only `paket update` works

**Comment by mexx** [comment]
It shouldn't work for github/gist either. `SmartInstall` takes the source files only from the lock file. See [UpdateProcess.fs#L61](https://github.com/fsprojects/Paket/blob/e2a33c6ca635e16018aeda69f929bd49ee9cfd80/src/Paket.Core/UpdateProcess.fs#L61)
We should add newly discovered added source files from the resolution and remove one not more present in it.

**Comment by tpluscode** [comment]
Hm, I could have sworn it actually did work for git

**Comment by tpluscode** [comment]
I confirm that `install` indeed doesn't work for gist. However it half works for GitHub. I added a new dependency and it got downloaded (and its own dependencies) but the lock file wasn't updated.

**Comment by forki** [comment]
looking into this again

**Comment by forki** [comment]
it was already working, but now we detect if something changed and if not we skip resolver phase.
