### ISSUE TITLE
Improve error message "Please try to relax some conditions"

### ISSUE THREAD

**Issue by Thorium** [fsprojects/Paket#534]
Paket version 0.22.6.0
found: C:\git\P2P\Src\paket.dependencies
Resolving packages:
    - exploring EnterpriseLibrary.TransientFaultHandling 6.0.1304.0
    - exploring Newtonsoft.Json 6.0.7
    - exploring EntityFramework 6.0.2
    - exploring Microsoft.AspNet.WebApi 5.2.2
    - exploring Microsoft.AspNet.WebApi.Client 5.2.2
    - exploring Microsoft.AspNet.WebApi.Core 5.2.2
    - exploring Microsoft.AspNet.WebApi.Owin 5.2.2
    - exploring Microsoft.AspNet.WebApi.OwinSelfHost 5.2.2
    - exploring Microsoft.AspNet.WebApi.WebHost 5.2.2
    - exploring NServiceBus 4.2.0
    - exploring NServiceBus.CastleWindsor 4.2.0
    - exploring NServiceBus.Interfaces 4.2.0
    - exploring NServiceBus.Testing 4.2.0
    - exploring Castle.Core 3.2.1
    - exploring Castle.Windsor 3.2.1
    - exploring FSharp.Core 3.1.2.1
    - exploring Microsoft.Owin 3.0.0
    - exploring Microsoft.Owin.Hosting 3.0.0
    - exploring Nuget.CommandLine 2.8.3
    - exploring NUnit 2.6.3
    - exploring Microsoft.Net.Http 2.2.18
    - exploring Rx-Core 2.1.30214.0
    - exploring Rx-Interfaces 2.1.30214.0
    - exploring Rx-Linq 2.1.30214.0
    - exploring Rx-Main 2.1.30214.0
    - exploring Rx-PlatformServices 2.1.30214.0
    - exploring Rx-Silverlight 2.1.30214.0
    - exploring Rx-XAML 2.1.30214.0
    - exploring Microsoft.Owin.Host.HttpListener 2.0.2
    - exploring Microsoft.Owin.Host.SystemWeb 2.0.2
    - exploring Microsoft.Owin.Security 2.0.2
    - exploring DotNetZip 1.9.3
    - exploring SpecFlow 1.9.0
    - exploring log4net 1.2.10
    - exploring Microsoft.Bcl 1.1.6
    - exploring Microsoft.Bcl.Async 1.0.165
    - exploring Microsoft.Bcl.Build 1.0.13
    - exploring Owin 1.0
    - exploring Paket.Core 0.22.6

paket : Paket failed with:
At line:1 char:1
+ paket install --verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Paket failed with::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    
Error in resolution.
  Resolved:
    - EnterpriseLibrary.TransientFaultHandling 6.0.1304.0
    - Newtonsoft.Json 6.0.7
    - EntityFramework 6.0.2
    - Microsoft.AspNet.WebApi 5.2.2
    - Microsoft.AspNet.WebApi.Client 5.2.2
    - Microsoft.AspNet.WebApi.Core 5.2.2
    - Microsoft.AspNet.WebApi.Owin 5.2.2
    - Microsoft.AspNet.WebApi.OwinSelfHost 5.2.2
    - Microsoft.AspNet.WebApi.WebHost 5.2.2
    - NServiceBus 4.2.0
    - NServiceBus.CastleWindsor 4.2.0
    - NServiceBus.Interfaces 4.2.0
    - NServiceBus.Testing 4.2.0
    - Castle.Core 3.2.1
    - Castle.Windsor 3.2.1
    - FSharp.Core 3.1.2.1
    - Microsoft.Owin 3.0.0
    - Microsoft.Owin.Hosting 3.0.0
    - Nuget.CommandLine 2.8.3
    - NUnit 2.6.3
    - Microsoft.Net.Http 2.2.18
    - Rx-Core 2.1.30214.0
    - Rx-Interfaces 2.1.30214.0
    - Rx-Linq 2.1.30214.0
    - Rx-Main 2.1.30214.0
    - Rx-PlatformServices 2.1.30214.0
    - Rx-Silverlight 2.1.30214.0
    - Rx-XAML 2.1.30214.0
    - Microsoft.Owin.Host.HttpListener 2.0.2
    - Microsoft.Owin.Host.SystemWeb 2.0.2
    - Microsoft.Owin.Security 2.0.2
    - DotNetZip 1.9.3
    - SpecFlow 1.9.0
    - log4net 1.2.10
    - Microsoft.Bcl 1.1.6
    - Microsoft.Bcl.Async 1.0.165
    - Microsoft.Bcl.Build 1.0.13
    - Owin 1.0
    - Paket.Core 0.22.6
  Can't resolve:
    - Microsoft.Net.Http >= 2.2.22
       - from Microsoft.AspNet.WebApi.Client 5.2.2
 Please try to relax some conditions.

   StackTrace:
     at Paket.PackageResolver.ResolvedPackages.GetModelOrFail()
     at Paket.LockFile.Create(String lockFileName, InstallOptions installOptions, ResolvedPackages resolvedPackages, FSharpList`1 resolvedSourceFiles)
     at Paket.UpdateProcess.SmartInstall(String dependenciesFileName, FSharpOption`1 exclude, Boolean force, Boolean hard, Boolean withBindingRedirects)
     at <StartupCode$Paket-Core>.$PublicAPI.Install@123.Invoke(Unit unitVar0)
     at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
     at Paket.Program.clo@157-5.Invoke(Unit unitVar)
     at <StartupCode$paket>.$Paket.Program.main@()

Well...ok. What next? lock-file is not generated...

**Comment by forki** [comment]
please show the dependencies file. Thanks

**Comment by forki** [comment]
When I remove the version restrictions from 4 packages:

    nuget Microsoft.Bcl 
    nuget Microsoft.Bcl.Async 
    nuget Microsoft.Bcl.Build 
    nuget Microsoft.Net.Http

the I get the following lock file:

  NUGET
      remote: https://www.nuget.org/api/v2
      specs:
        Castle.Core (3.2.1)
        Castle.Windsor (3.2.1)
          Castle.Core (>= 3.2.0)
        DotNetZip (1.9.3)
        EnterpriseLibrary.TransientFaultHandling (6.0.1304.0)
        EntityFramework (6.0.2)
        FSharp.Core (3.1.2.1)
        log4net (1.2.10)
        Microsoft.AspNet.WebApi (5.2.2)
          Microsoft.AspNet.WebApi.WebHost (>= 5.2.2 <  5.3.0)
        Microsoft.AspNet.WebApi.Client (5.2.2)
          Microsoft.Net.Http (>= 2.2.22)
          Newtonsoft.Json (>= 6.0.4)
        Microsoft.AspNet.WebApi.Core (5.2.2)
          Microsoft.AspNet.WebApi.Client (>= 5.2.2)
        Microsoft.AspNet.WebApi.Owin (5.2.2)
          Microsoft.AspNet.WebApi.Core (>= 5.2.2 <  5.3.0)
          Microsoft.Owin (>= 2.0.2)
          Owin (>= 1.0)
        Microsoft.AspNet.WebApi.OwinSelfHost (5.2.2)
          Microsoft.AspNet.WebApi.Owin (>= 5.2.2 <  5.3.0)
          Microsoft.Owin.Host.HttpListener (>= 2.0.2)
          Microsoft.Owin.Hosting (>= 2.0.2)
        Microsoft.AspNet.WebApi.WebHost (5.2.2)
          Microsoft.AspNet.WebApi.Core (>= 5.2.2 <  5.3.0)
        Microsoft.Bcl (1.1.9)
          Microsoft.Bcl.Build (>= 1.0.14)
        Microsoft.Bcl.Async (1.0.168)
          Microsoft.Bcl (>= 1.1.8)
        Microsoft.Bcl.Build (1.0.21)
        Microsoft.Net.Http (2.2.28)
          Microsoft.Bcl (>= 1.1.9)
          Microsoft.Bcl.Build (>= 1.0.14)
        Microsoft.Owin (3.0.0)
          Owin (>= 1.0)
        Microsoft.Owin.Host.HttpListener (2.0.2)
        Microsoft.Owin.Host.SystemWeb (2.0.2)
          Microsoft.Owin (>= 2.0.2) - >= net40, >= net45
          Microsoft.Web.Infrastructure (>= 1.0.0.0) - >= net40 < net45
          Owin (>= 1.0) - >= net40, >= net45
        Microsoft.Owin.Hosting (3.0.0)
          Microsoft.Owin (>= 3.0.0)
          Owin (>= 1.0)
        Microsoft.Owin.Security (2.0.2)
          Microsoft.Owin (>= 2.0.2)
          Owin (>= 1.0)
        Microsoft.Web.Infrastructure (1.0.0.0) - >= net40 < net45
        Newtonsoft.Json (6.0.7)
        NServiceBus (4.2.0)
          NServiceBus.Interfaces (>= 4.2.0)
        NServiceBus.CastleWindsor (4.2.0)
          Castle.Windsor (>= 3.2.1.0 <  4.0.0.0)
          NServiceBus (>= 4.2.0)
        NServiceBus.Interfaces (4.2.0)
        NServiceBus.Testing (4.2.0)
          NServiceBus (>= 4.2.0)
        NuGet.CommandLine (2.8.3)
        NUnit (2.6.3)
        Owin (1.0)
        Paket.Core (0.22.6)
          DotNetZip (>= 1.9.3)
          FSharp.Core (>= 3.1.2.1)
          Newtonsoft.Json (>= 6.0.7)
        Rx-Core (2.1.30214.0)
          Rx-Interfaces (>= 2.1.30214.0)
        Rx-Interfaces (2.1.30214.0)
        Rx-Linq (2.1.30214.0)
          Rx-Core (>= 2.1.30214.0)
          Rx-Interfaces (>= 2.1.30214.0)
        Rx-Main (2.1.30214.0)
          Rx-Core (>= 2.1.30214.0)
          Rx-Interfaces (>= 2.1.30214.0)
          Rx-Linq (>= 2.1.30214.0)
          Rx-PlatformServices (>= 2.1.30214.0)
        Rx-PlatformServices (2.1.30214.0)
          Rx-Core (>= 2.1.30214.0)
          Rx-Interfaces (>= 2.1.30214.0)
        Rx-Silverlight (2.1.30214.0)
          Rx-Xaml (>= 2.1.30214.0)
        Rx-Xaml (2.1.30214.0)
          Rx-Main (>= 2.1.30214.0)
        SpecFlow (1.9.0)

so it's taking Microsoft.Net.Http 2.2.18 instead.

then I did `paket simplify` and get the following dependencies file:

    source https://www.nuget.org/api/v2
    
    nuget Nuget.CommandLine 2.8.3
    nuget EnterpriseLibrary.TransientFaultHandling 6.0.1304.0
    nuget EntityFramework 6.0.2
    nuget log4net 1.2.10
    nuget Microsoft.AspNet.WebApi 5.2.2
    nuget Microsoft.AspNet.WebApi.OwinSelfHost 5.2.2
    nuget Microsoft.Bcl.Async
    nuget Microsoft.Owin.Host.SystemWeb 2.0.2
    nuget Microsoft.Owin.Security 2.0.2
    nuget NServiceBus.CastleWindsor 4.2.0
    nuget NServiceBus.Testing 4.2.0
    nuget NUnit 2.6.3
    nuget Paket.Core 0.22.6
    nuget Rx-Silverlight 2.1.30214.0
    nuget SpecFlow 1.9.0

Now I would start to relax some more conditions...

**Comment by Thorium** [comment]
Thanks Steffen! 
Could we get somehow more descriptive error message than just "Please try to relax some conditions." to describe what should the user do?

**Comment by forki** [comment]
yes. What would you suggest given the things I have done above?

**Comment by forki** [comment]
we could even make the process interacttive!

**Comment by Thorium** [comment]
From the user point of view:
Apparently some conflict in the dependency tree happened. But how should I continue?
1) The paket.lock-file is the one showing the hierarchy. So in my case, I'm just initially testing Paket for some big enterprise system.
I may want to see the hierarchy even if there is an error (with some command line -parameter). When the lock-file is not generated, the user doesn't see the dependency-tree?
2) "You should update or rollback either these (list) or these (list) packages". (Or split the paket.dependencies-file in two parts but that is not optimal solution.)

Interactive would be nice, but I would initially prefer solution that is just easy to code.

**Comment by forki** [comment]
at least we now give a bit more info. 

Before:

![image](https://cloud.githubusercontent.com/assets/57396/9251632/7f9a0372-41d4-11e5-995c-c71ad9565108.png)

Now:

![image](https://cloud.githubusercontent.com/assets/57396/9251813/38fa063c-41d5-11e5-8d82-a9af84e7af13.png)

**Comment by Thorium** [comment]
![accepted](http://babymetal.net/wp-content/uploads/2014/06/tumblr_n64h67TGug1txf9nko1_500.gif)
