### ISSUE TITLE
Paket restore doesn't download http dependencies

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#536]
As per the title please try doing `paket restore` in repository https://github.com/wikibus/JsonLD.Entities. The one http dependency will not be downloaded. It's defined as follows

```
http http://www.w3.org/2013/N-QuadsTests TESTS.zip
```

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/5685401/28a5cd10-983a-11e4-8a37-8ac50526d03a.png)

**Comment by forki** [comment]
can't reproduce. works as expected

**Comment by tpluscode** [comment]
You're showing me github files. There should be two folders in paket-files

**Comment by forki** [comment]
ah I see

**Comment by forki** [comment]
after changing the link (see #537) and running update we get a change in the lockfile:

![image](https://cloud.githubusercontent.com/assets/57396/5686196/419ef8f8-9841-11e4-94ee-d4ef82b393d6.png)

I can now confirm: restore fails to parse this.

**Comment by tpluscode** [comment]
Thank you for acting so quickly again :+1:

So is full URI the correct syntax for http dependency?

**Comment by forki** [comment]
yep. it would be awesome if you could try to reread the docs and improve it if it is wrong or misleading.

**Comment by tpluscode** [comment]
sure thing. will do first thing tomorrow. maybe after breakfast ;)

**Comment by tpluscode** [comment]
Hm, I wanted to create a pull request for gh-pages but I see that you keep entire HTML documents. Are they generated from somewhere with Jekyll or whatever?

**Comment by theimowski** [comment]
We use [FSharp.Formatting](https://github.com/tpetricek/FSharp.Formatting) to generate the docs. Just edit one of the markdown files: https://github.com/fsprojects/Paket/blob/master/docs/content/http-dependencies.md and run ``build GenerateHelp`` - it should generate the htmls to /docs/output

**Comment by forki** [comment]
There is also
https://github.com/fsprojects/Paket/blob/master/src/Paket/HelpTexts.fs -
this file contains the sources of the command texts
