### ISSUE TITLE
Paket update downloads wrong file for http dependency (and fails for invalid zip)

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#537]
In my [repository](https://github.com/wikibus/JsonLD.Entities) I have a http dependency 

```
http http://www.w3.org/2013/N-QuadsTests TESTS.zip
```

`paket update` does download something but instead of the TESTS.zip it fetches the index of `http://www.w3.org/2013/N-QuadsTests`. 

What's more it fails because the expected zip file is invalid. I think paket should only issue a warning like it now does for invalid nupkgs.

**Comment by forki** [comment]
did you try

    http http://www.w3.org/2013/N-QuadsTests/TESTS.zip

instead?

**Comment by tpluscode** [comment]
Yes and the behaviour is the same

**Comment by tpluscode** [comment]
Oh, I take it back. It worked the second time. I'll investingate some more

**Comment by forki** [comment]
will try to debug...

**Comment by tpluscode** [comment]
Interesting, when I changed the dependency as you suggested update worked fine but when I tried doing restore I got `Paket failed with: invalid remote details.`

**Comment by forki** [comment]
so I close this one and we check restore in #536
