### ISSUE TITLE
Create new command to automatically remove paket.targets from all projects in solution

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#542]
It calls `paket install` for each project in solution and it often fails (exit code = 1) on TeamCity. 
1. Do I understand properly that I can remove `paket.targets` from all projects if `paket install` is always launched by hand or build.cmd?
2. If above statement is true, how I can remove it automatically?

**Comment by forki** [comment]
0. It should only call paket restore. 
1. Yes
2. We need the inverse of http://fsprojects.github.io/Paket/paket-init-auto-restore.html

**Comment by vasily-kirichenko** [comment]
yes, it calls `paket restore`, sorry.

**Comment by vasily-kirichenko** [comment]
I'm right that it's enough to remove 
```xml
<Import Project="..\..\.paket\paket.targets" />
```
from all projects?

**Comment by forki** [comment]
yes.
or you could set your https://github.com/fsprojects/Paket/blob/master/.paket/paket.targets#L5 to false (maybe only in TC)

**Comment by forki** [comment]
if you manage to set the RestorePackages flag to false when inside a TC (FAKE?) build then this would probably be the best solutions. Then Restore from inside VS would still work.

**Comment by vasily-kirichenko** [comment]
I just set it to `false` permanently.

**Comment by theimowski** [comment]
maybe we could make a toggle command like ``paket auto-restore on`` \ ``paket auto-restore off``

**Comment by forki** [comment]
Yes.
