### ISSUE TITLE
Convert a single project in solution

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#543]
Is it possible? The scenario is as following

* convert a solution in a stable branch
* merge it into a feature branch which includes extra projects
* we have a solution that has most projects `paket`-ized and a few ones those are still `nuget`-ized 

What to do?

**Comment by forki** [comment]
No that's not possible, yet. But it makes totally sense.

//cc @theimowski

**Comment by theimowski** [comment]
@vasily-kirichenko check the [``--force`` flag](http://fsprojects.github.io/Paket/paket-convert-from-nuget.html) - you can run convert once again, and it should append remaining nuget configs to existing paket

**Comment by vasily-kirichenko** [comment]
I tried it. The result is that all solution that should not be converted to Paket are converted (again). Those solutions are DB ones. If `convert-from-nuget` could give an optional solution name, it would be great.

**Comment by theimowski** [comment]
one may have a project in many solutions, so maybe an option to exclude projects from ``convert-from-nuget`` would do the job?

**Comment by forki** [comment]
@vasily-kirichenko's solutions have > 150 projects ....

**Comment by theimowski** [comment]
I see. yeah, then we could do ``paket convert-from-nuget --exclude [paths to slns]`` which would omit all projects referenced by these slns

**Comment by vasily-kirichenko** [comment]
Maybe something like `paket convert-from-nuget --update` which would convert all non-paket projects in a paketized solution(s) (and only in such solutions)?

**Comment by theimowski** [comment]
Do I understand correctly that this would be a one-time operation?

IMO, your suggestion seems a bit too specific - how about:
``paket convert-from-nuget --force --exclude [paths to slns]``

How many solutions are ther that you don't want to convert?

**Comment by vasily-kirichenko** [comment]
6 solutions. And they buried deep in file system hierarchy. So I'll have to write a bat file which seems not a right thing to do.

Why do you think --update is too specific?

**Comment by theimowski** [comment]
from my understanding, --update would assume that someone on regular basis mixes nuget configs with paket dependencies for the same projects in codebase.

Seems like a rare use case, however if this is something that could save you from manual work - then it might be the way to go. But then I'd change the naming from ``update`` to sth like ``only-paket-solutions``

@forki any thoughts?

**Comment by vasily-kirichenko** [comment]
Maybe you are right and this feature is not worth implementing.

**Comment by theimowski** [comment]
then closing for now, reopen if such feature turns out to be essential
