### ISSUE TITLE
Create awesome slidedeck for Paket

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#544]
I started to create a FsReveal presentation for Paket and want to gather feedback before I annouce this.

Please help me and send your ideas / corrections (as PR or simply as comment).

Slidedeck can be found at https://github.com/forki/PaketIntro - just run build.cmd and it should start in browser. Or simply look at http://forki.github.io/PaketIntro

Any feedback is welcome. If you like it and have no corrections then just send me a :shipit: ;-)

/cc @agross @isaacabraham @mexx @theimowski @ilkerde @sergey-tihon 

PS: Please don't annouce it, yet. It's still WIP.

**Comment by theimowski** [comment]
looks great! 
a slide or two showing sample use case for the github reference feature could be useful

**Comment by forki** [comment]
Yes will add

**Comment by forki** [comment]
done

**Comment by sergey-tihon** [comment]
* Mention that we have [Paket.VisualStudio](https://github.com/hmemcpy/Paket.VisualStudio) and welcome contribution and usage of both.
* Show practical benefit of referencing files from GitHub... for example we can show some TypeProvider project.
* Say some words about [ProjectScaffold](https://github.com/fsprojects/ProjectScaffold) that it is already featured by Paket.
* Mention some F# & C# that already use Paket
* Say that Paket has Twitter account and we welcome questions on Twitter and on SO

**Comment by forki** [comment]
thanks.
what are projects we should list?

**Comment by forki** [comment]
is there a type provider which is already using this?

**Comment by forki** [comment]
Ok I released the current version. Please retweet https://twitter.com/sforkmann/status/554962982741229568 or feeld free to tweet yourself ;-)

**Comment by sergey-tihon** [comment]
Did not find TP project... we need to do it in FSharp.Data
