### ISSUE TITLE
Improve error message for non-existing nuget feeds

### ISSUE THREAD

**Issue by yreynhout** [fsprojects/Paket#545]
Given a computer that has a nuget package source that refers to a local folder on that computer and that local folder DOES NOT EXIST,
When running ```paket convert-from-nuget```
Then ```paket``` fails with the correct statement that it can not find part of the local folder (aka path).

To be precise, I think it's the implicit (unless ```--no-install``` was specified) ```paket install``` phase that fails, so the issue might be more general than the conversion from nuget.

However, it is non-obvious to an end-user what that path means nor why paket is even looking at that path. So what I'm asking for is a clearer message upon failure or skipping non-existing package sources silently, whichever matches the paket philosophy best.

Additionaly, once the end-user finds out about this, he can remove the culprit nuget package sources from his list of nuget package sources. But alas, that doesn't help, since at that point paket has already copied those sources into its ```paket.dependencies```. Perhaps the integrity of the paket sources should be verified as well.

**Comment by forki** [comment]
1) @theimowski could you try to check if a package feed exists during `convert-from-nuget`?
2) I'll try to improve the error message during `paket install`.

@yreynhout could you please give the corresponding line from the `paket.dependencies` file (or something similar)?

**Comment by yreynhout** [comment]
@forki  An entry that resembles ```source c:\path\does\not\exist``` at the top of that file.

**Comment by theimowski** [comment]
I'll take a look tomorrow

**Comment by forki** [comment]
In latest version we get the following on install:

![image](https://cloud.githubusercontent.com/assets/57396/5727325/82a39f7e-9b62-11e4-8f0b-47c11861ec25.png)

**Comment by theimowski** [comment]
should ``convert-from-nuget`` check local feeds only or remote too?

**Comment by forki** [comment]
probably all.
But the question is what we do if it fails!?

2015-01-14 11:15 GMT+01:00 Tomasz Heimowski <notifications@github.com>:

**Comment by theimowski** [comment]
nice yellow warning?

**Comment by theimowski** [comment]
sometimes nuget v2 feed is also down, so failing because of that seems like an overkill

**Comment by forki** [comment]
Yes a warning is good.
And then the new error message during install will fail and tell the user
what to do.

**Comment by theimowski** [comment]
cool, will do my best to send a PR today
