### ISSUE TITLE
packet restore hash issue

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#546]
Paket store hash of `*.nupkg` in lock file (md5 probably).
NuGet allow owners to edit package metadata online for existing packages without version increase, which change hash sum of `*.nupkg`.
This mean that Paket is potentially unable to restore a lot of NuGet packages, here is an example https://github.com/fsprojects/FSharpx.Collections/issues/21

We need to address this somehow... I think that the only option is to change hash cacl - unzip archive and exclude metadata files.

**Comment by forki** [comment]
we don't store the hash

**Comment by sergey-tihon** [comment]
Sorry, seems that  I misunderstood the cause
