### ISSUE TITLE
We need an idea to internalize source code dependencies

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#549]
If we reference files from other project we often want to internalize the referenced types (make them internal as in the internal keyword). Otherwise we might introduce conflicts if more than one project uses the same files. We also might want to change the namespace of the referenced files.
- This is discussed in https://github.com/aspnet/KRuntime/issues/819#issuecomment-69919665
- It's already a real-world issue in https://github.com/BlueMountainCapital/Deedle/pull/289/files (see src/Deedle/FSharp.Data/CsvFile.fsi)

/cc @tpetricek @adamralph

**Comment by adamralph** [comment]
This would be so awesome.

I think changing the namespace is going to be necessary.

**Comment by forki** [comment]
would a text replacement works?

**Comment by adamralph** [comment]
I think so. One way to do it would be to prepend the namespace in the referenced file with the root namespace of the referencing project, e.g.

```C#
namespace Newtonsoft.Json
...
```

Being imported into `Glimpse` becomes

```C#
namespace Glimpse.Newtonsoft.Json
...
```

**Comment by forki** [comment]
@tpetricek would that work for you?

**Comment by tpetricek** [comment]
I was thinking of sending an issue for this :-).

Well, what I did manually in Deedle could be (with the help of F# Compiler Service) done automatically and it sounds like the best thing to do for Deedle. That is, mark all things in the imported files as `internal`. I did that by adding signature files (which could be automated), but adding `internal` modifiers to the source files might work too (but it's not that easy).

I don't really need to change the namespace. But I suppose that would work too - e.g. replace `FSharp.Data` ~> `Deedle.Internals.FSharp.Data`. Unlike the previous approach, this one can actually be reasonably easy to implement though :-).

**Comment by adamralph** [comment]
Are you proposing *only* changing the namespace? I guess that might be enough, but I think it would be better to also internalise. I don't think either method on it's own is quite enough, but both together should cover 99% of cases.

I've had horrible headaches before when a dep is *only* internalised, e.g. MassTransit used to internalise JSON.NET and I came across situations where I was trying to use an externally referenced JSON.NET and the runtime would complain about type name clashes with the *internal* JSON.NET defined in MassTransit!

If only the namespaces are changed, that's probably enough to avoid typename clashes (apart from edge cases - but that would be an education concern), but it would pollute the public API of the final package with the types from the 'internalised' dep, albeit in an *.Internal.* sub-namespace. The problem then is that you may want to rev your package with a minor version but you require a new major version of a dep to do it. You then have a non-breaking change in the 'public' part of your public API but a breaking change in the 'internal' part of your public API, which is quite messy.
