### ISSUE TITLE
Installing content files on *nix with mono

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#561]
No content files are installed/copied into Projects on *nix systems with mono, at least for me.
I assume this is related to case-sensitive file systems.
The "content" directory (inside packages/.../) is starting with lower-case but here it's looking for a content directory starting with an upper-case: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/InstallProcess.fs#L20

**Comment by forki** [comment]
@theimowski @agross

**Comment by forki** [comment]
could you please test this? sorry for the delay
