### ISSUE TITLE
Cannot create paket.config file on *nix/mono

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#562]
When trying to add credentials on *nix/mono the following error occurs:

```
mono .paket/paket.exe config add-credentials http://myserver.com/myfeed
Paket version 0.24.1.0
Paket failed with:
	No credentials could be found for source http://myserver.com/myfeed
```

**Comment by devboy** [comment]
Turns out `Environment.UserInteractive` is always false on Mono.
Is there an `isMono` method in Paket somewhere like in FAKE?

**Comment by devboy** [comment]
For reference: https://bugzilla.xamarin.com/show_bug.cgi?id=7968

**Comment by devboy** [comment]
Also I found the error message `No credentials could be found ...` very misleading.

**Comment by forki** [comment]
if we'd had an `isMono` - would you find a fix?

**Comment by devboy** [comment]
I wouldn't know of a way in mono to inspect the current shell unfortunately.
Skip the check altogether on mono?
Or provide the credentials as arguments?

**Comment by yannisgu** [comment]
Skip the check completely. This is some rest-code from when the `this function was used during `install` and therfore also used from build servers etc. 
In the `config` command this check just does no sense

**Comment by yannisgu** [comment]
Skip the check completely. This is some rest-code from when the this function was used during `install` and therfore also used from build servers etc. 
In the `config` command this check just does no sense.

**Comment by devboy** [comment]
https://github.com/fsprojects/Paket/pull/565
