### ISSUE TITLE
Configure Output Directory

### ISSUE THREAD

**Issue by blair55** [fsprojects/Paket#563]
Ability to configure the output directory when adding a package in the way that nuget.exe allows:
http://docs.nuget.org/docs/reference/command-line-reference#Install_Command

At present all packages are installed into ".\packages", which is inflexible.

**Comment by forki** [comment]
@agross @mexx @theimowski 
Is this something we want to do? I'm not completle sure since I actually like the opnionated approach we take today.

**Comment by agross** [comment]
Yes, I don't see a reason for the adding complexity to paket. The OP should try to explain why he thinks the flexibility is required in the first place.




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by blair55** [comment]
In fairness, my use-case is not about managing packages & dependencies across projects for one solution.

I needed it because I was trying to use Paket to download individual packages to a specific folder, as part of a script which coordinates the running of multiple executables delivered by the packages (its a micro-service application dev workflow tool). I can do it with nuget.exe but just wanted to try out Paket.

However, whilst experimenting, I tripped up on the >260 chars filepath length. Might be nice if Paket had a backdoor to help out of that?

p.s. whats an OP? :-)

**Comment by agross** [comment]
Can't you just move the packages to the desired location after downloading?

The OP ist the original poster that opened a thread on a message board.




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by blair55** [comment]
Yes, but I may as well use nuget.exe with the switch fwiw.

**Comment by agross** [comment]
If you're fine with explicitly `nuget install`ing packages, what feature of Paket are you looking forward to use?

**Comment by blair55** [comment]
Good question! It was just on my radar... Nice work btw.

Happy for me to close the issue?

**Comment by beatcracker** [comment]
My 2¢

I'd like to use paket in various DevOps/CI/CD workflows, not directly related to managing packages in projects. Being able to pull dependencies from various source with one tool is pretty useful. But issues like this (or #3654) stifle this venue of adoption.

Othjer nice to haves:
