### ISSUE TITLE
Location of paket-files

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#564]
Hi. I'm not sure when that happened but latest paket restores html and github dependencies to different location depending on working dir. My folder structure is how `paket convert-from-nuget` created it.

```
src
|-- .paket
|     +-- paket.exe
+-- paket.dependencies
```

If I run

    /src/> .paket/paket.exe restore

The resulting folder structure is as expected

```
src
|-- .paket
|     +-- paket.exe
|-- paket-files
+-- paket.dependencies
```

However after running

    /src/.paket/> paket.exe restore

Ths structure is different:

```
src
|-- .paket
|     |-- paket-files
|     +-- paket.exe
+-- paket.dependencies
```

**Comment by forki** [comment]
mhm. the second version feels wrong.

**Comment by forki** [comment]
sorry for the delay, but should be fixed now.
