### ISSUE TITLE
Support maven-like provided depnedencies

### ISSUE THREAD

**Issue by damageboy** [fsprojects/Paket#569]
Currently, maven supports the notion of [provided dependencies](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html)

> This is much like compile, but indicates you expect the JDK or a container to provide the dependency > at runtime. For example, when building a web application for the Java Enterprise Edition, you would
> set the dependency on the Servlet API and related Java EE APIs to scope provided because the web > container provides those classes. This scope is only available on the compilation and test classpath, > and is not transitive.

This sort of a dependency obviously makes sense when pulling in dependencies for compilation purposes, while expecting for those same depndencies to be somehow provided magically by the host system running our code.

NuGet obviously does not support this at this time, but provided references are planned for 3.0

Obviouslly, as long as MSBuild doesn't recongnize NuGet/Other package format, or anything other than Reference elements, the only to describe this for MSBuild is through the Private element (Copy Local in the Solution explorer)

It would be great if paket could, by allowing this in the paket.refernces or paket.dependencies file (or both) to specify that a package should be considered to be a provided package, i.e. add the references, but make sure they DON'T get copied to the output folder through the use of Private references in MSBuild

**Comment by forki** [comment]
Could you please suggest a format for paket.references for this? I assume we want to infuence https://msdn.microsoft.com/en-us/library/bb629388.aspx

**Comment by damageboy** [comment]
Sure thing.
You are correct about the MSBuild outcome, when a dependency is provided, it means that the reference should look something like:
```xml
    <Reference Include="Some.Dependency">
      <HintPath>..\packages\SomeLib\lib\net40\Some.Dependency.dll</HintPath>
      <Private>False</Private>
    </Reference>
```

I've always used `<Private>False<Private>` to accomplish this, I never knew there are other values like Never/Always, so I guess we really want to stick to the spec, and specify `Never` here...

As for the `paket.references` / `paket.dependencies` files:
For paket.refernces:
```
Some.Dependency :provided
```
For paket.dependencies this could be:
```
Some.Dependency ~> 6.6.6 :provided
```

Does that make sense?
I like the `provided` name as it is a clear definition of what this reference is, i.e. provided by someone/something else, irregardless of where it's coming from, and it's much better than all the other .NET names like GAC, global, CopyLocal etc.

**Comment by forki** [comment]
I don't really like the "provided" part. Is this the word that NuGet will be using?

**Comment by agross** [comment]
Hm, `copy_local: false`?

**Comment by damageboy** [comment]
@forki , @agross I'll try and find out, I don't think it's settled..

I've seen two "related" discussion in NuGet 3.0.

One talks about deployment-only "references", [from](http://blog.nuget.org/20141023/package-manifests.html): 
```
Deployment-Only Assemblies

If your package needs to carry assemblies that are used only for deployment and don’t need actual Visual Studio/MSBuild references, then you can provide additional configuration within your nuspec to specific which set of assemblies actually do need references.
```

This is actually the reverse to the feature I'm asking for, but perhaps something we'd like to add to paket while we're at it? I guess we could call this `deployment_only`

The other discussion is from [this blog post](http://blog.nuget.org/20141014/in-the-platform.html) where the following piece of text appears:
```
We are still working on the design for this, but we anticipate NuGet packages being able to express artifact groups that can pivot on the following properties:

Architecture
Configuration
Reference vs. Copy-Local
Language
Design-Time vs. Runtime
```

So perhaps the proper way is to leave it as copy-local by default (in which case nothing needs to be specified), and in case we want to disable this we can either go with `reference_only` or as @agross  suggested `copy_local: false`...

**Comment by forki** [comment]
please test 0.26 alpha versions

**Comment by forki** [comment]
we changed the syntax to `copy_local:true`
