### ISSUE TITLE
Does paket support build customization in NuGet packages?

### ISSUE THREAD

**Issue by damageboy** [fsprojects/Paket#570]
Some NuGet packages are laden with MSBuild target/props files, the procesure is [described here...](http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Import_MSBuild_targets_and_props_files_into_project_(Requires_NuGet_2.5_or_above))

Does the Paket installer aware of this?
Is it capable of inserting the references into msbuild project for these custom files when running paket install?

**Comment by forki** [comment]
I'm stuck with this feature. See https://github.com/fsprojects/Paket/issues/516#issuecomment-68857417

**Comment by damageboy** [comment]
I'll try and continue the discussion there
