### ISSUE TITLE
Command line switches can't be positioned right after the action.

### ISSUE THREAD

**Issue by mexx** [fsprojects/Paket#573]
Following command line `paket add -i nuget FSharp.Data` is now illegal.
Also `paket add nuget -i FSharp.Data` isn't working.
Caused by #551.
However `paket add nuget FSharp.Data -i` function properly.

**Comment by theimowski** [comment]
I actually did that deliberately, so that ``nuget FSharp.Data`` comes as first - it seemed reasonable to me that specifying what to add should come first.
``paket add nuget -i FSharp.Data`` was illegal even before #551 - ``nuget`` requires a string arg just after

**Comment by mexx** [comment]
I understand your point, but it's unusual. Most of the command line tools I know allow the user to decide where to place the flag options.
The intermediate placement of `-i` can be left illegal, as before.

**Comment by theimowski** [comment]
Ok then fix is probably just removing the ' First' attribute from UnionArg
