### ISSUE TITLE
Create a install function in the api which takes deps file as text

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#576]
@dsyme created a nice sample which only uses only fsi to install a bunch of packages see https://gist.github.com/dsyme/9b18608b78dccf92ba33

in order to make things even better he proposed the following addition for our API:

    // This will be added to paket.exe in a future version
    module Paket = 
        type Scripting() = 
            static member Install(dependencies, ?force, ?hard) = 
                System.IO.File.WriteAllText("paket.dependencies", dependencies)
                let dependencies = Paket.Dependencies.Locate(__SOURCE_DIRECTORY__)
                dependencies.Install(force=defaultArg force false, hard=defaultArg hard false)

**Comment by dsyme** [comment]
Great! I'll update the gist

**Comment by moodmosaic** [comment]
Awesome! FYI, I also did [here](https://gist.github.com/moodmosaic/98e7884fde511bcf4eaa) and left a [note](https://gist.github.com/dsyme/9b18608b78dccf92ba33#comment-1385148) in the original gist.
