### ISSUE TITLE
Question: How to deal with Fody packages

### ISSUE THREAD

**Issue by DanielFabian** [fsprojects/Paket#582]
This it not a bug report, but really just a matter of understanding:

Some of our nugets are https://github.com/Fody/Fody packages. In the FAQ, I understood, that install.ps1 are not executed. So what mechanism can we somehow use instead to do things like installing Fody packages. Those usually need to create/adjust the fodyweavers.xml like in https://github.com/Fody/Virtuosity/blob/master/Fody/NugetAssets/install.ps1

Is there some way how we can use packages like the different Fody packages using paket? Or, alternatively, is there some way, we can write our own Fody packages such that they'll be compatible with paket?

**Comment by agross** [comment]
The short answer is that you need to make the modifications yourself as Paket doesn't execute `install.ps1`. The only automation we currently support (AFAIK, in the latest alpha) is MSBuild targets.

NuGet will drop support for PowerShell in the upcoming version and I'm not sure what they will offer instead to make things like modifying `fodyweavers.xml` possible.

**Comment by DanielFabian** [comment]
ok, cool thanks for the info and head-up. We'll take that into considerations for our packages ;-)
