### ISSUE TITLE
Stop touching my paket.dependencies during install

### ISSUE THREAD

**Issue by yreynhout** [fsprojects/Paket#584]
```paket install``` seems to overwrite ```paket.dependencies```, uncommenting any line I've started with ```//```. Very discomforting. Why does this happen? Why even touch that file during an install (I can understand the need during simplify and probably other commands I haven't looked into).

I got the // from digging in the code (who knew I could read F#): https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/DependenciesFile.fs#L171

I haven't ventured into looking why paket is doing this (way past my bed time), so pardon my ignorance.

**Comment by forki** [comment]
Install scans all references files for new packages and will add these to the dependencies file if needed. So there is a usecase where we save the dependencies file.  

Usually the dependencies file will only be saved when it has a modification. 

Something went wrong with the comment parsing of the dependencies file in the latest version. 

All this together seems to result in the bug you noticed.

**Comment by forki** [comment]
please test with 0.27.1 and report if you still have such issues. Thanks
