### ISSUE TITLE
Install process duplicates Imports of targets files

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#585]
This happens only if the targets file is directly imported with `__paket__` properties like:

    <Import Project="..\..\..\GitInfoPlanter\build\GitInfoPlanter.targets" Condition="Exists('..\..\..\GitInfoPlanter\build\GitInfoPlanter.targets')"  />

The reason is that we don't have this tagged with any paket specific markers and can't delete it.
So we need to tag it. Ideas?

/cc @damageboy

**Comment by forki** [comment]
I added a Paket attribute like:

    <Import Project="..\..\packages\GitInfoPlanter\build\GitInfoPlanter.targets" Condition="Exists('..\..\packages\GitInfoPlanter\build\GitInfoPlanter.targets')" Paket="true" />

This seems to be ignored by Visual Studio and works as a flag.

**Comment by damageboy** [comment]
@forki Verified!

**Comment by damageboy** [comment]
@forki New Bug... You seem to have added a `Paket=True` attribute for the `<Import>`s that you add.
Unfortunately, VS doesn't seem to like loading those...
It does seem though, that it's legal to specify a `Label` attribute,
So, instead of:
```xml
<Import Project="..\..\..\GitInfoPlanter\build\GitInfoPlanter.targets" Condition="Exists('..\..\..\GitInfoPlanter\build\GitInfoPlanter.targets')"  Paket="True" />
```

You could do:
```xml
<Import Project="..\..\..\GitInfoPlanter\build\GitInfoPlanter.targets" Condition="Exists('..\..\..\GitInfoPlanter\build\GitInfoPlanter.targets')"  Label="Paket" />
```

**Comment by forki** [comment]
Argh. Will check later today.

If you are interested: it's probably an easy fix in only two locations. ;-)

**Comment by damageboy** [comment]
@forki Good idea, it's time I got off my fat ass, wait for my PR, I'll feel more productive that way
