### ISSUE TITLE
Streamline package options

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#587]
Paket supports several options, configured at different levels:

* `content: none` (global)
* `framework` (for `nuget` in paket.dependencies)
* `copy_local` (paket.references)

I think we should streamline these to let the user define any option on any level (global, package level, reference level) with the possibility to enhance the option set or override default options on lower levels (comparable to Git's three-level configuration system).

The syntax should be streamlined to [the one discussed here](https://github.com/fsprojects/Paket/issues/574#issuecomment-72314403).

`paket.dependencies`:
```
copy_local: true
framework: >= net40
content: none

nuget Foobar 1.2.3 copy_local: true, framework: >= net40, content: none
```

`paket.references`:
```
Foobar copy_local: true, framework: >= net40, content: none
```

# Current status
`paket.dependencies` global support:
- [x] `content`
- [x] `framework`
- [x] `copy_local`
- [x] `import_targets`

`paket.dependencies` per-package support:
- [x] `content`
- [x] `framework`
- [x] `copy_local`
- [x] `import_targets`

`paket.references` support (only per-package):
- [x] `content`
- [x] `framework`
- [x] `copy_local`
- [x] `import_targets`

**Comment by forki** [comment]
The same applies to `import_targets:false` which already works in `paket.references` files.

**Comment by agross** [comment]
Please check off above ;-)

**Comment by forki** [comment]
![free](https://cloud.githubusercontent.com/assets/57396/6250646/ab970ee0-b78f-11e4-9748-634d5add56d0.gif)

**Comment by agross** [comment]
Perhaps we should add `redirects: on` as well?
