### ISSUE TITLE
Allow project references from elsewhere, convert them to binary refs and back

### ISSUE THREAD

**Issue by kurtschelfthout** [fsprojects/Paket#590]
Crazy idea. 

I think it might be useful to build support into paket to allow you to "reference" a project file from elsewhere; in another Git repo (GitHub for example). What this would do is pull down the source if necessary (recording the SHA1?), add the project and all its dependencies (other project files in the same repo, nuget packages, etc) to the solution and add a project reference to any referencing project.

A useful option would be to allow to "convert" the reference to a binary reference, i.e. get the source, build the project, and add the resulting binary as a "special" package. Possibly allowing you to convert it back to a project reference afterwards.

This might be useful for those that want to be on the bleeding bleeding edge; for debugging and testing the change to that 3rd party library; and for large codebases with many projects where working with one big solution with all the projects in there is not workable anymore (and, because solution files in vs are not composable, adding a dependency to some project require updating a number of solution files).

Just throwing it out there, not clear if any of this is within paket's scope.

**Comment by agross** [comment]
Is it just me or do you propose something like a Git submodule. If so, what's the difference between your suggestion and having that submodule?

As far as I can see a git submodule also has the URL to another project, a configurable local path and records the SHA.

Of course git doesn't care about msbuild et al, but it still sounds very similar.

**Comment by kurtschelfthout** [comment]
it's really orthogonal to Git, that was just an example (maybe a bad one). It's more comparable to having a reference to a file from some place (e.g. gist or http, as paket supports now, local filesystem would even be useful), but extending that to a project and its dependencies, with the ability to reference that project either by pulling it into the host solution as a binary or as a project. Or maybe even as the nuget package. 

E.g. you could have in paket.dependencies
nuget Foo
or
project path/to/Foo
or
buildproject path/to/Foo

The first would look through the nuget source definitions and find the package; the second would find the proj file at path and add it to the solution with all dependencies; the third would find the proj file at path, build it, and add the binary reference + all dependencies.

Once you have that, then you can really work with any kind of source; i.e. to do it for a GitHub project, yes you'd pbb use a submodule to pull in the source, then change the paket.dependencies to change dependency from nuget to source...

**Comment by obadz** [comment]
+1

**Comment by smoothdeveloper** [comment]
A first step would be to support handling of project dependencies, I opened a ticket: #1497

**Comment by forki** [comment]
Closing old issue. Part of it is possible with git dependencies.
