### ISSUE TITLE
Getting Object "reference not set to an instance of an object" on update/install

### ISSUE THREAD

**Issue by madhon** [fsprojects/Paket#591]
When Running either an Update or Install with v0.27.5.0 I am getting the following exception 

Paket version 0.27.5.0
found: C:\dev\ModelClassCreator\paket.dependencies
Resolving packages:
  - fetching versions for Dapper
    - exploring Dapper 1.38
  - fetching versions for JetBrains.Annotations
    - exploring JetBrains.Annotations 8.0.5.0
  - fetching versions for reactiveui-winforms
    - exploring reactiveui-winforms 6.4.0
    - exploring reactiveui-core 6.4.0
  - fetching versions for Rx-Main
    - exploring Rx-Main 2.2.5
  - fetching versions for Rx-Core
    - exploring Rx-Core 2.2.5
  - fetching versions for Rx-Interfaces
    - exploring Rx-Interfaces 2.2.5
  - fetching versions for Rx-Linq
    - exploring Rx-Linq 2.2.5
  - fetching versions for Rx-PlatformServices
    - exploring Rx-PlatformServices 2.3
    - exploring Rx-PlatformServices 2.2.5
  - fetching versions for Rx-WinRT
    - exploring Rx-WinRT 2.2.5
  - fetching versions for Rx-Xaml
    - exploring Rx-Xaml 2.2.5
  - fetching versions for Splat
    - exploring Splat 1.6.1
Locked version resolutions written to C:\dev\ModelClassCreator\paket.lock

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at <StartupCode$Paket-Core>.$ProjectFile.PaketNodes@340-1.GenerateNext(IEnume
rable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImp
l()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$Paket-Core>.$ProjectFile.PaketNodes@340-1.GenerateNext(IEnume
rable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImp
l()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$Paket-Core>.$ProjectFile.PaketNodes@340-1.GenerateNext(IEnume
rable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImp
l()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.ProjectFile.RemovePaketNodes()
   at Paket.ProjectFile.UpdateReferences(FSharpMap`2 completeModel, FSharpMap`2
usedPackages, Boolean hard)
   at Paket.InstallProcess.InstallIntoProjects(FSharpList`1 sources, Boolean for
ce, Boolean hard, Boolean withBindingRedirects, LockFile lockFile, IEnumerable`1
 projects)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@128.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 actio
n)
   at Paket.Program.clo@74-7.Invoke(Unit unitVar)
   at <StartupCode$paket>.$Paket.Program.main@()

paket.dependencies contains
source https://www.nuget.org/api/v2

nuget Dapper
nuget reactiveui-winforms
nuget JetBrains.Annotations 

paket.lock contains
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    Dapper (1.38)
    JetBrains.Annotations (8.0.5.0)
    reactiveui-core (6.4.0)
      Rx-Main (>= 2.2.5)
      Rx-WinRT (>= 2.2.5)
      Rx-Xaml (>= 2.2.5)
      Splat (>= 1.6.0)
    reactiveui-winforms (6.4.0)
      reactiveui-core (6.4.0)
    Rx-Core (2.2.5)
      Rx-Interfaces (>= 2.2.5)
    Rx-Interfaces (2.2.5)
    Rx-Linq (2.2.5)
      Rx-Core (>= 2.2.5)
      Rx-Interfaces (>= 2.2.5)
    Rx-Main (2.2.5)
      Rx-Core (>= 2.2.5)
      Rx-Interfaces (>= 2.2.5)
      Rx-Linq (>= 2.2.5)
      Rx-PlatformServices (>= 2.2.5)
    Rx-PlatformServices (2.2.5)
      Rx-Core (>= 2.2.5)
      Rx-Interfaces (>= 2.2.5)
    Rx-WinRT (2.2.5)
      Rx-Main (>= 2.2.5)
    Rx-Xaml (2.2.5)
      Rx-Main (>= 2.2.5)
    Splat (1.6.1)

**Comment by forki** [comment]
ouch. could you please retry?

**Comment by madhon** [comment]
Hi,

That's fixed it, thanks for quick response.
