### ISSUE TITLE
paket add should sort packages by name

### ISSUE THREAD

**Issue by dnauck** [fsprojects/Paket#596]
Like issue #187 paket add should sort dependencies while adding (maybe with an additional flag/option)

**Comment by cdrnet** [comment]
Since this file is often maintained by hand I don't think that should be default behavior (at least not reordering existing entries).

**Comment by forki** [comment]
I think we could try to preserve alphabetical order. Paket add could try to assume alphabetical order and add whereever it fits best. we should probably not reorder the whole file.

**Comment by agross** [comment]
> we should probably not reorder the whole file.

Definitely!

**Comment by dnauck** [comment]
+1 for @forki 's suggestion
