### ISSUE TITLE
paket reformat my app/web.config files while changing assembly redirects

### ISSUE THREAD

**Issue by dnauck** [fsprojects/Paket#597]
When using the [Redirects option](http://fsprojects.github.io/Paket/dependencies-file.html#Redirects-option) paket reformats my app.config and web.config files on every operation (restore, install, add, ...)

Especially removing blank lines i added for easier reading.

**Comment by isaacabraham** [comment]
Mmmm. This is because we essentially overwrite the file with a new one - this isn't unsurprising as we use XDocument rather than raw string manipulation

**Comment by dnauck** [comment]
Maybe this helps: [PreserveWhitespace option](http://blogs.msdn.com/b/charlie/archive/2008/09/29/linq-farm-preserving-formats-with-linq-to-xml.aspx)

**Comment by forki** [comment]
could you please check if the change helps?
