### ISSUE TITLE
Weird CRC error on HtmlAgilityPack 1.4.9

### ISSUE THREAD

**Issue by damageboy** [fsprojects/Paket#598]
When I run paket to restore [HtmlAgilityPack 1.4.9](https://www.nuget.org/packages/HtmlAgilityPack), I get this error:

```
Bad Crc during unzipping lib/sl3-wp/_._ in HtmlAgilityPack 1.4.9: CRC error: the file being extracted appears to be corrupted. Expected 0x00000000, Actual 0x6AF4413C
```

No other ZIP tool complains about the file...

**Comment by cdrnet** [comment]
See also #484

**Comment by forki** [comment]
it should be a warning. Not an error.
And it's an issue with nuget.org.
