### ISSUE TITLE
paket.version file not generated (0.27.11)

### ISSUE THREAD

**Issue by cdrnet** [fsprojects/Paket#600]
The first run of build.sh of ProjectScaffold fails with

    Paket failed with:
        Could not find file 'c:\ [...] \fsharp\FAKE\modules\Octokit\paket.version'.

Indeed, the file is not there. This seems to be a recent regression as it works fine in 0.27.10 but fails with 0.27.11.

**Comment by forki** [comment]
Ok. Will look at this. /cc @sergey-tihon

**Comment by cdrnet** [comment]
Looks like [here](https://github.com/sergey-tihon/Paket/commit/1b76f1ee5705cdcd789c1dbae8f7c3522e31b2a0#diff-f49621e896c9b89745f9d4aa9e06cb6fL168) we should check whether the file exists, if not write it as before.

**Comment by forki** [comment]
Could you please send a pull request?

**Comment by cdrnet** [comment]
Yes, will do.

**Comment by cdrnet** [comment]
Hm, that does not seem to have been enough, will check

**Comment by sergey-tihon** [comment]
Ouch, sorry guys
Thank you @cdrnet

**Comment by cdrnet** [comment]
Argh, I missed the operator precedence ... will submit a new PR, sorry for the extra work
