### ISSUE TITLE
Missing assembly redirect for transitive dependencies?

### ISSUE THREAD

**Issue by DanielFabian** [fsprojects/Paket#602]
I was trying to use `Alea.CUDA.Direct3D9`, which references `SharpDX (>= 2.5.0)`.

As of today, when I add a reference to `Alea.CUDA.Direct3D9`, without `SharpDX`, it'll install `SharpDX 2.6.0`, but it does not set a binding redirect. 

I think, that - in principle - `Alea.CUDA.Direct3D9` could work with `SharpDX 2.6.0`, but a binding redirect would be necessary.

For now, I see two work-arounds:
- Explicitly add `SharpDX 2.5.0` as a reference and thus force version `2.5.0` to be locked. I did that and it works.
- Make `Alea.CUDA.Direct3D9` depend on `SharpDX (= 2.5.0)`.

Do you know some good way?

**Comment by forki** [comment]
So we have a bug in the transitive assembly binding redirect code? 

/cc @isaac_abraham

**Comment by DanielFabian** [comment]
either that, or I misunderstood what should happen in this particular case,
i.e. transitive dep that is being used higher than the original one
mentioned in the nuget ref.

**Comment by forki** [comment]
@isaacabraham how does the filtering work here?

**Comment by isaacabraham** [comment]
As I recall, we pick the first strongly-named assembly in the list of available versions of that assembly in the package, and use that one.

**Comment by forki** [comment]
yes. but it's not filtered by package. at least I cant find the location of this.

**Comment by isaacabraham** [comment]
We do it for every package AFAIK.

**Comment by isaacabraham** [comment]
I don't recall any funky logic to check for transitive relationship for the binding redirects.

**Comment by forki** [comment]
if we do it for all packages then at least it should not be filtered out!?

**Comment by isaacabraham** [comment]
The evidence seems to suggest that we only do it for top-level dependencies rather than the entire graph of them...

**Comment by isaacabraham** [comment]
Just looking at the code, all packages are supplied to the binding redirects code that are returned from ``createModel()`` which in turn is derived from ``lockFile.ResolvedPackages`` - are these all packages or just top-level packages?
