### ISSUE TITLE
bcl.targets is not compatible with Paket

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#604]
If you reference any of the BCL nuget packages, they add a target (Microsoft.Bcl.Build.targets) to the project file. This in turn tries to validate package references by looking for, you guessed it - packages.config.

Not sure what the solution to this is but it leads to a build error and associated warnings.

**Comment by forki** [comment]
what about backlisting these?

**Comment by mavnn** [comment]
I have never had anything but pain from bcl.targets, and I've never seen a failure caused by removing them.

Even with Nuget they tend to break if you configure a non-standard package directory.

**Comment by forki** [comment]
would love to see a pull request which blacklists these targets files.

**Comment by isaacabraham** [comment]
@mavnn - they confuse the hell out of me too.
@forki - I assume that we're seeing them now that targets support is in paket. Yes a blacklist a good idea. Maybe the only idea aside from manually rewriting the targets file to not look for packages.config. But I don't think that we want to go down that route!

A bit concerned about where this path will lead us down though.

**Comment by forki** [comment]
I made this up-for-grabs, so if anyone wants to take it....

Blacklist is found here: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/InstallModel.fs#L228 

Sample for a test case: https://github.com/fsprojects/Paket/blob/master/tests/Paket.Tests/InstallModel/Xml/LibGit2Sharp.fs

**Comment by dedale** [comment]
I cannot reproduce the build failures under VS. The Bcl targets tells me that adding the following property in the project would skip nuget validation:

    <SkipValidatePackageReferences>true</SkipValidatePackageReferences>

**Comment by damageboy** [comment]
@forki I'll take a stab at it.
I assume some sort of and embedded resource like a `blacklist.txt` file that is part of paket is acceptable?

**Comment by ctaggart** [comment]
Can I get an option to turn off this feature? Like NuGet content support, this is a feature that I would like to turn off. I was very excited about it when came out in NuGet 2.5, but it doesn't work very well. The `Microsoft.Bcl.Build.targets are preventing me from upgrading paket.

**Comment by ctaggart** [comment]
How about a feature to opt-out of automatic import of targets with syntax from #574.
```
nuget Foobar 1.2.3 framework: net20 net35, autoimport: false
```

**Comment by damageboy** [comment]
I leave it to @forki to decide.

I know the ms BCL is a special kind of crap in this respect. I haven't seen anything else that bothers me that much... I don't think it's a bad idea to disable autoimport though, could be useful for more scenarios, but unlike what @ctaggart suggested, I think it should be a paket.references things, just like copy_local is

**Comment by isaacabraham** [comment]
Note that you will need targets for things like XUnit test runner in future (that's what got this whole .targets malarky started). But I agree - this BCL stuff is just a world of pain.

**Comment by isaacabraham** [comment]
@damageboy I wouldn't bother with an embedded text file personally - just make an F# list of strings for the blacklist (perhaps as it's own .fs file). F# is lightweight enough to not have fluff get in the way, and we're not going to do "drop in" replacements of the file.

**Comment by forki** [comment]
Please start by extending the blacklist. I need to think about a good way
to disable the target feature, but I agree we need a switch for that.

But I think it's safe to say that everyone wants to disable the bcl stuff
so blacklisting is still a good idea.

**Comment by ascjones** [comment]
This is currently preventing us from upgrading to the latest paket (which installs those pesky BCL targets). The `SkipValidatePackageReferences` does work but it's a pain to add to lots of projects.

I've managed to fix it for us locally with a hardcoded blacklist: https://github.com/betgenius/Paket/commit/352cc8e70fa867a7e39a14dc84f7213df21fd080

If that looks good and @damageboy hasn't already done a better fix, then I can submit as a PR.

**Comment by ascjones** [comment]
Deleted previous comment - I hadn't refreshed the page from earlier to see that this issue is closed!

I'd done a quick fix with a blacklist but obviously not needed now.

**Comment by forki** [comment]
The issue is not closed. We still need a fix, but we have a workaround. You can disable the targets - see #615

**Comment by ascjones** [comment]
Doh my mistake! Saw the Closed icon for the linked issue

In that case here is a quick fix for that with a blacklist I did to get it working for us locally:

https://github.com/betgenius/Paket/commit/352cc8e70fa867a7e39a14dc84f7213df21fd080

If that's any good and assuming @damageboy hasn't got something better in store then I can submit it as a PR.

**Comment by forki** [comment]
I also added http://fsprojects.github.io/Paket/dependencies-file.html#import_targets-settings

**Comment by ascjones** [comment]
Actually that might do the trick for us, more practical than adding to all the individual references files. Especially when dealing with the Bcl.Build which is a transitive dependency.



—

**Comment by forki** [comment]
I still think it's a very good idea to blacklist since the package is
broken for everyone who is using paket.

**Comment by forki** [comment]
Also keep an eye on https://github.com/fsprojects/Paket/issues/587

**Comment by ascjones** [comment]
Cool just created a PR, might want to check I've done it right.

**Comment by forki** [comment]
so it's blacklisted and a streamlined ìmport_targets` switch (see https://github.com/fsprojects/Paket/issues/587)
