### ISSUE TITLE
References added by Paket don't show in Xamarin Studio

### ISSUE THREAD

**Issue by rojepp** [fsprojects/Paket#605]
Xamarin Studio has trouble reading the `<Choose>` tags that Paket adds. 
I'm not sure if the issue needs to be fixed in XS, or if Paket could do something differently to avoid this problem. Note that the references are added, and projects compile fine. Its just that they don't show up under the References node in Solution explorer.

I tested on OSX but it probably behaves the same on Windows.

**Comment by 7sharp9** [comment]
Ive seen `Choice` rendered `n` times in the assembly browser, or maybe that was with conditions, I forget.

**Comment by damageboy** [comment]
@7sharp9 @rojepp It's not the first, not last XS / MSBuild integration isssue.
XS doesn't run do full MSBuild parsing, it will not read common properties coming from an imported .targets file, amongst other issues.

Xamarin need to address this as more and more functionality is being plugged through these mechanisms. XBuild works with these constructs perfectly, but XS is quite lagging behind.

**Comment by 7sharp9** [comment]
Maybe as MSBuilt is oss'ed this can be plugged by someone.

**Comment by damageboy** [comment]
@7sharp9 MSBuild / XBuild is fine, it builds .csproj/.fsproj project, even complex ones pretty easily.
I've looked at it a few years ago, and converting XS to full MSBuild integration, the way VS can handle is a major undertaking.

**Comment by forki** [comment]
Can you please file it as an XS issue so that we can close it here?

**Comment by rojepp** [comment]
Bug added: https://bugzilla.xamarin.com/show_bug.cgi?id=27124

**Comment by 7sharp9** [comment]
The project system came from SharpDevelop I think, as such its pretty old and doesn't support these features.
