### ISSUE TITLE
Use framework constraint for paket.dependencies in convert-from-nuget

### ISSUE THREAD

**Issue by mausch** [fsprojects/Paket#609]
Now that https://github.com/fsprojects/Paket/issues/574 works (thanks!) it would be great if Paket could insert framework constraints in paket.dependencies where appropriate when calling `convert-from-nuget`. 

Otherwise, a new user would still get the same error after `convert-from-nuget` until they figure out that they need to insert those constraints.

**Comment by forki** [comment]
@theimowski what do you think?

**Comment by theimowski** [comment]
can we read that from the packages.config? If so then that shouldn't be a big deal
