### ISSUE TITLE
Possible to convert pdb-files to mdb-files if on mono?

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#611]
Mono uses mdb files - when installing packages that have been built on Windows, we often get pdb files with them.

Would it be a nice feature/plugin to Paket to automatically create mdb files from existing pdb files, if running on mono?

All it would have to do is call 'pdb2mdb' on the dll file if there's a pdb file present and we're running on mono.

See http://www.mono-project.com/docs/faq/technical/#can-i-convert-microsoft-pdb-files-to-mono-mdb-files for reference.

**Comment by forki** [comment]
Closing old issue.
