### ISSUE TITLE
Allow to opt-out of targets import

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#615]
@ctaggart suggested we add a way to opt-out of targets import like in #574 

in https://github.com/fsprojects/Paket/issues/604#issuecomment-74549774 he proposed the syntax for `paket.dependencies:

    nuget Foobar 1.2.3 framework: net20 net35, autoimport: false

I don't really like the name `autoimport`. How about `import_targets: false`

/cc @agross

**Comment by agross** [comment]
`import_targets` is better. `autoimport` sounds like some magicical thing will (not) happen. I don't like magic in code.

**Comment by ctaggart** [comment]
That is fine. Just note that it is .props too, just not .targets. The original feature called: Automatic import of msbuild targets and props files. http://docs.nuget.org/Release-Notes/NuGet-2.5

**Comment by forki** [comment]
I started by adding this switch to the `paket.references` file.

**Comment by forki** [comment]
bringing this into `paket.dependencies` is now part of https://github.com/fsprojects/Paket/issues/587
