### ISSUE TITLE
NuGet sources with spaces?

### ISSUE THREAD

**Issue by amazingant** [fsprojects/Paket#616]
NuGet allows (and I currently use) package locations that include spaces. Both within the `nuget.config` file and on the command line, this is as simple as quoting the path (this is already done in the config file because the source path is an attribute on an XML node).

Working with a package source I set up for my team's internal libraries and trying to use @dsyme's F# script from [here][1] (and subsequently @moodmosaic's fork of it), I get back the error `Couldn't get package details for package X on ["C:\Path"].` when specifying `source C:\Path With Spaces\`.

Given a directory named `Test Folder` in my c-drive, I've tried the following formats:

```
Paket.Dependencies.Install """
    source "C:\Test Folder"
    nuget fscheck 0.9.4
"""
```
```
Paket.Dependencies.Install "
    source \"C:\Test Folder\"
    nuget fscheck 0.9.4
"
```
and
```
Paket.Dependencies.Install "
    source C:\Test\ Folder
    nuget fscheck 0.9.4
"
```

I have tried creating a symlink to the directory, such that the symlink can be accessed without spaces in the path; this works with no problems.

[1]: https://gist.github.com/dsyme/9b18608b78dccf92ba33

**Comment by forki** [comment]
this should be fixed now. please test and tell me if it works for you

**Comment by amazingant** [comment]
Tested with paket 28.14, is now magically delicious. Thanks, @forki :+1: :smile:
