### ISSUE TITLE
Create a push command

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#620]
We now have the pack command available in the latest alpha version (see #613).
We should implement a `push` command in order to get completely rid of NuGet.CommandLine.

**Comment by mavnn** [comment]
I have most of this already, by the way.

Should it be an option on "pack" or it's own command?

**Comment by forki** [comment]
I think it should be a separate command

**Comment by mavnn** [comment]
I'm tempted to make the default way of supplying the API key via environment variable. Thoughts?

**Comment by forki** [comment]
please make it optional parameters which get filled by environment if we don't specify directly.

**Comment by mavnn** [comment]
:+1:

**Comment by mavnn** [comment]
Code works now - just need to hook up the command.
