### ISSUE TITLE
Template file parser is fragile and very inefficient

### ISSUE THREAD

**Issue by mavnn** [fsprojects/Paket#625]
But has unit tests. If someone wants to put the time into making it more efficient, feel free - I'm not going to get there for a while.

**Comment by forki** [comment]
Could please give a little more details about what you think we should improve.

**Comment by mavnn** [comment]
In [TemplateFile.fs](https://github.com/fsprojects/Paket/blob/b4cf22385761628f4b1f230dcab2f06cf2ae10be/src/Paket.Core/TemplateFile.fs#L49) it currently rescans the whole file line by line with a RegEx each time it gets the value of a new property from the template file being parsed.

Tokenizing the whole file into a dictionary in a single pass would knock a few hundred milliseconds off parsing each file.

Tests for all of the basic functionality can be found here: https://github.com/fsprojects/Paket/blob/b4cf22385761628f4b1f230dcab2f06cf2ae10be/tests/Paket.Tests/TemplateFileParsing.fs

**Comment by mavnn** [comment]
The current parser is not only inefficient but also excessively fragile (see #659 ). I'll have a look at a rewrite over the next few days.
