### ISSUE TITLE
Auto restore still set up even when --no-auto-restore specified in nuget conversion

### ISSUE THREAD

**Issue by mavnn** [fsprojects/Paket#631]
I ran this:

    .paket\paket.exe convert-from-nuget --no-auto-restore --creds-migration plaintext --force

but I still seem to have paket.targets installed and it attempts auto restore. Is there a known bug in no-auto-restore?

**Comment by theimowski** [comment]
I'll try to reproduce

**Comment by theimowski** [comment]
I've sent a fix 
Thanks @mavnn for spotting

**Comment by mavnn** [comment]
Thanks!
