### ISSUE TITLE
Paket creates nupkg files without version in filename

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#633]
We create Paket.Core.nupkg and nuget.exe would create paket.Core.0.29.2.nupkg 

Not sure if this is an issue. /cc @mavnn

**Comment by mavnn** [comment]
That's a good question. Nuget.org correctly processes them as is, but it wouldn't be hard to add the version in.

**Comment by forki** [comment]
I think this is really important since Paket itself will use the nuspec file name (from inside a downloaded package) in order to check if the package is up-to-date ;-)
