### ISSUE TITLE
Pack command variable thoughts

### ISSUE THREAD

**Issue by mavnn** [fsprojects/Paket#636]
Actually using the Pack command, a few things are coming to mind.

The idea was that the paket.template files would be fairly static, and most variable metadata would come from assemblies. In practice, there's a fairly sharp split between "static" metadata (icon url, description) and variable metadata (release notes, version for file based templates).

Should we add ways of overriding some selected bits of metadata via the pack command? For people using things like Fake updating the paket.template isn't too bad, but the format was designed to be human friendly rather than easy to machine manipulate and not everyone will be using decent build tooling.

**Comment by forki** [comment]
the pack command needs optional parameters ate least for:
 - version
 - releasenotes

**Comment by forki** [comment]
I think if we have these two things in, it will be a good start. Could you please try to get this implemented?
BTW: I'm making good progress on the FAKE tasks.

**Comment by forki** [comment]
Ok I can now take this.

**Comment by mavnn** [comment]
Thanks, lots of admin and interviews today
