### ISSUE TITLE
Files syntax in template files

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#637]
Currently we have (see http://fsprojects.github.io/Paket/template-files.html#Files):

    from relative/to/template/file
    to folder/in/nupkg

how about:

    relative/to/template/file ==> folder/in/nupkg

and mybe we can make the `to` part optional?

/cc @mavnn @agross

**Comment by mavnn** [comment]
`==>` would be legal in a file name. You need some kind of demarkation character that isn't legal in a path (I chose newline :) )

**Comment by forki** [comment]
I see. 

I propose the following. Let's use the arrow and if some wants such a file namehe needs to quote.

I really want the syntax to be as easy as possible. Ok?

**Comment by mavnn** [comment]
Having said that, I'm not precious about the current syntax. Just don't want the alternative to be ambigious.

**Comment by mavnn** [comment]
Quotes would solve the problem, yes.
