### ISSUE TITLE
Packing without explicit file references

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#640]
In most of my projects I use a nuspec template like:

    <?xml version="1.0" encoding="utf-8"?>
    <package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <metadata xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
        <id>@project@</id>
        <version>@build.number@</version>
        <authors>@authors@</authors>
        <owners>@authors@</owners>
        <licenseUrl>http://github.com/fsprojects/FSharp.Management/blob/master/LICENSE.txt</licenseUrl>
        <projectUrl>http://fsprojects.github.com/FSharp.Management</projectUrl>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <summary>@summary@</summary>
        <description>@description@</description>
        <releaseNotes>@releaseNotes@</releaseNotes>
        <copyright>Copyright 2013</copyright>
        <tags>@tags@</tags>
      </metadata>
    </package>

The FAKE NuGet task is used to replace all the placeholders, but I don't specify explicit file references. Instead I create the package structure (i.e. the lib folder) in the FAKE script and use NuGet's folder detection feature. Can we do the same with Paket?

**Comment by mavnn** [comment]
Just set a files list like

```
files
    my/pre-arranged/dir ==> .
```
