### ISSUE TITLE
[WIP] Impressions from using Paket Pack API

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#642]
Started working on replacing `Fake.Nuget` with `Paket.Pack`

Thought it might be useful to have the first impression from someone working with this API for the first time. So consider this a braindump. If some of this stuff is to be considered a bug, we should probably create separate issues for them.

* Packing is just a __single line of code__ :smile: (And even for multi output solutions, the complexity does not change as far as I can see it.)
* Took a bit of time for me to locate the correct API level. I assume the `Dependencies.Locate().Pack(...)` is the correct one to use for this kind of integration.
* I had to manually add a reference to the dll of `DotNetzip` confusingly name `Ionic.Zip.dll`.  In order for Paket to find and load the DLL. Feels a bit wrong to do this as the script itself does not have any direct dependencies on this DLL. _Note_: I am note very used to writing F# scrips, and it is possible this is to be expected. If so, it should probably be documented somewhere, (Or maybe be part of the file load exception message given?)
* Even though `ProjectScaffold` explicitly sets quite a bit of assembly info (https://github.com/fsprojects/ProjectScaffold/blob/master/build.template#L71) None of this seemed to be read by Paket.Pack. Got exception that all mandatory info was lacking, even after checking assemblyinfo.
* Attempting to set version using the `?version:string` parameter to the `Pack` command did not seem to have any effect.
* I miss not being able to override _all template metadata info_ from the API. Forcing the use of template files makes project with multiple outputs duplicate a lot of data. (Actually, if we could set all template data from the API, the template file would be pretty much redundant when scripted from an F# environment.

**Comment by forki** [comment]
did you see that we already have FAKE tasks? https://github.com/fsprojects/Paket/blob/master/build.fsx#L188

**Comment by forki** [comment]
regarding overwrite of meta-data: that's exactly the pain point we need to figure out. Where would it make sense to add this feature? FAKE tasks or Paket or both?

**Comment by Vidarls** [comment]
No I did not :smile:

That does seem to solve most issues. Will have a go in the morning.

**Comment by mavnn** [comment]
An other option would be to enable paket.template files to share data in some way (I'm thinking off the top of my head here :) ). Some kind of template template that projects within the solution can override.

**Comment by JonCanning** [comment]
Just been trying it out; fell over when using an indirect dependency PackageMetaData line 209

**Comment by forki** [comment]
@JonCanning could you  please elaborate? thanks

**Comment by JonCanning** [comment]
Sorry, you may have noticed that I'm generally crap at reporting bugs

paket.dependencies contains FsPickler.Json, paket.template contains FsPickler

**Comment by mavnn** [comment]
It will assume that if you've got a dependency listed in paket.dependencies that you want it listed explicitly as a dependency of your package.

**Comment by JonCanning** [comment]
I'm trying to push to appveyor nuget and it's failing with a 500 error. I've been trying to fix it but am stumped :cry: Any pointers on what I can do to diagnose the problem?

**Comment by forki** [comment]
same as https://github.com/fsprojects/Paket/issues/646?

**Comment by JonCanning** [comment]
It's something with the nupkg, if I pack with nuget I can push with Paket

**Comment by mavnn** [comment]
@JonCanning really? Any chance you could get us a copy of the nupkg, or is it closed source code?

**Comment by mavnn** [comment]
If you can't send it to us, try opening the nupkg with Nuget Package Explorer and see if that succeeds.

**Comment by JonCanning** [comment]
Ah, RTFM Jon

    In a project file, the following dependencies will be added:

    any paket dependency with the range specified in the paket.dependencies file.

I had added a dependency block....

**Comment by mavnn** [comment]
@JonCanning did that help? It will just ignore the manually specified dependency block in that case. Also, open question to all: if a project template specifies a files or dependencies section, should that be an error? At the moment they will be silently ignored.

**Comment by JonCanning** [comment]
Yes, the dependencies are being duplicated

**Comment by forki** [comment]
I tried to apply the canges to https://github.com/fsprojects/FSharpx.Async but I get
![image](https://cloud.githubusercontent.com/assets/57396/6375061/f8aea730-bd14-11e4-9b56-53684d489d19.png)

ideas?

**Comment by forki** [comment]
can we close this?

**Comment by mavnn** [comment]
So, @forki 's issue is fixed in #660 . @JonCanning how are things going with AppVeyor?

**Comment by mavnn** [comment]
If it's broken, let's open a new issue for it.

**Comment by JonCanning** [comment]
It was fine when I removed the dependency block since they were being duplicated

**Comment by mavnn** [comment]
@JonCanning thanks!

**Comment by JonCanning** [comment]
Thanks for this, it has banished nuget completely from our code

**Comment by mavnn** [comment]
I feel like I should get this mounted and put on a wall (possibly with a copy for each Paket maintainer)
