### ISSUE TITLE
Running Paket Pack fails due to version conflict of Fsharp.core

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#645]
Running of a clean master branch of ProjectScaffold.

* Run build to create project
* Added template file to the project in src
* Run `Paket.exe pack output bin`
* Observe crash:

```
Paket failed with:
        Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

**Comment by Vidarls** [comment]
Running inside FAKE script using FAKE helpers yields the following:

```
Paket failed with:
        Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil.
Running build failed.
Error:
System.Exception: Error during packing ..
   ved Fake.Paket.Pack@64.Invoke(String message) i D:\code\fake\src\app\FakeLib\PaketHelper.fs:linje 64
   ved Fake.Paket.Pack(FSharpFunc`2 setParams) i D:\code\fake\src\app\FakeLib\PaketHelper.fs:linje 64
   ved FSI_0001.Build.clo@191-17.Invoke(Unit _arg8) build.fsx:linje 192
   ved Fake.TargetHelper.runTarget@329(String targetName) i D:\code\fake\src\app\FakeLib\TargetHelper.fs:linje 343
```

**Comment by forki** [comment]
This is really strange. The fsharp.core is merged into paket.exe

**Comment by mavnn** [comment]
No idea at the moment: running the exe works fine for me. I'll try and have a look tomorrow.

**Comment by Vidarls** [comment]
See fsprojects/ProjectScaffold#143 for the code I am running that fails.

**Comment by forki** [comment]
Could you please send a WIP pull request with your changes? I need to investigate

**Comment by Vidarls** [comment]
@forki Did we post simultaneously, or do you need something more than fsprojects/ProjectScaffold#143 ?

**Comment by forki** [comment]
Yep. ;-)

**Comment by Vidarls** [comment]
This is utterly weird:

Today, I wanted to create a file based package for some dll.

Did the following:

* Create a new Folder structure for the mini project
* Download latest `paket.bootstrapper`
* Run the bootstrapper to get latest paket (0.30.3)
* Create the `template file`
* Create empty `paket.dependencies`
* Run `Paket.exe pack output .\`
* Observe: __everything works as expected__

(Tried running the scaffold pack again, and still: no go)

**Comment by forki** [comment]
So there error is only happening in projectscaffold?

**Comment by Vidarls** [comment]
Yes, so far that seems to be true

**Comment by Vidarls** [comment]
Although, to be accurate: My simple file based package test was done manually. 

I was _not_ using FAKE for this project.

**Comment by Vidarls** [comment]
I have not tested using FAKE outside the context of ProjectScaffold

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/6345823/1e6c972c-bc0a-11e4-856d-688461575a46.png)

I don't get the issue with the missing FSharp.Core

**Comment by Vidarls** [comment]
Can this possibly be som GAC issue, IE have relatively recently (last december) moved to a new computer, and as such I don't think I've ever installed 4.3.0 as part of any official MS stuff that puts things in the GAC? If you have installed a sequence of different F# versions on you machine, you might have the correct F# version in your GAC?

**Comment by forki** [comment]
Yes that might be true, but why is it working in your other project?

**Comment by Vidarls** [comment]
yeah, that is weird.
I will try to do a clean clone and see what happens

**Comment by Vidarls** [comment]
* Did a clean clone from my Github Repo, 
* Build.cmd nuget
* Did init stuff
* Build fails with same issue:

```
C:\Users\Vidar\Documents\Visual Studio 2013\Projects\cleanclone\.paket\paket.exe pack output bin version "1.0" releaseNotes "More awesome stuff coming
Added SourceLink for Source Indexing PDB"
Paket version 0.30.3.0
found: C:\Users\Vidar\Documents\Visual Studio 2013\Projects\cleanclone\paket.dependencies
Paket failed with:
        Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil.
Running build failed.
Error:
System.Exception: Error during packing ..
   ved Fake.Paket.Pack@64.Invoke(String message) i D:\code\fake\src\app\FakeLib\PaketHelper.fs:linje 64
   ved Fake.Paket.Pack(FSharpFunc`2 setParams) i D:\code\fake\src\app\FakeLib\PaketHelper.fs:linje 64
   ved FSI_0001.Build.clo@173-15.Invoke(Unit _arg7) i C:\Users\Vidar\Documents\Visual Studio 2013\Projects\cleanclone\build.fsx:linje 174
   ved Fake.TargetHelper.runTarget@329(String targetName) i D:\code\fake\src\app\FakeLib\TargetHelper.fs:linje 343
```

**Comment by forki** [comment]
ah. so it's FAKE itself that throws the error and not paket.exe?

**Comment by Vidarls** [comment]
Not really, FAKE just copies the output after running the process.
I get the same failure running Paket manually from the command line (See my first two posts in this issue)

**Comment by Vidarls** [comment]
Output from running directly:

```
C:\Users\Vidar\Documents\Visual Studio 2013\Projects\cleanclonePS>.\.paket\paket.exe pack output bin version "1.0" releaseNotes "Some stuff"
Paket version 0.30.3.0
found: C:\Users\Vidar\Documents\Visual Studio 2013\Projects\cleanclone\paket.dependencies
Paket failed with:
        Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil.
```

**Comment by forki** [comment]
and all the other paket commands work? how is this even possibleß

**Comment by Vidarls** [comment]
at least the initial paket restore had no issues

**Comment by Vidarls** [comment]
Can you do a special build of Paket that prints a full stack trace on exceptions?, then maybe we could get some clue as to what is going on

**Comment by forki** [comment]
`-v` should print more

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/6347268/d8958102-bc16-11e4-80ca-d51d8ce60b75.png)

(not related to current issue, but I added more info for the issue I see)

**Comment by Vidarls** [comment]
```
Paket failed with:
        Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil.
StackTrace:
     ved System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   ved System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   ved System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   ved System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   ved System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   ved System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   ved System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   ved Paket.PackageMetaData.loadAssemblyMetadata(String buildConfig, ProjectFile projectFile)
   ved Paket.PackageProcess.f@1-62(String buildConfig, HashSet`1 allTemplateFiles, ProjectFile projectFile, TemplateFile templateFile)
   ved Paket.PackageProcess.Pack(DependenciesFile dependencies, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 version, FSharpOption`1 releaseNotes)
   ved Paket.Program.clo@197-21.Invoke(ArgParseResults`1 results)
   ved Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   ved Paket.Program.processCommand@59-1.Invoke(Command command, String[] args)
   ved <StartupCode$paket>.$Paket.Program.main@()
```

**Comment by forki** [comment]
ha! Thanks.

/cc @mavnn any idea.

**Comment by mavnn** [comment]
Are you trying to pack FSharp.Core? It's trying to load something for
reflection, but it should only be doing that for dlls with a matching
paket.template.

**Comment by forki** [comment]
side question: why are we loading the assembly via "bytes" in loadAssemblyMetadata?

**Comment by mavnn** [comment]
Hmm.

    <Reference Include="FSharp.Core,
Version=$(TargetFSharpCoreVersion), Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a">
        <Private>False</Private>
    </Reference>

In the fsproj file. It looks like when it loads the assembly with
reflection it tries to find all the dependencies and fails. If you
change that to true, does it succeed?

It's still a bug as we shouldn't need to load the dependencies to read
custom attributes, which is all we're doing with the reflection.

**Comment by mavnn** [comment]
@forki to avoid locking the file.

**Comment by Vidarls** [comment]
@mavnn This is just running `Paket pack` on the default ProjectScaffold after doing the initial renamings of init.fsx.

**Comment by Vidarls** [comment]
setting Private to `True` made no difference

**Comment by mavnn** [comment]
Pity :)

**Comment by forki** [comment]
also projectscaffold should really use FSharp.Core as nuget package dependency.

**Comment by mavnn** [comment]
@Vidarls Has the project been built before attempting to package it?

I'd still be surprised by the resulting error message, but it will break packaging if there's nothing to package yet...

**Comment by mavnn** [comment]
@forki agreed, but different issue in different project :)

**Comment by Vidarls** [comment]
@forki I don't think Paket should care about what version of Fsharp.Core is referenced, or how (nuget / GAC) it is referenced. 
For the sake of Project scaffold, I agree though.

@mavnn Yes, it is executed as the last part of a build script. (Also, I suppose there is a better error message if the problem was missing binaries right?)

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/commit/e3c311ccbf2af3b01209c7b057fa514656805bcd

**Comment by mavnn** [comment]
Good call - I don't have any great ideas without more info at this point.

**Comment by forki** [comment]
what if we try/catch https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PackageMetaData.fs#L98 and fall back to assembly.GetCustomAttributes(false) if an error occurs?

**Comment by forki** [comment]
ok. let's see where https://github.com/fsprojects/Paket/commit/8a6c63f090c2dac9acb99ce330335d0543842a13 takes us.

**Comment by Vidarls** [comment]
```
C:\Users\Vidar\Documents\Visual Studio 2013\Projects\limbergrove-scaffolding [paketpack +5 ~3 -13 !]> .\.paket\paket.exe pack output bin version "1.0" releaseNotes "Some notes" -v
Paket version 0.30.6.0
found: C:\Users\Vidar\Documents\Visual Studio 2013\Projects\limbergrove-scaffolding\paket.dependencies
Parsing C:\Users\Vidar\Documents\Visual Studio 2013\Projects\limbergrove-scaffolding\paket.dependencies
Loading assembly metadata for C:\Users\Vidar\Documents\Visual Studio 2013\Projects\limbergrove-scaffolding\src\Ra.Ta\..\..\bin\Ra.Ta.dll
Loading custom attributes failed for Ra.Ta, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.
Message: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil.
Paket failed with:
        Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil.
StackTrace:
     ved System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   ved System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   ved System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   ved System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   ved System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   ved System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   ved System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   ved Paket.PackageMetaData.loadAssemblyMetadata(String buildConfig, ProjectFile projectFile)
   ved Paket.PackageProcess.f@1-64(String buildConfig, HashSet`1 allTemplateFiles, ProjectFile projectFile, TemplateFile templateFile)
   ved Paket.PackageProcess.Pack(DependenciesFile dependencies, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 version, FSharpOption`1 releaseNotes)
   ved Paket.Program.clo@197-21.Invoke(ArgParseResults`1 results)
   ved Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   ved Paket.Program.processCommand@59-1.Invoke(Command command, String[] args)
   ved <StartupCode$paket>.$Paket.Program.main@()
```

**Comment by forki** [comment]
argh. even the GetCustomAttributes(false) is failing.

New strategy: There is an overload which takes the type of the attribute. what if we only ask for the attributes we need. Would this also fail?

**Comment by forki** [comment]
on the other hand: the project would not run on your machine since you don't have the referenced FSharp.Core.dll, right? Maybe the error message is now good enough and we close it. It's not really a Paket pack issue, right? Or do you see a way to improve things?

**Comment by Vidarls** [comment]
Strange, I do indeed have the Fsharp.Core installed. (I pretty much have to, as the build is passing). But it seems this version is not accessible from withing Paket.exe. Which makes sense, because local dll should always override GAC dlls

**Comment by forki** [comment]
I tried to minimize the impact

**Comment by cdrnet** [comment]
> Which makes sense, because local dll should always override GAC dlls

They do not. If an assembly is found in the GAC it will use it without even probing the local files. See [How the Runtime Locates Assemblies](https://msdn.microsoft.com/en-us/library/aa720133.aspx)

**Comment by forki** [comment]
our workaround seems to work around. 
https://github.com/fsprojects/ProjectScaffold/pull/143#issuecomment-75772058

**Comment by dsyme** [comment]
See also #1289 which looks like the same underlying issue as this
