### ISSUE TITLE
Paket push fails pushing to an Inedo ProGet feed

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#646]
Trying to use the new Paket Push to push to our internal Inedo Proget (http://inedo.com/proget/overview) server.

Fails with status 400, invalid request.

Now, this might be due to ProGet not following the standard properly. 
It may be that Paket is not following the standard properly
Or it may be that ProGet uses some redirects that are not properly handled by Paket push.

I do know that using nuget push works as expected though.

Are there any good reasons not to piggyback on nuget for this feature. Is paket gaining anything (except 1 less dependency) from re-implementing this?

**Comment by forki** [comment]
yes in some sense it's "only" 1 dependency less. But on the other side it's the last step to be completely independent of nuget.exe

**Comment by mavnn** [comment]
I actually use almost exactly the same code as NuGet - it's just a simple PUT request. Is there any authentication (apart from API key) on that feed?

**Comment by Vidarls** [comment]
No, it uses a sort "fake" api key giving "user:pw" as the api key.ref: http://inedo.com/support/documentation/proget/feeds/api-keys

**Comment by mavnn** [comment]
@Vidarls I cannot see any reason this wouldn't work off hand. I'm out for most of the rest of the day, but I may try and download a trial version of proget tomorrow and see if I can replicate.

**Comment by Vidarls** [comment]
My gut feeling is that ProGet is using redirects, and that your code using the simple webclient does not handle this. (The nuget code http://nuget.codeplex.com/SourceControl/latest#src/Core/Server/PackageServer.cs ) uses the more elaborate httpclient, that I believe might handle redirects automatically.

**Comment by mavnn** [comment]
Might be a good first attempt - I went with webclient as paket was using it already but we might as well upgrade to httpclient if it solves problems. Especially as the authentication is done differently for pull and push anyway...

**Comment by mavnn** [comment]
Unfortunately I won't be able to make the changes till tomorrow.

**Comment by Vidarls** [comment]
Unfortunately httpclient is 4.5 only, and still Paket is targeting 4.0

The httpclient of nuget is a custom beast they have made.(http://nuget.codeplex.com/SourceControl/latest#src/Core/Http/HttpClient.cs) based on httpwebrequest.

Anyways, I used fiddler and had a look at the difference between what Nuget.exe did, and what Paket does:
As far as I can see, the main difference is that Nuget uses multipart/Form-data as the content type, while the WebClient implementation uses application/octet stream.

(Also, I now believe  that my initial gut feeling of redirects being the issue is wrong, as no redirects are being returned by pro get)

**Comment by forki** [comment]
Could you please try to send a fix. Will release asap.

**Comment by Vidarls** [comment]
As it turns out, this was not entirely trivial. 

Started trying to enhance webclient to support multipart uploads (currently using application/octet), but so far I am failing miserably :disappointed: 

Just now found this: http://ferozedaud.blogspot.no/2010/03/multipart-form-upload-helper.html
that might be some ideas in the right direction

I hope I get the time to see this through, but so far this week has been a bit:

![yak shaving ftw](http://s.quickmeme.com/img/25/25c17af0b98cf8e06ad2550b2efd107a67990dd1938942ab2f11de68a9800652.jpg)

**Comment by forki** [comment]
welcome to my world...

**Comment by forki** [comment]
is https://github.com/fsharp/FAKE/pull/664 related?

**Comment by Vidarls** [comment]
Probably not, as I get the failure when using Paket push directly from the command line

**Comment by Vidarls** [comment]
Wow that was quick.

Did you test that push still works on the standard nuget.org feed?

**Comment by forki** [comment]
yep via dogfooding.
