### ISSUE TITLE
Paket package crashes Nuget v3 beta UI

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#655]
Repro:
* Install nuget v3 beta into VS2013
* "manage nuget packages"
* search for "paket"
* go to the results on the left. scroll up and down and select some results
* VS crashes wirth:

System.FormatException was unhandled
Message: An unhandled exception of type 'System.FormatException' occurred in WindowsBase.dll
Additional information: String was not recognized as a valid Boolean.

**Comment by mavnn** [comment]
Thanks.

**Comment by mavnn** [comment]
Hmm. No joy on the package side working out what's going on. Let's see if it's fixed on the NuGet side  and if they can give us any clues what is wrong.

**Comment by forki** [comment]
same now with FSharpx.Async

**Comment by mavnn** [comment]
Hmm. Same format exception as well?

**Comment by forki** [comment]
yep

**Comment by forki** [comment]
@maartenba @csharpfritz do you know if the packages are invalid or is this a Nuget v3 issue? It seems to work fine with v2.

**Comment by csharpfritz** [comment]
This is a v3 issue.. we're working on a patch now.



Jeff



On Thu, Feb 26, 2015 at 11:03 AM, Steffen Forkmann <notifications@github.com

**Comment by forki** [comment]
thanks.
