### ISSUE TITLE
Authors node is sometimes left empty even if authors are specified in template

### ISSUE THREAD

**Issue by mavnn** [fsprojects/Paket#659]
See https://github.com/fsprojects/FSharpx.Async/tree/212645ee810cc8defe9496501c158d979e03233e

Packaging claims to complete successfully, but there are no authors in the resulting nuspec despite the fact they are in the template.

This should:
a) work
b) if the authors weren't there or created an empty list, packing should fail

**Comment by forki** [comment]
I think a + b ;-)

**Comment by mavnn** [comment]
Agreed :)

**Comment by mavnn** [comment]
Ok: this was a general problem with the parser. If you use the multi line syntax for setting a value

```
description
    is a description that works
```
but have white space at the end of the first line it thinks you're explicitly setting the value to an empty string (and then ignores the indented line underneath)

```
description 
    This one is broken. See how obvious the difference is?
```

I'll close this bug for now as it's really part of #625 - I should actually write a proper parser soon.
