### ISSUE TITLE
Paket pack seems to miss some properties

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#665]
type project
    owners
        Steffen Forkmann, Max Malook, Tomasz Heimowski
    authors 
        Steffen Forkmann, Max Malook, Tomasz Heimowski
    projectUrl
        http://github.com/fsprojects/Chessie
    iconUrl
        https://raw.githubusercontent.com/fsprojects/Chessie/master/docs/files/img/logo.png
    licenseUrl
        http://github.com/fsprojects/Chessie/blob/master/LICENSE.txt
    requireLicenseAcceptance
        false
    copyright
        Copyright 2015
    tags
        rop, fsharp, F#
    summary
        Railway-oriented programming for .NET
    description
        Railway-oriented programming for .NET
    
in https://github.com/fsprojects/Chessie/blob/master/src/Chessie/paket.template results in:
    
![image](https://cloud.githubusercontent.com/assets/57396/6410183/2ccd9950-be6d-11e4-9678-714639e618b3.png)

/cc @mavnn I think we found our package issue.

**Comment by forki** [comment]
the generated nuspec is:

    <?xml version="1.0" encoding="utf-8" standalone="yes"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
      <metadata>
        <id>Chessie</id>
        <version>0.0.2</version>
        <authors>Steffen Forkmann, Max Mallok, Tomasz Heimowski</authors>
        <owners>Steffen Forkmann, Max Mallok, Tomasz Heimowski</owners>
        <description>Railway-oriented programming for .NET</description>
        <summary>Railway-oriented programming for .NET</summary>
        <releaseNotes>XML-docs added</releaseNotes>
        <copyright>Copyright 2015</copyright>
        <tags>rop, fsharp, F#</tags>
      </metadata>
    </package>

**Comment by mavnn** [comment]
It's not the causes of the crashes - the the compulsory fields have come through OK (only id, version, authors and description are required).

That said, it is still a bug. It's very odd that you've got some of the optional fields but not all of them.

I'll look into it, it might be something I'm not testing in the new parser.

**Comment by mavnn** [comment]
Tags should be space separated according to the spec, by the way - although nuget.org appears to just strip the commas anyway.

**Comment by forki** [comment]
>> Tags should be space separated according to the spec, by the way - although nuget.org appears to just strip the commas anyway.

we should do the same. Because I will never learn that ;-)

**Comment by mavnn** [comment]
Break the spec whilst creating :package: s?! Heresy!

I'll add a Trim along with the embarrassing bug fix.

**Comment by forki** [comment]
looks much better! thx.
But the title is still missing. Can we do some default value for this?

**Comment by mavnn** [comment]
No, I don't think so. It's supposed to be optional.
