### ISSUE TITLE
error parsing libgit2sharp prerelease

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#667]
![image](https://cloud.githubusercontent.com/assets/80104/6424737/835d8cde-beb9-11e4-9628-faf17926b614.png)

![image](https://cloud.githubusercontent.com/assets/80104/6424730/496de640-beb9-11e4-8b25-0e4ab1a11c2f.png)

![image](https://cloud.githubusercontent.com/assets/80104/6424733/64dc0de4-beb9-11e4-832d-3bd746a5635d.png)

**Comment by forki** [comment]
;-(

**Comment by forki** [comment]
@maartenba @shiftkey so that thing should be a string and sorted alphabetical?

**Comment by shiftkey** [comment]
The number after `pre` is the timestamp of the build time (just so it's always increasing from the build serve) and it's a recent change - https://github.com/libgit2/libgit2sharp/pull/941. I guess we just didn't expect it to hit Int.MaxValue like that - sorry!

cc @nulltoken

**Comment by forki** [comment]
Yep I figured that and fixed our parser. But I wonder if that will break
something else in the fragile world of nuget.

**Comment by shiftkey** [comment]
¯\(°_o)/¯

**Comment by nulltoken** [comment]
:heart_eyes: for taking care of this and sorry for somewhat causing this mess :confused:

>But I wonder if that will break something else in the fragile world of nuget.

The doc **[states](https://docs.nuget.org/create/versioning)** that everything after a `-` is dealt with as a string. The code seems to agree with this as well.

 - https://nuget.codeplex.com/SourceControl/latest#test/Core.Test/SemanticVersionTest.cs
 - https://github.com/NuGet/NuGet.Versioning/blob/93baf2421ab591e6a7560ed32dc81b591fe4fb01/test/Versioning.Test/VersionParsingTests.cs

**Comment by forki** [comment]
Ah now I remember. It's this super annoying nuget feature which require us to create -alpha001 versions instead of -alpha1. Paket tries to understand SemVer here and treats alpha10 as newer than alpha9. The timestamp is now a new pattern.

**Comment by nulltoken** [comment]
>Paket tries to understand SemVer here and treats alpha10 as newer than alpha9. 

@forki Sadly, the spec doesn't provide such interesting/corner cases examples. However, I'm under the impression that section 11 could be understood as

- Package.0.1.2-alpha10 < Package.0.1.2-alpha9
- Package.0.1.2-alpha.9 < Package.0.1.2-alpha.10

*"Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and* **identifiers with letters or hyphens are compared lexically in ASCII sort order** *"*

**Comment by kolektiv** [comment]
If it's of any use, you might want to lift the tests from my SemVer lib - I think they catch these cases...
https://github.com/xyncro/semver.net/blob/develop/tests/SemVer.Tests/SemVer.Tests.fs

**Comment by nulltoken** [comment]
@kolektiv :cool: :bangbang: 

However, I'm not sure I can see the test depicting (or invalidating)

```
Package.0.1.2-alpha10 < Package.0.1.2-alpha9
```

**Comment by kolektiv** [comment]
That's a good point, that exact case isn't covered (although I'm fairly sure a test for that would pass!) I'll add one soon, but the other tests may be useful :)

**Comment by forki** [comment]
numeric pre-release identifiers must not contain leading zeroes (SemVer 2.0.0/9)

    raises<exn> <@ SV "1.0.0-01" @>
    raises<exn> <@ SV "1.0.0-alpha.01" @>

this will break with nuget.

**Comment by kolektiv** [comment]
Yes, sadly one of the reasons I haven't suggested Paket or others to use SemVer.Net for this is because NuGet is not actually compliant with SemVer, and SemVer.Net doesn't have a "liberal" mode which would let a lot of common NuGet (wrong!) practice pass. Unfortunately tests for NuGet need to be basically "SemVer, but relaxed enough to let the slightly broken NuGet interpretation through"...

**Comment by forki** [comment]
Yes our strategy is basically: "accept everything that is in nuget.org but if we generate new versions then try to create only SemVer versions"
