### ISSUE TITLE
Our internal packages don't respect SemVer 'no leading zeros'

### ISSUE THREAD

**Issue by ascjones** [fsprojects/Paket#672]
I just updated to 31.7 and our internal package versioning is not compatible with it, since we (incorrectly) have leading zeros as version part names.

https://github.com/fsprojects/Paket/commit/3486c26d02c8073cef8c05be54d547b67e4adbdb

I can potentially fix this but it will take a while for the changes to propogate into our feed and across projects.

So I can tell people to stick on 31.6 until all our packages have removed the leading zeros, or we could add some kind of 'non-strict' semver option?

I suppose it's good to force us to be SemVer compatible, at the cost of some pain and management in the meantime. But on the other hand it might be nice not to break paket if you have any packages in the feed which don't respect SemVer 100%?

Not sure which approach is best - ideas?

**Comment by ascjones** [comment]
Found this issue https://github.com/fsprojects/Paket/issues/289 which talks about this

**Comment by forki** [comment]
our idea is to accept all existing nuget package versions. I reverted that stuff.

**Comment by ascjones** [comment]
Okay well that also solves it. Thanks!
