### ISSUE TITLE
Paket playgrounds

### ISSUE THREAD

**Issue by caindy** [fsprojects/Paket#673]
As a developer desiring to experiment with a nuget package/Github project
I would like to have a playground (workspace) created by typing e.g. `paket play nuget://nuget.org/...` or `paket play http://github.com/...`
So that I could quickly experiment with a package in F# interactive with minimal friction

`paket play` could create a new temporary folder, `cd` there, emit a `paket.dependencies` and do an `install`, then startup F# interactive with all the appropriate dependencies loaded. Repositories and packages that contained a designated `paket-play.fsi` could use that script to bootstrap the environment (e.g. load tutorials, print instructions, etc.).

**Comment by forki** [comment]
nice idea, but I think that's out of scope and should be done in a separate project.
But keep an eye on https://github.com/fsprojects/Paket/issues/677 for the load scripts. 
Alos look at http://www.navision-blog.de/blog/2014/10/14/retrieving-github-download-counts/ which shows how to use packages only by using fsi.
