### ISSUE TITLE
Paket pack fails if output type is executable.

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#674]
This is probably a bit of an edge case, but: I have a project that produces an `.exe` file, but this `.exe` file is also used as a library, so I want to pack it as a nuget package.

Leaving aside the discussion on where in the package folder this `.exe` file should go, paket .pack assumes it should be looking for a dll file, and failes packing when the `projectname.dll` file is nowhere to be found. (It should be looking for `projectname.exe`).

**Comment by Vidarls** [comment]
(This is a project template btw, not a file type template)

**Comment by Vidarls** [comment]
Attempted to work around this by not adding a template file to the executables => paket pack should include project binaries into package for packed dlls, same issue

**Comment by forki** [comment]
Yes I assume this needs to be addressed in paket

**Comment by Vidarls** [comment]
It's holding up my progress, So I'll have a go at shaving this yak. (unless @mavnn  is already way ahead of me)

**Comment by Vidarls** [comment]
found the issue
Now, lets see if I can also get some tests covering it
