### ISSUE TITLE
Paket failed with: This operation would create an incorrectly structured document.

### ISSUE THREAD

**Issue by palpha** [fsprojects/Paket#678]
I'm trying to convert-from-nuget on a largeish chunk of projects, and it seems like some XDocument operation fails.

This is the anonymized output:
https://gist.github.com/palpha/d56efad737fc49dfe89d

Any ideas for what I should look for? I'm assuming that this is due to something in my solutions/projects being wonky. This collection of code is the result of eight years of continuous development, so I'm sure there are weird, unexpected stuff that Paket isn't happy to deal with :).

**Comment by forki** [comment]
can you please try to run with `-v`?

**Comment by palpha** [comment]
Of course, sorry for not thinking. Brb.

**Comment by palpha** [comment]
Update the Gist for verbose output.

**Comment by forki** [comment]
Ok something in ensurePathExists seems to be "broken", but I can't see it from starring at the code.

I recommend the following:
* clone paket 
* set startup project to Paket.exe
* set working dir to you project path
* set command line args to `convert-from-nuget`
* hit F5

![image](https://cloud.githubusercontent.com/assets/57396/6508699/a28e6c4a-c35a-11e4-84c1-170e00fb6f33.png)

Debugger should break on the ensurePathExists and maybe you can see something.

**Comment by palpha** [comment]
Will do and report any findings. Thanks!

**Comment by palpha** [comment]
Sandcastle Help File Builder produces Web.Config files in which the configuration nodes are namespaced like this:

    <configuration xmlns="http://schemas.microsoft.com/.NetConfiguration/v2.0">

It looks like ensurePathExists/tryGetElement assumes zero namespace and tries to add an empty configuration element to the root of the document.

I can work around this by modifying the SHFB template (and resetting the changes Paket makes to these files, as they are part of the directory structure but not the application itself).

**Comment by forki** [comment]
Please reopen if you think we need to fix something in paket.

**Comment by feliara8** [comment]
im running to this exact same problem, whats the solution?

**Comment by forki** [comment]
I think I need paket.dependencies, paket.references and csproj to reproduce and fix.

**Comment by MrLuje** [comment]
I also have the same issue.

@forki, you can use the following repo : https://github.com/MrLuje/paket-issue-webconfig

run "npm install" from the csproj folder and then "paket install".

In this case, the issue comes from a web.config bundled in a npm package (selenium-webdriver here) in node_modules folder.
Another concern is : should the node_modules folder have to be parsed at all ?

**Comment by forki** [comment]
I think we would accept a PR that skips node folders.

Am 08.06.2017 9:41 vorm. schrieb "MrLuje" <notifications@github.com>:
