### ISSUE TITLE
No implicit file packaging in packet.template

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#680]
It is OK when `paket` add `PackageName.dll` to NuGet package when `files` section is not specified.
But when I write
```
files
	../../bin/DynamicsCRMProvider ==> lib/net40
```
i expect that all content of the folder will be packed inside 'lib/net40'. But in fact I get error
```
Paket failed with:
        An item with the same key has already been added.
Running build failed.
Error:
System.Exception: Error during packing ..
   at Fake.Paket.Pack@66.Invoke(String message) in C:\code\fake\src\app\FakeLib\PaketHelper.fs:line 66
   at Fake.Paket.Pack(FSharpFunc`2 setParams) in C:\code\fake\src\app\FakeLib\PaketHelper.fs:line 66
   at FSI_0001.Build.clo@180-16.Invoke(Unit _arg9) in d:\Personal\GitHub\DynamicsCRMProvider\build.fsx:line 181
   at Fake.TargetHelper.runTarget@329(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 343
```

So when I explicitly create section `files` I want to be sure that `paket` import only files mentioned there.

**Comment by mavnn** [comment]
@sergey-tihon this is what the ``file`` type templates are for. In general either you're going to want the default behaviour (a library nuget package based on the project) or you're doing something non-standard which needs specific files in specific places. At that point you can just create a template file with ``type file`` at the top and set everything up as needed.

If you've got a use case where you want to include elements of both, more details would be awesome.

**Comment by sergey-tihon** [comment]
Thanks @mavnn! I did not realize concept of configurable template `type` before.

**Comment by sergey-tihon** [comment]
But, I think that would be nice to have more granular control over dependencies, files, metadata inference. Like this:
```
type file
files
    ../../bin/DynamicsCRMProvider ==> lib/net40
dependencies
    auto
```
So I can specify what sections I want to infer.
@mavnn What do you think?
