### ISSUE TITLE
Investigate issues when using Klondike Nuget servers

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#682]
For Klondike-powered nuget feeds it seems the URLs may be different for the 'normal' nuget feeds.

My machine configuration was pointed to <serverroot>/api and the 'convert-from-nuget' command could not communicate with the server.

After some investigation, I realized that my nuget machine config and my VS nuget config differed in URL: the Vs ones were <serverroot>/api/odata.  When I changed the machine config to match (because it seems paket uses the nuget machine config), the convert operation completed successfully.

**Comment by forki** [comment]
I think we would need some help here. I have no idea what a "Klondike-powered nuget feed" is.

**Comment by baronfel** [comment]
(Klondike)[https://github.com/themotleyfool/Klondike] feeds are nuget feeds with a Lucene-powered search frontend on top of them.

I believe it's mostly used as a self-hosted, more performant, private nuget server.

**Comment by forki** [comment]
do you have a repro sample for me to check?

**Comment by mavnn** [comment]
If you configure your paket.dependencies to use the odata end point, then klondike and paket play nicely together:

```
source http://my.klondike.server/api/odata
```

Unfortunately klondike does not implemented most of the nuget v2 api, but doesn't error if you call an unsupported method - instead it redirects to the docs, which paket then (reasonably) tries to interpret as an api response.

**Comment by forki** [comment]
Can we configure paket to understand such feeds?

**Comment by mavnn** [comment]
Not really, I don't think. You'd have to infer that you'd recieved an html
response rather than a valid api response and then fall back to odata as a
second attempt.

**Comment by forki** [comment]
Please see #907

**Comment by baronfel** [comment]
I'll try to investigate this today and see if we can close this issue thanks to @ilkerde's awesome work.
