### ISSUE TITLE
security error for https://nuget.org/api/v2

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#683]
Use `https://www.nuget.org/api/v2` instead with the `www.` added. It looks like NuGet Gallery replaced their certificate today, but with a wildcard `*.nuget.org` certificate that doesn't support the naked domain. All our builds broke. All I had to do was update `paket.lock`. I updated `paket.dependencies` too.

https://twitter.com/cmr0n/status/573982728485388288

**Comment by forki** [comment]
I'd love to see a patch that works around this. Unfortunately I'm on vacation and can't help.

**Comment by forki** [comment]
If someone can fix it, then @mavnn and everyone with nuget fsprojects account can do a release.

**Comment by mavnn** [comment]
Did this get sorted? I'm not in a position to easily check at the moment, but can try and make this change later today if needed.

**Comment by forki** [comment]
AFAIK they fixed their certificate.

**Comment by ctaggart** [comment]
NuGet team did a good job at resolving this quickly. They solved it with a HTTP 301 permanent redirect. From Fiddler:

![image](https://cloud.githubusercontent.com/assets/80104/6600523/567dbc44-c7cd-11e4-8e55-378d3240490f.png)

To avoid the unnecessary requests, update the configurations to use `www.`.
