### ISSUE TITLE
Feedback: An item with the same key has already been added.

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#686]
If you add the same item twice to a `paket.references` file you get:
```
Locked version resolutions written to \paket.lock
Paket failed with:
        An item with the same key has already been added.
```

I would suggest that paket should at least tell me which file is invalid :). 
The error message itself could also be improved.
This could be a bug as well.

**Comment by forki** [comment]
I agree the error message is unfortunate. Could you please come up with a minimal repro?

**Comment by matthid** [comment]
Yeah its really simple you can just use paket.references:
```
FSharp.Core
FSharp.Core
```

OR https://gist.github.com/matthid/f617043240b36e096483

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/6553178/2e4d499a-c64e-11e4-801e-d606c07510f0.png)

**Comment by matthid** [comment]
Very cool, a real time-saver in the future :+1: , thanks!
