### ISSUE TITLE
Paket should pack XML docs into the nupkg

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#689]
/cc @mavnn 
Seems we're not packing these files. Also we're missing pdbs

references https://github.com/fsprojects/Chessie/issues/13

**Comment by forki** [comment]
I think I could add this to NupgkWriter.Write. Ok?

**Comment by mavnn** [comment]
You probably right that we should pack xml and pdb files as well. Thinking about this, should we be packaging Project.Name.* from the build output directory, or would that include things we should avoid?

**Comment by mavnn** [comment]
Or more accurately, Project.Name.* for each dll/exe we determine should be in the package.

**Comment by mavnn** [comment]
Doing it in the Write method seems reasonable.

**Comment by forki** [comment]
could you please review 8fdc1d5? Thanks
