### ISSUE TITLE
paket pack/paket.template should support wildcard patterns

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#690]
Like this:

```
type file
id GW.Angebot.Contracts
version 1.0
authors Alexander Groß
description
  Blah blah

files
    ../../build/bin/Angebot.Contracts.* ==> lib
```

**Comment by forki** [comment]
this is a known limitation right now.

/cc @mavnn

**Comment by forki** [comment]
maybe we could github link FAKE`s globbing module for this.

**Comment by forki** [comment]
ok I implemented basic wildcard pattern support. Again paket's gihub linking proves very handy (see d2e1502).

please give it a try.
