### ISSUE TITLE
paket.template fails to parse

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#692]
> Metadata fields can be specified in two ways; either on a single line prefixed with the property name (case insensitive), or in an indented block following a line containing nothing but the property name.

Given this `paket.template`:
```
type file
id GROSSWEBER.Angebot.Contracts
version 1.0

title
  grossweber.com Angebot contracts

description
  Contracts to talk to the Angebot service

authors
  GROSSWEBER

owners
  GROSSWEBER

projectUrl
  http://grossweber.com/

iconUrl
  http://grossweber.com/favicon.ico

copyright
  Copyright GROSSWEBER. All rights reserved.

files
  ../../build/bin/Angebot.Contracts.dll ==> lib
  ../../build/bin/Angebot.Contracts.pdb ==> lib
```

I get this:
```bash
$ paket pack output .
Paket version 0.31.13.0
found: paket.dependencies
Paket failed with:
        Unable to parse template file: Indented block with no name line 4.
```

Line 4 is an empty line.

**Comment by agross** [comment]
FYI, it works if I remove line 4 entirely.

**Comment by agross** [comment]
Also, it would be nice to see which file failed to parse. Right now I'm testing with a single file, so it was obvious which template is the culprit.

**Comment by mavnn** [comment]
It's very unforgiving on white space it doesn't expect, including blank lines after "single line" fields. I'll try and have a look it making it more friendly.

**Comment by forki** [comment]
@mavnn could you please review the fix? Thanks
