### ISSUE TITLE
paket pack should auto-include symbols

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#693]
> In a project template, the files included will be:
> * the output assembly of the matching project (in the correct lib directory if a library, or tools if an exe)
> * the output assemblies of any project references which do not have a matching template file

I'd like to see PDBs/MDBs to be included as well (if they're found) as they will aid debugging for my library users.

//cc @mavnn

**Comment by mavnn** [comment]
I think @forki already built with this, along with xml docs. @forki ?

**Comment by forki** [comment]
Yes I added pdbs and xml. I wonder what else is important.

**Comment by agross** [comment]
MDBs for mono? 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail
