### ISSUE TITLE
Upgrade to .NET 4.5?

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#697]
For a couple of things we need to upgrade to .NET 4.5.

Please comment if this is an issue for you.

**Comment by Vidarls** [comment]
The only potential problem I can think of is that you will end support for win xp / server 2003.

**Comment by Vidarls** [comment]
For my case I am (finally) moving our Interop and build stuff to a newer generation OS, so no worries here.

**Comment by forki** [comment]
> is that you will end support for win xp / server 2003

Like Microsoft did? ;-)

But yes that's why I ask.
