### ISSUE TITLE
paket.template - file type doesn't respect dir without slash at the end

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#698]
type file
	id xxx
	version 1.0
	authors xxx
	description
	        description of this test package
	files
		bin/Debug/ ==> lib

`bin/Debug` doesn't work
`bin/Debug/` works

/cc @mavnn

**Comment by forki** [comment]
ok this one is my fault. I changed that to FAKE's globbing. and the behaviour is already in FAKE.

Could you try to find a workaround around https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/TemplateFile.fs#L328?

we might even discuss changes to the globbing in FAKE
// @colinbull

**Comment by forki** [comment]
I wonder if it really copies the whole directory including subdirectories.

**Comment by theimowski** [comment]
In my case it did

**Comment by forki** [comment]
Ok then I think it should go upstream into FAKE

**Comment by forki** [comment]
It already annoyed some people there

**Comment by theimowski** [comment]
Go for It

**Comment by colinbull** [comment]
There is a slight subtly here, when we have the trailing slash this allows the globbing implementation to figure out that it is a directory so something like `bin\Debug\` will be turned into the following search tokens, [Directory(bin); Directory(Debug)]. Now if we don't have a the trailing slash we get [Directory(bin); Filename(Debug)], this is too support extension-less files. Now considering how rare they I could just test to see if the last token has an extension and emit the correct token. What do you think?

**Comment by forki** [comment]
Please take a look at 07a0b07
 and https://github.com/fsharp/FAKE/commit/8f834575301423cc5941c7e8deae4d1fa9bc7377 - I thought the `if Directory.Exists` would handle this?

**Comment by colinbull** [comment]
This causes a fair few test failures. I have added some failing tests and a fix https://github.com/colinbull/FAKE/commit/e3eb0413dd7841617adbb2203b240662331eab38 sent you a PR.

**Comment by forki** [comment]
yep. just reverted that thing. It's not correct. And the workarounf Paket will also fail on wildcards ;-(

**Comment by theimowski** [comment]
Should we revert then?

**Comment by forki** [comment]
could you please try with 0.33.15 - it uses colin's stuff from FAKE

**Comment by theimowski** [comment]
works fine, thanks

**Comment by colinbull** [comment]
Good too hear :+1:

**Comment by forki** [comment]
with https://github.com/fsprojects/Paket/commit/57a4455b3875cef3c8004fd7c6879d9a2a2a2ce9#diff-5850744305c961bd47fb58bd09062c26R329 applied it seems to work even for complicated stuff like: https://github.com/fsprojects/FsReveal/commit/18fcad53d02509a1dd826ca5e7af3ab305ad77f0#diff-38a9089c5d441003f1b29b8880065f07R15
