### ISSUE TITLE
Ignore *.*projs that do not look like MSBuild projects

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#70]
I have inherited a Git repository that contains a zreproj (no idea what it is) that is definitely not MSBuild. Paket fails to modify this file because it does not contain a Project node. Please ignore such files.

**Comment by szul** [comment]
@forki Hate to bring up a long dead issue, but I'm working on an IronPython project that uses a *.pyproj project file extension. Has there been any other movement/discussion on alternative project file extensions? I'd like to be able to have paket update this project file, but right now, I have to constantly change the extension back and forth to do so, it seems.

**Comment by forki** [comment]
Just grep for fsproj and csproj in the repo here and add your stuff in a
PR. Will be fastest way ;-)

Am 02.11.2017 20:54 schrieb "Michael Szul" <notifications@github.com>:
