### ISSUE TITLE
Multiple sources in dependencies file cause 404

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#706]
When using multiple sources, with authentication, like so:
```
source https://host.nuget/... username: "a" password: "xxx"
source https://other-host.nuget/... username: "b" password: "xxx"

nuget dependencyFromHost
nuget dependencyFromOtherHost 1.1.1
```

Only the first(dependencyFromHost) dependency is downloaded/updated. When switching the order then only the other one(dependencyFromOtherHost) will be downloaded.
When using `--force` both are updated.

**Comment by devboy** [comment]
Hmmm... also `--force` does not solve it all the time :(

```
mono .paket/paket.exe update --force
Paket version 0.35.0.0
found: .../paket.dependencies
Resolving packages:
 - dependencyFromHost
 - dependencyFromOtherHost 1.1.1
Locked version resolutions written to .../paket.lock
Paket failed with:
	Could not retrieve data from https://other-host.nuget/.../Packages(Id='dependencyFromOtherHost',Version='1.1.1')
 Message: The remote server returned an error: (404) Not Found.
```

**Comment by Vidarls** [comment]
Can you use something like fiddler to see if the http requests for the same host changes depending on the ordering of the sources?

**Comment by forki** [comment]
is there an easy repro sample for me?

**Comment by forki** [comment]
ping?

**Comment by forki** [comment]
please reopen if still not working
