### ISSUE TITLE
Better handling of paket dependencies from script files

### ISSUE THREAD

**Issue by ksuszka** [fsprojects/Paket#709]
I started to use F# as a scripting language - its concise syntax is ideal for scripting.
With introduction of [this](https://gist.github.com/moodmosaic/98e7884fde511bcf4eaa) trick it became really powerful.

However, there is a small issue. Consider following scenario. I have a single folder with multiple fsx scripts. Each script uses this trick. Every time I run one of them it overwrites paket.dependencies and paket.lock files with a different content.

[I've modified](https://gist.github.com/ksuszka/a1157df9c176afb2f6b5) original code to make a unique dependencies file for each script, however I still don't like it.

It would be great if we had public api with the dependencies file location decoupled from the packages folder.
Then we could make folder structure to look simliar to this:

```
+-- test1.fsx
+-- test2.fsx
+-- .fsx.dependencies
    +-- paket.exe
    +-- test1.fsx.dependencies
    +-- test1.fsx.lock
    +-- test2.fsx.dependencies
    +-- test2.fsx.lock
+-- packages
    +-- ...
```

The folder with scripts would not be poluted with helper files (in this scenario they are helper files as they are generated directly from fsx files).

**Comment by forki** [comment]
multiple dependencies files and lock files are not supported and I don't think they are a good idea.
Instead we should think about references files for fsx files.

**Comment by ksuszka** [comment]
I agree that direct support for fsx files would be much better. Till we have it, if I'm the only one with this problem, I can live with my current solution.

**Comment by matthid** [comment]
I think this solved since we have load scripts
