### ISSUE TITLE
Interpreting output of paket update

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#710]
```
$ paket update
Paket version 0.35.0.0
found: C:\blah\paket.dependencies
Resolving packages:
 - NServiceBus.Testing 5.0.4
 - NServiceBus 5.0.0
 - NServiceBus.Log4Net 1.0.0
 - Log4Net 2.0.0
 - NServiceBus.Host 5.0.3
 - Castle.Core 3.3.3
 - NServiceBus.RavenDB 2.1.0
 - RavenDB.Client 2.5.2956
 - FakeItEasy 1.25.2
 - GROSSWEBER.Infrastructure 1.5.2
 - Spark 1.8.0.0
 - Machine.Specifications.Runner.Console 0.9.0
 - Machine.Specifications.Should 0.7.2
 - Machine.Specifications 0.9.1
  Could not find compatible versions for:
     "NServiceBus >= 5.0.3 (from NServiceBus.Host 5.0.3)"
  Conflicts with:
  NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.Testing 5.0.4)
    NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.RavenDB 2.1.0)
 - Machine.Specifications 0.9.0
  Could not find compatible versions for:
     "NServiceBus >= 5.0.3 (from NServiceBus.Host 5.0.3)"
  Conflicts with:
  NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.Testing 5.0.4)
    NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.RavenDB 2.1.0)
 - Machine.Specifications 0.8.3
  Could not find compatible versions for:
     "NServiceBus >= 5.0.3 (from NServiceBus.Host 5.0.3)"
  Conflicts with:
  NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.Testing 5.0.4)
    NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.RavenDB 2.1.0)
... (more like this)
 - Castle.Core 3.2.0
  Could not find compatible versions for:
     "NServiceBus >= 5.0.3 (from NServiceBus.Host 5.0.3)"
  Conflicts with:
  NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.Testing 5.0.4)
```

As you can see there are several conflicts reported regarding NServiceBus.

Just to pick one:
```
 - Machine.Specifications 0.9.1
  Could not find compatible versions for:
     "NServiceBus >= 5.0.3 (from NServiceBus.Host 5.0.3)"
  Conflicts with:
  NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.Testing 5.0.4)
    NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.RavenDB 2.1.0)
```

[MSpec](https://www.nuget.org/packages/Machine.Specifications) doesn't have any relation to NServiceBus. The same is true for [Castle.Core](https://www.nuget.org/packages/Castle.Core). I wonder why they are reported next to each other.

**Comment by forki** [comment]
These lines are unrelated. Only the nservicebus stuff conflicts. Maybe we
should add a blank line or something to make this easier to read.

**Comment by agross** [comment]
OK, they look related because they're next to each other.

I wonder if we could report all conflicts at once, as the same/similar conflict is reported n times. Basically I see two different conflicts:

```
  Could not find compatible versions for:
     "NServiceBus >= 5.0.3 (from NServiceBus.Host 5.0.3)"
  Conflicts with:
  NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.Testing 5.0.4)
    NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.RavenDB 2.1.0)
```

```
  Could not find compatible versions for:
     "NServiceBus >= 5.0.3 (from NServiceBus.Host 5.0.3)"
  Conflicts with:
  NServiceBus >= 5.0.0 < 6.0.0 (from NServiceBus.Testing 5.0.4)
```

On top of that, what's conflicting here? `NSB.Testing` wants `NSB` in the `5.x` range, `NSB.Host` wants `NSB` `>= 5.0.3`. As far as I see the effective range for `NSB` would be `>= 5.0.3 < 6.0.0` then (where there is a NuGet [available](https://www.nuget.org/packages/NServiceBus)).

This is in my depfile:
```
nuget NServiceBus.Host ~> 5.0
nuget NServiceBus.Log4Net !~> 1.0
nuget NServiceBus.RavenDB ~> 2.0
nuget NServiceBus.Testing !~> 5.0
```

**Comment by agross** [comment]
OK, this was due to `nuget NServiceBus.Log4Net !~> 1.0`. Paket ties its dependencies to the oldest version (NuGet behavior), this basically pins `NSB` to `5.0.0`. I wish this was reported as well.

**Comment by forki** [comment]
IIRC ! doesn't pin, but changes the order

**Comment by forki** [comment]
as I expected:

    nuget NServiceBus.Host ~> 5.0
    nuget NServiceBus.Log4Net !~> 1.0
    nuget NServiceBus.RavenDB ~> 2.0
    nuget NServiceBus.Testing ~> 5.0

doesn't result in a conflict since `nuget NServiceBus.Log4Net !~> 1.0` doesn't pin. It#s just tracing intermediate conflicts, which forces the resolver to throw away some versions and try other versions instead.

i added a bit more logging info and moved this intermediate to the verbose mode.

**Comment by forki** [comment]
normal mode:

![image](https://cloud.githubusercontent.com/assets/57396/6769109/7945f52e-d08e-11e4-83ac-c360faef1570.png)

verbose mode:

![image](https://cloud.githubusercontent.com/assets/57396/6769122/dfee64c8-d08e-11e4-83bb-fac014fa573d.png)
