### ISSUE TITLE
How should redirects be created when a package contains different assembly versions for a single assembly?

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#711]
depfile:
```
nuget Sample
```

`Sample.nuspec` contains  `<dependency id="Spark" version="[1.8,2.0)" />`.

Spark 1.8.0 contains `lib\NET45\Spark.dll` which has
```
[assembly: AssemblyVersion("1.7.0.0")]
[assembly: AssemblyFileVersion("1.7.5.3")]
[assembly: AssemblyInformationalVersion("1.7.5.3")]
```

As far as I know the [version the CLR binds to is `AssemblyVersion`](http://stackoverflow.com/q/64602/149264), `1.7.0.0` in this case.

Paket generates this version redirect, though:
```xml
<dependentAssembly>
  <assemblyIdentity name="Spark" publicKeyToken="7f8549eed921a12c" culture="neutral" /> 
  <bindingRedirect oldVersion="0.0.0.0-1.8.0.0" newVersion="1.8.0.0" />
</dependentAssembly>
```

**Comment by isaacabraham** [comment]
Hmmm. We *use* AssemblyVersion to get the version used in the binding redirects file though. Are there other versions of the assembly in the nuget package, which have a different version perhaps? Maybe the binding redirects code is using one of those (incorrectly).

**Comment by agross** [comment]
WTF, you were right.

`lib\NET35\Spark.dll`: `1.8.0.0`
`lib\NET40\Spark.dll`: `1.8.0.0`
`lib\NET45\Spark.dll`: `1.7.5.3`

My project is 4.5. Seems like the redirects will break when you change the .NET version of your project. At least when package authors decide to use different version numbers for different platforms.

**Comment by agross** [comment]
It's alread reported. https://github.com/SparkViewEngine/spark/issues/54

**Comment by agross** [comment]
Question is, how would we handle such situations. Should we rather throw or warn and make it explicit that redirects will break than just picking any version?

**Comment by isaacabraham** [comment]
Yeah, the part of code that determines which version of the assembly to use to pull out the AssemblyVersion isn't aware of which version will ultimately be deployed by Paket. If that was added in, it then might just work.

**Comment by agross** [comment]
For sure. But only until you change e.g. from 4.5.1 to 4.0 without an additional `paket install`. :-)

**Comment by isaacabraham** [comment]
Could we do redirects that are framework-dependent I wonder?

**Comment by agross** [comment]
I'm not aware of app.config settings depending on the framework version. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by isaacabraham** [comment]
Not sure there's much we can do then unless we make a custom msbuild task?

**Comment by agross** [comment]
So redirects would be added at compilation time? Not sure it's worth the effort to work around this obvious bug in Spark. I'm not aware of other packages that deliberately use different version numbers for libs targeting different framework versions. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by isaacabraham** [comment]
I'm agree re: cost / benefit. Just pointing out what options are out there :-) Ok with closing this?

**Comment by forki** [comment]
Yes a warning would be good.

**Comment by agross** [comment]
Reopened because of suggested warning.
