### ISSUE TITLE
Detect dependencies for paket.template with files

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#716]
https://github.com/fsprojects/FsReveal/commit/7495609c50aa292651d5af22d76075e9656a8fe9#diff-38a9089c5d441003f1b29b8880065f07R22

^^ specifying this version seems wrong.

/cc @mavnn

**Comment by mavnn** [comment]
Any ideas on how to infer it?

**Comment by forki** [comment]
no actually not.
maybe we should use project template instead and allow additional files,

**Comment by Vidarls** [comment]
That's not supported? I'm using project templates with additional files on several projects to include localized satelite assemblies and file resources

**Comment by forki** [comment]
It's probably supported, but we should make that much clearer in the docs
