### ISSUE TITLE
Add references section to paket.template file

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#721]
NuGet nuspec allow to specify list of files that should be added to consumer project references (subset of files in `lib` folder), but `paket.template` does not support it now.

We need such functionality for Type Providers.
For example `RProvider`:
https://github.com/BlueMountainCapital/FSharpRProvider/blob/master/nuget/RProvider.nuspec#L21-L24

Package contains 5 assemblies:
- `RProvider.dll`
- `RProvider.DesignTime.dll`
- `RProvider.Runtime.dll`
- `RProvider.Server.exe`
- `FSharp.Core.dll`

but only two should  be referenced:
- `RProvider.dll`
- `RProvider.Runtime.dll`

We could not reference `RProvider.DesignTime.dll` because in this case we have no time to register `AssemblyResolve` event handler to redirect binding to `RDotNet.dll`. More details are [here](http://bluemountaincapital.github.io/FSharpRProvider/devnotes.html).

The same situation is in `DynamicsCRMProvider` I'm working on now.
https://github.com/fsprojects/DynamicsCRMProvider/pull/5

Would be nice to support this case in Paket. // @mavnn @forki

**Comment by forki** [comment]
someone already working on this?

**Comment by sergey-tihon** [comment]
Not me. Did it using Nuspec in `DynamicsCRMProvider`.

**Comment by forki** [comment]
could you please try to use Paket 0.36?

TODO: I forgot to add it to the docs.

**Comment by sergey-tihon** [comment]
It works. Thanks!
