### ISSUE TITLE
NPM link like functionality 

### ISSUE THREAD

**Issue by ryansroberts** [fsprojects/Paket#724]
http://justjs.com/posts/npm-link-developing-your-own-npm-modules-without-tears simplifies development of projects where you are also working on their dependencies by not requiring you to push and build a package before using it.

The npm implementation relies heavily on symlinks, which is not going to be appropriate for windows. 

Would it be practical to use an additional paket.link file alongside packet.dependencies that maps remote lookups to filesystem paths?

```
   nuget SomeDependency ==> ~/code/SomeDependency
   github ryansroberts/SomeProject ==> ~/code/SomeProject
```

These would then be checked before the actual dependency resolving gubbins kicks in and supply the package / file to be copied into the consuming project.

Could probably use some globbing to make it a little more forgiving than having to exactly specify the location of the local dependency. Possibly also append .gitignore, as it would be nasty if committed

**Comment by forki** [comment]
this sounds pretty interesting.

**Comment by sneal** [comment]
This would be a really great feature to have, we use it all the time in npm. One possibility for Windows is to use [mklink](https://technet.microsoft.com/en-us/library/cc753194.aspx) to simulate the same functionality.

**Comment by forki** [comment]
I wonder how this could work? If we link a project then we would need to make changes to the csproj file and the sln, right? we would also need to link transitive projects.

**Comment by matthid** [comment]
I think this is solved by `paket.local`? Please let us know if not.
