### ISSUE TITLE
Paket creates corrupt package (zip)

### ISSUE THREAD

**Issue by Vidarls** [fsprojects/Paket#729]
With a very specific file (that I am not allowed to put here) Paket.pack creates nupkg that give crc error when unpacked. Replacing that file after packing manually with somethign like 7 zip fixes the archive.

Simplest case I have been able to reproduce is file type template with single file content.

Are there any way I can get debug data to help figuring out this without publishing stuff I am not allowed to make public?

**Comment by forki** [comment]
I assume the only thing is to trust me and use email or something.

That said: maybe it's time to upgrade paket to newer .NET framework and use
the framework stuff to zip files.

**Comment by Vidarls** [comment]
Sent you an e-mail with the simplest possible repro. (and now everyone can create wonder what the super-secret file is..)

![mystery](http://1.bp.blogspot.com/-4N2wCeBk-6I/Tq948gW8gFI/AAAAAAAABBo/ZOCbxuocXdw/s1600/mystery.gif)

**Comment by forki** [comment]
IT IS A MYSTERY INDEED!
I got no mail.

**Comment by forki** [comment]
I can reproduce this bug with latest Paket, but #732 seems to fix it.
At least I don't get the CRC error any more. But #732 still has the issue that the package explorer can't find the metadata and I don't know why.

**Comment by forki** [comment]
should be fixed in 0.39 alpha

**Comment by Vidarls** [comment]
I can confirm that my original problem is now fixed
