### ISSUE TITLE
Support to update transitive nuget dependencies

### ISSUE THREAD

**Issue by dnauck** [fsprojects/Paket#738]
Please implement support to update transitive nuget dependencies via ```paket.exe update nuget transitive-package```

Currently this command executes but nothing happens.

**Comment by forki** [comment]
what does `paket outdated` give you?

**Comment by dnauck** [comment]
It shows that one of my transitive dependencies has a new version

**Comment by forki** [comment]
I tried the sample you sent me. I can't reproduce. Seems to work fine:

![image](https://cloud.githubusercontent.com/assets/57396/6916797/66bb3a64-d79f-11e4-940b-2de7667670a0.png)

**Comment by forki** [comment]
(It even removed the Octokit version,which we talked about)

**Comment by forki** [comment]
This was fixed.
