### ISSUE TITLE
paket install major performance degradation in version 0.38.0

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#739]
On my solution `paket install` runs for 39 seconds now, was - 2-3 seconds.
What's going on?

**Comment by forki** [comment]
mhm. maybe I broke something. do you know which version still worked?

**Comment by vasily-kirichenko** [comment]
My fault, it was the first time I run it after updating (it changed all the projects in my solution, so it took it such large amount of time). The subsequent runs are ok (7 seconds).
