### ISSUE TITLE
Support for branches?

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#741]
One thing that screws us up from time to time is switching between branches where different branches have different versions of dependencies and you forget to run paket install.

If you're lucky, when you switch, the "old" version will have a breaking API change so you'll get a compile time error. If you're unlucky, you'll run and maybe get a binding redirect error. If you're really unlucky, it'll continue to work and you'll just get the behaviour of the "old" version of the dependency.

I'm not sure what the solution to this problem is - maybe it's just inherent to the way that paket works i.e. versionless package folders?

**Comment by forki** [comment]
your build should do a restore. works fine for me from inside VS.

**Comment by isaacabraham** [comment]
you mean with the targets file?

**Comment by forki** [comment]
yep

**Comment by isaacabraham** [comment]
mmmm. And I guess if we do a build from cmdline e.g. Fake we could call Paket restore from there?

**Comment by isaacabraham** [comment]
Or would the msbuild target still work outside of VS?

**Comment by forki** [comment]
yep

**Comment by isaacabraham** [comment]
ok cool.
