### ISSUE TITLE
Failing download of license fails, package install fails also

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#743]
I just did "paket install --force" and with the package Albedo (indirect dependency for AutoFixture) the download of the license fails and then the whole process stops. 
First we should introduce a soft-fail for downloading licenses because this is really not important
Can also we introduce something like "license: no" for paket.dependencies file as well as for the dendency as well like we have it "redirects: on"

**Comment by forki** [comment]
I don't really think we should introduce `license no`, but yes the idea was that we just ignore license download errors. Did you already spot the issue? Otherwise I will try to take a look.

**Comment by Stift** [comment]
No. I'm currently on another workplace, but I try to make it work. I'll come back when I fixed it.

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/6936793/180d4a3a-d856-11e4-847e-b145934e079a.png)

this is what I get and would have expected. just a warning.

**Comment by Stift** [comment]
Yep. You are right. I did only see red glaring but this was an access failure on some directory. It was so close to each other, that I misinterpreted that. Please close that issue. Shame on me.
