### ISSUE TITLE
Nuget Package with no dependency gets no reference in csproj file

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#744]
I use the package `Blend.Interactivity.Silverlight` and it seems it has in its nuspec file no dependency definition. It seems that this is the reason why it got not added to the csproj file.
I would recommend to add it with
`
<Choose>
<When Condition="True">
...
</When>
</Choose>
`

**Comment by forki** [comment]
du you have the contents of the nuspec for me?

**Comment by Stift** [comment]
<?xml version="1.0"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
    <id>Blend.Interactivity.Silverlight</id>
    <version>2.0.20520.0</version>
    <authors>Microsoft</authors>
    <owners>Miguel</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Microsoft Expression Blend 4 includes new built-in behaviors, which are reusable pieces of packaged code that can be dragged onto any object, and then fine-tuned by changing their properties.</description>
    <summary>Microsoft Expression Blend 4 includes new built-in behaviors, which are reusable pieces of packaged code that can be dragged onto any object, and then fine-tuned by changing their properties. Behaviors allow you to add interactivity to your applications without having to write any code. The Behavior API consists of three core classes: Trigger, Action and Behavior. This SDK explores how to write each of these components, and contains a few code samples to help you get started. Programming reference topics are provided for Microsoft Silverlight. For more how-to and overview information about behaviors in Expression Blend, see the Expression Blend User Guide, available when you install Expression Blend 4.</summary>
    <language>en-US</language>
  </metadata>
</package>

**Comment by forki** [comment]
^^ seems there is something missing
is this the full file?

**Comment by Stift** [comment]
just corrected the markdown

**Comment by forki** [comment]
I can reproduce.

**Comment by forki** [comment]
should be fixed

**Comment by Stift** [comment]
Seems to work.
The following package is now working as well: LinFu.DynamicProxy.OfficialRelease.

**Comment by Stift** [comment]
This really saved me. Thanx.

![vffmfw3hhopco](https://cloud.githubusercontent.com/assets/1169723/6938559/a6c0974c-d864-11e4-8e51-87e1fc1dffa9.gif)
