### ISSUE TITLE
Paket deadlock since 0.38.0?

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#746]
Paket pretty much always deadlocks since 0.38.
The issue pops up as soon as you delete the cache and are on linux.

Repro:

```bash
git clone https://gist.github.com/d8653537d65775db669c.git
mono paket.bootstrapper.exe
rm -r ~/.local/share/NuGet/Cache
mono paket.exe -v restore # deadlock
# if you cancel the above and try again it will work
```

The last message seems to be different depending on the mono tracing flags. However is seems to be always near the FSharp.Compiler.Service License, after 2 previous 404 warnings.

I tried out the last few versions of Paket until the build started working again, see here: https://travis-ci.org/matthid/Yaaf.Shell/builds. I can repro this on my local gentoo machine as well.
Windows is not hit, as you can see here: https://ci.appveyor.com/project/matthid/yaaf-shell/history

Note it is also possible that the default timeout is >10 minutes (or longer on mono) and that's the reason why travis kills the process (I did not try to wait a day to see if it eventually finishes..)

Or this could be some mono race condition bug we should IMHO work around somehow, if possible.
That said: Can somebody reproduce this? Should I try to send a fix for this?

**Comment by forki** [comment]
yes please try to send a fix. we should cancel the license download after one or two seconds it's just not important enough.

**Comment by forki** [comment]
is 6d2f239 ready?

**Comment by matthid** [comment]
nope still testing

**Comment by matthid** [comment]
It looks like everything times out now with 5 secs on the async and 3 secs on the request.

**Comment by matthid** [comment]
But at least it doesn't fail anymore: See #747.
