### ISSUE TITLE
Could not resolve

### ISSUE THREAD

**Issue by petarvucetin** [fsprojects/Paket#748]
I am new to paket. Trying to convert current project  ```paket.exe" convert-from-nuget --force -v ```

I am getting resolution issues: 

    Could not resolve:
        - RavenDB.Embedded >= 2.5 < 3.0
             - from MyPrrojectOnLocalNuget 1.1.5.1
     Please try to relax some conditions. 

nuspec for MyProjectOnLocalNuget has this dependency:
```<dependency id="RavenDB.Embedded" version="[2.5,3.0)"/>```

**Comment by forki** [comment]
Closed?

**Comment by petarvucetin** [comment]
Closed. Still investigating...
