### ISSUE TITLE
Packet Pack for Silverlight projects outputs to lib\net40 instead of lib\sl40

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#751]
When using Packet Pack for a Silverlight 4.0 project using the following template:

type project
id TestProject
description
    Silverlight models for TestProject

Then the resulting nupkg has the binaries in lib\net40 instead of lib\sl40

**Comment by forki** [comment]
@mavnn how do we want to deal with this?

**Comment by mavnn** [comment]
We use ``Project.GetTargetFramework`` at the moment (see below). Is this a bug in GetTargetFramework, or does packaging need to provide it's own logic? I'm not clear if sl40 or net40 is the "correct" general response here.

https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PackageMetaData.fs#L138

**Comment by cjbhaines** [comment]
That's for the quick response! If you package using the official NuGet client it will place the files in "sl40". If you put the output of packet pack for a Silverlight project on a NuGet feed and try and install it to another Silverlight project it will fail with the following error messages because there is no "sl40" folder:

Install-Package : Could not install package 'TestProject 1.0.070.9617'. You are trying to install this package into a project that targets 'Silverlight,Version=v4.0', 
but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by forki** [comment]
@cjbhaines could you please post you fsproj /csproj file? I want to add an unittest.

**Comment by cjbhaines** [comment]
I sneakly renamed an actual production project to TestProject which I obviously can't publish. I have created a full example from scratch. Checkout the examples in the output folder.

https://onedrive.live.com/redir?resid=bb18e69b948ef2cb!9897&authkey=!AKTa3mOwLNgO-ZU&ithint=file%2czip

**Comment by forki** [comment]
could you please try 0.38.5?

**Comment by cjbhaines** [comment]
That's done the trick. Thanks a lot guys!
