### ISSUE TITLE
Paket ignores an fsproj

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#753]
Somehow, in a multi-project solution, when I try to add a reference, paket ignores a specific fsproj. Running the add command interactive lists all projects, but a specific one? Any ideas?

**Comment by forki** [comment]
Can you tell me how to reproduce that?

**Comment by forki** [comment]
(you could always edit the references file manually to get the stuff working)

**Comment by halcwb** [comment]
Ok, the thing is I first tried the manual method. That didn't work, i.e. the reference was not added. Then I tried the command line option, but because the reference was added to the paket.references file, of course the project was 'ignored'. So, that was my mistake. But still, when removing the reference from the references file, adding by the command line doesn't result in adding to the project references. I thought that was what should happen?

**Comment by forki** [comment]
Yes that should have happened. Is there a way for me to reproduce?

**Comment by halcwb** [comment]
I found what happened. Turned out that the required reference was conditional on the .net framework that was selected for the project. Only, somehow, there was no .net framework selected in the project properties. So, when I selected a .net framework, everything was fine.

Thanks for the quick reply.

**Comment by forki** [comment]
Mhm. Maybe we should default to something. Any ideas what framework nuget
would use?
