### ISSUE TITLE
convert-from-nuget: solution file in a subfolder

### ISSUE THREAD

**Issue by petarvucetin** [fsprojects/Paket#754]
![image](https://cloud.githubusercontent.com/assets/179653/7040156/7703aa64-dd80-11e4-85d0-da54b0e06520.png)

If solution is located in a sub-folder then running pakage convert-from-nuget does not seem to convert any projects and does not find packages folder.

It does create lock and empty dependencies files.

Here is the output from console.

	paket convert-from-nuget
	Paket version 0.38.6.0
	Removing C:\Development\Petar\Projects\ProjectX\src\Solution Files\.nuget\NuGet.Config
	Removing C:\Development\Petar\Projects\ProjectX\src\Solution Files\.nuget\NuGet.targets
	Dependencies files saved to C:\Development\Petar\Projects\ProjectX\src\Solution Files\paket.dependencies
	Solution C:\Development\Petar\Projects\ProjectDX\src\Solution Files\Project X.sln changed
	Downloading file from https://github.com/fsprojects/Paket/releases/download/0.38.6/paket.targets to C:\Development\Petar\Projects\ProjectDesignNinja\src\Solution Files\.paket\paket.target
	s
	Downloading file from https://github.com/fsprojects/Paket/releases/download/0.38.6/paket.bootstrapper.exe to C:\Development\Petar\Projects\ProjectDesignNinja\src\Solution Files\.paket\pak
	et.bootstrapper.exe
	Locked version resolutions written to C:\Development\Petar\Projects\ProjectDesignNinja\src\Solution Files\paket.lock
	Resolving packages:
	Locked version resolutions written to C:\Development\Petar\Projects\ProjectDesignNinja\src\Solution Files\paket.lock
	6 seconds - ready.

**Comment by forki** [comment]
which was the working directory?

Is this your structure?

    ./Project1
       p1.csproj
       packages.config
    ./Project2
       p2.csproj
       packages.config
    ./Solution Files
       Nuget.Config
       S1.sln

are you running paket in `./`?

**Comment by petarvucetin** [comment]
./Solution Files
      /.nuget
         NuGet.Config
         NuGet.targets
      S1.sln

I was using PM console window inside VS 2013.

**Comment by petarvucetin** [comment]
Running paket from command line inside "Solution Files" does not convert. Running it one folder up from Solution Files does work. It creates packages folder and all paket files inside the root folder. I would prefer to have all the solution related files go into its own folder.

**Comment by forki** [comment]
I assume paket is pretty opionated in this regard and follows https://github.com/fsprojects/ProjectScaffold. Currently the paket.dependencies and paket.lock are always in the root. 

Maybe this seems a bit restrictive but there are a couple of advantages and puts dependency handling where it belongs: directly into the sight of the devs. We don't want to hide this stuff from the users.

**Comment by petarvucetin** [comment]
Fair enough. I will check the ProjectScaffold guidance regarding C# projects. From my experiences no dev cares about it as long as it works.

Thank you for a fantastic tool!
