### ISSUE TITLE
Packet 0.39.0, using "." as target no longer works

### ISSUE THREAD

**Issue by neoeinstein** [fsprojects/Paket#756]
I have a Paket template that uses the specification:

```
files
    bin/Release/* ==> .
```

Prior to 0.39.0, using the . was a way to put the files at the root of a nupkg. (As is required for Octopus Deploy packages) Now this puts the files inside of a folder named `.`.

Alternates that I've tried include:
```
files
    bin/Release/* ==> 
```
But that just puts the files inside a folder with no name.

If this specification is no longer valid, is there an alternate way of specifying that the globbed files should be archived in the root?

**Comment by forki** [comment]
could you please check if 0.39.1 fixes this?

/cc @Vidarls @mavnn

**Comment by neoeinstein** [comment]
0.39.1 provides a viable workaround, namely using
```
files
    bin/Release/* ==> 
```
which is my preferred method of handling this. The special case for `.` still puts things in a folder named `.`. I'd either remove the special case and recommend using a blank string instead, or have `.` interpreted the same as a blank string.

I consider my issue closed, however.

**Comment by forki** [comment]
could you please retry with `.`?

**Comment by neoeinstein** [comment]
Looks good for `.`
