### ISSUE TITLE
Feature Request: NuGet.exe compatible 'pack' command

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#758]
It would be lovely if there was a NuGet-compatible Pack command built into paket; that way I could just take [this albacore configuration](https://github.com/Albacore/albacore/wiki/nugets_pack) and change the exe file to paket, and it would all just work!

**Comment by forki** [comment]
Could you please describe what you mean by this? I'm open for it, but just want to make sure we talk about the same thing.

**Comment by haf** [comment]
This is the invocation being made:

```
/tools/paket.exe Pack \
    -OutputDirectory /build/pkg \
    /src/JsonNet/Newtonsoft.Json.FSharp.nuspec
```

If Paket would support reading a nuspec file and taking 'OutputDirectory' just like NuGet.exe it would be a drop-in replacement.

Btw; current WIP ;):

![screen shot 2015-04-08 at 23 03 58](https://cloud.githubusercontent.com/assets/193115/7055436/945e529e-de43-11e4-8028-78c797ac9e4d.png)

**Comment by forki** [comment]
dude, we have to talk about your color scheme.

**Comment by haf** [comment]
Lol :hurtrealbad:

**Comment by mavnn** [comment]
@haf I deliberately decided against this as there are a lot of (sometimes pretty strange!) options available in nuspecs which I didn't want to support in the first release of a paket pack command.

You could argue whether this is a good decision, of course, but be aware that if we start accepting nuspecs we either have to:

* make the pack code quite a bit more complex  OR
* :boom: and die on quite a few valid nuspec files

Neither option fills me with that much joy :)

**Comment by haf** [comment]
I understand you point of view, but I would vote for a non-zero exit code for anything but the most basic nuspecs. In my sample, I have the easiest off-the-shelf nuspec possible.

**Comment by mavnn** [comment]
I'll leave that one to @forki to decide!

**Comment by matthid** [comment]
I think it still would make sense. Often times I still use `NuGet.exe` because of the low-level I access I get (and want).
This would allow me to use paket with the same low-level access.

**Comment by enricosada** [comment]
@haf now also `dotnet pack` has a different sintax.

so each tool has different configuration. this continue to make sense or can be closed?

**Comment by haf** [comment]
Yeah, this issue is not relevant any more. I spent a day re-coding the above for albacore, so the cost is sunk. Thanks for getting back to it.
