### ISSUE TITLE
Inconsistent error with restore--reference-files

### ISSUE THREAD

**Issue by halcwb** [fsprojects/Paket#762]
Using paket in a multiproject solution (42), I get inconsistent errors when trying to build the solution using Fake. When I perform the build manually directly from VS, everything runs fine. However, when using Fake, building the projects after each other or just using the solution file to build, sometimes it runs and exits OK, but mostly I run into the below sort of errors:

c:\Users\hal\Dropbox\Development\GenPres\.paket\paket.targets(36,5): error MSB3
073: The command ""c:\Users\hal\Dropbox\Development\GenPres\.paket\paket.exe" r
estore --references-files "c:\Users\hal\Dropbox\Development\GenPres\src\Informe
dica.Utils\paket.references"" exited with code 1. [c:\Users\hal\Dropbox\Develop
ment\GenPres\src\Informedica.Utils\Informedica.Utils.fsproj]
Running build failed.
Error:
Building c:\Users\hal\Dropbox\Development\GenPres\src\Informedica.GenPres.MvcWeb
\Informedica.GenPres.MvcWeb.csproj failed with exitcode 1.

The project with error can vary. So, there seems to be some sort of race condition in which the paket.references file is still locked by a competing restore-references process?

**Comment by forki** [comment]
mhm. yep I've seen this too. I'm not completely sure why this is happening.

In general I think paket should not be called during a FAKE compile target. We usually run the restore in a separate target at the beginning. I think we need to find a way to set https://github.com/fsprojects/Paket/blob/master/.paket/paket.targets#L5 to false during FAKE runs. This would probably also help @Thorium with #759

**Comment by forki** [comment]
https://github.com/fsharp/FAKE/pull/753 could work.

**Comment by halcwb** [comment]
@forki, thanks!
