### ISSUE TITLE
Access to path denied

### ISSUE THREAD

**Issue by yreynhout** [fsprojects/Paket#766]
From time to time I get an error while running ```paket install```

    Paket failed with:
        Access to the path 'C:\SomeProject\packages\Microsoft.Data.Services.Client\lib\portable-net45%2Bwp8%2Bwin8%2Bwpa' is denied.

**Comment by forki** [comment]
this happens when VS is locking files inside this folder. stuff like XML docs. Very annoying and also happens with nuget. There is a private issue in some microsoft issue tracker that apparantly nobody cares about (see https://github.com/Microsoft/visualfsharp/issues/57)
// @latkin

**Comment by yreynhout** [comment]
Bummer.
