### ISSUE TITLE
License not found

### ISSUE THREAD

**Issue by yreynhout** [fsprojects/Paket#767]
Not entirely sure if it's the root cause but when I took a dependency on Paramol 0.0.122 ```paket install``` failed with ```404 - Not Found``` (which is correct since in that version Paramol's nuget was pointing to a non existing license url). Is failure expected when the license can not be found?

**Comment by forki** [comment]
are you sure that this is the error? Paket should only warn (in yellow) if a license is missing. It should not fail.

**Comment by yreynhout** [comment]
I should add that paket was invoked from MSBuild. Might the paket return code 1 cause MSBuild to barf when ContinueOnError="false"?

**Comment by yreynhout** [comment]
@forki Correct, from the command line that is the observed behavior.

**Comment by forki** [comment]
> Might the paket return code 1 cause MSBuild to barf when ContinueOnError="false"?

what's that? can you fix it in https://github.com/fsprojects/Paket/blob/master/.paket/paket.targets ? ;-)

**Comment by yreynhout** [comment]
I'm not using auto-restore nor the paket.targets. I'm just using a simple Exec task to invoke paket. So in that case it will be my own code, euh, well, xml build file.
