### ISSUE TITLE
Wrong dependencies downloaded

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#775]
Hi,

I have a package 'A' v0.1.1, that depend on 'B', but previously depended on 'C'. Paket is downloading the wrong metadata, that of A v0.0.1, instead of v0.1.1; or the myget server is returning the wrong metadata; how do I inspect what 'call' paket has done that make it download that C is a dependency of A?

Can I toggle a verbose flag and see what data it gets back from what URL?

So I can narrow it down.

I've cleaned out packages/ and the cache. Downloading package 'A' manually shows it contains the right versions in the nuspec file. Paket still downloads an old version.

**Comment by forki** [comment]
let me guess: it's not on a public nuget server? ;-)

> Can I toggle a verbose flag and see what data it gets back from what URL?

nope, but that might be interesting. Currently I always break in the debugger if something like that happens. Let me see if I can add more verbose output at that point.

**Comment by haf** [comment]
That's right, it's MyGet again ;)

**Comment by haf** [comment]
Ok, so I added some debug code to Paket, and lo-and-behold, MyGet is returning faulty data...

**Comment by forki** [comment]
please try latest paket with - `-f -v`

**Comment by haf** [comment]
It seems myget is returning multiple results to this query:

`https://www.myget.org/F/logibit/Packages?$filter=Id%20eq%20%27My.Package%27%20and%20NormalizedVersion%20eq%20%270.1.1%27`

**Comment by forki** [comment]
summoning our MyGet guru @maartenba

are we missing something in Paket?

**Comment by maartenba** [comment]
Looking into it. Our expression tree rewriter seems to have missrd a beat.

**Comment by maartenba** [comment]
A fix has been deployed.

**Comment by haf** [comment]
I've verified the fix as well! Works now!
