### ISSUE TITLE
Doc section for readers used to Manage NuGet Packages dialog.

### ISSUE THREAD

**Issue by philderbeast** [fsprojects/Paket#778]
Looking at the [docs](http://fsprojects.github.io/Paket/), one thing that I don't see described is *how to switch* for users of nuget used  to the *Manage NuGet Packages* dialog of visual studio. How do I use paket with visual studio to do the equivalent of the following for a solution from within visual studio?

Manage NuGet Packages for Solution|Online|FSharp.Data|Install|Install the package in the following projects etc.

**Comment by forki** [comment]
Did you see http://fsprojects.github.io/Paket/paket-add.html?

**Comment by philderbeast** [comment]
I did and I tried it before raising this issue while working on https://github.com/fsharp/FAKE/issues/757. I don't think that someone coming to paket with only out of the box visual studio experience would be sure that project references can be managed this way. A lead into paket for those used to the builtin nuget dialog or the package manager console would be a good way to get started.

**Comment by forki** [comment]
The command line tool and the flat files work very well in practice. It was actually one of the design goals.

That said: https://github.com/hmemcpy/Paket.VisualStudio/tree/paket-intellisense by @hmemcpy is promising. but it needs volunteers.

**Comment by forki** [comment]
https://github.com/fsprojects/Paket.VisualStudio is now in the gallery
