### ISSUE TITLE
Paket Update is adding dependencies to paket.dependencies if specified in paket.references but not in paket.dependencies

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#779]
Paket version 0.41.3.

If you have a package referenced in paket.references and it doesn't exist in paket.dependencies it adds it without any version constraints. As far as I understand it, the paket.dependencies file should never be modified by Paket itself unless you do an add?

**Comment by forki** [comment]
Actually this is a feature. Requested by @haf and @agross  ;-)

**Comment by agross** [comment]
Really? I don't remember requesting that. Are you sure we're talking about *references* and *dependencies*?

**Comment by cjbhaines** [comment]
Yes, it definitely modifies my paket.dependencies file. That sounds extremely dangerous to me as it adds them without constraints. Can this be made opt in with a flag please as I'm fairly sure that most users will not want that enabled? This has broken a lot of my builds (it's partly bad configuration from us as we shouldn't reference stuff in paket.references that isn't in paket.dependencies so we are working on that).

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/issues/435#issuecomment-65946684 is what was suggested. @agross you were in that discussion so i thought you agreed ;-)

**Comment by forki** [comment]
ok. let's discuss how to make this configurable.

**Comment by cjbhaines** [comment]
There is a secondary problem here that it moves my sources around.

Original paket.dependencies:

source myinternalrepo
package..
package...

source officalrepo
package...


After update:

source myinternalrepo
source officalrepo
package..
package...
package...

**Comment by forki** [comment]
Please create a second issue

**Comment by cjbhaines** [comment]
https://github.com/fsprojects/Paket/issues/780

**Comment by agross** [comment]
It seems I didn't read @haf's suggestion entirely or didn't understand its consequences.


From my point of view, the only one who will modify paket.dependencies is either the user or paket add.





Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by forki** [comment]
Yeah it's basically like add. Consider the 1000 csproj-files solution from @Thorium - I don't really see a way to make this work without that. But I agree we should make that configureable and maybe even disabled on default.

**Comment by cjbhaines** [comment]
+1 for disabled by default :)

**Comment by agross** [comment]
Sorry, I don't see how automatically modifying the depfile "helps" with 1000 projects. You would need to modify 1000 references nonetheless.

**Comment by forki** [comment]
Nope what I meant is:

You have 1000 projects and you are working in 1. Now you want to use a nuget. How would you install it?

**Comment by agross** [comment]
`paket add nuget Foo project Bar`?

**Comment by agross** [comment]
Or manually (what I would probably do):

* Edit depfile adding `nuget Foo`
* Edit paket.references for Bar project
* `paket install`

**Comment by cjbhaines** [comment]
I usually go down the manual route as well. 

Also, would it make sense to fail the update in the case where you have something in references and not in dependencies? Obviously, if you enable the upcoming config option to fix the dependencies file instead it wouldn't fail.

**Comment by agross** [comment]
Yes, it should definitely fail when you paket.references something that's not in paket.dependencies!

**Comment by forki** [comment]
what about this:

We could you ask the user during install and let it fail if he doesn't want it. I think this could make everybody happy.

/cc @haf

**Comment by agross** [comment]
Not sure I'd be happy with that. I'd love the learn why @haf thinks adding deps automagically (even with explicit consent) is useful to him.

**Comment by agross** [comment]
Background: I want to limit the paths that you can take to add a dep. We currently have three:

* manual edit && paket install
* paket add nuget
* automagically adding from references

While 1 is absolutely crucial, and 2 is convenient, I feel that 3 is just a tad too magical for my taste.

**Comment by cjbhaines** [comment]
@agross, totally agree

**Comment by haf** [comment]
From the referenced issue, it's only point no 4 from https://github.com/fsprojects/Paket/issues/435#issuecomment-65948131 which this thread #779 is about - i.e. how should Paket react to adding new references through paket.references, rather than through paket.dependencies or paket add.

From [this comment](https://github.com/fsprojects/Paket/issues/435#issuecomment-65946684) it's only the first four paragraphs under the **install** heading I really care strongly about, not the fifth, which this thread is about.

I'd be open to this change.

The reason I created that thread in the first place is that I wanted paket install to 'just download and setup the fsproj files all-in-one' while update takes care to actually do version-levelling properly. Which wasn't the case before.

**Comment by forki** [comment]
so https://github.com/fsprojects/Paket/pull/781?

**Comment by forki** [comment]
please retry with 0.42

**Comment by cjbhaines** [comment]
Yep, all good now. Thanks for the quick response guys, I really appreciate it!
