### ISSUE TITLE
Paket Update messes with sources in paket.dependencies

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#780]
Original paket.dependencies:

source myinternalrepo
package..
package...

source officalrepo
package...

After update:

source myinternalrepo
source officalrepo
package..
package...
package...

**Comment by cjbhaines** [comment]
It also duplicates sources sometimes.

**Comment by forki** [comment]
could you define sometimes? With a concrete repro sample? Would love to fix it.

**Comment by cjbhaines** [comment]
Can I email you a project please?

**Comment by forki** [comment]
Sure sforkmann at gmail

**Comment by cjbhaines** [comment]
Actually this is fixed in 0.42.0, must be a side affect of https://github.com/fsprojects/Paket/issues/779

**Comment by forki** [comment]
It's not the only place where we save a dependencies file. The same thing happens if you run paket add

**Comment by cjbhaines** [comment]
Oh ok. In that case use packet 0.41.3 on the zip I will send you and you can see it in action.

**Comment by cjbhaines** [comment]
Getting a delivery failure, don't think gmail likes the zip. I uploaded it to my OneDrive account: https://onedrive.live.com/redir?resid=bb18e69b948ef2cb!9912&authkey=!AFuHFu_uOlLKWw0&ithint=file%2czip

**Comment by forki** [comment]
will try to fix after fsharpex

**Comment by cjbhaines** [comment]
Thanks!

**Comment by inosik** [comment]
#731 might be related to this.

**Comment by forki** [comment]
yes. I plan to fix both together - if possible.

/cc @matthid

**Comment by haf** [comment]
It duplicates any nuget it fails to add due to a connectivity problem. It duplicates sources for the same reasons - the source that fails most often.

**Comment by cjbhaines** [comment]
Hey guys, do you have any plans to fix this soon please? I'm having to spend a lot of time fixing my dependency files at the moment.

**Comment by forki** [comment]
I'm on it. but it's not trivial - the dependencies file representation needs redesign

**Comment by forki** [comment]
it's in 1.3.0-alpha001
