### ISSUE TITLE
How can I force wrong targetFramework?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/Paket#782]
If someone uses e.g. .NET 4.5.1 assembly to unit test Silverlight source code (yes, I know it sounds terrible, but it is possible), how could Paket be used to force wrong target framework for some reference? Now it creates this to csproj-files:

    <TargetFrameworkVersion>v4.5.1</TargetFrameworkVersion>
    
    <When Condition="$(TargetFrameworkIdentifier) == 'Silverlight'">
      <ItemGroup>
        <Reference Include="Microsoft.Practices.Unity.Silverlight">
          <HintPath>..\..\..\..\packages\Unity\lib\SL30\Microsoft.Practices.Unity.Silverlight.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>

...and the build fails because some Microsoft Unity-IoC -reference is not found. There is no corresponding .NET dll that would work. I can manually fix this by not referencing the dll through Paket, but what would be the correct solution? So that "paket install" wouldn't break the build?

**Comment by Thorium** [comment]
Or actually would be enough just to not generate When-condition at all, like in default dll-reference.

**Comment by forki** [comment]
So you want to reference the silverlight dll even in .NET 4.x?

Mhm. I think you need to manipulate manually and set the paket tag to false. This should tell paket to not mess with your changes

**Comment by Thorium** [comment]
Ok, I'll try that. Thanks.
