### ISSUE TITLE
Referencing unlisted packages should lead to a warning

### ISSUE THREAD

**Issue by AlexAtNet** [fsprojects/Paket#784]
I've added unlisted nuget package https://www.nuget.org/packages/System.Web.Http/ to the and the Paket  resolved it without any warning. Maybe it would be useful to display a warning if the referenced package is unlisted on nuget?

**Comment by forki** [comment]
I like that idea and I think it would be easy to add. ==> up-for-grabs

**Comment by forki** [comment]
this was merged.
