### ISSUE TITLE
We should be able to abort the bootstrapper 

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#789]
During @tpetricek's keynote we had the unfortunate situation that the download of paket.exe was taking a while.
Since @dnauck's latest pull request the bootstrapper downloads paket to a temp folder and only overwrites the existing paket.exe when the new one is available. 

So this what I'd like to see:
If we already have a version of paket.exe available then give the user a chance to cancel the download.

**Comment by Stift** [comment]
Ctrl+C does not work?

**Comment by forki** [comment]
Maybe it does and it's just a matter of tracing a line to make this visible
(when the file is already there).

Also it's important to only kill the bootstrapper and not the whole process

**Comment by Stift** [comment]
Got it. I'll try to take a look into that.

**Comment by forki** [comment]
Is this fixed? Do we have it in the docs?

**Comment by Stift** [comment]
Sorry, for the long waiting, but now it's done.

**Comment by Stift** [comment]
Could this be closed now?

**Comment by forki** [comment]
:kiss: 

thx

**Comment by forki** [comment]
ah. forgot to ask: do we have a bit of docs?

**Comment by Stift** [comment]
Thought about it, but did not find a good location. If yes, I would provide some. In the bootstrapper section below the options?

**Comment by forki** [comment]
yeah just some comment at
http://fsprojects.github.io/Paket/bootstrapper.html would be nice.

2015-06-08 23:07 GMT+02:00 Christian <notifications@github.com>:
