### ISSUE TITLE
Downgrading? - Awaiting better repro

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#794]
Install doesn't install specified version.

# Repro
## Step 1

```
source ..
nuget Chiron
```

`mono paket.exe install` - now 2.0 installed.

```
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    Aether (6.0)
    Chiron (2.0.0)
....
```

## Step 2

Now change paket.dependencies to: `nuget Chiron ~> 1.0.2`. Do `mono paket.exe install`. It lists all dependencies, but doesn't downgrade, nor say anything about Chiron.

**Comment by theimowski** [comment]
hmm i'm getting the following:

```
Paket version 1.0.1.0
Resolving packages:
Paket failed with:
        Could not find compatible versions for top level dependency:
     "Chiron >= 1.0.2 < 1.1.0 (from D:\SkyDrive\Dev\sandbox\Solution1\paket.dependencies)"
   Available versions:
     -
   Try to relax the dependency or allow prereleases.
```

if I do `nuget Chiron ~> 1.0` i get:

```
λ paket install
Paket version 1.0.1.0
Resolving packages:
 - Chiron 1.0.1
 - FAKE 3.0.2
 - Aether 6.0
 - FSharp.Core 4.0.0
 - FSharp.Core 3.1.2.1
 - FParsec 1.0.1
Locked version resolutions written to D:\SkyDrive\Dev\sandbox\Solution1\paket.lock
Downloading Chiron 1.0.1 to C:\Users\tomasz.heimowski\AppData\Local\NuGet\Cache\Chiron.1.0.1.nupkg
Chiron 1.0.1 unzipped to D:\SkyDrive\Dev\sandbox\Solution1\packages\Chiron
6 seconds - ready.
```

Have you tried `paket update`?

**Comment by haf** [comment]
No I haven't; is that the intended way to do it? So in that case, when does `install` **not** "just install what paket.dependencies specifies"?

**Comment by theimowski** [comment]
Have a look at #687. I guess @forki can better explain the exact behavior

**Comment by haf** [comment]
[this comment](https://github.com/fsprojects/Paket/issues/687#issuecomment-84030574) seems to suggest it's a bug, like I'm describing here

**Comment by theimowski** [comment]
Agreed, still I wasn't able to reproduce the issue

**Comment by haf** [comment]
Can you ensure you first can download v2.0.1 of Chiron? https://www.nuget.org/packages/Chiron/

Then try downgrading it through `install` cmd?

**Comment by theimowski** [comment]
yes I tried both: 
- `nuget Chiron` (downloaded latest, 2.0.1), install, then downgrade to `nuget Chiron ~> 1.0.2` and install
- pin 2.0 `nuget Chiron 2.0.0`, install, then downgrade to `nuget Chiron ~> 1.0.2` and install

In both cases I got paket reporting a conflict

```
Paket version 1.0.1.0
Resolving packages:
Paket failed with:
        Could not find compatible versions for top level dependency:
     "Chiron >= 1.0.2 < 1.1.0 (from D:\SkyDrive\Dev\sandbox\Solution1\paket.dependencies)"
   Available versions:
     -
   Try to relax the dependency or allow prereleases.
```

**Comment by haf** [comment]
I'm sorry, 1.0.1 is the v1 version.

**Comment by haf** [comment]
Let me create a better repro when I encounter this problem the next few days.

**Comment by theimowski** [comment]
sure

**Comment by forki** [comment]
I can reproduce

**Comment by forki** [comment]
mhm. I take that back. I messed with the `~>`.  I can't reproduce. My test allows to downgrade.
