### ISSUE TITLE
Support developmentDependency nuget dependencies

### ISSUE THREAD

**Issue by CumpsD** [fsprojects/Paket#796]
I just converted an existing project from Nuget to paket.

This project had a dependency on https://github.com/damianh/LibLog, which is a *developmentDependency*

When I produce a nuget package of the project, it includes LibLog as a regular dependency, while it should actually add no dependency to it.

Does paket support defining that a certain nuget package is a *developmentDependency* so it will not get included in the resulting *nuspec* from `paket pack`?

**Comment by forki** [comment]
I think I found a bit of docs at http://docs.nuget.org/Release-Notes/NuGet-2.7#development-only-dependencies.

So if I understand correctly we would need to understand the flag in dependent packages and just exclude it from the generated nuspec for the new package!?

/cc @adamralph

**Comment by theimowski** [comment]
regarding `convert-from-nuget` bits, the change will be trivial, just handle the developmentDependency in those places:
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NugetConvert.fs#L47-L51
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NugetConvert.fs#L185-L188

**Comment by forki** [comment]
I started to work on the feature

**Comment by forki** [comment]
<?xml version="1.0" encoding="utf-8"?>
    <feed xml:base="https://www.nuget.org/api/v2/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
      <id>https://www.nuget.org/api/v2/Packages</id>
      <title type="text">Packages</title>
      <updated>2015-04-23T15:46:55Z</updated>
      <link rel="self" title="Packages" href="Packages" />
      <entry>
        <id>https://www.nuget.org/api/v2/Packages(Id='LiteGuard.Source',Version='0.10.0')</id>
        <category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        <link rel="edit" title="V2FeedPackage" href="Packages(Id='LiteGuard.Source',Version='0.10.0')" />
        <title type="text">LiteGuard.Source</title>
        <summary type="text">The most simple, unambiguous and lightweight guard clause library. This is the source code package. Also available as a binary package (LiteGuard).</summary>
        <updated>2015-04-22T16:00:00Z</updated>
        <author>
          <name>Adam Ralph, LiteGuard contributors</name>
        </author>
        <link rel="edit-media" title="V2FeedPackage" href="Packages(Id='LiteGuard.Source',Version='0.10.0')/$value" />
        <content type="application/zip" src="https://www.nuget.org/api/v2/package/LiteGuard.Source/0.10.0" />
        <m:properties>
          <d:Version>0.10.0</d:Version>
          <d:NormalizedVersion>0.10.0</d:NormalizedVersion>
          <d:Copyright>Copyright (c) LiteGuard contributors. (liteguard.ch@gmail.com)</d:Copyright>
          <d:Created m:type="Edm.DateTime">2014-12-21T14:48:21.923</d:Created>
          <d:Dependencies></d:Dependencies>
          <d:Description>Why, it's lighter than air!&#xD; The aim of LiteGuard is to be the most simple, unambiguous and lightweight guard clause library available.&#xD; &#xD; Supported platforms: Desktop .NET 3.5+, Desktop Mono 3.2.8+, Windows 8+, Windows Phone 8.1+, Windows Phone Silverlight 8+, Silverlight 5+, Portable for Universal Apps (Profile32), Portable (Profile328).&#xD; &#xD; This is the LiteGuard source code package. Also available as a binary package (LiteGuard). If your project is an application or library which is not packaged and/or exported for use in other solutions then the binary package is usually the best choice. If you are writing a library which is packaged and/or exported for use in other solutions then the source code package is usually the best choice.&#xD; &#xD; After installing this package you may change the source code as required to match your coding conventions.&#xD; &#xD; We all have to do our bit in working toward the ultimate number of published guard clause libraries which, at current estimates, is somewhere in the region of 6.02214129(27) Ã— 10^23.</d:Description>
          <d:DownloadCount m:type="Edm.Int32">4664</d:DownloadCount>
          <d:GalleryDetailsUrl>https://www.nuget.org/packages/LiteGuard.Source/0.10.0</d:GalleryDetailsUrl>
          <d:IconUrl>https://raw.github.com/liteguard/liteguard/master/assets/liteguard_128.png</d:IconUrl>
          <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
          <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
          <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
          <d:Language m:null="true" />
          <d:Published m:type="Edm.DateTime">2014-12-21T14:48:21.923</d:Published>
          <d:PackageHash>PBRdKpqpP6vKWSAu1ysQ0GEAFQ/CMkXwzBN6QLT4FCmQLNNRQP9abv0twrZ/E/NeZDjQdaSmc2YAZXYs2jEmxQ==</d:PackageHash>
          <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
          <d:PackageSize m:type="Edm.Int64">13823</d:PackageSize>
          <d:ProjectUrl>https://github.com/liteguard/liteguard</d:ProjectUrl>
          <d:ReportAbuseUrl>https://www.nuget.org/package/ReportAbuse/LiteGuard.Source/0.10.0</d:ReportAbuseUrl>
          <d:ReleaseNotes>This release adds support for portable libraries for universal apps (Profile32) and fixes support for Windows Phone 8.1+.&#xD; &#xD; New: Support for portable libraries for universal apps (Profile32) - https://github.com/liteguard/liteguard/issues/94&#xD; Fixed: Does not compile for Windows Phone 8.1 projects - https://github.com/liteguard/liteguard/issues/94</d:ReleaseNotes>
          <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
          <d:Tags>guard clause arguments light avogadro</d:Tags>
          <d:Title>LiteGuard.Source</d:Title>
          <d:VersionDownloadCount m:type="Edm.Int32">371</d:VersionDownloadCount>
          <d:MinClientVersion>2.8</d:MinClientVersion>
          <d:LastEdited m:type="Edm.DateTime">2014-12-21T14:52:14.537</d:LastEdited>
          <d:LicenseUrl>https://github.com/liteguard/liteguard/blob/master/license.txt</d:LicenseUrl>
          <d:LicenseNames>MIT</d:LicenseNames>
          <d:LicenseReportUrl></d:LicenseReportUrl>
        </m:properties>
      </entry>
    </feed>

this is not part of the nuget odata, right?

**Comment by CumpsD** [comment]
This is where they originally implemented it: http://nuget.codeplex.com/workitem/1956

**Comment by forki** [comment]
I only implemented the part that we exclude these dependencies from the new nuget package. Please test it.

**Comment by adamralph** [comment]
@forki yep, that's the correct assumption. It just tells you whether or not to include the package as a dep when creating a package from your project.

**Comment by forki** [comment]
yeah, but it's really unfortunate that the data is missing in the OData metadata. It breaks our default assumption that we can look this stuff up while running update. Now we need to look into the nuspec which can only do after downloading the package.

**Comment by adamralph** [comment]
fugly :cry:

**Comment by CumpsD** [comment]
Bit late for my feedback, but it works, thanks :)
