### ISSUE TITLE
failed packet install is added to paket.dependencies

### ISSUE THREAD

**Issue by MorganPersson** [fsprojects/Paket#798]
I misspelled a paket install, I typed `paket add nuget faek` (instead of `paket add nuget fake`).
So the install failed with `Couldn't retrieve versions for faek` and it added `nuget faek` to `paket.dependencies`.
I would like paket to **not** add `nuget faek` to `paket.dependencies` when paket fails.

**Comment by Stift** [comment]
very nice. Happened to me several times.
:+1:

**Comment by MorganPersson** [comment]
@forki man you are fast. :+1:
