### ISSUE TITLE
Docs, say something of solutions and about relative folder hierarchy between them and projects.

### ISSUE THREAD

**Issue by philderbeast** [fsprojects/Paket#799]
On the Paket [home page](http://fsprojects.github.io/Paket/index.html) it mentions VS project files. Can we say something about whether paket considers solutions as well as projects and whether there are any assumptions or restrictions about the relative folder hierarchy between solutions and projects?

> You can place paket.references files alongside your Visual Studio project files to have Paket automatically sync references for the packages noted in that file whenever an install or update takes place.

**Comment by forki** [comment]
I'm open for additions. I'm not completely sure what you'd like to add.

**Comment by Stift** [comment]
I'm also not sure what you mean. Paket does not consider sln files, afaik. Would it be okay to mention something like that in the [FAQ](http://fsprojects.github.io/Paket/faq.html)?
