### ISSUE TITLE
Paket remove packages verion from folder name

### ISSUE THREAD

**Issue by silentnull** [fsprojects/Paket#803]
Hi,
When I add ex. ```Newtonsoft.Json``` packages from VS is created in packges directory subdirectory with packages name and version name ex. ```Newtonsoft.Json.6.0.8```, but Paket creates only folder with packages name. How I can resolve this problem ?

Pawel

**Comment by forki** [comment]
Ask VS team (+ NuGet team) to finally remove the version from the path.

Joking aside. Getting rid of the version number from the path was one of the major design goals. You can read about it in http://fsprojects.github.io/Paket/faq.html#NuGet-puts-the-package-version-into-the-path-Is-Paket-doing-the-same.

**Comment by davidfowl** [comment]
Is the big reason fsx files or just a general one version per solution POV?

**Comment by forki** [comment]
Actually both. fsx is only one instance of the issue that NuGet file names are not stable. You have the same issue in docs and lots other places. Just think of all the git diffs when you update packages.

**Comment by forki** [comment]
https://twitter.com/jeremydmiller/status/593761400511660032

**Comment by davidfowl** [comment]
Sure I understand the problems it causes but those problems are more about burning paths into things other things (like the project file), not the folder layout. 

IMO there's 2 ways to solve this problem:

- Remove versioning from folders that are local to something (solution or project). That enforces a single version per project/solution/{whatever you want to make the unit of version unification}. Benefit is that you don't have to update anything else to understand NuGet.
- In NuGet v3, we've been changing different places to understand NuGet instead. The benefit here is that we can do things like store packages globally, but still have (id, version) pointers in each projects, that get resolved to the right place at the right time (build time for example).

Anyways I was just curious. Thanks.

**Comment by forki** [comment]
BTW: the desire to remove the version from the path came from the C# community. But of course it fits with all we do in the F# ecosystem.

> Benefit is that you don't have to update anything else to understand NuGet.

There are so many things we can't control/change. 

> That enforces a single version per project/solution

Which is almost always what we want. We want to make conflicts obvious.

**Comment by isaacabraham** [comment]
@davidfowl given that NuGet is essentially the defacto package management system in the .NET world, there's also been a long-standing request from the F# side to allow referencing NuGet packages rather than individual assemblies e.g. ```#nuget "Newtonsoft.Json"```.

This fits with the sorts of things you're talking about, but I don't see this happening any time soon personally.

**Comment by davidfowl** [comment]
Yep it's tough changing all the places so I understand. We're still going in his direction though.

**Comment by isaacabraham** [comment]
FWIW I think its a good thing to do.
