### ISSUE TITLE
We have binding redirects for nunit in Paket console application

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#806]
while we don't have them for `Paket.Tests` project - does the `--redirects` option for `paket install` handle different packages in different projects?

/cc @isaacabraham

**Comment by isaacabraham** [comment]
It is pretty crude, as far as I remember it just supplies the redirects for all packages across all projects. Even if the project doesn't use a specific redirect (this is harmless though).

However, if there is no config file in the tests project you must create one first - the BR code won't do that automatically.
________________________________

**Comment by theimowski** [comment]
I see, maybe we could, as an enhancement, create new `app.config` file, as well as limit the redirects to the ones referenced by project only?

**Comment by isaacabraham** [comment]
yes, could do both - can you create issues for both of them?

The first one does make me think though how we would identify this though e.g. create <x>.config for every .csproj / .vbproj / .fsproj? Only exes? websites? etc. etc.?

The second one is definitely doable, probably just a bit of work to expand the current code to supply a different set of BRs for each project.

**Comment by theimowski** [comment]
ok closing this in favor of the new ones
