### ISSUE TITLE
Create app.config file if it's missing and binding redirects requested

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#808]
Extracted from #806
I think create app.config for every project that has its corresponding references file would do the job

/cc @isaacabraham

**Comment by davidfowl** [comment]
Does packet work in ASP.NET 4.x projects as well? What about web.config?

**Comment by isaacabraham** [comment]
I'm on this one now.

**Comment by isaacabraham** [comment]
I've done the main work of creating an app.config and associated BRs in it - is there an easy example somewhere of how to add a file reference to a cs/fs/vb proj file somewhere in the source?

**Comment by pavelhritonenko** [comment]
Hm... but I don't need app.config for my class libraries. Actually I need it only for assemblies with entry point and for tests assemblies.

Furthermore, for FSharp projects app.config should be included with Build Action = Content otherwise it will cause unwanted rebuilds of this project.

**Comment by forki** [comment]
@isaac_abraham could you please look into this?

**Comment by isaacabraham** [comment]
How do we identify unit test projects? This was actually the differ behind this change I.e. Allow unit tests to run properly.

You're right about content, that should have been done originally.

**Comment by isaacabraham** [comment]
Hmm, just checked - newly added config files *are* added as Content files.

**Comment by pavelhritonenko** [comment]
> How do we identify unit test projects?

I added myself app.config for all project where it is needed and I just don't want that paket do it for me.

**Comment by dzendras** [comment]
+1 for paket not adding app.config files.

In my setup, config files are generated during the build (from some other config files) and copied to app.config. Therefore app.config is always a derived thing and is not even added to my *.csproj files.
I'd go mad if running paket would recreate and readd this file to my project.

So if you consider doing so, please make it an optional feature.

**Comment by forki** [comment]
it's aöready optional.
