### ISSUE TITLE
Binding redirects - create entries only for applicable binaries for a project

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#809]
Extracted from #806 

/cc @isaacabraham

**Comment by davidfowl** [comment]
Worth noting that msbuild has a feature to generate binding redirects.

**Comment by isaacabraham** [comment]
Mmmm. Worth investigating that then - what is in Paket works but if we can easily offload that to a known good component I'd be happy to do that.

**Comment by forki** [comment]
@davidfowl does this work from command line? even on mono? any pointers? 
thanks.

**Comment by davidfowl** [comment]
https://msdn.microsoft.com/en-us/library/2fc472t2(v=vs.110).aspx

https://github.com/Microsoft/msbuild/blob/82177a50da735cc0443ac10fa490d69368403d71/src/XMakeTasks/AssemblyDependency/GenerateBindingRedirects.cs

Mono and xbuild? My first guess would be no but they are porting msbuild to be xplat via mono so who knows :smile:
