### ISSUE TITLE
Inconsistency when calling install and update

### ISSUE THREAD

**Issue by dzendras** [fsprojects/Paket#810]
I found an extremely annoying behaviour of paket (tested against versions 0.42 and 1.3.0)
I have a project which has only one dependency: a nuget package FSharp.Data 2.0.14. The dependency was properly installed, added to the project file, dll downloaded to packages directory. So everything works.

What I expect now is that calling a sequence of commands: update, install, update, intall, update etc. should not change anything at all (as the version is fixed). Unfortunately paket falls into an infinite loop of changes:
1. paket update - modifies csproj file and paket.lock file.
2. paket install - discards changes introduced previously by modifying csproj and lock file.
3. paket update - restores the state of csproj and lock files from the 1st step (by discarding changes made in the 2nd step)

and so on...

I have a sample solution which I'm more than happy to send you for analysis.

![paket1](https://cloud.githubusercontent.com/assets/7687934/7430115/e8e49642-f005-11e4-9deb-88897492ecf9.png)

which turns into:

![paket2](https://cloud.githubusercontent.com/assets/7687934/7430116/e8e5b888-f005-11e4-9184-f4e046e23361.png)

**Comment by dzendras** [comment]
Similar behaviour can be observed with another nuget package: Microsoft.AspNet.WebApi

**Comment by forki** [comment]
Yes please send me the sample to sforkmann at gmail - I will try to fix it.

**Comment by dzendras** [comment]
I've just sent it. Good luck! :)

**Comment by forki** [comment]
fixed in 1.3.1 - please give it a try

**Comment by dzendras** [comment]
I did check the repro I sent you using version 1.3.3. There the last paket command ran was install. After I ran update I did modify the lock and csproj file again (why?). However when I ran install afterwards, none of the files were modified (good!). Running update again did nothing (good!).

Unfortunately I was able to reproduce the problem using a different dependency.
I can send you another repro.

**Comment by forki** [comment]
Yes the version that update generates is the correct one. So it's expected
that update "wins" and install doesn't change it.

Please send the other repro

**Comment by forki** [comment]
I think I fixed your latest repro in 1.3.4

**Comment by dzendras** [comment]
Confirmed! Thanks! :)
