### ISSUE TITLE
Bootstrapper to get paket.exe from NuGet.org if GitHub is down.

### ISSUE THREAD

**Issue by Thorium** [fsprojects/Paket#815]
Bootstrapper takes paket.exe from GitHub. But today GitHub has been down. So Bootstrapper could also try NuGet. If NuGet is down, then the whole build probably fails.

**Comment by forki** [comment]
The latest bootstrapper should do this

**Comment by Thorium** [comment]
Great, that was fast!

**Comment by dnauck** [comment]
Hi, 

this is already implemented in the latest release. 

Am 6. Mai 2015 14:02:03 MESZ, schrieb Tuomas Hietanen <notifications@github.com>:
>Bootstrapper takes paket.exe from GitHub. But today GitHub has been
>down. So Bootstrapper could also try NuGet. If NuGet is down, then the
>whole build probably fails.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fsprojects/Paket/issues/815

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
