### ISSUE TITLE
Expose a public function that gives all package feeds from the machine

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#820]
@hmemcpy likes to use a function which gives all configured feeds as specified in
![feeeds](https://cloud.githubusercontent.com/assets/57396/7532491/a1c741e4-f567-11e4-89db-610e611800a5.png)

this would help to build autocomplete for VS addin for "source ..." in paket.dependencies files.

@theimowski we already have this under the covers in the conver-from-nuget stuff right? What's the easiest way to expose this in PublicAPI.fs?

**Comment by theimowski** [comment]
here is the function that does that: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NugetConvert.fs#L163

It goes through each config file and discovers feeds as defined here:
https://docs.nuget.org/consume/nuget-config-file

**Comment by forki** [comment]
like this: https://github.com/fsprojects/Paket/commit/8fb3d9c4205a867a4b4cb7e6dcdb82539e414d0c#diff-e2d8853e618aeb3b7f2e3821dd1ddb33R244 ?

**Comment by theimowski** [comment]
Just wondering now - in case this functionality is meant to work for Paket-based codebases, then maybe exploring just  %AppData%\NuGet\nuget.config would do the job? I mean if one uses Paket, then probably he won't have `nuget.configs` in his working directory anyway?

Exploring `nuget.config` files recursively as described at the nuget docs is necessary in context of `convert-from-nuget`

What you think?
Also, is it ok to expose the `Auth` type to the outside world?

**Comment by forki** [comment]
Yeah we shouldn't expose auth. 
Regarding local nuget.config files. It does no damage the way it is, right?

**Comment by theimowski** [comment]
probably not that big harm, however I can remember there was an issue where someone had a `nuget.config` file hanging around in `../..` dir resulting in adding unwanted source in dependencies file.

**Comment by forki** [comment]
Yeah but here it's only for completion...

**Comment by hmemcpy** [comment]
I just wanted to add my €0.02 that if this is only for completion/VS, than perhaps I could do this in the plugin, no need to "pollute" Paket with it.

**Comment by forki** [comment]
Yeah but other addins will use it, too. It's useful.

**Comment by theimowski** [comment]
ok then it seems fine

**Comment by forki** [comment]
And it will allow us to refactor internally without breaking plug-ins

**Comment by hmemcpy** [comment]
SGTM then :)

**Comment by forki** [comment]
-    member this.GetDefinedNuGetFeeds() : (string * Auth option) list = 
+    member this.GetDefinedNuGetFeeds() : string list = 

done.
