### ISSUE TITLE
Installing by adding to .references

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#822]
It was possible to install new packages with two steps:

1. Add a relevant line to a `paket.references`
1. Run `paket install`

With latest version (1.4.1) this doesn't work and I get an error saying `Paket failed with: Package X was referenced, but it was not found in the paket.lock file.`

Is this by design or a by-product of another issue. #779 maybe?

**Comment by forki** [comment]
Yes it was decided that this feature is confusing for most devs. We removed
it.
But we already added similar feature to new tooling in atom editor and I
assume we will do the same later in the vs addin.

**Comment by tpluscode** [comment]
That's unfortunate, because I liked that way. I will explore the add-in. Thanks
