### ISSUE TITLE
Adding a github link with custom folder adds a linked file

### ISSUE THREAD

**Issue by rojepp** [fsprojects/Paket#823]
This is fine for .fs/.cs files, but for web content files I think the file should be copied to the specified output folder. I was reading [docs](http://fsprojects.github.io/Paket/github-dependencies.html) but I couldn't find a way to do this?

**Comment by forki** [comment]
I assume we need options for FILE references too.

How about:

    File:ErrorHandling.fs . link:false
    File:Globbing.fs .  link:true  // default

/cc @agross @theimowski @mexx

**Comment by theimowski** [comment]
Can't be just "Copy To Output Directory" option set? I think we deliberately chose to link all files to discourage modifying

**Comment by forki** [comment]
so would this be better?
 
    File:ErrorHandling.fs . copy_local:true
    File:Globbing.fs .  copy_local:false  // default

@rojepp would that work?

**Comment by forki** [comment]
if fileItem.CopyLocal then addChild (this.CreateNode("CopyToOutputDirectory","Always")) node else node

**Comment by rojepp** [comment]
I'm not sure if that would work. In a web project, there really is no 'output directory'. Content files are just supposed to be there. Copy_local is maybe a bit too MsBuild specific. Either just let me place the downloaded file where I want instead of in paket-files, or implement all of the MSBuild content types. :)

**Comment by forki** [comment]
so `link:false` would be better?

**Comment by rojepp** [comment]
For me, yes. I'm sure there are also cases where CopyLocal would be preferable.

**Comment by forki** [comment]
then we start with that

**Comment by forki** [comment]
Paket 1.13.0-alpha002 has support for link:false in references files.
Could you please give it a try?

**Comment by matthid** [comment]
I guess this can be closed?
