### ISSUE TITLE
`paket pack` fails when assembly uses attribute defined in other assembly.

### ISSUE THREAD

**Issue by dmitryvk** [fsprojects/Paket#827]
See example C# solution: https://github.com/dmitryvk/PaketPackExample

I have a 2 projects: project `ClassLibrary1` defines custom attribute, and project `PaketPackExample` attaches this attribute to the output assembly. I'm trying to pack the `PaketPackExample` as nuget package and I'm getting the following output:

```
$ /c/users/user/Downloads/paket pack output build buildconfig Debug
Paket version 1.4.13.0
Loading custom attributes failed for PaketPackExample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
Message: Could not load file or assembly 'ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one o
f its dependencies. The system cannot find the file specified.
Paket failed with:
        Could not load file or assembly 'ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of
 its dependencies. The system cannot find the file specified.
```

If I comment out the following line from `PaketPackExample/Properties/AssemblyInfo.cs`:
```
[assembly: ExampleCustom]
```
then `paket pack` produces nuget package.

The problem seems to be that `GetCustomAttributes` tries to load assemblies that define custom attributes (and `GetCustomAttributesData` seems to do the same).

With `--verbose` the output is as follows:
```
$ /c/users/user/Downloads/paket pack output build buildconfig Debug --verbose
Paket version 1.4.13.0
found: c:\bars\code\git\PaketPackExample\paket.dependencies
Parsing c:\bars\code\git\PaketPackExample\paket.dependencies
Loading assembly metadata for c:\bars\code\git\PaketPackExample\PaketPackExample\bin\Debug\PaketPackExample.exe
Loading custom attributes failed for PaketPackExample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
Message: Could not load file or assembly 'ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one o
f its dependencies. The system cannot find the file specified.
Paket failed with:
        Could not load file or assembly 'ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of
 its dependencies. The system cannot find the file specified.
StackTrace:
     at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount
, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInsta
ntiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethod
Arguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope
, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilte
rType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMeth
odInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken,
 Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecorate
dTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Boolean inherit)
   at Paket.PackageMetaData.loadAssemblyAttributes(Assembly assembly)
   at Paket.PackageProcess.merged$cont@55(String buildConfig, TemplateFile templateFile, ProjectFile projectFile, Option
alPackagingInfo opt, ProjectCoreInfo md, Unit unitVar)
   at Paket.PackageProcess.f@1-97(String buildConfig, FSharpOption`1 version, HashSet`1 allTemplateFiles, ProjectFile pr
ojectFile, TemplateFile templateFile)
   at Paket.PackageProcess.Pack(DependenciesFile dependencies, String packageOutputPath, FSharpOption`1 buildConfig, FSh
arpOption`1 version, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile)
   at Paket.Dependencies.Pack(String outputPath, FSharpOption`1 buildConfig, FSharpOption`1 version, FSharpOption`1 rele
aseNotes, FSharpOption`1 templateFile)
   at Paket.Program.clo@268-26.Invoke(ArgParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] ar
gs)
   at Paket.Program.processCommand@71-1.Invoke(Command command, String[] args)
   at <StartupCode$paket>.$Paket.Program.main@()
```

**Comment by forki** [comment]
ouch. 

/cc @mavnn any ideas how to solve this?

**Comment by dmitryvk** [comment]
I've tried to find out a way to get custom attributes - but even using ReflectionOnlyLoad & GetCustomAttributesData tries to load assembly.
Maybe using Mono.Cecil instead of reflection would help?

**Comment by mavnn** [comment]
I don't have any immediate ideas, no. Like @dmitryvk my impression is that the whole attribute loading process is pretty brittle.

Something like Cecil might be able to help. I also can't remember from the API whether it's possible to ask for each of the relevant attributes by name and catch the exception for ones it can't find - that might work around the problem.

**Comment by forki** [comment]
summoning @dnauck - ideas?

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/7706922/73f5fdc0-fe4d-11e4-8cd4-4f68b3710693.png)

ok I can reproduce on Windows. so this is not a mono issue.

**Comment by forki** [comment]
let x = assembly.GetCustomAttributes(typeof<AssemblyDescriptionAttribute>,false) 

fails too. So retrieving only the specific attributes won't work.

**Comment by forki** [comment]
I might have a "fix".

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/pull/828 seems to work, but please review

**Comment by forki** [comment]
@dnauck said it doesn't work on his mac.

**Comment by dmitryvk** [comment]
Also, assembly loading might fail for different reasons - e.g., incompatible versions (different framework versions), different endianness (trying to pack 32-bit assemblies from 64-bit process).

**Comment by forki** [comment]
yes I'm open for improvements ;-)
Maybe we need to get rid of it alltogether and try to get the information wiht different techniques

**Comment by mavnn** [comment]
@forki I'd be a bit reluctant to drop this technique, as it potentially means a much larger effort in doing NuGet conversions. There is also already the option of putting the information in the paket.template file, so there's no "requirement" to use the attribute values.

Having said that, we should at the very least document the limitations, and I'm more than happy to brainstorms way it could be made more reliable.

**Comment by forki** [comment]
No I don't think we should get rid of extracting info. But maybe we can find a different way.

**Comment by mavnn** [comment]
In theory there is a well defined metadata table in the DLL that we could
extract from the raw binary data (i.e., not loading the assembly as an
assembly at all). Unfortunately I don't really have the time to dig into it
- which is a pity, as it looks like it would be quite a fun project.

**Comment by forki** [comment]
@dimitryvk did it at least solve your issue?

**Comment by dmitryvk** [comment]
I've not yet checked - but will do shortly.

**Comment by dmitryvk** [comment]
I confirm that the issue is fixed (tested on Windows 7, .net 4.5.1, paket 1.5.0-alpha001).
