### ISSUE TITLE
`paket install` fails if package version doesn't match .nupkg file

### ISSUE THREAD

**Issue by amazingant** [fsprojects/Paket#834]
While working on #832, discovered that if a nuget-installed package (in this case, it was [`MvvmLightLibs` version 5.0.2.0][1], which doesn't seem to be on NuGet.org anymore?) is in `packages.config` with the full version number, but the `.nupkg` file has a partial version number, it fails to download/install that package.

In my case, the package is stored in a local package source on a mapped drive pointing to a team network share (same one as my "help, there's spaces in my path" issues), and the `packages.config` file contains `<package id="MvvmLightLibs" version="5.0.2.0" targetFramework="net40" />` referring to the package.

When running `paket install` it fails with `Could not find file 'N:\Package Source\Here\MvvmLightLibs.5.0.2.0.nupkg'.`, and verifying that directory, it contains `MvvmLightLibs.5.0.2.nupkg` as downloaded from nuget.org previously. Updating all `paket.dependencies` and `paket.lock` files to show the version as `5.0.2` and running `paket install` again results in correctly downloading and unpacking everything.

[1]: https://www.nuget.org/packages/MvvmLightLibs/

**Comment by forki** [comment]
Ok this one is tricky. But I assume we can apply the NormalizeVersion before we convert the package version in the dependencies file. This will remove the trailing 0 and is the safer choice. At least I think it is. 

/cc @theimowski

**Comment by theimowski** [comment]
Yes but how about the opposite? If we normalize but the nupkg file name has trailing zeros?

**Comment by amazingant** [comment]
Not that I want to seriously suggest doing what NuGet does, but looks like `NuGet.LocalPackageRepository.GetPackageLookupPaths()` checks a handful of different versions of the file path to see what does(n't) exist: https://github.com/mono/nuget/blob/d129831d6fa1c7e3c83b520b877a273c636e120e/src/Core/Repositories/LocalPackageRepository.cs#L166-L199

**Comment by forki** [comment]
Actually I thought I fixed the issue in the resolver. The problem is that not not every source feed behave the same in regards to trailing zeros.

**Comment by forki** [comment]
this is happeing with local nuget feed (directory), right?
can you run it with -v?

**Comment by forki** [comment]
Could you please try latest version

**Comment by amazingant** [comment]
Remoted into my work machine and gave it a try, works great! Thanks, @forki :smile:
