### ISSUE TITLE
Override 'copy_local' in 'paket.dependencies' with values from 'paket.references' in projects

### ISSUE THREAD

**Issue by WebDucer** [fsprojects/Paket#836]
Helo.

We often build all projects of a solution to a common output directory. So we would like not to copy the nuget references with every project again and again.

So we deactivate 'Copy Local' by default in our projects. Only the project that has the major use of the package, set 'Copy Local' to true (in most cases the the adapter/proxy project).

I tried to rebuild this behaviour with paket, but without success.

In `paket.dependecies` is `copy_local` set to false. In the adapter project one of the nuget references in `paket.references` is set with `copy_local` to true. In all projects 'Copy Local' is set to false.

**paket.dependencies**
```
source http://localhost:8081/nexus/service/local/nuget/NugetPublic/  // Nexus

framework: net45
copy_local: false

# Libraries
nuget Prism ~> 5.0
nuget Prism.PubSubEvents ~> 1.0
nuget Prism.UnityExtensions ~> 5.0
```

**paket.references**
```
Prism.PubSubEvents copy_local: true
```

**Comment by forki** [comment]
please try 1.5.1 - I still have to cleanup the mess I did with the commit, but I want to get feedback if it works.

**Comment by WebDucer** [comment]
Helo.

I tested with the version 1.5.6 today. It doesn't work for me. As soon as I declare `copy_local:false` in `paket.dependecies` the flag is `FALSE` in all projects, no matter if the reference in `paket.references` is set to `TRUE`.

**Comment by forki** [comment]
Ok will check again

**Comment by forki** [comment]
Oups that helped me to discover a bigger issue. Thanks for reporting.
It works for me now with 1.6 when I do "paket install"

**Comment by WebDucer** [comment]
Now it works! Tested today with 1.6.2.

Thanks a lot.
