### ISSUE TITLE
Managing .Net framework references through Paket.

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Paket#840]
The idea is to extend Paket with way of managing .Net framework references through it. It would help workflow in non-VS / XS environments.

In IDE style editors there is no problem with adding new references to project - there are nice wizards to do so. (Un)Fortunately such behavior ( wizard) is not inline with other text editors - at this moment users not using VS/XS are required to make "by-hand" editions of project files to add new .Net references. 

It would be nice to have possibility to say in `paket.references` file "I want `System.Drawing` in this project" and put on Paket responsibility of adding this reference to project file

**Comment by forki** [comment]
do you only want to have it in paket.references? Not in the dependencies file?

**Comment by Krzysztof-Cieslak** [comment]
Is there a need of doing it in `dependencies` file? As I understand it's used to ensure one version on solution level. .Net references version is resolved by MSBuild based on targeted .Net version, so I don't see any reason to add .Net references in  `dependencies` file.

Of course my Paket understanding is not as good as You so maybe there are some good reason to add it also to `dependencies` file.

**Comment by forki** [comment]
no there is no real requirement since we don't manage versions for this.

**Comment by forki** [comment]
I thought about it and in the spirit of a "global" dependencies view I think we should put it into dependencies file. I also want to plain dll references. That would work similar

**Comment by forki** [comment]
could you please come up with some fantasy syntax for this?

**Comment by Krzysztof-Cieslak** [comment]
Preferably `paket.dependencies` would use `framework NAME`, but unfortunately it's already used for specification of framework restriction for file.

`assembly NAME` doesn't suggest that it's framework reference so it's not OK.

Maybe something like `framework_assembly NAME` but it's bit long, not sure if users would like it.

**Comment by mavnn** [comment]
``gac Lib.Name``?

After all, it could be any gac registered assembly (although that might involve strong words with people if they aren't framework libs)

**Comment by 7sharp9** [comment]
Oh, I need this for xebec

**Comment by 7sharp9** [comment]
Also how would paket know which version to use?  i.e. .Net 4.5, or a pcl versioned dll?

**Comment by matthid** [comment]
I'm closing this because it creates too much headache and dotnet-core seems to have "solved" this anyway

**Comment by Krzysztof-Cieslak** [comment]
"Solved" is good description
