### ISSUE TITLE
Confusing error on empty line in paket.references

### ISSUE THREAD

**Issue by isaksky** [fsprojects/Paket#845]
With this paket.references file
   
    FSharp.Core
    FSharp.Data.SqlClient

    WebSharper

Running paket install yields a " Package WebSharper  was referenced, but it was not found in the paket.lock file" error.

With this paket.references file, everything is fine:

    FSharp.Core
    FSharp.Data.SqlClient
    WebSharper

(paket 1.6.2.0 on windows 8.1.)

**Comment by forki** [comment]
just tried to reproduce. no luck. Can you try to create a minimal repro?

**Comment by isaksky** [comment]
Hmm, now I can't reproduce it either. I'll come back here with the exact steps if I see it again.
