### ISSUE TITLE
Confusion between "paket install" and "paket update"

### ISSUE THREAD

**Issue by cr7pt0gr4ph7** [fsprojects/Paket#848]
There's considerable overlap in the behavior of `paket install` and `paket update`, and some confusion on which one should be used in which situation.

# Summary
* `paket update` could also be called `paket forget-everything-and-re-resolve (and-install-into-projects)`
* `paket install` could also be called `paket only-update-packages-where-absolutely-necessary (and-install-into-projects)`

**Proposed solution:** My intuition is that `paket install` should really be called `paket update --pin-unchanged`, because this is what it really does.

`paket install` does not really have a purpose anymore then, but should probably be kept for compatibility reasons. The documentation of `paket install` could then say: "`paket install` has the same effect as `paket update --pin-unchanged`". This would also remove the confusion between the two commands.

For completeness: The third use case (no updates to `paket.lock`) is already covered by another command:
* `paket restore` could also be called `paket do-not-update-versions-and-install-into-projects`

# Details:
## Behavior of paket update:
  1. **Delete paket.lock if it exists**, therefore discarding the currently used versions of the packages  (*UpdateProcess.Update*).

  2. Compute a new `paket.lock` file based on `paket.dependencies` (*UpdateProcess.SmartInstall/.SelectiveUpdate*)

  3. (Optionally:) Install everything from paket.lock (*InstallProcess.InstallIntoProjects*)

## Behavior of paket install:
  1. If no `paket.lock` file exists: Same behavior as `paket update` (it just calls *UpdateProcess. SmartInstall*)

  2. **If a `paket.lock` file exists:** (*UpdateProcess.SmartInstall/.SelectiveUpdate*)
       1. Compare `paket.lock` and `paket.dependencies` to find (*DependencyChangeDetection. findChangesInDependenciesFile*):
          * Dependencies that were added to `paket.dependencies`
          * Dependencies where the current version from `paket.lock` does not match the version requirement from `paket.dependencies`
       2. **Pin all unchanged dependencies** (i.e. the ones that are not newly added or modified)
       3. Compute a new `paket.lock`, taking into account the pinned dependencies.
       
  3. Install everything from paket.lock (*InstallProcess.InstallIntoProjects*)

## Behavior of paket restore:
  1. Install everything from paket.lock (*RestoreProcess.Restore*)

**Comment by agross** [comment]
My mental model is based around this documentation from bundler:

> bundle install
Install the gems specified by the Gemfile or Gemfile.lock

>bundle update
Update dependencies to their latest versions

Bundler has no `restore`, but an existing Gemfile.lock + `bundle install` does basically the same as `paket restore` w.r.t. dependency resolution. As far as I understand, `paket restore` does not modify project files (a good thing), while `paket install` does.

Also, my understanding is that `paket update` does not simply forget the lockfile, since you can also update specific dependencies with `paket update nuget foo`.

To suggest a one-line documentation for the sake of this discussion:

> paket install
Install the dependencies specified by the paket.dependencies or paket.lock file and update project files

> paket restore
Install the dependencies specified by the paket.lock file

> paket update [nuget foo]
Update one or all dependencies to their latest version

I like that these high-level commands exist and I feel that none of these should be replaced by a parameter.

**Comment by cr7pt0gr4ph7** [comment]
I like your proposed one-line documentation, and I think that they avoid the confusion.
After finding the reason why `paket install` behaves the way it does in issue #777, I also think that its behavior makes sense.

So the only think that should be clarified is the documentation. I'd proprose the following extension to your one-line documentation (note that I'm looking for a more consice wording):

> paket install
> Install the dependencies specified by the paket.dependencies or paket.lock file and update projects
>
> If the paket.dependencies file has been changed since the last update of the paket.lock file (e.g. added dependencies or changed version requirements), Paket will update the paket.lock file to make it match paket.dependencies.
>
> In difference to `paket update`, `paket install` will only look for new versions of dependencies that have been modified in paket.dependencies, and pin the versions of all other dependencies.

**Comment by agross** [comment]
I think this matches quite well what the manpage of [bundle install](http://bundler.io/v1.9/man/bundle-install.1.html#DESCRIPTION) says:

> Install the gems specified in your Gemfile(5). If this is the first time you run bundle install (and a Gemfile.lock does not exist), Bundler will fetch all remote sources, resolve dependencies and install all needed gems.

>If a Gemfile.lock does exist, and you have not updated your Gemfile(5), Bundler will fetch all remote sources, but use the dependencies specified in the Gemfile.lock instead of resolving dependencies.

>If a Gemfile.lock does exist, and you have updated your Gemfile(5), Bundler will use the dependencies in the Gemfile.lock for all gems that you did not update, but will re-resolve the dependencies of gems that you did update. You can find more information about this update process below under CONSERVATIVE UPDATING.

**Comment by cr7pt0gr4ph7** [comment]
I didn't know the manpage of bundler yet; I think that I find their description more understandable than my proposal.

I find it interesting that they use the term "conservative updating", because that one came to my mind, too.

**Comment by forki** [comment]
what's the status here? do you propose to improve the docs? If so could you please send a PR. I think the distinction between update and install is very important.

**Comment by cr7pt0gr4ph7** [comment]
My proposal would be to update the documentation for `paket update and `paket install`, `paket restore` as proposed by [agross](#issuecomment-106835242) and [me](#issuecomment-106842879). To sum it up:

> **paket install**
> Install the dependencies specified by the paket.dependencies or paket.lock file and update projects.
>
> If the paket.dependencies file has been changed since the last update of the paket.lock file (e.g. added dependencies or changed version requirements), Paket will update the paket.lock file to make it match paket.dependencies again.
>
> In difference to `paket update`, `paket install` will only look for new versions of dependencies that have been modified in paket.dependencies, and use the version from paket.lock for all other dependencies.
>
> **paket restore**
> Download and install the dependencies specified by the paket.lock file.
>
> `paket restore` fails with an error if the paket.lock file does not exist. No packages are downloaded in that case. Please see `paket install` and `paket update` to learn how to create the paket.lock file.
>
> **paket update [nuget foo]**
> Update one or all dependencies to their latest version and update projects.
>
> *Updating all packages*
> If you do not specify a package, then all packages from paket.dependencies are updated.
>
> First, the current paket.lock file is deleted. `paket update` then recomputes the current dependency resolution, as explained under [Package resolution algorithm](http://fsprojects.github.io/Paket/resolver.html), and writes it to paket.lock. It then proceeds to download the packages and to install them into the projects.
>
> Please see `paket install` if you want to keep the current versions from your paket.lock file.
>
> ```batchfile
> $ paket update [--force|-f] [--hard] [--redirects] [--no-install]
> ```
>
> *Updating a single package*
> It's also possible to update only a single package and to keep all other dependencies fixed:
>
> ```batchfile
> $ paket update nuget PACKAGENAME [version VERSION] [--force|-f] [--hard] [--redirects] [--no-install]
> ```

Note that the part after the italic headings should go into [update.md](https://github.com/fsprojects/Paket/blob/master/docs/content/commands/update.md). 

I'm currently busy with my bachelor thesis, so it might take me some time to put the things above in a pull request. But it's definitely on my list.

**Comment by cdrnet** [comment]
IMO that description of `paket restore` is misleading. Restore does not install anything, it merely restores files which may be missing due to them being excluded from source control.

**Comment by cr7pt0gr4ph7** [comment]
Your're right; I cross-checked `RestoreProcess.Restore` to verify this.

I incorporated your feedback into [my proposal](#issuecomment-108988794) above. The original text is marked using ~~strikethrough~~. Do you think it's better now?

---

To get the terminology clear (and to try to establish an [**ubiquituous language**](http://martinfowler.com/bliki/UbiquitousLanguage.html)):

| What the<br>docs say: | What is meant: | Verb |
|----------------|------------------------------|---|
| **Add/Install a** package | *Add the package to paket.dependencies (and paket.references), update paket.lock as necessary,* **download** *the package and* **update** *the project files.* | `add` |
| ??? | *Add the package to paket.dependencies (and paket.references) and update paket.lock.* | `add --no-install` |
| **Install all** packages | *Update paket.lock as necessary,* **download** *all packages and* **update** *the project files.* | `install` |
| | | |
| **Remove/Uninstall a** package | *Remove the package from paket.dependencies (and paket.references), update paket.lock as necessary, delete the downloaded files and* **update** *the project files.* | `remove` |
| ??? | *Remove the package from paket.dependencies (and paket.references) and update paket.lock as necessary.* | `remove --no-install` |
| | | |
| **Update** one or all **packages** | *Look for new versions of a single/all packages and write them into paket.lock (and* **download/install** *them if not told otherwise).* | `update` |
| **Download the packages** | *Download the .nupkg files into packages/ but do nothing else.* | `restore` |
| **Update** (the) **project**/**s** files | *Update the project files with the current DLL paths (and download them according to paket.lock if necessary).* | (`install`) |

**Comment by forki** [comment]
very cool

**Comment by matneyx** [comment]
Is there a single-command way to update only the non-version-locked dependencies and restore everything else?  I know I can make a group (and I will if I have to), but I'd love it if this was a built-in function.

**Comment by forki** [comment]
I don't really understand. Can you create a new issue with concrete sample?

**Comment by matneyx** [comment]
@forki, possibly.  I'm still trying to wrap my head around it -- we were using ripple, before, and that was my first exposure to dependency management, and I've been asked to research and determine whether Paket can be a replacement for it.  The answer is a definite yes, but I need to figure out what is similar / different between the two.

So, to answer your question, by the time I know enough to really make an example, I may already know the answer.

**Comment by forki** [comment]
ok. maybe you can rephrase the question then?

**Comment by CumpsD** [comment]
Small reaction to this old issue, the table from https://github.com/fsprojects/Paket/issues/848#issuecomment-109312241 would actually make a nice summary to the docs as an overview

**Comment by forki** [comment]
@CumpsD PRs very welcome!
