### ISSUE TITLE
Paket pack: Duplicate files being archived when specified multiple times in templates

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/Paket#851]
I came across an issue where files being specified more than once result in the same file being included multiple times in the nupkg archive. The behaviour can be reproduced using [this commit](https://github.com/nessos/FsPickler/commit/3af7aefcc195de7796de92c7d0aa0d33dd7c6106). For instance, In FsPickler.fsproj, the paket template contains the following declarations:
```
type project
id FsPickler
...
files
    ../../bin/FsPickler.dll ==> lib/net45
    ../../bin/FsPickler.pdb ==> lib/net45
    ../../bin/FsPickler.xml ==> lib/net45
    ../../bin/net40/FsPickler.dll ==> lib/net40
    ../../bin/net40/FsPickler.pdb ==> lib/net40
    ../../bin/net40/FsPickler.xml ==> lib/net40
```
This will cause the `net45` FsPickler.dll to be bundled twice, but not the same for `net40`. 
![screen shot 2015-06-01 at 15 45 54](https://cloud.githubusercontent.com/assets/2813363/7913057/565c20dc-0875-11e5-81cf-d0c75a9fe249.png)
The obvious fix here would be to omit the net45 declarations, but I would prefer the explicitness of the current version. 

Taking this issue to the extreme, it is possible to do the following:
```
files
    ../../bin/FsPickler.dll ==> lib/net45
    ../../bin/FsPickler.dll ==> lib/net45
    ../../bin/FsPickler.dll ==> lib/net45
    ../../bin/FsPickler.dll ==> lib/net45
    ../../bin/FsPickler.dll ==> lib/net45
```
which yields the following result:
![screen shot 2015-06-01 at 15 50 44](https://cloud.githubusercontent.com/assets/2813363/7913143/ff86a38a-0875-11e5-9365-32db627792ae.png)

**Comment by forki** [comment]
4e2547a  should do the trick

**Comment by eiriktsarpalis** [comment]
Hmm, the problem still reproduces with 1.9.2.

**Comment by forki** [comment]
ah found another thingy

**Comment by forki** [comment]
could you please try 1.9.3 - looks good for me

**Comment by eiriktsarpalis** [comment]
It seems to be working, however now the net40 files have disappeared from the archive - as if the files in the template are being completely ignored.

**Comment by forki** [comment]
after running `build.fsx PaketNuget`on your branch and unzipping I see:

![image](https://cloud.githubusercontent.com/assets/57396/7913953/06f95cea-0874-11e5-81f0-868df1253b8b.png)

![image](https://cloud.githubusercontent.com/assets/57396/7913962/0e50255a-0874-11e5-8ff1-d6203ee6ae10.png)

![image](https://cloud.githubusercontent.com/assets/57396/7913971/17bdc174-0874-11e5-8894-60090c9deee4.png)

![image](https://cloud.githubusercontent.com/assets/57396/7913978/1cf69422-0874-11e5-948a-8cd9d799ec88.png)


LGTM

**Comment by eiriktsarpalis** [comment]
Ok, so I ran clean/reset in my local repo and everything seems to be working fine. Thanks!
