### ISSUE TITLE
`paket install` not respecting `content:none`

### ISSUE THREAD

**Issue by theburningmonk** [fsprojects/Paket#854]
I'm running paket 1.6.4.0 and I want to stop `FsCheck.Nunit` from bringing in the `FsCheckAddin.fs` content file.

My paket.dependencies looks like:

    source https://nuget.org/api/v2

    nuget AWSSDK
    nuget DynamoDB.Sql
    nuget FSharp.Core
    nuget FSharp.Formatting
    nuget FsCheck
    nuget FsCheck.Nunit >= 0 content:none
    ...

`paket restore` respects this but if someone runs `paket.install` then the `FsCheckAddin.fs` file is brought back in as `paket install` doesn't seem to respect the `content:none` clause

**Comment by forki** [comment]
Is this an open source project where I can reproduce?

**Comment by theburningmonk** [comment]
not open source unfortunately, but it seems to happen consistently for me, or perhaps I'm using the wrong commands?

steps:
- `paket add nuget FsCheck.Nunit project XYZ`
- edit `paket.dependencies` to add `>=0 content:none` for `FsCheck.Nunit`
- delete `FsCheckAddin.fs` file from project
- `paket install` adds the file back in
- close VS2012
- delete `FsCheck.Nunit` folder in pakcages
- reopen VS2012
- `paket restore` (package restored, and file is not added)
- `paket install` (adds file back in)

**Comment by forki** [comment]
i can reproduce.

the issue is that install doesn't detect the content:none addition in the dependencies file therefor doesn't change the lock file.

if you run update once then this would be fixed (since it recomputes the lock file).

That said: I consider this a bug and try to fix it.

**Comment by theburningmonk** [comment]
if I add another package it also seems to fix the issue too, thanks for looking into it

**Comment by forki** [comment]
yeah. it all depends on the lockfile.

Just for clarification: Restore is not really important here since it will
never touch projects. it just downloads and extracts packages.

2015-06-02 16:01 GMT+02:00 Yan Cui <notifications@github.com>:

**Comment by forki** [comment]
does it work for you?

**Comment by theburningmonk** [comment]
yup, 1.10.0.0 does what I expect it to wrt to `content:none` thanks for the quick turnaround!
