### ISSUE TITLE
"copy_local" is not respected for indirect dependencies

### ISSUE THREAD

**Issue by dmitryvk** [fsprojects/Paket#856]
I have a following case:
1. paket.dependencies:
    ```
    copy_local: false
    ...
    ```
2. paket.references:
    ```
    some_package_1 copy_local: true
    ```
3. some_package_1 depends on some_package_2.

After running "paket install", in csproj file I have:
```
...
<Reference Include="some_package_1">
  <Private>True</Private>
  ...
</Reference>
...
<Reference Include="some_package_2">
  <Private>False</Private>
  ...
</Reference>
...
```
I expected that some_package_2 would also get "<Private>True</Private>".

Is there a way to propagate this option to indirect dependencies of referenced nuget package?

**Comment by forki** [comment]
Mhm I think it's already inherited in the dependencies file. So you're
right we should inherit it also in the references file.

As a workaround add the dependent package also to the references file.
