### ISSUE TITLE
Version requirement is parsed incorrectly

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#857]
paket.dependencies:
```
source https://nuget.org/api/v2

nuget AutoMapper ~> 3.2
nuget Castle.Windsor !~> 3.3
nuget DataAnnotationsExtensions 1.1.0.0
nuget EntityFramework 5.0.0
nuget FakeItEasy ~> 1.23
nuget FluentAssertions ~> 3.1
nuget Machine.Specifications ~> 0.9
nuget Machine.Specifications.Runner.Console ~> 0.9
nuget NDbfReader 1.1.1.0
nuget Newtonsoft.Json ~> 6.0
nuget Plossum.CommandLine != 0.3.0.14
nuget PostSharp 3.1.52
nuget SharpZipLib 0.86.0
nuget Topshelf ~> 3.1
nuget Caliburn.Micro !~> 2.0.2
```

The last line was added for the install process.

paket.lock:
```
NUGET
  remote: https://nuget.org/api/v2
  specs:
    AutoMapper (3.3.1)
    C5 (1.0.2.0)
    Castle.Core (3.3.0)
    Castle.Windsor (3.3.0)
      Castle.Core (>= 3.3.0)
    DataAnnotationsExtensions (1.1.0.0)
    EntityFramework (5.0.0)
    FakeItEasy (1.25.2)
    FluentAssertions (3.3.0)
    Machine.Specifications (0.9.1)
    Machine.Specifications.Runner.Console (0.9.0)
    NDbfReader (1.1.1.0)
    Newtonsoft.Json (6.0.8)
    Plossum.CommandLine (0.3.0.14)
      C5 (>= 1.0.2.0)
    PostSharp (3.1.52)
    SharpZipLib (0.86.0)
    Topshelf (3.1.4)
```

```bash
$ paket install
Paket version 1.10.0.0
Paket failed with:
        Error in paket.dependencies line 4
  Invalid prerelease version !3.3.0
```

Line 4 contains: `nuget Castle.Windsor !~> 3.3`

**Comment by forki** [comment]
Let me guess this works with 1.9.0 and is a regression?

**Comment by Uli-Armbruster** [comment]
We haven't tried that. We just added Caliburn.Micro as new package and after executing the install command for the first time, this error came up.

**Comment by forki** [comment]
Will try to fix it, bit I'm currently on vacation. So it will be Monday

**Comment by Uli-Armbruster** [comment]
Nope, v1.9.0.0 already has this bug. Don't hurry, we don't need it this week.


D:\Development\Repository>paket install
Paket version 1.10.0.0
Paket failed with:
        Error in paket.dependencies line 4
  Invalid prerelease version !3.3.0

D:\Development\Repository>paket install
Paket version 1.9.0.0
Paket failed with:
        Error in paket.dependencies line 4
  Invalid prerelease version !3.3.0
