### ISSUE TITLE
`paket update` fails with prerelease version specification

### ISSUE THREAD

**Issue by dmitryvk** [fsprojects/Paket#859]
I have following version spec in paket.dependencies (package name was replaced):
```
nuget Foo >= 1.10.301 prerelease
```
In my nuget source, there is version "1.10.301-dev" of package Foo.
But when running "paket update", I get a failure:
```
Paket failed with:
        Could not find compatible versions for top level dependency:
     "Foo >= 1.10.301 (from C:\...\paket.dependencies)"
   Available versions:
     -
   Try to relax the dependency or allow prereleases.
```

If I change the version spec to this:
```
nuget Foo >= 1.10.301-dev prerelease
```
then "paket update" will correctly install version 1.10.301-dev of Foo.

This seems to happen because of VersionComparison in function VersionRequirement.IsInRange: in expression
```
match range with
...
| Minimum v -> v = version || (v <= version && checkPrerelease prerelease version)
```
"v" has value "1.10.301" and "version" has value "1.10.301-dev", so "v" is considered to be greater than "version" (since their numbers match, but "1.10.301" is a release version while "1.10.301-dev" is a prerelease version).

**Comment by forki** [comment]
Yes. Released versions are considered newer.

**Comment by dmitryvk** [comment]
So version spec '>= 1.10.301 prerelease' should not match version '1.10.301-dev'? It seemed unintuitive to me; but I guess then this is not a bug, just misunderstanding of documentation.

In my case, 'paket convert-from-nuget' create 'paket.dependencies' file which contained exact version dependency 'Foo 1.10.301-dev'. It seemed logical that just changing '=' to '>=' should at least allow the same version of package to be used (e.g., version '1.10.301-dev' matches spec '= 1.10.301 prerelease', but spec '>= 1.10.301 prerelease' does not; this confused me).

**Comment by forki** [comment]
I will check this again. Maybe we have a inconsistency here. But I
recommend to change the dependency for now.

**Comment by Stift** [comment]
I tend to admit to @forki and don't see an incosistency. Normally you have a release cycle like (in timely order)
1.0.0-beta1
1.0.0-beta2
1.0.0
1.0.1-beta1
... and so on.

If say now `>= 1.0.0 prerelease`. Then you accept everything released later that 1.0.0 (the third line and after).
As @forki said you should relax or specify the version directly.

**Comment by dmitryvk** [comment]
Thanks for explanations.

**Comment by Stift** [comment]
No problem. You are welcome.
