### ISSUE TITLE
SharpCompress crash on Mono

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Paket#861]
I was using Paket in F# training and one person on a Mac got the error below. To be fair, I'm really not sure what might be going on here. The [static constructor of ArchiveEncoding](https://github.com/adamhathcock/sharpcompress/blob/master/SharpCompress/Common/ArchiveEncoding.cs) is not doing anything interesting and we had other issues on the same machine (F# Data was failing to parse XML file with dates...), so maybe it was a cursed machine (it was a _Mac on Microsoft campus_). 

But I thought I'd report this anyway. It was using the latest version of Mono (4.0.1.44, I believe).

    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Zlib.Portable/Zlib.Portable.1.10.0.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Zlib.Portable 1.10.0 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Deedle.RPlugin/Deedle.RPlugin.1.0.7.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Deedle.RPlugin 1.0.7 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Deedle/Deedle.1.0.7.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Deedle 1.0.7 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Foogle.Charts/Foogle.Charts.0.0.5.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Foogle.Charts 0.0.5 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/FSharp.Charting/FSharp.Charting.0.90.10.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of FSharp.Charting 0.90.10 - automatic retry with --force.
    Downloading Zlib.Portable 1.10.0 to /Users/ismini/.local/share/NuGet/Cache/Zlib.Portable.1.10.0.nupkg
    Downloading Deedle 1.0.7 to /Users/ismini/.local/share/NuGet/Cache/Deedle.1.0.7.nupkg
    Could not download license for XPlot.Plotly 1.0.1 from http://github.com/TahaHachana/XPlot/blob/master/LICENSE.txt.
        The remote server returned an error: (404) Not Found.
    Downloading Foogle.Charts 0.0.5 to /Users/ismini/.local/share/NuGet/Cache/Foogle.Charts.0.0.5.nupkg
    Downloading Deedle.RPlugin 1.0.7 to /Users/ismini/.local/share/NuGet/Cache/Deedle.RPlugin.1.0.7.nupkg
    Downloading FSharp.Charting 0.90.10 to /Users/ismini/.local/share/NuGet/Cache/FSharp.Charting.0.90.10.nupkg
    Could not download license for XPlot.GoogleCharts.Deedle 0.6.2 from http://github.com/TahaHachana/XPlot/blob/master/LICENSE.txt.
        The remote server returned an error: (404) Not Found.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/FSharp.Compiler.Service/FSharp.Compiler.Service.0.0.89.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of FSharp.Compiler.Service 0.0.89 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/XPlot.Plotly/XPlot.Plotly.1.0.1.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of XPlot.Plotly 1.0.1 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/XPlot.GoogleCharts.Deedle/XPlot.GoogleCharts.Deedle.0.6.2.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of XPlot.GoogleCharts.Deedle 0.6.2 - automatic retry with --force.
    Downloading XPlot.Plotly 1.0.1 to /Users/ismini/.local/share/NuGet/Cache/XPlot.Plotly.1.0.1.nupkg
    Downloading FSharp.Compiler.Service 0.0.89 to /Users/ismini/.local/share/NuGet/Cache/FSharp.Compiler.Service.0.0.89.nupkg
    Downloading XPlot.GoogleCharts.Deedle 0.6.2 to /Users/ismini/.local/share/NuGet/Cache/XPlot.GoogleCharts.Deedle.0.6.2.nupkg
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/FSharp.Core/FSharp.Core.3.1.2.1.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of FSharp.Core 3.1.2.1 - automatic retry with --force.
    Downloading FSharp.Core 3.1.2.1 to /Users/ismini/.local/share/NuGet/Cache/FSharp.Core.3.1.2.1.nupkg
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/TaskParallelLibrary/TaskParallelLibrary.1.0.2856.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of TaskParallelLibrary 1.0.2856.0 - automatic retry with --force.
    Downloading TaskParallelLibrary 1.0.2856.0 to /Users/ismini/.local/share/NuGet/Cache/TaskParallelLibrary.1.0.2856.nupkg
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Suave/Suave.0.28.1.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Suave 0.28.1 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/R.NET.Community.FSharp/R.NET.Community.FSharp.0.1.9.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of R.NET.Community.FSharp 0.1.9 - automatic retry with --force.
    Downloading R.NET.Community.FSharp 0.1.9 to /Users/ismini/.local/share/NuGet/Cache/R.NET.Community.FSharp.0.1.9.nupkg
    Downloading Suave 0.28.1 to /Users/ismini/.local/share/NuGet/Cache/Suave.0.28.1.nupkg
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/R.NET.Community/R.NET.Community.1.5.16.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of R.NET.Community 1.5.16 - automatic retry with --force.
    Downloading R.NET.Community 1.5.16 to /Users/ismini/.local/share/NuGet/Cache/R.NET.Community.1.5.16.nupkg
    Could not download license for XPlot.GoogleCharts 1.1.7 from http://github.com/TahaHachana/XPlot/blob/master/LICENSE.txt.
        The operation has timed-out.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/XPlot.GoogleCharts/XPlot.GoogleCharts.1.1.7.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of XPlot.GoogleCharts 1.1.7 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/RProvider/RProvider.1.1.8.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of RProvider 1.1.8 - automatic retry with --force.
    Downloading XPlot.GoogleCharts 1.1.7 to /Users/ismini/.local/share/NuGet/Cache/XPlot.GoogleCharts.1.1.7.nupkg
    Downloading RProvider 1.1.8 to /Users/ismini/.local/share/NuGet/Cache/RProvider.1.1.8.nupkg
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Newtonsoft.Json/Newtonsoft.Json.6.0.8.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Newtonsoft.Json 6.0.8 - automatic retry with --force.
    Downloading Newtonsoft.Json 6.0.8 to /Users/ismini/.local/share/NuGet/Cache/Newtonsoft.Json.6.0.8.nupkg
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/MathNet.Numerics.FSharp/MathNet.Numerics.FSharp.3.6.0.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of MathNet.Numerics.FSharp 3.6.0 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Http.fs/Http.fs.1.5.1.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Http.fs 1.5.1 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Google.DataTable.Net.Wrapper/Google.DataTable.Net.Wrapper.3.1.2.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of Google.DataTable.Net.Wrapper 3.1.2 - automatic retry with --force.
    Downloading MathNet.Numerics.FSharp 3.6.0 to /Users/ismini/.local/share/NuGet/Cache/MathNet.Numerics.FSharp.3.6.0.nupkg
    Downloading Google.DataTable.Net.Wrapper 3.1.2 to /Users/ismini/.local/share/NuGet/Cache/Google.DataTable.Net.Wrapper.3.1.2.nupkg
    Downloading Http.fs 1.5.1 to /Users/ismini/.local/share/NuGet/Cache/Http.fs.1.5.1.nupkg
    Could not download license for FAKE 3.34.7 from http://www.github.com/fsharp/Fake/blob/master/License.txt.
        The operation has timed-out.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/FsPickler/FsPickler.1.2.6.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of FsPickler 1.2.6 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/FAKE/FAKE.3.34.7.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Something went wrong with the download of FAKE 3.34.7 - automatic retry with --force.
    Could not fix timestamps in /Users/ismini/Downloads/day-1/packages/Zlib.Portable/Zlib.Portable.1.10.0.nupkg. Error: An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding
    Paket failed with:
    	An exception was thrown by the type initializer for SharpCompress.Common.ArchiveEncoding

**Comment by tpetricek** [comment]
So, the other error I was getting with dates was unrelated (https://github.com/fsharp/FSharp.Data/pull/840).

**Comment by forki** [comment]
`SharpCompress.Common.ArchiveEncoding` I didn't know we are using this!!?

**Comment by tpetricek** [comment]
The failure is in a static constructor - which I guess might be triggered by all sorts of unrelated things.
