### ISSUE TITLE
`paket update` does not pick latest prerelease version of indirect dependency

### ISSUE THREAD

**Issue by dmitryvk** [fsprojects/Paket#866]
I have 3 versions of 2 packages:
1) p1 version 1.0-beta
2) p1 version 1.1-beta
3) p2 version 1.0-beta

p2 depends on:
```
p2 >= 1.0-beta
```

When I install package `p2`, paket pick version `1.0-beta` of `p1`.

I expect that version `1.1-beta` of `p1` would be selected.

**Comment by forki** [comment]
I'd suspect this too.
Is this somethin I can reproduce with public packages?

**Comment by dmitryvk** [comment]
This happened to me with private packages. I'll try to produce small example.

**Comment by dmitryvk** [comment]
https://github.com/dmitryvk/paket-866 - here is the reproducing example. Run `.paket/paket update` inside `tst` directory.

**Comment by forki** [comment]
I can confirm the bug with this awesome repro sample. Thanks a lot.

**Comment by forki** [comment]
can you confirm that it's fixed in 1.12.1?

**Comment by dmitryvk** [comment]
Yes, it works now.
