### ISSUE TITLE
Excluding files in paket.template

### ISSUE THREAD

**Issue by domaslasauskas** [fsprojects/Paket#867]
[NuSpec supports excluding](http://docs.nuget.org/create/nuspec-reference#excluding-files-in-the-nuspec) files when using wild cards. Is this possible with paket.template?

It's not mentioned anywhere in [paket.template documentation](http://fsprojects.github.io/Paket/template-files.html).

**Comment by forki** [comment]
nope it's currently not supported.

**Comment by forki** [comment]
this is now supported: http://fsprojects.github.io/Paket/template-files.html#Files
