### ISSUE TITLE
Creating symbol package with sources

### ISSUE THREAD

**Issue by domaslasauskas** [fsprojects/Paket#868]
NuGet supports `-Symbols` parameter for [creating symbol package](https://docs.nuget.org/create/creating-and-publishing-a-symbol-package#creating-a-symbol-package) which contains source files (in `\src` inside the package).

Paket is missing a way to include sources in the package when using paket.template.

**Comment by JohanLarsson** [comment]
Not sure this is a good idea but one way could be to transform the `.template` to a `.nuspec` and feed it to `nuget.exe`.

**Comment by cdrnet** [comment]
I'd have a use case for this as well, although in my case sources would need to go into `/src/Common` as it is a multi-platform package where all variants are compiled from the same sources. I'd rather not call into NuGet.exe for this as that's what I'm trying to get rid of by using Paket :).

**Comment by DavidHayden87** [comment]
I need this too... working on a pull request

**Comment by kichristensen** [comment]
Could this not issue be closed, as @forki merged the PR back in December 2015?
