### ISSUE TITLE
Paket on homebrew

### ISSUE THREAD

**Issue by simonhdickson** [fsprojects/Paket#869]
I saw a couple of tickets (#178, #42) talking about adding homebrew support but no homebrew formula, so I put together this formula:

https://github.com/simonhdickson/homebrew/blob/a370cf45d5dc6ef8b62af389aeacaf75b951025b/Library/Formula/paket.rb

Any changes or issues with adding it to homebrew?

**Comment by forki** [comment]
https://twitter.com/adamchester/status/609612835287502848

**Comment by inosik** [comment]
Tried it, can't install :cry: But I think this is actually an issue with my F# setup, since I can't build Paket myself either.

The log can be found here: https://gist.github.com/anonymous/d47708cdf3a9ce807873

**Comment by forki** [comment]
same as https://github.com/fsharp/fsharp/issues/378 ?

**Comment by inosik** [comment]
I think so, xbuild is looking for `Microsoft.FSharp.Targets` in the wrong path.
/cc @haf

**Comment by simonhdickson** [comment]
Yeah, I use the mono/F# installed with xamarin locally to avoid that, not homebrew

**Comment by haf** [comment]
If you drop `:fsharp => :recommended`, you can probably merge this as-is.

When we re-insert our Z3 solver for [qvitoo](https://qvitoo.com) for x64 mono I'm going to have to solve that ticket, unless someone beats me to it. A bit of GUI validation to do before then.

**Comment by LimoWanKenobi** [comment]
Yep, same error here... @simonhdickson how do I chose which mono/f# use without uninstalling mono/f# from homebrew? last time I just uninstalled and continued with my life.

**Comment by simonhdickson** [comment]
@LimoWanKenobi Might be best just uninstalling and waiting until that fsharp ticket is resolved as I'm not sure what to do otherwise.

Only thing that might be an issue is this bit:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#we-dont-like-install-scripts-that-download-things
Is there a way to build without having to download paket?

**Comment by haf** [comment]
@LimoWanKenobi If you have some time assistance solving the ticket would be nice. Xamarin has said they won't be and Don and the F# team doesn't see homebrew as prioritised.

**Comment by simonhdickson** [comment]
PR sent homebrew/homebrew#40754

**Comment by simonhdickson** [comment]
Can someone check out if these commits fix it?

https://github.com/simonhdickson/homebrew/tree/fix_framework_45
https://github.com/simonhdickson/Paket

**Comment by kostrse** [comment]
Paket was published to Homebrew today (Homebrew/homebrew-core/pull/3074)

```
brew update
brew install paket
```

Enjoy :)
