### ISSUE TITLE
Duplicate reference added

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#878]
Hi. We're using paket in a ASP.NET WebAPI project. Adding `Microsoft.Framework.Logging` dependency to a project causes multiple references to `System.Collections.Concurrent` and the build fails

```
Error	2	An assembly with the same identity 'System.Collections.Concurrent, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported.
```

Thanks

**Comment by tpluscode** [comment]
Apparently it is added to csproj together with `Microsoft.Framework.Logging` and then again on its own pointing directly to the packages folder

**Comment by forki** [comment]
mhh. can you provide me a repro for debugging?

**Comment by tpluscode** [comment]
There really isn't much to it but here you go: https://github.com/tpluscode/paket-dependencies. Clone, restore and build :)

**Comment by forki** [comment]
I assume the is that we don't understand `DNXCore5.0` yet

**Comment by forki** [comment]
with Paket 1.15.1 I was able to do "paket update -f" and it seems to resolve properly. Can you please confirm?

**Comment by tpluscode** [comment]
It works in my example but unfortunately still fails in our production code. It seems that adding another dependency, which also requires `System.Collections.Concurrent` has the same effect. Try adding `Microsoft.AspNet.FileProviders` or `Microsoft.Framework.DependencyInjection`

**Comment by forki** [comment]
I tried to reproduce, but no luck. Can you please try to update your repro? That would make it much easier for me. Thanks so much for your patience.

**Comment by tpluscode** [comment]
Okay this is weird. It indeed works on my home laptop but not at work. What could be the culprit? Different Framework version? Different VS edition (both 2015)? Anything else?

**Comment by tpluscode** [comment]
Hm, I've just updated to 1.21.1 and the problem seemingly no longer occurs. Closing
