### ISSUE TITLE
Exclusion syntax in paket.template files

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#880]
It would be nice to be able to exclude file patterns in paket.template files.

Something like:
```
files
    relative/to/template/file ==> folder/in/nupkg
    second/thing/to/pack ==> folder/in/nupkg
    second/thing/**/file.* ==> folder/in/nupkg
    -- third/*
    -- .DS_Store
```

What do you think?

**Comment by forki** [comment]
are you volunteering? ;-)

I think we already have FAKE's Globbing in place, so there must be a relatively easy way to do this.

**Comment by devboy** [comment]
Yeah, if we can agree on syntax ;)

**Comment by devboy** [comment]
```
files
    relative/to/template/file ==> folder/in/nupkg
    second/thing/to/pack ==> folder/in/nupkg
    second/thing/**/file.* ==> folder/in/nupkg
    ! third/*
    ! .DS_Store
```

would also be an idea, more glob-like...

**Comment by agross** [comment]
Looks good! Perhaps we should align the `!` syntax with `.gitignore` and not require the space between e.g. `!` and `third/*`.

**Comment by devboy** [comment]
Just saw your comment @agross ... will change it

**Comment by mavnn** [comment]
I'm with @agross - you can always use ./!stupidfilename.txt if you've named a file starting with a "!" and it makes things consistent with other systems.

**Comment by mavnn** [comment]
In fact: we should probably disallow the space to avoid ambiguity.

**Comment by devboy** [comment]
Put that into the parser ;)

Now trying to wrap my head around the `NupkgWriter` and how to apply the exclusion pattern there....

**Comment by devboy** [comment]
```
files
    relative/to/template/file ==> folder/in/nupkg
    second/thing/to/pack ==> folder/in/nupkg
    second/thing/**/file.* ==> folder/in/nupkg
    !third/*
    !.DS_Store
```

**Comment by devboy** [comment]
Would this be the right point to check files/dirs against exclude patterns?
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NupkgWriter.fs#L237-L248

And how could `Fake.Globbing` help with that?

**Comment by devboy** [comment]
Globbing is hard ...

![](http://media.giphy.com/media/5Zesu5VPNGJlm/giphy.gif)

**Comment by mavnn** [comment]
/me couldn't possible comment on why the initial version didn't include
exclusions/globbing...

**Comment by devboy** [comment]
So, as of https://github.com/devboy/Paket/commit/be5e406e573c3348853183305acf40276fc2f071, the following is possible:

- [X] `!MyFile.txt` will exclude that file in the working dir
- [X] `!**/MyFile.txt` will exclude that file in all dirs
- [X] `!../MyFile.txt` will exclude that file outside the working dir
- [X] `!../**/MyFile.txt` will exclude that file in all dirs outside the working dir
- [ ] `!Properties` will exclude `./Properties/AssemblyInfo.cs`
- [ ] `!Properties/*` will exclude `./Properties/AssemblyInfo.cs`
- [X ] `!Properties/*.*` will exclude `./Properties/AssemblyInfo.cs`

**Comment by forki** [comment]
Cool
