### ISSUE TITLE
sorting find-package-versions

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#886]
I was expecting find-package-versions to display the display the latest version first like the documentation describes here:
http://fsprojects.github.io/Paket/paket-find-package-versions.html

Unfortunately, I get this:
![image](https://cloud.githubusercontent.com/assets/80104/8269892/910f0024-1774-11e5-9200-1bb43628fed4.png)

I've got tab completion working for #873, but it would work a whole lot better with this fixed.

**Comment by forki** [comment]
Argh. So I assume the nuget team broke the order again.

**Comment by ctaggart** [comment]
This is not fixed in `1.16.0`.
![image](https://cloud.githubusercontent.com/assets/80104/8272565/0fffa5c2-17fd-11e5-9765-9905f791d041.png)

**Comment by cr7pt0gr4ph7** [comment]
Should it be possible to specify the sort order using `--sort ascending` and `--sort descending` (with `--sort descending` being the default?

**Comment by forki** [comment]
question is if anybody really needs this param.

btw: this issue is fixed in 1.17. - I must have been drunk yesterday when I accidentally added the "fix" to the `find-package` function and broke that one too.

**Comment by cr7pt0gr4ph7** [comment]
If you ask who needs this: Noone, really, because you just have to `.Reverse()` the resulting list of versions (if we assume no `max` argument). The only usage I can think of is scripting support, but there you most likely want to get the newest versions anyway.
