### ISSUE TITLE
Failing to add packages from Atom

### ISSUE THREAD

**Issue by mastoj** [fsprojects/Paket#888]
I'm quite new to both atom and paket, so it might be a beginner mistake, but I guess we don't want them either.

I installed atom, the fsharp and paket plugin for atom. When I try to run `Add Nuget package` I get:

    Paket failed with:
    	    Error in paket.dependencies line 3
      could not retrieve nuget package from 

When I run `paket install` from command line it seems to be working just fine though. Any ideas of what's wrong or anything I could do to help figure it out?

**Comment by forki** [comment]
Could you please provide the paket.dependencies file?

**Comment by forki** [comment]
And what package did you try to add

**Comment by mastoj** [comment]
The paket.dependencies file:

    source https://nuget.org/api/v2

    nuget FAKE
    nuget Suave
    nuget DotLiquid
    nuget FSharp.Data
    nuget FSharp.Compiler.Service
    nuget FSharp.Data.SqlClient

I started with a project from Petricek and just wanted to add `FSharp.Data.SqlClient`, the `FSharp.Data.SqlClient` in the file was added manually and after that it worked to run `paket install`.

How is the plugin supposed to work? Do I need to install paket separately and at it to the path or should the plugin handle everything? I'm on Windows btw.

**Comment by forki** [comment]
The atom plugin should handle everything. It downloads latest paket.exe on
install. /cc @krysztof_cieslak

The paket.dependencies file:

source https://nuget.org/api/v2

nuget FAKE
nuget Suave
nuget DotLiquid
nuget FSharp.Data
nuget FSharp.Compiler.Service
nuget FSharp.Data.SqlClient

I started with a project from Petricek and just wanted to add
FSharp.Data.SqlClient, the FSharp.Data.SqlClient in the file was added
manually and after that it worked to run paket install.

How is the plugin supposed to work? Do I need to install paket separately
and at it to the path or should the plugin handle everything? I'm on
Windows btw.

—
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/888#issuecomment-113902507>.

**Comment by Krzysztof-Cieslak** [comment]
I think I see the problem - the Paket for some reason (which I don't know yet) doesn't returns list of plugins - only element visible on `should-be-searched-packages` list is empty element ( displaying it is definitely the bug in plugin) and when user press `Enter` it's using chosen element from list (so in this case it's empty element) and we invoke Paket with wrong arguments.

So it's definitely plugin bug, but still for some reason Paket is not returning search results.

**Comment by Krzysztof-Cieslak** [comment]
Hmm... looks like I get search results from command line. Will investigate bit more

**Comment by Krzysztof-Cieslak** [comment]
@forki: When I fire `paket` in my local project location (just `.paket\paket.exe`) i get normal search results. When I try to run it using full path to paket atom plugin (i.e. `C:\Users\Krzysztof\.atom\packages\Paket\bin\paket.exe` ) I get empty result form it. Any idea?

**Comment by forki** [comment]
Maybe it doesn't find the right paket.dependencies to look up the nuget
feed urls?

**Comment by Krzysztof-Cieslak** [comment]
I'm starting Paket in both cases from same directory 

Other thing is that I'm kinda sure it WAS working yesterday or 2 days ago - don't remember when i lasted used Paket plugin

**Comment by forki** [comment]
Ok will try to reproduce tomorrow.

**Comment by forki** [comment]
yes I broke `find-packages` when I tried to fix `find-package-versions` - see https://github.com/fsprojects/Paket/issues/886#issuecomment-114022544 

sorry about that

**Comment by Krzysztof-Cieslak** [comment]
I've also added in Paket.Atom some better behavior if Paket for any reason returns empty result - same bug could occurred if someone gave text which could not be found by nuget. Should be better now.

**Comment by forki** [comment]
Very good. Thanks
