### ISSUE TITLE
find-packages not working in 1.16.0

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#889]
![image](https://cloud.githubusercontent.com/assets/80104/8272519/7beaa6b8-17fa-11e5-950e-3f93c1746812.png)

The web request shows that the data is retrieved.
![image](https://cloud.githubusercontent.com/assets/80104/8272525/b11e72b0-17fa-11e5-80a5-6ce4b9b57d3e.png)

**Comment by ctaggart** [comment]
![image](https://cloud.githubusercontent.com/assets/80104/8272571/4ba56f08-17fd-11e5-8f8c-86e963016b2a.png)

**Comment by ctaggart** [comment]
I am able to reproduce the problem with 1.16.0.0 on my work computer. When I build the executable myself with latest, I am unable to reproduce.

![image](https://cloud.githubusercontent.com/assets/80104/8274110/6aca9548-183e-11e5-8d9a-8977892664e6.png)

**Comment by ctaggart** [comment]
My announcement post for Paket.PowerShell is written and queued up as soon as this and #886 are fixed. :)

**Comment by cr7pt0gr4ph7** [comment]
Related to [#888](https://github.com/fsprojects/Paket/issues/888#issuecomment-114022824).

**Comment by ctaggart** [comment]
This was fixed in 0.17.0.
