### ISSUE TITLE
Make option names for paket find-package-versions consistent with the other packages

### ISSUE THREAD

**Issue by cr7pt0gr4ph7** [fsprojects/Paket#890]
Currently, the names of the options for `paket find-package-versions` are inconsistent with the other commands:
```
paket find-package-versions name My.Package
```
Compare with:
```
paket add nuget My.Package
paket remove nuget My.Package
paket update nuget My.Package
paket find-refs nuget My.Package Other.Package
```
The proposal would be to rename the `name <string>` argument to `nuget <string>`.

**Comment by ctaggart** [comment]
:+1:

**Comment by forki** [comment]
If we want to do this, then we need to patch dependent tools (I assume only atom).
//cc @Krzysztof-Cieslak

**Comment by ctaggart** [comment]
And powershell arg completion.

**Comment by cr7pt0gr4ph7** [comment]
I assume that changing the argument name is a breaking change, which would require a new major version number; especially given that `find-package-versions` is likely used in command line completion scripts. But one could also say that its marked as "EXPERIMENTAL", so that such changes are okay.

What about adding the `nuget` argument, but keeping the old `name` argument, adding a [`[<ArgUnionParser.Hidden>]`](http://nessos.github.io/UnionArgParser/tutorial.html#Customization) attribute to it and displaying a deprecation warning if its used? The plan would be to remove it in a later version.

**Comment by Krzysztof-Cieslak** [comment]
It's one line of code change in Atom plugin. Don't see any problem from this point of view.

**Comment by forki** [comment]
@Krzysztof-Cieslak done in 1.27.2. please let me know when you updated atom. we will then remove the name completely.

**Comment by Krzysztof-Cieslak** [comment]
@forki, Atom plugin updated.
