### ISSUE TITLE
Force update does not re-download HTTP dependencies

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#895]
When running `paket.exe update --force` it does not re-download HTTP dependencies.
I see why this is not done on update, as there is no version information, 
but when using force I'd expect it to re-download the files.

**Comment by forki** [comment]
Sounds reasonable to me

**Comment by ChrisMissal** [comment]
This can be closed, correct? @forki @devboy @kerams

**Comment by devboy** [comment]
Oh, didn't see this was merged. Nice. Will test tmrw.

**Comment by kerams** [comment]
Sure.
