### ISSUE TITLE
Generate assembly search path file

### ISSUE THREAD

**Issue by devboy** [fsprojects/Paket#899]
I tend to use plain F# script files more and more nowadays, much leaner.
It's still a bit tedious to reference all assemblies manually.
As paket already what dependencies i have, it would be quite cool if it would generate a paket.fsx file for me that looks something like this:

```F#
#I "packages/FSharp.Core/lib/net40"
#I "packages/Suave/lib/net40"
#I "packages/Newtonsoft.Json/lib/net45"
#I "packages/Google.Apis.Core/lib/portable-net40+sl50+win+wpa81+wp80"
#I "packages/Google.Apis.Auth/lib/net40"
#I "packages/Microsoft.Net.Http/lib/net45"
#I "packages/Microsoft.Bcl.Async/lib/net40"
#I "packages/Microsoft.Bcl/lib/net45"
#I "packages/FsPickler/lib/net45"
#I "packages/FsPickler.Json/lib/net45"
#I "packages/FSharp.Data/lib/net40"
```

Would that make sense?

**Comment by forki** [comment]
yes https://github.com/fsprojects/Paket/issues/677

**Comment by devboy** [comment]
sry for the dup

**Comment by isaacabraham** [comment]
Slightly different approach is that VS Power Tools can automatically generate (and keep up-to-date) a load-references.fsx file that loads all project references. Not –exactly- what you’re after, but it’s not bad.
