### ISSUE TITLE
`paket push` should have an option to not overwrite existing package in repository

### ISSUE THREAD

**Issue by dmitryvk** [fsprojects/Paket#902]
`paket push` re-uploads package to nuget server even if the package already exists on server. It would be useful to have an option for `paket push` that will make it check the presence of package version before uploading it.

**Comment by forki** [comment]
Oh this is a nuget server bug. Nuget.org doesn't allow that.

**Comment by dmitryvk** [comment]
I agree that servers should not allow re-uploading.
But some server do allow: e.g., myget.org by default allow this (there is an option "Forbid overwriting of existing packages" which is _off_ by default).

Hmm, maybe this isn't such a necessary option, after all.

**Comment by forki** [comment]
I think an optional flag could do this.
