### ISSUE TITLE
paket pack should provide an option for a version postfix (eg. alpha)

### ISSUE THREAD

**Issue by biohazard999** [fsprojects/Paket#904]
Currently when you are using paket pack with a paket.template "type project" there is no way to provide an -alpha -beta version postfix.

This commandline option can take a -VersionPostfix alpha and appends them to the nuget version. If the passed string is empty, nothing gets apended and it is a stable package.

This would be especially be very helpful on buildservers depending on the branch name for package previews.

What do you guys think?

**Comment by forki** [comment]
why don't you use the version parameter? `pack --version 1.0-alpha001` works!?

**Comment by biohazard999** [comment]
thanks forki, totally overlooked this
