### ISSUE TITLE
Should paket.pack include dependencies as inferred by paket.lock?

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/Paket#905]
I came across the following issue, which can be witnessed in [this commit](https://github.com/mbraceproject/MBrace.Core/tree/963e40ff561b0853da7b641f864dbb16e4e33bb0).

In the `Paket.dependencies` file, I have included the following lines:
```
source https://nuget.org/api/v2

nuget FsPickler 1.2.9
nuget FsPickler.Json
```
MBrace requires the FsPickler libraries to be version 1.2.9 precisely. When adding them, I decided to skip the FsPickler.Json version number, anticipating Paket to deduce it correctly, which it did:
```
NUGET
  remote: https://nuget.org/api/v2
  specs:
    FsPickler (1.2.9)
    FsPickler.Json (1.2.9)
```
However, when generating the nuget packages for MBrace, the following nuspec was created:
```xml
      <dependency id="FsPickler.Json" version="" />
      <dependency id="FsPickler" version="[1.2.9]" />
```
when it should really have been
```xml
      <dependency id="FsPickler.Json" version="[1.2.9]" />
      <dependency id="FsPickler" version="[1.2.9]" />
```
I did not notice this issue because we use paket on all our projects and no errors occurred when consuming the packages. However, @mathias-brandewinder reported [this issue](https://github.com/mbraceproject/MBrace.Core/issues/104) when using the default nuget client, so clearly something must be wrong. The obvious fix here (which I did) is to alter the original Paket.dependencies file to be like this:
```
source https://nuget.org/api/v2

nuget FsPickler 1.2.9
nuget FsPickler.Json 1.2.9
```
however this feels redundant.

Thoughts?

**Comment by inosik** [comment]
I would say that this is the correct behavior, because with your `paket.dependencies`-File, you're telling Paket that you don't care about the version of FsPickler.Json. So this is what gets written to the `.nuspec`-File when packing.

BTW, I assume when installing the package with Paket, this issue shouldn't arise at all, because this:
```
source https://nuget.org/api/v2

nuget FsPickler 1.2.8
nuget FsPickler.Json
```
gets resolved like this:
```
NUGET
  remote: https://nuget.org/api/v2
  specs:
    FsPickler (1.2.8)
    FsPickler.Json (1.2.8)
    ...
```
Paket picks **1.2.8** of FsPickler.Json, which is the latest version that is compatible with FsPickler 1.2.8, even if there is already **1.2.9**.

**Comment by eiriktsarpalis** [comment]
I agree with what you're saying, the reason why I'm filing this is that the
nuget client fails in the dependency resolution whereas paket does not.

**Comment by forki** [comment]
Yes I agree that we should create a package that works with nuget and
paket. So yes it could be that we need to give more information into the
nuspec than logically needed. I will look into this on Monday

**Comment by forki** [comment]
I wonder why you have

    source https://nuget.org/api/v2
    
    nuget FsPickler 1.2.9
    nuget FsPickler.Json

wouldn't it make more sense to write

    source https://nuget.org/api/v2
    
    nuget FsPickler.Json 1.2.9

I mean FsPickler.Json depends on FsPickler - that would probably solve it as well. Right?

**Comment by eiriktsarpalis** [comment]
You're right, but it's still an issue worth reporting. I think the point here is that paket proper accepts this as valid configuration, therefore paket pack should do this as well.

**Comment by forki** [comment]
Yeah I get that. But I'm not completely sure what to change. Have to think
about it.

**Comment by forki** [comment]
NuGet changes it resolver. They will support this eventually.
