### ISSUE TITLE
paket update gracefulness on non-existent version

### ISSUE THREAD

**Issue by ilkerde** [fsprojects/Paket#906]
#### Case

    paket update nuget iTextSharp-LGPL

with `paket.dependencies`

    nuget iTextSharp-LGPL 4.0.2 framework: >= net451

and a package history at nuget.org http://www.nuget.org/packages/iTextSharp-LGPL/

So apparently, v4.0.2 does not exist, so `paket update` fails to verify it. Paket ends with

    System.Exception: Could not retrieve data from https://nuget.org/api/v2/Packages(Id='iTextSharp-LGPL',Version='4.0.2')
    Message: The remote server returned an error: (404) Not Found.

#### Expectation

I'd like paket to fallback and qurey the most recent version, then fail with an error message that the current version does not exist anymore but another (newer) version exists. I would then like to have the option to force paket to update me to the latest version.

#### Alternatives

Just give me an alternative on how to update to most recent version in such a situation.

Thank you!

**Comment by forki** [comment]
Mhm that's a strange situation. Normally nuget servers shouldn't delete
packages.

It's also a complicated question when we discuss an update to a package
that's already locked to a specific version in the dependencies file.
