### ISSUE TITLE
Failure to get package Zlib.Portable

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/Paket#908]
Doing a paket update in the current FSharp.Data tries to update ZLib.Portable from 1.10.0 to 1.11.0, and fails with this error:

![image](https://cloud.githubusercontent.com/assets/738761/8398084/58ae423c-1dda-11e5-9757-3e00319dc0d7.png)

**Comment by forki** [comment]
it did it for me without any issues.

**Comment by ovatsus** [comment]
I can still repro it now

**Comment by ovatsus** [comment]
Humm, did a paket update -f, and the error went away, weird

**Comment by forki** [comment]
I fixed that caching bug, so next time you don't have to use -f
