### ISSUE TITLE
Make "paket auto-restore on" stateful

### ISSUE THREAD

**Issue by iainnicol** [fsprojects/Paket#909]
It would be nice if "paket auto-restore on" could persist the fact you have turned auto restore on.  Then "paket add" could check the state of paket auto-restore, and if necessary rerun "paket auto-restore on".

This would be useful for the following scenario.  You turn "paket auto-restore on".  Then, much later, you add a new project to a solution.  You do a "paket add" to the new project.  At the moment, you need to do another "paket auto-restore on" to be able to build the new project from Visual Studio.

**Comment by forki** [comment]
maybe we should add that to the options in the dependencies file.

**Comment by matthid** [comment]
Is this still relevant?

**Comment by iainnicol** [comment]
I think so.  But I can't object to closing enhancement requests which nobody (myself included) is likely to implement.

**Comment by matthid** [comment]
I mean especially considering the new sdk and dotnet-core where auto-restore is basically included in the design ...

**Comment by matthid** [comment]
But yeah we really need to trim down the issues list a bit :/

**Comment by iainnicol** [comment]
Ah.  Not sure.  I'm guessing it's still a problem with classic .NET Framework.  But as you say it's hopefully improved wiith .NET Core.

Regardless, let's just keep this closed.
