### ISSUE TITLE
paket install (+update?) should not overwrite EmbedInteropTypes flag

### ISSUE THREAD

**Issue by agross** [fsprojects/Paket#910]
We have a nuget-packaged dependency that requires to be referenced with the `EmbedInteropTypes` set to true. I know that nuget's install.ps1 could be used to set the flag and that paket doesn't support PowerShell (which is a good thing):

``` xml
<Reference Include="Interop.Foobar">
  <HintPath>..\packages\Interop.Foobar.dll</HintPath>
  <EmbedInteropTypes>True</EmbedInteropTypes>
</Reference>
```

While we can certainly set the flag ourselves, `paket install` (even without `--hard`) will remove the flag.

It would be great if `EmbedInteropTypes` was kept.

**Comment by forki** [comment]
does this thingy have `<paket>true</paket>`?

**Comment by agross** [comment]
Yes, I just copied our pre-Paket reference.

**Comment by forki** [comment]
ok. then try to set the falg to false.

that said: I think we should add that to our settings, so that paket can generate that itself.

**Comment by agross** [comment]
I think it'll probably be the best if paket migrates all custom flags and just manages the `HintPath` element. What do you think?

**Comment by forki** [comment]
Maybe, but that's not really easy with the current design.

Currently we do on every install:
1) delete existing paket = true nodes
2) add nodes for all packages where we can't find an existing node

**Comment by agross** [comment]
So if we just manually reference the DLL paket won't re-add the node with paket=true?

(The dep doesn't need TargetFramework-specific nodes.)

**Comment by forki** [comment]
Yes. At least as long as you don't use --hard. But I'm not completely sure
about the other libs. I assume they will be ignored as well.

**Comment by matthid** [comment]
Closing as the interest doesn't seem to be high and new sdk things are different anyway.
