### ISSUE TITLE
Make source dependency internal

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#912]
It would be great to be able to make the source dependency internal. I'm trying to reference Aether and Chiron: https://github.com/xyncro/aether/blob/master/src/Aether/Aether.fs, https://github.com/xyncro/chiron/blob/master/src/Chiron/Chiron.fs but want them to be internal to the library I'm referencing them into.

**Comment by forki** [comment]
yeah this is on the plan, but it's a big feature. @tpetricek used manual fsi files to work around this.

**Comment by haf** [comment]
Yes, I currently have a post-install task in my rakefile that uses a regex (lol).

**Comment by haf** [comment]
Closing due to lack of response.
