### ISSUE TITLE
Incorrect dependency version created when running paket pack

### ISSUE THREAD

**Issue by roji** [fsprojects/Paket#916]
To reproduce:
* Create a solution with two projects, one referencing the other
* Run `paket pack` as follows: `.paket/paket.exe pack output nupkgs buildconfig Release version 1.1.1-beta001`. The leading zeros in the nuget version are important.
* Paket will create two nugets with the correct version. However, if you open the nuspec for the projects, you will find that the nuget dependency version will be 1.1.1-beta1, *without* the leading zeros.

Of course this means that the produced nupkgs are pretty much unusable...

**Comment by roji** [comment]
@damageboy watch this

**Comment by baronfel** [comment]
can you try this again with a version higher than 1.19?  I could not reproduce once I tried on 1.19.2.

![image](https://cloud.githubusercontent.com/assets/573979/8679751/2e3ec270-2a22-11e5-8395-daa53ba84b5d.png)

**Comment by roji** [comment]
Looks good, thanks!
