### ISSUE TITLE
Exclude directories from processing

### ISSUE THREAD

**Issue by danielmue** [fsprojects/Paket#918]
Hello,

**What**: 
It would be nice if I could tell *Paket* to ignore specific directories from processing (`paket install`).

**Why**: 
We added git submodules to our repository and some (sub) projects use *Paket* as well. During `paket install` it detects ALL paket.reference files and replaces the DLL reference paths accordingly.

Example:
```diff
     <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0')">
       <ItemGroup>
         <Reference Include="System.Reactive.Core">
-          <HintPath>..\..\..\..\packages\Rx-Core\lib\net40\System.Reactive.Core.dll</HintPath>
+          <HintPath>..\..\..\..\..\..\packages\Rx-Core\lib\net40\System.Reactive.Core.dll</HintPath>^M
           <Private>True</Private>
           <Paket>True</Paket>
         </Reference>
```

The sub modules should not use the root/packages directory. The directory root/submodule path/packages makes much more sense. The root/paket.dependencies and root/paket.lock shouldn't apply sub modules dependencies.

**Proposal**:

*a.)*
Add a paket.ignore file that contains directory names to ignore.

```
+ <root>
|-+ submodules
  |-- paket.ignore
  |-+ submodule-1
    |-- .git
  |-+ submodule-2
    |-- .git
```

File content of paket.ignore (maybe regex?):
```
submodule-1
submodule-1
```

*b.)*
Paket recognises the sub directory's paket.lock + paket.dependencies files and processes the sub folder independently.

Greetings,
Daniel

**Comment by agross** [comment]
Ad *a)*: An empty file would be OK as well to exclude everything below the directory `paket.ignore` is in.

**Comment by danielmue** [comment]
@agross: if the *paket.ignore* file supports regular expressions as pattern, you could just add ```.*``` as file content.

**Comment by forki** [comment]
I like the idea of just stopping if we find another paket.dependencies file. This will help here and avoids lots of confusion.

**Comment by danielmue** [comment]
Cool! Thanks!
