### ISSUE TITLE
`install` doesn't install newest possible version

### ISSUE THREAD

**Issue by fbehrens** [fsprojects/Paket#925]
Hi, I don't know if this is an issue, so please bear with me.

    >type paket.dependencies
    source https://nuget.org/api/v2
    nuget FAKE

    c:\kata\sol\runner>paket install
    Resolving packages:
     - FAKE 3.37.1
     - FAKE 3.37.0
     - FAKE 3.36.0
    Locked version resolution written to c:\kata\sol\runner\paket.lock
    Downloading FAKE 3.36.0 to C:\Users\imbeh\AppData\Local\NuGet\Cache\FAKE.3.36.0.nupkg
    FAKE 3.36.0 unzipped to c:\kata\sol\runner\packages\FAKE
    56 seconds - ready.

I would expect, that paket would install version 3.37.1 as it is the newest, which fits the nonexistent version restrictions.

**Comment by forki** [comment]
I unlisted these two versions since it contained a bug. So paket does the right thing
