### ISSUE TITLE
Forced to put 'File:source.ext [dest]' directive in top of paket.references

### ISSUE THREAD

**Issue by gsscoder** [fsprojects/Paket#926]
I've recently put dependencies of this [mine open](https://github.com/gsscoder/commandline) source project in Paket hands, because among other goodies I appreciate the ability to set a dependency to a GitHub source file.

When trying to use this feature I was able to get it working only when putting the `File:...` directive in the top of [paket.references](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/paket.references).
This not worked for me:
```
FSharp.Core
File:Maybe.cs Infrastructure
```
This worked:
```
File:Maybe.cs Infrastructure
FSharp.Core
```
Thanks for this wonderful tool! :)

**Comment by forki** [comment]
mhm. this is strange. Paket itself has it the other way around (see https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/paket.references).

I just tried to reproduce in you project, but it works for me in any order.

**Comment by gsscoder** [comment]
@forki, you're right this is strange. Anyway I close the issue, since after the PR everything work as expected.

Again, thanks for support.

Giacomo
