### ISSUE TITLE
"paket update" installs pre-release versions

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket#927]
I used "paket update" today and got Autofac 4.0.0-alpha2 plus the whole .NET Framework 4 beta installed. I do not have any options for pre-release installation in paket.dependencies file.

**Comment by forki** [comment]
Could you please tell us your dependencies file?

**Comment by alexeyzimarev** [comment]
Sure

source https://nuget.org/api/v2

nuget Plivo
nuget angular-bootstrap-switch
nuget angular-idle.TypeScript.DefinitelyTyped
nuget angular-strap
nuget angular-translate.TypeScript.DefinitelyTyped
nuget angular-ui-bootstrap.TypeScript.DefinitelyTyped
nuget angular-ui-router.TypeScript.DefinitelyTyped
nuget Angular.UI.Bootstrap
nuget Angular.UI.UI-Router
nuget AngularJS.Animate
nuget AngularJS.Locale
nuget AngularJS.Messages
nuget AngularJS.Resource
nuget AngularTranslate.LoaderUrl
nuget Autofac.SignalR framework: >= net45
nuget AutoMapper framework: >= net45
nuget Ix-Main framework: >= net45
nuget ladda-bootstrap
nuget ladda.TypeScript.DefinitelyTyped
nuget Microsoft.AspNet.Mvc framework: >= net45
nuget Microsoft.AspNet.SignalR framework: >= net45
nuget Microsoft.AspNet.Web.Optimization framework: >= net45
nuget Microsoft.Azure.WebJobs framework: >= net45
nuget Microsoft.Web.WebJobs.Publish framework: >= net45
nuget Modernizr framework: >= net45
nuget NServiceBus.Azure >= 6.0.0 framework: >= net45
nuget NServiceBus.Azure.Transports.WindowsAzureServiceBus >= 6.0.0 framework: >= net45
nuget ServiceStack.Authentication.RavenDB 3.9.71 framework: >= net45
nuget ServiceStack.Host.Mvc 3.9.71 framework: >= net45
nuget signalr.TypeScript.DefinitelyTyped
nuget stripe.TypeScript.DefinitelyTyped
github ocombe/ocLazyLoad dist/ocLazyLoad.js
nuget pace.js
nuget metisMenu
nuget Jquery.slimScroll
nuget jquery.slimScroll.TypeScript.DefinitelyTyped
nuget Serilog.Sinks.Loggr
github g00fy-/angular-datepicker dist/index.js
github g00fy-/angular-datepicker dist/index.css
nuget oclazyload.TypeScript.DefinitelyTyped

**Comment by alexeyzimarev** [comment]
I tried to remove Autofac 4 alpha and all its .NET Framework 4 beta dependencies from paket.lock file, remove all these new packages from the packages folder and run paket update again, the result is the same.

**Comment by forki** [comment]
from the generated lock file:

    Autofac.SignalR (3.0.2) - framework: >= net45
      Autofac (>= 3.1.3-CI-027)

so I'm not claiming paket is correct, but let's try to anayze this. Autofac.SignalR is needing a version at least 3.1.3-CI-027. the `-CI...` is what paket uses to accept prereleases. Then Paket resolves to 4.0.0-alpha2. Sounds OKish to me.

**Comment by forki** [comment]
if you add ´nuget Autofac` to your dependencies file, you'll override this prerelease dependency and it will resolve to Autofac (3.5.2).

**Comment by alexeyzimarev** [comment]
I see. I will add version constraint on both packages to have ~>3, thanks.

**Comment by forki** [comment]
thanks.

Still the questions remains: does this behaviour make sense to you?
