### ISSUE TITLE
Binding redirect for FSharp.Core is wrong for F# 4.0 project

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [fsprojects/Paket#929]
I'm using VS 2015, and I have a project set to use .NET 4.6 and F# 4.0. My `paket.dependencies` has `redirects: on`, but the `paket install` writes a binding redirect to the `app.config` file, which is correct for F# 3.1, but wrong for F# 4.0.

```xml
<dependentAssembly>
  <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
</dependentAssembly>
```

For F# 4.0, this should be `4.4.0.0`.

**Comment by isaacabraham** [comment]
hmmmmm. There's no support currently (IIRC) in the binding redirects code which looks at the version of .NET to use. The only reason a BR for FSharp.Core will exist will (again, IIRC) be if some code has a dependency on that version of FSCore.

**Comment by Bananas-Are-Yellow** [comment]
My solution is a mixture of F# 3.1 and F# 4.0 at the moment.

This is because I'm using WebSharper and this doesn't support F# 4.0 yet, so those projects are still using F# 3.1, and I am ignoring the warnings you get when a F# 3.1 project references a F# 4.0 project:

    warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.

Soon WebSharper will support F# 4.0, so these warnings are a temporary situation, and I'll then have all my projects using F# 4.0.

My top level projects (3 Azure worker roles and one console app) are using F# 4.0, but they are getting a binding redirect to 4.3.1.0. I have to manually edit the app.config files to correct this, otherwise I get missing method exceptions.

My paket.lock file is:

    REDIRECTS: ON
    FRAMEWORK: NET451, NET46
    NUGET
      remote: https://www.nuget.org/api/v2
      specs:
        FSharp.Azure (1.0.2)
          FSPowerPack.Linq.Community (>= 3.0.0.0)
          WindowsAzure.Storage (>= 3.1.0.1)
        FSharp.Collections.ParallelSeq (1.0.2)
        FSharp.Control.AsyncSeq (2.0.1) - framework: net451, net46
        FSharp.Core (3.1.2.5) - framework: net451, net46
        ...

It shows F# 3.1.

Is this what you would expect?

**Comment by forki** [comment]
if you use the FSharp.Core package then there is no 4.0 version at the moment

**Comment by isaacabraham** [comment]
Yes this is what I would expect. The BR code just iterates through any strong named dlls and adds one BR for each of them.

Maybe we could add the ability to override this somewhere in e.g. Dependencies file?

**Comment by forki** [comment]
why? If you use the package then everything should work fine, right?

2015-07-23 9:54 GMT+02:00 Isaac Abraham <notifications@github.com>:

**Comment by Bananas-Are-Yellow** [comment]
I'm not using the FSharp.Core package. I have no mention of FSharp.Core in my paket.dependencies or any paket.references file. I am using VS 2015, which includes F# 4.0. So I just set the project properties to use F# 4.0.

**Comment by forki** [comment]
but your lock file shows it.

**Comment by Bananas-Are-Yellow** [comment]
I'm guessing that some of the packages that I do use are themselves using FSharp.Core (F# 3.1), even though I'm not specifying it directly. My F# 4.0 projects have references for F# 4.0, but your traversal does not consider this, I assume.

**Comment by forki** [comment]
> but your lock file shows it. So you are using it indirectly. That explains the redirects

**Comment by Bananas-Are-Yellow** [comment]
A typical F# project contains:

    <ItemGroup>
      <Reference Include="mscorlib" />
      <Reference Include="FSharp.Core, Version=$(TargetFSharpCoreVersion), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Private>True</Private>
      </Reference>
      <Reference Include="System" />
      <Reference Include="System.Core" />
      <Reference Include="System.Numerics" />
    </ItemGroup>

These are not packages, but are installed as part of VS 2015. If you set the F# version to 4.0 in the project properties, VS 2015 adds this to your app.config file:

      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="2.0.0.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="2.3.0.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="2.3.5.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="4.0.0.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="4.3.0.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="3.3.1.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="2.3.5.1" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="3.78.3.1" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="3.259.3.1" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="4.3.1.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="3.47.4.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="3.78.4.0" newVersion="4.4.0.0" />
        <bindingRedirect oldVersion="3.259.4.0" newVersion="4.4.0.0" />
      </dependentAssembly>

No idea why it uses multiple redirects for specific old versions, rather than a single redirect for a range of old versions, but that's what it does.

Then `paket install` edits this and you get:

    <dependentAssembly>
      <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
      <bindingRedirect oldVersion="2.3.0.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="2.3.5.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="4.0.0.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="4.3.0.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.3.1.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="2.3.5.1" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.78.3.1" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.259.3.1" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="4.3.1.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.47.4.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.78.4.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.259.4.0" newVersion="4.4.0.0" />
    </dependentAssembly>

Notice that paket replaced the first redirect. I don't know if it's even documented what should happen if you have more than one redirect for the same old version. Perhaps the last one wins? But anyway, the version mentioned in my paket.lock file is 3.1.2.5, which is not in this list of specific versions, so it should be redirected by your redirect to 4.3.1.0, which creates my problem.

**Comment by Bananas-Are-Yellow** [comment]
If you use the Add Reference command on a project, and look under Assemblies, there are many assemblies, which are installed. Some of these also exist as NuGet packages (e.g. System.Numerics.Vectors), so FSharp.Core is not a special case. I guess this means that when you consider the version requirements for each package, you should also take a look at the existing (i.e. non-Paket) references in the project file too?

**Comment by isaacabraham** [comment]
Hmmm, I think paket should remove all the other nodes - we don't want conflicts between BRs, they're confusing enough as it is!

So one could add some "special" case to exclude FSharp but I'm not overly keen on that idea. What dll is referenced by your project - FS3.x or FS4.x? Or both?

**Comment by isaacabraham** [comment]
@Bananas-Are-Yellow that's correct, the code doesn't look at project references - it just looks at DLLs in  packages. I suppose the thought behind this is if you're using paket for package management, you should rely on that rather than mixing / matching between two.

I suspect that this issue would be solved if / when 4.x of the FSharp Core nuget package is released? cc: @forki

**Comment by forki** [comment]
Yes using the 4.0 package would work. But it's not available yet

**Comment by Bananas-Are-Yellow** [comment]
I'd be happy for you to remove all those individual redirects and replace them with a single one, so long as it redirects to 4.4.0.0 in this case.

**Comment by isaacabraham** [comment]
So currently it won't redirect to 4.4.0.0 because we don't look at project references - we just use the packages in paket. Once FSharp Core 4.4 is released, that will solve this issue.

But we shouldn't leave conflicting BRs in the config file either way.

**Comment by Bananas-Are-Yellow** [comment]
[Notes and Guidance on FSharp.Core](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html) says:

_FSharp.Core is also available as a NuGet package. It is not yet normal to reference FSharp.Core via this package, though it is used by Xamarin application templates and by some F# library packages (as a transitive NuGet dependency)._

You can read the rest of that section.

The article contains quite a lot of information. It says _applications_ should use **AutoGenerateBindingRedirects**, and in fact this is added to console apps anyway. This means that when MyConsole.exe.config is generated from the app.config file, it corrects any binding redirects. So the 4.3.1.0 redirect appears as 4.4.0.0 in my MyConsole.exe.config file.

As mentioned earlier, I have 3 Azure worker roles and one console app. So it seems the console app does not have a problem, but the worker roles do. They are class libraries, but I'm guessing that the Azure framework reads the config file anyway when it hosts them. I tried adding **AutoGenerateBindingRedirects** to those projects, but this made no difference. Perhaps this is ignored for a class library.

**Comment by Bananas-Are-Yellow** [comment]
Outdated packages found:
      * FSharp.Core 3.1.2.5 -> 4.0.0.1

OK, that's my problem solved. It would still be nice if you could remove all the redundant redirects that VS put there, just to be tidy and safe.

(By the way, you can ignore my comment about 3.1.2.5 not being in the list. I was confusing package versions and assembly versions.)

**Comment by forki** [comment]
> It would still be nice if you could remove all the redundant redirects that VS put there, just to be tidy and safe.

I agree ;-) PRs are very welcome.
