### ISSUE TITLE
What to download and how to install Paket?

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/Paket#930]
It's not really clear to me what to download when I click on the download link. It lists
- paket.bootstrapper.exe
- paket.exe
- paket.targets

Do I need all of these files? Where should I put them? Is one of them an installer that puts them in the right places? What is the bootstrapper for?

**Comment by forki** [comment]
Mhm seems the "getting started" doesn't make this clear. I will update that. 

So in short:

* create a .paket folder in the root of your repo 
* download bootstrapper and targets file to it 
* commit both files
* whenever you run the bootstrapper it will download the latest paket.exe (so do this at the beginning of your build) 
* add paket.exe to the gitignore

**Comment by exercitusvir** [comment]
Thanks for the quick reply. I found out by trying that if you simply put the bootstrapper in the root of your solution folder and execute it, it will create the .paket folder, download paket.exe into the same folder, download paket.targets and place paket.targets in the .paket folder and also another copy of the bootstrapper in the .paket folder. So all you need to add to "Getting Startet" is to download the bootstrapper, place it in the root of your solution folder and execute it since it will take care of the rest. But you will then have the bootstrapper in both the solution folder and another copy in the .paket folder.

Another thing that is not clear to me is the difference between paket.dependencies and paket.references after reading the documentaion, but I will create another issue for this.

**Comment by exercitusvir** [comment]
Another question. You said to add paket.exe to the gitignore. What about the bootstrapper? Should git I ignore or commit that?

**Comment by forki** [comment]
commit the bootstrapper (it's small) and gitignore the huge paket.exe (but you have to run bootstrapper during build to restore paket.exe)

**Comment by exercitusvir** [comment]
I see, thanks!

**Comment by exercitusvir** [comment]
One last question. Why is the bootstrapper copied to the .paket folder? Which one should my build run? The one which I originally placed in the solution folder oder the one in the .paket folder?

**Comment by forki** [comment]
You should only have the one in the paket folder.

**Comment by exercitusvir** [comment]
I find it interesting that the bootstrapper does different things depending on from where it's run.

It acts like an installer if you run it from the solution folder without a .paket folder where it will download everything and put it in the right places.

But if you run it from the .paket folder, it only downloads .paket (but not paket.targets). Is this intended behavior?

**Comment by exercitusvir** [comment]
And should both installation approaches be documented (the one you described and the one I found out)?

**Comment by forki** [comment]
I assume one did a "paket init"

**Comment by exercitusvir** [comment]
But `paket init` creates only an empty paket.dependencies file according to the documentation. Running the bootstrapper from the solution directory:
- creates .paket folder
- places paket.targets into the .paket folder
- places paket.exe into the .paket folder
- places the bootstrapper into the .paket folder
- places paket.exe into the solution folder

So it acts like an installer that also places a redundant copy of paket.exe in the solution folder.

**Comment by forki** [comment]
ok then http://fsprojects.github.io/Paket/paket-init.html is outdated

**Comment by exercitusvir** [comment]
Does that mean that running the bootstrapper from the solution directory executes the `paket init` command that does all those things I described?

**Comment by forki** [comment]
I created http://fsprojects.github.io/Paket/getting-started.html please send corrections to this.

**Comment by mark4asp** [comment]
Still not quite crystal clear.
Q1: When I run paket should I be running it via: the Windows shell, Powershell, or VS Package Manager Console, ...
Q2: When converting from a mixed system e.g. Nuget installed and some directly referenced assemblies, with different versions of an assembly in different projects.  What does paket do for the solution as a whole. Does it update all references in every project to the latest assembly?

PS: Not everyone who wants to use paket is able to use git.  So, perhaps discussion of git could be left as an option rather than assume everyone might use the option.

**Comment by forki** [comment]
Q1: it doesn't matter. Paket is a command line tool and should work from all of the above.
Q2: paket convert will only touch the nuget references

Regarding git: most paket features have nothing to do with git. I don't really understand the question
