### ISSUE TITLE
Paket duplicates assembly reference for Microsoft.Net.Http nuget package

### ISSUE THREAD

**Issue by SavaNDragos** [fsprojects/Paket#932]
An old issue concerning the way Microsoft.Net.Http and System.Net.Http.WebRequest  are resolved started to appear again with the latest versions. 
The problem is that we will have a reference to .Net framework's System.Net.Http assembly and one to the one from packages ..\..\..\packages\System.Net.Http\lib\net40\System.Net.Http.dll
Error: "An assembly with the same identity 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references."	

    <Choose>
      <When Condition="($(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6')) Or ($(TargetFrameworkIdentifier) == 'MonoAndroid') Or ($(TargetFrameworkIdentifier) == 'MonoTouch')">
        <ItemGroup>
          <Reference Include="System.Net.Http">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.Net.Http.WebRequest">
            <Paket>True</Paket>
          </Reference>
        </ItemGroup>
      </When>
    </Choose>
    <Choose>
      <When Condition="($(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6')) Or ($(TargetFrameworkIdentifier) == 'MonoAndroid') Or ($(TargetFrameworkIdentifier) == 'MonoTouch')">
        <ItemGroup>
          <Reference Include="System.Net.Http.WebRequest">
            <HintPath>..\..\..\packages\System.Net.Http\lib\net40\System.Net.Http.WebRequest.dll</HintPath>
            <Private>True</Private>
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.Net.Http">
            <HintPath>..\..\..\packages\System.Net.Http\lib\net40\System.Net.Http.dll</HintPath>
            <Private>True</Private>
            <Paket>True</Paket>
          </Reference>
        </ItemGroup>
      </When>
    </Choose>

**Comment by forki** [comment]
do you have a repro sample for me?

**Comment by forki** [comment]
clsoing since no repro was given

**Comment by forki** [comment]
I assume this is fixed with #1333
