### ISSUE TITLE
How to restrict dependencies to specific profiles

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/Paket#933]
The documentation only explains how to restrict framework versions. I've tried adding the following to the paket.dependencies file:

framework: portable-net45+netcore45

which then generates conditional references for a selection of portable profiles. And it does not seem to matter which profile I specify after `framework:`. It seems to be always the same selection of portable profiles.

How can I restrict it to let's say specific portable profiles such as `Profile7` or `Profile259`. Or a list of specific profiles? Is it also possible to specify something like "all portable profiles that include for support .NET Framework 4.5 and Windows 8"?

**Comment by forki** [comment]
I guess portable profiles are not yet supported in framework restrictions. Nobody wanted to use this yet

**Comment by forki** [comment]
do you have a repro for me?

**Comment by exercitusvir** [comment]
Paket changes its behavior though when I place a portable profile in the framework line. For example, create the following paket.dependencies file:

> source https://www.nuget.org/api/v2/

> framework: portable-net45+netcore45
> nuget FSharp.Core

It will generate a selection of portable profiles in the MSbuild project files.

**Comment by forki** [comment]
yes, but I never tested that case.
