### ISSUE TITLE
paket convert-from-nuget changes solution file from Unicode encoding to ANSI encoding

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/Paket#934]
I noticed that after running `paket convert-from-nuget` it changed my solution file from Unicode encoding to ANSI encoding.

**Comment by theimowski** [comment]
Been a while, I'll have a look at weekend ;)

**Comment by forki** [comment]
thx Tomasz!

**Comment by theimowski** [comment]
no probs! it's a pleasure

**Comment by exercitusvir** [comment]
Awesome. Thanks!
