### ISSUE TITLE
How to resolve conflicts?

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/Paket#936]
I added `FSharp.Core` to paket.references of one project. I then reference that project from another project which includes `FSharp.Data` in its paket.references. I now get conflicts because both projects reference different versions of `FSharp.Core`. Is there a way to resolve version conflicts like this?

**Comment by forki** [comment]
yes there are ways to solve this, but unlike nuget which just does "something random", you need to resolve this yourself. There is no silver bullet for conflict resolution. Different conflicts need different resolution strategies. 

1) In the FSharp.Data case: what is the other package and what FSharp.Core does it use? Usually we try to update everything to latest.

2) in order to resolve it manually use the `==` operator in your dependencies file.  http://fsprojects.github.io/Paket/nuget-dependencies.html#Use-exactly-this-version-constraint 

then run `paket install --redirects`.

**Comment by exercitusvir** [comment]
For some reason, one used version 3.3.1.0 (I don't actually understand where this is coming from) and the other used version 3.259.3.1 (which is used by Profile259).

**Comment by forki** [comment]
that's weird. they should use the same package

**Comment by exercitusvir** [comment]
I think I know why this happens. The F# Core version gets special treatment in fsproj files because it uses the `TargetFSharpCoreVersion` tag specified at the top to chose the desired version, which was `3.259.3.1` in my case. But paket ignores that when it choses a version because it only looks at the `TargetFrameworkVersion` and `TargetProfile` tags. So when I specified `Profile7` in the `TargetFrameworkProfile` tag because FSharp.Data needs that, paket would also reference the FSharp.Core version for `Profile7`, which is version 3.3.1.0. But the other projects would use version `3.259.3.1`.

**Comment by forki** [comment]
but 3.259.3.1 is not a correct nuget version - see https://www.nuget.org/packages/fsharp.core

**Comment by exercitusvir** [comment]
How so? If you check the version of FSharp.Core in the folder `portable-net45+netcore45+wpa81+wp8` (.NET Portable Profile 259) it says 3.259.3.1.

**Comment by forki** [comment]
that's a file version right? not the nuget package version

2015-07-23 22:01 GMT+02:00 exercitusvir <notifications@github.com>:

**Comment by forki** [comment]
after rereading. I think you talk about a file conflict, not a nuget version conflict.
try `paket install --hard`

**Comment by exercitusvir** [comment]
Yes, that was both the file version and assembly version. I got an assembly version conflict.

Btw, FSharp.Core on nuget has version 4.0 (4.0.0.1) as of today.

**Comment by forki** [comment]
Yes I know. I helped to put it there ;-)

**Comment by exercitusvir** [comment]
I just realized that you are owner of FSharp.Core, so I guess you already knew ;-)
