### ISSUE TITLE
paket install takes 31 seconds

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#939]
Was 6 seconds.

Version 1.21.1

**Comment by forki** [comment]
oups?!

Just for cross-checking, can you reproduce the fast result with an older version (or is the nuget server slower after nuget 3.0 release). 
Do you already know which version has degraded perf?

**Comment by vasily-kirichenko** [comment]
I mentioned the issue yesterday. Will try to reproduce fast behavior on an older version.

**Comment by vasily-kirichenko** [comment]
Tested it on 1.19.3. 6 seconds.

**Comment by vasily-kirichenko** [comment]
Cannot reproduce it anymore. Must was a local or nuget server issue. Closing it.
