### ISSUE TITLE
Project templates are not found and are coming up as incomplete.

### ISSUE THREAD

**Issue by RandallDavis** [fsprojects/Paket#943]
I'm experiencing two failures with project templates that might be related:
1. Running ``pack`` without specifying a ``templatefile`` results in no files being added to the output directory. 
2. When specifying the ``templatefile`` for the project, I get the error _"There was an attempt to pack incomplete template file..."_.

I'm working in a solution with more than one F# project and have created AssemblyInfo.fs files for both.

I've created a sample solution that illustrates this [here](https://github.com/RandallDavis/Paket-sample-for-issue-943).

**Comment by inosik** [comment]
1. Your Template-Files are named `packet.template`, so Paket simply can't find them.

2. Template files with `type project` have to be matching, which means they have to be named `paket.template` or `Project.fsproj.paket.template`, as stated in the [docs](http://fsprojects.github.io/Paket/template-files.html). That's why Paket fails, as it can't find the matching project, to get the missing infos from.

Maybe we should show a better error message for such cases.

**Comment by forki** [comment]
yes I was just about to write 1) - rename it to paket.template without the c

**Comment by RandallDavis** [comment]
Sorry about the oversight in the template file name. It's been fixed, and I'm still experiencing the same behavior. I also added a few new projects to the solution to cover different potential use cases, but they're all failing the same way.

**Comment by forki** [comment]
your repro worked with pack (without specific template file) after the rename.

With latest alpha version it also worked with specific template file

**Comment by RandallDavis** [comment]
Okay - I tested with the latest version of whatever the bootstrapper pulls in (I'm assuming this isn't alpha). When I run ``paket pack output nugets``, I'm getting a success message, but no files are being put in /.paket/nugets/.

**Comment by forki** [comment]
did you try `.paket\paket pack output nugets` maybe it's just started from wrong folder!?

**Comment by RandallDavis** [comment]
Okay - that did it!

When I run ``paket pack output nugets`` from within the .paket folder, it says it succeeds and creates the nugets directory. Going up to the solution directory and running ``.paket\paket pack output nugets`` crawls everything successfully.

Thanks a ton

**Comment by forki** [comment]
yeah it just looks down. never up
