### ISSUE TITLE
"paket update nuget XXX" should report why it decides not to

### ISSUE THREAD

**Issue by et1975** [fsprojects/Paket#946]
if paket decides not to update the package it was explicitly asked to update it should at least tell me why. 
As it is, neither the return code nor the message tell me what happened - in my case dependency of the package was requiring an upgrade as well.

**Comment by forki** [comment]
Do you have a specific sample for me? Deps file + lock file + package you want to update? Would love to improve the output

**Comment by et1975** [comment]
Happened with some private packages, but I'll keep an eye out in my public projects for an opportunity to reproduce it. 
It should be a fairly common scenario though, so I'm wondering what is the expected behavior in this case:
- solution S has a dependency on packages A and B
- package B also has a dependency on package A
- package B has had its A dependency upgraded and the new version of B is released
- solution S upgrades B to latest (or rather fails to, quietly)

In my case the A package was RabbitMQ.Client which happened to have a new _revision_ released.

**Comment by forki** [comment]
Our current algorithm wasn't designed for such questions, but I'd love to
improve it in this direction. So I need good samples.

**Comment by et1975** [comment]
Incidentally, it does upgrade as expected if I specify the version explicitly.

**Comment by forki** [comment]
That is not unusual. Often there's more than one valid resolution.
Specifying more restrictions (concrete versions) leads to picking another.

**Comment by mrinaldi** [comment]
I have a repro case here:

paket.dependencies:
```
source https://nuget.org/api/v2

nuget Ninject.Extensions.Interception
nuget Ninject.Extensions.Logging.Log4Net
```

paket.lock
```
NUGET
  remote: https://nuget.org/api/v2
  specs:
    log4net (2.0.3)
    Ninject (2.2.1.4)
    Ninject.Extensions.Interception (2.2.1.2)
      Ninject (>= 2.2.0.0 < 2.3.0.0)
    Ninject.Extensions.Logging (2.2.0.4)
      Ninject (>= 2.2.0.0 < 2.3.0.0)
    Ninject.Extensions.Logging.Log4net (2.2.0.4)
      Ninject.Extensions.Logging (>= 2.2.0.0 < 2.3.0.0)
      log4net (>= 1.0.4)
```

```paket update nuget Ninject.Extensions.Interception```
Outputs:
``` 
Paket version 1.28.0.0
Updating Ninject.Extensions.Interception in D:\Projects\paket-test\paket.dependencies
Resolving packages:
 - Ninject.Extensions.Interception 3.2.0
 - Ninject.Extensions.Interception 3.0.0.8
 - Ninject.Extensions.Interception 2.2.1.2
 - Ninject 2.2.1.4
D:\Projects\paket-test\paket.lock is already up-to-date
3 seconds - ready.
```

It gives no clue at all of why it didn't update.

I was wondering if we should have a parameter to force the update of conflicting dependencies, like nuget does OOB.
If you think in this case specific, unless you update all packages, you are in a dead end.
