### ISSUE TITLE
Does paket.dependencies allow to use a local folder as nuget source?

### ISSUE THREAD

**Issue by wezhu** [fsprojects/Paket#950]
I cannot find it in [paket.dependencies] (http://fsprojects.github.io/Paket/dependencies-file.html), I am wondering:
1. Can it specify more than one Nuget source?
2. Can it use a local folder that contains nuget packages as Nuget source?

Thanks!

**Comment by forki** [comment]
1) yes 
 
    source https://nuget.org/api/v2     // nuget.org
    nuget package1
    source http://myserver/nuget/api/v2 // custom feed
    nuget package2

2) yes, see http://fsprojects.github.io/Paket/nuget-dependencies.html#Path-sources

**Comment by wezhu** [comment]
Thanks. Sorry for not reading the docs thoroughly ...
