### ISSUE TITLE
"Forced" convert-from-nuget doesn't add paket.targets to converted projects

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#951]
If you have a mixture of paket and nuget projects and want to convert the outstanding ones to paket, you can use ``force`` mode of ``convert-from-nuget``. Unfortunately it doesn't look like it adds the ``paket.targets`` msbuild task to the converted projects, so you have to manually do this either by hand or by called ``paket auto-restore`` on those projects.

The behaviour with normal convert-from-nuget is to automatically run this; the forced mode should do that also.

**Comment by theimowski** [comment]
@isaacabraham do you have auto restore set up for NuGet? 
Browsing through the code i can see that the paket.targets should always be added to projects on `convert-from-nuget` if auto restore is set up for NuGet, or there exists a `.nuget/nuget.targets` file in the working directory
