### ISSUE TITLE
Should `paket init` add the dependencies file to the solution

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsprojects/Paket#953]
@forki wrote a great new [Getting started](http://fsprojects.github.io/Paket/getting-started.html) guide yesterday that makes it very clear how to get going with Paket.

It currently advises to create the `paket.dependencies` file by hand, although there is also the `paket init` command that can do that.
However, `paket init` does not add the file to the actual solution, so that would have to be done manually afterwards, while it is a direct part of the process when the file is created by hand from within the IDE. Thus, it may be irritating to run `paket init` and not seeing anything happen inside your project (which is of course only an issue if you have little or no experience with Paket).

@forki suggested `paket init` could just do that as well, and while it would be a slightly better integration, I'm not sure whether it should, for a few reasons:

- It would have to *find* the solution, which is not necessarily on the top level of the repository - and may not even be unambiguously identifiable. [AutoFixture](https://github.com/AutoFixture/AutoFixture)'s project structure for example shows both of these problems. Finding the solution could just be done with a recursive directory search, but if there's more than one, that would at least mean adding another step maybe along the lines of `paket add -i`.
- It would have to put the file in one specific location in the .sln (probably the root level), which may not be where the user wants it. Of course, they can move it around afterwards, but that's not easier anymore than adding it by hand in the first place.
- It would prompt a reload of the solution inside the IDE, which is bad if the solution has unsaved changes, because you'll lose either those or the adding of the dependencies file.

**Comment by CumpsD** [comment]
I don't think `paket init` should change `.sln` files. At least not by default, with a flag, perhaps, but even then, it'd be very opiniated, meaning people will always complain anyway.

**Comment by TeaDrivenDev** [comment]
What if that flag/switch also took a solution folder name for the file as a parameter? Would that get too complicated compared to doing it manually?

I kind of like that idea, though; it would stay out of your way if you don't really want it. The only issue I see that would likely occur frequently is the problem with unsaved changes to the .sln in the IDE, but the only way that can be avoided is simply keeping one's hands off the file.
