### ISSUE TITLE
`paket init` should add the main NuGet feed to the dependencies file by default

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsprojects/Paket#954]
I think it should, because cases where you really *don't* want that should be all but nonexistent, and it's annoying to always have to look that address up.

**Comment by forki** [comment]
Marked as up-for-grabs

**Comment by inosik** [comment]
Paket already adds the default NuGet feed when you add the first package with `paket add nuget xy`. But yes, for people who add their packages by editing `paket.dependencies` this would be useful.

**Comment by TeaDrivenDev** [comment]
Not on `paket init`, only with `paket add`, as you first said.
