### ISSUE TITLE
Using Paket with some NuGet options?

### ISSUE THREAD

**Issue by mmisztal1980** [fsprojects/Paket#955]
Not sure if this has been asked before - if it has, then I apologize.

In one of my build scripts I have the following lines of code : 

```
.nuget\NuGet.exe update -self
.nuget\NuGet.exe install FAKE -ConfigFile .nuget\Nuget.Config -OutputDirectory packages -ExcludeVersion -Version 3.28.8
.nuget\NuGet.exe install xunit.runner.console -ConfigFile .nuget\Nuget.Config -OutputDirectory packages\FAKE -ExcludeVersion -Version 2.0.0
.nuget\NuGet.exe install nunit.runners -ConfigFile .nuget\Nuget.Config -OutputDirectory packages\FAKE -ExcludeVersion -Version 2.6.4
```

How do I achieve the same result as above with Paket? (How do I use -OutputDirectory or -ExcludeVersion NuGet flags ?)

Best regards

**Comment by forki** [comment]
Paket's default is to exclude the version from the path. For rare cases
where you need the version in the path you can do this
http://fsprojects.github.io/Paket/nuget-dependencies.html#Putting-the-version-no-into-the-path

Regarding output folder. We're pretty opionated about this. There is
currently no switch for that. It's always called "packages"

Not sure if this has been asked before - if it has, then I apologize.

In one of my build scripts I have the following lines of code :

.nuget\NuGet.exe update -self
.nuget\NuGet.exe install FAKE -ConfigFile .nuget\Nuget.Config
-OutputDirectory packages -ExcludeVersion -Version 3.28.8
.nuget\NuGet.exe install xunit.runner.console -ConfigFile
.nuget\Nuget.Config -OutputDirectory packages\FAKE -ExcludeVersion
-Version 2.0.0
.nuget\NuGet.exe install nunit.runners -ConfigFile .nuget\Nuget.Config
-OutputDirectory packages\FAKE -ExcludeVersion -Version 2.6.4

How do I achieve the same result as above with Paket? (How do I use
-OutputDirectory or -ExcludeVersion NuGet flags ?)

Best regards

—
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/955>.
