### ISSUE TITLE
BindingRedirects in paket reference?

### ISSUE THREAD

**Issue by TWith2Sugars** [fsprojects/Paket#958]
It would be nice to say which projects the generated redirects get applied to.

**Comment by isaacabraham** [comment]
That's a good idea. Currently it just blindly goes across every project. Perhaps this could be added to the paket.references file?

**Comment by TWith2Sugars** [comment]
That was my thinking, currently I use the auto generate *proj attribute for most projects. It's the web.config I want to transform.

**Comment by forki** [comment]
yes a switch in references file could be a nice way.

**Comment by isaacabraham** [comment]
Should the default be to assume "yes" and turn off in a specific .references file? e.g. solution with five projects. I want dependency redirected in 2 of those projects. Do you have in the references file that the redirect is "ON" in the files you want (and thus don't specify it in the dependencies file) or mark it in the dependencies file and then exclude from the other three projects?

**Comment by TWith2Sugars** [comment]
How about an extra option:

"some" or something like that which would let us choose which projects to generate the binding redirects.

This would mean existing Paket.dependencies file would be compatible.

**Comment by isaacabraham** [comment]
Don't understand 😊 example please
________________________________

**Comment by TWith2Sugars** [comment]
in paket.dependecies we could have

* *redirect: on* - Standard Behaviour
* *redirect: some* - Apply redirect only to reference files that have **redirect** in them

Something like that?

**Comment by isaacabraham** [comment]
Linked to #808 - adding this could solve the "what is a unit test project?" problem.

**Comment by forki** [comment]
you can set redirects from references files
