### ISSUE TITLE
Pack command doesn't escape filenames correctly

### ISSUE THREAD

**Issue by jamescrowley** [fsprojects/Paket#959]
I think we've identified an issue with the Pack step in Paket, whereby it escapes spaces in folder names correctly, but not file names:

https://github.com/fsprojects/Paket/blob/68614ba680deaccbfc759f08bcd7ba08cdf1c833/src/Paket.Core/NupkgWriter.fs#L261

Pull request to follow. Let me know if I'm mistaken!

**Comment by forki** [comment]
You are probably right.
