### ISSUE TITLE
Allow referencing fsprojs or dlls directly for development

### ISSUE THREAD

**Issue by theor** [fsprojects/Paket#962]
Let's say I have a library X with its matching nuget package. If I'm using it in another project P and fix something in X, I have to either re-publish the X package or add a temporary local nuget source, then paket.exe update in P.

**Comment by forki** [comment]
You can go the other way around and just use normal project references. Paket will replace these to nuget references during paket pack.

**Comment by theor** [comment]
Nice, thanks a lot !  I have to keep the references in the paket files and replace them in the sln?

**Comment by forki** [comment]
Yes you would use paket.template files of type project and just reference
nuget dependencies.
