### ISSUE TITLE
Directories encoded as %2F when creating Nuget packages

### ISSUE THREAD

**Issue by nickbabcock** [fsprojects/Paket#963]
Since July 26th (last time I pushed a nuget package successfully) there seems to be a change in behavior in paket that creates a `nupkg` that instead of directory structure of `lib/net40/` it creates `lib%2Fnet40%2F`, which breaks `paket install` (it is unable to add it as a reference to a project)

**Comment by forki** [comment]
Mhm that sounds bad. Could you please try to use older paket version for now. I will investigate on Monday when I'm back from vacation.

**Comment by nickbabcock** [comment]
My limited investigation has led me to 731801d6 which has [EscapeDataString](https://msdn.microsoft.com/en-us/library/system.uri.escapedatastring(v=vs.110).aspx), which could be the problem.

**Comment by nickbabcock** [comment]
I can confirm that reverting to paket 1.23.0 fixed the issue. Enjoy your vacation :tropical_drink:

**Comment by forki** [comment]
Oh so you used a prerelease? Then thanks for testing this and catching this early

**Comment by nickbabcock** [comment]
Correct, I used prerelease1.24.0-alpha002, as I blindly copied the releasing instructions from the F# project scaffold website, which included bootstrapping the prereleased version.

**Comment by forki** [comment]
Yep. That was a very unfortunate bug in projectscaffold. I think we fixed
that already.
