### ISSUE TITLE
Update specifying version pins version

### ISSUE THREAD

**Issue by mrinaldi** [fsprojects/Paket#973]
This is a question rather than an issue.

While updating, when you specify the version, that version is pinned in paket.dependencies.
Is this correct? I couldn't find anything related to it in the docs.

I don't want to pin the version, I just want to update to that specific version and that's it.
I'm willing to send a PR either to fix this behavior or to introduce a parameter to the update command.

What do you think?

**Comment by forki** [comment]
that is actually a very good question. @agross what do you think?

**Comment by forki** [comment]
I think you are right. We should not add the version as a permanent requirement to the deps file. PRs welcome.

**Comment by agross** [comment]
Sorry guys, I had little time during the last days. Does this mean paket modified the dependency file? If so, I think we should revert that decision. The depfile is the user's responsibility. Only the lockfile should be modified by us. 



Alex
-- 
Alexander Groß
Tiny phone, tiny mail
