### ISSUE TITLE
Pack command doesn't escape filenames correctly (mark 2)

### ISSUE THREAD

**Issue by jamescrowley** [fsprojects/Paket#975]
While https://github.com/fsprojects/Paket/issues/959 resolved issues with spaces, it also unnecessarily encodes parenthesis, which again results in files being missed when installing a nupkg. Need to review the NuGet spec more closely here, as there may be differences between folders and files in how they should be encoded.

**Comment by forki** [comment]
Sigh. Could you please send a pull request? I already added a post replacement.

**Comment by forki** [comment]
I think the twitter response https://twitter.com/emgarten/status/631571367083675648 doesn't help ;-)
