### ISSUE TITLE
Need help resolving prerelease NuGet packages

### ISSUE THREAD

**Issue by carolynvs** [fsprojects/Paket#976]
I am having a very difficult time getting NuGet prerelease packages to resolve properly and would really appreciate some help. :smile:  

What I would like to do is install the latest available of a package, including prereleases. In the example below, I expected Paket to find [Microsoft.AspNet.Mvc 6.0.0-beta6](https://www.nuget.org/packages/Microsoft.AspNet.Mvc/6.0.0-beta6). In the future when v7.0 is released, then I would expect that to be resolved.

```
source https://nuget.org/api/v2
nuget Microsoft.AspNet.Mvc >= 6.0.0 prerelease
```

```bash
$ .paket/paket.exe install
Paket version 1.26.2.0
Resolving packages:
Paket failed with:
        Could not find compatible versions for top level dependency:
     "Microsoft.AspNet.Mvc >= 6.0.0 (from y:\src\temp\paket.dependencies)"
   Available versions:
     -
   Try to relax the dependency or allow prereleases.
```

When I use a pessimistic version range with beta explicitly set e.g. `~> 6.0.0-beta` it is able to resolve. Am I using the right syntax? Based on the examples, I had thought the former would work.

Thanks!

**Comment by forki** [comment]
This is a common error. And I will change the semantics soon so that people
don't run into this anymore.
The issue is that prerelease versions are smaller than 6.0 so you filter
these out.

To solve your issue use only prerelease without any version filter. Or use
something like >= 5 prerelease.

**Comment by carolynvs** [comment]
Thank you very much for the quick reply! I'm slapping my forehead for not realizing sooner what was going on. :blush:

**Comment by forki** [comment]
no as I said it was a common misunderstanding and it is now fixed so that people get what they expect.
