### ISSUE TITLE
Http sources download behaviour

### ISSUE THREAD

**Issue by inventti-pedro** [fsprojects/Paket#978]
Suppose that paket.dependencies has an entry:
```http http://189.45.195.210/mysql.7z ..\..\build\MySQL\mysql.7z```
Executing it shows the following output:
```Downloading 189.45.195.210/:/mysql.7z ..\..\build\MySQL\mysql.7z```
Where did the ```:``` came from?

**Comment by forki** [comment]
do you have a repro with a real url to test for me?

/cc @sergey-tihon

**Comment by inventti-pedro** [comment]
My bad. Using and old version from local repo, updated to the most recent version things just works fine.

**Comment by forki** [comment]
cool ;-)
