### ISSUE TITLE
Could not resolve package while converting from nuget

### ISSUE THREAD

**Issue by albertjan** [fsprojects/Paket#987]
Why couldn't it resolve this dependency? This is the 10th package or so removing the version from the dependecies file fixes it.

```sh
Could not resolve package System.Data.SQLite:
   - Dependencies file requested 1.0.96.0
   - Dependencies file requested 1.0.96.0
```

while running a nuget auto conversion. I haven't had this with any of my other nuget-> paket coversions.

**Comment by forki** [comment]
do you have paket.dependencies file for me to reproduce?

**Comment by forki** [comment]
https://www.nuget.org/packages/System.Data.SQLite <- doesn't list that version
