### ISSUE TITLE
Querying for NuGet packages using v3 feed doesn't include prereleases

### ISSUE THREAD

**Issue by carolynvs** [fsprojects/Paket#988]
I have a [beta release of openstack.net on MyGet](https://www.myget.org/gallery/openstacknetsdk) but Paket is unable to find it. I believe the problem is that when Paket queries for the available versions, it is not using the prerelease query string parameter. Is my paket.dependencies file incorrect or is this a bug?

**paket.dependencies**
```
source https://nuget.org/api/v2
source https://www.myget.org/F/openstacknetsdk/api/v2

nuget openstack.net !>= 1.5.0 prerelease
```
From Fiddler, I can see that Paket detects that a v3 feed is available and automatically uses that. However this is the query it sends to MyGet:

```
GET http://myget.org/F/openstacknetsdk/api/v3/autocomplete?id=openstack.net

{"@context":{"@vocab":"http://schema.nuget.org/schema#"},"totalHits":0,"data":[]}
```

According to the MyGet team, this is what Paket should be using to query:

```
GET http://myget.org/F/openstacknetsdk/api/v3/autocomplete?id=openstack.net&prerelease=true

{"@context":{"@vocab":"http://schema.nuget.org/schema#"},"totalHits":3,"data":["1.5.0.0-beta2","1.5.0-beta1","1.5.0-beta-1"]}
```

**Comment by forki** [comment]
should be fixed in 1.29.2

**Comment by carolynvs** [comment]
Thank you, working great now! I owe you at least 2 beers at this point, if you have a donation page let me know. Otherwise I'll just pay you back in arcane internet currency a.k.a tweets. :smile:

**Comment by forki** [comment]
Thx ;-) I really like your blog post. Maybe you can write a testimonial one
day. http://fsprojects.github.io/Paket/testimonials.html

Cheers, Steffen
