### ISSUE TITLE
Paket Feature Request - Remove Invalid References On An Install

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#993]
I wanted to run an idea past the Paket community. I'm not quite sure how a csproj got into this state, but I have invalid references in my csproj without the normal Paket conditional logic. Perhaps the reference was added by ReSharper by accident after it’s hinted at importing a DLL it found in the package folder. This is quite easy to accidentaly hit if you are alt-entering through imports/references. I was wondering if on an install, Paket could remove any references to the packages folder that do not have conditional statements round them?

```
   <Reference Include="Betgenius.InRunning.DataContracts">
      <HintPath>..\..\..\packages\Betgenius.InRunning.DataContracts\lib\net40\Betgenius.InRunning.DataContracts.dll</HintPath>
   </Reference>
   <Reference Include="Betgenius.Resulting.Messages, Version=1.0.70.9811, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\packages\Betgenius.Resulting.Messages\lib\net40\Betgenius.Resulting.Messages.dll</HintPath>
   </Reference>
```

**Comment by forki** [comment]
Maybe we can do this on --hard

**Comment by cjbhaines** [comment]
Sounds like a good option to me. I will be forever in your debt if you implement this :-) Do you accept beer deliveries?

**Comment by ilivewithian** [comment]
Is there any update on this? This bit me hard yesterday, I added a reference to a project using resharper, but that didn't bring web config redirects with it and my project fell in a heap at runtime. Being able to run `install --force` would have been really helpful.

**Comment by forki** [comment]
No there is no update here. This is a non-trivial feature since it has potential to screw up manual fixes.

**Comment by cjbhaines** [comment]
This is redundant with the new csproj format
